### ISSUE TITLE
[3.x] Datatable sort Date Column

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#1005]
Hi,

I have a Datatable with sorting enabled on `Date` type Column.
I see that if my `Date` format is  `d/m/Y`, then the sorting method doesn't sort as expected.

Maybe a custom sorting function will be a nice enhancement. I use [Day.js](https://github.com/iamkun/dayjs) when I have to work with dates.

**Comment by cagataycivici** [comment]
type is used for filtering, if your data type is actually dates, it should work. Please provide a sample project via code sandbox and we'll review.

**Comment by makurtu** [comment]
Hi @cagataycivici,

Yes, you are right, I used already formated strings in place of "raw data object". But I need formated date on my Datatable.
Please, see this Codesandbox:
https://codesandbox.io/s/icy-shape-4doto?fontsize=14&hidenavigation=1&theme=dark

You can see that, if I use `datejs` objects, sorting works as expected (so this issue can be closed), buy I need to display formated date, and then, I need to export it. If you click `Export` button, you can see that `time` col isn't formated as expected (It shows `date object` in place of `formated string`). This issue is the same of this: #798.

I solved the exporting problem with "pre-formating" date (in backend), but obviously, the sorting method is broken with this kind of implementation.
