### ISSUE TITLE
Dropdown -> 'Edit in CodeSandbox' -> ModuleNotFoundError

### ISSUE THREAD

**Issue by cybay** [primefaces/primevue#1006]
https://www.primefaces.org/primevue/showcase/#/dropdown

Push the button "Edit in CodeSandbox"

![prime-vue-issue-err-drop-dn-001](https://user-images.githubusercontent.com/17382294/108738919-26423b00-7545-11eb-922a-355bb3fcf3e4.png)

![prime-vue-issue-err-drop-dn-002](https://user-images.githubusercontent.com/17382294/108738961-2f330c80-7545-11eb-9b59-dd72f09a232f.png)

And one more thing!!!

When list of options is quite big, let's say 10 items - they don't fit in dropdown and are not visible when you scroll to them with keyboard arrow keys ((( With mouse it's ok.

**Comment by tugcekucukoglu** [comment]
Thanks for your feedback. This will be fixed next version.

Also you want to consider option slot for MultiSelect component.
