### ISSUE TITLE
Cannot import FilterMatchMode from primevue/api

### ISSUE THREAD

**Issue by ericshuanders** [primefaces/primevue#1007]
I'm trying to add filtering functionality to the DataTable component. As per the documentation, I've imported FilterMatchMode this way:

import {FilterMatchMode} from 'primevue/api'

I'm met with :

![Screen Shot 2021-02-22 at 4 33 41 PM](https://user-images.githubusercontent.com/53028022/108773056-d0ad6480-752b-11eb-937a-cec83312f7df.png)

Seems that 'api' isn't available in the primevue node_module. Running npm install --save primevue/api doesn't work either.

Any suggestions?

**Comment by cagataycivici** [comment]
What is your PrimeVue version?

**Comment by ericshuanders** [comment]
Version 3.2.4

**Comment by Lyho8** [comment]
> Version 3.2.4

You need version 3.3.0 :)

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with our codesandbox template forkso that we can work on it again. Thank you.
