### ISSUE TITLE
PrimeVue 3.3.0 crashes in codesandbox.io

### ISSUE THREAD

**Issue by theo333** [primefaces/primevue#1012]
I was working with some PrimeVue components in codesandbox.io.  Yesterday the sandbox worked and now it throws an error. I noticed that PrimeVue 3.3.0 was released today.

**What happens?**
I open up [Button Demo on PrimeFaces website](https://primefaces.org/primevue/showcase/#/button)  in [Codesandbox](https://codesandbox.io/s/iq1ng ).  The sandbox does not compile and throws an error:

![pv3 3 0-error-codesandbox io-2021 02 23-12_58_48](https://user-images.githubusercontent.com/11414429/108886526-1115ec80-75d7-11eb-932e-48c22a967e42.png)

**How did I fix it?**
In package.json, I downgraded the PrimeVue version
`"primevue": "latest"` => `"primevue": "3.2.4"`

Now it works just fine.

**Comment by aStanleyLiang** [comment]
I have similar issue after install the latest one.

```
import Column from 'primevue/column'
```

**Comment by tugcekucukoglu** [comment]
@theo333 [PrimeVue Button Codesandbox](https://codesandbox.io/s/iq1ng) seems to be working. We could not replicate it. Did you add 

`app.component("Button", Button);`

**Comment by tugcekucukoglu** [comment]
@aStanleyLiang did you add `app.component("Column", Column);`

**Comment by aStanleyLiang** [comment]
> @aStanleyLiang did you add `app.component("Column", Column);`

Appreciate to reply. Yes I did.

Finally I resolve this by removing node_modules and re-install all dependencies.
