### ISSUE TITLE
Feature Request: Add "tab-click" to Event from TabView

### ISSUE THREAD

**Issue by CurrentlyNoName** [primefaces/primevue#1015]
Hello,
currently there is a "tab-change'"-Event for TabViews, yet (as the name already says) it's only triggered when a tab has changed. Yet I do need and "tab-click"-Event which is triggered every time  a tab is clicked (it doesn't matter my case if a tab has chaned or not, I want to do something every time the last tab in component is clicked). 

This can be achived with simply adding these lines to the "onTabChange"-Funktion in TabView  and addind the emit to the emit-array.

```
this.$emit('tab-click', {
	originalEvent: event,
	index: i,
});
```

Is it possible to add this to PrimeVue by default?

**Comment by FabianTe** [comment]
Nice, thank you very much @cagataycivici ! 👍

**Comment by jagbirsaini95** [comment]
i just want to know that this tab-click also works for keyboard events or not
