### ISSUE TITLE
DataTable Column's header text does not align in v.3.3.0

### ISSUE THREAD

**Issue by ubau** [primefaces/primevue#1016]
DataTable Column's header text does not align in v.3.3.0
'center' and 'right' ignored, text always stays on the left side.

![image](https://user-images.githubusercontent.com/4728539/108984959-28b5a980-7699-11eb-95d7-4dd5db6d5577.png)

code examples

```html
  <Column
    field="amount"
    header="Amount"
    :style="{ width: '123px', textAlign: 'right' }"
    :sortable="true"
  >
```

```html
  <Column
    field="amount"
    header="Amount"
    headerStyle="width: 123px; text-align: right"
    bodyStyle="width: 123px; text-align: right"
    footerStyle="width: 123px; text-align: right"
    :sortable="true"
  >
```

This is regression from v.3.2.4 and before.

**Comment by ubau** [comment]
Hello,

Commited fix https://github.com/primefaces/primevue/commit/179d947b2673adf2bd3853c58a5b9989538a7064 doesn't resolve the issue.
By examples header text 'Amount' must be aligned to column's right side (with or without sorting arrows).
(same problem for header's centering also)

If to look into DOM Inspector we can see that column's body and footer aligned according to style:
```html
<td style="width: 123px; text-align: right;" class="" role="cell">500.00</td>
```

but it's not the case for header
```html
<th style="width: 123px; text-align: right;" class="" role="cell">
  <div class="p-column-header-content">
    <span class="p-column-title">Amount</span>
  </div>
</th>
```
because `.p-column-header-content` has following lines:
```
display: -webkit-box;
display: -ms-flexbox;
display: flex;
```
so every column header requires specific `justify-content` for proper horizontal alignment.

**Comment by shweinfeld** [comment]
I seem to be facing the same issue using v^.3.9.1
![image](https://user-images.githubusercontent.com/53020099/149158807-fe2ecd2e-3f86-4cdc-9246-6b11dd300d32.png)

currently my code reads:
`<Column field="qty" header="Quantity" style="text-align:right"></Column>`

but I've also tried using headerStyle with no success.

**Comment by bjorntj** [comment]
Seems to be the same problem using 3.11.0 also...

**Comment by rolfs42** [comment]
Much has changed I think and DataTable employs flexbox. Thus, at least in my setup, I can format the column via       :style="{'justify-content':'flex-end'}" which works for both, the body and the header cells.

**Comment by xbhrnnd** [comment]
I tried with `<Column (...) alignHeader={'center'} />` an it worked for me.

**Comment by sbscan** [comment]
@cagataycivici it's not fixed. I believe flex inheritance makes the trouble.
Changing DataTable style from flex to inline-flex solves the problem. Perhaps you should change other occurrences.
DataTable.vue -> Style -> .p-column-header-content {display: inline-flex}

**Comment by zortext** [comment]
@sbscan I don't think changing global styles is a good idea. It may lead to unexpected results when more complex headers with filters are used. Instead I add `align-xxx`  classes for columns with the following css.
```css
.align-right{
  text-align:right;
}
.align-center{
  text-align:center;
}
.p-datatable th[class*="align-"] .p-column-header-content {
  display: inline-flex ;
}
```

I think this is much more convenient.

**Comment by thebleucheese** [comment]
We had to use the above CSS hack and justify-content: center rather than being able to apply a headerClass. 

That got the content to center but feels a bit hacky.

**Comment by fhprietor** [comment]
I using 3.15.0. Don't align

**Comment by wanglin86769** [comment]
I have the same problem with 3.15.0, is there any workaround to align center for table column header?

**Comment by ManuelTS** [comment]
> I have the same problem with 3.15.0, is there any workaround to align center for table column header?

Same here

**Comment by lao-tseu-is-alive** [comment]
same for me

**Comment by rubjo** [comment]
![SCR-20220825-cw1](https://user-images.githubusercontent.com/42270947/186601336-083d84eb-6648-4358-8faf-bfd82c658cd2.png)

**Comment by may820806** [comment]
> ![SCR-20220825-cw1](https://user-images.githubusercontent.com/42270947/186601336-083d84eb-6648-4358-8faf-bfd82c658cd2.png)

life saver

**Comment by Slimelvone** [comment]
![image](https://github.com/primefaces/primevue/assets/48656891/e05efcee-6494-42f2-8bac-62bb23984fdb)
----
Add headerClass="column-text-right"

    <Column
      field="totalValue"
      header="XXX"
      sortable
      :showFilterOperator="false"
      :showFilterMatchModes="false"
      :showAddButton="false"
      filterMatchMode="contains"
      headerClass="column-text-right"
    >
      <template #body="{ data }">
        <div class="text-right">{{ $helper.toCurrency(data.totalValue) }}</div>
      </template>
    </Column>

---

    <style lang="scss">
      .column-text-right {
        .p-column-header-content{
          text-align: right; // or center
          display: block !important;
        }
      }
    </style>

**Comment by mr-feek** [comment]
`:pt="{ headerContent: 'justify-content-end' }"` on the column component worked well for right aligning the header for me

**Comment by duzijie** [comment]
> I have the same problem with 3.15.0, is there any workaround to align center for table column header?

        <Column field="code">
            <template #header>
                <span class="flex-1 text-center">Code</span>
            </template>
        </Column>

**Comment by Robertofs1** [comment]
> > I have the same problem with 3.15.0, is there any workaround to align center for table column header?
> 
> ```
>     <Column field="code">
>         <template #header>
>             <span class="flex-1 text-center">Code</span>
>         </template>
>     </Column>
> ```
worked for me!! thanks

**Comment by BenJackGill** [comment]
> > I have the same problem with 3.15.0, is there any workaround to align center for table column header?
> 
> ```
>     <Column field="code">
>         <template #header>
>             <span class="flex-1 text-center">Code</span>
>         </template>
>     </Column>
> ```

This worked for me, but based on the obvious fragility of these hacks it really should be added as a built-in option.

**Comment by Drumstix42** [comment]
> `:pt="{ headerContent: 'justify-content-end' }"` on the column component worked well for right aligning the header for me

```
:pt="{ columnHeaderContent: 'justify-content-end' }"
```

Seems to do the trick in v4.

**Comment by diadras** [comment]
I added the following to my global CSS styling which aligns the text of both the table headers and column row contents to the right. This way this is fixed project wide and I don't have to write the theme pass-through part for each column I want to pull the the right. A simple `text-right` class now does what I want it to do.

```css
  th.text-right > .p-datatable-column-header-content {
    @apply justify-end;
  }
```
> Note: I use Tailwind V4, so replace `justify-end` with what sets the CSS rule `justify-content: flex-end` in your stack respectively

> Note2: I've always used `text-right` in my table headers and body cells, so using `<Column class="text-right"/>` is natural to me. 
If you were to use my code above a more "logical" implementation would be to use `th.justify-end` instead of `th.text-right` since the table headers are flex containers and using `text-right` is block container syntax.

**Comment by Azeirah** [comment]
I have the following solution in primevue `v4.3.7`

```ts
import { DataTableDesignTokens, DataTableTokenSections } from '@primeuix/themes/types/datatable';

/* ... */

export const css: DataTableTokenSections.CSS = /*css*/ `
thead th.align-right .p-datatable-column-title {
    flex: 1;
    text-align: right;
}

tbody td.align-right {
    text-align: right;
}

thead th.align-center .p-datatable-column-title {
    flex: 1;
    text-align: center;
}

tbody td.align-center {
    text-align: center;
}
`;

export default {
    css,
} satisfies DataTableDesignTokens;
```

This allows you to to set a utility class on the Column you want to align in a particular manner as such

```html
<Column field="openContracts" header="Open Contracts" class="align-right"></Column>
```
