### ISSUE TITLE
Resize support for Scrollable Tables

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#1018]
Column resizing does not work  well with the new (v3.3.0) DataTable scrolling changes.

To recreate, modify the following DataTables in the demo site source (/#/datatable/scroll) as follows: Add the attributes:

```
:resizableColumns="true"
columnResizeMode="expand"

```

Then drag a column separator.

Example 1: Vertical
Result: Column resizes by a fraction of the dragged delta. Column widths of other columns are also affected.

Example 3: Horizontal and Vertical with Footer
Result: Column header is resized correctly. Column data is not resized at all. If single selection is also enabled, selecting a row will cause the column header width to revert.

PrimeVue 3.3.0
Vue: 3.0.5

**Comment by cagataycivici** [comment]
The new scrolling does not support resize + scrollable columns yet. Will be worked on.
