### ISSUE TITLE
DataTable error while using stateStorage with date filter

### ISSUE THREAD

**Issue by ahmedkandel** [primefaces/primevue#1020]
First, thank you for the great library.

I have a DataTable column with `dataType="date"` and using default date filter modes. When enabling `stateStorage` on the DataTable I got the following error:
```
Uncaught (in promise) TypeError: filter.getTime is not a function
```

After some digging, I have found that in "src > components > DataTable.vue" the `saveState()` is using `JSON.stringify(state)` which will convert date objects to ISO8601 string, Then the `restoreState()` is using `JSON.parse(stateString)` which will keep the date as string and causes error when calling date methods e.g. `getTime()` on it to filter.

I made a PR to fix this and will submit it soon.

**Comment by cagataycivici** [comment]
Fixed with an alternate regex, thanks.

**Comment by ahmedkandel** [comment]
@cagataycivici I think the alternate regex is not accurate for two cases:

1. It will pass values like '9999-99-99T99:99:99.999Z' but when converting it to date will give an error.
2. It doesn't support  AD/BC years which is a part of [ISO 8601](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) e.g. ancient date “before Christ”.

So i think mine was better. Thanks.
