### ISSUE TITLE
[BUG]  PrimeVue 3.3.0: Dropdown's select item logic is broken

### ISSUE THREAD

**Issue by cybay** [primefaces/primevue#1026]
https://www.primefaces.org/primevue/showcase/#/dropdown

How to replicate the issue.
1. create Dropdown with items more than can be fit in overlay without need to scroll, for example 10 items.
2.  say. select first item from drop-overlay. It works.
3.  try to chose the last item. It will require to scroll the options. When you see the last item and click on it with mouse - it won't be selected as it expected. It will be selected only with the second click. 

Every time when you have some selected item and trying to select another one AND it requires scrolling - the new selection won't happen at first shot. Only with second one.

It's obviously that's a Bug.

Apparently there is some problem with scrolling.
In case there are amount of items that don't fit in overlay AND we selected some item beyond overlay rows capacity AND we open the options - it's not scrolling to make selected item visible. It's surely a Bug too.

**Comment by cagataycivici** [comment]
Are you using a grouped one or regular? I see this in group only.

**Comment by cagataycivici** [comment]
Replicated
