### ISSUE TITLE
Migrate appendTo use Teleport

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#1028]
Vue3 has a teleport component so we can remove our own dom manipulation to use Teleport.

**Comment by afonic** [comment]
Autocomplete dropdown used to spawn inside the p-autocomplete <span>. After commit https://github.com/primefaces/primevue/commit/ec15e9471813ed5fd674f4a7d6f5601d07a45817 it now appends to the body by default, which in my case creates a couple of issues styling-wise. 

How can I go back to the previous behavior? I tried using appendTo but it needs a selector outside the Vue component.

Maybe a prop can be added to disable the Teleport feature?
