### ISSUE TITLE
Dropdown optionDisabled is not working

### ISSUE THREAD

**Issue by std810901** [primefaces/primevue#1037]
When I set the "optionDisabled" of the Dropdown to be disabled, although the CSS style is disabled, the option can still be selected.
It just set the class "p-disabled",didn't prevent users from selecting.

**Comment by cagataycivici** [comment]
I'm unable to replicate, please fork the link below and provide a case that reproduces the issue.

https://codesandbox.io/s/ittu5

**Comment by std810901** [comment]
I use vue 2 & primevue ^2.0.0 to develop,but it is ok in vue 3 
![image](https://user-images.githubusercontent.com/25360897/109760682-181daa00-7c2a-11eb-8d06-7eb3744100f9.png)
![image](https://user-images.githubusercontent.com/25360897/109760758-35eb0f00-7c2a-11eb-9c49-5d2066c69bae.png)

**Comment by cagataycivici** [comment]
Ok, we'll check for vue 2 branch then.

**Comment by codenomnom** [comment]
@cagataycivici @tugcekucukoglu I don't think this is a proper fix. Please check https://github.com/primefaces/primevue/issues/1192#issuecomment-824626977
