### ISSUE TITLE
Filter Popup window closes when clicking / choosing option in table filter menu

### ISSUE THREAD

**Issue by TuguldurJ** [primefaces/primevue#1049]
If the user chooses the filter option in the data table, the filter pop-up immediately closes and the need to open pop-up filter for a 2nd time to click the Apply button. This is so annoying in the UX view. Check this:

![Table glitch](https://user-images.githubusercontent.com/1275537/109937001-79687a80-7d09-11eb-94d4-026378cf51a7.gif)

**Comment by cagataycivici** [comment]
An annoying regression that we missed during the recent overlay enhancements, fixed now via 1048 thanks.
