### ISSUE TITLE
Feature Request: Show active tab in TabMenu with different Route-Defintion

### ISSUE THREAD

**Issue by CurrentlyNoName** [primefaces/primevue#1051]
Hello,

using TabMenu it's possible to define one Tab-Item like this:

`{label: 'Home', icon: 'pi pi-fw pi-home', to: '/tabmenu'},`

When using it that way, the active tab-item is shown correctly.

Yet, we  use route with "to" like this:

`to: { name: 'LocatorSubView'}`

The route will be opened, but not be shown as active, because the "activeRoute" in TabMenu is defined with

```
activeRoute() {
    return this.$route.path;
}

```

and the path is not what's written in our to-property, which is why the comparison fails:

`return this.activeRoute === item.to;`

Is it possible for route-definitions like ours to also be shown as activated?

**Comment by CurrentlyNoName** [comment]
I checked the the TabMenu-Component and was able to achieve with the following changes:

1. Change the computed "activeRoute" to:

```
activeRoute() {
   return this.$route;
},
```

2. Change the "isActive"-Function to:

```
isActive(item) {
	if (this.activeRoute.path === item.to) {
		return true;
	}

	if (this.activeRoute.name === item.to.name) {
		return true;
	}

	return false;
},
```

I don't know if there are other combinations for valid-route-definitions, though.

**Comment by m-thorsen** [comment]
I find myself often using a Tab menu to switch between "dynamic versions" of the same page where it would be quite messy to add new routes for each possibility - so I have a request related to this enhancement: 
* Passing an object with query/hash as "to" (similar to `RouterLink`)
* Option for including query and/or hash in the active state check

**Comment by cagataycivici** [comment]
Covered via;

https://github.com/primefaces/primevue/issues/594
