### ISSUE TITLE
How can i use id instead of a key or generate key automictically ? 

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#1054]
I'm using vue js 3 and i'm using tree component"
```
https://primefaces.org/primevue/showcase/#/tree
```
When i click on the node it expands all the tree by default.
I see that i have to use keys but i don't want to map over 8 thousand elements  and crazy logic like
                                                                                                                                                               1
                                                                                                                                                                1-0
is there a way around not expands all the tree by default ? and instead of a key to use somehow an id or something else ?

**Comment by west-farmer** [comment]
Use computed property  wrapping the business model with a computed key maybe help.

**Comment by vadimt2** [comment]
Maybe it's a good idea, but what should i use instead of a key ? an id of my item?
