### ISSUE TITLE
Drag-n-drop for TabView to reorder tabs

### ISSUE THREAD

**Issue by alexterenya** [primefaces/primevue#1057]
Would be good to have a possibility to re-order tabs using drag-n-drop. Thanks in advance.

**Comment by cagataycivici** [comment]
There does not seem to be a demand for this feature although I think it is cool. Closing for now and we'll reopen when there is more demand. Thank you for your understanding.

**Comment by rogerhoen** [comment]
Hi,

We would like this enhancement too. Users are used to this functionality because of browser tabs, Excel tabs etc.. 

Regards,
Roger

**Comment by mhmghanem1** [comment]
we need this too. Any chance to be added?

**Comment by mortenkos** [comment]
This would be a very good feature and I know a few other people who would need it

**Comment by codearachnid** [comment]
++1 for this as a featuer

**Comment by LouisVA** [comment]
+1

**Comment by FabianNet** [comment]
+1

**Comment by jpoulain-tbs** [comment]
+1

**Comment by Tomdatbenik** [comment]
+1

**Comment by IsraelAfangideh** [comment]
I need this as a feature as I'm currently needing to implement a custom solution for this, and it is challenging

**Comment by tbarkley** [comment]
+1

**Comment by crisilva95** [comment]
@cagataycivici  Same here!!! This is definitely a high-interest feature!

**Comment by matguerin** [comment]
+1

**Comment by trm-bmo** [comment]
+1

**Comment by tmi-gonzalezroda** [comment]
+1

**Comment by tmi-victor** [comment]
+1

**Comment by ferencizsepi** [comment]
+1

**Comment by thomasklein1982** [comment]
+1

**Comment by thaneuk** [comment]
+1

**Comment by Hudayfa** [comment]
+1

**Comment by freaki2010** [comment]
+1

**Comment by adrianosotos** [comment]
+1

**Comment by julienbernat** [comment]
+1

**Comment by thaneuk** [comment]
I've successfully implemented drag-and-drop tabs using the Angular CDK drag-and-drop.

```
  <p-tablist
    cdkDropList
    cdkDropListOrientation="horizontal"
    (cdkDropListDropped)="tabDropped($event)">
    @for (tab of tabs(); track tab.id) {
    <p-tab cdkDrag>
    }
  </p-tablist>
```


```
  protected tabDropped(event: CdkDragDrop<ITab[]>) {
    const tabs = [...this.tabs()];
    moveItemInArray(tabs, event.previousIndex, event.currentIndex);
    this.tabs().set(tabs);
  }
```
