### ISSUE TITLE
Document Update Suggestion

### ISSUE THREAD

**Issue by BenHayat** [primefaces/primevue#1058]
Hello Team;

Could you please update the "Download" in Setup section (https://www.primefaces.org/primevue/showcase/#/setup)
As new users won't get confused with version #.

**From: npm install primevue@^3.2.1 --save
To: npm install primevue --save**

**Comment by fobass** [comment]
Hi Ben,
After install primeVue i got error 

![image](https://user-images.githubusercontent.com/20865522/110282072-ce153980-8018-11eb-83f2-c80b4d8ea5fc.png)

I can't figure out what is the problem, could you suggest pls

**Comment by BenHayat** [comment]
In Vue 3, this is how I create the "app" and works

`createApp(App)
  .use(store)
  .use(router)
  .use(PrimeVue, { ripple: true })
  .use(ToastService)
  .component('InputText', InputText)
  .component('Button', Button)
  .component('Toast', Toast)
  .mount('#app')`

**Comment by fobass** [comment]
thank you Ben, i fix that problem was with my vue version
