### ISSUE TITLE
Add filters to lazy loading demo

### ISSUE THREAD

**Issue by RobertoMaurizzi** [primefaces/primevue#1061]
The example at https://www.primefaces.org/primevue/showcase/#/datatable/lazy doesn't use the new DataTable filtering machinery and as a consequence its filters disappeared from the example.
Additionally, it's not really obvious from the docs in DataTable Documentation or FilterService how I should go and update the filters to work with remote data loading.

I'm also wondering if I missed some advice (not necessarily Prime-related, I'm still quite new at modern JS tooling) about how to write semantic versioning in `package.json`, because a deploy picked up version 3.3.4 from ^3.2.4 and broke filtering. Is the recommended approach to avoid using `^major`? I'd like to avoid pulling in new features that break compatibility.

**Comment by cagataycivici** [comment]
@yigitfindikli @tugcekucukoglu Please take over.

**Comment by RobertoMaurizzi** [comment]
@yigitfindikli I was going again through the example to finally fix my code but I noticed you fixed the code running on the page but not the <pre> code example at https://github.com/primefaces/primevue/blob/3740f7134347ba02aa04d64a0d12876e0906056d/src/views/datatable/DataTableLazyDemo.vue#L78-L82

Thanks! Waiting for 3.3.6 to hit npm :-)
