### ISSUE TITLE
Sidebar Mask not removed from DOM [3.3.5]

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#1062]
The Sidebars [ontransitionend](https://github.com/primefaces/primevue/blob/master/src/components/sidebar/Sidebar.vue#L109) callback isn't fired so the `div.p-sidebar-mask` will always remain in the DOM. Could you please fix that?

You can see it [here](https://codesandbox.io/s/distracted-darwin-m45jx?file=/src/App.vue) when you open and close the modal and inspect the App

**Comment by cagataycivici** [comment]
You seem to be missing styling that is causing the issue; Try adding;

import "primevue/resources/themes/saga-blue/theme.css";
import "primevue/resources/primevue.css";

Otherwise there won't be a transition.
