### ISSUE TITLE
no validation rules on forms

### ISSUE THREAD

**Issue by alisaayed** [primefaces/primevue#1064]
:')

**Comment by dheimoz** [comment]
@alisaayed Hello, is this a feature request?

**Comment by mrsai** [comment]
Its UI is very beautiful, but it does not have a "Form" component, so its form-verification is complicated and needs to be developed by yourself. My suggestion is to implement a "Form" component. Refer to "Vuetify", I think it is very easy to use and easy to worry  less about.
