### ISSUE TITLE
Dropdown components change event

### ISSUE THREAD

**Issue by code-black-wizard** [primefaces/primevue#1065]
Hi! How i can add event onChange on dropdown components? It's not working:

`<Dropdown @change="myCustomEvent" v-model="selectedCountry" :options="countries" optionLabel="name" modelValue="name" optionValue="name" placeholder="Select a Country" />`

**Comment by cagataycivici** [comment]
This works for me;

```js
myCustomEvent(event) {
            console.log(event.value);
        }
```
