### ISSUE TITLE
OverlayPanel -- Option to open by default

### ISSUE THREAD

**Issue by mike347** [primefaces/primevue#1068]
I'm using Overlay Panel to hide a list of filters for a data table (with a load data button). I'd like to have it show by default but haven't gotten it to work reliably. Can we get an option to do this?

I've tried grabbing a reference to the target area using $refs, and firing on nextTick() in Mounted() to no avail.

```
mounted() {
     this.showOL({currentTarget: this.$refs.buttonFilters.$el})
}
 methods: {
      showOL(event) {
                nextTick(() => this.$refs.op.show(event))
       },
}

```

**Comment by cagataycivici** [comment]
This worked for me;

```html
<Button ref="btn" @click="toggle" />

<OverlayPanel ref="op" >
...
</OverlayPanel>
```

```js
 mounted() {
        this.$refs.op.show({currentTarget: this.$refs.btn.$el});
    },
``

**Comment by mike347** [comment]
This doesn't reliably work for me. I thought maybe because <Button> is inside a <Toolbar>, but moving it out of the <Toolbar> doesn't work either.  I wonder if it's a timing issue, as this is a rather 'robust' component?

**Comment by dheimoz** [comment]
hello @mike347 are you using Options or Composition API?

**Comment by mike347** [comment]
Actually using a mixture (due to needing to use setters/getters with a model binding for vuex). I have a setup() , as well as a mounted().

**Comment by dheimoz** [comment]
personally, I do not recommend mix approaches. As you know, this is not accessible in Composition API. Have you taken a look into OnMounted?
https://v3.vuejs.org/api/composition-api.html#lifecycle-hooks

Your issue might be related to a timing or access detail.
