### ISSUE TITLE
Password Component need updates

### ISSUE THREAD

**Issue by Daveedz99** [primefaces/primevue#1069]
Hey prime vue team !!
i'm facing problems wiith the component ''Password'' expecially with his property : 'toggleMask' it's very buggie and it wont work on every  browsers so please surely you could help me. 
I wait for a response and i hope for a future update! 
thanks for your time,
Davide

**Comment by dheimoz** [comment]
Hello @Daveedz99 what are the issues you are experiencing with the property? Can you share a screen capture or a repo?

Remember that the more details provided is the best way to help.

Thanks.

**Comment by Daveedz99** [comment]
Hello im really sorry, but yesterday  i have updated prime vue version and now i fixed it so maybe it was for the version i had ( older!)  
thanks for your response, now im facing a problem with datatable filters ! but im gonna create a post with the appropriate img for it!
really thanks!
