### ISSUE TITLE
Menubar doesn't open the sub-menus when item is not a Proxy object

### ISSUE THREAD

**Issue by alexandreDavid** [primefaces/primevue#1070]
In this line:
https://github.com/primefaces/primevue/blob/b917e116729d0f2d44fa452d6594f0c1cee67df0/src/components/menubar/MenubarSub.vue#L242
When we call the component Menubar with an array as model, the sub-menu doesn't open. It's due to the fact we compare a proxy element with an object.

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1 please create a new ticket with our codesandbox template fork so that we can work on it again. Thank you.

**Comment by williamweckl** [comment]
Same issue here using PrimeVue 3.6.0.

**Comment by williamweckl** [comment]
@alexandreDavid was you able to do any workaround?

**Comment by williamweckl** [comment]
I was able to work declaring my array as a reactive object.

```
import { reactive } from 'vue'

let items = reactive([...])
```

**Comment by dheimoz** [comment]
thaks for sharing @williamweckl

**Comment by agm1984** [comment]
Aha, this helped me solve my problem. My sub-menu was not opening in Vue 3, but the menu items were just passed in tersely:

I'll just show my entire component. This wasn't working:
``` vue
<script setup>
import { ref } from 'vue';
import ContextMenu from 'primevue/contextmenu';

defineProps({
    employee: {
        type: Object,
        required: true,
    },
});

const menu = ref();

const toggleMenu = (event) => {
    menu.value.toggle(event);
};
</script>

<template>
    <button @click="toggleMenu">
        <i class="icon-more-h text-primary"></i>
    </button>

    <ContextMenu
        ref="menu"
        :model="[
            {
                label: 'View details',
                icon: 'icon-info',
                to: { name: 'dashboard.index' },
            },
            {
                label: 'Reset password',
                icon: 'icon-logout',
                items: [
                    {
                        label: 'Send SMS',
                    },
                    {
                        label: 'Send Email',
                    },
                ],
            }
        ]"
        popup
    />
</template>
```

But then I changed it to this, and it now works:

``` vue
<script setup>
import { ref, reactive } from 'vue';
import ContextMenu from 'primevue/contextmenu';

defineProps({
    employee: {
        type: Object,
        required: true,
    },
});

const menu = ref();

const menuItems = reactive([
    {
        label: 'View details',
        icon: 'icon-info',
        to: { name: 'dashboard.index' },
    },
    {
        label: 'Reset password',
        icon: 'icon-logout',
        items: [
            {
                label: 'Send SMS',
            },
            {
                label: 'Send Email',
            },
        ],
    }
]);

const toggleMenu = (event) => {
    menu.value.toggle(event);
};
</script>

<template>
    <button @click="toggleMenu">
        <i class="icon-more-h text-primary"></i>
    </button>

    <ContextMenu
        ref="menu"
        :model="menuItems"
        popup
    />
</template>
```

I'm guessing the problem is related to what is described by @[williamweckl](https://github.com/williamweckl). When menu items is a proxy, it works.

I'll just drop a few keywords in here to help future searchers:
- primevue context menu not opening
- sub menu not working
- sub-items, subitems, submenu

**Comment by mytlogos** [comment]
Can this documented explicitly on the [MenuBar ](https://primefaces.org/primevue/menubar) Page?
Currently it does not explicitly mention the required reactivity of the Menu Model, at least on the MenuBar Page.
The examples use a reactive model though, so it is kinda implicit.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
