### ISSUE TITLE
Divider doesn't show the line

### ISSUE THREAD

**Issue by irossett** [primefaces/primevue#1072]
I've tried to use this component, but the line doesn't appear (solid, dotted...).
Then I've downloaded sigma-vue-master template to check if that would work and I found the same problem in UI Kit -> Panel

I'm using Chromium for Manjaro.

Thanks

**Comment by alexterenya** [comment]
For me line doesn't appear as well. I'm using latest chrome.

**Comment by tugcekucukoglu** [comment]
Please import theme css firstly, after that import components. Like this

`
import "primevue/resources/themes/saga-blue/theme.css";
import "primevue/resources/primevue.min.css";

import Divider from 'primevue/divider';
`
