### ISSUE TITLE
Vue js 3 - select and show/focus on one node in the tree

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#1074]
Hi, so i'm using vue js 3 and primevue 3.3.6
and i would like to find out if there is an option to call a method from anywhere from the app
and select & show & focus node tree by key.
```
$refs.Tree.selectionKeys["93698"] = true;
```
This is selecting the tree node with anther nodes but not focusing.
I need to deselect all nodes 
then focus the node that i called from the method and show the only one node by key and focus
how can i do it?

**Comment by avenmore** [comment]
You can clear the previous selection first

```
$refs.Tree.selectionKeys = {};
$refs.Tree.selectionKeys["93698"] = true;

```

or replace the selection

`$refs.Tree.selectionKeys = { "93698" = true }
`
but I'm not sure if this will show the node if it is under a collapsed parent or scroll it into view.

**Comment by vadimt2** [comment]
It doesn't show the node if it's collapsed, and it doesn't scroll into it :(
i think i will use vanilla JavaScript if there is no primevue solution

**Comment by vadimt2** [comment]
```
$refs.Tree.selectionKeys = {};
```
The line above is not working
```
   catch (err) {
        handleError(err, instance, type);
    }
    ret
```

**Comment by cagataycivici** [comment]
You also need to update the expanded keys so Tree an expand to the selected node. Simply get all the parents and add them to expanded keys, this way you can programmatically expand and select a node.
