### ISSUE TITLE
Row double click for Table

### ISSUE THREAD

**Issue by nofxman** [primefaces/primevue#1075]
hi
dataTable is not support row-dblckick

Most other frameworks support it.
Request a feature addition

thankyou

**Comment by avenmore** [comment]
Seconded. I'm currently using `@dblclick.prevent="myTableDblClick"` and checking the selected row, but it would be nice to have inbuilt support with the target context.

**Comment by sirgale** [comment]
v-model:selection="selectedTicket" selectionMode="single" 
    @dblclick.prevent="editTicket(selectedTicket)"

**Comment by cagataycivici** [comment]
Will do this week.
