### ISSUE TITLE
Scrollpanel - Cannot read property classList

### ISSUE THREAD

**Issue by panwauu** [primefaces/primevue#1077]
Hi,

When I change the routes I sometimes get the error:
Uncaught TypeError: Cannot read property 'classList' of null
    at Function.addClass (utils.esm.js?dd76:132)
    at eval (scrollpanel.esm.js?ae1f:70)

Has somebody already encountered this problem and maybe found a solution?
I only found a similar Issue for Primereact (https://github.com/primefaces/primereact/issues/726)

Thanks

**Comment by cagataycivici** [comment]
Will be reviewed, thank you.
