### ISSUE TITLE
allow to set dir in Calendar  p-timepicker

### ISSUE THREAD

**Issue by tomer-yechiel** [primefaces/primevue#1080]
hi,
i am using <Calendar />
i set <html dir="rtl"> in my app but now it also effect the time picker which is not what i want, i want to keep the time picker ltr
as you can see in the img the minuts are on the left
![image](https://user-images.githubusercontent.com/32360493/111036404-b3333280-8427-11eb-8f57-56eb4958d9d4.png)

workaround:
```
<body dir="rtl">
...
<div class="fix-rtl" dir="ltr"></div>
</body>
```

and use the prop appendTo=".fix-rtl"

**Comment by cagataycivici** [comment]
.p-timepicker is flex so you can do this with flex-direction as well.
