### ISSUE TITLE
Vue3: Style lost on Dropdown & Multiselect components

### ISSUE THREAD

**Issue by maherma-adg** [primefaces/primevue#1083]
With the use of Teleport in Dropdown and MultiSelect components, any personalization based in scope is lost because panel is translated to body root, outside the scoped component.

Solution proposed is to add a "panelClass" property in the same way as Calendar component. 

a PR can be provided if this solutions is accepted

Regards,
Manuel

**Comment by maherma-adg** [comment]
Found this (https://github.com/primefaces/primevue/issues/1028#issuecomment-796918701) that look the same problem

**Comment by afonic** [comment]
I think adding panelClass like @maherma-adg suggested or adding a prop to disable it would solve this.

Besides, losing stying sometimes a Dropdown can be inside a dynamic component and closing that component flashes the dropdown in the top left corner for a few ms.

**Comment by LadislavBohm** [comment]
This is also issue for all dialogs now.

**Comment by cagataycivici** [comment]
I've added panel class where necessary, dialogs have class already.
