### ISSUE TITLE
DataTable global filter is reset when applying other filters

### ISSUE THREAD

**Issue by ahmedkandel** [primefaces/primevue#1087]
When using a global filter like `<InputText v-model="filters1['global'].value" placeholder="Keyword Search" />` toghether with column filters, Each time you apply a filter the global filter value gets reset.

To reproduce the issue visit the [demo](https://primefaces.org/primevue/showcase/#/datatable/filter), Type in some search value it will filter as expected but then if you select any column filter and click Apply the global filter gets reset.

The reason is that the DataTable component is using a filter object `d_filters` which is a clone of the filters provided by the parent component as a prop. Then the Datatable component watches any changes in the provided filter prop to reclone it. The issue is that changing any nested object property will not trigger the watcher unless the watch is deep.

Will create e PR to fix.

**Comment by ahmedkandel** [comment]
@cagataycivici any updates regarding this issue? thanks.

**Comment by mertsincan** [comment]
Hi @ahmedkandel,

You're right! Thanks a lot for your contribution!

Best Regards,
