### ISSUE TITLE
Change the icon element type in buttons

### ISSUE THREAD

**Issue by alexandreDavid** [primefaces/primevue#1089]
Hi, I'm using a button with a custom icon.
Unfortunatelly, I'm not able to use it because I accept only element <i>.
As improvement, it might be good to have a prop defining the icon element on the button: 
```html
<Button icon="pi pi-check" icon-tag="i" class="p-button-rounded p-button-text" />
```

**Comment by cagataycivici** [comment]
We'll introduce custom icon support e.g. svgs soon to cover this.
