### ISSUE TITLE
Tooltip continues to show after selecting item from Autocomplete

### ISSUE THREAD

**Issue by mallorygiles** [primefaces/primevue#1091]
Versions: 2.4.0 and 2.4.1-SNAPSHOT

Steps to reproduce:
Add a v-tooltip to the basic AutoComplete component in the AutoCompleteDemo.vue file.
Select an item and then mouse out of (or change focus from) the AutoComplete field

Expected: Tooltip goes away

Actual: Tooltip still showing
![image](https://user-images.githubusercontent.com/12798815/111199595-332bda80-8597-11eb-9e17-7ffd5decc9f1.png)

**Comment by tugcekucukoglu** [comment]
We could not replicate it. Could you please share your code or codesandbox example?

**Comment by mallorygiles** [comment]
[This is the sandbox that reproduces the issue](https://codesandbox.io/s/primevue-autocomplet-tooltip-qzxh1)

As I was creating this sandbox, I noticed the issue didn't happen until I imported 'primevue/resources/primevue.min.css' into the main.js file.

**Comment by tugcekucukoglu** [comment]
Yes, you need to import `primevue.min.css` and a theme css.

**Comment by mallorygiles** [comment]
I think you may have misunderstood. When importing the primevue.min.css, this issue DOES occur. 
Before I added the import, the issue wasn't happening, but of course nothing looked like it should without the primevue.min.css.
See the example in the codesandbox [example](https://codesandbox.io/s/primevue-autocomplet-tooltip-qzxh1).

**Comment by mallorygiles** [comment]
Will this issue be reopened as this bug was reproduced in [codesandbox ](https://codesandbox.io/s/primevue-autocomplet-tooltip-qzxh1)in Edge and Chrome Browsers for Primevue 2.4.0?
