### ISSUE TITLE
Feature Request/Suggestion: Hybrid development

### ISSUE THREAD

**Issue by BenHayat** [primefaces/primevue#1097]
Hello team;

I'd like to request/suggest to have some features built into PrimeVue to easily allow us to build Hybrid apps using Cordova for iOS and Android. Basically, to automate the steps of "Build" process to get ready for actual creating the Android and iOS app.

Quasar has some nice helps to speed up this repetitive process.
https://quasar.dev/quasar-cli/developing-cordova-apps/introduction

Hope this helps!

**Comment by cagataycivici** [comment]
Thank you but no plans right now.
