### ISSUE TITLE
[Vue 3] Dropdown grouping not available

### ISSUE THREAD

**Issue by valh1996** [primefaces/primevue#1100]
Hi,

The documentation does not seem to be up to date with the code. Indeed, in the documentation it is specified on the Vue3 documentation that we can do many things including Grouping on the Dropdown component. However, when inspecting the component interface... we find that the following options do not exist : `optionGroupLabel` and `optionGroupChildren`

Do you know when this will be available? It is very blocking for my project.

I would like to take this opportunity to thank you very much for your work!

**Comment by cagataycivici** [comment]
What is your PrimeVue version? It is up and running at live demo.

**Comment by valh1996** [comment]
@cagataycivici Ah, maybe that's the problem, I'm using version 3.1.1.
Can upgrading to the latest version break anything in your opinion?
