### ISSUE TITLE
DataTable with Filters (weird errors)

### ISSUE THREAD

**Issue by shaan1974** [primefaces/primevue#1102]
Hello,

![image](https://user-images.githubusercontent.com/3158745/111902838-9c03ce80-8a3f-11eb-8161-401f4988c438.png)

In the first example of DataTable with filter if we select "name" and we add 2 filters, when we click on "Apply" sometimes  javascript errors appear but not all the time ( really weird )

![image](https://user-images.githubusercontent.com/3158745/111902846-a625cd00-8a3f-11eb-8230-767b862d6eb4.png)

**Comment by slumtrimpet** [comment]
For what it's worth, I THINK this is the same issue as:
https://github.com/primefaces/primevue/issues/1076

**Comment by tugcekucukoglu** [comment]
Duplicate the [#1076 ](https://github.com/primefaces/primevue/issues/1076)
