### ISSUE TITLE
Multiselect showing null instead of value

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#1104]
Primevue v. 2.4.x

The multiselect showing null if the value is not present in the list of options.
![image](https://user-images.githubusercontent.com/13495631/111980531-535f1a80-8afe-11eb-8401-a07d59f29681.png)

```
    <MultiSelectView
      v-model="selectedItems"
      :options="items"
      data-key="id"
      option-label="name"
      :validation="{ required: true }"
    />

export default Vue.extend({
    name: "MultiSelectViewDemo",
    data() {
        return {
            items: [
                { id: "A", name: "Option A" },
                { id: "B", name: "Option B" },
                { id: "C", name: "Option C" },
            ],
            selectedItems: [
                { id: "A", name: "Option A" }, 
                { id: "B", name: "Option B" }, 
                { id: "D", name: "Option D" }
            ]
        };
    }
});
```

**Comment by fairking** [comment]
Please see my solution: https://github.com/fairking/primevue/commit/147494e628e57e96417d9bd038dec83869963d53

**Comment by fairking** [comment]
Please see my solution: https://github.com/fairking/primevue/commit/ff3d39588e04c64a5d762ff73efc212787827b6a

**Comment by cagataycivici** [comment]
I think it must be a requirement to have the value inside the options.

**Comment by fairking** [comment]
Sorry in a real world app there are selected items which don't exist in the dictionary anymore, but still actual for the user.
It is fine to have selected something different from what is in the dictionary.

There could be many examples.

1. On init in my application (with primevue ui) the selectboxes have selected only (the options are not loaded). Only when user click to expand the dropdown, those options are loaded from api.
2. The element user selected previously does not exists anymore as an option, so user will see this option as archived. It does not mean that option cannot exists. It is just not available for new items, but existsing one can see it.
