### ISSUE TITLE
no filled inputstyle in Sidebar or OverlayPanel

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1109]
I use Material Design Compact Indigo Light Theme with filled style.
Until version 3.2.1 the filled style inside a Sidebar or OverlayPanel is fine.
In higher versions and version 3.3.5 there is no filled style inside a Sidebar or OverlayPanel any more. It changes to outlined style.

**Comment by cagataycivici** [comment]
Issue is not clear, please create a new ticket with a codesandbox sample to we can see the issue. You may fork the official code sandbox samples at showcase and update it to demonstrate it.
