### ISSUE TITLE
DataTable does not honor initial selection

### ISSUE THREAD

**Issue by harveylee** [primefaces/primevue#1111]
When using `v-model:selection="selectedItems"` to bind a Vue ref to the data table selection, the data table is not created with any selection even if `selectedItems` is populated.

A workaround I am using is to call `updateSelectionKeys` when the component is mounted, i.e.:

`// Vue 3 script setup syntax
const dataTable = ref(null) // points to data-table ref in SFC template
onMounted(() => {
  if (dataTable.value.dataKey) {
    dataTable.value.updateSelectionKeys(selectedItems.value)
  }
})`

I think perhaps something like this should be implemented in the [`mounted` hook of DataTable.vue](https://github.com/primefaces/primevue/blob/54876807d17683c2cf1dc676309f5b5506c9b4ed/src/components/datatable/DataTable.vue#L385)?

**Comment by cagataycivici** [comment]
I've tried various cases but unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with **our codesandbox template** fork so that we can work on it again. Thank you.
