### ISSUE TITLE
Doubled grid lines in scrollable table

### ISSUE THREAD

**Issue by mmitevski** [primefaces/primevue#1112]
![image](https://user-images.githubusercontent.com/11592264/112419571-4deb1580-8d34-11eb-94b9-74a37dbe5175.png)

**Comment by tugcekucukoglu** [comment]
We could not replicate it. Could you share a code example or codesandbox?

**Comment by mmitevski** [comment]
<DataTable :value="items" ref="table"
        :loading="this.loading" :rowHover="true" v-model:selection="selected"
        dataKey="id" selectionMode="single" :scrollable="true" scrollHeight="flex"
        class="p-datatable-gridlines p-datatable-striped p-datatable-sm">
...
   </DataTable>

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with our codesandbox template forkso that we can work on it again. Thank you.
