### ISSUE TITLE
InputNumber: Cannot type or delete fraction digits when min-fraction-digits is null/0

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#1117]
When Using https://primefaces.org/primevue/showcase/#/inputnumber I cannot find a way to delete or insert decimal points but I would like to do so. There are several issues for other primefaces and most of them are resolved but I cannot find a way to do the same with primevue.

https://codesandbox.io/s/determined-roentgen-jvtit?file=/src/App.vue

Basically the same as https://github.com/primefaces/primeng/issues/9272

**Comment by tugcekucukoglu** [comment]
InputNumber does not renders text. So please remove `type="text"` from InputNumber component.

**Comment by Anubarak** [comment]
@tugcekucukoglu I did, it still does not work. Should I open a new issue?

**Comment by tugcekucukoglu** [comment]
using `:minFractionDigits` could help.

[csb](https://codesandbox.io/s/gifted-galois-n7rn4)

**Comment by Anubarak** [comment]
Yeah but I don't want to have them always, just when required.
So in the end it's not possible. Could we leave that as a feature request or do I have to create a custom component?
