### ISSUE TITLE
Control paginator page in lazy mode

### ISSUE THREAD

**Issue by AndreasNasman** [primefaces/primevue#1118]
I have an event that fetches paginated ready data from a backend. How do I manually control the current page of a `DataTable` paginator in lazy mode?

Currently, the current page stays the same (or as high as possible) when `:value` changes. Always going back to the first page when `:value` changes would also fix my problem.

**Comment by tugcekucukoglu** [comment]
Are you using PrimeVue 2? It will fix for 2.4.1 . If you're using PrimeVue 3, please try to use 3.3.5 .

**Comment by AndreasNasman** [comment]
I'm using version 3.3.5.

**Comment by shaan1974** [comment]
Hello,

A - Basicly you have to add event page on datatable "@page="onPage($event)"

B - You have to create a structure "lazyParms" that you fill into mounted:

`    this.datatable.users.lazyParams = {
      first: 0,
      rows: this.$refs.dtCustomers.rows,
      sortField: null,
      sortOrder: null,
      filters: null,
      page: 0
    }
`
    
C - You have to create a "Load Api" to get data from a php page by ex. This page should receive as params the "lazyParams"
    
`
onPage (e) {
var o = Object.assign({}, { params: { lazyEvent: this.datatable.users.lazyParams } })
this.datatableValue = this.loadData()
}

loadData ()
{
axios.post('/api/orest.php', o).then((res) => res.data)
}
`

If you datatable use "Sort" capability you can use also the "@sort" event on table.

**Comment by AndreasNasman** [comment]
@shaan1974 That code snippet is the other way around from what I want.

I basically have the backend controlling everything: the number of rows to show, the total amount of records, and the current page. Everything works and binds properly from my data to the `DataTable` props, except the current page, as it can't be given as a prop.

You can also see problems with the pagination in the [lazy `DataTable` example](https://www.primefaces.org/primevue/showcase/#/datatable/lazy) from PrimeVue's documentation. E.g., if you navigate to page 2, filter by **_F_** in the name filter and click `Enter`, the page number says that you are back on page 1 but you're really still on page 2; if you click on page 1, page 1's actual data is loaded.

**Comment by shaan1974** [comment]
I related this problem that when you have a table in lazy loading and you are by ex on page 3, if you select a filter , the pager goes directly on page 1 ;)
I ask the primevue team if it's possible in case of lazy loading to avoid this behaviour but no answer :)

In my case i just want to apply all selected filters when i want :) But right now i have to check if the filter model has been change with a watch and apply the news filter(s) directly and reload the data of datatable.

**Comment by juanparati** [comment]
I am facing the issue the Datatable, I am also using lazy load and I cannot set the page returned from the backend. I think that it could be nice to implement a method or a bind that force a page set.

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with our codesandbox template forkso that we can work on it again. Thank you.

**Comment by AndreasNasman** [comment]
Will test it once 3.4.1 is released.

**Comment by nonamez** [comment]
did any one managed to solve thIs? Basically what I need is to setup which current page is when loading first time.

**Comment by keystrm** [comment]
Did anyone find an answer to this? It seems the problem remains the same.Is there any way to control pagination or just reset the table to its initial state?

**Comment by blogui91** [comment]
I am having the same problem using `lazy`, in the current version 3.26.1

If It starts from page 3, the component doesn't select the page 3 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/5723380/231802745-aebba84d-0ab5-4591-9de4-384e0e5c1a52.png">

If I move next or to specific page it doesn't work neither.

**Comment by sobergt** [comment]
try to add Paginator component below the datatable ,then control the pagination of page

**Comment by elmalki** [comment]
The current page is a computed value on the Paginator component, it's calculated based on the first item, so you shoud change the first item by doing this `:first="(currentPage-1)*itemsByRow"`, where the **itemsByRow** represent the _number of rows showed_ so if rows=10 then `:first="(currentPage-1)*10"`. I hope this will help you.

**Comment by jabernalv** [comment]
It’s quite surprising this was closed without a fix or follow-up.

We’re still facing **the same issue today in lazy mode**: when using `v-model:first` to restore state (e.g., from `localStorage`), the DataTable **emits a rogue `@page` event with `first = 0` on mount**, overriding the correct pagination state.

We’ve opened a detailed bug report with reproducible steps and a working StackBlitz:  
👉 https://github.com/primefaces/primevue/issues/7618

This behavior is a major blocker for anyone trying to **persist DataTable state** (pagination, filters, sort) across sessions — something users **expect** from modern systems.

We kindly ask the core team to revisit this. If needed, we’ll bring back some of the original metralleta crew 🔥

**Comment by charlietyn** [comment]
I'm update the d_first value on the table instance
