### ISSUE TITLE
FullCalendar does not use option "backgroundColor" for each events

### ISSUE THREAD

**Issue by zablik** [primefaces/primevue#1119]
vue: "3.0.7"
primevue: "3.3.5"

Hi, 

I want to have different background colors for events displayed in `FullCalendar`.

In config I try to use all options I've found in origin FullCalendar documentation
```
      events: [
        {
...........
              {
                "id": 2,
                "title": "Long Event",
                "start": "2019-01-07",
                "end": "2019-01-10",
                color: 'red',
                backgroundColor: 'red',
                borderColor: 'red',
                textColor: 'red',
                eventColor: 'red',
              },
              {
                "id": 3,
                "title": "Repeating Event",
                "start": "2019-01-09T16:00:00",
                color: 'purple',
                backgroundColor: 'purple',
                borderColor: 'purple',
                textColor: 'purple',
                eventColor: 'purple',
              },
...........
```
... but the background color remains the same as it is defined in (my case is `saga-blue/theme.css`)
```
.fc .fc-view-harness .fc-event, .fc .fc-view-harness .fc-event-main {
  background: #0d89ec;
  border: 1px solid #0d89ec;
  color: #ffffff;
}
```

![Screenshot 2021-03-25 at 15 12 02](https://user-images.githubusercontent.com/6074433/112471319-caa1e200-8d7c-11eb-907d-4b0e9e2ac375.png)

What can I do to change the background color of the events?

**Comment by zablik** [comment]
For anyone who faces this issue I've found a temporary workaround. Hope there is a better way, though

```
a[style*="background-color: grey"] > * {
  background: grey !important;
}
```

**Comment by cagataycivici** [comment]
Closing as full calendar is deprecated in favor of the official component.

**Comment by MikesGlitch** [comment]
Pretty sure this is still a problem.  FullCalendar style inline like so
![image](https://user-images.githubusercontent.com/5285928/147248800-efdbce7d-47b5-425b-90d1-526eab0c199b.png)

PrimeVue is overriding the style further down the chain
![image](https://user-images.githubusercontent.com/5285928/147248736-9593d3df-047e-4b5f-9ac3-9fa48f907354.png)
