### ISSUE TITLE
Add raw html to components

### ISSUE THREAD

**Issue by gbayarri** [primefaces/primevue#1122]
Hi, is it possible to add raw html to components?

For example, in a Toast component:

```
this.$toast.add({severity:'success', summary: 'Success Message', detail:'Order <strong>submitted</strong>', life: 3000});
```
It seems that the only way in Vue is to use the v-html directive.

Thanks!

**Comment by cagataycivici** [comment]
Templating is the preferred way for this, feel free to create a new ticket for the component that you need templating for e.g. Toast.

**Comment by gbayarri** [comment]
HI @cagataycivici , where are the guidelines to create a ticket?

Thanks!
