### ISSUE TITLE
Time Filter Error on DataTable

### ISSUE THREAD

**Issue by ahmedkandel** [primefaces/primevue#1126]
This issue is related to #1048 , The Date filter issue is now fixed but if the filter has `:showTime="true"` it will have strange behavior and finally will give an error.

First, when focus on the filter field the calendar will show then hide immediately. But if we add another filter rule the second calendar will work properly while the first calendar will give the following error:
`Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. at insert (http://localhost.com/js/app.js:12712:16)`

PrimeVue version 3.3.5

**Comment by tugcekucukoglu** [comment]
Duplicate the [#1076 ](https://github.com/primefaces/primevue/issues/1076)
