### ISSUE TITLE
Calendar  component doesn't use dateFormat attribute for the  existing v-model value

### ISSUE THREAD

**Issue by mmitevski** [primefaces/primevue#1127]
Existing value from JSON is 2021-03-09T00:00:00Z, dateFormat is set to "dd.mm.yy", but UI renders  the JSON raw value.

**Comment by tugcekucukoglu** [comment]
Calendar component returns JSON data. This is expected behavior and also v-model reflects dateFormat. Using `.toString()` method, you can manipulate the UI.

**Comment by DevDecrux** [comment]
Is this fixed for Primevue/Calendar 2.4.1? Because I am receiving a date from my API backend and setting the value through v-model, and my dateFormat ignores to mask the value from v-model?

**Comment by Tomarr** [comment]
Can someone explain the reason why the calendar still showing JSON value? rather than formatting the value to the given format.

Thanks

**Comment by michug** [comment]
in my case the calendar is dispaying the date in the defined format (dd.mm.yy) but the v-model binded variable is geting a full blown:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/29923881/160015147-cd99cbd6-bddc-4949-914a-03b3dba64065.png">

**Comment by oooowl** [comment]
+1

**Comment by joaopaulocruz** [comment]
Is there a solution here?

**Comment by joaopaulocruz** [comment]
I created a new component that format the date and it's working fine!

`<template>
  <Calendar
    :modelValue="modelValue"
    :showTime="showTime"
    :hourFormat="hourFormat"
    :stepMinute="stepMinute"
    :showIcon="showIcon"
    @dateSelect="updateValue"
  />
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue"
import useUtil from "../hooks/useUtil"

export default defineComponent({
  name: "NewCalendar",
  props: {
    modelValue: null,
    showTime: { type: Boolean, required: false, default: false },
    showIcon: { type: Boolean, required: false, default: false },
    stepMinute: { type: Number, required: false, default: 1 },
    hourFormat: null
  },
  setup(props, context) {
    onMounted(() => {
      if (typeof props.modelValue === "string") {
        updateValue(useUtil().parseJSONISOToDate(props.modelValue))
      }
    })

    const updateValue = (date: Date) => {
      context.emit("update:modelValue", date)
    }

    return { updateValue }
  }
})
</script>
`

**Comment by joaopaulocruz** [comment]
I created a new component that format the date and it's working fine!

```
<Calendar
:modelValue="modelValue"
:showTime="showTime"
:hourFormat="hourFormat"
:stepMinute="stepMinute"
:showIcon="showIcon"
@dateSelect="updateValue"
/>
<script lang="ts"> import { defineComponent, onMounted } from "vue" import useUtil from "../hooks/useUtil" export default defineComponent({ name: "NewCalendar", props: { modelValue: null, showTime: { type: Boolean, required: false, default: false }, showIcon: { type: Boolean, required: false, default: false }, stepMinute: { type: Number, required: false, default: 1 }, hourFormat: null }, setup(props, context) { onMounted(() => { if (typeof props.modelValue === "string") { updateValue(useUtil().parseJSONISOToDate(props.modelValue)) } }) const updateValue = (date: Date) => { context.emit("update:modelValue", date) } return { updateValue } } }) </script>


```

**Comment by riyadhradhi** [comment]
Is this a WIP bug or a low priority? I'm facing the same issue.. 

Thanks!

**Comment by Kayrah87** [comment]
I'm facing the very same issue here. This really needs to be sorted. When you bind the element to a v-model you really do expect the output to respect the dateFormat property provided. 
in this case, ```                            <Calendar
                                id="start_date"
                                v-model="form.startDate"
                                date-format="dd/mm/yy"
                                name="start_date"
                                class="my-auto max-h-[35px] text-xs"
                                @change="getMembersForDates"
                            />```
sets form.startDate to `Mon Jan 01 2024 00:00:00 GMT+0000 (Greenwich Mean Time)`

**Comment by PaulMcML** [comment]
For anyone landing here with similar issues, the Calendar expects the v-model value to be a javascript Date object in order to work properly.  We'll normally have a string to work with , and so in my situation, in my parent component's onMounted method I had  (for the 'close_time' property of an item

```
onMounted(() => {
	// the calendar expects a javascript Date object
	if(props.item.close_time){
		props.item.close_time = new Date(props.item.close_time)
	}
})
```

...

then e.g.

`<Calendar id="closeTime" v-model="item.close_time" showIcon showTime dateFormat="dd/mm/yy" iconDisplay="input" hourFormat="12" :minDate="minDate"/>
`

Took some digging and headscratching and should probably be more explicit in the docs.

**Comment by Jarpiino** [comment]
very frustrating problem. why is it closed?

**Comment by movy** [comment]
Was reluctant to use calendar component instead of simple text input for dates due to potential timezone issues (programmer's childhood trauma), but this one really takes the cake. 
At the very least the docs should be updated: https://primevue.org/calendar/, as it's unobvious what v-model should be in `Calendar`'s case.

**Comment by nikriaz** [comment]
I found that direct assignment to another reactive variable, e.g. in Pinia store, breaks formats even if it's already in `Date`. Re-creating helps:

```
            //store.personalData.birthDate! ->> is already Date object type
            if (store.personalData) {
                //personalData.value = store.personalData; --> but direct assignment leads to rendering JSON
                personalData.value = {
                    ...store.personalData,
                    birthDate: new Date(store.personalData.birthDate!) // --> This fix it
                };
            }
```

**Comment by runecodedev** [comment]
If someone is strugling with it right now there is a solution that I made using watcher :)

```
<template>
  <Calendar
    v-model="dateOfBirth"
    placeholder="DD/MM/YYYY"
    dateFormat="dd/mm/yy"
    showButtonBar
    @date-select="handleDateOfBirthChange"
  />
</template>

<script setup>
  const dateOfBirth = ref();
  
  watch(
    () => dateSource, // dateSource is a variable where u retrieve your date
    () => {
      dateOfBirth.value = new Date(dateSource);
    }
  );
  
  const handleDateOfBirthChange = (date) => {
    // some function
  };
</script>
```

**Comment by CWSpear** [comment]
This was tested in PrimeVue v4 (where it's been renamed to `DatePicker`), but I created a `StringDatePicker` wrapper component. It's a drop-in replacement for `DatePicker`:

```vue
<template>
  <DatePicker v-bind="{ ...$attrs, ...$props }" v-model="modelValue" />
</template>

<script lang="ts" setup>
// could use `moment` or just raw `Date`
import dayjs from 'dayjs';

// if you want, you can import the types for code-completion. does not work for emits, as they are "too complex"
// import type { DatePickerEmits, DatePickerProps, DatePickerSlots } from 'primevue/datepicker';

// const props = defineProps<DatePickerProps>();
// defineEmits<DatePickerEmits>();
// defineSlots<DatePickerSlots>();

const modelValue = defineModel<string>({
  get: (value) => dayjs(value).toDate(),
  set: (value) => {
    const strFormat = dayjs(value).format();
    //  optionally only return the date portion if there is no `showTime`
    if (props.showTime) {
      return strFormat;
    } else {
      return strFormat.replace(/T.*$/, '');
    }
  },
});
</script>
```

**Comment by mazay33** [comment]
_v 4.0.5_

It is really very inconvenient to format the date that comes from the backend every time and format it before sending.

My wrapper, which solves my problems, can probably be improved. I didn't check for all props.

```vue
//UiDatePicker.vue
<script lang="ts" setup>
import type { DatePickerSlots } from 'primevue/datepicker';

import { format } from 'date-fns';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const slotProps = defineSlots<DatePickerSlots>();

const props = defineProps<{
	showTime?: boolean;
	formatValue?: string;
	selectionMode?: 'single' | 'multiple' | 'range';
}>();

const formatDate = (date: Date | null | undefined): string | undefined => {
	if (!date) return undefined;
	const formattedDate = format(date, props.formatValue || 'yyyy-MM-dd');
	return props.showTime ? formattedDate : formattedDate.replace(/T.*$/, '');
};

const modelValue = defineModel<Date | Date[] | undefined | null>({
	get: (value) => {
		if (Array.isArray(value)) {
			return value.filter(Boolean).map(date => new Date(date as Date));
		}
		else if (value) {
			return new Date(value);
		}
		return null;
	},
	set: (value) => {
		if (Array.isArray(value)) {
			return value.filter(Boolean).map(date => formatDate(date as Date)) as (string | undefined)[];
		}
		else {
			return formatDate(value);
		}
	}
});
</script>

<template>
	<DatePicker v-bind="$attrs" v-model="modelValue" :selection-mode="props.selectionMode">
		<template v-for="slot in Object.keys(slotProps)" #[slot]="slotProps">
			<slot :name="slot" />
		</template>
	</DatePicker>
</template>
```

use
```vue
<FloatLabel class="col-span-3">
	<UiDatePicker id="startDate" v-model="start_planned" selection-mode="multiple" format-value="yyyy-MM-dd"
		:disabled="mode === 'view'" class="w-full">
		<template #header>
			test slot header
		</template>
		<template #footer>
			test slot footer
		</template>
	</UiDatePicker>
	<label for="startDate">Дата начала(план)</label>
</FloatLabel>
```

**Comment by micdobro** [comment]
@mazay33 your solution works, but that component is still broken. It's totally anti-productive to deal with things like that in 2024...

**Comment by Jarpiino** [comment]
Agreed.

**Comment by martijnvanloonafs** [comment]
This is so annoying, I now need to format dates like 6 times. Still love the library in general

**Comment by paddelboot** [comment]
Datepicker submits a date formatted like this: `'Wed Dec 25 2024 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)'` 

Neither date-fns nor `new Date()` is able to correctly format this. What is going on here, why would you output such a string instead of the one provided in `dateFormat`?

**Comment by patie** [comment]
This is very annoying, I like PrimeVue components, but some things simply doesn't make sense.

**Comment by lordfeck** [comment]
This caused much more of a headache than it should. On first load, I couldn't get the Calendar to show anything other than an long, ugly ISO string. This is unacceptable for anything user-facing. I just gave up and used the native input date element. At least its string format is consistent when binding to v-model, and it defaults to the user locale for display anyway.

**Comment by marra-smartfit** [comment]
The year 2025 is coming to an end, and this is still a problem.
A simple “valueFormat” flag would be ideal for formatting the value, just like Dropdown's “option-value” works, but the PrimeVue team doesn't seem to care that much.
Why send the complete date and time object if I don't activate the time functionality?

<img width="399" height="82" alt="Image" src="https://github.com/user-attachments/assets/568bcf2e-69d4-4c63-a69c-8e7d9fed4b99" />

<img width="395" height="94" alt="Image" src="https://github.com/user-attachments/assets/15fa0e88-2d90-40ad-9a76-7d8292ea8ae5" />

**Comment by PaulMcML** [comment]
I'll just put a reminder on here that this component uses javascript Date objects, so you need to convert any string to that before setting the value.  When submitting, "2025-09-16T03:00:00.000Z" for example is a stringified representation of the object and so the any decode of the json would need to take that into account to convert into a native date object on the backend.

**Comment by nikriaz** [comment]
Okay, after updating PrimeVue from v3 to v4 old problems come in again. This is a quick wrap-up:

1. The bound model should be the Date type by default
2. They added `stringTypeModel ` prop as many wished above
3. In the TypeScript, If the variable is defined as a Date at the design time, it does not guarantee that it will stay the Date at the runtime. Specifically my answer on May, 2024 worked because Pinia deserializes from its persistent store to the string by default, so I mistakenly assumed that was a Date while it was actually a string. 
4. v4 of DatePicker brought something new. In the v3 when you updated the model, DatePicker updated the internal state as well. It is not the case anymore, or at least not always the case. 

When the page rendered normally, components are typically rendered before the model is hydrated. At this moment, the model is typically undefined. In v4, even if you change the model after then, new model value does not anymore change the component's inner state. I'm not sure if only "undefined" assignment causes this quirk or any continuous model changing. 

Solution is: add `v-if="isReady"` gate to the component and assign true only when the model is actually ready.
