### ISSUE TITLE
Module '"vue"' has no exported member 'PluginFunction'

### ISSUE THREAD

**Issue by tdloi** [primefaces/primevue#1128]
Version:
- Vue: `3.0.5`
- Vite: `2.1.3`
- PrimeVue: `3.3.5`

I'm trying to build my project [tdloi/utils](https://github.com/tdloi/utils) and encounter this error:
```
node_modules/primevue/config/PrimeVue.d.ts:1:15 - error TS2305: Module '"vue"' has no exported member 'PluginFunction'.

1 import Vue, { PluginFunction } from 'vue';
                ~~~~~~~~~~~~~~


Found 1 error.
```
It seems `vue` does not export `PluginFunction`, I couldn't find any document mention this, so maybe this is Vue 2?

After a little digging, turn out Vue use `PluginInstallFunction` for `install` which is declared here: 
https://github.com/vuejs/vue-next/blob/8ffcde2836baa41d279d9cc079f139a2e31cf6be/packages/runtime-core/src/apiCreateApp.ts#L90

Replace `PluginFunction` with `PluginInstallFunction` fix the issue.

**Comment by bylevel** [comment]
temporary repair, add file /src/types/primevue.d.ts

```typescript
import Vue from "vue";
declare module "vue" {
  export type PluginFunction<T> = (app: Vue.App, ...options: any[]) => any;
}
```

**Comment by uncodable** [comment]
Thanks for the quick fix @bylevel

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with our codesandbox template forkso that we can work on it again. Thank you.

**Comment by fuxkgxx** [comment]
> temporary repair, add file `src/types/primevue.d.ts`
> 
> ```ts
> import Vue from "vue";
> declare module "vue" {
>   export type PluginFunction<T> = (app: Vue.App, ...options: any[]) => any;
> }
> ```

vendor.bda01ced.js:1 Error: No PrimeVue Toast provided!
    at zs (vendor.bda01ced.js:1)
    at index.949a509a.js:formatted:21
    at ct (vendor.bda01ced.js:1)
    at ut (vendor.bda01ced.js:1)
    at Array.t.__weh.t.__weh (vendor.bda01ced.js:1)
    at Nt (vendor.bda01ced.js:1)
    at se (vendor.bda01ced.js:1)
    at mount (vendor.bda01ced.js:1)
    at Object.Hs.t.mount (vendor.bda01ced.js:1)
    at index.949a509a.js:formatted:78

**Comment by EthanHaid** [comment]
bumping, needed to use this workaround for toastservice
primevue: v3.5.1

**Comment by coolsam726** [comment]
REOPEN

**Comment by coolsam726** [comment]
Kindly reopen the issue. I am still experiencing the same error when registering services. Development works fine but `yarn build` throws the error described above. Here is my setup:

**Dependencies:**
- "vue": "^3.2"
- "vite": "^2.5.4"
- "vue-tsc": "^0.2.2"
- "typescript": "^4.3.2"
- "primevue": "^3.7.1"
**Build Command**
- "vue-tsc --noEmit && vite build"
