### ISSUE TITLE
InputNumber just update model after blur or "ENTER" key. Why not on KeyDown or KeyPress?

### ISSUE THREAD

**Issue by emersoncpaz** [primefaces/primevue#1130]
InputNumber just update model after blur or "ENTER" key, this is bad for realtime validation. 

Is there any workaround? Is it possible to update model on keydown or keypress?

**Comment by shaan1974** [comment]
Hello.

It's possible ;)

All you have to do is creating an attribute "ref" for your "inputNumber" and also create your own event "keyup".
See below

`<InputNumber ref="refAmount" v-model="form.amount" mode="decimal" :minFractionDigits="2" v-on:keyup="this.$refs.refAmount.onInputBlur($event)"/>`

**Comment by mertsincan** [comment]
Hi,

Please see this enhancement; https://github.com/primefaces/primevue/issues/506

Best Regards,

**Comment by codenomnom** [comment]
This is extremely annoying! Currently model is still not updated on user manual input. And I am sure there are many workarounds, but I cannot understand why is this intended?
