### ISSUE TITLE
Add loading prop to Dropdown, Multiselect ...

### ISSUE THREAD

**Issue by shadoWalker89** [primefaces/primevue#1132]
Hi,

I started using your components recently and i'm so happy that i did. This is such an amazing product, so thanks for that.
Before using vue prime i used to work with semantic ui dropdown and it has a cool feature. If you add a `.loading` class to the dropdown it will show a little loading spinner

![image](https://user-images.githubusercontent.com/1449151/112835953-41e7b680-909a-11eb-8f05-bde6341ab55f.png)

This allows for a nice feedback to the user that the app is loading something and it does not clutter the html with loader components.

Are you open to the idea of adding a `loading` prop to the Dropdown, Multiselect and other components ?

Maybe this could be my first contribution to this amazing project.

Thanks

**Comment by cagataycivici** [comment]
Sounds good!
