### ISSUE TITLE
[Help] select item Tree from a method instead of a click - hightLightSelectedNode

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#1134]
Tree
```
https://primefaces.org/primevue/showcase/#/tree
```

Is not working
```
this.selectedKey2 = id;
```

Clear selection is not working because you can't set this object.
```
this.$refs.tree.selectionKeys = {}
```

How can i hightLightSelectedNode from a method ?

For example:
```
hightLightSelectedNode(node) {
this.$refs.tree. ????(node)
}
```
```
this.$refs.tree.selectionKeys[this.$data.currentStructureItem.key] = false
      this.$data.currentStructureItem = itemInTree;
      this.$refs.tree.selectionKeys[itemInTree.key] = true
I have solved this by this way but i need to hightLightSelectedNode, how can i do it ?
```
p-treenode-content p-treenode-selectable p-highlight

and how can i get the element in the DOM without an id ?
not document.querySelector(".p-highlight");

**Comment by tugcekucukoglu** [comment]
You don't need to id `node-select` event return node. Please check [tree/selection csb](https://codesandbox.io/s/strange-sanderson-d3s4n)

If the issue still persists please provide codesandbox example or a github repo.

**Comment by vadimt2** [comment]
This is not helping me, The issue is that i need to select node without clicking on the node.
I have an emit somewhere in my app and i'm selecting from emit without clicking on the node.
and i need to unselect all the nodes!
```
this.$refs.tree.selectionKeys = {}
// for some reason it doens't let me set the object to {}
```

**Comment by vadimt2** [comment]
I have solved this by:
```
 const button = document.createElement("button");
        this.expand(path.path)
button.addEventListener('click', event => {
  (event as any).node = itemInTree
  (event as any).originalEvent = {metaKey: itemInTree.key}
  this.$refs.tree.onNodeClick(event);
});   
button.click();
```
Not the best solution but it works :)
I'm suggesting to keep it open

**Comment by cagataycivici** [comment]
Please use forum or discord chat for questions and help requests. Thank you.
