### ISSUE TITLE
InputNumber - Ability to add or remove fraction digits when min-fraction-digits is not set

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#1136]
It's essential for us to add the ability to write fraction digits at will.
If a user wants to they should be able to write
```text
// imagine comma "," as the decimal separator
10,05
10
10,00
```
as they like without forcing them.
Currently, when `min-fraction-digits` is null/empty you **cannot** add fraction digits. I think this is no good.
`min-fraction-digits` is missguiding in my opinion because it defines the max-fraction-digits as well when it's null,

**Comment by cagataycivici** [comment]
Delaying to post 3.5.0 as we'll tackle this one with some other issues and release them together.

**Comment by Jogai** [comment]
Too bad I didnt see this issue earlier. I'd like to have the ability to input a number starting with . or ,; Instead of typing 0.23 you should be able to type just .23 then. Is this possible? Should I open a separate issue for this?

**Comment by mertsincan** [comment]
Hi @Jogai,

No problem! Could you please create a new issue for it? Let's see what we can do :)

Best Regards,
