### ISSUE TITLE
Add metadata as web-types for better developing experience using Jetbrains Webstorm/Intellij IDEA

### ISSUE THREAD

**Issue by bjorntj** [primefaces/primevue#1138]
After PrimeVue 3.2.0, there is no IDE support for the PrimeVue components (in eg Webstorm). Jetbrains recommends to use web-types to add this kind of support, more info here: https://github.com/JetBrains/web-types
Would be great if this would be implemented.

**Comment by cagataycivici** [comment]
Added for 3.4.1.
