### ISSUE TITLE
Improve TieredMenu collision detection

### ISSUE THREAD

**Issue by arieljake** [primefaces/primevue#1139]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/59510/113245723-5bd8f300-926c-11eb-919d-0bccefa87f96.png">

**Comment by amisora** [comment]
Has this been fixed ?
Still having this issue with TieredMenu. 
ContextMenu, however behaves as expected.

#2765 is closed but the related duplicate doesn't address the TieredMenu, only the ContextMenu.

**Comment by melloware** [comment]
Just an FYI this is fixed in PrimeReact with this code:
https://github.com/primefaces/primereact/blob/d5331d174d39f182f2b269257c132f5f633a82ba/components/lib/tieredmenu/TieredMenuSub.js#L19-L38

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
