### ISSUE TITLE
Vite support for Charts

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#1140]
While [PrimeVue professes Vite support](https://dev.to/primetek/primevue-3-2-0-brings-vite-support-1i9k), the Chart cannot be used.

To recreate:
Pull the [primevue-quickstart-vite](https://github.com/primefaces/primevue-quickstart-vite) application from Github
Install Chart.js
Import Chart from 'primevue/chart'
Add `<Chart type="bar" />` to HelloWorld.vue

Result:
```
Uncaught TypeError: Chart is not a constructor
    at Proxy.initChart (chart.esm.js:42)
```

PrimeVue: 3.3.5
Vue: 3.0.11
Vite: 2.1.5
Chart.js 2.9.4

**Comment by makurtu** [comment]
You need a `Chart.js` version 3.x, using version 2.x of this lib is a bad idea (heavy lib and, as you said, is vite incompatible).

I provisionally use the raw implementation of `Chart.js` and not the provided by Primevue until `Chart.js` dependency not upgraded to 3.x.

**Comment by cagataycivici** [comment]
I think this is related to Chart bundle not directly related to Chart component, we just import it as a module.

**Comment by tugcekucukoglu** [comment]
With PrimeVue 3.5.2, Chart.js has been updated 3.3.2. 

Thank,
