### ISSUE TITLE
Support for Chart.js 3.0

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#1142]
Chart.js 3.0 is released which introduces [a number of of breaking changes](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html) and the PrimeVue Chart component does not work with this new version.

Please provide support for this new version of Chart.js.

**Comment by mwe-code** [comment]
> Chart.js 3.0 is released which introduces [a number of of breaking changes](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html) and the PrimeVue Chart component does not work with this new version.
> 
> Please provide support for this new version of Chart.js.

Although it is necessary and important to fix the PrimeVue Chart component accordingly, Chart.js version 3 can still be used with PrimeVue.

**Comment by cagataycivici** [comment]
Push to 3.5.0.

**Comment by adamdehaven** [comment]
Any update on this? I can't get charts to display at all; however, there don't seem to be any errors in the console either which I find strange

**Comment by tugcekucukoglu** [comment]
It's fixed for PrimeVue 3.5.2.

Thanks,

**Comment by adamdehaven** [comment]
@tugcekucukoglu any idea when will 3.5.2 be released...?
