### ISSUE TITLE
Add appendTo to overlay components

### ISSUE THREAD

**Issue by lukasschinninger** [primefaces/primevue#1148]
Currently for overlay components (like Dialog,Sidebar,etc) its not possible to set the appendTo attribute. So the dialog element directly  gets appended to the body 
![image](https://user-images.githubusercontent.com/31884422/113736569-80661c80-96fd-11eb-8bca-6c5c67d82ba4.png)
![image](https://user-images.githubusercontent.com/31884422/113736904-cde28980-96fd-11eb-9a7a-c4f3281b85b1.png)
and scoped css ( in this example the .inc class) is not working.

With appendTo it should be possible:
![image](https://user-images.githubusercontent.com/31884422/113737104-071af980-96fe-11eb-9d48-6906a27f8c87.png)
![image](https://user-images.githubusercontent.com/31884422/113737167-139f5200-96fe-11eb-8395-d3e6618b09bc.png)

Can you add support for appendTo (like in DatePicker or DropDown) for these components ?

**Comment by afonic** [comment]
The problem is that many overlay components were changed to use Vue 3's teleport feature, but teleport cannot be used inside the Vue app itself. So appendTo is impossible. This creates all kinds of problems in a variety of cases that are not trivial to fix.

Here is a relevant issue: https://github.com/primefaces/primevue/issues/1083

**Comment by cagataycivici** [comment]
This is related to Vue teleport, we should rely on the vue runtime to resolve this. For example, in React, teleport is much more flexible whereas in Vue teleport cannot be used within the app. So appendTo is pretty useless.

**Comment by afonic** [comment]
@cagataycivici there is no indication that Vue will resolve this though. 

In my opinion you could maybe revert the decision to use Vue teleport in a number of components? See https://github.com/primefaces/primevue/issues/1028

**Comment by cagataycivici** [comment]
This may help -> https://github.com/primefaces/primevue/issues/1185

We added "self" so it stays as a part of the element. I even solved a couple of cases with appendTo="self". So we not support "body" (default), "self" and any other thing that teleport supports.
