### ISSUE TITLE
Calendar datetime picker with stepMinute 15

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#115]
I have a field which is DateTime picker with stepMinute = 15. The problem is the minutes start not from zero but from some random number (probably from the current time). So increasing or decreasing minutes make those steps like `11`, `26`, `41`, `56`. But the way I'd like and how I think it should work is to start from `00` and then increse to `15`, `30`, `45`. I think the initial value must be somewhere to the closest interval (eg. if now is 14:35 then it must be 14:30). 
I could not figure out how to fix the issue.

```
<Calendar id="from_date" v-model="item.fromDate" date-format="dd.mm.yy" 
:step-minute="15" :showTime="!item.allDay" />
```

![image](https://user-images.githubusercontent.com/13495631/71134065-cdff0300-21f4-11ea-82c1-c604293ffac1.png)

PS. At the beginning the field is DatePicker with time 00:00. Then I switch it to DateTimePicker dynamically so `showTime` becomes `true`.

Also as an option there could be a dropdown for hour/minute input.

**Comment by melloware** [comment]
I just fixed this for PrimeFaces.  You can probably look at my PR and fix PrimeVue the same way.
https://github.com/primefaces/primefaces/pull/6048/files

**Comment by west-farmer** [comment]
Expecting this feture! So I can remove the complex computed field from my code.

**Comment by simcen** [comment]
Is there any workaround for this issue?
