### ISSUE TITLE
DataTable : Selection multiple with checkbox didn't appear with filter row

### ISSUE THREAD

**Issue by Zaaaoo** [primefaces/primevue#1150]
Hello, 

I make a CodeSandBox for explain the issue : [https://codesandbox.io/s/jolly-gauss-88kny?fontsize=14&hidenavigation=1&theme=dark&file=/src/DataTableSelectionDemo.vue](url)

**Comment by Herald88** [comment]
+1, Even I am facing the same issue.

**Comment by Zaaaoo** [comment]
This issue must be reopen

**Comment by Zaaaoo** [comment]
Link to the new one : [https://github.com/primefaces/primevue/issues/1193](url)
