### ISSUE TITLE
FullCalendar can't display on a hiden TabView-> TabPanel

### ISSUE THREAD

**Issue by voquanghoa** [primefaces/primevue#1151]
Hello,

It took me a while to discover why the calendar display error on my application.

Then I found that the error happens if I put a full-calendar component inside a TabPanel of TabView (except the first one)

Here is the link https://codesandbox.io/s/serene-cherry-mjorg?file=/src/FullCalendarDemo.vue

This sandbox I cloned from your one ( https://codesandbox.io/s/z7ltg ) and only change the template

```html
<template>
    <div>
        <FullCalendar :events="events" :options="options" />
    </div>
</template>
```

to
```html
<template>
  <TabView>
      <TabPanel header="Calendar OK">
        <FullCalendar :events="events" :options="options" />
      </TabPanel>
      <TabPanel header="Calendar Error">
        <FullCalendar :events="events" :options="options" />
      </TabPanel>
    </TabView>
</template>
```

And the error happens

![image](https://user-images.githubusercontent.com/10450325/113859577-41080080-97cf-11eb-8809-f869ef5ece1b.png)

Could you take a look at this?

Thank you

**Comment by cagataycivici** [comment]
What is your PrimeVue version?

**Comment by voquanghoa** [comment]
Hello.

I used PrimeVue version 3.1.1 at the beginning and got the error. Then I upgraded it to the latest one 3.3.5, the issue still occurs.

The issue can be reproduced at the link  https://codesandbox.io/s/serene-cherry-mjorg?file=/src/FullCalendarDemo.vue

The first calendar displays properly but the second one.

![image](https://user-images.githubusercontent.com/10450325/114738438-2bb44880-9d72-11eb-8732-5d041c8aa1d0.png)

Thanks.

**Comment by cagataycivici** [comment]
With 3.5.0, enable **lazy** rendering to resolve this;

https://github.com/primefaces/primevue/issues/1268
