### ISSUE TITLE
multiselect enhancement: auto-grow to show all selected items, remove items with X

### ISSUE THREAD

**Issue by mariusa** [primefaces/primevue#1152]
Would you please consider making multiselect more usable as a tag selector? That is

1. Auto-grow to show all selected items
2. Remove items with X
3. Be able to add new user defined items to the list (if search term doesn't exist already)
4. Clicking on the input after previously searching something should either have the search empty or auto-selected, so that typing another character starts a new search directly, without the need to select existing old text first

Example: https://vue-multiselect.js.org/#sub-tagging

**Comment by cagataycivici** [comment]
See chips display mode for this. There is a live demo as well.

**Comment by maximilianoCalderon** [comment]
There is something about the autogrow option? I've tried with width-styling but the "..." are always displaying in the control
