### ISSUE TITLE
Carousel breakpoints not working as expected

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#1157]
I used the following responsive options
```JS
responsiveOptions: [
    {
        breakpoint: '1024px',
        numVisible: 5,
        numScroll: 5
    },
    {
        breakpoint: '600px',
        numVisible: 2,
        numScroll: 2
    },
    {
        breakpoint: '480px',
        numVisible: 1,
        numScroll: 1
    }
]
```
https://codesandbox.io/s/focused-wilson-uedb2?file=/src/CarouselDemo.vue

And the result is the following
![breakpoints](https://user-images.githubusercontent.com/6122122/114049959-2ba4dc00-988c-11eb-90f8-6a638b87d727.gif)

Could you please explain me why it goes down to 3 after a certain point? I didn't insert a 3

**Comment by Anubarak** [comment]
I found out compared to most other libraries this is  value must be larger than the window, so it's not like breakpoint <= window and instead breakpoint >= window

**Comment by dheimoz** [comment]
@Anubarak great discovery. I hope this could be translated to the documentation.
