### ISSUE TITLE
[Feature-Request] Add "loading" prop to Buttons

### ISSUE THREAD

**Issue by CurrentlyNoName** [primefaces/primevue#1160]
Hello,

PrimeVue has many features I really like, but one that is missing and some other Frameworks do have is a loading-panel in Buttons.

Like this:
![image](https://user-images.githubusercontent.com/51439005/114190894-1ee7bd00-994c-11eb-9557-65e41321df65.png)
->
![image](https://user-images.githubusercontent.com/51439005/114190588-bf89ad00-994b-11eb-8384-0bcb6bea65ac.png)

For example, this is very useful when a button is clicked and the button should be blocked until there is an answer from a request that is triggered from the button click. 

Also triggering the same event multiple times can be prevented that way.

Best regards

**Comment by glebgolov-ziosem** [comment]
Does it make sense to implement it as a template (e.g.: `<template #loading>`) inside the `Button` component?

In the author's case something like:
```html
<Button label="CLICK ME" @click="handleClick($event)">
  <template #loading>
    <i class="pi pi-spin pi-spinner p-text-center"></i>
  </template>
</Button>
```

**Comment by Zaaaoo** [comment]
We already can perform this with a computed icon : 


    spinnerComputed(): string {
      let icon = ''

      if (this.loadingAuthorizedForAttachment) icon = 'pi pi-spin pi-spinner'
      else icon = 'pi pi-check-square'

      return icon
    },
 
And
  
  `<Button
      label="Valid"
      :icon="spinnerComputed"
      />`

**Comment by saenq** [comment]
worked well for me
`<Button
                :label="!loading ? 'CLICK ME' : ''"
                :icon="loading ? 'pi pi-spin pi-spinner' : ''"/>`
