### ISSUE TITLE
[Feature-Request] Add scrollable to TabView TabPanel

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#1163]
Request an option where the TabView can occupy 100% of the height, but if the contents of a TabPanel overflow, the tab content area will scroll while the tab headers remain fixed.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primevue/issues/364

**Comment by avenmore** [comment]
I think #364 is a different issue, dealing with the tab header overflow. What I am referring to here is the tab *content*. Currently, if there is content which stretches below the page and you have to scroll, the tab headers disappear out the top and to change to the next tab page you have to first scroll back up to the top. I would like an option where the tab headers remain fixed at the top and just the content scrolls, so that even if you are deep down in tab 2s content, it is just one click to change to tab 3.
