### ISSUE TITLE
[Feature request] Option to right align overlays/popup menus/dropdowns

### ISSUE THREAD

**Issue by m-thorsen** [primefaces/primevue#1167]
It's common to have menus triggered from the right side of a panel header/navbar/toolbar etc. - or from form elements in a sidebar on the right side of the viewport.     
In these cases it would be great to have an option to anchor menus/overlays/dropdowns etc. to the right side of the activator.

Similar to Bootstrap's dropdown options
https://getbootstrap.com/docs/5.0/components/dropdowns/#menu-alignment

---

Edit:   
Bonus points if this could be extended to allow overlays to spawn on the left or right side of the activator:  
https://getbootstrap.com/docs/5.0/components/dropdowns/#dropright

**Comment by m-thorsen** [comment]
Just for reference - here's how I've been "hacking" this though a wrapper component:
```js
if (!!this.popupRight) {
  const menuEl = this.$refs.menu;
  const oldAlignOverlay = menuEl.alignOverlay;
  menuEl.popup = true;
  menuEl.alignOverlay = function() {
    oldAlignOverlay();
    const targetRect = this.target.getBoundingClientRect();
    const parentNode = this.container.parentNode;
    this.container.style.left = '';
    this.container.style.right = (parentNode.clientWidth - targetRect.right) + 'px';
  }
}
```

I realize this doesn't cover re-aligning based on proximity to viewport edges and/or appending to other elements, but it's a quick fix for my use case.

**Comment by glebgolov-ziosem** [comment]
Or also trigger the overlay up like the [Bootstrap Dropup](https://getbootstrap.com/docs/5.0/components/dropdowns/#dropup).

**Comment by nbrylevv** [comment]
Yeah, +1!

**Comment by Rakasch** [comment]
+1
Option to display the overlay to the left of the target element would be great.
currently it hides the other buttons.
![image](https://user-images.githubusercontent.com/8471027/206474946-a45a9874-343f-4234-8c2f-b2a2586ed7d1.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
