### ISSUE TITLE
DataTable - Column add a prop to show the clear button only

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#1171]
Currently DataTable Columns have only one prop to display the match modes + the clear button, an example is [here](https://codesandbox.io/s/nostalgic-microservice-22tbe?file=/src/components/DataTableDemo.vue).
Even if I set 
```vue
:showFilterMatchModes="false"
:filterMatchModeOptions="[]"
``` 
I need to render an empty filter match mode menu
![image](https://user-images.githubusercontent.com/6122122/114415447-f9f38400-9baf-11eb-964d-b9cfff5e6ef3.png)
in order to display the clear filter icon.

I would like to display the clear button but no filter match modes, unfortunately this is currently not possible because it looks like this

```vue
<button 
    v-if="showMenuButton && display === 'row'" 
    :class="{'p-hidden-space': !hasRowFilter()}" 
    type="button" 
    class="p-column-filter-clear-button p-link" 
    @click="clearFilter()">
        <span class="pi pi-filter-slash"></span>
</button>
```
-> it's only rendered when `showFilterMenu` is true but that makes no sense to me.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
