### ISSUE TITLE
Editable Data Table not working in Mozilla Firefox

### ISSUE THREAD

**Issue by nicolecortes** [primefaces/primevue#1172]
I am using the vue and primevue versions:
**"primevue": "3.1.1",
 "vue": "3.0.4"**
 
I have a problem editing a table value in Mozilla Firefox browser. When I press the "TAB" button it is supposed to **capture this new value** but actually the data update only works when I click, but TAB and ENTER do not update the data. So far the editable **data table does NOT work in Mozilla Firefox,** **only in Gooogle Chrome.**

Does anyone know how to fix this problem I have with Mozilla Firefox browser?

```
 <DataTable :value="ingresoDato" editMode="cell" @cell-edit-complete="onCellEditComplete($event, 1)" class="editable-cells-table">
              <Column v-for="col of columnas" :field="col.field" :header="col.header" :key="col.field">
              <template #editor="slotProps">
                      <InputNumber :v-model="slotProps.data[slotProps.column.props.field]"    @update:modelValue="onCellEdit($event, slotProps)"
                    :disabled="col.field=='numero'" mode="decimal" :minFractionDigits="1" :maxFractionDigits="1" />
              </template>
      </Column>
</DataTable>
```

**Comment by cagataycivici** [comment]
It works for me on latest PrimeVue, could you please test with the latest version and verify?
