### ISSUE TITLE
Scrolling at the bottom of the page after changing month in calendar

### ISSUE THREAD

**Issue by Frozenzxc** [primefaces/primevue#1174]
Hey. 
You can check this bug here https://primefaces.org/primevue/showcase/#/calendar , for example"basic" calendar:
1. Open calendar
2. Change month
3. Click outside of calendar
4. Open same calendar

"primevue": "3.3.5",
"vue": "3.0.0"

**Comment by cagataycivici** [comment]
Can't get it, can you post a video?

**Comment by Frozenzxc** [comment]
> Can't get it, can you post a video?

https://vimeo.com/537587987 Maybe bad quality

**Comment by tugcekucukoglu** [comment]
Please track at [#1358](https://github.com/primefaces/primevue/issues/1358)
