### ISSUE TITLE
Sidebar content overflows its container

### ISSUE THREAD

**Issue by glebgolov-ziosem** [primefaces/primevue#1175]
"primevue": "^3.3.5",
"primeflex": "^2.0.0",
"vue": "^3.0.0"

As per title, I've seen that the content of the sidebar overflows without any scrollbar showing up. I don't know if it's wanted as it is now in PrimeVue, I've seen the [new Offcanvas component of Bootstrap 5 ](https://getbootstrap.com/docs/5.0/components/offcanvas/)behaving in a [different way](https://codepen.io/ggolov-ziosem/pen/jOyzKYX). Down below I share a little styling to resolve the issue.

### Simple sidebar
![Screenshot_20210413_121358](https://user-images.githubusercontent.com/79850269/114538315-8a36d500-9c53-11eb-897a-8b6bd7aaaf21.png)

### Simple sidebar content
![Screenshot_20210413_121221](https://user-images.githubusercontent.com/79850269/114540509-e7338a80-9c55-11eb-88a0-2daa96c7f113.png)

### A bit more complex example (with TabView and TabPanel(s))
![Screenshot_20210413_121558](https://user-images.githubusercontent.com/79850269/114540490-e00c7c80-9c55-11eb-8502-577d5ce5fda3.png)

## My solution for the TabView case (third image)
For the TabPanel that contains a lot of content I've written:
```html
<TabPanel>
    <template #header>
        <i class="pi pi-fw pi-user"></i>
        <span>Informazioni</span>
    </template>
    <div class="p-inputtext-sm p-mt-3 p-px-2" style="height: calc(100vh - 200px); overflow-y: auto">
        <div class="p-fluid p-formgrid p-grid">
            ...
        </div>
        <Divider class="p-mt-0" />
        <div class="p-fluid p-formgrid p-grid">
            ...
        </div>
        <Divider class="p-mt-0" />
        <div class="p-fluid p-formgrid p-grid">
            ...
        </div>
    </div>
</TabPanel>
```
where `style="height: calc(100vh - 200px); overflow-y: auto"` is added to make it work and the class `p-px-2` (`primeflex` needed) to compensate the width taken by the scroll bar. In this case 200px in the height calculation are ok but it is possible to change to your liking.

If you want to use the ScrollPanel component instead, it is possible to replace the uppermost div in the TabPanel with a little more concise `<ScrollPanel class="p-inputtext-sm p-mt-3" style="height: calc(100vh - 200px)">`

**Comment by tugcekucukoglu** [comment]
Thanks for your report. It is fixed.
