### ISSUE TITLE
Enhancement: Use css color variables also for Primevue-Components

### ISSUE THREAD

**Issue by panwauu** [primefaces/primevue#1176]
I think it is great that you expose the colors now! I am already using this a lot.

Still in order to unify the colors throughout the design it would be great if the Primevue-Components like Messages/Toast... would use the colors from the variables. As far as I have seen they are still different.

Correct me if you have already done this. Thanks for the great Library and the good support!

**Comment by cagataycivici** [comment]
Thanks but that would be a reimplementation of the entire theming for all Prime libraries so we rather not do it.
