### ISSUE TITLE
[Feature request] PromptPopup Component

### ISSUE THREAD

**Issue by glebgolov-ziosem** [primefaces/primevue#1182]
It may be handy for forms with a few inputs to pop up near their triggering elements instead of a new view or dialog.

A little visual example:
![Screenshot_20210415_170152](https://user-images.githubusercontent.com/79850269/114891626-5521b280-9e0c-11eb-803c-b0c8faf3a1d7.png)

**Comment by cagataycivici** [comment]
There is OverlayPanel for this.
