### ISSUE TITLE
Support for hiding a tab panel

### ISSUE THREAD

**Issue by rafaeljosem** [primefaces/primevue#1184]
Hello,

Please add support for hiding a tab panel in the tab view component. It could be a property such as :hide="true"

Thanks!

**Comment by cagataycivici** [comment]
I think you can just use v-if on the panel component for this.

**Comment by rafaeljosem** [comment]
I've tried but it gives an error: Uncaught (in promise) TypeError: child.children.forEach is not a function.

**Comment by Anubarak** [comment]
@cagataycivici This is not possible due to the "miss-use" of `vNodes` instead of actual child Components due to `this.slots.$default()`.
If you would use the TabPanel as an actual Component it would work
