### ISSUE TITLE
Error when hidding tab panel using v-if

### ISSUE THREAD

**Issue by rafaeljosem** [primefaces/primevue#1186]
Hello, in issue #1184 I proposed adding a prop for hidding a tab pane but I was told that it might work by using v-if on the tab pane. Nonetheless, when I do this I get the following error: Uncaught (in promise) TypeError: child.children.forEach is not a function.

Don't know if it's a bug or it's not supported yet. If there's a workaround I'd love to hear it.

I'm using prime vue 3.3.5.

Thanks.

**Comment by Anubarak** [comment]
Same goes for all other "Components" that don't really "use" their Child Components but rather their raw `vNodes` as placeholders https://github.com/primefaces/primevue/issues/1113

**Comment by Anubarak** [comment]
As a temp fix you could change
tabview.esm.js
from
```JS
tabs() {
    const tabs = [];
    this.$slots.default().forEach(child => {
            if (this.isTabPanel(child)) {
                tabs.push(child);
            }
            else if (child.children.length > 0) {
                   child.children.forEach(nestedChild => {
                    if (this.isTabPanel(nestedChild)) {
                        tabs.push(nestedChild);
                    }
                });
            }
        }
    );
    return tabs;
},
```

to
```JS
tabs() {
    const tabs = [];
    this.$slots.default().forEach(child => {
            if (this.isTabPanel(child)) {
                tabs.push(child);
            }
            else if (child.children.length > 0) {
               // check fo children first before looping them
                if(!child.children || !Array.isArray(child.children)){
                    return;
                }

                child.children.forEach(nestedChild => {
                    if (this.isTabPanel(nestedChild)) {
                        tabs.push(nestedChild);
                    }
                });
            }
        }
    );
    return tabs;
},
```

This will allow you to use comments as well. Currently writing comments in their components will result in an error.
```vue
<TabView>
 <!-- place your comment -->
</TabView>
```

**Comment by rafaeljosem** [comment]
Thanks! I'll give it a try.

**Comment by mertsincan** [comment]
Thanks a lot for your report!

Best Regards,
