### ISSUE TITLE
DataTable : Selection multiple with filter didn't appear in good place

### ISSUE THREAD

**Issue by Zaaaoo** [primefaces/primevue#1193]
The checkbox must change location 
![image](https://user-images.githubusercontent.com/70746510/115239599-362e6380-a11f-11eb-99b0-7d22cbde7b2c.png)

![image](https://user-images.githubusercontent.com/70746510/115239660-45adac80-a11f-11eb-905b-cf66d72a3b0b.png)

Could the box be moved in the same place ?

[https://codesandbox.io/s/jolly-gauss-88kny?fontsize=14&hidenavigation=1&theme=dark&file=/src/DataTableSelectionDemo.vue](url)

**Comment by Zaaaoo** [comment]
Example in my app with a boolean v-if on filters template
![image](https://user-images.githubusercontent.com/70746510/115240416-05026300-a120-11eb-8243-bfb938e4ac99.png)
![image](https://user-images.githubusercontent.com/70746510/115240503-177c9c80-a120-11eb-9d9b-1b6cfc929e17.png)

**Comment by tugcekucukoglu** [comment]
While using filterDisplay: 'row', it is expected behaviour. It seems like you need to decide whether to use filterDisplay: 'row' in your case. Please check [https://codesandbox.io/s/dt-filterdisplay-6r2j0](https://codesandbox.io/s/dt-filterdisplay-6r2j0)

**Comment by Zaaaoo** [comment]
Precisely, I do not understand the interest of having placed the checkbox in this place when we are in filterRow.

The checkbox is not a filter criterion.
