### ISSUE TITLE
DataTable column filter with overlay e.g. "calendar" closes immediately

### ISSUE THREAD

**Issue by ahmedkandel** [primefaces/primevue#1194]
Hi,

When using the Date filter in DataTable the calendar overlay closes immediately after clicking the date input field. It depends on the screen size if the overlay covers the input field there is an issue but if the overlay is shown before o after the field there is no issue.

![illustative gif](https://user-images.githubusercontent.com/28398523/115257311-41d65600-a130-11eb-819d-e7f597679a1f.gif)

**Comment by ahmedkandel** [comment]
I've tracked this issue and found that when the calendar component is shown above the input field the click event target will be <body> instead of the input field, So the overlay gets closed as if it was a click outside of the overlay. I will create a PR to fix this by changing the click event in `ColumnFilter` component that will fire `onContentClick` from click to mouse down.

**Comment by cagataycivici** [comment]
Works with 3.4.0;

https://primefaces.org/primevue/showcase/#/datatable/filter

**Comment by ahmedkandel** [comment]
@cagataycivici No it doesn't work with 3.4.0 the screenshots are from 3.4.0, please minimize the browser window until the calendar overlay comes over the filter overlay e.g. 1200px width and 500px height.

**Comment by lavoscore** [comment]
I can confirm this happens in 3.5.0. It's breaking a few of our Cypress tests.

**Comment by csworthington** [comment]
It's also causing issues for me in one of my applications. The behaviour seems to be present in Chrome and Edge, but not in Firefox. You can see the bug in [this code sandbox](https://s7z1c.csb.app/) by setting the height of the viewport to any value less than ~700px.
