### ISSUE TITLE
Drop down not populating correctly

### ISSUE THREAD

**Issue by devilwacause** [primefaces/primevue#1198]
https://codesandbox.io/s/morning-sea-uhngg?file=/index.html

Recreated

#1188

**Comment by tugcekucukoglu** [comment]
In the browser props should be kebab-case and tags should be used with closing tag. 

Working example: [https://codesandbox.io/s/unpkg-v2-dropdown-dv404](https://codesandbox.io/s/unpkg-v2-dropdown-dv404)
