### ISSUE TITLE
Modify calendar datepicker title

### ISSUE THREAD

**Issue by janicechan0318** [primefaces/primevue#1200]
Is there anyway we can modify the date-picker title of the calendar? 

For example instead of showing 
April 2021

how can I change it to 
Apr 21

![image](https://user-images.githubusercontent.com/49790100/115529236-513ad800-a2c5-11eb-801d-95d5d53bb130.png)

Thank you.

**Comment by tugcekucukoglu** [comment]
You can use Locale API like this
`this.$primevue.config.locale.monthNames = this.$primevue.config.locale.monthNamesShort;` 
and also customize year your own.
