### ISSUE TITLE
Calendar error in primevue 2.3+

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue#1215]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at codesandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/vue-typescript-example-forked-o05zt?file=/src/components/HelloWorld.vue

**Current behavior**
Clicking the component does not show the calendar to pick a date. Console is showing error "TypeError: Cannot read property 'config' of undefined"

**Expected behavior**
Calendar works like in the demo's.

* **Vue version:** 2.6.12

* **PrimeVue version:** 2.4.1

* **Browser:** 
All

**Comment by dheimoz** [comment]
Hi @Jogai I wonder if you setup the locale of your project.
https://www.primefaces.org/primevue/showcase-v2/#/locale

Calendar uses the config information to present the calendar and other several components.

Please confirm.

Thanks.

**Comment by Jogai** [comment]
Thanks a lot, that was it.

**Comment by dheimoz** [comment]
Glad you sort it out @Jogai 
Cheers.

**Comment by dcruz1990** [comment]
I'm having similar issue, but in my case i can't access primevue config from component. I follow instructions from the docs, but i only have access to locales but in read only mode. I'm using typescript. 
This is the error `TS2339: Property 'config' does not exist on type 'PrimeVueConfiguration'.`
