### ISSUE TITLE
Missing documentation for menu separator

### ISSUE THREAD

**Issue by willie68** [primefaces/primevue#1217]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```
**What is the motivation / use case for changing the behavior?**
Just missing a documentation how to add a separator into a menu

**Please tell us about your environment:**
not needed 

When you dig thru the source you will see, that simply 

```
        {
          separator: true,
        },

```
as a menuitem will do the trick. But it's nowhere documented. Should be very easy to document and helpful.

**Comment by willie68** [comment]
Great, thanks.

**Comment by notflip** [comment]
@willie68 Do we need to style this separator ourselves? When I add it to my items, it's added to the css but it has no width.
