### ISSUE TITLE
How Can I change color of Datatable row   when hover 

### ISSUE THREAD

**Issue by yvzkr** [primefaces/primevue#1218]
The Datatable components has a hover skill. I guess I can change color.  I use this.

![image](https://user-images.githubusercontent.com/18627973/116379926-2a782680-a81c-11eb-916d-f2d3deea98d6.png)

but ı dont want this. I want send class with paramether.  How Can I. ??

**Comment by tugcekucukoglu** [comment]
It's not an issue. Please use forum for support request.
