### ISSUE TITLE
DataTable / unselect the selected row doesn't work in single selection mode

### ISSUE THREAD

**Issue by regisaih** [primefaces/primevue#1219]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at codesandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://www.primefaces.org/primevue/showcase/#/datatable/selection

https://codesandbox.io/s/primevue-issue-template-forked-vgbzf

**Current behavior**

Selecting a row works as expected. But selecting that row again, the row is not unselected.

**Expected behavior**

Selecting the selected row should unselect the row.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Ubuntu 20.4

* **Vue version:** 3.X

https://www.primefaces.org/primevue/showcase/#/datatable/selection

* **PrimeVue version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome browser version 90.0.4430.93

**Comment by cagataycivici** [comment]
There are two solutions;

- Press metaKey when clicking a selected row
- Set metaKeySelection to false to use mouse only selection

**Comment by perexwi** [comment]
I have a similar situation to that of the ticket, so here I provide my solution.

In my case I need to use checkboxes, but I only want to activate one of them or none, apart from that I obviously don't want to have the checkbox in the header to select all the elements and I don't want to use the mouse selection.

So here is my alternative:

```vue
<script setup lang="ts">
// imports....

interface IProduct {
    id: string
    code: string
    name: string
    category: string
    quantity: number
}

// I use this to change between modes
const oneItemSelectionMode = ref(true)

const products: Ref<Array<IProduct>> = ref() // all items
// We need to use an array because the selectionMode "multiple" expects an
// iterable, so we manage only the first item
const selectedProducts: Ref<Array<IProduct>> = ref()

// Here we can control to select only one item at a time
const onRowSelect = (event) => {
    if (oneItemSelectionMode.value && selectedProducts.value.length > 0 && event.data.id !== selectedProducts.value[0].id) {
        selectedProducts.value = [event.data]
    }
}

</script>

<template>
    <div class="card">
        <DataTable v-model:selection="selectedProducts" :value="products" :metaKeySelection="false" @row-select="onRowSelect" dataKey="id" tableStyle="min-width: 50rem"
        :pt="{
            column: {
                headerCheckbox: { // hide and disable the select all checkbox
                    root: {class: oneItemSelectionMode ? 'd-none' : ''},
                    input: {disabled: oneItemSelectionMode},
                },
            }
        }">
            <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
            <Column field="id" header="Id"></Column>
            <Column field="code" header="Code"></Column>
            <Column field="name" header="Name"></Column>
            <Column field="category" header="Category"></Column>
            <Column field="quantity" header="Quantity"></Column>
        </DataTable>
    </div>
</template>
``` 

:wink:
