### ISSUE TITLE
Divider does not display in vue3

### ISSUE THREAD

**Issue by mrVeganProgrammerGuyDude** [primefaces/primevue#1220]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting

```
I have been able to reproduce the problem by starting a blank Vue 3 project and running "import Divider from 'primevue/divider';" and loading the component locally (I tried globally too).
![image](https://user-images.githubusercontent.com/68789633/116540331-04a05f80-a8b8-11eb-9ae9-3f981f08b89f.png)

![image](https://user-images.githubusercontent.com/68789633/116540351-09fdaa00-a8b8-11eb-9a9a-dd76034d8f6a.png)

**Current behavior**

The divider line does not show, but I can get text and icons to show.

**Expected behavior**

I expect to see the divider line

**Minimal reproduction of the problem with instructions**

To reproduce the problem I started a fresh Vue3 project and imported the divider after installing Primevue for Vue 3.

**Please tell us about your environment:**

Windows 10, npm, Visual Studio Code, Chrome

* **Vue version:** 3.X

* **PrimeVue version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I can't see the divider on Chrome or Firefox or Edge

Again I'm very sorry I don't have the codepen. I will use it as soon as I am able to figure out how to get it running. But When I follow the link you gave it did not load and I was unable to make it load.

**Comment by tugcekucukoglu** [comment]
Please import theme css firstly, after that import components. Like this

`
import "primevue/resources/themes/saga-blue/theme.css";
import "primevue/resources/primevue.min.css";

import Divider from 'primevue/divider';
`

**Comment by mrVeganProgrammerGuyDude** [comment]
THANK YOU!!!!!!

works perfectly
