### ISSUE TITLE
Steps component does not support named routes

### ISSUE THREAD

**Issue by codenomnom** [primefaces/primevue#1222]
**I'm submitting a possible bug report** (excuse me if that's intentional and it's a feature request)
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Currently, the `Steps` component does **not** support named routes, because of how it marks the active step:
```javascript
isActive(item) {
    return this.activeRoute === item.to || this.activeRoute === item.to + '/' ;
},
```
https://github.com/primefaces/primevue/blob/master/src/components/steps/Steps.vue#L59

**Expected behavior**
I'd expect it to correctly mark routes as active even if I provide named ones:
```javascript
steps = [{ label: 'Dashboard', to: { name: 'dashboard' } }];
```

**What is the motivation / use case for changing the behavior?**
Currently you need to duplicate your (possibly complex) routes in your router, as well as in your steps configuration. This is extremely **painful** when working with props:
```javascript
{ to: `/app/campaigns/${campaignID}/edit/${sectionID}/` }
```

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primevue/issues/594
