### ISSUE TITLE
Switch component misbehaving inside TabView/TabPanel

### ISSUE THREAD

**Issue by psuplat** [primefaces/primevue#1223]
Not sure if this is a bug or just me missing something.

Vue version: 2.6.11
PrimeVue version: 2.4.1

The switches are not working as expected inside a TabView. Take this setup:
```
<TabView>
    <TabPanel header="Tab1">
        <InputSwitch v-model="sw1" />
    </TabPanel>
    <TabPanel header="Tab2">
	<InputSwitch v-model="sw2" />
    </TabPanel>
    <TabPanel header="Tab3">
	<InputSwitch v-model="sw3" />
    </TabPanel>
</TabView>
```

```
data() {
    return {
        sw1: false,
        sw2: false,
        sw3: false
    }
}
```

For example in I toggle the switch inside Tab1, I can see in the vue dev tools that the value of `sw1` has been changed to true. However the switch stays in it's original "off" mode. Only when I move to any of the other tabs, and then back to Tab1, is the switch component correctly represented. Exactly the same way happens other way around, when toggling off the switch, `sw1` gets modified to false, but the switch stays "on" until I change tabs.

Am I missing something here?

**Comment by sid-6581** [comment]
We are seeing the same thing. Seems that 2.4.1 is broken in several areas (including this), and reverting to 2.3.0 fixed the problem for now. Hopefully this can be addressed. I've seen a number of bug reports related to this, but no response.

**Comment by tugcekucukoglu** [comment]
Duplicate [#1209 ](https://github.com/primefaces/primevue/issues/1209)
