### ISSUE TITLE
InputMask focus behaviour

### ISSUE THREAD

**Issue by blowsie** [primefaces/primevue#1225]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Plunkr Case (Bug Reports)**
https://codesandbox.io/s/green-lake-lgn7g?file=/src/InputMaskDemo.vue

**Current behavior**
 I'm using input mask, and if you click in an empty input, it places the cursor at the start, if you, however, move the mouse 1px to the right whilst clicking, its puts the cursor to the end, which is strange behaviour for an empty input

**Expected behavior**
to have a way to not be able to select the end of an empty input

**Minimal reproduction of the problem with instructions**
as above

**What is the motivation / use case for changing the behavior?**
unwanted behaviour

**Please tell us about your environment:**

* **Vue version:** 3.0.6

* **PrimeVue version:** 3.4.0

* **Browser:** all

**Comment by Irelynx** [comment]
I have the same issue.
Temporary fixed it with added `focus` event:

```vue
<InputMask
  mask="+9 (999) 999-99-99"
  @focus="inputMaskFix"
/>

...
<script>

import InputMask from "primevue/inputmask";

export default {
  name: "test",
  components: {
    InputMask,
  },
  methods: {
    inputMaskFix(event) {
      event.target.value = (event.target.value || "") + " ";
    },
  },
}
</script>
```

**Comment by tugcekucukoglu** [comment]
Please try to use the latest PrimeVue v3.18.0.

Thanks,
