### ISSUE TITLE
DataTable Crud Example doesn't demonstrate Update

### ISSUE THREAD

**Issue by tk1** [primefaces/primevue#1226]
It would be nice, if the DataTable Crud example also would demonstrate the case of updating an existing row using a Dialog like the New-Dialog.

**Comment by tugcekucukoglu** [comment]
This is not a valid issue ticket. Could you please attach a codesandbox link for us to replicate?

**Comment by tk1** [comment]
I'm sorry. I misunderstood the example.

It's ok for me now.
