### ISSUE TITLE
Calendar / first day of the week

### ISSUE THREAD

**Issue by regisaih** [primefaces/primevue#1228]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at codesandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://www.primefaces.org/primevue/showcase/#/calendar
https://codesandbox.io/s/primevue-issue-template-forked-vgbzf

**Current behavior**

Calendar component shows Sunday as first day of the week.

**Expected behavior**

User should be able to set the first day.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Monday is the first day of the week according to the international standard ISO 8601.
https://www.timeanddate.com/calendar/days/monday.html

**Please tell us about your environment:**

Ubuntu 20.4

* **Vue version:** 3.X

3.0.5

* **PrimeVue version:** 5.X

3.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 90.0.4430.93

**Comment by cagataycivici** [comment]
See;

https://primefaces.org/primevue/showcase/#/locale
