### ISSUE TITLE
FloatLabel going too high and out of the box into space

### ISSUE THREAD

**Issue by mrVeganProgrammerGuyDude** [primefaces/primevue#1229]
**I'm submitting a ...**  (check one with "x")

[ x] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
When I click in the InputText the label floats too high and goes out of the box:
![image](https://user-images.githubusercontent.com/68789633/116765273-58af5f00-a9f2-11eb-8d91-edd21fad0c3f.png)

![image](https://user-images.githubusercontent.com/68789633/116765279-5f3dd680-a9f2-11eb-9469-ce80fca8daba.png)

**Expected behavior**
I expected the label to stay on the border of the box like in the docs:
![image](https://user-images.githubusercontent.com/68789633/116765310-74b30080-a9f2-11eb-9c7a-10d3a567daf4.png)

**Minimal reproduction of the problem with instructions**
I was able to reproduce the issue on a brand new vue project.

![image](https://user-images.githubusercontent.com/68789633/116765413-f2770c00-a9f2-11eb-8440-be525d42b22a.png)

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm

* **Vue version:** 3.X
vue 3

* **PrimeVue version:** 5.X
3.3.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all browsers

**Comment by cagataycivici** [comment]
You need to use material theme then. Float label styling depends on the theme used.
