### ISSUE TITLE
Menu / drop Vue-Router dependency

### ISSUE THREAD

**Issue by regisaih** [primefaces/primevue#1231]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at codesandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-forked-vgbzf

**Current behavior**

Menu component does not work if Vue-router is not installed

**Expected behavior**

Menu should not be dependent of Vue-router

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

There is increasing number of users who does not need client side routing. For example Inertiajs uses server side routing..
https://inertiajs.com/

**Please tell us about your environment:**

* **Vue version:** 3.X

* **PrimeVue version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by AARP41298** [comment]
Dont work with inertia?
The only issue that i have using Menu are the warnings "Failed to resolve component: router-link" in the console every time i click in the menu

But it works fine
Im using inertia installed by laravel --jetstream

**Comment by ahmedkandel** [comment]
@AARP41298 me too am using PrimeVue with Inertia. As a workaround chain the following method to `createApp` function in your app.js
```
createApp({
...
})
...
.component('router-link', {})
...
```

**Comment by cagataycivici** [comment]
Currently no plans to proceed, we'll reconsider if there is more demand. Thank you.

**Comment by craigrileyuk** [comment]
> Dont work with inertia?
> The only issue that i have using Menu are the warnings "Failed to resolve component: router-link" in the console every time i click in the menu

Warnings are bad and can lead to code failing a code review. It's not exactly difficult to remove a dependency or add a prop to the Menu component to deactivate the check.

**Comment by 3zzy** [comment]
Wild that router is a dependency for a simple menu component! 😞

**Comment by 3zzy** [comment]
Turns out its not just the Menu component but also the SplitButton component and possible others 🤯

**Comment by robingiraud** [comment]
I have exactly the same issue so I'm reopening this topic because it is blocking all projects using Inertia.
Several components, like Menu, MegaMenu, Dropdowns etc.. are affected.

The solution to "fake" the router-link component seems working, for some components but the MegaMenu is still broken.

Hope you will find a solution to avoid this dependency :)

**Comment by timyourivh** [comment]
Reporting in as to show there is demand for dropping this dependency.
Also using Inertia.js

**Comment by phillipfickl** [comment]
Same here, also using Inertia

**Comment by kitro** [comment]
I faced the same issue today using the Menu component.
```
Failed to resolve component: router-link
```

**Comment by twatwak** [comment]
+1 
using inertia. 
fake router-link component works but doubt its a good idea to do that.
