### ISSUE TITLE
Checkbox causes Chrome viewport to jump

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#1232]
[X ] bug report

I am experiencing an issue where a Checkbox component that is scrolled into view and clicked causes the whole viewport to jump/mis-align with no way of getting it back without refreshing. I have distilled this down to a minimal demo at the link below.

Reproduction:
[https://codesandbox.io/s/quirky-mclean-j81fs](https://codesandbox.io/s/quirky-mclean-j81fs)

Windows 10 x64
Vue: 3.0.6
PrimeVue: 3.4.0
Browser: Chrome/ Edge (not Firefox)

**Comment by tugcekucukoglu** [comment]
It's a buggy situation in Chrome that using height for html or body when container's height is smaller than contents height. It might need to customize the container's style a bit. In PrimeVue Checkbox component, input's container has style 
`position: absolute`
So in this codesandbox example adding position: relative could solve the strange jumping.

```
.root-layout {
  position: relative;
  ...
}```

If issue still persists, reopen this issue again.

**Comment by avenmore** [comment]
This worked in the simple reproduction, but not in my complex app. Thanks to your clue, I was able to set
```
.p-hidden-accessible {
    position: unset;
}
```
which solved it for me (don't know what other problems I may have created).
Thank you :)
