### ISSUE TITLE
InputSwitch change event target is a div and no input

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#1235]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at codesandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-forked-vgbzf

**Current behavior**

The `currentTarget` of your `@change` callback is a `div` and not the `input` element. I would rate this one as a bug because it's obvious the target should be the input in order to call `$event.target.checked` or something like that.

**Expected behavior**

`$event.currentTarget` should be the `input`

**Minimal reproduction of the problem with instructions**

An example similar to your Code Sandbox is [here](https://codesandbox.io/s/primevue-issue-template-forked-62cxv)

**What is the motivation / use case for changing the behavior?**

The use case is when you want to get the current state of the value without using v-model like it's common in Vue.

**Please tell us about your environment:**

Does not matter

* **Vue version:** 3.0,12

* **PrimeVue version:** 3.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by cagataycivici** [comment]
I think this applies to all form components, we send the root element as the event target in most cases. I'd suggest using **@update:modelValue** where you get the new value as the parameter instead.

```html
<InputSwitch v-model="val" @update:modelValue="onChange($event)" /> 
```

$event is true or false
