### ISSUE TITLE
DataTable: Declaring a Tooltip for Column Header

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1238]
I'd like to have the option, to declare a tooltip for the header of a DataTable Column.
For example a new Column-property **headerTooltip**:
`<Column field="name" header="name" headerTooltip="This is the item's name" sortable style="min-width: 14rem">`

**Comment by dheimoz** [comment]
Hello @ibrdavid 

Have you tried using the tooltip component
https://www.primefaces.org/primevue/showcase/#/tooltip

And templating
https://www.primefaces.org/primevue/showcase/#/datatable/templating

**Comment by ibrdavid** [comment]
Thanks for your advice. I didn't realize, that there is a column slot for the header. Problem solved!
