### ISSUE TITLE
Add selectionLimit to MultiSelect

### ISSUE THREAD

**Issue by redfox05** [primefaces/primevue#1239]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Feature request:**
In the [`<Multiselect>` Vue component](https://primefaces.org/primevue/showcase/#/multiselect), it would be useful to be able to set a max number of selections per group. The groups aspect is already implemented so if this could be combined with a maximum per group, it opens it up to a lot of different possibilities.

My use case would be to be able to select 1 option from one group, and then have a second group with only 1 item, thus it means you can have a combination of any of the first, together with a toggle flag (the single option from the second group).

**Examples:**
Group1Option1 + [ empty ]
Group1Option1 + Group2Option1
Group1Option2 + Group2Option1
Group1Option3 + Group2Option1
Group1Option2 + [ empty ]

A similar request was implemented for the other libraries:
- In PrimeNg here: primefaces/primeng#4614
- And in PrimeReact here: primefaces/primereact/issues/1815

Would be great if this configurability can be added to PrimeVue as well.

**Comment by danny007in** [comment]
any solution
