### ISSUE TITLE
Calendar date-only sets time to local zero not UTC zero

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#1240]
When using the Calendar component to pick a date only, it sets the time to zero local time. 
e.g. Thu Aug 06 2020 00:00:00 GMT+0200

It is common to decode/store dates at offset zero, so this date is now stored as
Wed Aug 05 2020 22:00:00 GMT+0000

So if I wanted to know your birthday, if I take the date part of what's stored, the date is wrong - not what I set it to. It is necessary to convert this back to the original time zone to be sure of the date, but how do you know what that is?

Expected behavior:
Dates selected that have no time part should have the time set to zero GMT+0000.

**Comment by cagataycivici** [comment]
Calendar does not handle timezones, it always provided local dates and the processing is left to the user. In the past for PrimeNG, we had UTC built-in but it got very complex so none of the Calendars of Prime deal with timezones. You can just listen to bind event like update:modelValue and process it on your side and send back to backend. Similar case with displaying it. So timezone conversions are not done by the calendar and no plans to change it. Thank you.

**Comment by nemanjakmno** [comment]
Is this still like this? I just want to get value that i set on ui and i see not something that is changed in background somehow after submit

**Comment by iport-snk** [comment]
const date = ref(new Date())
