### ISSUE TITLE
ConfirmPopup's position won't change when button switched

### ISSUE THREAD

**Issue by Enoooch** [primefaces/primevue#1242]
**I'm submitting a bug report**

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primevue/showcase/#/confirmpopup

**Current behavior**
ConfirmPopup's position won't change when button switched.

**Expected behavior**
ConfirmPopup will change position when button switched.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Mac, VS Code, Yarn

* **Vue version:** 3.0.5

* **PrimeVue version:** 3.4.0

* **Browser:** [all]

**Comment by cagataycivici** [comment]
Issue is not clear, please create a new ticket with our codesandbox template fork so that we can work on it again. Thank you.
