### ISSUE TITLE
Multiselect doesn't set focus to the multiselect filter when dropdown is expanded

### ISSUE THREAD

**Issue by juanparati** [primefaces/primevue#1243]
```
[X] bug report
```

The input filter from the Multiselect do not get automatically the focus when the dropdown is expanded. This behavior is in inconsistent if we compare it with the Dropdown component with filter.

I can reproduce this issue with Vue 2.4.1.

**Current behavior**
The dropdown is expanded but the filter do not get the focus.

**Expected behavior**
The dropdown is expanded an the input filter get automatically the focus (See Dropdown component with filter).

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/mystifying-kirch-15inx

* **Vue version:**
2.x

* **Browser:** 
all

**Comment by juanparati** [comment]
I observed that "focusInput" is assigned to the wrong input element.

**Comment by cagataycivici** [comment]
V3 works so retargeting to V2.
