### ISSUE TITLE
Dropdown search by typing non-latin letters not working

### ISSUE THREAD

**Issue by alqa-dash** [primefaces/primevue#1253]
Hello,
In PriveVue 3.4.0 search item in dropdown element is very useful but it works only with latin letters (english in my case). If dropdown options are in cyrillic (e.g. Russian), search by typing does not work.

**Comment by cagataycivici** [comment]
Please use filterLocale for this.

**Comment by alqa-dash** [comment]
What about multilanguage support?

**Comment by dheimoz** [comment]
Hello @alqa-dash , @cagataycivici was talking about this:

https://www.primefaces.org/primevue/showcase/#/locale

Should you need support or share ideas for this kind of scenarios, join PrimeLand Discord community:
https://discord.gg/gzKFYnpmCY

**Comment by alqa-dash** [comment]
Hi, 

No, I mean searching for options in Dropdown by typing different languages (English or Russian). filterLocale option is string but not an array. I didn't check it but doubt that array is supported for this option in PrimeVue.
