### ISSUE TITLE
row-hover-on and row-hover-off events for DataTable

### ISSUE THREAD

**Issue by kibertoad** [primefaces/primevue#1254]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
```

**Current behavior**
There are no events fired when row is being hovered over or hover disappears.

**Expected behavior**
It would be helpful to have events `row-hover-on` and `row-hover-off` fired to be able to react to user mouse hover.

**What is the motivation / use case for changing the behavior?**
Some scenarios, such as being able to show/hide action buttons inside a column, based on user hover would benefit greatly from such functionality.

**Comment by cagataycivici** [comment]
I'm worried about performance implications, so we're unlikely to proceed if there is more user demand. Thank you for your understanding. I think you can still CSS hover to show hide content.

**Comment by kibertoad** [comment]
@cagataycivici Kinda, but it made us use an ugly hack like this: 
```
  function getIconHover() {
    const tableRows = document.querySelectorAll('.p-selectable-row')
    tableRows.forEach((tableRow) => {
      const buttonBar = tableRow.querySelector('.icon-btn')
      tableRow.addEventListener('mouseover', (e) => {
        buttonBar!.classList.remove('icon-btn')
      })
      tableRow.addEventListener('mouseleave', (e) => {
        buttonBar!.classList.add('icon-btn')
      })
    })
  }
```

Is there a nicer way to access children elements of PrimeVue components?

**Comment by RastogiNishant** [comment]
It would be great if we can have some hovering row events :)

**Comment by AurumTheEnd** [comment]
I support this change.

**Comment by Janash37** [comment]
+1 for this, it would be extremely useful to be able to provide our users with some visual feedback to say that they can click, without having to resort to length go-arounds

**Comment by theunsa** [comment]
+1 for exactly the same motivation/use case of @kibertoad

**Comment by cdumarcey** [comment]
+1 vote for exactly the same motivation/use case of @kibertoad

**Comment by sunhour001** [comment]
+1 vote for exactly the same motivation/use case of @kibertoad

**Comment by CustomEntity** [comment]
+1 vote for exactly the same motivation/use case of @kibertoad

**Comment by henrynguyen7** [comment]
+1 vote for exactly the same motivation/use case of @kibertoad

**Comment by JamesStandbridge** [comment]
+1

**Comment by lecorreyann** [comment]
+1

**Comment by trulyVolodymyr** [comment]
+1 vote for exactly the same motivation/use case of @kibertoad

**Comment by gerardmrk** [comment]
+1 Kind sirs
