### ISSUE TITLE
[Feature request] NavMenu with HTML

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#1257]
[https://primefaces.org/primevue/showcase/#/menubar](https://primefaces.org/primevue/showcase/#/menubar)

```
<Menubar :model="items" />
```
I see that i can add an item to the menu only by "model"

Can you please add a feature that i can add items from the HTML like in:
[https://bootstrap-vue.org/docs/components/navbar](https://bootstrap-vue.org/docs/components/navbar)

I need to add some components to the toggle menu and can't do it.

This is not useful because it's not inside the toggle.
```
  <template #start>
        Before
    </template>
    <template #end>
        After
    </template>
```

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primevue/issues/1257
