### ISSUE TITLE
Dialog with submit button failed

### ISSUE THREAD

**Issue by alqa-dash** [primefaces/primevue#1264]
PrimeVue 3.4.0

If Dialog component contains form with button in slot (e.g. #footer) and one has to set type to button (like type="submit") to submit form build returns error:

```
Syntax Error: Thread Loader (Worker 0)
Cannot read property 'type' of undefined
```

**Comment by alqa-dash** [comment]
Found solution by myself.

**Comment by dheimoz** [comment]
hey @alqa-dash do you sharing your solutions in case the community faces a similar problem?
Thanks.

**Comment by alqa-dash** [comment]
Pretty straightforward solution and if I wouldn't so stupid I'd never created this issue.

Looks like it is impossible to use 'type="submit"' at all. One should use @click instead.

So template should look like:

```
<Dialog>
<form>
...
</form>
<template #footer>
<Button @click="sendForm"/>
</template>
</Dialog>
```

**Comment by dheimoz** [comment]
Thanks for sharing. The problem you experienced was not related to Primevue or Vue at all, is how HTML works. Should you need to use a submit type button outside the Form tag, you need to specify that form:

https://www.w3schools.com/Tags/att_button_form.asp
