### ISSUE TITLE
Add lazy option to TabView and Accordion

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#1268]
All tabs are rendered when mounted and inactive tabs are hidden with CSS. Enabling **lazy** option activates the dynamic mode where a tab is only rendered at DOM when it is active. This option is useful to speed up the initial rendering performance if there are many tabs

**Comment by Shadercloud** [comment]
I think the lazy setting should only mount tab contents once, so after a user visits a tab it then gets mounted, if they move to another tab it should hide the tab with css (default behavior) and not unmount it.

For example if each tabs makes API calls when mounted, there is no sense making those API calls again and again every time the user changes tabs.  It would be better to work something like this:

```vue3
<script setup>
const tabs = ["Basic", "Pages"];
const activeTab = ref("Basic");

const visited = ref([activeTab.value])

watch(activeTab, (newTab) => {
    visited.value = [...visited.value.filter(v => v !== newTab), newTab]
});

</script>
<template>
<Tabs v-model:value="activeTab">
            <TabList>
                <Tab v-for="tab in tabs" :key="tab" :value="tab">
                    {{ tab }}
                </Tab>
            </TabList>
            <TabPanels>
                <TabPanel value="Basic">
                    <StoreSettings v-if="visited.includes('Basic')" />
                </TabPanel>
                <TabPanel value="Pages">
                    <Pages v-if="visited.includes('Pages')" />
                </TabPanel>
            </TabPanels>
        </Tabs>
</template>
```
