### ISSUE TITLE
ScrollPanel option for autoscroll to end

### ISSUE THREAD

**Issue by leolivier** [primefaces/primevue#1271]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**What is the motivation / use case for changing the behavior?**
I'm using a ScrollPanel as a Log viewer: it contains a div to  which new log lines are appended every x seconds and I want to automatically scroll to the end of the text to always see the last lines.
Can't find how to do this even after looking at the code of the ScrollPanel : shouldn't it be added ?

* **Vue version:** 3.0.11

* **PrimeVue version:** 3.5.0
(latest version)

* **Browser:**not related to browsers

**Comment by leolivier** [comment]
Linked to #1270

**Comment by cagataycivici** [comment]
Tracked at 1270, thanks.

**Comment by AnilkrishnaD** [comment]
Can u please tell me how to set auto scrool to end in scrool pannel

**Comment by robinwu2008** [comment]
Can u please tell me how to set auto scrool to end in scrool pannel
