### ISSUE TITLE
ProgressBar does not show zero percent

### ISSUE THREAD

**Issue by JoseGoncalves** [primefaces/primevue#1272]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When `showValue` prop is set to `true` and `value` is equal to `0` the percentage data is not shown.

**Expected behavior**
I would expect the ProgressBar to present `0%`.

* **Vue version:** 3.0.11

* **PrimeVue version:** 3.5.0

* **Browser:** [Chromium 91 | Firefox 88]

**Comment by tugcekucukoglu** [comment]
Thanks for your contribution. It is manually fixed. There is no need to add extra computed prop.

**Comment by hagabaka** [comment]
This is broken again in [3.12.5](https://github.com/primefaces/primevue/commit/fb7b2b24cc6747a8d6e74989299626a7e5c2ef71#diff-e40752689771020ea1d5b3b63d5314a649830fe7adf3f91df20e031c909b729fR4), which makes the label only render if `(value != null && value !== 0) && showValue`.

**Comment by ataylor32** [comment]
@tugcekucukoglu Would you be willing to reopen this issue? It's still present and it's a real usability issue. Imagine if a user is uploading quite a large file such as a video. They may go for several seconds without any indication that the upload is working, thus causing confusion. This is especially true if the user's Internet connection is slow.
