### ISSUE TITLE
DataTable slotProps.index mismatch

### ISSUE THREAD

**Issue by Enoooch** [primefaces/primevue#1274]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
slotProps.index return same value.

**Expected behavior**
slotProps.index return each index.

* **Vue version:** 3.1.0-beta.2

* **PrimeVue version:** 3.5.0

* **Browser:** [all]

**Comment by nndnha** [comment]
Codesandbox link: https://codesandbox.io/s/sleepy-tesla-9tmbx?file=/src/DataTableBasicDemo.vue
