### ISSUE TITLE
[Bug report]: Input components malfunction inside TabView/TabPanel  in PrimeVue 2.4.x 

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#1276]
The following code snippet works perfectly in PrimeVue 2.2.0, but works abnormally in PrimeVue 2.4.x. 

The problem in 2.4.x is that the input components inside TabView/TabPanel cannot receive keyboard input correctly, e.g. receive only one character when two characters are input. 

Input components outside TabView/TabPanel always work properly.
 
```
<template>
	<div>
		<InputText v-model="test1" />
		<br>
		<Textarea v-model="test2" rows="4" cols="22" />

		<TabView>
			<TabPanel header="Test">
				<InputText v-model="test3" />
				<br>
				<Textarea v-model="test4" rows="4" cols="22" />
			</TabPanel>
		</TabView>
	</div>
</template>

<script>
export default {
    data() {
        return {
			test1: null,
			test2: null,
			test3: null,
			test4: null
        }
	}
}
</script>
```

**Comment by tugcekucukoglu** [comment]
Duplicate [#1209 ](https://github.com/primefaces/primevue/issues/1209)
