### ISSUE TITLE
[Feature Request] Theme Switcher/Handler

### ISSUE THREAD

**Issue by KotkaZ** [primefaces/primevue#1290]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Currently, as a frontend developer, I have to use external dependencies to implement a proper theme switcher. (dark mode eg.)
Most of the implementations are not well fitted for importing CSS from node_modules, therefore in some cases, the implementation is even more complicated.

**Expected behavior**
I expect a simple component or element, which if handle the webpage theming according to developer needs and vision. There was a similar feature in PrimeFaces for Java: https://www.primefaces.org/showcase/ui/misc/themeSwitcher.xhtml
I am not sure, why this is not supported anymore. It would be an amazing feature to have.

**What is the motivation / use case for changing the behavior?**
Primefaces have amazing stylesheets and visual editor for any kind. Nowadays many sites have options to configure theming or at least turn on supported dark mode.
TheameSwitcher would simplify the implementation of the dark mode switch and loses the need for external dependencies. 

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

**Comment by tugcekucukoglu** [comment]
It is a deprecated component in PrimeFaces. There are no plans to add it to another Prime libraries.

Thanks,
