### ISSUE TITLE
Datatable horizontal scroll reset when editing with multiple selection boxes enabled

### ISSUE THREAD

**Issue by melinashak-noaa** [primefaces/primevue#1292]
I'm submitting a Bug

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/tender-hill-01kf6?file=/src/App.vue

**Current behavior**
When I use selection boxes for the DataTable and set selectionMode = 'multiple', horizontal scroll gets messed up when editing. 
1) Horizontal scroll to navigate to a field I'd like to edit
2) Once at that field select a drop down to edit
3) When I make a selection from the dropdown list, the horizontal scroll snaps back and I have to scroll again to see whether my edit was made properly. It's quite annoying. 

**Expected behavior**
1) Horizontal scroll to the field I'd like to edit
2) Edit and the scroll bar stays in the same place and I'm able to view the change I made. 

**Minimal reproduction of the problem with instructions**
1) Create an editable datatable with selectionMode = 'multiple' 
2) Add a column <Column selectionMode="multiple" headerStyle="width: 3em"></Column>
3) Make one of the columns show a dropdown when in edit mode.
4) Use horizontal scroll to navigate to a field and use the dropdown to edit
5) Make a selection on the dropdown and now the horizontal scroll is reset
6) Navigate back to view if edit was made correctly. 

**What is the motivation / use case for changing the behavior?**
Improve user experience when editing a data table and multiple selection boxes mode is enabled. 

**Please tell us about your environment:**
OS: Windows 10
IDE: Visual Studio
Package Manager: lerna

* **Vue version:** 3.X
^2.6.12

* **PrimeVue version:** 3.4.X
^3.5.0

* **Browser:** 
* Chrome
* Firefox

**Comment by tugcekucukoglu** [comment]
Thanks for your report. I dive into your codesandbox sample. It has some errors so I created new one. In this [sample](https://codesandbox.io/s/dt-horizontal-scroll-fuk5c), I didn't replicate the issue. There is no horizontal scrolling when I make a selection on the dropdown.

**Comment by tugcekucukoglu** [comment]
Unable to replicate the issue. So it is closing.

**Comment by melinashak-noaa** [comment]
Hi I'm not able to get your example working, I'm just seeing an empty table. 
![image](https://user-images.githubusercontent.com/44685558/122101008-b217f580-cdc8-11eb-8eed-846635bdb322.png)

**Comment by tugcekucukoglu** [comment]
<img width="506" alt="Screen Shot 2021-06-15 at 21 11 59" src="https://user-images.githubusercontent.com/32294991/122102770-7740ac80-ce1e-11eb-91ea-a8cb7201cf84.png">

**Comment by melinashak-noaa** [comment]
got it, I see it now, cool I'll experiment with that thanks
