### ISSUE TITLE
Upload button disable on FileUpload

### ISSUE THREAD

**Issue by kaushik546** [primefaces/primevue#1294]
**Current behavior**
After uploading a file upload button is not enable for click.
![Screenshot_4](https://user-images.githubusercontent.com/11855976/119253770-9740cf80-bbd4-11eb-9768-6a8d45d2ea45.png)

* **Vue version:** 3.0.11

* **PrimeVue version:** 3.5.0

**Comment by Antal1609** [comment]
PrimeVue 3.2.4 has a working FileUpload
