### ISSUE TITLE
Datatable with Paginator: Select mutiple rows with shift

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1297]
I have a DataTable with Paginator und selectionMode 'multiple'. If I go to e.g. page 3 and try to select multiple rows with shift it doesn't work on page 3.
When I go to page 1 the selection is there! (not on page 3).

Version 2.4.1

**Comment by tugcekucukoglu** [comment]
It's fixed for PrimeVue 2.4.2. [17e2f1b ](https://github.com/primefaces/primevue/commit/3b15695c9582616bfdf83c948941180e1a99379a)

Thanks.
