### ISSUE TITLE
Template for AutoComplete multiple 'chips'

### ISSUE THREAD

**Issue by mrichar1** [primefaces/primevue#1302]
**I'm submitting a ...** 
```
[ x ] feature request 
```

Would it be possible to add the ability to define a custom template for the 'chips' in Autocomplete 'multiple' mode?

Looking at the code it appears almost identical to that used in `Chips`, which has this:

https://github.com/primefaces/primevue/blob/master/src/components/chips/Chips.vue#L5-L8

https://github.com/primefaces/primevue/blob/master/src/components/autocomplete/AutoComplete.vue#L6-L9

* **Vue version:** 3.0
* **PrimeVue version:** 3.5.0
* **Browser:** all

**Comment by tugcekucukoglu** [comment]
It is added manually. Thank you.
