### ISSUE TITLE
Cannot use some PrimeVue Component :  Failed to mount component template or render function not defined.

### ISSUE THREAD

**Issue by seballot** [primefaces/primevue#1303]
Dear prime team,

When loading some components, like Password, or ConfirmDialog, I got strange error
```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <PInputText>
       <Password> at node_modules/primevue/password/Password.vue
         <MyTestComponent> at ***/MyTestComponent.vue
           <Root>
```

But some other components works okay (InputText, DataTable...)

Here is my simple Vue component where I try to use Password component :

```html
<template>
  <Password></Password>
</template>

<script>
import Password from 'primevue/password';
export default {
  components: { Password },
}
</script>
```

I have initialized PrimeVue with following
```
import PrimeVue from 'primevue/config'
Vue.use(PrimeVue);
```
I'm using Vue 2.6.12 and PrimeVue 2.4.1

And as I said, the error is happening only on certain PrimeVue components...

This is very weird, and I don't think it comes from the Prime component itself, but maybe you will have an idea to help me?
Many thanks !

**Comment by seballot** [comment]
Oh actually, I just make it work by changing this line https://github.com/primefaces/primevue/blob/2.x/src/components/password/Password.vue#L23

`import InputText from '../inputtext/InputText';`
to
`import InputText from 'primevue/inputtext';`

I can see that in master the same change have been applied. But master is for Vue3 right?

**Comment by tugcekucukoglu** [comment]
Yes, master branch for Vue3. PrimeVue 2 and PrimeVue3 have different build. So 

`import InputText from '../inputtext/InputText';`

is okey. How can I reproduce the issue. I can't say much without a codesandbox template demonstrating the issue.

**Comment by seballot** [comment]
Yes I made a sandbox, but it's working there, so I guess it comes from by webpack config or so... closing it, sorry for inconvenience, but if you have any clue I'm listening :)

**Comment by seballot** [comment]
I could find the root cause, but found a workaround by using the common js module... in case anyone else have same issue :

use
`import Password from 'primevue/password/password.common';`
instead of
`import Password from 'primevue/password';`
