### ISSUE TITLE
Datatable in stack mode does not show the first row in the first line

### ISSUE THREAD

**Issue by reencafesas** [primefaces/primevue#1309]
Greetings, I have been reviewing the demo datatable in stack mode, and the first row in the first column always disappears when entering stack mode, this is a serious problem since it also occurs in production

![image](https://user-images.githubusercontent.com/83246587/120220158-efde2100-c201-11eb-9502-35824f8b78b6.png)

**Comment by tugcekucukoglu** [comment]
I didn't replicate it. First rows are displayed in showcase. But the border replacement is wrong. Tracked [#1312 ](https://github.com/primefaces/primevue/issues/1312)
