### ISSUE TITLE
DataTable State: columnwidths are not restored correctly when using scrollable and resizableColumns props

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1311]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/datatable-scrollable-resizable-widthrestorenotworking-szcps

**Current behavior**
I am using a DataTable with resizableColumns, vertical scrolling and state. In this case, you recommend using flex for defining inital column widths. But when the DateTable restores the state, the values for each column width is set as "width: 123px" instead of "flex: 0 0 123px", so the column keeps it's predefined width and doesn't get it's stored width from the state.

* **Vue version:** 3.0.11

* **PrimeVue version:** 3.5

**Comment by JohnCampionJr** [comment]
FWIW, I just tried this code locally and it does not solve the column resizing not being restored; might want to take another look.  
The updated column widths are being saved to storage, but they seem to be reset there prior to being loaded.

**Comment by tugcekucukoglu** [comment]
Unfortunately, I couldn't replicate it. Could you please attach a codesandbox link for us to replicate?

**Comment by JohnCampionJr** [comment]
As I said, it is still not working in 3.7.0.  See the codebox forked from the original issue.  It does not save/restore widths

https://codesandbox.io/s/datatable-scrollable-resizable-widthrestorenotworking-forked-b4i2z

**Comment by ibrdavid** [comment]
I updated my codesandbox example, using primevue 3.7.1 and vue 3.1.1 and it is still not working as expected. In my example i have one column with a predefined width of "flex: 0 0 80px" (due to fact this is a scrollable table). The restored width-value is set as width: 123px" instead of "flex: 0 0 123px". This leads to an style-definition of style="flex: 0 0 80px; width: 123px;", which in fact leads to the old predefined columnwidth of 80px and not the 123px, i want to be restored.

CodeSandbox Case (Bug Reports)
https://codesandbox.io/s/datatable-scrollable-resizable-widthrestorenotworking-szcps
