### ISSUE TITLE
Toast center positioning enhancement

### ISSUE THREAD

**Issue by stoneloxday** [primefaces/primevue#1315]
I'm submitting a:
```
[ x] bug report
```

**Current behavior**
https://codesandbox.io/s/competent-cerf-fzw5n
Currently toasts in different position aren't aligned to center equally.
Also they may not feet on mobile screen width.
Would be nice if fix would be available in next version, and backported in PrimeVue2.X branch if it isn't completely frozen.

**Expected behavior**
https://codesandbox.io/s/nostalgic-pond-zonqx
Possible solution, copy from sandbox index.css:
Except important, as they needed to overwrite default properties.

```
.p-toast {
  width: min(25rem, 100vw) !important;
}
.p-toast-top-center {
  top: 20px !important;
  left: 0 !important;
  right: 0 !important;
  margin: 0 auto 0 auto !important;
}
.p-toast-top-center {
  left: 0 !important;
  right: 0 !important;
  margin: 0 auto 0 auto !important;
}
.p-toast-bottom-center {
  left: 0 !important;
  right: 0 !important;
  bottom: 20px !important;
  margin: 0 auto 0 auto !important;
}
```
**Vue version:** 3.0.6

**PrimeVue version:** 3.5.0

**Browser:** [all]

**Comment by tugcekucukoglu** [comment]
Thanks for your contribution. It will ported PrimeVue 2 for next release. It is not frozen.
