### ISSUE TITLE
Tooltips closed on window resize after system keyboard appears on mobile devices 

### ISSUE THREAD

**Issue by Irelynx** [primefaces/primevue#1318]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/embed/compassionate-elbakyan-hz6r5?module=/src/App.vue

**Current behavior**
On a **real mobile device**, all tooltips (with and without `.focus`) are hiding by clicking on the field to which they are attached (because of system keyboard, that appears on screen and **resizes** the browser window, which leads to hiding of tooltips).

You can see the showcase of current behavior here: https://youtu.be/BXO5SdjP_mY (32 seconds video)

**Expected behavior**
Tooltip must not be closed completly on mobile devices.

**Minimal reproduction of the problem with instructions**
Create <InputText>, add tooltip to it, then open on **real mobile device**

**What is the motivation / use case for changing the behavior?**
In some Inputs/Buttons, for better user experience, it is nice to show some hints. Not only on Desktop, but on mobile devices too.

**Please tell us about your environment:**
* Windows
* VSCode
* npm
* HTTP server - run project via `npm run serve` (`vue-cli-service serve`)

* **Vue version:**
3.0.11

* **PrimeVue version:**
3.4.0

* **Browser:** 
All mobile browsers i think.
In my showcase (youtube showcase video mentioned above) i use Chrome/86.0.4240.114 on Android

---
Also, i want to link some **closed** related issues in PrimeVue:
* #523 (Tooltip doesn't close in scrollable containers)
* #500 (Improvement in behavior of components that have overlay panels in scrollable containers)

**Comment by Irelynx** [comment]
Showcase (same as on youtube)

https://user-images.githubusercontent.com/20732860/120820162-f6033300-c55c-11eb-8450-8f2a1089235a.mp4

**Comment by tugcekucukoglu** [comment]
Thanks for the great explanation. It's fixed for next version.
