### ISSUE TITLE
Missing `class` prop on Button component fails Typescript complier

### ISSUE THREAD

**Issue by vutran6853** [primefaces/primevue#1319]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
I am using Vue 3 with typescript. import a button and want to add class to change the color. Get ts complier fail.

sample code

This is from the doc link: https://primefaces.org/primevue/showcase/#/button

`<Button label="Submit" class="p-button-secondary" />`

error message:
`TS2322: Type '{ label: string; class: string; }' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
  Property 'class' does not exist on type 'IntrinsicAttributes & ButtonProps'.
`

**Expected behavior**

Complier pass and not crash the app. 
From source code of primevue interface ButtonProps is missing `class`  property?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by west-farmer** [comment]
Same issue in version 2.4.2 on unpkg.com, and influenced many components.

**Comment by tugcekucukoglu** [comment]
What is your exact test case and environment? I could not replicate it with [primevue-typescript-quickstart](https://github.com/primefaces/primevue-typescript-quickstart).

**Comment by vutran6853** [comment]
Thank for update on this issue.

FYI. For me, I am using Vue 3 with typescript using cli. 

Example code:
```jsx
import { defineComponent } from 'vue';
import Button from 'primevue/button'

export default defineComponent({
  name: 'App',
  render() {
    return (
      <div>
        <Button label="Submit" class="p-button-secondary" />
      </div>
    )
  }
})
```
