### ISSUE TITLE
slotProps.index is always 0 in DataTable's column body slot

### ISSUE THREAD

**Issue by mmitevski** [primefaces/primevue#1322]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

**Current behavior**
props.index is always 0

**Expected behavior**
props.index to hold the actual row index

**Minimal reproduction of the problem with instructions**
Just create a  DataTable (scrolling enabled) with the following column:
      <Column field="pos" header="№" bodyClass="right" style="flex: 0 0 3em">
        <template #body="props">
          {{props.index + 1 + '.'}}
        </template>
      </Column>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Vue version:** 3.X
Vue 3.0.11

* **PrimeVue version:** 3.4.X
3.5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, Safari

![image](https://user-images.githubusercontent.com/11592264/121062432-bee78880-c7cd-11eb-819b-336bbbdf81a0.png)

**Comment by tugcekucukoglu** [comment]
It is fixed for next release. Track at [#1274 ](https://github.com/primefaces/primevue/issues/1274)
