### ISSUE TITLE
Dynamic columns not showing in Datatable with vue 3.1.1

### ISSUE THREAD

**Issue by nclemeur** [primefaces/primevue#1323]
[X ] bug report
**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/fancy-leftpad-2txyl

**Current behavior**
The datable is created without any columns. The base structure of the table is created (table, thead, tbody and tr), but no column is shown.

**Expected behavior**
Would expect to see all columns

**Minimal reproduction of the problem with instructions**
Please see sandbox below (please note the package.json has been modified to update to vue.3.1.1

https://codesandbox.io/s/fancy-leftpad-2txyl

* **Vue version:** 3.11
* **PrimeVue version:** 3.5.0

* **Browser:** all

![image](https://user-images.githubusercontent.com/7132890/121134242-8485f600-c876-11eb-82e4-25ebcfe0f0e1.png)

**Comment by slumtrimpet** [comment]
> * **Vue version:** 3.11

The subject of the issues is correct, but that typo is unfortunately confusing.
This issue exists in **Vue 3.1.1** but reverting to 3.0.11 resolves for now.

**Comment by mitow7821** [comment]
Got the same issue with vue 3.0.7, but table works with the same vue version is working on my laravel based setup. 
There is no warning or error, data is declared correctly and it seems like Column doesn't accept header and field props

**Comment by jatinthapar1910** [comment]
Same issue with me with 3.1

**Comment by mitow7821** [comment]
I compared broken table with working one and found that DTTable components in DataTable are empty (working version on the left) 
![image](https://user-images.githubusercontent.com/34492112/121599997-23ac1880-ca44-11eb-9c22-fb137078eeab.png)

In sandbox provided by @nclemeur it looks the same. All child components of datatable are empty.
![image](https://user-images.githubusercontent.com/34492112/121600673-193e4e80-ca45-11eb-989b-3dacfcfbcda8.png)

**Comment by mitow7821** [comment]
I've found that if you replace 'dynamicChildren' with 'children' in DataTable.vue, table is rendering correctly 

![image](https://user-images.githubusercontent.com/34492112/121605301-7558a100-ca4c-11eb-9037-16e2ab2f2120.png)

Please let me know whether this solution doesn't have any consequences.
