### ISSUE TITLE
Datatable - Column property hidden does not work - Vue 3

### ISSUE THREAD

**Issue by frnk01** [primefaces/primevue#1325]
```[x] bug report```

**Current behavior**
Property "hidden" on Column component does not work. 

**Expected behavior**
Column should be hidden when setting hidden="true" 

**Minimal reproduction of the problem with instructions**
`<Column field="fieldname" header="Field title" dataType="currency" sortable bodyClass="currency" hidden="true">`

Vue 3.x - Composition API

**Comment by tugcekucukoglu** [comment]
Please use `:hidden="true"` instead of `hidden="true"`. hidden excepts boolean.

[https://codesandbox.io/s/cranky-cartwright-qmk15](https://codesandbox.io/s/cranky-cartwright-qmk15)

**Comment by frnk01** [comment]
@tugcekucukoglu Have tried that aswell. It does not work either.

`<Column field="fieldname" header="fieldheader" sortable :hidden="true"></Column>`

**Comment by tugcekucukoglu** [comment]
Did you check the example [https://codesandbox.io/s/cranky-cartwright-qmk15](https://codesandbox.io/s/cranky-cartwright-qmk15) ? I can't say much without a codesandbox template demonstrating the issue.
