### ISSUE TITLE
Tooltip not showing on mobile

### ISSUE THREAD

**Issue by ndido98** [primefaces/primevue#1326]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/pedantic-leaf-rcqes

**Current behavior**
When hovering the tag on desktop the tag shows normally, while on mobile when tapping on the tag nothing happens.

**Expected behavior**
By tapping on the tag I should be able to see the tooltip, and by tapping everywhere else the tooltip should disappear.

**Minimal reproduction of the problem with instructions**
1. Open the CodeSandbox link on desktop
2. Hover on the tag, the tooltip should appear
3. Open the CodeSandbox link on mobile
4. Click on the tag, nothing happens

**What is the motivation / use case for changing the behavior?**
By allowing this behavior we can use the tag component as a cross-device abbreviation, by keeping the text inside it short and having a longer text inside its associated tooltip.

**Possible root cause**
This behavior is due to the fact that when clicking something on mobile _both_ `mouseenter` and `click` events are fired, so the tooltip is first shown, then it's hidden right away. One possible fix would be adding a new modifier to optionally suppress the hide-on-click event.

**Please tell us about your environment:**
Windows 10, WebStorm 2021.1, Vue CLI 5.0.0-beta.0

* **Vue version:** 3.0.4

* **PrimeVue version:** 3.5.0

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
For next version default attributes added to Tag component and tooltip will be available by using focus event.

Thanks for your contribution.
