### ISSUE TITLE
Label is shown underneath input text when using p-float-label with p-inputgroup

### ISSUE THREAD

**Issue by gpsd7-dbilli** [primefaces/primevue#1328]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/admiring-firefly-547ig?file=/src/InputGroupDemo.vue

**Current behavior**
Label is shown underneath input text.

**Expected behavior**
Label should not be visible underneath input text.

**Minimal reproduction of the problem with instructions**

1. Open the CodeSandbox link on desktop
2. Enter some text in the input field
3. Press the Tab key to make the input box lose focus
4. The text will be shown with the label behind it.

**What is the motivation / use case for changing the behavior?**
When the label is displayed behind the input text, the input text is unreadable.

**Please tell us about your environment:**
Windows 10

* **Vue version:** 3.1.1

* **PrimeVue version:** 3.5.0

* **Browser:** [all]

**Comment by tugcekucukoglu** [comment]
InputText needs v-model. Otherwise it can't fold text and label floats back.
