### ISSUE TITLE
Accordion tab-open and tab-close events

### ISSUE THREAD

**Issue by sid-6581** [primefaces/primevue#1329]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**

In 2.4.2 all the code for emitting tab-open and tab-close events was removed. It remains in master for the 3.x versions, so this does not seem intentional. The documentation still reflects tab-open and tab-close as events that are emitted.

**Expected behavior**

Expect tab-open and tab-close events.

* **Vue version:** 2.6.12

* **PrimeVue version:** 2.4.2

* **Browser:** [all]

**Comment by sid-6581** [comment]
5d2778a416141b5059ab57c65ea8f82018c68a81 is the commit that appeared to break these events. @tugcekucukoglu

**Comment by tugcekucukoglu** [comment]
Thanks for your report , we will fix it for next version.

**Comment by Messias-Ferreira** [comment]
forecast to update NPM ?
