### ISSUE TITLE
BlockUI does not unblock when blocked property changes fast

### ISSUE THREAD

**Issue by flo-at** [primefaces/primevue#1331]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```
**See also #486.**

**CodeSandbox Case (Bug Reports)**
The [current PrimeVue showcase](https://primefaces.org/primevue/showcase/#/blockui) can be used.

**Current behavior**
Blocking and unblocking a BlockUI fast gets it stuck in a state where the dark color overlay is not there, but you still cannot click / select / edit anything.

**Expected behavior**
It should always unblock, no matter how fast you click or how fast the model variable changes.

**Minimal reproduction of the problem with instructions**
Go to [current PrimeVue showcase](https://primefaces.org/primevue/showcase/#/blockui) and click "Block" and "Unblock" as fast as you can. Happens after a few clicks.\
This also happens in a project I'm working on (blocking/unblocking happens based on a axios promise here), but the showcase itself is a good minimal reproduction example, I guess.

**environment / Vue version / PrimeVue version**
see current PrimeVue showcase

**Browser:**
* Chromium 91 (Linux)
* Firefox 89 (Linux)

**Comment by tugcekucukoglu** [comment]
"Unblock" button is out of the component, so "Unblock" is clickable and when it is clicked, the component is unblocking. Also when you want to block the whole page, this works as expecting.

**Comment by west-farmer** [comment]
I have same problem. 
When a query return large record set  it''s work well, when it return few records the block layer disappeared, the blocked area display new data, but  not response to mouse and keyboard。

**Comment by amirh715** [comment]
I have the same issue.

**Comment by nathanwalasek** [comment]
I also have this issue. I have BlockUI active when axios is waiting for a request response. If I have multiple axios requests simultaneously, BlockUI gets activated/disabled in rapid succession and the end result is it's VISUALLY not blocked, but the DOM elements are still there and I am unable to click or interact with anything.

**Comment by Hiroki-Tamaru** [comment]
I also have this issue in PrimeVue ver. 3.28.0 when I change the blocked property quickly.
The error below is thrown.
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Proxy.removeMask (webpack-internal:///./node_modules/primevue/blockui/blockui.esm.js:79:23)
    at HTMLDivElement.eval (webpack-internal:///./node_modules/primevue/blockui/blockui.esm.js:73:14)
```

**Comment by kubiksk8ter** [comment]
When the "blocked" property of the BlockUI component is changed in quick succession, this p-blockui element remains in the template:
`<div class="p-blockui p-component-overlay p-component-overlay-enter p-blockui-document p-component-overlay-leave"></div>`

**Comment by meirhlmn** [comment]
Has there been any update on this? We are using PrimeVue 3.49.1 and the entire UI freezes when BlockUI is removed (fullscreen):

blockui.esm.js:109 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at Proxy.removeMask

**Comment by UnforgetMemory** [comment]
Unfortunately, v4.0.0 also has this issue. When I enable FullScreen, the Mask div cannot be removed when the route changes or even when I force blocked to false.

**Comment by 1Map** [comment]
Even the latest version.  I have a BlockUI where I test it with a button (Block/Unblock).  If I click the button too fast it throws the error:

```
Uncaught (in promise) NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Proxy.removeMask (BlockUI.vue:96:39)
    at Proxy.unblock (BlockUI.vue:86:22)
    at Proxy.blocked (BlockUI.vue:26:23)
    at callWithErrorHandling (runtime-core.esm-bundler.js:202:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:209:17)
    at job (runtime-core.esm-bundler.js:5967:9)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:363:7)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5148:5)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5061:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
...
```

**Comment by minzdrav** [comment]
@tugcekucukoglu please reopen the issue

**Comment by Daniel-WWU-IT** [comment]
Same here, 4.5.4 still has this issue.
