### ISSUE TITLE
Multiple sort custom function

### ISSUE THREAD

**Issue by welcome14** [primefaces/primevue#1332]
How i can sort my value array with my custom function ?

if i set sortmode=custom, the @sort event not return the column where i have clicked.
the event.sortfield is ''...

i have the originalEvent, but i don't see the metakey.

thanks

**Comment by tugcekucukoglu** [comment]
Please use the forum or discord channel for questions and help requests. 

Thanks.

**Comment by welcome14** [comment]
I can post this issue as a request ?

I have not received any response.

Thanks
