### ISSUE TITLE
 The value of the ProgressBar is not displayed when using the theme md-light-indigo

### ISSUE THREAD

**Issue by tk1** [primefaces/primevue#1334]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/upbeat-kowalevski-htn8b

**Current behavior**
 The value of the ProgressBar is not displayed when using the theme md-light-indigo.

**Expected behavior**
The value should be displayed.

```
  "vue": "^3.0.11",
  "primevue": "3.4.0"
```

**Comment by tugcekucukoglu** [comment]
It is completely about Material design. It is not a bug.

**Comment by tk1** [comment]
@tugcekucukoglu : Is it then also be design that the content of the slot in ProgressBar will not be displayed: [Example](https://codesandbox.io/s/eager-greider-86mdx?file=/src/App.vue) ? If yes this should be mentioned in the docs.

**Comment by tugcekucukoglu** [comment]
We thought there is a general idea about themes like Bootstrap, Material etc. If we wanted to write all of this at the documentation, it's gonna be little mess. You know. Instead, there is a configurator at the showcase. So everybody can try all the themes and see the differences.

Thanks,
