### ISSUE TITLE
ProgressBar doesn't show the true value

### ISSUE THREAD

**Issue by tk1** [primefaces/primevue#1335]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/elegant-lehmann-jcomj

**Current behavior**
Click the button "Restart" (e.g. when 50% are reached) to reset the value
of the ProgressBar to 0. Then the ProgressBar will move slowly backwards.
      It should instead jump to 0. The displayed value also doesn't correspond
      to the length of the bar.

**Expected behavior**
The length of the progressbar should at any time correspond to the value of the progress bar.

* **Vue version:** 3.1.1

* **PrimeVue version:** 3.4.0

* **Browser:** [Chrome 91 | Firefox 89| ]

**Comment by tugcekucukoglu** [comment]
Because of transition-duration is 1s for determinate mode, it is expected behaviour. Possible solution for this: [https://codesandbox.io/s/adoring-pine-ojs8y](https://codesandbox.io/s/adoring-pine-ojs8y)

**Comment by mmalcek** [comment]
Hi, I've just struggle with this for couple uf hours - this was the shortest I've made (in primeVue 4/tailwind)

```html
<ProgressBar
      :value="uploadState.progress"
      unstyled
      pt:root:class="h-6 border border-solid"
      :pt:value:class="`bg-blue-500 transition-all ${uploadState.progress > 0 ? 'duration-1000' : ''}`"
    ></ProgressBar>
```
