### ISSUE TITLE
Missing 'active' prop on AccordionTab

### ISSUE THREAD

**Issue by andilem** [primefaces/primevue#1338]
**I'm submitting a ...**  (check one with "x")

[x] bug report
[ ] feature request
[ ] support request

**Current behavior**
The component AccordionTab doesn't have an 'active' prop like described in the showcase https://primefaces.org/primevue/showcase/#/accordion

* **PrimeVue version:** 3.5.0

**Comment by tugcekucukoglu** [comment]
'active' prop is not available anymore. For more functionality, 'activeIndex' prop is added to Accordion component. Sorry for the confusion. We will update the documentation for next version.
