### ISSUE TITLE
Add custom filter for DataTable

### ISSUE THREAD

**Issue by AndreiSoroka** [primefaces/primevue#1343]
Add filterFunction for custom search

**Current behavior**
no functionality

**What is the motivation / use case for changing the behavior?**
Example:
```javascript
const filters = ref({
  tags: {
    operator: FilterOperator.AND,
    constraints: [
      {
        value: null,
        matchMode: FilterMatchMode.EQUALS,
      },
    ],
    filterFunction(value, items, mode) { // <-- for example
      return items.filter((item) => {
        return value.startsWith('#') ? item.includes(value) : item.includes(`#${value}`);
      });
    },
  },
});
```

* **Vue version:** 3.X
I use vue 3

* **PrimeVue version:** 3.4.X
My version: 3.5.0

**Comment by AndreiSoroka** [comment]
mmm, I find filterMatchModeOptions in code... and after that find in docs [here](https://primefaces.org/primevue/showcase/#/datatable)
(but not [here](https://primefaces.org/primevue/showcase/#/datatable/filter))

And docs are wrong...

**Comment by AndreiSoroka** [comment]
ok

```javascript
FilterService.register('filterByArrayEquals', (arr, value) => {
  if (!value) {
    return true;
  }
  return arr.includes(value);
});

/* Wrong
const filters = ref({
  tags: {
    operator: FilterOperator.AND,
    matchMode: 'filterByArrayEquals',
  },
});
*/

// ok
const filters = ref({
  tags: {
    operator: FilterOperator.AND,
    constraints: [
      {
        value: null,
        matchMode: 'filterByArrayEquals',
      },
    ],
  },

```

**Comment by AndreiSoroka** [comment]
need to update docs

**Comment by Drillan767** [comment]
Agreed, I've spent hours trying to find this solution, the doc is incredibly blur about how to customize this.

**Comment by AndreiSoroka** [comment]
FYI: @tugcekucukoglu

**Comment by jminardi** [comment]
I am using vue with the script setup syntax, typescript, and a PrimeVue datatable . Can anyone give me a minimum working example SFC that has a datatable with filtering and sorting?
