### ISSUE TITLE
Dropdown overlay not align

### ISSUE THREAD

**Issue by Aysnine** [primefaces/primevue#1344]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**

![image](https://user-images.githubusercontent.com/10137653/121763265-33734c00-cb6d-11eb-9129-a1b3f322e04d.png)

When:

![image](https://user-images.githubusercontent.com/10137653/121763098-f22e6c80-cb6b-11eb-8c7c-30706810cd86.png)

**Expected behavior**

align

**Minimal reproduction of the problem with instructions**

https://github.com/Aysnine/primevue-quickstart-vite/tree/overlay-align
                                                                    
**Please tell us about your environment:**

* **Vue version:** 3.0.5

* **PrimeVue version:** 3.5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Cause analysis**

![image](https://user-images.githubusercontent.com/10137653/121774072-de5a2900-cbb2-11eb-9ee0-5f45c9797043.png)

![image](https://user-images.githubusercontent.com/10137653/121774127-5aed0780-cbb3-11eb-850a-df3547dbce57.png)

The initialized DOM will stretch the page, and scroll bars will appear, which will affect the position calculation

**Comment by Aysnine** [comment]
My quick fix:

```css
.p-connected-overlay-enter-from.p-connected-overlay-enter-active {
  top: 0;
}
```

**Comment by tugcekucukoglu** [comment]
Thanks for the great repo. I cloned it and tried both 3.2.0 and 3.5.1. I didn't get any strange behaviour. My result: 
<img width="1154" alt="dropdwon-vite" src="https://user-images.githubusercontent.com/32294991/122221856-5b8ae400-ceba-11eb-94f9-961a9bd20be4.png">

**Comment by Aysnine** [comment]
@tugcekucukoglu 

Only if the scroll bar can affect the width of the body.

**Comment by Aysnine** [comment]
@tugcekucukoglu
Try windows or mac with mouse.

https://stackoverflow.com/questions/44668257/different-looks-on-scrollbars-when-using-usb-mouse-vs-wireless-trackpad-in-os-x

**Comment by tugcekucukoglu** [comment]
Thanks for the clarification. It will be applied all Prime libraries.

Please track at [#1358](https://github.com/primefaces/primevue/issues/1358)
