### ISSUE TITLE
Allow SelectButton to de-select option

### ISSUE THREAD

**Issue by StefanFabian** [primefaces/primevue#1346]
This was apparently possible at some point but #494 for some reason changed that behavior instead of at least making it an option.
I think both behaviors are useful depending on the context, it would be great if an option could be added to be able to click a selected option again to un-select it and change the `modelValue` to `null`.

**Comment by tugcekucukoglu** [comment]
We're currently not considering to revert this feature since there is not enough demand from the community.

Thanks,

**Comment by StefanFabian** [comment]
Thank you for the reply though it is not the answer I would have liked or expected.
This is a feature that every other Vue 3 UI framework supports and it literally only requires adding a prop `clearable: Boolean` and replacing:
https://github.com/primefaces/primevue/blob/9a43ebdb02a23b6df3b65032ba636652239629e6/src/components/selectbutton/SelectButton.vue#L61
with
```
        newValue = (this.clearable && selected) ? null : optionValue;
```

**Comment by Aterr** [comment]
I also agree that there should be this kind of option.

**Comment by FVolral** [comment]
Me too

**Comment by enriquemosso65** [comment]
Hi, i fix in my code using store method:

Vue 3 Index.vue

` <PVSelectButton v-model="selectedValue" :options="options" optionLabel="label" optionValue="value">`

`const selectedValue= computed({
  get: () => myStore.selectedValue,

  set: (newValue) => myStore.selectValue(newValue),
})`

Store action:
`selectedValue : 'myOptionValue'`

`    selectValue(value) {
      if (value=== null) return
     this.selectedValue = value
     
    },`

**Comment by emersonp** [comment]
Thanks for that, enrique! Gives me a path to implementing this since Prime seems unwilling to do so.

**Comment by petternett** [comment]
idk why the docs don't mention it, but you can also just add `:allow-empty="false"` to the component to make it non-unselectable

**Comment by SamGeodynamics** [comment]
> :allow-empty="false"
@tugcekucukoglu please add this to the documents, thank you :-)
