### ISSUE TITLE
Row double click for DataTable

### ISSUE THREAD

**Issue by adlaws** [primefaces/primevue#1347]
Howdy,

Issue 1075 dealt with DataTable row double click support for v3.x, but v2.x still has no support for it.

Ref: https://github.com/primefaces/primevue/issues/1075

Could the corresponding update be made to the v2.x DataTable as well? 

I have something of a workaround in place, but it would be nice to have the functionality available directly, as in the v3.x component.

Thanks!

**Comment by adlaws** [comment]
Wow! Fast! Awesome work, @tugcekucukoglu ! 

I'll watch out for the release of v2.4.3😎👍

**Comment by tugcekucukoglu** [comment]
Thanks @adlaws ,

Always bet on prime!

**Comment by adlaws** [comment]
🤣 👍

**Comment by khaledOghli** [comment]
Does this feature for row double click exist !?
