### ISSUE TITLE
expose breakpoint responsive variables (sm, md...)

### ISSUE THREAD

**Issue by mariusa** [primefaces/primevue#1349]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**

Bootstrap has these exposed as CSS variables:

```
--breakpoint-xs 0
--breakpoint-sm 576px
--breakpoint-md 768px
--breakpoint-lg 992px
--breakpoint-xl 1200px
```
**Expected behavior**
Please consider exposing similar variables with PrimeFlex too.
Docs say we can do it manually, obviously, but would like to avoid copy pasting:
https://primefaces.org/primevue/showcase/#/primeflex

**What is the motivation / use case for changing the behavior?**
The framework already has these defined, no need to repeat

* **PrimeVue version:** 3.5.x

Thanks!

**Comment by tugcekucukoglu** [comment]
You don't need to copy paste anything, for example [https://primefaces.org/primevue/showcase/#/grid](https://primefaces.org/primevue/showcase/#/grid). But you can customize your own css by overriding PrimeFlex. Also PrimeFlex is written with many new features and enhancements.
