### ISSUE TITLE
Rollup Issue when building to netlify.

### ISSUE THREAD

**Issue by antoinebeneteau** [primefaces/primevue#1350]
Hello, im getting this error when build to netlify.

`Error: [vite]: Rollup failed to resolve import "primevue/InputText" from `

Do you avec a solution for it ?

Regards

**Comment by tugcekucukoglu** [comment]
What is your environment? Could you provide a simple codesandbox example? For example how did you set the main.js, vue.config.js etc. of the project?

**Comment by antoinebeneteau** [comment]
Yes,

Vue 3 + Vite

`vite.config.js`
`import { defineConfig } from "vite";
import vue from "rollup-plugin-vue";
import path from "path";

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "/src"),
    },
  },
  server: {
    open: true,
  },
  devServer: {
    port: 8081,
  },
});
`

`vue-confie.js`
`module.exports = {
  configureWebpack: {
    devtool: "source-map",
  },
};
`

**Comment by cagataycivici** [comment]
I don't think that we can do anything on our side, better should be fixed from your config.

**Comment by inkbeard** [comment]
@antoinebeneteau , did you resolve the issue? I'm having similar build issues that are only happening in netlify.
