### ISSUE TITLE
multi select and grid css

### ISSUE THREAD

**Issue by magavel** [primefaces/primevue#1352]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/awesome-satoshi-gig7s?file=/src/components/testGrid.vue

**Current behavior**
I set up a form using grid css. In this form I use multiselect from primevue. With mozilla I can't get the multiselect to use its column and not overflow on the other columns when all options are selected. Can you think of a way to force the multiselect to stay in its column?
![image](https://user-images.githubusercontent.com/36990281/122184348-6af33880-ce8c-11eb-9a58-d37b0e905e26.png)

Nota: with chrome that's ok.

there are the same problem with the website of primevue.

![image](https://user-images.githubusercontent.com/36990281/122184017-194aae00-ce8c-11eb-9c5f-61f757c7f7a1.png)

**Please tell us about your environment:**

* **Vue version:** 2.6.12

* **PrimeVue version:** 2.4.1

* **Browser:** [ Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tugcekucukoglu** [comment]
Thanks, we will update also update showcase and a possible solution:
```
.p-multiselect {
   width: 18rem;
}

@media screen and (max-width: 640px) {
    .p-multiselect {
        width: 100%;
    }
}
```
