### ISSUE TITLE
Accessing Column props via vue internal field breaks wrapper components

### ISSUE THREAD

**Issue by obermillerk** [primefaces/primevue#1356]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/silly-gould-cjedz
For some reason this does not have the same error, but it still doesn't render the column as it should

**Current behavior**
Making a wrapper component for Column and then trying to use in a Datatable throws an error due to accessing props via the `columnProp` method in multiple other primevue components.

**Expected behavior**
I should be able to create a wrapper component and it should behave just as the normal Column would in a Datatable with my added functionality.

**Minimal reproduction of the problem with instructions**
See CodeSandbox link above

**What is the motivation / use case for changing the behavior?**
I want to define a custom default header slot on a Column so I don't have to redefine the same header everywhere. The "vue way" of doing this would be wrapping the existing Column component from primevue in a component that instantiates a Column and has a default header slot defined, with just the relevant props defined on this wrapper component, and all other props will be passed through to the original Column component from primevue.

The problem arises in the way primevue accesses props from Column components in the Datatable. Because I've defined a wrapper component, when the Datatable goes to look at the prop types only the types for my wrapper's props exist. I don't believe you're supposed to access the component.type field at all but especially from the parent, as this breaks vue's data flow.

I understand this is done to allow for certain aspects of a column to be defined on the Column but take effect elsewhere in the table, but this breaks expected vue behavior. Perhaps `teleport` could be used to render what's needed inside of the Column component and teleport it to the proper place in the table? That way the parent -> child data flow remains in tact, but the header etc can be rendered outside the Column's DOM.

**Please tell us about your environment:**
This theoretically applies to all environments

* **Vue version:** 3.1.1

* **PrimeVue version:** 3.5.1

* **Browser:** probably all

**Comment by tugcekucukoglu** [comment]
Column component is a kind of helper component for DataTable not a separate component like DataTable. If you add a wrapper component for it, DataTable never finds it and cannot render it. Therefore, Column only works if the wrapper is DataTable. Still if you want to add custom header, Column has own header slot.
