### ISSUE TITLE
DataTable cell editing regression

### ISSUE THREAD

**Issue by blurbiness** [primefaces/primevue#1357]
DataTable in cell editing is not working properly in 3.5.1.
It seems that row index provided in editor slot props is not correct.

Error is reproduced in the showcase page, Advanced Cell Editing sample:
https://primefaces.org/primevue/showcase/#/datatable/edit
If a cell is edited and then Enter or Tab is pressed, edited value is lost.

In a working app where the same approach as Advenced Cell Editing example had been adopted, I had detected that the row index provided in `<template #editor="slotProps">` was not correct. Same code without any modification worked as expected up to 3.4.0.

**Comment by nclemeur** [comment]
I haven't tested but too me it look like the fix for #1274 (see
[here](https://github.com/primefaces/primevue/commit/5defea1f9468297cfd4768ad7c6567c74e68a376#diff-d301c2a8fd7f7f502f0558318f615535b4e56170cc3c9146f2f86362c5c6bc55)) was a bit lazy and did not look pass the next line

**Comment by tugcekucukoglu** [comment]
It is a regression. 

Thanks,
