### ISSUE TITLE
Primevue 2.4.x Datatable inline edit not working with filter

### ISSUE THREAD

**Issue by zsuzsmuzs** [primefaces/primevue#1359]
**I'm submitting a ...** 
```
[X ] bug report 
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/hungry-brattain-h5ejs

**Current behavior**
If you use a filter with the datatable the inline edit is not working

**Expected behavior**
Inline edit should work with filter as well

**Minimal reproduction of the problem with instructions**
Filter category for accessoires. Try to edit last row --> Edit won't work.

The problem is, that props.index is used here. But when we filter the order of the rows is changed. I tried to work with the ids instead of the index,.

My aproach:
```
onCellEditComplete(event){
   const id = event.data.id,
   editingCellValue = this.editingCellRows[id][event.field];
   index = this.products.findIndex(item => item.id === id);
   Vue.set(this.products, index, this.editingCellRows[id];
}
```
and something similar to onCellEdit but it still is buggy this way. I could not make it work and had to go back to row  editing.

* **Vue version:** 2.X

* **PrimeVue version:** 2.4.X

* **Browser:** all

**Comment by cagataycivici** [comment]
#1273
