### ISSUE TITLE
Tooltip doesnt disapear in chrome

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#1360]
Tooltip is not working on chrome in example: https://www.primefaces.org/primevue/showcase/#/tooltip

![image](https://user-images.githubusercontent.com/34492112/123797802-d99db080-d8e6-11eb-8ab6-1fa04da64f10.png)

**Comment by tugcekucukoglu** [comment]
Are you testing it on mobile? It was fixed for next version for mobile. Also in this example to display the tooltip for InputText focus event is used. 

<img width="713" alt="Screen Shot 2021-06-30 at 12 14 45" src="https://user-images.githubusercontent.com/32294991/123935549-014f5000-d99d-11eb-9a42-72aacca4575a.png">
