### ISSUE TITLE
[Feature Request] Add autoHighlight property to AutoComplete

### ISSUE THREAD

**Issue by tft7000** [primefaces/primevue#1362]
**I'm submitting a feature request**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
On typing the AutoComplete component shows the dropdown. However, to select the first available entry, the user has to use the mouse or click on the arrow down.

**Expected behavior**
Optionally the first item of the dropdown should be automatically selected

**What is the motivation / use case for changing the behavior?**
Better UX in some cases: eg to add a list of items, I would like to type some letters, click enter (to add the first entry), type letter, click enter (to add another entry) and so forth.

* **Vue version:** 3.X
3.1.2

* **PrimeVue version:** 3.4.X
3.5.1

Note:
In primereact the same Issue was solved here: https://github.com/primefaces/primereact/issues/1801

**Comment by mouadTaoussi** [comment]
I'm gonna add this feature for You as soon as possible! I Hope it get merged!
