### ISSUE TITLE
Datatable headers not visible in expanded view

### ISSUE THREAD

**Issue by devtaha** [primefaces/primevue#1369]
Datatable headers are not visible in expanded view.

![Screenshot 2021-07-11 at 3 11 56 AM](https://user-images.githubusercontent.com/17719750/125177518-eaf39080-e1f5-11eb-8c48-f1dd1956184f.png)

I am using version "primevue": "3.3.4"

See the UI with no headers:
![Screenshot 2021-07-11 at 3 15 06 AM](https://user-images.githubusercontent.com/17719750/125177562-49207380-e1f6-11eb-9981-c46ad523c5b3.png)

Let me know if you need further information regarding this issue.

**Comment by devtaha** [comment]
I have found a workaround (not proper fix) to resolve this issue
I added css (not scoped)
![Screenshot 2021-07-11 at 3 36 52 AM](https://user-images.githubusercontent.com/17719750/125177939-6e62b100-e1f9-11eb-83aa-5ec6bbbd80e6.png)

Posting this as it may help someone facing this issue, until this issue is resolved properly

**Comment by tugcekucukoglu** [comment]
This issue is not clear. In the showcase [https://www.primefaces.org/primevue/showcase/#/datatable/rowexpand](https://www.primefaces.org/primevue/showcase/#/datatable/rowexpand) all column titles are shown. There should be a defect on your side.
