### ISSUE TITLE
Bug - Tool tip is now showing on mobile device

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#1370]
Reference:
https://www.primefaces.org/primevue/showcase/#/tooltip

You can inspect it with google chrome - mobile view.
and you will see that tooltip is not showing.
it's showing only on focus but sometimes you would like to hover over a div or a span or (button - not showing as well).

**Comment by tugcekucukoglu** [comment]
In mobile view using tabindex to focus on button is better solution instead of using hover over a span

```
<span tabindex="0" v-tooltip.bottom.focus="'Abbreviation'">
        <Button type="button" label="Save" icon="pi pi-check" />
</span>
```

**Comment by vadimt2** [comment]
Sorry, had no time to test it, it's not working.
