### ISSUE TITLE
[Feature-Request] Hover-Event for rows in Datatable

### ISSUE THREAD

**Issue by CurrentlyNoName** [primefaces/primevue#1371]
**I'm submitting a ...** 
```
[x] feature request
```

Hello,

there are many events for rows in the DataTable-Component, like row-click etc., but for our current solution we need an row-hover-Event. 

I think this could be quite easily be added by adding @hover="onHover($event, rowData, index)" to the TableBody.vue.

Adding this would help us quite a lot!

**Comment by mouadTaoussi** [comment]
I'll work for that feature for You! but I Hope it get merged!

**Comment by jsegars** [comment]
I see this pull request was closed to due performance concerns, but there was willingness to reconsider if there was more demand.  Count us as interested;  it's very important functionality for an app we're building.

**Comment by mouadTaoussi** [comment]
> I see this pull request was closed to due performance concerns, but there was willingness to reconsider if there was more demand. Count us as interested; it's very important functionality for an app we're building.

@jsegars **can you detail more what performance concerns mean ? so I could improve it.**

**Comment by jsegars** [comment]
I'm simply going off the comment from @cagataycivici at the very bottom of #1412
