### ISSUE TITLE
InputNumber input event returns wrong value

### ISSUE THREAD

**Issue by jatinthapar1910** [primefaces/primevue#1372]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```
**Current behavior**

`InputNumber` returns null irrespective we have value in input. Let's say we type 123.12 and with backspace when we delete decimals then input event returns null value. Attached is the screenshot.
![Screenshot 2021-07-14 at 4 15 24 PM](https://user-images.githubusercontent.com/65127762/125609610-c0ab6fad-c381-4cf9-9763-633256ac78dd.png)

**Expected behavior**
`InputNumber` should return current input value.

**Minimal reproduction of the problem with instructions**

Please open https://codesandbox.io/s/wonderful-chatelet-xuntn and try to type 123.12 as per the screenshot above and in the console it will show the input event value.

* **Vue version:** 3.1.2

* **PrimeVue version:** 3.5.1

* **Browser:** all

**Comment by Anubarak** [comment]
I had the same issue with this and ended up using `@update:modelValue` to solve it. Just in case you need a work around

**Comment by mertsincan** [comment]
Hi,

I think the input event should not be called because the value does not change when the decimal character is deleted.

Best Regards,
