### ISSUE TITLE
Show/Hide Clear Button

### ISSUE THREAD

**Issue by arnyee** [primefaces/primevue#1378]
**I'm submitting a ...**  (check one with "x")

[X] feature request => Please check if request is not on the roadmap already 

Hello,

I really love your project but I found something I couldn't solve. In your page https://primefaces.org/primevue/showcase/#/datatable/filter everything is working find but I need a little but extra feature. If it did exist then I didn't really find it in the documentation, it would be worth adding to it. 

So my problem is, I need to hide the clearFilter Button, and only show it when any of the column filters or the global filter is not null. I hope you can help me as soosn as you can, and I think this extra could be fancy and useful to anyone

**Comment by arnyee** [comment]
I handle itt with vue js watch. So it's not important but it will be nice if the library has this function

**Comment by cagataycivici** [comment]
I'll check this for 3.7.0.

**Comment by mertsincan** [comment]
I think my example can be used for questions like this. The button can be fully controlled by the user.

Best Regards,
