### ISSUE TITLE
Error: Do not access Object.prototype method

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#138]
if I include PrimeVue components right into my project the compiler shows the following errors in `DataTable.vue` and `TreeTable.vue`:
```
Do not access Object.prototype method 'hasOwnProperty' from target object
```
It references the error to the following eslint rule https://eslint.org/docs/rules/no-prototype-builtins

If I replace the lines `this.filters.hasOwnProperty(xxx)`  with `Object.prototype.hasOwnProperty.call(this.filters, xxx)` the error goes away.

**Comment by cagataycivici** [comment]
Thank you.
