### ISSUE TITLE
Using the newest PrimeFlex breaks DataView

### ISSUE THREAD

**Issue by psuplat** [primefaces/primevue#1380]
Using:
`"primeflex": "^3.0.0"`
`"primevue": "^3.5.1"`

Using grid layout DataView with the newest PrimeFlex results in elements being showed 1 per row, instead of (in given example) 4 items per row.
`<DataView :value="users" layout="grid" class="p-4" v-if="viewUsers">`

This is most likely because `layout="grid"` generates element with class p-grid

![image](https://user-images.githubusercontent.com/14207860/126370661-d9dbb981-bbd2-4352-881f-fc331b366198.png)

If, in browser inspector, I manually replace the above classes with those from PrimeFlex v3 all works perfectly
![image](https://user-images.githubusercontent.com/14207860/126370888-9dbef249-e1bc-490b-afa1-ba994931303c.png)

Perhaps changing the /src/components/dataview/DataView.vue line 16 from this:
`<div class="p-grid p-nogutter">`

to this:
`<div class="p-grid p-nogutter grid grid-nogutter">`

would fix the issue without breaking how older PrimeFlex works.

But then again I suspect while I only encounter this in DataView, there might be more components that will break with new PrimeFlex

**Comment by tugcekucukoglu** [comment]
PrimeVue still uses PrimeFlex 2.0. We highly recommend using PrimeFlex 2.0 on your project.
