### ISSUE TITLE
Auto ZIndex Issue with Toast and Sidebar 

### ISSUE THREAD

**Issue by Mirko92** [primefaces/primevue#1381]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/naughty-bohr-jmkhm?file=/src/App.vue

**Current behavior**
The toast is under the overlay_mask of the sidebar. Even when the component is inside the sidebar. 

**Expected behavior**
The toast component should be visibile, over the sidebar when is positioned inside it.

**Minimal reproduction of the problem with instructions**
The CodeSandbox is pretty clear.
Try to click the button "Toast on sidebar" and "Toast from page". 

* **PrimeVue version:** 3.4.X
Check CodeSandbox

**Comment by cagataycivici** [comment]
We'll check this for 3.7.0, thanks.
