### ISSUE TITLE
Tooltip renders as static element because of position-style

### ISSUE THREAD

**Issue by cbrgpl** [primefaces/primevue#1382]
Lost position: absolute||fixed; 

Packages versions:
"primevue": "^3.5.1",
"vue": "^3.0.0",

Styles after inserting:
(https://user-images.githubusercontent.com/52164184/126866682-f1c4294a-da13-44f2-969f-67cb6b08a13a.png)

**Left**, **top** and **z-index** styles are gray because they are not applied because tooltip's position is static

**Comment by cagataycivici** [comment]
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl
