### ISSUE TITLE
[Feature Request] Multi-level Sidebar

### ISSUE THREAD

**Issue by OneSeven** [primefaces/primevue#1387]
[X] feature request => Please check if request is not on the roadmap already

More convenient display of information,
I found that it is popular in the drawer to display information and fill in the form, especially the use of ant or element-ui is very common, and it is indeed interactive and friendly, efficient and efficient, I hope to add this function

It is recommended to refer to ant.design, this design is more flexible
https://ant.design/components/drawer/
https://element.eleme.cn/#/en-US/component/drawer

**Comment by dheimoz** [comment]
Hey @OneSeven does the sidebar not suffice the requirement?
https://www.primefaces.org/primevue/showcase/#/sidebar

**Comment by cagataycivici** [comment]
At core, there is sidebar but a fully functional navigational drawers are provided by PrimeBlocks instead.

https://www.primefaces.org/primeblocks-vue/#/application/sidebarnav
https://www.primefaces.org/primeblocks-vue/#/application/slideover
