### ISSUE TITLE
Nested sorting support for TreeTable

### ISSUE THREAD

**Issue by dottie77hotmail** [primefaces/primevue#1396]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/6wfij

**Current behavior**
TreeTable column sorting only sorts root-level nodes

**Expected behavior**
TreeTable column sorting should sort at every level

**Minimal reproduction of the problem with instructions**
The codesandbox link above is your own 'components' demo page example.
Collapse all nodes so that only root nodes are shown, click the "size" column header twice so that it is sorted in descending order from largest to smallest:
- "Videos" (size 1500kb) is correctly shown first
- "Other" (size 5kb) is correctly shown last

Expand the 'Applications' node, it has 3 children, presented in this incorrect/unexpected order (not sorted):
- Vue (size 25kb)
- Editor.app (size 25kb)
- Settings.app (size 50kb)

Click the Size column header twice again to attempt to resort the values, the root level nodes sort, however the other levels remain in original order

**What is the motivation / use case for changing the behavior?**
Tree sorting ought to sort nodes at each level

**Please tell us about your environment:**
MS Windows

* **Vue version:** 3.X
I'm using 3.0.0, your website's codepen is using 3.1.5

* **PrimeVue version:** 3.4.X
I'm using 3.3.3, your website's codepen is using 3.6.0

* **Browser:** 
occurs for me in both Chrome and Edge

* XX UIWebView | iOS XX WKWebView ]
occurs for me in both Chrome and Edge
![image](https://user-images.githubusercontent.com/84479970/127723206-17f98dec-a947-47da-ae05-f0bdca6f30bb.png)

**Comment by mouadTaoussi** [comment]
Hello! I'm gonna work on this issue to Fix it!

**Comment by mouadTaoussi** [comment]
Hello! I'm gonna work on this issue to **Fix** it!

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by sergeydus** [comment]
still not fixed

**Comment by tsunamilx** [comment]
+1, this is not fixed, @tugcekucukoglu can you please reopen it?
