### ISSUE TITLE
Password error: Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by webigorkiev** [primefaces/primevue#1397]
Using a component with SSR results in an error: Hydration completed but contains mismatches
append-to="self" Solves the problem
Something to do with the teleport
vue 3.1.5
primevue 3.6.0

Thanks

**Comment by webigorkiev** [comment]
It`s not bug. In ssr render need add teleports to html.

**Comment by wobsoriano** [comment]
> Using a component with SSR results in an error: Hydration completed but contains mismatches
> append-to="self" Solves the problem
> Something to do with the teleport
> vue 3.1.5
> primevue 3.6.0
> 
> Thanks

Where do you add `append-to="self"`? In the component itself?

**Comment by cagataycivici** [comment]
PrimeVue uses the standard teleport feature of Vue 3 so I'm not sure if there is anything we can do here. We're not doing the teleporting. If you can provide us a sample code then we'll be able to dig deeper.

**Comment by brillout** [comment]
Yea I'm as well not sure whether Vue's teleport properly supports SSR?

**Comment by wobsoriano** [comment]
Here's a simple repro using the [sidebar](https://primefaces.org/primevue/showcase/#/sidebar) component.

https://github.com/wobsoriano/primevue-teleport-ssr-repro

**Comment by brillout** [comment]
Neat, thanks for the repro.

**Comment by paulvonber** [comment]
Issue is closed, but it's still there, anyone was able to fix it or had any solution?

**Comment by inschrift-spruch-raum** [comment]
https://vuejs.org/guide/scaling-up/ssr.html#teleports
