### ISSUE TITLE
Empty message doesn't work for DataTable

### ISSUE THREAD

**Issue by Kameecoding** [primefaces/primevue#140]
Version: "primevue": "^1.0.0-rc.6",

    <DataTable :value="[]">
    <template #empty>
        No records found
    </template>
    <Column field="vin" header="Vin"></Column>
    </DataTable>

Expected Table with empty message: No records found.

Actual:
`<div class="p-datatable-wrapper"><table role="grid"><thead class="p-datatable-thead"><tr><th tabindex="-1" class=""><!----><!----><span class="p-column-title">Vin</span><!----><!----><!----></th></tr></thead><tbody class="p-datatable-tbody"><tr class="p-datatable-emptymessage"><td colspan="1"></td></tr></tbody><!----></table></div>`

Example:
https://github.com/Kameecoding/datatable

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primevue/issues/137
