### ISSUE TITLE
Make a contributing.md file

### ISSUE THREAD

**Issue by mouadTaoussi** [primefaces/primevue#1401]
**Current behavior**

there is no **CONTRIBUTING.md**

**Expected behavior**
Finding **CONTRIBUTING.md**

**Minimal reproduction of the problem with instructions**
While there is no **CONTRIBUTING.md** file, the developers who interested contributing to that project might find difficulties, while setting up the project to their local development env!
-->

**What is the motivation / use case for changing the behavior?**
Allow more developers contribute to that project

**Comment by cagataycivici** [comment]
Thanks, we'll consider this for sure.

**Comment by leszekhanusz** [comment]
Please reopen this bug, there is still no `CONTRIBUTING.md` file.
I'm having issues to try to modify a Primevue component but there is not `CONTRIBUTING.md` file which is usually present in open source package to give some advice on how to proceed to modify a component.

**Comment by FVolral** [comment]
I find that boring too

**Comment by SoyDiego** [comment]
> Please reopen this bug, there is still no `CONTRIBUTING.md` file. I'm having issues to try to modify a Primevue component but there is not `CONTRIBUTING.md` file which is usually present in open source package to give some advice on how to proceed to modify a component.

@leszekhanusz Maybe you can create a PR based on PrimeReact Contributing file :)
https://github.com/primefaces/primereact/blob/master/CONTRIBUTING.md

**Comment by FVolral** [comment]
It doesn't take long to figure out how to get started.: 

1. Clone the repository.
2. Install the dependencies by running npm install.
3. Start the project using `npm run dev`. Please note that the initial startup might take around 1 minute, or even more if you are using WSL  and have cloned the repository in a location where WSL has slow disk access (that's what get me here).
4. Once the project is up and running, you can access the PrimeVue documentation at localhost:3000. This URL serves the development environment.
5. Run unit tests with `npm run unit:test`

That's all the info I needed.

**Comment by SoyDiego** [comment]
> > @leszekhanusz Maybe you can create a PR based on **[PrimeReact Contributing file](https://github.com/primefaces/primereact/blob/master/CONTRIBUTING.md)** :). In PrimeNG it's necessary create on too @cagataycivici
> 
> @SoyDiego Sorry, I feel it's not my place to make a CONTRIBUTING.md file for a project I don't follow closely. It's kind of personal and is a message to other devs indicating how you would like them to contribute to the project.
> 
> The example you gave is more concerned by legal matters and is definitely something you could put in that file but I think what would interest more people is the technical side, how to set up your system to be able to start making changes, how to test, what are the contributing guidelines (coding style for example).
> 
> See the [CONTRIBUTING.md file of graphql-python/gql](https://github.com/graphql-python/gql/blob/master/CONTRIBUTING.md) for an example on a project I maintain to see what I mean.

I agree it's necessary more information about how to contribute. As a @FVolral you can do that steps, but yes I agree a file is necessary for new people. You have the channel on Discord where you can ask things too or they have a "suggestions" channel too.
