### ISSUE TITLE
Filtered Dropdown unusable on Windows Tablet

### ISSUE THREAD

**Issue by slumtrimpet** [primefaces/primevue#1411]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

Attempting to access filtered Dropdown in a Windows 10 tablet device (running Edge or Chrome browsers) immediately closes the dropdown and is therefore unusable.  

A 'resize' event is being registered when the keyboard is displayed.

An update of the following in Dropdown.vue fixes the issue (but of course renders the auto-close on legit-resize event broken).

```
    bindResizeListener() {
      if (!this.resizeListener) {
        this.resizeListener = () => {
          if (this.overlayVisible && !DomHandler.isAndroid()) {
            // this.hide();  <<< REMOVED THIS FOR NOW
          }
        };
        window.addEventListener('resize', this.resizeListener);
      }
    }
```

Suspect you need something similar to `DomHandler.isAndroid` to detect a Windows device running in tablet mode to fix this properly (if that's possible).

**Comment by cagataycivici** [comment]
We'll check thanks.
