### ISSUE TITLE
[Feature Request] Prop for binding row expansion to a model

### ISSUE THREAD

**Issue by kibertoad** [primefaces/primevue#1419]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
```

**Current behavior**

Currently it is not possible to selectively display expansion icon only for rows that satisfy specific criteria (e. g. having child entries), since `expand` prop is set on a column level, and `<template #body` which exposes row data is only available inside the column.

**Expected behavior**

It is possible to hide row expansion icon for rows that are not expandable.

**Minimal reproduction of the problem with instructions**

Currently this is how expander is enabled:
`<Column :expander="true" />`

It would be helpful if something like this would be possible:
`<Column :expanderRowKey="children.length" />`

Where if row value entry has field `children` with a truthy value for length, expander will be displayed. 

**What is the motivation / use case for changing the behavior?**

This change would enable to conditionally display the expander only in relevant cases.

**Please tell us about your environment:**

* **Vue version:** 3.1.5

* **PrimeVue version:** 3.6.0

* **Browser:** [all]

**Comment by cagataycivici** [comment]
I believe you can use expandedRows prop for this to expand them programmatically.

**Comment by kibertoad** [comment]
@loretari @anorv FYI

**Comment by kibertoad** [comment]
@cagataycivici Having checked this option, I believe it is for something different altogether. `expandedRows` only allows to expand rows programmatically, but it does not allow to selectively display expansion icon only on some of the rows (so that rows without children would not suggest user to expand them). It doesn't look like this is possible at all currently. Could you please reopen the issue?

**Comment by mr-feek** [comment]
Hi @kibertoad did you ever find a way to accomplish this?

**Comment by Petri-Oosthuizen** [comment]
Why has this been closed?
