### ISSUE TITLE
[feature request]Please add a prefix to all component names to prevent pollution of the component environment

### ISSUE THREAD

**Issue by OneSeven** [primefaces/primevue#1425]
In the program, I may introduce multiple component libraries, or have my own component library, 
if the component name is too common, it will cause conflicts

Suggest improvements：
```
<button />
<p-button /> or <pr-button>
````

This is very important, please consider carefully .Thanks

**Comment by createts** [comment]
why not use alias by yourself?

```
import Button from 'primevue/button';
......
app.component('YourButton', Button);
```

Then use `<your-button />` instead

**Comment by OneSeven** [comment]
> why not use alias by yourself?
> 
> ```
> import Button from 'primevue/button';
> ......
> app.component('YourButton', Button);
> ```
> 
> Then use `<your-button />` instead

![asa](https://user-images.githubusercontent.com/17974392/128607428-ab6544b3-127a-4938-8655-96478dd9d705.png)
Sorry, in webstorm and sfc, using aliases, you can’t get smart tips. This is probably a webstorm problem
Can you consider and improve it?
Because many component libraries are prefixed

**Comment by tugcekucukoglu** [comment]
We're not considering to add this feature for now since there is not enough demand from the community.

**Comment by tidan-16** [comment]
Can we do a poll and see who wants it and the ones that dont? Honestly it’s a thing really used in the vue world. I know it is not the case for react and etc, but vue yes. vuetify use it, quasar, elementui and many more. It is one reason I am not switching to this library even if it looks way more complete than the other ones, that is really a drawback for me so I think it is for the others. 

Do you guys would consider to give us to choice to add a prefix to every components by default instead?

**Comment by dharnil** [comment]
Yes, I feel, it is quite import. My company was considering this but we could not integrate primevue as the component name convention would have made readability difficult for devs.
