### ISSUE TITLE
Make Overlay Panel to Anchor on Specified Element

### ISSUE THREAD

**Issue by cosmotranglobal** [primefaces/primevue#1427]
**I'm submitting a Feature Request**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/primevue-overlay-anchor-request-93u6h?file=/src/App.vue

**Current behavior**
Overlay currently anchors on elements via events triggered only

**Expected behavior**
It should be able to anchor on a specified element via **$vm.ref or Element**
Just the way [ConfirmPopup](https://primefaces.org/primevue/showcase/#/confirmpopup) does.

**Minimal reproduction of the problem with instructions**
Just head over to the [Code Sandbox](https://codesandbox.io/s/primevue-overlay-anchor-request-93u6h) and click on the button, Also on the code I commented a sample of how it should be

**What is the motivation / use case for changing the behavior?**
When loading a page. On Mounted lifecycle callback, I want to check the route query params for certain conditions and auto toggle the *Overlay* over any desired element based on my condition. *"Programmatically"* **NO User Inputs or Clicks**

**Please tell us about your environment:**

* **Vue version:** 3.0.0

* **PrimeVue version:** 3.5.1

* **Browser:** [Chrome 92.0.4515.131 ]

*Please and this goes for every other component that uses the Event trigger method.
Let them just have the ability to have the target specified.*

Thanks 😄 ✌️

**Comment by tugcekucukoglu** [comment]
OverlayPanel and ConfirmPopup has different approach. OverlayPanel is positioned to a target and to trigger it needs an event. For backward compatibility we can't change this behaviour.

**Comment by robokozo** [comment]
@tugcekucukoglu This is extremely disappointing. I was able to 'work around' this by doing the following: 
```
const openOP = e => {
  op.value.toggle({
    ...e,
    currentTarget: targetElement.value
  });
};
```
Not having to do this hacky workaround would be great.
