### ISSUE TITLE
[feature request]Please add event while menu/overlay is dismissed.

### ISSUE THREAD

**Issue by createts** [primefaces/primevue#1428]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
There is no event fired while Menu or Overlay is dismissed. 

**Expected behavior**
Better to fire an event as 'dismissed'.

**What is the motivation / use case for changing the behavior?**
In some cases, a menu/overlay popups and wait for user's response, use may click somewhere else to close it, I want to do something for this case, but seems it is not possible because there is no such 'dismiss' event was fired in this case.

* **Vue version:** 3.X
3.0

* **PrimeVue version:** 3.4.X
3.5.0

**Comment by cagataycivici** [comment]
Sure!
