### ISSUE TITLE
Can't access PrimeVue config from component.

### ISSUE THREAD

**Issue by dcruz1990** [primefaces/primevue#1439]
I'm following the docs to dynamically change locale values but i'm getting this typescript error:
`TS2339: Property 'config' does not exist on type 'PrimeVueConfiguration'.`
I'm using PrimeVue 3.5.

**Comment by tugcekucukoglu** [comment]
You should set the core configuration to use locale.

main.js
```
import PrimeVue from "primevue/config";
Vue.use(PrimeVue);
```
