### ISSUE TITLE
Calendar select event has no value

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#144]
"primevue": "1.0.0"

Regarding docs:
![image](https://user-images.githubusercontent.com/13495631/72470409-b2c5ea00-37d8-11ea-8a5e-d4c25a5c847c.png)

Calendar select event has no value. `e` does not contain `value` property:
```
<Calendar :value="value" @select="dateSelect" date-format="dd.mm.yy" 
:show-time="showTime" :readonly="readonly" />
```
```
methods: {
    dateSelect(e) {
        console.log(e);
    },
},
```

**Comment by denis-pujdak-adm-it** [comment]
Ok. I think it is something related to the selection of the input.

Before select:
![image](https://user-images.githubusercontent.com/13495631/72481592-e7469f80-37f2-11ea-812d-5b8f97069189.png)

After select:
![image](https://user-images.githubusercontent.com/13495631/72481636-0ba27c00-37f3-11ea-91c9-f8369f695a88.png)

**Comment by denis-pujdak-adm-it** [comment]
My temporary solution is:
```
methods: {
			dateSelect(e) {
				if (e instanceof Date)
					this.$emit('select', e);
			},
		},
```

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primevue/issues/148

**Comment by cagataycivici** [comment]
Use date-select with 1.0.1

**Comment by fairking** [comment]
Thank you @cagataycivici
