### ISSUE TITLE
useToast's add method fails to create a toast

### ISSUE THREAD

**Issue by maciejpedzich** [primefaces/primevue#1442]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/angry-pare-pii1r

**Current behavior**
"No PrimeVue toast provided" error is thrown, preceeded by "injection "Symbol()" not found." warning.

**Expected behavior**
Toast with given `severity`, `summary` and `details` should be displayed and automatically dismissed after `life` miliseconds.

**Minimal reproduction of the problem with instructions**
1. Make sure to register the `Toast` component and place it in root component's template
2. Import `useToast` anywhere in the application (ie. either in another component or a separate composable function) and call the `add` method, passing an object with properties specified above.

**Please tell us about your environment:**
System: Windows 10
Code editor: Visual Studio Code 1.59.0
Package manager: npm 6.14.5
Node.js version: 14.3.0

* **Vue version:** 3.0.0

* **PrimeVue version:** 3.6.4

* **Browser:** Google Chrome 92.0.4515.131

**Comment by tugcekucukoglu** [comment]
You also need to import ToastService.

main.js

```
import ToastService from 'primevue/toastservice';
app.use(ToastService);
```

**Comment by maciejpedzich** [comment]
Hmm... thought you needed it only when using the Options API, but thanks for clearing this up!

**Comment by simaotwx** [comment]
For me the solution was to put `app.mount("#app")` at the very end of the file.

**Comment by impronta48** [comment]
This is not working for me in Nuxt3
