### ISSUE TITLE
Floating the label when giving an input a value instead of v-model

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue#1444]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/happy-paper-09dd9?file=/src/App.vue

**Current behavior**
Giving a disabled inputtext a value renders the label not on top of the inputtext

**Expected behavior**
The same as giving an inputtext a v-model

**Please tell us about your environment:**
Windows + Npm + Vite

* **Vue version:** 3.X
Vue 3.2.1

* **PrimeVue version:** 3.4.X
3.6.4 (its been there longer, but I dont know for how long because I came from primevue 2.x

**Comment by tugcekucukoglu** [comment]
For Vue 3, components use modelValue as a prop. So InputText waits for modelValue not value.

[https://codesandbox.io/s/bold-mayer-pjzxu](https://codesandbox.io/s/bold-mayer-pjzxu)

**Comment by Jogai** [comment]
Okay, but then this behaviour is strange too. Its half working, half broken.
