### ISSUE TITLE
Dialog not working with 3.6.2

### ISSUE THREAD

**Issue by zulq** [primefaces/primevue#1445]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report 
```
https://codesandbox.io/s/trusting-glade-oeip8?file=/src/main.html

**Current behavior**
dialog.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'config' of undefined
    at Proxy.dialogClass

**Expected behavior**
Dialog to open.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **Vue version:** 3.2.1

* **PrimeVue version:** 3.6.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mertsincan** [comment]
Hi,

Could you please try https://codesandbox.io/s/modest-star-b5qn8 ?

**Comment by zulq** [comment]
Thanks a lot @mertsincan , that works. Think though they should update the docs.
