### ISSUE TITLE
Scrollable Tabs

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#1446]
https://www.primefaces.org/primevue/showcase/#/tabview
If tabs don't fit inside the card can you please make right and left buttons to scroll?
1. NAME1, NAME2 >     (If some push on > it will show  the next name witch will be NAME3)
2. < NAME2, NAME3 > (If some push on > it will show the next name witch will be NAME4)
if someone push on < it will show NAME1

**Comment by cagataycivici** [comment]
This was planned for sometime, adding it to the roadmap.

**Comment by agm1984** [comment]
Would be nice if TabMenu could support this as well
