### ISSUE TITLE
Set Paginator Page from InputNumber

### ISSUE THREAD

**Issue by omerciftcibasi** [primefaces/primevue#1447]
I'm submitting an issue related to paginator component, Is it possible to set paginator page manually from an InputText?

Currently there is a Jumpto template and it is possible to set page by using a dropdown.

I have 2M records and roughly 100K pages (20 rows per page), and I need to set the page by an InputNumber.

```
[ ] bug report
[X ] feature request 
[ X] support request 
```

**Comment by cagataycivici** [comment]
We can do jumptopage input for sure.

**Comment by cagataycivici** [comment]
Wrong commit, targeting 1481
