### ISSUE TITLE
How to Extend all the Props from Primevue in Vue3 Component

### ISSUE THREAD

**Issue by DnD2k21** [primefaces/primevue#1449]
Hey,

can i extend the Primevue Props into my Component?

I am getting this when i output it on console. But i want Props from this output and not everything.

<img width="620" alt="Bildschirmfoto 2021-08-13 um 14 10 26" src="https://user-images.githubusercontent.com/85512087/129355117-df2f0163-0fb8-42fd-8ca2-be68b53149c9.png">

My Code looks like this:
```
<script lang="ts">
   import { defineComponent } from "vue"
   import PrimeButton from "primevue/button"
 
   const Component = defineComponent({

     components: { PrimeButton },

     mounted() {
       console.log(PrimeButton)
     },
   })

   export default Component
</script>
```

**Please tell us about your environment:**
MAC. os Catalina 10.15, IDE: VSCodium 1.59, Node Modules 14.16.0

* **Vue version:** 3.0

* **PrimeVue version:** 3.5.1

* **Browser:** [all  ]

**Comment by cagataycivici** [comment]
Please use forum or discord for questions. Thank you.
