### ISSUE TITLE
Overlay panel doesn't render more than 1 array element (via v-for) if its inside an another array.

### ISSUE THREAD

**Issue by dcruz1990** [primefaces/primevue#1452]
Let me explain this scenario, i have a component that receive events as a props, each event have an array as a child prop. So, i'm v-foring in the parent array and inside it i'm trying to v-foring again into the child array prop.  This is the way i'm doing it:

```<template>
  <Dialog
    :visible="modelValue"
    :style="{ width: '350px', maxHeight: '500px' }"
    :modal="true"
    :closable="true"
    class="calendar-dialog"
    @update:visible="$emit('update:modelValue', false)"
  >
    <template #header>
      <h5 class="title">
        {{ events.length + " " }}
        {{ t('post')}}
      </h5>
    </template>

    <div
      v-for="e in events"
      :key="e.id"
      style="display: flex; align-items: center"
      class="event-item p-mt-2"
    >
      <img :src="e.extendedProps?.image" width="50" :alt="e.title" class="dialogThumb" />
      <div class="event-body" style="flex-grow: 1">
        <div class="title">
          <i v-if="!e.title" style="color: #ff0000" class="pi pi-exclamation-circle"></i>
          {{ e.title ? parseTitle(e.title, 60) : t("msg_no_caption") }}
        </div>
        <div class="date">{{ formatDate(e.date) }} </div>
      </div>
      <OverlayPanel ref="op">
        <div v-for="(item, index) in e.extendedProps?.socialMediaData" :key="index">
            {{ item.id }}
        </div>
      </OverlayPanel>
      <div class="actions">
        <i class="pi pi-pencil" @click="$emit('edit', e.id)" />
        <i class="pi pi-info-circle" @click="toggle"></i>
      </div>
    </div>
  </Dialog>
</template>
``` 

The child array is `e.extendedProps?.socialMediaData`, im checking the debugger and the data is there, but Overlay Panel only renders the first position. This is all dynamic, one event cant have for ex. 5 items in `socialMediaData` but only ones gets rendered.

If i provide a test array from my `setup()` its rendered ok. The thing is inside the outer `v-for`.  I'm using Vue3 + Comp Api + TypeScript and PrimeVue latest. 

What can i do?

**Comment by cagataycivici** [comment]
I remember there are some things to consider when using v-for and refs. Does this help;

https://stackoverflow.com/questions/52086128/vue-js-ref-inside-the-v-for-loop
