### ISSUE TITLE
bug ConfirmDialog (async accept\reject)

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1454]
When using await in the accept or reject functions, a crash occurs

I use it like this:
`
 this.$confirm.require({
              message: "123",
              header: "123",
              icon: "pi pi-exclamation-triangle",
              accept: () => {
                let res = await component.onAttach(event.files[i]);
              },
              reject: async () => {},
            });
`

![image](https://user-images.githubusercontent.com/16963395/129693533-31567dde-b044-49e1-aeea-75cf8e946d21.png)

![image](https://user-images.githubusercontent.com/16963395/129694075-dd054725-7a9a-4548-b50e-0a9f4c214df9.png)

`dialog.esm.js?5bd2:117 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at Proxy.onEnter (dialog.esm.js?5bd2:117)
    at callHook (runtime-dom.esm-bundler.js?830f:755)
    at eval (runtime-dom.esm-bundler.js?830f:798)
    at Object.enter (runtime-core.esm-bundler.js?5c40:1720)
    at Array.eval (runtime-core.esm-bundler.js?5c40:4158)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?5c40:7189)
    at flushJobs (runtime-core.esm-bundler.js?5c40:7226)`

* **Vue version:** 3.2.2

* **PrimeVue version:** 3.6.4

* **Browser:** [Chrome XX ]

**Comment by tugcekucukoglu** [comment]
What is your exact test case? I didn't replicate it with codesandbox sample. [In this example](https://codesandbox.io/s/amazing-ramanujan-5w10p?file=/src/App.vue) I didn't get any error.
