### ISSUE TITLE
OK or YES button for Calendar component in showTime mode

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#1462]
When showTime attribute is true, it would be better if there is a OK or YES button to confirm and exit the date picker dialog.

**Comment by mouadTaoussi** [comment]
When I chose a Date it exit for itself

**Comment by wanglin86769** [comment]
> 
> 
> When I chose a Date it exit for itself

But in showTime mode, it is another story. 
It does not exit when choosing a date since hour and minute also need to be chosen. Therefore, it is better to have a button to exit.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
