### ISSUE TITLE
[Dropdown] - enable the search the selected item does not show in the viewport

### ISSUE THREAD

**Issue by jzs11** [primefaces/primevue#1464]
Go to https://codesandbox.io/s/e4mep

Select 
![image](https://user-images.githubusercontent.com/2770401/130552841-8a12bbf6-69e7-4547-959f-ae20affe1f03.png)

Reopen
![image](https://user-images.githubusercontent.com/2770401/130552863-8f0a9ec7-71e9-48c6-b843-3feb0b310080.png)

Expected behavior: the Australia should show in the list when open the dropdown

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your screenshots! I think this issue has been fixed on 3.7.0.

For now, closed. If the problem persists, please reopen this issue. Thanks a lot for your understanding!

Best Regards,
