### ISSUE TITLE
Tooltip in SpeedDial/DockSub not working

### ISSUE THREAD

**Issue by webgyver** [primefaces/primevue#1466]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
No Tooltip visible for SpeedDial/DockSub, e.g. https://www.primefaces.org/primevue/showcase/#/speeddial "Tooltip" Demo

**Expected behavior**
e.g. https://www.primefaces.org/primereact/showcase/#/speeddial "Tooltip" Demo

**Maybe the problem...**
... usage of [`data-pr-tooltip`](https://github.com/primefaces/primevue/blob/6daa56c36b0349dc07751538257f011bdaa4ffee/src/components/speeddial/SpeedDial.vue#L10) instead of `v-tooltip`

* **Vue version:** 3.0.5
* **PrimeVue version:** 3.6.4
* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

Added `tooltipOptions` property to SpeedDial and Dock components. Please see;
https://github.com/primefaces/primevue/issues/1489
https://github.com/primefaces/primevue/issues/1490

Best Regards,
