### ISSUE TITLE
DataTable: Column Resizing is not stored as part of the state

### ISSUE THREAD

**Issue by JohnCampionJr** [primefaces/primevue#1469]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

Will work on this if needed

**Current behavior**
Columns are resized by user, but not saved or restored as part the state

**Expected behavior**
Expect column sizes to be saved and restored

**What is the motivation / use case for changing the behavior?**
Users will be confused why the grid changes between page loads

**Please tell us about your environment:**
VS Code, MacOS

* **Vue version:** 3.2

* **PrimeVue version:** 3.4.2

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Fixed for next version. Duplicate[#1311 ](https://github.com/primefaces/primevue/issues/1311)

**Comment by JohnCampionJr** [comment]
FWIW, I just tried this code locally and it does not solve the column resizing not being restored; might want to take another look.
The updated column widths are being saved to storage, but they seem to be reset there prior to being loaded.

**Comment by tugcekucukoglu** [comment]
Unfortunately, I couldn't replicate it. Could you please attach a codesandbox link for us to replicate?

**Comment by JohnCampionJr** [comment]
I would but I'm not sure how to edit the DataTable.vue component from a codesandbox.  I can't seem to get into the node_modules :)  I'll try later today to see if I can figure something out.

**Comment by tugcekucukoglu** [comment]
In the showcase there are codesandbox samples. [https://codesandbox.io/s/keg1s](https://codesandbox.io/s/keg1s)

Thanks,

**Comment by JohnCampionJr** [comment]
As I said, it is not working in 3.7.0.  See the codebox forked from the original issue.  It does not save/restore widths

https://codesandbox.io/s/datatable-scrollable-resizable-widthrestorenotworking-forked-b4i2z
