### ISSUE TITLE
Two columns for rowedit showing on adding a new custom column

### ISSUE THREAD

**Issue by Deepak2985** [primefaces/primevue#147]
![image](https://user-images.githubusercontent.com/36476799/72705493-9aabed00-3b81-11ea-8d5f-864b6121d998.png)

I am getting two row edit columns on adding a new Delete column

**Comment by cagataycivici** [comment]
Could you please share your code for review?

**Comment by Deepak2985** [comment]
<template>
  
<DataTable :value="cars" dataKey="vin" editMode="row" :editingRows.sync="editingRows" 
@row-edit-init="onRowEditInit" @row-edit-cancel="onRowEditCancel" :filters="filters" :reorderableColumns="true" 
@column-reorder="onColReorder" :paginator="true" :rows="10">
       <Column :rowEditor="true" headerStyle="width:6em" bodyStyle="text-align:center"></Column>
                <Column headerStyle="width: 8em" header="Delete" bodyStyle="text-align: center">
        <template #body="slotProps">
            <Button type="button" label="Delete" class="p-button-success" style="margin-right: .5em"></Button>
            <Button type="button" icon="pi pi-pencil" class="p-button-warning"></Button>
        </template>
    </Column>
    <Column field="vin" header="Vin" :sortable="true" filterMatchMode="contains">
        <template #filter>
            <InputText type="text" v-model="filters['vin']" class="p-column-filter" placeholder="Contains" />
        </template>
    </Column>
    <Column field="year" header="Year" :sortable="true" filterMatchMode="contains">
        <template #filter>
            <InputText type="text" v-model="filters['year']" class="p-column-filter" placeholder="Contains" />
        </template>
         <template #editor="slotProps">
            <InputText v-model="slotProps.data[slotProps.column.field]" />
        </template>
    </Column>
    <Column field="brand" header="Brand" :sortable="true" filterMatchMode="contains">
        <template #filter>
            <InputText type="text" v-model="filters['brand']" class="p-column-filter" placeholder="Contains" />
        </template>
        <template #editor="slotProps">
            <InputText v-model="slotProps.data[slotProps.column.field]" />
        </template>
    </Column>
     
    <Column field="color" header="Color" :sortable="true" filterMatchMode="contains">
        <template #filter>
          <InputText type="text" v-model="filters['color']" class="p-column-filter" placeholder="Contains" />
        </template>
        <template #editor="slotProps">
            <InputText v-model="slotProps.data[slotProps.column.field]" />
        </template>
    </Column>
    <template #empty>
        No records found.
    </template>
</DataTable>

</template>

<script>
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import InputText from 'primevue/inputtext';
import Vue from 'vue';

export default {
  name: 'HelloWorld',
  data() {
    return {
        filters: {},
        editingRows: [],
        cars:  [
        {"brand": "Volkswagen", "year": 2012, "color": "Orange", "vin": 1},
        {"brand": "Audi", "year": 2011, "color": "Black", "vin": 2},
        {"brand": "Renault", "year": 2005, "color": "Gray", "vin": 3},
        {"brand": "BMW", "year": 2003, "color": "Blue", "vin": 4},
        {"brand": "Mercedes", "year": 1995, "color": "Orange", "vin": 5},
        {"brand": "Volvo", "year": 2005, "color": "Black", "vin": 6},
        {"brand": "Honda", "year": 2012, "color": "Yellow", "vin": 7},
        {"brand": "Jaguar", "year": 2013, "color": "Orange", "vin": 8},
        {"brand": "Ford", "year": 2000, "color": "Black", "vin": 9},
        {"brand": "Fiat", "year": 2013, "color": "Red", "vin": 10},
        {"brand": "Renault", "year": 2005, "color": "Gray", "vin": 11},
        {"brand": "BMW", "year": 2003, "color": "Blue", "vin": 12},
        {"brand": "Mercedes", "year": 1995, "color": "Orange", "vin": 13},
        {"brand": "Volvo", "year": 2005, "color": "Black", "vin": 14},
        {"brand": "Honda", "year": 2012, "color": "Yellow", "vin": 15},
        {"brand": "Jaguar", "year": 2013, "color": "Orange", "vin": 16},
        {"brand": "Ford", "year": 2000, "color": "Black", "vin": 17},
        {"brand": "Fiat", "year": 2013, "color": "Red", "vin": 18},
        {"brand": "Renault", "year": 2005, "color": "Gray", "vin": 19},
        {"brand": "BMW", "year": 2003, "color": "Blue", "vin": 20},
        {"brand": "Mercedes", "year": 1995, "color": "Orange", "vin": 21},
        {"brand": "Volvo", "year": 2005, "color": "Black", "vin": 22},
        {"brand": "Honda", "year": 2012, "color": "Yellow", "vin": 23},
        {"brand": "Jaguar", "year": 2013, "color": "Orange", "vin": 24},
        {"brand": "Ford", "year": 2000, "color": "Black", "vin": 25},
        {"brand": "Fiat", "year": 2013, "color": "Red", "vin": 26}
    ],
    originalRows: [],
    }
  },
  components: {
      'DataTable': DataTable,
      Column,
     // MultiSelect,
      //Dropdown,
      InputText
  },
  methods: {
       onColReorder() {
           window.console.log("Order changed");
        },
         onRowEditInit(event) {
            this.originalRows[event.index] = {...this.cars[event.index]};
        },
        onRowEditCancel(event) {
           Vue.set(this.cars, event.index, this.originalRows[event.index]);
        },
        deleteRow(row){
            window.console.log(row);
        }
  }
}
</script>


<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

**Comment by Deepak2985** [comment]
`<template>
  
<DataTable :value="cars" dataKey="vin" editMode="row" :editingRows.sync="editingRows" 
@row-edit-init="onRowEditInit" @row-edit-cancel="onRowEditCancel" :filters="filters" :reorderableColumns="true" 
@column-reorder="onColReorder" :paginator="true" :rows="10">
       <Column :rowEditor="true" headerStyle="width:6em" bodyStyle="text-align:center"></Column>
                <Column headerStyle="width: 8em" header="Delete" bodyStyle="text-align: center">
        <template #body="slotProps">
            <Button type="button" label="Delete" class="p-button-success" style="margin-right: .5em"></Button>
            <Button type="button" icon="pi pi-pencil" class="p-button-warning"></Button>
        </template>
    </Column>
    <Column field="vin" header="Vin" :sortable="true" filterMatchMode="contains">
        <template #filter>
            <InputText type="text" v-model="filters['vin']" class="p-column-filter" placeholder="Contains" />
        </template>
    </Column>
    <Column field="year" header="Year" :sortable="true" filterMatchMode="contains">
        <template #filter>
            <InputText type="text" v-model="filters['year']" class="p-column-filter" placeholder="Contains" />
        </template>
         <template #editor="slotProps">
            <InputText v-model="slotProps.data[slotProps.column.field]" />
        </template>
    </Column>
    <Column field="brand" header="Brand" :sortable="true" filterMatchMode="contains">
        <template #filter>
            <InputText type="text" v-model="filters['brand']" class="p-column-filter" placeholder="Contains" />
        </template>
        <template #editor="slotProps">
            <InputText v-model="slotProps.data[slotProps.column.field]" />
        </template>
    </Column>
     
    <Column field="color" header="Color" :sortable="true" filterMatchMode="contains">
        <template #filter>
          <InputText type="text" v-model="filters['color']" class="p-column-filter" placeholder="Contains" />
        </template>
        <template #editor="slotProps">
            <InputText v-model="slotProps.data[slotProps.column.field]" />
        </template>
    </Column>
    <template #empty>
        No records found.
    </template>
</DataTable>

</template>

<script>
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import InputText from 'primevue/inputtext';
import Vue from 'vue';

export default {
  name: 'HelloWorld',
  data() {
    return {
        filters: {},
        editingRows: [],
        cars:  [
        {"brand": "Volkswagen", "year": 2012, "color": "Orange", "vin": 1},
        {"brand": "Audi", "year": 2011, "color": "Black", "vin": 2},
        {"brand": "Renault", "year": 2005, "color": "Gray", "vin": 3},
        {"brand": "BMW", "year": 2003, "color": "Blue", "vin": 4},
        {"brand": "Mercedes", "year": 1995, "color": "Orange", "vin": 5},
        {"brand": "Volvo", "year": 2005, "color": "Black", "vin": 6},
        {"brand": "Honda", "year": 2012, "color": "Yellow", "vin": 7},
        {"brand": "Jaguar", "year": 2013, "color": "Orange", "vin": 8},
        {"brand": "Ford", "year": 2000, "color": "Black", "vin": 9},
        {"brand": "Fiat", "year": 2013, "color": "Red", "vin": 10},
        {"brand": "Renault", "year": 2005, "color": "Gray", "vin": 11},
        {"brand": "BMW", "year": 2003, "color": "Blue", "vin": 12},
        {"brand": "Mercedes", "year": 1995, "color": "Orange", "vin": 13},
        {"brand": "Volvo", "year": 2005, "color": "Black", "vin": 14},
        {"brand": "Honda", "year": 2012, "color": "Yellow", "vin": 15},
        {"brand": "Jaguar", "year": 2013, "color": "Orange", "vin": 16},
        {"brand": "Ford", "year": 2000, "color": "Black", "vin": 17},
        {"brand": "Fiat", "year": 2013, "color": "Red", "vin": 18},
        {"brand": "Renault", "year": 2005, "color": "Gray", "vin": 19},
        {"brand": "BMW", "year": 2003, "color": "Blue", "vin": 20},
        {"brand": "Mercedes", "year": 1995, "color": "Orange", "vin": 21},
        {"brand": "Volvo", "year": 2005, "color": "Black", "vin": 22},
        {"brand": "Honda", "year": 2012, "color": "Yellow", "vin": 23},
        {"brand": "Jaguar", "year": 2013, "color": "Orange", "vin": 24},
        {"brand": "Ford", "year": 2000, "color": "Black", "vin": 25},
        {"brand": "Fiat", "year": 2013, "color": "Red", "vin": 26}
    ],
    originalRows: [],
    }
  },
  components: {
      'DataTable': DataTable,
      Column,
     // MultiSelect,
      //Dropdown,
      InputText
  },
  methods: {
       onColReorder() {
           window.console.log("Order changed");
        },
         onRowEditInit(event) {
            this.originalRows[event.index] = {...this.cars[event.index]};
        },
        onRowEditCancel(event) {
           Vue.set(this.cars, event.index, this.originalRows[event.index]);
        },
        deleteRow(row){
            window.console.log(row);
        }
  }
}
</script>


<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
`

**Comment by Deepak2985** [comment]
[Datatable.txt](https://github.com/primefaces/primevue/files/4084882/Datatable.txt)
I have added the code in the above text file

**Comment by cagataycivici** [comment]
Please add a columnKey to the columns as it is mandatory to resolve the problem, docs are updated as well.

```xml
       <Column columnKey="editor" :rowEditor="true" headerStyle="width:6em" bodyStyle="text-align:center"></Column>
                <Column columnKey="actions" headerStyle="width: 8em" header="Delete" bodyStyle="text-align: center">
        <template #body="slotProps">
            <Button type="button" label="Delete" class="p-button-success" style="margin-right: .5em"></Button>
            <Button type="button" icon="pi pi-pencil" class="p-button-warning"></Button>
        </template>
    </Column>
```
