### ISSUE TITLE
DataTable export documentation

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1479]
Please add an example and documentation for creating a custom upload method in csv.

I have a table and I want to export some columns in a different way, and hide some.

The wiki does not currently have detailed documentation and examples on this matter.

**Comment by mertsincan** [comment]
Hi,

PrimeReact has a similar example. Please examine pdf and xls export. Like them, you can create a custom csv method according to your needs.

https://primefaces.org/primereact/showcase/#/datatable/export

Best Regards,

**Comment by tomastan** [comment]
As it looks the showcase is not available anymore, it there any other source to investigate?

> PrimeReact has a similar example. Please examine pdf and xls export. Like them, you can create a custom csv method according to your needs.
> 
> https://primefaces.org/primereact/showcase/#/datatable/export
