### ISSUE TITLE
bug in dock component

### ISSUE THREAD

**Issue by AndresArronaM** [primefaces/primevue#1492]
```
[ *] bug report
[ ] feature request 
[ ] support request 
```
** Description

I am using the Dock component and when including the modelItems variable, in the prop :model the google chrome console generates this error

![dcdc](https://user-images.githubusercontent.com/33308214/131520762-a50189e4-4d1e-410c-98d6-785f5d745c78.png)

**Please tell us about your environment: 
IDE Visual Studio
CLI Vue Cli

* **Vue version:** 3.0.4

* **PrimeVue version: 3.6.4

* **Browser:** Chrome

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it. Could you please attach a sample codesandbox link?

Best Regards,

**Comment by mertsincan** [comment]
Hi,

Please try the latest PrimeVue version. 

For now, closed. If the problem persists, please reopen this ticket. Thanks a lot for your understanding!
Best Regards,
