### ISSUE TITLE
FileUpload Documentation is misleading

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primevue#1497]
Hello,

There are a few mix-ups with the API Documentation of the [FileUpload](https://www.primefaces.org/primevue/showcase/#/fileupload):

![image](https://user-images.githubusercontent.com/17595640/131863629-936b3d18-d62e-4070-937c-75075d5711fa.png)

Also, it is not immediately apparent which events will fire with and without the custom uploader. 

Cheers

**Comment by tugcekucukoglu** [comment]
It's fixed.

Thanks,
