### ISSUE TITLE
Dropdown and MultiSelect on expand event

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#150]
I am missing a small feature on the `Dropdown` and `MultiSelect` components. I would like to load a list of options when the dropdown is being expanded first time, not on page load.
So I can see if I pass the selected value as `{ id: 123, name: "Bla-bla" } the name is already included so it will be visible without necessity of loading the list.
1. Currently if value is present but list is not loaded Dropdown shows empty field (even when my name is present in the value object).
2. Would be nice to have a spinner on the expanded area while items are loaded (not a big deal).
3. It might be an event `on-expand` or something. So when that happens I can check if options are loaded. If they're not I can load the list of options.

Please let me know what do you think guys.

**Comment by cagataycivici** [comment]
We'll add show and hide events to both of the components.

**Comment by fairking** [comment]
Thanks @cagataycivici

**Comment by fairking** [comment]
Loading the list on expand I meant  loading from the server, so the will be some delay when options are expanded. Thanks.

**Comment by cagataycivici** [comment]
I agree, once you confirm that it works we can later add a loading prop with a loading icon so the users can be notified during loading process.

**Comment by cagataycivici** [comment]
There are now;

- before-show
- before-hide
- show
- hide

**Comment by fairking** [comment]
Thanks @cagataycivici  I will be in touch as I am going to create such functionality to load dropdown options only when user expands it.
