### ISSUE TITLE
Checkbox docs

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1503]
check:  ttps://www.primefaces.org/primevue/showcase/#/checkbox

![image](https://user-images.githubusercontent.com/16963395/132216849-91567aa1-efde-442f-90ff-49f3e6805b2f.png)

**Comment by tugcekucukoglu** [comment]
<img width="1202" alt="checkbox" src="https://user-images.githubusercontent.com/32294991/132222985-234b938f-a799-4d4a-b60c-95afed5f4281.png">
