### ISSUE TITLE
Responsive DataTable Loses Filtering and Sorting

### ISSUE THREAD

**Issue by morpc-gohio** [primefaces/primevue#1504]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request 
[ ] support request
```
**Current behavior**
When configuring a DataTable with responsiveLayout="stack", any filtering and ordering capabilities configured on the table is lost. Upon inspection using developer tools in Chrome, it looks like display: none styling is applied to the cells of the table header. Removing that style shows the header and the filters and ordering still works, which is not really a surprise.

**Expected behavior**
Filtering and ordering capability should not be hidden when the responsive layout is stacked.  The UI for filtering and sorting should also be responsive along with the table data. If there is something I'm missing, please reply to the following forum post:

https://forum.primefaces.org/viewtopic.php?f=110&t=68444&p=193799&hilit=datatable+filter#p193799

* **Vue version:** 3.1.1

* **PrimeVue version:** 3.7.1

**Comment by agostinodd** [comment]
Happens also for defined ColumnGroups within a datatable.

**Comment by CWSpear** [comment]
I don't mean to detract/necro an old thread, but I don't see `responsiveLayout` [in the docs](https://primevue.org/datatable/#api.datatable.props)? Was this removed? (Current version: 3.34.1)

**Comment by mertsincan** [comment]
Yes, please see; https://github.com/primefaces/primevue/issues/3682

Best Regards,
