### ISSUE TITLE
InputNumber: the ability to customize the suffix and prefix

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1507]
Add the ability to change the css or classes css for prefix and suffix to InputNumber.

I want to make the suffix smaller and gray semi-transparent, is there a way to do that now?

Thank you in advance, primevue is really cool

**Comment by mertsincan** [comment]
Hi,

Unfortunately, it isn't possible. InputNumber uses Intl.NumberFormat API; 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

But, I think you can use <InputNumber mode="decimal" locale="..."> and inputgroup structure for this issue. 
https://primefaces.org/primevue/showcase/#/inputgroup

I'll add a method for you to find currency symbol in the next version. Details;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

Exp;
```
<div class="p-inputgroup">
        <InputNumber ref="myRef" v-model="value" mode="decimal" locale="en-US" />
        <span class="p-inputgroup-addon">{{currencySymbol}}</span>
</div>

computed: {
     currencySymbol() {
             const parts = this.$refs.myRef.getFormatter(). formatToParts(1111.11);
             return parts.filter(p => p.type === "currency").value;
     }
}
```
Best Regards,
