### ISSUE TITLE
Tooltip: crash when empty\null

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1511]
If v-tooltip is null or undefined, it will crash

Expected Behavior: if null or empty, do not show the tooltip at all

How to call: v-tooltip = "null" (In my project I do this v-tooltip = "data.value? Data.value: null")

![image](https://user-images.githubusercontent.com/16963395/132334826-a5099f74-ce33-4a41-a1bd-859766769d51.png)

![image](https://user-images.githubusercontent.com/16963395/132334096-8fbf5036-3f31-43a5-9b83-669b436827e6.png)

If there is no data, it is better not to show the hint at all (The photo looks like now if there is no data):
![image](https://user-images.githubusercontent.com/16963395/132336990-62823ba9-26e0-4ad8-b876-a8da4e6e675d.png)

codesandbox:
https://codesandbox.io/embed/cool-leaf-hyg2g?fontsize=14&hidenavigation=1&theme=dark

**Comment by shljshlj** [comment]
This should be fixed in PrimeVue for Vue 2 (breaking in v2.9.0)
