### ISSUE TITLE
Dropdown Bug - scrollValueInView when using filtering

### ISSUE THREAD

**Issue by cyfung1031** [primefaces/primevue#1517]
In Dropdown.vue,
for `onOverlayEnter(el)` method,
```
...
            this.scrollValueInView();
            this.alignOverlay();
...
```
sometimes it can make weird behavior to the scrollTop of the page.
I don't really have a code for reproduction, but it does happen for my project.

Sample Coding
```
<template>
<div style="background:gray; height:560px;"></div>
    <div> 
 
        <Dropdown v-model="selectedCountry" :options="countries" optionLabel="name" :filter="true" placeholder="Select a Country" :showClear="true">
            <template #value="slotProps">
                <div class="country-item country-item-value" v-if="slotProps.value"> 
                    <div>{{slotProps.value.name}}</div>
                </div>
                <span v-else>
                    {{slotProps.placeholder}}
                </span>
            </template>
            <template #option="slotProps">
                <div class="country-item"> 
                    <div>{{slotProps.option.name}}</div>
                </div>
            </template>
        </Dropdown>

    </div>
<div style="background:gray; height:560px;"></div>
</template>

<script>
import { ref } from 'vue';

export default {
    setup() {
        const selectedCountry = ref();
        const countries = ref([
            {name: 'Australia', code: 'AU'},
            {name: 'Brazil', code: 'BR'},
            {name: 'China', code: 'CN'},
            {name: 'Egypt', code: 'EG'},
            {name: 'France', code: 'FR'},
            {name: 'Germany', code: 'DE'},
            {name: 'India', code: 'IN'},
            {name: 'Japan', code: 'JP'},
            {name: 'Spain', code: 'ES'},
            {name: 'United States', code: 'US'}
        ]);


        return { selectedCountry, countries}
    },
    methods: {
    }
}

</script>

<style> 
</style>
```

My project use tailwindcss too, but not sure whether it is related to this issue.

https://user-images.githubusercontent.com/44498510/132397447-c43f4eb8-e1c2-4964-8dc4-6139739274cb.mp4

I have tried to change the css but in vain. After that,  I found some fixs for this issue.

1) set `modelValue = null` at the begining of `.show()`
this is success but changed the plugin behavior

2) to swap these two lines. I am happy with this solution but not sure whether it is suitable for all cases.

```
...
            this.alignOverlay();
            this.scrollValueInView();
...
```

**Comment by BurnashevDmitry** [comment]
Yes, the same. Also, when Dropdown in the end of page and you enter characters, it do like this:

![Screenshot 2021-09-08 at 09-56-45 PrimeVUE](https://user-images.githubusercontent.com/34347595/132444226-6301185d-6a46-4ad7-bd70-8e0013ad38dc.png)

**Comment by cyfung1031** [comment]
> Yes, the same. Also, when Dropdown in the end of page and you enter characters, it do like this:
> 
> ![Screenshot 2021-09-08 at 09-56-45 PrimeVUE](https://user-images.githubusercontent.com/34347595/132444226-6301185d-6a46-4ad7-bd70-8e0013ad38dc.png)

Yes I have this problem too. But for my case I can just make the input field wider to eliminate this issue.
This is because the width of filter input is wrong. 

Besides, there is the arrow up/down key problem when using filter.
I have modified it and perhaps I will make a new component for it.

The implementation of [combobox in vuetify](https://vuetifyjs.com/en/components/combobox/) is indeed better. Using an extract input field is a bad idea and not align with the common user practice.

**Comment by mertsincan** [comment]
Hi,

I think this issue has been fixed in 3.7.1. Could you please try it?

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,

**Comment by cyfung1031** [comment]
> Hi,
> 
> I think this issue has been fixed in 3.7.1. Could you please try it?
> 
> For now, closed. If the problem persists, please reopen this ticket.
> Best Regards,

Correct. The bug is fixed in 3.7.1. I used 3.7.0 due to the (official setup guideline](https://primefaces.org/primevue/showcase/#/setup).

**Comment by BurnashevDmitry** [comment]
> 
> 
> Hi,
> 
> I think this issue has been fixed in 3.7.1. Could you please try it?
> 
> For now, closed. If the problem persists, please reopen this ticket.
> Best Regards,

Upgraded to 3.7.1, bug fixed for Chrome, but still remain in Firefox

**Comment by mertsincan** [comment]
Thanks a lot for the updates!

@BurnashevDmitry, this ticket is not related to your issue. Could you please create a new issue for it?

Best Regards,

**Comment by BurnashevDmitry** [comment]
> 
> 
> @BurnashevDmitry, this ticket is not related to your issue. Could you please create a new issue for it?
> 
> Best Regards,

Ok, today I'll open issue for this, thanks.
