### ISSUE TITLE
DataTable doesn't work as expected when the container is resized.

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1521]
When resizing the container, the table does not expand automatically

https://codesandbox.io/embed/nameless-water-lpvgm?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/16963395/132480405-a7090658-e776-4ee5-a3af-7764e77ca5d0.png)

https://codesandbox.io/embed/nameless-water-lpvgm?fontsize=14&hidenavigation=1&theme=dark
![image](https://user-images.githubusercontent.com/16963395/132481219-fae9dc14-5ddf-4b64-a41b-a55cab3d34e1.png)
![image](https://user-images.githubusercontent.com/16963395/132481261-3ade99f7-06e1-4626-b28f-2d8b11175212.png)

Also the problem with showGridlines in my project

![image](https://user-images.githubusercontent.com/16963395/132478819-2310dd8e-5c20-495e-bbb4-156d7592a126.png)

![image](https://user-images.githubusercontent.com/16963395/132478954-94d49d48-dff7-45a7-af05-901221fd9d51.png)

![image](https://user-images.githubusercontent.com/16963395/132479082-526ffbaa-5e7d-4054-bb84-88837e903673.png)

When data is refreshed or when a group is expanded, the size returns to normal

![image](https://user-images.githubusercontent.com/16963395/132479409-8fb44fe4-e675-42bf-997f-693acea17f07.png)

When resizing back, a scroll appears (Although the table should have shrunk without scrolling)

![image](https://user-images.githubusercontent.com/16963395/132479604-a9d94518-fecc-41ec-bebd-18bb5c64a774.png)

One more thing with showGridlines

![image](https://user-images.githubusercontent.com/16963395/132479843-27279a93-035a-4dd7-a66e-907ec575fe7e.png)

**Comment by tugcekucukoglu** [comment]
> I think the issue still exists,
> 
> https://primefaces.org/primeng/showcase/#/table/colresize
> 
> At first, it works well, but when the column resizer is clicked, it crashes the table container and does not work properly!
> 
>  New.Recording.-.10_15_2021.10_29_20.AM.mp4

Please create a ticket for PrimeNG so we can not miss the good catches.
