### ISSUE TITLE
Date Range Picker Component [Feature Request]

### ISSUE THREAD

**Issue by TuguldurJ** [primefaces/primevue#1524]
**Current behavior**
Date picker's range has only within one month.
https://i.imgur.com/dtYhJyS.png
https://primefaces.org/primevue/showcase/#/calendar

**Expected behavior**
We need choose date range from two date pickers. for example.
http://www.daterangepicker.com/#example1

**What is the motivation / use case for changing the behavior?**
I think this is a critical feature for customers. If you need to reserve a room or choose the days available from August 20 to September 14, now that is impossible. This is a real world problem.

**Comment by mertsincan** [comment]
Hi,

Did you try numberOfMonths property?
```
<Calendar id="range" v-model="dates2" selectionMode="range" :manualInput="false" :numberOfMonths="2"  />
```

**Comment by TuguldurJ** [comment]
I did not see option. Thank you!
