### ISSUE TITLE
PanelMenu subItems 'to' route configuration breaks menu rendering

### ISSUE THREAD

**Issue by arjendekivet** [primefaces/primevue#1536]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When configuring a 'to' on a menu subitem, the menu breaks

**Expected behavior**
Menu not breaking and navigating to configured 'to' route.

**Minimal reproduction of the problem with instructions**
** Sandbox **
https://codesandbox.io/s/priceless-orla-d6iyc?file=/src/App.vue

**Please tell us about your environment:**

* **Vue version:** 3.2.6

* **PrimeVue version:** 3.7.0

* **Browser:** All
 
* **Suggested Fix**: 
in panelmenu.js on line 124:
 "aria-expanded": isActive(item)
 should be:
 "aria-expanded": $options.isActive(item)
 Resolves the issue for me.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your suggestion! Fixed now!

Best Regards,

**Comment by randybrutal** [comment]
same bug is still in 2.8.0

**Comment by tugcekucukoglu** [comment]
This fix for PrimeVue 3 but it will be ported for v2. 

Thanks,

**Comment by randybrutal** [comment]
I create a pull request 10 minutes ago.
Hope you team merge soon
Thanks!

**Comment by tugcekucukoglu** [comment]
Could create a different issue? So we could not miss anything.

Thanks!

**Comment by randybrutal** [comment]
Create a new already!
Thanks!
