### ISSUE TITLE
BlockUI doesn't get rid of div

### ISSUE THREAD

**Issue by Rpgilligan85** [primefaces/primevue#1537]
Current behavior
BlockUI div still exist and is overtop of everything. Looks like the z-index needs to be reset

Expected behavior
BlockUI div needs to go behind everything.

Minimal reproduction of the problem with instructions
It doesn't work on the docs site.
https://primefaces.org/primevue/showcase/#/blockui

Please tell us about your environment:

Vue version: 3.2.6
PrimeVue version: 3.7.1

Browser: All

Suggested Fix:
Have it update the z-index

**Comment by morpc-gohio** [comment]
I'm seeing the same issue in my project using v3.7.1. 

Until this is officially fixed, I am using:

document.querySelectorAll(".p-blockui").forEach((el) => el.remove());

to get around it.

**Comment by garp360** [comment]
Issue still exists with
"primeflex": "^3.1.3",
"primeicons": "^5.0.0",
"primevue": "^3.12.6",

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it at https://primefaces.org/primevue/showcase/#/blockui Could you please create a new ticket with codesandbox sample?

Best Regards,
