### ISSUE TITLE
Enquiry - Any Theme for the Floating Label like Google?

### ISSUE THREAD

**Issue by cyfung1031** [primefaces/primevue#1539]
![ascdvergtb](https://user-images.githubusercontent.com/44498510/132944996-fdb2c7b0-a96e-4425-a972-ad60e504fbe8.png)

Any Theme for the Floating Label like Google?
Or how can I modify the floating label setting for such effect??

**Comment by mertsincan** [comment]
Hi,

You can use Material Themes and review https://primefaces.org/primevue/showcase/#/floatlabel. Please use configurator at showcase to test effects.

Please see the list of all free themes;
https://primefaces.org/primevue/showcase/#/setup

Best Regards,
