### ISSUE TITLE
Text color of disabled primary button

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#154]
Strange the primary button has a different color from the secondary one.
I checked the css looks like it is coming from the primevue styles.
See the screenshot.
![image](https://user-images.githubusercontent.com/13495631/72873412-aadddc80-3ce7-11ea-8ccb-7f6f1dc94059.png)

**Comment by cagataycivici** [comment]
Disabled styles depend on the theme, which theme are you using? Can you also please post your button code so we can run it on our side?

**Comment by fairking** [comment]
I am using the following styles:
```
import "primevue/resources/themes/nova-light/theme.css";
import "primevue/resources/primevue.min.css";
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";
import "@fullcalendar/core/main.min.css";
import "@fullcalendar/daygrid/main.min.css";
import "@fullcalendar/timegrid/main.min.css";
```
My button code looks like that:
```
<Button label="Cancel" type="button" class="p-button-secondary pull-right" style="width:auto;" @click="cancelSubmit()" />
<Button label="Save draft" type="submit" class="p-button-secondary pull-right" style="width:auto;" :disabled="!isFormDirty" />
<Button label="Publish" type="button" class="p-button-success pull-right" style="width:auto;" :disabled="!isFormDirty" @click="publishSubmit()" />
```
Th value `isFormDirty` is false.

**Comment by cagataycivici** [comment]
![Screen Shot 2020-01-30 at 11 15 42](https://user-images.githubusercontent.com/686247/73431613-e284fe00-4351-11ea-8c6a-b83485aebd5b.png)

It seems ok for me

**Comment by fairking** [comment]
@cagataycivici 
Apologize guys. It was my fault. Next time I will be more careful before post any issues here to safe your time.
