### ISSUE TITLE
Give better credit to code taken from other authors

### ISSUE THREAD

**Issue by kramer99** [primefaces/primevue#1540]
While I am flattered that you guys deemed my component https://github.com/kramer99/vue-knob-control good enough to include in your UI component collection, and you were good enough to put a mention of where you got it from on line 210 (https://github.com/primefaces/primevue/blob/master/src/components/knob/Knob.vue#L210), I do think it would be fair of you to move that to the top of the file and replace the word "inspired" with "derived", or something similar, as it's pretty clear from a side by side comparison that this was a copy-paste-edit.

Obviously this is all open source, so you're under no obligation to do anything, but as the original creator of the component, you would have my thanks.

PrimeVue does look like a great component library, by the way. Congratulations on the good work.

**Comment by cagataycivici** [comment]
Thank you for reaching us out, vue-knob-control is really great and helped us to include a knob component to the suite. I've added more information about it and added referrals to main docs of the component as well. Thank you.

**Comment by kramer99** [comment]
> Thank you for reaching us out, vue-knob-control is really great and helped us to include a knob component to the suite. I've added more information about it and added referrals to main docs of the component as well. Thank you.

👍 Thank you, I appreciate it.
