### ISSUE TITLE
Sidebar Mask not being removed from DOM on close

### ISSUE THREAD

**Issue by nirmalgenji** [primefaces/primevue#1541]
The the mask (a div element with class p-sidebar-mask) is added to DOM but it is not removed.
Referred document:https://primefaces.org/primevue/showcase/#/sidebar
Issue with Primevue version: 3.7.1 , also checked with 3.3.2
JS framework: Vue3

Verified with existing issue logs:
https://github.com/primefaces/primevue/issues/329
https://github.com/primefaces/primevue/issues/869
and a fix: https://github.com/primefaces/primevue/commit/e12f3ff08a97b06256a7a2785ef56cd0982c96e7
Still not getting the root cause.

Code:

> 

        import Sidebar from 'primevue/sidebar';
        <Sidebar v-model:visible="visibleHelpPanel" position="right">
	        Content
        </Sidebar>
       const visibleHelpPanel = ref(false);
     

>

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate this issue. Could you please attach a codesandbox link for us? Also, does Dialog with mask work for you? If yes, we can make the changes according to Dialog.

Best Regards,

**Comment by Mirko92** [comment]
I have the same problem. 
But in CodeSandbox and Stackblitz, I cannot replicate it.

Any ideas ?

**Comment by nirmalgenji** [comment]
Hello mertsincan,

Yes Dialog with mask is working perfectly fine.
Also, I cannot replicate the issue on CodeSandbox.

**Comment by nirmalgenji** [comment]
Issue is not yet resolved. I did try with new Vue3 Project as well.
Can someone guide with the same?

**Comment by Mirko92** [comment]
I think your Css files is old. 

Maybe, It is missing these classes:
```
.p-component-overlay-enter {
    animation: p-component-overlay-enter-animation 150ms forwards;
}

.p-component-overlay-leave {
    animation: p-component-overlay-leave-animation 150ms forwards;
}

.p-component-overlay {
    @keyframes p-component-overlay-enter-animation {
        from {
            background-color: transparent;
        }
        to {
            background-color: var(--maskbg);
        }
    }
    
    @keyframes p-component-overlay-leave-animation {
        from {
            background-color: var(--maskbg);
        }
        to {
            background-color: transparent;
        }
    }
}
```

**Comment by nirmalgenji** [comment]
Okay. It's working. What i did is, updated _sidebar.scss to add above css. I am using saga-blue theme with premium feature.
But It was working previously. Is there any changes to new primevue version 3.7.1. ?

**Comment by tugcekucukoglu** [comment]
A new transition added [#1491](https://github.com/primefaces/primevue/issues/1491)

Thanks for the update.

**Comment by reksc** [comment]
I had the same issue with Calendar component with `touchUI` enabled. Hours of debugging, found that `animationend` was not firing. Found this issue. Yeap - it's all due to missing CSS classes 😄 🤦‍♂️ .
