### ISSUE TITLE
[BUG] Datatable reorder not work on mobile browsers

### ISSUE THREAD

**Issue by arnyee** [primefaces/primevue#1543]
[X ] bug report => Search github for a similar issue or PR before submitting

Hello primevue team.

I think I found a bug, or it might not be part of the feature I hope the former and you can help me. The DataTable component has a rowReorder function which is very cool but does not work at all in mobile browsers.  I think it would be nice if there was a solution/possibility for this.
https://primefaces.org/primevue/showcase/#/datatable/reorder

I hope you can help me as soon as you can.

**Comment by namcodes** [comment]
thank you guy
I also have the same problem
I switched from Ag-grid-vue to here because the table was added resize,reoder, scrool group

**Comment by FossPrime** [comment]
This is pretty much unfixable at the moment.

None of these work:
https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/HTMLElement/drag_event/_sample_.drag_and_drop_example.html
https://web.dev/drag-and-drop/
https://stackblitz.com/edit/bug-primevue-datatable-reorder-mobile?file=README.md

Chrome is working on this and things should be better by 109

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
