### ISSUE TITLE
Can not target dropdown/mutiselect options with CSS depending on parent class. 3.0.2-3.7.1 migration

### ISSUE THREAD

**Issue by songoo** [primefaces/primevue#1546]
Hello, After update from 3.0.2 to 3.7.1 I can not to target muliselect/dropdown options with css depending on parent class. Seems that muliselect/dropdown options are now not physicaly in component html, but are attached to end of `<body>`, outside of my defined` <div> `container, so my css is not able to target it depending on container class.

Is there any config to keep options html inside components as was in 3.0.2, or any way to specify/target css of dropdown options depending on parent class ?

**Current behavior**
```
          <div class="red-container">
              <Dropdown v-model="dropSelect" :options="yesNo" optionLabel="name" optionValue="code" />
          </div>
```
with style
```
.red-container .p-dropdown-item{
 color : red
}
```
Does nothing, since .p-dropdown-item is not actually inside of .red-container, but at end of the body with absolute position

**Expected behavior**
Red text at dropdown/multiselect options

**Minimal reproduction of the problem with instructions**
Any dropdown on current guide page https://www.primefaces.org/primevue/showcase/#/dropdown behave same, options are as block attached on end of the body.

Migration from
```
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primevue": "^3.0.2",
```
to
```
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primevue": "^3.7.1",
```
-->

**What is the motivation / use case for changing the behavior?**
I switch several classes for container `<div class="class1-7">` , and have defined css changes to primevue components inside depending on it, but with options being outside of container have a bit of trouble targeting them and doing migration from 3.0.2 since all my themes are broken being unable to target that parts.

**Please tell us about your environment:**
Phpstorm

* **Vue version:** ^3.0.0

* **PrimeVue version:** 3.7.1

* **Browser:** Chrome

Btw, Thank You very much for awesome work :-) this is one of my favorite v3 libraries :P

**Comment by tugcekucukoglu** [comment]
Hello,

Dropdown and MultiSelect and some other components append to body by default. With PrimeVue 3.3.3, these components start to use [Teleport](https://v3.vuejs.org/guide/teleport.html#using-with-vue-components). So you don't need to cover your code with .red-container to add style in App.vue or your css/scss file.

Thanks for your great feedback.

Regards,

**Comment by songoo** [comment]
Hello, tnx for answer, but is there any way I could target Teleported content with css depending of parent class? For now its seems kind of impossible since html is taken out of its position :( , as mentioned all my themes got broken and somehow am also not able to fix them since do not see any way ?

But for time being tnx for answer I at least will jump from 3.0.2 to 3.3.2.

**Comment by songoo** [comment]
Just note, solution for this is here https://github.com/primefaces/primevue/issues/1550 .
