### ISSUE TITLE
Hi @cagataycivici cagataycivici, i need help.. Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by rafaelguillermo** [primefaces/primevue#1547]
I have bought the template https://www.primefaces.org/sapphire-vue

I am very happy with it. I am finishing my development, I wanted to do a test on a productive server, using https://www.netlify.com/
The deployment was correct, but when executing the application I get an error which I have not been able to solve, I have investigated, updated some libraries, but the error persists.

![image](https://user-images.githubusercontent.com/5187027/133722619-90cc2c13-3870-4b8c-a673-e29428e76f74.png)

the line #9 is 
<div class="layout-topbar-separator"></div>

![image](https://user-images.githubusercontent.com/5187027/133722815-a8ef89ef-8944-4698-9a44-35840f8f3c34.png)

I used Amazon AWS to install everything manually, but the error persists, I have made all possible updates.

Can you help me find a solution, please.

URL
https://angry-hamilton-85b388.netlify.app/

Amazon AWS
http://3.17.147.20:8080/

package.json

{
 "name": "manoo",
 "version": "3.1.0",
 "private": true,
 "scripts": {
  "serve": "vue-cli-service serve",
  "build": "vue-cli-service build",
  "lint": "vue-cli-service lint",
  "test:unit": "vue-cli-service test:unit"
 },
 "devDependencies": {
  "@vue/cli-plugin-babel": "~4.5.0",
  "@vue/cli-plugin-eslint": "~4.5.0",
  "@vue/cli-plugin-router": "~4.5.0",
  "@vue/cli-plugin-unit-jest": "~4.5.0",
  "@vue/cli-service": "~4.5.0",
  "@vue/compiler-sfc": "^3.0.0",
  "@vue/test-utils": "^2.0.0-0",
  "babel-core": "7.0.0-bridge.0",
  "babel-eslint": "^10.0.1",
  "babel-jest": "^25.0.0",
  "eslint": "^6.7.2",
  "eslint-plugin-vue": "^7.0.0-0",
  "node-sass": "^4.12.0",
  "sass-loader": "^8.0.2"
 },
 "dependencies": {
  "@fullcalendar/core": "4.0.2",
  "@fullcalendar/daygrid": "4.0.1",
  "@fullcalendar/interaction": "4.0.2",
  "@fullcalendar/timegrid": "4.0.1",
  "@vuelidate/core": "^2.0.0-alpha.25",
  "@vuelidate/validators": "^2.0.0-alpha.21",
  "axios": "^0.21.4",
  "chart.js": "2.7.3",
  "core-js": "^3.6.5",
  "crypto-js": "^4.1.1",
  "primeflex": "2.0.0",
  "primeicons": "4.1.0",
  "primevue": "3.3.4",
  "prismjs": "^1.15.0",
  "vue": "3.0.6",
  "vue-i18n": "^9.1.7",
  "vue-router": "^4.0.0-0",
  "webpack": "^4.46.0"
 }
}

**Comment by tugcekucukoglu** [comment]
Please use the [https://forum.primefaces.org/viewforum.php?f=105](forum) for questions and help requests.
