### ISSUE TITLE
DataTable and filter date (data type)

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1548]
Please add a check or conversion to new Date () to the date filtering

i use 

```
 <Column headerStyle="width: 9em !important;" :maxConstraints="5" field="noteDate" sortable dataType="date" :header="$t('TypeDate')">
<template #body="{ data }">
                  {{ dateToShort(data.noteDate) }}
                  <p class="text-secondary" v-if="data.noteDate">
                    {{ getTimeText(new Date(data.noteDate)) }}
                  </p>
                </template>
<template #filter="{ filterModel }"> <Calendar v-model="filterModel.value" /> 
</template></Column>
```

and I get

![image](https://user-images.githubusercontent.com/16963395/133727525-4f7e2922-f41e-4482-85f0-804a181884f9.png)

You can add a setting to Column for automatic new Date () or always do new Date () or check for data type

My project has a lot of dates (strings, etc.) and it is difficult to keep track of what type is passed to the DataTable, it would be nice if primevue did new Date () itself

**Comment by tugcekucukoglu** [comment]
There is an [example](https://codesandbox.io/s/ch1os?file=/src/DataTableDemo.vue) for the format date. What is your exact test case? It's hard to demonstrate the issue without codesandbox example.

**Comment by NeluQi** [comment]
> There is an [example](https://codesandbox.io/s/ch1os?file=/src/DataTableDemo.vue) for the format date. What is your exact test case? It's hard to demonstrate the issue without codesandbox example.

example:
https://codesandbox.io/embed/sparkling-bird-jikle?fontsize=14&hidenavigation=1&theme=dark


if you remove it, there will be a crash. I propose to do the data conversion in the most for convenience
![image](https://user-images.githubusercontent.com/16963395/133740461-feeaa979-1b61-416e-8369-532780346526.png)

**Comment by tugcekucukoglu** [comment]
To format the date or any kind of data can cause performans issue for DataTable component. For now, there is no any plan for this.
