### ISSUE TITLE
Using #body and #edit templates in a Datatable Column

### ISSUE THREAD

**Issue by mrichar1** [primefaces/primevue#155]
I'm currently using the `DataTable` component and want to add 2 templates to a `Column` - a `#body` template to present a modified 'view' on the underlying data, and then a `edit` template that uses the real data. For example, the cell should display a rounded integer, but when editing the full float will be available.

When I add both `#body` and `#edit` templates, the `#body` template is positioned 'on top' and receives the clicks, so that the underlying column event never fires, and the `TextInput` field never appears. The solution is to click on the edge of the cell, so as to hit the underlying `<td>` parent, which isn't intuitive.

My Column code currently looks like this:

```
<Column  field="rows"  header="Rows">
  <template #body="slotProps">
    <span>{{ roundValue(slotProps.data[slotProps.column.field]) }}</span>
  </template>
  <template #editor="slotProps">
    <InputText v-model="slotProps.data[slotProps.column.field]" />
  </template>
</Column>
```

My workaround at the moment is to set the `<span>` css to include `pointer-events: none` which causes it to ignore mouse clicks, which then go to the parent instead. However this feels a bit 'hacky'.

Is there an 'official' way to set this up so that click events are correctly handled?

**Comment by cagataycivici** [comment]
I'd expect body not to be rendered at all when in editor mode, will check and get back to you.

**Comment by mrichar1** [comment]
body should be available alongside editor mode so that you can make changes to the 'default' until editor mode is enabled. It seems to work more or less as expected, apart from the 2 elements overlapping.

If anything was to change I'd suggest perhaps making editor mode have 2 'modes': 'read' and 'edit' with different templates for each?

**Comment by cagataycivici** [comment]
I guess you can just use the content of body in editor mode as well;

```xml
<Column  field="rows"  header="Rows">
  <template #body="slotProps">
    <span>{{ roundValue(slotProps.data[slotProps.column.field]) }}</span>
  </template>
  <template #editor="slotProps">
<span>{{ roundValue(slotProps.data[slotProps.column.field]) }}</span>
    <InputText v-model="slotProps.data[slotProps.column.field]" />
  </template>
</Column>
```

Which gives you full control over the presentation.

**Comment by mrichar1** [comment]
That solution also isn't quite right - when 'edit mode' is activated the InputText appears but the span doesn't disappear, so you see both elements. you'd need something to hide the span when the InputText element was active.

**Comment by Fanmade** [comment]
We're facing the same problem right now. If we just use the content within the body slot, it works. As soon as we add any element around that, it does block the click event. And we can only edit the cell if we click somewehere around the span. We're using your workaround (thanks for that @mrichar1 !) for now, but we'd love a non-hacky solution aswell
