### ISSUE TITLE
Feature request - inline property for components using teleport

### ISSUE THREAD

**Issue by songoo** [primefaces/primevue#1550]
Hello.

As stated in v3 documentation https://v3.vuejs.org/api/built-in-components.html#teleport

Teleport can be natively set to inline/dissabled mode

```
<teleport to="#popup" :disabled="displayVideoInline">
  <video src="./my-movie.mp4">
</teleport>
```

Would it be possible to add this as settable property for components using teleports (dropdown/multiselect), to gain control over this behavior?

For example :
`<dropdown :inlineComponent="true">`

Or as alternative please add ability to define class wich will wrap teleported content. So developers can target and override CSS styles of this teleported content dynamically. 
For example :
`<dropdown :teleportedContentClass="blue-options">`

Best regards.

**Comment by tugcekucukoglu** [comment]
You can use 'appendTo' property for Dropdown/MultiSelect. It accepts query selector and html element.

**Comment by songoo** [comment]
Tnx very much , appendTo="self" , solved issue it make html stay in its parent which is great, Your best :)
