### ISSUE TITLE
[FEATURE] Dialog: minimize, pin, stretching

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1557]
Please add functions to Dialog:
1) Minimize dialogue
2) pinning the dialogue
3) Stretching the edges of the dialog
4) Dynamic width depending on the size of the content (setting, can be enabled / disabled)
It seems to me very useful functions
I am attaching examples as I see it

![image](https://user-images.githubusercontent.com/16963395/133945934-19e437d1-7c92-482d-bbbb-0f0d63342eaf.png)

Minimize:
![image](https://user-images.githubusercontent.com/16963395/133945942-32b5e22b-7614-4327-838a-c38a518a08ef.png)

![image](https://user-images.githubusercontent.com/16963395/133945979-6c6e6e10-92a3-4dd2-be1a-52bc92abd674.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
