### ISSUE TITLE
Border after click

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1558]
Is it possible to disable the border that remains after the click?

When you click on buttons and other active elements, a click animation occurs (including a border appear), but after the animation the border remains, can it be removed after the click animation?

Example: https://www.primefaces.org/primevue/showcase/#/button

Before pressing
![image](https://user-images.githubusercontent.com/16963395/133946150-65b34020-a3c4-4c82-82bd-a1d0d8f7542a.png)

After clicking
![image](https://user-images.githubusercontent.com/16963395/133946154-4cdde57e-fbbc-4138-9d3c-4ea9832bf6a0.png)
![image](https://user-images.githubusercontent.com/16963395/133946160-0a3c67bc-6b92-44ba-9c68-c8a3216d2c36.png)

(I want to hide this border automatically, without clicking on an empty space)

After clicking on an empty space
![image](https://user-images.githubusercontent.com/16963395/133946163-bdbbbd72-81b2-4777-bd1c-30098e57db83.png)

**Comment by tugcekucukoglu** [comment]
You could override focus behavior of the component.

**Comment by CRC32EX** [comment]
Disable all element border after the click.

```css
*:focus {
  box-shadow: none !important;
}
```
