### ISSUE TITLE
DataTable with selectionMode 'multiple' select with shift

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1562]
I have a DataTable with Paginator und selectionMode 'multiple'. If I go to e.g. page 3 and try to select multiple rows with shift it doesn't work on page 3.
When I go to page 1 the selection is there! (not on page 3).

Version 3.7.2

https://codesandbox.io/s/pedantic-dream-7qscq

**Comment by namcodes** [comment]
if you selected page 3,
the dom at page 1 will be selecte :)))
