### ISSUE TITLE
DataTable column width increases by content limitlessly

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1573]
Due to the fixes of #1508 and #1521, you made a change in DataTable.vue from
```
.p-datatable table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;
}
```
to
```
.p-datatable table {
    border-collapse: collapse;
    min-width: 100%;
    table-layout: fixed;
}
```
This change leads to columns, whose width will increase by their content limitlessly:

![falsch](https://user-images.githubusercontent.com/81289327/134129647-ba7e1320-b410-4cb2-8069-fb963e54936b.jpg)

The former definition gave each column the same width, despite of their content:

![richtig](https://user-images.githubusercontent.com/81289327/134129689-7ba1bdfa-26a0-44be-9821-926b197f1b85.jpg)

**PrimeVue: 3.7.2
Vue: 3.2.11**

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate this issue. Could you please attach a codesanbox link for us to replicate?

**Comment by ibrdavid** [comment]
This codesandbox uses PrimeVue 3.7.2:
https://codesandbox.io/s/blissful-sea-6c060

If you edit package.json and change dependencies.primevue to "3.7.1", you'll get the original and desired result.

**Comment by tugcekucukoglu** [comment]
Could you please try to use the latest PrimeVue version? If the problem still persists, please create a new issue with a reproducer link.
