### ISSUE TITLE
Calendar today button TypeError: Cannot read property 'currentTarget' of null

### ISSUE THREAD

**Issue by tdecorte** [primefaces/primevue#158]
Function onTodayButtonClick(event) calls  this.onDateSelect(null, dateMeta);
But first parameter of onDateSelect is event, and on event we have: event.currentTarget.focus();
As event is null, this throws an error.

**Comment by Nerderer** [comment]
This is fixed in this PR:
https://github.com/primefaces/primevue/pull/160

**Comment by cagataycivici** [comment]
Merged, thank you.
