### ISSUE TITLE
rowsPerPageOptions dropdown is not coming in Datatable

### ISSUE THREAD

**Issue by Deepak2985** [primefaces/primevue#159]
![image](https://user-images.githubusercontent.com/36476799/73122005-8dd63180-3fa5-11ea-92c3-7c04142917af.png)

Even after adding these input properties to datatable the rowsPerPageOptions dropdown is not coming and I am getting the warning as in the above screenshot.
:paginator="true"
    :rows="10"
    :rowsPerPageOptions="[10,20,30]"

**Comment by Deepak2985** [comment]
@cagataycivici Thank you for such an early fixing of issue. I really appreciate that. 🙂

**Comment by Deepak2985** [comment]
@cagataycivici  I am get the similar error even after pulling the new version 1.0.2 

![image](https://user-images.githubusercontent.com/36476799/73454253-af635e80-4393-11ea-98c5-25d6a59e00de.png)

**Comment by fairking** [comment]
Sometimes I got some errors after upgrading a new version. Try to clear the `node_modules` folder and run `npm install`. It looks like some old stuff still remains in the cache. After this all errors disappear.

**Comment by Deepak2985** [comment]
@fairking Thank you It worked after removing the node_modules. Earlier I was just removing the primevue folder from node_modules but it didn't work.
