### ISSUE TITLE
Vite build with Typescript Module '"vue"' has no exported member 'PluginFunction'.  in `ConfirmationService.d.ts` and `ToastService.d.ts`

### ISSUE THREAD

**Issue by yichunsung** [primefaces/primevue#1596]
### The issue when using typescript in `vue-tsc --noEmit && vite build`

`ConfirmationService.d.ts` and `ToastService.d.ts` has some issue.

#### package version:

* `"vue": "^3.2.6"`
* `"vite": "^2.5.2"`
* `"vue-tsc": "^0.2.2"`

if using `vue-tsc --noEmit`, it not working with these error. 

### Error message

```bash
node_modules/primevue/confirmationservice/ConfirmationService.d.ts:1:15 - error TS2305: Module '"vue"' has no exported member 'PluginFunction'.

import Vue, { PluginFunction } from 'vue';
                ~~~~~~~~~~~~~~

node_modules/primevue/toastservice/ToastService.d.ts:1:15 - error TS2305: Module '"vue"' has no exported member 'PluginFunction'.

import Vue, { PluginFunction } from 'vue';
                ~~~~~~~~~~~~~~
```

I have already create a new PR  https://github.com/primefaces/primevue/pull/1595

**Comment by PeterHewat** [comment]
Hi @yichunsung 

This helped me out. I can confirm it fixes the issue. I hope your PR gets into the next release.

**Comment by MichaelVonB** [comment]
Same setup, hope it will get fixed

**Comment by cagataycivici** [comment]
@mertsincan Review please for 3.8.0.
