### ISSUE TITLE
DataTable: filter margin button

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1611]
Good: 
![image](https://user-images.githubusercontent.com/16963395/135030128-5638b4e1-4361-4b0d-b2d8-0a3f1ddf8e7b.png)

i choose condition

![image](https://user-images.githubusercontent.com/16963395/135030194-85f2d487-a648-4b3b-ae19-c1c9bc595eb8.png)

**Comment by tugcekucukoglu** [comment]
This is not a valid issue ticket, there seems to be an issue on your side. Please use the forum or discord channel for questions and help requests.
