### ISSUE TITLE
Tailwind theme location typing mistake in Setup docs

### ISSUE THREAD

**Issue by KayJay89** [primefaces/primevue#1614]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
NA

**Current behavior**
Typing mistake in file location for tailwind theme

**Expected behavior**
N/A
**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Correct a typing mistake in the official docs on website 

**Please tell us about your environment:**
N/A

* **Vue version:** N/A

* **PrimeVue version:** N/A

* **Browser:** NA

**See PR #1613**

**Comment by tugcekucukoglu** [comment]
Thanks for your contribution.

Fixed with [#1613](https://github.com/primefaces/primevue/pull/1613)
