### ISSUE TITLE
Generic menu component

### ISSUE THREAD

**Issue by bisubus** [primefaces/primevue#1618]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

The suggestion is to provide more generic inline menu component that implements MenuModel, or at least expose a usable primitive that could be customized. Currently ContextMenuSub or some other private component can be imported with few style adjustments, but it already contains `position` and `border` rules that aren't useful for general use. `Sub` components are not exported from package entry point, and the next release may break them.

**What is the motivation / use case for changing the behavior?**

The use of inline menu in sidebar navigation, similarly to mobile menu at https://www.primefaces.org/primevue/showcase/ 

* **Vue version:** 3.2.X

* **PrimeVue version:** 3.7.X

* **Browser:** [all]

**Comment by tugcekucukoglu** [comment]
For now it's not on the PrimeVue roadmap. But this might be possible using Menubar and/or Sidebar components.

Thanks for your time.
