### ISSUE TITLE
Unable to display rowsPerPageOptions dropdown in Datatable or Paginator component

### ISSUE THREAD

**Issue by VinitraMk** [primefaces/primevue#162]
I have tried displaying dropdown for selecting no of rows to display in Datatable as well as Paginator, but it doesn't render. I don't get console error to point out the cause of this issue. The following is the code snippet for usage in paginator component:
```
<Paginator :rows.sync="rows" :totalRecords="101" :rowsPerPageOptions="[10,20,30]"/>
```

**Comment by cagataycivici** [comment]
This is fixed now, please see;

https://github.com/primefaces/primevue/issues/159
