### ISSUE TITLE
[Feature Request] Disable +- Button on InputNumber when value reach min, max

### ISSUE THREAD

**Issue by liemdt1811** [primefaces/primevue#1621]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Feature Request)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

**Current behavior**
Button + and button - still clickable after the value reaches its min, max

**Expected behavior**
It should be configurable to disable those buttons when the value reach min, max

**Comment by mouadTaoussi** [comment]
@liemdt1811 I Might make this feature for you
