### ISSUE TITLE
DataTable reorder doesn't show when the rowReorder prop is passed as row-reorder

### ISSUE THREAD

**Issue by tig-mmp** [primefaces/primevue#1623]
I'm using ESLint to format the code and the rule [attribute-hyphenation](https://eslint.vuejs.org/rules/attribute-hyphenation.html) sets the rowReorder prop to row-reorder.
The problem is that the [reorder](https://www.primefaces.org/primevue/showcase/#/datatable/reorder) of the dataTable when the proposal passed as reorder row by column doesn't have the reorder icon.

This can be replicated in [codesandbox](https://codesandbox.io/s/71pv8?file=/src/DataTableReorderDemo.vue) by changing the prop to row-reorder.

from
`<Column :rowReorder="true" headerStyle="width: 3rem" :reorderableColumn="false" />`
to 
`<Column :row-reorder="true" headerStyle="width: 3rem" :reorderableColumn="false" />`

**Comment by tugcekucukoglu** [comment]
Fixed for the next version. Please check [#1263](https://github.com/primefaces/primevue/issues/1263)
