### ISSUE TITLE
FullCalendar: List view (agenda) 

### ISSUE THREAD

**Issue by m-thorsen** [primefaces/primevue#1624]
https://fullcalendar.io/docs/list-view

This is not a premium feature, and it works fine - except for the toolbar button not being styled.  
It is also not documented in the example at https://primefaces.org/primevue/showcase/#/fullcalendar

To solve, the following css definitions would have to be added: 
* `.fc.fc-theme-standard .fc-toolbar .fc-button.fc-listYear-button`
* `.fc.fc-theme-standard .fc-toolbar .fc-button.fc-listMonth-button`
* `.fc.fc-theme-standard .fc-toolbar .fc-button.fc-listWeek-button`
* `.fc.fc-theme-standard .fc-toolbar .fc-button.fc-listDay-button`

**Comment by tugcekucukoglu** [comment]
PrimeVue just support theming for FullCalendar. For now we are not considering to add theming list-view.

Thanks for your understanding.
