### ISSUE TITLE
TreeTable expandAll slow 

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1626]
Hi. If the table is heavily nested, it is slow.

In particular the expandAll method

In my real project ~ 3000 records with different nesting

When expandAll, I wait for about 30 seconds.

Is there a way to speed this up?

Example:
https://codesandbox.io/embed/mutable-architecture-in3jk?fontsize=14&hidenavigation=1&theme=dark

In the example, you can change the mounted loop to slightly higher values ​​to see even longer load times.

PS There is a lot of data in my project, so I really want all the components (Tables and trees (filters and search)) to work well with a large number of rows (and other data). Please pay attention to performance on big data and others in future components. My project may have plates with more than 3,000,000 lines

**Comment by NeluQi** [comment]
Also, if performance is not increased, make a loading indicator. Now the page just freezes

**Comment by tugcekucukoglu** [comment]
Instead of using expandAll method with ~ 3000 items, you could use lazy loading with the indicator. [https://codesandbox.io/s/kjol6?file=/src/TreeTableLazyDemo.vue](https://codesandbox.io/s/kjol6?file=/src/TreeTableLazyDemo.vue)
