### ISSUE TITLE
Cannot create dynamic ColumnGroup columns in DataTable

### ISSUE THREAD

**Issue by cberthiaume** [primefaces/primevue#1630]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

**Current behavior**
Dynamically generating columns inside a ColumnGroup does not produce the columns with the assigned headers.

**Expected behavior**
I expect it to work the same as dynamically generating columns inside the DataTable -- ColumnGroup columns are created with the assigned headers.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primevue-dynamic-column-group-pqr1z?file=/src/App.vue

**What is the motivation / use case for changing the behavior?**
I would like to create a summary ColumnGroup header with aggregate information based on data with varying columns.

**Please tell us about your environment:**
I'm using the template above for the code sandbox. On my development machine I use a mac. Vue 3 with Vite.

* **Vue version:** 3.2.19

* **PrimeVue version:** 3.7.2

* **Browser:** [ Chrome 94.0.4606.61 | Firefox 92.0.1  ]

Seems like this has been an issue since at least Dec. of 2020 going by [this thread](https://forum.primefaces.org/viewtopic.php?t=64670).

**Comment by mitow7821** [comment]
####  Is there any way to create dynamic rows in columngroup? 
Unfortunately this doesnt work :( 

![image](https://user-images.githubusercontent.com/34492112/146905201-f3cb7e93-63c6-4c99-baae-cefe8e58589c.png)

**Comment by tugcekucukoglu** [comment]
> #### Is there any way to create dynamic rows in columngroup?
> Unfortunately this doesnt work :(
> 
> ![image](https://user-images.githubusercontent.com/34492112/146905201-f3cb7e93-63c6-4c99-baae-cefe8e58589c.png)

Could you please open a new issue? Because they are different issues.
