### ISSUE TITLE
Treetable: sorting in a node (BUG)

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1634]
Now sort is sorting by top level, I want nested items to be sorted when sorting

Sorting should sort at each level of the tree, not just groups

https://www.primefaces.org/primevue/showcase/#/treetable/sort

![image](https://user-images.githubusercontent.com/16963395/135823613-5d4b681c-bf5a-4937-9aa8-170cb5c124fc.png)

![image](https://user-images.githubusercontent.com/16963395/135823676-e2f0e31a-5578-4424-8ed7-1f9d07459696.png)

**Comment by tugcekucukoglu** [comment]
Duplicate [#1396](https://github.com/primefaces/primevue/issues/1396)
