### ISSUE TITLE
[Feature Request] State

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1636]
It would be nice if State (State is the same as in https://www.primefaces.org/primevue/showcase/#/datatable/state) would be saved for:
1) MultiSelect (https://www.primefaces.org/primevue/showcase/#/multiselect)
2) Dropdown (https://www.primefaces.org/primevue/showcase/#/dropdown)
3) Input

It would be cool to be able to set up persistence for all components. Those that I listed above are my priority

**Comment by tugcekucukoglu** [comment]
It's not on our roadmap. For now closing this.
