### ISSUE TITLE
DataTable onPage event not fired automatically after loading if data is null

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#164]
We need to manually make an ajax request on a "mounted" method to fill first page after creating component.
Maybe the correct way is to call onPage event after mounting of bounded ":value" value is null? And it must not be called if ":value" have any value.

**Comment by cagataycivici** [comment]
I'm not sure, the component should not intervene with when data is loaded except events, it is common to load the data on mount.

**Comment by Sellec** [comment]
> I'm not sure, the component should not intervene with when data is loaded except events, it is common to load the data on mount.
With this solution we are need to fill property bound to ":value" twice - on mount and on "onPage" call.
