### ISSUE TITLE
[FEATURE] Custom sort function for DataTable/TreeTable

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1641]
I want to specify in sortField a function with parameters (or a field) that returns a string to sort.

For example, the table stores objects of type N

Class N has a getByUserId (id: number): number method that returns number. I want to specify in sortField = "getByUserId (5)"

and for the "Field" column this is also needed.
Often there are calculated fields in these rows and they require a function

**Comment by paulgrove** [comment]
I asked for this feature in the discord channel and was kindly pointed to this GitHub issue.

**Comment by Rakasch** [comment]
As a solution for now:
Loop your data and call your function once for each data set. Save the result in your data set as a separate variable. You can then specify this as a sortField in the column.

**Comment by paulgrove** [comment]
Thanks, @Rakasch that will work for me, though I would urge still for a custom sort function property or similar.

**Comment by tugcekucukoglu** [comment]
Duplicate [#323 ](https://github.com/primefaces/primevue/issues/323)
