### ISSUE TITLE
[Bug] VirtualScroller end up with a blank screen

### ISSUE THREAD

**Issue by nclemeur** [primefaces/primevue#1644]
```
[x] bug report 
```
**CodeSandbox Case (Bug Reports)**
See example `Template` in the primevie show case:
https://www.primefaces.org/primevue/showcase/#/virtualscroller

**Current behavior**
`Template` example does not scroll properly on firefox when using the dragging the scrollbar handle around, ending up with a blank box
![image](https://user-images.githubusercontent.com/7132890/136302729-ef2615a5-5646-4a95-89d6-92519ed581d9.png)

**Expected behavior**
Proper scrolling

**Minimal reproduction of the problem with instructions**
Use drag the scrollbarar handler around.

* **Browser:** [ Firefox 92 ]

**Comment by mertsincan** [comment]
Hi @nclemeur,

This is related to Firefox rendering performance. You can see the incoming data in the DOM.
![virtualScroller_FF_test](https://user-images.githubusercontent.com/11868120/142366174-75b7e639-a652-4a1e-a5c3-383a0f72d66b.png)

As far as I know, Firefox has made many things optional for performance reasons. 
https://www.techrepublic.com/article/how-to-enable-firefox-webrender-for-faster-page-rendering/
etc.

**Comment by nclemeur** [comment]
I really don't understand why you are closing this issue, or you should make it clear in the documentation that there are some issue with Firefox is not supported. But closing it won't make it disappear...

**Comment by mertsincan** [comment]
I think this issue is not related to PrimeVue. In the above screenshot, data will always appear in DOM. Exp; `Item #99999` Also, when you delete a few div elements from the template, Firefox will show text because the content it will display is reduced. Please try the following code;
```
<VirtualScroller class="custom-loading" :items="basicItems" :itemSize="75" showLoader :delay="250">
    <template v-slot:item="{ item, options }">
        <div :class="['custom-scroll-item scroll-item', {'odd': options.odd}]">
            <div class="p-d-flex p-ai-center p-px-2" style="height: 25px">{{`Item: ${item}`}}</div>
            <div class="p-d-flex p-ai-center p-px-2" style="height: 25px">{{`Index: ${options.index}`}}</div>
            <div class="p-d-flex p-ai-center p-px-2" style="height: 25px">{{`Count: ${options.count}`}}</div>
        </div>
    </template>
    <template v-slot:loader="{ options }">
        <div :class="['custom-scroll-item scroll-item', {'odd': options.odd}]">
            <div class="p-d-flex p-ai-center p-px-2" style="height: 25px"><Skeleton width="60%" height="1.2rem" /></div>
            <div class="p-d-flex p-ai-center p-px-2" style="height: 25px"><Skeleton width="50%" height="1.2rem" /></div>
            <div class="p-d-flex p-ai-center p-px-2" style="height: 25px"><Skeleton width="60%" height="1.2rem" /></div>
        </div>
    </template>
</VirtualScroller>
```
I only removed 4 div elements and change itemSize according to it.

Also, cdk-virtual-scroller("Virtual scroll context variables" example) has similar to our virtualScroller sample. Could you please check it?

**Comment by nclemeur** [comment]
Indeed, the example on the cdk-virtual-scroller is displaying the same behaviour...

However, even if the issue is not related to Primevue, I would expect from a library to warned be about the limitations. Specially, when it is clearly reproducible in an official example...

So it is clear that we are hitting some sort of limit on the height of the virtual element. With the previous the 75px elements we have the div spacer added at the end that has a height of height: 7500000px (100000 elements) and no problems...  With 175px elements, we start to see the issues... So I imagine there is a limit in between that is the maximum than Firefox can handle.

Ideally, I think a note in the documentation would be required referring to this issue and possibly to an issue in the mozilla project...  In addition, it would be nice to try to calculate this limit and emit a warning in development with a reference to this issue when the height is above...

**Comment by dheimoz** [comment]
@nclemeur then the best way to made other user to be aware is to write a PR.
