### ISSUE TITLE
css bug input number group

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1647]
buttons do not have a border in inputnumber 

check:  https://www.primefaces.org/primevue/showcase/#/inputnumber

![image](https://user-images.githubusercontent.com/16963395/136338324-e3ce144d-bda7-46bd-ad96-c7735b346abc.png)

![image](https://user-images.githubusercontent.com/16963395/136338401-03783a52-c6ba-4813-b57f-15cd02420a44.png)

**Comment by tugcekucukoglu** [comment]
These are separate elements, InputText and Button, so, for example when you focus on InputText, the other Buttons are not focused. The state at the showcase is expected behavior.
