### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by NicolasMelin** [primefaces/primevue#1648]
Hello,

I have a problem with the calendar component. When I click the calendar input, the beggining of the calendar popup is not displayed at the top or bottom of the input :

Not clicked :
![Capture](https://user-images.githubusercontent.com/13767020/136427122-268469c5-884b-40ce-9429-37a6d584ebfb.PNG)

Clicked :
![Capture2](https://user-images.githubusercontent.com/13767020/136427137-5752f01d-adc9-4ffc-a56f-bc4ab67f0a16.PNG)

Also, when I click on date or time, the input value is not updated at all !

My .vue file is this :

```
<script>
import Calendar from 'primevue/calendar';
</script>

...

<template>
...
<Calendar :show-time="true" date-format="dd.mm.yy" hour-format="24" required />
...
</template>
```

It's a bug or I miss something ?

Thanks by advance for the support.

Best regards.

**Comment by west-farmer** [comment]
try adding "append-to='body'"  to component
