### ISSUE TITLE
DataTable sort\page\filters slow and auto enabling loading when sorting\swap page\filters

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1649]
Hi. First I want to say a big thank you for primevue and the quick answers and improvements.

There is a lot of data in my project. When sorting in the DataTable (and filtering) (clicking on the <Column field = "id" sortable> column) with ~ 3k records (and this is still very little, there may be more data) - sorting takes 1-2 seconds.

Are there any ways to speed it up? If you have time, you can see if it is possible to speed up the DataTable (sorting and filtering)

Sorting on the server (lazy) and overriding the sorting of the DataTable in my project will most likely not be possible.

Also, when switching pages (paginator), it takes 1-2 seconds

And the most problematic

when entering a global filter in InputText (
<InputText v-model = "filters ['global']. Value": placeholder = "$ t ('Search')" style = "width: 100%" />)

input lag is very huge when entering each letter (1 letter - ~ 5 seconds)

You can make the loading state: loading = "loading" of the DataTable when sorting and filtering and other internal calculations in the DataTable (Now the DataTable does not include loading when it sorts itself, etc.)

For example, you can add a flag to the DataTable of type, like isBigData, and when it is turned on during sorts and any actions (sort \ page \ filters, etc.) that take time will be shown by loading at these moments (well, some then another optimization)

**Comment by J43fura** [comment]
> when entering a global filter in InputText (
> <InputText v-model = "filters ['global']. Value": placeholder = "$ t ('Search')" style = "width: 100%" />)
> 
> input lag is very huge when entering each letter (1 letter - ~ 5 seconds)

A debouncer might be a good solution for this.

> You can make the loading state: loading = "loading" of the DataTable when sorting and filtering and other internal calculations in the DataTable (Now the DataTable does not include loading when it sorts itself, etc.)
> 
> For example, you can add a flag to the DataTable of type, like isBigData, and when it is turned on during sorts and any actions (sort \ page \ filters, etc.) that take time will be shown by loading at these moments (well, some then another optimization)

This is a very important point
