### ISSUE TITLE
Toast z-index

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1654]
When using Sidebar and autoZIndex = true
Sidebar, after clicking on it, overlaps the Toast.

The same is with other elements with autoZIndex.

You can prioritize Toast autoZIndex so that it really is always on top

According to priorities, it should be like this:
Toast
Dialog
everything else

**Comment by tugcekucukoglu** [comment]
`
app.use(PrimeVue, {
    zIndex: {
        modal: 1100,        //dialog, sidebar
        overlay: 1000,      //dropdown, overlaypanel
        menu: 1000,         //overlay menus
        tooltip: 1100       //tooltip
    }
});
`

These are overwritable default settings.
