### ISSUE TITLE
[Bug] - Datatable selection with lazy mode not enabling the check all button

### ISSUE THREAD

**Issue by dacxjo** [primefaces/primevue#1655]
Not sure 100% if this is a bug, since by logic it works as expected, but it doesn't feel good with lazy mode and pagination.

**Current behavior**
Well, if we have many items in a datatable with lazy mode, pagination and multi-selection enabled, if we check to select all the items in the current page, the checkbox it's not enabled. I understand that this is happening because we are only selecting one page of all the total records, but it should be like that?

**Expected behavior**
I think that the behavior with lazy mode should be enable the select all checkbox, if all the elements per page are selected.

**CodeSandbox **

Click on the select all checkbox, it's going to select all the first 10 items but will not work to deselect.

https://codesandbox.io/s/mutable-grass-9cq11

**Comment by nclemeur** [comment]
I am not sure what the answer is here, but I think it would be nice to provide an easy way to override the default behaviour. Another use case not involving lazy load is to handle options disabled for whatever reason. If all the enabled options are selected I would also expect the check all to be selected (and vice-versa when some options are disabled to not select them)... Obviously, this would mean that you could actually disable some option (which I think I had to implement my-self)

**Comment by hollyfoxx** [comment]
There needs to be a way to override this. The main checkbox is still working to 'select all' by selecting all VISIBLE rows. The deselect simply needs to deselect all VISIBLE rows given a lazy DataTable. This is a common UI pattern and the fact that this behavior is disabled by default (and can't be changed) really doesn't make sense.

**Comment by arnyee** [comment]
Hello, Is there any solution with the DataTable Build In paginator?
