### ISSUE TITLE
InputNumber is not working width

### ISSUE THREAD

**Issue by qwerty3858** [primefaces/primevue#1668]
I am trying to give width to InputNumber but it is not working.
```
<InputNumber  style="width: 50px" mode="decimal" :minFractionDigits="2" class="p-inputtext-sm" id="username" v-model="value2" />```

**Comment by tugcekucukoglu** [comment]
style is a prop for InputNumber component and for input field for you also need to use inputStyle property. For example

<InputNumber inputStyle="width: 100%" style="width: 50px" />
