### ISSUE TITLE
DataTable filter should allow constraints to be undefined

### ISSUE THREAD

**Issue by mrichar1** [primefaces/primevue#1669]
https://codesandbox.io/s/vue-3-datatable-constraints-hp1w5?file=/src/components/HelloWorld.vue

**I'm submitting a ...** (could count as either?)
```
[ x ] bug report
[ x ] feature request
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/winter-microservice-vkwn0?file=/src/App.vue

**Current behavior**

When using `Filter menu` mode, if the `filters`object doesn't contain an appropriate `constraints` property, then when the match mode is selected from the UI the app crashes - e.g. `_filters[this.field].constraints is undefined`.And if `operator` is unset, the UI doesn't display the ability to add rules, even if `showFilterOperator` is true.

**Expected behavior**

There should be defaults for these in order that not setting them is not an error (e.g. in `Filter row` mode there are no errors if an empty object is passed (i.e `matchMode` can be undefined)).

`operator` could be set to a default value (`'and`' ?) if `showFilterOperator=true"`, and `constraints` could default to e.g. `[{ matchMode: 'contains' }]`

* **Vue version:** 3.2

* **PrimeVue version:** 3.7.1

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox but unfortunately it does not show the issue.  How could we replicate the issue using [this sample](https://codesandbox.io/s/great-sid-u337w?file=/src/DataTableFilterDemo.vue)?

**Comment by mrichar1** [comment]
Hi - sory I should have given clearer instructions to reproduce. The code change to make it happen is to provide an empty or no `constraints` field. For example, on the new sandbox, replace:

```
"country.name": {
        operator: FilterOperator.AND,
        constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }],
      },
```

with

```
"country.name": {}
```

 Then do the following:

1. Click on the filter icon for that column.
2. Select a 'Match Mode' - e.g `startsWith`.

The console will now show the error `_filters[this.field].constraints is undefined`

**Comment by tugcekucukoglu** [comment]
In case of using multiple constraints, 'operator' adds more constraint to filter and new 'constraints' must be an array. So usage of 'operator' without 'constraints' is not valid.

And also when you did not add 'operator', it doesn't add another constraint to filter and then even if 'showFilterOperator' is true, it does not render it to the UI.

**Comment by mrichar1** [comment]
Yes - I appreciate that each one by itself doesn't make sense - what I'm asking for is for PrimeVue to assume sensible defaults if some of the properties are missing.

This is how 'single' filters already work - for example, if you specify:

```
filters: {
  name: {}
}
```

The code will assume defaults equivalent to:

```
filters: {
  name: { value: null, matchMode: FilterMatchMode.STARTS_WITH }
}
```

It would be good if equivalent defaults could be picked for multiple constraints. 

If you specify `operator` it should assume that you want at least one constraint, with the defaults equivalent to the above (i.e empty value. `startsWith` match mode). For example:

```
filters: {
  name: { operator: "and" }
}
```

would be equivalent to:

```
filters: {
  name: {
    operator: "and",
    constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }],
 }
}
```

Equally, if you specify `constraints`, and `showFilterOperator` is true, then it should assume that `operator` was set, defaulting to `AND`. For example:

```
filters: {`
  name: {
    constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }],
  }
}
```

would be equivalent to:

```
filters: {`
  name: {
    operator: "and",
    constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }],
  }
}
```

I hope this makes sense - please let me know if this still isn't clear!

**Comment by cagataycivici** [comment]
When implementing this, we initially wanted to give sensible defaults but I remember it complicated the code. I think the feature is mature now and we can work on enhancements to give defaults to make the usage easier for sure. @mertsincan will work on it.

**Comment by mrichar1** [comment]
Just rediscovered this issue while hitting this bug again in a new project - has there been any progress on this?

**Comment by LeandroMarcondes** [comment]
no progress for know, the default filters still required to be set by the user. when it is not set, the filter function works, but the error  'defaultConstraint is undefined' appears when user try to clean the filter. Tested on PrimeReact 8.6.1

**Comment by LeandroMarcondes** [comment]
A workaround is set the 'filters' on the event 'onFilter' like that:

On render
` <DataTable   onFilter={onFilter} filterDisplay="menu" filters={filtersOnTable} >`

on React
`
const onFilter = (event) => {
        setFiltersOnTable(event.filters);
}
`

The error still happens if user try to clear filters without type any filter, but after type a filter the clear button starts to work.

Maybe it can be implement as default.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
