### ISSUE TITLE
Primevue editor formating problem

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#1673]
I've found that if u save formated data from editor component and they use them again when component is mounted some elements looses formatting. It`s caused by pasteHtml function that quill provides 
![image](https://user-images.githubusercontent.com/34492112/137462515-861ec721-2831-4bc0-8112-a22fb55cbac7.png)
![image](https://user-images.githubusercontent.com/34492112/137462611-cc061042-ddc9-4b60-8ffe-8d8b0d28d21a.png)

I've replaced that with `this.quill.root.innerHTML = this.modelValue;` and now everything works as expected ;) 

![image](https://user-images.githubusercontent.com/34492112/137462835-5ca80001-eabf-4c50-aabe-152b0dbb44cb.png)

(primevue 3.5.1)

**Comment by tugcekucukoglu** [comment]
How can I replicate this? Issue is not clear. Do you have a codesandbox link for us to replicate?

**Comment by mitow7821** [comment]
Despite of same modelValue in both cases i am getting different result in dom
![s1](https://user-images.githubusercontent.com/34492112/137492887-e6840677-ecec-4aab-af2a-5255263e2134.PNG)
![s4](https://user-images.githubusercontent.com/34492112/137492917-d0eaa144-b8e9-4e66-8ff0-354e20481691.PNG)
![s2](https://user-images.githubusercontent.com/34492112/137492933-0c69a471-e6bb-485d-a884-01cfb8d50389.PNG)
:
![s3](https://user-images.githubusercontent.com/34492112/137492958-d599a0b7-9ad7-4178-ba3b-75fc0ff44703.PNG)

It seems like dangerouslyPasteHTML is causing this problem, but still dont know why

**Comment by tugcekucukoglu** [comment]
Issue is not clear, please feel free to reopen with a codesandbox example.
