### ISSUE TITLE
ConfirmDialog not reopening

### ISSUE THREAD

**Issue by ollyrowe** [primefaces/primevue#1675]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Description**
I've been working with the `ConfirmationService` / `ConfirmDialog` components using the `this.$confirm.require(...)` API, and I've come across an issue with closing and re-opening dialogs. After `require(...)` is called for the first time, the confirmation dialog appears as expected (correct behaviour, etc.) however after closing the dialog via the close-icon at the top right of the dialog, the dialog closes (as expected), however subsequent `require(...)` calls do not re-open the dialog. 

After looking into the source behind the `ConfirmDialog` component, I can see that a [`closeDialog()`](https://github.com/primefaces/primevue/blob/2.x/src/components/confirmdialog/ConfirmDialog.vue#L59) method is called upon clicking the `Dialog` component. This method contains an `if` statement which basically turns off the subscribers to the event bus if the close-icon button is the target - this is the code which is causing the issue I'm experiencing. Is this intended behaviour?

**Environment**

* **Vue version:** 2.6.12
* **PrimeVue version:** 2.5.1

**Comment by tugcekucukoglu** [comment]
What is your exact test case? This example works for me [https://codesandbox.io/s/primevue-2-issue-template-lfydz?file=/src/App.vue](https://codesandbox.io/s/primevue-2-issue-template-lfydz?file=/src/App.vue)

**Comment by tugcekucukoglu** [comment]
Please track that issue [#1746 ](https://github.com/primefaces/primevue/issues/1746)
