### ISSUE TITLE
DataTable won't update model if there is no explicit @cell-edit-complete event handler that does it.

### ISSUE THREAD

**Issue by jpeletier** [primefaces/primevue#1686]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

Find here a sandbox app and workaround: https://codesandbox.io/s/silly-waterfall-swjcu?file=/src/App.vue

**Current behavior**
A ```DataTable```with in-cell editing and no ```@cell-edit-complete``` event handler won't update the model.
**Expected behavior**
Cell editing should automatically update the model after focus leaves the editor. This was the behavior in previous versions. To achieve the same effect now it is necessary to handle ```@cell-edit-complete``` to actually update the value. See code sandbox above.

**Workaround**

Add a dummy ```@cell-edit-complete``` event handler to Data Table such as:

```javascript
    function onCellEditComplete(event) {
      let { data, newValue, field } = event;
      data[field] = newValue;
    }
```
This will have DataTable behave as before.

**Minimal reproduction of the problem with instructions**
See code sandbox above for a minimal demo app

**What is the motivation / use case for changing the behavior?**
This breaks compatibility with existing code. Users of DataTable without validation that did not have an explicit ```@cell-edit-complete```

**Please tell us about your environment:**
happens across OSs and browsers

* **Vue version:** 3.X
3.0.11

* **PrimeVue version:** 
* 3.8.1

* **Browser:** 
all

**Comment by tugcekucukoglu** [comment]
It is not a valid usage. In your case 'data' must be reactive. This below example works

[https://codesandbox.io/s/smoosh-silence-uzt2y?file=/src/DataTableEditDemo.vue](https://codesandbox.io/s/smoosh-silence-uzt2y?file=/src/DataTableEditDemo.vue)
