### ISSUE TITLE
PanelMenu MenuModel command 'this' issue

### ISSUE THREAD

**Issue by donniekerr** [primefaces/primevue#1702]
I am using PrimeVue 2 PanelMenu
` <PanelMenu :model="getTree" />`
with the follow model example object.
`items: [
            {
               label: 'X',
               icon:'pi pi-fw pi-folder',
               command: (event) => {
                **this.selectTreeItem(event.item.label)**
                console.log(event.item)
               }]`
In my Vue 2 component where the PanelMenu is, I want command to be able to call the selectTreeItem method when an item is clicked
`methods: {
    **selectTreeItem: function (val) {
      console.log(val)
    }**
  }`
The problem is I get an undefined error for 'this' when a menu item is clicked.  Vue 2 requires me to use this.selectTreeItem to call the method. It does not work without this.  But the 'this' in the command callback is different and it doesn't work.  What am I missing?  How do I call a method in the parent component from the command callback? Or is this a potential bug?

**Comment by tugcekucukoglu** [comment]
Please check [this working example](https://codesandbox.io/s/v2-panelmenu-0y5em?file=/src/App.vue). Unfortunately, I could not replicate it. What is your exact test case?

**Comment by donniekerr** [comment]
ah. I think I see the problem.  Your itemClicked and your items are both in the same component and thus it finds this.itemClicked.  My items are in VUEX and generated using api data and stored in state, thus this.itemClicked is not present in the store.

**Comment by tugcekucukoglu** [comment]
There seems to be an issue on your side. You should be called methods from Vuex.
