### ISSUE TITLE
Dialog destruction (v-show or v-if settings)

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1704]
It is possible to add a setting to Dialog that will change the hiding and displaying of the dialog, now I will explain

I want the Dialog not to be destroyed when hidden and not to create an invoked end inside the Dialog.
i.e. now the dialog uses v-if, you can add a setting for the dialog to use v-show

This is a very necessary thing; with its help it will be possible to control who is called to create and load all the components in Dialog or display those already loaded

This change is very important to me, thanks.

**Comment by NeluQi** [comment]
P.S And for the Sidebar component the same thing

**Comment by tugcekucukoglu** [comment]
It's not on the PrimeVue roadmap.

Thanks,

**Comment by Aterr** [comment]
That would be very useful tbh.

**Comment by rolandtoth** [comment]
This makes impossible to use dynamic components with keep-alive, which is a huge deal breaker for me. I'll use a custom sidebar component instead.
