### ISSUE TITLE
optionDisabled prop on Dropdown wrongly typed

### ISSUE THREAD

**Issue by ckoopmann** [primefaces/primevue#1705]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Not sure how to demonstrate a typescript issue in CodeSandbox unfortunately.

**Current behavior**
According to the documentation,  the `optionDisabled` prop on the Dropdown component should receive _"**Property name or getter function** to use as the disabled flag of an option, defaults to false when not defined."_
However the Typescript type of this prop is `boolean`.
Therefore even thought the functionality works when passing the "Property name" into this prop it results in a Typescript error.
Documentation Screenshot:
![image](https://user-images.githubusercontent.com/15629702/139055225-9aae6560-8f9f-4195-a737-7744af66491d.png)

Typescript error:
![image](https://user-images.githubusercontent.com/15629702/139054425-8efb60fe-aa25-4cdb-9efb-1c08769d72e3.png)

**Expected behavior**
Typescript typing should match the range of expected values (i.e. include "string" in the typing)

**Minimal reproduction of the problem with instructions**
Add the following code to a typescript enabled vue component / project and observe above described type error. 

`      <Dropdown
        :options="[]"
        optionValue="code"
        optionLabel="name"
        optionDisabled="disabled"
      />
`

`tsconfig.json` value for reference:
`{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "baseUrl": ".",
    "types": ["jest"],
    "paths": {
      "@/*": ["src/*"] 
    },
    "skipLibCheck": true
  }
}
`

**What is the motivation / use case for changing the behavior?**
Typescript type errors when passing a string to the optionDisabled prop.

**Please tell us about your environment:**
MacOS, Vue3 + vite, Typescript

* **Vue version:** 3.X
3.2.11

* **PrimeVue version:** 3.4.X
3.7.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Browser independent issue

**Comment by tugcekucukoglu** [comment]
What is your exact test case? How could we replicate it with using this [codesandbox](https://codesandbox.io/s/vite-typescript-b7w6q)?
