### ISSUE TITLE
Is it possible to get a different slot for PanelMenuSub?

### ISSUE THREAD

**Issue by itapingu** [primefaces/primevue#1706]
https://github.com/primefaces/primevue/blob/e78feb914a0f6a647c1b5412701eba56a4781451/src/components/panelmenu/PanelMenu.vue#L26

Basically we should be able to define a different slot for "parent level" menu items, and for "childrens".

**Comment by tugcekucukoglu** [comment]
It's on our [roadmap](https://github.com/primefaces/primevue/wiki/Roadmap#menu-components).

Thanks,
