### ISSUE TITLE
Using templating in Menubar does not show dropdown for children items

### ISSUE THREAD

**Issue by ga676005** [primefaces/primevue#1707]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/eloquent-chihiro-mqtwu?file=/src/MenubarDemo.vue

**Current behavior**
When using custom template in Menubar, there's no feature applied, so the nested items are invisible by default, and there is no event documented on the doc that can manually toggle the dropdown.

**Expected behavior**
It should show nested items. 

**Minimal reproduction of the problem with instructions**
```vue
<Menubar :model="items">
   <template #item="{ item }">
     <div>
        {{ item.label }}
     </div>
   </template>
</Menubar>
```

**What is the motivation / use case for changing the behavior?**
Using custom template in Menubar should at least show dropdown for nested items in some ways.

**Please tell us about your environment:**

* **Vue version:** 3.2.20

* **PrimeVue version:** 3.8.2

* **Browser:** Edge  95.0.1020.30

**Comment by tugcekucukoglu** [comment]
While using custom templating, nested items will be invisible. Because, it also expects custom templating for nested items like you did for items.
