### ISSUE TITLE
PickList: drag and drop

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1708]
Please add the ability to drag elements between sheets and across your sheets with the mouse.

Simply put, add drag and drop support

![image](https://user-images.githubusercontent.com/16963395/139233089-e682a2a6-b972-421d-8a8f-1b4d7d79c7f6.png)

https://www.primefaces.org/primevue/showcase/#/picklist

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by antonywyatt** [comment]
> El rastreador de problemas se utiliza para defectos únicamente como parte de nuestro compromiso con la calidad y la mejora continua en todas las áreas. Las mejoras se recopilan como comentarios valiosos de la comunidad y se administran internamente, por lo que este ticket de mejora se traslada a nuestro trabajo interno de gestión de proyectos.

Thank c:
