### ISSUE TITLE
Toastification timeout bar

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1709]
I would like to be able to enable the display of the remaining time before the notification closes.

Also when hovering over notifications to stop the countdown.

Very good notifications are made here, as it seems to me:
https://maronato.github.io/vue-toastification/
https://github.com/Maronato/vue-toastification

You can borrow an idea from them

![image](https://user-images.githubusercontent.com/16963395/139251110-2e650ad6-7503-4793-a930-74f7075abbf3.png)

**Comment by cagataycivici** [comment]
This is available in PrimeVue Blocks;

https://www.primefaces.org/primeblocks-vue/#/application/notification

We may do it as a built-in feature as well, keeping the issue for votes. Thank you.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by allburov** [comment]
> https://www.primefaces.org/primeblocks-vue/#/application/notification

404 - Page not found
The page you are looking for is not found
:(
