### ISSUE TITLE
Calendar manual input not working properly

### ISSUE THREAD

**Issue by alqa-dash** [primefaces/primevue#1712]
Calendar component cleans up date manually typed when dateFormat is applied. It looks like this: when one typed last digit of date - date disappears. If date pasted - everything is ok.

Steps to reproduce:

1. Open page https://primefaces.org/primevue/showcase/#/calendar with latest version
2. Open codesandbox sample (in my case it was composition api). Primevue was 3.8.2
3. Add dateFormat="yy-mm-dd" to the first Calendar element
4. Tried to enter date manually (e.g. 1980-01-01, 2020-10-10, etc)

**Comment by cagataycivici** [comment]
My bad, there are some issues which are fixed now.
