### ISSUE TITLE
Drawer: multi opening 

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1714]
I came across the Drawer implementation

https://quatrochan.github.io/Equal/components/drawer

The idea of opening Multiple Drawer is ingenious.

I would really like primevue to be able to open multiple Drawers in the Drawer (example above).
At the same time, it was visually displayed

Can you do something similar in primevue?

![image](https://user-images.githubusercontent.com/16963395/139405844-f27c868c-c6da-4c54-8ecf-16167f54f041.png)
![image](https://user-images.githubusercontent.com/16963395/139405873-10120720-2acb-4b5e-a1c6-4a67623a95bb.png)
![image](https://user-images.githubusercontent.com/16963395/139405899-23bf3424-bbbb-4b38-9b82-83f5ab479325.png)

**Comment by tugcekucukoglu** [comment]
It's not on the PrimeVue roadmap.

Thanks,
