### ISSUE TITLE
DataTable: Unselect the row using the checkbox doesn't work

### ISSUE THREAD

**Issue by wsaca** [primefaces/primevue#1721]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/youthful-diffie-mi51f

**Current behavior**
Unchecking the row using the checkbox doesn't work.

**Expected behavior**
Unchecking the row using the checkbox should work.

**Minimal reproduction of the problem with instructions**
What's happening is:
1. The row is unselected because the function `toggleRowWithCheckbox()` is called.
2. The row is selected again, maybe the function `onRowClick()` is called.

**Browser:** all

**Comment by tugcekucukoglu** [comment]
While using checkbox/radiobutton selection, `selectionMode` prop for DataTable is not necessary. Because `selectionMode` for Column controls this usage.

**Comment by wsaca** [comment]
@tugcekucukoglu It's important to give a better experience, the documentation doesn't say anything about this restriction, the [datatable doc](https://primefaces.org/primevue/showcase/#/datatable) even show us an example:
```xml
<DataTable :value="cars" v-model:selection="selectedCars" selectionMode="multiple" dataKey="vin">
    <Column selectionMode="multiple"></Column>
    <Column field="vin" header="Vin"></Column>
    <Column field="year" header="Year"></Column>
    <Column field="brand" header="Brand"></Column>
    <Column field="color" header="Color"></Column>
</DataTable>
```
You could check the implementation in PrimeReact to see the expected behavior:
- https://primefaces.org/primereact/showcase/#/datatable/crud

**Comment by tugcekucukoglu** [comment]
The documentation will be fixed. It would be better to create separate tickets for the feature request.

Thanks,
