### ISSUE TITLE
Cannot close the filter menu of a DataTable.

### ISSUE THREAD

**Issue by lucaspouchot** [primefaces/primevue#1724]
Hi, I'm trying to use the filter of the DataTable component,

I override the #filterclear to hide it and the #filterapply to replace the filter behavior, setting the @click of the button, everything works fine except that I don't find a way to close the filter menu when I click on the apply button, how to do it ?

```ts
function onFilterArea(event: Event) {
    // work
    // how to close the filter menu ?
}
```

```vue
<template #filterapply="{}">
    <Button type="button" icon="pi pi-check" class="p-button-success" style="width:100%; margin-top:-1rem" @click="onFilterArea">{{ t('validate') }}</Button>
</template>
```
![https://i.imgur.com/gdBI6LM.png](https://i.imgur.com/gdBI6LM.png)

I'm using primevue 3.8.1 and vue 3.2.12

**Comment by tugcekucukoglu** [comment]
It's an invalid usage. When you didn't call the filterCallback, you couldn't do the default behaviour of filtering. Filter methods of DataTable have never been called.
