### ISSUE TITLE
Add loading indication to treeselect to suport lazy loading

### ISSUE THREAD

**Issue by nclemeur** [primefaces/primevue#1725]
```
[x] feature request
```
**Current behavior**
It is not possible to indicate a loading state in the TreeSelect component. It would be good to pass on the loading state to the underlying Tree component, so that the TreeSelect could also be used in a lazy mode.

**Expected behavior**
Add prop `loading` to TreeSelect component and pass it to the underlyng Tree component.

**Comment by nclemeur** [comment]
Is there any chance to get this included in the next release? I believe this is a trivial change...

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
