### ISSUE TITLE
Dropdown options positioning hard-coded, not responsive

### ISSUE THREAD

**Issue by erod550** [primefaces/primevue#1727]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report 

```

**Current behavior**
Dropdown options div is hard coded in place at the position where it was first opened. Resizing the window with the dropdown open results in the options div detaching from the dropdown and floating on its own in the absolute position where it was created.

**Expected behavior**
Dropdown options div would remain positioned with the dropdown control when the window is resized.

**Minimal reproduction of the problem with instructions**
This can be reproduced on the PrimeVUE demo page: https://primefaces.org/primevue/showcase/#/dropdown
*Expand the Basic drop-down
*Shrink window size horizontally until the left side menu collapses
*Note that the dropdown options are now floating off in space detached from the dropdown.

**What is the motivation / use case for changing the behavior?**
Being able to use this control in a responsive environment

**Please tell us about your environment:**
Vue 3.0 with ASP.NET MVC

* **Vue version:** 3.0.7

* **PrimeVue version:** 3.7.2

* **Browser:** all

**Comment by cagataycivici** [comment]
Can you post a screencast, not able to replicate. Position is recalculated dynamically and resize hides it for me.

**Comment by erod550** [comment]
Sorry, here are two. First one is in my app where a modal stays centered as the screen resizes (just one of many use cases). The dropdown options div opens and stays in a fixed position and does not move with the dropdown itself. The second one is on the PrimeVue demo page where you can see the options stay in a fixed position even when the dropdown itself moves position when shrinking the window.

If you close and reopen the dropdown options after changing window size, it does reposition itself next to the dropdown, but it's just a new hard-coded position.

https://watch.screencastify.com/v/x2E9TkpbAhQ0HEOJWfJ3

https://watch.screencastify.com/v/YCZbhCmXYTAgpNwEz6NU

**Comment by tugcekucukoglu** [comment]
Could you try to use it with latest PrimeVue version?

**Comment by Drumstix42** [comment]
This is still occurring with the latest version(s):
https://codesandbox.io/s/judhg7?file=/src/App.vue
