### ISSUE TITLE
MultiSelect - add option to add a line break instead of cutting off the overlapping items

### ISSUE THREAD

**Issue by matthiashermsen** [primefaces/primevue#1730]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
Items causing an overlapping are cut off with "three dots" as shown in this example

https://jsfiddle.net/gthn1ebd/

Like so

![image](https://user-images.githubusercontent.com/47159597/140517134-1dd752ab-cb4e-44d7-aaec-0bbb7a1ce5a4.png)

You can also remove all the CSS but then the component simply grows

https://jsfiddle.net/kgp0Ltcv/

Like so

![image](https://user-images.githubusercontent.com/47159597/140517392-c3b49ae3-bcd9-461a-87f8-9687da020acd.png)

**Expected behavior**
It would be nice to have an option to add a line break to see all the selected items. Other components seem to use this by default

- Element Plus: https://element-plus.org/en-US/component/select.html#basic-multiple-select

![image](https://user-images.githubusercontent.com/47159597/140518958-6e12207b-06d9-4dd5-9195-8bd3da30e66a.png)

- Vuetify: https://vuetifyjs.com/en/components/selects/#multiple

![image](https://user-images.githubusercontent.com/47159597/140519054-d3ef65f6-e70e-4f76-bfa9-88058fcbda16.png)

**Current solution**
Use custom CSS

**What is the motivation / use case for changing the behavior?**
You don't have to use custom CSS which may cause problems in the future.

* **Vue version:** latest

* **PrimeVue version:** latest

* **Browser:** all

**Comment by htxryan** [comment]
@tugcekucukoglu Where is this in the docs?

For anyone else stumbling across this, there is an actual solution here: https://stackoverflow.com/a/69843663/463907

```css
.p-multiselect {
  min-width: 17rem;
}
.p-multiselect-label {
  display: flex;
  flex-wrap: wrap;
}
.p-multiselect-token {
  margin: 0.1rem;
}
```
