### ISSUE TITLE
Passing ColumnGroup to default DataTable slot doesnt work

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#1731]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

I have BasicTable component where I imported and used DataTable. I've made my own slot inside defaults dataTable slot. 
In my other component i am using basicTable to pass custom colums. When I tired to pass ColumnGroup it doesnt work and throws error: 
![3](https://user-images.githubusercontent.com/34492112/140534951-1f4ed3f7-d4c5-4c21-a61b-db23c0dfe652.PNG)

BasicTable.vue
![t](https://user-images.githubusercontent.com/34492112/140535129-a159bc73-20b5-462f-8e2b-ac74711694ef.PNG)

BasicTable usage:
![2](https://user-images.githubusercontent.com/34492112/140535172-e5d1c83d-c014-42b9-9646-65fae6a198ae.PNG)

* **PrimeVue version:** 3.8.2

**Comment by tugcekucukoglu** [comment]
Issue is not clear, please feel free to reopen with a codesandbox example.

**Comment by mitow7821** [comment]
@tugcekucukoglu here is an example: https://codesandbox.io/s/v3-editor-forked-c92jp?file=/src/Table.vue
