### ISSUE TITLE
Docs: Tooltip and Script Setup

### ISSUE THREAD

**Issue by tft7000** [primefaces/primevue#1736]
I would suggest updating the Documentation for the Tooltip directive for local usage in a script setup environment:

The import must import the Tooltip as `vTooltip` otherwise it is not working:
```typescript
import vTooltip from "primevue/tooltip";
```

Unfortunately this is only mentioned in the RFC for script setup: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#using-directives. I think it might be helpful to mention it here as well, with an example.

see the following working example: if you change the import to the usual `Tooltip` you will get an error `Cannot read properties of undefined (reading 'deep')`

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB2VG9vbHRpcCBmcm9tIFwicHJpbWV2dWUvdG9vbHRpcFwiO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxIHYtdG9vbHRpcD1cIidteSB0b29sdGlwIG1lc3NhZ2UnXCI+VGl0bGU8L2gxPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yMS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJwcmltZXZ1ZS90b29sdGlwXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vcHJpbWV2dWVAXjMvdG9vbHRpcC90b29sdGlwLmVzbS5taW4uanNcIixcbiAgICBcInByaW1ldnVlL3V0aWxzXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vcHJpbWV2dWVAXjMvdXRpbHMvdXRpbHMuZXNtLm1pbi5qc1wiXG5cbiAgfVxufSJ9

```vue
<script setup>
import vTooltip from "primevue/tooltip";
</script>

<template>
  <h1 v-tooltip="'my tooltip message'">Title</h1>
</template>
```

**I'm submitting a ...**  (check one with "x")
```
[x] documentation suggestion
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB2VG9vbHRpcCBmcm9tIFwicHJpbWV2dWUvdG9vbHRpcFwiO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxIHYtdG9vbHRpcD1cIidteSB0b29sdGlwIG1lc3NhZ2UnXCI+VGl0bGU8L2gxPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yMS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJwcmltZXZ1ZS90b29sdGlwXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vcHJpbWV2dWVAXjMvdG9vbHRpcC90b29sdGlwLmVzbS5taW4uanNcIixcbiAgICBcInByaW1ldnVlL3V0aWxzXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vcHJpbWV2dWVAXjMvdXRpbHMvdXRpbHMuZXNtLm1pbi5qc1wiXG5cbiAgfVxufSJ9

**What is the motivation / use case for changing the behavior?**

It might help others to use your library in the new script setup environment.

**Please tell us about your environment:**

* **Vue version:** 3.2.20

* **PrimeVue version:** 3.8.2

**Comment by tugcekucukoglu** [comment]
We will consider it.

Thanks!
