### ISSUE TITLE
[Feature] Treetable: Node-level loading

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primevue#1739]
Hello,

When lazy loading nodes in a TreeTable (@nodeExpand) it would be nice to have a loading animation for just that node instead of using the global :loading property of the TreeTable.

Something along the lines of:

```
export interface TreeNode {
  isLoading: boolean; // <--- new property
  key: string;
  data: any;
  leaf: boolean;
  icon?: string;
  children?: TreeNodeModel[];
}
```

That way, the table is not blocked when loading a single node, and it would not flicker (and be less invasive)

Cheers,
Para

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
