### ISSUE TITLE
Loading prop for DataView component

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#1740]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

As issue title suggests - corresponding to the loading prop for DataTable.

**Comment by tugcekucukoglu** [comment]
Already have it [https://www.primefaces.org/primevue/showcase/#/datatable](https://www.primefaces.org/primevue/showcase/#/datatable) Loading section

**Comment by rubjo** [comment]
For DataView?

**Comment by rubjo** [comment]
@tugcekucukoglu ?

**Comment by WiRight** [comment]
any update?
