### ISSUE TITLE
Menu: Wrong position calculation when scrollbar is activated

### ISSUE THREAD

**Issue by wsaca** [primefaces/primevue#1741]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/hopeful-shamir-tqfk6

**Current behavior**
Menu left position is calculated taking into account the scrollbar width/height, in codesandbox when you click the "wrong" button the menu is shown behind the scrollbar, this behavior is activating the horizontal scrollbar.

**Expected behavior**
Menu position should be calculated without consider the scrollbar.

**Minimal reproduction of the problem with instructions**
In codesandbox I tried to replicate this problem adding two buttons, I'm not using vue in this example because it's not necessary to replicate it.
The only one function I changed was `getViewport()`, because it gives priority to window.innerWidth.

* **Browser:** all

**Comment by cagataycivici** [comment]
Can you please create a new sample with Prime components like menu, issue is not clear for us.

**Comment by tugcekucukoglu** [comment]
Any update on this?

**Comment by wsaca** [comment]
Hi @tugcekucukoglu, I've created another example using primevue 3.11.0.
- https://codesandbox.io/s/serverless-glade-pzujs

As you can see, the horizontal scrollbar is activated when you click the button because the menu is not positioned correctly (it takes into account the scrollbar width to calculate the position).

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
