### ISSUE TITLE
ProgressBar: color text

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1752]
![image](https://user-images.githubusercontent.com/16963395/141652162-293f2ab5-26e5-4261-8055-1762d2a96efc.png)

https://www.primefaces.org/primevue/showcase/#/progressbar

The color of the text is difficult to read against such a background.

I know that it is possible to change the colors in css, but due to the fact that the text is fixed in the middle and there are 2 different colors (filled and not filled), it is quite difficult to choose the color of the unfilled progress bar and the filled one so that the text reads well alone.

I suggest thinking and either choosing good colors in the standard themes, or doing something with the markup. The second is preferable.

**For example:**
1) You can make a background for the text
2) You can fix the progress text to the filled part (see screenshot below)
![image](https://user-images.githubusercontent.com/16963395/141652375-77b02638-fa3e-4a6d-b4f1-d43c2d2c3f9d.png)
3) Move the progress text outside the bar (to the right or left, or above)

Also a few examples for ideas (See the location of the text about progress)

![image](https://user-images.githubusercontent.com/16963395/141652385-0d78ce19-e10d-4089-813c-7c14bffbec49.png)

![image](https://user-images.githubusercontent.com/16963395/141652394-6c6b02d2-adb3-4ade-85b7-ce9499b847a1.png)

![image](https://user-images.githubusercontent.com/16963395/141652458-8fbd712b-5a33-4e71-9d36-fb12c57e5176.png)

![image](https://user-images.githubusercontent.com/16963395/141652494-afcac1d5-6e76-4093-9e6c-7785f79d2a03.png)

![image](https://user-images.githubusercontent.com/16963395/141652521-036e0c34-924a-4198-b75a-15988869f16d.png)

**Comment by cagataycivici** [comment]
Thanks

<img width="1006" alt="Screen Shot 2021-11-15 at 17 50 07" src="https://user-images.githubusercontent.com/686247/141802749-3e6371b7-7638-4565-b1f6-a1f1cad65fca.png">
