### ISSUE TITLE
Can't create column groups via v-for loop

### ISSUE THREAD

**Issue by jtuchel** [primefaces/primevue#1754]
**I'm submitting a ...**

```
[x] bug report
[ ] feature request
[ ] support request
```

Based on the docs https://primefaces.org/primevue/showcase/#/datatable/colgroup I want to create dynamic column groups via code. When hardcoding the HTML everything works fine.

Working demo: https://codesandbox.io/s/proud-voice-myuxr

**CodeSandbox Case (Bug Reports)**

Demo showing the error: https://codesandbox.io/s/cool-snow-lrcg0?file=/src/DataTableColGroupDemo.vue

**Current behavior**
When trying to create the column groups via code I get the following error

![image](https://user-images.githubusercontent.com/92626738/141733907-6dd48818-c1ad-4fb8-8286-fe5d79618a0b.png)

**Expected behavior**
I would expect the same result as seen in the working demo. The column headers should look like

![image](https://user-images.githubusercontent.com/92626738/141734027-57624bff-a1b2-4874-b573-dedad9fc0f78.png)

**Minimal reproduction of the problem with instructions**
Have a look at the file **DataTableColGroupDemo.vue**

**What is the motivation / use case for changing the behavior?**
If this is a bug it would be nice having this fixed to create dynamic column groups via code :)

**Please tell us about your environment:**
- OS: Linx/Win
- IDE: VSC
- Package Manager: npm
 
* **Vue version:** 3.1.5

* **PrimeVue version:** 3.8.2

* **Browser:** Checked with Chrome and Firefox

**Comment by tugcekucukoglu** [comment]
Duplicate [#1630](https://github.com/primefaces/primevue/issues/1630)

**Comment by matthiashermsen** [comment]
@tugcekucukoglu I saw that you have already fixed the error on master ( https://github.com/primefaces/primevue/commit/a51f26ce40ae4dc6df35a457f13a2d400604410a )

Do you know if there are any plans for a next release containing this fix any time soon? (v3.8.3)
