### ISSUE TITLE
Overriding 'global' filterMatchMode for Column requires modifying locale

### ISSUE THREAD

**Issue by mrichar1** [primefaces/primevue#1756]
**I'm submitting a ...** 
```
[ x ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

There are 2 ways to override the filter matchmode for a column - either globally, by passing a modified `filterMatchModeOptions` when initialising PrimeVue (`app.use(PrimeVue, { filterMatchModeOptions: { ...} })`) or by passing an object as a Column property (`:filterMatchModeOptions="matchModes"`)

The behaviour in each of these cases is subtly different. If the Column property is used, then the object is used as-is - however if the global filter is set, then it does an indirect lookup in the `locale` section of the config:

https://github.com/primefaces/primevue/blob/aee227f41eec5f1bd6fff17468266c3068dadb94/src/components/datatable/ColumnFilter.vue#L458-L462

Rather than having different behaviour for 'global' setting versus 'Column' setting, maybe it would be better to use `label` value directly if set, and only use `locale` if no `label` is set/the matchMode is a string, not an object.

Either way the documentation needs updating for DataTable to explain the need to also modify the `locale` if using the global option.

**Comment by tugcekucukoglu** [comment]
Tracked at [#1835 ](https://github.com/primefaces/primevue/issues/1835)
