### ISSUE TITLE
[Calendar] Allow change time values via typing (input)

### ISSUE THREAD

**Issue by nbrylevv** [primefaces/primevue#1769]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Now it's possible to change hour/minute/second in Calendar's dropdown by pressing chevron icon buttons below/above.

**Expected behavior**
A new prop which allows you to manually input time values by replacing value's text (<span>) to input component.
![Calendar, manual time input](https://user-images.githubusercontent.com/12825240/142188917-390061fd-32a4-4dbd-9fe5-633dad563573.png)

**What is the motivation / use case for changing the behavior?**
Pressing chevron icons is not so fast and convenient way to change time values.

* **Vue version:** 3.1.5

* **PrimeVue version:** 3.8.3

**Comment by tugcekucukoglu** [comment]
We have removed 'keepInvalid' property. Please see [#1849 ](https://github.com/primefaces/primevue/issues/1849)

The aim is to keep everything. All PR is always welcomed.
