### ISSUE TITLE
Passing ColumnGroup to default DataTable slot doesnt work

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#1776]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

I have BasicTable component where I imported and used DataTable. I've made my own slot inside defaults dataTable slot. 
In my other component i am using basicTable to pass custom colums. When I tired to pass ColumnGroup it doesnt work and throws error: 
![3](https://user-images.githubusercontent.com/34492112/140534951-1f4ed3f7-d4c5-4c21-a61b-db23c0dfe652.PNG)

BasicTable.vue
![t](https://user-images.githubusercontent.com/34492112/140535129-a159bc73-20b5-462f-8e2b-ac74711694ef.PNG)

BasicTable usage:
![2](https://user-images.githubusercontent.com/34492112/140535172-e5d1c83d-c014-42b9-9646-65fae6a198ae.PNG)

Example: (i've had some problems with slots on codesandbox, please try this example at local env)
https://codesandbox.io/s/v3-editor-forked-c92jp?file=/src/EditorDemo.vue

* **PrimeVue version:** 3.8.2

**Comment by tugcekucukoglu** [comment]
DataTable does not have '#default' slot. Please see provided slots for the [DataTable](https://primefaces.org/primevue/showcase/#/datatable). And also DataTable needs Column or ColumnGroup component to render UI, default slot does not do anything.

**Comment by mitow7821** [comment]
@tugcekucukoglu if it doesnt have default slot, then how I am able to do this? :o  

![image](https://user-images.githubusercontent.com/34492112/144256039-1ef8d090-d20f-446e-bc67-06a38629e86d.png)
