### ISSUE TITLE
[Bug] Toolbar not displaying/working

### ISSUE THREAD

**Issue by AscaL** [primefaces/primevue#1778]
Hi, wanted to let you know that the Toolbar component is not working (I remember it was yesterday) as you can see right on the official docs:
https://primefaces.org/primevue/showcase/#/datatable/crud
https://primefaces.org/primevue/showcase/#/toolbar

Cheers :)

**Comment by cagataycivici** [comment]
Fixed in 3.9.1, also please see;

[3.9.2-SNAPSHOT](https://github.com/primefaces/primevue/wiki/Migration-Guide)

Thank you.
