### ISSUE TITLE
Datatable Lazy Load Filter Menu Calendar filter

### ISSUE THREAD

**Issue by arnyee** [primefaces/primevue#1779]
[ ? ] bug report => Search github for a similar issue or PR before submitting
[ ? ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ? ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110

https://primefaces.org/primevue/showcase/#/datatable/filter

Hi, I hope you can help me with a problem. Please don't be mad, but unfortunately I don't know at this point whether it's a bug or a missing feature or I'm just not find the right solution. I want to be able to pass the Filter Menu date Calendar filter parameters to the backend somehow even with lazy load. In the Lazy load documentation you only show InputText examples, they work but there are no Calendar examples. I hope this is an existing feature, but if not then I would like to ask when it will be?

https://primefaces.org/primevue/showcase/#/datatable/lazy

**Comment by tugcekucukoglu** [comment]
There are many DataTable Filter example in PrimeVue showcase. I think these are easily implemented.
