### ISSUE TITLE
The InputNumber TypeScript definitions does not specify null as a model value

### ISSUE THREAD

**Issue by emeliehaggstrom** [primefaces/primevue#1782]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/hungry-ritchie-pc2gp?file=/src/App.vue

**Current behavior**

The TypeScript definitions specify that the `v-model` of an InputNumber component only accepts a `number` or `undefined` as value. However, the InputNumber component itself sets the value to `null` if the input field is empty. This makes the input invalid according to the TypeScript definition. We are unable to use InputNumber components without setting the attribute `allow-empty="false"`, otherwise we will have to check for `null` with a `v-if` on the input field, which in turn hides the input field if it lacks a value. 

You can find the TypeScript definition here: https://github.com/primefaces/primevue/blob/af6154f9dcac348dda0c715a4d03d4561b3b2565/src/components/inputnumber/InputNumber.d.ts#L2

**Expected behavior**

We expect that either the TypeScript definition specify that the value can be `null`, or that the input value is never set to `null` in the first place. 

**Minimal reproduction of the problem with instructions**

Open the CodeSandbox example and edit the value of the input field to see that it switches between a `number` and `null` value. 

**What is the motivation / use case for changing the behavior?**

To make the typescript definition match the functionality of the component.

**Please tell us about your environment:**

Windows 10 and macOS 12.0.1
npm

* **Vue version:** 3.X

Vue 3.2.20

* **PrimeVue version:** 3.4.X

3.8.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 96

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/1836

Best Regards,
