### ISSUE TITLE
Dialog header not visible

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#179]
After introducing the scroll: https://github.com/primefaces/primevue/issues/153, https://github.com/primefaces/primevue/issues/145 .
Would be nice to show the dialog header with the close button always on top:
![image](https://user-images.githubusercontent.com/13495631/73517460-6f33c880-43f3-11ea-9f36-e11b5091f616.png)

**Comment by mertsincan** [comment]
Thanks a lot for the screenshot. Fixed for next version.

**Comment by fairking** [comment]
@mertsincan I always glad to help you with the testing guys.

**Comment by cagataycivici** [comment]
There is a live demo for long content now;

https://www.primefaces.org/primevue/#/dialog

**Comment by fairking** [comment]
Thanks a lot guys for your hard work.
