### ISSUE TITLE
Cannot focus on filter input when dropdown/multiselect inside bootstrap modal

### ISSUE THREAD

**Issue by nsetyo** [primefaces/primevue#1793]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/immutable-wave-rvf9x?file=/src/MultiSelectDemo.vue

**Current behavior**
Open bootstrap modal with dropdown/multiselect, click to open, click filter input, close button get focused 
![image](https://user-images.githubusercontent.com/4555074/142714727-b9fe8dee-bdda-479f-af41-7fc5b6e8bfc2.png)

**Expected behavior**
filter input get focus

**Minimal reproduction of the problem with instructions**
Open bootstrap modal with dropdown/multiselect, click to open, click filter input, close button get focused

**Comment by anykate** [comment]
Yes please fix this bug on priority basis. As of now, what I am doing:
1) <MultiSelect ........................... :showToggleAll="false"/>
Then it works as expected.

But I need to show the "Toggle All" button and also set the focus to the 1st item in my filter items. Since this is not working, users are unable to scroll down the filter list with ArrowUp and ArrowDown keys and hence they cannot select any item from the filter list by pressing "Enter" key...

Please resolve this on priority basis.

Thanks,
Aniket

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.

**Comment by cyhnkckali** [comment]
I think this problem is not solved. I am using primevue v3.15 and there is no filter input focus in bootstrap mode.

**Comment by esviniciuscruz** [comment]
> I think this problem is not solved. I am using primevue v3.15 and there is no filter input focus in bootstrap mode.

Just add the property: append-to="self"

**Comment by viniciusrvcruz** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [x] bug report => Search github for a similar issue or PR before submitting
> [ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
> [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
> ```
> 
> **CodeSandbox Case (Bug Reports)**
> 
> https://codesandbox.io/s/immutable-wave-rvf9x?file=/src/MultiSelectDemo.vue
> 
> **Current behavior** Open bootstrap modal with dropdown/multiselect, click to open, click filter input, close button get focused ![image](https://user-images.githubusercontent.com/4555074/142714727-b9fe8dee-bdda-479f-af41-7fc5b6e8bfc2.png)
> 
> **Expected behavior** filter input get focus
> 
> **Minimal reproduction of the problem with instructions** Open bootstrap modal with dropdown/multiselect, click to open, click filter input, close button get focused

Just add the property: append-to="self"
