### ISSUE TITLE
Make it possible to apply theme CSS to overall page

### ISSUE THREAD

**Issue by akarelas** [primefaces/primevue#1794]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
I cannot create a CodeSandbox case, because even the default CodeSandbox you give below does not display any text on the white page (using Firefox on Linux).

```
https://codesandbox.io/s/primevue-issue-template-v3-5tlbl
```

**Current behavior**
When I follow your beginners' guide and create a page with a dark theme, the background of the page is still white.

**Expected behavior**
There should be a way to make the background dark, with the correct color the theme is good for.

**Minimal reproduction of the problem with instructions**
1. Follow the guide and use a dark theme.
2. Look at the page.
3. It has a light background.

**What is the motivation / use case for changing the behavior?**
I don't know what CSS I should write to make my page dark, and have the right fonts and font colors outside of components, when I pick a dark (or even light) theme.

**Please tell us about your environment:**
Linux

* **Vue version:** 3.X
3.2.22

* **PrimeVue version:** 3.4.X
3.9.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox on Linux

**Comment by tugcekucukoglu** [comment]
Themes effects components and importing a theme does not effect your layout for example body background or font family. So importing a theme make it easy to use the exported colors, font-family etc. Please check main.js and index.css in [this example](https://codesandbox.io/s/lara-text-qwoop?file=/src/index.css).
