### ISSUE TITLE
DataTable "$event" argument on page/sort events does not contains filterSearchMode.

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#181]
FilterSearchMode in lazy mode needs to be sended into server to correctly perform database query. 
This  information is provided in PrimeUI datatable widget.

**Comment by cagataycivici** [comment]
filterMatchModes property is now passed such as event.filterMatchModes[fieldName]= 'contains';

As a side note, a more enhanced example including page-sort-filter with a sample backend is being worked on and will be available at a github repository.

**Comment by 1Map** [comment]
@cagataycivici Can I also please have the link to the github example that you talked about here in 2020.
