### ISSUE TITLE
Sidebar overlay not removed after changing position

### ISSUE THREAD

**Issue by wolfsblu** [primefaces/primevue#1823]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request 
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/sad-wind-mxfmq?file=/src/App.vue

**Current behavior**
When changing the `position` of an open Sidebar the close button does not remove the overlay.

**Expected behavior**
The overlay gets removed after closing the Sidebar

* **Vue version:** 3

* **PrimeVue version:** 3.9.1

* **Browser:** all

**Comment by cagataycivici** [comment]
Will be resolved via;

#3474
