### ISSUE TITLE
Calendar manual input doesn't work

### ISSUE THREAD

**Issue by luk9400** [primefaces/primevue#1825]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/o5ctk?file=/src/CalendarDemo.vue

**Current behavior**
You are unable to manually type in a date (it works only for the timepicker)

**Expected behavior**
I would like to enter or edit a date manually

**Minimal reproduction of the problem with instructions**
Try to type in a date in "Basic" or "DateFormat" calendar. There is no cursor. It works only for "Time / 12h".

I think it's due to those two changes https://github.com/primefaces/primevue/commit/bd1b2ab1b063677a4f318586b4222c0b20cf27d9, https://github.com/primefaces/primevue/commit/3355a3ad5696660f05aa1e66456bf4eb747f2566, where the cell in overlay initially gets focus instead of the input.

**Please tell us about your environment:**

* **Vue version:** 3.2.22

* **PrimeVue version:** 3.9.1

* **Browser:** [Firefox 93 | Opera 80]

**Comment by havist** [comment]
Same issue here.

**Comment by cavanh** [comment]
Same.

**Comment by shoeb-howlader** [comment]
facing same issue

**Comment by titou10titou10** [comment]
Is this working for you?
Not for me with primevue v3.26.1 and vue 3.2.32...

**Comment by Chrisposure** [comment]
Same here! When will this be fixed?

**Comment by stoked74** [comment]
Same here.

**Comment by schreibermerc** [comment]
For me it is also not working in 3.31.0.
Are there any news, when this will be fixed?

**Comment by omzy** [comment]
It seems this issue has resurfaced, from a release at some point this year.

Can this issue be re-opened please, or do you need us to log another issue?

**Comment by SwenVogel** [comment]
I have the same problem with version 3.32.0. This issue should be reopened.

**Comment by bdebut01** [comment]
+1 with 3.32.0

**Comment by bdebut01** [comment]
Link to (currently) Open issue
https://github.com/primefaces/primevue/issues/3624

**Comment by dragomirweb** [comment]
+1 with 3.25.0

**Comment by berkanyldrim** [comment]
+1 with 3.28.0

**Comment by agm1984** [comment]
+1 with 3.23 and 3.34.

**Comment by trajano** [comment]
+1 3.49.0
The test I had was set manual input to true and specify a min and max date range
I enter the value manually but when I press tab the data disappears.
