### ISSUE TITLE
disabled attribute on menuitem doesn't work on custom template

### ISSUE THREAD

**Issue by ahyagoub40** [primefaces/primevue#1829]
```
       <Menu :model="items" >
              <template #item="{item}">
                <div @click.stop="item.command">
                  <i :class="['pi', item.icon]" />
                  <span>{{item.label}}</span>
                </div>
              </template>
            </Menu>
            
       export default {
	data() {
            return {
	        items: [
		    {
			label: 'Update',
			icon: 'pi-refresh',
			command: () => {}
		    },
		    {
			  label: 'Delete',
			  icon: 'pi-times',
                           disabled: true,
			  command: () => {}
		    },
    
	        ]
            }
          }
}
```
the disabled attribute in this case doesn't work, the `Delete` item will still be enabled and clickable.
I tried adding the `.p-disabled` class directly on the dom and it was working fine, I also tried the above example without using the custom template

I used this for the template
```
<Menu :model="items" />
```
the `.p-disabled` attribute works and it was added to the `<a>` tag that is added automatically by primeVue, but when i am using custom template, I am adding my own html and so the `.p-disabled` class doesn't get added anywhere.
![Screen Shot 2021-11-25 at 10 47 36 AM](https://user-images.githubusercontent.com/57871430/143484691-eabfdf7d-74ea-45f3-ab03-d0d9784ad2a6.png)

would it not make sense to add the class to the <li> tag instead because it is still there with custom template? And also I would want to override the styles on the <li> if it is disabled. not just part of.

side note: Also, the whole reason I am using custom template is I want to add custom icons, that aren't provided by prime vue
Thanks

**Comment by tugcekucukoglu** [comment]
When you use templating, menu does not check item is disabled or not. It's the same logic you used in your example `@click.stop="item.command"`

You could add this `<div :class="{'p-disabled': item.disabled}">`
