### ISSUE TITLE
Accordion Typescript declaration

### ISSUE THREAD

**Issue by MichaelVonB** [primefaces/primevue#1830]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Typscript declaration file does not fit to current implementation

**Expected behavior**
Declaration should match implementation

**Minimal reproduction of the problem with instructions**
In Accordion.vue line 55 to 81 we have
 this.$emit(eventName, {
                    originalEvent: event,
                    index: i
                });
the event interface should hence look like {originalEvent: event, index: number}. In Accordion.d.ts the event is defined as
e: {originalEvent: Event, tab: any})

**What is the motivation / use case for changing the behavior?**
Fix my typescript warnings

**Please tell us about your environment:**
VSCode, Volar

* **Vue version:** 3.02

* **PrimeVue version:** 3.8.1 - but its still on master

**Comment by tugcekucukoglu** [comment]
Fixed for the next version. 

Thanks,
