### ISSUE TITLE
Fileupload is not working on backend api request

### ISSUE THREAD

**Issue by Muhammedzturk** [primefaces/primevue#1832]
I am using primevue for vue. The use of fileupload there is as follows. But when I write the api end of a remote server in the url part, it does not receive the request on the backend. How should I use it?
```
<FileUpload name="demo[]" url="http://10.0.0.204:5001/api/issue/demo" @upload="onUpload" :multiple="true" accept="image/*" :maxFileSize="1000000">
        <template #empty>
          <p>Drag and drop files to here to upload.</p>
        </template>
      </FileUpload>
```

**Comment by tugcekucukoglu** [comment]
Please use the forum or discord channel for questions and help requests.

**Comment by D-Lite** [comment]
@Muhammedzturk 

You can check out this example for future reference https://codesandbox.io/s/primevue-fileuploader-custom-q2dqhh?file=/src/FileUploadDemo.vue

**Comment by stevegiorgi** [comment]
This example only half works.  The file upload loses reactivity when the custom upload is set to true.  If you upload a file with this set to false, the widget will show a preview of the file once uploaded.  If you've created a custom template it will also refresh whatever logic you may have defined (e.g. to show a delete button and preview thumbnail).  The widget view will update automatically with the custom upload set to false, but you must refresh the page with it set to true.  Any ideas why this might be?  I have tried to force a re-render of the component by setting a key and updating it whenever an action occurs.
