### ISSUE TITLE
ConfirmDialog - no onCLose event propogated

### ISSUE THREAD

**Issue by satanshiro** [primefaces/primevue#1833]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request 
[ ] support request 

confirm dialog does not allow me to hook to event of close dialog only reject.
In other words I can only do something if "no" was pressed but if anything outside of the confirm popup was pressed and it became hidden I cannot write code that will follow up on (ofcourse unless I manually add event listener).
I suggest to either on modal close fire the reject call back
or add another event of onPopupClosed

**Comment by tugcekucukoglu** [comment]
ConfirmationService provides two event `close` and `require`.  The close event could be used binding an event where you prefer.

**Comment by satanshiro** [comment]
@tugcekucukoglu I have double checked the close and require are to **invoke** close, i.e. when called will close the dialog.
I cannot run a callback function to event of onClose, only onReject
![image](https://user-images.githubusercontent.com/38865738/159919266-b7a8fe1c-e2e3-434f-a194-081dddf5b42e.png)

**Comment by xidan-developer** [comment]
ConfirmationService предоставляет два события closeи require. Событие закрытия можно использовать для привязки события там, где вы предпочитаете. как это работает ? можно пример пж

**Comment by BrendanBenoit** [comment]
For anyone stumbling on this, there is an `onHide` confirmation option available that is triggered when the ConfirmDialog is being closed/dismissed: https://primevue.org/confirmdialog/#api.options.ConfirmationOptions.onHide
