### ISSUE TITLE
Conditional Expander in a Column in a Data Table

### ISSUE THREAD

**Issue by websuasive** [primefaces/primevue#1834]
This started as a question asked in the forums and now Mert Sincan asked for it to be raised as a github issue (see https://forum.primefaces.org/viewtopic.php?f=57&t=67080) as presumably a bug report...

The problem is using a Datatable with the expander prop, there appears to be no way of getting the row data down into the conditional statement.

`<Column  expander={isNeeded ? true : false} />`

To see the problem in action, take a look at: https://codesandbox.io/s/vue-primevue-forked-oyitn?file=/src/App.vue

You can see the expander function is calling anySubTasks() but there appears to be no way of getting to the row data in order to decide whether to return true or false to the expander being shown.

The reason for wanting to conditionally set the expander is so that it is not shown if there isn't any nested data - ie in the example the second task (wash the car) doesn't have any sub tasks yet the system is misleading the user into thinking that there are (until the click the expander and find the nested datatable is empty).

In the sandbox, we are using 

    "primevue": "3.7.1",
    "vue": "3.1.5"

On my local system where I am trying to using this function for real, I am using primevue. 3.82 which is the latest composer wants to install.

Any questions, please ask.

**Comment by cristinafernandez1234** [comment]
I am having the same issue and I found a workaround while waiting for a good solution in https://github.com/primefaces/primeng/issues/1586.

```
<DataTable
   ...
    :row-class="rowClass">
```

```
methods: {
  rowClass(rowData) {
      return rowData.children ? "" : "no-expander";
    }
}
```

```
<style>
.p-datatable .p-datatable-tbody > tr.no-expander > td .p-row-toggler {
  display: none;
}
</style>
```

**Comment by tugcekucukoglu** [comment]
Actually this is a pretty good solution. Expander column needs to be render otherwise all rows will be different number of cells and it is not an expected behavior. And [this example](https://codesandbox.io/s/cond-expander-v6zsy?file=/src/DataTableDemo.vue) seems solves the problem.

**Comment by websuasive** [comment]
Thank you - I

> I am having the same issue and I found a workaround while waiting for a good solution in [primefaces/primeng#1586](https://github.com/primefaces/primeng/issues/1586).
> 
> ```
> <DataTable
>    ...
>     :row-class="rowClass">
> ```
> 
> ```
> methods: {
>   rowClass(rowData) {
>       return rowData.children ? "" : "no-expander";
>     }
> }
> ```
> 
> ```
> <style>
> .p-datatable .p-datatable-tbody > tr.no-expander > td .p-row-toggler {
>   display: none;
> }
> </style>
> ```

Thank you Cristina,

I appreciate your help - and yes it works for me too,
Mark

**Comment by websuasive** [comment]
> Actually this is a pretty good solution. Expander column needs to be render otherwise all rows will be different number of cells and it is not an expected behavior. And [this example](https://codesandbox.io/s/cond-expander-v6zsy?file=/src/DataTableDemo.vue) seems solves the problem.

Hi Tuğçe

Ok - I understand the column needs to be rendered and that this works around the issue.

But from a niceness point of view, as the expander parameter already accepts a true or false which dictates whether it should shown or not - wouldn't it be nicer if we could programmatically set that true or false from the data.  

Rather than hiding the expander via some special code hung off of the rowClass function that injects some special CSS....?

And if not, is it possible for the documentation to be updated please?

As this threw me as well as quite a few other people...

Thank you for your help,
Mark

**Comment by christhb** [comment]
The response that Cristina left works great, however, I require a Primevue `<Button />` with an onClick function in place of where display would be "none", here is a post for reference: https://stackoverflow.com/questions/74281627/primevue-datatable-expander-with-conditionals

Is this even possible through this setup?

**Comment by hasanradi93** [comment]
To resolve the issue, add the following CSS without the scoped attribute:
`<DataTable
   ...
    :row-class="rowClass">`
    `function   rowClass(rowData) {
      return rowData.children ? "" : "no-expander";
    }`
    `<style>
    .p-datatable-table .p-datatable-tbody > tr.no-expander > td .p-row-toggler { display: none !important; }
    </style>`

**Comment by byronigoe** [comment]
It's silly that we need this workaround, and it has been 7 years since being told to "wait for 5.1.0".

The CSS selector I had to use is:
`.p-datatable-table .p-datatable-tbody > tr.no-expander > td .p-datatable-row-toggle-button`

**Comment by LewisDamy** [comment]
I've faced the same issue, however in my case, I prefered to create manually the toggle icon in order to add the conditional logic, by adding the `<template #body="slotProps">` on the `<Column expander>`.

In this case the logic of expanding/collapsing as well as the validation whether or not the row is expanded needed to be done manually.

The logic was:

```vue

<DataTable
      :value="customers"
      v-model:expandedRows="expandedRows"
      ...
    >
      <Column expander style="width: 5rem">
        <template #body="slotProps">
          <div class="flex justify-center">
            <button
              v-if="slotProps.data.id % 2 !== 0"
              @click="handleToggleRow(slotProps.data)"
            >
              <i
                :class="
                  isRowExpanded(slotProps.data)
                    ? 'pi pi-chevron-down'
                    : 'pi pi-chevron-right'
                "
              ></i>
            </button>
          </div>
        </template>
       </Column>
</DataTable>
```
Now the `expandedRows` control muiltiple rows being expanded.

```vue
<script setup>
import { ref, onMounted } from 'vue';

const customers = ref([]);
const expandedRows = ref([]);

// Expand/collapse manually
const handleToggleRow = (rowData) => {
  const index = expandedRows.value.findIndex((r) => r.id === rowData.id);
  if (index !== -1) {
    expandedRows.value.splice(index, 1); // Collapse
    onRowCollapse(rowData);
  } else {
    expandedRows.value.push(rowData); // Expand
    onRowExpand(rowData);
  }
};

// Check if row is expanded
const isRowExpanded = (rowData) => {
  return expandedRows.value.some((r) => r.id === rowData.id);
};


// Handle onRowExpand
const onRowExpand = (expandedRow) => {
  console.log('Row Expanded:', expandedRow);

  // More logic here
};

// Handle onRowCollapse
const onRowCollapse = (collapsedRow) => {
  console.log('Row Collapsed:', collapsedRow);

  // More logic here
};

</script>
```

Result:

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/cb150838-b5a4-469c-aa09-abdabfc9c5ce" />


This has been work fine with:
```
"primevue": "4.2.5",
"vue": "^3.4.21"
```

Take a look at: https://stackblitz.com/edit/xmdjekhu-9vjzzmnt?file=src%2FApp.vue

**Comment by NikoGJ** [comment]
Another possible "hack" to achieve this is using the Pass Through API:
```
<Column
    expander
    :pt="{
        rowToggleButton(options) {
            const row = options.parent.props.rowData
            if (<some condition>) {
                return {
                    style: 'display: none',
                }
            }
        },
    }"
/>
```
