### ISSUE TITLE
[feature request] OverlayPanel display direction

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#1838]
For the tooltip component, you can define on which side the tooltip should be displayed.
It would be great if there were a similar option for the OverlayPanel.
For example, displaying the overlay to the right instead of downwards.

**Comment by arnyee** [comment]
This is a good idea. I think this feature would also be very useful

**Comment by Rakasch** [comment]
Here's an example problem case.
The Overlay hides the other IconButtons.
It would be much more convinient, if the Overlay was displayed to the left of the Icon.
![image](https://user-images.githubusercontent.com/8471027/156008043-7fdb0996-9b8a-4590-ae27-41228f83e240.png)

**Comment by xzx-xzx** [comment]
Specifying the display direction is very useful. Please use it as soon as possible.

**Comment by tugcekucukoglu** [comment]
Please track at https://github.com/primefaces/primevue/issues/1167
