### ISSUE TITLE
Feature Request: Reduce amount of this.$primevue dependencies

### ISSUE THREAD

**Issue by kris-sum** [primefaces/primevue#1839]
**I'm submitting a ...**  
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

Lots of primevue components work completely standalone as SFC modules, but some like Dropdown need the app global $primevue  to be registered, and will error becuase they can't access this.$primevue inside their components. I understand that they are needed for global texts and preferences, but it would be handy if components like Dropdown could reduce their dependency on it by providing sane defaults if this.$primevue is not available.

**Current behavior**
Dropdown component errors in panelStyleClass / emptyFilterMessageText / emptyMessageText / onOverlayEnter as this.$primevue is not accessible.

**Expected behavior**
Component should be able to function without the $primevue app global.

**Minimal reproduction of the problem with instructions**

    import Dropdown from 'primevue/dropdown/sfc';
    ... then use demo Dropdown code from documentation

**What is the motivation / use case for changing the behavior?**
Reducing usage of the app global $primevue will mean the component is able to be used standalone without registering Primevue against the vue app. This shoudln't be too painful to do, e.g.

    
        onOverlayEnter(el) {
            ZIndexUtils.set('overlay', el, this.$primevue.config.zIndex.overlay);
            ...

becomes

        onOverlayEnter(el) {
            ZIndexUtils.set('overlay', el, this.$primevue ? this.$primevue.config.zIndex.overlay : 1000);
            ...

* **Vue version:** 3.1.0
* **PrimeVue version:** 3.9.1
* **Browser:** all

**Comment by kris-sum** [comment]
P.S. Love the library, keep up the good work :)

**Comment by cagataycivici** [comment]
So many components depend on core config like z-index layering, locale and more so we need to keep this.$primevue or usePrimeVue. I also see many vue libs usually require plugin installation with Vue.use(lib) which helps us a lot. So we've decided not to do any changes. Thank you for your feedback.
