### ISSUE TITLE
DataTable component does not work correctly "Checkbox selection" together with "lazy"

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#1841]
When using "Lazy loading" and "Checkbox selection" in the "DataTable" component, using the "select all" button does not work correctly (if the number of pages is more than one).

It allows you to select all the elements on the page, but does not remove this selection.
If you make a filter by data (so that there are only one page of results), then everything works.

**Vue version:** 3.2.23
**PrimeVue version:** 3.9.1
**Browser:** all 

<img width="1307" alt="pic_bug2" src="https://downloader.disk.yandex.ru/preview/31a8938956dd924cc1bb7df860c5cccf4fb09cc244663b550c0f26633f9b7194/61aa7c09/ZB3j7R1fK3n0QxvaMyFDCpPGLRLffT-IdwoZxN8J4ktlW3Wa26e0WX0WGEIw04hSSNW332shnUMKWxLk69SPuA%3D%3D?uid=0&filename=2021-12-03_19-20-13.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048">

**Comment by mertsincan** [comment]
Hi,

I added a demo related to it on the next version.

Best Regards,

**Comment by atach** [comment]
Thank you
