### ISSUE TITLE
Add data param to exportCSV method on DataTable

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#1845]
By default, only the data that is in the "value" model itself is exported.
How to export all data. Not only those that are rendered, but all that exist on the server?

Is it possible to export an array for function exportCSV()?

**Vue version:** 3.2.23
**PrimeVue version:** 3.9.1
**Browser:** all

**Comment by mertsincan** [comment]
Hi,

You can use exportCSV method with custom data.
```
   /**
     * Exports the data to CSV format.
     * @param {DataTableExportCSVOptions} [options] - Export options.
     * @param {Object[]} [data] - Custom exportable data. This param can be used on lazy dataTable.
     */
    exportCSV: (options?: DataTableExportCSVOptions, data?: any[]) => void;
```
