### ISSUE TITLE
Dropdown search dont work, change the event to OnChange

### ISSUE THREAD

**Issue by juandfranco** [primefaces/primevue#1850]
Greetings, I have found a post where the problem that is being presented is replicated, this one is replicable, simply download gboard on an android phone from the play store, use this keyboard and you will notice that the search does not work. and when it does it does it after you exit the dropdown, this is really tricky since brands like motorola, huawei, nokia, xioami use gboard by default.

This is the link of the reported error, I am not advanced in vue and I do not know how to recompile the dropdown module to change the event to onChange

[https://github.com/primefaces/primevue/issues/1389](https://github.com/primefaces/primevue/issues/1389)

Thanks.

**Comment by tugcekucukoglu** [comment]
Please track issue from here [#1389 ](https://github.com/primefaces/primevue/issues/1389)
