### ISSUE TITLE
Missing props in ConfirmationOptions.d.ts

### ISSUE THREAD

**Issue by ReevMich** [primefaces/primevue#1852]
When running a production build of my application, im getting typescript errors of the property `Header` is not apart of type ConfirmationOptions in PrimeVue version 3.10.0. 

I just forked the project and will submit a pull request shortly.

**Comment by NeluQi** [comment]
Please fix it faster

**Comment by ReevMich** [comment]
@NeluQi you should use the prior version, as I am waiting for my PR #1853 to be reviewed and merged.
