### ISSUE TITLE
Toast: Production Typescript Build Error: Type detail

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1856]
I am using toast and my template for it

i do
  this. $ toast.add ({
           severity: 'info',
           summary: notificationMessage,
           detail: ms,
           life: 5000,
           group: 'notificationMessage',
         });

In detail, I do not pass a string, but my object, which I then display in my template.
![image](https://user-images.githubusercontent.com/16963395/145321837-751d7bc1-d54d-4954-bc05-b55d2120c78f.png)

Make detail: string | any

**Comment by tugcekucukoglu** [comment]
I can not replicate it. Do you have a codesandbox?

**Comment by NeluQi** [comment]
> I can not replicate it. Do you have a codesandbox? And what is your environment?

Hi
Here's an example.
https://codesandbox.io/embed/cool-cerf-0rlvr?fontsize=14&hidenavigation=1&theme=dark

Since the "detail" type is defined as string, I cannot set my object in "detail".
This greatly reduces the functionality, I want to display a lot of data in the notification
This error codesandbox does not really show.


In general I ask in "src / components / toast / Toast.d.ts" in interface ToastMessageOptions

Change follower:
With
  detail ?: string | undefined;
on the
  detail ?: string | undefined | any;


Since I want to transfer an object in detail and display it on the template.
or add one more property "CustomData: any" to ToastMessageOptions

**Comment by slumtrimpet** [comment]
@tugcekucukoglu 

Not sure if this is the same issue... but how is one supposed to assign 'severity' (in a typescript friendly way) without ToastMesasgeSeverityType being exported in https://github.com/primefaces/primevue/blob/master/src/components/toast/Toast.d.ts ?

Is this error more helpful?

![Screenshot from 2022-01-06 13-13-31](https://user-images.githubusercontent.com/4440932/148430809-6def991c-8d6f-494e-af36-021e91a26333.png)

**Comment by tugcekucukoglu** [comment]
@NeluQi @slumtrimpet  Could you please check https://github.com/primefaces/primevue/blob/master/src/components/toast/Toast.d.ts#L22 and https://github.com/primefaces/primevue/blob/master/src/components/toast/Toast.d.ts#L92
these changes? If the issue still persist please let me know before the next release?

Thanks,

**Comment by NeluQi** [comment]
> @NeluQi @slumtrimpet Could you please check https://github.com/primefaces/primevue/blob/master/src/components/toast/Toast.d.ts#L22 and https://github.com/primefaces/primevue/blob/master/src/components/toast/Toast.d.ts#L92 these changes? If the issue still persist please let me know before the next release?
> 
> Thanks,



Everything works, thank you
(I only looked at the code, I will really check it at the next release in my project. By the code, this is like what I wanted)

**Comment by slumtrimpet** [comment]
@tugcekucukoglu 

I should probably open another issue on this... if it's an issue at all, but looking at this with fresh eyes today I'm seeing what's going on.

This is my usage of toast and you can see 

```
if (resp != 'OK') {
        let severity = 'info';
        let summary = 'System Status';
        if (resp.indexOf('ERROR') >= 0) {
          severity = 'error';
          summary = 'Validation Error';
        }
        toast.add({
          severity: severity,
          summary: summary,
          detail: resp,
          life: 3000,
        });
      }
```

With the current implementation, there's not a way to dynamically set 'severity' as typescript can't evaluate that our local variable here is one of the valid options from https://github.com/primefaces/primevue/blob/master/src/components/toast/Toast.d.ts#L6.

VSCode still gripes about the severity usage above with:
https://user-images.githubusercontent.com/4440932/148430809-6def991c-8d6f-494e-af36-021e91a26333.png

**Comment by tugcekucukoglu** [comment]
@slumtrimpe I replicate the issue now. Could please open  a new issue for this. 

Thanks,
