### ISSUE TITLE
MultiSelect and Dropdow: Mobile adaptation

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1857]
https://codesandbox.io/embed/unruffled-ritchie-lqbt5?fontsize=14&hidenavigation=1&theme=dark

If there is a long line in the data, a terrible scroll appears on a mobile device

You need to make a stroll inside the drop-down list, and not so that a scroll appears on the whole page

Also when using
  html,
   body {
     overflow-x: hidden;
   }

   body {
     position: relative
   }

Then on the mobile you DO NOT open the choice at all (the one where there is long text).

On the mobile version, I do not want to see horizontal strolls of the entire page

Or cut off the text

![image](https://user-images.githubusercontent.com/16963395/145324356-7fa732d0-44bf-48c6-8584-30e83b67ef20.png)

![image](https://user-images.githubusercontent.com/16963395/145324518-540ef320-fc69-43f8-8f40-ab8372f920a7.png)

There are a lot of similar things on the mobile version when there is a lot of data | they are long, check all components with big lines

**Comment by tugcekucukoglu** [comment]
Mobile adaptation is on PrimeVue's roadmap not just MultiSelect and Dropdown, but all teleport components.

So closing for now.
