### ISSUE TITLE
Feature request: Make Toast usable in vuex

### ISSUE THREAD

**Issue by mkalus** [primefaces/primevue#1858]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

It would be helpful to make the toast service available in vuex.

**Minimal reproduction of the problem with instructions**

`main.js`:

```javascript
import { createApp } from 'vue';
import App from './App.vue';
import makeStore from './store';
import PrimeVue from 'primevue/config';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';

import 'primevue/resources/themes/saga-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';

const app = createApp(App);
//app.config.unwrapInjectedRef = true; // TODO: remove in next minor Vue version

// initialize PrimeVue
app.use(PrimeVue);

app.use(ToastService);

// create store
const store = makeStore();

app.use(store).mount('#app');
```

`App.vue`:

```vue
<template>
  <Toast />

  <button @click="clicked">Test</button>
</template>

<script>
export default {
  data() {
    return {
      messages: [],
    }
  },
  methods: {
    clicked() {
      this.$store.commit('test');
    }
  }
};
</script>
```

`store/index.js`:

```javascript
import { createStore } from 'vuex';
import { useToast } from 'primevue/usetoast';

export default function makeStore() {
    return createStore({
        mutations: {
            test() {
                // this does not work!
                const toast = useToast();

                toast.add({
                    severity: 'info',
                    summary: 'Info Message',
                    detail: 'Message Content',
                    life: 3000,
                });
            },
        },
    });
}
```

**What is the motivation / use case for changing the behavior?**

It would be great to have the means to access the toast service from vuex or other non-component libraries. Maybe I have missed something in the documentation, but in that case it would be helpful to add an example to the documentation on how to achieve this.

*Note:* Passing the $toast-Object to vuex via commit payload works, of course, but I find this a bit unwieldy.

**Please tell us about your environment:**

* **Vue version:** 3.2.23
* **PrimeVue version:** 3.10.0
* **vuex version:** 4.0.2
* **Browser:** all

**Comment by mkalus** [comment]
A note for a possible resolution: Pass the app reference into the store and access the app.config.globalProperties.$toast instance. This is not very elegant, but works, I guess.

**Comment by tugcekucukoglu** [comment]
Thanks for your report.
