### ISSUE TITLE
InputNumber: allow using dot key of numeric keypad for decimal for locale fr-FR

### ISSUE THREAD

**Issue by lobodol** [primefaces/primevue#1859]
**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
When typing decimal using numeric keypad, nothing happens when hitting the dot key. I have to use the comma key, which is far away from the numeric keypad. This is not handy.

**Expected behavior**
I expect I can use the dot key of the numeric keypad to type decimal numbers.

**Minimal reproduction of the problem with instructions**
```html
  <InputNumber
    v-model="value"
    mode="decimal"
    locale="fr-FR"
    :min-fraction-digits="0"
  />
```

**What is the motivation / use case for changing the behavior?**
My client uses numeric keypad and asked me to be able of using the dot key for decimal numbers.

**Please tell us about your environment:**
* package manager: yarn
* docker image: node:16-slim
* server: nginx
* **Vue version:** 3.0.5
* **PrimeVue version:** 3.9.1
* **Browser:** Firefox 95

Thanks for reading,  
Regards

**Comment by allanos-sisteplant** [comment]
Same problem here in Spanish. [es-ES]

When typing into an <input> in html5 using the keyboard in Spanish (or French,) '.' is correctly converted into ','. So for us: 12,05 is converted afterwards in JS into 12.05 as a number.

This is specially anoying when using an extended keyboard with number pad.

This is not working as of:
"vue": "^3.2.37",
"primevue": "^3.15.0",
 "vite": "^2.9.13",
 "pnpm": "^7.5.0",

Thanks,

Best Regards.

**Comment by tugcekucukoglu** [comment]
Could you send us a codesandbox link so we could replicate it?

**Comment by CeansBzh** [comment]
Hi, this is still an issue with the following :
"vue": "^3.2.41",
"primevue": "^3.29.1",
"vite": "^4.0.0",
"npm": "10.4.0"

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by lobodol** [comment]
Hi, thanks for the update. TBH this issue is so old I forgot it ^^
I'll keep you posted 
Cheers
