### ISSUE TITLE
OrderList: drag and drop

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#1861]
Please add the ability to drag elements on the list with the mouse.

Simply put, add drag and drop support

https://www.primefaces.org/primevue/showcase-v2/#/orderlist

**Comment by matthew-dean** [comment]
Note: please add touchdrag support as well, not just click-drag

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
