### ISSUE TITLE
Feature Request - full function data table with filter box 

### ISSUE THREAD

**Issue by ITKHMER** [primefaces/primevue#1862]
Hi,
I'm requesting for full function data table with filter box below the table header. Please find the sample below:
![demo]
(https://user-images.githubusercontent.com/93175803/144707539-be3bfac9-2dd3-4a39-912b-cb22118f9774.gif)

And please add Show/Hide Column as well.

This advanced data table is needed by many web app developers. 

Thank you!

**Comment by rubjo** [comment]
You should read the documentation before asking for functionality that exists.

https://www.primefaces.org/primevue/showcase/#/datatable/filter
https://www.primefaces.org/primevue/showcase/#/datatable/coltoggle

**Comment by tugcekucukoglu** [comment]
Thanks @rubjo for the links. @ITKHMER could you also check [paginator](https://www.primefaces.org/primevue/showcase/#/paginator)

**Comment by ITKHMER** [comment]
What I mean is to bind all those useful functions together to make one full set of data table (as in sample) in one of the template. Just to make it easier. Thanks anyway!
