### ISSUE TITLE
Hydration Toast

### ISSUE THREAD

**Issue by sun-pandey** [primefaces/primevue#1876]
Toast throws hydration error in nuxt 3. Toast component is "teleported to body" whereas everything is under div#__nuxt so there are two divs under body. Vue doesn't seem to like two divs directly under body.

Generated HTML below: 

```
<body>
      <div class="p-toast p-component p-toast-bottom-center">
           <div></div>
       </div>
      <div id="__nuxt">
           ... application html here
     </div>
</body>
```

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/2602
