### ISSUE TITLE
[Feature-Request] Dialog: closeOnEscape with multiple dialogs

### ISSUE THREAD

**Issue by Enoooch** [primefaces/primevue#1877]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
When I press esc button, it closes all dialogs.

**Expected behavior**
When I press esc button, it closes the top dialog only. (Configurable by adding a new prop)

**What is the motivation / use case for changing the behavior?**
A dialog with large information, and we use the second dialog to display other details, so we don't want to close the main dialog directly.

**Comment by tugcekucukoglu** [comment]
For now Dialog component properly support dynamic dialog but it's o our roadmap. For now closing this issue.
