### ISSUE TITLE
InputNumber not accepting decimal input with mode="decimal" and minFractionDigits="0"

### ISSUE THREAD

**Issue by Gordo5556** [primefaces/primevue#1881]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When entering values into  <InputNumber> with 
mode="decimal" 
:minFractionDigits="0" 
:maxFracionDigits greater than 2

It is not possible to enter enter any decimal values into the InputNumber box. 

**Expected behavior**
After pressing the period button, '.' , I would expect the decimal separator to be added and the next numbers types should then be the decimal numbers. 

**Minimal reproduction of the problem with instructions**
Add a InputNumber box such as:
<InputNumber mode="decimal" :minFractionDigits="0" :maxFracionDigits="2"/>
Then attempt to enter 123.45. The InputNumber box will not allow decimals.

* **Vue version:** 3.X
 "vue": "^3.0.11",

* **PrimeVue version:** 3.4.X
 "primevue": "3.4.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 95.0

**Comment by tugcekucukoglu** [comment]
`<InputNumber mode="decimal" />` just allows integers and to define fractions 'minFractionDigits' property is required. So  `<InputNumber mode="decimal"  :minFractionDigits="0" />` accepts only integer.

**Comment by dashavoo** [comment]
Hi @tugcekucukoglu - your description explains the reason for the issue described, but I think it is still an issue.

There are cases where you do not want to show a decimal place by default, but still allow the user to enter one. I am a little confused because #1136 described the requirement, and a milestone was added, but for InputNumber is still to be integer only and minFractionDigits=0 does not add optional fraction digits.

**Comment by Gordo5556** [comment]
Thank you @dashavoo, that is exactly the problem I am seeing. It seems like this has been mentioned in a couple different places but has not been addressed yet.

**Comment by DaveBruwer** [comment]
I agree with above sentiment. I want to be able to add a decimal, but I don't want to be forced to display ".00" all the time.
I believe the default behaviour should be allowing decimals but not displaying ".00".
