### ISSUE TITLE
Integration with capacitorjs\nativescript (Idea)

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1886]
It would be great if there was an integration with capacitorjs.com (or nativescript.org)
I would like to build a mobile application

By integration, I mean the use of native functions (be able to enable or disable them, and flexibly configure)

For example:
Toast > push-notifications (toast native)
etc

Also good adaptation for mobile UI applications

**Comment by tugcekucukoglu** [comment]
[primevue-quickstart](https://github.com/primefaces/primevue-quickstart) might help.
