### ISSUE TITLE
Scrolltop component has no discernible text

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1889]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/inspiring-stitch-jzg5c

**Current behavior**
The scrolltop component fails accessibility audits, because it renders as a button with no discernible test.
WCAG 4.1.2: https://dequeuniversity.com/rules/axe/3.5/button-name and https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

**Expected behavior**
The button should have (visually hidden) text explaining its behaviour

**Minimal reproduction of the problem with instructions**
Add a scrolltop

**What is the motivation / use case for changing the behavior?**
Improve accessibility

**Please tell us about your environment:**
n/a

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Thanks for the all great PRs. We're working on [accessibility](https://github.com/primefaces/primevue/wiki/Roadmap#accessibility) and it is planned to be completed in Q1 2022. Unfortunately we could only check all of this PR after it's completed.

Thanks for your understanding.

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
