### ISSUE TITLE
Hydration Tooltip

### ISSUE THREAD

**Issue by liemdt1811** [primefaces/primevue#1890]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/eloquent-kapitsa-nk3dp?file=/src/App.vue

**Current behavior**
The tooltip does not neutralize or incorrectly neutralizes user-controllable input
before it is placed in output that is used as a web page that is served to other users

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Please refer to this CodeSandbox 
https://codesandbox.io/s/eloquent-kapitsa-nk3dp?file=/src/App.vue

* **Vue version:** 3.X
* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by Ancient-Dragon** [comment]
I think this has been resolved? I can't replicate using the latest version of primevue

**Comment by tugcekucukoglu** [comment]
Could you please check the latest PrimeVue version?
