### ISSUE TITLE
Datatable - paginator includes input with no labels

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1892]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
This can be observed on https://www.primefaces.org/primevue/showcase/#/datatable/paginator

**Current behavior**
The datatable component fails accessibility audits, because it contains an input with no label

**Expected behavior**
All inputs should have a label

**Minimal reproduction of the problem with instructions**
Create a datatable with paginator, as per https://www.primefaces.org/primevue/showcase/#/datatable/paginator
The markup includes a hidden text input, with no label.
```
<div class="p-dropdown p-component p-inputwrapper p-inputwrapper-filled p-paginator-rpp-options">
  <div class="p-hidden-accessible"><input type="text" readonly="" aria-haspopup="true" aria-expanded="false"></div>
  <!---->
  <span class="p-dropdown-label p-inputtext">50</span>
  <!---->
  <div class="p-dropdown-trigger" role="button" aria-haspopup="listbox" aria-expanded="false">
    <span class="p-dropdown-trigger-icon pi pi-chevron-down"></span>
  </div>
</div>
```

**What is the motivation / use case for changing the behavior?**
Improve accessibility

**Please tell us about your environment:**
n/a

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by malcomio** [comment]
This input is actually part of the `Dropdown` component, and can be seen in the markup on https://www.primefaces.org/primevue/showcase/#/dropdown (as well as https://www.primefaces.org/primevue/showcase/#/paginator)

It isn't clear to me what the purpose of this readonly input is - looking at the code, it seems to receive focus after an option has been selected

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
