### ISSUE TITLE
Datatable - row expansion button has no discernible text

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1893]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
This can be observed at https://www.primefaces.org/primevue/showcase/#/datatable/rowexpand

**Current behavior**
The datatable component fails accessibility audits, because it includes a button without any text.

```
<button class="p-row-toggler p-link" type="button">
  <span class="p-row-toggler-icon pi pi-chevron-right"></span>
  <span class="p-ink" style="height: 28px; width: 28px; top: -0.828125px; left: -3px;"></span>
</button>
```

**Expected behavior**
The button should have (visually hidden) text explaining its behaviour

**Minimal reproduction of the problem with instructions**
Add a datatable with expandable rows, as per https://www.primefaces.org/primevue/showcase/#/datatable/rowexpand

**What is the motivation / use case for changing the behavior?**

**What is the motivation / use case for changing the behavior?**
Improve accessibility

**Please tell us about your environment:**

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
