### ISSUE TITLE
Datatable: scrollable + resizable columns problem with 100% table min-width

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#1896]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/v3-editor-forked-c92jp?file=/src/Table.vue:521-540

**Current behavior**
I need datatable with expand column resize mode. My table has style of min-width 100% (and its necessary in my case). While scrollable option is disabled everything works as expected but when I change its value to true and reduce column size. Table width is getting below 100%.

**Expected behavior**
- min table width of 100%
- columns should fill available space if table width is below 100%
- scrollable set to true
- col resize 
- expand mode 

**Minimal reproduction of the problem with instructions**

Change value of scrollable option and reduce column size using col resize.

* **Vue version:** 3.2.1
* **PrimeVue version:** 3.8.2
* **Browser:** Chrome 96.0.4664.93

**Comment by tugcekucukoglu** [comment]
It's expected behavior. When the scrollable property is set true, DataTable does not change the other columns' width.
The default of scrollable is false and in expand mode like in showcase recalculates the all columns' width.
