### ISSUE TITLE
Correct check MenuItem is disabled

### ISSUE THREAD

**Issue by s0nofthesun** [primefaces/primevue#1899]
If the "disabled" property of MenuItem is defined as a function, then when you try to execute a command by pressing MenuItem, the command is not executed, because **item.disabled** is always true.
Behavior is reproduced: https://codesandbox.io/s/menu-item-disabled-function-579mm

Pull request: https://github.com/primefaces/primevue/pull/1898

Thank you.

**Comment by tugcekucukoglu** [comment]
If the MenuItem is disabled, click event will never been executed

```
itemClick(event) {
            const item = event.item;
            if (item.disabled) {
                return;
            }
            ...
        }
```

**Comment by s0nofthesun** [comment]
Hello, @tugcekucukoglu 
The point is that this piece of code **do not** work if the "disabled" property is defined as a function.

```
itemClick(event) {
            const item = event.item;
            //item.disabled is always true in case it defined as function
            if (item.disabled) {
                return;
            }
            ...
        }
```

for example:
```
data(){
    return {
        menuItems: [
        {
            label: "Test",
            command: () => {
                alert("test");
            },
            disabled: () => {
                //any implementation of function
                return false;
            },
        }]
    }
}
```

in this case expression `item.disabled` returns "`() => { return false; }`", what is actually **true**

**Comment by s0nofthesun** [comment]
> 



> If the MenuItem is disabled, click event will never been executed
> 
> ```
> itemClick(event) {
>             const item = event.item;
>             if (item.disabled) {
>                 return;
>             }
>             ...
>         }
> ```

MenuItem **is enabled**, but when you click on it, command not execute. That is the issue.

**Comment by j-meds** [comment]
> If the MenuItem is disabled, click event will never been executed
> 
> ```
> itemClick(event) {
>             const item = event.item;
>             if (item.disabled) {
>                 return;
>             }
>             ...
>         }
> ```

Reread his issue again. On his example the menuItem is enabled but the click events does not work.. It should work. https://primefaces.org/primevue/showcase/#/menumodel The menuItem is enabled but click event suddenly stopped working. This is an issue with it being a function and menuItem is expecting a boolean.
