### ISSUE TITLE
Datatable - paginator dropdown trigger has no accessible name

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1900]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
This can be observed on https://www.primefaces.org/primevue/showcase/#/datatable/paginator

**Current behavior**
The datatable component fails accessibility audits, because the 
https://dequeuniversity.com/rules/axe/4.3/aria-command-name?application=AxeChrome

**Expected behavior**
All elements with aria roles of link, button or menuitem should have text.

**Minimal reproduction of the problem with instructions**
Create a datatable with paginator, as per https://www.primefaces.org/primevue/showcase/#/datatable/paginator
The markup includes a div with the role of `button`, that contains no discernible text.
```
<div class="p-dropdown-trigger" role="button" aria-haspopup="listbox" aria-expanded="false">
  <span class="p-dropdown-trigger-icon pi pi-chevron-down"></span>
</div>
```

**What is the motivation / use case for changing the behavior?**
Improve accessibility

**Please tell us about your environment:**
n/a

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by malcomio** [comment]
As with #1892, this is actually part of the `Dropdown` component

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
