### ISSUE TITLE
Paginator next/previous/first/last buttons have no discernible text

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1901]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
This can be observed on https://www.primefaces.org/primevue/showcase/#/paginator

**Current behavior**
The paginator component fails accessibility audits, because it contains buttons with no text

**Expected behavior**
All buttons should have discernible text

**Minimal reproduction of the problem with instructions**
Create a paginator, as per https://www.primefaces.org/primevue/showcase/#/paginator

The markup for the previous/next and first/last buttons has no text, e.g.
```
<button class="p-paginator-next p-paginator-element p-link" type="button"> 
 <span class="p-paginator-icon pi pi-angle-right"></span>
</button>
```

**What is the motivation / use case for changing the behavior?**
Improve accessibility

**Please tell us about your environment:**
n/a

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
