### ISSUE TITLE
header option is missing from confirmoption

### ISSUE THREAD

**Issue by NicolasMelin** [primefaces/primevue#1902]
Hello,

I have upgrade my primevue version to 3.10.0 and I have now a typescript error when I build my project :

![Capture](https://user-images.githubusercontent.com/13767020/146532876-bfb7d976-96be-4a44-9127-d3294e15c23e.PNG)

My code :
![Capture2](https://user-images.githubusercontent.com/13767020/146532885-a683550e-5e07-4028-98b7-f86d980130d3.PNG)

In fact, the header attribut is missing from Confirm option.

It's a bug from the new version or I miss something ?

Thakns by advance.

Best regards

**Comment by NicolasMelin** [comment]
Little up please.

**Comment by dacxjo** [comment]
They seem to have messed with all the types in this version, I'm rolling back while they fix it

**Comment by MichaelVonB** [comment]
Whats the current state of this? Just upgraded and realized the bug. 
https://github.com/primefaces/primevue/commit/2064e29a454235390e5e3fa560bb2bfabb8d775f would fix the issue, while the latest commit https://github.com/primefaces/primevue/issues/1852 removed it again
