### ISSUE TITLE
Bootstrap themes put horizontal rule in wrong place in stacked DataTable

### ISSUE THREAD

**Issue by dashavoo** [primefaces/primevue#1903]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Sandbox link below, but also demonstrable on the documentation website (see responsive DataTable examples).

https://codesandbox.io/s/keen-villani-vuwdz

**Current behavior**
Datatable in stacked mode separates at the wrong row. This can be seen on the documentation page itself. As shown in the screenshot, rating (which is the last column) is shown after the horizontal rule. This occurs for the Bootstrap themes only as far as I can tell.
![image](https://user-images.githubusercontent.com/3750013/146556297-8a143034-8e07-40db-b400-0701d8541186.png)

**Expected behavior**
The horizontal rule should come after the final column in the stacked table, not before.

**Minimal reproduction of the problem with instructions**

* **Vue version:** 3.2.23

* **PrimeVue version:** 3.10.0

* **Browser:** Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**Comment by tugcekucukoglu** [comment]
We follow the Bootstrap design but the DataTable component has this issue in stack mode.  We're working on the DataTabel scrolling behaviour and there is no need to use the stack mode for the next version.

Sorry for the delayed answer.
