### ISSUE TITLE
DataTable - Paginator doesn't reset on Lazy sort

### ISSUE THREAD

**Issue by jingglang** [primefaces/primevue#1905]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
The bug exists in this demo page (DataTable - Lazy)
https://www.primefaces.org/primevue/showcase/#/datatable/lazy

**Current behavior**
Paginator is out of sync with DataTable on sort action. DataTable will reset first to 0, but the Paginator doesn't change the page.

**Expected behavior**
On sort action, Paginator should reset to first page just like the DataTable first = 0

**Minimal reproduction of the problem with instructions**
When the paginator is at page 5, then click a column header to sort it, the Paginator still at Page 5 although the DataTable display first page.

* **Vue version:** 3.X

**Comment by morpc-gohio** [comment]
I am experiencing the same thing with sorting, filtering, and resetting the state of the table back to page 1. I've tried using :first="first" (for example), calling setPage directly, basically every hack I could think of, but nothing gets the paginator to react and go back to page 1. I'm on v3.10.

**Comment by web-swpl** [comment]
Updated demo page link: https://www.primefaces.org/primevue-v2/#/datatable/lazy
