### ISSUE TITLE
Primevue Dynamic optionlabel

### ISSUE THREAD

**Issue by qwerty3858** [primefaces/primevue#1906]
I want to add string data to the data in the optionlabel in Primevue dropdown. But I could not add it dynamically.

As an example, my data comes as 0,1,2,3.
I'm on dropdown

First Version
version 1
version 2
Version 3

My code here
```
 <Dropdown v-model="versionInfo" :options="resultVersion" optionValue="Id" optionLabel="VersionNo" placeholder="Önceki Versiyonları İncele"/>
```

**Comment by tugcekucukoglu** [comment]
What is your exact test case? It's hard to demonstrate the issue without codesandbox example.

**Comment by tugcekucukoglu** [comment]
If the issue still persist please provide a codesandbox sample before reopen it.
