### ISSUE TITLE
Accessibility - InputSwitch Invisible to VoiceOver

### ISSUE THREAD

**Issue by evanreichard** [primefaces/primevue#1908]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://primefaces.org/primevue/showcase/#/inputswitch

**Current behavior**
Apple VoiceOver completely skips over the InputSwitch element.

**Expected behavior**
VoiceOver identifies element.

**Minimal reproduction of the problem with instructions**
Enable VoiceOver on either MacOS / iOS and attempt to address the InputSwitch via gestures. VoiceOver does not identify the element and completely skips over it.

**What is the motivation / use case for changing the behavior?**
Those who are blind are unable to use InputSwitch elements. 

**Please tell us about your environment:**
Safari iOS Extension. Reproducible on the aforementioned link above to official documentation.

* **Vue version:** 3.X
3.2.19

* **PrimeVue version:** 3.4.X
3.7.1 -  Appears to still be an issue based on the documentation.

* **Browser:** Safari

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
