### ISSUE TITLE
Icon doc bug

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1916]
https://www.primefaces.org/primevue/showcase/#/icons

![image](https://user-images.githubusercontent.com/16963395/146821695-52a00202-2c4b-4863-9e47-fcc0134701ce.png)

![image](https://user-images.githubusercontent.com/16963395/146821769-2e2d9668-32f0-4428-a517-d9ef9e4f80be.png)

**Comment by tugcekucukoglu** [comment]
Fixed thanks.
