### ISSUE TITLE
Use Tailwind-like CSS framework (WindiCSS)

### ISSUE THREAD

**Issue by xlukasfrana** [primefaces/primevue#1921]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

I know this is a huge change, but I feel like there is a strong tendency to use Tailwind in JS world (or [WindiCSS](https://windicss.org/), because it has more features and is fully Tailwind comaptible). It has HMR, it does not need PurgeCSS and it has a lot of utilities which are not present in PrimeFlex and it provides better DX. When working with PrimeFlex, I found myself partly writing SCSS, partly using PrimeFlex and partly using CSS classes from the PrimeVue itself.

Although, WindiCSS can be easily used along with PrimeVue, but I would still need to purge my CSS and it increases the complexity of development. The idea is to rewrite CSS into Windi plugin for example. That way, only CSS would need to be cared for. It should provide better tooling, developer experience and the fact that many developers are already familiar with Tailwind-like frameworks.

What do you think of that?

> Note about Windi: I prefer it more since they were the first to introduce the JIT engine. Also, there are preparing more and more features in another repo called [UnoCSS](https://github.com/antfu/unocss). I suggest you check [his blog](https://antfu.me/posts/reimagine-atomic-css). Anthony Fu has done some incredible job. I also think it is highly usable with library, because you only need to develop one plugin and PrimeVue would work. The Windi is also 100% compatible with Tailwind and maybe the plugin would work in both frameworks without hassle.

**Comment by JohnCampionJr** [comment]
I know its months later, but this really should be considered; plus it would remove work on your end maintaining prime-flex.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
