### ISSUE TITLE
Use any icons framework

### ISSUE THREAD

**Issue by lukeeno** [primefaces/primevue#1922]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

I shall include PrimeIcons with PrimeVue. But the icon set is somehow limited and there are other far more complete solutions like FontAwesome or Material icons. The problem for me is that I need to use PrimeIcons, because are tightly integrated in the PrimeVue for selects and so on. I can use another icon set alongside, but that way I would combine two different styles.

Do you think it is acceptable to make icons configurable and allow users to use for example aforementioned Font Awesome? Or is there already some way to do this?

**Comment by tugcekucukoglu** [comment]
Please see [this](https://github.com/primefaces/primevue/issues/1627)
