### ISSUE TITLE
TabView Feature Offer

### ISSUE THREAD

**Issue by wayland** [primefaces/primevue#1923]
**I'm submitting a ...**  (check one with "x")
```
[X] feature **OFFER** => I didn't see this on the RoadMap
```

**Expected behavior**

Hi.  I've written some code, and am interested in knowing whether you're interested enough that it's worth cleaning up and submitting a pull request.  

Specifically, what I did is:
* Break TabView into SwitcherView and TabNav
* Made SwitcherView use a template for its navigation, so that I can switch TabNav out for TabMenu or Steps
* Added some (optional) routing and menu stuff; if you add attributes, it will add routing and menus for you
* Made it work with the Composition API
* Made it generate a menu model where useful (eg. you can now defined "panels", and it'll generate a menu that Steps can use to navigate, but it still works with RouterView)

**What is the motivation / use case for changing the behavior?**
I was thinking there should be a StepsView which is like a TabView, but with Steps.  Then I realised that stepping from page to page is also a common feature with Paginator as well, so I pulled the navigation out into a separate component (note: haven't integrated with Paginator, just commenting on the commonality here).  

I should also warn you that I'm not an habitual Javascript programmer, and am fairly new to Vue/PrimeVue, so I'll probably need some suggestions for improvement.  

**Please tell us about your environment:**
Linux (Fedora)

* **Vue version:** 3.X

* **PrimeVue version:** 3.9.1+

* **Browser:** only tested in Firefox

**Comment by tugcekucukoglu** [comment]
It's not on the roadmap.

Thanks,
