### ISSUE TITLE
Table header shake when scrolling

### ISSUE THREAD

**Issue by NickolayBauer** [primefaces/primevue#1925]
Table header skake when scrolling

You can see this in your documentation
https://www.primefaces.org/primevue/showcase/#/datatable/flexscroll

** Current behavior **
The header of the table skake when scrolling, it is more noticeable when zooming in, it is rather due to the "sticky" css property

** Expected behavior **
I would like nothing to shake when scrolling, I think this can be achieved using an absolute position

** Minimal reproduction of the problem with instructions **
1) Open the documentation of the DataTable component
For instance:
https://www.primefaces.org/primevue/showcase/#/datatable/virtualscroll
or
https://www.primefaces.org/primevue/showcase/#/datatable/flexscroll

2) Enlarge image
3) Make a scroll
4) Look at the gif
![GIF 24 12 2021 15-25-48](https://user-images.githubusercontent.com/35115545/147364360-d8f6489f-c1ab-4f8f-aede-a311cc57f95f.gif)

** What is the motivation / use case for changing the behavior? **
I want the component to work correctly.

** Please tell us about your environment: **
WIN10,
VUE3

* ** Browser: **
The problem only persists on CHROME
On FireFox and Edge ok

**Comment by tugcekucukoglu** [comment]
Could please try again after clear the cache?

**Comment by NickolayBauer** [comment]
@tugcekucukoglu, 
clearing the cache doesn't help - this is the first thing I tried.

use an ecanny magnifier to see the shake
