### ISSUE TITLE
Cannot find an app bar in the documentation.

### ISSUE THREAD

**Issue by builder555** [primefaces/primevue#1926]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

_I know it says to post the support request in the forum, but after trying various ways for about 15 minutes and constantly getting error 500 I gave up!_

I cannot find any documentation regarding the app bar (or the top toolbar for the entire app). When I use the Toolbar component it gets rounded corners and margins around the top, plus it doesn't stay at the top. If I use the Sidebar with position="top" it covers the page content. Maybe I'm missing something obvious, but I'd really appreciate a nudge in the right direction.

**Comment by tugcekucukoglu** [comment]
Please use the forum or discord channel for questions and help requests.

**Comment by builder555** [comment]
> Please use the forum or discord channel for questions and help requests.

I would, but the forum didn't work - that's why i said in the very first sentence that I was getting error 500
