### ISSUE TITLE
Add p-invalid support to InputGroup

### ISSUE THREAD

**Issue by Ariki** [primefaces/primevue#1929]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

`InputGroup` lets us create custom components by combining existing PrimeVue inputs. Often it is desirable to handle invalid state in such a component by changing border color of the group if `p-invalid` class is present. While it is possible to add custom style to a component or use custom theme, I'd be great to add `p-invalid` support to `InputGroup` in standard themes to make `p-invalid` border color dependent on theme. Or, even better, introduce a special CSS class (something like `p-invalidable-border`) for being able to add `p-invalid` support to any custom component.

* **PrimeVue version:** 3.10.0

**Comment by tugcekucukoglu** [comment]
Thanks for the report. Form components have invalid state and also adding invalid state in InputGroup means lots of code repeating. So we want to keep it simple and light-weight but we would suggest this usage

```
<div class="p-inputgroup">
    <span class="p-inputgroup-addon" style="border-color:.....">
        <i class="pi pi-user"></i>
    </span>
    <InputText placeholder="Username" class="p-invalid" />
</div>
```
