### ISSUE TITLE
Sidebar not closing when you click outside while :modal="false"

### ISSUE THREAD

**Issue by 2x-Hra** [primefaces/primevue#1931]
```
<template>
  <prime-sidebar :dismissable="true" :modal="false" class="p-sidebar-md w-max">
  </prime-sidebar>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Sidebar from 'primevue/sidebar'
export default defineComponent({
  name: 'Sidebar',
  components: {
    PrimeSidebar: Sidebar,
  },
  }
})
</script>

```
When `:modal` is true ,it's possible to close the sidebar by clicking outside of the `sidebar` but when you do it the layer that modal caused it , is still there and it makes you kind a stuck , so I turned the `:modal` to false and after that the layer gone but you can't close the `sidebar` with clicking outside the `sidebar`, and I tried using `dismissable` property but not working .

**Comment by tugcekucukoglu** [comment]
I think you mean 'dismissableMask' property. 'dismissableMask' specifies modal background will hide or not  when 'modal' is true. So it's expeccted behavior.
