### ISSUE TITLE
DataTable: sticky column header doesn't stay fixed 

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#1938]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/restless-waterfall-dmvip?file=/src/DataTableScrollDemo.vue
**Current behavior**

Sticky column header doesn't work with `resizableColumns` and `frozen`

**Expected behavior**

Column headers with `frozen` attribute should stay fixed instead of moving.

**Minimal reproduction of the problem with instructions**

Scroll the page horizontally to view the problem.

**Comment by beocaca** [comment]
`::v-deep(.p-datatable-scrollable .p-frozen-column) {
  font-weight: bold;
  position: sticky;
}`

**Comment by beocaca** [comment]
```
::v-deep(.p-datatable-scrollable .p-frozen-column) {
  font-weight: bold;
  position: sticky;
}
```
