### ISSUE TITLE
DataTable: td width doesn't match its th width

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#1940]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/jolly-wave-zz3x0?file=/src/DataTableFlexScrollDemo.vue

**Comment by tugcekucukoglu** [comment]
In vertical scrolling, we recommend to use 'flex' style for columns. Please check 'Column Widths of a Scrollable Table' section at [doc](https://primefaces.org/primevue/showcase/#/datatable/)

**Comment by nndnha** [comment]
@tugcekucukoglu  Can you please fork this to show me how to do that? https://codesandbox.io/s/youthful-allen-2lh3q?file=/src/DataTableScrollDemo.vue
