### ISSUE TITLE
How to call Tooltip it by API?

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#1941]
I want that when a component is loaded, a tooltip is immediately displayed on one element (not by mouse hover event, but immediately by default). Or how bind to a property in "data".

How to call (open) it by API?

Vue version: 3.2.26
PrimeVue version: 3.10
Browser: all

**Comment by tugcekucukoglu** [comment]
Tooltip waits focus/hover events to bind itself. So input focus could be added but tooltip still waits mouseenter event. For now there is no api usage.
