### ISSUE TITLE
Red Color Palette

### ISSUE THREAD

**Issue by julienripet** [primefaces/primevue#1944]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

Could you please add actual reds to the basic Color Palette ?  
I realise Pink is already in there, but it doesn't really cover all needs. 

Here is what I added to my custom theme to have access to red css-variables, it might not be perfect, be it was good enough for my uses :

  --red-50: #ffcdd2;
  --red-100: #ef9a9a;
  --red-200: #e57373;
  --red-300: #ef5350;
  --red-400: #f44336;
  --red-500: #e53935;
  --red-600: #d32f2f;
  --red-700: #d50000;
  --red-800: #c62828;
  --red-900: #b71c1c;

I would've made a pull request directly to add them, but I'm unsure where it is handled

**Comment by FlipWarthog** [comment]
The color values themselves are set per theme.css and the specific set of options spans all 4 Prime libraries + PrimeFlex: https://www.primefaces.org/primeflex/theming

So I think having your own custom values to get you by is the best option.
