### ISSUE TITLE
:first parameter not having any affect on Pagination Control in DataTable with :lazy="true"

### ISSUE THREAD

**Issue by adamshafer** [primefaces/primevue#1946]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Create a lazy loaded data table similar to https://www.primefaces.org/primevue/showcase/#/datatable/paginator. Add the :first parameter to the DataTable and set to various integers. You'll see that any value you set there has no affect on the pagination control.

**Current behavior**
In PrimeVue 3.8.2 and below, providing a :first parameter in a DataTable with :lazy="true" would keep the pagination component in sync with the table. In versions later than PrimeVue 3.8.2, this is no longer working. :first has no effect, and in loading the page (I'm using ?page=X in my querystring to keep this value) I am seeing page X of data, but the pagination control is still on Page 1. Additionally, if I am on page 3 of data, and sort by any column, the data shows me page 1, but the paginator is stuck on page 3 highlighted.

If I remove :first="X" from my DataTable using anything later than PrimeVue 3.8.2, nothing changes. It seems that something was broken in the release of 3.9.0 in regards to paging and :lazy="true" in DataTables.

**Expected behavior**
The paginator component attached to the DataTable should always highlight the proper page if given a value for :totalRecords, :rows, and :first, as it used to in version 3.8.2 and below.

**Minimal reproduction of the problem with instructions**
Create a lazy loaded data table similar to https://www.primefaces.org/primevue/showcase/#/datatable/paginator. Add the :first parameter to the DataTable and set to various integers. You'll see that any value you set there has no affect on the pagination control.

**What is the motivation / use case for changing the behavior?**
This is a bug... just needs fixed.

**Please tell us about your environment:**
Windows, VSCode, NPM, node.

* **Vue version:**
3.2.26, composition API using <script setup>

* **PrimeVue version:**
3.9.0 and later. The issue does not exist in 3.8.2 and previous 3.x versions.

* **Browser:**
Chrome (latest), Safari (latest)

**Comment by tugcekucukoglu** [comment]
It's a regression and fixed for the next version. [https://github.com/primefaces/primevue/issues/1905](https://github.com/primefaces/primevue/issues/1905)

**Comment by eliasbermudez** [comment]
@tugcekucukoglu When will the next version be released with the issue fixed?
