### ISSUE TITLE
Alignment issue with multiple frozen columns on TreeTable

### ISSUE THREAD

**Issue by Soph0208** [primefaces/primevue#1947]
The table has problems when using frozen in more than two columns (and can only be used in the first columns). 

From the third column in the second line, the data is displayed above the frozen column.

There are a lot of visual bugs with columns when creating tables.

Another problem is used to resize with frozen and scroll. The resize rows in the header are in the front of the frozen columns.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

* **PrimeVue version:** 3.9.1

**Comment by tugcekucukoglu** [comment]
Could you provide a simple codesandbox sample? could not replicate it with [this example](https://codesandbox.io/s/lhtoe)

**Comment by Soph0208** [comment]
https://codesandbox.io/s/strange-dew-g6nqk?from-embed=&file=/src/TreeTableScrollDemo.vue

The columns `Name`, `Key` and `Size` are frozen.  

![grafik](https://user-images.githubusercontent.com/97178234/148370283-5201557f-1210-484f-b19e-f0595a477aa5.png)

**Comment by tugcekucukoglu** [comment]
Using 'alignFrozen' would solve this demo problem.

**Comment by Soph0208** [comment]
`alignFrozen` doesn't fix the bug.
