### ISSUE TITLE
Calendar - Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by GuillermoFarias** [primefaces/primevue#1948]
In the first time the error is locatd when jest run unit testing

after updating package.json the component does not compile

dependabot alert deprecated dependencies

> TypeError
Cannot read properties of undefined (reading 'config')

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/epic-wing-e9ddr?file=/src/components/HelloWorld.vue

**Current behavior**
error on component rendering and run jest unit test

**Expected behavior**
build, rendering and run test successfully

* **Vue version:** 3.2.26
* **PrimeVue version:** 3.10.0
* **CoreJS:** 3.20.6
* **Browser:** [all]

**Comment by tugcekucukoglu** [comment]
Please follow setup constructions and add main.js

```
import PrimeVue from "primevue/config";
const app = createApp(App);
app.use(PrimeVue);
app.mount("#app");
```

**Comment by valh1996** [comment]
@tugcekucukoglu thank you, but how to make it works with `createSSRApp` knowing that we never call `.mount('#app')` ?

If I do this I get an error that says `window is undefined` which is normal in SSR mode.
