### ISSUE TITLE
Datatable with selection mode - table header has no text

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1951]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
This can be observed at https://www.primefaces.org/primevue/showcase/#/datatable

**Current behavior**
The datatable component fails accessibility audits, because it includes columns without any text - see https://dequeuniversity.com/rules/axe/4.3/empty-table-header

```
<th class="" role="cell" style="width: 3em;"><!---->
  <div class="p-column-header-content"><!----><!----><!----><!---->
    <div class="p-checkbox p-component">
      <div class="p-checkbox-box p-component" role="checkbox" tabindex="0">
        <span class="p-checkbox-icon"></span>
      </div>
    </div><!---->
  </div>
</th>
```

**Expected behavior**
The table header should include appropriate visually hidden text

**Minimal reproduction of the problem with instructions**
Add a datatable with a selection column, as per the `Radio Button` and `Checkbox` examples on https://www.primefaces.org/primevue/showcase/#/datatable/selection

**What is the motivation / use case for changing the behavior?**
Improve accessibility

**Please tell us about your environment:**

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
