### ISSUE TITLE
[feature] input:  autocomplete

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1956]
Add the ability to manage autocomplete for fields (For password (https://www.primefaces.org/primevue/showcase/#/password), and all other Input)

I want to disable some of the autocomplete fields from the browser (when the browser offers saved passwords and save the password)

**Comment by kinshukshah** [comment]
Hey @tugcekucukoglu, It's amazing to see such a wonderful thing you are building and myself experiencing primevue on day to day basis in my organization. 

I would love to contribute to this project can I take this issue ?

**Comment by abakucz** [comment]
+1 for this feature.

This is nowadays important especially for Password.

**Comment by tugcekucukoglu** [comment]
For now, would not prefer to add this functionality. Please check this information https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

Still if there is more demand, we'll definitely reconsider. Thank you for your feedback.
