### ISSUE TITLE
New Dialog v2 containerStyle prop and modal leave defect

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#1957]
For Primevue 2.7, if a modal and fixed-width Dialog contains Textarea, it appears from left to center with a shadow when it is opened.

Please refer to the following link,
https://codesandbox.io/s/stupefied-lichterman-ihupt

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox sample. This issue fixed for the next version.

**Comment by wanglin86769** [comment]
@tugcekucukoglu Hello, I upgraded PrimeVue and found the problem still exists in 2.9.0, please refer to the following link:
https://codesandbox.io/s/modest-rhodes-lkxqz

**Comment by tugcekucukoglu** [comment]
Please check [this commit](https://github.com/primefaces/primevue/commit/6db8ab9c540213804239160acc2320114c06593f) and new 'containerStyle' prop in the [documentation](https://www.primefaces.org/primevue/showcase-v2/#/dialog)
