### ISSUE TITLE
v2 DataTable Dynamic Row defect

### ISSUE THREAD

**Issue by Quentin-L21** [primefaces/primevue#1958]
Hello everyone,

**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I recently updated PrimeVue version from 2.3.0 to 2.8.0 and I discovered a bug regarding the filter functionnality on the ColumnGroup of a Datatable.

This is the current behavior : 
![image](https://user-images.githubusercontent.com/69462335/149287687-362c68ff-87b7-4ddd-9ea1-d1c6477be61e.png)

I've a filter on LY BUD and AI FCST columns. If I uncheck one of the filter, it filters the columns on the rows under but not on the row with the columns LY/BUD/...
![image](https://user-images.githubusercontent.com/69462335/149287857-8a667b34-ae2a-4945-b1ec-863e4300d27d.png)

I'm using the following hierarchy for my datatable :

```
<Datatable>
 <template #header>
        <div>
          <MultiSelect
            v-model="selectedOnlyEditable"
            :options="onlyEditable"
            optionLabel="header"
            @input="onToggle"
            placeholder="Select Columns"
            style="width: 20rem"
            class="f-12"
          />
        </div>
 </template>
 <ColumnGroup type="header">
     <Row>
         <Column /> --> JAN 2021 Column
         <Column /> --> FEB 2021 Column 
         ...
     </Row>
     <Row>
          <Column
            v-for="(col, index) of selectedSubColumns"
            :field="col.field"
            :header="col.header"
            :key="col.field + '_' + index"
            :headerClass="
              (col.header == firstColumnLabel ? 'w-125' : 'w-50') +
              ' f-095 align-right ' +
              columnBodyClass(col)
            "
            :bodyClass="col.bodyClass"
            :frozen="col.isFrozen"
            :sortable="col.header != firstColumnLabel"
          >
          </Column> --> Those are the columns that are not updating in the datatable on filter
        </Row>
 </ColumnGroup>
  <Column
        v-for="(col, index) of selectedSubColumns"
        :field="col.field"
        :header="col.header"
        :key="col.field + '_' + index"
        :bodyClass="columnBodyClass(col)"
        :frozen="col.header == firstColumnLabel"
      >
        <template #body="slotProps">
          {{ getFixedValue(slotProps.data[slotProps.column.field]) }}
        </template>
  </Column> --> Those are the columns updating in the datatable on filter 
</Datatable>
```

The **onToggle** function in the multiSelect is updating the selectedSubColumns array.

**Expected behavior**
The dynamic columns in a ColumnGroup should be updated after a filter is applied on them.

I saw a similar issue (https://github.com/primefaces/primevue/issues/1630) but it seems like you resolved it in this commit (https://github.com/primefaces/primevue/commit/a51f26ce40ae4dc6df35a457f13a2d400604410a). 

Is it possible for you to resolve it in version 2.8.0 (I can't update in Vue version 3.0) or do you have any workaround for me ? 

**My environment:**

* **Vue version:** 2.6.10

* **PrimeVue version:** 2.8.0

* **Browser:** all

Thanks a lot !

Kind regards,
Quentin

**Comment by tugcekucukoglu** [comment]
This [codesandbox](https://codesandbox.io/s/vigilant-leakey-7c4x8?file=/src/App.vue) works. What am I missing?

**Comment by tugcekucukoglu** [comment]
Any update?

**Comment by Quentin-L21** [comment]
Hi @tugcekucukoglu , I'll have a look into it this week-end or monday ! I'll let you know and I'll update the sandbox to reproduce the problem I'm facing. Thank you !

**Comment by Quentin-L21** [comment]
Hi @tugcekucukoglu , I tried to reproduce the problem in the following sandbox : https://codesandbox.io/s/frosty-goldstine-57x5er?file=/src/App.vue 

The problem is that when I remove one column everything is not aligned anymore : 
![image](https://user-images.githubusercontent.com/69462335/157626340-3487aabc-bf1a-4722-a389-e97aa68a85aa.png)

Thank you !
Quentin

**Comment by tugcekucukoglu** [comment]
Could you test with latest PrimeVue 2 version? With 2.8.0 we reimplemented PrimeVue 3 DataTable for PrimeVue 2.

If problem is still persist please reopen this issue.

Thanks,
