### ISSUE TITLE
Autocomplete: multiple selection 

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#1961]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Autocomplete with multiple selection set to true. Its not possible to select multiple values at once. The panel closing each time when selecting a value.

**Expected behavior**
It would be nice to be able to select multiple values at once. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
The goal of selecting multiple values at once is a simplified handlig. If there are e.g. 100 suggestions  and you want to select suggestion 95,96,97,  you need to scroll three times to get suggestion 95,96,97. It would be nice to be able to select all three at once, so you have to scroll just one time.

**Please tell us about your environment:**

* **Vue version:** 3.2.11

* **PrimeVue version:** 3.7.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tugcekucukoglu** [comment]
When a suggestion is selected, the query clears itself and also the panel will be closed. This is expected behavior for AutoComplete.
