### ISSUE TITLE
cannot run build-lib on windows

### ISSUE THREAD

**Issue by malcomio** [primefaces/primevue#1962]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
On a Windows machine, run the following commands in the repo directory:

1. npm install
2. npm run build-lib

An error message appears:
```
'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.
```

**Expected behavior**
The build should complete

**What is the motivation / use case for changing the behavior?**
Support users on Windows

**Please tell us about your environment:**
Windows 10 Pro, Node v14.15.1

* **PrimeVue version:** 3.4.X

**Comment by tugcekucukoglu** [comment]
This PR breaks the build on OS. We would be grateful if you create a PR with the general solution. For now, closing.

**Comment by malcomio** [comment]
when you say "OS", which OS do you mean? it worked for me on Mac 10.15.7, node v14.15.1
