### ISSUE TITLE
Editor tooltips

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#197]
What is about tooltips support for editor buttons? As i know, quill supports tooltip showing.

**Comment by fairking** [comment]
What do you mean? Which tooltips and where do you want to show?

**Comment by Sellec** [comment]
I mean this example.
https://quilljs.com/playground/#snow-toolbar-tooltips
You may simplify this way from adding additional options for <editor> tag

**Comment by cagataycivici** [comment]
The demo you have mentioned uses jQuery, we have our own native vue Tooltip directive for this;

```xml
<Editor v-model="value2" editorStyle="height: 320px">
                <template slot="toolbar">
                    <span class="ql-formats">
                        <button class="ql-bold"></button>
                        <button class="ql-italic"></button>
                        <button class="ql-underline" v-tooltip.bottom="'Underline'"></button>
                    </span>
                </template>
            </Editor>
```

![Screen Shot 2020-02-27 at 10 57 38](https://user-images.githubusercontent.com/686247/75423595-16067880-5950-11ea-8a80-2bc317e42a4d.png)

**Comment by Sellec** [comment]
> The demo you have mentioned uses jQuery, we have our own native vue Tooltip directive for this;
> 
> ```
> <Editor v-model="value2" editorStyle="height: 320px">
>                 <template slot="toolbar">
>                     <span class="ql-formats">
>                         <button class="ql-bold"></button>
>                         <button class="ql-italic"></button>
>                         <button class="ql-underline" v-tooltip.bottom="'Underline'"></button>
>                     </span>
>                 </template>
>             </Editor>
> ```
> 
> ![Screen Shot 2020-02-27 at 10 57 38](https://user-images.githubusercontent.com/686247/75423595-16067880-5950-11ea-8a80-2bc317e42a4d.png)

It is not a useful example, becouse in this we need to manually describe all toolbar content. But if i do not want to describe all toolbar, i need only to set tooltip for one button and all buttons need to stay here to without any tooltips?
