### ISSUE TITLE
[Feature request] Loading feedback

### ISSUE THREAD

**Issue by timyourivh** [primefaces/primevue#1972]
#### I'm submitting a...
```
[ ] bug report
[x] feature request
[ ] support request
```

### What is the motivation / use case for changing the behavior?
Currently you only have one option to give feedback to show the user a component is doing something: disable it.
To show it is loading you would have to change the icon dynamically which could result in this:
```html
<Button label="Save" :icon="'pi ' + (loading ? 'pi-spin pi-spinner': 'pi-check')" :disabled="loading" @click="submit" />
```
Now imagine having multiple components on in you component that have a loading state. It would get very messy. 

### Proposal
What I'm proposing is a prop that you could toggle so only a singe prop is required to toggle a loading state:
```html
<!-- Examples -->
<Button label="Save" icon="pi pi-check" :loading="loading" @click="submit" />
<InputSwitch v-model="checked" :loading="loading" />
<InputText type="text" v-model="username" :loading="loading" />
<Card :loading="loading">...</Card>
```
It could make use of the [progress spinner](https://www.primefaces.org/primevue/showcase-v2/#/progressspinner) instead of an rotating icon because it looks nicer. (Or the [indeterminate progessbar](https://www.primefaces.org/primevue/showcase-v2/#/progressbar) in the `<Card>` case)

**Comment by timyourivh** [comment]
For the people interested here's a Vue 3 component example for a submit button as alternative:

<details>
  <summary>Click to show</summary>

```vue
<script setup>
import Button from 'primevue/button'

defineProps({
  label: {
    type: String,
    default: 'Submit'
  },
  loading: {
    type: Boolean,
    default: false
  },
  icon: {
    type: String,
    default: 'pi pi-check'
  },
  loadingIcon: {
    type: String,
    default: 'pi pi-spin pi-spinner'
  },
  class: {
    type: String,
    default: ''
  },
  iconPos: {
    type: String,
    default: 'left'
  }
})
</script>

<template>
  <Button
    type="submit"
    :label="label"
    :icon="[loading ? loadingIcon : icon]"
    :icon-pos="iconPos"
    :class="{ 'opacity-25': loading }"
    :disabled="loading"
  />
</template>
```
</details>

Allows you to use it like this:

```vue
<form @submit.prevent="form.post('...')">
  <!-- ... -->
  <SubmitButton label="Safe" icon="pi pi-save" :loading="form.progress" />
</form>
```

**Comment by timyourivh** [comment]
I took a look at the button component code and apparently loading state is already implemented but not documented yet:
https://github.com/primefaces/primevue/blob/master/src/components/button/Button.vue#L39-L46
Great! That's the most important one.

__I don't know for how long this was available since it wasn't in the documentation so I assumed it didn't exist.__

I will leave this issue open for debate about the `<InputSwitch>`, `<InputText>`, `<Card>` and maybe other components that could need a loading state.
Another reason to keep it open is the docs not being updated/published yet.

**Comment by tugcekucukoglu** [comment]
Button component has a loading state but adding loading state to InputSwitch, InputText, and Card is not on the roadmap. 

Still if there is more demand, we'll definitely reconsider. Thank you for your feedback.
