### ISSUE TITLE
Bug: Tooltip shown at wrong place

### ISSUE THREAD

**Issue by oldbig** [primefaces/primevue#1976]
https://github.com/primefaces/primevue/blob/f6fbaeb6f38b54cd12280dec9f75e278dd2f31ee/src/components/tooltip/Tooltip.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L133
 
https://github.com/primefaces/primevue/blob/f6fbaeb6f38b54cd12280dec9f75e278dd2f31ee/src/components/tooltip/Tooltip.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L153

When moving to the opposite place, if still is out of bounds, it is just displayed at the wrong place.  The fixed code should be as follows:
Line 133
```
        if (modifiers.top) {
        alignTop(el);
        if (isOutOfBounds(el)) {
            alignBottom(el);
             if (isOutOfBounds(el)) {
                    alignTop(el);
             }
        }
    }
```

Line 153 
```
    else if (modifiers.bottom) {
        alignBottom(el);
        if (isOutOfBounds(el)) {
            alignTop(el);
            if (isOutOfBounds(el)) {
                alignBottom(el);
            }
        }
    }
```

**Comment by tugcekucukoglu** [comment]
Issue is not clear. Do you have a codesandbox or a repo?

**Comment by oldbig** [comment]
Hi @tugcekucukoglu 
I have no codesandbox, it just happens in a internal project, I create the following diagram to describe the scenario:
![image](https://user-images.githubusercontent.com/2577334/149642826-1140bf98-ebd3-4da1-978a-55976b48e682.png)

The reason: when the bottom has not enough space to put the tooltip message, it will be adjusted to the opposite position, but when the opposite position also has not enough space, the tooltip should put it at original place.
And all the following have the same problem:

- v-tooltip.right
- v-tooltip.top
- v-tooltip.bottom
- v-tooltip.left

**Comment by oldbig** [comment]
@tugcekucukoglu , this is corresponding [Pull Request](https://github.com/primefaces/primevue/pull/1997)

**Comment by tugcekucukoglu** [comment]
@oldbig Without seeing the problem, we couldn't accept the PR. The issue might be related to your project. How can I replicate this issue?

**Comment by oldbig** [comment]
@tugcekucukoglu I agree with you, I will prepare a demo of codesandbox.

**Comment by oldbig** [comment]
Hi @tugcekucukoglu 
Please check this [demo codesandbox](https://codesandbox.io/s/hopeful-star-pf8qc?file=/src/App.vue)

**Comment by oldbig** [comment]
Hi @tugcekucukoglu 
Is this demo ok?

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox example. PR is merged.
