### ISSUE TITLE
Expanded dropdown inside the modal window

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#198]
I got a small issue guys. Having dropdowns inside the scrolled modal window makes dropdowns akward to work with. Disabling `overflow-y: auto;` against `.p-dialog-content` make the situation better but in the same time we loose the modal window scrool which might be usefull in other situations.

I don't know what might be a solution for that, but I just want you to show if there any better way to have all things workable together. Maybe we can apply some extra css to the dropdown?

Please let me know if you have any ideas guys.

![Screenshot_25](https://user-images.githubusercontent.com/13495631/74611579-089df280-50f5-11ea-8803-ba5001b525db.png)

![Screenshot_26](https://user-images.githubusercontent.com/13495631/74611581-0c317980-50f5-11ea-9990-a7b8533252ac.png)

**Comment by fairking** [comment]
I guess I can just make the modal window bigger but wondering if there is some more universal solution. Same might happen with `Calendar` too.

**Comment by fairking** [comment]
I have found a solution somewhere on the git. Somebody says the following style would do the trick:
```
.ui-select-choices {
        position: fixed;
        top: auto;
        left: auto;
        width: inherit;
      }
```
where `.ui-select-choices` is actually ours `.p-multiselect-panel`, `.p-dropdown-panel`, `.p-datepicker`, `.p-autocomplete-panel` and so on. Not sure if it needs to be applied only to modals `.p-dialog .p-multiselect-panel` or it could be everywhere.

Let me know guys what do you think. 

I am applying temporary solution to my css until it is fixed.

**Comment by fairking** [comment]
Bellow is my temporary solution until it fixed. Just in case if everyone else is looking for this:
```
.p-dialog .p-dialog-content {
	overflow-y: visible !important;
}
.p-dialog-mask {
	position: absolute;
	pointer-events: auto;
}
```
And all Dialogs must have `:modal="false"`.

**Comment by mertsincan** [comment]
Could you please try appendTo="body" property for this issue?

**Comment by cagataycivici** [comment]
In addition to appendTo body.

```xml
<p:dialog :contentStyle="{'overflow': 'auto'}"
```

Should resolve it as well. I'm not sure about removing default overflow, it makes dialogs with long contents overflow like;

https://www.primefaces.org/primevue/#/dialog

**Comment by fairking** [comment]
> Could you please try appendTo="body" property on Dropdown for this issue?

In my situation it is `MultiSelect` but in other situations it could be `Calendar`, 'Autocomplete', 'ColorPicker'.

> In addition to appendTo body. `<p:dialog :contentStyle="{'overflow': 'visible'}"`.

It removes the scroll, I have a dialog with long content and the Multiselect at the bottom of the content.

**Comment by fairking** [comment]
@cagataycivici I think the issue needs to be reopened.
