### ISSUE TITLE
Is it possible to Primevue with already existing tailwind config file in a Nuxt app ?

### ISSUE THREAD

**Issue by damisparks** [primefaces/primevue#1982]
Hi there, 

is it possible to Primevue with the already existing tailwind config file in a Nuxt app?
I have a nuxt app with tailwind using my configured theme file. 
I want to add Primevue to my project, is it possible to tell Primevue to use the tailwind config file I have already?

**Comment by tugcekucukoglu** [comment]
Hi,

PrimeVue has own themes include Tailwind for its components. If you don't import a theme, you need to customized every style for yourself. There is no way import tailwind from nuxt config file. We recommend to use PrimeVue Tailwind theme at least to use the all PrimeVue components without customized their styles one by one.

Regards,

**Comment by damisparks** [comment]
@tugcekucukoglu thank you. I will follow your recommendation.
