### ISSUE TITLE
bugfix panelMenuSub isActive bug in 2.8.0

### ISSUE THREAD

**Issue by randybrutal** [primefaces/primevue#1986]
fix panelMenuSub isActive bug in 2.8.0
[pull request](https://github.com/primefaces/primevue/pull/1983)

![截圖 2022-01-14 下午4 03 51](https://user-images.githubusercontent.com/31371940/149472686-99498ee5-4004-4170-a7da-32345875f4b8.jpg)

**Comment by tugcekucukoglu** [comment]
Fixed [#1983 ](https://github.com/primefaces/primevue/pull/1983)
