### ISSUE TITLE
'header' does not exist in type 'ConfirmationOptions'

### ISSUE THREAD

**Issue by Mirko92** [primefaces/primevue#1988]
**I'm submitting a ...** 
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

This error is about Typescritp, and this "CodeSandbox" isn't ready. 

**Current behavior**
See the title.

**Expected behavior**
Header field should be in "ConfirmationOptions" type. 

**Minimal reproduction of the problem with instructions**
Try something like this: 
```js
deleteUser() {
    this.$confirm.require({
      message: `TODO: message ?`,
      header: 'TODO: header',
      accept: () => {
         console.log("accepted")
      },
      reject: () => {
         console.log("rejected");
      }
    });
  }
```
* **Vue version:** 3.2.11

* **PrimeVue version:** 3.10.0

**Comment by tugcekucukoglu** [comment]
Duplicate [#1852 ](https://github.com/primefaces/primevue/issues/1852)
