### ISSUE TITLE
Inline-block elements with no text renders different than with text

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#199]
[Related to this](https://stackoverflow.com/questions/4053575/inline-block-element-with-no-text-renders-differently). 
As you use lots of "display: inline-block;" for components, what about adding default "vertical-align:bottom/middle" into components css styles?
Its a normal situation for jquery/font-swesome styles and lots of other components, they are fixes ponential div render deviations with this hack.

**Comment by cagataycivici** [comment]
Can you give us a concrete example?

**Comment by Sellec** [comment]
https://unpkg.com/browse/jquery-ui-css@1.11.5/jquery-ui.css
Just search by `inline-block` and you will see `vertical-align` in 90% of this classes.
https://unpkg.com/browse/vuetify@2.2.15/dist/vuetify.css
If you will see base component classes, you will see `vertical-align` in most of them. So all classes applied to elements with base classes would have `vertical-align + inline-block` in summary style.

**Comment by cagataycivici** [comment]
Please try with 2.0.0-rc.2 which has a rewritten css. We mostly use flex now btw instead of inline-block.
