### ISSUE TITLE
Dropdown doesn't display empty string

### ISSUE THREAD

**Issue by sid-6581** [primefaces/primevue#1995]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When a dropdown list contains a string that is empty or all whitespace, two things happen:

1. The dropdown list entry will be collapsed, and not the correct height.
2. If a placeholder is provided, it will be displayed instead of the empty value.

**Expected behavior**
A blank value should be displayed instead of the placeholder, and the dropdown list should display the blank entry at the correct height.

* **Vue version:** 3.2.26

* **PrimeVue version:** 3.10

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Could you please add a codesandbox sample?

**Comment by sid-6581** [comment]
> Could you please add a codesandbox sample?

Here you go. This has two strings that causes problems. One is an empty string, one contains just whitespace. Both are not displayed with the correct height in the dropdown list, and both do not replace the placeholder.

[![Edit blazing-wildflower-ikc10](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blazing-wildflower-ikc10?fontsize=14&hidenavigation=1&theme=dark)
