### ISSUE TITLE
@cell-edit-cancel fired to remove focus but next cell InputText is not working

### ISSUE THREAD

**Issue by ashumsd7** [primefaces/primevue#1998]
I have one text field and two buttons check icon button and close icon button for cancelling cell edit.   
Normally we lose focus when we press Esc to cancel cell edit and Enter to lose focus on cell and save cell data.
I tried to fire   @cell-edit-cancel="onCellEditCancel"    specific 'onCellEditCancel' on a button click when is just after cell, text-field  + check button and close button. 
![image](https://user-images.githubusercontent.com/40313523/149722478-52884c03-dc46-4cbb-8b33-75d39d6e7bc3.png)

Code is : in DataTable
` @cell-edit-complete="onCellEditComplete"
      @cell-edit-cancel="onCellEditCancel"`

Code inside column (editor slot)
![image](https://user-images.githubusercontent.com/40313523/149722750-d43e5377-d682-482d-9e3a-8a5c7449d2f8.png)

`onCellEditCancel(event) {

    /// what to do here to lose focus from cell 
  

    
    },`

I want the same behaviour when we click Esc/Enter after editing or focusing on the cell.

I have also tried to mimic Esc and Enter key on the click of the cross [x] button. but not working.  Please suggest to me how to lose focus in a cell on the button click. 

I am using Prime Vue 2

**Comment by tugcekucukoglu** [comment]
The aim is here to separate cell editing and row editing. Cell editing cancelation is possible with the keyboard event. In this example the click event cannot lose the focus in the cell.
