### ISSUE TITLE
Dependency was not found

### ISSUE THREAD

**Issue by alirizaadiyahsi** [primefaces/primevue#2]
> This dependency was not found:

> * -!../../../node_modules/@vue/cli-service/node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!../../components/listbox/Listbox.css in ./node_modules/@vue/cli-service/node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./src/assets/styles/primevue.css
> 
> To install it, you can run: npm install --save -!../../../node_modules/@vue/cli-service/node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!../../components/listbox/Listbox.css
> 
> 
> These relative modules were not found:
> 
> * ./components/listbox/Listbox in ./src/main.js
> * ./views/listbox/ListboxDemo.vue in ./src/router.js
> 

![image](https://user-images.githubusercontent.com/4375000/50003089-76abce80-ffb3-11e8-9002-408af343d995.png)

**Comment by cagataycivici** [comment]
Should be fixed now.
