### ISSUE TITLE
TreeTable | relative positional components are not Compatible with Table Scroll and Frozen

### ISSUE THREAD

**Issue by Soph0208** [primefaces/primevue#2000]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/empty-sunset-2ck93?file=/src/TreeTableScrollDemo.vue

![grafik](https://user-images.githubusercontent.com/97178234/149772482-4c435062-b061-4201-8f07-95dda4d3f562.png)

**Current behavior**
If the user scrolls to the bottom of the table, the 'Edit Item' button is displayed above the Frozen columns and not in the background of the `Name` column. There is a problem with the position of the Button object. This also applies to other objects such as checkboxes, dropdowns, etc.

**Expected behavior**
If the user scrolls to the bottom of the table, the button must be below the `Name` column.

* **PrimeVue version:** 3.9.1

**Comment by tugcekucukoglu** [comment]
Behind the scenes PrimeVue calculates/keeps the z-index. For example default values are;

```
app.use(PrimeVue, {
    zIndex: {
        modal: 1100,        //dialog, sidebar
        overlay: 1000,      //dropdown, overlaypanel
        menu: 1000,         //overlay menus
        tooltip: 1100       //tooltip
    }
});
```

When we set any default z-index, it could break for example sidebar. So this z-index dependence of the project itself. In this case [this example](https://codesandbox.io/s/inspiring-mopsa-ho1yf?file=/src/TreeTableScrollDemo.vue:321-364) solve the problem.

Thanks,
