### ISSUE TITLE
SpeedDial requires tooltip and it's not listed in the docs. 

### ISSUE THREAD

**Issue by j-meds** [primefaces/primevue#2004]
https://codesandbox.io/s/agitated-shape-rcw2d?file=/src/App.vue

**Current behavior**
![image](https://user-images.githubusercontent.com/12689117/149794175-eed653d2-6e70-4b22-99ef-51ce64cf2a38.png)

**Expected behavior**
SpeedDial should work as it says in the docs, you need tooltip directive as it exists inside the SpeedDial source code. The change could be an update to the doc or include tooltip in SpeedDial.

**Comment by tugcekucukoglu** [comment]
Track this issue [#2013](https://github.com/primefaces/primevue/issues/2013)

check 'Properties' section in [docs](https://primefaces.org/primevue/showcase/#/speeddial)

**Comment by j-meds** [comment]
> Track this issue [#2013](https://github.com/primefaces/primevue/issues/2013)
> 
> check 'Properties' section in [docs](https://primefaces.org/primevue/showcase/#/speeddial)

For someone jumping into PrimeVue seeing a "tooltipOptions" property doesn't seem like a clear indicator I need to make tooltip a directive and call it "tooltip". Using SpeedDial you cannot change tooltip to a different name like "PrimeTooltip" because it's embedded in SpeedDial it should be more clearer.

**Comment by j-meds** [comment]
@tugcekucukoglu  I see you have place the directive in SpeedDial Thanks!
