### ISSUE TITLE
Drag and drop support for Tree

### ISSUE THREAD

**Issue by tgbarker** [primefaces/primevue#2006]
[Feature Request]
Provide drag and drop support on the Tree component similar to vue-jstree

**Comment by Noobiest9** [comment]
Would love this in PrimeVue too.  Prime NG and React already support drag and drop.  Thanks for this great library!!

**Comment by mkalinski93** [comment]
me too

**Comment by Alihd1** [comment]
We need this 🙏

**Comment by cyhnkckali** [comment]
Bu konuda bir gelişme mevcut mu!

**Comment by cybeq** [comment]
![image](https://github.com/primefaces/primevue/assets/99597892/71f57669-aea8-4449-9d4d-5ba6c4281ce8)
![image](https://github.com/primefaces/primevue/assets/99597892/2655f6f5-4b96-432b-995c-f7c6d6095e40)
![image](https://github.com/primefaces/primevue/assets/99597892/ae55711b-6eb9-4d3c-8564-badf5a1b80de)
just add to the library few lines and events. you can just assume selected item is a dragged one, so you can call select before that and you dont have to even manipulate an object

**Comment by cybeq** [comment]
![image](https://github.com/primefaces/primevue/assets/99597892/73d750c1-4c49-4fdd-b559-581028bd9590)
that is all you need

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by 1Map** [comment]
@vuelcomponents Can you please share a full example how you handled this?
