### ISSUE TITLE
Datatable - Footer column

### ISSUE THREAD

**Issue by jeremielodi** [primefaces/primevue#2020]
The current version of Datatable does not support footer options like **count**  or  **sum** .
The datable with thoses option will look like bellow :

![footer2](https://user-images.githubusercontent.com/25838121/149975066-7c021b72-6e0d-4e5f-ba7a-f0408faa99f6.PNG)

![footers](https://user-images.githubusercontent.com/25838121/149959728-0a030677-4c2f-4ace-86b7-19eb38788b7c.PNG)

**Comment by tugcekucukoglu** [comment]
Please check [https://primefaces.org/primevue/showcase/#/datatable/colgroup](https://primefaces.org/primevue/showcase/#/datatable/colgroup)

**Comment by Aspyryan** [comment]
@tugcekucukoglu This no longer exists? How would we do this in Primevue 4.x?
