### ISSUE TITLE
Dropdown list entries not correct height for empty or whitespace strings

### ISSUE THREAD

**Issue by sid-6581** [primefaces/primevue#2021]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

[![Edit competent-mendeleev-tmpz7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-mendeleev-tmpz7?fontsize=14&hidenavigation=1&theme=dark)

**Current behavior**
When a dropdown list contains a string that is empty or all whitespace, the dropdown list entry will be collapsed, and not the correct height.

Reported in #1995, and a fix for the placeholder problem mentioned in this issue was fixed in #2016. My PR #1996 contained fixes for both issues, but #2016 did not fix the dropdown list entry height problem.

![image](https://user-images.githubusercontent.com/28602336/149973083-e2fefc0a-cfb9-44c5-98f6-3c1e6dfa81d1.png)

**Expected behavior**
The dropdown list should display the blank entry at the correct height.

* **Vue version:** 3.2.26

* **PrimeVue version:** 3.11

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Please use templating for height. It's not the core issue.
