### ISSUE TITLE
Panel Menu does not highlight menu item when the deep link is used in browser

### ISSUE THREAD

**Issue by Bhagrot** [primefaces/primevue#2022]
Hello, 
I am using panel menu for my Menu items and when I click on the menu item it highlights the menu item but when I hit a deep link URL in browser, I am able to expand that menu items section but it does not highlight particular requested menu item. is there any way to highlight it?

**Comment by tugcekucukoglu** [comment]
I'm afraid I'm not understand the problem clearly. [https://codesandbox.io/s/panelmenu-nnoc7](https://codesandbox.io/s/panelmenu-nnoc7) this example is working for me.

**Comment by Bhagrot** [comment]
I bounded each menu item with router link using "to" attribute and when I hit the particular router link in browser we should highlight corresponding menu item , looks like the component does not have that feature.

I have fixed this issue, I  injected custom class on menu item to indicate active router link.
