### ISSUE TITLE
Dynamic rows don't work as expected.

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2029]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/dynamic-rows-fgypj

**Current behavior**
Using v-for with Row leaves footer blank.

**Expected behavior**
Displaying rows dynamically.

**Minimal reproduction of the problem with instructions**
I want to dynamically render footer column group by defining rows in array, so I could easily display them using v-for loop on row component. At this moment v-for loop doesn't seem to work correctly with Row. It doesnt even show footer block.

**What is the motivation / use case for changing the behavior?**
I've found that for this moment there are only 2 ways to display footer rows dynamically. First is by using dynamic rows, which is not working. Second is by using column group footer slot, which does not exist. 
So at this point there is no way to display dynamic footer.

**Please tell us about your environment:**

* **Vue version:** 3.2.26

* **PrimeVue version:** 3.10

* **Browser:** Chrome

**Comment by tugcekucukoglu** [comment]
Duplicate [#1932 ](https://github.com/primefaces/primevue/issues/1932)
