### ISSUE TITLE
Resize Support for ColGroups

### ISSUE THREAD

**Issue by mauritsderoover** [primefaces/primevue#2030]
**I'm submitting a ...** 
```
[ ] bug report
[X ] feature request 
[ ] support request 
```
Hi!

We have seen that when we activate ColGroups in a DataTable (PRIME VUE), It's not possible to perform column resize

A similar feature request has already been made in 2020 #484 

It seems however that it hasn't come on the roadmap since and we were wondering if primevue was planning to support this functionality? 

We are hopefull since RowGroup support for ColResize has been added in the near past!

Best Regards,

Maurits De Roover

**Comment by tugcekucukoglu** [comment]
Please follow [#484 ](https://github.com/primefaces/primevue/issues/484). These are same issues.

Best Regards,
