### ISSUE TITLE
DROPDOWN BUG ON ANDROID

### ISSUE THREAD

**Issue by Simons99** [primefaces/primevue#2033]
We of Octavian-lab have notice a bug on dropdown. If i use the advanced dropdown with the filter property on, with android if i search something on the input, it doesn't work properly: the dropdown doesn't react to the keyEnter and doesn't search anything; then if i click outside the dropdown and return on the dropdown the search is done

**Comment by tugcekucukoglu** [comment]
Duplicate [#1389 ](https://github.com/primefaces/primevue/issues/1389)
