### ISSUE TITLE
Progress circle

### ISSUE THREAD

**Issue by zhaojh329** [primefaces/primevue#2035]
The progress circle is usefull.

![image](https://user-images.githubusercontent.com/28673295/150377566-edfa93ba-4c0d-411f-8b19-afbae3033879.png)
![image](https://user-images.githubusercontent.com/28673295/150377618-2fb4a19f-23e9-42e1-94e7-a2ba25c65cab.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
