### ISSUE TITLE
[Feature request] Support for icons in AutoComplete component

### ISSUE THREAD

**Issue by kylevdr** [primefaces/primevue#2036]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**What is the motivation / use case for changing the behavior?**

Currently there does not appear to be a way to add a left or right icon to the input field in the AutoComplete component. It looks like this could be achieved by adding the p-input-icon-left or p-input-icon-right classes to the component itself and making the icon a child of the component, but the AutoComplete component does not accept children. Please support icons by allowing the AutoComplete component to accept children, or adding a prop or a slot for iconLeft and iconRight.

**Comment by robotpsychology** [comment]
I've also run into this issue. Anyone looking for alternatives can either add a placeholder to the Autcomplete with emojis as 'icons' or use [this method](https://stackoverflow.com/questions/48819704/add-an-image-to-a-placeholder-input-type) where you add icons as a background image and indent the text away from it. You can remove the focus from the example if you want to keep the icon. Not ideal, but a workaround for now.

**Comment by tugcekucukoglu** [comment]
Could you please check the latest PrimeVue version? `dropdownIcon`, `removeTokenIcon` and `loadingIcon` properties are available.

**Comment by aDogCalledSpot** [comment]
I would like to revisit this since the answer above doesn't meet my requirements. I would like to have a simple "Search" icon on the left that is always displayed. There should be a template for customizing the main input so anything can be added before or after.

**Comment by james-astra** [comment]
Is this possible out of the box yet?

**Comment by bblok11** [comment]
> I would like to revisit this since the answer above doesn't meet my requirements. I would like to have a simple "Search" icon on the left that is always displayed. There should be a template for customizing the main input so anything can be added before or after.

I strongly agree, we struggle to use PrimeVue in production because of the lack of these consistencies & features
