### ISSUE TITLE
Sidebar: ripple appears in the wrong place

### ISSUE THREAD

**Issue by brainstream** [primefaces/primevue#2039]
**I'm submitting a ...** 

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

The issue can be reproduced on your documentation website

**Current behavior**

Ripple appears in the wrong place  

![vlcsnap-2022-01-23-13h26m13s349](https://user-images.githubusercontent.com/678778/150674512-66a21108-95dd-4a1b-b7b4-e9fbff7a767c.png)

**Expected behavior**

Ripple appears upon a close button.

**Minimal reproduction of the problem with instructions**

Go to your documentation https://www.primefaces.org/primevue/showcase/#/sidebar and click a close button on any sidebar.

**Please tell us about your environment:**

I use VSCode on Kubuntu with NPM but the issue is reproducible on your website.

* **Vue version:** 3.2.19

* **PrimeVue version:** 3.11.0

* **Browser:** Firefox 96.0

**Comment by cagataycivici** [comment]
Resolved, thank you.
