### ISSUE TITLE
Editor infinite loop with some specific values

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#204]
Maybe this is not a bug...im not good in vue. 
In some specific scenario i got an infinite loop where vue's "data" field value changed by editor from 1st variant of content to 2nd and then to 1st and then to 2nd...
I create an example in jsfiddle - https://jsfiddle.net/Sellec/26fjhyqn/19/
You need to open this and run. All works fine. Then you need to open browser's developer console, and press example's button "Start hell spam in browser console". There is the method "startHell" which sets bugged value into property. And after that you will see lots of console output (from method "getId"). If you will see into this output, you will see that editor changes span.style="background-color color" to span.style="color background-color" and vise-versa.
An image example is here - https://c2n.me/4667NTV
I dont know if it is a quill's bug or primevue's editor wrapper bug.

**Comment by Sellec** [comment]
This can be temporarly fixed by using "text-changed" event and "value" property for initial value binding.

**Comment by fairking** [comment]
I have the same issue, moreover Quill inserts empry paragrafs everytime it loads text. So saving data it adds new empty paragraphs every time. I can see Quill is a bit dead now. I am switching to [tiptap-vuetify](https://www.npmjs.com/package/tiptap-vuetify).

**Comment by fairking** [comment]
Added the same issue to the quill repo https://github.com/quilljs/quill/issues/2948

**Comment by cagataycivici** [comment]
I've applied the Editor code from the PrimeNG codebase which is much older and known to work with no issues for years.
