### ISSUE TITLE
[Feature] Calendar numberOfMonths upgrade the active month should be in the middle

### ISSUE THREAD

**Issue by arnyee** [primefaces/primevue#2042]
[ ? ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ? ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110

Hi I really love your project, and I hope you can help me. I don't find any solution yet but it is possible that this is already available.

So the problem is if I set the numberOfMonths value to greater than 2 (usually 3), it would be nice if the month of the chosen month or the chosen date were the middle month. Is it any way to do this now? Or it needs a future development?

I hope you can answer me as soon as possible!

**Comment by tugcekucukoglu** [comment]
It could caused a performance issue that check all the dates and sort them every calendar input update. If there is more demand, we'll definitely reconsider it. For now closing.

Thanks,
