### ISSUE TITLE
InputNumber allowEmpty doesn't work while using CTRL+X

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2047]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/input-number-u6hby?file=/src/App.vue

**Current behavior**
Removing value with backspace sets value to min. Using ctrl+x changes value to null.

**Expected behavior**
While using allowEmpty flag input value should equal min.

vue - 3.0.11, primevue 3.8

**Comment by tugcekucukoglu** [comment]
It doesn't set the value to min when pressing command/ctrl+X, it sets value as null. To see just remove min prop in your example.

**Comment by mitow7821** [comment]
@tugcekucukoglu why are you closing still existing problem. 
Try to change the min value and then remove input value using backspace. 
Value changes to provided min (or 0 by default) becasue of allowEmpty option set to false. 
The problem is with ctrl+x when it sets value to null where it should be 0.
