### ISSUE TITLE
REOPENING THIS  - YOU CANT FILTER ON STRING DATES WITH FILTER DATE OPTIONS (DATE_IS, DATE_AFTER, ETC)

### ISSUE THREAD

**Issue by devilwacause** [primefaces/primevue#2052]
Primevue 2.8.0
Vue 2.6.14

YOU CANNOT FILTER ON A DATE IN A DATATABLE IF SAID DATE IS A STRING - I REPEAT YOU CANNOT FILTER ON A STRING WITH ANY OF THE DATE FILTERS.  IT REQUIRES A JAVASCRIPT DATE OBJECT.  MEANING DATA PULLED FROM A DATABASE (WHICH WOULD BE A STRING) CANNOT BE FILTERED AGAINST.  MY SECOND COMMIT FIXES THIS ERROR - BUT I BET YOU DIDNT EVEN LOOK AT IT NOW DID YOU? @tugcekucukoglu 

#2043 #2044 

sandbox
https://codesandbox.io/s/pensive-dawn-euplx?file=/src/App.vue

**Comment by tugcekucukoglu** [comment]
Just ask a codesandbox and reopen the old issue not create a new one. We are considering all PR.
