### ISSUE TITLE
PrimeVue 2.8 DataTable bug in column width with scrollable parameter enabled

### ISSUE THREAD

**Issue by timurash** [primefaces/primevue#2055]
[x] bug report 

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/primevue-2-8-datatable-column-width-bug-with-scroll-enabled-ipowu?file=/src/App.vue

**Current behavior**
When setting width of column with headerStyle option in DataTable component, width is not really applying, when scrollable parameter is set to "true". WIdth of columns remain default

**Expected behavior**
Width of columns is applying by headerStyle option even with scrollable parameter enabled

* **Vue version:** 2.6.14

* **PrimeVue version:** 2.8

**Comment by tugcekucukoglu** [comment]
Please use flex to disable grow and shrink while defining an initial width in vertical scrolling.

**Comment by timurash** [comment]
@tugcekucukoglu can you show some example for your problem solution proposal?

**Comment by htxryan** [comment]
What was the solution to this?

**Comment by lircos** [comment]
<Column field="vin" header="Vin" style="flex: 0 0 4rem"></Column>

(See documantation: [Column Widths of a Scrollable Table
](https://www.primefaces.org/primevue/datatable#:~:text=Column%20Widths%20of%20a%20Scrollable%20Table))

**Comment by pedrociarlini** [comment]
> style="flex: 0 0 4rem"

This solution doesn't work for me. No effect at all.
