### ISSUE TITLE
Dropdown displays the value 0 as "empty"

### ISSUE THREAD

**Issue by sid-6581** [primefaces/primevue#2060]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**

[![Edit loving-cache-kh1t8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-cache-kh1t8?fontsize=14&hidenavigation=1&theme=dark)

**Current behavior**

When binding a dropdown to an array of numbers, the number `0` is displayed as `empty` instead of `0`.

**Expected behavior**

Values should be displayed properly.

**What is the motivation / use case for changing the behavior?**

`0` is an acceptable value to have in a list of numbers, and it should be displayed appropriately.

* **Vue version:** 3.2.29

* **PrimeVue version:** 3.11

* **Browser:** all

**Comment by wkrick** [comment]
I didn't see this bug before submitting my bug which covers the same issue for Dropdown and a similar issue with MultiSelect...

https://github.com/primefaces/primevue/issues/2222

**Comment by tugcekucukoglu** [comment]
Docs says `Dropdown requires a value to bind and a collection of arbitrary objects along with the optionLabel property to specify the label property of the option.`

Please look at [this example](https://codesandbox.io/s/objective-spence-2st1yf?file=/src/MultiSelectDemo.vue)
