### ISSUE TITLE
Documentation does not match type definition for Tree key

### ISSUE THREAD

**Issue by dashavoo** [primefaces/primevue#2063]
The documentation for the Tree api states that the `key` field for TreeNodes is mandatory, of any type.
![image](https://user-images.githubusercontent.com/3750013/151813605-9d340eab-11ec-4233-828c-189544135d54.png)

The [interface](https://github.com/primefaces/primevue/blob/e4789c9a73af469d72401aca8ff0158bee934a0e/src/components/tree/Tree.d.ts#L8) states that the key is optional, but if present requires that it be a string.

The documentation and the definition should match, one way or the other.

**Comment by tugcekucukoglu** [comment]
[#L48](https://github.com/primefaces/primevue/blob/e4789c9a73af469d72401aca8ff0158bee934a0e/src/components/tree/Tree.d.ts#L48)
