### ISSUE TITLE
Range slider get stuck when both handle on max value

### ISSUE THREAD

**Issue by emaulandi** [primefaces/primevue#2074]
**Bug report**

Similar issue on primeng that don't seem to be resolved : https://github.com/primefaces/primeng/issues/1285

**CodeSandbox Case (Bug Reports)**
We can see this behavior on the component page : https://primefaces.org/primevue/showcase/#/slider
![image](https://user-images.githubusercontent.com/16479203/151952702-acfe312e-3485-4a4b-a9f1-fa41d10bcf6c.png)

**Current behavior**
When having both handle on the maximum value, the slider get stuck [max, max]. It is not possible to drag a handle to a lower value.

**Expected behavior**
When having both handle on the maximum value, it is possible to change the range to [x, max]

* **Vue version:** 3

* **PrimeVue version:** 3.11.1

* **Browser:** all

**Comment by agrawalrohant** [comment]
What version of Prime NG this fix is available ?
