### ISSUE TITLE
Invalid filter results when using Column #body slot.

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2075]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/v3-editor-forked-c92jp?file=/src/Table.vue

**Current behavior**
While using #body slot filter doesn't work as expected. If you search for "someValue" in my sanbox example table is blank. 
It looks only at data provided in value option.

**Expected behavior**
When #body is used filter should check its content. Instead of filtering array from which column was created.

**Minimal reproduction of the problem with instructions**
- Search "someValue" (should show rows but does not)
- Search "Volkswagen" (is showing rows that doesn't contant that value because of slot usage)

* **Vue version:** 3.2.29
* **PrimeVue version:** 3.11.1
* **Browser:** all

**Comment by tugcekucukoglu** [comment]
DataTable filters only predefined values. body templating just pass a template (see Vue slot content). So it's an expected behavior.
