### ISSUE TITLE
complete bundle as separate primevuelibrary - is it normal?

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#209]
Do you have any objections about separate library named [primevuelibrary](https://www.npmjs.com/package/primevuelibrary)?
I create it as a compiled bundle with all primevue components to use in asp.net development, becouse we dont have separate frontend projects and all frontend is present like html+js code in Asp.net razor views.
And we plan to create separate nuget package to use is with dataannotation attribute schema in C# view models.

**Comment by cagataycivici** [comment]
I don't see why not, it is always welcome to have the community building extensions.
