### ISSUE TITLE
DataTable 2.8.0 cannot use multiple selection with lazy mode

### ISSUE THREAD

**Issue by timurash** [primefaces/primevue#2103]
[x] bug report

This is reopen of this issue: https://github.com/primefaces/primevue/issues/2051

https://codesandbox.io/s/primevue-2-datatable-checkbox-selection-in-lazy-mode-ts5dc?file=/src/App.vue

Current behavior
When using lazy option with multiple selection, top checkbox of multiple selection is not getting selected when all rows is selected, When hitting top checkbox, all rows gets selected, but the checkbox itself doesn't get selected

Expected behavior
Top checkbox gets selected when all fields is selected

In other issue @tugcekucukoglu showed example of using this feature on PrimeVue 3: https://github.com/primefaces/primevue/issues/2051#issuecomment-1022989053

But DataTable component in PrimeVue 2.8.0 doesn't have selectAll prop and not emitting select-all-change event like DataTable component in PrimeVue 3

How can i achieve the behaviour i need in PrimeVue 2?

Can you provide some example on PrimeVue 2?

Vue version: 2.6.14
PrimeVue version: 2.8.0

**Comment by tugcekucukoglu** [comment]
Fixed for next version [#2109 ](https://github.com/primefaces/primevue/issues/2109)
