### ISSUE TITLE
[Solution?] Combine Dropdown functionalities: Lazy Loaded and Filtering

### ISSUE THREAD

**Issue by henckellSop** [primefaces/primevue#2107]
**Suggestion**
At the moment, the Dropdown component cannot lazy load items when also being force filtered (filter="true"). This possibly could be quickly fixed by _introducing another prop variable_, that skips the Filter service and directly shows the lazy loaded (and thus also filtered) elements:

**SOLUTION: In Dropdown.vue (line 314 ff.)**

```
computed: {
          visibleOptions() {
            console.log("inside visible options");
            if (this.filterValue && !this.filterLazy) {   <------ insert new Prop var:  filterLazy 
              if (this.optionGroupLabel) {
                const filteredGroups = [];
                for (const optgroup of this.options) {
                  [...]
                return filteredGroups;
              } else {
               [...]
                );
              }
            } else {
              return this.options;
            }
          },
```

* **Vue version:** 3.X

Tested for: 
* **PrimeVue version:** 3.11.1

**Comment by mauritsderoover** [comment]
Is there an update on this? @tugcekucukoglu

**Comment by tugcekucukoglu** [comment]
Could please try to use the latest PrimeVue version? If the problem still persists, please reopen this same issue.

**Comment by Anubarak** [comment]
@tugcekucukoglu I don't see any way to achieve this currently - how can you stop filtering while `:filter="true"`
