### ISSUE TITLE
Dropdown not showing items in list with VirtualScroller

### ISSUE THREAD

**Issue by gangsterschwein** [primefaces/primevue#2121]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Working in primevue@3.9.1:
https://codesandbox.io/s/pv3-dropdown-vs-391-ztem5
Broken in primevue@3.11.1:
https://codesandbox.io/s/pv3-dropdown-vs-3111-3ob10

**Current behavior**
In versions older than 3.9.1, Dropdown does not display list items when reopened after item selection > #14

**Expected behavior**
Dropdown should display the list of items and scroll to selected item than reopening after selecting an item.

**Minimal reproduction of the problem with instructions**
Open Dropdown and select item > #14. Reopen Dropdown. Dropdown will show an empty list and the scroll bar stays in the top position.
Open Dropdown and select item #14. Reopen Dropdown. Dropdown wil scroll to item #14 but will not show items > #14.
The same error is seen in lazy and not lazy cases.
Also this error is reproduced on https://primefaces.org/primevue/showcase/#/dropdown

**What is the motivation / use case for changing the behavior?**
Fixing broken software

**Please tell us about your environment:**
Windows, Linux

* **Vue version:**
3.2.29

* **PrimeVue version:**
3.11.1

* **Browser:**
Chrome 98

**Comment by henckellSop** [comment]
also see #2114

**Comment by tugcekucukoglu** [comment]
Duplicate [#2114](https://github.com/primefaces/primevue/issues/2114)
