### ISSUE TITLE
Autocomplete needs requery function

### ISSUE THREAD

**Issue by johnwc** [primefaces/primevue#2123]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**What is the motivation / use case for changing the behavior?**
We need a way to have the dropdown stay open and refresh the autocomplete list. A good scenario is when someone uses it for address auto complete. When they type a address that is a apartment building, the auto complete api returns a single address item with a flag set stating that the item has x amount of sub-addresses. When a user selects one of those, we have to re-query the api with the address to get the list of sub-addresses, Apt 101, Apt 102 or Suite 203, Suite 204, etc...

**Please tell us about your environment:**

* **Vue version:** 3.2.21

* **PrimeVue version:** 3.8.2

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
For now, we could suggest using filtering mode. 

Still, if there is more demand, we'll definitely reconsider.

**Comment by johnwc** [comment]
How would filtering mode work with the given scenario?
