### ISSUE TITLE
Impossibility to override the style of a local component

### ISSUE THREAD

**Issue by titou10titou10** [primefaces/primevue#2127]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```
**CodeSandbox Case (Bug Reports)**

Documentation [about theming](https://primefaces.org/primevue/showcase/#/theming) says that _"in case you required to change the style of a certain component for a specific use case use the class property and override the defaults"_

I have not been able to customize any style with the method described in the doc. I have the same behavior with all the components I  tried to scustomise (Menu, Panels...etc)
As an example, I want to remove the 1.5rem padding around an [OverlayPanel](https://primefaces.org/primevue/showcase/#/overlaypanel) . The component defines`"p-overlaypanel"`and`"poverlaypanel-content"` classes Those classes are indeed used when displayed (from the Firefox developper tools) :
    
    .p-overlaypanel .p-overlaypanel-content {
      padding: 1.5rem;
    }

I want to set the padding to "0". Fragment of the non-working view with all the styling tentaves:

    <style lang="scss" scoped>
    .p-overlaypanel {
      padding: 0 !important;
    }
    :deep(.p-overlaypanel) {
      padding: 0 !important;
    }
    .p-overlaypanel-content {
       padding: 0 !important;
    }
    :deep(.p-overlaypanel-content) {
      padding: 0 !important;
    }
    .p-overlaypanel :deep(.p-overlaypanel-content) {
      padding: 0 !important;
    }
    :deep(.p-overlaypanel .p-overlaypanel-content) {
      padding: 0 !important;
    }
    :deep(.p-overlaypanel) .p-overlaypanel-content {
      padding: 0 !important;
    }
    :deep(.p-overlaypanel) {
      .p-overlaypanel-content {
        padding: 0 !important;
      }
    }
    .p-overlaypanel .p-overlaypanel-content {
      padding: 0 !important;
    }
    </style>
    <template>
        <OverlayPanel ref="cm">
          <template v-for="ap in xxxxx" :key="ap">
            <Button :label="ap" />
          </template>
        </OverlayPanel>
    </template>

(Iwill try to get a sandbox later)

**Current behavior**
Not able to locally override the style of a local component

**Expected behavior**
Be able to locally override the style of a local component as described in the documentation

**Please tell us about your environment:**

* **Vue version:** v3.2.30
* **PrimeVue version:** v3.11.1
* **Vite** v2.7.13
* **typescript** v4.5.5
* **Microsoft Visual Studio Code** v1.64.0 + **volar** v0.31.1
* **Browesers** all

**[UPDATED 2022-02-09]**
It works if the `"<style>"`stanza is not `scoped`!
IMHO it is wrong. From the [vue 3/deep selector](https://v3.vuejs.org/api/sfc-style.html#deep-selectors) documention page, it should be the opposite
I'm not sure if it is a **Primevue** or **vite** or **vue** bug...

    <style lang="scss">
     /* works */
     .p-overlaypanel {
       padding: 0 !important;
     }
    </style>

    <style lang="scss" scoped>
     /* other local scoped styles */
    </style>

Also with vue 3,`"::v-deep()"`is deprecated and replaced by`":deep()"`, this should be reflected in the documentation

**Comment by tugcekucukoglu** [comment]
OverlayPanel uses Teleport component of the Vue itself. By default it binds itself to body, so you need to add the styles without using scoped.

**Comment by titou10titou10** [comment]
OK.Thx.
IMHO this should be stated in the documentation that for this category of components (Overlay, Menu..), overriding the style is handled the way you describe it. Maybe in the "Theming/Guide" section?
