### ISSUE TITLE
ScrollPanel Bars visible with Browser Zoom

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2137]
**I'm submitting a ...** 
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Scrollpanel causes white borders if you have Browser Zoom at 80% or smaller.
The original scrollbars are visible. It is particularly annoying in a Darktheme.
![image](https://user-images.githubusercontent.com/8471027/153401389-9749d9db-56d8-4ede-ab73-e0970e3f7e8c.png)

**Suggested fix**
Hide the default scrollbars from the scrollpanel component via css.
// Chrome 
.p-scrollpanel-content::-webkit-scrollbar {
  display: none;
}
.p-scrollpanel-content{
  -ms-overflow-style: none;  // IE and Edge 
  scrollbar-width: none;  // Firefox 
}

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

* **Browser:** Chrome XX

**Comment by tugcekucukoglu** [comment]
Unfortunately, I cannot replicate the issue. [For example this codesandbox](https://codesandbox.io/s/lr3k1y?file=/src/ScrollPanelDemo.vue) in the first example scrollbars cannot seems but the second and the last example scrollbar are visible because of the this line [https://codesandbox.io/s/lr3k1y?file=/src/ScrollPanelDemo.vue:4879-4938](https://codesandbox.io/s/lr3k1y?file=/src/ScrollPanelDemo.vue:4879-4938)

Do you have a codesandbox link for us to replicate?

**Comment by Rakasch** [comment]
I have those border in your codesandbox, too:

Browser Zoom 90% (Chrome)
![image](https://user-images.githubusercontent.com/8471027/159326276-85c93c3a-862a-4f4e-8af2-d69fb5eedef7.png)

Bowser Zoom 50% (Chrome)
![image](https://user-images.githubusercontent.com/8471027/159326722-a24da78f-0ac5-4c2a-8dfb-4ddf6a3e313c.png)

Bowser Zoom 50% (Firefox)
![image](https://user-images.githubusercontent.com/8471027/159327496-59e6246d-e00f-4a52-b00d-0fbce9846dc2.png)

**Comment by tugcekucukoglu** [comment]
Still can not replicate the issue. If problem still persists, please send us a codesandbox link or a repo, so we can replicate this issue.

**Comment by Rakasch** [comment]
Did you change the Browser Zoom of your browser as stated?

1. go to https://www.primefaces.org/primevue/scrollpanel
2. set the Browser ZOOM to some small value
![image](https://user-images.githubusercontent.com/8471027/197226953-c200cc15-8e11-44f2-b63f-e2a8d8a0be21.png)
you can usually do this ctrl + mousewheel
3. Result is this
![image](https://user-images.githubusercontent.com/8471027/197227151-9420a546-dc14-4cb3-97c3-57d13a3f29b6.png)

**Comment by tugcekucukoglu** [comment]
Thanks for the explanation. Reconsider it again.
