### ISSUE TITLE
DataTable Column Group Sort Bug

### ISSUE THREAD

**Issue by mr83-uw** [primefaces/primevue#214]
I don't see anyway to sort using the Column Group feature.

**Comment by cagataycivici** [comment]
Can you give us an example, e.g.

https://www.primefaces.org/primevue/#/datatable/colgroup

Which parts do you need to be sortable?

**Comment by cagataycivici** [comment]
Fixed for 1.0.6

**Comment by strateego** [comment]
Thanks
