### ISSUE TITLE
Can't use right mouse click for copy text on DataTable content

### ISSUE THREAD

**Issue by timurash** [primefaces/primevue#2171]
I'm submitting a bug report 

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/primevue-2-datatable-cant-copy-selected-text-g2q6g?file=/src/App.vue

**Current behavior**
My clients wanted to copy text from rows of DataTable, but when they select some text and then click on rihht mouse button, selected text is getting deselected and i can't copy text with this method. Only hotkey Ctrl+C can help my users to copy text, but this is not obvious

**Expected behavior**
When clicking on right mouse button, selected text is not getting deselected

**Minimal reproduction of the problem with instructions**
![123](https://user-images.githubusercontent.com/63206211/154062179-b3ff136b-6173-4429-b95e-bab9b74940cd.gif)

* **Vue version:** 2.6.14

* **PrimeVue version:** 2.9.0

**Comment by Wouter-J** [comment]
I've also run into this issue, has there been any update / workaround for this?

**Comment by dimon4ezzz** [comment]
I have the same problem on PrimeVue 3.18.

On firefox you can hold Shift and do right-click.

**Comment by colinstevens06** [comment]
Our team just encountered this issue, too - we're looking into not using DataTable because of this, so would be awesome to get this fixed if possible!

**Comment by dimon4ezzz** [comment]
I have found a culprit! [src/components/datatable/DataTable.vue#L971](https://github.com/primefaces/primevue/blob/master/src/components/datatable/DataTable.vue#L971)

**Comment by Magiczne** [comment]
This was probably fixed with https://github.com/primefaces/primevue/pull/3925 and 3.29.1

**Comment by tugcekucukoglu** [comment]
Could you check the latest version? If the problem still persists, please let us know.
