### ISSUE TITLE
[Feature] TreeTable: state-key

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primevue#2172]
I would be really convenient to have a state-key for the TreeTable - just like the DataTable.

**Comment by tugcekucukoglu** [comment]
TreeTable does not keep storage so there is no need to use state-key. For now closing this issue.

**Comment by TheParad0X** [comment]
Well, I know the TreeTable does not keep storage. I said that it would be very convenient, hence this enhancement issue 🤷🏻
