### ISSUE TITLE
Solution bug #1389

### ISSUE THREAD

**Issue by juandfranco** [primefaces/primevue#2184]
Greetings after struggling with this error, I write the definitive solution for this problem

Replace line 24 of the Dropdown.vue file currently:
https://github.com/primefaces/primevue/blob/470a4289e5ec46c4b20f4def911b722b2b82589a/src/components/dropdown/Dropdown.vue#L24

`<input type="text" ref="filterInput" v-model="filterValue" @vnode-updated="onFilterUpdated" autoComplete="off" class="p-dropdown-filter p-inputtext p-component" :placeholder="filterPlaceholder" @keydown="onFilterKeyDown"  @input="onFilterChange"/>`

For:

```
<input type="text" ref="filterInput" :value="filterValue" @vnode-updated="onFilterUpdated" autoComplete="off" class="p-dropdown-filter p-inputtext p-component" 
                            :placeholder="filterPlaceholder"  
                            @keydown="filterValue = $event.target.value"
                            @input="filterValue = $event.target.value"
                            />
```

Preview:
![primevuefix](https://user-images.githubusercontent.com/22731770/154621040-770c8db4-d11e-4add-89f6-90af63ee3e42.gif)

Thanks

**Comment by tugcekucukoglu** [comment]
Thanks for the great solution.

If you consider adding this solution as a PR, we gladly accept it.

**Comment by tugcekucukoglu** [comment]
Duplicate [#1389 ](https://github.com/primefaces/primevue/issues/1389)
