### ISSUE TITLE
DataTable: dark theme + rowHover + frozen column => overlapping contents

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#2197]
**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/little-sky-s4z6py?file=/src/DataTableScrollDemo.vue

**Minimal reproduction of the problem with instructions**

 Scroll the page horizontally then hover on a row it will show overlapping contents.

**Comment by tugcekucukoglu** [comment]
Please check this line of [code](https://codesandbox.io/s/frosty-firefly-sovc10?file=/src/DataTableScrollDemo.vue:5249-5257)

**Comment by nndnha** [comment]
@tugcekucukoglu I’m sorry, I didn’t catch that, the overlapping contents are still there

https://user-images.githubusercontent.com/12961516/156865110-c4bf4301-0788-40d0-9e04-738042e21c08.mp4

**Comment by nndnha** [comment]
@tugcekucukoglu Pls don't ignore that, did you see the problem in the above video?

**Comment by UsagiLan** [comment]
I've met the same problem, and i add same css to over write the styles of hovered cell, it will solve the problem above:
`:deep(.p-datatable.p-datatable-hoverable-rows
			.p-datatable-tbody
			> tr:not(.p-highlight):hover) {
		background: var(--gray-800);
	}`

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. So, closed. If the problem persists with the latest version, please reopen this issue or create new one.

Best Regards,
