### ISSUE TITLE
Fixed class binding quotation mark typo on Menubar Docs

### ISSUE THREAD

**Issue by robotpsychology** [primefaces/primevue#2204]
**I'm submitting a ...**  
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

On [line 186](https://github.com/primefaces/primevue/blob/master/src/views/menubar/MenubarDoc.vue#L186) of the Menubar docs there is a class binding quotation mark typo inside the <a> tag on the router configuration example that leads to an error when used. Will submit pull request. Simply changed
`:class="{'active-link': isActive, 'active-link-exact": isExactActive}`
to
`:class="{'active-link': isActive, 'active-link-exact': isExactActive}"`
in the <a> tag.

**Comment by robotpsychology** [comment]
Pull request: https://github.com/primefaces/primevue/issues/2204

**Comment by tugcekucukoglu** [comment]
Merged .

Thanks,
