### ISSUE TITLE
Chart documentation missing loaded event

### ISSUE THREAD

**Issue by AndreasNasman** [primefaces/primevue#2215]
https://www.primefaces.org/primevue/#:~:text=in%20the%20options.-,Events,-Name shows only `select` all though there is also a `loaded` event you can listen to.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/17124245/155606140-f64f84c3-ad6b-4e54-9b00-1e5d3ad542bd.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/17124245/155606244-4f7eb731-857c-459e-aac6-914e594530b4.png">

**Comment by tugcekucukoglu** [comment]
Thanks for the report. It will added.
