### ISSUE TITLE
Autocomplete losses focus when mobile keyboard is opened.

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2217]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/purple-bash-jr996i?file=/src/App.vue

**Current behavior**
I am using AutoComplete component with completeOnFocus option.
When I click on input it gets focused and open modal with options. 
While keyboard shows up input losses focus and modal is closed.

**Expected behavior**
Prevent suggestions from being closed when keyboard is showed.

**Please tell us about your environment:**
Android 11

**Comment by tugcekucukoglu** [comment]
When input is clicked, the complete method will fired while using completeOnFocus. For this async function, setTimeout must be called. 

```
searchData(event) {
            setTimeout(() => {
                this.filteredData = this.data.filter(....);
            }, 100);
        },
```

**Comment by mitow7821** [comment]
@tugcekucukoglu this works but adding delay feels hacky and results in bad UX (100 is not enough in my situation and I feel like keyboard animation time could be different on each device). Is there any way to make modal stay opened, even after keyboard shows up? Dropdown component works perfect in this scenario.
