### ISSUE TITLE
DataTable with virtualScrollerOptions break scrollHeight="flex"

### ISSUE THREAD

**Issue by bgoscinski** [primefaces/primevue#2218]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/cranky-gagarin-xuz9pk?file=/src/DataTableVirtualScrollDemo.vue

**Current behavior**
When using `scrollHeight="flex"` DataTable adapts to changing available vertical space. This behavior is broken when using _also_ `virtualScrollerOptions` on DataTable and available vertical space grows. Available area highlighted in green should be occupied by DataTable

![image](https://user-images.githubusercontent.com/5730169/155718321-459a629d-057d-444e-843c-02e78d04fd34.png)

**Expected behavior**
DataTable should fill available space when it grows

**Minimal reproduction of the problem with instructions**
1. Create DataTable with `scrollHeight="flex"` and virtual scrolling
2. Allow it to initialize
3. Make available space bigger (for example by maximizing the window)

**What is the motivation / use case for changing the behavior?**
Should look good

**Please tell us about your environment:**
Windows 10, Chrome and Brave

* **Vue version:** 3.2.31
* **PrimeVue version:** 3.12.0
* **Browser:** Reproduced on Chrome and Brave. Didn't test others

**Comment by bgoscinski** [comment]
The bug is still reproducible on PrimeVue 3.15.0

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response. This issue has already been fixed in the latest version. Please try it.

Best regards,
