### ISSUE TITLE
Dropdown and MultiSelect components display zero incorrectly when selected from options array of numbers

### ISSUE THREAD

**Issue by wkrick** [primefaces/primevue#2222]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```
**Current behavior**
the Dropdown and MultiSelect PrimeVue components do not display as expected when the option array contains numbers, specifically the number"zero".   All other numbers appear to work as expected.

Dropdown: 0 displays as "empty"
MultiSelect: 0 displays as "null"

**Expected behavior**
I expect both components to display zero as "0"

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/busy-star-kszt3i?file=/src/App.vue

INSTRUCTIONS: Select the "0" item in either control.

**What is the motivation / use case for changing the behavior?**

I have a JSON data sources that have fields that are numbers (not strings) and I'm using that to populate Dropdown and MultiSelect controls dynamically.

**Please tell us about your environment:**
Windows 10, VS Code, npm, Vite

* **Vue version:** 3.2.25

* **PrimeVue version:** 3.12.0

* **Browser:** Firefox 97.0.1 (64-bit), Chrome 98.0.4758.102 (Official Build) (64-bit)

**Comment by tugcekucukoglu** [comment]
Docs says `Dropdown requires a value to bind and a collection of arbitrary objects along with the optionLabel property to specify the label property of the option.`

Please look at [this example](https://codesandbox.io/s/objective-spence-2st1yf?file=/src/MultiSelectDemo.vue)

**Comment by wkrick** [comment]
I see that's what it says, but it works as expected if you feed in an array of strings, but not when you feed in an array of number primitives.  So it's just inconsistent.  Maybe this should be reclassified as a "feature request".

For reference, a normal select in Vue 3 behaves as expected when fed an array of numbers...
https://codesandbox.io/s/competent-diffie-5j74ds?file=/src/App.vue
(Ignore the lint warnings about the v-bind:key)

As an aside, the issue reporting template (which my example is based on) seems really buggy and doesn't always load correctly.  It's pretty annoying...  
https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

**Comment by tugcekucukoglu** [comment]
[https://codesandbox.io/s/competent-diffie-5j74ds?file=/src/App.vue](https://codesandbox.io/s/competent-diffie-5j74ds?file=/src/App.vue) is still empty. Could you provide a link with an example demo.
