### ISSUE TITLE
Material DataTable extension border typo fix

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#2227]
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Minimal reproduction of the problem with instructions**

https://github.com/primefaces/primevue/search?q=3404040&type=code

**Comment by tugcekucukoglu** [comment]
Please reopen this same issue with working link.

**Comment by nndnha** [comment]
@tugcekucukoglu https://github.com/primefaces/primevue/blob/d8ad47cab41b7cc749ea491311573c76d37a0792/public/themes/md-dark-deeppurple/theme.css#L2536

Just search for *3404040* in this repository.

**Comment by nndnha** [comment]
TIL that github's search result page is not a portable link, here is screenshot of the search result page on my machine 
![cs](https://user-images.githubusercontent.com/12961516/156132900-6becda99-ff2e-47db-8999-eba0a583b0b4.png)

https://cs.github.com/primefaces/primevue?q=3404040
