### ISSUE TITLE
Dropdown is not displaying lable when I set optionValue and optionLabel

### ISSUE THREAD

**Issue by abidmaqbool20** [primefaces/primevue#2233]
## Dropdown code

<Dropdown @change="setParentModule" modelValue="1" v-model="form.parent_module_id" optionValue="id" :options="modules"  optionLabel="name" :filter="true" placeholder="Select a Parent Module" :showClear="true" class="full-width">
                                                    <template #value="slotProps">
                                                        <div class="item item-value" v-if="slotProps.value"> 
                                                            <div>{{slotProps.value.name}}</div>
                                                        </div>
                                                        <span v-else>
                                                            {{slotProps.placeholder}}
                                                        </span>
                                                    </template>
                                                    <template #option="slotProps">
                                                        <div class="item"> 
                                                            <div>{{slotProps.option.name}}</div>
                                                        </div>
                                                    </template>
                                                </Dropdown>

## Data I pass

[{'id' : 1, 'name' : 'dd'},{'id' : 2, 'name' : 'Modules'}]

 Please check the attached file to see the issue:

![dropdown error](https://user-images.githubusercontent.com/26866661/156129769-bc09030c-c9e3-4282-a352-5183d6208b40.JPG)

**Comment by tugcekucukoglu** [comment]
Could you please try this

```
<template #value="slotProps">
        {{ slotProps.value || slotProps.placeholder }}
</template>
```

**Comment by danny007in** [comment]
issue still not solved
