### ISSUE TITLE
Buttongroup with outlined buttons

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2238]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/hover-border-bug-upd15c?file=/src/App.vue

**Current behavior**
Hovering the first button displays an additional border between both buttons.
Results in an ugly 'jump' if you hover the button.
![image](https://user-images.githubusercontent.com/8471027/156158808-f70663f2-8002-4d33-9057-049dd2ab8981.png)
Note: Icons don't seem to load in the issue template. But that is a different problem.

**Possible Fix**
. p-buttonset > .p-button.p-button-outlined:enabled:not(:last-child):hover {
  border-right: none;
}

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

**Comment by Tarabass** [comment]
Seems like this issue is back again :(
