### ISSUE TITLE
Custom SVG icons on menu items

### ISSUE THREAD

**Issue by KeremKoksal** [primefaces/primevue#2243]
Hi, 

There was a request for custom icons on menu without templating before. Templating didn't work for me too. When I used the example from the docs, submenus were not rendering. So, I have changed the codebase and submited a [pull request](https://github.com/primefaces/primevue/pull/2242)

I have added svgIcon property to MenuItem and used it to render a svg icon on menu. I have used v-html and tested it for simple xss attacks. It's safe for script tags and html events. 
I have also added relevant documentation to "src/views/menu/MenuDoc.vue"

**Comment by pavi2410** [comment]
@tugcekucukoglu Is there support for custom SVG icons such as https://lucide.dev/ present now?
