### ISSUE TITLE
Reopen issues

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#225]
Is there any chance guys to reopen the following issues?
[#198 - Expanded dropdown inside the modal window](https://github.com/primefaces/primevue/issues/198)
[#194 - DataTable rowSelect event triggers rowClick](https://github.com/primefaces/primevue/issues/194)

I feel like they still need some rework. Let me know what do you think?

Thanks

**Comment by cagataycivici** [comment]
Please create new tickets instead.

**Comment by fairking** [comment]
Ok. Thanks. Will do.
