### ISSUE TITLE
InputNumber v-model behaves as v-model.lazy (unlike other components)

### ISSUE THREAD

**Issue by sua-dawn** [primefaces/primevue#2250]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
[codesandbox.io/...](https://codesandbox.io/s/modest-curran-7vj8cw)

**Current behavior**
`v-model` on `InputNumber` acts by default as `v-model.lazy` (it only updates model on blur/enter).
It only emits `'update:modelValue'` in the method `updateModel()`, which is only called in `onInputKeyDown()` (on enter-key), in `spin()` (?) and in `onInputBlur()`.
From: https://github.com/primefaces/primevue/blob/master/src/components/inputnumber/InputNumber.vue#L897-L900

**Expected behavior**
Expected the passed in `v-model` to update on input, as per default v-model behavior. (like `InputText` and most other components do)

**What is the motivation / use case for changing the behavior?**
Aligned `v-model` behavior across PrimeVue components.

**Please tell us about your environment:**
MacOS, Yarn, VSCode, Vite

* **Vue version:** `3.2.31`

* **PrimeVue version:** `3.12.1`

**Comment by tugcekucukoglu** [comment]
Please check [this issue](https://github.com/primefaces/primevue/issues/506)
