### ISSUE TITLE
SelectButton tooltips

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2252]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case **
https://codesandbox.io/s/tooltip-on-outer-element-xq0rde?file=/src/App.vue:682-704

**Current behavior**
It's not possible to have a tooltip on the whole individual option button.
I can add it only within the template, and this way the tooltip is only within the padding of the button.

**Expected behavior**
Would like to have a property to add the tooltip to the wrapping .p-button element.
eg.
'optionTooltip' = Property name or getter function to use as the value of the tooltip.
'optionTooltipDirection' = Property name or getter function for the direction of the displayed tooltip (top, bottom, left, right)

**What is the motivation / use case for changing the behavior?**
Hovering the buton does not show the tooltip, if you dont also hover the icon.
The current workaround to have the tooltip on the whole button:
You have to overwrite and remove the padding of the .p-button and add the padding to the element inside the template. 
Which is quite the ugly solution.

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

**Comment by tugcekucukoglu** [comment]
Please try to use v3.16.0. If the problem still persists, please reopen this same issue.
