### ISSUE TITLE
DataTable lazy loading paginator bug

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#2253]

**Comment by blv-federicoviviani** [comment]
Hello team, this is happening also in v 2.9.2 and is blocking my team to upgrade from 2.6.0 , do you have plan to look into this?
Thanks!

**Comment by Voltra** [comment]
I think I might look into it this week-end and make a PR, but I might just end up replacing `:first="lazy ? 0 : d_first"` with `:first="d_first"` (I'm still unclear on why it's always 0 when `lazy`)

**Comment by tugcekucukoglu** [comment]
The DataTable needs to know which row will be the first, just as it needs to know the number of rows.

https://stackblitz.com/edit/lxpxlz-93qeul?file=src%2FApp.vue%3AL106
