### ISSUE TITLE
Tooltip | dynamic argument

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#2255]
[directive-hooks](https://vuejs.org/guide/reusability/custom-directives.html#directive-hooks)

**Comment by tugcekucukoglu** [comment]
There is this kind of usage and the object key must be `position` or `event`: 

`<InputText v-tooltip:[pos]="...." />`


```
data() {
  return {
     pos: {position: 'bottom'}
  }
}
```

**Comment by pollna** [comment]
If this solution for dynamic position doesn't work for you, like it was in my case - don't forget to try adding `:key="..."` to the component for tooltip re-render 🙈 I was confused, when it didn't help, and wasted a lot of time trying other options to set another position when tooltips div gets out of a viewport. Althought this [unmatching behavior](https://github.com/primefaces/primevue/issues/3822) could be easily fixed, like it [stated here](https://github.com/primefaces/primevue/issues/3975) 😥
