### ISSUE TITLE
TreeTable | autoLayout property are not Compatible with Table Scroll 

### ISSUE THREAD

**Issue by Soph0208** [primefaces/primevue#2256]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/autumn-shadow-6uubl8?file=/src/TreeTableScrollDemo.vue:223-233

**Current behavior**
If the content of the cell increases, then the cell and the header do not adapt automatically, even though `autoLayout=true` is used.

**Expected behavior**
If the content of the cell changes, the cell and the header should increase in size at the same time.

* **Vue version:** 3.2.22

* **PrimeVue version:** 3.11.1

**Comment by tugcekucukoglu** [comment]
Please check [this example](https://codesandbox.io/s/autumn-shadow-forked-2p9gsd?file=/src/TreeTableScrollDemo.vue:380-419)
