### ISSUE TITLE
Styling not applied to Password component

### ISSUE THREAD

**Issue by monipatel26** [primefaces/primevue#2257]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Styling is applied to parent div when using style in Password component

**Expected behavior**
Styling should also apply to the inputbox

* **Vue version:** 3.0.0

* **PrimeVue version:** 3.9.1

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Please use `inputStyle ` props for this.

Thanks,
