### ISSUE TITLE
InputSwitch accessibility bug

### ISSUE THREAD

**Issue by franklioxygen** [primefaces/primevue#2258]
**I'm submitting a accessibility bug**  (check one with "x")

MacOS VoiceOver cant read correct InputSwitch status

**Minimal reproduction of the problem with instructions**

1. Visit official document of InputSwitch
https://www.primefaces.org/primevue/#/inputswitch
2. Enable VoiceOver from Mac
3. Focus any switch then trigger it.
4. It only read initial status (ON/OFF), won't change reading after toggle.

**Please tell us about your environment:**
MacOS 10.15.7

* **PrimeVue version:** 3.4.X
5.12.1

* **Browser:**
Safari 15.3

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q2. 

Thanks for your report!

**Comment by franklioxygen** [comment]
Thank you! 
I found another accessibility bug:

**Message accessibility bug**

I'm submitting a accessibility bug (check one with "x")

MacOS VoiceOver close Message will bring focus to top element of page

Minimal reproduction of the problem with instructions

Visit official document of InputSwitch
https://www.primefaces.org/primevue/#/message
Enable VoiceOver from Mac
Focus any message then close it.
Navigate to next message or element, VO focus go to top element (website header logo).

Please tell us about your environment:
MacOS 10.15.7

PrimeVue version: 3.4.X
5.12.1

Browser:
Safari 15.3
