### ISSUE TITLE
Column Header not fit column content when header text is short and body text is large

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#2267]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/nifty-heyrovsky-vll9ym?file=/src/DataTableScrollDemo.vue

**Current behavior**
Columns and text not fit same column.

Demo:

![image](https://user-images.githubusercontent.com/2920935/157208796-02ac644b-eaa6-497a-94ed-97d668135afa.png)

**Expected behavior**
Headers fitting his space in columns, they remains aligned with body content.

**Please tell us about your environment:**

* **Vue version:** 3.2.31

* **PrimeVue version:** 3.12.1

* **Browser:** All

**Comment by tugcekucukoglu** [comment]
It is a demo problem. [https://codesandbox.io/s/nifty-heyrovsky-vll9ym?file=/src/DataTableScrollDemo.vue](https://codesandbox.io/s/nifty-heyrovsky-vll9ym?file=/src/DataTableScrollDemo.vue)

**Comment by makurtu** [comment]
@tugcekucukoglu Your link throws an `import error`.

But you can simply try it with your default Primevue documentation: Change your fake value for `id` item to `SOMEVERYLARGETEXT`.

**Comment by tugcekucukoglu** [comment]
Sorry, I send you your link. [https://codesandbox.io/s/adoring-breeze-y3gypx](https://codesandbox.io/s/adoring-breeze-y3gypx)

If it stucks, could you please simply reload the page?

**Comment by makurtu** [comment]
@tugcekucukoglu True! It was an error from Codesandbox, thanks!

Can you tell me the error on my Demo example?

Thanks in advance! :clap:

**Comment by tugcekucukoglu** [comment]
Vertical scrolling uses flex, so you can set the width as you want. In your demo `id` columns have `100px` but setting is for example `200px` looks like solve the problem.
