### ISSUE TITLE
Menubar model prop doesn't work with raw/computed array

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#2268]
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/elegant-shadow-qiqo52?file=/src/MenubarDemo.vue

**Minimal reproduction of the problem with instructions**

There are 3 Menubars in the demo code and only the first one works.

**Comment by tugcekucukoglu** [comment]
Some Vue tips: [https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods](https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods)

[https://vuejs.org/guide/essentials/reactivity-fundamentals.html#reactive-variables-with-ref](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#reactive-variables-with-ref)

**Comment by nndnha** [comment]
@tugcekucukoglu So  what are you trying to say? According to this line of code  https://github.com/primefaces/primevue/blob/8d8a1f086e97bab77d2afcacc9b4cd170f68120b/src/components/menuitem/MenuItem.d.ts#L24 I didn't see why raw object/computed is invalid value for model props,  and the problem is that the submenu didn't work with raw/computed value, did you see that problem in the CodeSandbox link?

**Comment by DanHulton** [comment]
@nndnha I accidentally discovered the solution to this just now when getting frustrated by a similar issue with PanelMenu:

```
      computedItems: computed(() => items.map((item) => reactive(item))),
```

Computed items can't be modified, but reactive ones can.  So if your computed items return a reactive version of themselves, it works as expected!

**Comment by agm1984** [comment]
Thanks to @DanHulton I fixed my menu:

``` vue
const menuItems = computed(() => ([
    reactive({
        label: 'Set status to',
        icon: 'icon-logout',
        items: [
            {
                label: 'Active',
            },
            {
                label: 'On hold',
            },
            {
                label: 'Terminated',
            },
        ],
    }),
    reactive({
        label: 'Add to program',
        icon: 'icon-programs',
        command: () => openAddToProgramModal(),
        disabled: !employees.checkedRows.length,
    }),
    reactive({
        label: 'Message',
        icon: 'icon-message',
        command: () => openMessageModal(),
        disabled: !employees.checkedRows.length,
    }),
    reactive({
        label: 'Customize columns',
        icon: 'icon-settings',
        command: () => openCustomizeColumnsModal(),
    }),
]));
```
