### ISSUE TITLE
DataTable expanded on row click

### ISSUE THREAD

**Issue by EwaMakowska** [primefaces/primevue#2276]
Hi,

As in title. I really don't know what is important to do this. Do I have to call some method additionally (how it's named), or is array expandedRows is enough? Have I have this button created by expander="true", or I can miss it?

If this is possible, please, create some examples.

**Comment by tugcekucukoglu** [comment]
Please check [this example](https://codesandbox.io/s/yvtpv).

If problem is still persist, please reopen this issue with codesandbox example.

**Comment by nathanhennig** [comment]
Just wanted to add this for future readers.

That example just shows the same collapse all/expand all that's in the documentation. Helpful, but I (and I assume the original poster) wanted to open and close individual rows. After a while I realized that the expandedRows needs to use shallow copies of data rows and be reassigned to trigger view updates, and I came up with:

```
            <Column header="Actions">
                <template #body={data}>
                    <div>
                        <button @click="toggleRow(data)">
                            Update / Add
                        </button>
                    </div>
                </template>
            </Column>
          
------

        const toggleRow = (data) => {
            const index = expandedRows.value.find(x => x.id === data.id)

            if (index === undefined) {
                expandedRows.value = [...props.pageData.filter(x => x.id === data.id), ...expandedRows.value]
            } else {
                expandedRows.value = expandedRows.value.filter(x => x.id !== data.id)
            }
        }
```
Using the triple dot spread operator and filter() let me get shallow copies of the data rows. I'm not sure if there's a more elegant way to get the data row refs, but this worked in my project.
