### ISSUE TITLE
DataTable rowSelect event triggers rowClick

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#228]
Primevue: 1.0.6

Old conversation: https://github.com/primefaces/primevue/issues/194

Still having an issue with ability of multiselect and showing details on row click at the same time.

The problem is checking the checkbox triggers row click.

Details of the current behaviour reproduced here: Branch https://github.com/fairking/primevue/tree/DatatableRowClickIssue (see DataTable -> Selection -> Checkboxes page) (Commit: https://github.com/fairking/primevue/commit/0bf73a653c70e87cb95f3750dc4fb1b6f6510db8)

The temporary and very ugly solution is:
```
rowClick(e) {
    if (!e.originalEvent.target.classList.contains('p-checkbox-box') 
        && !e.originalEvent.target.parentElement.classList.contains('p-checkbox-box')) {
        this.showRowDetails(e.data); // Open dialog with row details.
    }
},
```

My proposal was to stop propagating `click` on the checkbox (multi mode) and radio button (single mode).

**Comment by cagataycivici** [comment]
@mertsincan Wdyt? It still makes sense for rowSelect with mouse to trigger rowClick as we did for all other Prime UI libraries.
