### ISSUE TITLE
datatable  RowSpan Grouping and Frozen Columns not functional

### ISSUE THREAD

**Issue by dt-jegomez** [primefaces/primevue#2299]
I am doing freezing my first column and I am also grouping them. but this does not work apparently they are not compatible.
apparently the "scrollable" props is not compatible with
"Row Span Grouping"

if I remove "scrollable" the grouping is correct but the freezing is not done

https://codesandbox.io/s/weathered-waterfall-d5xwzk?file=/src/DataTableScrollDemo.vue:441-459

**Comment by eliasbermudez** [comment]
I have the same problem

**Comment by duvanweb** [comment]
I have the same problem

**Comment by cantin-f** [comment]
Same problem here, waiting for a fix.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
