### ISSUE TITLE
DataTable rowsPerPage option does not work

### ISSUE THREAD

**Issue by hargitomi97** [primefaces/primevue#2304]
Hi!

I have a working table in Vue3, like here:
![image](https://user-images.githubusercontent.com/36476318/157838659-fc9aa301-aa9f-4573-96a0-363b86fad3be.png)

However, when I add `:rowsPerPageOptions="[10,20,50]"`, it does not work.
![image](https://user-images.githubusercontent.com/36476318/157838877-6f88886d-12e0-4a2f-a465-1ecfa1dfbfec.png)
When I try to click it, I get the following error:
![image](https://user-images.githubusercontent.com/36476318/157838948-c6e133d1-9ac6-48a3-89a0-fc5e23e802e9.png)

Can someone help me what am I missing? Everything else work fine. Is this a bug?

**Comment by tugcekucukoglu** [comment]
Please import PrimeVue in main.js

```
import PrimeVue from 'primevue/config';

app.use(PrimeVue);
```
