### ISSUE TITLE
[Bug][Android] DataTable filter input field hides Android keyboard on focus

### ISSUE THREAD

**Issue by Gobbo89** [primefaces/primevue#2318]
Hello.

**I'm submitting a bug report**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already
[ ] support request => Please do not submit support request here, instead see
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/nehsv

**Current behavior**
DataTable component. Trying to apply a filter from all Android browsers.
As soon as you focus the input field for a filter, Android keyboard pops up and immediately hides.
The filter menu then closes.

**Expected behavior**
You should be able to focus the input field, input some text using your keyboard and then applying the filter.

**Minimal reproduction of the problem with instructions**.
- Tap the filter symbol for whatever column
- Filter menu appears, tap the input field 

You can reproduce here: https://codesandbox.io/s/nehsv or even using the [Documentation page for DataTable component](https://primefaces.org/primevue/#/datatable).
Screen capture of the bug: https://giphy.com/gifs/MPXWiPugy5ba2Jir5d/fullscreen

**What is the motivation / use case for changing the behavior?**
With the current behavior It is impossible to effectively use filters for DataTable on Android.

**Please tell us about your environment:**
Android 11 / Android 12

* **Vue version:** 3.2.31

* **PrimeVue version:** 3.12.1

* **Browser:** Mobile Chrome, Mobile Opera, Mobile Firefox, Android Web Browser

Thank you.

**Comment by arnyee** [comment]
Unfortunately, this error also occurred to me, but I could not find a solution. Has there been any solution to this since then?

**Comment by mertsincan** [comment]
Fixed with https://github.com/primefaces/primevue/issues/2618
