### ISSUE TITLE
DataTable header and body style 

### ISSUE THREAD

**Issue by Errichamonda** [primefaces/primevue#2327]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

https://codesandbox.io/s/sharp-rui-rgfjzt

**Current behavior**

Header and body style are not applied

**Expected behavior**
Header and body style to be applied correctly

**Minimal reproduction of the problem with instructions**
Apply frozen to any column and try to give it a width

**Please tell us about your environment:**
Windows 11
Node 16
NuxtJS

* **Vue version:** 2.X

* **PrimeVue version:** 2.9.1

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
These are must be an object. [https://codesandbox.io/s/nervous-maxwell-l0xsbe?file=/src/App.vue](https://codesandbox.io/s/nervous-maxwell-l0xsbe?file=/src/App.vue)
