### ISSUE TITLE
Boolean Columns for DataTables Create False-Positive Matches with Global Filters

### ISSUE THREAD

**Issue by AverageCakeSlice** [primefaces/primevue#2331]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/datatable-filter-type-coercion-bug-jo9p6l?file=/src/App.vue

**Current behavior**
If you have a boolean column on the DataTable component, the global filter will get a false-positive match with "true" or "false" string literals, or any substring of those values ("rue", "lse", "fal", etc.). Using the `excludeGlobalFilter` property on the column doesn't seem to work around this behavior either.

**Expected behavior**
I would expect boolean columns to be excluded from global filters by default, but at the very least, substrings of "true" and "false" shouldn't filter down the table data at all, and nothing should happen at all if the excludeGlobalFilter property is present.

**Minimal reproduction of the problem with instructions**
In the global filter InputText field, enter "true" "false" or any substring of the two. The rows should filter down to fields that match with the boolean column. See the codesandbox linked above for a demo of the issue.

**What is the motivation / use case for changing the behavior?**
This behavior causes issues when trying to search through other fields, as it creates false-positive matches for certain substrings, (say I was searching for an iPhone SE from a list of phone models that also has a "5G Enabled" boolean column, and I type "se" into the search field. Instead of filtering properly, I'll get both rows with the iPhone SE model name, as well as matches with any row that has a false value in the 5G column, which isn't very useful.

**Please tell us about your environment:**
MacBook Pro 2020 (Intel), MacOS Monterey 12.2.1, Visual Studio Code, Freya 3.0.0 template, NPM, Webpack

* **Vue version:** 3.X
Vue 3.2.31

* **PrimeVue version:** 3.4.X
PrimeVue 3.10.0

* **Browser:** 
* Chrome 99 (MacOS)
* Brave Browser 1.36.22
* Safari 15.3

**Comment by tugcekucukoglu** [comment]
Please check the [example](https://codesandbox.io/s/magical-lucy-y7ykgb?file=/src/DataTableFilterDemo.vue)
