### ISSUE TITLE
Frozen columns get hidden when Datatable container width is tiny

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#2332]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
You can try this bug with the default demo CodeSandbox (is the CodeSandbox provided by the official Docs).

**Current behavior**
When the container of the Datatable is tiny, and you have Frozen columns, this frozen columns get hidden.

**Expected behavior**
Frozen columns reimains visible even if the cointainer is tiny. 

**Minimal reproduction of the problem with instructions**

I've recorded a video showing this issue, I think that is a problem with `position: sticky` of `.p-column-frozen`.

https://user-images.githubusercontent.com/2920935/158758396-68b29ffd-80c0-4538-be26-e2415cb35a7e.mp4

* **Vue version:** latest

* **PrimeVue version:** latest

* **Browser:** all.

**Comment by tugcekucukoglu** [comment]
Could you check[this example ](https://codesandbox.io/s/admiring-sound-bgcth7?file=/src/DataTableScrollDemo.vue)?

**Comment by makurtu** [comment]
Yes! Now it seems to work!

I will try it on my code. Many thanks @tugcekucukoglu
