### ISSUE TITLE
Multiselect overflows when used inside inputgroup with float-label

### ISSUE THREAD

**Issue by rodrigoUriarte** [primefaces/primevue#2335]
Hello.
I am having a problem using the Multiselect component in conjunction with float label and input-group.
When the amount of multiselect elements exceeds the physical space of the input, the input overflows its space, occupying space of the input next to it. 
I have made a sanbox with an example similar to the one I found in the documentation.
[SANDBOX example](https://codesandbox.io/embed/pedantic-wilbur-6885bp?fontsize=14&hidenavigation=1&theme=dark)
I'm currently using version 2.9.1 but apparently it also affects version 3.12.2
Greetings.

**Comment by tugcekucukoglu** [comment]
All accessibility issues will be fixed in 2022 Q2. 

Thanks for your report.
