### ISSUE TITLE
v2 PrimeVue @keyup.enter event does not work on InputNumber component

### ISSUE THREAD

**Issue by timurash** [primefaces/primevue#2336]
**I'm submitting a bug report** 

**CodeSandbox Case (Bug Reports)**

https://codesandbox.io/s/v2-primevue-inputnumber-keyup-enter-events-pchd2i?file=/src/App.vue

**Current behavior**
@keyup.enter event does not work on InputNumber component

**Minimal reproduction of the problem with instructions**

![ezgif-1-fbccbcf617](https://user-images.githubusercontent.com/63206211/158971950-4a833962-7a1f-455c-872e-a8ee8ef5b624.gif)

* **Vue version:** 2.6.14

* **PrimeVue version:** 2.9.1

**Comment by MedLabs** [comment]
@keyup.enter does not work on Input components and buttons

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/4e220384577701de44e6df7abd2fdc099dd107ca
