### ISSUE TITLE
Excessive Datatable select all time with Large Datasets starting with Primevue 3.10.0. Works correctly in older versions

### ISSUE THREAD

**Issue by mr83-uw** [primefaces/primevue#2339]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**CodeSandbox Case (Bug Reports)**
v3.9.1 -> https://codesandbox.io/s/epic-tesla-90sprw
v3.12.2 -> https://codesandbox.io/s/agitated-haze-rf7gw4

**Current behavior**
Select All Header Checkbox times out in any Primevue version after 3.9.1 for large data sets starting with primevue 3.10.0. Using older versions of the library causes the checkbox to work as expected. 

**Expected behavior**
Quick selection of all the elements in the datatable. 

**Minimal reproduction of the problem with instructions**
Click the select all box in the header using either of the code sandboxes above.

**Please tell us about your environment:**
Windows, Chrome 99, Primevue 3.12.2

* **Vue version:** 3.X
Tested in vue 3.1.15 and 3.2.10

* **PrimeVue version:** 3.4.X
3.12.2

* **Browser:**
Chrome

**Comment by tugcekucukoglu** [comment]
There is a breaking change. In this case you could use new `selectAll` prop and `select-all-change` method similar to [Lazy Demo](https://www.æçprimefaces.org/primevue/#/datatable/lazy)
