### ISSUE TITLE
Sidebar overlay is still visible after closing 

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2343]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Can't replicate on sandbox. It's old issue (https://github.com/primefaces/primevue/issues/1541)

**Current behavior**
After closing sidebar overlay is still visible. I've found this issue https://github.com/primefaces/primevue/issues/1541 and after adding leave animation it works.

**Expected behavior**
Overlay should not be visible after close.

**Comment by mitow7821** [comment]
Missing css:
``` 
.p-component-overlay-leave {
  animation: p-component-overlay-leave-animation 150ms forwards;
}

@keyframes p-component-overlay-leave-animation {
  to {
    background-color: transparent;
  }
}
```

**Comment by tugcekucukoglu** [comment]
Without knowing PrimeVue version, it's really hard to demonstrate this issue. Please fill the issue template while creating an ticket.

Please reopen this issue with a codesandbox or a repo. Even if issue can't replicate on a codesandbox, please send a link so we could use it in a local repo.

Also leave animation is not missing [https://github.com/primefaces/primevue/blob/master/public/themes/saga-blue/theme.css#L93](https://github.com/primefaces/primevue/blob/master/public/themes/saga-blue/theme.css#L93)

**Comment by romanown** [comment]
overlay is show and i can not click on any element. css missing for p-component-overlay-leave. but it not fix this problem.
