### ISSUE TITLE
Tooltips do not appear on the dropdown control

### ISSUE THREAD

**Issue by TRexOnGit** [primefaces/primevue#2344]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/tooltip-on-outer-element-forked-g3d0jo?file=/src/App.vue

**Current behavior**
Tooltips do not appear on dropdowns.

**Expected behavior**
Tooltips should appear on dropdown controls

**Minimal reproduction of the problem with instructions**
Create a Dropdown and add a tooltip. Tooltip does not appear.
Create any other control with a tooltip. Tooltip appears as expected.

**What is the motivation / use case for changing the behavior?**
Users would like to have tooltips on all controls including dropdowns.

* **Vue version:** 3.X
Most recent version used when reported.

* **PrimeVue version:** 3.4.X
Most recent version used when reported.

* **Browser:** Tested on Chrome

**Comment by hakiiver2** [comment]
@tugcekucukoglu @TRexOnGit 
Same
How did you fix it?
I temporarily did as in the picture below.
I do not think this is the right way.

![スクリーンショット 2022-07-05 22 23 01](https://user-images.githubusercontent.com/42739911/177337943-8d113654-9e35-49b4-99c2-e8c04f5c09a0.png)

**Comment by TRexOnGit** [comment]
@hakiiver2 I have not solved it. I would have thought that primevue would have done it by now. 😢

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by iampapagray** [comment]
This still doesnt work for me.
