### ISSUE TITLE
FileUpload removes file in preview when auto=true

### ISSUE THREAD

**Issue by Rpgilligan85** [primefaces/primevue#2347]
[x ] bug report

**Current behavior**
In FileUpload if you have auto set to true it will remove the file after it finishes uploading. 

**Expected behavior**
Should work the same way when auto is set to false, the file should stay in the preview. It worked this way in previous versions.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/fast-hooks-0e51g7

**What is the motivation / use case for changing the behavior?**
Have the ability to remove files if they don't need it anymore like the previous versions.

* **Vue version:** 3.X
3.2.16

* **PrimeVue version:** 3.4.X
3.12.2

Broken in all browsers

**Comment by tugcekucukoglu** [comment]
This is expected behavior. Auto means here just like that `upload begins automatically after selection is completed.`
