### ISSUE TITLE
Removable sort on DataTable

### ISSUE THREAD

**Issue by Deepak2985** [primefaces/primevue#235]
If we apply sorting to the column in datatable. We can then only sort it ascending and descending.
There is no option of removing the sort. What I am mean to say on clicking third time on the column header the sorting should get removed.

**Comment by Deepak2985** [comment]
Yes I have seen please find the link below.
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/defaultfunctionality.htm?light

**Comment by Deepak2985** [comment]
One more Angular material datatable
https://material.angular.io/components/table/overview

**Comment by Deepak2985** [comment]
@Sellec The thing is if we add sort to a column then we should have an option to remove the sort. Right?

**Comment by cagataycivici** [comment]
Although it is not a common UX, it is available in PrimeReact, see the removable sort option.

https://primefaces.org/primereact/showcase/#/datatable/sort

If there is demand on this issue, we can add it to PrimeVue as well.

**Comment by wanglin86769** [comment]
For the bootstrap-vue component library, Clicking on a non-sortable column header will clear the sorting.
https://bootstrap-vue.js.org/docs/components/table

**Comment by cagataycivici** [comment]
Adding **removableSort** enables this behavior where 3rd click removes the sorting on a column, also works on multiple column sorting.
