### ISSUE TITLE
DataTable filtering causes js TypeError

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#2353]
**I'm submitting a bug report with version 2.9.1.**  

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/ecstatic-archimedes-x93xsk

**Current behavior**
JS error when pressing filter button in column header in mode "menu".

> TypeError: Cannot read properties of undefined (reading 'operator')
    at VueComponent.isShowOperator (https://x93xsk.csb.app/node_modules/primevue/datatable/ColumnFilter.vue?8b2a5a0c:483:60)

**Expected behavior**
Must be opened pop-up filter menu.

**Minimal reproduction of the problem with instructions**
Create default datatable from PrimeVue docs with filterDisplay="menu" and any filtered column.

* **Vue version:** 2.6.14

* **PrimeVue version:** 2.9.1

* **Browser:** [all]

**Comment by tugcekucukoglu** [comment]
Could you please check this [example](https://codesandbox.io/s/billowing-meadow-jus9ts?file=/src/App.vue)?

**Comment by chrisjohnstone** [comment]
Would it be possible to post the solution set out in the example? I'm facing the same issue and the example codesandbox is no longer available.

**Comment by timmushen** [comment]
Any word on the solution?

**Comment by MathieuB1** [comment]
After digging in my case v-model:filters="filters1" was missing.
