### ISSUE TITLE
Accordion header broken on some default themes.

### ISSUE THREAD

**Issue by JsonMiller** [primefaces/primevue#2357]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/fervent-sutherland-7qlzsl?file=/src/App.vue

**Current behavior**
When using a default dark theme from PrimeVue and using a Accordion Panel the hover over whites out the Accordion Header.

**Expected behavior**
When using a default dark theme from PrimeVue hovering over an Accordion Panel header the header should be highlighted instead of white. A light shade of the color perhaps?

**Minimal reproduction of the problem with instructions**
I included a repro in code sandbox but it kept giving me errors so here's a small repo also.
1. Create a project using bootstrap4-dark-purple or md-dark-indigo I assume others might have the same problem, but I only tried these two.
2. Add an Accordion Panel to your app with some kind of header, doesn't need to be custom.
3. Hover over the header.
4. Header is completely whited out instead of highlighted.

**What is the motivation / use case for changing the behavior?**
The header looks terrible being whited out and the text is no longer readable.

**Please tell us about your environment:**

Windows, WebStorm, Node / Express, Tested in Chrome and Firefox latest.

* **Vue version:** 3.X
Vue 3.2.20

* **PrimeVue version:** 3.4.X
PrimeVue 3.8.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 98.0.1 Chrome 99.0.4844.82

**Comment by tugcekucukoglu** [comment]
Please check this [example ](https://codesandbox.io/s/infallible-surf-5fl2es?file=/src/index.css:36-79). In this example body background is changed. Also you can change background or color style of the `p-accordion-header-link` when `p-accordion-header` is hovered.

**Comment by JsonMiller** [comment]
Man I went through a whole gamut of emotions processing your response. I eventually sussed out what needed doing and got it working! 

Thanks for the help!
