### ISSUE TITLE
autoClear not working for InputMask

### ISSUE THREAD

**Issue by monipatel26** [primefaces/primevue#2358]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Setting autoClear for InputMask to false still clears value on blur

**Expected behavior**
Setting autoClear for InputMask to false should not clear value on blur

**Please tell us about your environment:**
OS: MacOS 12.3
IDE: Visual studio code

* **Vue version:** 3.0.0

* **PrimeVue version:** 3.9.1

* **Browser:** all

* **Warning:**
<img width="1668" alt="Screen Shot 2022-03-28 at 01 11 54" src="https://user-images.githubusercontent.com/8273099/160330553-29e22407-e1d6-4b2a-a026-ca28a416c6ce.png">

**Comment by tugcekucukoglu** [comment]
`:autoClear="false"`

This clears the typescript issue and works correctly.
