### ISSUE TITLE
DataTable header not displayed

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#236]
DataTable header in version 1.0.2 can be display properly. However, if I update to 1.0.7, the DataTable header disappears, even if I run the sample sigma-vue project.

**Comment by cagataycivici** [comment]
Can you send me an example please? Demos work fine on 1.0.7;

https://primefaces.org/primevue/showcase/#/datatable/templating

**Comment by wanglin86769** [comment]
My operations are as follows:

1. Cloned the following repository,
https://github.com/primefaces/sigma-vue

2. npm uninstall primevue

3. npm install primevue -D

4. npm run serve

**Comment by wanglin86769** [comment]
D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git config --get remote.origin.url
https://github.com/primefaces/sigma-vue.git

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>
D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git diff package.json
diff --git a/package.json b/package.json
index 94410e9..8ff593d 100644
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
                "node-sass": "^4.9.0",
                "primeflex": "1.0.0",
                "primeicons": "2.0.0",
-               "primevue": "1.0.2",
+               "primevue": "^1.0.7",
                "prismjs": "^1.15.0",
                "quill": "^1.3.7",
                "sass-loader": "^7.1.0",

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>

**Comment by wanglin86769** [comment]
`D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git config --get remote.origin.url
https://github.com/primefaces/sigma-vue.git

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>
D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git diff package.json
diff --git a/package.json b/package.json
index 94410e9..8ff593d 100644
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
                "node-sass": "^4.9.0",
                "primeflex": "1.0.0",
                "primeicons": "2.0.0",
-               "primevue": "1.0.2",
+               "primevue": "^1.0.7",
                "prismjs": "^1.15.0",
                "quill": "^1.3.7",
                "sass-loader": "^7.1.0",

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>`

**Comment by wanglin86769** [comment]
D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git config --get remote.origin.url
https://github.com/primefaces/sigma-vue.git

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>
D:\Development4\AdminDashboard\PrimeVue\sigma-vue>git diff package.json
diff --git a/package.json b/package.json
index 94410e9..8ff593d 100644
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
                "node-sass": "^4.9.0",
                "primeflex": "1.0.0",
                "primeicons": "2.0.0",
--               "primevue": "1.0.2",
++               "primevue": "^1.0.7",
                "prismjs": "^1.15.0",
                "quill": "^1.3.7",
                "sass-loader": "^7.1.0",

D:\Development4\AdminDashboard\PrimeVue\sigma-vue>

**Comment by wanglin86769** [comment]
Attached are the screenshot.

**Comment by wanglin86769** [comment]
![sigma](https://user-images.githubusercontent.com/62229607/76777857-d3fc8400-67e3-11ea-8e1f-2e78208cf5c4.png)

**Comment by wanglin86769** [comment]
[sigma-vue.zip](https://github.com/primefaces/primevue/files/4339113/sigma-vue.zip)

**Comment by cagataycivici** [comment]
Headers worked fine for me.

<img width="1662" alt="Screen Shot 2020-03-17 at 12 18 27" src="https://user-images.githubusercontent.com/686247/76841154-700ca680-6849-11ea-942c-80c3a29e0309.png">
