### ISSUE TITLE
Menu | disabled property as a function is not working with command prop

### ISSUE THREAD

**Issue by marlonrichert** [primefaces/primevue#2365]
### CodeSandbox Case
https://codesandbox.io/s/falling-cdn-8rlxcu?file=/src/MenuDemo.vue

### Current behavior
In the menu model, if an object's `disabled` property is set to a function, then the corresponding `Menu` item's `command` no longer fires when clicked.

### Expected behavior
According to the [menu model documentation](https://www.primefaces.org/primevue/#/menumodel), `disabled` is allowed to be a boolean *or a function returning a boolean.* 

### Minimal reproduction of the problem with instructions
In the sandbox above, note that clicking Update does nothing, even though it has a valid `command`.

### What is the motivation / use case for changing the behavior?
The implementation should match the documentation.

### Environment
* Vue 3.1.5
* PrimeVue 3.12.2
* All browsers

**Comment by tugcekucukoglu** [comment]
This is expected behavior. Anchor link is disabled so click event do nothing.

**Comment by marlonrichert** [comment]
@tugcekucukoglu It’s not expected behavior [according to your documentation](https://www.primefaces.org/primevue/#/menumodel).

> Anchor link is disabled so click event do nothing.

That’s not at all an accurate description of the bug’s cause. The real problem lies on this line:
https://github.com/primefaces/primevue/blob/6f48ac5eed7427e039c0cf2613a360b3184da9b8/src/components/menu/Menu.vue#L88

It does not check if `disabled` is a function. According to your own documentation, `disabled` is allowed to be a function, just like `visible`. It should be check in the same way that you check `visible`:
https://github.com/primefaces/primevue/blob/6f48ac5eed7427e039c0cf2613a360b3184da9b8/src/components/menu/Menu.vue#L195

**Comment by AndreasNasman** [comment]
@tugcekucukoglu The `disable` property **is not working** per the documentation.

In the example, @marlonrichert has set the `disable` property to a function returning `false`,

```js
disabled: () => false,
```

meaning the `Menu` component should be enabled. In the current implementation, it's disabled, however. See Marlon's answer where it occurs in the source code.

Either the documentation should be fixed, or better, the code be fixed to handle the function case
