### ISSUE TITLE
When using dark theme, background flashes white before the dark background color appears. Only on Firefox

### ISSUE THREAD

**Issue by 0x199x** [primefaces/primevue#2380]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
I'm unable to get the sandboxes to work properly to provide you with a test case.  Both of the sandbox links keep giving me errors the moment I make a modification to the code. Here is a screen recording instead:

https://user-images.githubusercontent.com/89231731/160933176-b04d5d9e-0110-4ae3-8944-b8a080823c57.mp4

**Current behavior**
**EDIT**: Major corrections to this behavior.  Bug report has been thoroughly edited. 

When refreshing the page or navigating to another page in Firefox, the page flashes white (noticable when using dark theme) before the correct background color is set on the new/refreshed page.  It seems there are very specific circumstances when this does and doesn't happen.

Flashes: `App.vue`, `<style>html,body{background-color:var(--surface-ground);}</style>`
Flashes: `App.vue`, `<style>html,body{background-color:rgb(0,0,0);}</style>`
Flashes: `index.html`, `<head><style>html,body{background-color:var(--surface-ground);}</style></head>`
NO FLASH: `index.html`, `<head><style>html,body{background-color:rgb(0,0,0);}</style></head>`

**Expected behavior**
...

**Minimal reproduction of the problem with instructions**
* Make new empty project
* Import theme `primevue/resources/themes/lara-dark-purple/theme.css` in main.js
* Add `<style>html { background-color: var(--surface-ground); }</style>` to `App.vue`
* `npm run serve`
* Refresh Firefox a few times

**What is the motivation / use case for changing the behavior?**
...

**Please tell us about your environment:** Linux, VS Code open source, npm

**Vue version:** 3.0

**PrimeVue version:** 3.12.2

**Browser:** Firefox 98 - Issue is present, Vivaldi 5.1.2567 - Issue does not occur

**Comment by tugcekucukoglu** [comment]
Sorry for the late answer. Dark themes take some time to load it's obvious. But I didn't see this white blinking. Please try to use the latest PrimeVue version and if the problem still persists let us know.
