### ISSUE TITLE
Customizing DataTable Row Expansion icon

### ISSUE THREAD

**Issue by monipatel26** [primefaces/primevue#2388]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Can't customize icon to expand the row.

**Expected behavior**
customize expand functionality in a way that I can use button component or change icon.

**What is the motivation / use case for changing the behavior?**
I have a table in which specific rows have icon but for some rows I want to use button.

* **Vue version:** 3.0.0

* **PrimeVue version:** 3.9.1

**Comment by tugcekucukoglu** [comment]
These are available properties for this `expandedRowIcon` and `collapsedRowIcon`

**Comment by monipatel26** [comment]
With this update can I add button instead of icon? @tugcekucukoglu
