### ISSUE TITLE
Dialog not mounting white writing unit test

### ISSUE THREAD

**Issue by sankita15** [primefaces/primevue#2389]
```
<Dialog :show-header=false :visible="visible" >
    <div class="popover-content-container">
        <div class="popover-content-1">
          <span class="popover-header">Title1:</span>
           Description1
        </div>
      <br />
      <div class="popover-content-2">
    <div class="popover-header ">Title2:</div>
    Description 2
    </div>
    </div>
</Dialog>
```

I am using Dialog component from primevue library, and its rendering fine in browser. But when I write test using vue-test-utils mount function, I am getting below error while mounting the component.

**TypeError: Cannot read property 'config' of undefined

at Proxy.dialogClass**

Below is the test which is giving error:
```
it('should match snapshot for popover', () => {
        const component = mount(PopOver)

        expect(component.element).toMatchSnapshot();
    });
```

I raised this issue because after debugging I came to know that the primevue config is undefined for the dialogClass which is shown below:
```
dialogClass() {
            return ['p-dialog p-component', {
                'p-dialog-rtl': this.rtl,
                'p-dialog-maximized': this.maximizable && this.maximized,
                'p-input-filled': this.$primevue.config.inputStyle === 'filled',
                'p-ripple-disabled': this.$primevue.config.ripple === false
            }];
        },
```

I am using other primevue components also and is perfectly mounting fine with vue test-utils mount. This is the issue with primevue dialog component with vue test-utils

**Comment by tugcekucukoglu** [comment]
Please import PrimeVue in the test file and set the component like this:

```
const wrapper = mount(PopOver, {
	global: {
                plugins: [PrimeVue],
         }
});
```

**Comment by sankita15tw** [comment]
I tried this and it worked for me.

```
global: {
                mocks: {
                	['$primevue']: {
                	   config: {
                	     'ripple': true
                	   }
                	}
                }
         }

```

The issue was that $primevue(a global variable) was not getting set for the test and thats why we need to mock $primevue variable explicitly during mounting.

**Comment by nagisaando** [comment]
@sankita15tw Hello, this worked for me! Thanks a lot!

**Comment by Made-of-Clay** [comment]
@sankita15tw I agree with @nagisaando, your suggestion helped me get passed my blocker. Thanks for the tip!

**Comment by AndreyVialichka** [comment]
@sankita15tw Hi, worked for me to, big thanks
