### ISSUE TITLE
Arrow for OverlayPanel doesn't have borders in Lara Light Blue theme

### ISSUE THREAD

**Issue by develar** [primefaces/primevue#2390]
**Current behavior**

Enable Lara Light Blue on https://www.primefaces.org/primevue/#/overlaypanel and open OverlayPanel. Arrow is not properly designed (no border, I guess).

<img width="541" alt="Screenshot 2022-04-03 at 18 19 09" src="https://user-images.githubusercontent.com/350686/161437567-ce01a593-c091-4b7e-beb3-b412b65b0a5f.png">

**Expected behavior**
No such issues for Saga Light Blue.

<img width="520" alt="Screenshot 2022-04-03 at 18 19 48" src="https://user-images.githubusercontent.com/350686/161437588-a4770b1e-8b9a-4c73-885d-af65b62eec01.png">

**Please tell us about your environment:**
macOS.

* **Vue version:** 3.X
3.2.31

* **PrimeVue version:** 3.4.X
3.12.4

* **Browser:** 
Chrome, Safari.

**Comment by tugcekucukoglu** [comment]
You could use different background-color and also please check [elevation settings](https://www.primefaces.org/primeflex/elevation)

**Comment by develar** [comment]
Could you please answer? I fixed the issue on my side, I simply bought theme designer.
But I also worry about PrimeVue adoption, so, I want to be sure that it is not a bug. It is not my project only, it is your official demo :)
