### ISSUE TITLE
Feat: `disabled` and `readonly` for `InputNumber`

### ISSUE THREAD

**Issue by DreadIsBack** [primefaces/primevue#2394]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Description**
Please implement `disabled` and `readonly` properties for `InputNumber` (just how it works in `InputText`).
Thank you!

**Comment by tugcekucukoglu** [comment]
Please check this [example](https://codesandbox.io/s/modest-saha-42f09c?file=/src/InputNumberDemo.vue). It seems InputNumber already have these properties.

**Comment by xxxKOTxxx** [comment]
> Readonly for InputNumber has a bug: you can edit the value.

Confirm. 
STR:
Create readonly input with value equal to empty string.
Focus and unfocus input
@valueChange shows that input value changed to null
Created a [separate issue](https://github.com/primefaces/primevue/issues/8051)
