### ISSUE TITLE
New `exportFooter` property for Exportable DataTable

### ISSUE THREAD

**Issue by Trinvm1997** [primefaces/primevue#2395]
Do we have option for exporting datatable with both header and footer ?
Currently I don't see any options for footer exporting.

**Comment by tugcekucukoglu** [comment]
Issue is not clear. Are you asking `exportFooter` property like `exportHeader` or Column header/footer templating support for exportable DataTable?

**Comment by Trinvm1997** [comment]
sorry for late response. What I am asking for is exporting the footer of datatable along with header and body.
