### ISSUE TITLE
Attribute "position" is missing in ConfirmationOptions.d.ts

### ISSUE THREAD

**Issue by ramiswailem** [primefaces/primevue#2408]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When trying to add 'position' attribute in the literal object passed to require method, vscode will complain that this attribute is not present in ConfirmationOptions.d.ts

**Comment by tugcekucukoglu** [comment]
Duplicate [#2381 ](https://github.com/primefaces/primevue/issues/2381)
