### ISSUE TITLE
Galleria: change activeIndex to 0 not emitted

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2409]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/frosty-dawn-9vumgp?file=/src/CheckboxDemo.vue

**Current behavior**
If you click the image with index 1 or 2, activeIndex gets updated.
If you click back on the image with index 0, activeIndex should get 0. But it does not change.
The Gallery Component itself updates, but it does not emit the update for activeIndex.

**Expected behavior**
activeIndex should get 0, if I click on the first thumbnail.

* **Vue version:** 3.X

* **PrimeVue version:** 3.4.X

**Comment by tugcekucukoglu** [comment]
Please try this

`<Galleria :value="images" v-model:activeIndex="activeIndex" @update:activeIndex="changeIndex">`
