### ISSUE TITLE
When changing the inputMask `mask` prop the redered mask is not updated

### ISSUE THREAD

**Issue by tavoohoh** [primefaces/primevue#2429]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
I am currently using the `InputMask` component along with a dropdown to display a PhoneField. The dropdown allows you to choose the country and the InputMask to write the phone number. When the user selects a country, the InputMask mask is configured, internally the prop is updated with the new mask but the render remains the previous mask.

**Expected behavior**
Changing the value passed to the "mask" prop should update the input and its mask

Here is a [pull request](https://github.dev/tavoohoh/primevue/tree/bugfix/mask-changes) with the fix. Just add a couple of lines of code and abstract the mount to a function to reuse it in a watch

**Comment by tugcekucukoglu** [comment]
Thanks for the PR.

I have tried to replicate the issue but it seems working. Please send us a codesandbox sample so we can clearly understand the problem.

**Comment by tugcekucukoglu** [comment]
How can we replicate this issue?
