### ISSUE TITLE
Feat: Datatable header cell tooltip

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2436]
### Feature request: Add tooltip to table cell (when sorting is enabled)

**Current behavior**
I am using tooltip by passing it to #header slot. (tooltip will be enabled when small area with text will be hovered)

**Expected behavior**
 I'd like to add tooltip on the whole cell but at this moment there is no way to pass it to th element.

**Comment by tugcekucukoglu** [comment]
Please check this [example](https://codesandbox.io/s/intelligent-roman-uyznb8?file=/src/DataTableCrudDemo.vue:1221-1239) that tooltip given the span element. 

If issue is still persist, please reopen this issue with a codesandbox link.
