### ISSUE TITLE
InputNumber @input not triggered when cut the text

### ISSUE THREAD

**Issue by bilal-app4legal** [primefaces/primevue#2437]
Hi,

just creating normal input number "primevue.inputnumber" with @input="any_function()"
if i start writing in the input "any_function" is called but in case if i select a part of the text and right click and click cut it will not trigger @input and any_function is not called, note onpaste it is called and working normally but on right click cut or delete not calling it.

Thnaks,

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
