### ISSUE TITLE
Add button based on condition for Datatable expand

### ISSUE THREAD

**Issue by monipatel26** [primefaces/primevue#2440]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
Datable expand does not support adding button.

**Expected behavior**
Should allow:
- adding button instead of icon
- add button conditionally
![Datatable example](https://user-images.githubusercontent.com/8273099/162834473-631dbf66-aeac-4ede-971d-417ad78eb889.png)

* **Vue version:** 3.0.0

* **PrimeVue version:** 3.12.4

**Comment by tugcekucukoglu** [comment]
We're currently not considering to add this feature since there is not enough demand from the community.

Thanks,
