### ISSUE TITLE
Customizing paginator in datatable primevue

### ISSUE THREAD

**Issue by Deepak2985** [primefaces/primevue#245]
Can paginator be customized in primevue datatable?

**Comment by wanglin86769** [comment]
According to the source code in DataTable.vue, my understanding is that the paginator can be customized by props of paginatorPosition, paginatorTemplate, pageLinkSize, rowsPerPageOptions, currentPageReportTemplate.

Things can alse be added to the left or right part by using template:
<template #paginatorLeft>
</template>
<template #paginatorRight>
</template>

**Comment by cagataycivici** [comment]
Yes, it has templating and also the order of built-in elements can be configured with paginatorTemplate.

**Comment by cagataycivici** [comment]
By the way, forum would be the better place for questions;

https://forum.primefaces.org/viewforum.php?f=110
