### ISSUE TITLE
Feature Request | Voice Message

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#2452]
I think the following components will be very helpful:

**Recording a voice message (with animation as in a telegram, for example)**
Example:
![image](https://user-images.githubusercontent.com/16963395/163184732-58a3790c-5236-4499-a343-7981e9e8e1d7.png)
For the component itself to give a ready-made audio file that could be processed
And the ability to specify an audio file to her and she will allow you to listen to it

**Component for working with audio\video\media (play, pause, etc.)**

**Integration of lottie-player and its animations**

**pdf\doc\xml viewer etc**

**Map (OSM)**

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
