### ISSUE TITLE
BlockUI doesn't remove div

### ISSUE THREAD

**Issue by adhasahar97** [primefaces/primevue#2453]
I'm submitting a ... (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

Unblocking BlockUI doesn't remove the transparent div. 

![image](https://user-images.githubusercontent.com/66990673/163311082-c81488b9-62a9-451d-9486-2f5816fdc857.png)

Had to use this method to remove the div manually
`document.querySelectorAll(".p-blockui").forEach((el) => el.remove());`

Using PrimeVue v3.12.5

**Comment by tugcekucukoglu** [comment]
Please check this [example](https://codesandbox.io/s/70ezvh)
