### ISSUE TITLE
Tooltip on focus and on hover

### ISSUE THREAD

**Issue by minzdrav** [primefaces/primevue#2455]
[X] feature request 

https://primefaces.org/primevue/tooltip

**Current behavior**
You can show tooltip on hover OR on focus.

**Expected behavior**
Show tooltip on hover for devices with mouse/touchpad and show on click for devices with touchscreen(phones, tablets, PC with touchscreen).

**Minimal reproduction of the problem with instructions**
Go to https://primefaces.org/primevue/tooltip
You can't see tooltip in "Positions" examples on mobile devices.
You can't see tooltip in "Focus and Blur" example on mouse hover.

**What is the motivation / use case for changing the behavior?**
Hover is expected behavior for devices with mouse, click is expected behavior for touchscreens. Right now we can't implement expected tooltip behavior for all devices.

* **Vue version:** 3

* **PrimeVue version:** 3.12.4

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Duplicate [#2254 ](https://github.com/primefaces/primevue/issues/2254)

**Comment by minzdrav** [comment]
Hi @tugcekucukoglu 
Issue https://github.com/primefaces/primevue/issues/2254 is closed.
Problem is not resolved. Why you closed both issues? Please open original or this one.

**Comment by tugcekucukoglu** [comment]
Please first read the comments for [#2254 ](https://github.com/primefaces/primevue/issues/2254). As you know, hover and focus behaves different desktop and mobile. So the other comments gives a solution.

**Comment by minzdrav** [comment]
@tugcekucukoglu 
I double checked the comments. Unfortunately, there is no solution for my issue. Also, please read comments from mitow7821. He is asking for universal solution too.

I'll try to explain my issue again. I'm interested in universal solution that will work for both touch and mouse users. Show tooltip on mouse hover and on touch event. One code - both behaviors. 
For example please look at bootstrap tooltip: https://getbootstrap.com/docs/4.0/components/tooltips/
You can hover and touch. Tooltip is working for both mouse and touch users without issues.

**Comment by s-o-l-b** [comment]
I would also like a solution to this. It should be possible to show the tooltip on desktop when you focus or hover over it.

**Comment by minzdrav** [comment]
Hi @s-o-l-b 
I'm using vue-tippy alpha: https://www.npmjs.com/package/vue-tippy/v/6.0.0-alpha.63
It's pretty good.

**Comment by codeflorist** [comment]
This is actually the default behaviour of any frontend library i know - and logically so. Of course i want tooltips to work on all devices by default.

On a sidenote: Tooltips do not work on PrimeVues own page, when browsing with touch devices, and thus appear broken.
