### ISSUE TITLE
Add menubar-left and menubar-right slots to Menubar

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#246]
How can I add a logo image on the leftmost of the PrimeVUE menubar? Like the logo image on the topleft of this github website.

**Comment by cagataycivici** [comment]
Using this as a new request to add two new slots, currently you can use the default slot and it will be rendered at the right side, you can move it to left with css though.

See the sample at

https://primefaces.org/primevue/showcase/#/menubar

```html
<Menubar :model="items">
    <img src="logo.png"/>
</Menubar>
```

```css
.p-menubar .p-menubar-custom {
   float: left;
}
```
