### ISSUE TITLE
Add overlay to the parent component when Progress Spinner is shown

### ISSUE THREAD

**Issue by j-meds** [primefaces/primevue#2461]
Would be nice if there is an "overlay" property on the Progress Spinner. This property if true would expand an overlay the parent's element container and a center the spinner when it is shown. Image shows the overlay over a sign in form.

![image](https://user-images.githubusercontent.com/12689117/163894996-4fca3f8b-bb7a-4664-ade9-e0caf8c9ac14.png)

**Comment by j-meds** [comment]
I'm not getting the option to submit as enhancement ? I've already done most of the work for this on a another project and have confirmed that it works on several elements. I can submit a PR as well lmk, if this is a feature that will be approved.

**Comment by 4KDA** [comment]
That would be good. Or create a separate component

**Comment by mertsincan** [comment]
Hi,

After fixing https://github.com/primefaces/primevue/issues/2486, I think you can use blockUI+ProgressSpinner.
Exp; https://www.primefaces.org/primereact/blockui/ ('Template')

**Comment by j-meds** [comment]
@mertsincan Thanks I'll give this a try on a sandbox!

**Comment by breizhwave** [comment]
@j-meds  did you find solution for display of  template property in primevue blockUI ? thks

**Comment by richardkshergold** [comment]
I would like this too - is there a way of doing it?

**Comment by richardkshergold** [comment]
this helped me https://stackoverflow.com/questions/53681904/how-can-i-overlay-a-progressspinner-in-primeng

**Comment by wkrick** [comment]
@richardkshergold I just added a comment to the stackoverflow you linked showing how I toggle BlockUI and ProgressSpinner at the same time.  It seems to work pretty well so far for what I'm doing.
