### ISSUE TITLE
I can't pass a custom theme in the Nuxt config

### ISSUE THREAD

**Issue by yesiddg** [primefaces/primevue#2473]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**

Option to pass a custom Nuxt theme is not available currently. An example below.

`
primevue: {
    theme: 'assets/styles/primevue-theme.scss',
    ripple: true,
    components: []
  },
`

**Expected behavior**

I should be able to pass a css/scss/stylus file from my project to the built-in module for Nuxt js.

**Minimal reproduction of the problem with instructions**

1. Pass a path instead a theme-name and it fails.

**What is the motivation / use case for changing the behavior?**

It's very difficult to add customizations to the components.

**Comment by dzcpy** [comment]
Same issue, it shows the following error:
`Unexpected token '<'`

**Comment by tugcekucukoglu** [comment]
`primevue` options in `nuxt.config.js` defines only PrimeVue themes not a custom theme. To avoid a confusion, we could suggest to [https://nuxtjs.org/docs/directory-structure/nuxt-config#css](https://nuxtjs.org/docs/directory-structure/nuxt-config#css)

**Comment by dzcpy** [comment]
@tugcekucukoglu Yes I can understand, it would work if it's set in the css config. But the default theme is also loaded, there's duplication

**Comment by yesiddg** [comment]
@dzcpy @tugcekucukoglu  Yeah, It was de reason I created the PR. Have a theme with saga-blue and the theme generated by primevue designer. WTF. I will create a fork of primevue and set my changes, thanks!

**Comment by lacoste-sochi** [comment]
no custom theme =((( 

You just need to install not as a module, but as a plugin ...

![image](https://user-images.githubusercontent.com/42961050/193693258-71777320-40a5-4239-9835-71c724ec9e65.png)
