### ISSUE TITLE
visible prop of Dialog uses v-if rather than v-show internally

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#248]
It is not clear to me if there are some performance considerations for implementing dialog visibility using v-if rather than v-show internally. The problem is, when I try to draw a QR code using canvas tag in a Dialog as follows, the getElementById() always returns null, even if it is called in the nextTick() after dialog visibility is set to true, because getElementById is always called before the dialog is actually rendered. So I have to find other solutions to draw QR code in a dialog.

`showQrCodeInDialog() {
  displayQrCodeDialog = true;
  let canvas = document.getElementById('canvas');
 
  QRCode.toCanvas(canvas, 'sample text', function (error) {
    if (error) console.error(error)
    console.log('success!');
  }) 
}`

**Comment by fairking** [comment]
You can try to attach an event and render the QR code when the event triggers.
Something like that:
```
<Dialog @show="onDialogShow()" ... >
```
```
methods: {
    onDialogShow() {
        let canvas = document.getElementById('canvas');
    }
}
```

**Comment by wanglin86769** [comment]
The @show event works, thanks very much.

**Comment by cagataycivici** [comment]
v-if is used for performance, @show will be a solution.
