### ISSUE TITLE
InputNumber with min/max - value on buttonclick

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2485]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/nervous-spence-dpc90l?file=/src/InputNumberDemo.vue

**First issue:**
**Current behavior**
Clicking on the up (or down) button on Inputnumber with min/max prop behaves strange.
Sometime it increases the value and sometimes not.

**Expected behavior**
The Inputnumber **without** min/max prop increases the value on each click and resets to the modelValue on blur.
Adding min/max should not change the behaviour of the component.
The Inputnumber **with** min/max prop should behave the same way.

**Second Issue**
The blur on both InputNumber components does not trigger the update event on the modelValue.
On blur: the input's value is resetted, but someOtherVal is not.
Even if I add @blur handler, someOtherVal does not reset to modelValue.

**Notes**
I do **not** use v-model on purpose.
The value is readonly. The setter is a function that needs to change some other values simultaneously when the value changes.

**Minimal reproduction of the problem with instructions**
see Codesandbox link
Click the "up" button on "modelValue with MinMax" multiple times.
Sometimes the value will increase and sometimes not.

* **Vue version:** 3.X

* **PrimeVue version:** 3.12.X

**Comment by tugcekucukoglu** [comment]
Please check the difference between `v-model` and `modelValue`.

In second example modelValue never updates.

```
setVal2(newVal) {
      this.val2 = newValue;
      this.someOtherVal2 = newVal;
}
```

**Comment by 3zzy** [comment]
I have the same question basically but for InputSwitch. Everything works when using v-model but I don't want to use it for a reason. Instead I'd like to set the initial value using `modelValue=myVar` and update the variable `onChange` or `update:modelValue` so it works basically the same but without v-model. Haven't found a way to make it work yet.
