### ISSUE TITLE
How does the Datatable component trigger the filtering function through code?

### ISSUE THREAD

**Issue by iran1024** [primefaces/primevue#2488]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Expected behavior**
 
Can trigger the filters by code.

**What is the motivation / use case for changing the behavior?**

I want to trigger the filtering function through code, such as automatically filtering a column after the page is loaded.

**Please tell us about your environment:** Win 11, VS Code, NPM

* **Vue version:** 3.2.13

* **PrimeVue version:** 3.12.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tugcekucukoglu** [comment]
This is not a valid issue ticket. Please use forum or Discord channel for your questions.

In this [example](https://codesandbox.io/s/wt509f?file=/src/DataTableFilterDemo.vue:13395-13419) filtered values is null, as you can see it could be modified.
