### ISSUE TITLE
How to apply style on a popup component, like Dropdown, etc..

### ISSUE THREAD

**Issue by iran1024** [primefaces/primevue#2489]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Expected behavior**
Can set the style of  a popup component, like Dropdown, MultiSelect, etc...

**Please tell us about your environment:** Win11, VS Code, NPM

* **Vue version:** 3.2.13

* **PrimeVue version:** 3.12.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tugcekucukoglu** [comment]
There is `panelClass` property and templating slots for the styling components like Dropdown and MultiSelect. Also you can find an example in showcase demo with scoped styling.
