### ISSUE TITLE
Ability to programmatically control editable cells

### ISSUE THREAD

**Issue by mauserzjeh** [primefaces/primevue#2490]
Hi!

Is there a way to programmatically set a cell in editing mode in a datatable? I have a datatable with an "Add new row" button. After the button is clicked I add a new row to the datatable which appears correctly, but the user will still have to click on a cell in this new empty row. What I would like to achieve is that when the new row is added, one of the cell's of this new row is automatically in edit mode.

Is there a way to do this? I tried to search for documentation, examples or closed issues which could provide a solution but I haven't found any.

Thanks!

**Comment by cagataycivici** [comment]
There is no known way, converting this ticket to an enhancement, thank you.

**Comment by sean-ccm** [comment]
I noticed this was closed, but I don't see a correlating commit for an enhancement. The use case would be to allow certain columns to remain un-editable either due to props/functions while the other columns to still be editable.
