### ISSUE TITLE
DataTable Paginator page syncing edge case

### ISSUE THREAD

**Issue by AndreasNasman** [primefaces/primevue#2494]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**CodeSandbox Case (Bug Reports)**
https://www.primefaces.org/primevue/datatable/lazy

**Current behavior**
Being on page >= 2 on a lazy-loaded DataTable, updating `:value` (through a filter, e.g.) makes the DataTable Paginator reset to page 1, but the items displayed are from page >=2. See video:

https://user-images.githubusercontent.com/17124245/165038780-fd7fa737-0b53-438e-aaec-0576180e46b9.mp4

**Expected behavior**
The paginator page should always be in sync with the data displayed.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Visually indicating the wrong page number can be confusing to the user and cause other unintentional behavior.

**Please tell us about your environment:** Not relevant

* **Vue version:** 3.2.33

* **PrimeVue version:** 3.12.5

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Duplicate [#2253 ](https://github.com/primefaces/primevue/issues/2253)

**Comment by AndreasNasman** [comment]
Saw #2253 but there was no description in it. Please add one to better specify what the issue is about.
