### ISSUE TITLE
When the content is folded, the tooltip appears in an incorrect position

### ISSUE THREAD

**Issue by iran1024** [primefaces/primevue#2495]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/infallible-goldberg-bgzd8n?file=/src/App.vue

**Current behavior**
When the content style is set to: 'white-space: nowrap;overflow: hidden', the emerging position of the v-tooltip is still in the middle of the content before the style is set.

**Expected behavior**
When the overflow part of the text is folded, v-tooltip should appear in the correct position.

**Minimal reproduction of the problem with instructions**
When the mouse crosses an element, use v-tooltip to display its content. Please pay attention to trying on the element whose content is folded.

**Please tell us about your environment:** Win11, VSCode, NPM

* **Vue version:** 3.2.13

* **PrimeVue version:** 3.12.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tugcekucukoglu** [comment]
`white-space: no-wrap` breaks the width. In this example the width is larger than 124px. Tooltip calculates the final width and try to show itself the middle of the span. So this is expected behavior. It's a demo bug.
