### ISSUE TITLE
Dropdown search character problem

### ISSUE THREAD

**Issue by macingili** [primefaces/primevue#25]
Screen pictures

![trError2](https://user-images.githubusercontent.com/28981367/61708242-04734780-ad55-11e9-802c-8815bf7048bb.png)
![trError3](https://user-images.githubusercontent.com/28981367/61708244-04734780-ad55-11e9-8c10-9846f532d97c.png)
![trError4](https://user-images.githubusercontent.com/28981367/61708246-04734780-ad55-11e9-8710-c793d720d32d.png)
![trError5](https://user-images.githubusercontent.com/28981367/61708247-050bde00-ad55-11e9-9fe6-82a61b2123c1.png)
![trError6](https://user-images.githubusercontent.com/28981367/61708249-050bde00-ad55-11e9-922b-3529aac11b40.png)
![trError](https://user-images.githubusercontent.com/28981367/61708250-05a47480-ad55-11e9-8495-fc5d17718c5b.png)

**Comment by cagataycivici** [comment]
Issue is not clear, please provide more information and a sample code.
