### ISSUE TITLE
MegaMenu subItems 'to' route ' is not working

### ISSUE THREAD

**Issue by zongjingcom** [primefaces/primevue#2501]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

Current behavior
When configuring a 'to' on a menu subitem, the browser console report error:"The .native modifier for v-on is only valid on components but it was used on 'a'"

Expected behavior
Menu not breaking and navigating to configured 'to' route.

Please tell us about your environment:

Vue version: 2.6.14
PrimeVue version: 2.9.

Browser: All

Suggested Fix:
in MegaMenu on line 30:
@click.native="onLeafClick($event, item, navigate)"
should be:
@click="onLeafClick($event, item, navigate)"
Resolves the issue for me.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/fe8f56ec4ab21516dc9647caa7195ac9a93a87b8

**Comment by Ttito19** [comment]
https://github.com/primefaces/primevue/issues/4056 please
