### ISSUE TITLE
Can the DataTable's header be fixed when I scroll down the page?

### ISSUE THREAD

**Issue by iran1024** [primefaces/primevue#2503]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
No way to fix the DataTable's header was found.

**Expected behavior**
When I scroll down the page, the header of the DataTable can be fixed at the top of the page.

**Please tell us about your environment:**

* **Vue version:** 3.X

* **PrimeVue version:** 3.12.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tugcekucukoglu** [comment]
Please check the documentation before create an issue. [https://www.primefaces.org/primevue/datatable/scroll](https://www.primefaces.org/primevue/datatable/scroll)

**Comment by iran1024** [comment]
Hello, you misunderstood what I mean. I just want to fix the header and don't want to set the content scrolling of datatable.

**Comment by tugcekucukoglu** [comment]
The `scrollable` property of the DataTable does this. `thead` could be positioned as sticky.

**Comment by iran1024** [comment]
I'm sorry that I can't express myself accurately. I want the content in the DataTable is not allowed to scroll, but the header is fixed when scrolling the page.
