### ISSUE TITLE
 why can't use right mouse click for copy text on DataTable content

### ISSUE THREAD

**Issue by Woodyjtr** [primefaces/primevue#2508]
when click right on mouse for copy text in inputNumber tag  on dataTable it not work
![Screen-Recording-2565-04-25-at-20 47 21-2](https://user-images.githubusercontent.com/56378216/165685747-71e0e7e1-3243-4b3f-b9d0-f709d7db96a5.gif)

**Comment by tugcekucukoglu** [comment]
It's an InputNumber issue. Duplicate [#2437 ](https://github.com/primefaces/primevue/issues/2437)

Thank you.
