### ISSUE TITLE
Calendar resize listener bug

### ISSUE THREAD

**Issue by cm-tigeen** [primefaces/primevue#2509]
Hi Support Team,

Calender not working inside web view url in the hybrid application.

We are using basic form which includes four inputs & one calendar input. While focus input field after move to next, calender not showing datepicker popup.

<Calendar ref="publishDateCalendar"  class="startdate smallCalendar" :manualInput="isMobile ? false : true" :touchUI="isMobile ? true : false" name="publishDate" @focus="publishDateSelected" v-model="data.publish_date" :showButtonBar="true" required="true" autocomplete="off" :class="{'p-invalid': submitted && !data.publish_date}"/>

PFA, Please check shared video screen recording.

https://user-images.githubusercontent.com/77827545/165733120-73a925f8-209e-400a-98e9-39cbe0006421.mp4

**Comment by tugcekucukoglu** [comment]
Hi,

Which version are you using PrimeVue 2 or 3? I cannot find it in the your description.

**Comment by cm-tigeen** [comment]
Hi,

Thank you for your reply. We are using  primevue (3.12.0).
