### ISSUE TITLE
The filter field of the DataTable filter cannot be correctly obtained from the value object

### ISSUE THREAD

**Issue by iray1024** [primefaces/primevue#2511]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When the multiselect component is used as the column filter of the DataTable, the value field can only be set as the filter field, otherwise it cannot be filtered, but in this way, more data cannot be obtained in #value. For example, I tried to obtain the filter fields "username" and user's Avatar in #value.

**Expected behavior**
Value can be set to be similar to [{"Id": 1, "username": "XXX", "Avatar": "Base64"}], and the filter field can be correctly applied in the DataTable to which it belongs.

**Minimal reproduction of the problem with instructions**
Try to use MultiSelect as a filter. When an option is selected, the username and avatar can be displayed in value, and the filtering function of DataTable works normally.

* **Vue version:** 3.2.33

* **PrimeVue version:** 3.12.5

* **Browser:**  Chrome

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. If the issue still persists with the latest version, please create a new issue with a reproducer link.
