### ISSUE TITLE
Floating label dropdown with integer zero value

### ISSUE THREAD

**Issue by zortext** [primefaces/primevue#2515]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/quiet-cache-0nkdwl?file=/src/App.vue

**Current behavior**
Floating labels do not work if the option key value is `Integer` and `0`.  
`p-inputwrapper-filled` class is not applied for the wrapper

**Expected behavior**
Label should float  at any value other than `undefined` and `null` 

**Minimal reproduction of the problem with instructions**
See codesandbox

**Please tell us about your environment:**
Windows 11, Vue3 on Vite, NPM, VS Code

* **Vue version:** 3.X
3.2.31

* **PrimeVue version:** 3.12.X
3.12.4

* **Browser:** [all ]

**Comment by zortext** [comment]
Applied conditional class for quick fix:

`<Dropdown v-model="value" :class="{ 'p-inputwrapper-filled': value === 0 }"/>`

**Comment by tugcekucukoglu** [comment]
`optionValue` only accepts string or function not number.

Thank you.
