### ISSUE TITLE
OrderedList highlight not reacting to v-model:selection changes

### ISSUE THREAD

**Issue by helmi77** [primefaces/primevue#2518]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request 
[ ] support request
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/interesting-hill-yp2b8h

**Current behavior**
When the `v-model:selection` of an `OrderedList` changes the item(s) are not highlighted correctly.

**Expected behavior**
The items added to the `v-model:selection` should be highlighted in the list.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/interesting-hill-yp2b8h

* **Vue version:** 3.2.31

* **PrimeVue version:** 3.12.6

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Please check the solution [https://codesandbox.io/s/loving-wave-zm14ng?file=/src/OrderListDemo.vue:1457-1524](https://codesandbox.io/s/loving-wave-zm14ng?file=/src/OrderListDemo.vue:1457-1524)
