### ISSUE TITLE
TabView: lazy + vue-router

### ISSUE THREAD

**Issue by itprodavets** [primefaces/primevue#2519]
Dear

When you click on the tab, all tabs are loaded. it used to work for me, but now I transferred this piece of code to a new project and this problem happens 

It is work okay in version => 
   Vue version: 3.0.5
   PrimeVue version: 3.6.0

```
[x] bug report
[ ] feature request
[ ] support request
```
CodeSandbox Case (Bug Reports)
https://codesandbox.io/s/async-browser-csy7hj
![image](https://user-images.githubusercontent.com/5946414/166299918-7fd3d88e-7000-45e7-aeda-a5810b034577.png)

Vue version: 3.2.25
PrimeVue version: 3.12.5
Browser: all

**Comment by cagataycivici** [comment]
TabMenu is specifically created for cases like this, please use TabMenu instead of TabView when you load children lazily with a router.
