### ISSUE TITLE
Datatable time filter with range issue when the From Date field is left blanked

### ISSUE THREAD

**Issue by daniel-pk** [primefaces/primevue#2520]
If you have a PrimeVue PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 1 business hour.

If you do not have a PrimeVue PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~1-4 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
url: https://www.primefaces.org/primevue/datatable

**Current behavior**

The goal is to open a date filter where I can define a date range (From Date and To Date) where we can input either both fields either only one of them
The bug occurs when we want to input only the To Date  field while the From Date field is left blank.
1) Click on the Date filter icon.
2)
![image](https://user-images.githubusercontent.com/99213432/166473154-f3bdeb6a-54c8-4630-812b-2f4563c9fb53.png)
3) click on Apply
The Date filter icon is not marked as Filtered (painted in blue)
![image](https://user-images.githubusercontent.com/99213432/166474697-3a31fc3b-f848-42a8-afdc-d7594e5a9a32.png)

Note that if I input the From Date field  but leave the To Date field blank, the filter icon works as expected

**Expected behavior**

The Date filter icon should be painted in blue after step 3.

**Please tell us about your environment:**
Mac - npm

* **Vue version:** ^3.2.29
Vue latest with Vite latest

* **PrimeVue version:** ^3.8.2

* **Browser:** Chrome latest

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
