### ISSUE TITLE
InputText and Textarea duplicating custom class(es) in DOM element

### ISSUE THREAD

**Issue by mrt-prodz** [primefaces/primevue#2522]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/beautiful-pond-wy082c

**Current behavior**
Element has duplicated custom class name(s).

**Expected behavior**
Element should assign custom class name(s) only once.

**Minimal reproduction of the problem with instructions**
Add an InputText, InputNumber or Textarea with a custom class to your project then inspect the element in a browser, the input element has your custom class(es) twice.

Same issue could be observed in PrimeVue documentation, for example : https://www.primefaces.org/primevue/inputtext
Inspect the input for the **Invalid** example of an InputText, the class `p-invalid` will be assigned twice to the input element.

* **Vue version:** 3.2.31

* **PrimeVue version:** 3.12.2

* **Browser:** Chrome 101.0.4951.41 | Firefox 94

**Comment by mb-mysterdev** [comment]
Hello, 

I have cloned the project : 
https://github.com/primefaces/primevue.git

I went in src/components/inputtext/InputText.vue and I added 
`    inheritAttrs: false,
`

that fixed the inputtext and inputNumber Bug

For the textarea I did the same thing by patching 
 src/components/textarea/Textarea.vue 
On export default i added :
`    inheritAttrs: false,
`

Now everything is working fine but I have to confirm with Primevue team if it doesn't have bad consequences.

Note: I checked and it does not affect the transmission of other attributes such as aria etc ...

Thanks for reporting the bug
