### ISSUE TITLE
Bug: Accordion using dynamic tabs and `:multiple="true"` keep incorrect tabs expanded when changed

### ISSUE THREAD

**Issue by ched-dev** [primefaces/primevue#2524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Bug behavior is reproduced at https://codesandbox.io/s/dreamy-architecture-mbej6m?file=/index.html

**Current behavior**
When I have an Accordion with `:multiple="true"` using dynamic tabs, the tab will stay open by index instead of keeping state with specific item.

**Expected behavior**
I expect the accordion to keep items open by the specific item instead of index. This is because if I add a new item, I want each item to keep its state.

**Minimal reproduction of the problem with instructions**
1. Expand the first item in the Accordion
1. Click the Add Tab button
1. The first tab will remain open even though the item has changed

https://codesandbox.io/s/dreamy-architecture-mbej6m?file=/index.html

https://user-images.githubusercontent.com/73146636/167048924-4969629a-6087-469c-8aa2-ef4e2f651b28.mov

**What is the motivation / use case for changing the behavior?**
We use the Accordion to show a list of events. When a new event occurs, we add the event as a new tab. If a tab was open at a specific index, it will now display it's open state based on it's new index, not the specific item.

**Please tell us about your environment:**
See codesandbox environment

* **Vue version:** 3.X
Vue@next via unpkg script src

* **PrimeVue version:** 3.12.X
Version 3 via unpkg script src

* **Browser:**
Chrome 100.0.4896.127 Mac OS 12.0.1

**Comment by tugcekucukoglu** [comment]
`activeIndex` can be controlled when a new tab is added. Please check this [example](https://codesandbox.io/s/lively-grass-mn4bko?file=/index.html:4103-4136)

**Comment by ched-dev** [comment]
I still think the expected behavior when using `:multiple="true"` is that open tabs stay open and a new tab can start closed. I know you can add code to make that happen, but the default behavior right now feels like a bug. I shouldn't have to add code to "fix" the behavior.
