### ISSUE TITLE
Sub-items in PanelMenu does not receive the `router-link-active` class

### ISSUE THREAD

**Issue by LorianColtof** [primefaces/primevue#2528]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

A sub-item in PanelMenu never receives the `router-link-active` class, which causes it to not be highlighted even though the route matches in a non-exact way.

**Comment by tugcekucukoglu** [comment]
[https://github.com/primefaces/primevue/blob/master/src/components/panelmenu/PanelMenuSub.vue#L6](https://github.com/primefaces/primevue/blob/master/src/components/panelmenu/PanelMenuSub.vue#L6)

I saw the PR [#2529 ](https://github.com/primefaces/primevue/pull/2529) but I could not replicate the issue. Could you create a codesandbox demo?

**Comment by LorianColtof** [comment]
Yes, here you go: https://codesandbox.io/s/reverent-almeida-etrj2z

**Comment by LorianColtof** [comment]
Any update on this?
