### ISSUE TITLE
Improve DataTable ContextMenu Styling

### ISSUE THREAD

**Issue by Fanmade** [primefaces/primevue#253]
When the context menu is closed again, no event is thrown.
So if you right-clicked on a row and click somewhere else to hide the context menu again, the row will stay highlighted until you reload the page.
![image](https://user-images.githubusercontent.com/2896491/78104015-a4a66380-73ee-11ea-83ea-eb4aacce0669.png)
![image](https://user-images.githubusercontent.com/2896491/78104167-e9ca9580-73ee-11ea-87e6-7a2689e1b660.png)

It would be great to have an event like "onRowContextMenuClose" to be able to remove the selection of that row again.

**Comment by cagataycivici** [comment]
Also please add new "contextMenu" prop so that the rows can become focusable in 1.2.0.
