### ISSUE TITLE
Multiselect doesn't work inside ColumnFilter due to overlay dissapears

### ISSUE THREAD

**Issue by jmverges** [primefaces/primevue#2531]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
Please demonstrate your case at CodeSandbox by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://codesandbox.io/s/primevue-3-issue-template-ip3vm
https://codesandbox.io/s/primevue-3-typescript-issue-template-z1f6e2
https://codesandbox.io/s/primevue-2-issue-template-dw7jd7

**Current behavior**
I have a MultiSelect inside ColumnFilter inside DataTable. When I click a value inside the multiselect the ColumnFilter (overlay) disapears and I need to click again to hit Apply button.

**Expected behavior**
To be able to control if the overlay from the column filter will dissapear when clicking outside or not. Am I missing some property somewhere?

**Minimal reproduction of the problem with instructions**
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/2902073/167473126-d876d692-20cd-47c3-bdbd-2047d5668111.png">
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2902073/167473206-0354a76c-57ae-44d9-aa0d-9ff0140b6e97.png">

**Comment by tugcekucukoglu** [comment]
Without codesandbox example it is really hard to replicate this issue.

**Comment by jmverges** [comment]
@tugcekucukoglu many thanks. I created https://codesandbox.io/s/boring-babbage-jjfw4s and I cannot replicate it neither so must be something in my side. Closing for now.

**Comment by tugcekucukoglu** [comment]
Sorry, I really didn't catch that the issue. Are you having a problem with importing DataTable component?

**Comment by jmverges** [comment]
@tugcekucukoglu yes when doing primevue/datatable/DataTable.vue

**Comment by tugcekucukoglu** [comment]
```
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';

app.component('DataTable', DataTable);
app.component('Column', Column);
```

This is for the global component registration said as in PrimeVue documentation. For more information about component registration please check [Vue docs](https://vuejs.org/guide/components/registration.html)

**Comment by jmverges** [comment]
@tugcekucukoglu thanks but that doesn't resolve my problems.
I have a "patched" version of DataTable.
The problem resides in not being able to do 
 import DataTable from primevue/datatable/DataTable.vue (doesn't matter if patched or not)

**Comment by tugcekucukoglu** [comment]
Sorry, It's really hard to replicate this issue without seeing any code example. A repo or a codesandbox sample really could help to understand this problem. Until that time closing this issue.
