### ISSUE TITLE
VirtualScroller not working when loaded lazily

### ISSUE THREAD

**Issue by helmi77** [primefaces/primevue#2537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request 
[ ] support request
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/vigilant-meninsky-v661b5

**Current behavior**
Currently when putting a VirtualScroller inside an accordion tab that is not immediately visible, the VirtualScroller will not display even upon opening the tab it is contained in.

**Expected behavior**
When opening an accordion tab that contains a VirtualScroller we should see the VirtualScroller

**Minimal reproduction of the problem with instructions**
1. Create an accordion with two tabs
2. Put some dummy content in the first tab 
3. Put a VirtualScroller in the second tab
4. Mark the first tab as active
5. Test by opening the second tab and verify that the VirtualScroller is not showing up

https://codesandbox.io/s/vigilant-meninsky-v661b5

* **Vue version:** 3.2.31

* **PrimeVue version:** 3.12.6

* **Browser:** all

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox example. Lazy mode for Accordion could resolve this issue.
