### ISSUE TITLE
Menubar | new `center` slot

### ISSUE THREAD

**Issue by ccsv** [primefaces/primevue#2544]
The horizontal menubar needs options to align the items to the left, right or center in the menu bar, instead of creating buttons at the template #start and template #end positions.

This should allow me to setup a nav bar with 3 items aligned left and 1 item aligned right in the vue file.

**Comment by tugcekucukoglu** [comment]
For now, you could use `item` templating for first and last menu items according to your case. 

We'll discuss it in the team.

**Comment by yuya737** [comment]
Is there an example I can follow to see how exactly the `item` templating works?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
