### ISSUE TITLE
Datatable row editing with filter doesn't work properly

### ISSUE THREAD

**Issue by badalya1** [primefaces/primevue#2563]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

Here is a codesandbox example
https://codesandbox.io/s/blissful-colden-7lpmg?file=/src/App.vue

**Current behavior**
A datatable with global search filter causes editing rows to malfunction. 

**Expected behavior**
Each row should be editable individually. The changes should only be committed on 

**Minimal reproduction of the problem with instructions**
Click on edit button of the first row, change some of the properties without saving, then start editing the second row.
The first row will stay in "editing" mode but the changed values will be reset. 

Change the values in row 1 (while row 1 and row 2 are both in editing mode). After cancelling row 1, the model value of row one changes. 

* **Vue version:** 3.2.36

* **PrimeVue version:** 3.12.6

* **Browser:** Chrome Version 101.0.4951.67

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox demo. I've edited it and seems working. [https://codesandbox.io/s/youthful-lucy-gojwgi?file=/src/App.vue](https://codesandbox.io/s/youthful-lucy-gojwgi?file=/src/App.vue)
