### ISSUE TITLE
Multiline Comment support for Table Editing

### ISSUE THREAD

**Issue by CRC32EX** [primefaces/primevue#2566]
**I'm submitting a ...**
```
[x] feature request 
```

**CodeSandbox Case**
- https://codesandbox.io/s/hungry-euler-5zyqt7?file=/index.html
- https://5zyqt7.csb.app/

**Current behavior**
1. Press `Enter` key
2. `onCellEditComplete` called.
3. I can't submit multiline comment.

**Expected behavior**
1. Press `Shift + Enter` or `Ctrl + Enter` or `Alt + Enter` key
2. `onCellEditComplete` `not` called.
3. Press `Enter` key
4. `onCellEditComplete` called.

**Comment by tugcekucukoglu** [comment]
[tugcekucukoglu](https://github.com/tugcekucukoglu) deleted a comment from [bahadirsofuoglu](https://github.com/bahadirsofuoglu) [on Oct 21, 2022](https://github.com/primefaces/primevue/issues/2784#event-7640986433)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
