### ISSUE TITLE
Popup menu does not appear where it should 

### ISSUE THREAD

**Issue by codeplotter** [primefaces/primevue#258]
When I go to the demo page:

https://www.primefaces.org/primevue/showcase/#/menu

and click the Toggle button for the overlay, the popup is way over on the upper left of the screen, almost not visible because it is too high.  I am running into the same issue when I use it in my site.

**Comment by cagataycivici** [comment]
Thank you, fix is included in 1.2.0 which will be released later today.

**Comment by codeplotter** [comment]
I do appreciate the quick attention to this!  At 100% or above browser zoom, it now appears right where it should be.  I now see a less troublesome issue.... as the browser is zoomed out, the menu gets farther and farther away.  See enclosed screen shots at 100% and 75%.

<img width="1327" alt="100 Percent" src="https://user-images.githubusercontent.com/25725009/78939830-6fe37d80-7a7a-11ea-863f-a13fd372fe3e.png">

<img width="1312" alt="75 Percent" src="https://user-images.githubusercontent.com/25725009/78939836-73770480-7a7a-11ea-8f5c-3b74b7ec5e6c.png">
