### ISSUE TITLE
Duplicate columns and warning when re-ordering columns without a key / field value

### ISSUE THREAD

**Issue by Ancient-Dragon** [primefaces/primevue#2592]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**Current behavior**
When you don't specify a key or a field when re-ordering columns you get duplicate columns

**Expected behavior**
Without specifying either of those two I should bea ble to re-order columns

**Minimal reproduction of the problem with instructions**
Add:  :reorderableColumns="true" to the DataTableFilterDemo.vue and try and move columns around
**Please tell us about your environment:**
Windows 11 (although it'll effect all)

**Vue version:**
3.2.31

**PrimeVue version:**
3.12.7-SNAPSHOT

**Browser:**

![Screenshot 2022-05-31 122018](https://user-images.githubusercontent.com/22601875/171161897-4a5b961d-87df-4a6f-abb9-86f21a8beaf5.png)

**Comment by tugcekucukoglu** [comment]
Please check this example [https://codesandbox.io/s/pensive-mestorf-809jl5?file=/src/DataTableReorderDemo.vue:468-513](https://codesandbox.io/s/pensive-mestorf-809jl5?file=/src/DataTableReorderDemo.vue:468-513)

**Comment by Ancient-Dragon** [comment]
@tugcekucukoglu what more do you need for me to show this is a bug?
