### ISSUE TITLE
DataTable responsive layout resets on route change with a transition (before unmount)

### ISSUE THREAD

**Issue by mtardal** [primefaces/primevue#2596]
**I'm submitting a ...** 
```
[X ] bug report
```

**Current behavior**

DataTable's (which uses responsive stack option) stack layout resets to default layout for a split second on route changes with a transition, which results in a bad UX and other layout issues. The bug does not happen (doesn't happen or is not visible with human eyes 😄 ) if there is no transition for route changes.

**Expected behavior**

DataTable's layout stays the same (stack mode, as defined on creation of the component) on route changes.

**Minimal reproduction of the problem with instructions**
1- Have two routes, one with a DataTable (which uses responsive stack layout) and one empty page.
2- Have a transition between routes.
2- Use a mobile browser or responsive design mode (CTRL+Shift+M on Firefox) of desktop browsers with an example device selected.
3- Notice the table layout when you switch to the blank route from the route that contains the DataTable.

**Possible issue / solution**
I have patched the beforeUnmount hook of the component (https://github.com/primefaces/primevue/blob/master/src/components/datatable/DataTable.vue#L442=) to comment the `this.destroyResponsiveStyle();` line, which fixes the bug without any negative side effects I could notice. But I do not know if `destroyResponsiveStyle()` method has other crucial functions which need to be executed.

Maybe you could expose a prop to disable/enable the calling of this (destroyResponsiveStyle) method or maybe another way to support route changes with transitions?

If you are not able to reproduce the bug, please let me know if commenting the `destroyResponsiveStyle()` method is safe, so I can fork the component with the fix and use the forked one.

* **Vue version:** 3.2.33
* **PrimeVue version:** 3.12.6

* **Browser:** [all mobile browsers ]

PS: I appreciate the work you are doing, loving the library so far.

**Comment by tugcekucukoglu** [comment]
`destroyResponsiveStyle` destroys the styles for stateful DataTable [#L1692](https://github.com/primefaces/primevue/blob/master/src/components/datatable/DataTable.vue#L1692). A codesandbox sample could help understand the problem correctly.

**Comment by mtardal** [comment]
@tugcekucukoglu Sure, an example of the issue can be observed in this codesandbox: https://codesandbox.io/s/brave-curie-qqb9qc . Switch between Home and Table router links and you can notice the table layout resetting when you switch to the Home route from the Table route.
