### ISSUE TITLE
Selecting Text in Dialog / Modal closes Modal

### ISSUE THREAD

**Issue by sebbo2002** [primefaces/primevue#2597]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/wizardly-rgb-rcxms8?file=/index.html

**Current behavior**
1. Open a Modal with an input field in it. I added an example above.
2. Type a value into the input if it's empty.
3. Select the value with your mouse, while holding down the left mouse key.
4. Hold the left mouse button and navigate into the modal background area and release the button.
5. The modal closes.

**Expected behavior**
The modal should not close if the click was initiated in the modal content. The position of the release of the mouse click should not have an impact on the modal behavior.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/wizardly-rgb-rcxms8?file=/index.html

**What is the motivation / use case for changing the behavior?**
People get annoyed when they want to fill in a form in a modal and then close the modal when selecting / copying text. That is a bit unattractive.

* **Vue version:**`vue@next` / `vue@latest` (see Codesandbox)
* **PrimeVue version:** `primevue@^3` (see Codesandbox)
* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
