### ISSUE TITLE
Password: Missing change and blur events

### ISSUE THREAD

**Issue by timyourivh** [primefaces/primevue#2610]
### Describe the bug

The password component does not fire any events except for `@input`.

I'm using vee-validate in lazy mode to validate inputs. Which works fine on `<InputText>` but not on `<Password>`. So I wanted to manually validate on `@change` and `@blur` but noticed only `@input` is being emitted. 

Lazy mode relies on `@change` being emitted. Which `<Password>` doesn't emit.

### Reproducer

https://codesandbox.io/s/pedantic-jasper-72u654?file=/src/App.vue

### PrimeVue version

2.9.2

### Vue version

2.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Use Password component.
2. Try to make use of events `@blur`, `@change`, `@focus`, `@keyUp` or `@keyDown`.

### Expected behavior

The component emitting these events. (Or at least the `@change` event)

### Actual behavior

Events are not being emitted.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/7ba774007ae3a55846f55ef854c2046b76b95674
