### ISSUE TITLE
Editor: SyntaxError when using Editor in Nuxt 3

### ISSUE THREAD

**Issue by shienyuan** [primefaces/primevue#2612]
### Describe the bug

Showing this error when using in Nuxt 3 

`Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/quill/dist/quill.js?v=96818de6' does not provide an export named 'default' (at Editor.vue:51:8)`

I found out this is related to Vite and Quill, shown on this page https://vite.nuxtjs.org/misc/common-issues.

My workaround was to add this in my nuxt.config.js, please note the common issues page of Vite said to add in exclude, but it didn't work for me intead include worked.
```
vite: {
        optimizeDeps: {
            include: ['quill'],
        },
    },
```

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

**Comment by ericzaev** [comment]
nuxt.config.js

```
export default defineNuxtConfig({
  alias: {
    'quill': 'quill/dist/quill.js'
  },`
}
```

**Comment by Eronne** [comment]
Thanks @ericzaev, it's working for me! 🙏🏼

**Comment by flaviooria** [comment]
Thank you so much, it's work for me too ❤️
