### ISSUE TITLE
InputMask cannot input content when setting unmask="true" in Android browser and IOS browser

### ISSUE THREAD

**Issue by yangdachaun** [primefaces/primevue#2613]
### Describe the bug

**InputMask** cannot input content when setting` unmask="true" `in Android browser  and IOS browser

### PrimeVue version

3.12.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

TypeScript

**Comment by tugcekucukoglu** [comment]
Please try to use v3.16.0. If the problem still persists, please reopen this same issue.
