### ISSUE TITLE
Menu component documentation states that show() method accepts a target parameter but doesn't

### ISSUE THREAD

**Issue by joerattz** [primefaces/primevue#2624]
### Describe the bug

In the documentation for the Menu component here:  [Menu](https://www.primefaces.org/primevue/menu)

It shows that the show() method accepts a target parameter.

![image](https://user-images.githubusercontent.com/5185202/171730541-ffd2ef4f-ec7b-4061-9600-2e1ba7dcd7af.png)

But the code that gets called doesn't look at it.

![image](https://user-images.githubusercontent.com/5185202/171731195-e5118cb6-e9b4-47f4-a282-8f45b01fcddf.png)

You can see in the image above that I have passed a second argument that I wanted to be used as the target but nothing in the code is using it.

I sure hope you don't fix this by removing the target parameter from the documentation.

This is how I am working around this right now.

`
const proxyEvent: Event = Object.assign({}, $event, { currentTarget: headerActionKebabButtonProxy.value });  
menu.value?.show(proxyEvent);
`

But I sure hope for a real fix so I can ditch my hack.

### PrimeVue version

3.12.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Browser(s)

Chrome

### Steps to reproduce the behavior

1.  Compare documentation to actual method invoked.

### Expected behavior

Expect the documentation to match the code.  In this case I hope the code is fixed rather than the documentation.

**Comment by tugcekucukoglu** [comment]
Docs fixed. Thanks,

**Comment by joerattz** [comment]
Is it not possible to instead fix the code to match what the docs had?
    On Monday, June 6, 2022, 04:32:08 AM EDT, Tuğçe Küçükoğlu ***@***.***> wrote:  
 
 


Docs fixed. Thanks,

**Comment by tugcekucukoglu** [comment]
Please create different issue.

Thanks,
