### ISSUE TITLE
PickList: Move all to source and move all to target does not update the v-model multidimensional array

### ISSUE THREAD

**Issue by hargitomi97** [primefaces/primevue#2625]
### Describe the bug

So as the title says: If we click on the move all to source, or to the move all to target button, the elements are transferred on the UI, but **not transferred in the multidimensional v-model array**. (console logging the arrays justifies this, for example, even if there is no element left in the source list, they are still there in the array, when they should not be).

It worth mentioning that a **single transfer** (move-to-source, move-to-target) **works well**, and the corresponding array gets updated every time.

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
We could not replicate the issue. Please check this example https://codesandbox.io/s/silly-burnell-7if1ce?file=/src/PickListDemo.vue
