### ISSUE TITLE
DataTable: footer can't be fixed when using VirtualScroll

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#2626]
### Describe the bug

Footer doesn't stick to the bottom of the table when using virtual-scroll.

### Reproducer

https://codesandbox.io/s/goofy-shape-04e6ug?file=/src/DataTableVirtualScrollDemo.vue

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Could you try to use the latest version? If the problem still persists, please feel free to add a new issue.
