### ISSUE TITLE
InputMask disabled attr error

### ISSUE THREAD

**Issue by jairoblatt** [primefaces/primevue#2627]
### Describe the bug

Hi, first of all I love primevue so much, thanks to keep doing it. So,  i'm facing this issue in InputMask with typescript.

It looks like the InputMask props don't extend input html attributes.

```html
   <InputMask
     :model-value="phone"
      mask="(99)99999-9999"
     disabled
   />
```

![image](https://user-images.githubusercontent.com/45108346/171908582-6c7574ea-2cd2-4d51-a7f9-74efa6f4f6ac.png)

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a codesandbox example.
