### ISSUE TITLE
DataTable: Header columns and row columns doesn't resize together with Virtual Scroller and resizable columns

### ISSUE THREAD

**Issue by jayzzer** [primefaces/primevue#2630]
### Describe the bug

When resizing columns with enabled **resizable-columns** prop and **virtual-scroller-options** header columns and row columns are not aligned

### Reproducer

https://codesandbox.io/s/loving-shannon-jlmvdq?file=/src/DataTableColResizeDemo.vue

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a DataTable component with props `:scrollable: true :resizable-columns: true :virtual-scroller-options="{ lazy: true, itemSize: 47 }"`;
2. Try to resize a column.

### Expected behavior

Header columns and row columns are aligned

**Comment by tugcekucukoglu** [comment]
Please update the codesandbox example so we can see the problem.

**Comment by jayzzer** [comment]
> Please update the codesandbox example so we can see the problem.

It's already updated. You have to resize any column
Proof:
![image](https://user-images.githubusercontent.com/13298820/172402347-962c0678-95fb-4eb5-b78d-de2f9e5058f3.png)
