### ISSUE TITLE
Component: VirtualScroll in DataTable is not scrolling to the top after table value change

### ISSUE THREAD

**Issue by nikolashkubelev** [primefaces/primevue#2641]
### Describe the bug

Once the value is changed (e.g. remove rows in the beginning) for DataTable with VirtualScroll it doesn't scroll content to the first row.

https://user-images.githubusercontent.com/1980190/172274887-1446e064-559b-4bca-9e11-652829788ae1.mov

### Reproducer

https://codesandbox.io/s/amazing-meitner-j4zxk8?file=/src/DataTableDemo.vue

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 101

### Steps to reproduce the behavior

1. Click the 'Slice' button
2. The virtual scroll top value remains the same

### Expected behavior

1. Click the 'Slice' button
2. The virtual scroll should scroll to the first row

**Comment by mertsincan** [comment]
Hi,

Please update your itemSize property to 45.5 as the actual height of the DataTable's row is 45.5.
https://codesandbox.io/s/wonderful-hellman-5qureq
In addition, I've added getVirtualScrollerRef method to public API. You can access it via $refs.<your_dataTable> And then, you can scroll to an item index you want using virtualScroller API's methods.
Exp;
this.$refs.dt.getVirtualScrollerRef().scrollToIndex(0);

Best Regards,
