### ISSUE TITLE
Script: CDN Script Fail

### ISSUE THREAD

**Issue by yulinliu** [primefaces/primevue#2642]
### Describe the bug

CDN Script can not read primevue.config

https://unpkg.com/primevue@3.13.0/core/core.min.js

### PrimeVue version

3.13.0

### Vue version

3.x

### Language

ES5

### Build / Runtime

CDN Script

### Browser(s)

Chrome

### Steps to reproduce the behavior

        <link href="https://unpkg.com/primevue/resources/themes/lara-light-indigo/theme.css" rel="stylesheet">
        <link href="https://unpkg.com/primevue/resources/primevue.min.css" rel="stylesheet">
        <link href="https://unpkg.com/primeicons/primeicons.css" rel="stylesheet">

        <script src="https://unpkg.com/vue@next"></script>
        <script src="https://unpkg.com/primevue/core/core.min.js"></script>
        <script src="https://unpkg.com/primevue/slider/slider.min.js"></script>

    <body>
        <div id="app">
            <p-slider v-model="val"></p-slider>
            <h6>{{val}}</h6>
        </div>

        <script>
            const {createApp, ref} = Vue;

            const App = {
                setup() {
                    const val = ref(null);

                    return {
                        val
                    };
                },
                components: {
                    'p-slider': primevue.slider
                }
            };

            createApp(App).use(primevue.config.default).mount("#app");
        </script>
    </body>

**Comment by tugcekucukoglu** [comment]
It's fixed for v.3.13.1. 

Thanks,
