### ISSUE TITLE
Component: Toast - Shorthands and defaults

### ISSUE THREAD

**Issue by huzaifahj** [primefaces/primevue#2646]
### Describe the feature you would like to see added

1. Allow shorthands for creating toasts like so

```ts
import { useToast } from "primevue/usetoast";

const toast = useToast();
toast.success("Summary here")
```

2. Allow global defaults for toasts (e.g. the `life` and the default `summary` message depending on the `severity`

**Comment by tugcekucukoglu** [comment]
ToastService has some built-in functions like `add` that emits a custom event which says there is a message and its properties such as severity, summary and detail. Without creating a message via `add`, to add a success property means nothing. But of course the success property can be change dynamically. So we won't support this kind of usage.

Thanks!
