### ISSUE TITLE
DataTable: multiSortMeta doesn't seem to function correctly

### ISSUE THREAD

**Issue by nootey** [primefaces/primevue#2647]
### Describe the bug

When applying multiSortMeta to a DataTable, it seems to ignore every other condition after the first.

I have a DataTablewith 3 columns I want to sort: receive_date, due_date and calibration_state.label. I've defined sortMode="multiple" and :multiSortMeta="multiSortMeta"

    const multiSortMeta = ref(
        [
          {field: 'receive_date', order: -1},
          {field: 'due_date', order: -1},
          {field: 'calibration_state.label', order: -1},
        ]
    );

I'd expect it to sort by 'receive_date' first, and then by 'due_date' and finally by 'calibration_state.label', but it completely ignores the last two columns.

Expected result (I hope it makes sense): 
![image](https://user-images.githubusercontent.com/71206589/172394225-7f4479d1-f89b-49a2-8b12-863a57ead9f8.png)

Actual result:
![image](https://user-images.githubusercontent.com/71206589/172393877-5c11bbd6-9d92-4ac5-be15-2f052903088c.png)

### PrimeVue version

3.12.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by nootey** [comment]
I'm sorry, but I don't know if i can create a codesandbox in a reasonable time right now. I can describe it a bit more: I have 3 columns per say, 2 are dates and 1 is a string. If i multisort with the string first, I can sort it with the dates as well, but I can't multisort if I start with any of the dates. Does that make sense?

Pseudo:

multisort: 1. sort = string, 2./3. sort = date = sorts
multisort: 1. sort = date, 2. string = doesn't sort

**Comment by nootey** [comment]
I'm sorry, but I don't know if i can create a codesandbox in a reasonable time right now. I can describe it a bit more: I have 3 columns per say, 2 are dates and 1 is a string. If i multisort with the string first, I can sort it with the dates as well, but I can't multisort if I start with any of the dates. Does that make sense?

Pseudo:

multisort: 1. sort = string, 2./3. sort = date = sorts
multisort: 1. sort = date, 2. string = doesn't sort

**Comment by tugcekucukoglu** [comment]
This example seems to working correctly. [https://codesandbox.io/s/nervous-hill-5bb6y5](https://codesandbox.io/s/nervous-hill-5bb6y5?file=/public/demo/data/products-small.json)
