### ISSUE TITLE
Tooltip: ZIndex is cleared on wrong element

### ISSUE THREAD

**Issue by engelhjs** [primefaces/primevue#2649]
Tooltip.js show() function sets zIndex on created tooltip dom element (see: https://github.com/primefaces/primevue/blob/7d386882dc63434eb3862d4222a8eee9f6a26bbf/src/components/tooltip/Tooltip.js#L82)

but hide() function tries to remove the zIndex from the tooltip's parent element instead of the tooltip itself:
https://github.com/primefaces/primevue/blob/7d386882dc63434eb3862d4222a8eee9f6a26bbf/src/components/tooltip/Tooltip.js#L88

which leads to tooltip zIndex is not deleted from ZIndexUtils internal list on hide, letting it grow for every tooltip.

I would expect something like this in hide() function:
```
const tooltipElement = getTooltipElement(el);
  if (tooltipElement) {
    utils.ZIndexUtils.clear(tooltipElement);
  }
```

Is this correct or am I missing something?

**Comment by mertsincan** [comment]
Good catch! Can you please create a PR for this?
