### ISSUE TITLE
Button: Bring the loading prop from primevue3 to primevue2

### ISSUE THREAD

**Issue by tforget** [primefaces/primevue#2655]
### Describe the feature you would like to see added

The primevue2 button lacks the primevue3 button prop loading that hides the icon if any and shows a loading spinner unstead.

Most of the work if not all have been done for you here: https://github.com/primefaces/primevue/pull/2648.

### Describe alternatives you have considered

Should the button also be disabled when the loading prop is true?

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/2648
