### ISSUE TITLE
TreeTable component limited features and future plans

### ISSUE THREAD

**Issue by ZiadJ** [primefaces/primevue#268]
The TreeTable component comes with limited features as compared to the angular and react counterparts so a timeline on their implementation would help if it's in the plans.

**Comment by cagataycivici** [comment]
What are the missing features that you'd like to see?

**Comment by ZiadJ** [comment]
I'm not sure yet but I'm in a position where I have to choose between the Angular and the Vue version on a project that'll only make heavy use of the component in a year from now. I'd much prefer Vue and I don't mind the wait if the missing features will get some love eventually.

**Comment by cagataycivici** [comment]
We plan to add Scrolling, Column Grouping, Resizing and Reordering in 2.0.0 which will come up in a month or so.

**Comment by Alpiag** [comment]
Hi cagataycivici

Finally, have you add these new features (Scrolling, Column Grouping and Reordering) on TreeTable componente in versión 2.0.0?

Best Regards
