### ISSUE TITLE
Component: The "emptyfilter" slot section in Dropdown does not work

### ISSUE THREAD

**Issue by cyhnkckali** [primefaces/primevue#2685]
### Describe the bug

The "emptyfilter" slot does not work among the opened slots. I am sharing the sample code below;

![Ekran görüntüsü 2022-06-16 083033](https://user-images.githubusercontent.com/93313260/173998280-31d5347d-e5f6-48d2-8872-a652956475ce.png)
![Ekran görüntüsü 2022-06-16 083107](https://user-images.githubusercontent.com/93313260/173998284-a66ba821-6c25-47fd-8f4d-105236e7842f.png)

### PrimeVue version

3.15

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 102, Microsoft Edge 102

### Expected behavior

 <Dropdown
        :showClear="true"
        v-model="timezoneId"
        :options="timeZoneList"
        optionLabel="Value"
        :placeholder="translate('user_modal_select_user_time_zone')"
        style="padding: 5px !important"
      >
        <template v-slot:emptyfilter>
          <div class="p-dropdown-filter-container">
            <input type="text" autocomplete="off" class="form-control" />
            <span class="p-dropdown-filter-icon pi pi-search"></span>
          </div>
        </template>
      </Dropdown>

**Comment by tugcekucukoglu** [comment]
Please send us a codesandbox link so we can replicate the issue.
