### ISSUE TITLE
DataTable: Chrome 102 bug => scroll Delay, stutter

### ISSUE THREAD

**Issue by gowy222** [primefaces/primevue#2687]
### Describe the bug

this is not just happen with primevue, also naive UI... It has been proven that the chrome version 102 caused this bug.
but antd-vue's solution successfully circumvented the bug.

reference:
https://github.com/TuSimple/naive-ui/issues/3082
https://github.com/TuSimple/naive-ui/issues/3048

-----
Expect this to help and circumvent bugs caused by browsers

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

chrome 102

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. If the problem is still persists with the latest version, please create a new issue with a reproducer link.
