### ISSUE TITLE
Calendar: wrong overlay position

### ISSUE THREAD

**Issue by nndnha** [primefaces/primevue#2689]
### Describe the bug

- It shows wrong position for calendar overlay.
- It doesn't hide the calendar overlay when clicked on other row.
- After after several click it shows the error: 
```
Cannot read properties of null (reading 'value')
Proxy.onBlur
https://1vxtm6.csb.app/node_modules/primevue/calendar/calendar.esm.js:1812:27
$props.inline.onBlur._cache.<computed>._cache.<computed>
https://1vxtm6.csb.app/node_modules/primevue/calendar/calendar.esm.js:2268:80
...
```

https://user-images.githubusercontent.com/12961516/174263414-a508b6de-2bb0-4119-9140-e8032954a8e8.mp4

### Reproducer

https://codesandbox.io/s/pedantic-https-1vxtm6?file=/src/DataTableEditDemo.vue

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by CraniumAdamantium** [comment]
I've been experiencing the same issue, it happened after npm update

**Comment by CraniumAdamantium** [comment]
Note: temporal solution is to downgrade to 3.12.0
Just change your package-lock.json
