### ISSUE TITLE
FileUpload before-upload event set auth header

### ISSUE THREAD

**Issue by eichgi** [primefaces/primevue#269]
Hi, I am using the FileUpload component but so far I haven't found how to define a bearer token or any other header parameter to the XHR object I can access when using the before-upload event.

Here is my code:

```
beforeUpload(request) {
        console.log(request);
        request.xhr.setRequestHeader('Authorization', this.$auth.getToken('local'));
        return request;
      },
```

The first options request goes to the server but the second got a 302 status code with a redirection, and no bearer token is assigned.

I hope you can guide me, thanks!

**Comment by cagataycivici** [comment]
Hi,

What do you mean by " first options request goes to the server", so when you try to upload again, beforeUpload is not called? Is there an easy way to help us replicate?

**Comment by h-guerrero** [comment]
This is my setting:

```
<FileUpload mode="basic" name="picture" :url="'http://tripo-api.test/api/v1/users/profile/picture'"
                              chooseLabel="Cambiar imagen" :auto="true" @before-upload="beforeUpload"/>

beforeUpload(request) {
        console.log(request);
        request.xhr.setRequestHeader('Authorization', this.$auth.getToken('local'));
        return request;
      },

```
I got the following error: _DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED_.

The first request is an OPTIONS request, then the following request is a GET without headers, shouldn't be a POST?

**Comment by eichgi** [comment]
This is my setting:

```
<FileUpload mode="basic" name="picture" :url="'http://tripo-api.test/api/v1/users/profile/picture'"
                              chooseLabel="Cambiar imagen" :auto="true" @before-upload="beforeUpload"/>

beforeUpload(request) {
        console.log(request);
        request.xhr.setRequestHeader('Authorization', this.$auth.getToken('local'));
        return request;
      },
```

I got the following error: DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.

The first request is an OPTIONS request, then the following request is a GET without headers, shouldn't be a POST?

**Comment by cagataycivici** [comment]
Please use **before-send** instead;

```
@before-send="beforeUpload"
```

**Comment by eichgi** [comment]
You were right, it worked like a charm. I will read the docs thoroughly next time. Thanks!

**Comment by mahkis** [comment]
Raxmat akalar, mendayam ishladi

**Comment by rafaelguillermo** [comment]
hi, i have a question..

i have..

<div class="card">
                        <h2>Foto perfil</h2>
    <FileUpload mode="basic" :url="vUrlCargueArchivoFoto" :auto="true" 
        accept="image/*" :maxFileSize="1000000" @before-send="adicionaHeader" />    
</div>


methods: {        
        adicionaHeader(event){
            console.log(JSON.stringify(event));
            
            event.xhr.setRequestHeader('Content-Type', 'application/json');            
            event.xhr.setRequestHeader('Authorization', `Bearer ${this.todoServicio.getToken()}`);            
            
            console.log(JSON.stringify(event));
            return event;
        }
    },  


but... event.hrx always is empty

<img width="508" alt="Screen Shot 2021-08-12 at 2 10 05 PM" src="https://user-images.githubusercontent.com/5187027/129254835-6128d748-1023-4f84-b851-696d7adeedc8.png">

help me...
