### ISSUE TITLE
Menubar: - Add highlighting of clicked item

### ISSUE THREAD

**Issue by huzaifahj** [primefaces/primevue#2694]
### Describe the feature you would like to see added

Just like the TabMenu component, Menubar should add the `p-highlight` class so that we can see which menu item is the currently active one.

This could be an opt-in feature.

Is there a current workaround without having to manually style `router-link-active-exact`?

**Comment by tugcekucukoglu** [comment]
There is 'p-menuitem-active' class which set when item is active. I'll add it to the documentation.

If you do not want to `router-link-active-exact` class, you could set `exact` property as false.
