### ISSUE TITLE
Component: Calendar @month-change returns 0-11 and 1-12

### ISSUE THREAD

**Issue by flohoss** [primefaces/primevue#2696]
### Describe the bug

Event @month-change should return the same month range when changing with arrow keys or the drop down menu.
Currently it returns different values for the same month depending on the method.
Forward and Backwards arrows: 0-11
Drop down picker: 1-12

![Screenshot 2022-06-21 143255](https://user-images.githubusercontent.com/65008174/174811718-4cc9f4ca-b2be-41b9-80c4-bd5303d53970.png)
![Screenshot 2022-06-21 143314](https://user-images.githubusercontent.com/65008174/174811736-d9d75beb-7c70-4cd7-a153-efb7daa07632.png)
Select May, click backward and forward creates this:
![Screenshot 2022-06-21 143341](https://user-images.githubusercontent.com/65008174/174811752-341a03ae-0ae8-43e3-a6bb-027b74f59761.png)

### Reproducer

https://codesandbox.io/s/zealous-johnson-761y2c

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox 101, Chrome 102

### Steps to reproduce the behavior

Click month forward and backward arrow, month will change from 0-11
Click on month to select month in drop down, month will change from 1-12

### Expected behavior

Both methods should return the same number range

**Comment by tugcekucukoglu** [comment]
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)

**Comment by tugcekucukoglu** [comment]
Fixed via [#2708 ](https://github.com/primefaces/primevue/pull/2708)
