### ISSUE TITLE
Chips: Multiple separator

### ISSUE THREAD

**Issue by Soph0208** [primefaces/primevue#2698]
### Describe the feature you would like to see added

Could multiple strings be specified for the separator?

I need this for entering email addresses. Here it cannot be clearly determined whether every user really only ever uses a comma. It can also happen that one user puts a comma between several email addresses and the next uses a space. However, `Chips `would not format a bookmark because the separator is not correct here.

### Is your feature request related to a problem?

Various user inputs cannot be intercepted.

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primevue/issues/3240
