### ISSUE TITLE
Calendar is not empty when the v-model is null

### ISSUE THREAD

**Issue by voquanghoa** [primefaces/primevue#270]
Hello team,

I got an issue with the Calendar component and it can be reproduced here https://codesandbox.io/s/nervous-brahmagupta-hd7oc

When we click the Clear button, the value becomes null but the text in the textbox (represent the calendar) still displays the last date-time value.

Did I do anything wrongly?

Thanks for checking the issue

UPDATE 1. I found a similar issue https://github.com/primefaces/primevue/issues/42 but the issue still happens on the lastest version 1.2.0, so I keep the issue here.

**Comment by cagataycivici** [comment]
Let me check this and get back to you.

**Comment by cagataycivici** [comment]
Fixed for 1.3.0. https://github.com/primefaces/primevue/commit/e4707c955ad1e665985a722f26f6aca7b16c641a
