### ISSUE TITLE
Component: Resize error when using "Dropdown" in modal

### ISSUE THREAD

**Issue by cyhnkckali** [primefaces/primevue#2706]
### Describe the bug

When  "dropdown component" is used in a "bootstrap modal" with the filter feature turned on, the event in the image occurs. Mobil Platform
![untitled](https://user-images.githubusercontent.com/93313260/175034339-cf7e2866-1825-4300-b393-c69d1d30ad75.gif)
![Ekran görüntüsü 2022-06-22 155820](https://user-images.githubusercontent.com/93313260/175034760-f76edba0-16d2-451c-b903-737b865a5095.png)

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Android Chrome

**Comment by mertsincan** [comment]
Hi,
Which Primevue version are you using? Also, could you please check the output of DomHandler.isTouchDevice()?

**Comment by cyhnkckali** [comment]
Hi @mertsincan , Primevue version 3.15.0.   "Also, can you check the output of DomHandler.isTouchDevice()? " How should I do,

*Mert merahaba, Control etmemi istediğin şey tam olarak nedir?

**Comment by cyhnkckali** [comment]
> 
Hi! Mert , output as below

![Ekran görüntüsü 2022-07-05 102443](https://user-images.githubusercontent.com/93313260/177273100-f3aacbb9-fcea-4238-9248-f7d374117b50.png)
![Ekran görüntüsü 2022-07-05 102508](https://user-images.githubusercontent.com/93313260/177273105-1bf3a785-c83e-47d9-b659-c106a180f4b3.png)

* Android için deneme yaptım. İlk iki block için true dönüş aldım

**Comment by mertsincan** [comment]
Hi @cyhnkckali,

Her şey doğru görünüyor. Normal şartlarda mobile devicelar virtual keyboard ekranda göründüğü zaman resize eventini çağırıyorlar. Bizde resize eventi bağladığımız overlay bişenlerinde DomHandler.isTouchDevice() değil ise kapatma işlemini yapmıyoruz. Kod;
https://github.com/primefaces/primevue/blob/master/src/components/dropdown/Dropdown.vue#L523

Virtual keyboard çıktığı zaman, sizin tanımladığınız resize eventin çalışıp çalışmadığını kontrol edebilir misin? Şu an paneli neyin kapattığı konusunda bir fikrim yok. 
```
onMounted(() => {
    window.addEventListener('resize', () => {
         console.log('resize');
    });
})
```

**Comment by cyhnkckali** [comment]
Hi @mertsincan,

Klavye açılıp kapandığı için  iki kez resize event'ı oluyor. Bu durum denemek için Primevue dialog u kullandığımda da aynı durumu orada da yaşadım.  Acaba modal'ın bir css özelliğimi bunu engelliyor. Çünkü bu modal içerisinde bir çok Dropdown var fakat focus sorunu modalın sonuna doğru gelen dropdownlarda yaşanıyor.

![Ekran görüntüsü 2022-07-06 091413](https://user-images.githubusercontent.com/93313260/177481655-7492ee09-e0b2-4f8b-b39e-43799e2c1bd8.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
