### ISSUE TITLE
DataTable: Bad Sort Performance 

### ISSUE THREAD

**Issue by zortext** [primefaces/primevue#2707]
### Describe the bug

When large data loaded into `DataTable` component, sort by column runs extremely slow. While large `DataTable` is good at loading, rendering, paginating and navigating it has a poor performance on sorting and filtering. 

### Reproducer

https://codesandbox.io/s/dank-morning-trh8lp?file=/src/DataTableSortDemo.vue

### PrimeVue version

3.6.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

All

**Comment by tugcekucukoglu** [comment]
Duplicate [#1649 ](https://github.com/primefaces/primevue/issues/1649)
