### ISSUE TITLE
Listbox: Filter array of strings

### ISSUE THREAD

**Issue by IvanSGurdian** [primefaces/primevue#2709]
### Describe the feature you would like to see added

Proper filter for array of strings.

### Is your feature request related to a problem?

Currently, Listbox allows to filter an array of objects by providing an `optionLabel` to look for a property to use as a value to compare; when the `options` array is just an array of strings the filter simply won't return matches.

### Describe the solution you'd like

Maybe implement a `mode` prop or similar to allow Listbox to filter its list of options using a simple `filter()` method.

### Describe alternatives you have considered

I tried using a custom function on the `@filter` event Listbox exposes and with the filter value updating a computed property which holds the filtered items, inspecting the VueTools the array is updating correctly, but the Listbox component still only shows a `No results found` message even though the filtered array has items.

### Additional context

I'm using the component like this:

```html
<Listbox class="border-0" v-model="selectedField" :multiple="true" :options="filteredFields"
 :filter="true" @filter="customFilter($event)"/>
```

```js
data() {
        return {
            selectedFields: [],
            filterValue: ''
        }
    },
computed: {
        filteredFields() {
            return this.myArray.filter(item => item.toLowerCase().includes(this.filterValue))
        }
    },
methods: {
        customFilter(event) {
            this.filterValue = event.value
        }
    }
```

I still get this

![image](https://user-images.githubusercontent.com/34893604/175144562-f18276bd-069c-4bff-b9f6-9304c939259e.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
