### ISSUE TITLE
DataTable: Arrow up and down event listeners

### ISSUE THREAD

**Issue by naveenreddy3** [primefaces/primevue#2711]
### Describe the bug

First of all thanks for the library and i am using datatable in my vue3 project. In that i am using datatable single selection and its working fine. So we have **rowSelect** event listener on first click but i want the index of selected row whenere user clicks on up or down arrows, is there any event listeners for arrow up/down?

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
arrow keys get focus a row not select the row except radio single selection. So when a row is selected or unselected the events that mentioned will be called.
