### ISSUE TITLE
DataTable  multiple sort seems not work

### ISSUE THREAD

**Issue by hakiiver2** [primefaces/primevue#2716]
### Describe the bug

How can I implement multiple sorting?
The example does not appear to allow multiple sorting

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Multiple sort is available for DataTable component. [https://primefaces.org/primevue/datatable/sort](https://primefaces.org/primevue/datatable/sort)

**Comment by hakiiver2** [comment]
@tugcekucukoglu 
Is this implementation correct?

https://user-images.githubusercontent.com/42739911/176174678-8a585615-c451-44cd-88b2-728ce47d7b78.mov

**Comment by hakiiver2** [comment]
I was under the impression that I could sort by both columns.

**Comment by tugcekucukoglu** [comment]
I think you miss the documentation. ```Multiple columns can be sorted by defining sortMode as multiple. This mode requires metaKey (e.g. ⌘) to be pressed when clicking a header.```

**Comment by rowanfuchs** [comment]
I've created the feature request https://github.com/orgs/primefaces/discussions/3111 as our experience is that it's a UX anti-pattern, as it often necessitates extra explanations to inform users on how to sort by multiple fields.
