### ISSUE TITLE
The "frozen column " Don't' exist feature  in primevue

### ISSUE THREAD

**Issue by Weigle** [primefaces/primevue#272]
Hey people.
I'm was searching for one function that freezes the column in primeVue, but doesn't exist.

This feature has in Primefaces and Primeng

I going created this issue to leave registered

thanks, everyone

**Comment by cagataycivici** [comment]
It is available, please see the last demo at;

https://primefaces.org/primevue/showcase/#/datatable/scroll

**Comment by Weigle** [comment]
Sorry, I forget to say to the frozen column don't exist in TreeTable.

**Comment by Weigle** [comment]
> Hey people.
> I'm was searching for one function that freezes the column in primeVue, but doesn't exist.
> 
> This feature has in Primefaces and Primeng
> 
> I going created this issue to leave registered
> 
> thanks, everyone



> It is available, please see the last demo at;
> 
> https://primefaces.org/primevue/showcase/#/datatable/scroll

Thanks for yours response but,
I forget to say to the frozen column don't exist in TreeTable.
sorry about that
