### ISSUE TITLE
GalleriaAdvancedDemo.vue: <script> part doesn't correspond to actual demo

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#2720]
### Describe the bug

primevue/src/views/galleria/GalleriaAdvancedDemo.vue: <script> part doesn't correspond to actual demo

There are variables in the template (like `activeIndex`) which are never defined in the script.

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for the report. It'll be fixed.
