### ISSUE TITLE
Range and Multiple selection support for Calendar Month Picker

### ISSUE THREAD

**Issue by f1l0** [primefaces/primevue#273]
Hi, Im trying to use the calendar with the "month" view in combination with a range selection. As soon as I click on a month I get: TypeError: "this.value.getMonth is not a function" on isMonthSelected Calendar.vue:404.

Im using the following code:
`<Calendar id="period" v-model="selectedPayment.period" :showIcon="true" dateFormat="mm/yy" :locale="it" class="wauto" selectionMode="range" :manualInput="true" view="month" :yearNavigator="true" yearRange="2020:2030" />`

"primevue": "1.1.0",

Thank you

**Comment by voquanghoa** [comment]
Seem `selectedPayment.period` should be a Date object

**Comment by f1l0** [comment]
I tried already with a default null value or with "new Date()". In the last case I see the current month pre-selected, but I get the same beheviour: Once I click somewhere the exception is visible in the console... If I remove the selectionMode attribute all is working correctly. Looks like that the combination of the two produce the problem... 
Thank you

**Comment by cagataycivici** [comment]
Not sure, range selection is supported in month view, I'll check for next week's 1.3.0.

**Comment by f1l0** [comment]
thank you both!

**Comment by cagataycivici** [comment]
Yes, only single selection is supported in month mode, we'll convert this to an enhancement ticket.

**Comment by tugcekucukoglu** [comment]
I think this issue was fixed with [that issue](https://github.com/primefaces/primevue/issues/1880)
