### ISSUE TITLE
Component: AutoComplete stops highlighting first suggestion

### ISSUE THREAD

**Issue by sebastian-stephan** [primefaces/primevue#2733]
### Describe the bug

When setting `auto-highlight` on an `AutoComplete` component, the first items stops being highlighted when the user continues typing and the first suggestion changes.

I checked the react implementation where this correctly works.

### Reproducer

https://codesandbox.io/s/proud-surf-xshl0k?file=/src/App.vue

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open Sandbox
2. Start typing "tri"
3. Wait for first item to be highlighted
4. Continue typing "...stan"
5. First item is no longer highlighted

### Expected behavior

The first item always keeps being highlighted.

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a new codesandbox example.

**Comment by sebastian-stephan** [comment]
Can confirm that this is fixed in v3.16.0. Thanks!
