### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by karmac2015** [primefaces/primevue#2744]
### Describe the feature you would like to see added

At the moment primevue does not support rtl layout, if I still want  to use primevue for rtl layout can you help me to convert it to rtl using postcss-rtl or rtlcss or give me another method to convert the components to rtl.

**Comment by tugcekucukoglu** [comment]
It's on our roadmap. 

Thanks,

**Comment by karmac2015** [comment]
Thank you, can I know how long this feature will be available ?

**Comment by mertsincan** [comment]
Details; https://primevue.org/roadmap/
