### ISSUE TITLE
Component: datatable

### ISSUE THREAD

**Issue by hakiiver2** [primefaces/primevue#2747]
### Describe the feature you would like to see added

When sorting a data table, sometimes I don't want to set the page to 0, so I want an option to not reset the page when sorting.

**Comment by tugcekucukoglu** [comment]
Lazy loading demo could be example for this. `first` options could be changed via sort methods.

**Comment by hakiiver2** [comment]
@tugcekucukoglu 
Thank you for replying!
![スクリーンショット 2022-07-01 23 38 13](https://user-images.githubusercontent.com/42739911/176915643-cd48d557-72a5-41aa-b2d2-ca6c03c864e7.png)

I thought this picture's resetPage method always `first` is set to 0.

**Comment by nlien** [comment]
Any chance of reopening this? I am using the lazy load attribute and whenever I sort my table, the paginator resets to the first page, due to the resetPage() method referenced above.
