### ISSUE TITLE
Datatable rowStyle wrong documentation

### ISSUE THREAD

**Issue by mattiapv** [primefaces/primevue#2750]
https://github.com/primefaces/primevue/blob/9bea5bb25f6146edd0670a522455f65071949e8b/src/views/datatable/DataTableDoc.vue#L2131

rowStyle is not a function. 
However it would be more useful if it was like rowClass.

**Comment by tugcekucukoglu** [comment]
I'll fixed the docs.

Thanks,

**Comment by badalya1** [comment]
Can we have this issue back, but not as "wrong documentation" but as "wrong implementation". 

There is actually a very important use case with rowStyle, for example setting css variables for the entire row then using classes that depend on those variables.
