### ISSUE TITLE
Data Table Loading

### ISSUE THREAD

**Issue by marceana** [primefaces/primevue#2758]
### Describe the feature you would like to see added

Hi! How are you? I believe a good feature is to replace the standard loader and css applied to the Data Table.

### Is your feature request related to a problem?

I've been working with prime vue and I've stumbled into a possibly nice new feature to the Data Table. Specifically I tried to use the loading template but I didn't want to use the standard loader and css that are applied by prime vue. So I think it would be nice to have some kind of feature to make it easier if someone doesn't want to use the standard loading.

### Describe the solution you'd like

Maybe a new property that gives you the option to use the standard icon and css or not, with the values being true or false.

### Additional context

![image](https://user-images.githubusercontent.com/78447100/177182402-bba0c813-dc7f-49e8-b9bd-4bb4f47cc1c0.png)

**Comment by tugcekucukoglu** [comment]
You could check loading templating slot.

**Comment by andreLuis1506** [comment]
Loading templating slot work, but the loading icon and overlay still keeping.

**Comment by ae-vivanov** [comment]
Hi! I also would like an option to control whether to display overlay or not. How to remove `p-datatable-mask p-overlay-mask` in the div?

```html
<div class="p-datatable-mask p-overlay-mask" data-pc-section="mask">
    <i class="p-datatable-loading-icon pi-spin pi pi-spinner" data-pc-section="loadingicon"></i>
</div>
```

**Comment by Alvarezzz14** [comment]
> Hi! I also would like an option to control whether to display overlay or not. How to remove `p-datatable-mask p-overlay-mask` in the div?
> 
> <div class="p-datatable-mask p-overlay-mask" data-pc-section="mask">
>     <i class="p-datatable-loading-icon pi-spin pi pi-spinner" data-pc-section="loadingicon"></i>
> </div>

I use this :deep(.p-datatable-mask.p-overlay-mask) {
  background: transparent !important; 
} but don't know. if is the best practice, but is functionally
