### ISSUE TITLE
Dropdown: Tabbing out of filter doesn't close dropdown

### ISSUE THREAD

**Issue by zcdunn** [primefaces/primevue#2759]
### Describe the bug

If the dropdown panel is open and focus is in the filter input, pressing tab moves focus to the next element but the dropdown panel remains open.

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Open a filterable dropdown
2. Press Tab

### Expected behavior

Focus moves to the next focusable element and the dropdown panel closes.

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a new codesandbox example.
