### ISSUE TITLE
AutoComplete: problem with completeOnFocus

### ISSUE THREAD

**Issue by lipiniak** [primefaces/primevue#2762]
### Describe the bug

Autocomplete component not showing box after focusing with data in input. Component have completeOnFocus set on true. 

Complete event is starting but search query is empty. I noticed that focusing back on input is using PointerEvent and typing in input witch works fine is using InputEvent.

Selected complete event after focusing on input by clikcing on it. 
![Zrzut ekranu 2022-07-6 o 08 28 11](https://user-images.githubusercontent.com/5384562/177483562-10eae9eb-2241-4a38-87e0-d32f72a43780.png)
 

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Type in AutoComplete input
2. Select option
3. change focus
4. set focus back to AutoComplete

### Expected behavior

After focusing on input component should show autocomplete box with data.

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a new codesandbox example.
