### ISSUE TITLE
Calendar: Multiple example causes error on double-click

### ISSUE THREAD

**Issue by havist** [primefaces/primevue#2769]
### Describe the bug

When selecting a date by the double-click from the calendar popup following error appears in the console:
```
chunk-vendors.09ff30d3.js:7 TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at Object.find (app.0f2c8172.js:1:1351045)
    at Proxy.onDateSelect (app.0f2c8172.js:1:269161)
    at onClick (app.0f2c8172.js:1:248857)
    at Vt (chunk-vendors.09ff30d3.js:7:36703)
    at Yt (chunk-vendors.09ff30d3.js:7:36795)
    at HTMLSpanElement.r (chunk-vendors.09ff30d3.js:7:83794)
```

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to the component's demo page https://www.primefaces.org/primevue/calendar.
2. Open calendar's popup.
3. Select a date by double-clicking on it.

### Expected behavior

No error appears.

**Comment by tugcekucukoglu** [comment]
The issue cannot be replicated. Please try to use the latest PrimeVue version. If the problem still persists let us know.
