### ISSUE TITLE
Timeline: new item and index slot props for connector slot

### ISSUE THREAD

**Issue by robbienohra** [primefaces/primevue#2771]
### Describe the feature you would like to see added

Currently, style overrides to the timeline connector component happen globally at the timeline component level.  It is not an uncommon use case to require dynamic style overrides across multiple connectors for a given timeline instance.

### Is your feature request related to a problem?

NA

### Describe the solution you'd like

Dynamic styling can be achieved (as is being done with the `marker` and `content` named slot) by binding the `item` property to the `connector` named slot. This enables the following type of customization to connectors for a given timeline.

```vue
<template #connector="slotProps">
            <div
              class="p-timeline-event-connector"
              :style="{ width: '4px', backgroundColor: slotProps.item.color }"
            ></div>
</template>
```

![image](https://user-images.githubusercontent.com/28514482/178623384-7f5b448a-f59c-460d-9e91-a0e661590c76.png)

**Comment by tugcekucukoglu** [comment]
Fixed via [#2770 ](https://github.com/primefaces/primevue/pull/2770)
