### ISSUE TITLE
SpeedDial: Tooltip doesn't display when using SpeedDial

### ISSUE THREAD

**Issue by noel-srocha** [primefaces/primevue#2772]
### Describe the bug

When using a SpeedDial button component alongside the Tooltip, the later doesn't display when passing the mouse over the button.

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Vivaldi 5.3.2679.68

### Steps to reproduce the behavior

1) Import SpeedDial and Tooltip to main.ts, define the first as component and the second as a directive (as shown in their respective docs);

2) Add the SpeedDial component to the template of a Vue file;

3) Add the tooltip directive to the SpeedDial;

4) Launch "npm run dev" to observe the behavior.

### Expected behavior

On hover, the SpeedDial button component should display a tooltip describing its purpose.

**Comment by tugcekucukoglu** [comment]
Instead using directly tooltip as a directive, please use `tooltipOptions` property for SpeedDial.

Also see [https://codesandbox.io/s/4z6fe5?file=/src/SpeedDialDemo.vue:1765-1865](https://codesandbox.io/s/4z6fe5?file=/src/SpeedDialDemo.vue:1765-1865)
