### ISSUE TITLE
Component: Menubar

### ISSUE THREAD

**Issue by paulocoutinhox** [primefaces/primevue#2773]
### Describe the feature you would like to see added

Hi,

My suggestion is a way to align menubar items to right direction, because it always go to left.

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/395096/178896830-73e12b18-ccb5-49c3-851c-fb0831e8dcab.png">

### Is your feature request related to a problem?

No

**Comment by tugcekucukoglu** [comment]
There is `item` templating slot for menu's items to handle for this.

Thanks for your consideration.

**Comment by mherb63** [comment]
@tugcekucukoglu can you please provide an example of how to do this.  like the op, I want the About menu on the far right.

Thank You
