### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by Son-Hom** [primefaces/primevue#2774]
### Describe the bug

How can I set the disabled checkbox row on datable?
I saw in datatable->RowCheckbox.vue it has a condition like below but don't know how to use it.
```
onClick(event) {
            if (!this.$attrs.disabled) {
                this.focused = true;
                this.$emit('change', {
                    originalEvent: event,
                    data: this.value
                });
            }
        },
```

### PrimeVue version

3.10.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
DataTable component doe snot support this kind of usage. It checks only `selectionMode` property.

https://github.com/primefaces/primevue/blob/master/src/components/datatable/BodyCell.vue#L12
