### ISSUE TITLE
Passing Attributes to a component

### ISSUE THREAD

**Issue by choff5507** [primefaces/primevue#2775]
Im pretty new to PrimeVue and I have a question. When using the `<InputText>` component and I click on the field, my browser will give me some options to put into the field. Using `autocomplete="off"` doesn't seem to have an effect. So my question is about this component primarily but in how can standard attributes be passed to a component? Is setting it like a prop generally the way?

**Comment by tugcekucukoglu** [comment]
`autocomplete` is not a valid property. You could find available properties in `Properties` section in the docs.

**Comment by mertsincan** [comment]
Hi,

All standard input properties are added directly to the input tag. Exp;
https://codesandbox.io/s/gifted-babbage-fyj9od?file=/src/InputTextDemo.vue

```
Component:
<InputText type="text" v-model="value1" autocomplete="off" />

DOM:
<input class="p-inputtext p-component" type="text" autocomplete="off" data-v-2f087a71="">
```
Could you please check DOM using the browser's inspector?

Best Regards,
