### ISSUE TITLE
Accordion Header, when focused z-index is higher that Tooltip 

### ISSUE THREAD

**Issue by dizzyn** [primefaces/primevue#2777]
### Describe the bug

Once the Accordion Header is focused, it's z-index covers Tooltips.

UI:
![image](https://user-images.githubusercontent.com/2071816/179233796-173af2b9-48d0-4b2e-965a-f7fa7d2290f1.png)

Code:
![image](https://user-images.githubusercontent.com/2071816/179233927-992e1053-f4d3-4412-a979-c083af4858f3.png)

### PrimeVue version

 3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
![Screen Shot 2022-06-08 at 09 16 37](https://user-images.githubusercontent.com/32294991/180718771-df7bf045-d864-4d0d-891d-e80ba9564cdd.png)


I did not replicate the issue. Could you send us a codesandbox link?

**Comment by tugcekucukoglu** [comment]
<img width="418" alt="Screen Shot 2022-08-08 at 12 34 46" src="https://user-images.githubusercontent.com/32294991/183387690-600af47b-200b-4ec0-b88e-c1c19c35f11a.png">


Can not replicate the issue. Could you provide a codesandbox link?

**Comment by dizzyn** [comment]
please try to focus the accordion header and then hover the hint.

**Comment by tugcekucukoglu** [comment]
Cannot replicate this issue. If problem is still persist, please send us a codesandbox link to replicate the issue and reopen this same issue.
