### ISSUE TITLE
DataTable/TreeTable: Tooltip support on cells

### ISSUE THREAD

**Issue by soixam93** [primefaces/primevue#2779]
### Describe the feature you would like to see added

whether to hide extra content and show them in a tooltip when hovering on the cell

**Comment by soixam93** [comment]
thanks. but i think should be have a Column Component Properties to use it is better. When the content of cell is so long you can hidden and show the content when mouse hover on

**Comment by ZiadJ** [comment]
Have you considered using the templating functionality for that so far?

**Comment by tugcekucukoglu** [comment]
`body` templating could be used for this purpose. I have a demo [https://codesandbox.io/s/busy-cdn-p0r0wv?file=/src/DataTableBasicDemo.vue:158-219](https://codesandbox.io/s/busy-cdn-p0r0wv?file=/src/DataTableBasicDemo.vue:158-219)

**Comment by ZiadJ** [comment]
@tugcekucukoglu Notice how the tooltip has a white border separating the content from the arrow. It may be a tiny detail but it degrades the overall experience. Fortunately, it only applies to certain themes only but I'm hoping that it'll be resolved soon for the sake of integrity.
