### ISSUE TITLE
Documentation: DataTable row editing documentation refers to cellEdit instead of editMode

### ISSUE THREAD

**Issue by nathanhennig** [primefaces/primevue#2781]
### Describe the bug

At https://primefaces.org/primevue/datatable the documentation for DataTable, there is a line:

> "Row Editing is specified by setting cellEdit as row, defining editingRows with the v-model directive to hold the reference of the editing rows,"

From the paragraph above that line that describes cell editing and the context of the demo code for row editing, it is clear that "cellEdit" should be "editMode".

### Reproducer

https://primefaces.org/primevue/datatable

### PrimeVue version

v3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
It will be fixed. 

Thank you!
