### ISSUE TITLE
Slider: fails for values [1850, 2022]

### ISSUE THREAD

**Issue by leegee** [primefaces/primevue#2782]
### Describe the bug

```javascript
const ageRange = ref([1850, 2022]);

<h3>Age {{ ageRange }}</h3>
<Slider v-model="ageRange" :range="true" />
```
Tried with and without `:step="10"`.

![image](https://user-images.githubusercontent.com/512816/179502108-f10b9498-dbe5-4d57-9c97-bbc810487ec8.png)

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

As above

### Expected behavior

I expect the slider to appear as illustrated in the documentation website, with two handles, spaced apart. If there is a limit to the values that can be set, or a way of pre-setting values, please let me know!

**Comment by tugcekucukoglu** [comment]
The default value of the `max` property is 100. In your case passing a max prop solves problem.
