### ISSUE TITLE
DataTable: `first` prop is not properly reflected on the paginator when `lazy` is true

### ISSUE THREAD

**Issue by Voltra** [primefaces/primevue#2783]
### Describe the bug

When setting the `lazy` prop to `true` on the DataTable, the `first` prop of the Paginator is always zero due to a [ternary in its template](https://github.com/primefaces/primevue/blob/56cfbcad990cb146589337a3301af3ce22da5a79/src/components/datatable/DataTable.vue#L10) which makes it impossible to properly show that a page different from the first is loaded (on page load).

### Reproducer

https://codesandbox.io/s/upbeat-haibt-2dxnnv?file=/src/App.vue

### PrimeVue version

2.9.2

### Vue version

2.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

https://codesandbox.io/s/upbeat-haibt-2dxnnv?file=/src/App.vue

### Steps to reproduce the behavior

1. Have a DataTable with the `lazy` prop set to `true` (i.e. for data fetching)
2. Have a way to change the `first` prop on page load (e.g. via query string)
3. Visit the page with a `first` that would be on the 2nd (or any page that isn't the 1st)
4. Notice the data fetched is the one of the appropriate page
5. Notice the page number is 1 instead of the appropriate page's

### Expected behavior

The paginator should always be in sync with the DataTable

**Comment by tugcekucukoglu** [comment]
Duplicate [#2253 ](https://github.com/primefaces/primevue/issues/2253)
