### ISSUE TITLE
Calendar dayNamesMin localization

### ISSUE THREAD

**Issue by marcobacci86** [primefaces/primevue#2784]
### Describe the bug

I'm having some troubles with primevue locale configuration. I filled and loaded the json configuration with my own locale but it seems like something is missing with the calendar component. Some configurations are correctly loaded, like 

> monthNames

 but some others, like 

> dayNamesMin

are not. 
Here a screenshot of the missing locale:
![Schermata 2022-07-13 alle 11 46 01](https://user-images.githubusercontent.com/90399143/179711312-b256f913-e06b-40b3-9de5-ed2b90e9bc9e.png)

### PrimeVue version

3.10.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 103.0.5060.114 (Build ufficiale) (x86_64)

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.

**Comment by mrc-bsllt** [comment]
Same problem in the versions:
primevue: 3.49.1
nuxt-primevue: 0.3.1

Is there any news?

**Comment by KumJungMin** [comment]
I think, this issue is resolved
In my playground, the dayNamesMin is working :)
If I misunderstood the problem, can you attach playground link of issue?

<img width="1021" alt="스크린샷 2024-06-11 오후 1 41 27" src="https://github.com/primefaces/primevue/assets/37934668/e394c00e-1a18-4934-8211-9785379611a8">

https://stackblitz.com/edit/syhrzk?file=src%2Fmain.js

**Comment by tjbrains** [comment]
You must specify "firstDayOfWeek" like below:
~~~
app.use(PrimeVue, {
	locale: {
             dayNamesMin: [ ... ],
             firstDayOfWeek: 0
         }
})
~~~

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
