### ISSUE TITLE
Calendar firstDayOfWeek property

### ISSUE THREAD

**Issue by marcobacci86** [primefaces/primevue#2785]
### Describe the feature you would like to see added

Add the _firstDayOfWeek_ property to the Calendar component that we can find in Primeng version also in Primevue component.

![Schermata 2022-07-19 alle 11 08 22](https://user-images.githubusercontent.com/90399143/179713067-86cbc31f-f08c-4cab-88e1-a2efaf1b2163.png)

**Comment by tugcekucukoglu** [comment]
Yes, Calendar does not have `firstDayOfWeek` property but there is locale option for this. Please check https://www.primefaces.org/primevue/locale

**Comment by cyhnkckali** [comment]
Bu öneri işe yaramaz çünkü tarih sırası yerel ayarlarla değişmez. Lütfen gerçek bir çözüm önerin.

**Comment by cyhnkckali** [comment]
This suggestion does not work because the date order does not change with local settings. Please suggest a real solution.

**Comment by rhristow** [comment]
I'm also having this problem, please a solution

**Comment by mfrey777** [comment]
I have the same issue. I would like to get monday as first column in the calendar (instead of sunday) I could not find a "settings" in locale to achieve that

**Comment by anchan42** [comment]
This seem to work fine for me. It also sorted out the week number calculation.

``` 
app.use(PrimeVue, {locale: {firstDayOfWeek:1}}),
```
