### ISSUE TITLE
PickList: add prop to disable doubleclick event

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2786]
### Describe the feature you would like to see added

Prop which would enable/disable double click event.

### Is your feature request related to a problem?

- With :metaKeySelection="false" it doesn't work as it should (need to select item at first then double click)
- If I click on item fast it doesn't fire double click event.
https://sharing.clickup.com/clip/p/t4774246/e9ff59f5-3715-4fd8-ade1-14f5e115b9fa/screen-recording-2022-07-19-13:28.webm

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
