### ISSUE TITLE
Component Name: Documentation : DataTable -> Vuelidate example

### ISSUE THREAD

**Issue by y-emiage** [primefaces/primevue#2787]
### Describe the feature you would like to see added

In documentation, there is not examples to describe vuelidate using with Primevue Datatable/TreeMap compoment

### Describe the solution you'd like

adding an example article with a datable/treeTable

**Comment by tugcekucukoglu** [comment]
Vuelidate example page consists only form elements. But DataTable editing mode could be used easily with Vuelidate.

Thanks,

**Comment by AkromaPhage** [comment]
Would be nice if an example could be provided
