### ISSUE TITLE
DataTable: aria-sort is not being used correctly

### ISSUE THREAD

**Issue by tlframe2** [primefaces/primevue#2789]
### Describe the bug

The correct way to use aria-sort is to only use it on elements where role equals columnheader or rowheader. It should also only be used on one header at a time. Currently, DataTable columns have role of cell and aria-sort is used on all columns.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/32079409/179805312-dd987715-2c74-4b6b-a834-76086e2946a2.png)
![datatable](https://user-images.githubusercontent.com/32079409/179805335-18d3fa6d-d78a-4f75-90db-f75ab0f06fd6.PNG)

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
We're working on the accessibility. DataTable is still not fixed and there could be another wrong uses.

Thanks for the report.
