### ISSUE TITLE
AutoComplete: AutoHighlight lost on subsequent searches

### ISSUE THREAD

**Issue by furmandev** [primefaces/primevue#2791]
### Describe the bug

https://user-images.githubusercontent.com/7343697/180011023-1ae0b6bf-4efd-4164-821c-335e6ed125e1.mp4

Notice `chad` is highlighted, but then `china` is not.

If this is intended behavior, an additional config field to allow subsequent highlighting would be nice.

Thanks! 🙏

### Reproducer

https://codesandbox.io/s/lucid-khayyam-wbqkxc

### PrimeVue version

3.2.31

### Vue version

3.x

### Language

ALL

### Build / Runtime

TypeScript

### Steps to reproduce the behavior

1. Type `ch` (notice `chad` is highlighted)
2. Continue typing `chin` (notice `china` is not highlighted)

### Expected behavior

I would expect `china` to be highlighted after typing more.

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a new codesandbox example.
