### ISSUE TITLE
Calendar: Cannot select dates when passing in an initial value when selection mode is 'range'

### ISSUE THREAD

**Issue by agm1984** [primefaces/primevue#2793]
### Describe the bug

Here is a minimal reproduction: https://codesandbox.io/s/stupefied-danilo-rfk5b6

When selection-mode is range and an initial value is passed to the Calendar component, the picker doesn't allow a new range to be selected.

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. set selection-mode to range
2. set model-value to a two element array of dates
3. open the calendar picker
4. attempt to change the selection

### Expected behavior

Dates should be allowed to change.

**Comment by tugcekucukoglu** [comment]
Please use `v-model` instead of `modelValue` to update Calendar value.
