### ISSUE TITLE
Dynamic Dialog: Cannot Access ref variables from Open dialog method

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#2794]
### Describe the bug

```
const dialogRef = dialog.open(editInvoiceNumberDialog, {
        props: {
          header: "hello",
          modal: true,
          position: 'top',
          draggable: false
        }, templates: {
          footer: () => {
            return [
              h(Button, { label: "No", icon: "pi pi-times", onClick: () => dialogRef.close({ buttonType: 'No' }), class: "p-button-text" }),
              h(Button, { label: "Yes", icon: "pi pi-check", autofocus: true, type: "submit", form: "edit-invoice-number-form", loading: dialogRef.isProcessing })
            ]
          }
        }
      });
```

Inside the editInvoiceNumberDialog component, I am making an ajax request, so I need the button yes of the dialog display the loader according to the state of a ref variable called isProcessing inside the editInvoiceNumberDialog.

The problem is dialogRef.isProcessing is always null

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

chrome

**Comment by tugcekucukoglu** [comment]
Please check this example [https://codesandbox.io/s/loxc5z?file=/src/DynamicDialogDemo.vue:785-818](https://codesandbox.io/s/loxc5z?file=/src/DynamicDialogDemo.vue:785-818)

If problem is still persist, please reopen this same issue with a codesandbox example.
