### ISSUE TITLE
Dropdown: add filterInputAutoFocus prop

### ISSUE THREAD

**Issue by mitow7821** [primefaces/primevue#2796]
### Describe the feature you would like to see added

I'd like to see new filterInputAutoFocus prop which will allow to focusing filter field by default.
This prop has been already implemented in PrimeReact and PrimeNG.

### Is your feature request related to a problem?

Autofocusing filter input on mobile causes keyboard to open which leads to poor UX.

**Comment by panruza** [comment]
+1

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
