### ISSUE TITLE
DataTable: Incorrect sorting when using Cyrillic.

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#2799]
### Describe the bug

Incorrect sorting in the data table when using Cyrillic.
Data is sorted in different ways (from mysql database and Prime DataTable rendering)

**Vue version:** 3.2.37
**PrimeVue version:** 3.15
**Browser:** all 

<img width="1198" alt="primeRep1" src="https://user-images.githubusercontent.com/5528152/180221131-3b5d9ffe-5a14-4a9d-9118-12fcc6933123.png">
<img width="1179" alt="primeRep2" src="https://user-images.githubusercontent.com/5528152/180221159-ba299d6d-d504-47ca-a093-388096dab9a7.png">

// Testing data
```
[
      {
         "id":1,
         "last_name":"Шевчук"
      },
      {
         "id":20,
         "last_name":"Петров"
      },
      {
         "id":55,
         "last_name":"Агентов"
      },
      {
         "id":53,
         "last_name":"Wolff"
      },
      {
         "id":51,
         "last_name":"Walker"
      },
      {
         "id":54,
         "last_name":"Spinka"
      },
      {
         "id":49,
         "last_name":"Schuster"
      },
      {
         "id":50,
         "last_name":"Sauer"
      },
      {
         "id":56,
         "last_name":"Robel"
      },
      {
         "id":24,
         "last_name":"Mohr"
      },
      {
         "id":21,
         "last_name":"Littel"
      },
      {
         "id":52,
         "last_name":"Huel"
      },
      {
         "id":23,
         "last_name":"Goldner"
      },
      {
         "id":22,
         "last_name":"Adams"
      }
   ]
```

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Safari 15.6

**Comment by tugcekucukoglu** [comment]
How can we replicate the issue? 

We would be grateful if you create a PR with the possible solution.

**Comment by atach** [comment]
> How can we replicate the issue?
> We would be grateful if you create a PR with the possible solution.

I don't have a solution, but Here I showed the problem:
https://codesandbox.io/s/hungry-einstein-rm3rmv?file=/src/App.vue

In all databases, servers, services and applications, Cyrillic sorting works quite differently: Latin words are sorted first, and only then Cyrillic comes. In the DataTable component, everything is the opposite.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
