### ISSUE TITLE
Support Plugins in ChartModel

### ISSUE THREAD

**Issue by strateego** [primefaces/primevue#280]
Support for plugins in the ChartModel would be great.

I am using the https://github.com/chartjs/chartjs-plugin-annotation, with a customized version of the charts component. I was able to add the plugin by adding plugins as a prop type of array, and passing the plugins in the initChart() method.

Offical support for plugins would be great! Thanks for the hard work.

**Comment by cagataycivici** [comment]
We'll review, thanks.

**Comment by cagataycivici** [comment]
You can use options property to use plugins;

```
<Chart type="line" :data="mydata" :options="config" />
```

```js
data() {
   return {
        mydata: //your data
        config: {
             annotation: {...
        }
   }
}
```
