### ISSUE TITLE
DataTable: confirming edit with TAB causes old content to reappear when edited again

### ISSUE THREAD

**Issue by woodcoder** [primefaces/primevue#2800]
### Describe the bug

Using a DataTable with editable cells, I found an issue where pressing TAB after editing would look to be working correctly, but if you click to edit the cell again, the original value reappears.

### Reproducer

https://stackblitz.com/edit/vue-6d7vng?file=src/App.vue

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. click on the table cell with 'edit me' in it
2. edit the text in the cell to some other string (e.g. 'edit me edited')
3. press TAB to leave the cell and move to the next one - the contents will be the edited string
4. click back on the table cell with 'edit me edited' in it
5. you will find it goes back to just saying 'edit me'

### Expected behavior

Expected behaviour is that when you go to re-edit it, that it says 'edit me edited' - i.e. maintains the previous edits made and changes are not lost.

**Comment by woodcoder** [comment]
I believe that the issue could be to do with using the DataTable in a subcomponent, where I am using `:value="modelValue"` for the property data to flow into the table, and emitting `'update:modelValue'` after each `'cell-edit-complete'` event.

I think the issue is that when you press TAB, the `editing-meta-change` events fire in the wrong order/before the model  value updates have been applied?  

Making the artificial 'click' event invoked in `moveToNextCell` and `moveToPreviousCell` (to take you to the next editable component) fire in `this.$nextTick` certainly seems to resolve the issue:
https://github.com/primefaces/primevue/blob/091d26e7e37a1b75fb45d0fb72be330db344ac6c/src/components/datatable/BodyCell.vue#L260

**Comment by tugcekucukoglu** [comment]
https://user-images.githubusercontent.com/32294991/180739248-4aa3c39d-5185-4069-a0e5-849aebfb50b9.mov

It seems working correctly. Am I missing something?

**Comment by woodcoder** [comment]
Hi thanks for trying it out - sorry I wasn't clear enough in the instructions - you need to click back to the last cell that you tabbed out of:

https://user-images.githubusercontent.com/218889/180747714-26516016-9eac-4ae4-b508-6ddef69ca8b2.mov

I think it was working for you because the last column edited was B, but you clicked on A.

**Comment by tugcekucukoglu** [comment]
It seems `onCellEditComplete` function does not change the value. I've found a solution.

[https://stackblitz.com/edit/vue-16gxvf?file=src%2Fcomponents%2FMyDataTable.vue%3AL49](https://stackblitz.com/edit/vue-16gxvf?file=src%2Fcomponents%2FMyDataTable.vue%3AL49)

**Comment by tugcekucukoglu** [comment]
Could you check this link? https://stackblitz.com/edit/vue-16gxvf?file=src%2Fcomponents%2FMyDataTable.vue%3AL50 

I updated previous one.

**Comment by woodcoder** [comment]
Thanks again - sure, that workaround also works.  I'm very grateful for the extra info.

I have been trying to avoid making direct changes to the array properties, and was working on emitting update events, as per the Vue 3 recommendation: https://vuejs.org/guide/components/props.html#one-way-data-flow

I do believe there is still an underlying framework bug:
   * there is no need for the workaround when you press ENTER or click away - this only affects TAB (so if it's not a bug, it is at least inconsistent)
   * the events that normally fire to update the field data work correctly if the artificially invoked click to focus from moveToNext/PrevCell is deferred to the nextTick [presumably because of some change to when the field focus/blur events happen]
   
However, as I say, the workaround you provided is fine, thank you.
