### ISSUE TITLE
Calendar: inline calendar force scroll into viewport when disabledDates changed 

### ISSUE THREAD

**Issue by BoYuanSu** [primefaces/primevue#2803]
Watch data months change will trigger updateFocus method.

when disabledDates changed, months will be recalculated, and trigger watch data to updateFocus 

demo code please refer the last commit of this branch https://github.com/BoYuanSu/primevue/tree/demo-2798 

bellow is demo gif

![demo-bug](https://user-images.githubusercontent.com/30211393/180799980-ffcbc45e-3a66-4396-9033-478720cfd36a.gif)

from #2798 pr

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
[#2798 ](https://github.com/primefaces/primevue/pull/2798) points to the wrong issue number. If you create a new PR, we would gladly accept it.
