### ISSUE TITLE
Slider (range): Strange effect when value is 0

### ISSUE THREAD

**Issue by gbayarri** [primefaces/primevue#2804]
### Describe the bug

When we have a range slider between a negative and a positive values, at the moment of reaching the 0 value, the slider suddenly jumps to the original value. Attached you can find a gif with the behavior:

![ezgif-3-8f72027098](https://user-images.githubusercontent.com/19928100/180806240-d68ba5e4-8457-455c-a787-dddfc5a360fb.gif)

### PrimeVue version

3.10.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Please use `min` and `max` property of Slider.

**Comment by gbayarri** [comment]
I am using them:

```
<Slider 
    v-model="model" 
    :range="true" 
    :min="-5" 
    :max="5" 
    :step="0.5" 
/>
```

```
const model = ref([-1, 1])
```

Thanks
