### ISSUE TITLE
DataTable: Reorder doesn't work on mobile devices

### ISSUE THREAD

**Issue by slano** [primefaces/primevue#2805]
### Describe the bug

DataTable component reorder functionality doesn't work on mobile devices

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primevue/datatable/reorder on mobile
2. Try to reorder rows/columns

### Expected behavior

ability to reorder rows/columns on mobile devices

**Comment by tugcekucukoglu** [comment]
Duplicate [#1543](https://github.com/primefaces/primevue/issues/1543)
