### ISSUE TITLE
Dropdown: Placeholder class is applied even though an option is selected

### ISSUE THREAD

**Issue by Voltra** [primefaces/primevue#2806]
### Describe the bug

When the dropdown's placeholder value is the same as the select option's label, the Dropdown components adds the `p-placeholder` class even though it semantically makes no sense.

Currently, this is due to the fact that the placeholder class is applied [when the current label is equal to the placeholder](https://github.com/primefaces/primevue/blob/2.x/src/components/dropdown/Dropdown.vue#L513) instead of when there's no value selected (e.g. `!this.value`).

### PrimeVue version

2.9.2

### Vue version

2.x

### Language

ES6

### Build / Runtime

Nuxt

### Expected behavior

The placeholder class should never be applied if a value is selected

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a codesandbox example.
