### ISSUE TITLE
ColorPicker: Color resets to violet after sliding to the left

### ISSUE THREAD

**Issue by kentonbandy** [primefaces/primevue#2808]
### Describe the bug

Hello, I was playing with the ColorPicker on https://www.primefaces.org/primevue/colorpicker and I noticed that the color changes to violet when following these steps:

- Move the vertical slider on the right to any color
- Move the color picker circle all the way to the left side of the window
- Move the color picker back to the right
- Green value is 0, red and blue values are equal (I was watching the RGB values using dev tools)

Issue happens in Vue 2 and Vue 3 versions.
Browser: Chrome

### Reproducer

https://www.primefaces.org/primevue/colorpicker

### PrimeVue version

latest

### Vue version

2.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primevue/colorpicker
1. Move the vertical slider on the right to any color
1. Move the color picker circle all the way to the left side of the window
1. Move the color picker back to the right
1. Green value is 0, red and blue values are equal (I was watching the RGB values using dev tools)

### Expected behavior

When sliding the color picker circle to the left and back to the right, it should retain the color ratio indicated by the vertical slider.

**Comment by kentonbandy** [comment]
I've decided to try to fix this myself. Have fixed the main issue but still seeing odd behavior so looking further into it.

**Comment by kentonbandy** [comment]
I'm happy to report that the issue is addressed in this PR: https://github.com/primefaces/primevue/pull/2809

**Comment by davidglezz** [comment]
https://user-images.githubusercontent.com/194784/214708923-629daa2f-c552-4289-8507-c3a4b55c4396.mov

**Comment by Sagmedjo** [comment]
Bug still persist. Are there any news on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by davidglezz** [comment]
The issue still exists
