### ISSUE TITLE
"--mask-bg" maybe "--maskbg" ?

### ISSUE THREAD

**Issue by haidongdong** [primefaces/primevue#2815]
### Describe the bug

at web pages : https://www.primefaces.org/primevue/colors

TABLE "General Colors."
...These are common variables used throughout the theme...

the LAST row: 
    ==>  "--mask-bg | Background of an overlay mask."
MAYBE:
   ==>  "--maskbg | Background of an overlay mask."   ？

### PrimeVue version

primevue@3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Firefox 91.10.0

**Comment by tugcekucukoglu** [comment]
Could you explain the issue with this variable name?
