### ISSUE TITLE
MegaMenu: Documentation regarding router-link has invalid syntax 

### ISSUE THREAD

**Issue by loneil** [primefaces/primevue#2816]
### Describe the bug

On the MegaMenu documentation https://primefaces.org/primevue/megamenu there is a section showing how to use `<router-link>` that contains a syntax error regarding quotation types and placement

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to https://primefaces.org/primevue/megamenu Documentation
2. Find the Templating section and the `<router-link>` example
3. Try copying that code snippit into your application and see the syntax error on startup or linting

### Expected behavior

The code example in the documentation should work in a Vue 3 PrimeVue project

**Comment by loneil** [comment]
I've created a PR for this here https://github.com/primefaces/primevue/pull/2817

**Comment by tugcekucukoglu** [comment]
PR is merged.

Thank you for your contribtion.
