### ISSUE TITLE
Icon: Documentation of what `pi-fw` means

### ISSUE THREAD

**Issue by loneil** [primefaces/primevue#2820]
### Describe the feature you would like to see added

On the various menu component documentations "pi-fw" is used in all the icons, but I can't find anywhere on the icon documentation (or anywhere else) that explains what that class means. 

### Describe the solution you'd like

Documentation of the `pi-fw` class.

**Comment by tugcekucukoglu** [comment]
`pi-fw` comes form PrimeIcons library.

```
.pi-fw {
    width: 1.28571429em;
    text-align: center;
}
```

**Comment by scooby359** [comment]
What's the purpose of `.pi-fw`? Why is it an arbitrary width and alignment?

**Comment by krazkidd** [comment]
> What's the purpose of `.pi-fw`? Why is it an arbitrary width and alignment?

I'm going to guess it normalizes the width (and centers) to the width of the widest icon. So if you have a list of icons, they all line up evenly. The width value will change if a new wider icon is added to the set.
