### ISSUE TITLE
MenuItem: Error in package.json + vite

### ISSUE THREAD

**Issue by ig-onoffice-de** [primefaces/primevue#2823]
### Describe the bug

I added a menu and imported the MenuItem type. Unfortunately now vite breaks on `npm run dev` with the following error:

```
X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "primevue/menuitem". The package may have incorrect main/module/exports specified in its package.json: Failed to re
solve entry for package "primevue/menuitem". The package may have incorrect main/module/exports specified in its package.json.
```

Changing the `package.json` in `primevue/menuitem` to

```
{
  "main": "MenuItem.d.ts",
  "types": "./MenuItem.d.ts"
}
```

fixes the error (although I'm not sure if this is the right way). Currently all our developers have to do the change in their `node_modules`, so could you please fix this?

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for your report. Unfortunately, we can not replicate the issue. Could you share a simple codesandbox link with your current environment to try it locally?

**Comment by ig-onoffice-de** [comment]
Here is a github repo to try it out
https://github.com/ig-onoffice-de/primevue-issue2823
or the repo imported to codesandbox
https://codesandbox.io/s/bold-shockley-pfmcft?file=/src/App.vue

**Comment by tugcekucukoglu** [comment]
Thanks for the both repo and codesandbox example. MenuItem is not a component and is just a TS declaration helper. It is not a valid usage that you have used. I hope it's clarified.

**Comment by colinbes** [comment]
Clear as mud. How do we include the interface MenuItem when using TypeScript?

Error message when running `rpm run dev`

```
[ERROR] Failed to resolve entry for package /node_modules/primevue/menuitem. The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
```
```
❯ node --version
v18.16.0
❯ npm --version
9.5.1
```
