### ISSUE TITLE
AutoComplete: completeOnFocus with keyboard navigation

### ISSUE THREAD

**Issue by rico** [primefaces/primevue#2824]
### Describe the feature you would like to see added

It would be nice if `completeOnFocus` works with keyboard navigation as well, not only when the user clicks the input.

### Is your feature request related to a problem?

Suggestions do not open, when the user navigates to the Autocomplete input using the keyboard.

### Describe the solution you'd like

Open suggestions if Autofocus input receives focus.

### Describe alternatives you have considered

Add focus event listener to the input using the ref and open the suggestions.

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.16.0? If problem is still persist, please reopen this same issue with a codesandboz example.

**Comment by rico** [comment]
Unfortunately with v3.16.0 the `completeOnFocus` does not work at all - not even on click. I have the following declaration:

```
<AutoComplete v-model="_clientService.service"
                      @complete="onComplete"
                      @item-select="onServiceSelected"
                      placeholder="Leistung suchen ..."
                      :suggestions="_services"
                      :forceSelection="true"
                      class="w-full"
                      input-class="w-full"
                      :minLength="2"
                      :autoHighlight="true"
                      :completeOnFocus="true"
                      :field="servicesSearchLabel" />
```
And with v3.16.0 this combination pre-selects (sets as v-model) the first item from the suggestion. If I remove `                      :autoHighlight="true"`, no pre-selection happens, but the suggestions do not open on focus. Searching & select, however, works as before.

**Comment by rico** [comment]
@tugcekucukoglu let me know if I can help with something (testing, etc.). Do you still need that codesandbox example?

**Comment by tugcekucukoglu** [comment]
The issue waits the review again. A codesandbox could really help.

**Comment by rico** [comment]
@tugcekucukoglu created a test repo: https://github.com/smartcode-ch/primevue-autocomplete-issue  ... was easier because codesandbox does not support `<script setup>`.

Just switch  primevue version to `3.15.0` to see the difference.

Hope that helps, and thanks for looking into this!

**Comment by tugcekucukoglu** [comment]
Yes, codesandbox does not support `<script setup>`, but it doesn't matter we could try it in local environment.

Thanks for your time.
