### ISSUE TITLE
Event: column-click in DataTable component

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#2828]
### Describe the feature you would like to see added

Many times I have come across the need to listen to the event "click on a certain column in the table" in DataTable Component - @columnClick (@col-click).

Maybe there is some ready-made solution that I do not know about?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
