### ISSUE TITLE
TreeSelect: Filter

### ISSUE THREAD

**Issue by Grldk** [primefaces/primevue#2832]
### Describe the feature you would like to see added

Would live to see the filter as seen in the Tree component added to the TreeSelect component. As far as I can see this is not supported right now.

**Comment by erinleary** [comment]
I was able at add my own filter using the Header template. See my comment under this issue for the code (also expands nodes until you can see the ones that matched the filter). https://github.com/primefaces/primevue/issues/2964

**Comment by minzdrav** [comment]
+1 for filter.
Workaround from https://github.com/primefaces/primevue/issues/2964 is hacky and I don't think we should use it.

**Comment by adamndev** [comment]
+1 please!

**Comment by luketPatchworks** [comment]
+1

**Comment by nixwins** [comment]
+1 for filter

**Comment by chung-orient** [comment]
+1 for filter

**Comment by Akkuzin** [comment]
+1

**Comment by tugcekucukoglu** [comment]
https://primevue.org/treeselect/#filter
