### ISSUE TITLE
AutoComplete: Add Selected item template

### ISSUE THREAD

**Issue by j-meds** [primefaces/primevue#2833]
### Describe the feature you would like to see added

A slot option for the autocomplete's selected item in the input.

Bottom component is desired effect after selection
![image](https://user-images.githubusercontent.com/12689117/183757723-2f0ab082-3d8e-471e-bcce-0ef493947259.png)

I want my template item slot to be similar to the selected
![image](https://user-images.githubusercontent.com/12689117/183757788-f97310c0-9ad4-4dbd-b73f-eda9402ae09d.png)

### Is your feature request related to a problem?

No

### Describe the solution you'd like

similar to the #item slot 
```
<template #selected=item="slotProps">
   <div class="my-option">
      <div>{{ slotProps.item.name}}</div>
      <div class="text-xs text-muted">{{ slotProps.item.description}}</div>
   </div>
</template>
```

**Comment by tugcekucukoglu** [comment]
The upcoming `pt` property will add this functionality and more.

Thanks!

**Comment by j-meds** [comment]
@tugcekucukoglu I saw that it's live how would I apply a custom message like above, it says I can only pass in attributes using pt. I need to pass in a custom template

**Comment by cuberinooo** [comment]
Would also like to see something like a slot to change the template of the selected-item. Is there are chance to do this with :pt ?
