### ISSUE TITLE
Add icon templating to Rating

### ISSUE THREAD

**Issue by capoia** [primefaces/primevue#2834]
### Describe the feature you would like to see added

Hello how are you ?

I would like to change the rating component icons, using svg or the primeicons.
Something like vuetify already does.

Thanks!

### Is your feature request related to a problem?

no.

### Describe the solution you'd like

Put a slot for the filled icon and the empty icon

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/f0ae0138b74a3190f15161cc5eed1e0eb53be836

Added properties;

- [ ] onIcon
- [ ] offIcon
- [ ] cancelIcon

Added slots;

- [ ] onicon
- [ ] officon
- [ ] cancel
