### ISSUE TITLE
Slider: Keyboard navigation is broken when in range mode

### ISSUE THREAD

**Issue by lriecken** [primefaces/primevue#2836]
### Describe the bug

If the slider is in range mode, the incrementValue and decrementValue functions do not get the index of the model value to update. Thus, the model value gets set to NaN if the user tries to change the range slider with the arrow keys.

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

TypeScript

### Steps to reproduce the behavior

1. Create a slider and set the attribute range to true.
2. Tab until you have the first slider handle selected.
3. Use the arrow keys to change the value.
4. The model value gets set to NaN.

### Expected behavior

The model value should be incremented or decremented.

**Comment by tugcekucukoglu** [comment]
Please try to use v3.16.0. If the problem still persists, please reopen this same issue with a codesandbox link.
