### ISSUE TITLE
DataTable: Column filter does not work correctly for lazy mode

### ISSUE THREAD

**Issue by tradersr** [primefaces/primevue#2837]
### Describe the bug

Column filter only works if you you search on the 1st page.

Simply confirm your example below which is introduced in PrimeVue site, does not work either.
https://www.primefaces.org/primevue/datatable/lazy

If you search "James Butt" or someone else for Name field on the 1st page display, it works. But if you search the same person on the 2nd page or other pages, it does not work. And then if you just click on the page button "2" once again, the correct result is returned.

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

https://www.primefaces.org/primevue/datatable/lazy
1. Search "James Butt" or someone else for Name field on the 1st page display, it works. 
2. Search the same person on the 2nd page or other pages, it does not work. 
3. And then if you just click on the page button "2" once again, the correct result is returned.

### Expected behavior

Column filter should work on every page.

**Comment by mertsincan** [comment]
This issue has already been fixed in the latest version. Please try it.

Best Regards,
