### ISSUE TITLE
Accessibility for Form Components

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#2838]
- AutoComplete
- Calendar
- CascadeSelect
- Checkbox
- Chips
- ColorPicker
- Dropdown
- Editor
- InputMask
- InputNumber
- InputSwitch
- InputText
- Knob
- Listbox
- MultiSelect
- Password
- RadioButton
- Rating
- SelectButton
- Slider
- Textarea
- ToggleButton
- TriStateCheckbox
- TreeSelect (partially)

**Comment by zachlearnscode** [comment]
I'm noticing that pressing "return" to submit a form is triggering the submit event listener, but the true "enter" on a numpad works. Could that related to these changes?
