### ISSUE TITLE
Datatable: disabledSelection property for checkboxes

### ISSUE THREAD

**Issue by Derpa-Chief** [primefaces/primevue#2839]
### Describe the feature you would like to see added

I would like to see the disabledSelection feature in the Datatable component in PrimeFaces implemented in PrimeVue

NOTE - If this feature is already planned for a future release then apologies in advance! Thanks for your time

### Is your feature request related to a problem?

There's a use case for our application that uses PrimeVue in which we want certain rows in a datatable to not be selectable when using the select all checkbox on the datatable.

### Describe the solution you'd like

Would like to be able have certain rows in the datatable component to be unselectable and not have a checkbox/radio element appear in the column for that datatable row.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
