### ISSUE TITLE
DataTable: Make Filter and Sort icons customizable 

### ISSUE THREAD

**Issue by noel-srocha** [primefaces/primevue#2840]
### Describe the feature you would like to see added

Right now, as far as I read from the documentation, I'm not able to configure the DataTable's icons to use another icon library instead of PrimeIcons. I believe PrimeVue and other Prime frameworks would benefit if the settings were flexible.

### Is your feature request related to a problem?

I'm using Font Awesome icon library with PrimeVue in one of my companies' projects, but, according to the DataTable's documentations, there are no properties to customize the mentioned icons.

It would help the UI's standardization if the DataTable's icons settings were flexible.

### Describe the solution you'd like

It would be great if the following properties were added to the DataTable component:

1) **sortIcon** -> This property would configure the icon to describe sorting operations;

2) **filterIcon** -> Same as the above, but for the filter.

**Comment by tugcekucukoglu** [comment]
`filtericon ` and `sorticon ` slots are avaailable for Column component. Please try to use the latest version.
