### ISSUE TITLE
Nuxt3 : use calendar => error

### ISSUE THREAD

**Issue by titoff002** [primefaces/primevue#2841]
### Describe the bug

Hello,

I'm use nuxt3 with primevue.

When i would to use Calendar, this error is encoured : 

```
Vue warn]: Failed to resolve component: Calendar
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
```

![image](https://user-images.githubusercontent.com/24948237/184553638-555d88c2-32e7-4af8-aebb-d9c5366e090e.png)

![image](https://user-images.githubusercontent.com/24948237/184553649-47de6a58-8e23-48f5-b691-41cf72ee0e2c.png)

![image](https://user-images.githubusercontent.com/24948237/184553663-ae77f182-52b6-4319-b22f-42d43f1ac834.png)

But, when call directly "Calendar" on app.vue => it's OK !

![image](https://user-images.githubusercontent.com/24948237/184553850-eacb0287-7eaf-4bdb-8573-f0693d7faa00.png)

Have you on idea why when call calendar on file plugins\primevue.js => doesn't work ??

Thanks to you.

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
I've create an example [https://codesandbox.io/s/elastic-lamarr-xh0b8u?file=/components/PrimeVueCalendar.vue](https://codesandbox.io/s/elastic-lamarr-xh0b8u?file=/components/PrimeVueCalendar.vue). If problem is still persist please reopen this same issue with a codesandbox example.
