### ISSUE TITLE
Editor Quill: SSR error document is not defined

### ISSUE THREAD

**Issue by medusiora** [primefaces/primevue#2842]
### Describe the bug

Hi, 
Is possible to use Editor component in SSR mode ?

```
   "nuxt": "^3.0.0-rc.8",
   "primevue": "^3.15.0",
    "quill": "^1.3.7",
    "unplugin-vue-components": "^0.21.1"
```

Thanks.

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by mertsincan** [comment]
I'll work on it and get back to you.

**Comment by medusiora** [comment]
> I'll work on it and get back to you.

Many thanks.
