### ISSUE TITLE
DataTable: Column Filter filterClear templating for filterDisplay: "row"

### ISSUE THREAD

**Issue by woodcoder** [primefaces/primevue#2843]
### Describe the bug

When using the filtering on the DataTable in `filterDisplay="row"` mode, the `<template #filterclear="{ filterCallback }">` that is available normally doesn't work.

I believe this is because the template code is missing from:
https://github.com/primefaces/primevue/blob/master/src/components/datatable/ColumnFilter.vue#L9

Whereas `filterClearTemplate` is used when not in row mode:
https://github.com/primefaces/primevue/blob/master/src/components/datatable/ColumnFilter.vue#L41-L42

As a workaround, you can still override the icon using CSS, but without the template, it's not possible to add additional customisation (e.g. a tooltip) in this datatable filter display mode.

### Reproducer

https://codesandbox.io/s/sad-mountain-rpdhxo?file=/src/App.vue

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Load the Code Sandbox reproducer
2. Filter the columns by entering a name search, picking from the status select or clicking on the verified checkbox.
3. The clear filter button appears, but is not using the template, which would show a pi-times (X) icon

### Expected behavior

The filterclear template should be used, and a pi-times (X) icon should be shown instead.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
