### ISSUE TITLE
CDN Script fails

### ISSUE THREAD

**Issue by enyachen** [primefaces/primevue#2844]
### Describe the bug

The CDN script _https://unpkg.com/primevue@^3/core/core.min.js_ causes the following errors:

- **Uncaught SyntaxError: Unexpected token ']'**
- **Uncaught TypeError: Cannot destructure property 'FilterMatchMode' of 'primevue.api' as it is undefined.**

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

`  <head>
  	<meta charset="utf-8" />

  	
  	<link href="https://unpkg.com/primevue@^3/resources/themes/saga-blue/theme.css" rel="stylesheet" />
  	<link href="https://unpkg.com/primevue@^3/resources/primevue.min.css" rel="stylesheet" />
  	<link href="https://unpkg.com/primeflex@^3/primeflex.min.css" rel="stylesheet" />
  	<link href="https://unpkg.com/primeicons/primeicons.css" rel="stylesheet" />

  	
  	<script src="https://unpkg.com/vue@next"></script>
  	<script src="https://unpkg.com/primevue@^3/core/core.min.js"></script>

  	
  	<script src="https://unpkg.com/primevue@^3/datatable/datatable.min.js"></script>
  	<script src="https://unpkg.com/primevue@^3/column/column.min.js"></script>
  	<script src="https://unpkg.com/primevue@^3/multiselect/multiselect.min.js"></script>
  	<script src="https://unpkg.com/primevue@^3/calendar/calendar.min.js"></script>

  </head>
  <body>
  	<div id="app">
  		<div class="card">
  			<p-datatable :value="jobs" :paginator="true" :rows="10" striped-rows
  			paginator-template="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
  			:rows-per-page-options="[10,20,50]"
  			responsive-layout="stack"  v-model:filters="filters" filter-display="menu" :global-filter-fields="['location']"> 

  			<template #header>
  				<div class="flex justify-content-between">
  					<p-button type="button" icon="pi pi-filter-slash" label="Clear" class="p-button-outlined" @click="clearFilter()"></p-button>
  					<span class="p-input-icon-left">
  						<i class="pi pi-search"></i>
  						<p-inputtext v-model="filters['global'].value" placeholder="Search"></p-inputtext>
  					</span>
  				</div>
  			</template>

  			<p-column field="location" header="Location" :sortable="true">
  				<template #body="{data}">
  					{% raw %}
  					{{data.location}}
  					{% endraw %}
  				</template>
  				<template #filter="{filterModel}">
  					<p-inputtext type="text" v-model="filterModel.value" class="p-column-filter" placeholder="Search by location"></p-inputtext>
  				</template>
  			</p-column>

  		</p-datatable>
  	</div>
  </div>

  <script type="module">
  	const { createApp } = Vue;
  	const { FilterMatchMode, FilterOperator } = primevue.api;

  	const App = {
  		created() {
  			this.initFilters();
  		},
  		methods: {
  			initFilters() {
  				this.filters = {
  					'global': {value: null, matchMode: FilterMatchMode.CONTAINS},
  					'location': {operator: FilterOperator.AND, constraints: [{value: null, matchMode: FilterMatchMode.CONTAINS}]},
  				}
  			},
  			clearFilter() {
  				this.initFilters();
  			},
  		},
  		components: {
  			"p-datatable": primevue.datatable,
  			"p-column": primevue.column,
  			"p-inputtext": primevue.inputtext,
  			"p-button": primevue.button,
  			"p-multiselect": primevue.multiselect,
  			"p-calendar": primevue.calendar,
  			"p-inputnumber": primevue.inputnumber,
  			"p-dropdown": primevue.dropdown,
  		},
  		data() {
  			return {
  				filters: {},
  				jobs: [
  		
  				]
  			}
  		},
  	};

  	const app = createApp(App);
  	app.use(primevue.config.default);
  	app.mount("#app");
  </script>

</body>`

**Comment by mertsincan** [comment]
Fixed now. Thank you!

**Comment by h00jie** [comment]
It seems its not working yet

**Comment by mertsincan** [comment]
Could you please try it with v3.16.1?

**Comment by pvidalis** [comment]
It seems its not working yet too

**Comment by h00jie** [comment]
Yes you are right, excuse me  ... probably my browser cached something

**Comment by mertsincan** [comment]
No problem! Thanks a lot for your update!
