### ISSUE TITLE
Dropdown and MultiSelect: TS2322 compilcation error

### ISSUE THREAD

**Issue by sid-6581** [primefaces/primevue#2845]
### Describe the bug

In PrimeVue 3.16, `DropdownProps` and `MultiSelectProps` were changed to extend `HTMLDivElement`. This causes TS2322 compilation errors:

```
error TS2322: Type '{ id: string; modelValue: string | null | undefined; options: string[] | undefined; filter: true; }' is not assignable to type 'IntrinsicAttributes & DropdownProps & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
  Type '{ id: string; modelValue: string | null | undefined; options: string[] | undefined; filter: true; }' is missing the following properties from type 'DropdownProps': align, addEventListener, removeEventListener, accessKey, and 276 more.
```

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by jzs11** [comment]
Temp solution is to open the d.ts file to remove the HTMLDivElement

**Comment by oliviermattei** [comment]
Hello,

 error TS2322: Type '{ modelValue: MENU_OPENING_TYPE | undefined; options: MENU_OPENING_TYPE[]; placeholder: string; }' is not assignable to type 'ComponentProps<GlobalComponentConstructor<Dropdown>>'.
  Type '{ modelValue: MENU_OPENING_TYPE | undefined; options: MENU_OPENING_TYPE[]; placeholder: string; }' is missing the following properties from type 'DropdownProps': align, addEventListener, removeEventListener, accessKey, and 284 more.

32           <Dropdown

I'm actually on the 3.22.4 and I have the same problem, I would like to reopen the issue.
