### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by pribadi1st** [primefaces/primevue#2847]
### Describe the bug

Hi, i'm working on nuxt3 project and want to implement primevue 3

i tried to follow the documentation and this [issue](https://github.com/primefaces/primevue/issues/975)
however i encounter the same error

error result: 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/26956664/184720541-4f42a36b-3ab3-4916-a552-ecb7241a7290.png">

my primevue.js
`import { defineNuxtPlugin } from "#app";
import PrimeVue from "primevue/config";
// import Toast from "primevue/toast";
// import ToastService from 'primevue/toastservice';
// import Skeleton from 'primevue/skeleton';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(PrimeVue, {ripple: true});
    // nuxtApp.vueApp.use(ToastService);
    // // nuxtApp.vueApp.component('Button', Button);
    // nuxtApp.vueApp.component('Skeleton', Skeleton);
    // nuxtApp.vueApp.component('Toast', Toast);
   //other components that you need
   return {
        provide: {
        //    toast: nuxtApp.vueApp.config.globalProperties.$toast
        }
    }
});`

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Please check this example [https://codesandbox.io/s/elastic-lamarr-xh0b8u?file=/plugins/primevue.js](https://codesandbox.io/s/elastic-lamarr-xh0b8u?file=/plugins/primevue.js).

If problem is still persist, please send us a codesandbox link so we can replicate the issue.

**Comment by pribadi1st** [comment]
build: {
    transpile: ["primevue"]
  }
  
  this solve my problem, thank you, i dont know why i couldnt find it on documentation
