### ISSUE TITLE
Dropdown:  Cannot read properties of undefined (reading 'replaceAll')

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#2848]
### Describe the bug

![image](https://user-images.githubusercontent.com/16963395/184734459-4aa96fc9-43e0-4a69-9476-c6aaf72fe4c5.png)
![image](https://user-images.githubusercontent.com/16963395/184734480-ba07f850-d3c5-4bce-ab44-8442c1f14c74.png)

![image](https://user-images.githubusercontent.com/16963395/184735004-bd67ef74-f7fc-4675-80f6-cb37be31e59e.png)
![image](https://user-images.githubusercontent.com/16963395/184736665-4a07cd31-f7b6-4805-a722-05df690a20f0.png)
![image](https://user-images.githubusercontent.com/16963395/184739913-c9a8f263-7570-4eae-9325-59a2ac9e4073.png)
 

After the update, all my Dropdowns were broken
It is difficult to say why this happened. I just upgraded prime

Moreover, even Dropdown in the DataTable broke. So it's probably my fault

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by S-le** [comment]
You can set the 'selectionMessage' property with type String in primevue config.locale (`locale: { selectionMessage: ''  }`). But I don't think this is a fix for production.

**Comment by tugcekucukoglu** [comment]
While creating an issue, please share a codesandbox so we can replicate the issue.

**Comment by NeluQi** [comment]
> While creating an issue, please share a codesandbox so we can replicate the issue.

It is very difficult to make a sandbox, because it is not even clear why this happened. I just updated prime and everything broke. I'll try to explore more soon, I'll write if possible

**Comment by NeluQi** [comment]
> You can set the 'selectionMessage' property with type String in primevue config.locale (`locale: { selectionMessage: '' }`). But I don't think this is a fix for production.

It didn't solve the problem


![image](https://user-images.githubusercontent.com/16963395/184817109-8f40b4c7-84d4-4c7b-b2a3-8fcedb9fad05.png)
![image](https://user-images.githubusercontent.com/16963395/184817178-80a9fb38-c182-4be3-8ad8-1537c4342d3e.png)
![image](https://user-images.githubusercontent.com/16963395/184817204-42b008d5-f9d8-4be7-b7aa-826393a89b3c.png)

**Comment by NeluQi** [comment]
Official codesandbox crashes when scrolling Virtual Scroll (1000 Items) and Lazy

![image](https://user-images.githubusercontent.com/16963395/184818256-b277437e-87fa-4056-a14e-dc08e2446fdd.png)

https://codesandbox.io/s/i5zwyu

**Comment by NeluQi** [comment]
> While creating an issue, please share a codesandbox so we can replicate the issue.

Alternatively, add a null check to filterResultMessageText

https://github.com/primefaces/primevue/issues/2848#issuecomment-1216209674

**Comment by mertsincan** [comment]
@NeluQi Thanks a lot for your report!

**Comment by NeluQi** [comment]
> @NeluQi Thanks a lot for your report!



If it was a matter of translations. Update the documentation page (add missing translation keys)
![image](https://user-images.githubusercontent.com/16963395/185122638-d973ea41-11af-420c-9b89-dfb49854900d.png)

**Comment by tugcekucukoglu** [comment]
Live updated [https://www.primefaces.org/primevue/locale](https://www.primefaces.org/primevue/locale)

Thanks,

**Comment by edengal283** [comment]
hey, so how did you solve this problem?

**Comment by edengal283** [comment]
hey, did you solve the problem? I have it now using version 3.24.0
