### ISSUE TITLE
vue-cli-service build produce code with absoluthe path

### ISSUE THREAD

**Issue by vanna80** [primefaces/primevue#285]
I have cloned repo and run a build script. A resulted code has references (to css, png, etc. files) as absoluthe path.
Example from index.html: "..... href=/primevue/showcase/favicon.ico ..."
The app must be served from /primevue/showcase folder, otherwise it doesn't work.

**Comment by cagataycivici** [comment]
That's is where we deploy in prod yes. In dev it is from "/" though. See vue.config.js.
