### ISSUE TITLE
cdn version not work

### ISSUE THREAD

**Issue by yulinliu** [primefaces/primevue#2851]
### Describe the bug

cdn version not work

primevue@3.16.0/core/core.min.js

line number 13 , is undefined

### Reproducer

https://unpkg.com/primevue@3.16.0/core/core.min.js

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
Duplicate [#2844 ](https://github.com/primefaces/primevue/issues/2844)
