### ISSUE TITLE
Overlay components don't work with SSR

### ISSUE THREAD

**Issue by oooowl** [primefaces/primevue#2853]
### Describe the bug

Password: cannot SSR

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

 "nuxt": "3.0.0-rc.8"

**Comment by sfxcode** [comment]
It seems that the actual 3.16 Release have general problems with ssr and hydration.
At the moment components are not usable in SSR mode.

**Comment by mertsincan** [comment]
Thanks a lot, @oooowl and @sfxcode! Fixed now. We'll release v3.16.1 asap.
