### ISSUE TITLE
OverlayPanel: Show/Toggle without event

### ISSUE THREAD

**Issue by dcarapic** [primefaces/primevue#2854]
### Describe the feature you would like to see added

Currently the OverlayPanel can only be displayed from within an event handler. However when using debouncing (for example on a search input control) it does not seem possible to show the OverlayPanel as the debounced method fires

### Is your feature request related to a problem?

I would like to show OverlayPanel beneath a text input (InputText) after the user finishes typing (debounced).

### Describe the solution you'd like

Show/Toggle methods should not require an event but only a target.

### Describe alternatives you have considered

The OverlayPanel seems to be the best fit for a making an input search control which displays a list of results after some time (debounced).

**Comment by martinszeltins** [comment]
I also need to show the Overlay Panel but not as a result of a mouse click but as a result of an API event that occurs. But this is not possible since it requires an event right now.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
