### ISSUE TITLE
DataTable: Pagination isn't working as expected

### ISSUE THREAD

**Issue by zachlearnscode** [primefaces/primevue#2857]
### Describe the bug

I will attempt to make this as concise as possible, but the source of the bug isn't overly clear.

I have an app that utilizes the lazy DataTable component on several pages. Yesterday, one of my co-workers noticed that the pagination controls broke across the app after visiting a specific page, call it "Page A", which contains a DataTable, call it "DataTable1".

After navigating away from Page A, the DataTable's `page` event doesn't seem to be firing. The table's other functionality, including `sort` events all seem to be working just fine. **Essentially, the DataTable component's** `page` **isn't firing as expected.**

One possible issue is that we've placed duplicate `ref` values on multiple DataTables across the site. This hasn't caused any problems up to this point. Perhaps this is a rendering or reactivity issue? i.e. Is it possible that Vue sees two DataTable components with the same `ref` value and that's causing errors?

### PrimeVue version

^3.12.4

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. If the problem still persists, please create a new issue with a reproducer link.
