### ISSUE TITLE
InputNumber: disabled prop is not passed to input text

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#2864]
### Describe the bug

InputNumber: disabled prop is not passed to input text, only buttons

### PrimeVue version

3.16.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

Both input field and buttons should be disabled

**Comment by darmanovic** [comment]
Same thing is happening with Calendar component. "Disabled" attribute disables only button, but not the native input

**Comment by darmanovic** [comment]
Hey you haven't fixed Calendar component!
