### ISSUE TITLE
Message: Doc typo

### ISSUE THREAD

**Issue by abakucz** [primefaces/primevue#2865]
### Describe the bug

Message component has few silly typos in Styling section - [docs](https://www.primefaces.org/primevue/message).

Now there is:
<html>
<body>

### Problem
p-messages | Container element.
-- | --
p-messages-info | Container element when displaying info messages.
p-messages-warn | Container element when displaying warning messages.
p-messages-error | Container element when displaying error messages.
p-messages-success | Container element when displaying success messages.
p-messages-close | Close icon.
p-messages-icon | Severity icon.
p-messages-text | Content of a message.

</body>
</html>

### Solution
All `p-messages-*` should be `p-message-*` (without **s**).

### PrimeVue version

3.16.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Fixed.

Thank you.
