### ISSUE TITLE
Custom Icon Support

### ISSUE THREAD

**Issue by siba2893** [primefaces/primevue#2869]
### Describe the feature you would like to see added

I believe in letting the user decide the icon library of their choosing is the right way to go. So why not exploring the usage of the largest library of icons available. Unplugin Icons

### Is your feature request related to a problem?

I want to use food icons which I cannot because they do not exist in primeicons and my apps is a food based app.

### Describe the solution you'd like

It would be cool to be able to pass a slot for changing the icon of elements. For Example in the Menu component I would love to be able to pass the Unplugin Icon component to render.

**Comment by tugcekucukoglu** [comment]
Please check the MenuModel [https://primefaces.org/primevue/menumodel](https://primefaces.org/primevue/menumodel). Menuitem has `icon` property for this kind of usage.

**Comment by ashokgelal** [comment]
I also want what @siba2893 is asking. Maybe I'm missing something with @tugcekucukoglu's reply and that there could be something missing in the documentation but how does that answer what @siba2893 is asking? That is, allow us to use any icon we want. Right now, menu model icon property only receives a string corresponding to primevue icon name, which is very very limiting.
