### ISSUE TITLE
Calendar: Button Bar Slots

### ISSUE THREAD

**Issue by account00001** [primefaces/primevue#2870]
### Describe the feature you would like to see added

The current button bar leaves some to be desired. 
![image](https://user-images.githubusercontent.com/52767641/185822367-74a6ff0f-529a-4785-8d06-7bbe9e7b2208.png)

It'd be great to expose slots so I can add my own buttons to it like so
![image](https://user-images.githubusercontent.com/52767641/185822706-3039c14d-75d6-46a3-85db-7e9aceaf22f3.png)
Or even replace the existing buttons all together.

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Something like...

In Calendar.vue
```
<div class="p-datepicker-buttonbar" v-if="showButtonBar">
    <slot name="buttons">
        <CalendarButton type="button" :label="todayLabel" @click="onTodayButtonClick($event)" class="p-button-text"
            @keydown="onContainerButtonKeydown" />
        <CalendarButton type="button" :label="clearLabel" @click="onClearButtonClick($event)" class="p-button-text"
            @keydown="onContainerButtonKeydown" />
    </slot>
</div>
```

On use:
```
<Calendar v-model="date" :minDate="minDate" :maxDate="maxDate">
    <template #buttons>
        <CalendarButton type="button" :label="minLabel" @click="onMinButtonClick($event)" class="p-button-text" @keydown="onContainerButtonKeydown"/>
        <CalendarButton type="button" :label="maxLabel" @click="onMaxButtonClick($event)" class="p-button-text" @keydown="onContainerButtonKeydown"/>
    </template>
</Calendar>
```

### Describe alternatives you have considered

Alternative would be to have a separate button outside the calendar which breaks the flow.

### Additional context

A classic example would be the minDate and maxDate, adding buttons to jump to those instead of just "Today."

**Comment by joaomarcelofm** [comment]
This would be a great addition indeed 👍
The use case for us is to provide some presets for the user, for example `Last x days` or `Next x days`.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
