### ISSUE TITLE
Calendar: calendar closes on scroll when calendar is in Sidebar component

### ISSUE THREAD

**Issue by tjackson-vert** [primefaces/primevue#2874]
### Describe the bug

We have calendar on the Sidebar and it closes automatically when we scroll. 

`<Calendar
      :showButtonBar="true"
      dateFormat="mm/dd/yy"
      :manualInput="false"
      appendTo="self"
    />`

### PrimeVue version

v3.16.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1) Add Calendar on Sidebar component
2) Click side bar
3) Click Calendar textbox
4) Scroll and you see calendar disappears
5) Calendar won't open again when you click the same textbox immediately after scroll  

### Expected behavior

Keep the calendar open when we scroll, same behavior like when we have calendar not in sidebar or popup.

**Comment by bahadirsofuoglu** [comment]
Hi,
Best practice is use 'append=body' (default props). But if you want to use it like this I think increasing sidebar-content(.p-sidebar-content) box width and height should work.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by Arthurjim** [comment]
Hi, Im having the same error in version 4.4.1.
