### ISSUE TITLE
Column selectionMode="multiple" isnot disabled props

### ISSUE THREAD

**Issue by shenshuai89** [primefaces/primevue#2876]
### Describe the feature you would like to see added

<DataTable :value="products" v-model:selection="selectedProducts3" dataKey="id" responsiveLayout="scroll" >
      <Column selectionMode="multiple" headerStyle="width: 3em"></Column>
      <Column field="code" header="Code"></Column>
      <Column field="name" header="Name"></Column>
      <Column field="category" header="Category"></Column>
      <Column field="quantity" header="Quantity"></Column>
  </DataTable>
<img width="426" alt="image" src="https://user-images.githubusercontent.com/5692360/186152084-2f168feb-69ee-4849-ad2d-3b61dbdcab94.png">

**Comment by mertsincan** [comment]
Hi,

Maybe, this link can help to you; https://dev.to/mertsincan/handling-big-data-on-datatable-with-checkbox-selection-multiselect-4hgc#checkbox-condition

Best Regards,
