### ISSUE TITLE
TreeTable: Enable to highlight elements with custom classes

### ISSUE THREAD

**Issue by mihalcea-bogdan-daniel** [primefaces/primevue#2878]
### Describe the feature you would like to see added

Add a custom class if an element is inside a list of highlighted classes. Similar to expanded keys, but this would be highlighted keys. The selection should still work even if the element is highlighted.

### Is your feature request related to a problem?

No.

### Additional context

I have a TreeTable with 2 columns, one column with static data the other with user inputs. I would like to be able to highlight the row if the values in the two columns are different.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
