### ISSUE TITLE
OverlayPanel when set appentTo by id incorrect

### ISSUE THREAD

**Issue by vanthasokongofficial** [primefaces/primevue#2879]
### Describe the bug

OverlayPanel when I appendTo without body tag show problem

### PrimeVue version

3.16.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Hi,
Could you send any link for reproducing the behavior? I tried but I could not find any issue.
