### ISSUE TITLE
Password: Unable to add invalid event listener after 3.16

### ISSUE THREAD

**Issue by dpogue** [primefaces/primevue#2880]
### Describe the bug

As of PrimeVue 3.16, adding `@invalid="invalidHandler"` to a Password component no longer calls the `invalidHandler` method when the underlying password input emits the `invalid` DOM event.

This worked in 3.15 and earlier. It's probably related to `v-bind="$props"` changing to `v-bind="inputProps"`, but there doesn't seem to be a way to pass an event listener in through `inputProps`.

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Sorry for the regression. Password was in a heavy accessibility development.

For the v3.17.0, invalid event could be used in two different ways:

`<Password :inputProps="{oninvalid: onInvalid}"></Password>`

or 

`<Password @invalid="onInvalid""></Password>`
