### ISSUE TITLE
SubHeader Grouping with mdc-light-indigo

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#2883]
### Describe the bug

SubHeader Grouping doesn't work with theme 'mdc-light-indigo'. The headers overwrite eachother.

![grafik](https://user-images.githubusercontent.com/81289327/186391771-538bb36f-5443-48b6-b96b-35903bf7a68d.png)

https://codesandbox.io/s/quirky-dream-pxthg1

### PrimeVue version

3.16.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Hi, Does the problem persist? I could not repeat it.
