### ISSUE TITLE
Password: When its value is dynamically set, the strength indicator is not updated

### ISSUE THREAD

**Issue by ricardobrunosr** [primefaces/primevue#2885]
### Describe the bug

When Password component value is dynamically set, and when user focus the input the strength indicator info is not updated.
My form has a password generator that sets the value of the component Password, but the strength indicator is never updated not even on focus event, user has to change the value manually to trigger the update of the strength indicator.

### PrimeVue version

3.12.6

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Fixed via [#2934 ](https://github.com/primefaces/primevue/pull/2934)
