### ISSUE TITLE
Menu: Keyboard navigation (Accessibility)

### ISSUE THREAD

**Issue by ian4uia** [primefaces/primevue#2887]
### Describe the feature you would like to see added

I would like keyboard navigation capability for the Menu component. When a menu is toggled by a button, which is often the case, the menu can be activated by the keyboard however the user cannot select the menu items.

### Is your feature request related to a problem?

People who cannot use a mouse cannot navigate via the keyboard.

### Describe the solution you'd like

As with the Dropdown and Menubar, the user should be able to cycle up and down through the menu items using the arrow keys and select an item by pressing Enter.

**Comment by tugcekucukoglu** [comment]
Accessibility for PrimeVue is under development. We can not guarantee that the implementation of Menu will be the same with Dropdown. It will be updated for the next versions.

Thanks for your understanding.
