### ISSUE TITLE
Password: Initial value is not displayed

### ISSUE THREAD

**Issue by service-paradis** [primefaces/primevue#2894]
### Describe the bug

If we use the Password component with an initial value, the input will stay empty. Here is the reason for this:

- The password component does not pass directly the value received as props to the inner input. I uses `:value="d_value"`.
- `d_value` is defined by watching changes on the prop `value` (https://github.com/primefaces/primevue/blob/2.x/src/components/password/Password.vue#L95)
- This watch is not triggered initially since it is missing the `immediate` attribute

### PrimeVue version

2.10.0

### Vue version

2.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Use the password component and use a variable with some content as `v-model`:

```html
<Password v-model="myPasswordWithInitialValue" />
```

2. Look at the generated input, it will be empty.
![image](https://user-images.githubusercontent.com/12817388/186958669-53fb6721-f7c9-4016-bfad-32286444ac6a.png)

### Expected behavior

The generated input should display some content. Ex. 
![image](https://user-images.githubusercontent.com/12817388/186958738-51dbed4d-85e0-4524-b923-679f8abf1e68.png)

**Comment by bahadirsofuoglu** [comment]
Fixed
#2933
