### ISSUE TITLE
TreeTable: Wrapping tree table node text beneath tree table node icon

### ISSUE THREAD

**Issue by wojciechdydacki** [primefaces/primevue#2897]
### Describe the bug

In TreeTable component, if a text of a node is long enough to be placed in more than one line, it gets wrapped into a new line, starting right beneath the tree table node icon.  

### PrimeVue version

3.12.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

104.0.5112.102 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. Run the application in the development environment of your choice.
2. Go to /public/demo/data/treetablenodes.json
3. In line 127. of the treetablenodes.json file, replace "Work" with "Work Work Work Work Work Work Work Work Work Work Work", to make sure the phrase is long enough to be split into two lines.
4. In the application, navigate to the [env-of-choice]/treetable path.
5. In the Basic (or any other) tree table, expand node "Documents". "Work (...)" should appear as the first child node of it.
6. Observe the second line of the "Work (...)" node being broken in such way that wraps the node icon (arrow) from beneath.

### Expected behavior

If the node text is long enough to be broken into two or more lines, each of those node text lines should appear at the right side of the node icon (arrow) and start from the same position.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
