### ISSUE TITLE
DataTable: missing registration component?

### ISSUE THREAD

**Issue by michelebroggi** [primefaces/primevue#29]
Following the basic example of your documentation, DataTable does not work.

I report the console log error:

> vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <Column> - did you register the component correctly? For recursive components, make sure to provide the "name" option...

**Dependencies**
- Vue 2.6.10
- core-js 2.6.5
- primevue-1.0.0-beta6

**Comment by fuvito** [comment]
Workaround: introduce the component in main.js,

i.e. Column:

import Column from "primevue/components/column/Column";
.
.
.
Vue.component('Column', Column);

**Comment by cagataycivici** [comment]
1.0.0-beta.6 should have fixed this. Could you please confirm?

**Comment by fuvito** [comment]
Cagatay, after upgrading to 1.0.0-beta.6 I am still seeing the same behavior. I am having problem with "Column". As long as it is registered like I mentioned before, it works, otherwise I am getting the same error as Michele's

**Comment by michelebroggi** [comment]
> 
> 
> 1.0.0-beta.6 should have fixed this. Could you please confirm?

No, still have the same problem in 1.0.0-beta.6

**Comment by cagataycivici** [comment]
Hmm, I can't see this with beta.6, today beta.7 is released with the new TreeTable and InputMask in addition to resizable columns for DataTable, please update to beta.7 and hopefully it will fix it.

https://www.primefaces.org/primevue-1-0-0-beta-7-released/

**Comment by fuvito** [comment]
Cagatay,

If you like, I've added you as a collaborator to https://github.com/fuvito/vuepv.git, you can see the problem over there,

(after you login go to Admin  --> Tiers)

Will send you login credentials through other means,

One note: I converted above project to TypeScript, and started getting other errors, then created a file Column.d.ts under ..\node_modules\primevue\components\column, then it started working again,

--fuat

**Comment by cagataycivici** [comment]
Ok, it happens with Typescript only, fixing now.
