### ISSUE TITLE
Context Menu throw error after update to 1.3.1

### ISSUE THREAD

**Issue by ngohuunam** [primefaces/primevue#291]
Hi

After update to 1.3.1, Context Menu throw type error when open
![ContextMenu Error](https://user-images.githubusercontent.com/3610240/80119765-53842c80-85b4-11ea-8db1-e62c6f5fda7f.jpg)
![ContextMenu Error 1](https://user-images.githubusercontent.com/3610240/80119860-744c8200-85b4-11ea-8e8e-ace863ae7c47.jpg)

**Comment by cagataycivici** [comment]
Fixed for 1.3.2 now, thank you;

https://primefaces.org/primevue/showcase/#/contextmenu
