### ISSUE TITLE
Datatable loading property does not work after upgrade

### ISSUE THREAD

**Issue by frnk01** [primefaces/primevue#2914]
After upgrading primevue to 3.16.2 the loading prop on datatable does not work.

`<DataTable
        :value="transactions.listGroupedTransactions"
        :paginator="true"
        :rows="30"
        :loading="true"`

Tested with hardcoded value and #empty template is still showing instead of #loading template.

**Comment by ian4uia** [comment]
Hi frnk01. I have also upgraded to 3.16.2 and my Datatable #loading template / slot is working correctly.  Can you provide a reproduction of the bug?  (Maybe use the Prime example https://www.primefaces.org/primevue/datatable/lazy as a starting point)

**Comment by tugcekucukoglu** [comment]
DataTable needs to know which row will be the first, just as it needs to know the number of rows.

https://stackblitz.com/edit/lxpxlz-93qeul?file=src%2FApp.vue%3AL106
