### ISSUE TITLE
Add `autoFilterFocus`property to Dropdown and MultiSelect

### ISSUE THREAD

**Issue by ArinSantry** [primefaces/primevue#2916]
### Describe the feature you would like to see added

When a multiselect (with filter enabled) dropdown is opened, auto focus on the filter input. PrimeNG already has this feature: https://www.primefaces.org/primeng/multiselect

### Is your feature request related to a problem?

When I try to give focus to the filter in a multiselect using Vue's .focus() method, it focuses on the multiselect component itself, not the filter specifically. This feature would make the use of the multiselect filter easier, since the user will not need to click twice to find what they want in a potentially very long list of items.

### Describe alternatives you have considered

I have tried to use Vue's .focus() method on the multiselect, but it focuses on the component itself, not the filter.

**Comment by jamiewaese-uncharted** [comment]
Thank you!
