### ISSUE TITLE
Disable full row in datatable.

### ISSUE THREAD

**Issue by strateego** [primefaces/primevue#292]
I was looking through the documentation and could not find a way to disable a full row in a datatable. I would like to be able to show rows in the table that are not selectable.

I looks like primefaces might have a similar feature with the disableSelection attribute.

**Comment by mr83-uw** [comment]
This appears to be a duplicate of https://github.com/primefaces/primevue/issues/324

**Comment by cagataycivici** [comment]
Tracked at 324.
