### ISSUE TITLE
Sidebar: scoped style overrides not taking effect

### ISSUE THREAD

**Issue by robbienohra** [primefaces/primevue#2922]
### Describe the bug

Style overrides using deep operator not working on sidebar.

E.g.

```
<style scoped>
:deep(.p-sidebar) {
  background: magenta;
  border: thin solid red;
};
```

If you remove `scoped` and the `deep` operator (i.e. apply the override globally) then the override works.

We suspected that this is due to usage of the portal + transition components [here](https://github.com/primefaces/primevue/blob/master/src/components/sidebar/Sidebar.vue#L2).

We tested this hypothesis by copying the source code and removing the transition + portal and adding the deep operator + scss override and it appeared to take effect (note in the recording the sidebar of course appears instantaneously in that case).

https://user-images.githubusercontent.com/28514482/187959784-0f8b381b-c4a2-432f-958c-dedcdafe990a.mov

The road to solutioning this then appears to be how we get the deep operator to work — if this is possibly — while simultaneously using the portal + transition parent elements.

### Reproducer

https://codesandbox.io/s/cranky-solomon-9scn8k

### PrimeVue version

3.12.4

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 104.0.5112.101

### Steps to reproduce the behavior

Trigger opening of sidebar — observe style overrides not taking effect.

### Expected behavior

Scoped SCSS class theme overrides for the sidebar using the deep operator should work as indicated in [theming documentation](https://www.primefaces.org/primevue/theming).

**Comment by tugcekucukoglu** [comment]
As you said Sidebar uses Portal and the default appendTo property is `body`. So there is no need to use scoped styling and `deep` selector.
