### ISSUE TITLE
Paginator: better responsivity defaults

### ISSUE THREAD

**Issue by robbienohra** [primefaces/primevue#2923]
### Describe the feature you would like to see added

The default responsivity wrapping behaviour for the paginator occupies a significant amount of vertical space.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/28514482/187961334-42cddc15-c5c9-4058-a84a-54418d477181.png">

### Is your feature request related to a problem?

Yes responsivity-wise.

### Describe the solution you'd like

There a number of alternatives for lower viewport sizes including:

- reducing the visible page number options
- previous + next + page dropdown selection for specific page

Another approach could be — similarly to how there is a [data table responsive](https://primefaces.org/primevue/datatable/responsive) prop (with `stack` and `scroll` options) — to have a prop that allows for a "collapsed" view on mobile (similar to the custom collapsed view [here](https://primefaces.org/primevue/paginator)). The idea would be to auto-morph from default to collapsed on mobile (via a specified breakpoint — although this case as well has some wrapping issues). Or, to take it one step further, allowing for a custom user-specified template for the mobile case (again as specified by a breakpoint).

<img width="806" alt="image" src="https://user-images.githubusercontent.com/28514482/187963115-2df2849c-2e8c-4081-bd39-8bb00901fdf5.png">

### Describe alternatives you have considered

Using [vue3-mq](https://www.npmjs.com/package/vue3-mq) to manually morph from a default to a custom paginator at specified breakpoints — although this likely leads to integration-level issues w.r.t. data-table that we'd prefer to avoid.

### Additional context

NA

**Comment by tugcekucukoglu** [comment]
You could check the latest version for this: https://primevue.org/paginator/#responsive
