### ISSUE TITLE
Calendar: inputProps typescript error ts(2740)

### ISSUE THREAD

**Issue by suntel-nagamine** [primefaces/primevue#2925]
### Describe the bug

In order to set autocomplete on the calendar input.
I get error number 2740 in typescript when I write the following.

```
:inputProps="{ autocomplete: 'off' }"
```

Error message
```
Type '{ autocomplete: 'off' }' is missing the following properties from type 'inputProps': accept, align, alt, capture and 335 more.
```

You are prompted to set all values of HTMLInputElement.
Please consider changing the type of inputProps to any.

Or am I using it incorrectly?

### PrimeVue version

3.16.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by mertsincan** [comment]
Fixed for the next version. Thanks a lot for your report!
