### ISSUE TITLE
DynamicDialog: Improved onClose Function

### ISSUE THREAD

**Issue by jjackevans** [primefaces/primevue#2931]
### Describe the feature you would like to see added

The DynamicDialog has an `onClose` event which is only invoked on the close event.

If one wanted to add restrictions to the close event (like using a ConfirmDialog to verify that the user wants to delete unsaved data), they are required to implement their own close button, in which case the user may still override this check with the button in the header.

I propose having the `onClose` return a boolean value whether to continue the close event.

### Is your feature request related to a problem?

No control over dialogs being closed.

### Describe the solution you'd like

```
  dialog.open(x.component, {
    props: {
      header: x.header,
      modal: true,
      class: x.class,
    },
   onClose: (opts) => {
       confirm.require({
            message: 'Are you sure you want to close - you have unsaved data?',
            header: 'Confirmation',
            reject: () =>  return false,
            accept: () => return true
          })
   }
})

```

### Describe alternatives you have considered

It is possible to load the same dialog when the user chooses to not destroy the dialog.
This is not an optimal solution for clear reasons.

**Comment by veco9** [comment]
It would also be nice to control ConfirmDialog being closed the same way (via return value).

e.g. changing this:
```
  accept() {
      if (this.confirmation.accept) {
          this.confirmation.accept();
      }
      this.visible = false;
  }
```
to this:

```
  accept() {
      if (this.confirmation.accept) {
          this.visible = this.confirmation.accept();
      } else {
         this.visible = false;
      }    
  }
```

A common use case for this involves using a confirm dialog with input that needs to be passed when accepting something, such as a remark or footnote. In this scenario, I would appreciate having control over the closing process, as I need to validate the input. There is a possibility that the input may be invalid, and in such cases, it is necessary for the user to remain on the dialog.
