### ISSUE TITLE
ProgressBar: Bind colour in props

### ISSUE THREAD

**Issue by jjackevans** [primefaces/primevue#2932]
### Describe the feature you would like to see added

Ability to change the colour of the ProgressBar with props (and bind this dynamically).

### Is your feature request related to a problem?

It's very hacky to fix otherwise.

### Describe the solution you'd like

`<ProgressBar :color="data.colour"/>`

### Describe alternatives you have considered

```
          let el = document.getElementById('pbid')
                if(el !== undefined && el !== null && el.hasChildNodes()){
                  let pbv = el.children[0]
                  pbv.style.backgroundColor = some_dynamic_colour;
                }
```

**Comment by bahadirsofuoglu** [comment]
Hi, 
We can consider the color prop. But the following usage may also help you if you are using vue3.
`
<style scoped>
.your-parent-class :deep(.p-progressbar-value) {
    background: v-bind(dynamicColor);
}
</style>
`

**Comment by jjackevans** [comment]
Thanks @bahadirsofuoglu .

Could you elaborate how this would work with a variable number of ProgressBars, with different id's?
For example,
<ProgresssBar id="pb1" :color="dataitem[1].color" />
<ProgresssBar id="pb2" :color="dataitem[2].color" />
<ProgresssBar id="pb3" :color="dataitem[3].color" />
....
<ProgresssBar id="pbn" :color="dataitem[n].color" />

**Comment by bahadirsofuoglu** [comment]
I realize you don't fully cover the situation. I shared it in the hope that it can cover some situations for others. Thank you for explaining in detail.
