### ISSUE TITLE
Unified scrollbars

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#2936]
### Describe the feature you would like to see added

Unified scrollbars across components that can be scrolled

### Is your feature request related to a problem?

The `ScrollPanel` component allows us to have customized scrollbars for element. The downside of that is that other components which content can be scrolled are using native scrollbars from the browser which is inconsistent when using ScrollPanel component inside app.

### Describe alternatives you have considered

I've considered hooking up separate library to handle scrollbars or even making custom component that ecapsulates `Dropdown` and fully overrides content but it does not seem like a good idea.

**Comment by JohnCampionJr** [comment]
This would be really nice to see on the dropdowns and such.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
