### ISSUE TITLE
TreeTable: Add custom header for column

### ISSUE THREAD

**Issue by spore9** [primefaces/primevue#2941]
### Describe the feature you would like to see added

In primevue 2.x treetable component I would like to be able set a custom header via slots. Like this:
                <template #header>
                    <Button type="button" icon="pi pi-cog"></Button>
                </template>

### Is your feature request related to a problem?

I need to add tooltips to my headers in treetable component, but for now I can set them only as a plain text via header attribute.

### Describe the solution you'd like

As I see, the easiest way to do this, is to add "header" slot to column header

### Describe alternatives you have considered

As I understand this feature works in primevue 3, but for sake of stability I still use version 2.x

**Comment by tugcekucukoglu** [comment]
For some technical reasons, we are unable to do this at the moment.

Thanks for your understanding.
