### ISSUE TITLE
Dialog: ReferenceError: display is not defined

### ISSUE THREAD

**Issue by Mikkohaa** [primefaces/primevue#2944]
### Describe the bug

Attempting to close Dialog will throw "ReferenceError: display is not defined".

This can be reproduced by creating vue project with build tools (https://vuejs.org/guide/quick-start.html#with-build-tools), adding PrimeVue and Dialog component to the project by following the instructions in https://primefaces.org/primevue/setup and building with script setup section being not empty in the same component where Dialog is used.

Error only happens in production build, NOT in dev mode. Build process doesn't throw any errors.

**package.json:**
```
{
  "name": "vuetest",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 4173"
  },
  "dependencies": {
    "primeicons": "^5.0.0",
    "primevue": "^3.16.2",
    "vue": "^3.2.38",
    "vue-router": "^4.1.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.3",
    "vite": "^3.0.9"
  }
}
```

### PrimeVue version

3.16.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create new project with vue build tool instructions (https://vuejs.org/guide/quick-start.html#with-build-tools)
2. "No" to all prompts except "Add Vue Router for Single Page Application development?"
3. cd your-project-name
4. npm install
5. npm install primevue@^3.16.2 --save
6. npm install primeicons --save
7. Add PrimeVue to project as shown in https://primefaces.org/primevue/setup, see below for changed files
8. npm run build
9. npm run preview
10. Navigate to About page, click the button to open dialog
11. Trying to close the dialog will result in error "ReferenceError: display is not defined"
12. (If script setup is emptied in AboutView.vue, the error will not occur after building)
13. (Error will not occur in dev mode (npm run dev))

**main.js:** 
```
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import PrimeVue from 'primevue/config';
import Dialog from 'primevue/dialog';

import 'primevue/resources/themes/arya-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';

import './assets/main.css'

const app = createApp(App)

app.use(router)
app.use(PrimeVue);
app.component('Dialog', Dialog);
app.mount('#app')
```

**view/AboutView.vue:** 
```
<script setup>
  // anything, even comment in here will cause the ReferenceError in preview mode after building
</script>

<template>
  <div class="about">
    <h1>This is an about page</h1>
    
    <button @click="display = !display">show dialog</button>

    <Dialog v-model:visible="display">
      dialog content
    </Dialog>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        display: false
      }
    }
  }
</script>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>

```

### Expected behavior

Clicking "close" button in Dialog closes the dialog in production mode.

**Comment by bahadirsofuoglu** [comment]
I cannot reproduce. Please try version 3.17.0.
