### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NoDozing** [primefaces/primevue#2945]
Could someone please put together documentation on how to get this working. I'm very new to VUEjs. I'm looking into using PrimeVUE. I've already done the PrimeVUE installs, but got immediate error when I try to run. After doing vue add babel, I'm getting "Invalid options in vue.config.js: child "transpileDependencies" fails because ["transpileDependencies" must be an array]". 

Thanks for adding it to README

**Comment by bahadirsofuoglu** [comment]
Hi,
You can find the detailed document [here](https://www.primefaces.org/primevue/setup). We also have a discord channel. As PrimeVue community, we help each other. You can also access the Discord channel [here](https://discord.com/invite/gzKFYnpmCY).
