### ISSUE TITLE
Tooltip: Unavailable configuration breaks z-index

### ISSUE THREAD

**Issue by franklx** [primefaces/primevue#2946]
### Describe the bug

The z-index mechanism provided by utils/ZIndexUtils get broken by a bug in the Tooltip component.
In the `beforeMount` hook component loads `config.zIndex.tooltip` from `options.instance.$primevue` that is undefined (
[tooltip/Tooltip.js](https://github.com/primefaces/primevue/blob/master/src/components/tooltip/Tooltip.js#L327)).
Being `$_ptooltipZIndex` undefined breaks z-index stack provided by ZIndexUtils.add/clear affecting other components.
Apart from fixing the bug a sensible default should be provided (1100 for example).

### PrimeVue version

3.16.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a simple view like this:
```html
<Dialog>
    <Button v-tooltip="test tooltip">
   <Dropdown options="...">
</Dialog>
```
2. Open dropdown: it should work
3. Hover on button triggering tooltip
4. Tooltip will not work
5. Dropdown doesn't work anymore: dropdown overlay will be behind dialog

**Comment by tugcekucukoglu** [comment]
I've tried to create an example using [vite-quickstart](https://github.com/primefaces/primevue-quickstart-vite), but could not replicate the issue.

Did you have a codesandbox link or a repo, to replicate the issue?

**Comment by tugcekucukoglu** [comment]
We will check it again. Thanks for the repo.

**Comment by tugcekucukoglu** [comment]
Please follow this ticket https://github.com/primefaces/primevue/issues/2468

You could use

```
<script setup>
import { usePrimeVue } from "primevue/config";

const $primevue = usePrimeVue();
defineExpose({
     $primevue
})
</script>
```
