### ISSUE TITLE
Image: want set preview to fullscreen

### ISSUE THREAD

**Issue by suntel-nagamine** [primefaces/primevue#2947]
### Describe the feature you would like to see added

Is it possible to hide the scrollbar of the browser when displaying the preview of an Image, like FullScreen in Galleria?

**Comment by tugcekucukoglu** [comment]
We can not replicate the issue. https://primefaces.org/primevue/image in Preview seems working correctly. If the problem still persists, please open this same issue with a codesandbox link.

**Comment by suntel-nagamine** [comment]
I apologize for not providing more details.

Screen images have been prepared.
As shown below, https://primefaces.org/primevue/image in Preview shows a browser scroll bar that can be navigated.

Is it possible to make it so that the scrollbar does not appear as in https://www.primefaces.org/primevue/galleria/fullScreen?

image
![image](https://user-images.githubusercontent.com/73452395/197212264-93d0a180-bacf-40e4-865e-6261ed043c22.gif)

Galleria
![Galleria](https://user-images.githubusercontent.com/73452395/197212295-9971494c-193f-4781-ac26-6d5de1e04780.gif)
