### ISSUE TITLE
Toast: Close button resizes on longer text

### ISSUE THREAD

**Issue by abakucz** [primefaces/primevue#2949]
### Describe the bug

If the Toast `details` are longer than one line, the clickable area around close button becomes **oval** instead of keeping circular shape.

With **short** `details` text:
![image](https://user-images.githubusercontent.com/49059299/189140829-f719dceb-0ef0-4756-b368-db4ec8c813cf.png)

With **long** `details` text:
![image](https://user-images.githubusercontent.com/49059299/189141048-4feaee87-bed4-49a7-bfde-9a4c6c9ec316.png)

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Easiest way:

1. Go to https://www.primefaces.org/primevue/toast
2. Click `Sticky` to open the toast.
3. Inspect the toast element with Chrome DevTools.
4. Change the toasts details text to something longer.

### Expected behavior

Close button's shape (clickable area) should remain circular independent of toast's details text length.

**Comment by bahadirsofuoglu** [comment]
Fixed #2978
