### ISSUE TITLE
DataTable Expanded Row Styles

### ISSUE THREAD

**Issue by caputech** [primefaces/primevue#2950]
### Describe the feature you would like to see added

Please provide a style class similar to rowClass that applies to expanded rows.  Would like to be able to set the background color and other attributes of expanded rows similar to regular rows using the rowClass property.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
