### ISSUE TITLE
datatable-paginator: lazyload

### ISSUE THREAD

**Issue by drAliRahnema** [primefaces/primevue#2956]
### Describe the bug

hi
i have an api that return total number of records as i need.
i use lazy loading in datatable to show that data
but when i click on a page , the data correctly return, but the page number (and also filters and sort ,...) was not change (update correcctly)

### PrimeVue version

3

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

chrome

### Steps to reproduce the behavior

1.click on a page like page3
2. the data reurns correctly from service with extra field total number
3. i updae ref val data.value and totalNumbers.value
4. the paginator show page 1 instead of page 3 with data page 3
5.this issu is also for filter and sort and ... in lazy mode

### Expected behavior

it must show propper data page and filter and sort and ....

**Comment by tugcekucukoglu** [comment]
Duplicate [#2253 ](https://github.com/primefaces/primevue/issues/2253)
