### ISSUE TITLE
MultiSelect: Scroll to focused item on select

### ISSUE THREAD

**Issue by blackjak231** [primefaces/primevue#2957]
### Observed behaviour
Selecting an item in MultiSelect scrolls to focused item before setting new focus.

![ezgif-2-20a6833b8b](https://user-images.githubusercontent.com/1529214/189646245-bc7bc75f-13e6-43f4-b244-69185de57f82.gif)

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

All

### Steps to reproduce the behavior

1. Go to [https://www.primefaces.org/primevue/multiselect](https://www.primefaces.org/primevue/multiselect)
2. Click on any dropdown (best results with "Grouped")
3. Scroll down to "Osaka" (for grouped example)
4. Select "Osaka"
5. List scrolls back to top
(repeatable if you select others)

### Expected behavior

Selecting an item in MultiSelect should select the item and keep me at the same scroll position

**Comment by blackjak231** [comment]
Okay, after playing around a bit more, I realized that this issue happens if the option `autoOptionFocus` is true. (value is `true` by default).

### Solution
For anyone trying to fix this, you simply need to set `autoOptionFocus` to `false`. If you need to keep the autoOptionFocus on, then this will need to be addressed in PrimeVue.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll check it and get back to you.
