### ISSUE TITLE
Rating: dont work with nuxt

### ISSUE THREAD

**Issue by capoia** [primefaces/primevue#2959]
### Describe the bug

When I add the rating component to a page in nuxt it returns the error: TypeError: Cannot read properties of undefined (reading 'star')

### Reproducer

https://stackblitz.com/edit/github-j7fk9f?file=app.vue

### PrimeVue version

3.15

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

- Install nuxt
- Add the <rating> component

### Expected behavior

not generate error.

**Comment by tugcekucukoglu** [comment]
`aria` locale options are missing In your stackblitz. Also, `onIcon` etc. was added with v3.17.0
