### ISSUE TITLE
Menu: keyboard support

### ISSUE THREAD

**Issue by eldardada** [primefaces/primevue#2960]
### Describe the bug

The component is not accessible from the keyboard.

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by eldardada** [comment]
The "command" property responds on click, but should also respond to pressing the "space" or "enter" button.

Also there is no way to navigate using the up / down arrows

**Comment by eldardada** [comment]
the "command" property responds on click, but should also respond to pressing the "space" or "enter" button.

Also there is no way to navigate using the up / down arrows

**Comment by tugcekucukoglu** [comment]
Currently, we're working on the menu accessibility. It will be updated for the next version.

Thanks,
