### ISSUE TITLE
TreeSelect: programmatically open nodes

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2964]
### Describe the feature you would like to see added

I want to be able to programmatically control the opened nodes of the Treeselect component.

### Is your feature request related to a problem?

I want to write a filter for the Treeselect.
I can add a textinput to the header and filter the nodes before passing them to the Treeselect component.
Now I want to open all filtered nodes to display the result.

The textfilter matches the red childs.
The grey options would not be shown, removed by the filter.
The green option should be opened.
![image](https://user-images.githubusercontent.com/8471027/189843049-0a48b65a-3b29-482d-abfb-9cd268195f1f.png)

### Describe the solution you'd like

Have a property for the opened nodes on the TreeSelect component.

### Describe alternatives you have considered

Adding a filter to the Treeselect component itself would be nice.
But a programmatic controll may have more other use cases.
Maybe adding a 'toggle all open/close' checkbox somewhere.

**Comment by Rakasch** [comment]
My interim solution is to change the label to show the breadcrumbs, if a filter is active.
![image](https://user-images.githubusercontent.com/8471027/189854407-f3b74d80-9255-4adf-9d53-4dfc73264f62.png)

**Comment by Rakasch** [comment]
my interim solution is to change the label if a filter is active and show a flat list of the breadcrumbs.
![image](https://user-images.githubusercontent.com/8471027/189854972-2b60ce66-c38c-4110-a359-6b2247c556d3.png)

**Comment by erinleary** [comment]
I've been able to do this with the current control.

`<template #header>
        <span class="field grid p-2">
          <div class="col-10 pl-4">
            <span class="p-input-icon-right" style="width: 100%">
              <InputText
                type="text"
                class="w-full"
                v-model="search"
                id="search-input"
                placeholder="Search Tree"
              />
              <i class="pi pi-search" />
            </span>
          </div>
          <Button
            label="Clear Selected"
            class="w-2 p-button-sm text-white font-semibold"
            @click="resetTree"
          />
        </span>
      </template>`

`const search = ref(null);
    const expandedKeys = ref({});
    const treeRef = ref(); 

   watch(search, newValue => {
      setTimeout(() => {
        if (newValue === search.value) {
          lookupStore.filter = search.value;
          lookupStore.fetchTree().then(() => {
            if (search.value && search.value.length > 0) {
              expandFiltered();
            } else {
              expandedKeys.value = {};
            }
            treeRef.value.expandedKeys = expandedKeys.value;
          });
        }
      }, 300);
    });
    const expandFiltered = () => {
      expandedKeys.value = {}; // reset the expandedKeys
      for (let node of lookupStore.tree) {
        expandNode(node);
      }

      expandedKeys.value = { ...expandedKeys.value };
    };
    const expandNode = node => {
      if (node.children && node.children.length) {
        expandedKeys.value[node.key] = true;

        if (!node.key.toUpperCase().includes(lookupStore.filter.toUpperCase())) {
          for (let child of node.children) {
            expandNode(child);
          }
        }
      }
    };
`

**Comment by Rakasch** [comment]
Thanks for the suggestion of a workaround.
But I am hesitant to use it.

Using refs to manipulate the internals of another component has some disadvantages.
-it creates a strong coupling between components.
-you duplicate code eg for the expandNode logic
-its more likely that your component will break, if the internals of the primevue component change.

It would be much easier and cleaner to have an exposed "openedNodes" prop on the vue TreeSelect component.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
