### ISSUE TITLE
TreeSelect: add Slot for Options

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2965]
### Describe the feature you would like to see added

would like to have a slot for the options inside of the tree.

### Is your feature request related to a problem?

I want to add custom html, like those right aligned custom icons
![image](https://user-images.githubusercontent.com/8471027/189858738-64e4294c-969d-4206-b572-4d932e3a1186.png)

### Describe the solution you'd like

would like to have a slot for the options inside of the tree.

### Describe alternatives you have considered

allow to have html in the label
![image](https://user-images.githubusercontent.com/8471027/189859631-3c23491f-2dc6-4be1-a1c7-c0e745655ab3.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
