### ISSUE TITLE
Editor: Placeholder

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#2967]
### Describe the bug

Placeholder does not disappear when typing.
Only when you press enter or backspace.
![quill_editor](https://user-images.githubusercontent.com/8471027/189898646-f019e7d3-2710-4421-9cdf-84b219d0209f.gif)

primevue 3.17.0, quill 1.3.7

issue in Chrome only,
works correct in Firefox,
(dont have other browsers to test it)

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome Version 105.0.5195.102 (Offizieller Build) (64-Bit)

**Comment by bahadirsofuoglu** [comment]
Hi,
Could you send a sandbox link for reproduction? When I tried on 3.17.0 I could not reproduce it. Works correctly.

**Comment by Rakasch** [comment]
The problem has disappeared.
Very strange. Had tried everything and updated and restarted to get rid of the error. But nothing had helped. 
And now it no longer occurs.
