### ISSUE TITLE
Dropdown: I want to add tooltip each option.

### ISSUE THREAD

**Issue by hakiiver2** [primefaces/primevue#2968]
### Describe the feature you would like to see added

I want to add tooltip and icon for tooltip  each option's label.

### Describe the solution you'd like
add optionTooltip option   maybe
_No response_

**Comment by mertsincan** [comment]
Hi,

You can use `<template #option="slotProps">` to customize option's label. Exp;
```
<Dropdown v-model="selectedCity1" :options="cities" optionLabel="name" optionValue="code" placeholder="Select a City">
            <template #option="slotProps">
                <div v-tooltip="slotProps.option.name">{{slotProps.option.name}}</div>
            </template>
        </Dropdown>
```
