### ISSUE TITLE
Calendar: Add Quarter Picker

### ISSUE THREAD

**Issue by DanielStaroscik** [primefaces/primevue#2970]
### Describe the feature you would like to see added

Can You add a "Quarter Picker" to the Calendar Component?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
