### ISSUE TITLE
Sidebar: add appendTo property

### ISSUE THREAD

**Issue by telion2** [primefaces/primevue#2971]
### Describe the feature you would like to see added

Like Dialog I would like to see the property "appendTo", which controls where the Sidebar is teleported to. 

### Is your feature request related to a problem?

Yes, I am using PrimeVue in a shadow dom, and the sidebar is teleported outside of it by default. 
So, I want to teleport it inside the shadow dom and control/style it there. 

### Describe the solution you'd like

add the Property "appendTo" to the component Sidebar. 
Extra Points for adding it to every component that uses Portal. 

### Describe alternatives you have considered

I don't see another way.

**Comment by bahadirsofuoglu** [comment]
We think that appending the sidebar somewhere other than the body may be against the behavior of the component. Many alternative components can be used in PrimeVue. Thank you very much for your feedback.

**Comment by cyhnkckali** [comment]
https://primeng.org/sidebar Why is the feature for Angular not available for vue?

**Comment by nsnyder** [comment]
I'd love a more clear explanation. I recognize there are alternatives, but what makes those use cases with append-to different than this Sidebar? The Sidebar is effectively a Dialog with some specialized styles. It doesn't make sense that those would offer append-to and this one wouldn't. And if the append-to breaks something because someone using it appended to a weird element (which could happen with any of these append-to components), that's on the user to ensure it'll be attached in the correct place.

**Comment by NoelDeMartin** [comment]
@tugcekucukoglu Can you reconsider this issue? As the original poster mentioned, these components don't work if you're using PrimeVue inside of the ShadowDOM.

I don't think using PrimeVue inside the ShadowDOM goes "against the behavior of the component". If you want to know more about the use-case, in my case I am developing a browser extension using [WXT](https://wxt.dev/), which renders the extension UI in the ShadowDOM to avoid conflicts with the page content.

I understand that this is not one of the most common use-cases out there, but it's a shame that this issue remains when the solution is as simple as exposing a property that's already there.

And for anyone else who ends up here, one solution is to use something like [patch-package](https://www.npmjs.com/package/patch-package) (or [pnpm patch](https://pnpm.io/cli/patch), etc.). It's not ideal, but the changes are small and I think it's pretty safe. This is the diff I'm using myself (I only need the Drawer component for now):

```patch
diff --git a/drawer/index.mjs b/drawer/index.mjs
index 6dd055769ba589ea39e7f5078037d5b8e7cf0f68..9b153a28a636f4096881879d2bb0f3218368bd0e 100644
--- a/drawer/index.mjs
+++ b/drawer/index.mjs
@@ -83,6 +83,12 @@ var script = {
   "extends": script$1,
   inheritAttrs: false,
   emits: ['update:visible', 'show', 'after-show', 'hide', 'after-hide', 'before-hide'],
+  props: {
+    appendTo: {
+      type: [String, Object],
+      "default": 'body'
+    },
+  },
   data: function data() {
     return {
       containerVisible: this.visible
@@ -272,7 +278,7 @@ function render(_ctx, _cache, $props, $setup, $data, $options) {
   var _component_Button = resolveComponent("Button");
   var _component_Portal = resolveComponent("Portal");
   var _directive_focustrap = resolveDirective("focustrap");
-  return openBlock(), createBlock(_component_Portal, null, {
+  return openBlock(), createBlock(_component_Portal, { appendTo: $props.appendTo }, {
     "default": withCtx(function () {
       return [$data.containerVisible ? (openBlock(), createElementBlock("div", mergeProps({
         key: 0,
```
