### ISSUE TITLE
Password: Required prop doesn't exist

### ISSUE THREAD

**Issue by bobbybol** [primefaces/primevue#2975]
### Describe the bug

The documentation tells me that there's a required prop for making the password field required. However, this doesn't work, and looking at the source code, the required prop doesn't exist on the Password component at all. 

### PrimeVue version

3.16.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by bahadirsofuoglu** [comment]
Hi,
Could you try 3.17.0 version? Also if you could send a reproducer we can find a solution more easily.
