### ISSUE TITLE
Nuxt 2 for Prime 2.*.* does not work on ssr: true

### ISSUE THREAD

**Issue by shidcordero** [primefaces/primevue#2983]
### Describe the bug

Does not work when ssr: true on Nuxt using Nuxt modules. It will throw an Unexpected token '<'

Also tried it using plugin add add it in nuxt.config with `mode: 'client'` and still show same error

### PrimeVue version

2.9.2

### Vue version

2.x

### Language

ES6

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

set ssr: true or taget: 'static' on nuxt.config

### Expected behavior

It should work as expected

**Comment by tugcekucukoglu** [comment]
Unfortunately cannot replicate the issue. If the problem still persists, please create a new issue ticket with a reproducer.
