### ISSUE TITLE
Toast: new `close` and `life-end` methods

### ISSUE THREAD

**Issue by vasiliyaltunin** [primefaces/primevue#2989]
Add callback to Toast that fire up when toast message closed on timeout. 

For example on password change i would like to redirect to login page after message about succes password change closed.

**Comment by mroettgen** [comment]
I think it would be preferrable to have events that one can bind to in these cases, e.g. `@close` and `@timeout`, since `@close` can already be used for messages

**Comment by Jogai** [comment]
@cagataycivici said in discord:

> Sounds good to me, we already have an internal close event, just needs to expose it. Please create a ticket at github and we'll add it to the plan. It'd help to quote this comment as well as a reference.

**Comment by cagataycivici** [comment]
Thanks Jogai
