### ISSUE TITLE
Listbox component does not load

### ISSUE THREAD

**Issue by Narsas** [primefaces/primevue#299]
Getting the following error message after implementing the Listbox component in my application: 

> webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Property or method "getOptionRenderKey" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
> 
> found in
> 
> ---> <Listbox> at node_modules/primevue/components/listbox/Listbox.vue
>        <Card> at node_modules/primevue/components/card/Card.vue
>          <DeploymentControl> at src/views/deploymentControl.vue
>            <App> at src/App.vue
>              <Root>

and

> Error in render: "TypeError: _vm.getOptionRenderKey is not a function"

Here's my vue file:

```
<template>
  <div>
      <Listbox
                  v-model="selectedUser"
                  :options="users"
                  optionLabel="name"
                />
  </div>
</template>
<script>
export default {
  data() {
    return {
      selectedUser: null,
      users: [
        {
          name: "Simon Glatt",
          value:1
        },
        {
          name: "Ralf Blatt",
          value: 2
        },
      ],
      checkedContactPerson: false,
    };



  },
};
</script>
<style lang="scss">
@import "src/assets/layout/component_sass/_deploymentControl_component.scss";
</style>

```

**Comment by Merve7** [comment]
Hello,
What is your version? We tried your code but it works. Please, can you try again after remove package-lock.json and node_modules and install again.

**Comment by cagataycivici** [comment]
Any news? I'm also not able to replicate.
