### ISSUE TITLE
AutoComplete: completeOnFocus option doesn't show the suggestions dropdown on consequent focuses

### ISSUE THREAD

**Issue by Defrosted** [primefaces/primevue#2991]
### Describe the bug

Hello!

There's an annoying behaviour with the AutoComplete component using the `completeOnFocus` option whenever I'm not triggering an asynchronous action from the `complete` event of the component. If the function invoked by the complete event doesn't change the suggestions, the list of suggestions isn't showed after the first time `complete` is invoked (since the query value isn't changed). This leads to the behaviour where once I've clicked the AutoComplete component once, and unfocused it, any consequent focuses of the component do not trigger the list of suggestions. Additionally, the loading spinner shows up when you refocus the AutoComplete the second time, even though no asynchronous loading is going on.

In my experience, this behaviour doesn't happen when invoking slower async actions from the `complete` handler. Only when I already have an array of suggestions ready that doesn't take a lot of computation time to filter.

I've provided a sandbox showcasing the issue.

### Reproducer

https://codesandbox.io/s/dazzling-faraday-lfb16y

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click the AutoComplete component. The list of suggestions show up.
2. Unfocus the input by clicking outside of the component.
3. Click the AutoComplete component again. The list of suggestions do not pop up!

### Expected behavior

I'm expecting the list of suggestions to pop up each time I refocus the AutoComplete component (with the `completeOnFocus` flag), even though the query hasn't changed.

**Comment by Defrosted** [comment]
Any updates regarding this issue?

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox. We've tried but did not replicate the issue. It seems the problem is on your side. Please try to update the `complete` event.
