### ISSUE TITLE
Tree: Add Slot for Options on the right of the Filter Bar

### ISSUE THREAD

**Issue by emsouza** [primefaces/primevue#2992]
### Describe the feature you would like to see added

I would like to have a slot to add some options on the right of the filter bar.

![tree_with_filter](https://user-images.githubusercontent.com/1131916/191041542-349630fc-e2bc-4790-8f13-9ed0f18d232e.png)

![tree_without_filter](https://user-images.githubusercontent.com/1131916/191041574-f0b56134-a984-4cd5-a65c-0cf8f8812795.png)

### Describe the solution you'd like

I would like to have a slot to add some options on the right of the filter bar.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
