### ISSUE TITLE
AutoComplete :  Slot Required for autcomplete model value

### ISSUE THREAD

**Issue by Sandip124** [primefaces/primevue#2994]
### Describe the feature you would like to see added

i would just want slot for item list for autocomplete.

### Is your feature request related to a problem?

When using autcomplete with multiple  items then the layout is shifted and it breaks all layout. so for consistency i would required slot so that i can  customize it.

### Describe the solution you'd like

I want slot for  list item so that i can just put '4 items' instead of all  items that may lead to layout shifting.

### Describe alternatives you have considered

i have considered alternative to customize the chip slot but it was limited so  for such customization i would require slot for list items so i can control over my list.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
