### ISSUE TITLE
Datatable: Use different primeicon as sort icon

### ISSUE THREAD

**Issue by gvg356** [primefaces/primevue#2995]
### Describe the feature you would like to see added

Change the sort icon to different icon from prime icons
Instead of
pi-sort-alt
pi-sort-amount-up-alt
pi-sort-amount-down

would like to use
pi-sort
pi-sort-up
pi-sort-down

### Is your feature request related to a problem?

Cannot change the sort icon

### Describe alternatives you have considered

I can replace the content and give the desired icon using css but want to check for better approach

**Comment by tugcekucukoglu** [comment]
Icon prop support is on our roadmap.

Thanks,
