### ISSUE TITLE
DataTable cell editing updates model after next change

### ISSUE THREAD

**Issue by LukaszBober** [primefaces/primevue#3002]
### Describe the bug

Hello, I can't deduce why model is updating only after next change.
            
`            <DataTable v-if="selectedStation.parsers" :value="selectedStation.parsers" class="editable-cells-table"
                       editMode="cell"
                       responsiveLayout="scroll" @cell-edit-complete="onCellEditComplete">
              <Column v-for="col of parsersColumns" :key="col.field" :field="col.field" :header="col.header"
                      style="width:25%">
                <template #editor="slotProps">
                  <InputText v-model="slotProps.data[slotProps.field]" />
                </template>
              </Column>
              <Column :exportable="false" style="min-width:8rem">
                <template #body="slotProps">
                  <Button class="p-button-rounded p-button-warning" icon="pi pi-trash" style="scale: 80%;"
                          @click="removeParser(slotProps)"/>
                </template>
              </Column>
            </DataTable>`

` const parsersColumns = ref([
      {field: 'name', header: t('hydro.stations.modal.name')},
      {field: 'parser', header: t('hydro.stations.modal.parser')},
      {field: 'matcher', header: t('hydro.stations.modal.matcher')},
      {field: 'custom', header: t('hydro.stations.modal.custom')}
    ]);
    const selectedStation = ref();`

`    const onCellEditComplete = (event) => {
      let {data, newValue, field} = event;
              data[field] = newValue;
    }`

<a href="https://ibb.co/QXTXBxM"><img src="https://i.ibb.co/QXTXBxM/screen.jpg" alt="screen" border="0"></a>

Best regards

### PrimeVue version

3.16.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox

**Comment by tugcekucukoglu** [comment]
For `editMode="cell"`,  `cell-edit-complete` method could update the model or not. All control is given to the user and `cell-edit-complete` event can be changed according to logic.
