### ISSUE TITLE
ProgressBar: progress value centered relative to the whole progress bar's width

### ISSUE THREAD

**Issue by smellyshovel** [primefaces/primevue#3022]
### Describe the feature you would like to see added

A prop or any other way to make the "<progress>%" text be always centered relative to the whole progress bar's width instead of the colored-part only width.

### Is your feature request related to a problem?

The issue with the current implementation is that when the progress values are small (1-8% roughly) and the total progress bar's width is also not very large (appr. 100-150px), the value is not visible at all or visible only partially. When the progress goes slowly, it's hard to tell because of that that there's some progress at all.

### Describe the solution you'd like

The text-representation of current progress should always be visible. Either by default or there should be a possibility to enable such a functionality using any of the framework's avaialble interfaces.

### Describe alternatives you have considered

I didn't try to apply a workaround becase:
1) I don't have access to the application where these progress bars are used at the moment
2) I think it's a common-enough case to be considered globally and not with local workarounds.

### Additional context

![Screenshot_20220923_161255](https://user-images.githubusercontent.com/9782236/191957826-6abe3820-8176-4e77-9fa2-b17234e4fa1f.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
