### ISSUE TITLE
Galleria: allow to step through the images using the arrow keys

### ISSUE THREAD

**Issue by leszekhanusz** [primefaces/primevue#3029]
### Describe the feature you would like to see added

With the Galleria component, it should be possible to step forward and backward through the pictures using the arrow keys of the keyboard.

### Is your feature request related to a problem?

It's easier to step through a lot of pictures using the keyboard than using the mouse.

### Describe the solution you'd like

To support horizontal and vertical layout, I propose the following scheme:

* `BottomArrow` and `RightArrow` key moves forward.
* `TopArrow` and `LeftArrow` moves backward.

### Describe alternatives you have considered

It should be possible to do with the [programmatic](https://www.primefaces.org/primevue/galleria/programmatic) feature of the Galleria component but it seems such an obvious feature that it would be nice to have it by default.

**Comment by tugcekucukoglu** [comment]
We're currently working on the Accessibility. It's on our roadmp.

Thanks for your report.
