### ISSUE TITLE
Dropdown: Long list causes the page to have a long scroll bar

### ISSUE THREAD

**Issue by jf908** [primefaces/primevue#3031]
### Describe the bug

When you open a dropdown list, the height of the dropdown's contents affect the page's height which causes the page's scrolling to go past the page's contents.

I believe this is caused by the `<span role="status" aria-live="polite" class="p-hidden-accessible">No selected item</span>` element because removing it fixes the issue.

### Reproducer

https://codesandbox.io/s/elated-morning-q30llq?file=/src/App.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 105

### Steps to reproduce the behavior

1. Click on the dropdown to open it
2. See that the contents of the page can be scrolled very far down

### Expected behavior

The page's height shouldn't be affected by the inner contents of a dropdown.

**Comment by sid-6581** [comment]
I'm seeing the same thing.

**Comment by Rakasch** [comment]
`<span role="status" aria-live="polite" class="p-hidden-accessible">No selected item</span>`
Its absolut positioned. and at the end of the list.
moving it before the ul list fixes the scrollbar.

**Comment by mertsincan** [comment]
I'll check it and get back to you.
