### ISSUE TITLE
DataTable: FlexScroll is not flexible with virtualScroller

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3034]
### Describe the bug

When using scrollable datatables, it's a pretty likely use case that you'll want to use the virtualScroller as well.

I used Datatable "Flexible Scroll" example from here:
https://www.primefaces.org/primevue/datatable/scroll

I added :virtualScrollerOptions="{ itemSize: 50 }" to the datatable.

If you now expand the dialog, the datatable height does not adapt to the dialog height anymore.

### Reproducer

https://codesandbox.io/s/nervous-morning-1qnqwv?file=/src/DataTableScrollDemo.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Please try to use the latest PrimeVue version.
