### ISSUE TITLE
DataTable: virtualScroller breaks sticky footer

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3035]
### Describe the bug

If you have a **scrollable** datatable with **virtualScrollerOptions**, the **footer** is no longer displayed sticky at the bottom of the table. It's now over the first item and thus hides the first item.

### Reproducer

https://codesandbox.io/s/dreamy-gagarin-2lxeb5?file=/src/DataTableScrollDemo.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Duplicate [#2626 ](https://github.com/primefaces/primevue/issues/2626)
