### ISSUE TITLE
[DataTable with virtual scroll] Using primevue inside shadow-dom

### ISSUE THREAD

**Issue by moduval** [primefaces/primevue#3037]
### Describe the bug

When using this component with datatable and virtual scroll, some style seems to be added with some sort of lib. Those styles are added outside shadow dom so they do not apply to the data table. Is there a way to make PrimeVue work with shadow dom?

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use a datatable inside a shadow-dom web-component with multiple elements in it. See that some style are not working (like the height of the table is not applied)

### Expected behavior

Work as expected inside shadow-dom

**Comment by scvnc** [comment]
I am also trying to use PrimeVue in a Shadow DOM and am experiencing some style issues.  At least in my case it is related to the fact that PrimeVue appears to append elements to the document.body for some of its features, and the styles that may be scoped to the inside of the Shadow DOM are not found.  

Here is my test harness for exploring this issue... perhaps if you add DataTable with your use case, it would illustrate the same issue.

https://scvnc.github.io/experiment-primevue-shadowdom/

**Comment by hpalma** [comment]
Was this change applied in 4.x? I don't see it.
