### ISSUE TITLE
primeicons  unable to resolve dependency tree

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3038]
### Describe the bug

npm ERR! Found: primeicons@6.0.1
npm ERR! node_modules/primeicons
npm ERR!   primeicons@"6.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer primeicons@"^5.0.0" from primevue@3.17.0
npm ERR! node_modules/primevue
npm ERR!   primevue@"3.17.0" from the root project

in   "primeflex": "3.2.1",
    "primeicons": "5.0.0",
    "primevue": "3.17.0",
    "prismjs": "1.29.0",

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by tugcekucukoglu** [comment]
PrimeVue v3.17.0 still uses the PrimeIcons v5.0.0. The problem will be fixed for the next PrimeVue version.
