### ISSUE TITLE
Calendar: Time picker: tab navigation fails inside dialogs

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#3040]
### Describe the bug

It's impossible to tab to all up/down controls for hours and minutes when the component is inside a dialog.

### Reproducer

https://stackblitz.com/edit/vue-gqyw6n?file=src/App.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

See StackBlitz link.

### Expected behavior

One should be able to focus on all controls using tab.

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.

**Comment by rubjo** [comment]
This is really strange - does it mean that you *are* in fact able to access all the up/down timepicker controls inside the modal using only the keyboard?
