### ISSUE TITLE
DataTable: Only select visible rows with selectAll-Toggle

### ISSUE THREAD

**Issue by re-kfa** [primefaces/primevue#3042]
### Describe the bug

Hi,

how can I use the selectAll-Toggle to only select rows which are currently visible to the user?

I'm pretty sure I need to use the `select-all-change` - Callback for this, but I didn't found any possibility to get the currently shown rows of the table to just select them.

Thanks!

### PrimeVue version

3.12.2

### Vue version

3.x

### Language

ES5

### Build / Runtime

Nuxt

**Comment by odranoelBR** [comment]
@re-kfa are you using nuxt 3 ?

**Comment by re-kfa** [comment]
@odranoelBR no, just vue3 and vue-cli-service.

**Comment by re-kfa** [comment]
I have now found a way to achieve the desired result:

```
<PrimeDataTable
   ref="dt"
   :value="items"
   :selectAll="selectAll"
   @select-all-change="onSelectAllChange"
   @value-change="onValueChange"
   @update:first="onUpdateFirst"
   @update:rows="onUpdateRows"
>
```
```
let processedData = [];
const onValueChange = (event) => {
   processedData = event;
};

const onUpdateFirst = (event) => {
   first.value = event;
};

const onUpdateRows = (event) => {
   rows.value = event;
};

const onSelectAllChange = (event) => {
   selectAll.value = event.checked;
   if (selectAll.value) {
      selectAll.value = true;
      selectedItems.value = processedData.slice(first.value, first.value + rows.value);
   } else {
      selectAll.value = false;
      selectedItems.value = [];
   }
};
```
It's somewhat inconvenient as one might think, that this should be the standard behaviour of a "Select all"-checkbox in a paginated table anyway.

When using the above code a bug occurs: If using `sortField` or `sortOrder`-props the `value-change`-event will not be fired. Therefore the `processedData`-Array is not populated with the sorted data. 
This is due to the fact, that the event is only thrown in the `onColumnHeaderClick`-method of DataTable.vue and not in the sort-methods where it also needs to be thrown. The filter method does this and therefor works as expected.

**Comment by tugcekucukoglu** [comment]
Thanks for the feedback. Now closing the issue.
