### ISSUE TITLE
MultiSelect: can clearAll  when hover the selected div

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3046]
### Describe the feature you would like to see added

link [element-plus](https://element-plus.org/zh-CN/component/select.html#%E5%8F%AF%E6%B8%85%E7%A9%BA%E5%8D%95%E9%80%89)

can clear selected value when hover the input

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.
