### ISSUE TITLE
Password: toggleMask

### ISSUE THREAD

**Issue by hakiiver2** [primefaces/primevue#3049]
### Describe the bug

Thanks for a great project.

About the password eye icon．
Currently, when there is a diagonal line on the eye icon, the password is visible, but sometimes I want to reverse this.
Is there a way to implement this?

Sorry, I think this is not bug.

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
`toggleMask` changes the input type as text or password. If you are asking when the input type is text, the value will be seen and there is no way to change this behaviour.

**Comment by hakiiver2** [comment]
@tugcekucukoglu 
Sorry, I'm asking just icon behaviour.
