### ISSUE TITLE
Dialog: Allow custom icons

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3054]
### Describe the feature you would like to see added

Extracted from https://github.com/primefaces/primevue/issues/2979 - adding custom icons support for dialog component

**Comment by tugcekucukoglu** [comment]
If you are still interested, maximize and minimize icons do not have icon props. https://github.com/primefaces/primevue/blob/master/src/components/dialog/Dialog.vue#L401

Thanks for your contribution.

**Comment by Magiczne** [comment]
@tugcekucukoglu sure. Will do it
