### ISSUE TITLE
Tooltip: Dynamic Positioning

### ISSUE THREAD

**Issue by DazDotOne** [primefaces/primevue#3063]
### Describe the feature you would like to see added

Dynamically change position of tooltip

### Is your feature request related to a problem?

I'd like to be able to use a tooltip in a reusable component which may require positioning it differently based on where the component is rendered.

### Describe the solution you'd like

`v-tooltip="{value: 'my content', position: 'position'}"`
or 
`v-tooltip:[position]="content"`

### Describe alternatives you have considered

````js
// As set out in vue docs: https://vuejs.org/guide/reusability/custom-directives.html#hook-arguments
v-tooltip:[props.tooltipPosition]
v-tooltip[position]

v-tooltip="{
  value: props.tooltip,
  options: { modifiers{top: true } },
}"
````
overriding css, can't use scoped because it appears outside of component scope, can't set it via class property as it doesn't remove  the p-tooltip-right don't want to hack over your css ifd possible.

Others but considering you haven't replied to my last issue (also about reusability), I'm hesitant to put any more time into this than I have to.

### Additional context

It's just dynamically setting the position of the tooltip.

**Comment by Rakasch** [comment]
I think it's already possible.
https://github.com/primefaces/primevue/issues/2255

**Comment by DazDotOne** [comment]
Dynamically?It doesn't seem to be documented.I could be wrong, there are a lot of docs but I've not seen anything and the few ways I've seen people call directives with dynamic modifiers haven't worked so far.Any idea as to where I can find some info?On 30 Sept 2022 07:42, Rakasch ***@***.***> wrote:
I think it's already possible.
#2255

**Comment by DazDotOne** [comment]
Sorry the issue link didn't come through on the email.

I'll try that now.

Thanks.

**Comment by DazDotOne** [comment]
Excellent, thanks for the response.

That works.
