### ISSUE TITLE
Textarea Component: Breaking in Nuxt 3 

### ISSUE THREAD

**Issue by brianmhlanga** [primefaces/primevue#3066]
### Describe the bug

Textarea component in nuxt 3.0.0-rc.11 returning the error below

`runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: Textarea
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <LoanCalculator[typeId][id] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/loanCalculator_2_4" routeProps= Object pageKey="/loanCalculator_2_4"  ... > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>`

### PrimeVue version

3.16.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
[https://codesandbox.io/s/elastic-lamarr-xh0b8u?file=/app.vue](https://codesandbox.io/s/elastic-lamarr-xh0b8u?file=/app.vue) 

Can not replicate the issue. Could you send us a codesandbox or a repo so we can see the problem?

**Comment by bahadirsofuoglu** [comment]
https://github.com/primefaces/primevue-quickstart-nuxt3 The repository is updated. I tested and I could not reproduce it.
