### ISSUE TITLE
MultiSelect group labels disappear when filtering

### ISSUE THREAD

**Issue by john-oc** [primefaces/primevue#3068]
### Describe the bug

When groups are used with the MultiSelect and filtering is enabled, when any filter text is entered, all group labels are hidden.
Have created a pull request with a fix for this:- https://github.com/primefaces/primevue/pull/3069

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Add :filter="true" to the MultiSelect grouped example in the docs
2. Type a value in the filter which matches one or more options
3. Matching option(s) are shown, but all group labels disappear

### Expected behavior

Group labels for options which match the filter should still be visible

**Comment by tugcekucukoglu** [comment]
Fixed https://github.com/primefaces/primevue/pull/3069
