### ISSUE TITLE
Nuxt 3 rc.11 problem in SSR -> client styles

### ISSUE THREAD

**Issue by odranoelBR** [primefaces/primevue#3070]
### Describe the bug
On load / reload the app, the styles glitch, making a bad transition from ssr to client.

### Reproducer

[CodeSandBox](https://codesandbox.io/p/github/odranoelBR/primevue-quickstart-nuxt3/csb-sp3gvk/nuxt-3-primevue?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A9%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8rengzd0000lri08gbuff2q%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl8rfbnb503pb2v6lhp5osc9o%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 105

### Steps to reproduce the behavior

1. I started from Documentation repo https://github.com/primefaces/primevue-quickstart-nuxt3
2. Updated nuxt to rc.11
3. Added some components.
4. Load / reload the app.

Video
https://vimeo.com/756125638

### Expected behavior

Syles dont change after browser paint.

**Comment by tugcekucukoglu** [comment]
The video link is broken. How can we replicate the issue?

**Comment by odranoelBR** [comment]
Hello @tugcekucukoglu.
You can reproduce with the [codesandbox](https://codesandbox.io/p/github/odranoelBR/primevue-quickstart-nuxt3/csb-sp3gvk/nuxt-3-primevue?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A9%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8rengzd0000lri08gbuff2q%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl8rfbnb503pb2v6lhp5osc9o%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)
Attached video here
https://user-images.githubusercontent.com/7774534/193632579-d176aeb1-8bf7-4a00-9bdf-b7d4b1e6cc33.mp4

**Comment by bahadirsofuoglu** [comment]
You shouldn't need this part. Nuxt automatically imports your plugin. 
`  
 build: {
        transpile: ['primevue']
    }
`

**Comment by odranoelBR** [comment]
Tks @bahadirsofuoglu , i think nuxt 3 vite doesn't do this by default. This configuration come from primevue example https://github.com/primefaces/primevue-quickstart-nuxt3.
If i ommit it, nuxt throws an error.

**Comment by bahadirsofuoglu** [comment]
Thank you for your answer. I updated the repo. Could you try to update your PrimeVue version

**Comment by odranoelBR** [comment]
Tks @bahadirsofuoglu , updated but still with the problem. I'm already using primevue 3.17.0
Check:


https://user-images.githubusercontent.com/7774534/193936727-d371c67b-03d0-4dc5-92d9-ffccc8b33ec1.mp4

**Comment by odranoelBR** [comment]
Hi @tugcekucukoglu, need anything else to update the issue?  This last video is opening ? tks

**Comment by tugcekucukoglu** [comment]
We still could not replicate this issue. Please send a codesandbox or a repo link while creating an issue, so we can replicate the issue.

**Comment by odranoelBR** [comment]
Hi @tugcekucukoglu tks for the feedback
You guys can't see this codeSandBox link in the issue ?

![image](https://user-images.githubusercontent.com/7774534/197828375-d4f01a68-f34a-4fc6-8aed-6f1633e344a8.png)

**Comment by odranoelBR** [comment]
[codeSandBox](https://codesandbox.io/p/github/odranoelBR/primevue-quickstart-nuxt3/csb-sp3gvk/nuxt-3-primevue?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A9%7D%5D)

**Comment by hjJunior** [comment]
I'm also having the same issue

**Comment by shidcordero** [comment]
I am also having this issue now when ssr was true. Setting ssr: false won't show the FOUC(Flash of unstyled Content) issue. Any thoughts on this?

**Comment by Ice-Hazymoon** [comment]
Hi, this issue still exists to this day. How can I fix it? When I enable SSR, the component’s styles load with a delay.

**Comment by farshidpg** [comment]
same issue with ssr:true
