### ISSUE TITLE
General: Allow PrimeIcons 6.0 as peer dependency

### ISSUE THREAD

**Issue by jnoordsij** [primefaces/primevue#3073]
### Describe the bug

Installing the latest `primevue` and `primeicons` versions together using the latest yarn version yields a warning  
```
YN0060: │ project@workspace:. provides primeicons (pba73d) with version 6.0.1, which doesn't satisfy what primevue requests
```

To me, there don't seem to be any incompatibilities with the new version, so I think listing 6.0 as additional peer dependency (or maybe even as replacement) can be done without any further problems.

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

TypeScript

### Browser(s)

N/A

**Comment by bahadirsofuoglu** [comment]
Will be fixed with the new release.

**Comment by tugcekucukoglu** [comment]
Duplicate [#3044 ](https://github.com/primefaces/primevue/pull/3044)
