### ISSUE TITLE
Tooltip: If directive is wrapped in a parent component, focus and blur event propagation does not occur.

### ISSUE THREAD

**Issue by julienlaplante** [primefaces/primevue#3076]
### Describe the feature you would like to see added

Use focusin and focusout events instead of focus and blur for better propagation.

### Is your feature request related to a problem?

Ex: I have a component "FiledWrapper" which additionally manages labels. In this component I have a slot to receive input type components. When I want to use the tooltip in focus-blur mode in a text input (for example) this one does not work because the envent does not bubble.

### Describe the solution you'd like

#3075

**Comment by tugcekucukoglu** [comment]
We could not replicate the issue. If you send us a codesandbox or a simple repo, we could catch the problem.
