### ISSUE TITLE
incorrect peer dependency "primeicons@^5.0.0".

### ISSUE THREAD

**Issue by deguich** [primefaces/primevue#3084]
### Describe the bug

Message "incorrect peer dependency primeicons@^5.0.0" when doing a yarn install.

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Duplicated issue. Please track at [#3044 ](https://github.com/primefaces/primevue/pull/3044)
