### ISSUE TITLE
[big bug] lazy-load event can be  invoke infinity 

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3087]
### Describe the bug

https://github.com/primefaces/primevue/blob/master/src/components/virtualscroller/VirtualScroller.vue#L134

e.g. 
```vue
 <MultiSelect
          v-model="selectedItems"
          :options="items"
          :maxSelectedLabels="3"
          :selectAll="selectAll"
          @selectall-change="onSelectAllChange($event)"
          @change="onChange($event)"
          optionLabel="label"
          optionValue="value"
          filter
          @filter="onFilter"
          :virtualScrollerOptions="{
            scroll: onScroll,
            itemSize: 44,
            lazy: true,
            onLazyLoad: onLazyLoad,
          }"
          placeholder="Select
        Item"
        />
        
        <script setup>
const selectedItems = ref<any[]>([])

const items = ref([])

        const onLazyLoad = async (event) => {
  console.log('onLazyLoad', event)

  const { data } = await myFetch('xxx', {
    query: {
      name: 'store_name',
      page: 1,
      perPage: 12,
    },
  })
  console.log(data)

  items.value = items.value.concat(data)

}
        </script>
```

1. when click MultiSelect button, invoke onLazyLoad,items change, the options prop changed, then  raw source code emit watch items 
2. items change can invoke  init() -> calculateOptions() ->  `this.$emit('lazy-load', { first, last })` -> onLazyLoad()
3. items change, the options prop changed, then  raw source code emit watch items 
4. ...Infinite loop
            

### PrimeVue version

^3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Valar103769** [comment]
@tugcekucukoglu

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.
