### ISSUE TITLE
[Dialog] body can be click when dialog is show and with modal prop 

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3088]
### Describe the bug

don't lie to you, has two problem

<img width="546" alt="image" src="https://user-images.githubusercontent.com/36926073/194794170-ea87860f-6022-44ef-847a-850530a6433e.png">

1.  when dialog B is showen, and with model prop , and the overlayA can be close when click body,
2. when close dialogB by click cancel button, also close overlayA; 

it like not to do stop event bubbling

expected behavior:
1. when dialog  is shown with model prop, the nothing can be click except dialog self 

### PrimeVue version

3.xx

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Valar103769** [comment]
> How can we test it? Could you send us a codesandbox so we could replicate it?

https://github.com/primefaces/primevue/pull/3089 
you can look at this pr, then you know what happened

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.
