### ISSUE TITLE
[MultipleSelect VirtualScroll] items length can modify by scroll

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3090]
### Describe the bug

https://codesandbox.io/s/amazing-tree-3bmjh5?file=/src/MultiSelectDemo.vue

Two questions:
1. Correct: data is loaded twice, but the connection is loaded one more time
2. After 2 data loads are completed, scroll again, and elements will be added infinitely

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Valar103769** [comment]
correct
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/36926073/194828869-b87ab3d2-d74a-42b5-b07b-ee819fe99e86.png">

incorrect
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/36926073/194828959-800d3652-452b-4ddb-86b7-708b2fadf12f.png">
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/36926073/194829089-593826e7-cb6f-4c25-b736-1dc0bebb4047.png">

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.
