### ISSUE TITLE
.p-overlaypanel-content  can’t to be modify 

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3091]
### Describe the bug

`.p-overlaypanel-content ` should not has padding-left and padding-right that can cause the checkbox can't to be checked,
and not way to modify that style

i try 

```vue
 <OverlayPanel ref="overlayRef" class="panel w-[200px]">
    <RecycleScroller
      class="max-h-[220px]"
      :items="options"
      emitUpdate
      :item-size="44"
      key-field="value"
      v-slot="{ item }"
      @update="onUpdate"
    >
      <div class="flex py-3 items-center hover:bg-stone-300">
        <div class="p-checkbox p-component mr-2">
          <div :class="['p-checkbox-box', { 'p-highlight': isSelected(item) }]">
            <span
              :class="['p-checkbox-icon', { 'pi pi-check': isSelected(item) }]"
            ></span>
          </div>
        </div>
        <span>{{ item.label }}</span>
      </div>
    </RecycleScroller>
  </OverlayPanel>

<style lang="scss" scoped>
.panel :deep(.p-overlaypanel-content) {
  padding-left: 0 !important;
  padding-right: 0 !important;
}
</style>

```
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/36926073/194848991-146f67b8-570d-42bb-831b-7e99c46e7ecc.png">

 because it not has data-v  and I guess  the portal component  not support data-v 

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
OverlayPanel appends itself to the `body` by default. You could change this behavior using the `appendTo` prop. In this default behavior, you do not need to use `:deep` selector.
