### ISSUE TITLE
Overlay: Cannot Modify Z-Index

### ISSUE THREAD

**Issue by AutoAwesome** [primefaces/primevue#3093]
### Describe the bug

Hi Guys,

I have a problem with the Overlay z-index. Basically I want to click on an overlay to bring it to the foreground. 
The easiest way to do that is to modify the z-index. I tried multiple things like `:style={'z-index': wndIndex}` with and without `autoZIndex` set to either `true` or `false` but nothing seems to work.

Here is a minimal code sandbox where you can see the issue yourself.
I try it with `baseZIndex` and it still doesn't work.

https://codesandbox.io/s/infallible-northcutt-g4x05m?file=/src/DialogDemo.vue

The only thing what kinda worked was to put all overlays in an array and do a `v-for` over them. Then reorder when I reorder the array it works. But it looks silly and I really want to avoid doing such silly tricks :smile:

Is there anything I'm missing?

Thanks for your time! 

### Reproducer

https://codesandbox.io/s/infallible-northcutt-g4x05m?file=/src/DialogDemo.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create 2 Overlays
2. Adjust z-index of both overlays so first overlay has higher z-index than second overlay
3. Observe that first overlay is still in the background

### Expected behavior

First overlay should be in the foreground.

**Comment by tugcekucukoglu** [comment]
If `autoZIndex` is false, `baseZIndex` does not work. If a page has more than one PrimeVue component that uses ZIndex layering, the z-index of the first one sets as expected but for the second one (according to DOM structure) PrimeVue ZIndex layering will calculate the new z-index as 1 greater than the previous on. You could check: (https://github.com/primefaces/primevue/blob/master/src/components/utils/ZIndexUtils.js#L5)

**Comment by AutoAwesome** [comment]
If anybody else is in a similar situation - here is how I solved it:

Just add panels with `position: absolute` and move them around. Also add `@onClick` listeners and change z-index accordingly. No overlays needed.
