### ISSUE TITLE
[Overlay] show methods must need second param but docs is option

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3095]
### Describe the bug

<img width="889" alt="image" src="https://user-images.githubusercontent.com/36926073/194991147-5285e973-38b6-4f9a-961c-6e409a11c432.png">

```vue
 <Button
    class="p-button-help"
    @click="toggle"
    icon="pi pi-bookmark"
    v-bind="attrs"
  />
const overlayRef = ref<InstanceType<typeof OverlayPanel> | null>(null)

const show = async (event: any) => {
  await getOptions()
  if (options.value.length !== 0) {
    overlayRef.value?.show(event)
  }
}
```
 and what is second param target meaning?

**Comment by bahadirsofuoglu** [comment]
Hi,
We believe there is a problem with the use of the show method. We can get better results if you share the Reproduce link and PrimeVue version.

**Comment by Valar103769** [comment]
> how to use of the show method? about the second param  how to use ?

**Comment by bahadirsofuoglu** [comment]
If we are talking about the show method, the show method use event target. So we don't use it directly. We prefer the toggle method. You can find it in the docs.
