### ISSUE TITLE
[Pagnator] onPage event.page should is currentPage text  instead of index 

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3096]
### Describe the bug

https://codesandbox.io/s/youthful-elbakyan-8eg6p4?file=/src/PaginatorDemo.vue

many ui librarys is  `event.page =  Number(index + 1) `

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by bahadirsofuoglu** [comment]
We believe this is a choice. We don't think this is a bug. Any change to be made here will affect all users.
