### ISSUE TITLE
Editor: Can not click change color text and background color in Editor

### ISSUE THREAD

**Issue by huuphuc0261993** [primefaces/primevue#3097]
### Describe the bug

can not click change color text and background color in Editor

### Reproducer

https://codesandbox.io/s/vigorous-sky-yyopyk?file=/src/EditorDemo.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

step 1. click button show modal
step 2. close modal 
step 3. click button show modal and change color text, change background text not working

https://user-images.githubusercontent.com/54783850/195056939-2d357941-05d7-41df-a909-6e2de9a132c9.mov

### Expected behavior

fix above error

**Comment by Valar103769** [comment]
what screen recording app do you use
