### ISSUE TITLE
Calendar: rangeSelect's formatDate is invalid

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3102]
### Describe the bug

I create some pull request ,if you has time ,can you review them please?

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by bahadirsofuoglu** [comment]
We're unable to replicate without the reproducer, if you are able to create a reproducer in the future please create a new ticket.
