### ISSUE TITLE
PrimeVue datatable - can't reset sort to default sortfield

### ISSUE THREAD

**Issue by gvg356** [primefaces/primevue#3107]
I can't find a way to reset sort on datatable to the default sortField/sortOrder. First time the default sort is working and if I click sort on other column and perform search which refreshes the data in the table, the sort doesn't reset to the default column
`<DataTable
        id="table_searchResults"
        :value="searchResults"
        :paginator="true"
        :rows="defaultRowsPerPage"
        paginatorTemplate="Rows per page: RowsPerPageDropdown FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink"
        :rowsPerPageOptions="rowsPerPage"
        currentPageReportTemplate="{currentPage} of {totalPages}"
        :sortField="defaultSort.field"
        :sortOrder="defaultSort.sortOrder"
        lazy
        :totalRecords="totalElements"
      ></DataTable>`
**JS code**
`   const defaultSort = {
      field: "column1",
      sortOrder: 1,
    };`

**Comment by tugcekucukoglu** [comment]
Could not replicate the issue. If the problem persists, please create a codesandbox or a repo, so we can replicate the issue?
