### ISSUE TITLE
InputGroup: Textarea in InputGroup has no rounded corners

### ISSUE THREAD

**Issue by mskr** [primefaces/primevue#3109]
### Problem

A [Textarea](https://www.primefaces.org/primevue/textarea) inside an [InputGroup](https://www.primefaces.org/primevue/inputgroup) is missing rounded corners.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/10597783/195409673-4dcf123f-13f1-4e29-8149-be2e32fa15c1.png">
</details>

### Interesting fact

Replacing Textarea with InputText works.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/10597783/195408007-b4fd5144-0cc4-4691-8c84-d6eb0224e82e.png">
</details>

### Proposed Solution

Please add the same CSS selector as for input (`p-inputgroup input:first-child`) for textarea.

As long as this bug persists users need to add the following CSS to get a perfect rounded corner appearance.

```css
.p-inputgroup > textarea:first-child {
    border-top-left-radius: 3px;
    border-bottom-left-radius: 3px;
}
```

### Reproducer

https://codesandbox.io/s/modest-http-zegcy3?file=/src/App.vue

### PrimeVue version

3.12.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

https://codesandbox.io/s/modest-http-zegcy3?file=/src/App.vue

### Expected behavior

https://codesandbox.io/s/great-germain-ztd5h9?file=/src/App.vue

**Comment by bahadirsofuoglu** [comment]
Hi,
p-inputgroup class works with the input component. İf you want to use Textarea you should use custom css like your example. In short, this is expected behavior.
