### ISSUE TITLE
Datatable coltoggle changes columns order.

### ISSUE THREAD

**Issue by velavoc** [primefaces/primevue#311]
Could it be like in PrimeNG? Now if we remove a column from a table and then return it back to the table, it appears at the end of the table.

https://www.primefaces.org/primevue/showcase/#/datatable/coltoggle
https://primefaces.org/primeng/showcase/#/table/coltoggle

**Comment by cagataycivici** [comment]
Sure, we'll update the demo to keep the order.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primevue/commit/e20a6964f30437cae1cd8a08d1ab1aeaf1eed3ec

**Comment by JoJuhasz** [comment]
If you mix togglable and non-togglable columns and have non-togglable columns after togglable ones, the bug is still present.
For exemple, in the demo, if you want to keep the "code" column at the end of the row, this is not possible.
