### ISSUE TITLE
[Data table] column header ·word-break:keep-all is base case for  old development

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primevue#3115]
### Describe the bug

bad

### PrimeVue version

newest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Thank you for your contribution but we cannot reproduce most of the issues you have opened. İf you apply our issue template we can evaluate your issues and pull requests.
