### ISSUE TITLE
styleclass: TypeError: Cannot read properties of null (reading 'offsetParent')

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3116]
### Describe the bug

styleclass.esm.js:11 Uncaught TypeError: Cannot read properties of null (reading 'offsetParent')
    at el.$_pstyleclass_clicklistener (styleclass.esm.js:11:1)
el.$_pstyleclass_clicklistener @ styleclass.esm.js:11

![image](https://user-images.githubusercontent.com/16963395/195586062-122fd89e-01a9-425e-a2e4-4385c7435212.png)

In code:
function bind(el, binding) {
    el.$_pstyleclass_clicklistener = () => {
        const target = resolveTarget(el, binding);

        if (binding.value.toggleClass) {
            if (DomHandler.hasClass(target, binding.value.toggleClass)) DomHandler.removeClass(target, binding.value.toggleClass);
            else DomHandler.addClass(target, binding.value.toggleClass);
        } else {
            if (target.offsetParent === null) enter(target, el, binding);
            else leave(target, binding);
        }
    };

    el.addEventListener('click', el.$_pstyleclass_clicklistener);
}

![image](https://user-images.githubusercontent.com/16963395/195586108-edd53f13-0b74-4af0-9b52-fedf264f1bca.png)

Add check null of undefined for offsetParent

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

all

**Comment by bahadirsofuoglu** [comment]
Hi,
Could you send a code sandbox link for reproducing?

**Comment by NeluQi** [comment]
> Hi, Could you send a code sandbox link for reproducing?

This rarely happens and I can't even figure out which styleclass it's throwing out. It does not affect the work (or maybe it does), but the error in the console is not pleasant
