### ISSUE TITLE
FormLayout is missing in Showcase

### ISSUE THREAD

**Issue by kuz30** [primefaces/primevue#312]
You can't find any reference to FormLayout in Showcase:
https://www.primefaces.org/primevue/showcase/#/formlayout
https://github.com/primefaces/primevue/blob/63139035576ade0e4fa74d273516d32b06c81088/src/views/formlayout/FormLayoutDoc.vue

**Comment by cagataycivici** [comment]
Deployed just now;

https://primefaces.org/primevue/showcase/#/formlayout
