### ISSUE TITLE
Dropdown: Add autoZIndex and baseZIndex props as in other components

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3121]
### Describe the feature you would like to see added

Most components that use `ZIndexUtils` expose prop `autoZIndex` which can disable automatic z-index assignment feature. 

Dropdown is missing this feature, which makes hard working with it in certain conditions (e.g. Modals with sticky site header with manually assigned z-indexes.

### Describe the solution you'd like

Add `AutoZIndex` and `baseZIndex` props to the Dropdown component

**Comment by mvisd** [comment]
+1

The dropdown breaks for me in a model with z-index 1101. The choices will be rendered underneath the modal.

**Comment by kaipaysen** [comment]
With the recent release 3.22.3 this became an issue for us as well. We're having a DropDown in a Sidebar Component. 
As a workaround we added `panelClass="primevue-dropdown-zindex-workaround"` to the component. 
```
<template>
    <Dropdown 
                class="p-inputwrapper-filled"
                v-model="fieldValue" 
                :options="selectOptions" 
                optionLabel="text" 
                optionValue="value" 
                :id="inputId" 
                :aria-describedby="inputErrorId" 
                :disabled="readOnly"
                panelClass="primevue-dropdown-zindex-workaround"
            />
</template>
```

```
<style lang="scss">
    .primevue-dropdown-zindex-workaround {
        z-index: 1400 !important;
    }
</style>
```

**Comment by zachlearnscode** [comment]
> With the recent release 3.22.3 this became an issue for us as well. We're having a DropDown in a Sidebar Component. As a workaround we added `panelClass="primevue-dropdown-zindex-workaround"` to the component.
> 
> ```
> <template>
>     <Dropdown 
>                 class="p-inputwrapper-filled"
>                 v-model="fieldValue" 
>                 :options="selectOptions" 
>                 optionLabel="text" 
>                 optionValue="value" 
>                 :id="inputId" 
>                 :aria-describedby="inputErrorId" 
>                 :disabled="readOnly"
>                 panelClass="primevue-dropdown-zindex-workaround"
>             />
> </template>
> ```
> 
> ```
> <style lang="scss">
>     .primevue-dropdown-zindex-workaround {
>         z-index: 1400 !important;
>     }
> </style>
> ```

We have run into this same issue. As far as your workaround goes, how can you be sure that the 1400 value will always work?

**Comment by zachlearnscode** [comment]
The most recent release, 3.22.3, includes changes to the zIndexUtils files. We were able to solve the issue you're addressing with your workaround by reverting to 3.22.2. It seems like 3.22.3 might have introduced a bug

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/3554
