### ISSUE TITLE
AutoComplete:  Slot content not working

### ISSUE THREAD

**Issue by DavidSprauel** [primefaces/primevue#3122]
### Describe the bug

I'm using the auto complete to search through DB for existing user's email.
The component is rendering fine but i'm unable to use the `content` slot to customize the list of results.

Here is my code:

```js
 <AutoComplete v-model="form.mainContact.email"
                                          class="w-100"
                                          inputClass="w-100 form-control"
                                          :dropdown="false"
                                          :suggestions="usersSuggest"
                                          @complete="searchUser($event)">
                                <template #content="{items}">
                                    <ul class="list">
                                        <li class="list-item" v-for="user in items" :key="user.id">
                                            item
                                        </li>
                                    </ul>
                                </template>
                            </AutoComplete>
```

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 105.0.5195.125

### Expected behavior

The content slot is present in the AutoComplete component in my node_modules primevue/autocomplete dir but it doesn't work. Am I missing something ? 

This is the doc. Thing is i'm using a framework, and i need to set up a specific class to specific elements like `ul` and `li`
![image](https://user-images.githubusercontent.com/3330345/196199329-bf71c444-072a-4469-838b-4a8fdab27ed7.png)

**Comment by bahadirsofuoglu** [comment]
Hi,
Virtual Scroller has a content slot. Autocomplete just uses this slot. You can use #item or #optiongroup slots such as this [https://www.primefaces.org/primevue/autocomplete](example)
