### ISSUE TITLE
Calendar: Not responsive to view changes.

### ISSUE THREAD

**Issue by iampeternguyen** [primefaces/primevue#3123]
### Describe the bug

Toggling the view from `date` to `month` doesn't work with the calendar.

### Reproducer

https://codesandbox.io/s/cool-wildflower-vgi1k2?file=/src/App.vue

### PrimeVue version

2.9.1

### Vue version

2.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

See sandbox. 

### Expected behavior

Would expect changing the view would update the component

**Comment by iampeternguyen** [comment]
in the sandbox, binding key to type works as a workaround

**Comment by bahadirsofuoglu** [comment]
This is expected behavior with an inline selected calendar. But you can re-render the component. It worked when I tried it.
https://michaelnthiessen.com/force-re-render/
