### ISSUE TITLE
inputnumber: Design problem

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3126]
### Describe the bug

![image](https://user-images.githubusercontent.com/16963395/196626798-72ec3f74-a704-48a5-a4eb-f9db06c8217f.png)

![image](https://user-images.githubusercontent.com/16963395/196626850-9eaec809-8f14-4d54-b52f-740d77f4daed.png)

theme
![image](https://user-images.githubusercontent.com/16963395/196631804-b6e55bd7-bddc-4cbf-a1e2-31729b4db738.png)

The new thing is very abrupt and ugly ending with buttons
Solution: either do not update at all, or stroke to the end
Or you can add rounding for the border (for its end)

### Reproducer

https://www.primefaces.org/primevue/inputnumber

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Currently, it's not on the PrimeVue roadmap.  If there is more demand, we'll definitely reconsider. 

Thank you for your feedback.
