### ISSUE TITLE
InputNumber Up Down buttons send form on submit

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#313]
Primevue: v1.3.2
My form is being sent when up/down buttons are pressed. See bellow example:
```
<form @submit.prevent="onSubmit">
  <InputNumber />
  <Button label="Save" />
</form>
```
The solution is to add `type="button"` to the up/down buttons in InputNumber component.
Thanks.

**Comment by fairking** [comment]
There could be other situations with other components.

**Comment by cagataycivici** [comment]
Default type is button now for all components that use buttons so resolved the issue, thank you.

**Comment by fairking** [comment]
Thank you @cagataycivici  👍

**Comment by vcmenezes** [comment]
The image component is submitting my form when clicking in the preview overlay, how to fix it?

**Comment by vcmenezes** [comment]
To fix the issue for the image component:
```javascript
<Image
  :src="image.objectURL || image.url"
  :pt="{
    button: {
      type: 'button',
    },
  }"
  :preview="true"
/>
```
