### ISSUE TITLE
FileUpload: Type Definition does not allow to access files

### ISSUE THREAD

**Issue by some-user123** [primefaces/primevue#3133]
### Describe the bug

I'm using `FileUpload` and would like to access the files that have been selected for upload using a `ref`:

```html
<template>
  <div id="app">
    <FileUpload ref="fileUpload"> </FileUpload>
    {{ fileUpload }}
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue"
import FileUpload from "primevue/fileupload";

const fileUpload = ref<InstanceType<typeof FileUpload>>();
</script>
```

If I output the ref `fileUpload` the selected files are accessible via `fileUpload.files`. However, the type definition does not allow to access them.

E.g. `console.log(fileUpload.value.files)` in a script works, but raises a typescript error:
> Property 'files' does not exist on type 'FileUpload'. 

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Add `FileUpload` with a `ref`
2. Try to access `files` from script or in template

### Expected behavior

Should work (as it already does) but without typescript error...

**Comment by bahadirsofuoglu** [comment]
Hi,
You can access selected files with select emit. Is there anything that prevents you from using it this way?

**Comment by some-user123** [comment]
To my understanding I would at least have to track `select` and `remove` events and maintain a copy of the state that is already properly tracked and accessible from the component - only the typing is missing.

Adding a `update:files` event to allow binding with `v-model` would be a nice alternative as well.

**Comment by bahadirsofuoglu** [comment]
We are working on a big feature for fileupload component. Next release you can test it. Then if you want you can open a new ticket.

**Comment by some-user123** [comment]
Thanks for the hint. I took a look at the changes in 3.18. It seems, they are mainly around templating (which is great). I couldn't find a change related to the problem above. Can you give me a hint? Or kindly re-open this issue instead of creating a new one with identical content.

**Comment by bahadirsofuoglu** [comment]
I think it is the right way to follow the process with select and remove events. The situation you are experiencing is really a type error. Because you want to reach a property that we do not give direct access to. Thanks for the update-file idea. You can open a new ticket for this and we will consider it.
