### ISSUE TITLE
Autocomplete: focus method

### ISSUE THREAD

**Issue by maherma-adg** [primefaces/primevue#3138]
### Describe the feature you would like to see added

Add a focus method on autocomplete component to be able to set focus on component programatically. 
This request can be extended to any other complex (all?) components to allow a homogeneus API.

### Is your feature request related to a problem?

The usually hack to set focus via DOM:

```
ComponentRef.value.$el.focus()
```

doesn't work because this control is complex and the input element is deeply nested in DOM. you need to dig into to set focus properly.

You can set focus with:
```
ComponentRef.value.$refs.focusInput.focus()
```

but this code is implementation dependant and can stop working at any time.

### Describe the solution you'd like

Add a focus() method to component to provide a clean and standard API (equivalent to HTML element API) that take care of the internal implementation of setting the focus.

### Additional context

this request is in the same direction of  #2397

**Comment by cantin-f** [comment]
Can't make it works :

``

**Comment by cantin-f** [comment]
Can't make it works, is this the right way :

`
<template>
  <AutoComplete
    ref="autocomplete"
    v-model="dontcare"
    :suggestions="dontcare2"
  >
  </AutoComplete>
</template>

...
  mounted() {
    this.$refs.autocomplete.value.$refs.focusInput.focus()
  },
...
`

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by sidjoshi001** [comment]
Find the input inside & then you can apply the focus as below

@cantin-f @maherma-adg 

`autocomplete.value.$el.querySelector('input').focus()`
