### ISSUE TITLE
Tooltip: Triggering any tooltip fails to set its own auto-zindex, and affects any other component's ability to set an auto-zindex

### ISSUE THREAD

**Issue by adamshafer** [primefaces/primevue#3144]
### Describe the bug

When running a site in localhost (dev mode) using npm run dev, activating a tooltip on any element shows the tooltip. However, the auto-zindex that usually happens on a tooltip is not occurring. After the first failed auto-zindex, any other component that might use an auto-zindex also fails to happen, causing odd layering problems on our site. I have tried this in our codebase and in a blank Vue 3 project using the standard create-vue setup.

When the site is compiled and served in a live environment, this problem does not occur. It is only occurring while in dev mode.

### Reproducer

https://codesandbox.io/s/flamboyant-solomon-vk4uc7

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Please see the codesandbox link. For some reason this code won't run in codesandbox but will run locally. 

Essentially if you activate a tooltip anywhere on any page, the auto-zindexing doesn't work, and it then breaks all other instances in which the auto-zindexing should occur... resulting in z-indexes messing up and content being in the wrong layers.

### Expected behavior

As it used to, auto-zindex should work for Tooltips, and it should not affect other components ability to auto-zindex when working in a development environment.

**Comment by bahadirsofuoglu** [comment]
Hi,
Link is not working

**Comment by adamshafer** [comment]
I've uploaded my project to https://github.com/adamshafer/sandbox ... it will run locally, but for some reason doesn't run in the codesandbox.io environment.

**Comment by tugcekucukoglu** [comment]
We could not replicate the issue. We clone the codesandbox but it's not working on the local. If the problem still persists, please create a working codesandbox or a repo. 

Closing for now.

**Comment by dinyo** [comment]
try #2468 for workaround
