### ISSUE TITLE
Tree Component: new `disabled` prop

### ISSUE THREAD

**Issue by Pedro-Mag** [primefaces/primevue#3147]
### Describe the bug

When applying disabled prop to Tree component and selectionMode="checkbox", as described in the documentation, the behavior of the component does not change.

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 106.0.5249.119

### Expected behavior

It's expected the checkbox to become disabled.

**Comment by bahadirsofuoglu** [comment]
Hi, Could you send any link for reproducing?

**Comment by Pedro-Mag** [comment]
Here is the link:

https://codesandbox.io/s/cranky-babbage-iiozwp

**Comment by bahadirsofuoglu** [comment]
There is no disable prop in this component. It can be done as a new feature in the future. That's why I'm changing the label. Thank you for the feedback.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
