### ISSUE TITLE
AutoComplete: Max selectable for multiple

### ISSUE THREAD

**Issue by johnwc** [primefaces/primevue#3150]
### Describe the feature you would like to see added

Being able to set the max that can be selected when multiple option is enable.

**Comment by cuberinooo** [comment]
This feature would also be an option for this: https://github.com/primefaces/primevue/issues/4108 (using max item= 1)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
