### ISSUE TITLE
Menu: Using a separator in a Menu component breaks when loading the menu

### ISSUE THREAD

**Issue by admin-nexgen** [primefaces/primevue#3153]
### Describe the bug

The latest update breaks the Menu component when you add a separator to the menu.

This was working fine in version 3.17.0.

### Reproducer

https://codesandbox.io/s/nifty-chebyshev-nth5i1

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Add a separator to the Menu component

### Expected behavior

Expect to see a separator in the Menu as it was in the previous version 3.17.0

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3151
