### ISSUE TITLE
FileUpload: Failed to resolve the Badge and Button components 

### ISSUE THREAD

**Issue by FilipeAlmeida20** [primefaces/primevue#3154]
### Describe the bug

The FileContent component inside the FileUpload does not locally register the Badge and Button components.
![image](https://user-images.githubusercontent.com/72601872/197741853-ab69280b-7565-4e2a-8619-89b7ed59986e.png)
As you can see in the FileContent implementation there is no local registration of both the Button and Badge components: 
![image](https://user-images.githubusercontent.com/72601872/197742361-f0a7ffeb-9946-4c3f-8103-35e913d499ee.png)

Note: this warning is not shown in the PrimeVue demo because the components are globally registered.

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 106

### Expected behavior

The components should be resolved.

**Comment by tugcekucukoglu** [comment]
Fixed https://github.com/primefaces/primevue/commit/9a6183cf8da28c5aae7696253c8db5f80d103d44

**Comment by bahadirsofuoglu** [comment]
This issue will be fixed in 3.18.1. But now you can import badge component globally for fixing warnings (temporary solution). Thank you for your feedback.
