### ISSUE TITLE
Slider: Dragging to max getting 'value.toFixed is not a function'

### ISSUE THREAD

**Issue by kayahasa** [primefaces/primevue#3160]
### Describe the bug

1- Slider added to the page
2- Set max value to 100
3- Drag slider till max (100)

Result:

Slider freeze and cant change/slide component.

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

chrome

### Steps to reproduce the behavior

1- Slider added to the page
2- Set max value to 100
3- Drag slider till max (100)

Result:

Slider freeze and cant change/slide component.

**Comment by bahadirsofuoglu** [comment]
Hi, I tried but I could not replicate this issue. Could you share any sandbox link?
