### ISSUE TITLE
PanelMenu: passing computed value as a model prop

### ISSUE THREAD

**Issue by luk9400** [primefaces/primevue#3166]
### Describe the bug

When you pass `computed` value instead of `ref` to `model` prop in `PanelMenu`, you cannot expand any menu item, because computed values are immutable. 

### Reproducer

https://codesandbox.io/s/runtime-http-vdle6p

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open PanelMenuDemo in codesandbox
2. Change `items` declaration to `computed` instead of `ref`
3. Try to expand "File" (or any other) menu item
4. Nothing happens

### Expected behavior

You can pass `computed` values to `model` prop.

Possible solutions:
- don't try to mutate passed object (preferred)
- mention about this behavior in documentation

I know that this topic was already discussed in https://github.com/primefaces/primevue/issues/2268 and https://github.com/primefaces/primevue/issues/2766, however I think that at least mentioning it in documentation as a warning could be beneficial.

**Comment by igorraphael** [comment]
@luk9400 This work if you pass v-model:expandedKeys, [look here.](https://github.com/primefaces/primevue/blob/master/src/views/panelmenu/PanelMenuDemo.vue)
