### ISSUE TITLE
Overlay Scrollbars

### ISSUE THREAD

**Issue by smhmd** [primefaces/primevue#317]
Could we have minimal overlay scrollbars?

![image](https://user-images.githubusercontent.com/46059092/82107892-85536380-971a-11ea-948a-cb1b318e6d14.png)

**Comment by cagataycivici** [comment]
Which OS are you using?

**Comment by smhmd** [comment]
`Linux manjaro 5.6.11-1-MANJARO`, I didn't include that thinking both Linux and Windows suffer from this.

**Comment by cagataycivici** [comment]
After a discussion, we decided to rely on scrollbars of OS. This might help;

https://alligator.io/css/css-scrollbars/
