### ISSUE TITLE
FileUpload: add invalidFileTypeMessage prop

### ISSUE THREAD

**Issue by XindiShang** [primefaces/primevue#3170]
### Describe the feature you would like to see added

Being able to pass an invalidFileTypeMessage prop to the FileUpload component, in order to change the language of the error message.

### Describe alternatives you have considered

Provide an option in locale setup

**Comment by tugcekucukoglu** [comment]
This prop already exists but is not documented. Please check https://github.com/primefaces/primevue/blob/master/src/components/fileupload/FileUpload.vue#L84

Sorry for the confusion.

**Comment by XindiShang** [comment]
> This prop already exists but is not documented. Please check https://github.com/primefaces/primevue/blob/master/src/components/fileupload/FileUpload.vue#L84
> 
> Sorry for the confusion.

Yep, I noticed the prop in source code, thanks.
