### ISSUE TITLE
BlockUI: Components peeking out of the 'BlockUI' can still be interacted with.

### ISSUE THREAD

**Issue by AutoAwesome** [primefaces/primevue#3175]
### Describe the bug

When blocking the UI using BlockUI, components which 'peek out' of the greyed out area can still be interacted with.

### Reproducer

https://codesandbox.io/s/cool-dawn-h20y75?file=/src/BlockUIBug.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add BlockUI component
2. Add component which peeks out of the bounds a bit (like slider)
3. Set BlockUI to blocked and try to interact with the slider.

### Expected behavior

Any component under the BlockUI element should be effectively disabled/blocked when :blocked is set to true.

**Comment by bahadirsofuoglu** [comment]
Hi,
We can calculate height or width but we don't believe this is a good solution. You can override CSS or set the padding. If there is a situation that prevents you, we can re-evaluate
