### ISSUE TITLE
Sidebar: Add ability to keep the contents of the sidebar alive when closed

### ISSUE THREAD

**Issue by harveylee** [primefaces/primevue#3176]
### Describe the feature you would like to see added

A flag that allows me to selectively configure the Sidebar not to dispose its contents when `visible` is set to false.

### Is your feature request related to a problem?

My users are frustrated when they open the sidebar and the contents have been reset. 

e.g. in a simple case: if the sidebar contains a long list, they scroll halfway down, close the sidebar and open it again, the scroll position is reset to the top.

### Describe the solution you'd like

Set a prop (e.g. `keep-alive`) on Sidebar that switches the mode of Sidebar and causes it not to dispose the components in the default slot.

### Describe alternatives you have considered

I can, of course, write my own Sidebar that does this.

I've tried experimenting with the `KeepAlive` built-in Vue component but I couldn't get it working / I don't think it's suitable for this.

### Additional context

I had a go at implementing this in #3171

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeVue version. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
