### ISSUE TITLE
Menubar:  #item slot is never called

### ISSUE THREAD

**Issue by paceband** [primefaces/primevue#3177]
### Describe the bug

Slot #item is never called

Example:
```
<MegaMenu :model="items">
    <template #start>
        Before
    </template>
    <template #item="{item}">
        <a :href="item.url">{{item.label}}</a>
    </template>
    <template #end>
        After
    </template>
</MegaMenu>
```

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

The slot #item should be called.

**Comment by tugcekucukoglu** [comment]
Can not replicate the issue. Here is a working example. https://codesandbox.io/s/jolly-glade-x6b0vr?file=/src/MegaMenuDemo.vue

**Comment by paceband** [comment]
Sorry... I was talking about Menubar which does not make use of #item slot.
