### ISSUE TITLE
Adding Filters: Dynamic Datatable

### ISSUE THREAD

**Issue by mohd-fahd** [primefaces/primevue#3181]
### Describe the feature you would like to see added

Hello guys, is there any possible way to set Filters in Dynamic Datatable ?

**Comment by tugcekucukoglu** [comment]
This is not an issue.

**Comment by mohd-fahd** [comment]
I have created a Dynamic datatable with filter on it using Multiselect . Its not working for me. 

Please suggest me its that possible or not, because my project is getting delayed for this issue.

**Comment by tugcekucukoglu** [comment]
A codesandbox link could help to understand the problem.

**Comment by mohd-fahd** [comment]
https://codesandbox.io/s/quizzical-field-725j72?file=/src/App.vue

**Comment by tugcekucukoglu** [comment]
thanks for the codesandbox. We'll review it again.

**Comment by tugcekucukoglu** [comment]
Please check this example and update the codesandbox https://www.primefaces.org/primevue/datatable/filter

Choose to use filter row or filter menu
