### ISSUE TITLE
Menu: Separator No Longer Works

### ISSUE THREAD

**Issue by jsmatlick** [primefaces/primevue#3184]
### Describe the bug

When using a separator in a menu, an exception is thrown and the menu does not render.

menu.esm.js:571 Uncaught (in promise) TypeError: $options.separatorClass is not a function
    at menu.esm.js:571:72
    at renderList (runtime-core.esm-bundler.js:2894:22)
    at menu.esm.js:554:82
    at renderList (runtime-core.esm-bundler.js:2894:22)
    at menu.esm.js:536:72
    at Proxy.renderFnWithContext (runtime-core.esm-bundler.js:856:19)
    at Proxy.<anonymous> (runtime-core.esm-bundler.js:1957:78)
    at renderComponentRoot (runtime-core.esm-bundler.js:902:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5615:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome Version 106.0.5249.119 (Official Build) (x86_64)

### Steps to reproduce the behavior

Using the example for a menu with a separator, get an error in the console and the menu does not render.

```
<template>
  <div>
    <h5>Inline</h5>
    <Menu :model="items" />

    <h5>Overlay</h5>
    <Button
      type="button"
      label="Toggle"
      @click="toggle"
      aria-haspopup="true"
      aria-controls="overlay_menu"
    />
    <Menu
      id="overlay_menu"
      ref="menu"
      :model="items"
      :popup="true"
    />
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  setup() {
    const menu = ref();
    const items = [
      {
        label: 'Item 1',
      },
      {
        separator: true,
      },
      {
        label: 'Item 2',
      },
    ];

    const toggle = (event) => {
      menu.value.toggle(event);
    };

    return { items, menu, toggle };
  },
};
</script>
```

### Expected behavior

The menu to render and be functional with no exceptions shown in the console.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3151

Fixed for the next version.
