### ISSUE TITLE
DataTable: the table is broken in 3.18.0

### ISSUE THREAD

**Issue by erropix** [primefaces/primevue#3189]
### Describe the bug

Once I updated primevue to 3.18, all the tables in my application are broken and after disabled props one by one, I found that if `alwaysShowPaginator` is set to `false` the table breaks, and I get this error in the console:

```
Uncaught (in promise) TypeError: this.$refs.paginator is not iterable
    at Proxy.setPaginatorAttribute (primevue_datatable.js?v=670db3b1:1624:22)
    at Proxy.mounted (primevue_datatable.js?v=670db3b1:1523:10)
    ...
```
### Reproducer

https://codesandbox.io/s/primevue-3-18-0-table-paginator-bug-n3f3v3?file=/src/App.vue

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by pkwestm** [comment]
I think this error is related to the primevue/paginator. I got the same problem using only Paginator component. Error is shown when count < limit. I solved this adding a v-if to not render paginator in those cases. My working code is as follows
`
    <Paginator
      v-if="numCount > numLimit"
      class="mt-4"
      :first="(curPageNum - 1) * numLimit"
      :rows="numLimitlimit"
      :always-show="false"
      :total-records="numCount"
      @page="onPage($event)"
    ></Paginator>
`

**Comment by erropix** [comment]
> 

Yes, that may work in your case, but for the DataTable component, we can't do the same.

**Comment by smit6488** [comment]
Hi, @all I am getting the error related to data table

Here is the screenshot 
![image](https://user-images.githubusercontent.com/107909172/229032514-73d8da81-6989-4c40-986e-5f231d12d9a2.png)
