### ISSUE TITLE
SplitButton: Expands Up 

### ISSUE THREAD

**Issue by choff5507** [primefaces/primevue#3191]
### Describe the bug

Going from 3.17.0 to 3.18.0 causes a SplitButton I am using to open upwards for some reason, this was not a problem until I updated. I went back to 3.17.0 and confirmed that going back to the previous version does not suffer from this. 

The only thing thats changed is the version of PrimeVue. 

There are pics illustrating it here:
https://imgur.com/a/Y3XPLU0

### PrimeVue version

3.18.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chromium Based 

### Expected behavior

Splitbutton should open downwards.

**Comment by bahadirsofuoglu** [comment]
Hi, Could you share any link for reproducing? Seems like a class affected but we can't know without a reproducer.

**Comment by tugcekucukoglu** [comment]
SplitButton is a composite component that includes Button and TieredMenu components. As part of general accessibility and better UX, when the button is clicked, the button loses its focus and the popup menu opens and focuses first available item.

If there is another problem, please let us know.
