### ISSUE TITLE
Tooltip: Appears underneath Modals

### ISSUE THREAD

**Issue by gbdubs** [primefaces/primevue#3199]
### Describe the feature you would like to see added

If you use a tooltip directive in the contents of a modal, the resulting tooltip doesn't recieve a Z-Index higher than that of the modal on which it appears, making it so that the tooltip content isn't visible. Minimal example:

```
<Dialog>
  <Button v-tooltip="'Example'" />
</Dialog>
```

### Describe the solution you'd like

I'd love a configuration option for the tooltip directive that would instruct it to use ZIndexUtils in much the same way that Dialogs/Toasts do with `:auto-z-index="true"`

**Comment by bahadirsofuoglu** [comment]
Hi, You can set z-index as follow. When I test it, I see that the tooltip z-index is higher. Is there anything I missed?


`
import {createApp} from 'vue';
import PrimeVue from 'primevue/config';
const app = createApp(App);

app.use(PrimeVue, {
    zIndex: {
        modal: 1100,        //dialog, sidebar
        overlay: 1000,      //dropdown, overlaypanel
        menu: 1000,         //overlay menus
        tooltip: 1100       //tooltip
    }
});
`
