### ISSUE TITLE
Wrong date with "yy.mm.dd" date format

### ISSUE THREAD

**Issue by RosenbecherRoland** [primefaces/primevue#32]
Typing date with dateFormat="yy.mm.dd" gives wrong date, in day section automatically inserts leading zero and cannot be typed e.q. "23" to day, it forces "02" when "2" is pressed. And without specifying dateFormat in the component it gives date in default format, however it's set in "hu" locale.

Component:
Calendar v-model="myDate" :showIcon="true" :locale="hu" :showOnFocus="false" dateFormat="yy.mm.dd"

function returns "hu" data:
 return {
            firstDayOfWeek: 1,
            dayNames: ["Vasárnap", "Hétfő", "Kedd", "Szerda", "Csütörtök", "Péntek", "Szombat"],
            dayNamesShort: ["Vas", "Hét", "Ke", "Sze", "Csü", "Pén", "Szo"],
            dayNamesMin: ["Vas", "Hét", "Ke", "Sze", "Csü", "Pén", "Szo"],
            monthNames: [ "Január","Február","Március","Április","Május","Június","Július","Augusztus","Szeptember","Október","November","December" ],
            monthNamesShort: [ "Jan", "Feb", "Már", "Ápr", "Máj", "Jún","Júl", "Aug", "Szep", "Okt", "Nov", "Dec" ],
            today: 'Ma',
            clear: 'Törlés',
            dateFormat: 'yy.mm.dd',
            weekHeader: 'Wk'
    }

**Comment by cagataycivici** [comment]
Isn't this expected, from the docs;

y - year (two digit)
yy - year (four digit)

So double y means four digits so zeros are added.
