### ISSUE TITLE
Css styles get messed when upgrade from 1.3.2 to primevue@2.0.0-beta.1

### ISSUE THREAD

**Issue by Rocking80** [primefaces/primevue#320]
When I upgrade primevue@1.3.2 to primevue@2.0.0-beta.1, some erros occurred in console and some components not shown correctly.

Do I need to do something before this upgrade? Or I need to change exising code? Thanks.

**Comment by cagataycivici** [comment]
2.0.0 has a brand new theming infrastructure reimplemented from scratch. All free themes have been upgraded to be compatible. Which theme are you using?

**Comment by Rocking80** [comment]
I am using nova-light

```
import "primevue/resources/themes/nova-light/theme.css";
```
And I just uninstalled 1.3.2 primevue and installed the latest primevue as below.

```
# npm uninstall primevue
# npm install primevue --save
# npm ls | grep primevue 
├── primevue@2.0.0-beta.1
```

**Comment by cagataycivici** [comment]
That seems correct, do you have a screenshot for review? Live demo seems to be working fine.

**Comment by cagataycivici** [comment]
Also please remove node_modules and try a clean npm install.
