### ISSUE TITLE
Max file size error message shows wrong file size.

### ISSUE THREAD

**Issue by neptunecentury** [primefaces/primevue#3206]
I have a FileUpload control which I am setting the max file size property to 104857600 (100MB). When I try to upload a file that exceeds this limit, it is working correctly and showing an error. But the error message says 104.858 MB and not 100 MB. It seems that the max file size is being calculated like maxFileSize / 1000 / 1000, when it should be 1024.
![image](https://user-images.githubusercontent.com/3356091/199583131-c522f030-a925-469d-9a82-152c7bb77bfe.png)

**Comment by neptunecentury** [comment]
@tugcekucukoglu I just reproduced it on the demo in codesandbox...

![image](https://user-images.githubusercontent.com/3356091/200323809-af325e27-c391-457e-ae21-b35fd53499df.png)

https://codesandbox.io/s/competent-murdock-cxdvp8?file=/src/FileUploadDemo.vue

The problem is in the calculation. I checked the code. It is using 1000 as bytes per k, and that is wrong. It should be 1024. Thus, when I use max file size of 104857600 (which is exactly 100 MB) the FileUpload control is showing 104 MB.
![image](https://user-images.githubusercontent.com/3356091/200324451-ba3b17c8-4f74-4b97-befd-31248f3649ba.png)

**Comment by tugcekucukoglu** [comment]
<img width="267" alt="Screen Shot 2022-11-11 at 16 13 46" src="https://user-images.githubusercontent.com/32294991/201348061-cee7213f-9dca-463c-91d8-5fc1acfe453d.png">

**Comment by neptunecentury** [comment]
There seems to be some fundamental misunderstanding. 1 kilobyte is not 1000 bytes, it is 1024. So, the calculate is wrong. This example shows what happens when I try to use just 100,000,000 (which is actually around 95MB)
![image](https://user-images.githubusercontent.com/3356091/201350033-bcec586c-b97a-497b-9565-ec59502016af.png)

I set the maxFileSize to 100,000,000. This makes the FileUpload show 100MB. BUT, when i tried to upload my EXACTLY 100 MB file, I get an error message. 100,000,000 bytes is LESS than 100MB because 100MB is 104,857,600 bytes.

**Comment by coldpumpkin** [comment]
Incredible how this hasn't been fixed yet.
