### ISSUE TITLE
Toast: Allow to be used outside of script setup

### ISSUE THREAD

**Issue by lifelofranco** [primefaces/primevue#3209]
### Describe the feature you would like to see added

Allow toast to be called outside of script setup.

### Is your feature request related to a problem?

Currently, the Toast component only works when using inside of a script setup call.

### Describe the solution you'd like

Toast can be called from anywhere, inside compostables or in a pinea store, or even inside the router.

### Additional context

Looking at the code, useToast uses inject and so this limits its usage. May need a refactor to make it more reusable.

**Comment by lifelofranco** [comment]
Any feedback from this?

**Comment by service-paradis** [comment]
I'm following this thread! I was really surprised that we cannot use Toast outside of script setup.

**Comment by salvw** [comment]
Also see this [thread on stackoverflow.](https://stackoverflow.com/questions/72425297/vue-warn-inject-can-only-be-used-inside-setup-or-functional-components)

**Comment by ericktucto** [comment]
hello, how do you close toastmessage from custom button inside toastmessage ?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
