### ISSUE TITLE
Menu: Make initial focus id configurable on popup menus

### ISSUE THREAD

**Issue by pkwestm** [primefaces/primevue#3210]
### Describe the feature you would like to see added

Make initial index of focus in Menu component configurable. In 3.18 there was a change that focuses the first menu item in a popup list. This is something i would like to disable as it does not fit my usage of the component.

### Describe the solution you'd like

Add prop that makes this configurable.

### Describe alternatives you have considered

Currently i am listening to the "show"-event and edit focusedOptionIndex directly from component parent. But I feel this should be configurable in the component.

### Additional context

![Screenshot from 2022-11-05 10-26-19](https://user-images.githubusercontent.com/5667363/200113070-bb759858-8856-4a32-9865-12a26daf695b.png)
Top item is in focus and highlighted.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
