### ISSUE TITLE
SelectButton: Material Ui Theme has uggly space

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3213]
### Describe the bug

In **Material Ui Themes** SelectButtons with custom template are displayed with an additional space on the right.
![image](https://user-images.githubusercontent.com/8471027/200264931-4cfbcf4d-f7e7-4d98-9398-adb889e1dd40.png)
![image](https://user-images.githubusercontent.com/8471027/200265941-0f93c4dc-a40f-48e6-935e-1ec6886959e7.png)

### Reproducer

https://www.primefaces.org/primevue/selectbutton

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. go to https://www.primefaces.org/primevue/selectbutton
2. change the theme to "Material Design Compact"

**Comment by tugcekucukoglu** [comment]
It's Material design for the Button component and SelectButton consists of Button components with default templating. SelectButton provides option slot so the styling could be changed easily.

**Comment by Rakasch** [comment]
Icon Buttons do not have that spacing in the Material Design.
Therefore, the spacing at Selectbuttons does not seem intentional to me.
![image](https://user-images.githubusercontent.com/8471027/201347417-72a6489c-b9cf-4bc0-88e1-6e0d07142162.png)
