### ISSUE TITLE
TabMenu: Not accessible with keyboard when used with vue-router

### ISSUE THREAD

**Issue by ztiromoritz** [primefaces/primevue#3214]
### Describe the bug

When the TabMenu is used with vue-router and we are on a route that is not matched in the TabMenu, and we just loaded the page, then the TabMenu is not accessible via keyboard navigation.

All entries have tabindex=-1

### Reproducer

https://codesandbox.io/s/hidden-feather-e76vry

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

chrome

### Steps to reproduce the behavior
[EDIT: clarification, Links corrected]

See the sandbox example above 
- Navigate to : https://e76vry.csb.app/#/
- Press Tab on keyboard several times 
    -> works as expected, we can reach the TabMenu with keyboard focus
    
- Navigate to: https://e76vry.csb.app/#/career  
- Reload the page.
- Press Tab on keyboard several times 
    -> TabMenu with main Navigation items no longer accessible using "Tab"

### Expected behavior

TabMenu used as main navigation is accessible via keyboard, even if we are not on a matched route.

**Comment by ztiromoritz** [comment]
In the first version, there was a wrong link to the sandbox result. 
I corrected it.

**Comment by tugcekucukoglu** [comment]
This is expected behavior. If the router does not match with the item 'to' prop, the tabindexes will stay -1.

**Comment by ztiromoritz** [comment]
It is expected behaviour, that a navigation item is not reachable via keyboard input?
Yes, I understand that, if one of the elements is reachable because it matches the route, you can reach them all. (By switching to Left/Right-Keys.)

But in the example I posted, the whole component is made unreachable to keyboard only users. 

Before 3.18.1 this would have been no problem. 
I think the behavior was introduced with https://github.com/primefaces/primevue/pull/2993  

Is there a workaround so that one can select on of the Items, without touching the mouse?
