### ISSUE TITLE
PanelMenu: style does not load under custom theme

### ISSUE THREAD

**Issue by ArinSantry** [primefaces/primevue#3218]
### Describe the bug

Since the 3.18.0 update, our PanelMenu has not been displaying correctly under our custom theme.

PanelMenu under saga-blue theme (similar to our custom theme):
![image](https://user-images.githubusercontent.com/75813416/200402724-d68bceb4-9281-446f-9884-2576404662a1.png)

PanelMenu under our custom theme:
![image](https://user-images.githubusercontent.com/75813416/200402833-c7404646-817e-4d8e-bc9b-a40c661b50f8.png)

The PanelMenu still appears without styling, even when copying the CSS from saga-blue directly into our custom theme. All other aspects of the theme are still correct.

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Expected behavior

The PanelMenu under the custom theme should look similar to the menu in the saga-blue theme.

**Comment by bahadirsofuoglu** [comment]
There were some style changes during our accessibility improvements. If you have some custom styles for panel menu, I suggest you re-review. If you create a reproduce link, I would like to help.

**Comment by tugcekucukoglu** [comment]
You could check this commit about the style changes https://github.com/primefaces/primevue/commit/2580c0020c9848a23f9083104ba90fbbea7ce0bb#diff-cccea1c9b76d17e3f72fae1ea5bdb4cc0fb6bda98d8879c44098751954eafbf9 and also you could find the latest classnames on the Styling section on the docs.

If there is any problem about saga-blue, please let us know.
