### ISSUE TITLE
DataTable: groupRowsBy has wrong type

### ISSUE THREAD

**Issue by harveylee** [primefaces/primevue#3219]
### Describe the bug

The groupRowsBy could accept a function which gets resolved with `ObjectUtils.resolveFieldData()` but the prop type is set to `[Array, String]` [here](https://github.com/primefaces/primevue/blob/1507ec2d5715f0d59b2d6040792e1244268a5b57/src/components/datatable/DataTable.vue#L436) and Typescript type is `string[] | string | undefined` set [here](https://github.com/primefaces/primevue/blob/1507ec2d5715f0d59b2d6040792e1244268a5b57/src/components/datatable/DataTable.d.ts#L687).

### Reproducer

https://codesandbox.io/s/data-table-group-rows-by-type-6f6sjp

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Steps to reproduce the behavior

1. Use a function as the groupRowsBy prop of a DataTable (e.g. d => d.type ?? "not applicable")
2. Many warnings appear in the console and Typescript complains, however the rows are grouped as expected.

### Expected behavior

No Vue warnings or Typescript errors.

**Comment by Jogai** [comment]
Its broken again: https://github.com/primefaces/primevue/blob/master/src/components/datatable/DataTable.d.ts#L687

Maybe `object | string[] | string | undefined`? instead of `(field: string) => ...`
