### ISSUE TITLE
Calendar Component: Thai solar calendar support

### ISSUE THREAD

**Issue by anurat** [primefaces/primevue#3220]
### Describe the feature you would like to see added

https://en.wikipedia.org/wiki/Thai_solar_calendar

It is essentially the same as Gregorian calendar except that 543 is added to the year e.g. year 2022 in Gregorian calendar will be year 2565 in Thai solar calendar.

### Is your feature request related to a problem?

To show Thai solar calendar correctly, we not only have to change month name to Thai language but also add 543 to the year. But adding 543 years to date object and display the calendar will result in an incorrect calendar since it will show the calendar of the incorrect year.

To display the calendar correctly the calendar in the correct year has to be shown but year + 543 is shown instead.

### Describe the solution you'd like

Adding a new property thai-solar to the Calendar component e.g.

Calendar(v-model="thai_date" :thai-solar="true")

Then the calendar panel should be displayed accordingly.

**Comment by anurat** [comment]
I also would like to contribute to this feature.
I haven't found a developer guide so far. How do I setup my machine (macOS) for development after pull request?

Best,

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
