### ISSUE TITLE
DataTable: Incorrect event values being returned when in edit mode with sort filter column added

### ISSUE THREAD

**Issue by admin-nexgen** [primefaces/primevue#3226]
### Describe the bug

I'm getting the incorrect event values being returned when using the datatable in combination with the sort filter.

The first table works correctly if you enter a new value for the first two cells, it gets the correct values for the original values data and value and the updated values newData and newValue.

If you do the same for the second example which also contains a filter row added. If you don't add anything in the first row, but you capture the same values in the second table, the values of data and value compared to newData and newValue are the same, but they shouldn't be.

### Reproducer

https://codesandbox.io/s/stoic-dubinsky-lt47o8?file=/src/DataTableEditDemo.vue:3061-3206

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to the table with the heading Cell Editing with Sorting and Filter.
2. Enter a new value "NewCode" for the code in the first editable cell skipping the filter row.
3. Tab into the next field and enter a new value "NewName" into the next editable cell.
4. Look at the output in the chrome debugging tools in the onCellEditComplete method for the values of data, value, newData and newValue.
5. The first cell entry has the correct output, but the second cell output has the incorrect values as both data and newData have the same values.
6. So basically every second cell you edit returns the wrong values for data and value, so you can't tell if you need to save or not because you don't know what the old values were every second edit.
7. If you repeat the same steps on the first "Cell Editing" table, you will notice that it works as expected.

### Expected behavior

The data and value returned in the onCellEditComplete method should have the correct from the previous edit every time.

![DataTable_Bug](https://user-images.githubusercontent.com/6703726/201078079-1cbf6f3a-b8eb-4f26-b0f5-3e32558859df.png)

**Comment by tugcekucukoglu** [comment]
I've just tried the example that you send and the result is:

<img width="1517" alt="Screen Shot 2022-11-11 at 15 16 07" src="https://user-images.githubusercontent.com/32294991/201338741-d206ca8c-998f-45b0-8345-a94118b98bef.png">

Could you check your code again?

**Comment by admin-nexgen** [comment]
Checked my code and it is definitely an issue. It also only happens when you use to tab character to move to the next cell and then use shift+home and shift+end to delete the data in the cell without leaving the new cell and then hit tab to leave the next cell. if you click into the cell and edit and click into the next cell it works.
