### ISSUE TITLE
Dynamically disable checkbox/selection in Table

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#324]
Same as the disabledSelection as in PrimeFaces.

**Comment by avbentem** [comment]
Aside, in PrimeFaces, this is [handled by `disabledSelection` on both column and on the table itself](https://primefaces.github.io/primefaces/8_0/#/components/datatable?id=attributes):

> Disables row selection when true. Overrides p:column's disabledSelection attr. Example: var="xxx" disabledSelection="#{xxx.year > 1960}"

**Comment by may820806** [comment]
may I ask is this issue still developing?

**Comment by levitomer** [comment]
Same here

**Comment by musaq** [comment]
still going on?

**Comment by Hulkmaster** [comment]
wow, still not there?

**Comment by lbeougher** [comment]
@cagataycivici Is this going to be fixed ever?

**Comment by JackHimes** [comment]
@mr83-uw Bless your soul child 🙏 - worked like a charm!

**Comment by cagataycivici** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by 1Map** [comment]
> I've been able to use this hack as a work around.
> 
> https://stackblitz.com/edit/ky1gjk?file=src%2FApp.vue
> 
> By adding a directive to the :rowClass="disableRow" to a function that return 'p-disabled' if you want that row disabled.

This does not work as it completly disable the whole row and not just the checkbox.  In my case I also have an Action column with some buttons (for example pencil icon that edits the record).  I only want to disable the checkbox and not the whole row.

**Comment by DileepSArjun** [comment]
@1Map I have made a demo where the checkbox alone is disabled. This makes the action buttons work as per your use case.
See: https://stackblitz.com/edit/3z633b?file=src%2FApp.vue

**Comment by xl495** [comment]
fix https://github.com/primefaces/primevue/pull/8102

**Comment by xxxKOTxxx** [comment]
Not having this functionality even in 2026 is a disgrace.

It's already implemented by contributors - @cagataycivici what's Your problem?
