### ISSUE TITLE
add contextmenu event to TabView

### ISSUE THREAD

**Issue by Shiro350** [primefaces/primevue#3244]
### Describe the feature you would like to see added

Add onfocus or contextmenu event

### Is your feature request related to a problem?

For example i want to delete tabitem (categorie maybe?) from my db and tabitem using contextmenu, but i can't do that because i don't know how to get right-clicked element.

### Describe the solution you'd like

Add contextmenu event in TabPanel with index or name argument.

### Describe alternatives you have considered

I try to 'pack' TabPanel to div but that don't work.

**Comment by tugcekucukoglu** [comment]
Currently, header slot and tab-click event might help. In the future, we might reconsider it if there is more demand.
