### ISSUE TITLE
PrimeVue in Output global rollup otpions

### ISSUE THREAD

**Issue by Jesse-Lucas1996** [primefaces/primevue#3245]
### Describe the feature you would like to see added

Can I add Primevue in globals rollup options in vue 3?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
