### ISSUE TITLE
datatable filter not work in some firefox

### ISSUE THREAD

**Issue by west-farmer** [primefaces/primevue#325]
Datatable filter report a javascript error "event is not defined" in some firefox release,  it likes to  response the keyboad event.   
I have find this issue in v1.3.x and v2.0beta with firefox 65,  the screen likes below ,   

![Screenshot](https://user-images.githubusercontent.com/55118339/82170710-d2d8f780-98f7-11ea-9022-3813b7986999.png)

**Comment by cagataycivici** [comment]
We'll review for the RC1 and get back to you, thanks for reporting.
