### ISSUE TITLE
Slider: onDragStart() -> this.modelValue is undefined

### ISSUE THREAD

**Issue by asyyy** [primefaces/primevue#3251]
### Describe the bug

When using Slider with range, move the left range doesn't work and write in console that modelValue in "onDragStart()" is undefined.

### Reproducer

https://codesandbox.io/s/quizzical-joji-gk5ifu?file=/src/App.vue

### PrimeVue version

2.10

### Vue version

2.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by hlaunay** [comment]
It may by a duplication with #2986
