### ISSUE TITLE
Dropdown: add keyboard support for Numpad Enter

### ISSUE THREAD

**Issue by hossader** [primefaces/primevue#3257]
### Describe the bug

The Dropdown component does not respond to the enter key on the numeric keypad

### Reproducer

https://3jmtbg.csb.app/

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by bahadirsofuoglu** [comment]
Hi, I can't try this case because of my keyboard. Could you follow the steps below?

Focus dropdown > open with space > select with arrow down > approve with Enter

If it is not working we can reevaluate
