### ISSUE TITLE
Editor: document is not defined SSR Nuxt js 2

### ISSUE THREAD

**Issue by Matoto2** [primefaces/primevue#3259]
### Describe the bug

Seems like version 2.10.0 of primevue doesn't support SSR for the Editor component.

![localhost-3000-admin-nouvelles-1](https://user-images.githubusercontent.com/66121373/202015329-6c523031-0dd0-463b-8401-790d0459c8bd.png)

This issue seems to have been solved for version 3.17.0 (https://github.com/primefaces/primevue/issues/2842)

### Reproducer

https://github.com/primefaces/primevue/issues/2842

### PrimeVue version

2.10.0

### Vue version

2.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Due to the technical limitations of Vue 2's Vite support, we recommend the use of Vue 3.

If the problem still persists, please reopen this issue.

**Comment by kstan79** [comment]
tested. same error still exists in vue3 ssr=true mode.
