### ISSUE TITLE
p-input-icon-right puts icon outside InputText on the left side.

### ISSUE THREAD

**Issue by abdu4188** [primefaces/primevue#326]
I am trying to implement the left icon InputText specified on the documentation. I copied the exact same code from the documentation, but the result I am getting is different. The InputText code looks like:
`<span class="p-input-icon-right">
    <i class="pi pi-spin pi-spinner" />
    <InputText type="text />
</span>`
The result I get puts the icon outside of the InputText and in front of it like the following.
![Screenshot from 2020-05-20 11-10-23](https://user-images.githubusercontent.com/39178255/82422702-760e4600-9a8b-11ea-8da9-35f71afe67be.png)

**Comment by west-farmer** [comment]
Your code maybe  missed a " after type="text, I have try  bellow code, It looks working.
`<span class="p-input-icon-right"> <i class="pi pi-spin pi-spinner"></i> <p-inputtext type="text"></p-inputtext> </span>`

![Screenshot1](https://user-images.githubusercontent.com/55118339/82456580-02018b80-9ae7-11ea-8b57-f8b21881bbb1.png)

**Comment by cagataycivici** [comment]
What is your PrimeVue version, you need 2.0.0-beta.1 at least.

**Comment by abdu4188** [comment]
ya I am on 1.1.0. I'll upgrade and try. Thaks
