### ISSUE TITLE
AutoComplete: Add option to show all filtered selection on empty search

### ISSUE THREAD

**Issue by umzzz** [primefaces/primevue#3260]
### Describe the feature you would like to see added

When the user clears the search by using backspace add a prop to show all the results. i.e show all results without filtering

### Additional context

I would be willing to implement it and create a PR for the team

**Comment by dmcbride** [comment]
We've been trying to work around this for months, largely without success.  Agreed that it should be a prop.

Also, this prop should also imply that when the input field gets focus, it should automatically enable the drop-down immediately, much like clicking the button (if it is there). This one we've been hacking around, but it requires the button to be present.
