### ISSUE TITLE
Multiselect: Close button doesn't work with append-to='self'

### ISSUE THREAD

**Issue by jfitzsimmons2** [primefaces/primevue#3262]
### Describe the bug

MultiSelects with append-to=self has events from the close button bubbling up and being captured by onContainerClick which is causing the multiselect to reopen. Repro link attached. Stopping propagation on the close button fixes it.

### Reproducer

https://codesandbox.io/s/laughing-shape-x5sqck?file=/src/App.vue

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on MultiSelect
2. Click on the X to close the MultiSelect
3. MultiSelect doesn't close

### Expected behavior

After clicking the X, the multiselect should close

**Comment by tugcekucukoglu** [comment]
Can not replicate the issue with the latest PrimeVue version. Please try to use the latest primeVue version.
