### ISSUE TITLE
ConfirmPopup: Wrapping confirm.require in setTimeout breaks position of a popup

### ISSUE THREAD

**Issue by TrsnkVld** [primefaces/primevue#3268]
### Describe the bug

I need to show second popup right after action is confirmed in first popup.
Instead of the button (target) it displays the second popup in the corner of a page

Initially i wanted to display the second one without setTimeout, but in that case the second popup doesn't show at all, but if i use setTimeout, the second popup is displayed not near the button ("target"), but in the corner of a page

![image](https://user-images.githubusercontent.com/68476553/202205544-76e26626-8c94-4c68-b599-3bc3ecbedc7b.png)

### Reproducer

https://codesandbox.io/s/competent-visvesvaraya-8llhq7

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 107

### Steps to reproduce the behavior

1. Click on button
2. Click "Yes" to confirm action
3. See how second popup is in the corner of the page, instead of below the button

### Expected behavior

1. Click on button
2. Click "Yes" to confirm action
3. The second popup shows near its button (target)

**Comment by jayzzer** [comment]
+1

**Comment by tugcekucukoglu** [comment]
This is an invalid usage. The first popup closes itself and clears all listeners and so the second popup appends itself to the body.
