### ISSUE TITLE
Editor: Quill Formula Toolbar Cannot read properties of undefined (reading 'render')

### ISSUE THREAD

**Issue by fransrudolfbanjarnahor** [primefaces/primevue#3269]
### Describe the bug

When activated Formula Toolbar
					
`<button class="ql-formula"></button>
`
<img width="283" alt="image" src="https://user-images.githubusercontent.com/18527832/202221218-f394ddf6-6274-4c1e-b179-5afa3a0409ab.png">

<img width="908" alt="image" src="https://user-images.githubusercontent.com/18527832/202226730-6c9b8803-7453-4576-b397-e5a8f96bcf48.png">

### Reproducer

https://yjmuyh.csb.app/

### PrimeVue version

^3.12.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. add `<button class="ql-formula"></button>`
2. Test add formula
3. Error Raised

### Expected behavior

<img width="243" alt="image" src="https://user-images.githubusercontent.com/18527832/202230114-18a2821b-251d-427c-9be6-89bcf5353c9e.png">

**Comment by bahadirsofuoglu** [comment]
Hi, The KaTex is required for the formula. You may want to review the following documents.

https://quilljs.com/docs/formats/#embeds
https://katex.org/docs/browser.html
