### ISSUE TITLE
Menubar: invalid focus

### ISSUE THREAD

**Issue by CRC32EX** [primefaces/primevue#3294]
### Describe the bug

Invalid focus

### Reproducer

https://codesandbox.io/s/zealous-rumple-8r9t08?file=/src/App.vue

### PrimeVue version

3.19.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Google Chrome 107.0.5304.107

### Steps to reproduce the behavior

1. Access codesandbox URL
https://codesandbox.io/s/zealous-rumple-8r9t08?file=/src/App.vue
2. Click `Item2` or `Item3`
3. `Item1` focused.
![image](https://user-images.githubusercontent.com/25629617/202678464-320f5a5f-9838-4961-8538-c27768857e54.png)

### Expected behavior
- When i click `Item1` then `Item1` focused.
- When i click `Item2` then `Item2` focused.
- When i click `Item3` then `Item3` focused.

**Comment by tugcekucukoglu** [comment]
Fixed via https://github.com/primefaces/primevue/issues/3352
