### ISSUE TITLE
TriStateCheckbox: Allow custom icons

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3299]
### Describe the feature you would like to see added

Extracted from https://github.com/primefaces/primevue/issues/2979 - adding custom icons support for tri- state checkbox component

**Comment by Ancient-Dragon** [comment]
@Magiczne I added a new PR which allowed the users to specify the null icon class. Our team would like to have the false mode be empty as it could be confusing when used with a normal checkbox.

**Comment by tugcekucukoglu** [comment]
We decided to use icon template instead of icon property to support svg, png etc.
