### ISSUE TITLE
Webpack Build Error: Can't resolve subcomponents within a PrimeVue UI component

### ISSUE THREAD

**Issue by redfox05** [primefaces/primevue#331]
I am unable to build certain PrimeVue UI components with webpack.

I have tried several components, and all the basic ones work fine, but as soon as I try and use a component that requires a sub-component, webpack fails to build. I experienced this so far with the Breadcrumb and PanelMenu components.

The error is:
```
ERROR in ./node_modules/primevue/components/panelmenu/PanelMenu.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/panelmenu/PanelMenu.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve './PanelMenuSub' in '/my-application-directory/node_modules/primevue/components/panelmenu'
 @ ./node_modules/primevue/components/panelmenu/PanelMenu.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/panelmenu/PanelMenu.vue?vue&type=script&lang=js&) 27:0-42 86:24-36
 @ ./node_modules/primevue/components/panelmenu/PanelMenu.vue?vue&type=script&lang=js&
 @ ./node_modules/primevue/components/panelmenu/PanelMenu.vue
 @ ./node_modules/primevue/panelmenu.js
 @ ./interface/html5/vue-components/Menu.js
 @ ./interface/html5/vue-components/App.js
 @ ./interface/html5/vue-main.js
```

My webpack config is as follows:
```
const path = require('path');
const { VueLoaderPlugin } = require('vue-loader');

module.exports = {
	mode: 'development',
	entry: 'vue-main.js',
	output: {
		filename: 'vue-main.bundle.js',
		path: path.resolve(__dirname, 'dist'),
	},
	module: {
		rules: [
			{
				test: /\.vue$/,
				use: 'vue-loader'
			},
			// the below will apply to both plain `.js` files AND `<script>` blocks in `.vue` files
			// the below will apply to both plain `.css` files AND `<style>` blocks in `.vue` files
			{
				test: /\.css$/,
				use: [
					'vue-style-loader',
					'css-loader'
				]
			}
		]
	},
	plugins: [
		new VueLoaderPlugin()
	]
};
```

The component is used exactly as described in the documentation.

What could be causing this? The same is happening with the Breadcrumb component, except it can't find the BreadcrumbItem component. I checked the node_modules directory and the files are there.

Is this a webpack config file problem, or a PrimeVue bug?

I found a similar issue reported here: https://stackoverflow.com/questions/59968225/primevue-toast-component-error-cant-resolve-toastmessage-in-toast

**Comment by manikantavoonna** [comment]
I am also facing same issue

**Comment by ammar91** [comment]
Same issue. Any workaround?

**Comment by cagataycivici** [comment]
Seems like a webpack config issue as with vue-cli it works, I'm not webpack expert but we import the subcomponents without the vue extensions so need to tell webpack about this;

```
 resolve: {
    extensions: ['.vue']
   },
```

Got this from;

https://github.com/vuejs/vue-loader/issues/685

**Comment by t-k-** [comment]
I've tested the code snippet of @cagataycivici , yes it works for Primevue submodules. But you also need to add .js extension as default for resolver:
```
 resolve: {
    extensions: ['.js', '.vue']
   },
```
At least this solves my issue.
