### ISSUE TITLE
Chip: Issue in the chip remove icon

### ISSUE THREAD

**Issue by islamroshan** [primefaces/primevue#3316]
### Describe the bug

**Issue in the Chip Component Documentation**

The property **_removeIconClass_** actually does not exist, I check the component and find out that the actual property name is **_removeIcon_**.

So, make sure to use **_removeIcon_** property instead of the **_removeIconClass_**

thanks

### Reproducer

https://www.primefaces.org/primevue/chip

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

The property **_removeIconClass_** actually does not exist, I check the component and find out that the actual property name is **_removeIcon_**.

### Expected behavior

 make sure to use **_removeIcon_** property instead of the **_removeIconClass_**

**Comment by bahadirsofuoglu** [comment]
removeIconClass is defined as a computed property. Thank you for your attention

**Comment by tugcekucukoglu** [comment]
Documentation will be fixed and yes the right property name `removeIcon`.

Thanks!
