### ISSUE TITLE
Calendar: Time range

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3318]
### Describe the feature you would like to see added

Is there currently an option using `numberOfMonths` to have one time picker assigned to one calendar column? If not if there are any plans to support this kind of behavior?

It could be especially useful when using range selector

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by emink92** [comment]
Any plans on implementing this feature?

**Comment by xiaomudk** [comment]
@tugcekucukoglu This is a very important feature to me. Is there any scheduling plan?

**Comment by AniaKru95** [comment]
Any news about this feature?
