### ISSUE TITLE
Interfaces/ Type export for `PrimeVue.d.ts`

### ISSUE THREAD

**Issue by toddeTV** [primefaces/primevue#3325]
### Describe the feature you would like to see added

Export the interfaces in `PrimeVue.d.ts` in order to be able to use the definitions outside this file in projects that use PrimeVue for type safety when writing locale/ language translations.  
See MR !3326

### Describe the solution you'd like

Add exports.

**Comment by tugcekucukoglu** [comment]
Could you check the latest version? If the problem still persists, please create a new issue.
