### ISSUE TITLE
DataTable: exportData exclude column footers

### ISSUE THREAD

**Issue by revivedtitan** [primefaces/primevue#3328]
### Describe the feature you would like to see added

The ability to exclude the column footers in the exported CSV

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add a boolean prop that would exclude column footers from the csv export

### Describe alternatives you have considered

Bypassing completely the exportCSV function and using an custom function. This creates more work when it could probably simply be added into the primevue code base.

**Comment by scritrolf** [comment]
Hello all, I can only second that. A CSV file with a footer containing the column names is rather uncommon in my opinion.  I'd go as far as saying that the default should be to not export footers into csv.

**Comment by tugcekucukoglu** [comment]
If `exportFooter` is not defined, the CSV file does not consist export footer for a column.
