### ISSUE TITLE
Multiselect Uncaught TypeError

### ISSUE THREAD

**Issue by ineshbose** [primefaces/primevue#3329]
### Describe the bug

When Multiselect is focused, and there are keystroke events, there's an error in the console. Possibly due to this:
https://github.com/primefaces/primevue/blob/b91d5a1e67b3e3abe191420615d724bebf8ddccc/src/components/multiselect/MultiSelect.vue#L950

Error:
`Uncaught TypeError: this.findSelectedOptionIndex is not a function`

### Reproducer

https://codesandbox.io/s/primevue-3-issue-template-ip3vm

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

**Comment by matthew-dean** [comment]
This [has been a persistent error](https://github.com/orgs/primefaces/discussions/4132) that pops up periodically. I've tried everything to fix it, and it's really unclear what causes it. Somehow PrimeVue is binding something that causes Vue to break the binding of the computed label.
