### ISSUE TITLE
table: header -> wanna Fixed header (scrollbar under header) any idea?

### ISSUE THREAD

**Issue by gowy222** [primefaces/primevue#3340]
### Describe the feature you would like to see added

Fixed header /  Sticky-header

### Is your feature request related to a problem?

nop,  just make UI looks better... when scrolling

### Describe the solution you'd like

maybe like this => https://www.creative-tim.com/vuematerial/components/table -> Fixed headers

**Comment by tugcekucukoglu** [comment]
Please check these examples: https://primefaces.org/primevue/datatable/scroll

**Comment by gowy222** [comment]
@tugcekucukoglu  Thanks but this is not what I mean to..
![image](https://user-images.githubusercontent.com/52201479/205303012-0c9ad282-c2a9-4e33-be89-67323169a01c.png)

![image](https://user-images.githubusercontent.com/52201479/205303097-676c02fc-f856-47c8-8c47-aed5b5a5bb91.png)

**Comment by gowy222** [comment]
its all about scrollbar position
