### ISSUE TITLE
[Bug] TabPanel: HMR does not work when changing the default slot

### ISSUE THREAD

**Issue by martinszeltins** [primefaces/primevue#3343]
### Describe the bug

_* I think this might be a bigger problem and not only related to `TabPanel` component._

If I change the content inside the TabPanel's default slot, HMR does not work automatically unless the page is reloaded. To reproduct this, simply clone run the reproduction repo and go to `App.vue` and change anything inside `TabPanel` default slot (line 9). Then if you look at the browser the content did not automatically update unless you refresh the whole page.

### Reproducer

https://github.com/martinszeltins/vue-hmr-not-working-slot

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 107.0.5304.121

### Steps to reproduce the behavior

1. Clone and run the project.

```shell
$ git clone git@github.com:martinszeltins/vue-hmr-not-working-slot.git
$ cd vue-hmr-not-working-slot
$ npm install
$ npm run dev
```
2. Now open App.vue and change the default slot of TabPanel (line 9). Then save the App.vue file and look at the browser - HMR did not work unless you manually reload the page.

All I did was take the Vite starter template and added PrimeVue.

```shell
$ npm create vite@latest my-vue-app -- --template vue
$ cd my-vue-app
$ npm install
$ npm install primevue@^3 --save
$ npm install primeicons --save
```

Then I added PrimeVue to `main.js` like this:

```js
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import PrimeVue from 'primevue/config'
import AppModal from 'primevue/dialog'

const app = createApp(App);

app.use(PrimeVue);
app.component('AppModal', AppModal);
app.mount('#app')
```

And then I added the component in `App.vue` as you can see from the reproduction repo. I didn't change anything else. Something is wrong.

### Expected behavior

I was expecting HMR to work and auto refresh the content inside the default slot but it is not working unless I reload the whole page.

**Comment by tugcekucukoglu** [comment]
Duplicate [https://github.com/primefaces/primevue/issues/2470](https://github.com/primefaces/primevue/issues/2470)
