### ISSUE TITLE
DataTable (and other components that include scrolling): Scroll control / easy access to scrolling component's element

### ISSUE THREAD

**Issue by James-Laidlaw** [primefaces/primevue#3345]
### Describe the feature you would like to see added

An easy way to control the scrolling position of scrollable components such as datatable. alternatively, a way to directly attach the scrolling element interface to a ref in order to easily use the .scroll() function on it

### Is your feature request related to a problem?

this originally became a problem for me when making a data table with a variable number of elements. when the user is scrolled down on the page, then performs an action that would reduce the amount of items in the table, they would stay scrolled to the same position, regardless of if the items reach that far down, resulting in a blank page. this is made worse if the amount of items no longer warrants a scroll bar, as the scroll bar disappears and leaves the user unable to navigate to the portion containing information. My solution to this was to automatically scroll the user back to the top of the table whenever the number of items changes, however there is no easy way to do this

### Describe the solution you'd like

either a 2 way bound prop representing the scroll position such that changing it's value will cause the element to scroll to that position, or a way to access the scrolling element similarly to how is possible for default elements e.g.
For default elements:
`<div ref="elementRef"></div>`

for a scrolling primevue element:
`<DataTable scrollElementRef="elementRef"> </Datatable>`

### Describe alternatives you have considered

my current work around is to use slots to insert an element I can access a reference for as the header of a column, then use .parentElement six times to access the scrolling element, and use .scroll() on that. In my opinion, this is less than optimal.
 
e.g.

```
function scrollToTop() {

  //header span > header div > th element > tr element > thead element > table element > scroll div
 
tableRef.value.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.scroll(
    {
      top: 0,
      behavior: "auto",
    }

  );
}
```

where tableRef is made using:
```
<DataTable>
<Column>
<template #header>
<span ref="tableRef">
HeaderText
</span>
</template>
</Column>
</DataTable>
```

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
