### ISSUE TITLE
Clear buttons

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#335]
Would be nice guys to add clear buttons to other elements than dropdown. Related #83

![image](https://user-images.githubusercontent.com/13495631/83191855-9b0a5500-a12c-11ea-87cb-a9108fdd3877.png)

Thanks

**Comment by cagataycivici** [comment]
Sure, but please create separate tickets for the ones you request. e.g. clear icon for MultiSelect and another issue for clear icon for calendar.
