### ISSUE TITLE
AutoComplete: new `dropdownClass` prop

### ISSUE THREAD

**Issue by ig-onoffice-de** [primefaces/primevue#3350]
### Describe the bug

I am using the `p-inputtext-sm` class for my inputs. But for an the Autocomplete with DropDown-Button enabled the setting does not work correctly. The input is (because of the button) always higher than the other ones.

### Reproducer

https://codesandbox.io/s/awesome-vaughan-ktnkjy?file=/src/App.vue

### PrimeVue version

3.19.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Just open the reproduction and see that the second autocomplete is higher than the Input Element.

### Expected behavior

They should be of the same size.

**Comment by tugcekucukoglu** [comment]
This new property could be used like this: 

```
<AutoComplete class="p-inputtext-sm" :dropdown="true" dropdownClass="p-button-sm" />
```
