### ISSUE TITLE
Calendar: maxDate with 12-hour-format does not allow minute and second value modification 

### ISSUE THREAD

**Issue by rydengraham** [primefaces/primevue#3356]
### Describe the bug

If you set the calendar to have a morning (AM) max-date, you cannot modify the minute value of the time on the same day as the max-date. In order to change the minute value on the final day, you must select an earlier day, modify the minute value, then reselect the final day.

### Reproducer

https://codesandbox.io/s/hardcore-tamas-451wmf?file=/src/App.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

<Calendar show-time hour-format="12" :max-date="maxDate" />

Where maxDate is a morning (AM) time

While the selected day is equal to the day portion of the max-date, attempt to change the minute value.

### Expected behavior

Minute value can be changed to any value as long as the max-date is not exceeded.

**Comment by bahadirsofuoglu** [comment]
Am I missing something? Could you try again?
