### ISSUE TITLE
Styles conflict with primereact

### ISSUE THREAD

**Issue by madeofsun** [primefaces/primevue#336]
### Bug description
I have a project with both primereact and primevue, and I have faced a problem with  `.p-dialog-mask`  css class.
When dialog components from both of them are used at the same time, unexpected things happens, since they have different class definitions for `.p-dialog-mask`.

You can check it out here: https://codesandbox.io/s/flamboyant-snowflake-3dghf?file=/src/App.vue

### Expected behavior

Since primereact and primevue share same prefix and therefore class names, I expected that they would have same style definitions for such names.

**Comment by eichgi** [comment]
I was about to post something similar with PrimeVue, checking out your sandbox you are requesting the following theme: 

`import "primevue/resources/themes/nova-light/theme.css";`

But if you look up for the releases, the latest is PrimeVue 2.0.0-rc.1 which has almost 24 hours active.  And this release doesn't contain the nova-light theme anymore.

Checking out the docs new themes are available on Free themes section in https://www.primefaces.org/primevue/showcase/#/setup

You might need to look for a valid version of a theme whether you use prime vue or prime react.

**Comment by madeofsun** [comment]
> I was about to post something similar with PrimeVue, checking out your sandbox you are requesting the following theme:
> 
> `import "primevue/resources/themes/nova-light/theme.css";`
> 
> But if you look up for the releases, the latest is PrimeVue 2.0.0-rc.1 which has almost 24 hours active. And this release doesn't contain the nova-light theme anymore.
> 
> Checking out the docs new themes are available on Free themes section in https://www.primefaces.org/primevue/showcase/#/setup
> 
> You might need to look for a valid version of a theme whether you use prime vue or prime react.

In the sandbox and in my project, PrimeVue 1.3.2 is used, that contains  'nova-light theme', if I am not mistaken.

**Comment by cagataycivici** [comment]
2.0.0 renames Nova-Light to Nova, Nova-Dark to nova-alt and nova-colored to nova-ccent.

PrimeReact 5.0 styling will be aligned with PrimeVue 2.0.
