### ISSUE TITLE
TabMenu: First tab is always highlighted even when selected other tabs

### ISSUE THREAD

**Issue by klsl2008** [primefaces/primevue#3368]
### Describe the bug

In TabMenu, the first tab is always highlighted. The bug can be reproduced in the official website.

### Reproducer

https://primefaces.org/primevue-v2/#/tabmenu

### PrimeVue version

2.10.1

### Vue version

2.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to official website: https://primefaces.org/primevue-v2/#/tabmenu
2. In default section, click on "Calendar"
3. Calendar tab is highlighted, but Home tab is also highlighted.

### Expected behavior

Home tab should not be highlighted.

**Comment by mathewGlenn** [comment]
I am working with a project that requires me to use vue2 and stumbled with this bug. I fixed it by not making the route of the first tabmenu item same as the parent route. The trick is to load the route of the first item onMounted.
