### ISSUE TITLE
InputNumber prevents min key number

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#337]
The following example:
```
<InputNumber v-model="value" :min="1" :max="100" />
```
prevents from typing `1` by keyboard.

See the example https://www.primefaces.org/primevue/showcase/#/inputnumber and try to type `0`.

![image](https://user-images.githubusercontent.com/13495631/83427654-f720f200-a428-11ea-9f07-3c627b3435ba.png)

**Comment by cnstonicz** [comment]
While the max is set to 100, i can only write 99 on numeric keyboard.
After that, it is possible to increase the value by up arrow key or button to set 100.
