### ISSUE TITLE
DataTable: Long duration of checking all items for table containing 2000 items - issue not resolved

### ISSUE THREAD

**Issue by adam-koala** [primefaces/primevue#3371]
The problem is not long loading but long duration of checking all items

_Originally posted by @adam-koala in https://github.com/primefaces/primevue/issues/3083#issuecomment-1296025107_

**Comment by adam-koala** [comment]
Please fix issue [DataTable: Long duration of checking all items for table containing 2000 items](https://github.com/primefaces/primevue/issues/3083#issuecomment-1337113139)

**Comment by tugcekucukoglu** [comment]
Please create and follow **one** issue ticket.
