### ISSUE TITLE
Portal: appendTo default value 

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3374]
### Describe the feature you would like to see added

Please make a setting for the global setting (PrimeVue setup) primevue/src/components/portal/Portal.vue for a default appendTo value.

I'm using one framework that only allows focus inside itself and because of that a lot of focus issues because I can't change the appendTo default value for Portal

![image](https://user-images.githubusercontent.com/16963395/205749796-b26c8496-e3a3-4b4a-8b49-8607c74d28cf.png)

**Comment by tugcekucukoglu** [comment]
It is definitely on PrimeVue roadmap. Portal is the inner component, for example, Dialog uses Portal inside it. This property could be overridden using the `appendTo` property.

**Comment by NeluQi** [comment]
> Это определенно включено в дорожную карту PrimeVue. Портал — это внутренний компонент, например, Dialog использует внутри себя Portal. Это свойство может быть переопределено с помощью `appendTo`свойства.



> It is definitely on PrimeVue roadmap. Portal is the inner component, for example, Dialog uses Portal inside it. This property could be overridden using the `appendTo` property.

It is because they are inside that this is a problem.

I'm using a modal window from ionic and a datatable in it. Overlay for filters into tables creates them in the body (because appendTo
  default) and cannot be changed. Since they are created behind the modal window, the focus does not pass and the filters cannot be used and cannot be changed in any way.



Either add a prop to each component that uses Portal


![image](https://user-images.githubusercontent.com/16963395/206398864-a3928c65-8abc-4a33-9e07-9c3675fee26f.png)
