### ISSUE TITLE
DataTable: Slots for Header Items

### ISSUE THREAD

**Issue by ig-onoffice-de** [primefaces/primevue#3376]
### Describe the feature you would like to see added

It would be really nice if there was a possibility to enhance the icons in the header (like FilterButton or SortIcons (Arrows and Number)) with custom properties. 
For example I would like to add a Tooltip to the filterButton with the currently selected filters and a Badge if there are errors in the filter. 
Also I want to add a Tooltip to the SortIcons to explain the multisort mode. 

Is there any chance that you change this to slots and keep the current behavior as default?

### Is your feature request related to a problem?

I added a filter to our table. We test our changes in our team, so an other developer tried to test the changes but not even he as a softwaredeveloper did understand how it works right away. It should be possible to provide a better user experience.

### Describe the solution you'd like

Add two slots, one for filterHeader and one for sortHeader. The default is the actual behavior and everybody can change it if necessary.

### Describe alternatives you have considered

I also considered not even passing the filter properties to the table and to do everything on my own, but I think that is not the best way.

**Comment by tugcekucukoglu** [comment]
We are starting to work on Headless mode in Q1 of 2023. DataTable slots and all properties are definitely on our radar.

**Comment by ig-onoffice-de** [comment]
Now it is Q3 2024 and I am still not able to add more elements to the filter button, as e.g. a badge. 😢
