### ISSUE TITLE
AutoComplete: Search status never reset

### ISSUE THREAD

**Issue by ig-onoffice-de** [primefaces/primevue#3377]
### Describe the bug

In some cases the loading/searching icon is displayed forever at the `autoComplete` component.

### Reproducer

https://codesandbox.io/s/elated-violet-h4n1hp?file=/src/App.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Enter in the AutoComplete and type 'foo'
2. Now before the search Process ends leave the field and click for example at the code section in `codesandbox`.
3. The valid value is added but the search Icon is never removed

### Expected behavior

If the value is valid and added, the search icon should disappear.

**Comment by bahadirsofuoglu** [comment]
Hi, 
Could you try the below sample (Multiple)? You can check @complete emit's method.
https://codesandbox.io/s/t6085y?file=/src/AutoCompleteDemo.vue:859-864

**Comment by ig-onoffice-de** [comment]
You are right, with this change it works correctly. Thanks :)
