### ISSUE TITLE
Tree: Focus lock when navigating with tab key

### ISSUE THREAD

**Issue by TsenkoTsenov** [primefaces/primevue#3378]
### Describe the bug

Basically when you once focus inside the Tree component while navigating with the tab key it is impossible to switch the focus to another component.
My guess is that at some point in the versions the navigation inside the Tree was switched from tab OR arrow keys to only arrow keys.

### Reproducer

https://codesandbox.io/s/friendly-wood-9psi7w?file=/src/App.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Focus inside Tree component using the tab key
2. Try to focus out and focus another component / element

**Comment by tugcekucukoglu** [comment]
It is fixed for the next version.

Thanks,
