### ISSUE TITLE
AutoComplete: Duplicate Value

### ISSUE THREAD

**Issue by ig-onoffice-de** [primefaces/primevue#3379]
### Describe the bug

I use an `Autocomplete` as a filter field in the `Datatable` with popup mode. 
If I select an item by mouse, sometimes it is added twice.

### Reproducer

https://codesandbox.io/s/elated-voice-86kebz?file=/src/App.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. click on filter button in header
2. type 'test'
3. select 'test' value from dropdown by mouse click
4. item 'test' is now added twice.

### Expected behavior

It should only add the selected item once.

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox but the example seems working correctly. Am I missing something?

**Comment by ig-onoffice-de** [comment]
> Thanks for the codesandbox but the example seems working correctly. Am I missing something?

It is necessary to select the value from the dropdown with a mouse click not with the keyboard arrows and enter. Did you do that?

**Comment by havist** [comment]
I'm confirming the described bug. It occurs, when Autocomplete's properties ```multiple``` and ```force-selection``` are both set to **true**. So does in version 3.21.0.

**Comment by havist** [comment]
Is there any plan to fix this issue, please?

**Comment by ig-onoffice-de** [comment]
@tugcekucukoglu Anything new on this issue?

**Comment by keymasjp** [comment]
I can confirm I have also come across this bug. Steps to reproduce...

1. Go to: https://primevue.org/autocomplete/#multiple
 
2. Click on "Edit in StackBlitz"

3. Add the following props to the AutoComplete component: 
  ` :multiple="true" forceSelection`
  
4. Type in "Iraq" and then select Irag from the dropdown using your mouse.

You should see this selection duplicate.
![image](https://github.com/primefaces/primevue/assets/57758438/bc58ff64-c287-4aed-94e1-fcadbabedb23)


Hope this helps

**Comment by ig-onoffice-de** [comment]
@tugcekucukoglu Anything new on this issue?
