### ISSUE TITLE
MultiSelect: Very long selection time due to Chips

### ISSUE THREAD

**Issue by arielkuzminski** [primefaces/primevue#3380]
### Describe the bug

Hello.
For some reason MultiSelect takes very long time to select all items in list or even single select when lots of items are already selected.
I did a "Performance" benchmark and I think issue is in `deepEquals` function used by PrimeVue, although I may be wrong.
![image](https://user-images.githubusercontent.com/20773060/206183504-04ae34cb-cdfa-40ef-8a74-f9896bbea1a2.png)
![image](https://user-images.githubusercontent.com/20773060/206183764-17690c82-b3f6-48b9-ad22-1517f224b4fa.png)

### Reproducer

https://codesandbox.io/s/primevue-multiselect-long-selection-time-stwzeq?file=/src/MultiSelectDemo.vue

### PrimeVue version

3.20

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Open CodePens `MultiSelectDemo.vue` file
2. Open MultiSelect component and click `Checkbox` for selecting all items.
3. Depending on your CPU, selection will take about 5 - 20 seconds, or even in bad case browser tab may freeze.

### Expected behavior

Selection should take much less time

**Comment by mertsincan** [comment]
Hi @arielkuzminski,

I made some changes related to maxSelectedLabels and chips mode. For your case, you can use :maxSelectedLabels options.

Best Regards,

**Comment by arielkuzminski** [comment]
> Hi @arielkuzminski,
> 
> I made some changes related to maxSelectedLabels and chips mode. For your case, you can use :maxSelectedLabels options.
> 
> Best Regards,

Thanks for the contribution.

Good day!
