### ISSUE TITLE
Menu: Add ability to right align.

### ISSUE THREAD

**Issue by websanova** [primefaces/primevue#3381]
### Describe the feature you would like to see added

It would be nice if there was an option to right align a dropdown menu to it's initiator. A good example from Bootstrap here:

https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Right now it seems to always default to a best fit, so would be nice to for instance, right align first and then only best fit after that.

### Describe alternatives you have considered

I've tried using an css offset which works if the menu needs to be a bit lower or something. But an offset here, would completely throw things off on the auto align. For instance on desktop it could be made to look fine, but then on mobile the offset would completely throw it off.

### Additional context

Currently the left side example is what happens, the right side example is the intended result.

![image](https://cdn.discordapp.com/attachments/787968635414118421/1049791470330191943/menu-example.png)

**Comment by melloware** [comment]
@websanova did you mean this for Vue or for React?  You posted on Discord in React forum?

**Comment by melloware** [comment]
@websanova you can look at my PrimeReact PR and probably apply the exact same changes for PrimeVue: https://github.com/primefaces/primereact/pull/3754

**Comment by websanova** [comment]
> @websanova did you mean this for Vue or for React? You posted on Discord in React forum?

Ah yea, I meant it for Vue, posted in wrong section on Discord by accident.

**Comment by websanova** [comment]
@melloware I'll take a look at that PrimeReact PR, thx.

**Comment by melloware** [comment]
Let me know if you have any questions!

**Comment by timyourivh** [comment]
Any update on this?

**Comment by christianwebdev200** [comment]
any update on this?

**Comment by melloware** [comment]
@christianwebdev200 it works in PrimeReact now so porting the changes to Vue should be possible via a PR.

**Comment by timyourivh** [comment]
Link to PR? Couldn't find it

**Comment by melloware** [comment]
@timyourivh PrimeReact PR was right here: https://github.com/primefaces/primereact/pull/4416

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by ikasianiuk** [comment]
@tugcekucukoglu I would love to see this improvement as well. Maybe you could tell me if it is planned in the nearest future?

**Comment by FAbrahamDev** [comment]
Well it's been a minute and i dont see how to do that in vue?
Is the project dead?
