### ISSUE TITLE
InputNumber: Incorrect formatting when in decimal mode with a suffix (maybe all the time)

### ISSUE THREAD

**Issue by Ancient-Dragon** [primefaces/primevue#3382]
### Describe the bug

It seems that when formatting an input number the logic is wrong, the method: `concatValues` [here](https://github.com/primefaces/primevue/blob/master/src/components/inputnumber/InputNumber.vue#L980). Has an issue when it calcalates val1 it determines 5 and then val2 is 05 so it works out to 5 + 5 + suffix whereas it should be 0 + 5 + suffix. It should be 0 + 5 + suffix. Hope that makes sense.

We have this issue with vite, but I can also see it's an issue on the main website which uses the vue cli.

### Reproducer

https://www.primefaces.org/primevue/inputnumber

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Any

### Steps to reproduce the behavior

Go to the temperature input in the docs and select all, and type 05 and it will replace it with 55.

### Expected behavior

When typing 05 for it stay 05 not 55.

**Comment by melloware** [comment]
Similar issue in PrimeReact: https://github.com/primefaces/primereact/issues/2871

**Comment by hurahurat** [comment]
When typing 2000 with suffix in the InputNum it shows 20.000. And when I type a long number it shows 0 instead of the number I had typed.

**Comment by denisbraud** [comment]
Test Ko in 3.29.1

Steps to reproduce

- https://primevue.org/inputnumber/#currency
- In Germnay Field (EUR), input "-1"
- "-11" is displayed immediatly :-(
- impossible to enter "-1" (solution: leave the field and come back)
