### ISSUE TITLE
Calendar: Dropdown of the calendar is contained inside the dialog but it should be over the dialog

### ISSUE THREAD

**Issue by tforget** [primefaces/primevue#3383]
### Describe the bug

Hello I'm having this same issue as this one. I believe it was fixed by making append-to default value to body for most components that have this prop. For me it is with the calendar. When it opens it opens inside the dialog component. If the dialog component is to small to display it all, you have to scroll. I believe that the calendar should be over the dialog when opened.

### Reproducer

https://codesandbox.io/s/async-thunder-f5fhpj?file=/src/App.vue

### PrimeVue version

2.10.0

### Vue version

2.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

go to https://codesandbox.io/s/async-thunder-f5fhpj?file=/src/App.vue

click the open button

click the calendar input

the calendar input dropdown opens inside the dialog

### Expected behavior

the calendar dropdown should not be contained inside the dialog

**Comment by bahadirsofuoglu** [comment]
Hi, I think appendTo prop solves this issue. You can try as below

`
<Calendar appendTo="body" />
`

**Comment by tforget** [comment]
I know I can fix it with appendTo="body", this improvement is not for me. It is for people using this library so they don't have to wonder why their dropdowns are broken when displayed inside a dialog.
