### ISSUE TITLE
DataTable: Cannot select row or select all checkbox in multiple selection mode

### ISSUE THREAD

**Issue by RCelty** [primefaces/primevue#3384]
### Describe the bug

Nothing happened when I click on any of the checkbox of the DataTable

### Reproducer

https://codesandbox.io/s/cool-pascal-pqoux2

### PrimeVue version

^3

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Click on any of the checkbox
2. Nothing happened

### Expected behavior

Row checkbox checked on click, all checkbox checked when header checkbox clicked

**Comment by volvachev** [comment]
Hi, you have an invalid example in the sandbox. This is not an error.

I have changed your [example](https://codesandbox.io/s/trusting-nobel-4715r5).

**Comment by RCelty** [comment]
Ok thank you, that was my fault.
I will close this issue
