### ISSUE TITLE
DataTable: Disable filter overlay panel when clicking outside

### ISSUE THREAD

**Issue by AniaKru95** [primefaces/primevue#3388]
### Describe the feature you would like to see added

I'm wondering is there possible way to disable option "click-outside close element".

### Is your feature request related to a problem?

I used above code from: https://codesandbox.io/s/wbhep2

1. I selected two Agents like on the screen
![obraz](https://user-images.githubusercontent.com/84393751/206442422-dfbf50b2-dba5-459d-9a8a-2c1d285c6766.png)

2. Then i clicked somewhere outside
3. Multiselect with dropdown closes and "Agent Picker" also is closed.
4. I have to  click again "filter column" to open panel and then click "Apply"
5. Finally filters are applied

### Describe the solution you'd like

I would like to: 
1. select options in dropdown
2. click outside
3. dropdown panel should close
4. "Agent picker" shouldn't close
5. Click apply 

It is really annoying, in case of huge dropdown list, and everything is closed.

**Comment by mertsincan** [comment]
It is by design. But, you can create a ticket on our [discussion](https://github.com/orgs/primefaces/discussions/categories/primevue) page. 
For now, I think you can call `onFilterApply` method when you click outside.

Best Regards,
