### ISSUE TITLE
SplitButton: Clicking Arrow for other commands triggers default command

### ISSUE THREAD

**Issue by hollyfoxx** [primefaces/primevue#3389]
### Describe the bug

When clicking the dropdown arrow in SplitButton to select from list of commands, the default command is triggered as well. Bugged behavior can be observed in PrimeVue docs.

### Reproducer

https://primefaces.org/primevue/splitbutton

### PrimeVue version

3.2.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by choff5507** [comment]
I have this same issue and stumbled across this thread. Im wondering if this will be part of the next release and if there was an ETA for it? Thanks!

**Comment by tugcekucukoglu** [comment]
Please follow the https://github.com/primefaces/primevue/issues/3467
