### ISSUE TITLE
InputNumber can input special char

### ISSUE THREAD

**Issue by Gary-HuangHao** [primefaces/primevue#339]
**Hi PrimeVue team:**
**I find the inputnumber component can input special char, e.g Chinese char,and program error location, If input the special char browser will display an error message "Cannot set property 'value' of undefined",**
**1.Input chinese char show error message**
[![image](https://user-images.githubusercontent.com/66305136/83705123-9e2ea500-a646-11ea-9a80-9547448b4bf9.png)
](url)
**2.Program error location**
**OnInput event received is value not object**
[![image](https://user-images.githubusercontent.com/66305136/83704782-acc88c80-a645-11ea-97d2-c9dcbc9cfda0.png)
](url)

**Comment by mertsincan** [comment]
Could you please try this issue with v2.0.8?

Best Regards,

**Comment by Gary-HuangHao** [comment]
Thank you mertsincan, this problem is solved.
