### ISSUE TITLE
TieredMenu: Menu commands in the TieredMenu don't receive any arguments

### ISSUE THREAD

**Issue by jf908** [primefaces/primevue#3391]
### Describe the bug

In a typical menu item:
```js
{
  label: "Test",
  command: function(e) {
    console.log(e); // e is undefined
  }
}
```
The command function receives undefined instead of an object contained the originalEvent and other menu bits.

### Reproducer

https://codesandbox.io/s/dry-forest-3zsdh5?file=/src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Create a TieredMenu
2. Click on one of the TieredMenu items
3. Print out argument of command to see that it's undefined

### Expected behavior

The argument should be the same as Menu, it should be an object that contains the originalEvent.

**Comment by jf908** [comment]
Apologies, I linked a working version that used `<Menu>`, I've updated the reproducer to use `<TieredMenu>`

**Comment by Kixell-NicolasJardillier** [comment]
Hi, 

I have the same issue with Menubar
From the example provided by @jf908 replace TieredMenu by : 

- Menu => It works
- Menubar => It fails, with same error
- MegaMenu => It fails, with same error

any workaround ?

Best regards

**Comment by ThomasLaigneau** [comment]
Hi,

Same error here on MenuBar.

Any idea on how to fix it ?
