### ISSUE TITLE
DataGrid: Invalid typing of slot props

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3395]
### Describe the bug

When using scoped slots for column header/footer in data grid, typescript will complain for typings of the slot props.
For example

```vue
<column>
  <template #footer="{ column }">
     {{ column.props.field }}
  </template>
</column>
```

TS Will complain:
```error TS2551: Property 'props' does not exist on type 'Column'. Did you mean '$props'?```

In the templates the `$` is removed, so the typings should be updated

### Reproducer
https://codesandbox.io/s/vite-primevue-forked-7rl78b?file=/src/App.vue

Happen when using vite + vite-tsc
```ts
import vuePlugin from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import checkerPlugin from 'vite-plugin-checker'

export default defineConfig({
  plugins: [checkerPlugin({ vueTsc: true }), vuePlugin()]
})
```
Would probably appear in the VS Code using Volar extension

### PrimeVue version

3.20

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Magiczne** [comment]
Will prepare reproduction today/tommorrow

**Comment by Magiczne** [comment]
@tugcekucukoglu  - I've added reproduction codesandbox.

**Comment by tugcekucukoglu** [comment]
How can we replicate the problem? The link is broken.

**Comment by Magiczne** [comment]
Updated link: https://codesandbox.io/p/sandbox/vite-primevue-forked-wl16wi
