### ISSUE TITLE
Button : LongPress

### ISSUE THREAD

**Issue by capoia** [primefaces/primevue#3397]
### Describe the feature you would like to see added

Hello, I think it would be amazing to have some directive or even some separate component where you need to hold down (while this fills the button to indicate the necessary time) to execute an action, it would be a great alternative to dialogs to delete things.

### Describe the solution you'd like

A button that executes a function after being pressed for a predefined time, with visual indication.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
