### ISSUE TITLE
Keep selected status of menu

### ISSUE THREAD

**Issue by west-farmer** [primefaces/primevue#340]
The selected status of menu  (with a blue box) disappeared when the focus losed, is there plan to enhance this feature, or any suggestion to do it in applicaton?

**Comment by cagataycivici** [comment]
I think it depends on theme, please try with 2.0.0-rc.2 at least, for example with Saga theme;

![Screen Shot 2020-07-04 at 13 13 40](https://user-images.githubusercontent.com/686247/86510444-424b6d80-bdf8-11ea-8bc3-307494d16b6a.png)
