### ISSUE TITLE
More powerful Field or Form components

### ISSUE THREAD

**Issue by codeflorist** [primefaces/primevue#3401]
### Describe the feature you would like to see added

What i find sorely lacking in PrimeVue are the form field components. Almost every other frontend UI component library provides form-field components that provide all functionality typically required for form-fields, e.g.
- `label` property and/or slot to handle labels
- `hint`/`message`/`error` property and/or slot to handle help-texts, errors for fields
- `clearable` prop to add a clear-button to an input

These additional functionalities are typically provided either directly with the field-components, or via a wrapper-component (e.g. `Field`).

Furthermore, many libraries provide a `Form` component to centrally handle fields/validation etc. for the whole form.

E.g. PrimeVue's `InputText` component does not even have a `label` property, which means it is basically not much more than a styled HTML `input` element. This means i have to create many wrapper components with lots of additional markup and code to achieve a fully woking form with minimal code duplication.

See e.g. how other frameworks are providing such funcionality:
[Vuetify](https://next.vuetifyjs.com/en/components/forms/), [Ionic](https://ionicframework.com/docs/api/input), [Oruga](https://oruga.io/components/Field.html), [VANT](https://vant-ui.github.io/vant/#/en-US/field)

**Comment by tugcekucukoglu** [comment]
It's on our roadmap.

Thanks for your understanding.
