### ISSUE TITLE
Tooltip should fire on focus and hover by default

### ISSUE THREAD

**Issue by codeflorist** [primefaces/primevue#3402]
### Describe the feature you would like to see added

Almost every frontend framework's Tooltip behaviour is, that it fires both on hover (for Desktop) and on focus (for mobile and screenreaders).

PrimeVue's tooltip fires only on hover by default, which can be changed to focus via a property - but then it won't fire on hover anymore.

So to accomplish the behaviour i want from a tooltip 99,9% of the time, i have to do something silly like this in PrimeVue:

```html
<InputText type="text" v-tooltip.focus="'Enter your username'" v-if="my-own-touch-and-screenreader-detection" />
<InputText type="text" v-tooltip="'Enter your username'" v-else />
```

Please make tooltips fire on hover AND focus by default, or at least make it possible to listen to hover AND focus events at the same time.

PS: Please note, that there were already 2 issues requesting this: #2254 and #2455, which were sadly ignored and closed.

**Comment by tugcekucukoglu** [comment]
Duplicate #2254 #2455

**Comment by codeflorist** [comment]
lol

**Comment by painerp** [comment]
> Duplicate #2254 #2455
Even if it is a duplicate the underlying problem is still not resolved. Furthermore there are only bandaid solutions given in your linked Issues. 
Please reconsider one of these issues since it seems like an problem worth fixing to help mobile & desktop interoperability

**Comment by Hextar** [comment]
I absolutely agree this is should be the default behavior.

It shows on hover by default on desktop and on focus on mobile.

I've tried doing things like:
```
v-tooltip="{
      value: missingConsume,
      autoHide: false,
      disabled: !isDisabled,
      modifiers: { 
          focus: isMobile
     }
}"
```

OR 

```
v-tooltip="{
      value: missingConsume,
      autoHide: false,
      disabled: !isDisabled,
      focus: isMobile
}"
```

but it doesn't works
