### ISSUE TITLE
Autocomplete: Overlay dropdown not opening consistently with server side data

### ISSUE THREAD

**Issue by tforget** [primefaces/primevue#3404]
### Describe the bug

When using the autocomplete with server side data, we do not fetch any data when the search string is empty and the suggestions are a empty array or null. However this does not work well with the current logic to open the overlay as it sometimes does not open when it should. 

### Reproducer

https://codesandbox.io/s/practical-joana-71i86y?file=/src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

go https://codesandbox.io/s/practical-joana-71i86y?file=/src/App.vue

Overlay inconsistent behavior

type a   --> search term is "a" and overlay is open
hit delete. --> seach team is "" and overlay is closed
type a --> seach tearm is "a" and overlay is closed

The overlay opens correctly the first time you type "a", however the second type you type a, the overlay does not open and the state is remains loading.

The overlay works correctly if using "A"

type A   --> search term is "A" and overlay is open
hit delete. --> seach team is "" and overlay is closed
type A --> seach tearm is "A" and overlay is open

### Expected behavior

The overlay should be visible when you type a the second type.

**Comment by bahadirsofuoglu** [comment]
Hi,
We discussed this issue as a team. We believe that the problem you are experiencing can be solved with some events such as 'change'. I'm closing this issue for now. If you have trouble finding the solution, you can create a new ticket.

Best Regards,
Bahadir
