### ISSUE TITLE
Tree: expandedKeys not updating

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#3407]

**Comment by tugcekucukoglu** [comment]
<img width="459" alt="Screen Shot 2022-12-16 at 11 12 30" src="https://user-images.githubusercontent.com/32294991/208053549-2b4f028d-6c30-4f58-b390-75a08a006c80.png">

**Comment by bahadirsofuoglu** [comment]
We will check again.

<img width="802" alt="Screen Shot 2022-12-30 at 11 45 38" src="https://user-images.githubusercontent.com/45143524/210051706-1d3c0b98-8212-40fc-b1f6-e695d4d3bda6.png">

**Comment by tugcekucukoglu** [comment]
Fixed https://github.com/primefaces/primevue/commit/59451e279a81069189fc599ccda6742563c7637e
