### ISSUE TITLE
Inplace: programmatically switch to display mode

### ISSUE THREAD

**Issue by stevenvdbosch** [primefaces/primevue#3408]
### Describe the feature you would like to see added

My use case is: i would like to make a form with multiple inplace elements and one Save button. Whenever i hit the save button, my changes will be send to my backend and i would like to put all my inplaces back to display mode. 
I currently don't see a way to close them programmatically unless i am missing something.

Do i miss something ?
In case i miss something: maybe we could update the documentation, now it is very brief in my opinion.

In case i don't miss something, is there interest in this sort of behavior?

PS: i don't want the closable button to be displayed. I think it is confusing.

### Is your feature request related to a problem?

I currently don't see a way to close "Inplace" programmatically

### Describe the solution you'd like

a way to call the close method of the Inplace element.

**Comment by stevenvdbosch** [comment]
An alternative i am seeing right now is to rerender my whole form with the :key="xx" technique.

`<template>
  <MyComponent :key="componentKey" />
</template>`

`import { ref } from 'vue';
const componentKey = ref(0);

const forceRerender = () => {
  componentKey.value += 1;
};`

there might be not enough value in my request... but we might see if others are interested

**Comment by DenizMOz** [comment]
There is a property of listbox called "active",with an assigned watcher. Have you tried using :active="@onclick" or similar?

**Comment by umar13893** [comment]
In my case re rendering the component was not a good options. I have tried something like this.

`<Inplace :closable="true" :active="**display_inplace_view**" @open="**callback_inplace_open**()">`

on the @open **<Inplace>** event event change the :active **display_inplace_view** value to true and then on save changes button click change the **display_inplace_view** value to **false**.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
