### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by yormy** [primefaces/primevue#3414]
### Describe the bug

It seems that the input style is not applied to the container. When I do a input-style: width:100%, the actual field is not 100% as it is contained by the container

`<div class="p-password p-component p-inputwrapper p-input-icon-right" is-required="true" id="71502">
<input class="p-inputtext p-component p-password-input" type="password" aria-controls="pv_id_1_panel" aria-expanded="false" aria-haspopup="true" style="width: 100%;">

### Reproducer

.

### PrimeVue version

.

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

.

### Steps to reproduce the behavior

..

### Expected behavior

..

**Comment by volvachev** [comment]
Hi, could you please add an example.
