### ISSUE TITLE
Icon splitbutton is hardcoded

### ISSUE THREAD

**Issue by yormy** [primefaces/primevue#3415]
### Describe the bug

I cannot change the dropdown chevron icon from the splitbutton
```
...
icon="pi pi-chevron-down"
...
```

### Reproducer

.

### PrimeVue version

.

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

.

### Steps to reproduce the behavior

.

**Comment by volvachev** [comment]
Hi, you can set a new icon using `menuButtonProps`.

`:menuButtonProps="{icon: 'pi pi-chevron-up'}"`

**Comment by tugcekucukoglu** [comment]
There is no specific attribute for dropdown button icon, you can use `menuButtonProps`

**Comment by yormy** [comment]
Awesome... thanks
