### ISSUE TITLE
Autocomplete: Browser Source does not match Documentation

### ISSUE THREAD

**Issue by Dazaer** [primefaces/primevue#3417]
### Describe the bug

I was trying to reproduce a different issue and I'm unable to proceed because the browser source does not match the documentation.
For example it's using `optionLabel`, while `field` is the only prop that actually works.

I can't guarantee the proper reproduction of my bug if even the base code given is not working properly. I don't know what else could be missing.

### Reproducer

https://codepen.io/dazaer/pen/abjbzvd

### PrimeVue version

3^

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Change the `optionLabel` to `field`

This will display the proper name.

**Comment by tugcekucukoglu** [comment]
Browser example does not accept camelcase. You could change `optionLabel` as  `option-label`.

**Comment by Dazaer** [comment]
> Browser example does not accept camelcase. You could change `optionLabel` as `option-label`.

Ah great, thanks. Browser Source still needs to be updated though as it won't run properly currently.

**Comment by tugcekucukoglu** [comment]
Thanks for the update.
