### ISSUE TITLE
DataTable: Filtering using Named Scoped Slots does not work as documented

### ISSUE THREAD

**Issue by eduvv** [primefaces/primevue#3425]
### describe the bug
When using the destructured props `{ filterModel, filterCallback }` as described here: https://primefaces.org/primevue/datatable/filter the component does not seem to filter or do anything.

However when dynamically altering the passed `:filters="filter"` prop, it does work.

⚠️ The strange this is that the example in the docs does seem to work with those slot props, but when recreating this behavior it renders a different result.

**this works** (ignoring named slot props)
```html
<template>
    <DataTable :filters="filter">
      <Column>
        <template #filter>
          <InputText v-model="filter['foo'].value" />
        </template>
      </Column>
    </DataTable>
</template>
<script setup>
const filter = ref({'foo': { value: null, matchMode: FilterMatchMode.STARTS_WITH }});
</script>
```

**this doesn't work**
```html
<template>
    <DataTable :filters="filter">
      <Column>
        <template #filter="{ filterModel, filterCallback}">
          <InputText v-model="filterModel.value" @input="filterCallback()"/>
        </template>
      </Column>
    </DataTable>
</template>
<script setup>
const filter = ref({'foo': { value: null, matchMode: FilterMatchMode.STARTS_WITH }});
</script>
```

### reproducer
https://stackblitz.com/edit/nuxt-starter-us9exy?file=app.vue

### dependencies
nuxt: `3.0.0`
primeflex: `^3.2.1`
primeicons: `^6.0.1`
primevue: `^3.18.1`

### envinfo
```
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.64 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.asdf/installs/nodejs/18.10.0/bin/node
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 108.1.46.133
    Chrome: 108.0.5359.94
    Safari: 16.1
  npmGlobalPackages:
    corepack: 0.14.1
    npm: 8.19.2
    pnpm: 7.17.1
```

**Comment by tugcekucukoglu** [comment]
Please try to use `v-model:filters="filters"` instead of `:filters="filters"`
