### ISSUE TITLE
Can't create groupfooter with expander and inherited aligning

### ISSUE THREAD

**Issue by viladimiru** [primefaces/primevue#3427]
I want to create table with custom row at the end and expansion and for this I need to create a new table inside of the groupfooter, but am missing aligning of the parent table

**Comment by tugcekucukoglu** [comment]
We're working on the DataTable css styles and for the next versions, it will fixed.

**Comment by tugcekucukoglu** [comment]
Please try to use the latest version. If the problem still persists please create an issue with a codesandbox link.

**Comment by marcelfilipe** [comment]
Hi @tugcekucukoglu 
The legacy alignment issue in groupfooter still doesn't work. I tried updating to version 3.30.1 and it didn't work.
The last version this feature works on is 3.23.0
Tks.
