### ISSUE TITLE
Messages are not visible in simple uploader

### ISSUE THREAD

**Issue by h-guerrero** [primefaces/primevue#343]
Hi, I am using the **FileUpload basic with auto** component. I set a maxFileSize attribute for 1mb, when I choose a heavier file I see no error. 

I found the "invalidFileSizeMessage" attribute but nothing is visible on @error event.

How can I catch the invalid file size message? Thanks!

**Comment by cagataycivici** [comment]
Added support for messages in simple mode as well, note that error is for http code, this is more like validation error so a message is displayed instead.

**Comment by alqa-dash** [comment]
How can one internationalize error messages to be able to display file name, localized message and file size?
