### ISSUE TITLE
PanelMenu: open/close events flipped

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3434]
### Describe the bug

If you use the expandedKeys property of PanelMenu, the open/close events are flipped.

### Reproducer

https://codesandbox.io/s/serene-goodall-xl38t1?file=/src/PanelMenuDemo.vue

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

on Reproducer:
on first example a click on a closed option will alert "panel**Open**".
on second example a click on a closed option will alert "panel**Close**".

### Expected behavior

click on a closed option should always fire "panelOpen" event

**Comment by limbitskiy** [comment]
yep. i can confirm that
