### ISSUE TITLE
PanelMenu: add an 'item-select' event when clicking an item

### ISSUE THREAD

**Issue by limbitskiy** [primefaces/primevue#3438]
### Describe the feature you would like to see added

Many components, including panel menu, lack an event when user clicks an item. I think it might be useful to people and i can add that to all components that need it.

### Describe the solution you'd like

Adding one line of code

### Additional context

Components use 'commands' to execute certain actions, but this is not always suitable. In my case ( i'm sure i'm not alone in this ) i just need an event of item click, which is really easy to implement.

**Comment by Rakasch** [comment]
PanelMenu has "panel-open" and "panel-close" event.
If you use both, it's equivalent to panel-click.

**Comment by limbitskiy** [comment]
Also it's semantically wrong. When i click an item i am not opening or closing anything.
(I know that internally the component opens and closes **any** item, regardless of whether it has children or not, which is also kind of strange)

**Comment by tugcekucukoglu** [comment]
For now, we're not planning to add new emit.

Thank you for your time.

**Comment by tewnut** [comment]
I would vote up for request from @limbitskiy. Panel open and close are not triggered when sub menuitem is clicked.
