### ISSUE TITLE
Broken link in docs 

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3439]
### Describe the bug

all link on github in docs broken 

![image](https://user-images.githubusercontent.com/16963395/208981286-9afd67b2-737f-4bef-b1e0-c3e57ac3b527.png)
![image](https://user-images.githubusercontent.com/16963395/208981315-01cc3866-fd87-452f-a351-b3363491d141.png)

### Reproducer

no

### PrimeVue version

now

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Thanks for your attention. It will be fixed with the new showcase.
