### ISSUE TITLE
TableHeader and DataTable: warn on console (already defined in Props.)

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3440]
### Describe the bug

Something is wrong with DataTable, throws an exception in the console for some tables

![image](https://user-images.githubusercontent.com/16963395/208981623-ae0d84cd-18ac-4776-9e65-b2ee27756296.png)
![image](https://user-images.githubusercontent.com/16963395/208981646-a062163d-6945-40cd-83e9-54e96ac6628b.png)

[Vue warn]: Computed property "groupRowSortField" is already defined in Props. 
  at <TableHeader columnGroup=null columns= (3) [{…}, {…}, {…}] rowGroupMode=null  ... > 
  at <VirtualScroller ref="virtualScroller" items= [] columns= (3) [{…}, {…}, {…}]  ... > 
  at <DataTable paginator=true rows=20 RowsPerPageDropdown=""  ... > 

runtime-core.esm-bundler.js:40 [Vue warn]: Computed property "allRowsSelected" is already defined in Props. 
  at <TableHeader columnGroup=null columns= (3) [{…}, {…}, {…}] rowGroupMode=null  ... > 
  at <VirtualScroller ref="virtualScroller" items= [] columns= (3) [{…}, {…}, {…}]  ... > 
  at <DataTable paginator=true rows=20 RowsPerPageDropdown=""  ... > 

### Reproducer

no

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by Tamas-hi** [comment]
I have the exact same warnings, when I use an expanded DataTable. Upon expanding, these warnings pop up.
