### ISSUE TITLE
Selection of data table is not updated after removing element

### ISSUE THREAD

**Issue by some-user123** [primefaces/primevue#3442]
### Describe the bug

When an element of the table is removed from the underlying array that was previously selected, it remains in the selection, even though it isn't selected any more as it is not even available to be selected.

### Reproducer

https://codesandbox.io/s/damp-snowflake-69j4qb?file=/src/App.vue

### PrimeVue version

3.12.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

- Open linked code sand box 
- Select first element
- Press button

Actual: Selected products still contains the element that is not displayed any more.
Expected: Selected products should be empty.

**Comment by tugcekucukoglu** [comment]
It is not a good practice if there are thousands of data on the client side. For now, we do not want to listen if the data is changed or not. Please check crud example https://www.primefaces.org/primevue/datatable/crud

Still, if there is more demand, we'll definitely reconsider. Thank you for your feedback. Closing for now.

**Comment by dm1tr** [comment]
@tugcekucukoglu I use `apollo client` and send a mutation that deletes the selected rows, after the mutation i update caches elements but, there is no way to remove the selected rows that no longer exists.

I think the selected elements mustn't contain elements that aren't exist in the table.
