### ISSUE TITLE
PanelMenu: Custom menu created with slots has an accesibillity bug in keyboard navigation

### ISSUE THREAD

**Issue by MargaritaBusyginaCa** [primefaces/primevue#3444]
### Describe the bug

Using the default PanelMenu with keyboard only works perfectly, however, if I create a menu with slots like this:

`<PanelMenu :model="items">
    <template #item="{ item }">
      <span>{{ item.label }}</span>
    </template>
  </PanelMenu>` 

I cannot navigate through the menu with a keyboard. Some nested items can't be expanded and links do not open (only with a mouse click).

### Reproducer

https://codesandbox.io/s/purple-rgb-q5kuop?file=/src/main.js

### PrimeVue version

3.21.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to "https://codesandbox.io/s/purple-rgb-q5kuop?file=/src/main.js"
2. Try tabbing through the first menu item ("File") with nested items. 

### Expected behavior

"New" menu items cannot be opened with keyboard, but can be opened with a mouse click.

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. Please check this example https://codesandbox.io/s/silly-sun-dgrhl0?file=/src/PanelMenuDemo.vue

**Comment by MargaritaBusyginaCa** [comment]
> Cannot replicate the issue. Please check this example https://codesandbox.io/s/silly-sun-dgrhl0?file=/src/PanelMenuDemo.vue

Thank you, I changed the code and now you should be able to replicate the bug. 
Please try tabbing through the menu (especially nested items). All nested items can't be opened with a keyboard, only a mouse click.

**Comment by mertsincan** [comment]
Hi @MargaritaBusyginaCa,
Unfortunately, I couldn't replicate it. What steps do I need to follow to replicate this issue?

https://user-images.githubusercontent.com/11868120/211316815-b9a90482-3293-4581-a394-a8ef98c40584.mov

**Comment by MargaritaBusyginaCa** [comment]
@mertsincan Hi there, in the menu, if you open File -> New -> Bookmark element has a link. Are you able to open it with a keyboard only? I can open it with a mouse, but not a keyboard.
The code is [here](https://codesandbox.io/s/purple-rgb-q5kuop?file=/src/PanelMenuDemo.vue).
