### ISSUE TITLE
TabView: When switching tabs, I duplicate the initialization of the previous component

### ISSUE THREAD

**Issue by itprodavets** [primefaces/primevue#3445]
### Describe the feature you would like to see added

Hi, I have a problem with TabView component. When switching tabs, I duplicate the initialization of the previous component. 

How can this be fixed? 

### Is your feature request related to a problem?

https://codesandbox.io/s/intelligent-snyder-e6ijsk?file=/src/views/C.vue

### Describe the solution you'd like

I want to use TabView component with routing.

**Comment by tugcekucukoglu** [comment]
Please check this example https://codesandbox.io/s/elastic-gwen-91xhnp?file=/src/Home.vue
