### ISSUE TITLE
Checkbox check item through props

### ISSUE THREAD

**Issue by yormy** [primefaces/primevue#3446]
### Describe the bug

In other components i can set the icon through props, that is really cool. Would be nice to have that feature too in the checkbox

### Reproducer

.

### PrimeVue version

.

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

..

### Expected behavior

.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3298
