### ISSUE TITLE
DataTable VirtualScroll: provided codesandbox link not working properly

### ISSUE THREAD

**Issue by eduvv** [primefaces/primevue#3451]
### Describe the bug

Codesandbox link at the top (https://www.primefaces.org/primevue/datatable/virtualscroll) does not work properly.

`CustomerService` -> `CarService` etc.
![image](https://user-images.githubusercontent.com/38420911/209688689-ce9b7d9d-c3f3-4bbd-94d1-587091f4b315.png)

### Reproducer

https://codesandbox.io/s/3654iz?file=/src/DataTableVirtualScrollDemo.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by tugcekucukoglu** [comment]
Please import the correct service.

`import CarService from "./service/CarService";`

**Comment by eduvv** [comment]
> Please import the correct service.
> 
> `import CarService from "./service/CarService";`

I know.. but it is literally documented like this: https://www.primefaces.org/primevue/datatable/virtualscroll
![image](https://user-images.githubusercontent.com/38420911/209813448-c5c52a84-74f6-46cd-9dbe-00155ce99878.png)

Also the link to the corresponding github page is broken..
![image](https://user-images.githubusercontent.com/38420911/209813602-e02af124-07e4-42c4-bbfb-a88fe184e31f.png)

**Comment by tugcekucukoglu** [comment]
Documentation will be fixed. Thanks for your attention!
