### ISSUE TITLE
ContextMenu cannot use this in command option

### ISSUE THREAD

**Issue by mjorgegulab** [primefaces/primevue#3454]
### Describe the bug

I cannot call a method when defining the `command` option of a _**ContextMenu**_ items.
Cannot use this directive.
I'm using typescript.

![](https://cdn.discordapp.com/attachments/787968875135762452/1057971348200226826/Captura_de_pantalla_2022-12-29_a_las_11.40.04.png)

### Reproducer

https://codesandbox.io/s/elastic-farrell-xnqmvp?file=/src/App.vue:1450-1461

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chromium 108, Brave 1.46.144

### Steps to reproduce the behavior
![Captura de pantalla 2022-12-29 a las 12 52 41](https://user-images.githubusercontent.com/57524711/209947420-8292905c-0bde-4179-a8ee-afb1ae9ee833.png)
![Captura de pantalla 2022-12-29 a las 12 52 48](https://user-images.githubusercontent.com/57524711/209947416-115408db-ba62-49e9-8767-01cda2126b3f.png)

###Expected behavior

_No response_

**Comment by bahadirsofuoglu** [comment]
When I changed to the script like below I can't find any problem. You can check this sample. https://codesandbox.io/s/g5cqub?file=/src/DataTableDemo.vue:1376-1465
`
<script>
export default {
  data() {
    return {
      dtColumns: [
        { field: "type", header: "Field Type" },
        { field: "kpi", header: "KPI" },
      ],
      products: [
        {
          type: "0",
          kpi: "hsfuishfdf",
        },
        {
          type: "327864",
          kpi: "sdfosidfj",
        },
      ],
      dtContextmenuModel: [
        {
          label: "Ver",
          icon: "pi pi-fw pi-search",
          command: () => this.viewProduct(),
        },
        { label: "Editar", icon: "pi pi-fw pi-pencil" },
      ],
      fieldObject: null,
    };
  },
  methods: {
    onRowContextMenu(event) {
      this.$refs.cm.show(event.originalEvent);
    },
    viewProduct() {
      alert("hello");
    },
  },
};
</script>
`

**Comment by mjorgegulab** [comment]
**you're completely right 🤦‍♀️**

But why when i use **_data_** like this: `data: () => ({ name: 'TEST' })` is not running??

**Comment by bahadirsofuoglu** [comment]
Your sample doesn't have this method. Could you try this and let me know again? Maybe a new codesandbox sample helps us. 

```
  onRowContextMenu(event) {
      this.$refs.cm.show(event.originalEvent);
    },
```
