### ISSUE TITLE
Calendar: Doesn't allow null types

### ISSUE THREAD

**Issue by Jupakabra** [primefaces/primevue#3469]
### Describe the bug

Currently calendar does not accept (Date | null) type as a valid CalendarValueType.
This results in typing errors, even though clearing the date sets the value to null.

### Reproducer

https://primefaces.org/primevue/calendar

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Browser(s)

Any

### Steps to reproduce the behavior

```TS
type CalendarValueType = Date | Date[] | undefined;

const date: CalendarValueType = null; // Type 'null' is not assignable to type 'CalendarValueType'
```

### Expected behavior

Typescript compiler not giving errors on valid date values.

**Comment by bahadirsofuoglu** [comment]
Duplicate #3400
