### ISSUE TITLE
DataTable: When clicking a row it does not expand

### ISSUE THREAD

**Issue by iamKonick** [primefaces/primevue#3476]
### Describe the feature you would like to see added

Hi, 

I have a **datatable** with rows and columns. Inside the rows I have **nested rows**. From the main row if I click the **toggle** button, only then it **expands** to the nested rows. 

There is no functionality to add if the user **clicks anywhere in the row** it should be also **expanded**. Basically, even without showing the toggle button the user should be able to click anywhere and see the expanded rows. 

- Because sometimes the **user doesn't know they need to click the toggle button.**

**Comment by iamKonick** [comment]
Anyone can shed some light in this one?

**Comment by iamKonick** [comment]
@cagataycivici can you please help?

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue? If the problem still persists, please create a new with a reproducer link.
