### ISSUE TITLE
DataTable: Grouping with expand

### ISSUE THREAD

**Issue by AniaKru95** [primefaces/primevue#3478]
### Describe the bug

I found an issue in datatable when options: grouping and expanding rows are used. (rowspan gorup mode)

When row has been expanded, data is moved to left like in my screen:

![obraz](https://user-images.githubusercontent.com/84393751/210329309-163be952-01bf-4e0f-9a9c-ff0c6b5b4edd.png)

### Reproducer

https://codesandbox.io/s/nice-fog-7875d0?file=/src/DataTableDemo.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create datatable with grouping
2. Add expander in the middle in table
3. Expand first row in a group - data is moved to left (skipping one column)
4. Expand last row in group - data is moved to left (skipping to first column)

### Expected behavior

Expanded data should be placed in fixed place, i.e. below the expander icon.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
