### ISSUE TITLE
CascadeSelect: "TypeError: Cannot set properties of undefined (setting 'minWidth')" when using appendTo=body

### ISSUE THREAD

**Issue by patrickschroeter** [primefaces/primevue#3479]
### Describe the bug

When using the 'appendTo="body"' property for the CascadeSelect component I'll get the following error: 

TypeError: Cannot set properties of undefined (setting 'minWidth')

### Reproducer

https://codesandbox.io/s/withered-architecture-okke9w?file=/src/App.vue

### PrimeVue version

2.9.x / 2.10.x

### Vue version

2.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

tested in Chrome

### Steps to reproduce the behavior

1. Open Select
2. Check developer tools for js errors

### Expected behavior

There is no error when opening the select options.

**Comment by NeisserMS** [comment]
Tengo este error, estoy trabajando con Angular 12 y pdfMake-wrapper y la verdad no entiendo el error, ya he definido los anchos de mis columnas. 

core.js:6479 ERROR Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting '_minWidth')
TypeError: Cannot set properties of undefined (setting '_minWidth')

**Comment by NeisserMS** [comment]
Muchas gracias, voy a probar.
