### ISSUE TITLE
Usage of header slot produces JavaScript error when beeing combined with ColumnGroups

### ISSUE THREAD

**Issue by AlexanderGrasberger** [primefaces/primevue#349]
Vue produces a error when using <template #header> inside of a ColumnGroup like so:
```
<ColumnGroup type="header">
    <Row>
        <Column field="someField" :sortable="true">
            <template #header>
               Custom header
            </template>
        </Column>
    </Row>
</ColumnGroup>
```
The issue is being caused by the usage of a component **ColumnSlot** within the TableHeader.vue.
In the registration for the component the name was changed to **DTColumnSlot**.

**Comment by AlexanderGrasberger** [comment]
I have sent a pull request according to this problem: https://github.com/primefaces/primevue/pull/345

**Comment by cagataycivici** [comment]
Thank you sir!
