### ISSUE TITLE
DataTable:  doesn't work as expected with Expand + Virtual Scroll

### ISSUE THREAD

**Issue by nin3439** [primefaces/primevue#3491]
### Describe the bug

When I use virtual scroll and expand functionality together, scroll's behavior is weird. It's jumping in one place if several rows are expanded.

### Reproducer

https://codesandbox.io/s/relaxed-fast-idujxj?file=/src/App.vue

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Safari 15, Google Chrome 107

### Steps to reproduce the behavior

1. Expand several (for instance, 1,2 and 3) rows and try to scroll

### Expected behavior

Scroll should work as usual

**Comment by colinstevens06** [comment]
I am also experiencing this. Running v3.17.0. I experience this with only one row expanded. Using scrollable table, using virtual scroll & an expanded row. With an expanded row, after scrolling lower on the page and stopping scrolling, it jumps to another spot

**Comment by sergeydus** [comment]
Doesn't virtual scroll require the use of the prop?

**Comment by glenndejaeger** [comment]
We have the same issue. When using virtual scroller in the DataTable, itemSize needs to be provided. This property is used by the virtual scroller to determine how many items should be rendered. But if the provided itemSize doesn't correspond to the height of every row,  virtual scroller will have strange behaviour.

We have the issue in 2 cases:
- Multiline text is shown in a row which makes the row's height grow
- A row is expanded

The first issue could be solved by explicitly setting row height via CSS and using overflow: ellipsis. The second issue can't be fixed easily.

Does anyone have a solution? The codesandbox link shared above doesn't seem to work.

**Comment by tomaskovacic** [comment]
> This example seems to work https://codesandbox.io/s/fancy-sun-9bt4ve with the latest PrimeVue version.

@tugcekucukoglu  Could you please provide a new link because this one doesn't work. 


We have the same problem.
