### ISSUE TITLE
Select with create new values

### ISSUE THREAD

**Issue by bauhuynhdev** [primefaces/primevue#3497]
### Describe the feature you would like to see added

Please add this feature, Thank you so much.
Demo: [https://quasar.dev/vue-components/select#create-new-values](https://quasar.dev/vue-components/select#create-new-values)

**Comment by bahadirsofuoglu** [comment]
Hi, Link is broken.

**Comment by bauhuynhdev** [comment]
> Hi, Link is broken.

Hi [bahadirsofuoglu](https://github.com/bahadirsofuoglu). I updated the link.

**Comment by tugcekucukoglu** [comment]
This functionality already exists. Please check https://primevue.org/chips/
