### ISSUE TITLE
MenuItem: Failed to resolve entry for package "primevue/menuitem"

### ISSUE THREAD

**Issue by TechWatching** [primefaces/primevue#3498]
### Describe the bug

When importing and using the MenuItem component in a Vue.js component I have the following error when the code runs: 
`Failed to resolve entry for package "primevue/menuitem". The pacakge may have incorrect main/module/exports specified in its package.json`.

It seems that this [PR](https://github.com/primefaces/primevue/pull/2963) solves the issue but it was not merged.

### Reproducer

https://codesandbox.io/s/frosty-clarke-6y4o40?file=/src/main.ts

### PrimeVue version

3.12.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. import MenuItem in a vue component
2. run the vuejs application
(Can be reproduced using the codesandbox)

**Comment by tugcekucukoglu** [comment]
Menuitem is an inner component that PrimeVue menu components use. As you can see here there is no menuitem dependency https://primefaces.org/primevue/menumodel

**Comment by TechWatching** [comment]
@tugcekucukoglu If we are using the MenuModel component and want to pass the items dynamically, we need the MenuItem types. Otherwhise we have to create a type with the exact same properties than MenuItem.

**Comment by TechWatching** [comment]
@tugcekucukoglu  This [PR](https://github.com/primefaces/primevue/pull/3618) solves the issue, could you accept the PR ?

**Comment by wcarson** [comment]
@tugcekucukoglu   Why was this closed? This is still an issue.

**Comment by colinbes** [comment]
Any progress on this as I have the same issue but with later version of primevue 3.29.2

My work around is to import as follows:
```
import { MenuItem } from "@/../node_modules/primevue/menuitem/MenuItem"
as opposed to
import { MenuItem } from "primevue/menuitem"
```

**Comment by lenaschimmel** [comment]
@tugcekucukoglu Could you please consider to re-open this issue and/or merge one of the two related PRs (#2963 or #3618)?

Importing `MenuItem` is needed for everyone who uses strictly typed TypeScript to dynamically create menu items.

I know that this was originally reported for `3.12.4`, but in my setup, it only broke recently when I updated from `3.27.0` to `3.30.2`. With the current state of the code, there are these options to import it:

* `import { MenuItem } from "primevue/menuitem"` - works with `vite build` but not with `vite`*
* `import { MenuItem } from "primevue/menu"` - works with `vite` but not with `vite build`
* `import { MenuItem } from "@/../node_modules/primevue/menuitem/MenuItem"` (as suggested [above](https://github.com/primefaces/primevue/issues/3498#issuecomment-1624351437)) works with both but seems really hacky

Before the update, `import { MenuItem } from "primevue/menuitem"` just worked with both `vite build` and `vite`.

_\* Note: `vite build` runs `rollup` under the hood to create a production build, `vite` runs a development server for local experimentation._

**Comment by svwezel** [comment]
I have the same problem but with using the DynamicDialogInstance type like so:
`const dialogRef = inject<ComputedRef<DynamicDialogInstance>>("dialogRef");`
`Failed to resolve entry for package "primevue/dynamicdialogoptions/". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by kiasyn** [comment]
> Any progress on this as I have the same issue but with later version of primevue 3.29.2
> 
> My work around is to import as follows:
> 
> ```
> import { MenuItem } from "@/../node_modules/primevue/menuitem/MenuItem"
> as opposed to
> import { MenuItem } from "primevue/menuitem"
> ```

Extending on this workaround I added it as an alias to my vite.config file which lets me use the old syntax:

```
{
    // [ ... ]
    resolve: {
        alias: {
            'primevue/dynamicdialogoptions': '@/../node_modules/primevue/dynamicdialogoptions/DynamicDialogOptions',
            'primevue/menuitem': '@/../node_modules/primevue/menuitem/MenuItem'
        }
    },
    // [ ... ]
}
```

**Comment by andrey-zakharov** [comment]
Fix for me was to "import type", not just "import":
```
import type { MenuItem } from "primevue/menuitem"
import type { DynamicDialogCloseOptions, DynamicDialogOptions } from 'primevue/dynamicdialogoptions'
```

**Comment by frasza** [comment]
> Fix for me was to "import type", not just "import":
> 
> ```
> import type { MenuItem } from "primevue/menuitem"
> import type { DynamicDialogCloseOptions, DynamicDialogOptions } from 'primevue/dynamicdialogoptions'
> ```

Same thing solved issue on my side. Any explanation on this @tugcekucukoglu ? I just want to understand it well enough to explain. Thanks!

**Comment by marknn3** [comment]
This generates the 'failed to resolve' error:
```javascript
import { type MenuItemCommandEvent } from 'primevue/menuitem';
```
But this fixes the error:
```javascript
import type { MenuItemCommandEvent } from 'primevue/menuitem';
```

Is this a Vite bug?

**Comment by DanRoddis** [comment]
> This generates the 'failed to resolve' error:
> 
> ```js
> import { type MenuItemCommandEvent } from 'primevue/menuitem';
> ```
> 
> But this fixes the error:
> 
> ```js
> import type { MenuItemCommandEvent } from 'primevue/menuitem';
> ```
> 
> Is this a Vite bug?

Your initial import syntax isn't quite hitting the mark for what you're trying to achieve. When you use import { type MenuItemCommandEvent } from 'primevue/menuitem';, it's actually a mix-up of two different valid syntaxes, which is why Vite gets a bit confused.

The correct way to go about it, as you've found out, is import type { MenuItemCommandEvent } from 'primevue/menuitem';. This syntax is spot on because it specifies that you're importing a type rather than a regular JavaScript module.

**Comment by NodeAdam** [comment]
This needs to be exported if primevue is going to be typesafe

**Comment by Jimmy-sheep** [comment]
Use this...
```typescript
import type { MenuItem } from "primevue/menuitem";
```
instead of these...
```typescript
import { MenuItem } from "primevue/menuitem";
import { type MenuItem } from "primevue/menuitem";
```
