### ISSUE TITLE
SpeedDial: Overlapping Issue

### ISSUE THREAD

**Issue by acsellers** [primefaces/primevue#3504]
### Describe the bug

When a SpeedDial overlaps another SpeedDial, the closed one can block clicks from the open one. Giving the open SpeedDial a higher z-index fixes the conflict for my instance at least.

### Reproducer

https://codesandbox.io/s/jolly-river-f8z5n5

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Click on the upper SpeedDial, the buttons will show up under the lower SpeedDial or the buttons will not be clickable.

### Expected behavior

The Open SpeedDial should have its button clickable even if it overlaps another SpeedDial

**Comment by bahadirsofuoglu** [comment]
Hi,
I believe that the problem you are experiencing can be solved without a core development. I hope the example I shared below will help you with the solution.
https://codesandbox.io/s/exciting-lumiere-c4i5vp?file=/src/App.vue
