### ISSUE TITLE
Primevue 2.0.0-SNAPSHOT npm package does not contain any components

### ISSUE THREAD

**Issue by annnoo** [primefaces/primevue#351]
Hello everybody,

apperantly there are some issues with the latest npm package (*2.0.0-SNAPSHOT*). This release does not contain **any** components at all, just a package.json, a gulpfile, the chamgelog and the readme.
![image](https://user-images.githubusercontent.com/23224564/86089608-d4760d80-baa8-11ea-8a80-03d54ff7e01c.png)

You can also see this via the npm page of the package. The latest version of the package has only as size of ~33kb, compared to the 33MB of the previous version (*2.0.0-rc.1*).   

![image](https://user-images.githubusercontent.com/23224564/86089729-13a45e80-baa9-11ea-84b2-141244f30809.png)
![image](https://user-images.githubusercontent.com/23224564/86089759-24ed6b00-baa9-11ea-8e98-d1869c9df538.png)

I guess that this behavior is not intentional. To still use primevue you have to install the 2.0.0-rc.1 manual (`npm i primevue@2.0.0-rc.1`)

# Steps to Reproduce

`npm i primevue`

This will install the latest primevue version, which is 2.0.0-SNAPSHOT and does not contain any components.

**Comment by zhiwenchong** [comment]
Corroborating... there's nothing in node_modules/primevue in 2.0.0-SNAPSHOT.

Very unusual.

**Comment by codeplotter** [comment]
This also affects those of us using script tags instead of package managers.

**Comment by cagataycivici** [comment]
It was a broken release, sorry for that, please use 2.0.0-rc.2
