### ISSUE TITLE
DataTable: Single Selection Mode Cannot Deselect Row

### ISSUE THREAD

**Issue by MoMack20** [primefaces/primevue#3510]
### Describe the bug

The documentation states "In single mode, a row is selected on click event of a row. If the row is already selected then the row gets unselected." However, on the example this is not the case as the row will always remain selected.

### Reproducer

https://codesandbox.io/s/primevue-3-issue-template-ip3vm

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1) Go to the DataTable Selection page: https://www.primefaces.org/primevue/datatable/selection
2) Click on a row to select it, click the same row again.
3) The row is not deselected

### Expected behavior

The row is deselected.

**Comment by Olguorsbasak** [comment]
Hi,
The "metaKeySelection” property is used when the selectionMode property is set to "single", and it indicates that the user needs to press a meta key to select the row. 

If you do not want to use metaKey feature, change the metaKeySelection prop to false .
