### ISSUE TITLE
DropdownMenu: Disabled dropdown can still be opened with screen reader

### ISSUE THREAD

**Issue by MargaritaBusyginaCa** [primefaces/primevue#3512]
### Describe the bug

The disabled menu can be expanded and the options can be selected even when the disabled prop is set to true. This bug only happens with a screen reader (in my case, VoiceOver on Mac).

![Screen Shot 2023-01-10 at 12 08 43 PM](https://user-images.githubusercontent.com/74435192/211618007-b0d5dbb5-14dd-47b3-8f58-975cce56eff6.png)

### Reproducer

https://codesandbox.io/s/admiring-wilson-8orq7w?file=/src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. go to the code [playground](https://codesandbox.io/s/admiring-wilson-8orq7w?file=/src/App.vue).
2. open your screen reader
3. tab on the heading, so the screen reader selects it and then tab to the dropdown field (on Mac press Shift+CTRL+Option+right arrow)
![Screen Shot 2023-01-10 at 12 18 54 PM](https://user-images.githubusercontent.com/74435192/211619597-3f375301-d859-42a4-a139-9bf1d8c18b6d.png)
![Screen Shot 2023-01-10 at 12 19 46 PM](https://user-images.githubusercontent.com/74435192/211619607-b87884c9-10f6-42a9-96d3-489a7e2b3b69.png)

### Expected behavior

The disabled dropdown will be opened with a screen reader, it will be possible to select options and close the menu.

**Comment by mertsincan** [comment]
Affected components;

- [ ] Dropdown
- [ ] AutoComplete
- [ ] MultiSelect
- [ ] CascadeSelect
