### ISSUE TITLE
Wanna create a custom class with Primevue component classes but it doesn't work

### ISSUE THREAD

**Issue by sahil-xyrintech** [primefaces/primevue#3515]
### Describe the feature you would like to see added

`.btn-icon {
    @include styleclass('p-button-rounded border-round-md p-button-danger p-button-outlined');
}`

I'm trying like this but I didn't find any solution .

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
