### ISSUE TITLE
ConfirmPopup: page scrolls up when push the button

### ISSUE THREAD

**Issue by Cersin** [primefaces/primevue#3516]
@tugcekucukoglu its working now but only with first click.
https://codesandbox.io/s/compassionate-lovelace-xr1deg
When you click no and try again it scrolls up again :P

_Originally posted by @Cersin in https://github.com/primefaces/primevue/issues/3432#issuecomment-1378673623_

**Comment by Cersin** [comment]
Completed?

**Comment by bahadirsofuoglu** [comment]
Hi, I closed it because the issue was invalid. We will check the issue and open the old issue if necessary.

**Comment by Cersin** [comment]
@bahadirsofuoglu problem still occurs

**Comment by bahadirsofuoglu** [comment]
We are actively working on major changes. But we are aware of this problem. It will be fixed shortly. Thank you for your understanding
