### ISSUE TITLE
Can't import terminal (or any other component) into a project

### ISSUE THREAD

**Issue by pitometsyurii** [primefaces/primevue#352]
After installing the library with `npm install primevue --save` I have an error message in my IDE that 

<img width="384" alt="Screen Shot 2020-06-30 at 11 04 00" src="https://user-images.githubusercontent.com/4027685/86149420-8d484680-bac1-11ea-82a5-bff41cd57b52.png">

This is how package looks in node_modules folder.

<img width="330" alt="Screen Shot 2020-06-30 at 11 05 34" src="https://user-images.githubusercontent.com/4027685/86149529-af41c900-bac1-11ea-9007-84a29a22f2e8.png">

**Comment by annnoo** [comment]
Alcready created this problem in #351 . The current default version has somehow no vue files in it. To still use vue just install the latest working version (npm i primevue@2.0.0-rc.1)

**Comment by pitometsyurii** [comment]
Thanks, did not noticed that. I am closing this one then.
