### ISSUE TITLE
Two way binding for dropdown, listbox, multiselect filter

### ISSUE THREAD

**Issue by ochiers** [primefaces/primevue#353]
Hello,

Would be nice to add a double-binding for the filter value on the dropdown.

Hope that is the good way to ask for new content :)

**Comment by cagataycivici** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
