### ISSUE TITLE
Datatable: dropdown in filter fail when filterDisplay is set to "menu"

### ISSUE THREAD

**Issue by rmartinm** [primefaces/primevue#3536]
### Describe the bug

Dropdown in filter throws "Cannot read properties of undefined (reading '0')" when i change between the filter options.
The problem appears when the datatable property filterDisplay is set to "menu".

![image](https://user-images.githubusercontent.com/2640799/212434339-ee919c8b-cede-4024-b0c7-6a22d9e95553.png)

### Reproducer

https://codesandbox.io/s/tender-benji-ltt8ix?file=/src/FilterServiceDemo.vue

### PrimeVue version

3.22.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to name filter
2. Select an option

**Comment by tugcekucukoglu** [comment]
You could follow menu filter example from [here](https://www.primefaces.org/primevue/datatable/filter) and also https://codesandbox.io/s/tender-benji-ltt8ix?file=/src/FilterServiceDemo.vue:1995-3117
