### ISSUE TITLE
Carousel: missing event `@upadte:page` in the document

### ISSUE THREAD

**Issue by ga676005** [primefaces/primevue#3544]
### Describe the feature you would like to see added

I could not find a way to get the current index of visible item of the carousel. 
I looked into the [source code](https://github.com/primefaces/primevue/blob/master/components/carousel/Carousel.vue#L89), and I found that there is a `update:page` custom event can do the job.
I try listen to the event on carousel and it works.

**Comment by tugcekucukoglu** [comment]
You could also listen `v-model:page` and v-model brings the default Vue method: `update:page`. Because of its Vue behavior, we do not document it.

Thanks,

**Comment by ga676005** [comment]
I see. I check the document again and It's not clear to me that I can do  `v-model:page`.
