### ISSUE TITLE
AutoComplete v-model on specific field

### ISSUE THREAD

**Issue by ochiers** [primefaces/primevue#355]
Hello,

I want to use the autoComplete component with complex object like suggestions.
But I need to bind the model on a specific field of the suggestion only.

We can specify the field to display selection but i need to bind on other field.

For example, a user with id and name, we want to display the name and autocomplete on it but the binding is on the id of the user.

Sincerely

**Comment by west-farmer** [comment]
My idea is  using  computed field sync simple var with the selected object

**Comment by cagataycivici** [comment]
Yes, that would work. If there are more requests, we may consider adding props like optionLabel, optionValue like the select components to AutoComplete.

**Comment by darmanovic** [comment]
I would also like to see this option. Strange that you haven't implemented it.

**Comment by vcmenezes** [comment]
I would also like to see this option.

**Comment by JuanRomanRiquelme** [comment]
i aldo need this, was there no update lately?

**Comment by InToSSH** [comment]
+1 would love to see this too. I switched from Vuetify where this was working, you could specify the prop for label and for value, then you could also switch if you want to return just the value prop (for example id) or the whole object, which was really useful. Now I need to create my custom wrapper for the Autocomplete to do this.

**Comment by mklueh** [comment]
Would be really nice to have that option. I'm basically transforming my Vue model to query parameters immediately, and having an object instead of the value inside it will create `city=[object+Object]`.

**Comment by kstan79** [comment]
ya ya, autocomplete + v-mode databinding need that so badly. Please support `optionValue`

**Comment by sshkpp** [comment]
I agee! I need optionValue props.

**Comment by YuriOsipov** [comment]
I agree! I need optionValue props as well

**Comment by frasza** [comment]
Cmon, please? :) @cagataycivici

**Comment by kstan79** [comment]
Base on my understanding autocomplete not design as prefetch all value. In that case autocomplete very hard to obtain label and value separately. If you need that you shall use dropdown, or create separate component, perform deeper engineering, play with emits to modify achieve the goal. I'm using primevue auto complete but I have similar requirement with you, with more complex requirement so I created own customize component on top of autocomplete

**Comment by Pijuli** [comment]
Why is this issue closed?
Select is working with optionLabel and optionValue, why would Autocomplete work the same way?
