### ISSUE TITLE
Editor: Add modules props for editor component

### ISSUE THREAD

**Issue by KbMstafa** [primefaces/primevue#3551]
### Describe the feature you would like to see added

Using editor, i believe it's easier to pass toolbar as array of controls rather than pass the buttons in slot
 for example `modules: { toolbar: ['bold', 'italic', 'underline'] }`
 
 i believe this feature is added in version 3, but i hope you have a plan to add it to version 2

**Comment by kamerat** [comment]
I too find this not too straight forward as I'd hoped it to be.
When you provide toolbar as modules, the default toolbar from prime is still present but looks like it's missing it's style:

![Image](https://github.com/user-attachments/assets/d42bda4a-a53a-48b3-974f-6e96c9623dc0)

So to remove it, you have to either find and create all the toolbar modules via the toolbar slot, or a workaround I've just noticed: simply adding a non breaking space in the toolbar slot to cancel the default slot;

```html
  <Editor
      v-model="section.content"
      :modules="editorModules"
      :pt="{
          content: '!h-[300px]'
      }"
  >
      <template #toolbar>
          &nbsp;
      </template>
  </Editor>
```
```ts
import type { QuillOptions } from 'quill'

const editorModules:QuillOptions['modules'] = {
    toolbar: [
        [{ 'header': [ 2, 3, 4, 5, 6, false] }],
        ['bold', 'italic', 'underline', 'strike'],
        [{ 'list': 'ordered'}, { 'list': 'bullet' }, { 'list': 'check' }],
        [{ 'color': [] }, { 'background': [] }],
        ['link'],
        ['clean']
    ]
}
```

Doing that at least removes the default items (as we don't want it double up), but it still leaves an "empty" p-editor-toolbar div:

![Image](https://github.com/user-attachments/assets/12e53415-a38f-413a-8e86-c4d94c77a6da)

**Maybe it's possible to remove the slot if user provides toolbar option in modules?**
