### ISSUE TITLE
ZIndexUtils: Dropdown inside Dialog doesn't work

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#3554]
### Describe the bug

Bug: Dropdown panel is placed behing dialog.

### Reproducer

https://stackblitz.com/edit/vue-t2a2kw?file=src/App.vue

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

See reproduction.

### Expected behavior

ZIndexes are managed automatically to make sure layering of overlay components work seamlessly when combining multiple components.

**Comment by rubjo** [comment]
https://user-images.githubusercontent.com/42270947/213120892-15ed87ca-42ef-47ea-aff2-c38a2c5a85e3.mov

**Comment by rubjo** [comment]
FYI, bug seems to be introduced with 3.22.3. In 3.22.2, this works.

**Comment by LMarcinkowski** [comment]
I can confirm this. 3.22.3 not working. 3.22.2 works.

**Comment by mertsincan** [comment]
Thanks a lot for your report! Fixed now.
