### ISSUE TITLE
Ripple: The ripple effect of components does not appear as expected

### ISSUE THREAD

**Issue by Kicshikxo** [primefaces/primevue#3555]
### Describe the bug

In new versions of PrimeVue ripple effect appears in a different way than expected.
Whereas in previous versions it appeared smoothly, now it does so abruptly.
Examples from the reproduction link and from the official site (with v3.22.1):

https://user-images.githubusercontent.com/41877938/213286141-23632445-fafe-4d2d-b4d3-afb8fec26dd2.mp4

https://user-images.githubusercontent.com/41877938/213286184-f11f9f40-ed5c-4243-8dd5-716dbf976e59.mp4

### Reproducer

https://codesandbox.io/s/jolly-cerf-frybzj

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Just create any component with ripple effect and periodically click on it

### Expected behavior

The expected behavior appears in version 3.12.4 (supplied in the reproduction template - https://codesandbox.io/s/primevue-3-issue-template-ip3vm)
Expected behavior from the link - https://codesandbox.io/s/runtime-feather-5mdwck:

https://user-images.githubusercontent.com/41877938/213287339-2ab5d6fa-dc51-40dc-b9f7-a58d2945e8ba.mp4

https://user-images.githubusercontent.com/41877938/213289447-685ad2a9-e2ba-4fa4-b2e9-67f036aa0fd2.mp4

**Comment by tugcekucukoglu** [comment]
Thanks for your attention. The team has decided to use Ripple in this way. And it affects all Prime libraries. For now, closing.
