### ISSUE TITLE
DataTable: Default value if field is empty

### ISSUE THREAD

**Issue by oliverbj** [primefaces/primevue#3559]
### Describe the feature you would like to see added

I have a simple datatable with PrimeVue, where I can add columns like below:

```javascript
<Column field="destination" header="Destination"></Column>
```

This will render a column with the field `destination` for that specific row. However, in some cases, the `destination` will be null. I am looking for an easy way to define a default value - without using templating like below.

```javascript
<Column field="destination" header="Destination" :sortable="true">
   <template #body="slotProps">
      {{ slotProps.data.destination ?? 'N/A' }}
   </template>
</Column>
```

The reason why I don't want to use the template and slotProps is simply because I have a very large datatable with +50 columns, and this just looks messy.

### Is your feature request related to a problem?

Only semantics and developer experience.

### Describe the solution you'd like

See above.

### Describe alternatives you have considered

Using the template props.

**Comment by tugcekucukoglu** [comment]
On our end, checking whether the data is null or not and/or adding new props creates performance issues. In this case, using templating could be a better approach.
