### ISSUE TITLE
PanelMenu header action color update

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#3561]
This example belongs to the Avalon

Before Accessibility
![Screen Shot 2023-01-19 at 15 09 04](https://user-images.githubusercontent.com/32294991/213439791-f74b1383-ebdc-4211-a9ad-14bac308d234.png)

After Accessibility
![Screen Shot 2023-01-19 at 15 09 13](https://user-images.githubusercontent.com/32294991/213439820-9418df99-265f-4836-86d9-d7b7adf301b9.png)

**Comment by jamesli2021** [comment]
Not from the team, I'm not sure what are the problems you spotted?
