### ISSUE TITLE
Dialog / Calendar z-index problem

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue#3562]
### Describe the bug

The calendar pops under the dialog.

There is a workaround, see https://github.com/primefaces/primevue/issues/3199#issuecomment-1313465050 but it would be nice if it worked out-of-the box.

### Reproducer

https://codesandbox.io/s/angry-swirles-km36m6?file=/src/App.vue

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

Go to the example, click in the input

### Expected behavior

Expected to see the datepicker in full.

**Comment by MoMack20** [comment]
I am seeing this same z-index issue using any component that has a dropdown type of effect when on a dialog.

I forked your sandbox to show this behavior is also exhibited for dropdown and multiselect component as well
https://codesandbox.io/s/musing-sid-con4ko?file=/src/App.vue

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/3554

**Comment by Jogai** [comment]
Sorry I didn't see that

**Comment by rlopezb** [comment]
Same problem with multiselect -> Vue 3.4.15 + Nuxt 3.9.3 + PrimeVUE 3.46.0

**Comment by rlopezb** [comment]
Same problem with multiselect and password strength panel (vue 3.4.15, nuxt 3.9.3, primevue 3.46)
