### ISSUE TITLE
DataTable: can`t remove footer in exporting csv file

### ISSUE THREAD

**Issue by Antontsyk** [primefaces/primevue#3563]
### Describe the bug

How I can export CSV file (method - $refs.dt.exportCSV()) without footer?

### Reproducer

https://www.primefaces.org/primevue/datatable/export

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
