### ISSUE TITLE
Menu / Datatable overlap issue

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue#3564]
### Describe the bug

When using frozen headers in the datatable with a menu above it, the menu drops under the frozen row. (example is using correct primevue version but not vite. But I have the problem when building with vite)

### Reproducer

https://codesandbox.io/s/recursing-ardinghelli-qotv5g?file=/src/App.vue

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

Go to example, click one of the menu items

### Expected behavior

Expect the menu to be over every element of the datatable

**Comment by tugcekucukoglu** [comment]
Table tr and the panel of the menu have the same z-index by design. This can be easily overwritten. Please check https://codesandbox.io/s/modern-frost-z2jd6v?file=/src/App.vue:4726-4756

**Comment by Jogai** [comment]
Thanks!

And also for the 3.23 release with all the free themes :yum:
