### ISSUE TITLE
DataTable: Cannot copy text with right-click

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3565]
### Describe the bug

There is no possibility to select text and copy it using right mouse click. It could be problematic with users that are not so familiars with computers.

### Reproducer

https://codesandbox.io/s/zen-bird-hrssoy

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Try to select some data in the table
2. Right mouse click
3. The selection goes off - cannot copy text using mouse.

### Expected behavior

Selection should not be removed to allow copying with mouse

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/2171
