### ISSUE TITLE
DataTable: Column sorting not working correctly when using custom header template

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3575]
### Describe the bug

As in title - one cannot sort the columns with custom slot when clicking on the text. Only icon works.

Possible solutions are to fix behavior or expose method to invoke sort in the slot.

### Reproducer

https://codesandbox.io/s/divine-dawn-roj712

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to reproduction example
2. Try to sort column with custom header template by clicking the text - not working
3. Try clicking the text in column without custom template - working

### Expected behavior

Consistent behavior - possibility to sort columns with custom header templates

**Comment by tugcekucukoglu** [comment]
Please try to use

```
<template #header>
      <span>
          .....
      </span>
</template>
```

div is a block line, span is an inline element and this affects the click event.

**Comment by Magiczne** [comment]
@tugcekucukoglu this issue shouldn't be closed, as your solution is not working.

https://codesandbox.io/s/sad-ellis-dr0pim
Either using div or span makes no difference here.

The column can be sorted if clicked below the text, but clicking directly the text, which is common will not sort it.
Look at `Image` columns which does not have custom header. clicking the text inside header still correctly sort the columns.
