### ISSUE TITLE
ContextMenu: Document Menu not working

### ISSUE THREAD

**Issue by louia** [primefaces/primevue#3577]
### Describe the bug

Hello,

When I try to use the ContextMenu component globally (with the prop "globally"), it does not work, the menu does not appear.

According to the documentation, it should work. https://www.primefaces.org/primevue/contextmenu 

On the codesandbox link, I placed an image and it works with it but not globally. But when I press the contextual key on my keyboard, the menu appears only once.

### Reproducer

https://codesandbox.io/s/bug-primevue-contextmenu-jli4n0

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 109.0.5414.75

### Steps to reproduce the behavior

1. Right click on image > it should work
2. Right Click on blank area > it sould work but it doesnt

1. Press the  context menu
2. Close the custom context menu
3. Press the context menu
4. The default context menu appear and not the custom one

### Expected behavior

Right click in the blank area should appear the menu

**Comment by tugcekucukoglu** [comment]
It was fixed with earlier version. Please try to use the latest version.
