### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by oliviermattei** [primefaces/primevue#3582]
### Describe the bug

Hello,
I formely had a look on the issue #2845 and if it's fixed, I have the same problem with the 3.22.4

```
error TS2322: Type '{ modelValue: MENU_OPENING_TYPE | undefined; options: MENU_OPENING_TYPE[]; placeholder: string; }' is not assignable to type 'ComponentProps<GlobalComponentConstructor>'.
Type '{ modelValue: MENU_OPENING_TYPE | undefined; options: MENU_OPENING_TYPE[]; placeholder: string; }' is missing the following properties from type 'DropdownProps': align, addEventListener, removeEventListener, accessKey, and 284 more.

32 <Dropdown
```

I would like to reopen the issue.

You need to run `npm run typecheck`

### Reproducer

https://codesandbox.io/s/snowy-brook-9cm4rq

### PrimeVue version

3.22.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome latest

**Comment by mertsincan** [comment]
Hi,

This issue has already been fixed in the next version.

Best Regards,
