### ISSUE TITLE
ColorPicker: Saturation and Value reset after change the Hue

### ISSUE THREAD

**Issue by davidglezz** [primefaces/primevue#3586]
### Describe the bug

https://user-images.githubusercontent.com/194784/214708923-629daa2f-c552-4289-8507-c3a4b55c4396.mov

Related https://github.com/primefaces/primevue/issues/2808

### Reproducer

https://www.primefaces.org/primevue/colorpicker

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/2808
