### ISSUE TITLE
Calendar: Disable year and month when set minDate or maxDate

### ISSUE THREAD

**Issue by king-ppap** [primefaces/primevue#3589]
### Describe the bug

I want it to be disabled the number button because when I use it to be a Month Picker or Year Picker users don't understand why they can not click the button or click it but the input doesn't change.
PR #3588

### Reproducer

https://codesandbox.io/s/reverent-butterfly-nytd5z?file=/src/App.vue

### PrimeVue version

3.22.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. User has to click select a month or year in Month Picker or Year Picker.
2. User cannot click select a month or year that was not in the range set with `minDate` or `maxDate` prop.

### Expected behavior

Prevent users to click the months and years number buttons when setting `minDate` or `maxDate`

**Comment by hifisultonauliya** [comment]
hi btw, how to use this feature in "primevue": "2.10.1" ?

**Comment by king-ppap** [comment]
> hi @king-ppap, can we have this feature in primevue v2 also?

@hifisultonauliya Sorry, I think you have to ask PrimeVue directly to do that for you 🤔
I'm just the one who passing by. 😅

**Comment by hifisultonauliya** [comment]
Hi @tugcekucukoglu 
can you add this bugs fix on privevue 2x also?
