### ISSUE TITLE
Cannot find module './components/column/Column'

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#36]
Hi Guys,

I am trying to start a new project with primevue but I encountered an issue with Column component.
When I compile typescript it says `Cannot find module './components/column/Column'` in `node_modules/primevue/column.d.ts:1:15`
Is that something wrong with my dependency setup or it is an issue with primevue itself?
Any other primevue components are fine. I am using target: `es5` and module `esNext`. PrimeVue version is `1.0.0-beta.7`.

Very appreciate.

**Comment by cagataycivici** [comment]
Dup of 29

**Comment by denis-pujdak-adm-it** [comment]
Thanks @cagataycivici . I have upgraded to beta 8 and the issue disappeared.
Very appreciate your help. 👍
