### ISSUE TITLE
Keyboard support: Numpad enter

### ISSUE THREAD

**Issue by bluetopp** [primefaces/primevue#3602]
### Describe the feature you would like to see added

Now there is possible to use the Enter key for various stuff like open a item in datatable etc.
But what about the nampad enter key?
I would like the numpad enter and the enter key to work in the same for the various components

**Comment by mariopries** [comment]
I believe this should be a standard for the tool. Because there are many people who are accustomed to using only the Enter key on the Numpad. This ends up causing some inconvenience in development, trying to find a makeshift solution to fix it, and not always ending up in the best way.

**Comment by pdame** [comment]
I agree, I think it is essential to be supported. Our end users are accustomed to using the number pad ENTER key the same ways as the primary ENTER key on a keyboard.
