### ISSUE TITLE
TieredMenu: Responsive issues

### ISSUE THREAD

**Issue by Ali-hd** [primefaces/primevue#3606]
### Describe the bug

I have placed the menu component at the right of my page. When you open a nested menu, the nested items are going out of the screen
![Screenshot 2023-01-29 104224](https://user-images.githubusercontent.com/55294514/215312547-a3a17be8-127c-4ccc-bf4c-524a9f9680c8.png)
 view.  

### Reproducer

https://codesandbox.io/s/muddy-cache-gfdk70?file=/src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

The same behavior on PrimeNG

**Comment by LanFeusT23** [comment]
I believe this used to work, I have the same problem but I don't recall having it a few months ago?

**Comment by tugcekucukoglu** [comment]
Overlay components responsiveness issues are on our roadmap.

Thanks for your report.
