### ISSUE TITLE
TieredMenu: Incorrect TieredMenu location when used for multiple items in the page 

### ISSUE THREAD

**Issue by Ali-hd** [primefaces/primevue#3607]
### Describe the bug

Say you have multiple buttons that toggle a Tiered menu on the same page, If you click the first button the menu appears below but if you click the second button the menu is still apearing below the first button and so on. It just gets stuck under the first button clicked. 

I have applied the same idea to Menu Component below and It works there, but didnt work with TieredMenu

*note: I have tested the same code in the Prime [PrimeVue 3 Issue Template](https://codesandbox.io/s/primevue-3-issue-template-ip3vm) below and saw that there is no bug. But In my app the bug is till there. So I made another reproducer using Vue Vite and tailwind which I have in my app, and you can check the bug there. 

### Reproducer

https://stackblitz.com/edit/vue3-tailwind-tmzs8y?file=src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Please check reproducer link
https://stackblitz.com/edit/vue3-tailwind-tmzs8y?file=src/App.vue

### Expected behavior

Expected to open a menu below each of the click buttons

**Comment by bahadirsofuoglu** [comment]
Hi, I think you should define a separate 'ref' for each menu. You are trying to access a component method. (toggle) But the first component's method is called for both components.

**Comment by Arriadnie** [comment]
Hi, I've got the same issue with tiered menu with primevue^3.27.0.
Not sure if define a separate 'ref' for each menu is good idea.
Is there any update on the issue?

**Comment by tugcekucukoglu** [comment]
TieredMenu examples call the 'toggle' method. When 'toggle2' method bind the one of the buttons, issue can resolve.
