### ISSUE TITLE
OrderList: When running in cypress tests the ref isn't created

### ISSUE THREAD

**Issue by Ancient-Dragon** [primefaces/primevue#3612]
### Describe the bug

When you run component tests in cypress with PrimeVue the order list throws an error and doesn't select properly. 

The issue is with the way ref is done / cypress works (so please say if I should go to cypress's team), essentially on the OrderList it calls the function: https://github.com/primefaces/primevue/blob/master/components/orderlist/OrderList.vue#L548 when in the browser, however this function isn't called when in cypress mode. 

I'm not sure of the use case of using a function to get the ref, or maybe it's because it's specifically gets the element which isn't available later if ref'd a different way. 

This was implemented in the 3.21.0 release by the looks of it for accessibility purposes. Not sure if functionality should break when something that is there for accessibility breaks. It might be worth adding some try / catch around some of these things. 

This works fine in a browser but ideally should work in cypress tests as well.

### Reproducer

TODO

### PrimeVue version

3.22.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Cypress Electron

### Steps to reproduce the behavior

Create an app which has a view which uses the order list and open create a cypress component test which clicks on an item in the order list.

### Expected behavior

The test should pass and the item should be selected in the component test

**Comment by tugcekucukoglu** [comment]
Please try to use with the latest version. If the problem still persists, please create a new with a reproducer link.
