### ISSUE TITLE
DataTable: Virtualscroller Height broken on Firefox

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3617]
### Describe the bug

Virtualscroller has incorrect height. Therefore the rows are not visible.
![image](https://user-images.githubusercontent.com/8471027/216296657-4f368f05-5b91-47c5-a103-60fd99b0a172.png)

Only happens when there is a horizontal scrollbar.
Only reproducable on Windows systems in Firefox Browser.

### Reproducer

https://codesandbox.io/s/modest-hofstadter-x44zuz?file=/src/DataTableDemo.vue

### PrimeVue version

3.22.4

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Firefox on Windows

### Steps to reproduce the behavior

1. Be on a Windows System
2. Open a Firefox Browser
3. Go to Reproducer

**Comment by tugcekucukoglu** [comment]
Please try to use the upcoming version 3.24.0. If the problem still persists, please reopen this same issue.
