### ISSUE TITLE
InputMask number repeat

### ISSUE THREAD

**Issue by 2019wei** [primefaces/primevue#3623]
### Describe the bug

hi, I entered number (keyboard number pad) and number repeated 2 times in chinese (Tradtional Taiwan) Microsoft Bopomofo , 
![messageImage_1675477559616](https://user-images.githubusercontent.com/46859361/216772995-5991ab3a-9bbf-4a0d-a73d-b7f94b797d20.jpg)

https://user-images.githubusercontent.com/46859361/216772968-eec90f67-763c-4b9e-b899-63114ef92414.mp4

### Reproducer

https://codesandbox.io/s/angry-dream-xn0noy?file=/src/App.vue

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by a20246** [comment]
I also have the same issue, but it only occurs on the numeric keypad. 
If I use the number row above the keyboard, there is no problem.
