### ISSUE TITLE
Calendar: manuelInput does not work

### ISSUE THREAD

**Issue by carstenmetzler** [primefaces/primevue#3624]
### Describe the bug

Since version 3.22.0 and also in 3.23.0 the manual input of dates is not possible. It only works for time fields. 

### Reproducer

https://primevue.org/calendar

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by bordermedia** [comment]
Same.  Needed to go back to 3.21.0 for manual input to work.

**Comment by lalmat** [comment]
Same here too... It was an old 2021 bug.

**Comment by aliehsdev** [comment]
@tugcekucukoglu The problem was created in issue #3452. You need to return check `!this.preventFocus`.

**Comment by cricketthomas** [comment]
any update on this?

**Comment by aliehsdev** [comment]
It is strange that such important functionality as entering the date in the calendar has not yet been restored. You need to check your demos and the official website that use the latest PrimeVue components and you will find that entering the date anywhere in the calendar view does not work. I can't update PrimeVue components in my projects as the ability to enter a date is an important part of user input.

**Comment by bordermedia** [comment]
> It is strange that such important functionality as entering the date in the calendar has not yet been restored. You need to check your demos and the official website that use the latest PrimeVue components and you will find that entering the date anywhere in the calendar view does not work. I can't update PrimeVue components in my projects as the ability to enter a date is an important part of user input.

Yep, same.  Still stuck on 3.21.0 until this gets fixed.

**Comment by eytienne87** [comment]
I am disappointed in this calendar input it is very complicated for no reason

**Comment by rwparris2** [comment]
we have monkey patched this component to make it work

this hasn't been super-vetted, it may have other unintended consequences

```html
<Calendar
  ref="calendarComponentRef"
  ...
/>
```

```typescript
/**
 * Prevent PrimeVue's Calendar component from stealing focus from its own
 * input, preventing users from manually entering dates
 *
 * see https://github.com/primefaces/primevue/issues/3624
 */
const fixCalendarFocusTrap = () => {
  const componentExists = !!calendarComponentRef.value;
  if (!componentExists) return;

  const alreadyMonkeyPatched =
    !!calendarComponentRef.value.originalUpdateFocusFunc;
  if (alreadyMonkeyPatched) return;

  calendarComponentRef.value.originalUpdateFocusFunc =
    calendarComponentRef.value.updateFocus;

  calendarComponentRef.value.updateFocus = () => {
    const inputEl = calendarComponentRef.value.input;
    const inputElHasFocus = inputEl && inputEl == document.activeElement;
    if (!inputElHasFocus) {
      calendarComponentRef.value.originalUpdateFocusFunc();
    }
  };
};

watch(calendarComponentRef, () => fixCalendarFocusTrap(), {
  immediate: true,
});
```

**Comment by csmaller** [comment]
still in PR with merge conflicts

**Comment by aliehsdev** [comment]
> still in PR with merge conflicts

The causes of the problem have long been found, and the solution is very simple. MR with conflicts, because the code base has changed and the project developers ignore this issue, despite the fact that they themselves created this bug.

**Comment by knadich** [comment]
> ```ts
> /**
>  * Prevent PrimeVue's Calendar component from stealing focus from its own
>  * input, preventing users from manually entering dates
>  *
>  * see https://github.com/primefaces/primevue/issues/3624
>  */
> const fixCalendarFocusTrap = () => {
>   const componentExists = !!calendarComponentRef.value;
>   if (!componentExists) return;
> 
>   const alreadyMonkeyPatched =
>     !!calendarComponentRef.value.originalUpdateFocusFunc;
>   if (alreadyMonkeyPatched) return;
> 
>   calendarComponentRef.value.originalUpdateFocusFunc =
>     calendarComponentRef.value.updateFocus;
> 
>   calendarComponentRef.value.updateFocus = () => {
>     const inputEl = calendarComponentRef.value.input;
>     const inputElHasFocus = inputEl && inputEl == document.activeElement;
>     if (!inputElHasFocus) {
>       calendarComponentRef.value.originalUpdateFocusFunc();
>     }
>   };
> };
> 
> watch(calendarComponentRef, () => fixCalendarFocusTrap(), {
>   immediate: true,
> });
> ```

Hello,
Can I see more about your solution please ? 
Thanks

**Comment by carstenmetzler** [comment]
Are there any updates? It still not works in 3.30.2. I stick to version 3.21.0 because of this bug.

**Comment by dmhendricks** [comment]
Users kept complaining, so I did what @argentines recommended plus added these two fixes:
- 404a238e9e4b8b69f2bb5cdf627d42dd773e1c44
- d68ff23fa99160f13bef99aed0efa9a1e4cc9a4d

I also had to add `/* falls through */` to various case statements because JSLint was complaining about the lack of breaks in case statements. It worked. I'm able to use this custom Calendar component in conjunction with the latest version of PrimeVue (3.31.0 at the time of this post).

Here is my CalendarNew.vue component with the modified code: https://pastebin.com/TWyjvVuE

**Comment by dragomirweb** [comment]
+1 with 3.25.0

**Comment by omzy** [comment]
Issue still exists on latest version (3.32.2)

**Comment by RobbieLD** [comment]
Still broken in V3.34.1

**Comment by csmaller** [comment]
How the heck does this pass PR all the time as it's still broken. You guys need some QA over there

**Comment by cagataycivici** [comment]
Set to be fixed at 3.34.2. So many comments, we must fix it!

**Comment by bordermedia** [comment]
Not fixed, still not working in 3.34.1

**Comment by ilearnio** [comment]
It's still not fixed 3.35.0

**Comment by dmhendricks** [comment]
I'm not sure what to do now. It appears that my custom version https://github.com/primefaces/primevue/issues/3624#issuecomment-1670029816 doesn't work with 3.35.0. I am experiencing issue https://github.com/primefaces/primevue/pull/4451 now.

I tried adding the fix mentioned in the post:
https://github.com/primefaces/primevue/pull/4451/files

...but the AM/PM thing is still happening, which leads me to believe I'm missing some other changes along the way. Regardless, maintaining a compatible custom Calendar component has become undesireable.

I think my options are:
1. Stay at version 3.21.0 indefinitely, or
2. Stop using `manualInput` on the Calendar component, or
3. Use 24-hour format only (since the AM/PM bug only affects 12-hour format), which will allow me to continue using my crappy custom component

Options 1 & 3 aren't ideal for me, and users will complain about options 2 & 3. I suspect I'll have to go with option 2, but if anyone has additional ideas, please share. Thank you.

**Comment by D-Bastien** [comment]
For people who cannot upgrade their versions, here's another monkey patch. Not sure why it works with seemingly no breaks, but it's good enough for my needs. Use at your own risk.

```ts
import Calendar from 'primevue/calendar'

import {defineComponent} from 'vue'

export default defineComponent({
    extends: Calendar as any,
    methods: {
        updateFocus: () => {
            /* Prevents primevue's default behaviour. */
        }
    }
})
```

Just put this in a .ts or .js file & use this instead of the base component.

**Comment by NguyenNghia412** [comment]
> For people who cannot upgrade their versions, here's another naive fix. Not sure why it works with seemingly no breaks, but it's good enough for my needs. Use at your own risk.
> 
> ```ts
> import Calendar from 'primevue/calendar'
> 
> import {defineComponent} from 'vue'
> 
> export default defineComponent({
>     extends: Calendar as any,
>     methods: {
>         updateFocus: () => {
>             /* Prevents primevue's default behaviour. */
>         }
>     }
> })
> ```
> 
> Just put this in a .ts or .js file & use this instead of the base component.

Thank you. I'm using v3.29.1 and it works <3

**Comment by devmini1203** [comment]
The 3.52.0 version has the same error
