### ISSUE TITLE
Steps: text overflow

### ISSUE THREAD

**Issue by AniaKru95** [primefaces/primevue#3631]
### Describe the bug

In case of long labels, steps component goes beyond the frame.
It is clearly visible on mobile devices.

### Reproducer

https://codesandbox.io/s/intelligent-rosalind-et1byx?file=/src/StepsDemo.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Only one step should be visible on mobile devices.

**Comment by fairplex123** [comment]
::v-deep(.p-steps .p-steps-item:last-child .p-steps-number, .p-steps
    .p-steps-item:last-child
    .p-steps-title) {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 200px;
}

**Comment by AniaKru95** [comment]
Unfortunately, I does not work me.
