### ISSUE TITLE
Calendar: Issue with manual input when dateFormat="yy-mm-dd", manual entry of 1956-03-3" automatically updates the date value to "1956-03-03"

### ISSUE THREAD

**Issue by tforget** [primefaces/primevue#3635]
### Describe the bug

When dateFormat="yy-mm-dd", entering "1956-03-3" automatically updates the date value to "1956-03-03" making it impossible to enter "1956-03-30"

### Reproducer

https://codesandbox.io/s/suspicious-davinci-n8nzou

### PrimeVue version

2.10.0

### Vue version

2.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

enter "1956-03-3" in the calendar textinput

The date changes automatically to 1956-03-03

### Expected behavior

1956-03-30 can be entered manually without the date changing automatically to 1956-03-03

**Comment by tugcekucukoglu** [comment]
With the latest PrimeVue 2 version, Calendar core side has some changes and behaves differently from the codesandbox demo that you've sent. In that version Calendar does not add any zero but does not select the typed date because of date format is "yy-mm-dd".
