### ISSUE TITLE
Tree: Add focus event / props

### ISSUE THREAD

**Issue by xontik** [primefaces/primevue#3636]
### Describe the feature you would like to see added

When navigating in the tree, it's impossible for child templates to know when they are focused

### Is your feature request related to a problem?

I'd like to implement a behavior on my children nodes when they get the focus 

### Describe the solution you'd like

I think of 2 solutions :
- add a focused property on the child slot props
- add event on focus change wiht a ref to the new node focused

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
