### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by AniaKru95** [primefaces/primevue#3637]
### Describe the bug

Filter row does not display on mobile view.

Used options:
filterDisplay="row"
responsiveLayout="stack"

I place example in codesandbox.

### Reproducer

https://codesandbox.io/s/strange-payne-b0x63i?file=/src/DataTableDemo.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Show filters in mobile view.

**Comment by tugcekucukoglu** [comment]
DataTable responsive structure is deprecated. We suggestion to investigate this example https://primevue.org/datatable/#basic_filter
