### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by OybekMavlonov** [primefaces/primevue#3638]
### Describe the bug

Hi. Is it possible to give how many items in datatable pagination. In primevue pagination, we can give it with totalRecords, but in datatable pagination it gets size based on given value's length. Is it possible to give the pagination size like totalRecords ?

### Reproducer

https://codesandbox.io/s/immutable-river-ww0ygp?file=/src/App.vue

### PrimeVue version

3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Expected behavior

In my datatable, pagination size should be totalRecords size(224), but it does not work

**Comment by tugcekucukoglu** [comment]
Hi. DataTable also has `totalRecords` property and accepts number like Paginator `totalRecords`.
