### ISSUE TITLE
TotalRecords in datatable

### ISSUE THREAD

**Issue by OybekMavlonov** [primefaces/primevue#3639]
### Describe the bug

TotalRecords in datatable does not work

### Reproducer

https://codesandbox.io/s/immutable-river-ww0ygp?file=/src/App.vue

### PrimeVue version

3

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by GrosjeanEddy** [comment]
You must set the 'lazy' props to true if you want that the totalRecords be used instead of the value.length

**Comment by tugcekucukoglu** [comment]
Please check that example https://primevue.org/datatable/#lazy_load

**Comment by luichooy** [comment]
> Please check that example https://primevue.org/datatable/#lazy_load

The hash in this link no longer exists in v4. Is there a new link or somewhere in the document that emphasizes that TotalRecords must be used with lazy? I've searched for the FEATURES and API documentation and found none

**Comment by ernald06** [comment]
Using totalRecords property together with lazy will brake the filters property. This last one will not work at all since the DataTable "is lazy". Is there also a solution? Does anyone have any idea how to combine all this 3 property together without implementing the filters logic manually?
