### ISSUE TITLE
Scrollable Tabs

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#364]
Similar to PrimeFaces version;

https://www.primefaces.org/showcase/ui/panel/tabView.xhtml

**Comment by fairking** [comment]
I don't like this approach too much.  The scroll is not the easiest way to switch tabs. Especially on mobile devices..

I recommend to make a tab menu for any hidden tabs. Please look at the example bellow:

![image](https://user-images.githubusercontent.com/13495631/95243374-7a53b980-0808-11eb-9d4c-6244b5403b78.png)

Anyway, Thanks for the wonderful PrimeVue. 👍

**Comment by fairking** [comment]
Also I would consider to have a vertical TabView as well.

**Comment by tugcekucukoglu** [comment]
Related to [#1446 ](https://github.com/primefaces/primevue/issues/1446)
