### ISSUE TITLE
Password: incorrect ref to level in docs

### ISSUE THREAD

**Issue by tmlmt** [primefaces/primevue#3640]
### Describe the bug

In various places in the doc, e.g. in the [Password component doc](https://primevue.org/password) itself, or in the [Vuelidate](https://primevue.org/validation) page, it is made use of a reference to the named scoped props for the footer slot: 

```vue
<template #footer="sp">
    {{sp.level}}
    <Divider />
    // ...
</template>
```
`sp` is of type `PasswordProps` but `level` is not one of its property / it's not a prop. It's one of the properties of the `Password` component. One could eventually use a `ref` on the Component itself, but it's actually not needed, because the intention is to display the `meter` property of the component, which is already [part](https://github.com/primefaces/primevue/blob/master/components/password/Password.vue#L32-L35) of the `content` slot: 
```vue
<slot name="content">
    <div class="p-password-meter">
        <div :class="strengthClass" :style="{ width: meter ? meter.width : '' }"></div>
    </div>
    <div class="p-password-info">{{ infoText }}</div>
</slot>
```
Shouldn't the first snippet below be replaced simply by: 
```vue
<template #footer>
    <Divider />
    // ...
</template>
```
? 

I'd be happy to submit a PullRequest if you confirm that's correct. 

### Reproducer

https://primevue.org/password

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Firefox

### Steps to reproduce the behavior

Copy/paste example from the doc

**Comment by tugcekucukoglu** [comment]
Is this issue still valid? Could you please update the links as they have changed?

**Comment by tmlmt** [comment]
Things have indeed changed since I've posted this 8 months ago, so yeah, the issue is not obsolete. Closing.
