### ISSUE TITLE
DataTable: Lazy loading with multiple selection clears previous selection when clicking "select all"

### ISSUE THREAD

**Issue by xengulai** [primefaces/primevue#3641]
### Describe the bug

When using the "lazy" option for pagination and allowing multiple row selection, clicking the "select all" checkbox in the column header clears all previous selection and resets to only what's on the current page.

This is happening becuse the select all functionality is setting the selection to the currently processed data, which is only the current page when lazy.

### Reproducer

https://codesandbox.io/s/nostalgic-haslett-wfkhk9

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a page with a DataTable that lazy loads pagination and allows multiple row selection
2. Make some selection on a page
3. Go to another page and click the "select all" checkbox in the header column
4. See that all prior selection are cleared and only the current page is selected

### Expected behavior

Prior selections to be maintained.

**Comment by xengulai** [comment]
PR: https://github.com/primefaces/primevue/pull/3642 to solve the issue.

**Comment by tugcekucukoglu** [comment]
In lazy mode, the header checkbox selection can be customized with `selectAll` property and `select-all-change`. Please check the document https://primevue.org/datatable/#lazy_load
