### ISSUE TITLE
DataTable add new prop 'keyMetaSort'

### ISSUE THREAD

**Issue by pabloid64** [primefaces/primevue#3643]
### Describe the feature you would like to see added

Add a **metaKeySort** property that would work similar to **metaKeySelected** only for sorting in **sortMode = 'multiple'**

### Is your feature request related to a problem?

Without this property, it is not possible to use multiple sorting with the mouse only. If there is a problem with resetting the sort, then there is the **removableSort** flag.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
