### ISSUE TITLE
Discussion about hidden tabs

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#365]
https://github.com/primefaces/primevue/pull/358
Solution with "v-if"  is not the way becouse sometimes you need to use v-show becouse you dont want to regenerate html.

**Comment by cagataycivici** [comment]
How about we add a mode to the component e.g hideMode="invisible | none" where invisible used v-show and none uses v-if?

**Comment by Sellec** [comment]
> How about we add a mode to the component e.g hideMode="invisible | none" where invisible used v-show and none uses v-if?

looks interesting but this new mode needs to work with any visibility flag?

**Comment by cagataycivici** [comment]
Closing due to lack of demand from the community, once there is more interest. We'll reconsider adding the new flag.
