### ISSUE TITLE
DataTable with virtualscroll and single selection mode enabled. Uncaught TypeError: Cannot set properties of undefined (setting 'tabIndex')

### ISSUE THREAD

**Issue by vargen2** [primefaces/primevue#3650]
### Describe the bug

DataTable with virtualscroll and single selectionmode enabled. 

Scroll a bit then select a row and error will throw.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/8985927/218487154-44bf81e1-0844-4590-b781-451d9efbb821.png">

![image](https://user-images.githubusercontent.com/8985927/218487318-62fa8779-b19f-44c1-bd53-38010a10404a.png)

Versions used 3.22.4 and 3.23.0

### Reproducer

https://codesandbox.io/p/github/vargen2/primevue-bug-vscroll-select/main

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. DataTable with virtualscroll and single selection mode enabled. 
2. Scroll a bit 
3. Select/click a row, larger than (item 31) and error will throw.

**Comment by tugcekucukoglu** [comment]
The latest version 3.24.0 has major changes to DataTable. Please check https://github.com/primefaces/primevue/issues/3682

Also in this example, https://stackblitz.com/edit/angular-dkcbvp?file=src%2FApp.vue scrolling seems to work fine. If problem still persists, please create a new issue.
