### ISSUE TITLE
Tree: key event not passed to children

### ISSUE THREAD

**Issue by MassimoBev** [primefaces/primevue#3651]
### Describe the bug

I have added an InpuText field inside a Tree, but this is not editable because the Tree catch all the key events.

It worked with the previous Primevue version

### Reproducer

https://codesandbox.io/s/hidden-sun-9u8whl?file=/src/App.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox, Chrome

### Steps to reproduce the behavior

1) Expand the "Document" node
2) As a child there is an Input text
3) Try to write inside the input text

### Expected behavior

The InputText is writable

**Comment by DenizMOz** [comment]
Hi, I changed the version in the sandbox from 3.20.0 to 3.22.2 and it works. Updating to a newer version will fix the issue.
