### ISSUE TITLE
AccordionTab: name property

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3652]
### Describe the feature you would like to see added

I would like to have a unique identifier like a name or id property on the AccordionTab Component.
The identifier should be available in Accordion events, eg openTab.

### Is your feature request related to a problem?

I have an Accordion with multiple AccordionTabs.
The first AccordionTab has a v-if condition.
Depending on the condition the the first Tab is displayed or not.
Therefore the indexes of all the folloging tabs change.
If you want to refer to a specific tab, you dont have a fixed index to compare to anymore.
You always have to check if the first tab is displayed to know the correct index for the other tabs.

It would be simpler and more readable to check against the tab name instead of an index. 
Especially if the index can change.
Furthermore, if you add a new tab in between, currently you would have to change all the tab indexes in the code.

### Describe the solution you'd like

I would like to have a unique identifier - like a name or id property - on the AccordionTab Component.
The name should be available in Accordion events, eg openTab.

### Describe alternatives you have considered
I could identify the tabs by html id attributes.
The html of the tabs is created by the Accordion Component.
Therefore AccordionTab would need a property for the id. And Accordion.vue can then add the id to the html of the tab.

This alternative is easier to implement than a pure vue solution.

### Additional context
**requested code example:**
```html
<Accordion @tab-open="openTab">
   <AccordionTab v-if="firstTabVisible">...</AccordionTab>
   <AccordionTab name="twelveMonthTab">...</AccordionTab>
</Accordion>
```
```javascript
openTab(event) {
  if (event.tabname === "twelveMonthTab") {
    this.loading12Months = true;
    this.fetch12MonthOverview();
  }
},
```

**current code example:**
```html
<Accordion @tab-open="openTab">
   <AccordionTab v-if="firstTabVisible">...</AccordionTab>
   <AccordionTab>...</AccordionTab>
</Accordion>
```
```javascript
twelveMonthTabIndex() {
  if(this.firstTabVisible) return 3;
  return 2;
},
openTab(event) {
  if (event.index === this.twelveMonthTabIndex) {
    this.loading12Months = true;
    this.fetch12MonthOverview();
  }
},
```

**Comment by DenizMOz** [comment]
Hi, it sounds like what youre trying to achieve can be done using the ID attribute, and the getElementByID() function. 
Example: https://www.w3schools.com/html/html_id.asp

**Comment by Rakasch** [comment]
> Hi, it sounds like what youre trying to achieve can be done using the ID attribute, and the getElementByID() function. 

Yes, ids would work.
But the html of the tabs is created by the Accordion Component, so I can't specify an html id for the tabs.
AccordionTab would need a property for the id, which is added to the tab by the Accordion.vue.

**Comment by Rakasch** [comment]
I have found that you can use headerProps to set the id. 
No idea if it is intended to use it this way, but it works.
```
<AccordionTab :headerProps="{ id: 'twelveMonthTab' }">
```

```
function openTab(event) {
  const target = event.originalEvent.target;
  const tab = target.closest(".p-accordion-header");
  if (tab.id === "twelveMonthTab") {
    ...
  }
}
```
