### ISSUE TITLE
Menubar.vue missing event emit on click item

### ISSUE THREAD

**Issue by yormy** [primefaces/primevue#3656]
### Describe the bug

The menubar does not contain an event that is fired when an item is clicked. 
I would like to handle the click event outside the component, but currently there is no way to determine what item has been clicked (with the proper data). 
Sure I can catch the @click, but then I do not have the actual data structure of the menu item which was clicked

### Reproducer

.

### PrimeVue version

3.23

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome

### Steps to reproduce the behavior

...

### Expected behavior

being able to do @item-clicked on the entire menu bar and get the data of the menuitem back

**Comment by tugcekucukoglu** [comment]
MenuModel API has a `command` property to handle this.

**Comment by yormy** [comment]
Do you have an example how to catch that in the calling component ?

**Comment by imad-mn** [comment]
I would like to have that functionality as well. I want to track when the menuitem changed so I can put the label as a page title.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by agardes** [comment]
For anyone wondering : 
```

const goTo = (page) => {
  // Function to fire when clicked
}

const items = ref([
  { label: 'Profile', icon: 'pi pi-user' , command:goTo('profile')}
])
```

**Comment by bellithyagaraj** [comment]
Was this ever implmented?

**Comment by agardes** [comment]
For those wondering :


```
const myFunction = () => {} 

const items = ref([
  { label: 'My files', icon: 'pi pi-file', command: myFunction }
])

```

**Comment by bellithyagaraj** [comment]
@agardes what if i have to call same function on click of every menu item? For example: I have 3 items and for all should i do this?
`const items = ref([
  { label: 'My files', icon: 'pi pi-file', command: myFunction },
{ label: 'My files'2, icon: 'pi pi-file', command: myFunction },
{ label: 'My files3', icon: 'pi pi-file', command: myFunction }
])`
