### ISSUE TITLE
Datatable icon filter doesn't disappear when filterDisplay is set to Row

### ISSUE THREAD

**Issue by IcyTempest** [primefaces/primevue#3657]
### Describe the bug

When the filterDisplay is set to row, even if showFilterMatchModes is set to false, the button doesn't disappear. This behaviour is fine when filterDisplay is set to menu, but not in row.

### Reproducer

https://codesandbox.io/s/fancy-resonance-2n3tg3?file=/src/App.vue

### PrimeVue version

3.4.2-SNAPSHOT

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. set filterDisplay="row" in Datatable
2. Insert Whatever TextField you would like in one of the column
3. set showFilterMatchModes="false"

### Expected behavior

Icon Filter in Row mode disappear when showFilterMatchModes is set to false

**Comment by tugcekucukoglu** [comment]
Cannot replicate with the latest PrimeVue version. For now, closing, if the problem persists, please let us know.
