### ISSUE TITLE
Component Name: Multiselect

### ISSUE THREAD

**Issue by fricke** [primefaces/primevue#3662]
### Describe the bug

Hello, In working w/ the Primevue version 2.10.1 code, noticed that there is an issue on the onClick handler in MultiSelect.vue complaining about missing "event" variable, which does not exist. I found found this writing a jest tests from our usage of this component in our company's application. 

 When digging deeper into the code I found that on this line:

https://github.com/primefaces/primevue/blob/f8ddfd10fb8355ca97e209421a5d288357b26fec/src/components/multiselect/MultiSelect.vue#L191

The error happens here:
`!this.$refs.overlay.contains(event.target))`
due to `event` not being defined. 

### Reproducer

https://codesandbox.io/s/primevue-2-issue-template-dw7jd7

### PrimeVue version

2.10.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

This was done through a JEST test and discovered there. It's clear the missing field is not in the scope of `onClick` method. causing a null pointer (in JS).

**Comment by fricke** [comment]
reporting bug and then going to put in a PR.

**Comment by tugcekucukoglu** [comment]
Thanks for your attention. Added for the next release.
