### ISSUE TITLE
Documentation: Subpage `validation` cannot be loaded directly

### ISSUE THREAD

**Issue by toddeTV** [primefaces/primevue#3663]
### Describe the bug

The documentation for the validation cannot be loaded directly via SSR, bc Nuxt will throw an error 500.  
Loading the documentation on another subpage first and then navigating to this subpage works.  
Address: https://primevue.org/validation

### Reproducer

https://primevue.org/validation

### PrimeVue version

x

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

all

### Steps to reproduce the behavior

Call the following documentation subpage directly: https://primevue.org/validation

### Expected behavior

Nuxt Error 500.

**Comment by bahadirsofuoglu** [comment]
Hi, We are working on the new showcase change. will be resolved with the new showcase. That's why I'm closing the issue. Thank you for your contributions
