### ISSUE TITLE
DataTable: currentPageReportTemplate is not visible

### ISSUE THREAD

**Issue by tonkolviktor** [primefaces/primevue#3665]
### Describe the bug

Hi,

first of all thanks for all the work!!

I'm unsure if this is a bug or if i'm missing some settings, but on this page: https://primevue.org/datatable/paginator
For the second table I cannot see the `currentPageReport`
![image](https://user-images.githubusercontent.com/4534324/219884446-9a984f66-e01b-4864-bdf4-88502d87370f.png)
although it's specified, even if it would not be at least the default should be there.
![image](https://user-images.githubusercontent.com/4534324/219884463-762277f0-1c49-4008-b1b5-5dc7e37191fb.png)
In the docs I cannot see any condition which would suggest that this is not available for responsive paginators.
![image](https://user-images.githubusercontent.com/4534324/219884475-3de502e4-d3a1-4ec2-bd82-3c0772ebdf1b.png)

I'm also happy if there would be a workaround on showing it somehow quickly!?

Thanks

### Reproducer

https://no_link.com

### PrimeVue version

any

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome

### Steps to reproduce the behavior

it's in your docs

### Expected behavior

that it works

**Comment by bahadirsofuoglu** [comment]
Hi. The second table is the responsive paginator example. A recent feature. If you make the page less than 960px using the dev tool, you can see the currentPageReport. You can use it as below.

`
:paginatorTemplate="{
                '640px': 'PrevPageLink CurrentPageReport NextPageLink',
                '960px': 'FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink',
                '1300px': 'FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink',
                default: 'FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink JumpToPageDropdown'
            }"
`
