### ISSUE TITLE
VirtualScroller: lazy mode breaks table height

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3668]
### Describe the bug

In primevue lazy examples the datatables value array is always initializd with an array of length of the total count of entries.
But only the remote source knows the total count of entries.
Therefore I init the array length asynchronous from the remote source.
This does not seem to work as expected.

### Reproducer

https://codesandbox.io/s/compassionate-saha-tj2g95?file=/src/DataTableDemo.vue

### PrimeVue version

3.22.4

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Please try to use the upcoming version 3.24.0. If the problem still persists, please reopen this same issue.
