### ISSUE TITLE
AutoComplete: Empty Message never displayed

### ISSUE THREAD

**Issue by ig-onoffice-de** [primefaces/primevue#3669]
### Describe the bug

I wanted to use the empty message property to tell the user about possible reasons why he was not able to find what he was looking for. 
But unfortunately, the empty Message is never displayed. I hoped for it to appear in the dropdown window if it does not contain any options. 
But the actual behaviour is: 
1. If I just type anything *invalid* the drop down just closes
2. If I type anything *invalid* and open the dropdown by click it does not open at all.

### Reproducer

https://codesandbox.io/s/condescending-voice-lyxcw1?file=/src/App.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Enter the Autocomplete 
2. Type e.g. `ff`
3. See how the Overlay disappears can not be opened

### Expected behavior

The overlay opens although there is no suggestion and shows the emptyMessage String.

**Comment by proalaa** [comment]
+1
