### ISSUE TITLE
Ability to activate PanelMenu item declaratively or programmatically

### ISSUE THREAD

**Issue by ilyavaiser** [primefaces/primevue#367]
I want to open PanelMenu programmatically or declaratively, through child properties

**Comment by cagataycivici** [comment]
We can add the same approach we did for Accordion.

**Comment by ilyavaiser** [comment]
Any news?

**Comment by maidzen** [comment]
I have the same use case, any updates?

**Comment by ilyavaiser** [comment]
Hello!

**Comment by joniavila** [comment]
same issue , i cant change the activeItem from the PanelMenu programmatically. Any help?

**Comment by ilyavaiser** [comment]
Is anybody home?

**Comment by ilyavaiser** [comment]
Any news?

**Comment by cagataycivici** [comment]
Scheduled for 2.4.0 and 3.3.0.

**Comment by cagataycivici** [comment]
It first needs to be implemented for 3.x and then we'll port it back.

**Comment by west-farmer** [comment]
Any news about this feature?

**Comment by mertsincan** [comment]
I think this is better suited to the approach within Tree or TreeSelect. OR we can add _expanded_ option to MenuModel API for it. WDYT? @cagataycivici @everyone

**Comment by cagataycivici** [comment]
Something like expandedKeys with v-model sounds good to me.

**Comment by mertsincan** [comment]
Yes, +1 for expandedKeys attribute like in Tree ;)

**Comment by cagataycivici** [comment]
Ok, I'll go ahead and do it.
