### ISSUE TITLE
pages/datatable/Crud.vue: Class Name Typos

### ISSUE THREAD

**Issue by maxnth** [primefaces/primevue#3673]
### Describe the bug

The documentation for the CRUD implementation features a typo (`justiify-content-between` instead of `justify-content-between`) in the class name of some elements at the moment.
Fixed by #3672

### Reproducer

…

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Hi, We are working on the new showcase. will be resolved with the new showcase. That's why I'm closing the issue. thank you for your contributions
