### ISSUE TITLE
InputText inputClass attribute show incorrect warning on class style binding

### ISSUE THREAD

**Issue by IcyTempest** [primefaces/primevue#3674]
### Describe the bug

I need to access the InputText to customize the border color and such for validation. I can do that through the inputClass attribute of Calendar. Everything work well and all is fine. Until you inspect it and saw that inputClass doesn't accept anything that is related to Vue, class style binding with Array or object doesn't shut down the error, it accepts nothing but pure string in order for the error to not shown. Again, all is fine, it's just that it's giving false warning. 

### Reproducer

https://codesandbox.io/s/youthful-river-kgh9dm?file=/src/App.vue

### PrimeVue version

3.4.2-SNAPSHOT

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Give :inputClass any types of class style binding
2. Inspect the page
3. Make the condition valid or true and see the warning

### Expected behavior

Giving it any kinds of Class Style Binding shouldn't show up any warning.

**Comment by tugcekucukoglu** [comment]
This is an obvious defect. It is fixed for the next version. Please follow this ticket https://github.com/primefaces/primevue/issues/3707
