### ISSUE TITLE
DataTable: background-color cell column

### ISSUE THREAD

**Issue by ahellrigl** [primefaces/primevue#3676]
### Describe the bug

Good morning, I have a datatable where I need to paint the entire cell of the column through a condition.
For example: if the value is 1 paint green, else paint red.

I managed to do something similar but it doesn't paint the cell in the first row, it's weird.

![Captura de pantalla 2023-02-24 a la(s) 10 06 41](https://user-images.githubusercontent.com/51087271/221187024-f6347cc5-e1e7-436b-8313-8225181550fc.png)

### Reproducer

https://codesandbox.io/s/frosty-water-zxqkie?file=/src/App.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Hi!

Reaching column props seems easy in this case but might not be the best practice. 

`For example: if the value is 1 paint green, else paint red.`  What you mean `value`? Row index or cell value?

**Comment by ahellrigl** [comment]
Hello.
I mean the value of the cell, for example the total column.
If the total is <10 paint green, if the total is >= 10 paint red.
Paint the entire cell only of the total column.

Thank you!

**Comment by tugcekucukoglu** [comment]
`rowClass` is the best approach for this kind of styling and I made some changes to your codesandbox. You could check it here https://codesandbox.io/s/xenodochial-gianmarco-ub0clc?file=/src/App.vue

**Comment by ahellrigl** [comment]
Thanks, but I'm looking to just paint a cell, for the example you shared with me it would just paint the cell that contains 29 and 15.
The rowClass paints the entire row and I just want the cell.
