### ISSUE TITLE
ProgressBar: Global Loading Service

### ISSUE THREAD

**Issue by IvanSGurdian** [primefaces/primevue#3677]
### Describe the feature you would like to see added

I'm not sure if there's already an elegant way to do this; I'm looking to add a ProgressBar to my `main` component, and have something to trigger it when I need to show a loading happening.

Currently, I mostly use props, injects, emits, etc to update a ProgressBar that I have included on each `view` component.

### Is your feature request related to a problem?

I'm a bit frustrated having to include a ProgressBar or boolean property on every component I want to use it; relying on props or injects to update the state of the ProgressBar.

### Describe the solution you'd like

So my idea is building something similar to the `ToastService` or `ConfirmationService` that we have for `Toast` and `Dialog` which allows us to show these components globally instead of having to include them everywhere we want to display them.

We could have a `LoadingService`, which we can trigger from API call methods, usually I'd have something like:

```
getUsers() {
  this.loading = true;
  // get request here
  this.loading = false;
}
```

Instead we could call this global service to update the state of the progress bar to show/hide it, increment progress, etc.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
