### ISSUE TITLE
DataTable:re-order rows: can't reorder to last row when page is scrolled

### ISSUE THREAD

**Issue by garthmason** [primefaces/primevue#3680]
### Describe the bug

Same issue in the equivalent component for Prime React - see https://github.com/primefaces/primereact/issues/2703

This has been fixed in PrimeReact under PR https://github.com/primefaces/primereact/pull/2712, so I believe we can apply the same fix to PrimeVue

### Reproducer

https://www.primefaces.org/primereact/datatable/reorder/

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

When the browser is scrolled, you cannot reorder a row in the DataTable to the bottom row position - you can only drop between the 2nd last and last row - as described in https://github.com/primefaces/primereact/issues/2703

### Expected behavior

I should be able to reorder a row to the bottom of the table.

**Comment by garthmason** [comment]
Added related fix PR https://github.com/primefaces/primevue/pull/3681

**Comment by sthKrn** [comment]
The issue still persists when there is a window scrollbar.

https://stackblitz.com/edit/mptwzp-lxn9kf?file=src%2Fstyle.css,src%2Fservice%2FProductService.js,src%2FApp.vue
