### ISSUE TITLE
DataTable CSS and responsive structure improvements

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#3682]
Details;
https://github.com/primefaces/primeng/issues/12047

Breaking changes are;

- **responsiveLayout** is now defaults to scroll. The 'stack' mode is deprecated. 
- **scrollDirection** is now obselete
- **autoLayout** is obselete as table is based on auto layout now, tableStyle="table-layout:fixed" can be used for fixed.

**Comment by Sko007** [comment]
Please add this feature

**Comment by VictorKrasnov** [comment]
You can just close the project to make your life easier. And I will have to look for another product.
