### ISSUE TITLE
Calendar: Not accepting manual input

### ISSUE THREAD

**Issue by miriamstreit** [primefaces/primevue#3687]
### Describe the bug

I have the requirement to provide a date input field which accepts both inputs from the calender overlay and from manual inputs. However, since I last updated my dependencies from Primevue 3.16.2 to 3.23.0, the calendar input field won't accept manual inputs anymore. I have checked multiple browsers and it does not seem to work in my own app, in the code sandbox or in the [Primevue Documentation](https://primevue.org/calendar).

I did some digging in my own app using the Vue.js DevTools in my browser and it seems that the `focused` attribute of the Calendar component itself is causing this issue. It's always set to false when I click on the field, and when I changed it manually using the DevTools, the manual input was possible.

### Reproducer

https://codesandbox.io/s/primevue-calendar-demo-yet6dv

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Brave 1.48, Chrome 110, Safari 14

### Steps to reproduce the behavior

1. go to the code sandbox / the Primevue documentation
2. click on the Calendar input field
3. attempt to manually input a date

### Expected behavior

The input field should accept my manual input as well as inputs through the calender overlay.

**Comment by tugcekucukoglu** [comment]
Please follow this ticket https://github.com/primefaces/primevue/issues/3624
