### ISSUE TITLE
DataTable: Add Indeterminate support to header checkbox

### ISSUE THREAD

**Issue by sean-dickinson** [primefaces/primevue#3688]
### Describe the feature you would like to see added

When the checkbox selection mode is used, the "check all" checkbox in the <th> doesn't support an indeterminate state. This is a bit strange considering the TreeTable does support this state. Looking at the source code, this issue is likely due to the fact that the `Checkbox` component itself doesn't support this state. In the TreeTable it's actually implemented separately. 

### Describe the solution you'd like

Ideally the treetable and datatable should align on an implementation for an indeterminate state. This could take the form of adding this state to the regular checkbox component, or implementing #2652 and internally using the TriStateCheckbox in both components, or moving the non-checkbox component code to a new component from the TreeTable selection so it can be shared.

I'd happily open a PR to work on any of these solutions if any of them sound like the right choice.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by dixhuit** [comment]
Any update on progress here since this request was moved to the "internal project management backlog"?

**Comment by AcidRaZor** [comment]
I would like some feedback as well @tugcekucukoglu We're looking to move to Vue 3, away from Buefy and really enjoy the agnostic approach and accessibility support. One big kicker here is indeterminate checkbox on the DataTable selection. We would ideally want to run base-code and not have to modify ourselves.
