### ISSUE TITLE
DataTable: cannot uncheck when click the checkbox in column

### ISSUE THREAD

**Issue by cn2156** [primefaces/primevue#3691]
### Describe the bug

restore checkbox stop propagation in datatable checkbox from version 3.20

In version 3.21, if  set selectionMode in <Datatable>, and checkbox select column, then the checkbox in column not checked currectly:
can not uncheck when click the checkbox in column

https://primevue.org/datatable/selection

With the example in document, add `selectionMode="multiple"` in `<DataTable>`

`<DataTable :value="products" v-model:selection="selectedProducts3" selectionMode="multiple" dataKey="id" responsiveLayout="scroll" >
    <Column selectionMode="multiple" headerStyle="width: 3em"></Column>
    <Column field="code" header="Code"></Column>
    <Column field="name" header="Name"></Column>
    <Column field="category" header="Category"></Column>
    <Column field="quantity" header="Quantity"></Column>
</DataTable>`

### Reproducer

https://codesandbox.io/s/datatable-checkbox-error-upnwwc

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

1. checked two rows by click the checkbox in column
2. click the first checked row to uncheck, then: the first checked row is still checked in step 1, the second checked row in step 1 is unchecked

### Expected behavior

the first checked row will unchecked, and the second checked row will still checked, such as in version 3.20

**Comment by mertsincan** [comment]
Hi,

There are already multiple selections in checkbox mode. So, you need to remove selectionMode="multiple" from DataTable component.

Best Regards,

**Comment by cn2156** [comment]
In a DataTable, can convenient select the row through click the row.
If need select more rows, check multiple checkbox.

Otherwise, stop propagation when click the checkbox is logical.

**Comment by cn2156** [comment]
before version 3.21, stop propagation is used, why remove it?

**Comment by mertsincan** [comment]
You're right! I think stopPropagation should always be the last solution. So I made some changes. Fixed now. Thanks a lot for your update!

**Comment by cn2156** [comment]
OK
