### ISSUE TITLE
AutoComplete: empty-search-message vanishes quickly

### ISSUE THREAD

**Issue by Michael2109** [primefaces/primevue#3693]
### Describe the bug

The `empty-search-message` is displayed for a very short amount of time before disappearing. This should be visible long enough for the user to see or stay displayed until the user changes their search or the AutoComplete loses focus. 

I would also expect typing and getting no results in all cases to show the `empty-search-message`. 

### Reproducer

https://primevue.org/autocomplete

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

On the `Basic` AutoComplete start typing a matching entry. E.g. "United". After adding a different character it will briefly show the empty search message value. 

Also typing and getting no results doesn't show any message. 

### Expected behavior

The `empty-search-message` value should display when a value is entered that has gotten no results back from the search.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3669
