### ISSUE TITLE
Chips component doesn't work on mobile

### ISSUE THREAD

**Issue by macingili** [primefaces/primevue#3694]
### Describe the bug

chips component doesn't work on mobile.When enter is pressed, it moves to the next field

### Reproducer

https://primevue.org/chips

### PrimeVue version

3.23.0 

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Android

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by FVolral** [comment]
I confirm, that on iOS, using Enter key or Separator works. but on Android, the keyboard layout doesn't provide any 'Enter' key and nothing happens when touch ',' separator.

**Comment by Lukasss93** [comment]
Same issue on my android

**Comment by Lukasss93** [comment]
How to fix the issue:
https://clark.engineering/input-on-android-229-unidentified-1d92105b9a04

**Comment by MarcelGeo** [comment]
same issue

**Comment by MarcelGeo** [comment]
I think separator is also not working on mobile 

![Screenshot_2024-03-04-19-24-18-581_com android chrome](https://github.com/primefaces/primevue/assets/12643115/98528832-e6ca-4d6a-954b-6fd86172877a)

**Comment by Lukasss93** [comment]
How I (temporarily) solved this problem in my project:

### Caused in
Chrome for Android (only)

### Problem and solution
https://clark.engineering/input-on-android-229-unidentified-1d92105b9a04

### Why don't you use another browser?
Because I'm using this library in a MiniApp for Telegram.
Telegram uses Android's default webview (Chrome) and I can't force every user to switch webview (if it's possible).

### Temporary fix in my project:
```vue
<Chips v-model="tags"
    :ptOptions="{ mergeProps: true }"
    :pt="{input: { id: 'chipper'}}"
    separator=" "/>

<script setup>
import Chips from 'primevue/chips';
//import script from https://clark.engineering/input-on-android-229-unidentified-1d92105b9a04
import * as K from '@/Support/Utils'; 

let tags = ref([]);
let canDeleteChip = 0;
let recentDelete = false;

const handleEvent = (element, e: K.CompatibleInputEvent) => {
    element.value = element.value.trim();

    if(e.inputType !== 'deleteContentBackward'){
        canDeleteChip = 0;
        recentDelete = false;
    } else if(element.value === '' && !recentDelete){
        canDeleteChip++;
    }

    if(e.data === ' ' || e.data === 'Enter'){
        if(tags.value.includes(element.value)){
            return;
        }
        tags.value = [...tags.value, element.value.trim()];
        element.value = '';
        canDeleteChip = 1;
        recentDelete = false;
    } else if(e.inputType === 'deleteContentBackward' && element.value === '' && canDeleteChip===2 && tags.value.length > 0){
        tags.value = tags.value.slice(0, -1);
        element.value = '';
        recentDelete = true;
    }
};

onMounted(() => {
    document.getElementById('chipper')?.addEventListener('keydown', (event) => {
        const e = K.normalizeInputEvent(event);

        if (!K.IS_INPUT_SUPPORTED || event.key.length > 1) {
            handleEvent(event.target, e);
        }
    }, false);

    document.getElementById('chipper')?.addEventListener('input', (event:InputEvent) => {
        if (K.IS_INPUT_SUPPORTED) {
            handleEvent(event.target, K.normalizeInputEvent(event));
        }
    }, false);
});
</script>
```

**Comment by MarcelGeo** [comment]
Very sad, that browsers having such differences.

**Comment by Lukasss93** [comment]
Any news about this fix? 😊
_I wrote the solution in my previous message_

**Comment by tronco99** [comment]
The workaround is okay, but do we happen to know if they want to solve this issue?

**Comment by tugcekucukoglu** [comment]
Chips component is deprecated. Please use AutoComplete with typeahead mode.

**Comment by Lukasss93** [comment]
This problem persists even with the `AutoComplete` component.
https://github.com/user-attachments/assets/0ccb2b82-a020-4946-ac4e-a6bf053dfbf0

**Comment by muhdammar** [comment]
why close this issue. is still have bugs right

**Comment by OliverRC** [comment]
@tugcekucukoglu why was this closed. This issue still exists. Even though there are work arounds I think the default behaviour should be corrected so it works on all devices.

Edit: This issue still exists on the the Autocomplete component, however I found a work around to hint to the mobile keyboards to allow Enter key as opposed to the Next key.

You can add the following to the Autocomplete component `:pt="{ input: { enterkeyhint: 'enter' } }"`

```vue
<AutoComplete  :pt="{ input: { enterkeyhint: 'enter' } }"/>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/enterkeyhint
