### ISSUE TITLE
Removed TypeScript types

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#3696]
AutoComplete
- AutoCompleteFieldType
- AutoCompleteOptionLabelType
- AutoCompleteOptionDisabledType
- AutoCompleteOptionChildrenType
- AutoCompleteDropdownMode
- AutoCompleteAppendTo

Avatar
- AvatarSizeType
- AvatarShapeType

Badge
- BadgeSeverityType
- BadgeSizeType

Button
- ButtonIconPosType

Calendar
- CalendarValueType
- CalendarSlotDateType
- CalendarSelectionModeType
- CalendarViewType
- CalendarHourFormatType
- CalendarAppendToType

Carousel
- CarouselOrientationType

CascadeSelect
- CascadeSelectOptionLabelType
- CascadeSelectOptionValueType
- CascadeSelectOptionDisabledType
- CascadeSelectOptionChildrenType
- CascadeSelectAppendToType

ColorPicker
- ColorPickerFormatType
- ColorPickerAppendToType

Column
- ColumnFieldType
- ColumnSelectionModeType
- ColumnAlignFrozenType

ColumnGroup
- ColumnGroupType

ContextMenu
- ContextMenuAppendTo

DataTable
- DataTablePaginatorPositionType
- DataTableSortFieldType
- DataTableDataKeyType
- DataTableMultiSortMetaType
- DataTableSortOrderType
- DataTableSortModeType
- DataTableFilterMatchModeType
- DataTableFilterDisplayType
- DataTableSelectionModeType
- DataTableCompareSelectionBy
- DataTableColumnResizeModeType
- DataTableRowGroupModeType
- DataTableStateStorageType
- DataTableEditModeType
- DataTableScrollDirectionType
- DataTableScrollHeightType
- DataTableResponsiveLayoutType

Dialog
- DialogPositionType
- DialogAppendToType

Divider
- DividerHorizontalAlignType
- DividerVerticalAlignType
- DividerAlignType
- DividerLayoutType
- DividerType

Dock
- DockPositionType
- DockTooltipEventType

Dropdown
- DropdownOptionLabelType
- DropdownOptionValueType
- DropdownOptionDisabledType
- DropdownOptionChildrenType
- DropdownFilterMatchModeType
- DropdownAppendToType

DynamicDialog
- DynamicDialogCloseType

FileUpload
- FileUploadModeType

Galleria
- GalleriaThumbnailsPositionType
- GalleriaIndicatorsPositionType

InlineMessage
- InlineMessageSeverityType

InputNumber
- InputNumberButtonLayoutType
- InputNumberLocaleMatcherType
- InputNumberModeType

Listbox
- ListboxOptionLabelType
- ListboxOptionValueType
- ListboxOptionDisabledType
- ListboxOptionChildrenType
- ListboxFilterMatchModeType

MegaMenu
- MegaMenuOrientationType

Menu
- MenuAppendToType

MenuItem
- MenuItemLabelType
- MenuItemDisabledType
- MenuItemVisibleType

Message
- MessageSeverityType

MultiSelect
- MultiSelectOptionLabelType
- MultiSelectOptionValueType
- MultiSelectOptionDisabledType
- MultiSelectOptionChildrenType
- MultiSelectFilterMatchModeType
- MultiSelectAppendToType
- MultiSelectDisplayType

OrganizationChart
- OrganizationChartSelectionModeType

OverlayPanel
- OverlayPanelAppendToType

Password
- PasswordAppendToType

ProgressBar
- ProgressBarModeType

ScrollTop
- ScrollTopTargetType

SelectButton
- SelectButtonOptionLabelType
- SelectButtonOptionValueType
- SelectButtonOptionDisabledType

Sidebar
- SidebarPositionType

Skeleton
- SkeletonShapeType
- SkeletonAnimationType

Slider
- SliderOrientationType

SpeedDial
- SpeedDialDirectionType
- SpeedDialType
- SpeedDialTooltipPositionType
- SpeedDialTooltipEventType

SplitButton
- SplitButtonAppendToType

Splitter
- SplitterLayoutType
- SplitterStateStorageType

Tag
- TagSeverityType

TieredMenu
- TieredMenuAppandToType

Timeline
- TimelineVerticalAlignType
- TimelineHorizontalAlignType
- TimelineAlignType
- TimelineLayoutType

Toast
- ToastPositionType
- ToastMessageSeverityType

ToggleButton
- ToggleButtonType

TreeSelect
- TreeSelectSelectionModeType
- TreeSelectAppendToType
- TreeSelectDisplayType

TreeTable
- TreeTablePaginatorPositionType
- TreeTableSortFieldType
- TreeTableMultiSortMetaType
- TreeTableSortOrderType
- TreeTableSortModeType
- TreeTableFilterMatchModeType
- TreeTableSelectionModeType
- TreeTableFilterModeType
- TreeTableColumnResizeModeType
- TreeTableScrollDirectionType
- TreeTableScrollHeightType
- TreeTableResponsiveLayoutType

VirtualScroller
- VirtualScrollerItemsType
- VirtualScrollerItemSizeType
- VirtualScrollerOrientationType
- VirtualScrollerToType

**Comment by DoubleJ-G** [comment]
Is there a reason all these types were removed? Not to mention that there doesn't seem to be any change log under https://github.com/primefaces/primevue/releases for 3.24.0 so this is a pretty easy thing to miss
