### ISSUE TITLE
DataTable with highlighting focus cell and arrow key navigation

### ISSUE THREAD

**Issue by chuyennk** [primefaces/primevue#370]
Just discover about this awesome Vue UI component libraries. This DataTable with cell editing ability is the best component compared to other libraries. Thanks a lot for your great works.

It would be perfect if it able to highlighting focus cell, allow users to navigate using arrow keys and enter to edit mode by press enter key. Hope these features will be available in next version. Thanks.

**Comment by fairking** [comment]
Currently you can use Tab to navigate through the cells.

**Comment by cagataycivici** [comment]
Sure, arrow key support should not be hard because we already hook-in tab key to navigate, will add it to our roadmap.

**Comment by chuyennk** [comment]
Wow! that enhancement was very fast. Thanks a lot.

**Comment by RalfWohner** [comment]
Hi there, I'm also/still interested in this feature.
Or, alternatively, an API to get and set the currently selected cell in cell edit mode, then it would be easy to write our own keyUp events.

Thanks!

**Comment by cagataycivici** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
