### ISSUE TITLE
DataTable: drag and drop reordering doesn't work on mobile devices

### ISSUE THREAD

**Issue by alexterenya** [primefaces/primevue#3700]
### Describe the bug

Reordering via drag and drop doesn't work on mobile devices. Can be reproduced in official documentation.

### Reproducer

https://primevue.org/datatable/reorder

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open attached link on mobile device in any browsers.

### Expected behavior

Reorder is possible via drag and drop as on Desktop version.

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate it. Could you please try it with the latest version? For now, closed. If the problem persists, please reopen this ticket or create a new one.

Best Regards,
