### ISSUE TITLE
DataTable: Skeleton component is not displaying when scrollable is true

### ISSUE THREAD

**Issue by nicolascvoodoo** [primefaces/primevue#3705]
### Describe the bug

When using a Skeleton component inside a column, the Skeleton component doesn't show up when we set `:scrollable=true` to the DataTable component

### Reproducer

https://codesandbox.io/s/inspiring-banzai-q8q52m?file=/src/DataTableDemo.vue

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Create a DataTable component
2. Insert a Skeleton component into a column content (you should see it)
3. add `scrollable=true` to the DataTable component

The Skeleton component isn't display anymore

### Expected behavior

The Skeleton component should be displayed whether the `scrollable` prop is true or not.

**Comment by tugcekucukoglu** [comment]
DataTable has new css structure https://github.com/primefaces/primevue/issues/3682

The new updated demo: https://codesandbox.io/s/inspiring-banzai-q8q52m?file=/src/DataTableDemo.vue
