### ISSUE TITLE
Overlay Panel: Wrong position when opens

### ISSUE THREAD

**Issue by martinszeltins** [primefaces/primevue#3706]
### Describe the bug

[primevue.org/overlaypanel](https://primevue.org/overlaypanel/)

When the popover component opens it is sometimes in the wrong position as can be seen from the screencast. When I click on the "Bamboo Watch" button the first time the popup opens too low.

https://user-images.githubusercontent.com/34019878/223940310-314393dc-7dcc-499f-a6ec-d1d3043443f6.mp4

### Reproducer

https://primevue.org/overlaypanel/

### PrimeVue version

3.24.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 110

**Comment by tugcekucukoglu** [comment]
Please track this ticket https://github.com/primefaces/primevue/issues/1579
