### ISSUE TITLE
DataTable: performance of row selection

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#3709]
### Describe the bug

In our application, the user sometimes needs to select a large amount of rows (>1000). Selecting for example 1000 rows in DataTable requires at least about 5 seconds to be finished. Based on experiences with other tables, this seemes to have some room for improvement.

### Reproducer

https://codesandbox.io/s/confident-turing-9sn1fo?file=/src/DataTableDemo.vue

### PrimeVue version

3.24.0 and prior

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox, Chrome, Edge

### Steps to reproduce the behavior

The given CodeSandbox example shows a DataTable with 1000 datasets and a selection via checkbox. To select all 1000 rows just toggle the header checkbox and count the seconds...

### Expected behavior

I would really expect, that 1000 rows could be selected in just 1 second.

**Comment by tugcekucukoglu** [comment]
For large data records, we recommend using lazy loading for better performance. It is not a good practice to load thousands of data to the client side. With lazy loading, data size does not matter for filtering, sorting, and selecting rows.
