### ISSUE TITLE
primefaces.org/primevue/setup - 404 Page Not Found

### ISSUE THREAD

**Issue by martinszeltins** [primefaces/primevue#3713]
### Describe the bug

Before the new website there was a link to the setup page but now it leads to a 404. There should be a redirect to the new installation page.

https://www.primefaces.org/primevue/setup

Screencast:

https://user-images.githubusercontent.com/34019878/224031236-773dad4a-3f40-4e96-bc39-e4747d1c73ca.mp4

### Reproducer

https://www.primefaces.org/primevue/setup

### PrimeVue version

3.24.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Setup link is changed. The new link is 'installation' https://primevue.org/installation

You could also check the https://primevue.org/configuration
