### ISSUE TITLE
Dropdown: Disabled option do not update label

### ISSUE THREAD

**Issue by paweljaworowski-sc** [primefaces/primevue#3715]
### Describe the bug

When have dropdown with option disabled - option label is not shown. Instead we still see the placeholder.

I think issue is in PrimeVue's `Dropdown.vue` file, where we have a method:
```
isValidOption(option) {
    return option && !(this.isOptionDisabled(option) || this.isOptionGroup(option));
}
```

This method is called in `findSelectedOptionIndex`, which is called in `label` computed. 

Since disabled option won't be valid option, then we won't find an index  and computed `label`
will return `this.placeholder` in return `selectedOptionIndex !== -1 ? this.getOptionLabel(this.visibleOptions[selectedOptionIndex]) : this.placeholder`. 

I'm able to workaround that with value slot, where for value i'm searching via options and show proper label.
### Reproducer

https://codesandbox.io/p/sandbox/fervent-wind-rzkgsw?file=%2Fsrc%2FApp.vue

### PrimeVue version

3.24.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Have pre-defined value with disabled option
2. Dropdown do not populate with value, but keeps showing placeholder

### Expected behavior

Instead placeholder, we should see the value.

**Comment by mneciunas** [comment]
Duplicate issue: https://github.com/primefaces/primevue/issues/3541
Here's my workaround
```
<Dropdown ...>
  <template #value="slot">
    <span>
      {{ slot.value ?? '&nbsp;' }}
    </span>
  </template>
</Dropdown>
```

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3541
