### ISSUE TITLE
InlineMessage: Documentation error

### ISSUE THREAD

**Issue by adrianrudnik** [primefaces/primevue#3716]
### Describe the bug

The [import documentation](https://github.com/primefaces/primevue/blob/master/doc/inlinemessage/ImportDoc.vue) states

```js
import InlineMessage from 'primevue/message';
```

which is the wrong component to be imported, it should be

```js
import InlineMessage from 'primevue/inlinemessage';
```

### Reproducer

https://primevue.org/inlinemessage

### PrimeVue version

3.24.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for your contribution!
