### ISSUE TITLE
Esc key support to close the Dialog

### ISSUE THREAD

**Issue by ilyavaiser** [primefaces/primevue#372]
It would be nice to have built-in support for this behavior.

**Comment by cagataycivici** [comment]
PrimeFaces, PrimeNG and PrimeReact have this, we sure can add it to Vue as well.

**Comment by nestorrente** [comment]
Hi everyone!

It would be nice if there was a way to close the dialog when the mask is clicked. For example, Vuetify's `<v-dialog>` emits a `@click:outside` event when its mask is clicked that is very useful.

Thank you for your great job!
