### ISSUE TITLE
MultiSelect: Overwrite the MultiSelectFilterEvent

### ISSUE THREAD

**Issue by TsungLin716** [primefaces/primevue#3721]
### Describe the feature you would like to see added

When triggering filter event on multiselect, we are able to overwrite the filter event function based on our service call.

### Is your feature request related to a problem?

I filtered on my first input value and select them all, I clear it out and type in a second input value and the previous selections are all wiped out so our service call cannot capture them. I am not able to pass all the options we selected based on different input value.

### Describe the solution you'd like

visibleOptions() 
{
                const options = this.optionGroupLabel ? this.flatOptions(this.options) : this.options || [];
               

               if (this.filterValue) {
                    const userFilterdOptions = api.UserFilterService.filter(options,this.searchFields, this.filterValue, this.filterMatchMode, 
                                                           this.filterLocale);// this is just my thought on how we can customize our own filtering 
                                                                                         function and not use the default one.
                    const filteredOptions = userFilteredOptions?userFilteredOptions:api.FilterService.filter(options, this.searchFields, 
                                                          this.filterValue, this.filterMatchMode, 
                                                           this.filterLocale); // we are able to use our own function and return filteredOptions.

                    if (this.optionGroupLabel) {
                        const optionGroups = this.options || [];
                        const filtered = [];

                        optionGroups.forEach((group) => {
                            const filteredItems = group.items.filter((item) => filteredOptions.includes(item));

                            if (filteredItems.length > 0) filtered.push({ ...group, items: [...filteredItems] });
                        });

                        return this.flatOptions(filtered);
                    }

                    return filteredOptions;
                }

                return options;
            },

**Comment by TsungLin716** [comment]
There is not a bug with the way the component currently operates, however we would like a way to implement a custom filter or gain access to an event that fires after the filtering occurs

**Comment by tugcekucukoglu** [comment]
Could you send us a reproducer link?
