### ISSUE TITLE
InputNumber: Issue Accept Numpad Decimal when different to the region symbol

### ISSUE THREAD

**Issue by Pedro-Mag** [primefaces/primevue#3722]
### Describe the feature you would like to see added

Accept the Numpad Decimal key event always as decimal point input, no matter the region format defined.

### Is your feature request related to a problem?

Sometimes the user has the keyboard numpad decimal key defined to a different symbol of region format selected.
When that happens, it's impossible to insert the decimal symbol by using the numpad.

### Describe the solution you'd like

One solution could be to listen to the code off the event and if is equal to 'NumpadDecimal' change the char variable accordingly.

```
        onInputKeyPress(event) {
            if (this.readonly) {
                return;
            }

            event.preventDefault();
            let code = event.which || event.keyCode;
            let char = String.fromCharCode(code);
            if(event.code === 'NumpadDecimal' && !this.isDecimalSign(char)) {
                char = char == ',' ? '.' : ','
            }
            const isDecimalSign = this.isDecimalSign(char);
            const isMinusSign = this.isMinusSign(char);

            if ((48 <= code && code <= 57) || isMinusSign || isDecimalSign) {
                this.insert(event, char, { isDecimalSign, isMinusSign });
            }
        },
```

**Comment by omgitsarnout** [comment]
I am suffering from the same problem. Our client expects to be able to use both a dot and a comma as a decimal seperator but sadly primevue inputNumber does not support it by default.

**Comment by Haine-Thomas** [comment]
Is there an update on this subject ?
In some countries, people often use both dot and comma as a decimal separator. It would be nice to have the option to do both !
