### ISSUE TITLE
DataTable: ExportDoc incorrect closing `script` tag for composition api example

### ISSUE THREAD

**Issue by neilmerton** [primefaces/primevue#3723]
### Describe the bug

<img width="1138" alt="2023-03-10 at 09 11" src="https://user-images.githubusercontent.com/505027/224274938-01940a3f-73cc-4591-8664-5cbe3010ce0f.png">

### Reproducer

https://primevue.org/datatable/#export

### PrimeVue version

3.24.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Please check the latest changes.
