### ISSUE TITLE
Api: Type mismatch

### ISSUE THREAD

**Issue by JeffreyNijs** [primefaces/primevue#3727]
### Describe the bug

Type checks fail for 3.24.0 when using a variable with an interface extending type `DataTableFilterMeta` and giving an object with `matchMode` using `FilterMatchMode`. `FilterMatchMode` is of type `string` but `matchMode` expects specific values.

This error occurs:

`Type 'string' is not assignable to type '"startsWith" | "contains" | "notContains" | "endsWith" | "equals" | "notEquals" | "in" | "lt" | "lte" | "gt" | "gte" | "between" | "dateIs" | "dateIsNot" | "dateBefore" | "dateAfter" | undefined'.`

This applies to other types defined in Api.d.ts.

### Reproducer

https://codesandbox.io/s/eloquent-proskuriakova-wy0x47?file=/src/customerTableFilters.type.ts

### PrimeVue version

3.24.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to 'src/customerTableFilters.type.ts'.
2. Notice TS error below the comment.

### Expected behavior

No TS error. `matchMode` should expect the correct string values.

**Comment by loneil** [comment]
Hmm I've just come across this as well after updating a functioning app from 3.23 to 3.24.
Is there any workaround? I'm still getting the error even if using a hard-coded string instead of the type

![image](https://user-images.githubusercontent.com/17445138/224453847-9bff6ad7-2493-44e4-86f0-e20dc97c3f78.png)

**Comment by loneil** [comment]
Looks like casting it removes the error for me actually.

![image](https://user-images.githubusercontent.com/17445138/224454299-9809be4a-1034-4e1b-9db5-5e3eadae1ef2.png)

![image](https://user-images.githubusercontent.com/17445138/224454288-426412af-255a-4970-accc-f834b3a1d6ea.png)

**Comment by Goldenaries658** [comment]
@mertsincan You've refactored the solution in 53312c0. However this seems to break it as seen below. Happy to open a new issue if needed.
![image](https://user-images.githubusercontent.com/59972622/225088114-483a0405-ee7f-49f0-9988-4225c10cb59a.png)

**Comment by JeffreyNijs** [comment]
Actually I can confirm this is still an issue. Now that it's an enum in the .d.ts file, it can't be found in the esm.js file when building the application.

**Comment by JeffreyNijs** [comment]
Please see the related issue: https://github.com/primefaces/primevue/issues/3751#issuecomment-1469637959
