### ISSUE TITLE
DataTable: Sorting icons feel wrong

### ISSUE THREAD

**Issue by web-swpl** [primefaces/primevue#3730]
### Describe the bug

Ascending Order sort icon (i.e. `pi-sort-amount-up-alt`) is just the Descending Order sort icon (`pi-sort-amount-down`), but flipped upside down. Therefore, the Ascending Order sort icon is extremely confusing as the arrow points in the wrong direction.

### Reproducer

https://codesandbox.io/s/primevue-issue-3730-x5kuds?file=/src/App.vue

### PrimeVue version

2.10.1

### Vue version

2.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Make a datatable with at least 1 sortable column
2. Click on the sorting icon
3. Notice that the icon used to indicate an Ascending Order sort is `pi-sort-amount-up-alt`
4. Click again on the same sorting icon
5. Notice that the icon used to indicate a Descending Order sort is `pi-sort-amount-down`

### Expected behavior

Both icon should visually represent what the sorting state is

**Comment by tugcekucukoglu** [comment]
Thank you for your contribution. We don't think it is a bug.
