### ISSUE TITLE
DataTable: rowStyle function doesn't work 

### ISSUE THREAD

**Issue by vaiil** [primefaces/primevue#3738]
### Describe the bug

According to the [docs](https://primevue.org/datatable/#api.datatable.props.rowStyle):
rowStyle is a function that takes the row data as a parameter and returns the inline style for the corresponding row.

But if we look at code, we see that it accept only object. There were an issue [before](https://github.com/primefaces/primevue/issues/2750), but it wasn't fixed. 

### Reproducer

https://codesandbox.io/s/funny-noyce-90zjm0?file=/src/App.vue

### PrimeVue version

3.24

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to sandbox

### Expected behavior

rowStyle function should be called, its result should be used as a style of row

**Comment by Rakasch** [comment]
Oh wow. That "fix" just broke my datatable.
All rows vanished. Took me quite some time to find the root cause.

I had an inline
` :rowStyle="'height: ' + itemSize + 'px'"`
This does not work anymore.

Had to change it to
`:rowStyle="rowStyle"`
Where rowStyle is a function that returns the string.

**Comment by pyramid-johng** [comment]
actually `rowStyle` et al take "objects" (it parses them) not strings so you should have had `{'height': itemSize + 'px'}` as the value you omitted the curly braces indicating an object.

**Comment by Rakasch** [comment]
> actually `rowStyle` et al take "objects" (it parses them) not strings so you should have had `{'height': itemSize + 'px'}` as the value you omitted the curly braces indicating an object.

I had rowstyle as I wrote it.
I don't know what the old documentation said, but it worked like this until version 3.24.x
