### ISSUE TITLE
DataTable: Storage support

### ISSUE THREAD

**Issue by havist** [primefaces/primevue#3740]
### Describe the feature you would like to see added

First, I found DataTable's state management very useful, especially in master-detail scenarios. But this state management is limited to session or local storage. In my opinion some little enhancement could be made with extending this storage property to be of any [Storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage) interface. With this, custom implementation of Storage interface could be passed to inject any implementation of it (e.g. wrapping Pinia store).

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
