### ISSUE TITLE
Responsive Breadcrumb

### ISSUE THREAD

**Issue by JordanMed** [primefaces/primevue#3744]
### Describe the feature you would like to see added

Currently when I use the bread crumb on mobile the breadcrumb overflows off of the screen. I would like the bread crumb to wrap so that they start to stack as the screen gets smaller. 

or even better what i implemented on my project. you hide all of the crumbs except for the second last one and add a < arrow in front of the label to let users know that they can go back one page easily.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
