### ISSUE TITLE
Nuxt 3: Import all components

### ISSUE THREAD

**Issue by f11y11** [primefaces/primevue#3746]
### Describe the feature you would like to see added

It would be great if all components were auto imported in a Nuxt project. Unused components could be filtered out when the app is built for production and primevue plugin wouldn't get so messy with all the required imports and app.component() calls.

### Is your feature request related to a problem?

I'm always frustrated when I have to import every PrimeVue component when I start a new project. Since Nuxt supports auto imports, I think this would be a good feature if possible.

### Describe the solution you'd like

Auto import every component by default. IDE already shows available PrimeVue components while writing in a Nuxt project but they still require manual imports inside primevue plugin.

### Describe alternatives you have considered

Nothing.

**Comment by frandmb** [comment]
seems to be what https://github.com/sfxcode/nuxt-primevue does, an official implementation would be neat

**Comment by tugcekucukoglu** [comment]
PrimeVue Nuxt module is available now. For more information: https://primevue.org/nuxt/
