### ISSUE TITLE
Slider: Focus on slider on mouse click

### ISSUE THREAD

**Issue by riorudo** [primefaces/primevue#3748]
### Describe the bug

When the slider is selected with the mouse, the focus is **NOT** set on the slider.
At the moment it is possible to set the focus on the slider via the tab navigation, but not with the mouse.

Focus on mouse selection works for the [PrimeNG Slider v15.2.0](https://primeng.org/slider) but not for the [PrimeVue Slider v3.25.0](https://primevue.org/slider/). This can be reproduced using the official documentation as an example.

### Reproducer

https://primevue.org/slider

### PrimeVue version

3.25.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 111.xx, Firefox 110.xx

### Steps to reproduce the behavior

1. Select slider handle with the mouse
2. Try to increase/decrease the value of the slider using the arrow keys

### Expected behavior

When the slider is selected with the mouse, it should receive focus so that the slider value can also be increased/decreased with the keyboard.

**Comment by kilobyte2007** [comment]
This issue seems to be present again. @tugcekucukoglu can you please take a look?
It's reproducible on the docs site - https://primevue.org/slider/
