### ISSUE TITLE
Ability to set a template for the selected value for AutoComplete field

### ISSUE THREAD

**Issue by ilyavaiser** [primefaces/primevue#375]
All advanced autocomplits can do this!

**Comment by cagataycivici** [comment]
Why not :)

**Comment by west-farmer** [comment]
Good news, just I hope for.

**Comment by ilyavaiser** [comment]
Any news?

**Comment by cagataycivici** [comment]
We have it for the multiple mode, single mode is not supported as it is a simple input field.
