### ISSUE TITLE
ConfirmDialog - Confirmation Service: Emit not working inside accept function

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#3756]
### Describe the bug

Emit in Context is not being called when used inside the confirm service accept function:
```
    const handleSubmit = () => {
      confirm.require({
        message: 'Do you want to delete this record?',
        header: 'Delete Confirmation',
        icon: 'pi pi-info-circle',
        acceptClass: 'p-button-danger',
        accept: () => {
         // This line is not being called here
          ctx.emit("enableTax");
        }
    });
    };
```

### Reproducer

https://codesandbox.io/s/cocky-rgb-q45b1x?file=/src/Child.vue

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
You just need to add `<ConfirmDialog />` to your app. Please check this example that fixed https://codesandbox.io/s/infallible-feather-hhzfwr
