### ISSUE TITLE
PickList: Add items slot (to customize wrapping markup)

### ISSUE THREAD

**Issue by septatrix** [primefaces/primevue#3759]
### Describe the feature you would like to see added

The PickList component should expose an `items` slot which would be responsible for rendering markup wrapping the items and looping over the items and rendering those.

### Is your feature request related to a problem?

We are currently working on a project where we would like to customize the `PickList` component items. Currently, it is possible to provide a template for each individual item itself. However, this does not allow more rigorous customization like exchanging the ul+li markup with a tree or table.

### Describe the solution you'd like

As stated above, a slot for more powerful customization should be added. This slot should also ideally inject the props and events required on the wrapping elements such that the user can easily apply these (`<foobar v-on=sourceListEvents v-bind=sourceListProps>`).

### Describe alternatives you have considered

Manually implement a PickList with our required desired look though this would mean reimplementing a lot of behavioural code which already exists. Furthermore this would also mean that other users of PrimeVue would not benefit from this.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
