### ISSUE TITLE
DataView: grid styles missing

### ISSUE THREAD

**Issue by iampeternguyen** [primefaces/primevue#3761]
### Describe the bug

I'm trying to use the dataview in grid layout, but it seems like the primevue.min.css is missing the grid related styles (ex: p-grid p-nogutter grid grid-noguttter). if i search through the code, i can only see style related grid stuff if the theme. 

am i missing something here?

### Reproducer

n/a

### PrimeVue version

2.x

### Vue version

2.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Use dataview component in grid layout. All items span full width.

### Expected behavior

It would look like a grid.

**Comment by tugcekucukoglu** [comment]
Which PrimeVue version are you using? You need to use 2.5.0+.

https://github.com/primefaces/primevue/commit/9820c77d9a7b07a9a2fea08bf11496b57d85625c

**Comment by iampeternguyen** [comment]
@tugcekucukoglu im using 2.9.2. the dataview component has the class names, but there doesn't seem to be any related styles in the primevue.min.scss that add flex or grid so the classes don't do anything.

**Comment by tugcekucukoglu** [comment]
DataView has PrimeFlex dependency. You could try to download PrimeFlex.
