### ISSUE TITLE
MultiSelect enable tooltips

### ISSUE THREAD

**Issue by csakis** [primefaces/primevue#3763]
### Describe the feature you would like to see added

It would be nice if we could add `v-tooltip` directive to MultiSelect components.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

When the user hovers over a MultiSelect component, a tooltip would pop up with some help text.

### Describe alternatives you have considered

No

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
