### ISSUE TITLE
Tooltip Delay option

### ISSUE THREAD

**Issue by csakis** [primefaces/primevue#3764]
### Describe the feature you would like to see added

Tooltips can be overwhelming for users. It would be nice to be able to set a delay in ms before tooltips pop up.

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

 It would be nice to be able to set a delay in ms before tooltips pop up.

### Describe alternatives you have considered

None

**Comment by ZiadJ** [comment]
That would be a most welcome addition. I ended up using a separate library for that.

**Comment by ZiadJ** [comment]
It would be even nicer if there was an option to show the tooltip only when mouse is stationary.
