### ISSUE TITLE
Documentation: Is there a place to view older documentation?

### ISSUE THREAD

**Issue by dmhendricks** [primefaces/primevue#3765]
### Describe the feature you would like to see added

Is there a way to view older documentation? We are using PrimeVue v3.20.0, but the documentation on the web site appears to be for the latest version.

### Is your feature request related to a problem?

I went to the [Button](https://primevue.org/button) documentation today and noticed some of the CSS classes were removed. For example, I wanted to look up how to create a gray (secondary) button. However, the documentation says to use this:
```html
<Button label="Secondary" severity="secondary" />
```

That doesn't appear to work with v3.20.0 (?) - the button remains blue (primary). This is how we have been doing it:
```html
<Button label="Secondary" class="p-button-secondary" />
```

I imagine the disparities will get worse with time, as features are added and changes are made.

### Describe the solution you'd like

It would be nice to be able to reference older versions of the 3.x documentation. (maybe this is possible already, but I don't know where)

### Describe alternatives you have considered

We're using v3.20.0 because of the removal of the ability to manually input dates/times #3523. In order to upgrade to the latest PrimeVue, I need to find a suitable replacement for the Calendar control (easier said than done since the users are picky, and has been a low priority since 3.20.0 is otherwise working great).

**Comment by dmhendricks** [comment]
I understand that the classes aren't removed, but it's kind of annoying to have to inspect elements to discover the appropriate CSS classes to use (especially when an element has nested elements with their own classes). It was nice when they were just listed in the documentation. It feels like the documentation is incomplete if you have to inspect elements to discover how to use them.

**Comment by dmhendricks** [comment]
Regardless, the point of my post was being able to see documentation for older versions. I was merely using that as an example.

Going forward, I'm sure PrimeVue will divert from 3.20.0 more and more as time progresses, making the latest documentation useless for anyone using an older version.

**Comment by dmhendricks** [comment]
@tugcekucukoglu - Regardless, the point of my post was being able to see documentation for older versions. I was merely using that as an example.

Going forward, I'm sure PrimeVue will divert from 3.20.0 more and more as time progresses, making the latest documentation useless for anyone using an older version.

**Comment by alansgonzaga** [comment]
I have been dealing with this problem a long time unfortenaly. Is there anyway to check old documentation?

**Comment by oliviermattei** [comment]
Indeed, It's a mess when we are stuck on an old version to give the right documentation. It would be awesome to be able to navigate beetween all old released. 

There are too many breaking changes in every version to upgrade it all the time
