### ISSUE TITLE
Drag-n-drop for TabView to reorder tabsComponent

### ISSUE THREAD

**Issue by mortenkos** [primefaces/primevue#3775]
### Describe the feature you would like to see added

To be able to drag-n-drop and reorder tabs

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
