### ISSUE TITLE
Multiselect: Tagging

### ISSUE THREAD

**Issue by ineshbose** [primefaces/primevue#3777]
### Describe the feature you would like to see added

It would be incredible if Multiselect would enable the option to add custom inputs when it is filterable / editable and option is not in the dropdown.

Please refer to https://vue-multiselect.js.org/#sub-tagging for an example. It could use a prop named `tags` or `tagging`.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
