### ISSUE TITLE
Dropdown: Filter through edit input

### ISSUE THREAD

**Issue by ineshbose** [primefaces/primevue#3778]
### Describe the feature you would like to see added

It would be incredible if options can be filtered from the editable input (https://primevue.org/dropdown/#editable) instead of another text field. This could also be added to Multiselect then and benefit #3777.

Please refer to https://vue-multiselect.js.org/#sub-select-with-search for an example.

**Comment by tugcekucukoglu** [comment]
This means there is a big core change. Still, if there is more demand, we'll definitely reconsider. Thank you for your feedback.
