### ISSUE TITLE
DataTable: dynamic row expansion

### ISSUE THREAD

**Issue by kaipaysen** [primefaces/primevue#3779]
### Describe the feature you would like to see added

We hava a DataTable where some rows should be able to expand and other might not. Right now [Row Expansion](https://primevue.org/datatable/#row_expansion) can only be applied to the whole table but not to individual rows. Having the expanderer chevron icon in every row suggests there might be something to see in every row. But as stated before its just every now and then.

I'd like an option to control the expand option on a per row basis.

### Is your feature request related to a problem?

Yes, Users think they should see something in the expansion area. As the area is often empty they are confused and ask for support.

### Describe the solution you'd like

One Option would be to add a property `expandableField`on the DataTable which holds the row propertyName which controls the visibility of the expand chevron. 

Another option might be adding a slot `#expand` with access to a "toggle expand" function to the Column Component.

### Describe alternatives you have considered

I tried to fiddle around with the body slot of the expander column but didn't get it to dynamicly hide the chevron based on the row data.

**Comment by jgalb** [comment]
+1

**Comment by garry-mitchell-coats-com** [comment]
Just started looking at how I'd do this, and found this request, so adding my +1 here too

**Comment by kaipaysen** [comment]
As this issue hasn't stop bugging me I fiddled around a litte and found a way how the desired behaviour could be achieved. We can utilize the [PT Options](https://primevue.org/passthrough/) like this:

```
<Column expander :pt="{
    rowToggler: ({ instance: { rowData }}) => ({
        class: {
            'hidden': (rowData?.price > 50)
        }
    })
}" />
```

https://stackblitz.com/edit/h5peg4?file=src%2FApp.vue

**Comment by danillojose** [comment]
> As this issue hasn't stop bugging me I fiddled around a litte and found a way how the desired behaviour could be achieved. We can utilize the [PT Options](https://primevue.org/passthrough/) like this:
> 
> ```
> <Column expander :pt="{
>     rowToggler: ({ instance: { rowData }}) => ({
>         class: {
>             'hidden': (rowData?.price > 50)
>         }
>     })
> }" />
> ```
> 
> https://stackblitz.com/edit/h5peg4?file=src%2FApp.vue

YOU SAVED MY LIFE! I signed in to github just to like u comment. Thank you!

**Comment by okssdeveloper** [comment]
> As this issue hasn't stop bugging me I fiddled around a litte and found a way how the desired behaviour could be achieved. We can utilize the [PT Options](https://primevue.org/passthrough/) like this:
> 
> ```
> <Column expander :pt="{
>     rowToggler: ({ instance: { rowData }}) => ({
>         class: {
>             'hidden': (rowData?.price > 50)
>         }
>     })
> }" />
> ```
> 
> https://stackblitz.com/edit/h5peg4?file=src%2FApp.vue

Hi sir the method you are using is not applying in my code what am i doing wrong  -------------------------

**Comment by peekay1234** [comment]
@okssdeveloper My code work with https://github.com/primefaces/primevue/issues/1834

**Comment by LewisDamy** [comment]
Workaround: https://github.com/primefaces/primevue/issues/1834#issuecomment-2825359537
