### ISSUE TITLE
DataTable: Group Rows do not span all Columns with Selection Mode set and group-by not in the Column list

### ISSUE THREAD

**Issue by pyramid-johng** [primefaces/primevue#3781]
### Describe the bug

When using the `DataTable` with the group features and explicitly setting the `selectionMode` attribute to either "single" or "multiple", this causes the generated group rows to fail to span all the grid's columns.  Same effect if you use the `Column` with explicit `selectionMode` (which adds another column).

This is more obvious with `showGridLines` turned on.

When generating the markup for the `td` element, the `colspan` attribute is off-by-one, and this causes the artifact.

In versions before 3.25, this did not occur, or the styling was such that it was not visible.

![image](https://user-images.githubusercontent.com/13980984/226628101-0b01aaf9-a639-42f3-b4f6-68f5cdb66796.png)

I have it set up here https://codesandbox.io/p/sandbox/primevue-demo-forked-dizc0c

More research indicates that if the field that is grouped on is not in the list of `Column` entries, the artifact is produced.  You can reproduce this with any of the examples on the `DataTable` page on the website.

https://codesandbox.io/p/sandbox/primevue-demo-forked-qqxrxr

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-dizc0c

### PrimeVue version

3.25.0+

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. get a `DataTable` into your app
2. bind some columns with `Column` elements
3. configure the grid for grouping `rowGroupMode="subheader"` not sure the mode matters
4. explicitly enable `selectionMode="single"` or add a `Column` with `selectionMode`
5. **do not include** the group-by column as a `Column`
6. note that the group bands do not extend across all columns (when hovered)

Note that `selectionMode` doesn't really matter, because you can see the cell borders are missing on the "last" column.

### Expected behavior

Group rows should span all columns regardless of any other settings.

**Comment by pyramid-johng** [comment]
I have this narrowed down to the group-by column is missing from the `Column` list in the grid, and `selectionMode` is explicitly set.

**Comment by Tamas-hi** [comment]
This still doesn't work for me in all versions above 3.23.0. <td> is still off by one, which you can see in the Subheader row.
I haven't set the selectionMode explicitly.
![image](https://user-images.githubusercontent.com/36476318/228458699-451cb48d-1ff8-4e4e-ab1e-d6128eda8b14.png)

**Comment by kubiksk8ter** [comment]
Why is this bug closed? It seems, that it is not fixed in any version...

**Comment by JasonLandbridge** [comment]
This fix doesnt seem to be backported to version 3.52, this is a workaround:

```vue
  <DataTable
    :pt="{
      rowGroupHeaderCell: {
        colspan: 6, // Set this to the number of columns
      },
    }"
    selectionMode="multiple">
    <Column :field="profileNo" />
    <Column :field="description" />
    <Column :field="lengthPerUnit" />
    <Column :field="squareMeterPerUnit" />
    <Column :field="weightPerUnit" />
    <Column :field="numberOfUnits" />
    <template #groupheader="{ data }: { data: ProductionOrderDTO }">
      <Text bold>{{ data.productionOrderNo }}</Text>
    </template>
  </DataTable>


```

**Comment by panwauu** [comment]
Still relevant as of 3.53

Reproduced in: https://stackblitz.com/edit/hoqwgk?file=src%2FApp.vue

![image](https://github.com/user-attachments/assets/851f8987-bfc2-4423-845b-c98a76d9e53e)
