### ISSUE TITLE
Button: Custom severities

### ISSUE THREAD

**Issue by lwpinion** [primefaces/primevue#3782]
### Describe the feature you would like to see added

It would be great if there was a way to add custom severities to the buttons. In fact, I'm sure there are other components that could benefit from being able to have consistent custom styles. With Bootstrap it's easy to add new colors to the sass map and then the components that use these theme colors just iterate over the map.

On our site, for instance, we are looking for a white outlined button. However, white isn't our secondary color so we can't just use that. We could repurpose other severities that we don't think we'll use like "Help," but I'd rather keep the semantics accurate when it comes to assigning those severities.

Speaking of semantics, have you ever considered renaming that property to something other than "severity"? The term works when you're talking about "Warning" or "Danger" but it doesn't really make sense when you're referring to a button using the "Secondary" color. I can open a separate issue for this if needed.

### Is your feature request related to a problem?

No, not inherently.

### Describe the solution you'd like

I don't have a specific solution in mind. Just some way to add new styles for some of the components that can be configured at a high level and used consistently across a project/theme. That being said, I do see now when looking at the theme-base styles for the button that the specific severity classes are hard-coded, so this might be more of an undertaking than I would have expected.

**Comment by tugcekucukoglu** [comment]
The new `pt` property can do that and the upcoming unstyled mode will make it easier to use with Bootstrap.

**Comment by lwpinion** [comment]
> The new `pt` property can do that and the upcoming unstyled mode will make it easier to use with Bootstrap.

Great, thanks! Can you point me in the direction of the documentation for this new property? I'm not sure where it is. 😄

**Comment by tugcekucukoglu** [comment]
https://primevue.org/button/#pt.doc.button

**Comment by OliverRC** [comment]
What I eventually did was globally set custom severities. In my case I set these for the `Tag` component but you can easily do something similar for `Button`. I also chose to use Tailwind classes but it's really up to you.

```
app.use(PrimeVue, {
  pt: {
    tag: {
      root: ({ props }) => {
        const customSeverities = {
          slate: 'bg-slate-500 text-white dark:bg-slate-400 dark:text-slate-950',
          gray: 'bg-gray-500 text-white dark:bg-gray-400 dark:text-gray-950',
          zinc: 'bg-zinc-500 text-white dark:bg-zinc-400 dark:text-zinc-950',
          neutral: 'bg-neutral-500 text-white dark:bg-neutral-400 dark:text-neutral-950',
          stone: 'bg-stone-500 text-white dark:bg-stone-400 dark:text-stone-950',
          red: 'bg-red-500 text-white dark:bg-red-400 dark:text-red-950',
          orange: 'bg-orange-500 text-white dark:bg-orange-400 dark:text-orange-950',
          amber: 'bg-amber-500 text-white dark:bg-amber-400 dark:text-amber-950',
          yellow: 'bg-yellow-500 text-white dark:bg-yellow-400 dark:text-yellow-950',
          lime: 'bg-lime-500 text-white dark:bg-lime-400 dark:text-lime-950',
          green: 'bg-green-500 text-white dark:bg-green-400 dark:text-green-950',
          emerald: 'bg-emerald-500 text-white dark:bg-emerald-400 dark:text-emerald-950',
          teal: 'bg-teal-500 text-white dark:bg-teal-400 dark:text-teal-950',
          cyan: 'bg-cyan-500 text-white dark:bg-cyan-400 dark:text-cyan-950',
          sky: 'bg-sky-500 text-white dark:bg-sky-400 dark:text-sky-950',
          blue: 'bg-blue-500 text-white dark:bg-blue-400 dark:text-blue-950',
          indigo: 'bg-indigo-500 text-white dark:bg-indigo-400 dark:text-indigo-950',
          violet: 'bg-violet-500 text-white dark:bg-violet-400 dark:text-violet-950',
          purple: 'bg-purple-500 text-white dark:bg-purple-400 dark:text-purple-950',
          fuchsia: 'bg-fuchsia-500 text-white dark:bg-fuchsia-400 dark:text-fuchsia-950',
          pink: 'bg-pink-500 text-white dark:bg-pink-400 dark:text-pink-950',
          rose: 'bg-rose-500 text-white dark:bg-rose-400 dark:text-rose-950',
        };
        return { class: customSeverities[props.severity] || null };
      },
    },
  },
});
```
