### ISSUE TITLE
Steps Component

### ISSUE THREAD

**Issue by 95sunny** [primefaces/primevue#3784]
### Describe the feature you would like to see added

I neet use Steps without Router, how can I doit

### Is your feature request related to a problem?

I want a progress bar like Steps Component, but Steps only load value from router. I want use it with custom variable

### Describe alternatives you have considered

import components we actually need from other UI library like ElementUI

**Comment by tugcekucukoglu** [comment]
Vue-Router support removed from Steps and all Menu components. You could try to use the latest version.
