### ISSUE TITLE
Breadcrumb Component - scroll to top of screen on select

### ISSUE THREAD

**Issue by ccperegrine** [primefaces/primevue#3787]
### Describe the bug

Hi, I am using a Breadcrumb component in my code - when an item is clicked, it updates a child component as expected (using the command: () => {...} method), however at the same time, it scrolls back to the top of the page - this can be a bit disorienting for users, especially on mobile where they may have scrolled quite a way down the page (past various menu options) before clicking on the breadcrumb.
This behaviour happens in the examples given on the breadcrumb component documentation page...   [https://primevue.org/breadcrumb](https://primevue.org/breadcrumb) ... scroll down the page so the Basic breadcrumb is at the top, and select an item - once clicked the page will reset to the top of the screen.
I assume this is something to do with the behaviour of the ''target' option - Is there any settings that can be changed to make sure that when the item in the breadcrumb is clicked, it only executes the code in the command method for that item, and doesn't treat it as any kind of hyperlink?
Thanks in advance!

### Reproducer

-

### PrimeVue version

3.18.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

When clicking on a breadcrumb item, the page should remain in the same location, with just the function being executed

**Comment by bahadirsofuoglu** [comment]
duplicated #3744
