### ISSUE TITLE
PanelMenu: Collapse Menu Horizontally

### ISSUE THREAD

**Issue by MoMack20** [primefaces/primevue#3792]
### Describe the feature you would like to see added

I would like the ability to collapse the menu down to just the icon display so that I can save horizontal space on the screen. This is implemented pretty often for applications and websites. A notable example is azure devops.

### Describe the solution you'd like

It would easy as offering an "short label" or "short icon" and having a toggle to flip the display back and forth between the two.

### Additional context

![image](https://user-images.githubusercontent.com/11836187/227081643-6af7c954-979d-4706-8bc9-dda994d86e34.png)

![image](https://user-images.githubusercontent.com/11836187/227081723-9e416794-c948-4e67-b94e-0e6a5b0d347f.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
