### ISSUE TITLE
Dropdown: Tabbing out of filter doesn't close dropdown

### ISSUE THREAD

**Issue by zcdunn** [primefaces/primevue#3793]
### Describe the bug

See #2759

If the dropdown panel is open and focus is in the filter input, pressing tab moves focus to the next element but the dropdown panel remains open.

### Reproducer

https://codesandbox.io/s/amazing-hamilton-hdyhlc

### PrimeVue version

3.25.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Open a filterable dropdown
2. Click into the filter input
3. Press Tab

### Expected behavior

Focus moves to the next focusable element and the dropdown panel closes.

**Comment by mertsincan** [comment]
When the Dropdown panel is open, you cannot close the panel without selecting 'esc' or an item with the 'enter' key. There is focustrap feature in the panel, so you cannot close the panel with 'tab' key.
