### ISSUE TITLE
DataTable: Filter Menu not showing in ColumnGroup with `filterDisplay="row"` 

### ISSUE THREAD

**Issue by hanrea** [primefaces/primevue#3799]
### Describe the bug

In DataTable component and `ColumnGroup` header, Filter Menu not showing  with `filterDisplay="row"`  , but  use `filterDisplay="menu"` is  ok!

### Reproducer

https://codesandbox.io/s/strange-http-c0tw29?file=/src/App.vue

### PrimeVue version

3.26.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

### Steps to reproduce the behavior

Codesandbox compilation error, but the code passed compilation in my local vite example!

**Comment by hanrea** [comment]
In the [source code](https://github.com/primefaces/primevue/blob/b58ef712dbcb4984a9bf5a3d214bdb3bdf087fdc/components/datatable/TableHeader.vue#L80) , No  columnGroup and  "filterDisplay=== 'row'"  conditional branch.

**Comment by bouyass** [comment]
Did you figure it out ? I'm facing the same problem

**Comment by mertsincan** [comment]
Hi all,

This feature is not currently supported by PrimeVue DataTable with ColumnGroup. Can you create a ticket for this in the [discussion](https://github.com/orgs/primefaces/discussions/categories/primevue)? We can decide whether to add it or not based on user feedback.

Best Regards,
