### ISSUE TITLE
PrimeBlocks-Vue: Error in component code

### ISSUE THREAD

**Issue by adrianrudnik** [primefaces/primevue#3800]
### Describe the bug

Steps to reproduce:

- Download und extract `primeblocks-vue-3.2.0`
- Start it with `npm run serve`
- Visit http://localhost:8080/#/application/formlayout
- Scroll to "Full-Width Card", hit "code" or "copy"

Code is invalid at `<Dropdown id="country2 v-model="selectedCountry2"`: Missing the ending quote on `country2`. It is also missing the vue part completly, not sure if that is intended for a vue package.

### Reproducer

http://localhost:8080/#/application/formlayout

### PrimeVue version

primeblocks-vue-3.2.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Thanks for your report. It'll be fixed for the next version.
