### ISSUE TITLE
InputNumber: doesn't open numeric keyboard on mobile devices

### ISSUE THREAD

**Issue by alexterenya** [primefaces/primevue#3803]
### Describe the bug

When using InputNumber on mobile devices, it shows regular alphabetical keyboard. Since number input allows input only numbers, it should show numeric keyboard only.

### Reproducer

https://primevue.org/inputnumber/

### PrimeVue version

3.26.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Click on InputNumber component on mobile browser.
2. Pay attention on type of keyboard opened.
3. It shows alphabetical keyboard instead of numeric.

### Expected behavior

Numeric only keyboard appeared

**Comment by mertsincan** [comment]
Hi,
Please try `:inputProps="{type: 'number'}"`.

Best Regards,
