### ISSUE TITLE
How to pass slotProps argument into 'command' handler with SplitButton?

### ISSUE THREAD

**Issue by Sellec** [primefaces/primevue#381]
I have a SplitButton in my DataTable component row. I can pass slotProps into @click event but how to do this for submenu buttons?

**Comment by cagataycivici** [comment]
Please use forum for questions;

https://forum.primefaces.org/viewforum.php?f=110

**Comment by marcuschristiansen** [comment]
@Sellec Can you please link to the forum post if you did post it?
