### ISSUE TITLE
TabView: Template header of TabPanel doesn't count as an event to trigger the update:modelValue

### ISSUE THREAD

**Issue by Horos34** [primefaces/primevue#3810]
### Describe the bug

Inside the TabPanel while having a custom header template, triggering an event inside the template doesn't update the modelValue. But anywhere outside the template eveything works perfectly fine and the modelValue do update !

Context : I want to create a system where i can naviguate between tabs like Google Chrome, Mozilla, etc... opening and closing tabs....
So i tried to implement the closing tab method which splice an array of objects and change the value of the active tab.

### Reproducer

https://codesandbox.io/s/primevue-tabview-issue-zvubuq?file=/src/main.js

### PrimeVue version

3.26.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Click the button "Change me"
2. Click on the red button next to the "test 4" tab
3. Click until no tabs are left
4. Then reload the VM browser to repeat the process

### Expected behavior

When "closing" a tab, next or previous tab should be actived and show its content

**Comment by Horos34** [comment]
If anything is unclear, pls let me know so i can explain the issue again

**Comment by tugcekucukoglu** [comment]
When a tab is clicked the `tab-click` and `update:activeIndex` events trigger. To stop that, stopPropagation must be added to the button click in the tab. Please check this example https://codesandbox.io/s/primevue-tabview-issue-forked-831ydp?file=/src/App.vue
