### ISSUE TITLE
Calendar: Emit year-change event via navBackward and navForward

### ISSUE THREAD

**Issue by colinstevens06** [primefaces/primevue#3811]
### Describe the bug

When the user is using the Calendar component as the ~~Year~~ Month Picker, it would be helpful if the year-change emit would fire when the user navigates to previous or next year.

Fix would likely be emitting the 'year-change' event in 2 places:

- https://github.com/primefaces/primevue/blob/master/components/lib/calendar/Calendar.vue#L901
- https://github.com/primefaces/primevue/blob/master/components/lib/calendar/Calendar.vue#L928

### Reproducer

https://codesandbox.io/s/dreamy-firefly-oy6in1?file=/src/App.vue

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

In the code provided, use the 'next' and 'previous' buttons on the calendar to change year ... note that no information is logged via the @year-change emitted event

### Expected behavior

@year-change should emit when using Year Picker and using the next/previous buttons

**Comment by tugcekucukoglu** [comment]
If you have any solution, we would be grateful if you create a PR with the possible solution.

**Comment by colinstevens06** [comment]
@tugcekucukoglu FYI: created a PR for this issue: https://github.com/primefaces/primevue/pull/3821

Thanks!
