### ISSUE TITLE
Splitter: Gutter handle style override

### ISSUE THREAD

**Issue by csakis** [primefaces/primevue#3814]
### Describe the bug

I am trying to make the gutter handle in the Splitter component bigger. I added a custom class to the style overriding the `p-splitter-gutter-handle` class, but it does not take effect.

### Reproducer

https://stackblitz.com/edit/angular-h19ofx?file=src/App.vue

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Microsoft Edge

### Steps to reproduce the behavior

check gutter-splitter-handle in dev tools. No custom styles are applied

### Expected behavior

Seeing bigger handle for gutter handle

**Comment by tugcekucukoglu** [comment]
For now, you could use v-deep

```
::v-deep(.p-splitter .p-splitter-gutter .p-splitter-gutter-handle) {
   ...
}
```

But, currently we are working on a new `pt` property, and via `gutterhandler` object of this prop gutter handle's styles would be easily overwritten.
