### ISSUE TITLE
DataTable doesn't respond to assigning new array to ref bound to value property when virtualScrollerOptions property is set

### ISSUE THREAD

**Issue by Joshua-Schroijen** [primefaces/primevue#3819]
### Describe the bug

When binding the value property of DataTable to a ref to an array, setting the ref's value to a new array doesn't update the rows in the DataTable when the virtualScrollerOptions property is set.

### Reproducer

https://codesandbox.io/p/sandbox/peaceful-mahavira-0nwf6u?file=%2FREADME.md

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Click on the "Add book" button

### Expected behavior

New rows should appear in the DataTable like they do in the plain list below it.

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it with the latest version. For now, closed. If the problem persists, please reopen issue or create a new issue with the runnable sample codesandbox/stackblitz link.

Best Regards,
