### ISSUE TITLE
Message: wrong background color for severity="error" in tailwind-light theme.

### ISSUE THREAD

**Issue by baringji** [primefaces/primevue#3823]
### Describe the bug

The Message and InlineMessage component background color for severity="error" messages is the same with the warning background in tailwind-light theme.

### Reproducer

https://primevue.org/message/

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Visit primevue documentation site. https://primevue.org/message/
2. Set the theme to tailwind-light.
3. Observe the background color of the message box. The severity="error" message background is the same as the severity="warning" message background.

### Expected behavior

It should show something reddish.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
