### ISSUE TITLE
CascadeSelect: Add max-height prop to p-cascadeselect-items

### ISSUE THREAD

**Issue by Enoooch** [primefaces/primevue#3825]
### Describe the feature you would like to see added

Add max-height prop to CascadeSelect, so it can be scrolled when there are many options.

### Additional context

If we want to add `overflow: auto` to the container, the inner `ul.p-cascadeselect-items` elements should be added directly after `p-cascadeselect-items-wrapper`.

**Comment by tugcekucukoglu** [comment]
`pt` property can solve this problem.

**Comment by mark033100** [comment]
Greetings, could someone explain how it should the pt property should be applied? I was trying to but its not working for me.
