### ISSUE TITLE
Inplace: Close Programmatically

### ISSUE THREAD

**Issue by capoia** [primefaces/primevue#3828]
### Describe the feature you would like to see added

I would like to be able to control (open and close) the inplace programmatically, the user clicks on the inplace to edit what he wants and deduces that it has been changed, I added a button to save the information, but even after the user clicks on save it need to manually close inplace, which doesn't make much sense.

### Is your feature request related to a problem?

The problem is that there is no way to control the component (open and close) programmatically.

### Describe the solution you'd like

A way to control the component (close and open) via programming 

### Describe alternatives you have considered

an extra option in addition to closing to also validate the user's action, and that button at the end would close the inplace.

**Comment by tugcekucukoglu** [comment]
Duplicate #3408
