### ISSUE TITLE
Add new Icon components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#3829]
To remove the dependency of core components on primeicons, icon components have been added for primeicons used only in core components.

```js
import _iconname_ from 'primevue/icon/_icondir_';

Exp;
import PlusIcon from 'primevue/icon/plus'
```

**Comment by ineshbose** [comment]
Wouldn't it be easier and less maintenance if `Icon` component from `@iconify/vue` was used? 😬
