### ISSUE TITLE
Tree: keyboard keys don't work in InputElement

### ISSUE THREAD

**Issue by MassimoBev** [primefaces/primevue#3831]
### Describe the bug

If I have an InputText inside a Tree some keys doesn't work, for example the space, arrows or tab.
Tree captures this events

### Reproducer

https://codesandbox.io/s/eloquent-montalcini-wdttff?file=/src/App.vue

### PrimeVue version

3.23/3.24

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox, Chrome

### Steps to reproduce the behavior

- Expand the "Document" node
- As a child there is an Input text
- Try to write for example "Test Space"
- the space doesn't work

### Expected behavior

I can use space, arrows and tab

**Comment by Zebnastien** [comment]
I still have the same problem in 3.35.0 with TreeTable.

**Comment by jbreneman** [comment]
I also ran into this in 3.37.0 with TreeTable. I was able to work around it for now by adding an empty keydown handler to my input that stops propagation to prevent the TreeTable from hijacking the event when the user is focused on an input:

```
<InputText @keydown.stop="() => {}" />
```
