### ISSUE TITLE
Checkbox: Option to change the checkbox color when its checked

### ISSUE THREAD

**Issue by gabrielforster** [primefaces/primevue#3835]
### Describe the feature you would like to see added

I think that would be pretty nice if the Checkbox component accepts a prop that changes its color when checked.

### Describe the solution you'd like

A prop that accepts a hexadecimal color.

**Comment by DarynHolmes** [comment]
I can't figure this pass through out. Can you please give me an example?

Can this be used in https://primevue.org/tree/ ?

Thanks

**Comment by DarynHolmes** [comment]
I think I have it, something like 

```
<Tree
      v-model:selectionKeys="selectedKeys"
      v-model:expandedKeys="expandedKeys"
      :value="nodes"
      selectionMode="checkbox"
      class="w-[30rem] shrink-0 my-check"
      :pt="{ pcNodeCheckbox: { box: { class: '!bg-red-500' } } }"
    ></Tree>
```
