### ISSUE TITLE
Tooltip: TypeError: Cannot set properties of null (setting '$_ptooltipModifiers')

### ISSUE THREAD

**Issue by shadoWalker89** [primefaces/primevue#3839]
### Describe the bug

When `v-tooltip` directive is used on a Dropdown component this error will be thrown and it will prevent the rest of the app of displaying / working

`TypeError: Cannot set properties of null (setting '$_ptooltipModifiers')`

It gets thrown here https://github.com/primefaces/primevue/blob/84b85dc77deb069833a7fc292f54c2046825f527/components/lib/tooltip/Tooltip.js#L315 because `target` is `null`
And this is the `el` being passed to the `beforeMount()` `div#pv_id_2.p-dropdown.p-component.p-inputwrapper`

The latest version where this worked was 3.15.0
Starting from 3.16.0 the error is thrown

### Reproducer

https://stackblitz.com/edit/angular-muthw1?file=src%2FApp.vue

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 111.0.5563.147

**Comment by shadoWalker89** [comment]
@tugcekucukoglu 
Hi guys, i'm currently locked into primevue 3.15.0 because of this bugs, i tried fixing it before submitting this issue but i cloudn't.
I would appreciate if someone can give me some pointers on how to fix this so i could make a PR

**Comment by Rakasch** [comment]
primevues BaseDropdown.vue has the class 'p-inputwrapper'.

the conflict is between that class beeing on the dropdown and this function in the Tooltip.js
![image](https://github.com/primefaces/primevue/assets/8471027/3c84a77a-cc12-4d48-bb78-0cb6c797c4c8)

It tries to find the inout element, but a dropdown does not have an input element, therefore it returns null.

Either the BaseDropdown should not have that class or the Tooltip function must chech for dropdowns separately.

**Comment by Rakasch** [comment]
> We're unable to replicate your issue, if you are able to create a reproducer or add details please edit this issue. This issue will be closed if no activities in 20 days.

the issue still persists.
it already has a reproducer.
open the reproducer link and the dev console. the error is visible in the dev console.
![image](https://github.com/primefaces/primevue/assets/8471027/ba41fad3-f6f7-42ff-afba-4070bdded856)

**Comment by iampapagray** [comment]
THis issue still exists. How to resolve it?
