### ISSUE TITLE
Dropdown: Change prop autoFilterFocus default value to true

### ISSUE THREAD

**Issue by shadoWalker89** [primefaces/primevue#3840]
### Describe the feature you would like to see added

Hi,

Prior to 3.16.0 when a dropdown has a the filtering enabled, when the dropdown is clicked to show the list of options the filter field will be auto focused.

This is a stackblitz using 3.15.0 demonstrating what i just described https://stackblitz.com/edit/angular-4ppqqo-bwmcks?file=src%2Fmain.js,src%2FApp.vue,package.json

And this another one using 3.16.0 where the auto focus no longer occurs https://stackblitz.com/edit/angular-4ppqqo-hkajcu?file=package.json

I made a PR https://github.com/primefaces/primevue/pull/3841

### Is your feature request related to a problem?

The filter input of the dropdown has always been auto focused until 3.16.0
This allows the user to start typing and filtering without the need to manually click on the filter text input

### Describe the solution you'd like

Change the default value of the newly added prop to `autoFilterFocus` to maintain the old behaviour

**Comment by tugcekucukoglu** [comment]
3.16.0 includes accessibility improvements. According to WCAG standards, we have changed this behavior but with respect to the backward compatibility `autoFilterFocus` is still available.
