### ISSUE TITLE
Calendar: Change popup size

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#3842]
### Describe the bug

I am using PrimeVue 3.15 in Vue 3.2 PrimeVue popup Calendar takes its input width.(Image 1) How Can I make it smaller without decreasing the size of the input as in the second image?
I tried all the props related to classes and styles (inputProps, inputStyle, panelClass, panelStyle) but in vain.

![image](https://user-images.githubusercontent.com/57847174/230360942-99cb0dd6-0f41-4d4f-81dd-2d14ff0926c1.png)
![image](https://user-images.githubusercontent.com/57847174/230360983-e4b2a820-1822-4aee-8905-6bbd42e1bbe5.png)

### Reproducer

https://codesandbox.io/p/sandbox/naughty-sun-dyfcx4?welcome=true&file=README.md

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
Calendar calculates the panel's width so you could try to use it like this: 

```
Calendar v-model="date" class="w-full" panelClass="min-w-min w-10rem" />
```

**Comment by AmmarMohamadIsmaeel** [comment]
@tugcekucukoglu Thank you, It Worked! 🚀

**Comment by estradamarkie** [comment]
> Calendar calculates the panel's width so you could try to use it like this:
> 
> ```
> Calendar v-model="date" class="w-full" panelClass="min-w-min w-10rem" />
> ```

@tugcekucukoglu was these classes removed in ^3.53?
