### ISSUE TITLE
ZIndexUtils: dropdown and autocomplete doesn't work inside dialog using sfc imports 

### ISSUE THREAD

**Issue by mattiapv** [primefaces/primevue#3844]
### Describe the bug

Dropdown and Autocomplete suggestions panel are placed behind dialog. I haven't checked if this issue occurs with the Multiselect and CascadeSelect also.

I'm importing Dropdown and Autocomplete using `/sfc`. 

```js
import Dropdown from 'primevue/dropdown/sfc';
import AutoComplete from 'primevue/autocomplete/sfc';
```

It doesn't happen in vite build for production.
This is probably similar to #3554 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-vg4pex

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

z-index 2102 not 1001

**Comment by bahadirsofuoglu** [comment]
Hi, If you're using these components as sfc and haven't set the z-index configuration, this problem happens. You can use the baseZIndex prop as a solution.
