### ISSUE TITLE
z-index calculation if using PrimeVue as a library

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [primefaces/primevue#3846]
### Describe the feature you would like to see added

in my SPA project i use PrimeVue. i needed to write an component that also uses PrimeVue as a UI library.

Now, when i call a dialog component in my project and use a PrimeVue component from my library (i.e. dropdown) in it, the search filter opens with z-index 1001 (whereas the dialog box has z-index 2001).

As i understand it, the calculation of the z-index is carried out within the framework of a certain instance of the PrimeVue. Can i somehow control this and avoid miscalculations?

**Comment by veco9** [comment]
How did you solve this problem?
