### ISSUE TITLE
VirtualScroller: You may need an appropriate loader to handle this file

### ISSUE THREAD

**Issue by thalysmg** [primefaces/primevue#3848]
### Describe the bug

Hi everyone, after I updated my PrimeVue to 3.26.1 I'm getting the following error when running **npm run dev**.
Does anyone has any idea what could this be? I have no deeper experience/knowledge about webpack in depth.

The error:

```
ERROR  Failed to compile with 1 error                                9:50:21 AM

 error  in ./node_modules/primevue/virtualscroller/virtualscroller.esm.js

Module parse failed: Unexpected token (635:39)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         },
|         getPageByFirst(first) {
>             return Math.floor(((first ?? this.first) + this.d_numToleratedItems * 4) / (this.step || 1));
|         },
|         isPageChanged(first) {

 @ ./src/main.ts 48:0-55 73:631-646
 @ multi (webpack)-dev-server/client?http://192.168.0.11:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

### Reproducer

https://codesandbox.io/p/sandbox/cocky-nightingale-g5yfdz?file=%2FREADME.md

To see the error, just run `npm run dev` in the terminal

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Update primevue to 3.26.1
2. Run **npm run dev**

### Expected behavior

That no error occur when trying to run the dev server.

**Comment by tugcekucukoglu** [comment]
How can we replicate the issue? A reproducer link could help.

**Comment by zhujiangtao123** [comment]
I meet the same  problem;can you help me

**Comment by zhujiangtao123** [comment]
> ### Describe the bug
> Hi everyone, after I updated my PrimeVue to 3.26.1 I'm getting the following error when running **npm run dev**. Does anyone has any idea what could this be? I have no deeper experience/knowledge about webpack in depth.
> 
> The error:
> 
> ```
> ERROR  Failed to compile with 1 error                                9:50:21 AM
> 
>  error  in ./node_modules/primevue/virtualscroller/virtualscroller.esm.js
> 
> Module parse failed: Unexpected token (635:39)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |         },
> |         getPageByFirst(first) {
> >             return Math.floor(((first ?? this.first) + this.d_numToleratedItems * 4) / (this.step || 1));
> |         },
> |         isPageChanged(first) {
> 
>  @ ./src/main.ts 48:0-55 73:631-646
>  @ multi (webpack)-dev-server/client?http://192.168.0.11:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
> ```
> 
> ### Reproducer
> 
> ### PrimeVue version
> 3.26.1
> 
> ### Vue version
> 3.x
> 
> ### Language
> TypeScript
> 
> ### Build / Runtime
> Vue CLI App
> 
> ### Browser(s)
> _No response_
> 
> ### Steps to reproduce the behavior
> 1. Update primevue to 3.26.1
> 2. Run **npm run dev**
> 
> ### Expected behavior
> That no error occur when trying to run the dev server.

Do you  solve it,I'm same of you

**Comment by thalysmg** [comment]
> 

I went to StackOverflow and after trying to use **transpileDependencies** in my **vue.config.ts** and not having success, I just followed the recommendation of upgrading my VueCLI.
I was using v. 4 and I upgraded to v.5.

It is simples to do that, just go to your project, type `vue upgrade` and select 'yes' where it is asked.

**Comment by eledwinn** [comment]
I replicated it in codesandbox too
https://codesandbox.io/p/sandbox/jolly-parm-s4w96y

**Comment by JotDakha** [comment]
@thalysmg please check the node version. for primeVue 3.27.0 node version [16.x, 18.0] required.
https://github.com/primefaces/primevue/blob/master/.github/workflows/node.js.yml

In my case, I must upgrade [ @vue/cli-* ] version also.

I hope this will help you.
