### ISSUE TITLE
InputNumber: decrement&increment button class props typo

### ISSUE THREAD

**Issue by mtirimie1** [primefaces/primevue#3856]
### Describe the bug

the props for decrementButtonClass/incrementButtonClass had a typo in documentation which led to confusion internally

### Reproducer

n/a

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Go to the inputnumber page on the website and note that the +/- buttons don't have the desired red/green color

<img width="1114" alt="Screenshot 2023-04-12 at 11 52 58 AM" src="https://user-images.githubusercontent.com/106685374/231514410-3cc38819-aab2-43c6-bb0f-5bda9ce66812.png">

**Comment by mertsincan** [comment]
Thanks a lot for your contribution! 

Best Regards,
