### ISSUE TITLE
rowGroup feature is not working with paginator in PrimeVue's DataTable

### ISSUE THREAD

**Issue by jdkcoder** [primefaces/primevue#3858]
### Describe the bug

At first page, everything works perfectly
![image](https://user-images.githubusercontent.com/89140442/231686221-28cf2ec9-131b-4d88-8823-b8ff4e05ca17.png)

And when I change to the others, all the rowgroup header is duplicated like this
![image](https://user-images.githubusercontent.com/89140442/231686603-f0667412-1418-4f87-8e8f-d463d978577d.png)

I just checked around PrimeNG & PrimeReact and I saw this problem seems had been fixed but in PrimeVue, there is no one reported yet or maybe I haven't found any related issues yet so this problem still exists

The StackBlitz link below is based on example in PrimeVue's doc, I got this problem when developing my project, I try to use PrimeVue's example to make sure I did not do anything wrong in my project and I got same problem

### Reproducer

https://stackblitz.com/edit/angular-5xa4up?file=src%2FApp.vue

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Edge

**Comment by jcannata** [comment]
I'm seeing the exact same thing on 3.28

**Comment by iuriag** [comment]
Same bug on primevue 2.10.2
