### ISSUE TITLE
How to remove Operator in filter in prime vue ?

### ISSUE THREAD

**Issue by rs-kienht** [primefaces/primevue#3859]
I have a proplem when use filter in prime vue, I want to remove operator when filter 
![image](https://user-images.githubusercontent.com/82860628/231696194-3a5808bb-e494-4f2b-840d-7382597dda17.png)
. I try remove operator: FilterOperator.AND in code but filter is not work.Please check help me this issue. Thanks and best regard

**Comment by tugcekucukoglu** [comment]
There is `showFilterOperator` property for Column component.

<Column field="..." header="..." :showFilterOperator="false" />
