### ISSUE TITLE
DataTable: component we need to have a v-on:scroll event

### ISSUE THREAD

**Issue by rockycastadata** [primefaces/primevue#3863]
### Describe the feature you would like to see added

on the DataTable component we need to have a v-on:scroll event

<DataTable @scroll="scrollMethod"></DataTable>

scrollMethod($event) {
  // $event should have a way to check the position of the scroll value 
  // of x,y or something to make us aware where in the world is this user scrolling at
}

**Comment by Tamas-hi** [comment]
I am in need of an event like this, so I completely support.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3235

**Comment by rlopezb** [comment]
```
<template>
  <DataTable
      ref="table"
 ...
</template>

<script setup lang="ts">
const table = ref();

onMounted(() => {
  table.value.$el.children[0].addEventListener("scroll", onScroll);
});

...
</script>
```
