### ISSUE TITLE
Chip: Add Severity prop

### ISSUE THREAD

**Issue by IvanSGurdian** [primefaces/primevue#3867]
### Describe the feature you would like to see added

Allow a `severity` prop in `Chip` component so it can be quickly styled similar to components like `Tag` and `Button`.

### Is your feature request related to a problem?

It's a bit cumbersome to style Chips using only provided CSS clases, since we would have to take into account text and background color.

### Describe the solution you'd like

Allowing a `severity` prop like the one present in `Tag` and `Button` would allow consistency on theme and quick access to styling a `Chip` component.

### Describe alternatives you have considered

I've tried styling by using a mix of custom classes and component classes, but this is harder to keep consistent with other components that handle this through props.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
