### ISSUE TITLE
Chips: Suggest input action

### ISSUE THREAD

**Issue by ineshbose** [primefaces/primevue#3869]
### Describe the feature you would like to see added

Entries can be added to the Chips component by pressing Enter (and separator), but some users aren't aware of this and could rather think of the input as a normal text field that doesn't require pressing enter.

For clarity and accessibility, it would be great to have a button say "Enter" on the right of the input, similar to Form Tags component of BootstrapVue - https://bootstrap-vue.org/docs/components/form-tags#basic-usage

![image](https://user-images.githubusercontent.com/56732164/232555142-9171e19e-2d18-4abb-a0fb-30a77c6d038b.png)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
