### ISSUE TITLE
Local filters do not work properly on TreeTable when there are repeated child values on different nodes

### ISSUE THREAD

**Issue by jehupacheco** [primefaces/primevue#387]
Local filter does not work properly on TreeTable when filtering by a repeated value on children nodes (although keys are unique)

This is the data passed to node:
```
 [
  {
    "key": "applications",
    "data": {
      "label": "Applications",
      "size": '100MB',
    },
    "children": [
      {
        "key": "applications-finder",
        "data": {
          "label": "Finder",
          "size": "70MB",
        }
      },
      {
        "key": "applications-photobooth",
        "data": {
          "label": "PhotoBooth",
          "size": "30MB",
        }
      }
    ],
  },
  {
    "key": "pictures",
    "data": {
      "label": "Pictures",
      "size": "3MB",
    },
    "children": [
      {
        "key": "pictures-finder",
        "data": {
          "label": "Finder",
          "size": "2MB",
        }
      },
      {
        "key": "pictures-lena",
        "data": {
          "label": "Lena",
          "size": "1MB",
        }
      }
    ],
  }
]
```

When filtering by a non-repeated value, everything works as expected
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/12038433/87555525-2f982a80-c67b-11ea-97ac-5030f2d9f095.png">

However, when filtering by a value that exists in more that one node, the table shows all the value (despite matching or not the filter)
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/12038433/87555666-6110f600-c67b-11ea-84ac-ead6c57d4a6f.png">

Here is a fiddle that replicates the issue
https://jsfiddle.net/w5rq4dej/21/

**Comment by cagataycivici** [comment]
@mertsincan Wdyt?

**Comment by cagataycivici** [comment]
May be fixed by;

https://github.com/primefaces/primevue/issues/424
