### ISSUE TITLE
InputSwitcher: "Disabled" prop do not pass the type check

### ISSUE THREAD

**Issue by Goomba41** [primefaces/primevue#3875]
### Describe the bug

App is created with vite and package.json contains next tasks: 

```
    "build": "run-p type-check build-only",
    "type-check": "vue-tsc --noEmit -p tsconfig.vitest.json --composite false",
```

When i build app for production some components attributes don't pass type check from vue-tsc. For example InputSwitch, in "Disabled" section:
`<InputSwitch v-model="checked" disabled />`

No matter how i write this: just `disabled`, `disabled="true"` or `:disabled="true"`, type checking when run build is provide same result: 

```
Argument of type '{ inputId: string; modelValue: any; class: string; disabled: string; }' is not assignable to parameter of type 'InputSwitchProps & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
  Object literal may only specify known properties, and 'disabled' does not exist in type 'InputSwitchProps & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
```

And this not only in InputSwitch and disabled prop:
```

Object literal may only specify known properties, and 'id' does not exist in type 'DropdownProps & VNodeProps & AllowedComponentProps & ComponentCustomProps'.

208                   id="OptionCatalogId"
                      ~~~~~~~~~~~~~~~~~~~~
```

So, what i do wrong?

### Reproducer

https://codesandbox.io/p/sandbox/infallible-water-ri5msz?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A9%7D%5D

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Could you tell us about your environment and create a reproducer using ts-issue template https://codesandbox.io/s/primevue-create-vue-typescript-issue-template-fb775d

**Comment by Goomba41** [comment]
> Could you tell us about your environment and create a reproducer using ts-issue template https://codesandbox.io/s/primevue-create-vue-typescript-issue-template-fb775d

For temporary solution i build project with only-build task `"build-only": "vite build"`, which skip type-check step

node is 18.15.0
npm is 9.5.0, but i use yarn (3.5.0)

related project dependencies is:
  "primeicons": "^6.0.1",
  "primevue": "^3.27.0",
  "vue": "^3.2.47",

devDep's is:
  "typescript": "~5.0.4",
  "vite": "^4.2.2",
  "vitest": "^0.30.1",
  "vue-tsc": "^1.2.0"
  "@vue/eslint-config-typescript": "^11.0.2",
  "@vue/test-utils": "^2.3.2",
  "@vue/tsconfig": "^0.1.3"

About reproducer: i don't know how to properly create this, cause problem appears only when i start build task in terminal with `yarn run build` (can codesandbox run commands in separate terminal?), and even more, when i forked your template a sandbox error occured:

![image](https://user-images.githubusercontent.com/11630715/233287779-968586f6-d159-480d-ab5d-dcd5b7b22bfb.png)
