### ISSUE TITLE
Dropdown: Treating the value of 0 as an empty value

### ISSUE THREAD

**Issue by mrdisa97** [primefaces/primevue#3880]
### Describe the bug

Hello,
I have a problem with Dropdown component, as it seems to be treating the value of 0 as an empty value.

I have object:
```js
const test = ref([
  { name: 'Some Status', value: 0 },
  { name: 'Other Status', value: 1 },
  { name: 'Etc.', value: 3 }
]);
```
I also have:

```js
optionLabel="name"
optionValue="value"
```
So when I select first option (with value of 0) my floating label goes in front of my selected option on focus leave, you can check that in codesandbox.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-error-wkb7x1

### PrimeVue version

3.26.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

all

**Comment by tugcekucukoglu** [comment]
Fixed with this issue https://github.com/primefaces/primevue/issues/3891

Please try to use latest version.
