### ISSUE TITLE
Menu components should allow the change of the component rendered by the "to" property of the MenuItem

### ISSUE THREAD

**Issue by DouglasAR01** [primefaces/primevue#3884]
### Describe the feature you would like to see added

You should be allowed to customize the rendered component by the `to` property of `MenuItems` in order to change it according to your App needs. For example, if you are using Nuxt, you may be using `NuxtLink` for your page routing, however, if you use any PrimeVue component that implements MenuItems, they will always render `RouterLink`.

### Is your feature request related to a problem?

If you are using a custom router component or a wrapper around an existing one (e.g NuxtLink), you may have to write a wrapper around the PrimeVue menu components.

### Describe the solution you'd like

The `to` property could include a `component` property that accepts the component that should be rendered. For example:

`to: {
    path: '/',
    component: NuxtLink
}`

**Comment by DouglasAR01** [comment]
There is a new issue related to this. If you are using Nuxt 3 with Nuxt 18n 8.0.0-beta.13, the RouterLink generated by the `to` option does not allows navigation. It must be a NuxtLink. My current workaround is, instead of using `to`, use `command` with a navigateTo.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
