### ISSUE TITLE
Column Resizer not working when column is Frozen in Primevue

### ISSUE THREAD

**Issue by sahil-xyrintech** [primefaces/primevue#3886]
### Describe the bug

https://stackblitz.com/edit/angular-ythpnk?file=src%2FApp.vue
I'm using a primeval table and there is the first column is frozen when I try to resize the frozen column it doesn't work. other columns that are not frozen are resized perfectly.

### Reproducer

https://stackblitz.com/edit/angular-ythpnk?file=src%2FApp.vue

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

I checked the code in inspect of the browser and I found the frozen is true, removed the p-column-resizer element from DOM.

**Comment by tugcekucukoglu** [comment]
Resizing is not available on frozen columns. Still if there is more demand, we'll definitely reconsider.

**Comment by KommuSoft** [comment]
I found a "workaround" for this. One can write the resizer manually, like:

```
<DataTable ref="dt">
  <Column :frozen="true">
    <template #header>
        <span @mousedown="onResizeStart" class="p-datatable-column-resizer" data-pc-section="columnresizer"/>
    </template>
  </Column>
</DataTable>
```

and then in the method, let the `DataTable` handle it:

```
methods: {
  onResizeStart (e) {
    this.$refs.dt.onColumnResizeStart(e);
  }
}
```
