### ISSUE TITLE
DataTable (Virtual Scroll): Cannot set properties of undefined (setting 'tabIndex')

### ISSUE THREAD

**Issue by LiamRiddell** [primefaces/primevue#3888]
### Describe the bug

The issue has been raised and closed before incorrectly see #3650. The major DataTable changes mentioned in #3682 does not fix this issue.

![image](https://user-images.githubusercontent.com/3812154/233981620-d928c5ca-f661-4e8f-aa3b-4cf060a10318.png)
Source:
https://github.com/primefaces/primevue/blob/0cedd4813a1657981b1d7d29f61e05e3a54d92ee/components/lib/datatable/DataTable.vue#L1001

### Reproducer

https://stackblitz.com/edit/angular-7eg97z?file=src%2FApp.vue

### PrimeVue version

3.27.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open developer console.
2. Select and existing row on screen and you should see a log message with "Index X". 
3. Scroll down a few hundred rows and click another row. It throws an exception: 
![image](https://user-images.githubusercontent.com/3812154/233979940-5590eee9-32b6-450d-b4ef-51b728aaeb96.png)
4. Clicking the row again will then show the correct log message "Index X".

### Expected behavior

There shouldn't be an error and the row is selected correctly the first time and does not require a secondary click to change the row correctly.

**Comment by Cersin** [comment]
same problem

**Comment by chrisnoden** [comment]
I get the error clicking on any row that isn't on page 1 of a paginated datatable

**Comment by itsserbin** [comment]
same problem

**Comment by nyiri** [comment]
> I get the error clicking on any row that isn't on page 1 of a paginated datatable

The same here.
It's pretty disturbing...

**Comment by barthy-koeln** [comment]
I have opened PR #3984 to fix this issue. I have mainly tested it on paginated datatables. 
The problem of removed DOM nodes is the same though.

**Comment by LiamRiddell** [comment]
Great, thank you @barthy-koeln. I was going to come back around and put a PR in but you beat me to it!

**Comment by 1993garik** [comment]
Hello  @barthy-koeln, the problem solution is not published yet, right ?

**Comment by christianschoenmakers** [comment]
We use the row-click emit to trigger a redirect to a new page, this is also resulting in the same error.

**Comment by barthy-koeln** [comment]
@1993garik and the rest :)

I have given up on keeping the PR up to date. I was going to look into actually fixing the `tabindex` changes but got discouraged seeing the 5000+ lines files of vanilla JS and direct DOM manipulation in Vue.js files.

**Comment by reksc** [comment]
I'm getting the same error at **3.41.1**.

`targetRow` is null and so setting `tabIndex = '0'` fails.
