### ISSUE TITLE
Listbox: Unwanted behavior?

### ISSUE THREAD

**Issue by csakis** [primefaces/primevue#3893]
### Describe the bug

1. Open the StackBlitz demo below
2. Click on New York. You can see that the Selected city is New York.
3. Click on New York again. The selected city will be null.

I believe this is unwanted behavior. The Selected city should not be toggled on a click event. If The user clicks on the Lit object it should remain selected. 

### Reproducer

https://stackblitz.com/edit/angular-xug2sz?file=src/App.vue

### PrimeVue version

3.27.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open the StackBlitz demo below
2. Click on New York. You can see that the Selected city is New York.
3. Click on New York again. The selected city will be null.

### Expected behavior

When the user clicks on a list element, it should remain selected and not toggled.

**Comment by mertsincan** [comment]
Please use `:metaKeySelection="false"` for this behaviour.

Best Regards,

**Comment by csakis** [comment]
It works without the `:`
`metaKeySelection="false"`
Thanks
