### ISSUE TITLE
DataTable: Grouping with Pagination is Broken

### ISSUE THREAD

**Issue by pyramid-johng** [primefaces/primevue#3896]
### Describe the bug

When using the `paginator` set to `true` the grid grouping fails after page one.

The first `rows` rows are grouped correctly on page one, then on subsequent pages, every row forms a group of one, even though it should be grouped with a preceding row.

All the examples on the website are conveniently displaying all rows at once, so this defect is not evident.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-42u3s1?welcome=true

### PrimeVue version

3.27

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to the example and witness the behavior; it is the Group sample from the website.
2. Add the `:paginator=true` (already done).
3. Remove the `scrollable` and `scrollheight` attributes (already done).
4. Set `:rows=5` or any value less than size of data collection.
5. Observe first page of `rows` is grouped correctly.
6. Go to another page (page 2).
7. Observe every row forms its own group, in spite of there being formable groups.

### Expected behavior

Grouping should correctly re-initialize each time new `items` are bound to the `DataTable`.  Not expecting any carry-over from previous/next pages, just correct behavior regardless of the `items` chosen.

**Comment by sarkariajatt** [comment]
I am also facing the same issue.
If you have a number of rows 15 and pagination is on with row group, then the first page show one grouped row with 15 items inside, and on next page it shows multiple groups with same name with one item inside
![Screenshot_29](https://github.com/primefaces/primevue/assets/21108847/bea59e13-0880-48ff-84eb-2a41856b0ca5)
![Screenshot_31](https://github.com/primefaces/primevue/assets/21108847/437c98bf-d2b0-448e-9681-0d04fa922b4a)
![Screenshot_32](https://github.com/primefaces/primevue/assets/21108847/1bd6ffb8-ff54-49ae-8669-ff57e0332e2d)
![Screenshot_30](https://github.com/primefaces/primevue/assets/21108847/b0283b79-c2e1-4eb6-b988-e1876dbbdd7e)

**Comment by levitomer** [comment]
Same here
