### ISSUE TITLE
Toast: icon slots should receive useful information as scope

### ISSUE THREAD

**Issue by service-paradis** [primefaces/primevue#3897]
### Describe the bug

You added support for custom icons in Primevue 3.27.0.

It looks like it is missing some needed properties to work as expected for the Toast component. For example, it would be useful to receive `severity` as scope for the slot `icon` in order to display the expected icon according to the message severity. The complete message could also be sent as scope to give more flexibility like it is for the slot `message`.

### Reproducer

https://codesandbox.io/s/strange-bassi-551rf1?file=/src/App.vue

### PrimeVue version

3.27.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Version 1.50.114 Chromium: 112.0.5615.49 (Build officiel) (64 bits)

### Steps to reproduce the behavior

_Ignore the CodeSandbox above since it does take into account the slot..._

1. Create a new Toast component
2. Customize the icon:
```vue
<Toast>
    <template #icon>
      <FontAwesomeIcon
        :icon="['far', 'circle-xmark']"
        size="xl"
        class="p-icon p-toast-icon-close-icon"
      />
    </template>
</Toast>
```
3. Try to customize the icon depending on severity received...

### Expected behavior

I would expect the severity to be available for the `icon` slot so we can customize it accordingly.

**Comment by tugcekucukoglu** [comment]
Toast has a `container` slot now. I suggest check the headless demo: https://primevue.org/toast

**Comment by GideonRoose** [comment]
> Toast has a container slot now.

In my opinion, that is not a (good) solution to this problem, though. Going headless means rewriting most of the component, instead of just using the pass through options. In my case, I can completely style the component exactly how I want using the pass through options, except that I need to use a custom icon for each severity type. Now I have to rewrite everything in the container instead of just using the pass through options just because of that custom icon.

I feel there is no reason to have this 'icon' slot in the first place if it doesn't have the 'severity' information.

**Comment by dominique-mueller** [comment]
Well, for what it's worth, you can do some trickery with classes to get it working.

In your passthrough options, define any custom class based on the severity, and then use it as a condition in the template.

For example:

```vue
<Toast
  :pt="{
    icon: ({ props: toastProps }) => ({
      class: [
        {
          'is-success': toastProps.message?.severity === 'success',
          'is-error': toastProps.message?.severity === 'error',
        },
      ],
    }),
  }"
>
  <template #icon="{ class: className }">
    <svg v-if="className.includes('is-success')" :class="className">
      <!-- path -->
    </svg>

    <svg v-if="className.includes('is-error')" :class="className">
      <!-- path -->
    </svg>
  </template>
</Toast>
```

Still, icon slots for each severity would've been a much nicer API to solve this ...

**Comment by inkbeard** [comment]
Yeah, I ended up with a similar approach to @dominique-mueller with https://github.com/inkbeard/monorepo/pull/301. I agree though, the severity would be extremely helpful since the icons are most likely to change based on the severity.

**Comment by clowcher** [comment]
+1 for adding severity to the scope of the Icon slot. We don't want to rewrite the whole thing, just customize the icon based on severity.
