### ISSUE TITLE
MenuBar: Html support

### ISSUE THREAD

**Issue by krishnaprasad-g** [primefaces/primevue#3901]
### Describe the feature you would like to see added

I see this is fixed in primeng - https://github.com/primefaces/primeng/issues/4370 and looking for similar in PrimeVue as well.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
