### ISSUE TITLE
Calendar: prevent repeat on increase icon and decrese icon mouse down and up event for time picker

### ISSUE THREAD

**Issue by seyfer** [primefaces/primevue#3916]
### Describe the feature you would like to see added

Add a parameter to disable repeated increases and decreases of the value for the time picker on the mouse up or down hold.
It should be doing just one button click without `repeat()` of events. 

It happens currently in the Calendar component code in these handlers
```
@mousedown="onTimePickerElementMouseDown($event, 0, 1)"
@mouseup="onTimePickerElementMouseUp($event)"
```

### Is your feature request related to a problem?

Currently, if I have the time picker enabled if I press and hold the up or down icon - it will automatically keep increasing or decreasing values.
It can cause a problem in the case when I want to have some logic to connect two time-pickers.
Let's say I have startTime time picker and endTime time picker. I want to set the end time always equal to the start time + 15 mins.

For that, I use slots for slots and custom handlers

```
<template #incrementicon>
            <span
              class="pi pi-chevron-up p-icon"
              style="font-size: 16px"
              @click="startTimeIncrementClick"
            />
          </template>
          <template #decrementicon>
            <span
              class="pi pi-chevron-down p-icon"
              style="font-size: 16px"
              @click="startTimeDecrementClick"
            />
          </template>
```

I also have validation with VueValidate on start and end times, which is asynchronous.

When I do just one click - it works perfectly. 

The problem is, if a user holds the mouse up or down icon intentionally or by accident - events keep repeating.
And it happens so fast, that sometimes the end time is not able to update in time and VueValidate validation validates an old time, showing an error, or the end time picker shows the time 1 step before the last update.
and sometimes when I want to make just one click, I hold the mouse a bit longer and repeat events start to happen.

### Describe the solution you'd like

Some kind of property on the Calendar component, something like 
`repeatIncrement` and `repeatDecrement` can be set to false, and that is true by default.

When set to false, this repeat should not happen

```
        onTimePickerElementMouseDown(event, type, direction) {
            if (this.isEnabled()) {
                this.repeat(event, null, type, direction);
                event.preventDefault();
            }
        },
```

but should consider mouse down as just one click.

### Describe alternatives you have considered

Another option could be to set a `timeChangeRepeatTime`, something like that, for this code

```
repeat(event, interval, type, direction) {
            let i = interval || 500;
```

to be set from the Calendar component property. probably if I could increase this interval to 1000-2000 from default 500, then the issue would be solved.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
