### ISSUE TITLE
DataTable and TreeTable: new Paginator dropdown slots

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#3921]
### Describe the bug

3.27 introducted custom slots for icons. Unfortunately some of them are missing.
When using DataTable I cannot customize paginator icons for dropdowns `RowsPerPageDropdown` and `JumpToPageDropdown`.

As can be seen in code https://github.com/primefaces/primevue/blob/master/components/lib/paginator/Paginator.vue, 
paginator is not exposing slots to pass to the dropdowns, so using paginator, dataTable, any any other component that is using paginator forces user to use icon provided by library.

### Reproducer

-

### PrimeVue version

3.27

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Ability to customize dropdown icons

**Comment by Magiczne** [comment]
@tugcekucukoglu This is a bug that prevents us from updating to the newer versions of primevue, which includes many bugfixes. Is this gonna be addressed soon?

**Comment by tugcekucukoglu** [comment]
Definitely, I will implement this feature as soon as possible. I am unable to support you on Github as I am busy with Tailwind samples these days.

**Comment by Magiczne** [comment]
Sure, thanks for info!
