### ISSUE TITLE
New passthrough(pt) property implementation for Data Components

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#3924]
- [x] VirtualScroller
- [x] Paginator
- [x] DataTable
- [x] DataView
- [x] DataViewLayoutOptions
- [x] OrderList
- [x] OrganizationChart
- [x] PickList
- [x] Tree
- [x] TreeTable
- [x] Timeline
- [x] Column
- [x] ColumnGroup
- [x] Row

**Comment by Skyfox64** [comment]
@tugcekucukoglu ,I believe Column.d.ts's ColumnProps is missing pt. No way to use any of the passthroughs without it.

**Comment by tugcekucukoglu** [comment]
Added. Thanks!
