### ISSUE TITLE
Calendar: When selection mode is range allow user to set both start time and end time for the date range

### ISSUE THREAD

**Issue by eneeio-nm** [primefaces/primevue#3926]
### Describe the feature you would like to see added

Currently when implementing the `Calendar` component, and setting the `selection-mode` to `range` and having `show-time` enabled, the user is only able to set one `time` option for the dates selected.

### Is your feature request related to a problem?

Without this feature users would not be able to specify a **start time and end time** for the dates they've selected. In some cases a user might want to select a single date, but be able to say that they need data returning between two particular times on that date.

### Describe the solution you'd like

Something like this should do:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/127733587/236426675-8ad6d597-2837-4cf0-85ca-47515937ad48.png">

### Describe alternatives you have considered

[Vue Datepicker](https://vue3datepicker.com/props/modes/#range) allows users to do this. It would be a shame if we would be forced to implement a 3rd party date picker instead of using the PrimeVue `Calendar`.

**Comment by eneeio-nm** [comment]
Looks like this has been previously requested - #3318 - back in Nov 2022

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3318
