### ISSUE TITLE
Missing steps buttons Component

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#393]
In many places I had to implement some king of a group of buttons like `SelectButton` but much like steps.

The SelectButton looks like this:
![image](https://user-images.githubusercontent.com/13495631/87801587-da5d4400-c847-11ea-8b80-cd843488262f.png)

But the design is not intuitive enough for users. I also was thinking about `Breadcrumbs` but it lacks of functionality like template or selected.

The ideal look for the component could be like this:
![image](https://user-images.githubusercontent.com/13495631/87801938-5d7e9a00-c848-11ea-8990-5523aebfd6fc.png)
https://semantic-ui-vue.github.io/?ref=madewithvuejs.com#/elements/step

Or, I was also thinking if I can just apply some style to the `SelectButton` and make it like this:
![Untitled-Steps](https://user-images.githubusercontent.com/13495631/87803518-7be59500-c84a-11ea-8a6e-9f9cb507d74f.png)

What do you think guys?

**Comment by fairking** [comment]
BTW I aware about the `Steps` component (https://www.primefaces.org/primevue/showcase/#/steps)
But it is more about switching/progressing the status rather than going through forms.

**Comment by cagataycivici** [comment]
SelectButton supports any content with templating so it could be done already with some custom css. A new component doesn't look necessary but a demo would be nice to show how to implement a steps component for sure.
