### ISSUE TITLE
Galleria: navigate on swipe

### ISSUE THREAD

**Issue by tmlmt** [primefaces/primevue#3932]
### Describe the feature you would like to see added

It would be enable navigating on swipe, instead of having to click on the navigator elements. 

### Is your feature request related to a problem?

Mobile-friendliness

### Describe the solution you'd like

A new property `navigateOnSwipe`, turned on by default

### Describe alternatives you have considered

Programming the feature for my own need, for instance using VueUse's `useSwipe()` function. 

### Additional context

Typical use case, Galleria with Navigator and Indicator elements: 

![image](https://user-images.githubusercontent.com/10244927/236564299-b048b732-b77b-497e-a4d3-d8db55b4ae63.png)

**Comment by mrc-bsllt** [comment]
I have the same request, does anyone have any news?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by haiderchristoph** [comment]
@tugcekucukoglu Hi! Any updates on this matter? Are you planning to add swipe support? Or is there a proper workaround for this?
