### ISSUE TITLE
OrderList: make the component disabled (view only)

### ISSUE THREAD

**Issue by it-emkabetech** [primefaces/primevue#3934]
### Describe the feature you would like to see added

sometimes we need to make the whole component disabled (view only) after some function

**Comment by it-emkabetech** [comment]
hi @tugcekucukoglu 
any concern about this request?

**Comment by tugcekucukoglu** [comment]
We need more community demand for this new feature. So this issue can be moved to [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

Thank you.
