### ISSUE TITLE
TreeTable Column: Can not access body slot props

### ISSUE THREAD

**Issue by darmanovic** [primefaces/primevue#3937]
### Describe the bug

While using TreeTable component we encountered a need to make custom body for a column. Using `<template #body="slotProps">` for `Column` component custom template can be inserted, but slot props **can not be accessed**!

```javascript
<Column header="Test">
  <template #body="slotProps">
    <div>{{ slotProps.data.field1 }}</div> <!-- slotProps.data is undefined -->
  </template>
</Column>
```

I'm expecting behaviour as with DataTable Column component.

### Reproducer

https://codesandbox.io/s/serene-browser-p0phg2

### PrimeVue version

<=3.28.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome

### Expected behavior

Exactly the same behaviour as in DataTable.

**Comment by tugcekucukoglu** [comment]
Please use `slotProps.node` instead of `slotProps.data`

**Comment by wa3l** [comment]
@tugcekucukoglu the docs still say `data` btw. https://primevue.org/treetable/#api.column.slots

**Comment by kimhanui** [comment]
@tugcekucukoglu still now [slotProps.node](https://primevue.org/treetable/#api.column.slots)

**Comment by travs15** [comment]
I had to use it like: `slotProps.node.data`

**Comment by giuliovivian** [comment]
> I had to use it like: `slotProps.node.data`

Works for me on v4.3.4

**Comment by bilalaslam777** [comment]
How to get the index of the row? I tried slotProps.index but no success. Can someone help please?
