### ISSUE TITLE
Steps: Make it possible to take vertical steps

### ISSUE THREAD

**Issue by r331** [primefaces/primevue#3939]
### Describe the feature you would like to see added

Often you need to take vertical steps to navigate. Currently, the library only has the option of placing the steps horizontally.

### Is your feature request related to a problem?

Feature request

### Describe the solution you'd like

Best solution you could find here - https://stackblitz.com/angular/vokyygxqeva?file=src%2Fapp%2Fstepper-vertical-example.ts

<img width="325" alt="image" src="https://github.com/primefaces/primevue/assets/34960570/c02fcee6-e620-456d-a0f9-4615933bdce7">

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
