### ISSUE TITLE
Toast: No PrimeVue Toast provided!

### ISSUE THREAD

**Issue by drAliRahnema** [primefaces/primevue#3942]
### Describe the bug

hi 
when i want to use toast in composition api (not in setup function) it gives me error No PrimeVue Toast provided!

### Reproducer

http://a.b

### PrimeVue version

3.28.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

chrome

### Steps to reproduce the behavior

create a composition api

import { useToast } from "primevue/usetoast";

export default async function callApi<T>():Promise<any>{

const { $i18n, $toast } = useNuxtApp();
const toast = useToast();
toast .add({})
...
}

### Expected behavior

it must show toast
---------------------------------------

**Comment by bahadirsofuoglu** [comment]
Hi, You can find an example below for Composition API, Nuxt and toast.

https://github.com/primefaces/primevue-examples/tree/main/nuxt3-quickstart

**Comment by Dubemtopsite** [comment]
Hi @drAliRahnema were you able to solve the issue

Mine was working only for me to restart server and it start showing me same error


![image](https://github.com/primefaces/primevue/assets/31639636/4ed5e096-d35e-4bf8-9b2b-1c4a9fd549b9)

**Comment by xianxuhua** [comment]
When using toast in primevue, you have to declare the toast tag, if you want to use it in ts/js files, you can write the Toast tag in app.vue, then create a new toast.js file and write the following

// toast.js
const nuxtApp = useNuxtApp();
const getToast = () => nuxtApp.vueApp.config.globalProperties.$toast
const toast = {
    add(msg: any) {
        getToast().add(msg)
    }
}
export default toast


// request.js
import toast from '@/utils/toast'
if (404) {
  toast.add({severity:'error',
    summary: 'not found',
    detail:'not found',
    life: 3000
  });
}

**Comment by helderhernandez** [comment]
@xianxuhua Thanks for the guidance,

I share code for a composable element that returns toast (ToastServiceMethods), which will allow you to invoke it both within another **composable** and in a **component**.

File: `composables/usePVToastService.ts `
```typescript
import { useToast } from "primevue/usetoast";

export const usePVToastService = () => {
    const nuxtApp = useNuxtApp();
    const getToast: typeof useToast = () => nuxtApp.vueApp.config.globalProperties.$toast
    const toastService = getToast();
    return toastService
}
```

## Example of call inside another composable
File: `composables/useApiFetch.ts `

```typescript
export const useApiFetch: typeof useFetch = (request, opts?) => {
    const config = useRuntimeConfig()
   // call my composable
    const toastService = usePVToastService();

    const apiFetch = useFetch(request, {
        baseURL: config.public.apiURL,

        onResponseError({ request, response, options }) {
            toastService.add({    // use 😃 
                severity: 'error',
                summary: 'Error 😢 ',
                detail: "Error bla bla bla",
            });
        },
        ...opts
    })

    return apiFetch
}
```

## Example of a call within a component:
File: `composables/useApiFetch.ts `

```typescript
<template>
    <div class="container-login">
        <h1>Iniciar Sesión</h1>

        <form @submit.prevent="submitForm">
                 <!--  your code -->
        </form>
    </div>
</template>

<script setup lang="ts">
// your code...

 // call my composable
const toastService = usePVToastService();

// your code ....

const submitForm = async () => {
    // your validation...

    if (error) {
       // use 😃 

        toastService.add({
            severity: 'warn',
            summary: 'Invalid form data',
            detail: "Bla bla",
            life: 5000,
        });

        return;
    }
    // your code....
};
</script>
```
