### ISSUE TITLE
SpeedDial: Mask and SpeedDial itself prevent pointer events and speedDial does not close using item slot

### ISSUE THREAD

**Issue by michastubi** [primefaces/primevue#3945]
### Describe the bug

1. When using the SpeedDial, all elements within the mask area are not clickable. 
2. Even if the mask is deactivated, all elements in the SpeedDial area are not clickable.
3. When using the item slot, the SpeedDial does not close after an item is selected.

The example in the codesandbox shows the problem quite well.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-j3swv6?file=%2Fsrc%2FApp.vue%3A25%2C20

### PrimeVue version

3.28.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1.1. Add a SpeedDial Component with mask = true
1.2. Add some clickable elements in the area where mask should appear.
1.3. Try to click the elements

2.1. Add a SpeedDial Component
2.2. Add some clickable elements in the area where speedDial items should appear
2.3. Try to click the elements

3.1. Add a SpeedDial Component with item slot
3.2. Click on one of the items
3.3. The SpeedDial does not close

### Expected behavior

1. Elements should be clickable
2. Elements should be clickable
3. SpeedDial should close

**Comment by michastubi** [comment]
I added some css to the codesandbox which can be used as a workaround to solve the first two problems. (Uncomment in the sandbox to activate). But I think there should be a better solution?

``` 
:deep(.p-speeddial) {
  pointer-events: none;
}

:deep(.p-speeddial .p-speeddial-button) {
  pointer-events: auto;
}

:deep(.p-speeddial-mask) {
  pointer-events: none;
}
:deep(.p-speeddial-mask.p-speeddial-mask-visible) {
  pointer-events: auto;
}
```

**Comment by tugcekucukoglu** [comment]
You could use with the next version

```
<SpeedDial :model="items" mask direction="up" :style="{ right: 0, bottom: 0 }">
      <template #item="{ item, onClick }">
            <Button :label="item.label" @click="onClick" />
      </template>
/SpeedDial>
```
