### ISSUE TITLE
 'dialogRef' is of type 'unknown'

### ISSUE THREAD

**Issue by Bowis** [primefaces/primevue#3947]
### Describe the bug

When using the dynamic dialog, accessing the dialogRef and its data props you can send, like: 

```
const showUser = (userId: string) => {
  dialog.open(PlayerInfoOverview, {
    props: {
      header: "User",
      style: {
        width: "50%",
      },

      modal: true,
    },
    data: {
      userId,
    },
  });
};
```

```
const dialogRef = inject("dialogRef");
const userId = dialogRef.value.data.userId;
```

results in  `dialogRef' is of type 'unknown`. I can't seem to find a good type I can assign to the dialogRef. 

### Reproducer

-

### PrimeVue version

3.26.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by dipbhi** [comment]
Assuming you are referring to the TypeScript error,

Using `const dialogRef = inject("dialogRef") as any;` should remove the error.

**Comment by adrianrudnik** [comment]
just came across this. A type is available via

```js
import type { DynamicDialogInstance } from 'primevue/dynamicdialogoptions'

const dialogRef = inject<Ref<DynamicDialogInstance>>('dialogRef')
```

**Comment by jackytank** [comment]
> just came across this. A type is available via
> 
> ```js
> import type { DynamicDialogInstance } from 'primevue/dynamicdialogoptions'
> 
> const dialogRef = inject<Ref<DynamicDialogInstance>>('dialogRef')
> ```
> 
> as with anything injected, it might be undefined, so use optional chaining for close.
> 
> ```js
> dialogRef?.value.close()
> ```

I love you dude

**Comment by matiasbellovisma** [comment]
You're the boss
