### ISSUE TITLE
Dropdown: Performance Issue with Dropdown slots

### ISSUE THREAD

**Issue by oliviermattei** [primefaces/primevue#3954]
I am working on a form with multiple dropdowns, I detected a performance issue using slots to contextualize my value. 

Here is a simple example that just displays a counter when my method is called
```
<script lang="ts" setup>
const options = ['a', 'b', 'c']
const selected = ref()

const transCount = ref(0)
function trans(value) {
  transCount.value = transCount.value + 1
  return `_${value}`
}
</script>

<template>
  <div>trans : {{ transCount }}</div>

  <Dropdown
    v-model="selected"
    :options="options"
  >
    <template #value="{ value }">
      {{ trans(value) }}
    </template>
  </Dropdown>
</template>
```

When the page is loaded, the counter shown : 101

After selecting 1 option : 608 
etc...

The problem should be resolved using a computed with computed inside but in my case, I need to generate the value on the fly

If I use a slot #option the counter increments faster multiply by the number of dropdown the page is much slower

**Comment by barthy-koeln** [comment]
Hey, your example produces an infinite loop. When the dropdown renders, you change the `transcount`, which re-renders the entire component, which re-renders the `transcount`, … Until you reach an exception of "maximum call stack exceeded":

> [Vue warn]: Maximum recursive updates exceeded in component <dropdown-test>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

You can see the same behaviour without any additional components:

```vue
<template>
  <div>trans : {{ transCount }}</div>

  <button @click="selected++">{{ trans(selected) }}</button>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const selected = ref(0)
const transCount = ref(0)
function trans(value) {
  transCount.value = transCount.value + 1
  return `_${value}`
}
</script>
```
In your example, you can use `v-memo` to momoize the value rendering:

```vue
  <Dropdown v-model="selected" :options="options">
    <template #value="{ value }">
      <span v-memo="[value]">{{ trans(value) }}</span>
    </template>
  </Dropdown>
```

This will only retrigger a render when `value` changes. You could also use `selected` instead, or any other source of reactivity, except `transcount`.

[More about v-memo in the docs](https://vuejs.org/api/built-in-directives.html#v-memo)

___

All of this being said, I'm unsure to which extent this could be done in the dropdown component internals. I just wanted to provide a possible fix.
