### ISSUE TITLE
Accordion: pt options for root applied twice

### ISSUE THREAD

**Issue by jfitzsimmons2** [primefaces/primevue#3955]
### Describe the bug

I'm experimenting with global pt options and noticed that when setting this pt option in the global config
```js

  accordion: {
    root: {
      class: "root-global"
    }
  }

```

"root-class" is applied twice, once to the root of the `Accordion`, and once to the root each `AccordionTab` component. Compare this with the behavior shown in the wireframe, and it seems the class should only be applied to the `Accordion` root.

### Reproducer

https://codesandbox.io/p/sandbox/happy-ioana-lv0r02

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Look at the PT options being set for accordion
2. Inspect the accordion and notice the class being applied twice

### Expected behavior

The class should only apply to the `Accordion` root.

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primevue/commit/57b6f2c63a23d8ad8ab472d08ad1b6074904aa00#diff-5ca99ff4b8455dde74bcbef1185985db62941fe2f5d31105e5329b966be66a5d
