### ISSUE TITLE
Button: add ghost version

### ISSUE THREAD

**Issue by ezmemoar** [primefaces/primevue#3956]
### Describe the feature you would like to see added

It would be nice to add a ghost version for button like buefy, which has light color background and dark color text

![image](https://github.com/primefaces/primevue/assets/48541679/2251c2a9-dfc2-4fcc-ab13-94955a9434d3)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
