### ISSUE TITLE
Table ALL: add event, click row 

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3957]
### Describe the feature you would like to see added

For all tables and trees, add a click event to a row.A very necessary thing, now if you make SelectionMode="checkbox" it is impossible to process a click on the line itself. And in general, it is often necessary to process a separate click event on the line itself without highlighting

I would also like a cell click event

I would also like a setting for SelectionMode="checkbox" so that you can select both the checkbox and the usual click on the row

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
