### ISSUE TITLE
PassThrough is not working with Tailwind in Nuxt 3

### ISSUE THREAD

**Issue by Pawel2505** [primefaces/primevue#3960]
### Describe the bug

PassThrough feature is not working with Tailwind classes in Nuxt 3. It works fine with classes from <style> tag, however cannot see the tailwind classes.

### Reproducer

nuxt 3

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Create Nuxt 3 project.
2. Install PrimeVue (as in docs) and Tailwindcss Nuxt 3 plugin (https://nuxt.com/modules/tailwindcss)
3. Add the Button with a tailwind classes to a component:
```
<Button label="Add"  :pt="{ 
      root: { class: 'bg-gray-600 border-gray-600' } 
  }" />

```           
4. The Button is still blue (with default 'primary' severity)

### Expected behavior

The button should change its background color into gray.

**Comment by jfitzsimmons2** [comment]
Prime's styles are likely overriding tailwind because of specificity. You can try removing the prime CSS or changing your [tailwind config to use !important](https://tailwindcss.com/docs/configuration#important)

**Comment by hjJunior** [comment]
Also, If you're using new versions of tailwind, you can prefix your class names with `!` which will make that class be marked as `important`

eg.

Instead of `w-5`, you can use `!w-5`

https://tailwindcss.com/docs/configuration#important-modifier

**Comment by notflip** [comment]
I saw on the homepage that there's a "Preview of unstyled Primevue", does this mean it's in beta? Can we use this functionality?

**Comment by tugcekucukoglu** [comment]
With the latest version, Tailwind has become easier to implement. You can use and/or override the PrimeVue built-in Tailwind. For further information https://primevue.org/tailwind/

**Comment by MatanelGordon** [comment]
I'm experiencing the same issue, primevues' styles has **more specificity** than tailwinds'. 

So far i've encountered this problem only in nuxt projects...
 
Specifications:
 - Using `Nuxt3`
 - primevue version: `3.34.1`
 - taiwind version: `3.3.3`

**Comment by philipimperato** [comment]
I finally picked `primevue` over all others because I loved it... and now I find out it doesn't even work yet!

**Comment by valh1996** [comment]
@MatanelGordon,
> I'm experiencing the same issue, primevues' styles have **higher specificity** than tailwinds'.
> 
> So far i've encountered this problem only in nuxt projects...
> 
> Specifications:
> 
> * Using `Nuxt3`
> * primevue version: `3.34.1`
> * taiwind version: `3.3.3`

Do you have follow the official doc? https://primevue.org/tailwind/#csslayer :

> If you are using Nuxt modules of [PrimeVue](https://primevue.org/nuxt) and [Tailwind](https://tailwindcss.nuxtjs.org/), the layer order is required to be configured with the [cssLayerOrder](https://primevue.org/nuxt/#layerorder).

**Comment by MatanelGordon** [comment]
Hy @valh1996.
no, I havent done it since it didnt exist 😅

will try soon enough

**Comment by philipimperato** [comment]
Not sure why this isn't explicitly in the docs, but I got it to working with a custom theme using:

```
// tailwind.config.js
content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}"
],
```

Created a custom them and added it to `tailwind.css`

```
// assets/cess/tailwind.css
@import 'tailwindcss/base' layer(tailwind-base);
@import './custom-solo-theme.css' layer(primevue);
@import 'tailwindcss/components' layer(tailwind-utilities);
@import 'tailwindcss/utilities' layer(tailwind-utilities);
```

Insure you have postcss installed:
```
postcss: {
    plugins: {
      "postcss-import": {}
    }
},
```

Then the docs suggestion of `cssLayerOrder: 'tailwind-base, primevue, tailwind-utilities',` works!
