### ISSUE TITLE
DataTable: Clear filter icon is there but not visible in table column header

### ISSUE THREAD

**Issue by gszentesi** [primefaces/primevue#3961]
### Describe the bug

Hi All!

I created a table with some cols filterDisplay row mode. InputText control was added to the header template. 

When I filter on any rows but first, the clear filter icon is not visible. If I filter on the first column as well, all the icons appears where a filter applied.

Could you please check it?

Thanks
Gergely

### Reproducer

https://codesandbox.io/s/8tbsbm

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

You can reproduce the issue on your official page: [https://primevue.org/datatable/](https://primevue.org/datatable/).

In the **Filter basic** example.
1. Filter Name column with 'J', then filter Country col with 'A'. Both crossover funnels are visible. 
![image](https://github.com/primefaces/primevue/assets/130458518/4331d305-8953-49e4-87a4-eac28252026f)

2. If you delete the 'J' from Name column, then both disappear. 
![image](https://github.com/primefaces/primevue/assets/130458518/e32ef5f4-f0bc-4417-aa81-6acb14c55ad0)

4. If you filter Name col again, then the second funnel will appear again. 
![image](https://github.com/primefaces/primevue/assets/130458518/53128488-57f8-45da-be21-c47fbb54931c)

### Expected behavior

If a filter is applied on any column then the clear filter cross over funnel icon should be visible.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3959
