### ISSUE TITLE
dropdown: Custom class passthough does not take effect

### ISSUE THREAD

**Issue by duyudong2010** [primefaces/primevue#3968]
### Describe the bug

  <Dropdown
      v-model="selectedCity"
      :options="cities"
      optionLabel="name"
      placeholder="Select a City"
      :pt="{
        root: { class: 'w-full md:w-14rem' },
        item: ({ props, state, context }) => ({
          class: context.selected
            ? 'test1'
            : undefined,
        }),
      }"
    />

<style>
.test1 {
  background-color: var(--green-600);
}
</style>
`
Custom class “test1“” cannot passthrough, but I use 'bg-green-700' in primeflex, no problem

### Reproducer

https://stackblitz.com/edit/7jvbkx?file=src%2FApp.vue

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

109.0.5414.120 chrome win-x64

**Comment by tugcekucukoglu** [comment]
PrimeFlex uses the `important` rule of CSS's which means these classes have the highest priorities to all styles/classes.

```
<style>
.test1 {
  background-color: var(--green-600) !important;
}
</style>
```
