### ISSUE TITLE
Editor: Uncaught (in promise) TypeError: module is not a constructor

### ISSUE THREAD

**Issue by medusiora** [primefaces/primevue#3971]
### Describe the bug

Can not load quill module in dev mode, But it works on production mode.

Error message
![image](https://github.com/primefaces/primevue/assets/38559820/86858a7e-cea5-4140-848b-0e4b866eb395)
![image](https://github.com/primefaces/primevue/assets/38559820/58a9f066-eb89-40d0-9f1f-7c9cab9a6a5f)

dependencies
```
...
"nuxt": "^3.5.0",
...
```
devDependencies
```
...
"unplugin-vue-components": "^0.24.0",
"primeicons": "^6.0.1",
"primevue": "^3.18.1",
"quill": "^1.3.7",
...
```

Node.js version
v18.16.0

### Reproducer

Nuxt 3

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

Error when init Editor component

**Comment by jeverduzco** [comment]
I have the same problem.

![Screen Shot 2023-05-19 at 3 43 34 p m](https://github.com/primefaces/primevue/assets/3856266/35c6e444-dfbc-47f0-82d6-9795de30450b)

Reproduction link: [https://stackblitz.com/edit/nuxt-starter-u1qmpk](https://stackblitz.com/edit/nuxt-starter-u1qmpk)

**Comment by michastubi** [comment]
I have exacly the same error, with an identical configuration.

**Comment by brianmhlanga** [comment]
Having the same issue, anyone with a workaround

**Comment by chris-pynegar** [comment]
I worked around this by adding the following import to primevue.ts:

`import Quill from 'quill'`

**Comment by thewebdevelopers** [comment]
> I worked around this by adding the following import to primevue.ts:
> 
> `import Quill from 'quill'`

Can confirm, adding this to my primevue Nuxt plugin fixes the Editor component.

**Comment by brianmhlanga** [comment]
Thanks for the work around @chris-pynegar

**Comment by adiramardiani** [comment]
any update on this issue @mertsincan ?
for now I disable unstyled, and editor workswell
`<Editor v-model="value" editorStyle="height: 320px" :unstyled="false" />`

but yes, we need editor on unstyle too, I think on documentation need to show code sample to work on all available icon/toolbar from this editor icon if use unstyle is enable

I think this issue must move to another version greater than 3.31 because this version is released

**Comment by Dubemtopsite** [comment]
> import Quill from 'quill'

Having same issue and have tried this but stil not working

**Comment by ethanolle** [comment]
Thanks @chris-pynegar

**Comment by cberthiaume** [comment]
Same issue here.

**Comment by Kelileis** [comment]
> I worked around this by adding the following import to primevue.ts:
> 
> `import Quill from 'quill'`

Thanks!

**Comment by brianmhlanga** [comment]
@Dubemtopsite try doing this if the import only is not working

import Quill from 'quill'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(Quill);
)}
you will get an error, then you remove the export. It works for me.

**Comment by xscasnya** [comment]
I am having the same issue, any update here ?

**Comment by Dubemtopsite** [comment]
> @Dubemtopsite try doing this if the import only is not working
> 
> import Quill from 'quill'
> 
> export default defineNuxtPlugin((nuxtApp) => { nuxtApp.vueApp.use(Quill); )} you will get an error, then you remove the export. It works for me.

Thanks for the reply but I have already moved on with CKeditor

**Comment by krishnasinghrathore** [comment]
Hi,

I was facing same issue for a long time, now having following solution which is working as normal Quill editor.

in <script> section
import Quill from 'quill';
const quill = ref(null);
<img width="325" alt="image" src="https://github.com/primefaces/primevue/assets/25331628/74394d75-d309-43bd-b5e7-655848c611b2">

onMounted(() => {
  quill.value = new Quill('#editor', {
    theme: 'snow', // or use another theme
  });

  // You can also set options and event listeners here
  quill.value.on('text-change', handleTextChange);
});

const handleTextChange = () => {
  // Handle text changes here
  const content = quill.value.root.innerHTML;
};
<img width="375" alt="image" src="https://github.com/primefaces/primevue/assets/25331628/0cd2c1b9-948f-45c0-b537-7d14cb962e39">


in template section add id and ref "editor"

<Editor
      id="editor"
      ref="editor"
      v-model="inputValue"
      :name="name"
      :aria-describedby="`${name}-error`"
    >
    </Editor>
<img width="373" alt="image" src="https://github.com/primefaces/primevue/assets/25331628/c886149e-3fa1-4d62-97d8-d6fad5934888">

It worked for me.

Thanks
