### ISSUE TITLE
Dialog: Adding fullscreen parameter or default to fullscreen on mobile devices

### ISSUE THREAD

**Issue by thor9n** [primefaces/primevue#3972]
### Describe the feature you would like to see added

- Add `fullscreen` parameter to the `Dialog` and `DynamicDialog`.
- Consider making non-interactive dialogs default to fullscreen on mobile devices.

### Is your feature request related to a problem?

Modals are a key part of both websites and web applications, and the best practice is to serve them full screen for users on mobile devices. It doesn't make any sense to restrict the size of a modal on a mobile device.

Everyone speaks so highly about Primevue so I just assumed an elegant solution to a common use-case would be available

### Describe the solution you'd like

I don't want users to see a modal opened on a mobile device that is not full screen. It's bad user experience and goes against all best-practices.

Please note that this does not apply to interactive modals such as ConfirmationDialogs, Alerts, etc.

### Describe alternatives you have considered

- Choosing another UI library.
- The `maximizable` property is not a viable alternative to this for several reasons. There's not a single forward-looking, smart application that uses a separate button for the user to maximize the dialog. Again, why not use best-practice solutions?

**Comment by kris-sum** [comment]
Was also requested in [#1854](https://github.com/primefaces/primevue/issues/1854)

**Comment by tugcekucukoglu** [comment]
`maximizable` property can be added programmatically.

**Comment by kris-sum** [comment]
@tugcekucukoglu please don't close this ticket - maximizable is not useful because that needs the user to click on the maximizable button. This ticket issue is to have the modal appear full screen by default.

**Comment by alwaqfi** [comment]
@tugcekucukoglu Thank you for your response, but it does not address the request. 

This request and the other referenced one is an enhancement/feature request. It is about introducing a property on dialog to have it opened in fullscreen without the need for the user to do any extra clicks. 

To give a bit of extra context. My workplace uses Vuetifyjs while I decided to use Primevue for my personal project. In Vuetifyjs, they have a property called `fullscreen` to start the dialog in fullscreen (no additional clicks needed form the user). Primevue has only maximizable option which requires the user to click on a button (next to X/close button) on a small screen to switch to fullscreen. 

Maybe there are workarounds like use JS to or some css but having a property that we can use is much cleaner. 

So, I hope reconsider re-opening this issue.

**Comment by squallstar** [comment]
I would also love to have this feature, as we have a use case where dialogs should open as maximised on mobile devices to ensure all available viewport space is used.

**Comment by fatelgit** [comment]
+1 I think this would be pretty useful!

As a workaround we can make use of the "show" - Event to toggle the "maximized" state.

```js
<Dialog ref="myDialog" @show="showDialog" v-model:visible="dialogOpen" maximizable modal header="Header" 
</Dialog>
```
example method:

```js
showDialog() {
    this.$refs.myDialog.maximized = true
}
```

**Comment by squallstar** [comment]
@fatelgit that's a really nice nifty hack, thanks for sharing it. Does it cause some flickering or the modal appears maximised when rendered in the screen?

**Comment by fatelgit** [comment]
In my case it appears maximized without any flaws. But I didn't run any tests on different setups/browser yet.

**Comment by dandred** [comment]
@fatelgit solution didn't work for my dynamic dialog (https://primevue.org/dynamicdialog/), but it helped me think of this workaround which maximizes the dialog:

`
import ProductListDemo from './ProductListDemo';
import { useDialog } from 'primevue/usedialog';

const dialog = useDialog();

const showProducts = () => {
    dialog.open(ProductListDemo, {});
    
    // Here is the workaround:
    		setTimeout(() => {
			const elem = document.querySelector(".p-dialog");
			elem?.classList.add("p-dialog-maximized"); // adds the maximized class
		}, 100);
    
}
`
I hope this is useful for someone.

**Comment by Jay-Stoll** [comment]
For Vue 3 and composition API 

` <Dialog
      ref="maxDialog"
      v-model:visible="showDialog"
      maximizable
      :header="props.name"
      class="w-full md:w-5/6"
      @show="biggifyDialog"
    >

const maxDialog = ref();

function biggifyDialog() {
  maxDialog.value.maximized = true;
}`

**Comment by Migushthe2nd** [comment]
Using the `@show` event has a slight delay for me. Another possibility is simply adding the `p-dialog-maximized` class to the `Dialog` element. Make sure to remove the 'maximizable' prop if you want the maximize/minimize button hidden:

```html
 <Dialog
        v-model:visible="value"
        class="p-dialog-maximized"
>
</Dialog>
```

**Comment by NHOHMS** [comment]
> // Here is another workaround that you can apply:
>     		// setTimeout(() => {
> 			// const elem = document.querySelector(".p-dialog");
> 			// elem?.classList.add("p-dialog-maximized"); // >>> This will maximize the dialog
> 		//}, 100);

This one was working for me but with a not so nice transition.
