### ISSUE TITLE
Add `allowEmpty` property to SelectButton

### ISSUE THREAD

**Issue by jnoordsij** [primefaces/primevue#3973]
### Describe the bug

In https://github.com/primefaces/primevue/pull/3610 and https://github.com/primefaces/primevue/issues/3708, the behavior for the `unselectable` was reversed. This is very confusing, as it is dubious wether or not this is an improvement to the logic. 

Moreover it certainly is a breaking change of behavior and should not have been added in a minor version update.

For further reference, please see https://github.com/primefaces/primevue/issues/3708#issuecomment-1507166982 and below.

**Comment by rubjo** [comment]
I really cannot see how this is dubious at all, the behaviour reversal was unfortunately just wrong.

All of these are logically the same:
unselectable
possible to *un*select
possible to clear
clearable
can be blank

If another wording is less likely to be misinterpreted, I agree with @jnoordsij that this should be fixed as per his suggestion in #3708.

**Comment by kennyfellows** [comment]
Agreed. I had to read the code to figure out why I needed `:unselectable="false"` in order for it to be _unselectable_.

**Comment by colinstevens06** [comment]
Agreed. Is not intuitive as it currently is labeled. Now that I know, I know, but I expected it to perform the opposite of how it does based on the naming of the prop.

**Comment by jnoordsij** [comment]
This has been adressed in #4107, by deprecating the old flag and introducing a non-ambiguous new flag. Would be great to have it merged!
