### ISSUE TITLE
Treeselect : Value slot return type problem

### ISSUE THREAD

**Issue by erdemsusam** [primefaces/primevue#3974]
### Describe the bug

Treeselect slot "value" is returning an array. I can access object with id 0

            <template #value="slotProps">
              <div v-if="slotProps.value.length" class="flex align-items-center">
                <i class="pi pi-folder text-yellow-400  mr-2"/>
                <span>{{ slotProps.value[0].label }}</span>
              </div>
              <span v-else>{{ slotProps.placeholder }}</span>
            </template>

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

Default implementation is enugh

### Expected behavior

slotProps.value should be an object

**Comment by tugcekucukoglu** [comment]
This is expected behavior. The type of `modelValue` and the type of `value` should be the same.
