### ISSUE TITLE
DataTable Editor nested Data

### ISSUE THREAD

**Issue by gitbeginner** [primefaces/primevue#3979]
### Describe the bug

If you have nested row data, for example:

```
{
    name: { value: "test123Name" },
    val: { value: "test123Val" },
}
```

then you cant cancel the edit because there is no deep clone implemented.
could you either provide an event to do cloning in this event or use some other library like klona to support deep cloning of objects?

otherwise its not usable :-(

**part from DataTable.vue:**

```
onEditingMetaChange(event) {
            let { data, field, index, editing } = event;
            let editingMeta = { ...this.d_editingMeta };
            let meta = editingMeta[index];

            if (editing) {
                !meta && (meta = editingMeta[index] = { data: { ...data }, fields: [] });
                meta['fields'].push(field);
            } else if (meta) {
                const fields = meta['fields'].filter((f) => f !== field);

                !fields.length ? delete editingMeta[index] : (meta['fields'] = fields);
            }

            this.d_editingMeta = editingMeta;
        }
```

_here could be emitted an event where you can put cloned value back in event object._

### Reproducer

https://codesandbox.io/p/sandbox/kind-volhard-t7g1f3

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
