### ISSUE TITLE
AutoComplete: Long text tags overflows

### ISSUE THREAD

**Issue by ghost** [primefaces/primevue#3980]
### Describe the bug

Long tags cannot be removed from the autocomplete components

### Reproducer

https://codesandbox.io/s/zealous-fog-0czu8o?file=/src/App.vue:0-1361

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 10.13

### Steps to reproduce the behavior

1. Go to autocomplete examples with multi option (https://primevue.org/autocomplete/#multiple)
2. Type very long text eq. "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime animi, quae eius nobis explicabo deserunt et aperiam est autem, unde officiis quibusdam atque temporibus sapiente, ab ullam voluptates. Corrupti ab, quibusdam modi quasi maiores hic earum officiis commodi voluptas atque non delectus quisquam aperiam quos accusantium nobis autem repellendus repudiandae! Neque exercitationem ut consectetur, accusantium accusamus nemo ex alias quas officia fuga consequuntur provident quos, voluptas nisi labore nobis optio explicabo. Distinctio quae repellat amet, consequuntur esse consequatur quia eius? Totam assumenda quibusdam laborum ratione a. Labore aperiam ipsum necessitatibus molestias laboriosam dignissimos quam facere voluptatum numquam, sapiente sed excepturi nesciunt quasi veritatis doloremque, enim nobis est pariatur ratione ea dolorem impedit dolor obcaecati? Quia, quasi voluptas fugiat quae dignissimos, harum, dolorum quaerat a fugit nulla inven"

### Expected behavior

A newly created tag cannot be removed as "x" button is hidden. Would be awesome to wrap white-spaces and show a tag with multiple lines

**Comment by inanc-can** [comment]
I came up with the idea that once text is too long remove the icon placed on the left end of the box.

There would be of course some space between the text and the icon.

<img width="1059" alt="Screenshot 2023-05-28 at 16 41 39" src="https://github.com/primefaces/primevue/assets/55583718/986c2e8d-df58-4c50-a2c6-657e494c05b3">

**Comment by tugcekucukoglu** [comment]
`pt` property can be used for this case.
