### ISSUE TITLE
Dropdown: asynchronous filtering

### ISSUE THREAD

**Issue by alex-dow** [primefaces/primevue#3982]
### Describe the feature you would like to see added

The Dropdown / MultiSelect components should make it easier to enable asynchronous filtering of select options.

### Is your feature request related to a problem?

The main problem is that the list of options is rendered via a computed property and that computed takes into consideration the value of the filter the user entered.

This poses several problems. 

1. There may be a discrepancy between how I want to filtering of objects, and how the Component does filtering of objects. For example, I want to allow the user to use wildcards to narrow down their search. I can't do this, because the filter will be `foo*` and while my server will respond with `foo` and `foobar`, nothing will be displayed because `foo*` doesn't match any of those options.
2. When user types in a query, the list is rendered with no or misleading options while waiting for the server to respond to the query.

### Describe the solution you'd like

My preferred solution would be to bind to the @filter event and use preventDefault() to stop default filtering behavior.

```typescript
onFilter = async (e: DropdownFilterEvent) => {
    e.originalEvent.preventDefault();
    // my custom search logic goes here, whatever it may be.
}
```

### Describe alternatives you have considered

Another alternative could just be a prop for custom filtering behavior and then anyone can do pretty much anything with filtering I suppose:

```typescript
<dropdown :filter-callback="myCustomFilter" />

const myCustomFilter = async (query: string) => {
    // do whatever I want here, including server calls
}
```

### Additional context

There are non-intuitive workarounds to this problem, such as setting empty messages to indicate that data is loading when data is actually loading. But they are just that, non-intuitive. I think it would be much easier to just allow user to bypass default filtering behavior (and support asynchronous filtering).

**Comment by alex-dow** [comment]
Actually there is an intuitive workaround (sorry, still new to PrimeVue) that, while not as nice as having this functionality built is, is none the less not a hack. Simply implement your own header and don't use the one in Dropdown/Multiselect:

```typescript
<template>
    <Dropdown @show="onShow">
        <template #header>
            <input type="text" :id="searchInputId" :value="searchQuery" @input="onSearchInput" />
        </template>
    </Dropdown>
</template>
<script lang="ts" setup>
import Dropdown from 'primevue/dropdown';
const searchInputId = computed(() => {
    // generate a useful id
    return 'search-input';
});

const onShow = () => {
    document.getElementById('search-input').focus();
}

const searchQuery = ref('');
const onSearchInput = (e: InputEvent) => {
    emit('search', e.currentTargt.value);
    searchQuery.value = e.currentTarget.value;
}
</script>
```

With MultiSelect, you'll need to set show-toggle-all to false unfortunately.

**Comment by alex-dow** [comment]
ok, this is actually more trickier.

In MultiSelect, you can't have selected values that don't exist in the list of available options (no `editable` prop for Multiselect) So what one needs to do is add selected values to the list of available options if those selected values are not already there.

**Comment by zinki97** [comment]
I have a dropdown with ~19.000 items. I definitly need an async function.
Even if I introduce a filter match mode "none", it takes 2 seconds until I can see my input on the screen, because every element is filtered with `() => true`.

I think it would be nice to have an optional "filter callback" which can be async.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
