### ISSUE TITLE
Tooltip: hideDelay missing in listener 

### ISSUE THREAD

**Issue by barthy-koeln** [primefaces/primevue#3986]
### Describe the bug

The `onKeyDown` listener of `Tooltip` is missing the `hideDelay` property declaration.

### Reproducer

https://codesandbox.io/p/sandbox/bold-breeze-4yxpiy
### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1) Add `v-tooltip` to a button
2) Click the button
3) Hit 'escape'
4) Read the console error:

> tooltip.esm.js:87 Uncaught ReferenceError: hideDelay is not defined
>     at HTMLButtonElement.onKeydown (tooltip.esm.js:87:58)

### Expected behavior

No error and `hideDelay` is used.

**Comment by tugcekucukoglu** [comment]
The issue seems to be fixed in earlier versions. Please try to use the latest version.
