### ISSUE TITLE
Datatable Pagination is not being reset on data source change

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#3990]
I am using Datable with lazy loading server-side pagination.

Let's say I am now on Page 3, When I click a button that calls the function getData to refresh the data, the data is being reloaded hover the pagination will remain on 3 while the data are being displayed now from page 1.

I tried so many solutions like changing the first props and calling certain functions in the data table to update it but in vain.

```
<DataTable
            v-model:selection="selecteddata"
            :value="data"
            selectionMode="single"
            dataKey="id"
            :paginator="true"
            :rows="pagination.per_page"
            :lazy="true"
            :loading="isLoading"
            :row-hover="data.length > 0 ? true : false"
            :total-records="pagination.total"
            @row-select="onRowSelect"
            @page="getData"
          >
```

```
    const getData = (event) => {
      isLoading.value = true;
      let url = `files`;
      if (event?.page) {
        url += `?page=${event.page + 1}`;
      } else if (searchCriteria.value) {
        url += `?criteria=${decodeURIComponent(searchCriteria.value)}`;
      }
      axios.get(url).then((response) => {
        data.value = response.data.files;
        pagination.value = response.data.page_context;
        isLoading.value = false;
      });
    };
```
![image](https://github.com/primefaces/primevue/assets/57847174/ee47183b-d03d-4c0d-b10c-632a78908c35)

**Comment by blogui91** [comment]
I'm not sure if I understood your issue, but some weeks ago I had a problem with the paginator, the reason was that I needed to pass a prop "first"  with the first index of the current page `:first="index"`

for example:
```
the index value of the page 3 is currentPage * perPage - perPage

perPage = 15
currentPage = 3

first = 3 * 15 - 15; // 30

```
Having this value solved just  add it to your component, it should work

**Comment by garry-mitchell-coats-com** [comment]
Even the current Lazy demo on the documentation can be used to easily demonstrate this problem.

Navigate off page 1, and then do a filter on Country for anything (for example, `Algeria`) and press Enter to perform the filtering. The table will refresh, and show no records. Click on the `1` in the paginator, and it will refresh and show the 1 matched result.

**Comment by qkrdkwl9090** [comment]
I am currently using version 3.30.0, but this problem continues to occur.

Data length : 27
rows: 20

1. Move page 2 from page 1
2. api refetch call
3. DataTable has been updated, but rows maintain row7 on page 2. The pagination is also on page 2.

Version
nuxt: 3.6.2
primevue: 3.30.0

**Comment by tugcekucukoglu** [comment]
The DataTable needs to know which row will be the first, just as it needs to know the number of rows.

https://stackblitz.com/edit/lxpxlz-93qeul?file=src%2FApp.vue%3AL106

**Comment by LokkiDog** [comment]
I faced the same problem. 

Did you manage to solve it? How do you solved it?

**Comment by Asparagirl** [comment]
Hi, I had this problem and eventually had to employ some overrides within my table component to finally get this all to work. Note that I'm using Vue3. Here's my code:

```
<DataTable ref="dt" :value="results" :loading="loading" paginator :first="firstNumber"
      :totalRecords="totalRecordsNumber" :rows="10" :rowsPerPageOptions="[10, 25, 50, 100]"
      paginatorTemplate="FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink RowsPerPageDropdown"
      currentPageReportTemplate="{first} to {last} of {totalRecords} records" stripedRows showGridlines removableSort
      dataKey="id" v-model:expandedRows="expandedRows" tableStyle="min-width: 50rem">
      
      [other HTML goes here]
 ```
 
Note that I chose to include this DataTable inside a component, so I'm sending it the "results" from a parent page/component, using props. Also note the 'ref' value here is explicitly set to "dt". That's important.
 
And then in the Composition API I do this... (also edited somewhat):
 
 ```
 <script setup>
 import DataTable from 'primevue/datatable';
 import Column from 'primevue/column';
 
 // define the various props sent to this component by parent
  const props = defineProps({
    results: {
      type: Object,
      required: false,
      default: [],
    },
  });
 
 // reactive AND synced, used for watch() below
 const newResults = toRef(props, 'results');
  
  // datatable ref
  const dt = ref(null);
  
  watch(newResults, (newValue, oldValue) => {
    // make really sure the pagniator resets to page 1 every time the results change
    dt.value.d_first = 0; // 0 is the first row, not 1
    dt.value.d_page = 1;
    dt.value.page = 1;
    // and make sure the data table gets rid of any previous column sorting that might have been applied
    dt.value.d_sortField = null;
    dt.value.d_sortOrder = null;
  });

</script>
```

So now every time there's a new set of "results" in the parent page/component, the "results" object flows down to this component, which holds the DataTable. The results data updates, but that also triggers an update of the props, which has a copy made a "newResults", which is being always watched by "watch(newResults, (newValue, oldValue)" which then forcibly resets the actual page number to 1, so that the text is finally correct. And then it also forcibly resets the sorting too, if there was any.

Hope this helps!

**Comment by mertoztat** [comment]
@Asparagirl its works. thank you.

if you're create clear button and this button was clicked remove all filters and set pagination 1,  you dont need watch. 



<DataTable ref="dataTable" :value="results" :loading="loading" paginator :first="firstNumber"
      :totalRecords="totalRecordsNumber" :rows="10" :rowsPerPageOptions="[10, 25, 50, 100]"
      paginatorTemplate="FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink RowsPerPageDropdown"
      currentPageReportTemplate="{first} to {last} of {totalRecords} records" stripedRows showGridlines removableSort
      dataKey="id" v-model:expandedRows="expandedRows" tableStyle="min-width: 50rem">
      
      [other HTML goes here]
....
</DataTable>

<Button
      label="Clear"
      :loading="tableLoading"
      class="p-button-warning"
      @click="clearData"
    />

composition api 

function clearData () {
      // clear filters
      this.pagination.pageIndex = 1;
      this.$refs.dataTable.value.d_first = 0;
      this.getTableData();
    },

options api 
// you dont need dataTable.value just dataTable.d_first = 0 its worked
clearData () {
      // clear filters
      this.pagination.pageIndex = 1;
      this.$refs.dataTable.d_first = 0;
      this.getTableData();
    },

**Comment by jabernalv** [comment]
We’re also facing a closely related (possibly identical) issue in **lazy mode with `v-model:first`** and `@page`.

Even when restoring a valid `first` value programmatically (e.g., from `localStorage`) and binding it with `v-model:first`, the DataTable emits a `@page` event with `first = 0` immediately after mount — **overriding the intended pagination state**.

This causes incorrect double-fetching and resets the page to 1, making lazy loading inconsistent and hard to work with when restoring state.

We’ve opened a detailed bug report here (including a full StackBlitz reproducer):  
👉 https://github.com/primefaces/primevue/issues/7618

If this sounds familiar or related, please consider upvoting and helping push this to resolution. It’s a critical blocker for any app trying to persist or restore DataTable state across views.

Thanks!

**Comment by manikandan-k-oa** [comment]
I used the code below to reset the pagination. It worked for me 👍

```
<DataTable
    ref="dt"
    :value="results"
    showGridlines
    stripedRows
    v-model:selection="selectedResults"
    dataKey="id"
    paginator
    :rows="pageSize"
    v-model:filters="filters"
    :rowsPerPageOptions="[5, 10, 25]"
    :globalFilterFields="['name', 'state']"
    :loading="isLoadingData"
    :totalRecords="tolalRecords"
    :lazy="true"
    @page="handleOnPageChange"
    scrollHeight="330px"
    scrollable
  >
// remaining code
</DataTable>
```

```

// datatable ref
const dt = ref(null);

const resetPagination = () => {
  const backToFirstBtn = dt.value.$el.querySelector(
    ".mds-paginator__content > button"
  );
  if (backToFirstBtn) {
    backToFirstBtn.click();
  }
};

// Call this method where you want to reset
// resetPagination();

```

**Comment by rgabbard** [comment]
@tugcekucukoglu This seems to still be a major issue in PrimeVue 4.4.0. Neither setting `:first=0` as well as the ref-based workaround `this.$refs.dataTable.value.d_first = 0;` appear to work. I've tried numerous workarounds to no avail. How can you make the paginator reset back to page 1 in lazy mode when reloading the data source?
