### ISSUE TITLE
SplitButton: Broken styles when no icon

### ISSUE THREAD

**Issue by alexterenya** [primefaces/primevue#3993]
### Describe the bug

If create SplitButton without icon, label is not centered correctly. Issue can be observed in official documentation:  
<img width="1167" alt="image" src="https://github.com/primefaces/primevue/assets/41677103/7cc6b535-dcb5-44a9-a591-edb97be0132d">

### Reproducer

https://primevue.org/splitbutton/#pt.demo

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Please track this issue https://github.com/primefaces/primevue/issues/3993
