### ISSUE TITLE
General: How are styles synced between prime* projects?

### ISSUE THREAD

**Issue by septatrix** [primefaces/primevue#3994]
### Describe the feature you would like to see added

**Not a direct feature request though I did not find a discussion section on any of the prime* repos (nor a general repo for topics regarding all implementations).**

How is it ensured that styles between all prime projects are synced, i.e. primeng, primevue and primereact?
We are currently considering moving a project from primeng to primevue. For this we would have a transition time where both frameworks will be used side-by-side. Consequently components from both variants can occur on the same page.
In our preliminary testing we have not yet found any problems with this, however, it would be great to know how the team is ensuring that styles do not get out of sync between all three projects.

### Is your feature request related to a problem?

It is annoying and looks unprofessional if the same component looks different on some parts of a website.

### Describe the solution you'd like

Intuitively I would have assumed that there is a repo with general styles which can be reused and imported by each project though this does not seem to be the case.

### Describe alternatives you have considered

If an internal tool already exists within the team which is used to sync styles between all projects then everything is fine.
Another alternative would be to have visual snapshot tests which can be compared between all three projects.

**Comment by tugcekucukoglu** [comment]
If you prefer, we could transfer this issue to [discussions](https://github.com/orgs/primefaces/discussions/categories/primevue)

**Comment by septatrix** [comment]
> If you prefer, we could transfer this issue to [discussions](https://github.com/orgs/primefaces/discussions/categories/primevue)

Yes please, can you transfer and convert this or should I start a new discussion there?
