### ISSUE TITLE
Tree: Tree branches should expand during filtering

### ISSUE THREAD

**Issue by joshas** [primefaces/primevue#3996]
### Describe the bug

Vue Tree Component tree branches does not expand during filtering to display matching search results.

### Reproducer

https://codesandbox.io/s/8kdizf

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

In provided code example (or in [official documentation](https://primevue.org/tree/#filter)) enter "resume" in search field.
![image](https://github.com/primefaces/primevue/assets/79141/4c9515a8-d5c1-4a7d-a23b-a03710bf726b)

### Expected behavior

If item with provided search term is found, parent branches should automatically expand, like they do in [Angular](https://primevue.org/tree/#filter) and [React](https://primereact.org/tree/#filter) versions.
![image](https://github.com/primefaces/primevue/assets/79141/d0ae44b6-5b07-4b03-af39-9f8fcc1807f4)

And it would be nice to add appropriate placeholder texts to filter inputs in PrimeVue documentation page.

**Comment by Gikkman** [comment]
I ran in to this problem today too. I expected it to behave like the react version, but it didn't. So instead of posting a 2nd issue, I'll just leave this comment to show support

**Comment by HNH12** [comment]
+1

**Comment by AlexyNau** [comment]
Until it's fixed, here is an alternative I'm using. It expand the tree during filtering, and collapse all tree when filtering value is erased from the text field.
I use Tree Pass Through Options (see [primevue.org/tree/#selection](https://primevue.org/tree/#selection)) to get input changes.

Versions:
_primevue_ **3.37.0**
 _vue_ **3.3.4**

```typescript
<template>
    <!--Tree branches should expand during filtering @primefaces/primevue #3996-->

    <Tree :value="nodes"
          selectionMode="single" @nodeSelect="selectNode"
          v-model:selectionKeys="selectedKeys" v-model:expandedKeys="expandedKeys"
          :filter="true" filterMode="lenient"
          filter-placeholder="Search..."
          :pt="passThroughOptions"
          class="w-full md:w-30rem">
    </Tree>

</template>

<script lang="ts">
import {defineComponent} from 'vue';
import Tree, {TreeExpandedKeys, TreeNode, TreeSelectionKeys} from 'primevue/tree';
import {PassThroughOptions} from 'primevue/passthrough';

export default defineComponent({
    name: 'TreeNodeSelectionPage',
    components: {
        Tree
    },
    data() {
        return {
            nodeStore: useNodeStore(), // Your Pinia store for example
            selectedKeys: {} as TreeSelectionKeys,
            expandedKeys: {} as TreeExpandedKeys,
            passThroughOptions: {
                input:
                    ({state}) => {
                        if (state.filterValue != null) {
                            this.filterValueChanged(state.filterValue);
                        }
                    }
            } as PassThroughOptions,
            searchLabel: ''
        };
    },
    computed: {
        nodes(): TreeNode[] {
            return this.nodeStore.getNodes;
        }
    },
    methods: {
        expandNode(node: TreeNode) {
            if (node.children && node.children.length && node.key) {
                this.expandedKeys[node.key] = true;

                for (const child of node.children) {
                    this.expandNode(child);
                }
            }
        },
        expandAll() {
            for (const node of this.nodes) {
                this.expandNode(node);
            }
        },
        collapseNode(node: TreeNode, currentExpandedSiteKey: TreeSelectionKeys) {
            if (node.children && node.children.length && node.key) {
                currentExpandedSiteKey[node.key] = false;

                for (const child of node.children) {
                    this.collapseNode(child, currentExpandedSiteKey);
                }
            }
        },
        collapseAll() {
            const currentExpandedSiteKey = this.expandedKeys;
            for (const node of this.nodes) {
                this.collapseNode(node, currentExpandedSiteKey);
            }

            this.expandedKeys = currentExpandedSiteKey;
        },
          allSiteCollapsed(obj: TreeSelectionKeys) {
            for (const prop in obj) {
                if (obj[prop]) {
                    return false;
                }
            }
            return true;
        },
        filterValueChanged(value: string | null) {
            if (value && value?.trim().length > 1) {
                // Expand all nodes when a new value is entered in the text field
                if (this.searchLabel != value) {
                    this.searchLabel = value;
                    this.expandAll();
                }
                // Collapse all nodes when value is erased
            } else if (!this.allSiteCollapsed(this.expandedKeys) && value != null && value?.trim().length === 0 && this.searchLabel.length != 0) {
                this.collapseAll();
                this.searchLabel = '';
            }
        },
        selectNode(node: TreeSelectionKeys) {
            console.log(node);
        }
    }
});
</script>
```

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by roberthoenig** [comment]
+1

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
