### ISSUE TITLE
Form fields: Required asterisk

### ISSUE THREAD

**Issue by angelaburon** [primefaces/primevue#4005]
### Describe the feature you would like to see added

It would be super useful to have a way to show requiredness in forms as part of the design system, as this is a very common feature and would take away a lot of work and room for inconsistencies for both dev and design teams.

### Describe the solution you'd like

A red asterisk at the left of the label.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
