### ISSUE TITLE
DataTable: Subheader on horizontal scrolling when rows are grouped are not sticky

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#4009]
### Describe the bug

The documentation shows the example: 
![image](https://github.com/primefaces/primevue/assets/36476318/6efaa650-50a5-41c9-991d-94f79b11c157)
If you keep scrolling to the right, the subheader is scrolled as well, while it should be sticky so it is always visible.
I believe this is rather a bug than a new feature request. 

### Reproducer

Official docs

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by cantin-f** [comment]
https://github.com/primefaces/primevue/issues/2299 duplicate ?

**Comment by Tamas-hi** [comment]
Yeah, it seems so. It is a long time issue, hoping for a fix in the near future

**Comment by tugcekucukoglu** [comment]
Duplicate #2299
