### ISSUE TITLE
Prop "optionValue" for "AutoComplete" component

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#4012]
### Describe the feature you would like to see added

You can add the "optionValue" property by analogy as in other components.

**Comment by affulisaac** [comment]
I had also like to see this feature. You should be able to define the field to bind to the v-model.

**Comment by kstan79** [comment]
yes please support it. at the moment we have to 'hack' the modelValue, it kind of ugly and break something

**Comment by gnucifer** [comment]
Same problem here, was a little surprised there is no such prop for this component.

**Comment by kstan79** [comment]
I ended up change my way of coding which is save json object into db instead of  Id. Surprisingly it is better approach and reduce lot of development overhead.

**Comment by gnucifer** [comment]
That doesn't work if used as a filter i a DataTable though, as the filterModel and filterCallback (in my case, needs and id or list of ids). My workaround was to create a custom wrapper component:

`<script>
import { ref, toRef, toRaw, watch } from 'vue'

import AutoComplete from 'primevue/autocomplete'
export default {
  emits: ['update:modelValue', 'change'],
  props: {
    optionValue: {
      type: String,
      required: true
    },
    options: {
      type: Array,
      required: true
    },
    modelValue: {
      required: true
    },
  },
  setup(props, { emit }) {

    const model = ref()

    const parentModel = toRef(props, 'modelValue')

    watch(parentModel, (newValue) => {
      if (Array.isArray(newValue)) {
        model.value = newValue.map(id => {
            return props.options.find(elem => elem[props.optionValue] == id)
        })
      }
      else if (newValue) {
        model.value = props.options.find(elem => elem[props.optionValue] == newValue) || newValue
      }
      else {
        model.value = newValue
      }
    })

    const onModelUpdate = (event) => {
      if (Array.isArray(event)) {
        const value = event.map(elem => elem[props.optionValue])
        emit("update:modelValue", value)
        emit("change", value)
      }
      else if(typeof(event) === "object") {
        emit("update:modelValue", event[props.optionValue])
        emit("change", event[props.optionValue])
      }
      else {
        emit("update:modelValue", event)
      }
      if (!event) {
        emit("change", event)
      }
    }

    return {
      model,
      onModelUpdate
    }
  },
  components: {
    AutoComplete
  }
}
</script>
<template>
  <AutoComplete :modelValue="model" @update:modelValue="onModelUpdate"/>
</template>
`

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by louia** [comment]
Hi @tugcekucukoglu, any news on this ? The lack of homogeneity between components is regrettable

**Comment by kstan79** [comment]
You guys just create new autocomplete from this component, and manually process the variable, update parent using emit

**Comment by timyourivh** [comment]
It should be as easy as changing:

https://github.com/primefaces/primevue/blob/6e55ee9514af77125ff50f50e59f8e766dce1367/packages/primevue/src/autocomplete/AutoComplete.vue#L268-L270

To:

```diff
 getOptionValue(option) {
-    return option; // TODO: The 'optionValue' properties can be added.
+    return this.optionValue ? resolveFieldData(option, this.optionValue) : option;
 },
```

And adding `optionValue: null,` to the props of the `BaseAutoComplete` component.

But I noticed when selecting a value the modelValue is displayed in the InputText which may result in undesired behavior. Let me explain.

Say you got an object like:

```js
const test = {
  name: "Bob"
  id: 1
}, // ... etc
```

And set the `optionLabel` to "name" and `optionValue` to "id" this will result in the InputText showing the id instead of the label upon selection. 

I'm not sure if this is desired so I stopped with creating a PR due to this. 

I'm afraid to introduce opinionated changes due to the consistency of the package. Because I think the component should keep it's own `modelValue` internally and emit/show properties of the content of that value.

Please @tugcekucukoglu let me know what you think. 

---

We currently use a workaround so for anyone interested:

<details>
  <summary>Click to expand</summary>
  
```vue
<script setup lang="ts">
const users = {
  name: "Bob"
  id: 1
}, // ...

const form = reactive({
  user: null,
  // ...
})

const selectedValue = ref() // Required or the value inside the text field will be cleared

const onItemSelected = (event) => {
  form.user = event.value.id // Option value is taken and set here
}
</script>

<template>
  <div>
    <AutoComplete v-model="selectedValue" :suggestions="users" optionLabel="name" @item-select="onItemSelected" />
  </div>
</template>
```
</details>

**Comment by mcmule** [comment]
Hello all, what's the status of this? When used inside a Form, manually wrapping is not really a solution since the whole model+events are managed by Form.
Thanks,

**Comment by stepan323446** [comment]
This is still not available, even though two years have passed. It's a big issue for AutoComplete and a fairly common task (for example, I have 1,000 tags).

**Comment by john-psina** [comment]
This feature would be very useful.
At the moment the only solution for me is:
```
@update:modelValue="(value: any) => onLinkChange(field, value)"
```

```ts
async function onLinkChange(field: any, value: string | { name: string, path: string }) {
field.value = (value as { name: string, path: string }).path ? (value as { name: string, path: string }).path : value as string
}
```

And it doesn't work perfectly. From time to time this solution causes strange bugs

**Comment by YacovTurak** [comment]
Here is a simpler solution:
```
const selectedCity = computed({
    get() {
        return generalStore.cities.find((c) => c.id === user.value?.cityId) || null;
    },
    set(val) {
        user.value.cityId = val?.id || null;
    },
});
```
In `get` I return the entire object, as `Autocomplete` expects, in `set` I update only the field I need to update.

Then I link it to computed.
```
<AutoComplete
    v-model="selectedCity"
    :suggestions="filteredCities"
    optionLabel="name"
    @complete="searchCity"
/>
```
