### ISSUE TITLE
Add appendTo To SideBar

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#4019]
### Describe the feature you would like to see added

Add appendTo To SideBar

### Is your feature request related to a problem?

Yes, on a scenario where you have, for example, 4 vue instances of the same custom vue element (App) on the same page, you want to show the sidebar per element and not mounted to the body, but rather the element (like appendTo in dialog boxes, etc)

<img width="1919" alt="image" src="https://github.com/primefaces/primevue/assets/1152458/222add7c-b7d1-483d-ae0f-5d920c0f4b41">

**Comment by cyhnkckali** [comment]
Is there any progress on this issue?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
