### ISSUE TITLE
Chips and AutoComplete(multiple mode) support multiline input mode

### ISSUE THREAD

**Issue by west-farmer** [primefaces/primevue#402]
Chips and AutoComplete(multiple mode) are very useful,  but too many items will run out the input area.

**Comment by cagataycivici** [comment]
Do you have an example? Do you mean they should wrap?

**Comment by west-farmer** [comment]
sorry to see this message so late.
 
Yes,  I think they  can wrap in a multi-line control like a textarea . I use a chips manage user group , it's difficult to use when members more then 10. 

![image](https://user-images.githubusercontent.com/55118339/90408765-e3596380-e0da-11ea-9ba1-1add244921d8.png)

**Comment by cagataycivici** [comment]
They wrap in recent versions.
