### ISSUE TITLE
Datatable: Datatable selection is lag and slow with large dataset

### ISSUE THREAD

**Issue by hurahurat** [primefaces/primevue#4020]
### Describe the bug

Datatable is so slow when there are large number of dataset and large number of columns.
When I click select all checkbox it show a lag before all rows is selected and even select a single row could show me a lag.

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-lgz1dg

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

The checkbox should be selected without any lag for large datasets also.

**Comment by NeluQi** [comment]
+1

**Comment by hurahurat** [comment]
After forked and made some changes I have successful reduce the lag time less than 1s(~700ms)

**Comment by NeluQi** [comment]
> After forked and made some changes I have successful reduce the lag time less than 1s(~700ms)

Send a PR, I want to see it in the official version

**Comment by galilmori** [comment]
This is a terrible bug in my case i have a lot of data and it goes crashes my application wirth a blank page

**Comment by martinszeltins** [comment]
+1

**Comment by NxMgh** [comment]
+1

**Comment by dipbhi** [comment]
+1

**Comment by omzy** [comment]
Any update on this? Or is anyone able to share a workaround?

**Comment by thevalo** [comment]
I have the same problem, but instead of a checkbox, the table really lags (and pages becomes sometimes unresponsive) when searching using global filters. Following.

**Comment by ibrdavid** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

Please see; https://dev.to/mertsincan/handling-big-data-on-datatable-with-checkbox-selection-multiselect-4hgc
I tried to explain how you can overcome these problems.

Best Regards,
