### ISSUE TITLE
Treetable: Columns Width with scrollable

### ISSUE THREAD

**Issue by martinfruehmorgen** [primefaces/primevue#4022]
### Describe the bug

When using scrollable the width of a column is not respected

### Reproducer

https://stackblitz.com/edit/frctyr?file=src%2FApp.vue

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. See stackblitz, the last 2 columns should be 45px

### Expected behavior

The columns should be 45px width.

**Comment by tugcekucukoglu** [comment]
Could you try to add `scrollDirection="both"` like here https://stackblitz.com/edit/frctyr-vn68ul?file=src%2FApp.vue%3AL9 ?
