### ISSUE TITLE
Component Name: InputMask

### ISSUE THREAD

**Issue by drShvets** [primefaces/primevue#4026]
### Describe the bug

There is an issue with pasting new value when the old value is provided and is not removed

### Reproducer

https://codesandbox.io/p/sandbox/loving-ace-qgjt3e?welcome=true

### PrimeVue version

3.9.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. copy value after "Value to paste:"
2. focus input
3. paste copied value using "cmd + v"

### Expected behavior

InputMask to contain pasted value

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3915
