### ISSUE TITLE
ConfirmDialog: Control over closing dialog

### ISSUE THREAD

**Issue by veco9** [primefaces/primevue#4027]
### Describe the feature you would like to see added

Control over closing ConfirmDialog after pressing accept / reject buttons.

### Is your feature request related to a problem?

Problem is the lack of control over ConfirmDialog after pressing accept button.

### Describe the solution you'd like

e.g. changing this:

```
  accept() {
      if (this.confirmation.accept) {
          this.confirmation.accept();
      }
      this.visible = false;
  }
```
to this:

```
  accept() {
      if (this.confirmation.accept) {
          this.visible = this.confirmation.accept();
      } else {
         this.visible = false;
      }    
  }
```

A common use case for this involves using a confirm dialog with some input field (form) that needs to be passed when accepting something, such as a remark or footnote. In this scenario, I would appreciate having control over the closing process, as I need to validate the input. There is a possibility that the input may be invalid, and in such cases, it is necessary for the user to remain on the dialog.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by AAABingBing** [comment]
@tugcekucukoglu @cagataycivici 

Yes, I also encountered this problem.
I hope to use it like ElementPlus message boxes, so that ConfirmDialogs can be closed asynchronously. Although I know I can use the Dialogs component, it is slightly more cumbersome to use compared to ConfirmDialogs.
Just like this [ElementPlus MessageBox](https://element-plus.org/en-US/component/message-box.html#customization)

![element-plus message-box](https://github.com/primefaces/primevue/assets/53040248/5ba0be15-fff8-4ccf-ae2e-1f4ba469fede)

**Comment by AAABingBing** [comment]
> @tugcekucukoglu @cagataycivici
> 
> Yes, I also encountered this problem. Can we add asynchronous shutdown functionality to ConfirmDialogs and ConfirmPopups? I hope to use it like ElementPlus message boxes, so that ConfirmDialogs can be closed asynchronously. Although I know I can use the Dialogs component, it is slightly more cumbersome to use compared to ConfirmDialogs. Just like this [ElementPlus MessageBox](https://element-plus.org/en-US/component/message-box.html#customization)
> 
> ![element-plus message-box](https://private-user-images.githubusercontent.com/53040248/341695209-5ba0be15-fff8-4ccf-ae2e-1f4ba469fede.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTY0NjcsIm5iZiI6MTcxOTE5NjE2NywicGF0aCI6Ii81MzA0MDI0OC8zNDE2OTUyMDktNWJhMGJlMTUtZmZmOC00Y2NmLWFlMmUtMWY0YmE0NjlmZWRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyMjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxODFkMTlmYjQ4ODJlYzBiZmI1YTUyYTVjN2I1NThlMzQwNGU3OWM0OTRlNjc2NTUzNThiYWU4M2U1NjA3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7haRUMF6iXgXlADZycQLPYsI5STEan-H2ps48gHFPs) [ ![element-plus message-box](https://private-user-images.githubusercontent.com/53040248/341695209-5ba0be15-fff8-4ccf-ae2e-1f4ba469fede.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTY0NjcsIm5iZiI6MTcxOTE5NjE2NywicGF0aCI6Ii81MzA0MDI0OC8zNDE2OTUyMDktNWJhMGJlMTUtZmZmOC00Y2NmLWFlMmUtMWY0YmE0NjlmZWRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyMjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxODFkMTlmYjQ4ODJlYzBiZmI1YTUyYTVjN2I1NThlMzQwNGU3OWM0OTRlNjc2NTUzNThiYWU4M2U1NjA3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7haRUMF6iXgXlADZycQLPYsI5STEan-H2ps48gHFPs) ](https://private-user-images.githubusercontent.com/53040248/341695209-5ba0be15-fff8-4ccf-ae2e-1f4ba469fede.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTY0NjcsIm5iZiI6MTcxOTE5NjE2NywicGF0aCI6Ii81MzA0MDI0OC8zNDE2OTUyMDktNWJhMGJlMTUtZmZmOC00Y2NmLWFlMmUtMWY0YmE0NjlmZWRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyMjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxODFkMTlmYjQ4ODJlYzBiZmI1YTUyYTVjN2I1NThlMzQwNGU3OWM0OTRlNjc2NTUzNThiYWU4M2U1NjA3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7haRUMF6iXgXlADZycQLPYsI5STEan-H2ps48gHFPs) [ ](https://private-user-images.githubusercontent.com/53040248/341695209-5ba0be15-fff8-4ccf-ae2e-1f4ba469fede.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTY0NjcsIm5iZiI6MTcxOTE5NjE2NywicGF0aCI6Ii81MzA0MDI0OC8zNDE2OTUyMDktNWJhMGJlMTUtZmZmOC00Y2NmLWFlMmUtMWY0YmE0NjlmZWRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyMjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxODFkMTlmYjQ4ODJlYzBiZmI1YTUyYTVjN2I1NThlMzQwNGU3OWM0OTRlNjc2NTUzNThiYWU4M2U1NjA3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7haRUMF6iXgXlADZycQLPYsI5STEan-H2ps48gHFPs)

I created a new issue #5954

**Comment by charlietyn** [comment]
@veco9 ,@a81n9 any temporal solution for this?
