### ISSUE TITLE
Tooltip: showDelay still triggers Tooltip when original element is removed

### ISSUE THREAD

**Issue by Benoxi** [primefaces/primevue#4029]
### Describe the bug

**Description:**

When using the `Tooltip` component with `showDelay` and we destroy the original trigger element (before the `showDelay` time runs out), the `Tooltip` still appears, even though the trigger element is not there anymore.

**Example code:** 

```vue
<template>
    <div>
        <Button
            v-if="isShown"
            label="hide this button"
            @click="isShown = false"
            v-tooltip.bottom="{ value: 'This is a tooltip', showDelay: 2000 }"
        />
    </div>
</template>

<script setup>
import { ref } from 'vue';

const isShown = ref(true);
</script>
``` 

### Reproducer

https://codesandbox.io/p/sandbox/eager-sea-qpwszh?file=%2Fsrc%2FApp.vue%3A8%2C8

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

**Steps to reproduce:**

- Create a `Button` that can be removed (removed from render)
- Add a `Tooltip` (`v-tooltip.bottom` to see the issue better) with a `showDelay` of `2000` (enough to close the parent component before the Tooltip would show) to the element/component
- Close (remove) the component before the `showDelay` runs out

**Expected behavior:**

The `Button` is removed and the `Tooltip` is not shown

**Actual behavior:**

The `Tooltip` still appears in the top left corner, coord (0,0)

**Suggested fix:**

Before showing the `Tooltip`, check again if the trigger element exists on the page

### Expected behavior

The `Button` is removed and the `Tooltip` is not shown

**Comment by hamidovz** [comment]
hi ! i fixed this bug. can i send a PR ? @tugcekucukoglu
