### ISSUE TITLE
Dropdown: Group filter

### ISSUE THREAD

**Issue by arnyee** [primefaces/primevue#4031]
### Describe the feature you would like to see added

Hi, I really like your project!

Using the dropdown component, which is a very well-designed feature, I find it lacking the ability to specify a custom filter algorithm. My goal is to have groups with items, and currently, I can only filter the items. However, I would like to achieve a functionality where it shows all items that either match the basic filtering criteria or have a group name that matches the filtering criteria.

### Is your feature request related to a problem?

My customers have very long lists and they don't know the item names only the group name, but they can't filter it.

### Describe the solution you'd like

It would be nice if I can make a custom filter algorithm or there be a property where I can set when filtering the group name is enough for match.

### Additional context

I hope you can help me. Is there a solution for this please show me.

**Comment by arnyee** [comment]
This could be nice, but I can handle it if i add the items plus properties for search and use the filterFileds property!

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
