### ISSUE TITLE
Injected Styles in a CSS @Layer

### ISSUE THREAD

**Issue by alex-dow** [primefaces/primevue#4036]
### Describe the feature you would like to see added

The ability to put the injected CSS of primevue components into a CSS @layer.

### Is your feature request related to a problem?

CSS Specificity can be weird. Especially when the load order can't be garaunteed. CSS Cascading Layers is a solution to this problem.

### Describe the solution you'd like

```javascript

app.use(PrimeVue, { injectLayer: 'some-layer-name'});

```

Example output of paginator CSS:

```
@layer some-layer-name {
    .p-paginator {
        // ...
    }
}
```

### Additional context

I wrote a vite plugin that seems to work. I don't know the primevue code base extensively, and this is working on built code anyways, but this seems to work for all the components I'm concerned about. But it definitely feels dirty to be transforming code this way, but hey, when you need to hack, you need to hack! ;)

```javascript
module.exports = function() {
    return {
      name: 'vite-plugin-layer-primevue',
      transform(src, id) {
        const matchString = /styleInject\((.*)\)\;/;
        //console.log('id:', id);
        if (id.toLocaleLowerCase().indexOf('primevue') > -1) {
  
          const matches = matchString.exec(src);
          if (matches) {
            if (matches.length > 0) {
              const newsrc = src.replace(matchString, 'styleInject("@layer primevue {" + ' + matches[1] + ' + "}");');
              return {
                code: newsrc,
                map: null
              }
            }
          }
        }
      }
    }
  }
```

Now all  the injected styles for components I care about, are in `@layer primevue` and my css layers look something like:

`@layer vendors primevue mycomponents` and style rules in the mycomponents layer will always take priority.

**Comment by tugcekucukoglu** [comment]
PrimeVue uses @layer css with the latest version.

Thank you for your time!
