### ISSUE TITLE
value duplication in multiselect

### ISSUE THREAD

**Issue by NadavSi** [primefaces/primevue#4037]
when creating and array of data with duplicate name but not code:
[
    { name: 'New York', code: 'NY' },
    { name: 'Rome', code: 'RM' },
    { name: 'Rome', code: 'RMA' },
    { name: 'London', code: 'LDN' },
    { name: 'Istanbul', code: 'IST' },
    { name: 'Paris', code: 'PRS' }
]
 i get a Vue warn "Duplicate keys found during update: "Rome" Make sure keys are unique"
but no matter how i try to add dataKey to the v-for it is not identifying unique keys and gives a distorted ui dropdown on filtering
![image](https://github.com/primefaces/primevue/assets/19567670/947a42ed-3fd2-40b6-8aa2-54483ebd2822)

my multiselect code:
```
<MultiSelect v-model="selectedCities" :options="cities" filter optionLabel="name" placeholder="Select Cities"
            :dataKey="code">
            <template #value="slotProps">
                <template v-if="!slotProps.code || slotProps.code.length === 0">
                    {{ slotProps.placeholder }}
                </template>
                <div v-for="(option,index) of slotProps.value" :dataKey="index"> 
                 //also not working :dataKey="option.code" :key="..."
                    <span>{{ option.name }}</span>
                </div>
            </template>
            <template #option="slotProps">
                <div>
                    <span>{{ slotProps.option.name }}</span>
                </div>
            </template>
        </MultiSelect>
```

**Comment by tugcekucukoglu** [comment]
I have a correctly working example https://stackblitz.com/edit/upxnfg?file=src%2FApp.vue with dataKey. Could you check that, please? If problem still persists, please let us know?

**Comment by NadavSi** [comment]
does not work. in your example any checkbox i click marks all of them

**Comment by joaomarcelofm** [comment]
@NadavSi did you solve this issue? I just encountered this as well.

**Comment by joaomarcelofm** [comment]
@NadavSi I solved it by adding something like `data-key="code"`. In my case `id`, but it fixed the vue warning and funky behavior.
