### ISSUE TITLE
Datatable: Show the "Select All" checkbox on mobile stacked view. 

### ISSUE THREAD

**Issue by clowcher** [primefaces/primevue#4038]
### Describe the feature you would like to see added

Currently, on desktop when you enable multiselect, you get a nice checkbox in the header of the datatable. 

However, you go to a mobile screen size with the stacked layout option, the following primevue styles force the all the `<td>` tags in the `<thead>` to have `display: none !important`. Therefore, the header disappears and you lose your global checkbox.

I understand why the header gets hidden on mobile, since the grid style changes.

But it would be really nice to display a blank header section with only the select all checkbox on mobile if the option is enabled. 

```
@media screen and (max-width: 960px) {
.p-datatable[pv_id_3] .p-datatable-thead > tr > th, .p-datatable[pv_id_3] .p-datatable-tfoot > tr > td {
    display: none !important;
}
```

### Is your feature request related to a problem?

Not sure.

### Describe the solution you'd like

It would be really nice to display a blank header section with the select all checkbox on mobile. 

Even if you just remove the `!important` from the style, we can then override it. 

### Describe alternatives you have considered

We have tried overriding the style but the !important is taking priority over any styles we try to force it to show. Even if we mark ours `!important` as well. It seems to be added to the DOM after any of the CSS we write, so it'll take precedence.

For now, we have created our own checkbox and hook into the `row-select-all` and `row-unselect-all` events. However, even with the custom checkbox, we don't get all the full functionality of the built-in primevue select all checkbox. Like how it unselects itself when you start unselecting other rows, etc, etc. 

It would be nice not to have to re-invent the wheel when this checkbox is on the DOM already.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
