### ISSUE TITLE
Treetable: InputText in body Slot does not allow space character

### ISSUE THREAD

**Issue by martinfruehmorgen** [primefaces/primevue#4045]
### Describe the bug

While editing any value in the "size" column with the InputText component it is not possible to enter space, all other characters work.
The slots (#body, #editor) like descriped in the api (https://primevue.org/treetable/#api.column.slots) are not fully integrated.

### Reproducer

https://stackblitz.com/edit/ygrc7m?file=src%2FApp.vue

### PrimeVue version

3.39.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Try to enter with the keyboard in any cell in the size column some text with space, f.e. "test 1 2 3".
2. The space character is not possible to enter.

### Expected behavior

All characters should be possible to enter. The slots like in the api description should be fully existing.

**Comment by Antmatveev** [comment]
The same behavior can be seen DataTable in slot "header", in other slots everything is fine.

```
<DataTable>
    <template #header>
        <input v-model="inputModel"> // spaces aren't printed
    </template>

    <template #footer>
        <input v-model="inputModel"> // spaces are printed
    </template>
</DataTable>
```
