### ISSUE TITLE
Column resizer on doubleclick add auto-fit to content.

### ISSUE THREAD

**Issue by ilzbergs** [primefaces/primevue#4046]
I 'm using resizableColumns on DataTable and added a double click function on columnResizer and my goal is:

- if I resize some columns and do double click on columnResizer , the columns widths changes back to starting width(maybe auto fit content...etc.).
Is it possible to do that?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
