### ISSUE TITLE
Version History in PrimeVue documentation

### ISSUE THREAD

**Issue by mtirimie1** [primefaces/primevue#4047]
### Describe the feature you would like to see added

It would be nice to have some ability to toggle between major release versions in the documentation so that we can see the version that we are using specifically.

### Is your feature request related to a problem?

There have been a lot of changes in documentation and features lately, and it's been a bit difficult to keep track of what features are in my project's version of PrimeVue. Updating is not always possible

### Describe the solution you'd like

A simple dropdown list with versions of documentation

### Describe alternatives you have considered

I've used the wayback machine but its a little incomplete when lookign for specific components

**Comment by tugcekucukoglu** [comment]
We will discuss this within the team.

Thank you!
