### ISSUE TITLE
Carousel: Responsiveness breaks when nested inside a grid of flex container

### ISSUE THREAD

**Issue by maximbelo** [primefaces/primevue#4049]
### Describe the bug

When the Carousel component is wrapped in a grid or flex container, it breaks and creates a horizontal scroll on the page. 

### Reproducer

https://codesandbox.io/p/sandbox/modest-brook-n6ysgx?file=%2Fsrc%2FApp.vue%3A2%2C9

### PrimeVue version

3.27.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add Carousel component
2. Wrap the component in a section or div tag 
3. Give the tag a display of flex or grid

### Expected behavior

The Carousel should be responsive and the functionality should remain the same when it is wrapped in a grid or flex wrapper. 

Otherwise, this issue causes problems when trying to create a layout with multiple columns.

**Comment by tugcekucukoglu** [comment]
I cloned the codesandbox and try to remove the Card component and the Carousel is still broken. https://primevue.org/carousel/ Examples might be helpful.

**Comment by maximbelo** [comment]
The Card component is not the problem...Having the Carousel inside a section with a display of grid or flex is. The examples are not helpful because they don't take into account the fact that the Carousel may be used with a multi column layout.

**Comment by bezo97** [comment]
FYI this is still an issue in primevue 4.0.5
