### ISSUE TITLE
Speed Dial: option for text label or template for link content

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#4050]
### Describe the feature you would like to see added

https://github.com/primefaces/primevue/assets/42270947/485d1f75-8f72-4da8-be93-baa22288249a

### Is your feature request related to a problem?

Icons can be ambiguous.

### Describe the solution you'd like

Either an option to display a text label below the icon, or full-fledged control over the contents of .p-speeddial-action

**Comment by tugcekucukoglu** [comment]
`item` templating can be used for menuitems.

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
