### ISSUE TITLE
MultiSelect: Disabled Header checkbox

### ISSUE THREAD

**Issue by camposAaron** [primefaces/primevue#4051]
### Describe the feature you would like to see added

Will be great that header checkbox can be disabled with the optionDisabled propertie

<img width="589" alt="image" src="https://github.com/primefaces/primevue/assets/58676376/3d5530e8-af0c-418f-8874-42b57d11a6df">

UI:
<img width="234" alt="image" src="https://github.com/primefaces/primevue/assets/58676376/34c8a208-b6f1-4020-911d-5354c3072983">

there's an alternative to do that?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
