### ISSUE TITLE
Tooltip: Add appendTo option

### ISSUE THREAD

**Issue by janvrieler** [primefaces/primevue#4053]
### Describe the feature you would like to see added

The current implementation appends the tooltip to document.body. 

![image](https://github.com/primefaces/primevue/assets/43779566/cb291a37-4f30-4351-bf5c-5b092db858a3)

It would be nice to have the option to have the option to attach it to some other element in the DOM. 

### Is your feature request related to a problem?

Due to the setup of some of our projects, custom styling from PrimeVue themes are not scoped on the the document.body but on some element within it. It is not possible to scope it at the document.body due to the setup, making it impossible to add styling to the tooltip. This is also the case when using the class property in the directive options. 

### Describe the solution you'd like

I would like to add an (optional) parameter to the tooltip properties: appendTo. If the option is not set, the tooltip is appended to document.body. Otherwise, the tooltip is appended to the provided html element. 

Example:
![image](https://github.com/primefaces/primevue/assets/43779566/67ec55e5-cae7-4876-b405-85ffec82baea)

### Describe alternatives you have considered

The alternative is using something like OverlayPanel and somehow toggling it on hover, but I think it is preferable to not have add custom logic like that for each time we need to use a tooltip (which is often)

**Comment by indy-sendhar** [comment]
I would like this feature also. We package our components as web components to drop in as micro front ends but this is the one thing that stops us from encapsulating our styles completely within the shadow dom.

**Comment by tugcekucukoglu** [comment]
Thanks for the updates. As described above, we suggest using OverlayPanel and not planning to add new options like `appendTo`.

**Comment by 3zzy** [comment]
We have exactly the same use case as @indy-sendhar. Makes absolutely no sense to not support appendTo for overlay components!

**Comment by alekoako2** [comment]
we have same issue, we have multi iframe application and need to teleport toast to top window, we managed to fix this issue with dialog and confirm dialog using appendTo, but toast doesn't have this property.

**Comment by mlmoravek** [comment]
Why can't this be added? A popover has a different semantic ARIA meaning than a tooltip!

**Comment by jnachtigall** [comment]
The proposed solution to use OverlayPanel (which is nowadays the Popover component) is not a valid workaround. The [Popover dialog](https://primevue.org/popover/#accessibility) adds completely different aria attributes the [Tooltip](https://primevue.org/tooltip/#accessibility). The Popover adds the `dialog` role and some other attributes (wrong), whereas the Tooltip adds `tooltip` role (correct).

**Popover:**
```html
<div role="dialog" aria-modal="true"
```

**Tooltip:**
```html
<div id="pv_id2_tooltip" role="tooltip"
```

So I do not see any valid workaround except the patch as provided by @indy-sendhar in #5371 

@tugcekucukoglu Please re-evaluate.
