### ISSUE TITLE
Tailwind Theme: wrong error bgcolor

### ISSUE THREAD

**Issue by emink92** [primefaces/primevue#4058]
### Describe the bug

The tailwind theme has a wrong background-color on the following components:

- Inline Message (error)
- Message (error)
- Toast Message (error)

<img width="1145" alt="image" src="https://github.com/primefaces/primevue/assets/9529536/eff87e78-1003-481a-b982-c52db4cac316">

<img width="1145" alt="image" src="https://github.com/primefaces/primevue/assets/9529536/579631cf-b5bb-430d-9e8b-2d0b1bb13d53">

<img width="396" alt="image" src="https://github.com/primefaces/primevue/assets/9529536/9ba86be0-2c7f-48d9-82da-e4137f0fa5c6">

### Reproducer

Can be seen in the documentation

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Expected behavior

Should have a redish background.

**Comment by tugcekucukoglu** [comment]
The Tailwind Light theme is not maintained anymore due to actual Tailwind integration with unstyled mode
