### ISSUE TITLE
DataTable: Icon slot template unable to get a specific style

### ISSUE THREAD

**Issue by IanLai0201** [primefaces/primevue#4062]
### Describe the bug

When I use a slot template to customize the "rowreordericon", I am unable to achieve a specific style for the reorder feature.

<img width="460" alt="image" src="https://github.com/primefaces/primevue/assets/65215264/569cde21-02b0-4a6c-9337-8f319ca9095c">

### Reproducer

https://codesandbox.io/s/exciting-turing-myj5cf?file=/src/App.vue

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Antal1609** [comment]
You need to add `data-pc-section="rowreordericon"` like this:
```html
<column :row-reorder="true" :reorderable-column="false">
    <template #rowreordericon>
        <i class="fas fa-bars" data-pc-section="rowreordericon"></i>
    </template>
</column>
```

Optionally add `p-datatable-reorderablerow-handle` for the move cursor.
