### ISSUE TITLE
Toast: allow linebreaks

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#4067]
### Describe the feature you would like to see added

I would like to have the ability to add linebreaks in my toast messages

### Is your feature request related to a problem?

My clients want defined error messages with custom linebreaks.

### Describe the solution you'd like

You could either parse `<br>` or `\n` or something in your messages

### Describe alternatives you have considered

The alternative would be to not use Prime Toasts and use a custom error message service.

**Comment by hamidovz** [comment]
@Anubarak  can't you use named slots ?

**Comment by Anubarak** [comment]
> @Anubarak can't you use named slots ?

Yeah I could - but in this case I have 2 options:
1) Copy their HTML + Logik in their components into my custom slot since I want the styling to be the same
2) create custom HTML and custom CSS to control the styling by myself

The latter would take much longer and the first one tends to break, when they do upgrades (I already did this multipe times in other components just in order to add one or two attributes here and there and PrimeVue tends to include breaking changes during their releases so I have to upgrade their HTML / Logik as well).
All in all it's way less stress to just use a different library in that case.

**Comment by hamidovz** [comment]
> > @Anubarak can't you use named slots ?
> 
> Yeah I could - but in this case I have 2 options:
> 
> 1. Copy their HTML + Logik in their components into my custom slot since I want the styling + icons to be the same
> 2. create custom HTML and custom CSS to control the styling by myself
> 
> The latter would take much longer and the first one tends to break, when they do upgrades (I already did this multipe times in other components just in order to add one or two attributes here and there and PrimeVue tends to include breaking changes during their releases so I have to upgrade their HTML / Logik as well). All in all it's way less stress to just use a different library in that case.
> 
> Edit: what I mean is: I need to move this part https://github.com/primefaces/primevue/blob/3.29.2/components/lib/toast/ToastMessage.vue#L5-L9
> 
> ```
> <component :is="templates.icon ? templates.icon : iconComponent.name ? iconComponent : 'span'" :class="iconClass" class="p-toast-message-icon" v-bind="ptm('icon')" />
>     <div class="p-toast-message-text" v-bind="ptm('text')">
>     <span class="p-toast-summary" v-bind="ptm('summary')">{{ message.summary }}</span>
>     <div class="p-toast-detail" v-bind="ptm('detail')">{{ message.detail }}</div>
> </div>
> ```
> 
> into my custom slot, `ptm` aside, I need to have access to the logic in the component `is` and `class` part

since you don't want to use slots and want to preserve origina; template then i think the best solution to your problem is adding a new property which allows preformatted text. so the provided text will  be rendered as original inluding all spaces and linebreaks. but for know you can do this by changing white-space parameter of "p-toast-detail" class in your css.

**Comment by Anubarak** [comment]
How would the css way look like?
I never wrote css our designers are responsible for that.

**Comment by hamidovz** [comment]
> How would the css way look like? I never wrote css our designers are responsible for that.

You need combine "p-toast-detail" class with deep selector (::v-deep) like this: `::v-deep . p-toast-detail { white-space : 'pre' `

**Comment by Anubarak** [comment]
Just including
```CSS
.p-toast-detail{ white-space : pre  }
```
was enough. Thank you.
I think that could be included in the documentation for JS only's like me

**Comment by tugcekucukoglu** [comment]
New [Headless mode ](https://primevue.org/toast/#headless) for Toast can be used for these cases.
