### ISSUE TITLE
Datatable:  Advanced filter only allows 2 rules

### ISSUE THREAD

**Issue by mrichar1** [primefaces/primevue#4069]
### Describe the bug

When using the advanced filter, there is the option to select 'Add Rule'. If this is clicked, a 2nd rule is created, but the 'Add Rule' button disappears and no more rules can be added.

### Reproducer

https://codesandbox.io/s/bold-surf-jrnzzd?file=/src/App.vue

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

<ol>
<li>Click on the filter icon</li>
    <li>Enter 'Contains:a'</li>
    <li>Click on 'Add Rule'</li>
    <li>Enter 'Contains:b'</li>
 </ol>
 <p>You canot now add more rules (e.g. 'Contains:c')</p>

### Expected behavior

The Add Rule button should exist no matter how many rules have been added.

**Comment by hamidovz** [comment]
@mrichar1  after checking the source code i found a property named maxcontrainst which is equal to 2 by default and also looked the api section of documentation and found that property there too. so just assign desired count of constraint to that property.  you can see the details here: [](https://primevue.org/datatable/#api.column.props.showFilterMatchModes)

**Comment by mrichar1** [comment]
Thanks - I missed this when reading the docs - will close this as not an issue :+1:

**Comment by mrichar1** [comment]
Thanks - I missed this when reading the docs - will close this as not an issue :+1:

**Comment by hamidovz** [comment]
you're welcome
