### ISSUE TITLE
Vertical Buttonset Class

### ISSUE THREAD

**Issue by kaperont** [primefaces/primevue#4070]
### Describe the feature you would like to see added

I would like to add a vertical button set class (i.e. `p-buttonset-vertical`)

### Describe the solution you'd like

Create a vertical button set class.

### Describe alternatives you have considered

I have already created the class and use it in my projects.

**Comment by kperont** [comment]
`
.p-buttonset-vertical {
  display: flex;
  flex-direction: column;

  .p-button {
    margin: 0;
  }

  // First button in set
  .p-button:first-of-type {
    border-bottom-left-radius: 0;
    border-bottom-left-radius: 0;
  }

  // Middle buttons in set
  .p-button:not(:first-of-type):not(:last-of-type) {
    border-radius: 0;
  }
  .p-button:not(:last-child) {
    border-bottom: 0 none;
  }

  // Last button in set
  .p-button:last-of-type {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

}
`

**Comment by kperont** [comment]
I have implemented the changes locally (excluding adding the class to all of the themes). Is that something that needs to be done manually? Or is there a script to add that in?

I edited/added the following files:
- `components/lib/button/BaseButton.vue`
- `components/lib/button/Button.css`
- `doc/button/VerticalButtonSetDoc.vue` (added file)
- `pages/button/index.vue`

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
