### ISSUE TITLE
MultiSelect: Filter does not work when options is an array of strings

### ISSUE THREAD

**Issue by maaattg** [primefaces/primevue#4071]
### Describe the bug

The filter in the MultiSelect component doesn't work if the `options` prop is an array of primitives/strings.

This issue was previously reported in the primereact repo (see [#3420](https://github.com/primefaces/primereact/issues/3420)) and subsequently fixed by [#3380](https://github.com/primefaces/primereact/pull/3380). However the issue persists in primevue.

### Reproducer

https://codesandbox.io/p/sandbox/red-framework-mp2p8h?file=%2Fsrc%2FApp.vue%3A8%2C1

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Visit the linked Sandbox
2. Click on the MultiSelect dropdown in the preview window
3. In the filter field, type a keyword matching one of the options, such as "red" or "Blue"
4. See error: no results are returned even if the filter string matches an option

### Expected behavior

Given an array of primitives, the MultiSelect filter (i.e. the filter service) should compare its query string directly against them instead of targeting a property.

**Comment by CraZzier** [comment]
.

**Comment by cha-hin** [comment]
+1

**Comment by xiscohv** [comment]
I have the same issue, when it will be possible to have this change in the main branch?

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4447
