### ISSUE TITLE
Picklist: Unexpected behavior on double click while holding control

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#4072]
### Describe the bug

If I hold down control, and double click on an item in the source list (it occures the other way around as well), it will be put to the target list, however the PickListEvent.items will contain the moved item twice.
![chrome-capture-2023-5-22](https://github.com/primefaces/primevue/assets/36476318/544d54ad-f708-4348-bb8d-e5d6d131101c)
![image](https://github.com/primefaces/primevue/assets/36476318/5fecfbbe-6a69-40db-926a-8601d5608b1b)
I think it shouldn't contain the same element twice, it doesn't make sense. Codesandbox example also shows this if you open console.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-qnj83h?welcome=true

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by SerxhioBekteshi** [comment]
Is there a way to disable the double click event on the list item of te picklist component?
