### ISSUE TITLE
Calendar: With range selection, endDate should be the last second of the selected day

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#4073]
### Describe the bug

If I use Calendar with `selectionMode="range",` and with `showTime=false` I expect that the last day of the selection is included completely, meaning the modelValue should be 2023-06-20 23:59:59 (last moment of the day), and not 2023-06-20 00:00:00 (current behaviour).

Checking my example, you can click on the OK button and then check the console message for the modelValues.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-2cvknn?file=%2Fsandbox.config.json%3A1%2C1

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
```
new Date("January 1, 1970");
// Thu Jan 01 1970 00:00:00 GMT+0200 (GMT+03:00)
```

This is JavaScript behavior and don't want to manipulate it. So, the best approach in this case using `showTime`.
