### ISSUE TITLE
DataTable: Formatted Data via Column <template> is not searchable

### ISSUE THREAD

**Issue by kepoly** [primefaces/primevue#4076]
### Describe the bug

As can be seen in the advanced_filter example via primevue docs: https://primevue.org/datatable/#advanced_filter

If we have a column where it has been formatted via some function i.e the date column, the global search option will not work on these columns.

In our application IDs are coming down as numerical values and formatted from an array depending on selections on the frontend and thus we encounter the same issue.

Recommended course of action here?

### Reproducer

https://primevue.org/datatable/#advanced_filter

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

All

### Steps to reproduce the behavior

1) Click primevue link
2) Observe formatted Date column
3) Try to use table global search for the first date: 09/12/2015
4) Notice no results because the date has been formatted in the HTML column template

### Expected behavior

It would be nice if the DataTable function in a way that allowed the global search to work on columns that have been formatted in the HTML template.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
