### ISSUE TITLE
Component Name: frozen column with draggable column in datatable

### ISSUE THREAD

**Issue by chandresh-0** [primefaces/primevue#4079]
### Describe the bug

Frozen column position gets changed when drag other column to frozen column's position

### Reproducer

.

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

Datatable component code:
:reorderableColumns="true"
@columnReorder="onColReorder"

Datatable component code for column component:
:frozen="col.isColumnFixed"
:alignFrozen="col.forzenPosition"
:reorderableColumn="col.draggable"

<img width="276" alt="draggble issue with frozen column" src="https://github.com/primefaces/primevue/assets/94173777/701e6489-4c0a-449d-aa7f-e073d0d494ba">

When I reorder mobile or email column with user name column it should prevent me from doing this as user name column is frozen column.

### Expected behavior

Frozen column should not be orderable with any other columns of datatable.

**Comment by mertsincan** [comment]
Hi,
I made some changes related to it in the next version. But, I think you have columns that do not have the field prop or have the same field value. The draggable columns must have a unique field value or columnKey prop.

Best Regards,
