### ISSUE TITLE
[bug] inputnumber: duplicated numbers, cannot delete numbers

### ISSUE THREAD

**Issue by Hulkmaster** [primefaces/primevue#4080]
### Describe the bug

https://github.com/primefaces/primevue/assets/2781622/1e0d7381-cd3e-4c4b-b009-465091459652
(in the video i use only 2 buttons: "2" and "backspace", i do not use arrows)

repro here: https://primevue.org/inputnumber/#prefixsuffix

try to just input number "2", and then try to delete it with backspace.

First: extra "2" is added whenever comman is added, so when you add forth "2" - you see that five "2" appears.

When i try to delete them - caret position also is somehow offsetted when "comma" is removed

### Reproducer

https://primevue.org/inputnumber/#prefixsuffix

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Version 114.0.5735.133 (Official Build) (arm64)

### Steps to reproduce the behavior

in description

### Expected behavior

no extra numbers are added; backspace deletes 2 number at a time

**Comment by Ancient-Dragon** [comment]
See this issue: #3382 , it was just fixed today but hasn't been released yet.

**Comment by Hulkmaster** [comment]
yeah, seems to be so

closed with https://github.com/primefaces/primevue/pull/3999
