### ISSUE TITLE
Dropdown: Primitive value 0 or reference value 0 does not display correctly

### ISSUE THREAD

**Issue by jkocyigi** [primefaces/primevue#4085]
### Describe the bug

Dropdown component does not display the correct label when either the selected option has a primitive value of 0 or a reference value of 0 

see sandbox

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-ylmlhj?welcome=true

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Open dropdown
2. Select option with value 0

![image](https://github.com/primefaces/primevue/assets/97892643/a99091f2-ca9e-4370-8ad0-db828ab6cbec)

### Expected behavior

The selected option should be displayed correctly

![image](https://github.com/primefaces/primevue/assets/97892643/c7270444-aad0-4bc6-9c95-faa14a444642)

**Comment by tugcekucukoglu** [comment]
Could you check that example? https://stackblitz.com/edit/vdwsus?file=src%2FApp.vue

If the problem still persists, please create a new issue
