### ISSUE TITLE
Calendar time picker editable

### ISSUE THREAD

**Issue by dy-xiaodong2022** [primefaces/primevue#4088]
### Describe the feature you would like to see added

I would like to let the time in the Calendar time picker can just with one click, then can let user type the specific time.

https://primevue.org/calendar/

### Is your feature request related to a problem?

No, it doesn’t with a bug.

### Describe the solution you'd like

Have a little bit change of time picker and let time be an input or editable content.

### Describe alternatives you have considered

I think this is a good change, it doesn’t affect the old method(click to add or minus time), and it can let selecting time easier.

### Additional context

No, that’s all

**Comment by tugcekucukoglu** [comment]
Please check the latest version. If the problem still persists, please create a new issue.

**Comment by manjindersinghsarkaria** [comment]
Even with the latest version, I'm unable to find an option to display input fields for entering time in a timepicker within the calendar.
![Screenshot_98](https://github.com/primefaces/primevue/assets/139247024/1dadb486-1e24-46a5-9466-c4cd3e679890)

**Comment by mrc-bsllt** [comment]
any update?
