### ISSUE TITLE
Dropdown/Calendar: No way to overwrite dropdown panel z-index in a nice way.

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#4093]
### Describe the bug

Somehow related to fix made by @mertsincan in #3554

Currently dropdowns are using automatic z-index handling, which not always is good. There are many cases when dropdown appear in custom elements, or are related to custom elements which are not handled by ZIndexUtils.

This is why previously I've created feature request for adding auto-z-index and baseZIndex props for the dropdown - #3121 - which was closed by previously mentioned fix.

### Reproducer

https://codesandbox.io/p/sandbox/recursing-https-4mg3dp

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to reproduction example
2. Click on the dropdown and open it
3. Scroll down
4. Observe overlapping content
5. Click on the calendar and open it
6. Scroll down
7. Observe overlapping content

### Expected behavior

Dropdown should have possibility to manually assign z-index without manually assigning classes with !important z-index applied to them.

**DISCLAIMER** Yes I know, that solution for this particular example is just to change some z-indexes. But in a more complicated example (which we're currently dealing with and that's why this bug is reported) there is no way to this nicely.

**Comment by tugcekucukoglu** [comment]
The default z-index configuration is: https://primevue.org/configuration/#zindex

These z-indexes can be changed from the config setup.

**Comment by Magiczne** [comment]
@tugcekucukoglu this is not a solution to a problem. I am aware of the ability to configure z-index.
Updated the reproducer with another case which is still suitable for this bug:

## Reproducer
https://codesandbox.io/p/sandbox/recursing-https-4mg3dp

## Reproduction
1. To to the reproducer
2. Open dropdown in the Header
3. Observe panel content rendered above header - that is perfectly fine
4. Open dropdown in the body content
5. Scroll down
6. Observe content floating above the header - **that is invalid**

And I see no options to properly configure that using ZIndex, as input dropdown panel does not have ability to manually assign z-index which was content of my previously reported bugs.
