### ISSUE TITLE
Dropdown/Calendar: Solution for placing in sticky/fix elements

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#4094]
### Describe the feature you would like to see added

I would like to see a solution for a problem when dropdown/calendar are placed instide sticky/fixed elements. They can't be used in a sensible way - for example dropdowns in search boxes in sticky headers.

### Is your feature request related to a problem?

https://codesandbox.io/p/sandbox/competent-chebyshev-mrzg9d?file=%2Fsrc%2FApp.vue%3A6%2C26

1. Open example
2. Click on the dropdown/calendar
3. Scroll view
4. Observe dropdown moving above the header and dissapearing as you scroll.

### Describe the solution you'd like

Maybe a prop which enables closing panels when user scrolls down.
Or detecting that element has sticky context, or prop "fixed" that changes the way dropdown is being positioned.

**Comment by tugcekucukoglu** [comment]
` appendTo="self"` can resolve the problem.
