### ISSUE TITLE
Datatable: Expand not working with row select and expanded rows enabled

### ISSUE THREAD

**Issue by FlorianSarron** [primefaces/primevue#4095]
### Describe the bug

When we have a datatable with row select and expanded rows enabled, when we click on expand button it selects the row and the row don't expand

### Reproducer

none

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create datatable with row select and expanded rows enabled.
2. Click on the expand button and you will see that is not working

**Comment by yormy** [comment]
I face the same issue

**Comment by yormy** [comment]
workaround::
        <Column expander style="width: 5rem"  @click.stop='' />

**Comment by yormy** [comment]
my workaround by customizing the expand
`
        <Column expander style="width: 5rem"  >
            <template #body="{ data }">
                <div @click.stop="onExpandClicked(data)">
                    <span v-if="isExpanded(data)"> UP</span>
                    <span v-else>down</span>
                </div>
            </template>
        </Column>
`

`

function containsObject(list, obj) {

    return list.some(function(elem) {
        return elem === obj
    })
}

const onExpandClicked = (data: any) => {

    if( isExpanded(data))
    {
        console.log('close');
        expandedRows.value = [];
    } else {
        console.log('open');
        expandedRows.value = [data];
    }
};

const isExpanded = (data: any) => {
    return containsObject(expandedRows.value, data);
};

`
