### ISSUE TITLE
DataTable: breakpoint is not working

### ISSUE THREAD

**Issue by shutemov** [primefaces/primevue#4096]
### Describe the bug

When trying to set the table to mobile rendering mode, nothing happens.
* Modified example from the documentation: https://stackblitz.com/edit/rlymdw?file=src%2FApp.vue,src%2Fmain.js,package.json

If you replace version primvue with 3.17.0, then breakpoint works according to the documentation.

### Reproducer

https://stackblitz.com/edit/rlymdw?file=src%2FApp.vue,src%2Fmain.js,package.json

### PrimeVue version

v3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Any browser

### Steps to reproduce the behavior

1. Go to: https://stackblitz.com/edit/rlymdw?file=src%2FApp.vue,src%2Fmain.js,package.json
2. Try to change the window size to less than 1200px
 2.1  Expected behavior: the table does not change
3. Replace the primvue version in the package.json on 3.17.0 and reload th page
 3.1 Expected behavior: after the reload, the table is rendered in a mobile form

### Expected behavior

The table should be displayed in a mobile form

**Comment by mertsincan** [comment]
Hi,

You need to use `responsiveLayout="stack"` options. But, it is deprecated. Please see; https://github.com/primefaces/primevue/issues/4131#issuecomment-1862677928

Best Regards,
