### ISSUE TITLE
Calendar: showOtherMonths - does not match the description in the documentation #2810

### ISSUE THREAD

**Issue by matheus6417** [primefaces/primevue#4099]
### Describe the bug
Documentation: (versions 2 and 3)
showOtherMonths [ boolean : true ] Whether to display dates in other months (non-selectable) at the start or end of the current month...

### Current lib code:
```
onPrevButtonClick(event) {
    if(this.showOtherMonths) {
        this.navigationState = {backward: true, button: true};
        this.navBackward(event);
    }
},
onNextButtonClick(event) {
    if(this.showOtherMonths) {
        this.navigationState = {backward: false, button: true};
        this.navForward(event);
    }
},
```

### Reproducer

https://codesandbox.io/s/funny-moon-i48yc4

### PrimeVue version

3.25.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

add :showOtherMonths="false"

### Expected behavior

Dates in other months are invisible.
Prev/next month buttons are enabled.

**Comment by tugcekucukoglu** [comment]
Please try to use the latest version. This example seems to be working https://stackblitz.com/edit/szu7bl?file=src%2FApp.vue
