### ISSUE TITLE
Data Table row checkboxes propagate click events when a checkbox is unchecked

### ISSUE THREAD

**Issue by MassimoBev** [primefaces/primevue#4100]
### Describe the bug

If I have a checkbox inside a DataTable when I uncheck it the row is clicked, and if there is an Event associated with the row-click, it will be triggered.
This should not happen.

I can't reproduce the Bug in codesandbox because the combination Vue 3.3.4 and Primevue 3.29.2 is not possible

### Reproducer

https://codesandbox.io/s/modest-feather-dmd5ql?file=/src/App.vue

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox, Chrome

### Steps to reproduce the behavior

1)Check a Checkbox inside a DataTable
2)Unchecked the Checkbox -> the row is clicked and the event is called

### Expected behavior

When a checkbox is unchecked soll the row not be clicked

**Comment by tugcekucukoglu** [comment]
I guess there is a misunderstanding here. Multiple selection and checkbox selection have different behaviors.

https://primevue.org/datatable/#multiple_rows_selection
https://primevue.org/datatable/#checkbox_row_selection

Which one do you want to use?

**Comment by MassimoBev** [comment]
This is what I have and when I unchecked the Checkbox from a row "myFunction" is called 

`   <DataTable
      v-model:selection="mySelection"
      v-model:first="first"
      v-model:rows="rows"
      :loading="loading"
      scrollable
      class="w-full h-full p-datatable-sm"
      :value="myValue"
      data-key="id"
      scroll-height="flex"
      :paginator="totalCount > 0"
      :lazy="true"
      :total-records="totalCount"
      :rows-per-page-options="[10, 20, 50]"
      :row-class="rowClass"
      @row-click="myFunction"
      @row-dblclick="myFunction2"
    >
	   <Column
        selection-mode="multiple"
      />
	  <Column>
        <template #body="{myData}">
            <i
              v-if="myData.showIt"
              class="myClass"
            />
        </template>
      </Column>
	  ...
	  </DataTable>`

**Comment by alexandrapopa96** [comment]
I have the same issue. 

For now I used as work around: `@row-unselect="isRowUnselectEvent = true"` and const ```
onRowClick = event => {
  if (!isRowUnselectEvent.value) {..}}
```

**Comment by tugcekucukoglu** [comment]
I want to ask again. Which selection mode are you trying to use?

https://primevue.org/datatable/#multiple_rows_selection
https://primevue.org/datatable/#checkbox_row_selection

**Comment by alexandrapopa96** [comment]
@tugcekucukoglu The second one: https://primevue.org/datatable/#checkbox_row_selection

**Comment by alexandrapopa96** [comment]
> I want to ask again. Which selection mode are you trying to use?
> 
> https://primevue.org/datatable/#multiple_rows_selection https://primevue.org/datatable/#checkbox_row_selection

@tugcekucukoglu The second one: https://primevue.org/datatable/#checkbox_row_selection

**Comment by jf908** [comment]
I'm also experiencing this issue so I am using this workaround for the time being:

```vue
<Column
  selectionMode="multiple"
  :pt="{
    checkboxWrapper: {
      onClick(e) {
        e.stopPropagation();
      },
    },
  }"
/>
```

Hopefully it gets fixed!

**Comment by Okdesk** [comment]
Any update on this? Having the same issue.

**Comment by farhan27555** [comment]
In case someone comes across this issue, I did this as a quick workaround. It's not pretty but it works.

```
handleRowClick(event) {
  const targetEl = event.target;
  const parentEl = targetEl.parentElement;
  if (targetEl.classList.contains("p-checkbox-icon") || parentEl?.classList?.contains("p-checkbox-icon")) return;
```

**Comment by notflip** [comment]
Why is this closed? Issue remains, with the following code, when clicking a checkbox, the rowSelect is called

```
  <DataTable
    v-model:selection="selectedUser"
    :loading="loading"
    :value="users"
    dataKey="id"
    selectionMode="single"
    @rowSelect="onRowSelect"
  >
```
