### ISSUE TITLE
DataTable: removable sort doesn't work reliably

### ISSUE THREAD

**Issue by FranzBuehl** [primefaces/primevue#4105]
### Describe the bug

The removable sort doesn't work always work.
I was able to recreate the problem in your example.

[https://primevue.org/datatable/#removable_sort](https://primevue.org/datatable/#removable_sort)

When I click on the sorting icons, sometimes the sorting does not change. No matter how often I click it. It works again when I click on the text or the white space.
I could not find out the exact pattern to reproduce the error. Sometimes you have to switch between the sorting columns a few times first.

### Reproducer

https://codesandbox.io/s/jne0jd

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 114.0.5735.199

### Steps to reproduce the behavior

1. Go to  [https://primevue.org/datatable/#removable_sort](https://primevue.org/datatable/#removable_sort)
2. Sort the columns by clicking on the sorting icons.
3. Change sorting multible times, also between columns.
4. Sorting does not change any more until you click on the name or the whitespace.

### Expected behavior

Changing the sort does always work also when you click on the icon.

**Comment by tugcekucukoglu** [comment]
The codesandbox and live demos seem to be working.

Cannot replicate.

**Comment by FranzBuehl** [comment]
Here is a video, how I reproduced it on https://primevue.org/datatable/#removable_sort

https://github.com/primefaces/primevue/assets/107650239/cb3f8c15-bd72-46e8-aaea-f00584937ace

**Comment by FranzBuehl** [comment]
Why is this issue closed?
