### ISSUE TITLE
Add Remove Button for AutoComplete for single item

### ISSUE THREAD

**Issue by cuberinooo** [primefaces/primevue#4108]
### Describe the feature you would like to see added

I would like to have a remove icon button like here: https://primevue.org/dropdown/#clearicon for the AutoComplete component. In AutoComplete you can use "multiple" as per default it will show a remove icon button on each selected item. But it would be great if we could use this on a single selected item (without the property "multiple")

### Describe the solution you'd like

Like as you would use the Dropdown component where you are able to add a remove button whenever an item is selected to deselect the item. 
An alternative would be to change the view of the selected item by using a slot. I saw in the docs that "item" is deprecated
https://primevue.org/autocomplete/#api.autocomplete.slots.item

### Describe alternatives you have considered

See solution

**Comment by tugcekucukoglu** [comment]
In the future, we might add it if there is more demand. item template is deprecated but option templating can be used for this.

**Comment by cuberinooo** [comment]
Thanks !
I thought the item slot relates to the selected value. (The name is indeed irritating). What I meant is to have a slot where you can change the template of the selected value. In the Dropdown component it would be the slot "value".

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by jiliop** [comment]
Hi, I need clear/remove Icon on autocomplete as well. (on single selection mode)
Thank you.

**Comment by zhoub** [comment]
Bump, it would be great to have this.

**Comment by philippmunzert** [comment]
Bump, could also need this for the component at the moment.

**Comment by JeeDevUser** [comment]
+1 for this request. It would be great to have this

**Comment by francescods** [comment]
+1

**Comment by beqachx** [comment]
or add at least new slot, so we can implement it ourself

**Comment by nicklas-nilsson-ux** [comment]
+1 for this request.
I also think it would be good if different input fields had a consistent way to present the clear action and how it behaves interaction wise. An example is to compare how "clear" is implemented in DatePicker and Select.

**Comment by jfranciscoap** [comment]
Just to add my 2c here: There is a very consistent primevue way of doing this, but that, indeed, could be automated to an attr: you can use `<IconField>` and `<InputIcon class="pi pi-times" @click="<theref> = null" />`. You can style it further as well with hover classes (if you use tailwind).

I support the enhancement, but there is indeed a low-coding way of doing this

**Comment by edihasler** [comment]
+1

**Comment by suzumejakku** [comment]
+1 for this request
