### ISSUE TITLE
The `primevue[.min].css` has been deprecated

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#4110]
All components now add their own styles when they are created. Good bye, primevue.css :wave:

**Comment by AmmarMohamadIsmaeel** [comment]
Removing the primevue.css was not a good idea as long as RTL is not supported yet.
I used primevue for about 1 year in the RTL mode by converting primevue.css classes to RTL using rtlcss.com, but now after I upgraded to 3.3.1, the site in the RTL is messy, Is any solution for this other than waiting for the RTL support? @mertsincan

**Comment by bruno-braga** [comment]
So, I'm presuming it should just work even with nothing on primevue.css/primevue.min.css? I have a situation here in which on 3.42 no style is done on components, but, primeflex works just fine.

When downgraded to 3.29 the styles were being applied.
