### ISSUE TITLE
Multiselect: Dropdown Floating when opens on top

### ISSUE THREAD

**Issue by fil619** [primefaces/primevue#4111]
### Describe the bug

![image](https://github.com/primefaces/primevue/assets/13111100/c5a6b4a7-4c12-4b30-a6e1-94a141a9d39c)

Step 1 : MultiSelect Dropdown positioned on top with Filter enabled.
Step 2 : Type in Random Text.
Dropdown position is not near the input field. 

Issue 2 : 
When having a dropdown in a dialog, on moving the dialog along, the dropdown menu stays fixed.
![image](https://github.com/primefaces/primevue/assets/13111100/88acddd0-60fc-4114-a1f2-94f013b308a7)

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-cgvhtq

### PrimeVue version

^3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

Step 1 : MultiSelect Dropdown positioned on top with Filter enabled.
Step 2 : Type in Random Text.

### Expected behavior

Issue 1
Dropdown stays near the input field
![image](https://github.com/primefaces/primevue/assets/13111100/2368539f-7509-4f18-860a-58cbc89b0381)

Issue 2 : 
Dropdown closes when clicked outside

**Comment by Quang-Dong** [comment]
any updates?

**Comment by pollna** [comment]
I'm facing simmilar problem, hope for any update on it 🙏 
For now I decided to set fixed height of panel in several places and they look strange with this behavior 😥

**Comment by tugcekucukoglu** [comment]
Via [panelClass](https://primevue.org/multiselect/#api.multiselect.props.panelClass) class attribute can be changed.
