### ISSUE TITLE
DataTable with cell editing: cell-edit-complete/cancel events seem to be called to late

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#4112]
### Describe the bug

Hi,
I have a tricky issue which I think is related to how the events on cell editing are raised, especially on scenario when clicking 'outside' the cell. I'm not sure I can find a workaround without changing the user experience, that's why I'm writing a report.

Basically, what happens is that when clicking outside to make an action on the row (or the complete data), for example when clicking on a button, the data of the datatable is not yet updated by the time the button is pressed. (The data is updated once the cell-edit-complete event is raised, but it is raised AFTER the click event on the button). You would have to make an extra step to force the unfocus of the cell (which cannot be done programmatically, because the Datatable component store some state internally about what cell is/are being edited) and make it so that it happens before you click on any other button.
Plus, it can induce strange behaviour in some cases due to stale data being memorized in the Datatable. (see repro steps below)

### Reproducer

https://codesandbox.io/p/sandbox/happy-scott-56vsqy?file=%2Fsrc%2FApp.vue%3A28%2C46

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

The provided repro sandbox includes:
1. a Datatable with operating cell edition, displaying 2 columns
2. one button to add a new row
3. a button to delete the selected row
4. a button "Do something" on each row that print the column Name in a toast

Repro steps:
1. Select a row and modifies the name field
2. Click on "Do something"
3. The name being displayed is the name before the editing. This is because the cell-edit-complete was raised after the click event of the button

Steps to make it work:
1. Select a row and modifies the name field
2. Tab or click elsewhere (either to stay on the same row or not, doesn't matter) to have the Name cell leave the edit mode
3. Click on "Do something"
4. The name being displayed is correct this time because the data has been updated before clicking on the button

Now another issue:
1. Select the 1st row by clicking on the Name field: The cell Name is now in edit mode
2. Click on "Delete row" button
3. Redo step 1: Notice the cell content changed to the name that was just deleted. This is because Datatable kept in memory that the cell of the removed row was in edit mode and the associated value.

To avoid it:
1. Select the 1st row by clicking on the right of the "Do something" button: No cells of the row are in edit mode
2. Click on "Delete row" button
3. Reselect the 1st row from the Name: Cell is in edit mode but didn't change value.

### Expected behavior

As a resolution, I'd consider modifying the 2 methods of the BodyCell.vue : bindDocumentEditListener and unbindDocumentEditListener and ~~changing the listened event from 'click' to 'mousedown'~~

I don't know as much as you guys, what could be the potential regressions/side effects as a result of this.

**Comment by NikoGJ** [comment]
Note that it would maybe also "fix" another unwanted side-effect with cell editing, which is when the user selects the content of an InputText inside the cell by using mouse drag, if the mouse goes out of the cell and the user releases the mouse button, then the cell goes into view mode again, losing the text selection.
That behavior can be disturbing for users because standard input controls in browsers in comparison don't work that way.

**Comment by NikoGJ** [comment]
I'll see if I can't do the fixing myself and eventually submit a PR for a review.

**Comment by mertsincan** [comment]
Hi,

You need to control this behaviour. DataTable with cell-editing binds the document.click event and when you click on the button, the button's click event will be called first and then Datatable's document.click event will be called. Therefore, the button's click event processes the old data before the data is refreshed. To overcome such problems, you can wrap the button's click event with `setTimeout` or block the button with css or js until the cell-edit-complete process is completed.

Best Regards,

**Comment by Ignlek** [comment]
> Note that it would maybe also "fix" another unwanted side-effect with cell editing, which is when the user selects the content of an InputText inside the cell by using mouse drag, if the mouse goes out of the cell and the user releases the mouse button, then the cell goes into view mode again, losing the text selection. That behavior can be disturbing for users because standard input controls in browsers in comparison don't work that way.

Hi Niko, as i understand nobody fixed this issue with drag, maybe you know why?

**Comment by NikoGJ** [comment]
Hi @Ignlek,
As far as I know, it's still not fixed. However, I haven't tested if this behaviour is still present in V4....

The DataTable component is quite complex with all the features it has, so I'm guessing this is a hard task to do without inducing regressions.
But I agree, this behaviour is very annoying and disturbing, that's why I stopped using the cell edit feature and went on writing my own implementation. 😅
