### ISSUE TITLE
TreeTable: A "select all" checkbox in a the table header of a TreeTable

### ISSUE THREAD

**Issue by JasonLandbridge** [primefaces/primevue#4115]
### Describe the feature you would like to see added

A "select all" checkbox in a the table header of a [TreeTable](https://primevue.org/treetable)

### Is your feature request related to a problem?

In [the Angular version](https://primeng.org/treetable#checkbox) I see a separate checkbox to select all so I figured I do the same.

![image](https://github.com/primefaces/primevue/assets/15127381/f6d6cc33-8c5c-41c4-808f-e927b1c207cd)

However, now it just floats there and it would be better to have it in front of the first column.

### Describe the solution you'd like

Ideally there would be an extra header slot in the TreeTable that allows me to set a custom checkbox, which can then be used to toggle everything.

**Comment by darkvertex** [comment]
A builtin feature would be very welcome.

I was able to hijack this feature into a `<TreeTable>` of checkboxed rows I had by using a fieldless column with the "expander" property, like this:

```
<Column expander headerStyle="width: 3rem">
  <template #header>
    Test
  </template>
</Column>
```

I put that before my other columns. The `<Column>` with "expander" is the one that gets the column of checkboxes. Afterwards it's easy enough to override the `#header` template with something practical.

You can replace "Test" with a TriStateCheckbox or whatever component you want, and make that component do a select-all on `@click` and have it set the `v-model:selectionKeys` value accordingly to make the mass selection happen.

---

Now, do I wish I could just set a magical `:displaySelectAllCheckbox="true"` attribute on my `<TreeTable>` and it do the above for me? Absolutely I do. 😅

**Comment by darkvertex** [comment]
Hnmm, perhaps my trick is not ideal. It appears to break indentation of nested items when the "expander" column is not the first one with the name in it.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by Hassanbhb** [comment]
I opened a discussion [here](https://github.com/orgs/primefaces/discussions/3016)
still couldn't find a way
