### ISSUE TITLE
Tooltip component: Escape option no work

### ISSUE THREAD

**Issue by nikkable** [primefaces/primevue#4116]
### Describe the bug

If an object is passed in which a string with HTML tags is passed, with the "escape" option specified, no "innerHTML" occurs. Added a fix that solves this problem, please roll it out to "npm". Thank you!

### Reproducer

https://github.com/nikkable/primevue/blob/nikkable-patch-1/src/components/tooltip/Tooltip.js

### PrimeVue version

2.10.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
https://stackblitz.com/run?file=src%2FApp.vue

Cannot replicate the issue.

**Comment by muhammadhendrahaqq** [comment]
i find it also not working, try to set false, and it still render plain string of html

**Comment by Arham1243** [comment]
> i find it also not working, try to set false, and it still render plain string of html

in v3 it actually works if you set escape: true
```
<Button
    v-tooltip="{
        value: '<strong>Bold text</strong><br/>Line break<br/><em>Italic text</em>',
        escape: true
    }"
    label="Hover me"
/>
```
