### ISSUE TITLE
Component DataTable, trying to sort rows with sub-properties with sortField

### ISSUE THREAD

**Issue by mdartic** [primefaces/primevue#412]
Hello,

Thanks for this amazing library !

We are trying to sort data in a DataTable, but some "columns" are in fact Objects.

For displaying the table, no problem, we use the slot `#body`, and so we can display what we want from the column.

But, for sorting (and I think for filtering too), we try to use the `sortField` without success.

Example of data displayed : 

```json
[
  {
    "14a772f2-c161-4931-a8e5-bfb3acaaf42d": "10/07/2020",
    "360a9a83-d046-4b64-a39e-944d2bfbd9c5": {
      "value": "AAAA",
      "reference": 5
    },
    "3a659ea1-446f-4755-8db9-583a204279cc": 1,
    "80780a95-d709-43ec-b4f3-d6b5cb5dd31e": "10/10/2020",
    "b712959e-3808-4bbc-b86e-17ab2ded8c6d": "XXXX",
    "bde4bbbd-2584-447f-acff-f434f53619da": {
      "value": "ZZZ",
      "reference": 4
    },
    "e065323c-1151-447f-be0f-6d2728117b38": "AZE"
  },
  {
    "14a772f2-c161-4931-a8e5-bfb3acaaf42d": "01/07/2020",
    "360a9a83-d046-4b64-a39e-944d2bfbd9c5": {
      "value": "CCCC",
      "reference": 5
    },
    "3a659ea1-446f-4755-8db9-583a204279cc": 2,
    "80780a95-d709-43ec-b4f3-d6b5cb5dd31e": "01/10/2020",
    "b712959e-3808-4bbc-b86e-17ab2ded8c6d": "YYYY",
    "bde4bbbd-2584-447f-acff-f434f53619da": {
      "value": "XXX",
      "reference": 3
    },
    "e065323c-1151-447f-be0f-6d2728117b38": "QSD"
  },
  {
    "14a772f2-c161-4931-a8e5-bfb3acaaf42d": "16/07/2020",
    "360a9a83-d046-4b64-a39e-944d2bfbd9c5": {
      "value": "DDDD",
      "reference": 6
    },
    "3a659ea1-446f-4755-8db9-583a204279cc": 3,
    "80780a95-d709-43ec-b4f3-d6b5cb5dd31e": "16/10/2020",
    "b712959e-3808-4bbc-b86e-17ab2ded8c6d": "ZZZZ",
    "bde4bbbd-2584-447f-acff-f434f53619da": {
      "value": "OOOO",
      "reference": 3
    },
    "e065323c-1151-447f-be0f-6d2728117b38": "ERT"
  }
]
```

We want sort by all of these columns, each uuid is matching a column name (in another object, and that's fine).

We can sort the "basic" columns, with the `field` prop, by setting this prop to the column uuid.

But for the complex ones, we would like make a sort on the `value` prop.

Can we do this by setting the `sortField` prop, maybe only for the complex columns ?

I think actually we can't do this, because it's not "dynamically" done, for each row.

Could we imagine that `sortField` could be a function executed for each row, returning the value we want to sort ?

**Comment by cagataycivici** [comment]
At online sample, the representative is an object just like the country;

https://primefaces.org/primevue/showcase/#/datatable

It uses sortField="representative.name" and it seems to be working. If you can provide a stackblitz, we can discuss over it.

**Comment by mdartic** [comment]
Thanks for your answer,

Here is a jsfiddle : https://jsfiddle.net/rfgtp0ze/13/

You can see three examples.
The first one use data "normalized" for helping DataTable component.
The other ones use original data.
The second one doesn't use the `sortField`, and the last one use a method for getting dynamically the value of sortField.

But, second & third ones don't work as I would like.

If you have an idea of what's wrong, that would be really nice !

**Comment by cagataycivici** [comment]
Let me work on the fiddle and get back to you.

**Comment by cagataycivici** [comment]
I think ``'${column.id}.value'`` should be ``'${column.id}.value``
