### ISSUE TITLE
DataTable: Selection and Row/Cell editing : Cannot input space character

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#4120]
### Describe the bug

When a datatable uses selection mode single or multiple and cell or row editing, we cannot input space character in the InputText anymore.

### Reproducer

https://codesandbox.io/p/sandbox/loving-noyce-yxnmvh?file=%2Fsrc%2FApp.vue%3A13%2C37

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Check the codesandbox
Try input data with some space characters in both datatables.
Notice that only the datatable with no selection works with space characters.

### Expected behavior

It should be possible to input space characters in InputText in all scenarios.

**Comment by limbitskiy** [comment]
yes, i have the same problem

**Comment by MarcM-PL** [comment]
I updated to 3.34.1 today and I still see this issue, is there anything else I need to do?

**Comment by RedLionHeart** [comment]
Still not working, with 3.35.0

**Comment by NikoGJ** [comment]
@MarcM-PL Tested with the original reproduer in 3.35.0 and I don't see the issue anymore.
Could you share a repo sand box with your scenario ?
