### ISSUE TITLE
[Feature Request] Please provide full styling example for unstyled mode

### ISSUE THREAD

**Issue by martinszeltins** [primefaces/primevue#4123]
### Describe the feature you would like to see added

Right now if you take a look at the [Calendar component](https://primevue.org/calendar/#pt.demo), you can see that there is only a partial custom style example _(only input and dropdownButton)_ in the [Pass Through section](https://primevue.org/calendar/#pt.demo). It would be very useful to have an example with ALL of the options for custom styled components. It would make styling unstyled components much easier if there were full examples.

![image](https://github.com/primefaces/primevue/assets/34019878/376acaac-9a1d-4992-ba9b-089e7b8f4825)

**Comment by mertsincan** [comment]
Thanks @martinszeltins, we're working on it ;) We'll release it with 3.31.0. https://discord.com/channels/787967399105134612/787968875135762452/1126596004175683594

**Comment by martinszeltins** [comment]
> Thanks @martinszeltins, we're working on it ;) We'll release it with 3.31.0. [discord.com/channels/787967399105134612/787968875135762452/1126596004175683594](https://discord.com/channels/787967399105134612/787968875135762452/1126596004175683594)

Awesome, thank you! 👍🏻
