### ISSUE TITLE
splitbutton (change color)

### ISSUE THREAD

**Issue by basitiyidir** [primefaces/primevue#4127]
### Describe the feature you would like to see added

I am trying to change the colors of the SplitButton, but the style and class are not working.

While the class and style work for Button, they don't work for SplitButton. Why could this be?

You can check it yourself from here.

https://primevue.org/splitbutton/

**Comment by tugcekucukoglu** [comment]
New `pt` property can be used or you could check the templating demo: https://primevue.org/splitbutton/#template
