### ISSUE TITLE
ProgressSpinner: is not spinning

### ISSUE THREAD

**Issue by jaimesuarez99** [primefaces/primevue#4128]
### Describe the bug

Hi, here I want to report a minor issue with the ProgressSpinner component, from the 3.29.0 release the spinner is not been working, I know it is not a  big deal, but I want you all to know it. it happens when we use the prop "fill="var(--surface-ground)", u can see it in your own code sandbox, however when we use the simple implementation which is just calls the component without any prop it works.

### Reproducer

https://codesandbox.io/s/24cz5k?file=/src/App.vue

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

just importing the ProgressSpinner

### Expected behavior

not spinning

**Comment by RichardRepenning** [comment]
Opened your reproducer and it is spinning. Spinner is changing colors.

**Comment by reksc** [comment]
In my case this was purely CSS issue. I was still importing the old `'primevue/resources/primevue.min.css';` and it doesn't play with the current ProgressSpinner component.
