### ISSUE TITLE
DataTable: Exporting an empty DataTable throws TypeError

### ISSUE THREAD

**Issue by cRAN-cg** [primefaces/primevue#413]
# 🐞 bug report

### Affected Package
 The issue is caused by package primevue/datatable

### Is this a regression?

 No

### Description

 Exporting any DataTable instance with empty values (undefined/null) throws a TypeError

## 🌍  Your Environment

**PrimeVue Version:**
<pre>
"primevue": "^1.2.0"
</pre>

**Comment by cagataycivici** [comment]
Thanks.
