### ISSUE TITLE
TabView: Some unstyled classes not working as expected

### ISSUE THREAD

**Issue by dflock** [primefaces/primevue#4132]
### Describe the bug

I'm trying to use unstyled mode, then apply Bootstrap classes to some Tabs. This is minimal bootstrap markup, showing the classes I need to output:

```html
<ul class="nav nav-tabs">
  <li class="nav-item">
    <button class="nav-link active">Header I</button>
  </li>
  <li class="nav-item">
    <button class="nav-link">Header II</button>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane show active">Panel I</div>
  <div class="tab-pane">Panel II</div>
</div>
```

This is some (slightly) simplified DOM output from PrimeVue:

```html
<div class="root" data-pc-name="tabview" data-pc-section="root">
  <div class="navContainer" data-pc-section="navcontainer">
    <div class="navContent" data-pc-section="navcontent">
      <ul role="tablist" class="nav nav-tabs" data-pc-section="nav">
        <li data-pc-name="tabview" data-pc-section="header" class="nav-item">
          <a data-pc-section="headeraction" class="nav-link active">
            <h2>Header I</h2>
          </a>
        </li>
        <li data-pc-name="tabview" data-pc-section="header" class="nav-item">
          <a data-pc-section="headeraction" class="nav-link">
            <h2>Header II</h2>
          </a>
        </li>
        <li class="inkbar" data-pc-section="inkbar"></li>
      </ul>
    </div>
  </div>
</div>
```

you can see that this partially works - I can apply classes to the `root`, `navContainer `& `navContent` (none of which I need). I can also apply the `nav nav-tabs` classes to the `<ul>` - but I can't seem to apply classes to the `<li>` or `<a>` elements, so the styling doesn't work properly.

Going by the documentation [here](https://primevue.org/tabview/#api.tabpanel), I think I ought to be able to set these classes by doing something like this in my `bootstrap.ts`:

```ts
const Bootstrap_PT: PrimeVuePTOptions = {
	...
	tabPanel: {
	  headerAction: { class: 'nav-link' },
	  headerTitle: { class: 'nav-item' },
	}
	...
}
```
... but that doesn't seem to add any classes to the DOM?

There's a reproduction here which shows this: https://codesandbox.io/p/sandbox/unstyled-primevue-tabs-with-bootstrap-2j7gyl?embed=1&file=%2Fsrc%2FApp.vue%3A8%2C8, based on the example from here: https://primevue.org/bootstrap/

### Reproducer

https://codesandbox.io/p/sandbox/unstyled-primevue-dialog-with-bootstrap-forked-2j7gyl?embed=1&file=%2Fsrc%2Fmain.ts%3A16%2C33

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

I expect to be able to apply classes using the passthrough mechanism to the `<li>` or `<a>` elements of the tabs, as documented here: https://primevue.org/tabview/#api.tabpanel

**Comment by mertsincan** [comment]
Hi @dflock,

Could you please try https://codesandbox.io/p/sandbox/unstyled-primevue-tabs-with-bootstrap-forked-nq93pk?embed=1&file=%2Fsrc%2Fpassthrough%2Fbootstrap.ts%3A28%2C6

**Comment by dflock** [comment]
That works, thanks!
