### ISSUE TITLE
Paginator: Docs Passthrough wireframe numbers don't match

### ISSUE THREAD

**Issue by dflock** [primefaces/primevue#4140]
### Describe the bug

The numbers in the wireframe on this page: https://primevue.org/paginator/#pt.image don't match up with the list in the table below.

They seem correct up to "7: previousPageButton" - after that they're mostly wrong, I think.

### Reproducer

https://primevue.org/paginator/#pt.image

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for your attention!
