### ISSUE TITLE
Editable Cells for TreeTable

### ISSUE THREAD

**Issue by y-emiage** [primefaces/primevue#415]
As datatable component, could you add " cell editing mode " in TreeTable ?

**Comment by cagataycivici** [comment]
Sure, on the roadmap since NG already has it;

https://primefaces.org/primeng/showcase/#/treetable/edit

**Comment by Soph0208** [comment]
When will this feature be integrated for Primevue?

**Comment by cagataycivici** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
