### ISSUE TITLE
InputSwitch: Loading state

### ISSUE THREAD

**Issue by m3hari** [primefaces/primevue#4154]
### Describe the feature you would like to see added

I wanted to show a loading state when using `InputSwitch` for long-running tasks. however, there is no easy way to do it now.

### Is your feature request related to a problem?

Yes, usually we do async actions when toggling `Switch` , in those cases we would like to show loading state to the user

### Describe the solution you'd like

- Providing a slot for the `thumb` will make it flexible to do anything 
- Adding `loading` props on `InputSwitch` to conditionally show a loading spinner on the thumb is best

[Vuetify has](https://vuetifyjs.com/en/components/switches/#states) loading props for switchs

### Describe alternatives you have considered

- Played with CSS to override the content of the `thumb` , but as it's a  pseudo-element it makes it difficult to reuse an existing spinner class

### Additional context

Vuetify as inspiration 
<img width="245" alt="Screenshot 2023-07-18 at 12 20 01" src="https://github.com/primefaces/primevue/assets/9920926/f862a403-eac0-42d9-878c-406d5640b1cb">

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
