### ISSUE TITLE
Chips PassThrough does not work with Tailwind in Nuxt 3

### ISSUE THREAD

**Issue by KuyaKoya** [primefaces/primevue#4155]
### Describe the bug

I tried using the passthrough feature for the Chips component to modify the default styles using tailwind however this does not work. Tried looking into the source code of the component and it seems like there is an Internal CSS definition in the Base Chip component.
This results to the screenshot below:

<img width="630" alt="Screen Shot 2023-07-18 at 4 06 53 PM" src="https://github.com/primefaces/primevue/assets/30855417/ebff604a-25e4-4701-9fba-d731d6e3b5d9">

the `<style>` block comes from the BaseChip.vue
the `_common.scss` comes from https://github.com/primefaces/primevue-sass-theme
the `utilities.css` comes from tailwind

this could also be the case for #3960 

### Reproducer

https://codesandbox.io/p/sandbox/busy-lumiere-6ymt8k?file=%2Fsrc%2FApp.vue%3A22%2C5

### PrimeVue version

3.30.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 114.0.5735.198

### Steps to reproduce the behavior

1. Create Nuxt 3 project.
2. Install PrimeVue (as in docs) and Tailwindcss Nuxt 3 plugin (https://nuxt.com/modules/tailwindcss)
3. Add the Chips with a tailwind classes to a component:
```vue
<Chips
      v-model="chips"
      class="mt-[18px]"
      :max="5"
      :pt="{
        root: { class: 'block' },
      }"
    />
``` 
4. The component will not change to have display: block

### Expected behavior

Chips component should have display:block

**Comment by mertsincan** [comment]
Hi,

This is related to your Tailwind configuration. I checked the DOM and Chips component adds 'block' class. Could you please check DOM?

Best Regards,

**Comment by mertsincan** [comment]
Ah sorry, I noticed it now. PT is just adding properties to DOM elements. Added classes do not mean that they will be stronger. So there are two ways to solve this issue.
https://tailwindcss.com/docs/configuration#important
OR
you can use `unstyled` attribute to style whole component.
https://primevue.org/unstyled/

Best Regards,

**Comment by KuyaKoya** [comment]
Thank you for your response.
I tend to use `important` as a last resort if there are other ways to go around the issue and using `unstyled` seems overkill when I only want to change the display to `block`
Nevertheless, thank you for the input
