### ISSUE TITLE
OrganizationChart: Allow use of Display instead of Visibility

### ISSUE THREAD

**Issue by RodTGG** [primefaces/primevue#4158]
### Describe the feature you would like to see added

Allow the use of display prop instead of visibility pop to control the child node visibility/display. This would allow nodes shrink and grow when collapsed and not collapsed.

### Is your feature request related to a problem?

Not really, displaying medium to large data causes some overflow. Allowing the tables to shrink simply helps avoiding scrolling for nodes that had long labels and bring everything towards the center

### Describe the solution you'd like

Not sure if a prop or an override through the pass through props can be added to allow overriding using the visibility hidden prop and use the display none prop instead

### Describe alternatives you have considered

Tried using on expand and collapsed finding the dom element clicked and toggling all children manually.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
