### ISSUE TITLE
TreeTable: Dynamic columns

### ISSUE THREAD

**Issue by Asbarn** [primefaces/primevue#4165]
### Describe the bug

I've created a "wrapper" component with a PrimeVue's TreeTable component in it and it should accept an array of PrimeVue's Columns passed via default slot. But apparently TreeTable is ignoring the fact that when passing the children using v-for it gets wrapped in a additional fragment (mock wrapper, which doesn't render anything and is thrown away during the rendering. That's why when trying to find the columns, TreeTable can't find them because there's a fragment in the array, not Column

### Reproducer

https://stackblitz.com/edit/nfvmaa

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to the stackblitz
2. Notice that nothing is rendering and there's a "Uncaught TypeError: Array.prototype.filter called on null or undefined" error in the console

### Expected behavior

Developer can pass the Column using v-for to the custom components containing TreeTable and it's rendering correctly

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by antony-k1208** [comment]
@Asbarn did you find a solution for this yet? We are currently experiencing the exact same issue
