### ISSUE TITLE
TreeTable: Custom Column header sort event

### ISSUE THREAD

**Issue by Asbarn** [primefaces/primevue#4166]
### Describe the bug

Sort event does not happen because click event does not get triggered. The reason is because custom sort icon has data-pc-section="sort" but in the TreeTable it checks for "sortIcon"
<img width="991" alt="image" src="https://github.com/primefaces/primevue/assets/47718251/d4e84291-445d-4204-bd4c-c6df62b5075b">
![image](https://github.com/primefaces/primevue/assets/47718251/648ea79e-86dc-46fd-8aef-f1a8e6792bfd)

### Reproducer

https://stackblitz.com/edit/nfvmaa-hhucse

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to stackblitz link
2. Try to apply sorting by clicking on the sort icon

### Expected behavior

Rows should be sorted when clicking on the sort icon

**Comment by tugcekucukoglu** [comment]
Could you try to use the latest version?

If the problem still persists please open a new issue.
