### ISSUE TITLE
Related to all overlay components (dialogs, toasts, dropdowns etc)

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4168]
### Describe the feature you would like to see added

In case if we are using nested vue3 applications, it will be better to place nested app's overlays to nested app's container, but not to body

### Is your feature request related to a problem?

Overlay components working incorrect if we create nested vue3 application on external component. It is because overlays are added to body, but not to nested container, and it causes issues with css in case if we create selectors using nested application container id

Also, if I pass appendTo prop to overlay components, overlay appends to the container i need, but its absolute position is wrong

### Describe the solution you'd like

Maybe we should pass application container id to primevue configuration to use it as root, or something like this

**Comment by tugcekucukoglu** [comment]
In this case, we suggest using the `appendTo` property. And if a problem occurs, `pt` property can helped.

**Comment by 3zzy** [comment]
@tugcekucukoglu Could you please provide an example of a Toast appended to a custom container using either `appendTo` or `pt` as you described? Thanks!
