### ISSUE TITLE
TreeTable: Custom Column's Toggler Icon

### ISSUE THREAD

**Issue by Asbarn** [primefaces/primevue#4170]
### Describe the bug

Can't provide custom toggler icon via Column's "rowtogglericon" slot. Only toggler from the TreeTable's slot "togglericon" but it doesn't provide rowExpanded or something else to check whether the row is expanded or not (ex. we want to rotate the custom icon on row expand )

Note: Also attributes from the pt's rowGroupToggler are not applied so we can't provide aria-label for toggler's button for accesibility 

### Reproducer

https://stackblitz.com/edit/nfvmaa-jh7cwq?file=src%2FApp.vue,src%2FDataTable.vue,src%2Frouter.js

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to stackblitz link
2. Notice that Column's rowtogglericon content is not applied
3. Uncomment TreeTable's togglericon and notice that it is being applied
4. Also notice that data for rowGroupToggler is not being applied

### Expected behavior

We can provide custom toggler icon for Column
We can check whether the row is expanded in the TreeTable's togglerIcon slot
We can provide attributes to the rowtoggler and its icon

**Comment by ZiadJ** [comment]
I haven't looked at the other issues but `v-slot:togglericon="{ expanded }" `seems to work fine
