### ISSUE TITLE
TreeTable: Sort Icon

### ISSUE THREAD

**Issue by Asbarn** [primefaces/primevue#4171]
### Describe the bug

SortIcon slot content is not being applied to the TreeTable and the default icon is being shown. But at the same time the SortIcon from the Column's sortIcon slot is being applied

### Reproducer

https://stackblitz.com/edit/nfvmaa-ky9gwj?file=src%2FDataTable.vue

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to stackblitz link
2. Notice that Name Column has default PrimeVue's icon on sort

### Expected behavior

1. We can provide sort icon for TreeTable so we won't need to add additional code and add the same sort icon to each Column

**Comment by tugcekucukoglu** [comment]
sorticon slot does not belong to the TreeTable, belongs to the Column component.
