### ISSUE TITLE
Dropdown: default optionLabel and default optionValue are null (but doc say, default to label and value)

### ISSUE THREAD

**Issue by deguich** [primefaces/primevue#4174]
### Describe the bug

When using a simple dropdown with data like : 
```javascript
const data = [
  {label: "first", value: "firstval"},
  {label: "second", value: "secondval"}
];
const selectedData = ref();
```

This dropdown should show a list of labels, it shows the objects list :

```javascript
<Dropdown
  v-model="selectedData"
  :options="data"
/>
```

 

### Reproducer

https://codesandbox.io/p/sandbox/condescending-tu-n5pvck

### PrimeVue version

3.30.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by dkurucz** [comment]
@deguich I am seeing the same thing, so I took a look at the source for dropdown and it appears things aren't working as documented... and it appears to be a pattern across lots of other selection-based controls.  Working on a fix but it might be a bit.

**Comment by deguich** [comment]
Could you re-open this issue ?

**Comment by dkurucz** [comment]
@deguich @mertsincan PR opened to fix this issue: https://github.com/primefaces/primevue/pull/4340.  Please review at earliest convenience.  This is a blocker for my project and I will be referencing the fork until this is pulled in!

If I am missing anything such as a test scenario or documentation update, etc, please also let me know so I can address.

Thanks!

**Comment by tugcekucukoglu** [comment]
Sorry for the confusion. Documentation will be fixed.

**Comment by deguich** [comment]
Hi,
I think the documentation is accurate and describes a functioning that should be correct.
Why don't fix the code ?
