### ISSUE TITLE
Improve connected overlay positioning

### ISSUE THREAD

**Issue by nestorrente** [primefaces/primevue#418]
When using `appendTo="body"`, dropdown's option list overflows the viewport's width if the element is near to the right side of the screen, even if there is enough space to display the list:

![image](https://user-images.githubusercontent.com/9889025/89104577-9a3abb80-d41a-11ea-8946-2d94f1636650.png)

You can see it in action here: https://codesandbox.io/s/hardcore-satoshi-xz465?file=/src/components/HelloWorld.vue

I think the problem is at this line of `DomHandler`:
https://github.com/primefaces/primevue/blob/d624e17cf12bb1e6647b8106bd7292163e377d0d/src/components/utils/DomHandler.js#L199

The current condition is:
`targetOffset.left + targetOuterWidth + elementOuterWidth > viewport.width`

which I think is not right, because it is adding both the target and the element width. I think the right condition would be:
`targetOffset.left + elementOuterWidth > viewport.width`

With this change, the result is:
![image](https://user-images.githubusercontent.com/9889025/89104618-ea198280-d41a-11ea-9699-f11b37181235.png)

Do you see any issues with doing that change?

**Comment by cagataycivici** [comment]
I've ported the algorithm we use in PrimeNG which is more mature and proven to be more precise.
