### ISSUE TITLE
Calendar: Shortcuts/Quick date pick

### ISSUE THREAD

**Issue by AfzalSabbir** [primefaces/primevue#4180]
### Describe the feature you would like to see added

A feature that'll help us to select date from shortcut as shown in the image:

![image](https://github.com/primefaces/primevue/assets/98600409/2b78d4c1-8354-4874-827a-33fa93d0a8d0)

### Is your feature request related to a problem?

I need to select some date frequently of past or future. It takes a lot of clicks to select them, it would be a great help if the feature is there.

### Describe the solution you'd like

There can be an area (left/right of the calendar) where the the list can be shown like the image:

![image](https://github.com/primefaces/primevue/assets/98600409/2b78d4c1-8354-4874-827a-33fa93d0a8d0)

### Describe alternatives you have considered

Alternatively I can use: [ElementPlus](https://element-plus.org/en-US/component/date-picker.html#enter-date) but I want to stick with PrimeVue.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
