### ISSUE TITLE
SSR enabled shows FOUC(Flash of unstyled content) issue

### ISSUE THREAD

**Issue by shidcordero** [primefaces/primevue#4184]
### Describe the bug

Same issue to this ticket https://github.com/primefaces/primevue/issues/3070

### Reproducer

https://codesandbox.io/p/github/odranoelBR/primevue-quickstart-nuxt3/csb-sp3gvk/nuxt-3-primevue?file=/app.vue:1,1&selection=[{%22endColumn%22:30,%22endLineNumber%22:9,%22startColumn%22:30,%22startLineNumber%22:9}]

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/3070
