### ISSUE TITLE
Expect the component library documentation to be in Chinese

### ISSUE THREAD

**Issue by dong-lufei** [primefaces/primevue#4185]
### Describe the feature you would like to see added

Expect the component library documentation to be in Chinese

There are a lot of Chinese programmers

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
