### ISSUE TITLE
Accordion: Animate list of AccordionTabs

### ISSUE THREAD

**Issue by da5idb** [primefaces/primevue#4193]
### Describe the feature you would like to see added

I would like there to be animations on the AccordionTabs when the list of tabs changes:
- Order of the tabs change
- Adding an AccordionTab
- Deleting an AccordionTab

The functionality should probably use TransitionGroup 

### Is your feature request related to a problem?

Due to the way Accordion works we cannot use TransitionGroup on the AccordionTab items to animate the position changes (and also adding and removing an AccordionTab) 
That makes it confusing for the user if the order of the AccordionTabs changes due to an update on the items - eg sorted by name or similar.

### Describe the solution you'd like

Add a default TransitionGroup to the Accordion 

### Describe alternatives you have considered

Use a different approach that works best with existing PrimeVue animations

### Additional context

I think this should be an obvious one since we already have animations on the AccordionTab - just not for this useCase.
Looking forward to the discussion.

**Comment by da5idb** [comment]
How it is right now:

https://github.com/primefaces/primevue/assets/80884454/ec473298-6f16-4971-abc3-46b2b212959c


How I would like it to be:

https://github.com/primefaces/primevue/assets/80884454/acc9fb60-7a0c-47e9-8c64-3c02eb280330

**Comment by da5idb** [comment]
Sorry totally forgot about this one... in the end we implemented our own version of the accordion 😄

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
