### ISSUE TITLE
Component Name: TreeTable

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4194]
### Describe the feature you would like to see added

Add context menu support like in DataTable, i.e. add ability to get node on which context menu was called.

### Is your feature request related to a problem?

Now we need explicitly select item and then click right mouse button to call context menu for a node, but it can be not obvious in some cases, and user can think he called context menu for node by just right-click it

### Describe the solution you'd like

Add an event 'node-contextmenu' (or something like this), and pass node to it

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
