### ISSUE TITLE
DataTable: Custom icon not triggering sort

### ISSUE THREAD

**Issue by gustavobmichel** [primefaces/primevue#4197]
### Describe the bug

When using a custom icon and clicking on it, sorting is not triggered. If we use the primeicon, the sorting is performed as expected. Sorting is still working if you click in any other part of the `th`.

This was previously working on PrimveVue version `3.29.x`.

### Reproducer

https://stackblitz.com/edit/tidtbp?file=index.html,src%2FApp.vue

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Click on the custom icon for sorting

### Expected behavior

Table should be sorted.

**Comment by tugcekucukoglu** [comment]
It was fixed with 3.32.0. Please try to use the latest version.

Thanks,
