### ISSUE TITLE
Component Name: Menubar

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4198]
### Describe the bug

Menubar's menu do not close on click outside

### Reproducer

https://codesandbox.io/s/hy2lnn

### PrimeVue version

3.30.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Expected behavior

Close menubar's menu on click outside

**Comment by tugcekucukoglu** [comment]
Could you check that with the latest version? If the problem still persists, please create a new issue.
