### ISSUE TITLE
Dropdown: clearicon slot prop `onClick` has invalid type

### ISSUE THREAD

**Issue by bgoscinski** [primefaces/primevue#4216]
### Describe the bug

I'm trying to use `clearicon` slot to define my own icon for clear action. I need to forward clicks by using `onClick` slot prop but I get TS error as shown below

<img width="530" alt="image" src="https://github.com/primefaces/primevue/assets/5730169/855c5371-1fbf-4df6-9326-26bb7479d900">

### Reproducer

n/a

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Fixed for the next version.

Thanks for your report!
