### ISSUE TITLE
DataTable: paginator doesn't work when rowGroup mode is enabled

### ISSUE THREAD

**Issue by aka-jun** [primefaces/primevue#4218]
### Describe the bug

Trying to load large datasets with rowGroup mode (https://primevue.org/datatable/#rowgroup_subheader)
but if add paginator or virtualScrollerOption to the datatable, it will break table

A similar issue is also open with virtual scrolling.
A similar issue link : https://github.com/primefaces/primevue/issues/4109
( https://stackblitz.com/edit/43cdnh?file=src%2Fservice%2FCustomerService.js,src%2FApp.vue )

Could you guys check this one? 
Thank you in Advance!

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-paginator-vplfv4?file=%2Fvite.config.js%3A1%2C1

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. go to next page

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
