### ISSUE TITLE
Password: add "@change" event

### ISSUE THREAD

**Issue by darkvertex** [primefaces/primevue#4219]
### Describe the bug

The `<Password>` component does not react to `@change` events.

(#2610 hints that apparently it once used to.)

### Reproducer

https://codesandbox.io/s/muddy-frost-9rjfdy?file=/src/App.vue

### PrimeVue version

3.31.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

See my Stackblitz link for an example.

Basically, "@change" events do nothing on a `<Password>` component tag.

(Looks like a potential regression given that #2610 claims it was fixed in Primevue 2.x)

### Expected behavior

I expect the event to trigger when clicking away or when pressing enter inside the <input> element.

**Comment by AfzalSabbir** [comment]
@darkvertex no you can't use `@change`. You know what, I think youc can use one of
- `@input`
- `@focus`
- `@blur`
- `@keyup`

Specifically you can use `@blur`

**Comment by tugcekucukoglu** [comment]
#2610 is about lack of input emit. But in Vue 3 there is @update:modelValue can be used for two data binding. For more information: https://vuejs.org/guide/components/v-model.html#component-v-model

In any way, I will also add change emit.
