### ISSUE TITLE
SplitButton: Add loading icon

### ISSUE THREAD

**Issue by DanielMcAssey** [primefaces/primevue#4221]
### Describe the feature you would like to see added

Loading icon is missing from SplitButton

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add the same loading icon from the Button component

### Describe alternatives you have considered

Potentially using the Icon slot

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
