### ISSUE TITLE
Add `transition` option to Pass Through(PT) of components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#4231]
Users can control all options of Vue transition component;
https://vuejs.org/guide/built-ins/transition.html#transition

```
const pt = {
     panel: {
        transition: {
           onEnter(el, done) {
              ....
           },
           enterToClass: 'MyEnterClass',
           ...
        }
     }
}
```

Affected components:
- [x] Accordion
- [x] AutoComplete
- [x] Calendar
- [x] CascadeSelect
- [x] ColorPicker
- [x] ConfirmPopup
- [x] ContextMenu
- [x] DataTable
- [x] Dialog
- [x] Dropdown
- [x] Fieldset
- [x] Galleria
- [x] Image
- [x] Menu
- [x] Message
- [x] MultiSelect
- [x] OrderList
- [x] OverlayPanel
- [x] Panel
- [x] PanelMenu
- [x] Password
- [x] PickList
- [x] ScrollTop
- [x] Sidebar
- [x] TieredMenu
- [x] Toast
- [x] TreeSelect

**Comment by rbcunhadesign** [comment]
Google search lead me here. Thanks for this!
