### ISSUE TITLE
SplitButton: Large Split Button missing arow

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#4233]
### Describe the bug

![image](https://github.com/primefaces/primevue/assets/57847174/21cb5079-d885-4693-a561-a602c11c0b1e)

### Reproducer

https://stackblitz.com/edit/ncdhph?file=src%2FApp.vue

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
It was fixed with version 3.32.0.

Thanks for your report!
