### ISSUE TITLE
SpeedDial: tooltip not working on speed dial

### ISSUE THREAD

**Issue by gabstafari** [primefaces/primevue#4238]
### Describe the bug

When trying to add a tooltip to a speed dial item, it does not seem to work. 

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-kx829k

### PrimeVue version

3.30.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by Lyokolux** [comment]
The examples of the documentation does not work (anymore?) https://primevue.org/speeddial/#tooltip
