### ISSUE TITLE
Add `Content Security Policy (CSP)` config

### ISSUE THREAD

**Issue by ydcjeff** [primefaces/primevue#4241]
### Describe the feature you would like to see added

Currently, PrimeVue creates many style elements and directly append into head tag. While we deploy the app with strict CSP headers, many CSP style errors occur saying failed to inject inline styles.

Thus, to support CSP config, I think we could add a CSP config when creating PrimeVue vue plugin.

```js
app.use(PrimeVue, { csp: /* ... */ });
```

### Is your feature request related to a problem?

Currently, our client apps are deployed with strict CSP report only headers. Although the app works, there are multiple errors in the console and multiple false positive CSP style errors are reported.

### Describe the solution you'd like

Provide a CSP config when creating PrimeVue vue plugin, and use the provided CSP values when creating inlin style elements.

```js
app.use(PrimeVue, { csp: /* ... */ });
```

### Describe alternatives you have considered

- Use `'unsafe-inline'`, but unfortunately we can't do for our case.
- Write a Vite plugin that injects `setAttribute('nonce', ...)` code (we workaround with this for now, however could break between each version).

**Comment by mertsincan** [comment]
Thanks a lot for the report! On 3.32.0, please try;
```
app.use(PrimeVue, {
    csp: {
        nonce: '...'
    }
});
```

**Comment by ydcjeff** [comment]
Thank you for implementing quickly.

**Comment by ElteHupkes** [comment]
@ydcjeff This may not be the place, but is there any indication, here or in some other docs, on how to actually securely use such a nonce value? Unless you're serving the frontend from a backend that randomly rotates the nonce, I fail to understand how a nonce config value is any less unsafe than `unsafe-inline`.

**Comment by lognaturel** [comment]
Good question, @ElteHupkes, I wonder as well. `app.use` is only run once per plugin initialization, right? So there's nothing a backend can do to make this actually provide security as far as I can tell. A nonce is supposed to be used exactly once in the context of a single HTTP request.

**Comment by ElteHupkes** [comment]
@lognaturel I suppose that if you had a non-static backend, you could serve a random nonce with the HTML page that initializes PrimeVue, both in the header and the source code. I'd imagine something like `<script nonce="random-value">window.primeNonce = "random-value";</script>`, before PrimeVue is loaded, which you can then use within `app.use()`. That would provide some measure of security, but it's easy to get wrong and (most importantly) impossible to do if you want to serve your static content, well, statically, from a CDN or something.

**Comment by lognaturel** [comment]
> which you can then use within app.use(). That would provide some measure of security

Yes, you're right that it's not nothing, it's just not new for each HTTP request as intended. I guess each tab would have its own nonce until closed in that case?

**Comment by ElteHupkes** [comment]
@lognaturel Yes. That would still be effective against XSS attacks, an attacker wouldn't know the nonce, after all. I would probably have implemented this, if the app wasn't served from a CDN.

Come to think of it, against untargeted scanning types of attacks, even a fixed nonce could be effective. It'll take like 1% effort to bypass of course 😅.
