### ISSUE TITLE
DataTable: stateStorage Page and Sort does not restore when using Lazy Load

### ISSUE THREAD

**Issue by dassels** [primefaces/primevue#4245]
### Describe the bug

I have a table that uses the `lazy` property. I also want to use stateStorage, and this works for any filters that are applied. However, if sort or paginate is applied, for example I sort DESC and am on page 2, only default sort and first page results are returned.

### Reproducer

https://stackblitz.com/edit/lxpxlz?file=src%2FApp.vue

### PrimeVue version

3.30.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to example stackblitz link
2. Sort a column
3. Refresh page (via icon at top).
4. Results go back to default

5. Go to page 2
6. Refresh page
7. Results go back to default page paginator (still says it is on page 2)

8. Enter a filter search criteria (for example, search "Ivan" in "representative" column
9. Sort and/or go to page 2
10. Refresh page
11. Only filter persists, sort or pages not kept.

### Expected behavior

Any filters, sort order and page number and rows set should be reinstated after reload when `stateStorage` is set

**Comment by tugcekucukoglu** [comment]
The DataTable needs to know which row will be the first, just as it needs to know the number of rows.

https://stackblitz.com/edit/lxpxlz-93qeul?file=src%2FApp.vue%3AL106

**Comment by dassels** [comment]
Ok that makes sense. How about the sort? For example, if I sort first column ASC, then go to page 5, when reloading I get the unsorted values even though I'm on page five. Was expecting to see the sorted values of that page.
