### ISSUE TITLE
InputNumber

### ISSUE THREAD

**Issue by csakis** [primefaces/primevue#4246]
### Describe the bug

The input box does not allow to enter a number starting with a decimal point. The user needs to type a number or the `-` key

### Reproducer

https://stackblitz.com/edit/nmbkfb?file=src%2FApp.vue

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Start typing '.'

### Expected behavior

the input box should let the user enter decimal point

**Comment by tugcekucukoglu** [comment]
It's default behavior. Decimal numbers expect a digit before type '.'

**Comment by Paul-Hebert** [comment]
>It's default behavior. Decimal numbers expect a digit before type '.'

Is there a way to change this default?
