### ISSUE TITLE
InputNumber: tooltip directive not working when set to focus

### ISSUE THREAD

**Issue by JeremieChab** [primefaces/primevue#4254]
### Describe the bug

The InputNumber component is not working properly with the tooltip directive.

When applying a tooltip directive with the focus mode to an existing InputNumber, the tooltip doesn't show on focus of the InputNumber as it should. This is specific to the InputNumber component, as the tooltip directive is working as intended for the InputText component.

You can refer to the stackblitz linked in this bug report to reproduce the issue (https://stackblitz.com/edit/1ft6dj?file=src%2FApp.vue).

### Reproducer

https://stackblitz.com/edit/1ft6dj?file=src%2FApp.vue

### PrimeVue version

3.30.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create an InputNumber component on your application.
2. Add the tooltip directive on your InputNumber with the focus property. For example: `v-tooltip.focus="'focus tooltip'"`.
3. Click inside the InputNumber to focus it.
4. The tooltip doesn't show.

### Expected behavior

The tooltip should show when focusing the InputNumber.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by JeremieChab** [comment]
I'm not sure why this was categorized as an enhancement and then closed, it clearly is a defect/bug.

Please refer to the stackblitz (https://stackblitz.com/edit/1ft6dj?file=src%2FApp.vue), the tooltip directive is not fully working on a InputNumber component.
