### ISSUE TITLE
Dropdown: Icon classes not being correctly exposed

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#4264]
### Describe the bug

When using custom slots for customizing icons the classes are not properly exposed.

In `dropdownicon` slot everything is working perfectly fine, but in the rest of the slots the classes are not applying.

For reproduction go to the reproducer, look for example at the content of the replaced filter icon - it does not have any class, but when you comment it the default element has the `p-dropdown-filter-icon`

The same happens for the clear icon and probably for loadnig icon.
As for the filter is does not make much difference, that for the clear icon it completely broke the styling as icon is now not positioned correctly.

A bit connected to the #4263

### Reproducer

https://codesandbox.io/p/sandbox/compassionate-snow-z7dzxs

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
It seems fixed with #4263. I have tested with this repo: https://github.com/primefaces/primevue-examples/tree/main/vite-quickstart

If the problem still persists, please create a new issue. Closing for now.

**Comment by Magiczne** [comment]
Works indeed. Thanks.
