### ISSUE TITLE
Textarea autoResize with max-height doesn't show scrollbar

### ISSUE THREAD

**Issue by SimonFard** [primefaces/primevue#4269]
### Describe the bug

When setting a max-height to a textarea with autoResize set to true the scrollbar doesn't appear when reaching the max-height.

### Reproducer

https://codesandbox.io/p/sandbox/agitated-fire-kznqzc?file=%2Fsrc%2FApp.vue%3A1%2C1

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Add newlines to textarea until max-height is reached

### Expected behavior

There should be a scrollbar that appears. 

In the resize method on the textarea component the parseFloat(this.$el.style.height) returns NaN because of 'calc()' which makes it so the overflow cant be set to scroll.

**Comment by bahadirsofuoglu** [comment]
Hİ, I think the component behaves as expected. However, if you want to use it this way, you can override the 'overflow:hidden' by giving a class to the Textarea component. Below, I'm sharing an example

https://codesandbox.io/p/sandbox/magical-dan-4fgxmc?file=%2Fsrc%2FApp.vue%3A10%2C13
