### ISSUE TITLE
Component Name: DragDropList

### ISSUE THREAD

**Issue by matthew-dean** [primefaces/primevue#4275]
### Describe the feature you would like to see added

I'd love to see some kind of draggable list component, with slotted props for specifying which element is draggable. Right now there's the [OrderList](https://primevue.org/orderlist/), but this seems pretty 2000s-era design, and I think most designers now would reach for something draggable (with mouse or finger) to implement the same requirement.

### Is your feature request related to a problem?

OrderList isn't draggable.

### Describe the solution you'd like

Allow draggable items, with things like ghosting or outline drag.

### Describe alternatives you have considered

There are certainly draggable list / drag/drop components out there, like [vue-easy-dnd](https://github.com/rlemaigre/Easy-DnD). But it would be nice for one that has the same design sensibility / integration with PrimeVue.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/1861
