### ISSUE TITLE
usePassThrough: Components with function as their value doesn't seem to work properly

### ISSUE THREAD

**Issue by firlottea** [primefaces/primevue#4278]
### Describe the bug

```
const CustomTailwindTheme = usePassThrough(
  Tailwind,
  {
    datatable: {
      column: {
        //  Attempt 1:
        // headercell: ({ context, props }) => ({
        //   class: ['!px-4 !pt-2 !pb-0 bg-pink-500'],
        // }),
        //  Attempt 2:
        // headercell: ({ context, props }) => ({
        //   class: '!px-4 !pt-2 !pb-0 bg-pink-500',
        // }),
        //  Attempt 3:
        // headercell: {
        //   class: ['!px-4 !pt-2 !pb-0 bg-pink-500'],
        // },
        //  Attempt 4:
        headercell: {
          class: '!px-4 !pt-2 !pb-0 bg-pink-500',
        },
        columnfilter: {
          class: ['!pb-2 bg-pink-500'],
        },
      },
    },
    paginator: {
      rowperpagedropdown: {
        root: {
          class: ['md:!w-24'],
        },
      },
    },
  },
  { merge: true, useMergeProps: true }
);
```

When trying to have global PassThrough on component which have a function as their value  
EX : 
```
headercell: function headercell(_ref162) {
```

Seems like there is no way to merge the Global classes and the ones provided by the Tailwind PassThrough class.

Attempt 1 : 
The class property is empty

Attempt 2 : 
The class property is empty

Attempt 3 : 
The class property is overwritten by the pt2 value

Attempt 4 : 
The class property is overwritten by the pt2 value

I tried with useMergeProps at true and false.

### Reproducer

https://stackblitz.com/edit/t2cmve?file=src%2Fmain.js

### PrimeVue version

3.32

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Firefox Developper Edition

### Steps to reproduce the behavior

1. Open the provided Stackblitz link
2. Inspect the class property of the "headercell" <th> 
3. Comment or uncomment each headercell attempt in the main.js file 
4. Inspect the class property of the "headercell" <th> 

### Expected behavior

Classes from usePassThrough should be merged and not overwritten. Also the syntaxed shown in the panel.header section here 
https://primevue.org/tailwind/#customization
doesn't seem like it's working for this Component. (Haven't tried many other components)

**Comment by mertsincan** [comment]
Thanks a lot for the report! Fixed in https://github.com/primefaces/primevue/issues/4289
You can use all of the examples you commented on above.
