### ISSUE TITLE
SelectButton: passthrough option

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4286]
### Describe the feature you would like to see added

I want to add tooltips to the buttons.
Since each button has it's own tooltip, I have the tooltip within the options.
eg.
![image](https://github.com/primefaces/primevue/assets/8471027/57218036-c88c-409c-80ee-6d251d594fc6)

I want to use passthrough to add those tooltips to the buttons.
But currently the passthrough context only contains the buttons active and disabled state.
I need access to the buttons option data from the passthrough context.

This would also allow a lot more custom configuration depending on each button's state.

### Describe the solution you'd like

add the blue line of code to Selectbutton.vue
![image](https://github.com/primefaces/primevue/assets/8471027/25a3f064-ad7f-4481-804c-d2e8b60da1df)

**Comment by Feher-Zsofia** [comment]
The Tooltip directive can't set the tooltip of each of the buttons, it only works within the template part (where the `item` is accessible). Is this the intended solution for this problem?
