### ISSUE TITLE
Sidebar: using unstyled mode and Tailwind theme, the :modal="false" doesn't work. Can't disable the modal layer.

### ISSUE THREAD

**Issue by daniel-cintra** [primefaces/primevue#4288]
### Describe the bug

In a clean install of PrimeVue, using unstyled mode with the Tailwind theme, for the Sidebar component, the :modal="false" is ignored. It behaves like the prop is always :modal="true".

### Reproducer

-

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

In a clean PrimeVue install (with Tailwind):

```vue
<template>
  <div class="card flex justify-content-center">
    <Sidebar v-model:visible="visible" :modal="false">
      <h2>Sidebar</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat.
      </p>
    </Sidebar>
    <Button label="Sidebar Toggle" @click="visible = true" />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import Sidebar from 'primevue/sidebar'
import Button from 'primevue/button'

const visible = ref(false)
</script>
```

**Comment by daniel-cintra** [comment]
The 3.32.1 update, fixed the modal/backdrop opacity (now it's visually removed as expected). But the content area outside the Sidebar using prop :modal="false" isn't accessible (in unstyled mode with Tailwind theme) as the mask (that remains and is invisible), blocks all the page content. 

Disabling unstyled mode, and using `primevue/resources/themes/lara-light-indigo/theme.css` everything works as expected (content outside Sidebar is accessible using prop :modal="false").

**Comment by AcidRaZor** [comment]
@atakantepe This appears to be still an issue, some guidance required
