### ISSUE TITLE
DataTable: Clear ColumnFilter button destroys filter instead of resetting it when filters are initialized in onMounted

### ISSUE THREAD

**Issue by patrickschroeter** [primefaces/primevue#4291]
### Describe the bug

When using the DataTable with ColumFilter in 'menu' mode - the 'Clear' button does not work correctly when the initial filters are defined in the `onMounted` lifecycle hook and not directly in the setup method.

Screenshot 1 shows initial state and expected state after clear button is pressed.
Screenshot 2 shows actual state after clear.
![Screenshot 2023-08-18 at 09 52 35](https://github.com/primefaces/primevue/assets/14996876/379c0d86-09e3-4c5a-b26d-4ea0c53ff771)
![Screenshot 2023-08-18 at 09 52 42](https://github.com/primefaces/primevue/assets/14996876/aa0dffc0-2532-4e66-a2a6-9881fa60a9e1)

Edit: it is possible to work around that issue by moving the initialization in the `onBeforeMount` (it that's possible)

### Reproducer

https://stackblitz.com/edit/jqghbq?file=src%2FApp.vue

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the filter and click the 'Clear' button
2. Open the filter again and the `operator` dropdown is missing and `matchMode` is empty

### Expected behavior

When clearing the filter i expect to recreate the initial state with the `operator` dropdown still visible and selected default `matchMode`

**Comment by tugcekucukoglu** [comment]
There is no need to specifically call `initFilters` on `onBeforeMount`. Calling it on setup is enough for the menu filtering. This is being closed because it is a demo problem.
