### ISSUE TITLE
Slot prop missing for virtualscroller in DataTable

### ISSUE THREAD

**Issue by Acetyld** [primefaces/primevue#4293]
### Describe the bug

Hi!
We are actively using primevue blocks pro and running into a problem.

Right now we manage to get a infinite loading working, problem is that when we load to much records, the page freezes. So we wanted to use the included virtual scroller from datatable, problem is the virtual scroll component (the detect component) [https://vue3-infinite-loading.netlify.app/](https://vue3-infinite-loading.netlify.app/) needs to be at the bottom of the scrollable content, and we cant manage to do this without creating a fork/pull adding the slot and rebuilding the library our self. Is there any way you guys can add a slot for this?

### Reproducer

https://primevue.org/virtualscroller/#api.virtualscroller.slots

### PrimeVue version

3.30.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
