### ISSUE TITLE
Galleria Docs (Controlled): Incorrect activeIndex calculation

### ISSUE THREAD

**Issue by shmatul** [primefaces/primevue#4294]
### Describe the bug

The prev() function that has been shown consistently returns the same index from the images array. 
Instead, it should function by reducing the value of the currentIndex, not the images.length.

Currently:
`const prev = () => {
    activeIndex.value = activeIndex.value === 0 ? 0 : images.value.length - 1;
};`

### Reproducer

https://primevue.org/galleria/#controlled

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

*

### Steps to reproduce the behavior

1. Go to the Galleria Controlled Example
2. Click on the previous button (minus)

### Expected behavior

`const prev = () => {
    activeIndex.value = activeIndex.value === 0 ? images.value.length - 1 : activeIndex.value - 1;
};`

**Comment by tugcekucukoglu** [comment]
It was fixed.

Thanks for your contribution.
