### ISSUE TITLE
Dialog: Draggable Fails

### ISSUE THREAD

**Issue by caputech** [primefaces/primevue#4298]
### Describe the bug

Dialog Component: Draggable prop no longer works.  Dialogs cannot be dragged since 3.30.0.  The docs illustrate the behavior now.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-s7vhyc

### PrimeVue version

3032.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Attempt to drag a Dialog.  Even explicitly setting draggable to true does not correct.

### Expected behavior

Expect Dialog to be draggable when set or by default.  The docs now also illustrate this behavior in 3.32.1.

**Comment by reksc** [comment]
In my case after I upgrade from primevue@3.16.2 to the latest 3.32.1 drag and drop of dialogs is broken with an error message of "getComputedStyle is not a function".

**Comment by reksc** [comment]
In my case in **3.32.0 drag and drop works well**, the breaking change is introduced in the latest 3.32.1.

`Uncaught TypeError: getComputedStyle is not a function at HTMLDocument.documentDragListener (dialog.esm.js:436:34)`

**Comment by melloware** [comment]
Introduced by: https://github.com/primefaces/primevue/pull/4252

**Comment by Dmytro-Lukashenko** [comment]
Hi guys! I've fixed this bug. It was the incorrect naming of the variable. I've changed getComputedStyle to containerComputedStyle. @melloware could you please check it?

**Comment by caputech** [comment]
This is not really the issue I was reporting.  Draggable is failing if their is a Tab View in the Dialog.  It seems to have started in 3.30.0.  A reproducer is here.  https://stackblitz.com/edit/o7cqoc-gmw8jq?file=package.json
