### ISSUE TITLE
DataTable: PT Options missing for Expansion Row Cell

### ISSUE THREAD

**Issue by kaipaysen** [primefaces/primevue#4306]
### Describe the bug

The `td` Element surrounding the expansion template is not accessible with the PassThrough API. 
I guess that is related to 
https://github.com/primefaces/primevue/blob/master/components/lib/datatable/TableBody.vue#L94-L96.

### Reproducer

[StackBlitz](https://stackblitz.com/edit/angular-qvm9mg-vvikje?file=src%2FApp.vue)

### PrimeVue version

3.32.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open [StackBlitz](https://stackblitz.com/edit/angular-qvm9mg-vvikje?file=src%2FApp.vue) and expand one of the rows in the table. 

### Expected behavior

I'd expect a red bottom border for the expanded row.

**Comment by tugcekucukoglu** [comment]
There is a misunderstanding here. `td` already has a pt. But expansion is a slot and it totally depends on how the user will use it. We can only export data and index. It may not be right for us to intervene from the outside, because we may not be able to guess correctly how the user plans templating.

**Comment by kaipaysen** [comment]
@tugcekucukoglu please have a look at the following screenshots

1. the td in the expansion row has no pc-section attribute.
![image](https://github.com/primefaces/primevue/assets/8957069/9be4ccc2-75a7-4557-b27d-96a2b774f985)

2. compared to the td in body row which has a pc-section attribute.
![image](https://github.com/primefaces/primevue/assets/8957069/467b85cb-8132-49b0-9a0f-054492d12ed4)

I'd like to work on the DOM Element td outside of the slot.

**Comment by kaipaysen** [comment]
> Is there any reproducer link for the issue?

No. I just the example you mentioned from then website to create the screenshots. 
If you expand the first row a second `tr` will be visible which holds the "tobe-pted" `td`.
