### ISSUE TITLE
Column: `colspan` only applied to `thead>tr>td` but should be applied to `tbody>tr>td`

### ISSUE THREAD

**Issue by horlarme** [primefaces/primevue#4307]
### Describe the bug

When adding the `colspan` prop to the `Column` component, the attribute `colspan` is supposed to be applied to both the `thead>tr>td` and `tbody>tr>td` but it was only applied to the header (`thead>tr>td`).

### Reproducer

https://codesandbox.io/s/cold-wood-ghjqyl

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Goto https://codesandbox.io/s/cold-wood-ghjqyl
2. From the table displayed on the page, you'll see that the "Full Name" header is spanning to 2 columns as coded but the body isn't.

### Expected behavior

Both the header and the body should share the same value for `colspan`.

**Comment by tugcekucukoglu** [comment]
`colspan` determines how many columns a cell overlaps, not the size of those columns. To specify the size of a cell, it is necessary to use width.

https://stackblitz.com/edit/web-platform-p3juch?file=index.html

**Comment by horlarme** [comment]
@tugcekucukoglu The stack blitz link provided contains HTML code without the usage of the `DataTable` component. 

Your comment seems to assume I don't know how to use the `colspan` on HTML which as mentioned, I do know how to but when using `DataTable` component, I cannot replicate what you showed in your code.

**Comment by tugcekucukoglu** [comment]
My point is how colspan will behave for html table element and DataTable will behave the same. That's why I sent a demo showing the default table behavior of html.

**Comment by horlarme** [comment]
Thanks but that's not how DataTable behaves. 

PS: I asked on the `primevue` server on Discord about this and I was asked to create an issue.

**Comment by horlarme** [comment]
@tugcekucukoglu How are you doing? I still await a suggestion on proceeding with this issue you closed.  

Thank you.
