### ISSUE TITLE
Button: Failed to resolve component: Badge

### ISSUE THREAD

**Issue by selcukkutuk** [primefaces/primevue#4308]
### Describe the bug

I get the following warning when using with CDN.
"[Vue warn]: Failed to resolve component: Badge"

This warning is also present in the cdn sample prepared by Mrs. @tugcekucukoglu and which can be accessed via the link below.
@tugcekucukoglu example link: https://stackblitz.com/edit/web-platform-dwzmk2

The problem is with the badge component in the button component. In order to eliminate the problem, I registered the Badge component with the name used in the button component globally in the components section. However, there was no solution.

    components: {
        .........
        "Badge": primevue.badge,
        .........
    },

Also, this problem will occur in all nested components during use with CDN. In this example Button > Badge

### Reproducer

https://stackblitz.com/edit/web-platform-dwzmk2?file=index.html

### PrimeVue version

3.32.1

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1-) Open this example: https://stackblitz.com/edit/web-platform-dwzmk2
2-) Check the Browser/Platform console.

### Expected behavior

The ability to use the relevant components without any warning or error.

**Comment by tugcekucukoglu** [comment]
Could you check the same link again? I guess Stackblitz couldn't save the file. Also need to add this line.

`<script src="https://unpkg.com/primevue/button/button.min.js"></script>`
