### ISSUE TITLE
ConfirmPopup: Alignment fails when the target is a template ref 

### ISSUE THREAD

**Issue by danielshawellis** [primefaces/primevue#4311]
### Describe the bug

Per the documentation [here](https://primevue.org/confirmpopup/#api.options.ConfirmationOptions.target), the confirm popup should align with the target that's passed to `confirm.require({ target: HTMLElement })`. The target should be of type HTMLElement.

Alignment works correctly when the target comes from a click event (i.e. event.currentTarget as demonstrated [here](https://primevue.org/confirmpopup/#basic)). However, alignment fails when the target is set using [a Vue template ref](https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs). In that case, the popup appears in the top left corner of the page.

### Reproducer

https://codesandbox.io/p/sandbox/nervous-greider-frhh29?welcome=true

### PrimeVue version

3..32.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the sandbox: https://codesandbox.io/p/sandbox/nervous-greider-frhh29?welcome=true
2. Observe the alignment of the confirm popup

### Expected behavior

The confirm popup should align with the HTML Element provided by the Vue template ref to [the target ConfirmationOption](https://primevue.org/confirmpopup/#api.options.ConfirmationOptions.target) when `confirm.require({ target: HTMLElement })` is called.

**Comment by tugcekucukoglu** [comment]
Could you check that with the latest version? If the problem still persists, please create a new issue.

**Comment by dsldiesel** [comment]
Still happens in latest version. Please fix.

**Comment by RonnieSan** [comment]
I noticed this happens (popup is aligned to top-left) if I have a method that makes an async call before the confirm.require call on a click.

**Comment by skyne98** [comment]
Still happening!

**Comment by SalvatoreCapano** [comment]
still happening if the confirm.require call is in an async "then"callback
