### ISSUE TITLE
DataTable Column: Resizable on individual column does not work

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#4313]
### Describe the bug

By setting:

`:resizableColumns="true"`

on the datatable and

`:resizable="false"`

on an individual column

Makes the columns resizable (which is fine), but, even the column where `:resizable="false"` (which is wrong)

### Reproducer

https://codesandbox.io/p/sandbox/angry-hooks-fc326w?file=/src/App.vue:1,1

### PrimeVue version

3.32.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Column component does not `resizable` property. You can find more information in the documentation

**Comment by 1Map** [comment]
Ok, thanks.  So how can I disable the resizing of an individual column (In other words, have a fixed size column)?

The documentation is a bit confusing.

<img width="1262" alt="image" src="https://github.com/primefaces/primevue/assets/1152458/c389958b-7ad5-4584-894e-56e9f994f2c3">

**Comment by tugcekucukoglu** [comment]
As the description says these are pt options of the Column.

Columns props: https://primevue.org/datatable/#api.column.props
