### ISSUE TITLE
Datatable Columns: Reordable Columns does not work together with Column Body Template

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#4315]
### Describe the bug

When reorderableColumns is set to true on a DataTable with Template Columns, then when you drag (reorder) your columns, columns gets messed up.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-6snhr3

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Look at the CodeSanbox example and start dragging columns 2, 3, 4, etc.  Keep reordering columns.  Everytime a column gets re-ordered, it mess up the rest of the column orders.

**Comment by 1Map** [comment]
Bump, noone had to time to look at this yet - posted it 3 weeks ago

**Comment by 1Map** [comment]
Unfortunately it still does not work.  What happens if you add columns not bounded to a field.  For example.  Add the following 2 columns in the beginning of your datatable as a test and, for example, drag the Name column.  You will see it still gets messed up:

Apart from the 2 columns below, also make sure to add the following to your datatable:

`v-model:selection="selectedRecords"`

```
            <Column
                frozen
                selectionMode="multiple"
                headerStyle="width: 2rem"
                :sortable="false"
                :reorderableColumn="false"
            ></Column>
            <Column
                frozen
                header="Actions"
                headerStyle="width: 7rem; text-align: center;"
                :sortable="false"
                :reorderableColumn="false"
            >
                <template #body="slotProps">
                    <Button icon="far fa-edit" text rounded severity="success" @click="">Edit</Button>
                </template>
            </Column>

```

**Comment by eness** [comment]
defining `columnKey="randomstr"` for each column solved the issue for me.

![image](https://github.com/primefaces/primevue/assets/2032225/f5fa0088-a59b-46ae-98f9-a1aea163453f)
