### ISSUE TITLE
DataTable: Current row editing gets lost when filtering is enabled

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#4319]
### Describe the bug

Hello,
I'm trying to use row editing + filtering features of the DataTable component and stumbled upon this error:
When you initialize editing for a specific row and start to edit a column field, if you want to start editing a another row (clicking the edit button), the current edited field is resetted.

### Reproducer

https://codesandbox.io/p/sandbox/kind-cookies-s9mzzk?file=/src/App.vue:34,5-35,35

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on the edit button for the first row
2. Start modifying the name field. (Do not end editing by clicking on save)
3. Click on the edit button of the second row
4. Notice the name of the first row has been reset

If the filtering feature is removed from the DataTable (comment lines v-model:filters... and :globalFilterFields...), the error doesn't occur.
This is because the internal data field d_editingMeta of the component is being reset when filtering is applied, and filtering is applied after....focus change ? I don't know :)

### Expected behavior

Behaviour should be consistent regardless of the filtering feature being enabled or not.

**Comment by NikoGJ** [comment]
Not reproducible in v3.32.2
Closing issue

**Comment by NxMgh** [comment]
+1
