### ISSUE TITLE
InputNumber with decimals should support entering comma/decimal point

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#432]
![image](https://user-images.githubusercontent.com/8471027/89665647-4415be80-d8d9-11ea-8f8d-8e1ce1abae8f.png)
Currently the input of 12,34 into an InputNumber is quite unintuitive.
If you enter 12, you have to press right arrow to enter the decimal numbers.

It would be nice if you could put the cursor behind the comma by entering the comma. 
So that you can actually type 12 comma 34.

**Comment by cagataycivici** [comment]
@mertsincan Please port our latest inputnumber enhancements from PrimeReact to PrimeVue to resolve cases like these.
