### ISSUE TITLE
DataTable: Column editor constantly lose focus when row edit and filtering are enabled

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#4321]
### Describe the bug

Another one,

Focus gets stuck on the edit button when multiple rows are being edited.

### Reproducer

https://codesandbox.io/p/sandbox/kind-cookies-s9mzzk?file=/src/App.vue:34,5-35,35

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on the edit button of row 1
2. Click on the edit button of row 2
3. Start trying to change the name column of either row 1 or row 2
4. Notice the focus of the InputText gets lost and focus is placed on the "check" button of row edition.

If the filtering feature is removed from the DataTable (comment lines v-model:filters... and :globalFilterFields...), the behaviour doesn't occur.

### Expected behavior

Behaviour should be consistent regardless of the filtering feature being enabled or not.

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox example. I have forked and updated the PrimeVue version and then DataTable worked as expected.

If the problem still persists please let us know.
