### ISSUE TITLE
InputText: Placing Icons inside is not supported in unstyled mode with the Tailwind theme.

### ISSUE THREAD

**Issue by svwezel** [primefaces/primevue#4325]
### Describe the bug

Placing Icons inside a InputText is not supported in unstyled mode with the Tailwind theme.
Icons appear above the search field instead of in it.
see: https://primevue.org/inputtext/#icons

I fixed it by doing
```
<span class="relative">
  <span class="absolute inset-y-0 left-0 flex items-center pl-3">
    <i class="pi pi-search" />
  </span>
  <InputText v-model="search" placeholder="search" class="pl-9" />
</span>
```

But maybe this can be included in the component or documentation in some way?

### Reproducer

/

### PrimeVue version

3.32.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
We're planning to add new form components to make styling easy with Tailwind and/or `pt` property. 

Thank you!
