### ISSUE TITLE
Fluent UI v2 Theme

### ISSUE THREAD

**Issue by cricketthomas** [primefaces/primevue#4327]
### Describe the feature you would like to see added

Microsoft updated their fluent UI for windows 11, and it would be nice if the current fluent theme was updates for the new design guidelines. 

https://fluent2.microsoft.design/

some component libraries:
https://github.com/microsoft/fluentui
https://www.fluentui-blazor.net/

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
