### ISSUE TITLE
DataTable: exportCSV file name

### ISSUE THREAD

**Issue by 770shl** [primefaces/primevue#4329]
### Describe the feature you would like to see added

an option to add the file name to the DataTable exportCSV function.

**Comment by NikoGJ** [comment]
Hello,
Such property seems to already exist [doc](http://localhost:3000/datatable/#api.datatable.props.exportFilename)
It is working as intended ?

**Comment by 770shl** [comment]
sorry, i haven't noticed that property.
It works.
thanks
