### ISSUE TITLE
Dialog:  Draggable fails with Tab View Present

### ISSUE THREAD

**Issue by caputech** [primefaces/primevue#4330]
This is not really the issue I was reporting.  Draggable is failing if their is a Tab View in the Dialog.  It seems to have started in 3.30.0.  A reproducer is here.  https://stackblitz.com/edit/o7cqoc-gmw8jq?file=package.json

_Originally posted by @caputech in https://github.com/primefaces/primevue/issues/4298#issuecomment-1692318058_

**Comment by Dmytro-Lukashenko** [comment]
Hi @caputech. You're right, there is really issue with dragging Dialog when TabView is inside it, but not only TabView. I found the same problem with other components. Today I'll investigate the reason for this bug and try to fix it. Happy codding!

**Comment by Dmytro-Lukashenko** [comment]
You can try adding a title to the header and with the title you can drag the dialog only by clicking on the title text or close button.
[Implementation with header title](https://stackblitz.com/edit/3hxjac?file=src%2FApp.vue)
But it doesn't solve the problem. 

I've figured out the reason for the bug. Inside the Dialog component, we have an initDrag method. Inside this method, we have the condition for checking if the element or its parent has `'data-pc-section'` attribute with` "headeraction"` value. If the element meets this condition `initDrag` stops working and Dialog doesn't drag. We can solve this problem by deleting this condition from the `initDrag` method. But it could cause unexpected behavior in the Dialog. 

@bahadirsofuoglu could you please check this solution cause you added this condition in [commit](https://github.com/primefaces/primevue/commit/ac65dd284041bb2b2f607b319f893d9a7e2a52f1). Won't it cause the unexpected behavior of the Dialog component?

I've created a pull request to fix this bug.

**Comment by caputech** [comment]
Thanks.  I did notice that a header could be dragged.  However, we use the header slot instead of the prop.  And using that, it does not allow dragging via the header.

**Comment by bahadirsofuoglu** [comment]
Duplicate #4182
