### ISSUE TITLE
Datatable Export CSV

### ISSUE THREAD

**Issue by lpalacecr** [primefaces/primevue#4331]
### Describe the bug

When export to CSV file the datetime field show as string, and the excel not reconize like date. See the image below:

![imagen](https://github.com/primefaces/primevue/assets/2246195/02fb1b7f-f484-4ff0-9da6-d5011f3fd0d4)

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-sjnl7x?file=/src/App.vue:19,33

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Firefox, chrome, edge, safari, brave

### Steps to reproduce the behavior

1. Press export bottom.
2. Select file name
3. Download

### Expected behavior

See image below:

![imagen](https://github.com/primefaces/primevue/assets/2246195/dd3fac79-1f9e-4b7c-8e27-9e0b95d0ebfc)

**Comment by NikoGJ** [comment]
There is a undocumented property (though it is defined in the Typescript DataTable.t.ds) called "exportFunction" where you could pass a custom function and do the formatting all by yourself. Note that this function would be called for every field.

I don't know if the lack in the documentation is being there on purpose due to an incomplete feature not yet officially released.

**Comment by lpalacecr** [comment]
> There is a undocumented property (though it is defined in the Typescript DataTable.t.ds) called "exportFunction" where you could pass a custom function and do the formatting all by yourself. Note that this function would be called for every field.
> 
> I don't know if the lack in the documentation is being there on purpose due to an incomplete feature not yet officially released.

Thanks for your cooperation, could you give me a example. The documentation of primevue is very ligth and there not enough examples to understand the use of the framework.

**Comment by NikoGJ** [comment]
Could be something like the following:
```
function myExportFunction(data, field) {
    switch (field) {
        case 'myDateField':
            return data[field].toLocaleString('en-us')
        default:
            return String(data[field])
    }
}

<DataTable
    :exportFunction="myExportFunction"
    ...
>
```

**Comment by lpalacecr** [comment]
> Could be something like the following:
> 
> ```
> function myExportFunction(data, field) {
>     switch (field) {
>         case 'myDateField':
>             return data[field].toLocaleString('en-us')
>         default:
>             return String(data[field])
>     }
> }
> 
> <DataTable
>     :exportFunction="myExportFunction"
>     ...
> >
> ```
Thank you very much for your help. Excellent solution. The code that worked for me was like this:

exportDate(data, field) {
	if (data.data && data.data instanceof Date) {
		return this.formatDate(data.data);
	} else return data.data;
},

<DataTable
    :exportFunction="exportDate"
    ...
>
