### ISSUE TITLE
FileUpload : Selected file size is incorrect

### ISSUE THREAD

**Issue by johnfanyong** [primefaces/primevue#4334]
### Describe the bug

The advanced  FileUpload When using the click event to select the file, the size is not correct. But the file size selected with the drag event is correct 。
![bug](https://github.com/primefaces/primevue/assets/9602639/dadf6847-8dd6-43fc-a066-7b2e7fd78bc0)

### Reproducer

https://codesandbox.io/s/twilight-wildflower-r9jjjn

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome  116.0.5845.96

### Steps to reproduce the behavior

1. Click choose button to select a file,the file size is not correct
2. Drag a file to FileUpload,the file size is correct

### Expected behavior

1. Click choose button to select a file,the file size is correct
2. Drag a file to FileUpload,the file size is correct
![bug](https://github.com/primefaces/primevue/assets/9602639/dadf6847-8dd6-43fc-a066-7b2e7fd78bc0)

**Comment by bahadirsofuoglu** [comment]
Hi, I could not replicate this issue when I checked it from the link you shared. Below, I am sharing the scenario I tested.

![Screen Shot 2023-08-29 at 08 08 44](https://github.com/primefaces/primevue/assets/45143524/c19e599a-d5ff-4b86-8ace-186453c43bfc)
