### ISSUE TITLE
Component Name: PickList (Filter props)

### ISSUE THREAD

**Issue by basitiyidir** [primefaces/primevue#4336]
### Describe the feature you would like to see added

I am using PickList, but I couldn't find the filtering feature in the documentation and examples. 

I noticed that this feature is also available in PrimeReact and PrimeFaces. I'm curious if the PrimeVue administrators are considering adding this feature to PrimeVue as well. 

Will this feature be added? When

**Comment by Terrijoo** [comment]
I'm curious about this.
Currently implementing this component and I'm also missing the filter option for the PickList.
Are there any news on when this will be implemented for Vue?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
