### ISSUE TITLE
Documentation for primeflex setup

### ISSUE THREAD

**Issue by gotjoshua** [primefaces/primevue#434]
I just spent a little more time than I would have liked importing primeflex into a gridsome project, so i am writing to ask for an extra line or two of documentation about importing primeflex into vue projects.

In the end it was simple:

**in main.js:**
```js
import 'primeflex/primeflex.css' 
```

so i suggest adding docs to at least two places:  
1. https://primefaces.org/primevue/showcase/#/display  ( [PR here](https://github.com/primefaces/primevue/pull/435) )
2. https://primefaces.org/primevue/showcase/#/setup ( I am happy to add a P here also, but I need to figure out where...)

**Comment by cagataycivici** [comment]
Thanks, I've added a separate doc page for PrimeFlex setup in the primeflex submenu. Hope it is more clear now. Should be up live with 2.0.8 later today.
