### ISSUE TITLE
Dialog with Accordion is not draggable

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#4344]
### Describe the bug

If a dialog has an Accordion component inside, the dialog is no longer draggable.

### Reproducer

https://stackblitz.com/edit/h6r9s9?file=src%2FApp.vue

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Put an Accordion component inside a Dialog.
2. Try to click and hold anywhere in the dialog header to drag the dialog.

### Expected behavior

Dialog is draggable regardless of internal components.

**Comment by bahadirsofuoglu** [comment]
Duplicate #4182
