### ISSUE TITLE
Tree.vue

### ISSUE THREAD

**Issue by docdoogi** [primefaces/primevue#4345]
### Describe the feature you would like to see added

Expand the tree if has something in filter. 

### Is your feature request related to a problem?

User need to Expand tree before to be able to use filter

### Describe the solution you'd like

Added **this.d_expandedKeys[node.key] = true;** to findFilteredNodes in Tree.vue
```
findFilteredNodes(node, paramsWithoutNode) {
    if (node) {
        let matched = false;

        if (node.children) {
            let childNodes = [...node.children];

           // This or something similar that can be enabled with a prop
            this.d_expandedKeys[node.key] = true;

            node.children = [];

            for (let childNode of childNodes) {
                let copyChildNode = { ...childNode };

                if (this.isFilterMatched(copyChildNode, paramsWithoutNode)) {
                    matched = true;
                    node.children.push(copyChildNode);
                }
            }
        }

        if (matched) {
            return true;
        }
    }
},
```

**Comment by AlexyNau** [comment]
Hi, for the record, there's a similar issue posted in May, and still opened : [Tree branches should expand during filtering #3996](https://github.com/primefaces/primevue/issues/3996)

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by paulocosta94** [comment]
This is not working yet?
