### ISSUE TITLE
Paginator: pt `rowPerPageDropdown` not working

### ISSUE THREAD

**Issue by g1eny0ung** [primefaces/primevue#4346]
### Describe the bug

As the title says.

### Reproducer

https://stackblitz.com/edit/p1qrnn?file=src%2FApp.vue

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Hi, I am sharing the correct usage example for rowPerPageDropdown below.

**Comment by g1eny0ung** [comment]
> Hi, I am sharing the correct usage example for rowPerPageDropdown below.
> 
> https://stackblitz.com/edit/p1qrnn-2mcgya?file=src%2FApp.vue

@bahadirsofuoglu 😮 Oh...thanks for the correction! Now I can figure out how to pass it properly.

But there is still a question. Currently, we can not determine if the element behind a `pt` option is a component. The amount of work may seem overwhelming and easy to overlook if explained individually in the documentation. Is it possible here to throw an error when passing the wrong `pt` value?

**Comment by bahadirsofuoglu** [comment]
Hi. While preparing the answer, I thought the same way. In the Pass Through tab of the Paginator documentation, there is an explanation for rowPerPageDropdown that says: 'Used to pass attributes to the Dropdown component.' However, we will definitely consider how we can make it more understandable as a team. Thank you very much for your suggestions.

**Comment by g1eny0ung** [comment]
Understood. Glad to have your help.
