### ISSUE TITLE
PassThrough from parents to child components may not work properly

### ISSUE THREAD

**Issue by g1eny0ung** [primefaces/primevue#4347]
### Describe the bug

Related to: https://github.com/primefaces/primevue/issues/4346.

I didn't look more deeply into the source code for time reasons, but upon initial inspection, I discovered that the `pt` from parents to child components (which means vue components, like dropdowns) may not work.

E.g.:

https://github.com/primefaces/primevue/blob/c57faf3db114934b0776655cdd924ce20c896662/components/lib/paginator/PageLinks.vue#L2

https://github.com/primefaces/primevue/blob/c57faf3db114934b0776655cdd924ce20c896662/components/lib/paginator/RowsPerPageDropdown.vue#L11

### Reproducer

https://stackblitz.com/edit/p1qrnn?file=src%2FApp.vue

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Related https://github.com/primefaces/primevue/issues/4346#issuecomment-1698606516 #4346
