### ISSUE TITLE
Tree.vue

### ISSUE THREAD

**Issue by docdoogi** [primefaces/primevue#4349]
### Describe the bug

I had performance issue on expand all tree (with a very big tree) using 3.32.2 (3s) had to roll back to 3.29.2 (0.7s)

I do the following to expand all the nodes in the tree:
```
expandNode(nodes) {
            for (const node of nodes) {
                this.expandedKeys[node.key] = true;

                if (node.children) {
                    this.expandNode(node.children);
                }
            }
        },
```

Not Working
```
├── @vitejs/plugin-vue@4.3.4
├── axios@1.5.0
├── date-fns@2.30.0
├── primeflex@3.3.1
├── primeicons@6.0.1
├── primevue@3.32.2
├── sass@1.66.1
├── vite@4.4.9
├── vitest@0.30.1
├── vue-i18n@9.2.2
├── vue-router@4.2.4
└── vue@3.3.4
```
Working
```
├── @vitejs/plugin-vue@4.3.4
├── axios@1.5.0
├── date-fns@2.30.0
├── primeflex@3.3.1
├── primeicons@6.0.1
├── primevue@3.29.2
├── sass@1.66.1
├── vite@4.4.9
├── vitest@0.30.1
├── vue-i18n@9.2.2
├── vue-router@4.2.4
└── vue@3.3.4
```

### Reproducer

-

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue Vite

### Steps to reproduce the behavior

Take very big tree. Try to expand all in 3.29.2 or 3.32.2 and speed test.

**Comment by tugcekucukoglu** [comment]
Could you check the latest version? For the earlier version, the community worked on performance issues.

**Comment by docdoogi** [comment]
I tried with version 3.39.0 and still experienced performance issues when expanding my large tree. In version 3.29.2, it took less than 1 second, while in version 3.39.0, it took approximately 6 seconds.
