### ISSUE TITLE
DataTable: Column: Body slot doesn't receive documented 'node' prop

### ISSUE THREAD

**Issue by ansteele** [primefaces/primevue#4355]
### Describe the bug

The docs for [Column slots](https://primevue.org/datatable/#api.column.slots) refer to a 'node' prop containing the 'row node data'. 

This prop doesn't exist, I can't find any reference to it in the [code](https://github.com/primefaces/primevue/blob/76b9190afc024fa662a64096b8585a8b8c2cb4d9/components/lib/datatable/BodyCell.vue#L21). Presumably it is meant to contain the data for this particular row cell.

### Reproducer

none

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
DataTable uses `data` and TreeTable uses `node` options for body templating.

**Comment by ansteele** [comment]
So the docs are incorrect? I don't understand
