### ISSUE TITLE
Error when using the ContextMenu component without vue-router

### ISSUE THREAD

**Issue by atach** [primefaces/primevue#4357]
### Describe the bug

When using the **ContextMenu** component, it constantly throws an error:
```
Failed to resolve component: router-link. 
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
I am using laravel along with InertisJS
Why should I connect a plugin - "vue-router"  if I don't use it in my application?

### Reproducer

https://codesandbox.io/s/crazy-euclid-y343x5

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

JS

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
In the next versions, PrimeVue does not have vue-router support. https://github.com/primefaces/primevue/issues/4351

Closing for now.
