### ISSUE TITLE
DataTable - Lazy mode - Sort by Column

### ISSUE THREAD

**Issue by y-emiage** [primefaces/primevue#436]
Hello,

Thanks for your useful library,

I am using a datatable compoment with lazy loading option. 

But when I click on any column header  to sort, there is no column values order change.

Thanks for help or some advices.

**Comment by cagataycivici** [comment]
Can you provide more information? In lazy mode, table just passes your that has changed, it is your responsibility to implement the logic which is usually doing a remote call with the sort info and get the new data.

**Comment by y-emiage** [comment]
okay, thanks you for your answer.

But where I could found or call the sort methode in datatable ? when I click on column header, I don't catch an event.

**Comment by cagataycivici** [comment]
See the events section please at;

https://primefaces.org/primevue/showcase/#/datatable

There is (sort) event handler which gives you various parameters about the state.

We'll also put up an example with a real backend that does lazy paging, sorting and filtering.
