### ISSUE TITLE
Datatable: pass ColumnGroup to grandchild

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4362]
### Describe the bug

I'm trying to write a wrapper component for the DataTable component.
So the constelletion I have is
`App/MyComponent > MyDataTableWrapper > DataTable`
If I just pass the ColumnGroup to the slot of MyDataTableWrapper, it does not work.
The ColumnGroup is not visible in the header:
![image](https://github.com/primefaces/primevue/assets/8471027/2a4a48a6-515a-43cb-98e7-7a3e27bd996d)

Here's the reason:
DataTable cant find the ColumnGroup, since it is no longer a direct child, but a grandchild of the DataTable.
![image](https://github.com/primefaces/primevue/assets/8471027/b8fd87cf-cda1-433b-b2d7-0d04a4e2e1e7)

### Reproducer

https://stackblitz.com/edit/idru1f?file=src%2FApp.vue

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

see reproducer
ColumnGroup does not work

**Comment by mertsincan** [comment]
Related to https://github.com/primefaces/primevue/issues/4646

Best Regards,
