### ISSUE TITLE
Panel: Adding an option to collapse panels using the header instead of the "+" icon

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#4373]
### Describe the feature you would like to see added

Ideally, I'd like to have a similar user experience for toggleable Panels as there is for Accordions.

Accordions can be collapsed using the full header area being clickable/focusable, but lacks the same customizations (eg. right align icon slots) that what the Panel component provides. Plus, multiple accordions tabs are by design stacked together, whereas panels are positionned freely and independently of each other.

It would be nice to have the option to control the collapsing of panels (either choose the default + icon at the right or choose what's have been implemented for accordion headers, which is the whole header makes the panel collapse/uncollapse)

### Describe alternatives you have considered
Close alternative would be to use the header slot to add the toggle logic in here as well, but require extra code.

**Comment by proalaa** [comment]
+1

**Comment by mahesh-in** [comment]
+1

**Comment by monipatel26** [comment]
+1

**Comment by tugcekucukoglu** [comment]
As you've said there is Accordion component for this purpose. For these improvements, we need more community demand. For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by monipatel26** [comment]
@NikoGJ you can use `$refs` to manipulate the toggle method.

`<template>
  <div class="card">
    <Panel ref="panel" toggleable>
      <template #header>
        <div
          @click="$refs.panel.toggle()"
          class="p-panel-title w-full cursor-pointer"
        >
          Header
        </div>
      </template>
      <p class="m-0">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum.
      </p>
    </Panel>
  </div>
</template>

<script setup></script>`
