### ISSUE TITLE
Autocomplete: icons of p-input-icon-left/right classes are not displayed

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#4374]
### Describe the bug

When using the Autocomplete component inside the span with class p-input-icon-left or p-input-icon-right, the icon is not displayed, the autocomplete component is masking it

```
<span class="p-input-icon-left">
	<i class="pi pi-search" />
	<AutoComplete v-model="value" :suggestions="suggestions" placeholder="Filter" @complete="onComplete" />
</span>
```

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Icons should be visible.

**Comment by tugcekucukoglu** [comment]
InputText supports this functionality but AutoComplete does not. We could do that but it causes too many css style duplications. 

Sample code: https://github.com/primefaces/primevue/blob/master/public/themes/lara-light-blue/theme.css#L1131

In this case, we do not have any plan to implement icon positioning support so closing issue. If you have any further questions you could use Discord and forum support pages.

Thanks for your understanding,
