### ISSUE TITLE
ConfirmDialog: `acceptClass` or `rejectClass` or pt for `acceptButton` or `rejectButton` doesn't work

### ISSUE THREAD

**Issue by larrasu** [primefaces/primevue#4378]
### Describe the bug

I want to hide the `rejectButton` using `rejectClass`:

```js
confirm.require({
    group: 'not_allowed',
    acceptIcon: 'pi pi-check mr-2',
    acceptLabel: 'Ok',
    rejectClass: '!hidden'
})
```

### Reproducer

https://codesandbox.io/p/sandbox/inspiring-chebyshev-82w9t4

### PrimeVue version

^3.32.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Please try to use the latest PrimeVue version.

This example seems to be working: https://stackblitz.com/edit/gui167?file=src%2FApp.vue

If the issue still persists, please let us know.

**Comment by mertsincan** [comment]
@howellmartinez,

Could you please create a new issue?

Best Regards
