### ISSUE TITLE
How to use the SASS api?

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue#438]
I dont see the sass files included. How could we make use of the 'SASS Api'?

**Comment by Rakasch** [comment]
The page says "This means free themes are open source and for customization with SASS, a designer license needs to be acquired."
The link to the SASS API leads to https://www.primefaces.org/designer/primevue
for which you must buy a licence.

In case you already have a license here's the documentation
https://www.primefaces.org/designer-vue/#/documentation

**Comment by Jogai** [comment]
I dont need access to the designer, I just want to set a few variables...

**Comment by lochstar** [comment]
@Jogai You need to purchase a designer licence to access the uncompiled SASS files. With this then you can edit the variables. Without it we just have the compiled CSS files.

**Comment by cagataycivici** [comment]
Please use forum for questions, thank you.
