### ISSUE TITLE
SplitterPanel: this.$slots.default is not a function

### ISSUE THREAD

**Issue by dimitri-ks2** [primefaces/primevue#4382]
### Describe the bug

Sometimes, splitterpanel crash when default slot is not defined

Dans le fichier [splitterpanel](https://github.com/primefaces/primevue/blob/master/components/lib/splitterpanel/SplitterPanel.vue)
``` js
  isNested: function isNested() {
      return this.$slots["default"]().some(function (child) {
        return child.type.name === 'Splitter';
      });
    },
```
this.$slots["default"]() can be undefined
Fix : 
``` js
  isNested: function isNested() {
      if(!this.$slots["default"]()) { return false; }
        return this.$slots["default"]().some(function (child) {
        return child.type.name === 'Splitter';
      });
    },
```

### Reproducer

Can't reproduce

### PrimeVue version

3.33.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
How can we replicate this issue?

**Comment by tugcekucukoglu** [comment]
I guess you have used at least one SplitterPanel that default is an empty string or null, am I right? To replicate the issue, please send us a reproducer link
