### ISSUE TITLE
Menu: unnecessary warnings

### ISSUE THREAD

**Issue by rubjo** [primefaces/primevue#4386]
### Describe the bug

The warning

`In future versions, vue-router support will be removed. Item templating should be used.`

appears anywhere the Menu component is used without an item slot. For example for a non-navigation menu with only `command`s.

Instead, I guess it should appear only if one or more menu items have a `url` property.

### Reproducer

Eg. the Basic StackBlitz template from the Menu docs page

### PrimeVue version

3.33.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Use Menu component without using navigation / `url` (and without using item template)
2. Console warning

### Expected behavior

1. Use Menu component without using navigation / `url` (and without using item template)
2. No warnings

**Comment by tugcekucukoglu** [comment]
It is a deprecation warning given for a certain period of time.

Thanks for your understanding!

**Comment by inane** [comment]
So, this warning is irrelevant and will solved in next primevue versions?
