### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by SoyDiego** [primefaces/primevue#4388]
### Describe the bug

Typo error in CalendarMonthOptions

![image](https://github.com/primefaces/primevue/assets/19764334/9dddddb8-e910-4391-abe1-adb2393693cd)

### Reproducer

-

### PrimeVue version

Last version

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

All browsers

**Comment by DamianGlowala** [comment]
Closed in https://github.com/primefaces/primevue/commit/9b4fecfc4b5808fc20190b9ddeb17772aa7ec201

**Comment by SoyDiego** [comment]
> Closed in [9b4fecf](https://github.com/primefaces/primevue/commit/9b4fecfc4b5808fc20190b9ddeb17772aa7ec201)

Thanks I will close this PR, sorry
