### ISSUE TITLE
Dropdown: Style the placeholder with `unstyled: true`

### ISSUE THREAD

**Issue by phijma-leukeleu** [primefaces/primevue#4390]
### Describe the bug

It's seems impossible to style the placeholder of the Dropdown using `unstyled: true`. This setting removes `p-placeholder` from the classes, because otherwise PrimeVue's styling would be applied.

Suggestion: Add something to this element targetable by CSS.

Nice package, thank you!

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
This example seems to be working https://stackblitz.com/edit/64cgzk?file=src%2FApp.vue or am I missing something?

Thanks for your feedback!

**Comment by phijma-leukeleu** [comment]
> This example seems to be working https://stackblitz.com/edit/64cgzk?file=src%2FApp.vue or am I missing something?
> 
> Thanks for your feedback!

This changes the styling for the whole input. The issue is about the `placeholder` styling.

**Comment by tugcekucukoglu** [comment]
The class is applied to the placeholder.

Do you want to add style to the placeholder not the selected option value? The issue is not clear.

**Comment by phijma-leukeleu** [comment]
Sorry that the issue is not clear to you.

I thought it was clear by mentioning the `p-placeholder` class. That is used to style the placeholder *only*, correct? I'd like to style the placeholder only as well. But there isn't much to distinguish the placeholder from a selected option if using `unstyled: true`.

Thanks for looking into this.

**Comment by tugcekucukoglu** [comment]
Can reach every dom element of a component with pt. placeholder is an attribute for the input and the input option of the pt gives all styles. In this circumstance, I've updated the demo. You can see the difference by selecting an option.

https://stackblitz.com/edit/64cgzk?file=src%2FApp.vue

**Comment by phijma-leukeleu** [comment]
@tugcekucukoglu Thanks, that's pretty cool!
