### ISSUE TITLE
DataTable VirtualScroller: resizableColumns broken

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4394]
### Describe the bug

"resizableColumns" does not work anymore in a scrollable Datatable with a virtualscroller.
You can drag the column width, but the column resets as soon as you release the mouse button.

Did work with version 3.29.2, 
broken since version 3.30.0

### Reproducer

https://stackblitz.com/edit/xq17ml?file=src%2FApp.vue,src%2Fservice%2FProductService.js

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

see Reproducer
try to change the column width

**Comment by Rakasch** [comment]
Why is this marked as enhancement?
resizableColumns is a documented feature. It did work in an earlier version. Now it does not work anymore.

**Comment by maidzen** [comment]
Why is this Tagged as Enhancement?
This broke on patch "3.30.0" and makes many of my applications DataLists unusable for Users. (custom Columns, big text gets hidden because of column size and cant be resized).

please prioritize this as bug.

**Comment by TeoDar** [comment]
Faced with the same problem. I thought this was the usual, and at first I started looking for how to add code to the buttons for opening nested elements to update the width...
But if it worked before, then it's also interesting why the problem was moved to improvements.

**Comment by Rakasch** [comment]
Still an issue in 3.39.1
