### ISSUE TITLE
Component Name: Data Table, Filter by date console error

### ISSUE THREAD

**Issue by vobar** [primefaces/primevue#4396]
### Describe the bug

version: 3.32.2
if use datatable filter by date - error in console Uncaught (in promise) TypeError: value.getTime is not a function

Fix for this problem.
![image](https://github.com/primefaces/primevue/assets/4314201/9dd89056-7f4f-4ecb-b450-0ff0c9d5d54c)

pull request:
https://github.com/primefaces/primevue/pull/4395

### Reproducer

https://codesandbox.io/p/sandbox/headless-butterfly-56mv4q

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

all

### Steps to reproduce the behavior

1. open filter
2. set two dates
3. check the console

### Expected behavior

datable was filtered =)

**Comment by tugcekucukoglu** [comment]
The filtered value should be a Date instance, not a string. For more information: https://primevue.org/datatable/#advanced_filter


Here is a string to Date converter:

```
 return [...(data || [])].map((d) => {
        d.date = new Date(d.date);

        return d;
    });
```

**Comment by vobar** [comment]
oh, i'm sorry, i am missed this moment.
all work's correctly now! =)
Thank you very much! PrimeVue is awesome!
