### ISSUE TITLE
Maybe a general issue

### ISSUE THREAD

**Issue by jonasraoni** [primefaces/primevue#44]
Methods that run after the component is destroyed fail due to non-safe access to refs (`$refs?.x`) (they become undefined when destroying), maybe it's worth taking a look. I had this problem with the Dropdown.vue

**Comment by cagataycivici** [comment]
Could you please elaborate what the issue is and how to replicate?

**Comment by cagataycivici** [comment]
I'm unable to replicate, we'll create an issue template, please create a new issue with a test case reproducing the problem if the issue persists in the future.
