### ISSUE TITLE
DataTable: (unstyled + Tailwind) stripedRows styling applies in dark mode but not light mode

### ISSUE THREAD

**Issue by hamish-smith** [primefaces/primevue#4406]
### Describe the bug

I tried adding `stripedRows` to the `DataTable` sandbox code for unstyled + Tailwind passthrough on the Theming page of the component documentation.

Toggling between light mode and dark mode, there is no visual difference between rows in light mode, whereas in dark mode the rows are clearly different colours.

### Reproducer

https://codesandbox.io/p/sandbox/proud-water-5c8jl2?welcome=true

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

# Steps to reproduce

I went to the code example for the DataTable and editing the App.vue to add `stripedRows` to the DataTable in the sandbox/example code.

Then I toggled between light and dark theme.

### Expected behavior

Visually different rows for stripedMode in light and dark mode.

**Comment by tripex** [comment]
I guess this issue is not fixed, at least I has the same behaviour for me, just installed primevue today.
