### ISSUE TITLE
SplitButton: Resolving Deprecation Warning, Documentation Unclear

### ISSUE THREAD

**Issue by dmhendricks** [primefaces/primevue#4411]
### Describe the bug

I just upgraded to PrimeVue 3.34.0. I noticed several components were displaying a deprecation warning in the console:
> In future versions, vue-router support will be removed. Item templating should be used. (tieredmenu.esm.js:445)

I was able to resolve the deprecation warning for the **Menu** and **Menubar** components by adding an `#item` template as shown in the documentation. However, I'm unable to resolve the deprecation warning with the **SplitButton** component - It's not obvious to me in the current [documentation](https://primevue.org/splitbutton/).

Can someone provide an example/template that will allow the SplitButton to function as it did previously and resolve the deprecation warning? Example provided below from the docs.

### Reproducer

None.

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

The warning appears using the "Basic" syntax as shown in the [documentation](https://primevue.org/splitbutton/). I'm uncertain how the "template" should look for this example to remove the deprecation warning. From the documentation:

```html
<template>
    <div class="card flex justify-content-center">
        <Toast />
        <SplitButton label="Save" icon="pi pi-plus" @click="save" :model="items" />
    </div>
</template>

<script setup>
import { useToast } from "primevue/usetoast";
const toast = useToast();

const items = [
    {
        label: 'Update',
        icon: 'pi pi-refresh',
        command: () => {
            toast.add({ severity: 'success', summary: 'Updated', detail: 'Data Updated', life: 3000 });
        }
    },
    {
        label: 'Delete',
        icon: 'pi pi-times',
        command: () => {
            toast.add({ severity: 'warn', summary: 'Delete', detail: 'Data Deleted', life: 3000 });
        }
    },
    {
        label: 'Vue Website',
        icon: 'pi pi-external-link',
        command: () => {
            window.location.href = 'https://vuejs.org/';
        }
    },
    { label: 'Upload', icon: 'pi pi-upload', to: '/fileupload' }
];

const save = () => {
    toast.add({ severity: 'success', summary: 'Success', detail: 'Data Saved', life: 3000 });
};
</script>
```

### Expected behavior

The goal is to have the SplitButton to look/function as it did before, without the deprecation warnings. I'd like to get my code updated now so I don't have to worry about it later when the old syntax is no longer supported. Thank you.

**Comment by rubjo** [comment]
Same as #4386. The check to determine whether the warning should be shown (= "Is there an #item template?") is unfortunately not relevant to the warning text (should be "Is there at least one entry with an `.url` property?")

**Comment by tugcekucukoglu** [comment]
SplitButton uses TieredMenu internally and the warning says vue-router support will be removed for all Menu components for the next versions. The warning will also be removed when vue-router support is completely removed. All menu demos have been updated according to this change. If you are using vue-router features, we recommend that you migrate before all support is removed.

**Comment by adrianrudnik** [comment]
Just had to dig into this as well, would be nice if deprecation warnings emit some kind of link to the related or updated documentation or migration guide.

The related and updated menu demo part can be found [here](https://primevue.org/menubar/#router).

Be advised, the current example

```html
  <router-link v-if="item.route" v-slot="routerProps" :to="item.route" custom>
    <a :href="routerProps.href" v-bind="props.action">
```

will break SPA navigation and do a hard url navigation due to a missing navigate slot operation. Here is an updated variant that respects SPA navigation:

```html
  <router-link v-if="item.route" v-slot="{ navigate, href }" :to="item.route" custom>
    <a :href="href" v-bind="props.action" @click="navigate">
```

based on the current [vue-router example](https://router.vuejs.org/guide/advanced/extending-router-link.html#Extending-RouterLink).

**Comment by Stephan-DXRS** [comment]
> Same as #4386. The check to determine whether the warning should be shown (= "Is there an #item template?") is unfortunately not relevant to the warning text (should be "Is there at least one entry with an `.url` property?")

So we don't have to do anything if we are not using any `url` options?

**Comment by rubjo** [comment]
It's not really necessary to do anything. But the issue is still there: lots of warnings in the console, even with no `url` properties.

**Comment by eepson123tw** [comment]
![image](https://github.com/user-attachments/assets/cbaa2c82-7db7-47c7-9d72-6e4f3f2ee85c)
Same here wait for any update
