### ISSUE TITLE
Component Name: SplitButton

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4413]
### Describe the bug

SplitButton shows warning "In future versions, vue-router support will be removed. Item templating should be used.". But there is no slot for menutem in it.

### Reproducer

https://codesandbox.io/s/zxjgjf?file=/src/App.vue

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open console.

### Expected behavior

No warnings, or maybe add a slot for menu item.

**Comment by tugcekucukoglu** [comment]
SplitButton uses TieredMenu internally and the warning says vue-router support will be removed for all Menu components for the next versions. All menu demos have been updated according to this change. If you are using vue-router features, we recommend that you migrate before all support is removed. 

This warning will be removed after a certain period of time.
