### ISSUE TITLE
Bitwise operator used in passthorugh/tailwind/index.js instead of logical operator

### ISSUE THREAD

**Issue by tomaszpuzio** [primefaces/primevue#4415]
### Describe the bug

In `/components/lib/passthrough/tailwind/index.js` in lines 771 - 775 bitwise & operator is used instead of logical && operator. 
```
{
    'text-gray-500 hover:bg-gray-300/20': props.plain & props.text,
    'text-gray-500 border border-gray-500 hover:bg-gray-300/20': props.plain & props.outlined,
    'text-white bg-gray-500 border border-gray-500 hover:bg-gray-600 hover:border-gray-600': props.plain & !props.outlined & !props.text
}
```
I believe this is a typo as also everywhere else in the file logical operators are used.
When trying to create custom button styling options, bitwise operator results in typescript error `The '&' operator is not allowed for boolean types. Consider using '&&' instead.`.

I was not able to import `PrimeVuePTOptions` type in sandbox, therefore I did not add reproducer.

The proposed solution is to update bitwise & operator to logical && operator in the lines mentioned above.

### Reproducer

no reproducer

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Create file e.g. `example.ts` :
```
import { type PrimeVuePTOptions } from 'primevue/config'

const example: PrimeVuePTOptions = {
  button: {
    root: ({ props, context }) => ({
      class: [
        {
          'text-gray-500 border border-gray-500 hover:bg-gray-300/20': props.plain & props.outlined,
        },
      ]
    })
  },
}
```

### Expected behavior

No typescript error.

**Comment by mertsincan** [comment]
Opss! Good catch, we'll fix it asap. Thanks a lot for your report!

**Comment by tomaszpuzio** [comment]
Thanks for such a prompt reaction! 👍
