### ISSUE TITLE
component size

### ISSUE THREAD

**Issue by Rhejie** [primefaces/primevue#4416]
### Describe the feature you would like to see added

all components should have a size from small to large

### Is your feature request related to a problem?

No

**Comment by BenJackGill** [comment]
100% agree. A `size` prop on all components is sorely needed.

**Comment by psuplat** [comment]
Fully agree. The new features, like updates to float labels (although not without bugs) are nice and all, but main point of any framework should be consistency as much as possible. I'm going around it by simply increasing padding with scoped styling, but that should be a quick and much needed improvement

**Comment by JustineMiko** [comment]
Hello, any update about this ? I'm using the Multiselect component and the size prop does not work

**Comment by psuplat** [comment]
@JustineMiko apparently yes. The working example are on the official documentation. You probably need to update your packages to 4.2.1 (I think that's the lates version anyways)

**Comment by JustineMiko** [comment]
> @JustineMiko apparently yes. The working example are on the official documentation. You probably need to update your packages to 4.2.1 (I think that's the lates version anyways)

That's not it, my package is up to date. I think it's because it's not working yet for Multiselect component as sait @BenJackGill

**Comment by psuplat** [comment]
@JustineMiko I've never actually used nuxt, so can't help here. But I just did a copy&pasts of the code from the docs, into login component in one of my projects, and it worked perfectly fine, as advertised. 

![obraz](https://github.com/user-attachments/assets/01f7fcaf-cb23-4257-a3cd-e3264637280d)

Have you tried switching it off and on again - meaning, delete the entire _node_modules_ folder and running _npm install_ again?

**Comment by JustineMiko** [comment]
@psuplat yes i did try that to but it doesn't change anything. Thank you for your advices and your time. If i find out how to fix my issue i'll leave a comment here for people using nuxt3

**Comment by JustineMiko** [comment]
@psuplat i had one dependency not up to date ! the primevue/theme one ! so it's properly working now. Thank you so much !

**Comment by tugcekucukoglu** [comment]
You could check the latest version.

Thanks for the updates.

**Comment by JustineMiko** [comment]
@tugcekucukoglu it works absolutely fine with V4.2.2. Thanks a lot
