### ISSUE TITLE
usePassThrough: doesn't merge default pt and custom with TailwindCSS

### ISSUE THREAD

**Issue by awkoy** [primefaces/primevue#4417]
### Description:
I am attempting to modify the global styles of the Button component using the usePassThrough function. My objective is to have a Button component that combines both default styles and customized text color.

### Pass-Through Configuration:
```
const Tailwind_PT: PrimeVuePTOptions = {
    button: {
        root: {
          class: "text-custom-black",
        },
    },
};

const CustomTailwind = usePassThrough(
    Tailwind,
    Tailwind_PT,
    {
        mergeSections: true,
        mergeProps: true,
    }
);
```

### Tailwind Configuration (tailwind.config.js):
```
export default {
    content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
    theme: {
        extend: {
          colors: {
            custom: {
              black: "#f3f3f3"
            }
          }
        },
    },
    plugins: [],
};
```

### Expected Behavior:
I expect to see a Button component that retains its default styles but has its text color changed to black (#f3f3f3).

### Actual Behavior:
What I get instead is an unstyled Button component with the text color changed to black (#f3f3f3).

### Reproduction:
Here is a [CodeSandbox link](https://codesandbox.io/p/sandbox/unstyled-primevue-dialog-with-tailwind-css-forked-dgyghy?embed=1&file=%2Fsrc%2Fpassthrough%2Ftailwind.ts%3A7%2C13) for reproducing the issue.

Any guidance on resolving this issue would be greatly appreciated. Thank you!

### Reproducer

https://codesandbox.io/p/sandbox/unstyled-primevue-dialog-with-tailwind-css-forked-dgyghy?embed=1&file=%2Fsrc%2Fpassthrough%2Ftailwind.ts%3A7%2C13

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

Here is a [CodeSandbox link](https://codesandbox.io/p/sandbox/unstyled-primevue-dialog-with-tailwind-css-forked-dgyghy?embed=1&file=%2Fsrc%2Fpassthrough%2Ftailwind.ts%3A7%2C13) for reproducing the issue.

### Expected behavior

I expect to see a Button component that retains its default styles but has its text color changed to black (#f3f3f3).

**Comment by mertsincan** [comment]
Hi @awkoy,

You need to make some changes;
1) Please add `"./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}"` to content in tailwind.config.js; 
https://tailwindcss.com/docs/content-configuration#working-with-third-party-libraries

```js
/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
        "./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}"
    ],
    theme: {
        extend: {
            colors: {
              custom: {
                black: '#f3f3f3',
              },
            },
          },
    },
    plugins: []
}
```

2) Button component has a more powerful colour class. So, you can add important character(!) to your custom class.
```js
button: {
    root: {
      class: '!text-custom-black',
    },
  },
``` 
You can control their effects in DOM. Also, #f3f3f3 is not in the black pallet.  Please try `#000000` to test it.

Best Regards,

**Comment by larrasu** [comment]
It's not working for me either. I have to manually set `:ptOptions="{ mergeProps: true }"` each component to merge Tailwind classes. My PT config has `mergeProps` and `mergeSections` set to `true`.

**Comment by mertsincan** [comment]
@larrasu, can you please create a new issue with a sample codesandbox link?

Best Regards,
