### ISSUE TITLE
Button renders an empty label element

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue#442]
The buttons render  a label element when the label is empty. Is that intentional? It seems to me that it should be omitted.

The following button from the documentation:

    <Button icon="pi pi-check" class="p-button-rounded" />

Is being rendered as (label on line 3)

```html
<button data-v-1c7a860c="" type="button" class="p-button-rounded p-button p-component p-button-icon-only">
    <span class="pi pi-check p-button-icon"></span>
    <span class="p-button-label">&nbsp;</span>
    <!---->
    <span class="p-ink" style="height: 33px; width: 33px; top: -1.5px; left: -4.40625px;"></span>
</button>`

**Comment by cagataycivici** [comment]
Yes, it is intentional for styling and we have plans to use for for aria purposes as well for screen readers.
