### ISSUE TITLE
Steps: Invalid typing for StepsRouterBindProps

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#4420]
### Describe the bug

`StepsRouterBindProps` are not containing definition for the `step`.
In documentation https://primevue.org/steps/seat/ we see that the props.step is used to apply attributes to the step item. It is working, but the types are not defining it, which causes typecheckers to fail.

### Reproducer

-

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by borsTiHD** [comment]
I can confirm this, I get the same typing error in primvue `v3.37.0`:
`Property 'step' does not exist on type 'StepsRouterBindProps'.ts(2339)`

**Comment by Magiczne** [comment]
Fixed in https://github.com/primefaces/primevue/issues/4703
