### ISSUE TITLE
Column: headercheckboxicon slot issues

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#4425]
### Describe the bug

The `headercheckboxicon` slot is not doing anything for column.

https://primevue.org/datatable/#api.column.slots is telling us that the `headercheckboxicon` slot on the Column should define icon for the header checkbox.
It is not working

### Reproducer

https://codesandbox.io/s/immutable-currying-jlptlr

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

We can customize header checkbox using this slot

**Comment by Magiczne** [comment]
@tugcekucukoglu could this be handled?

**Comment by mertsincan** [comment]
I couldn't replicate it with the latest version. For now, closed. If the problem persists, please reopen it.

Best Regards,
