### ISSUE TITLE
Mask for Calendar

### ISSUE THREAD

**Issue by aydemirfatih** [primefaces/primevue#443]
Hi primevue team,
Would be nice to add a mask according to the specified dateformat.

If the user enters date ("05.08.2020") manually unlike dateformat  (dd/mm/yy), value will be "05.08.2020" but the expected value is "2020-08-04T21:00:00Z". In addition to that it causes misunderstanding, which part of date is day or month, because of not having knowledge whether the user entered the date manually or not.

**Comment by cagataycivici** [comment]
Adding it to our todo list, thank you for the feedback.

**Comment by emersoncpaz** [comment]
Any news about this enhancement?

**Comment by cagataycivici** [comment]
Recently, PrimeReact got this feature. If there is more demand from the community, we'll add it to Vue as well.

**Comment by svengeance** [comment]
The default DatePicker in the browser (`<input type="Date">`) has this feature and it's rather nice - means our users don't need to know the ordering or type in special characters. I would love to see this added to Vue as well. Shame we can't combine the InputMask and Calendar

**Comment by makurtu** [comment]
@cagataycivici do you have any plans on implement it?

I can send a PR with this feature, but I will rewrite all InputMask code, moving all "shareable" code to a lib file and using it from InputMask and Calendar, it's same code and now is'nt unusable from Calendar.

Can I do it (the PR)?

**Comment by emersoncpaz** [comment]
A mask support for time would be nice too.

**Comment by joerattz** [comment]
We need this feature.  An alternative approach would be to slot the input field?

**Comment by gimler** [comment]
I also need this feature.

My idea add a input slot. So that we can override the default input field with InputMask?

**Comment by cagataycivici** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
