### ISSUE TITLE
Dropdown & MultiSelect: Disabled selected value

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#4431]
### Describe the bug

There appears to be a discrepancy in this behaviour between `Dropdown` & `MultiSelect` components. See demo in reproducer link.

- The data array contains 5 options, and the `Rome` option is disabled
- In `Dropdown` component, I have selected `Rome` and this option does not get selected
- In `MultiSelect` component, I have selected `New York` & `Rome`, both of these options are selected

I am not entirely sure what the correct behaviour should be, but either way it should be consistent. I can see this was tackled previously in: https://github.com/primefaces/primevue/issues/3715 & https://github.com/primefaces/primevue/issues/3541.

I think some users may prefer to see the disabled option selected, and some users may prefer the opposite. Perhaps a prop to control the behaviour could work?

### Reproducer

https://stackblitz.com/edit/prncz5-sebdlg?file=src%2FApp.vue

### PrimeVue version

3.32.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by MiguelBamberino** [comment]
Good Morning,
is there an update on the priority of this issue ?

**Comment by banyalshipu** [comment]
Hi , 
Can you please update on same because i am stuck with this issue . I need disabled option render on input same like non disabled . Your support would be very helpful.

**Comment by omzy** [comment]
Hi there, any chance I can get an update on this please?

**Comment by rubjo** [comment]
@tugcekucukoglu This is not fixed and should not have been closed. A Select's value is not rendered if the option is disabled. There are use cases for this, like if the selected value is old / obsolete / no longer should be selectable – you might still want to show the current value.
