### ISSUE TITLE
Container Slots for Overlay Components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#4433]
For example, Toast, Dialog, Sidebar and OverlayPanel are good candidates for the container slot where entire content inside the root can be templated.

```html
<p-toast>
   <template #container>
     Replaces the whole content, we should also pass close event handler to bind to custom UI
  </template>
</p-toast>
```

Related discussion;

https://github.com/orgs/primefaces/discussions/16

**Comment by tugcekucukoglu** [comment]
Toast and Dialog: https://github.com/primefaces/primevue/commit/962ddb13530e4a109971dc02012317a6a6da68c3
