### ISSUE TITLE
DataTable: VirtualScroller breaks when sort is applied

### ISSUE THREAD

**Issue by zachlearnscode** [primefaces/primevue#4434]
### Describe the bug

The DataTable VirtualScroller displays empty table rows when a sort is applied to a column. The issue occurs after:

1. a sort is applied somewhere in the middle of the dataset
2. after applying a sort at the top of the dataset, then scrolling to a random location in the middle of the table.

On the other hand, if a sort is applied and the user scrolls the table slowly (ie one chunk of `{first, last}` at a time, the does not occur. Additionally, if you take the same steps _without_ a sort applied, the DataTable responds as you'd expect.

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-ssgtwk?file=/src/App.vue

### PrimeVue version

3.31.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Without a sort applied, scroll to a random location beyond the top of the table (you can do this with a scroll wheel or dragging the scroll bar with the cursor)
3. Note that the table rows are loaded as expected
4. Apply a sort
5. Note that the table displays empty table rows.
6. Scroll back to the top of the table and note that the issue corrects itself
7. Scroll the table slowly and note that the issue doesn't occur
8. Scroll again to a random location in the table and note that the table again displays empty rows

### Expected behavior

When a sort is applied to a VirtualScroller DataTable, the table should work the same when a sort applied while scrolling quickly around the table

**Comment by zachlearnscode** [comment]
bumping

**Comment by mertsincan** [comment]
Fixed now. But, as you know, sorting in DataTable with lazy must be done by you. Please see the details; https://primevue.org/datatable/#lazy_load

Best Regards,
