### ISSUE TITLE
Menubar: Deprecation Message is displaying for all programmatic usage of Vue Router outside of Prime

### ISSUE THREAD

**Issue by admin-nexgen** [primefaces/primevue#4439]
### Describe the bug

When I try to use a MenuBar component I get a warning message in the console for every single usage of Vue Router, even outside of Prime. The Vue Router deprecation message is showing up for all usage of Vue Router, even just registering it in the main.ts.
It should only be displayed if you use a Prime Component and you are not using templating within the component.
The result is that in a large application, it shows up everywhere, which is really annoying.
There are plenty of valid reasons for using programmatic navigation with Vue router outside of Prime such as when using dynamic components.

### Reproducer

https://codesandbox.io/p/sandbox/stupefied-kate-dxff4s

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 116

### Steps to reproduce the behavior

Add a MenuBar component into the page.
It shows a warning in the console just because I have registered to use the router in the site.
It should have nothing to do with Prime as I haven't even configured the MenuBar component.
If you use the MenuBar in each page, then the message appears for every single page navigation.
If you toggle between the home and about pages, the console message appears each time you navigate.

### Expected behavior

Console should be free from warnings outside of prime components.
Only if you try to use programmatic navigation inside the prime component itself.

**Comment by tugcekucukoglu** [comment]
It is a deprecation warning given for a certain period of time. It will definitely be removed after a few versions.

Thanks for your understanding!

**Comment by admin-nexgen** [comment]
The issue i'm logging about is not about the warning, it's that the warning is showing up for the wrong reasons. It should not be displayed simply because I am using the router component in my application and I happened to use the menubar component. As I said in the description of the bug. I didn't even violate what the message is saying.
