### ISSUE TITLE
DataTable VirtualScroller: Firefox , Scroll-linked

### ISSUE THREAD

**Issue by ciroamaro88** [primefaces/primevue#4440]
### Describe the bug

**I have this warning in console:**

"Questo sito utilizza un effetto di posizionamento “scroll-linked” che potrebbe non funzionare correttamente in combinazione con il panning asincrono. 

Consultare https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html per ulteriori dettagli e partecipare alla discussione su strumenti e caratteristiche."

**This is the web site to go for info:**
Scroll-linked effects[¶](https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html#scroll-linked-effects)

The definition of a scroll-linked effect is an effect implemented on a webpage where something changes based on the scroll position, for example updating a positioning property with the aim of producing a parallax scrolling effect. This article discusses scroll-linked effects, their effect on performance, related tools, and possible mitigation techniques.
Scrolling effects explained[¶](https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html#scrolling-effects-explained)

Often scrolling effects are implemented by listening for the scroll event and then updating elements on the page in some way (usually the CSS [position]((https://developer.mozilla.org/en-US/docs/Web/CSS/Position “The position CSS property sets how an element is positioned in a document. The top, right, bottom, and left properties determine the final location of positioned elements.”) or [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) property.) You can find a sampling of such effects at [CSS Scroll API: Use Cases](https://github.com/RByers/css-houdini-drafts/blob/master/css-scroll-api/UseCases.md).

These effects work well in browsers where the scrolling is done synchronously on the browser’s main thread. However, most browsers now support some sort of asynchronous scrolling in order to provide a consistent 60 frames per second experience to the user. In the asynchronous scrolling model, the visual scroll position is updated in the compositor thread and is visible to the user before the scroll event is updated in the DOM and fired on the main thread. This means that the effects implemented will lag a little bit behind what the user sees the scroll position to be. This can cause the effect to be laggy, janky, or jittery — in short, something we want to avoid.

### Reproducer

https://codesandbox.io/s/4ync75

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox

### Steps to reproduce the behavior

Apply virtualScrollerOptions in DataTable with more 200 items for example.
Use Firefox Browser and scroll to bottom of DT.

Rendering take 10 seconds or more and in console write the warning described above.

### Expected behavior

Rendering behaviour same Chrome Browser.

**Comment by mertsincan** [comment]
Hi,

I searched this issue and found; https://stackoverflow.com/questions/50443959/what-is-the-alternative-to-scroll-linked-positioning-effect-to-prevent-perform/57641938#57641938

If you use the `delay` option, we wrap our scroll methods with setTimeout. I tried it with that and the warning in FF disappeared.

```
<DataTable :virtualScrollerOptions="{ delay: 100, ... }" ....
```

Best Regards,
