### ISSUE TITLE
Dropdown: Options doesn't change its position by changing the screen size

### ISSUE THREAD

**Issue by ALC-Poehacker** [primefaces/primevue#4448]
### Describe the bug

Dropdown options div position still the same by changing the screen size. 

You can also reproduce it on the website: https://primevue.org/dropdown/

![image](https://github.com/primefaces/primevue/assets/71490832/e1160485-55ed-4fa4-a680-aeb72577b458)

### Reproducer

https://codesandbox.io/p/sandbox/primevue-dropdown-options-issue-forked-gq3fyt?file=/src/App.vue

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome, Edge, Firefox...

### Steps to reproduce the behavior

1. Click on the dropdown
2. After the options div is visible, change the screen size

### Expected behavior

Options div should change its position by resizing the screen and should stay below the dropdown

**Comment by tugcekucukoglu** [comment]
Please try to use the latest version. If you think there is a problem, we can reopen the issue. So closing.
