### ISSUE TITLE
Add `modules` property to Editor

### ISSUE THREAD

**Issue by Vinccool96** [primefaces/primevue#4450]
### Describe the feature you would like to see added

It's exactly like the feature request #2498 but for primevue v2 (for vue 2). It's for the samr usage (using an extra Quill module called "Quill image uploader".

### Additional context

If you give me a few minutes I'll create a PR to implement it.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4452
