### ISSUE TITLE
Menu: Deprecation warnings in production builds

### ISSUE THREAD

**Issue by eneeio-nm** [primefaces/primevue#4453]
### Describe the bug

Whilst I understand the need to warning developers about deprecations, there is no need to display deprecation warnings in production builds.

The second point I wish to make here is that the deprecation warning is displayed if the menu has no `item` slots being used e.g.

```js
if (!this.$slots.item) {
  console.warn('In future versions, vue-router support will be removed. Item templating should be used.');
}
```

This doesn't make sense. Not all menu instances need to have items in the item slot? The deprecation warning should only be displayed if the usage of the menu requires it.

Please can these be resolved as a matter of urgency?

### Reproducer

https://primevue.org/menu/

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

1. Go to PrimeVue menu docs
2. Open browser devtools and view console

### Expected behavior

Deprecation warnings only displayed in development mode and if outdated implementation of menu is being used.

**Comment by tugcekucukoglu** [comment]
It is a deprecation warning given for a certain period of time. It will definitely be removed after a few versions.

Thanks for your understanding!

**Comment by omzy** [comment]
The warning message doesn't make sense. I am not using Vue-Router, I am using hardcoded URLs, e.g:

```
{label: 'Dashboard', url: '/dashboard'},
{label: 'Settings', url: '/settings'},
```

Please can you update the IF statement to only display the warning if the user is using Vue-Router.

**Comment by sid-6581** [comment]
We're also getting this warning in production builds (which is just incorrect and looks unprofessional), please make it conditional and don't show it in production.

Also like the others, we are getting this warning when we're not even using vue-router. We use hardcoded URLs or commands, so we shouldn't be seeing this warning at all.

**Comment by robokozo** [comment]
I'm only using the `command` callback with my menu and I'm still getting this message. No vue-router or urls in sight!

I don't mind deprecation messages but this, like others have said, looks completely unprofessional in our application.
