### ISSUE TITLE
Dropdown: Selected value not shown using filter when contentValue is used

### ISSUE THREAD

**Issue by DanRoddis** [primefaces/primevue#4456]
### Describe the bug

When using the Dropdown control when a contentValue is selected e.g. an id property when filtering the placeholder is shown rather than the detail of the selected item.

Issue is visible in the following StackBlitz, select an option, then filter for another option - the placeholder content is displayed rather than the selected option.

https://stackblitz.com/edit/suqusr?file=src%2FApp.vue

Rather than having to specify a template for the slot the default should be that the selected item is always displayed rather than the placeholder.

### Reproducer

https://stackblitz.com/edit/suqusr?file=src%2FApp.vue

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Go to https://stackblitz.com/edit/suqusr?file=src%2FApp.vue
Select an option in the dropdown
Filter the dropdown to not include the selected option
The selection option is no longer displayed in the selection area and instead the placeholder is displayed

### Expected behavior

Go to https://stackblitz.com/edit/suqusr?file=src%2FApp.vue
Select an option in the dropdown
Filter the dropdown to not include the selected option
The selected option is always displayed in the selection area while it is selected

**Comment by tugcekucukoglu** [comment]
The demo that you've shared seems working correctly. Please check with the latest version. If the problem still persist, please create a new issue.

**Comment by DanRoddis** [comment]
Thanks @tugcekucukoglu - this is still an issue created #4838 with additional information
