### ISSUE TITLE
[DataTable] Reorder feature and rowreordericon slot problem.

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue#4459]
### Discussed in https://github.com/orgs/primefaces/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **tuffkidd** September 14, 2023</sup>
The Reorder feature of DataTable sometimes doesn't work correctly.

1. When I click the reorder icon, the draggable attribute of the corresponding <tr> changes from false to true.
2. However, after moving it, occasionally the false does not change back to true, making it impossible to reorder.
3. After randomly clicking other areas and then clicking it again, it changes to true.

![PrimeVue-DataTable-Reorder](https://github.com/primefaces/community/assets/2167254/982b31e2-aef3-4f3b-aafc-0ffb18f6697d)

And when using the rowreordericon slot, the icon appears but it doesn't work. See the code below.
```html
<Column :row-reorder="true" header-style="width: 3em">
  <template #rowreordericon>
    <i :class="['p-datatable-reorderablerow-handle', 'ICONCLASS']" style="font-size: 1.25rem"></i>
  </template>
</Column>
```
</div>

**Comment by Antal1609** [comment]
To get row reordering to work you need to add `data-pc-section="rowreordericon"` like this:
```html
<column :row-reorder="true" :reorderable-column="false">
    <template #rowreordericon>
        <i class="fas fa-bars" data-pc-section="rowreordericon"></i>
    </template>
</column>
```

Optionally add `p-datatable-reorderablerow-handle` for the move cursor.

Originally answered in #4062

**Comment by davidglezz** [comment]
In v4 it is renamed to `data-pc-section="reorderablerowhandle"`

**Comment by R1ckyCZ** [comment]
> If anyone still having this problem this solution worked for me: `<Column rowReorder headerStyle="width: 3rem"> <template #body="slotProps"> <div :draggable="true" class="cursor-move"> <i class="pi pi-bars"></i> </div> </template> </Column>`

That did the trick for me, thanks a bunch. Was losing my mind already, seemed like it just works for everyone. For me it was working like 1 out of 10 at best, with solution mentioned by @Rody-Khalil I am at 10 out of 10 successful drags.

**Comment by noah-johnson1810** [comment]
Wow, thank you @Rody-Khalil. :draggable="true" is what I was missing. Your comment was just in time for me :)

**Comment by jet-aimss** [comment]
If anybody still has this problem, here's an improved answer based on @Antal1609 & @davidglezz. I've added an additional tailwind class to achieve the default behavior.

`<Column rowReorder headerStyle="width: 3rem" :reorderableColumn="false">
        <template #rowreordericon>
          <i class="pi pi-bars hover:cursor-move" data-pc-section="reorderablerowhandle"></i>
        </template>
      </Column>`

@Rody-Khalil answer is ok, but the drag animation only applies to the icon, not the whole row, which looks off to me.
