### ISSUE TITLE
Use different icons for the data table sort icon

### ISSUE THREAD

**Issue by rlightner** [primefaces/primevue#446]
Is it possible to specify different icons rather than using the predefined icons?

**Comment by cagataycivici** [comment]
There are no props but it can be done with css overrides. Do you need to use your own icons or other ones from PrimeIcons?

**Comment by rlightner** [comment]
Was hoping to use FontAwesome as that's the theme we're going with.

**Comment by leifcr** [comment]
Similar issue in #634, and for buttons.
This:
```
<Button icon="fads user-times" class="p-button-raised p-button-rounded">
```
Outputs this for the icon::
```
<span class="fad user-times p-button-icon"></span>
```

By making it possible to override or remove p-button-icon class it should work with fontawesome as well.

A global setting for icon class 'disable' should solve this.

**Comment by leifcr** [comment]
Solutions for buttons, that work:
```
      <Button icon='pi' class="p-button-raised p-button-rounded">
        <font-awesome-icon :icon="['fad', 'user-times']" />
      </Button>
```

**Comment by leifcr** [comment]
@cagataycivici I think you might want to add a new task to perhaps be able to swap icon set with fontawesome across the entire project.

**Comment by binarykiwi** [comment]
Same for me with `Password` - I`d like to have props like `<Password iconShow="icon-show" iconHide="icon-hide" />` to set the classnames for the icons... Possible for all components using icons?

**Comment by cagataycivici** [comment]
We can add sortIcon, sortAscIcon etc however it would be to repetitive to do it for all tables and columns. Simple solution is to override the icons with CSS. PrimeIcons are icon fonts so can be overridden easily by swapping the font family and the css content.

**Comment by nicholasirsyad** [comment]
Has this been resolved? I can't find any way to customize sort icon even using the pTemplate="sorticon". 
Am I missing something?

**Comment by nicholasirsyad** [comment]
> Has this been resolved? I can't find any way to customize sort icon even using the pTemplate="sorticon". Am I missing something?
> 
> Using primeng v17.12.0 here. There doesn't seem to be any specific CSS class attached to the sort icon on the header. I also can't find any documentation on how to do it via the PrimeNGConfig. Following this article also doesn't work for me: https://stackoverflow.com/questions/76112717/how-to-replace-table-header-sort-icons-in-primeng-15-4

For now, I've had to resort to customizing through global CSS. In primeNG v17 there is no CSS class associated with the ascending or descending icon, so I had to resort to these convoluted CSS Rules:

`
  .p-sortable-column-icon .p-element.p-icon-wrapper svg {
    display: none;
  }

  .p-sortable-column-icon .p-element.p-icon-wrapper {
    font-family: 'primeicons';
  }

  .p-sortable-column-icon sortamountdownicon.p-element.p-icon-wrapper:before {
    content: '\e919';
  }

  .p-sortable-column-icon sortamountupalticon.p-element.p-icon-wrapper:before {
    content: '\e91c';
  }
`
