### ISSUE TITLE
AutoComplete: add a `value` slot (like in DropDown)

### ISSUE THREAD

**Issue by Irelynx** [primefaces/primevue#4465]
### Describe the feature you would like to see added

Currently it is impossible to change a value title (visible text, that user will see when value is selected) via slots unlike DropDown ([link](https://primevue.org/dropdown/#api.dropdown.slots.value))

### Is your feature request related to a problem?

I know that i can pass a function into `optionLabel` prop, but what if i would like to use more complex markup than just text?
Other slots (e.g. `option`) doesn't have impact when value is selected and pop-up dialog is closed

### Describe the solution you'd like

Add `value` slot like in DropDown component ([link](https://primevue.org/dropdown/#api.dropdown.slots.value))

### Describe alternatives you have considered

Alternatively, I can use DropDown with editable text

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
