### ISSUE TITLE
usePassThrough: `mergeProps` and `mergeSections` are set to `true` but doesn't merge when components have `:pt` props

### ISSUE THREAD

**Issue by larrasu** [primefaces/primevue#4466]
### Describe the bug

I have set `mergeProps` and `mergeSections` to `true` using `usePassThrough`. Whenever I use passthrough in a component, I have to enable `mergeProps` manually. I end up having to always type `:pt-options="{ mergeProps: true }"` in every component.

### Reproducer

https://codesandbox.io/p/sandbox/condescending-framework-jqtvyy?welcome=true

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

If `mergeProps` and `mergeSections` are set to `true` in `usePassThrough`, it should affect all components. Or have I misunderstood the purpose of `usePassThrough`?

**Comment by lotestudio** [comment]
Same question?

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/4473
