### ISSUE TITLE
Failed to resolve component ProgressBar

### ISSUE THREAD

**Issue by Stephan-DXRS** [primefaces/primevue#4477]
### Describe the bug

We are trying to use a progress bar and progress spinner component in our app. Either component causes a `Failed to resolve component` warning in the console.

The strange part is that the button, panel and scroll panel components load just fine.

We are globally registering the components like this:
`app.component('Button', Button);`
`app.component('Panel', Panel);`
`app.component('ScrollPanel', ScrollPanel);`
`app.component('ProgressSpinner', ProgressSpinner);`
`app.component('ProgressBar ', ProgressBar);`

We are not doing anything special, in this example the button is shown and the progress bar isn't, hence the warning. They are both in the same component.
`<Button label="test"></Button>`
`<ProgressBar mode="indeterminate"></ProgressBar>`

### Reproducer

N/A

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 117

**Comment by eneeio-nm** [comment]
In the first instance, check this [StackBlitz](https://stackblitz.com/edit/l9hsrj?file=src%2Fmain.js) to make sure your imports are correct. Without further code, or a reproducible repo it'll be difficult to get you further help.

**Comment by Stephan-DXRS** [comment]
It seems to be related to Vite not compiling the newly added import. After moving the import to a component, I saw the Vite CLI stating that it was compiling the ProgressBar, afterwards I was able to move the import back to main.ts.
