### ISSUE TITLE
MenuBar: Allow HTML in menu item label

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#4479]
### Describe the feature you would like to see added

I am trying to include HTML in my menu item labels, however it just outputs the raw HTML instead of rendering it.

See demo here: https://stackblitz.com/edit/prncz5-zhmezj

I am aware I can use the `item` template, but as you can see in my demo, I am rendering different HTML per item. I would prefer not to have to loop over each item and manually create them that way.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
