### ISSUE TITLE
Menu: Remove focus from first item (in popup mode)

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#4481]
### Describe the feature you would like to see added

When using Menu in popup mode, the first item is receiving focus. 

See demo here: https://stackblitz.com/edit/prncz5-52f7xt

I think the source element should retain the focus. Alternatively, this behaviour could be controlled by an option, similar to the `autoOptionFocus` option in `Dropdown` component.

**Comment by eneeio-nm** [comment]
An example of how another UI library does this is the [Nuxt UI dropdrown](https://ui.nuxt.com/elements/dropdown#usage) component

**Comment by ericktucto** [comment]
use .p-focus on popup
![imagen](https://github.com/primefaces/primevue/assets/22831024/8db8c809-97dc-40ca-aee7-7c529917e62f)

this class is giving the styles
![imagen](https://github.com/primefaces/primevue/assets/22831024/af6e7013-2a70-4625-b6f6-6b1f15d1fa95)

and this large class ( .p-menu .p-menuitem:not(.p-highlight):not(.p-disabled).p-focus > .p-menuitem-content  )
![imagen](https://github.com/primefaces/primevue/assets/22831024/92eca24f-d934-4cad-a28c-fd44ffcc4b81)

you modify the styles css of class, example background: transparent, first item have not styles

**Comment by J-George** [comment]
There is an option available in the MenuState called `focusedOptionIndex`, which you can set to -1 when the menu is open. That should prevent the autofocus..

**Comment by eneeio-nm** [comment]
It would be better if there was an option available, similar to the **Dropdown** `auto-option-focus`, it would make the **Menu** component more consistent with the **Dropdown** component.

**Comment by genu** [comment]
> > There is an option available in the MenuState called `focusedOptionIndex`, which you can set to -1 when the menu is open. That should prevent the autofocus..
> 
> Yep, that's what I'm doing at the moment, as a workaround:
> 
> ```
> <Menu ref="menu" :model="options" :popup="true" @focus="focussed" />
> ```
> 
> ```
> function focussed() {
>   setTimeout(function () {
>     menu.value.focusedOptionIndex = -1
>   }, 0)
> }
> ```

A better way to do this without having to rely on a time out is using `nextTick` like so:

```vue
<Menu
    ref="items"
    :model="options"
    popup
    @focus="() => nextTick(() => (items.focusedOptionIndex = -1))"
 />
```

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by SamuelWei** [comment]
I think the enhancement request can be found here: https://github.com/orgs/primefaces/discussions/503

**Comment by Themalni** [comment]
I've created a mixin for myself: 

<img width="475" alt="image" src="https://github.com/user-attachments/assets/54af7a38-1b8e-4e02-afbd-fcbbc94bd019">
<img width="594" alt="image" src="https://github.com/user-attachments/assets/5bade472-4942-475b-865b-4502231927d5">

Now I can reuse it both for Menu and for PannelMenu components.
