### ISSUE TITLE
Add left and right arrow navigation buttons to the preview mode of Image component 

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#4482]
### Describe the feature you would like to see added

I would like to see left and right arrow navigation buttons also added to the preview mode of Image component besides the existing zoom, rotate and close buttons. The navigation buttons are used to switch to the previous or next image.

Although the Galleria component has navigation buttons, it does not provide operation buttons like zoom, rotate or close.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
