### ISSUE TITLE
DataTable: Filters don't work well with ColumnGroups

### ISSUE THREAD

**Issue by Neluji** [primefaces/primevue#4486]
### Describe the bug

When using `ColumnGroup`s in a `DataTable` for the header, filters inputs don't behave well :
- If `filterDisplay` is set as `menu`, the filter element (i.e. an `InputText`, `MultiSelect` etc...) loses the focus when calling the `filterCallback`. This does not happen when not using `ColumnGroup`s.
- If `filterDisplay` is set as `row`, the filters row is not even shown, so no way to filter (as reported in #3799).

### Reproducer

https://stackblitz.com/edit/idru1f-x3bgt5

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

- When `filterDisplay` is `menu`, the filter element (i.e. an `InputText`, `MultiSelect` etc...) keeps the focus when calling the `filterCallback`.
- When `filterDisplay` is `row`, the filters row is shown.

**Comment by bouyass** [comment]
Did you figure it out ? I'm facing the same problem

**Comment by Neluji** [comment]
No, I didn't had the time to investigate on this since, and because I use `filterDisplay` with `menu` it is still usable in a sense (so I cannot put much effort in trying to fix this as it is not critical in my case)
It is however actually annoying when typing long words to filter for example, it would be great to have this fixed.

**Comment by louia** [comment]
@tugcekucukoglu any news on this issue ?

**Comment by mertsincan** [comment]
Hi all,

This feature is not currently supported by PrimeVue DataTable. Can you create a ticket for this in the [discussion](https://github.com/orgs/primefaces/discussions/categories/primevue)? We can decide whether to add it or not based on user feedback. If there are a lot of votes from users, I will open this ticket again. Thanks a lot for your understanding.

Best Regards,

**Comment by Neluji** [comment]
Hi,

> This _feature_ is not currently supported by PrimeVue DataTable.

I am not sure to understand what this means, since this issue actually sounds more like a bug rather than a missing feature: do you mean by this that _"filters with `ColumnGroup`"_ is a missing feature we need to ask for ?
 
Thanks
