### ISSUE TITLE
FileUpload: pt prop does not work while trying to customize the Badge component inside.

### ISSUE THREAD

**Issue by salemhamdani** [primefaces/primevue#4487]
### Describe the bug

While trying to  customize the badge inside the FileUpload component I found that the props that I pas through the passthrough mechanism is not working and maybe it is due to the rerender of the component after reloading a value and It is the same for the upload and cancel buttons.  

### Reproducer

https://codesandbox.io/p/sandbox/black-star-4hw52v?welcome=true

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 

### Steps to reproduce the behavior

Try to customize the text inside the badge containing pending label  when uploading a file in FileUploader. you will see in the code in codesandbox that the class wont appear on the badge element.

### Expected behavior

The acceptance of the passed through props to change the inside components.

**Comment by tugcekucukoglu** [comment]
Correct usage:

```
:pt="{ badge: { 
   root: { class: '**' }
} }"
```
