### ISSUE TITLE
Dropdown: incorrectly renders when in a modal on top of horizontally scrollable content

### ISSUE THREAD

**Issue by Kostia-K** [primefaces/primevue#4488]
### Describe the bug

When you have a Dropdown component inside a Dialog modal, it comes out on the left if the content behind the modal is horizontally scrollable. It also pushes the content behind the modal in the opposite direction. Try clicking the dropdown multiple times in the codesandbox - once it pushed the content all the way to the right, the dropdown starts working normally.

![Screenshot from 2023-09-21 19-21-58](https://github.com/primefaces/primevue/assets/22246866/a715676a-7579-464c-964b-096496997c92)

### Reproducer

https://codesandbox.io/s/async-hooks-d4h8jk

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open a dialog modal with a dropdown on top of horizontally scrollable content and click the dropdown.

### Expected behavior

The dropdown should not shift and the content behind the modal should not shift either. E.g.

![Screenshot from 2023-09-21 19-27-52](https://github.com/primefaces/primevue/assets/22246866/ad0067ba-2948-4e8a-a851-3ab8badb56af)

**Comment by injae-kim** [comment]
Fix PR: https://github.com/primefaces/primevue/pull/5758

**Comment by HardWorkerFree** [comment]
Same bug with 4.0.0+ version

https://github.com/primefaces/primevue/pull/5758#issuecomment-2363470492
