### ISSUE TITLE
Dynamic labels for Menu components

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#449]
Would be nice, if the 'label' and 'icon' would also support a function or component variable - instead of a string.
My current solution for a dynamic text is to change the text before opening the menu.
![image](https://user-images.githubusercontent.com/8471027/90729595-211adf80-e2c7-11ea-8851-d1c6bd381ee7.png)

**Comment by cagataycivici** [comment]
Thanks, will keep this to wait for more user requests to proceed.

**Comment by makurtu** [comment]
Hi @Rakasch,

Finally I solved the issue using this code:

```js
const userItems = ref([
      {
        label: "",
        disabled: true
      },
      {
        label: "Close session",
        icon: "fas fa-sign-out-alt",
        command: () => keycloak.logoutFn()
      }
    ]);


onMounted(() => {
    ...
    userItems.value[0].label = me.value.username;
    ...
});
```
I'm using Vue3, maybe you can adapt this code to Vue2.

**Comment by cagataycivici** [comment]
Thanks for sharing the solution.

**Comment by Rakasch** [comment]
well, it's the same "solution" I used, isn't it?
