### ISSUE TITLE
Virtual Scroller do not render when it is hidden when mounted

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4490]
### Describe the bug

If Virtual Scroller is hidden when mounted (for example, it is on tabview), it is not rendered properly. It is related not only to Virtual Scroller itself, but to all components, that use it under the hood

### Reproducer

https://stackblitz.com/edit/3c87fs?file=src%2FApp.vue

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open second tab in sandbox

### Expected behavior

The second tab must looks same as first one

**Comment by tugcekucukoglu** [comment]
Could you try to use `lazy` property? If the problem still persists, please create a new issue.

**Comment by liam-b** [comment]
Ok, so after banging my head against this for a while I realised @tugcekucukoglu meant setting lazy=true on the Tabs component, not the DataTable. That actually does fix it but the original issue is still present with lazy=false. I made a quick reproduction here: https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-56z3s5?file=src%2FApp.vue

**Comment by bonniegrubbs** [comment]
@liam-b Thank you this was my exact issue as well. Using `lazy=true` on the Tabs fixed it for me.
