### ISSUE TITLE
TreeTable column does not allow templating

### ISSUE THREAD

**Issue by robiharid** [primefaces/primevue#4491]
### Describe the bug

In TreeTable, using column templates does not work:
```
<Column field="action" header="Action" sortable>
            <template #body="{ data }">
                {{ data }}
                <InputSwitch v-model="data.action" />
            </template>
        </Column>
```

Switching this to DataTable and Column works.

It should work the same on both DataTable and TreeTable

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i?file=/src/App.vue

### PrimeVue version

3.30.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

above

### Expected behavior

above

**Comment by robiharid** [comment]
```
<Column>
  <template #body="slotProps" v-if="column.format">
                {{ slotProps.node.data[column.field] }}
  </template>
</Column>

This works, but slotProps.data needs to be fixed.

**Comment by tugcekucukoglu** [comment]
Thanks for the update.
