### ISSUE TITLE
Component Name: DeferredContent

### ISSUE THREAD

**Issue by nattyluke** [primefaces/primevue#4492]
### Describe the feature you would like to see added

My window is fixed. I have a subelement that scrolls (because i need a fixed bg.
So i had to copy DeferredContent into my local dev and adjust it, so that the eventlistener(scroll) will attach to my scrolling sub html element.

It would be cool to have a prop called: **attachScrollEventToId** where you can give the component the id of the element you want to attach the scroll event to.

### Is your feature request related to a problem?

Having window that does not scroll, but a sub HTML Element in which scrolling is done

### Describe the solution you'd like

Adding a new prop to be able to attach the scroll listener to another element than window

### Describe alternatives you have considered

Had to copy the component into local setup and edit it so that the event listener is attached to the right dom element

**Comment by nattyluke** [comment]
Since i have this already setup in my project i could write a pull request if you like

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
