### ISSUE TITLE
Dialog: AppendTo does not take the mask

### ISSUE THREAD

**Issue by FabienVINCENT** [primefaces/primevue#4493]
### Describe the bug

When you make a dialog modal with a append-to="body", the mask is not teleported, it is only the modal itself.

This causes the problem that the modal is not displayed correctly and the mask remains in the DOM

The modal is not clickable and is not displayed in the center but below the content.

### Reproducer

https://codesandbox.io/s/sharp-ellis-c6ml3v?file=/src/App.vue

### PrimeVue version

2.10.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Clic on the button and look to the modal

**Comment by tugcekucukoglu** [comment]
Please try to type appendTo property like this: `append-to="'body'"`. This solves the problem.

**Comment by FabienVINCENT** [comment]
this is not true : [https://codesandbox.io/p/sandbox/test-dialog-modal-23gj6h?file=/src/App.vue:14,18](https://codesandbox.io/p/sandbox/test-dialog-modal-23gj6h?file=/src/App.vue:14,18)

**Comment by FabienVINCENT** [comment]
![image](https://github.com/primefaces/primevue/assets/68119797/050911c2-ddd4-4047-846a-6f56f1faa5bd)
This is not true, this doesn't solves the problem, its make like there is no append-to prop
