### ISSUE TITLE
Datatable, in rowedit mode + row filtering enabled, clicking roweditor link opens all rows for editing, not just the chosen one

### ISSUE THREAD

**Issue by farkinca1971** [primefaces/primevue#4495]
### Describe the bug

Hello

Clicking roweditor link opens all rows for editing, not just the chosen one. See screenshot

Config for the datatable

                <DataTable
                    :value="persons"
                    v-model:filters="filtersPerson"
                    :filters="filtersPerson"
                    tableStyle="min-width: 25rem"
                    stripedRows
                    :paginator="true"
                    class="p-datatable-gridlines"
                    :rows="10"
                    dataKey="uiid"
                    filterDisplay="menu"
                    :loading="loadingPerson"
                    :globalFilterFields="['nameFirst', 'nameMiddle', 'nameLast', 'motherName', 'pod', 'dob']"
                    selectionMode="single"
                    @row-select="getPersonData"
                    v-model:editingRows="editingRows"
                    editMode="row"
                    @row-edit-save="onRowEditSave"
                    tableClass="editable-cells-table"
                >

The column where I inserted the editor

                    <Column field="nameFirst" header="First Name" sortable selectionMode="single">
                        <template #editor="{ data, field }">
                            <InputText v-model="data[field]" />
                        </template>
                        <template #body="{ data }">
                            {{ data.nameFirst }}
                        </template>
                        <template #filter="{ filterModel }">
                            <InputText type="text" v-model="filterModel.value" class="p-column-filter" placeholder="Search by first name" />
                        </template>
                    </Column>

And at the end the roweditor column

                    <Column :rowEditor="true" style="width: 10%; min-width: 8rem" bodyStyle="text-align:center"></Column>

Clicking on the first row to edit, will produce the following state
![tempsnip](https://github.com/primefaces/primevue/assets/49434212/699a39a1-b158-458c-886c-ccf20738581b)

Can You help me please?
Thanks a lot,

Br,

Zoltán

### Reproducer

Nope

### PrimeVue version

3.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Only one row should be in editing mode

**Comment by tugcekucukoglu** [comment]
As you have said roweditor opens all cells, but cell editing mode opens just one cell to edit. You may consider to use this.
