### ISSUE TITLE
usePassThrough support for Bootstrap

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#4496]
### Describe the feature you would like to see added

I would like to be able to build upon the base Bootstrap Theme supplied by PrimeVue using bootstrap 5 utility classes in a similar fashion to the Tailwind usePassThrough theme so that I don't have to manually assign everything in a custom pass through.

To my knowledge, the only way to do this is either to create a global custom passthrough and setting unstyled to true, use passthroughs on each component or to download the css files for the theme and store/maintain them locally.

### Describe the solution you'd like

To be able to build upon the base Bootstrap Theme supplied by PrimeVue using boostrap 5 utility classes in a similar fashion to the Tailwind usePassThrough theme

**Comment by JakeMinor** [comment]
I found a viable solution to the problem outlined above, closing the issue.

**Comment by jesusvpct** [comment]
Can you have any steps to do it? I want to use it too. Thanks.

**Comment by xkiller838** [comment]
Hello, I'm interested in knowing what solution you gave to the problem you raise, thank you very much.

**Comment by karlskidmore** [comment]
@JakeMinor Please share details on your viable solution 🙏
