### ISSUE TITLE
SelectButton : max item select

### ISSUE THREAD

**Issue by breizhwave** [primefaces/primevue#4497]
### Describe the feature you would like to see added

allow disable of option when more than x options have been selected on selectbutton multiple

### Describe the solution you'd like

working on event , getting near but can't find out how to related selected options and disable remaining options : 
`
var optWalls = ref([
  { name: 'West', value: 'o' },
  { name: 'North', value: 'n' },
  { name: 'East', value: 'e' },
  { name: 'South', value: 's' },

])
function checkDisabled( )
{
   
     if(walls.length==3)
for (var opt in unref(walls))
    {
      console.log(unref(opt))
    }

}
  <SelectButton v-model="walls" :options="optWalls" multiple optionLabel="name" @change="checkDisabled"  optionDisabled="constant"   />
`

**Comment by breizhwave** [comment]
Ok found a quick hack , example here witgh max 3 selection on a multiple select button: 
`
function checkDisabled( e )
{
  unref(optWalls).forEach(function (opt)
  {
    if (walls.length==3) opt.constant=true; else opt.constant=false;
  walls.forEach(function (opt2){ if (opt2.value==opt.value) opt.constant=false})
  })
}
`

**Comment by tugcekucukoglu** [comment]
Thanks for the update. We think this can be done dynamically with the change event.
