### ISSUE TITLE
MultiSelect.vue: error on onToggleAll and bad default placeholder

### ISSUE THREAD

**Issue by jonasraoni** [primefaces/primevue#45]
When triggering the onToggleAll, the function isn't applying the `getOptionValue` to the items, which cause different outcomes than when selecting all by hand.
Also, when there's no placeholder it defaults to `p-multiselect`.

**Comment by Merve7** [comment]
Thank you for your pull request. We have another solution. You can check after release. If the problem still persists please let me know again.
