### ISSUE TITLE
MultiSelect: add toggle all label

### ISSUE THREAD

**Issue by karlfock** [primefaces/primevue#4501]
### Describe the feature you would like to see added

A toggle all label that will be to the right of the checkbox that can select all or unselect all values

### Is your feature request related to a problem?

It will make it easier to have this property instead of having to override the slot which is the way it has to be done currently. 

### Describe the solution you'd like

Currently this is the way I do it:

```
<template #headercheckboxicon="{ allSelected }">
                  <CheckIcon
                    v-show="allSelected"
                    class="p-checkbox-icon"
                    data-pc-section="headercheckboxicon" />
                  <span class="select-all-columns">Select all</span>
                </template>
```

Instead we can just have a prop that is added like this:

```
<MultiSelect toggle-all-label="Select all" .../>
```
### Describe alternatives you have considered

As above, the slot solution is ok, but requires some work.

**Comment by EmreAka** [comment]
Thanks for the trick :) @karlfock
