### ISSUE TITLE
V-Tooltip, TailwindCSS: Styling not working when using pinia store

### ISSUE THREAD

**Issue by Nils3311** [primefaces/primevue#4505]
### Describe the bug

When Pinia Store is used in the same component with ﻿v-tooltip and the new Tailwind Pass-Through-Styling the ﻿v-tooltip styling appears to be lost or not applied.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-qmh8ef?file=src%2FApp.vue

### PrimeVue version

3.3.4

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the provided stackblitz url
2. Hover over the "Hover me" Text -> the styling of the v-tooltip is not working.
3. Delete the pinia store from the script 
`import { useTestStore } from './store/teststore.js';
const testStore = useTestStore();`
4. Hover again over the "Hover me" Text -> the styling is now working

### Expected behavior

The ﻿v-tooltip should retain its styling as specified by Tailwind CSS even when a Pinia Store is utilized within the same component.

**Comment by mertsincan** [comment]
Fixed for the next version. But, please update your pt preset for Tooltip;
```
:pt={
   ...
   directives: {
       tooltip: {
             ...
       }
      // other directives
   }
   // components
}
```
