### ISSUE TITLE
Dropdown: Editable dropdown doesn't open when typing on a mobile device

### ISSUE THREAD

**Issue by onursazak** [primefaces/primevue#4509]
### Describe the bug

Editable dropdown is not be opened when typing on input on a mobile device.
I tried both Samsung Keyboard and Gboard. The result is the same.

If it is the expected behavior, what should I do to show dropdown options when typing on input?

https://github.com/primefaces/primevue/assets/6557458/996f7044-6ca7-40a8-b647-2aa1b9a8788a

### Reproducer

https://codesandbox.io/s/objective-margulis-wmlzdr?file=/src/App.vue

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome, Samsung Browser

### Steps to reproduce the behavior

1.Focus editable dropdown
2.Try typing something that is among options.

### Expected behavior

I expect dropdown options to be opened when typing as it works in desktop.

**Comment by erhansaydam** [comment]
We are also affected highly from this bug. Our web application is to be used by hundred thousands of people.

We are urgently waiting this problem to be solved.

Thanks, regards.
