### ISSUE TITLE
Splitter: blocked by content

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4513]
### Describe the bug

If the Splitterpanel contains anything with a fixed size, like Buttons, Images, anything besides text,
this content blocks the dragging. You can't drag the panel smaller than its content.

### Reproducer

https://stackblitz.com/edit/x2uuev?file=src%2FApp.vue

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to reproducer.
Try to drag the first panel fully to one side. 

### Expected behavior

Should be able to drag the splitter fully to one side, as shown as in the second panel.

**Comment by jozefnad** [comment]
Did you tried just add styles for your SplitterPanel, such as flex, overflow etc?

**Comment by Rakasch** [comment]
@jozefnad 
Of course I can fix it by setting styles myself, what I did in the stackblitz fixed example.
I would expect a component to work out of the box. As it is now, it's just broken if you dont fix it yourself.

**Comment by Rakasch** [comment]
What sense does it make if I can only move the whitespace?
