### ISSUE TITLE
TreeTable sorticon slot is not working

### ISSUE THREAD

**Issue by nneekkiitt** [primefaces/primevue#4515]
### Describe the bug

TreeTable sorticon slot is not working

### Reproducer

https://stackblitz.com/edit/eknkuw?file=src%2FApp.vue

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Open sandbox and notice that default sort icon is not changed

### Expected behavior

Custom sort icons

**Comment by tugcekucukoglu** [comment]
TreeTable has not but Column component has `sorticon` template.

```
<Column>
  <template #sorticon>
        <span class="pi pi-caret-down"></span>
      </template>
</Column>
```

Documentation will be fixed also. Thanks!
