### ISSUE TITLE
Button: pass through CodeSandbox example is broken

### ISSUE THREAD

**Issue by miketests** [primefaces/primevue#4518]
### Describe the bug

Docs are outdated: https://primevue.org/button/#icononly
CodeSandbox just doesn't work:

![image](https://github.com/primefaces/primevue/assets/131380665/bac4bde3-047c-4152-bebf-14c31e9ef725)
![image](https://github.com/primefaces/primevue/assets/131380665/dcae1f85-a457-49ba-b19e-93a0db71cd17)

### Reproducer

https://codesandbox.io/s/zwz34z

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

Go to the link

### Expected behavior

Working example

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue:

<img width="1783" alt="Screenshot 2023-09-29 at 09 17 02" src="https://github.com/primefaces/primevue/assets/32294991/96595a3a-19d7-45a5-96e8-350b322afccf">

<img width="1786" alt="Screenshot 2023-09-29 at 09 17 24" src="https://github.com/primefaces/primevue/assets/32294991/08b3b3e3-f5f4-4cdd-8bbc-5c5029544e58">
