### ISSUE TITLE
[Editor] Lara Styling Issue

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue#4521]
![image](https://github.com/primefaces/primevue/assets/28745098/c3b93c44-ddc9-4a87-ad80-e9944b04cd74)
![image](https://github.com/primefaces/primevue/assets/28745098/8b3dd102-c23a-4fe7-b7f3-c1f2c0e65c5e)

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primevue/issues/4576
