### ISSUE TITLE
InputGroup with Tailwind: Issue Title

### ISSUE THREAD

**Issue by aeruggiero** [primefaces/primevue#4527]
Hi everyone,
I'm using PrimeVue with Tailwind, everything seems to be working fine, except these input groups

It seems like Tailwind is resetting the border-radius.
```
<div class="p-inputgroup">
    <span class="p-inputgroup-addon">
       €
    </span>
    <InputNumber
        v-model="product.pivot!.price_sold"
        :minFractionDigits="2"
        :maxFractionDigits="2"
        :key="'in' + product.pivot!.id"
    />
</div>
```

![image](https://github.com/primefaces/primevue/assets/68345097/fe7922c1-3bb7-4484-adf2-a4e9b9b3806a)

```
<InputNumber
    :pt="{
        input: { class: 'w-14' },
    }"
    v-model="product.pivot!.quantity"
    inputId="stacked-buttons"
    showButtons
/>
```
![image](https://github.com/primefaces/primevue/assets/68345097/92aa16b8-0c3c-49b2-8e08-3ad4ef5e29f3)

app.ts
```
const app = createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue, Ziggy)
            .use(PrimeVue, { pt: Tailwind });
```

tailwind.config.js
```
/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}",
    ],
    darkMode: "media", // or 'media' or 'class'

    plugins: [],
};
```

Any idea?
Thanks!

### Reproducer

//

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
I'm currently working on new InputGroup and InputGroupAddon components. Implementation will become easier with the `pt` property.

**Comment by onekiloparsec** [comment]
I don't want to re-open the issue, but just for the record, it seems v `3.35` introduced a regression UI/glitch with stacked buttons. It is still present in the latest version. Here are two screenshots (`3.34.1` and `3.35.0`)
![Screenshot 2023-11-04 at 11 57 06](https://github.com/primefaces/primevue/assets/226224/024b638f-c598-456e-8698-04e526374945)
![Screenshot 2023-11-04 at 13 01 55](https://github.com/primefaces/primevue/assets/226224/2d2c45e2-0bb9-4056-9070-cf7f0c6b31d9)
