### ISSUE TITLE
Error: Could not parse CSS stylesheet at exports.createStylesheet

### ISSUE THREAD

**Issue by felixzapata** [primefaces/primevue#4531]
### Describe the bug

Updating _primevue_ from 3.34.1 to 3.35.0 throws errors launching the tests and rendering the components.

It is especially ugly for example the input switches.

#### Old version

<img width="223" alt="Captura de pantalla 2023-10-02 a las 15 25 56 (2)" src="https://github.com/primefaces/primevue/assets/997038/62e082e0-f9d0-4204-9a50-52957079c475">

<img width="213" alt="Captura de pantalla 2023-10-02 a las 15 27 03 (2)" src="https://github.com/primefaces/primevue/assets/997038/da2df09b-ebb5-42d2-bb9a-ed3d6126c402">

#### New version

<img width="270" alt="Captura de pantalla 2023-10-02 a las 15 20 53 (2)" src="https://github.com/primefaces/primevue/assets/997038/ecacdfea-4935-4325-af1a-89bc583f8579">

<img width="115" alt="Captura de pantalla 2023-10-02 a las 15 14 39 (2)" src="https://github.com/primefaces/primevue/assets/997038/5be6601d-6ced-489a-85b1-2bff5a67c204">

### Reproducer

no one

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

No parsing errors launching the tests with Vite.

**Comment by tugcekucukoglu** [comment]
PrimeVue switched to the CSS layer configuration. This may require some changes. For better explanation https://www.youtube.com/watch?v=EPRUy0lvgBA&t=305s&ab_channel=CagatayCivici
