### ISSUE TITLE
InputText: Float labels bug out when page loads with form auto-filled (webkit)

### ISSUE THREAD

**Issue by RickKukiela** [primefaces/primevue#4533]
### Describe the bug

I found this issue was already fixed in the `primeng` fork back in 2018 but the fix was never applied to the `primevue` fork: https://github.com/primefaces/primeng/pull/5473/commits/d2abf21fb9c63862f28b67ce581274464c01986d

I have created a PR that implements the same fix here. It should be an easy merge.

(Note the reproducer link is nothing, just put something since it's required entry and this issue does not require a reproduction IMO as its clearly documented as an issue on the `primeng` fork. If you need to reproduce it all you need to do is create a login form with float style InputText component labels and then load the page in chrome with autofill enabled with data for the given site so the login form is autofilled on page load).

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome / webkit

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4534
