### ISSUE TITLE
DataTable: filterDisplay="menu" filtering throws an error

### ISSUE THREAD

**Issue by jovicanorthriver** [primefaces/primevue#4538]
### Describe the bug

When you want to change the type of the filter, it throws an error and the filters no longer work

![chrome_rdtkqbIQn0](https://github.com/primefaces/primevue/assets/126563023/e442da0e-0fb4-4097-ac5e-16d7f934e44e)

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-hzkqnp

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

- Click on any table column filter icon
- Click on select to change type (ex. Starts With)
- Click on any type (ex. Contains)
- See error in console

![chrome_rdtkqbIQn0](https://github.com/primefaces/primevue/assets/126563023/d0dfe25c-e489-454c-8c73-a6ad422500c1)

### Expected behavior

Filters should fire an event and change the data in the table

**Comment by colinatwork** [comment]
I think I may be seeing a version of this issue as well. When clicking on the filter icon, the first time it throws an error and won't open. The second time you click it does open.
![Screenshot 2023-10-10 at 8 03 09 PM](https://github.com/primefaces/primevue/assets/106704020/2be02128-276d-42ff-be85-d4221addf008)

**Comment by rossvasquez** [comment]
So we're required to use a filterOperator?

**Comment by koolio29** [comment]
@kiasyn I think you could use `filterMatchModeOptions` for the `Column` component if you want to restrict a given column for a single filter.

You could probably have something like this in your template:
```vue
            <Column
              field="username"
              header="Username"
              :filter-match-mode-options="[{label: 'Equal', value: equalsFilter}]"
            >
              <template #filter="{ filterModel }">
                <Dropdown
                  v-model="filterModel.value"
                  :options="users"
                  option-label="name"
                  optionValue="name"
                  placeholder="Select One"
                  class="p-column-filter"
                  showClear
                />
              </template>
            </Column>
```

Have the following in the script:

```javascript
const filters = ref({
  global: {value: null, matchMode: FilterMatchMode.CONTAINS},
  username: {value: null, matchMode: FilterMatchMode.EQUALS},
});

// This filter matching mode allows us to restrict matching mode for a given column
const equalsFilter = ref(FilterMatchMode.EQUALS);
```

[Full Example](https://codesandbox.io/s/tender-benji-ltt8ix?file=/src/FilterServiceDemo.vue:1085-1107) as mentioned in [here](https://github.com/primefaces/primevue/issues/3536#issuecomment-1383586476)
