### ISSUE TITLE
InputNumber: insert behavior defects

### ISSUE THREAD

**Issue by dimitriadisg** [primefaces/primevue#4539]
### Describe the bug

The InputNumber component **when combined with a suffix** doesn't handle the input correctly when typing after a leading `0`.
As seen in the video below, I am typing the following sequences:

`123456` - First attempt, all works good
`0123456` - Second attempt, the input gets deleted after I type `2`.
[Screencast from 2023-10-03 04:57:35 PM.webm](https://github.com/primefaces/primevue/assets/14919500/4f834072-43b7-4caf-8570-7461e09b5d5e)

This happens with any number combinations after typing the second digit after the leading `0`.
The bug happens with all scenarios when you type after 0, it doesn't matter if done in one streak or if you blur and  focus the element again. If you put the cursor before the `0` the input is entered correctly, but if you start typing after a leading `0`, the input gets nullified after the second number hit. Also happens if you type `00000000000....` into the input, every second `0` typed the input will be turned null. Possible related to https://github.com/primefaces/primevue/issues/3964
Earliest version this was introduced is `3.30.0` and it is still there in the newest version.

### Reproducer

https://primevue.org/inputnumber/#prefixsuffix

### PrimeVue version

3.30.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox 118.0.1 (64-bit) on Ubuntu

### Steps to reproduce the behavior

1. Go to https://primevue.org/inputnumber/#prefixsuffix
2. Find the input field labeled as `Expiry`
3. Delete the content of the input and type `012345`
4. See the input now has value `345` instead of what you typed

### Expected behavior

On step 4 from above, the input should have the value `12345`

**Comment by dimitriadisg** [comment]
Hey @mertsincan I can still see this bug in 3.52.0, check this:
[Screencast from 2024-05-20 04:03:02 PM.webm](https://github.com/primefaces/primevue/assets/14919500/b9b17469-b661-4237-b387-c5a6e633c9ea)

**Comment by KingKoxy** [comment]
Hey the bug seems to still exist in version 4.2.4 and can also still be reproduced by the steps provided by the original post.

**Comment by dimitriadisg** [comment]
@tugcekucukoglu What do we do with this as the bug is still present, shall we re-open this issue?

**Comment by dimitriadisg** [comment]
Hey @tugcekucukoglu this bug is still present in latest Primevue, please don't ignore it
