### ISSUE TITLE
Tabview: broken UI for dark themes using tailwind passthrough

### ISSUE THREAD

**Issue by MatanelGordon** [primefaces/primevue#4540]
### Describe the bug

Hy, Tabview component has bright background and weird bottom border radius. I'm using the new tailwind passthrough.

<img width="814" alt="image" src="https://github.com/primefaces/primevue/assets/72258277/fc6715ba-d88e-4034-a4ab-7ef369c78fd9">

My temporary solution was to disable `pt` for this  component:

```typescript
nuxtApp.vueApp.use(PrimeVue, {
	ripple: true,
	pt: {
		...Tailwind,
		tabview: {},
	},
});

```

Also, I synced tailwind's color pallate with primevue's (see `tailwindcss.config.js` ), I don't know why it's not happening by default.

P.S. it was a nightmare configuring tailwindcss into this sendbox fork so feel free to fork mine for future tailwind bugs 😄 

### Reproducer

https://codesandbox.io/p/sandbox/tabview-bug-primevue-5zppxk?file=%2Fpackage.json%3A13%2C18

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

chrome 117

**Comment by mertsincan** [comment]
Thanks a lot for the report! @atakantepe could you please check it?

**Comment by atakantepe** [comment]
Hi, the issue in your example is that you are using PrimeVue Styled classes and Unstyled. The Tailwind, as you know, is not "!important" by default.

I belive you need add unstyled: true  ==>  app.use(PrimeVue, { ripple: true,unstyled: true, pt: Tailwind });

This way, you'll get only the Tailwind theme and what you have as custom classes.

For colors, we are currently working on a new Tailwind Preset, which will have primary colors and surface colors for easy customization. We will be relating with the new tailwind.primevue.org website.
