### ISSUE TITLE
Button: Tailwind Passthrough collides with primevue themes

### ISSUE THREAD

**Issue by MatanelGordon** [primefaces/primevue#4541]
### Describe the bug

Hy, I'm using `tailwindcss` but i see it overrides primevue themes and not in a good way. 

Without Hover (using **arya-purple!** YES, PURPLE!)
<img width="407" alt="image" src="https://github.com/primefaces/primevue/assets/72258277/ff22fa0e-b79a-4ac9-9797-0b64b7beb08e">

With Hover:
<img width="477" alt="image" src="https://github.com/primefaces/primevue/assets/72258277/4967e0a0-3d78-4df2-bb43-9e17b4988e92">

Now the hover color is the right `arya-prurple's` primary color. 

I found this out while creating a general purpose repro for the new Tailwindcss passthrough.

Link for the general repro: [Primevue-tailwind-repro](https://codesandbox.io/p/sandbox/tabview-bug-primevue-forked-dlcnx4?file=%2Ftailwind.config.js%3A6%2C12
)

### Reproducer

https://codesandbox.io/p/sandbox/tabview-bug-primevue-forked-dlcnx4?file=%2Ftailwind.config.js%3A6%2C12

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome latest

### Steps to reproduce the behavior

- apply the tailwind passthrough
- apply a primevue theme
- create a button

### Expected behavior

tailwind should use the chosen theme's color pallete, be more generic.

**Comment by tugcekucukoglu** [comment]
Team currently working on that. [Tailwind showcase](https://tailwind.primevue.org/) will be updated soon.

Thank you!

**Comment by valh1996** [comment]
> Team currently working on that. [Tailwind showcase](https://tailwind.primevue.org/) will be updated soon.
> 
> Thank you!

Do you have a release date pls?
