### ISSUE TITLE
MenuBar: Whole bar grows when clicking on menu dropdown in 3.35.0

### ISSUE THREAD

**Issue by BITSOLVER** [primefaces/primevue#4547]
### Describe the bug

When upgrading from PrimeVue 3.34.1 to 3.35.0 the MenuBar functionality is broken, when you click on a menu to expand the whole container div increases in size.  See attached image.
<img width="689" alt="Screenshot 2023-10-04 at 11 32 44" src="https://github.com/primefaces/primevue/assets/15092505/4cf0ab3a-1775-4563-ac50-571dd73f32a2">

I've created a simple sandbox but there is a config error as it's the first time I've tried to create a sandbox.

### Reproducer

https://codesandbox.io/p/sandbox/sparkling-hooks-r2fv6q

Update sandbox link 15th Oct 2023

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome Version 117.0.5938.132 (Official Build) (64-bit)

### Steps to reproduce the behavior

Click parent menu to expand children.

### Expected behavior

MenuBar height does not change.

**Comment by tugcekucukoglu** [comment]
Reproducer link can not show the issue. Could you update the link?

**Comment by BITSOLVER** [comment]
@tugcekucukoglu I've updated the link with the issue.  I think I may need to remove a lot of the content in src/assets/base.css as CSS is handled differently from 3.35.0+?

**Comment by tugcekucukoglu** [comment]
Yes, it seems there are some styles that broke the components. For example

```
*,
*::before,
*::after {
  position: relative;
}
```
