### ISSUE TITLE
Buttonset: styling issues around singular Button or SplitButton

### ISSUE THREAD

**Issue by Coretteket** [primefaces/primevue#4548]
### Describe the bug

The [buttonset class](https://primevue.org/button/#buttonset) can be used to visually group multiple buttons together. This handles the rounding of corners of the buttons inside the div with this class. However, there are some issues with the styling as it is currently.
1. If there is one button inside of a buttonset, all corners become unrounded. (This is relevant in our app because depending on state there may be one or two buttons inside of the buttonset div.)
2. If there is a button next to a SplitButton component, the first button still is fully unrounded, and the SplitButton fully rounded, therefore not visually grouping the two.

### Reproducer

https://codesandbox.io/p/sandbox/nice-swirles-5jpmcr

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Only the left corners of the left-most button (regardless of type or number of buttons) should be rounded, and only the right corners of the right-most button should be rounded.

**Comment by SelenKockar** [comment]
Hi, the link you posted works correctly in my locale. I tried to reproduce your issue both in the current version and in the version of Primevue you are using, but I could not reproduce your issue. Any chance of reproducing the issue?

**Comment by tugcekucukoglu** [comment]
It seems the same issue was fixed for version 3.35.0 

https://github.com/primefaces/primevue/issues/4467
