### ISSUE TITLE
InputNumber with dynamic fraction digits doesn't work as expected

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#455]
Since the upgrade to 2.0.8 I can no longer enter decimal places.
It always stays at xx,00.
The zeros cannot be overwritten.
If you delete a 0, it will be autocompleted again immediately.
Maybe #432 has broken something here.

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate this issue in https://primefaces.org/primevue/showcase/#/inputnumber
What steps should I follow to replicate it?

**Comment by Rakasch** [comment]
The reason in my example is that the value for minFractionDigits and maxFractionDigits can change here.
If the value of fraction_digits is first set to 0 and later changed to 2, you can see the decimal places in the NumberInput field, but you cannot write them.

[numberinput_fractiondigits_example.txt](https://github.com/primefaces/primevue/files/5143165/numberinput_fractiondigits_example.txt)

**Comment by mertsincan** [comment]
Thanks a lot for the sample code! Fixed now.

Best Regards,

**Comment by abhijeetj100** [comment]
Hey guys, newbie here!
So following the docs I got primevue v2.0.0, which now I am realizing is too old. To overcome this issue, I need to update to 2.0.9 ?

CC: @mertsincan 

Thanks,
Abhijeet
