### ISSUE TITLE
DataTable&VirtualScroll: Bind virtual scroll to window

### ISSUE THREAD

**Issue by lakkvak** [primefaces/primevue#4557]
### Describe the bug

Can I somehow make a virtual scroll work with the event of scrolling the whole page? I want the scroll itself to refer not to the table, but to the whole document, and at the same time the elements in the table scroll and interact properly. 

I have made a draft version.  But when you resize the document, all elements in dom are loaded at once 
And on the whole, so far, such a decision looks questionable. Are there any ways to implement something like this?

### Reproducer

https://stackblitz.com/edit/ggnong-8dchrp?file=src%2FApp.vue

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi,

I think you can use DeferredContent component; https://primevue.org/deferredcontent/

Best Regards,
