### ISSUE TITLE
InputNumber: Buttons are not sorted correctly in TW theme if buttonLayout is horizontal

### ISSUE THREAD

**Issue by opc-norriq** [primefaces/primevue#4560]
### Describe the bug

Right now buttons are always placed on the right side of the input.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-fdyqlb?file=src%2FApp.vue

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by opc-norriq** [comment]
PR here: #4520

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4520
