### ISSUE TITLE
Toast: Message prop is missing from ToastProps type

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#4568]
### Describe the bug

When creating a custom Passthrough object to use when setting PrimeVue to use the unstyled mode, the Message props is missing from the ToastProps type. 

The message object contains the severity property which can be used for dynamic styling and is used in the premade Tailwind Passthrough object which comes as apart of PrimeVue.

Below I have attached some images to explain the issue further.

![rider64_TJdvzrj8og](https://github.com/primefaces/primevue/assets/49190778/cdb3ba96-9269-4463-8d14-4503e12f6318)
![rider64_r8TwUYR9Va](https://github.com/primefaces/primevue/assets/49190778/f3068f34-b209-4a52-81ca-62f73c3f7632)
![chrome_Iv8xFW55L6](https://github.com/primefaces/primevue/assets/49190778/d8f70cc3-dacd-490d-b840-e8bc3857e146)

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a custom passthrough object
2. Add the toast property
3. Add any of the passthrough options
4. Attempt to access message using the following object `options.props.message.severity`

### Expected behavior

I expect to not receive a type error when trying to dynamically change styling based on the severity of a toast.

**Comment by JakeMinor** [comment]
I am more than happy to create a PR to solve this issue if required!

**Comment by FlipWarthog** [comment]
@JakeMinor If you can work out a PR, go for it. They're always appreciated. 🙏

**Comment by JakeMinor** [comment]
Just finished up the PR @FlipWarthog if you have a chance to take a look :)

**Comment by FlipWarthog** [comment]
@JakeMinor Looks good to me, will need final approval from PrimeTek to merge it in. Thanks!
