### ISSUE TITLE
Toast: severity="warn"

### ISSUE THREAD

**Issue by mozart77** [primefaces/primevue#4571]
### Describe the bug

Hi. I believe that severity for Toast component should be "warning" (just like for Button and others) not "warn". Also "error" should be "danger".

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
