### ISSUE TITLE
@layer backward compatibility

### ISSUE THREAD

**Issue by cnSchwarzer** [primefaces/primevue#4573]
### Describe the feature you would like to see added

@layer is introduced in Chrome 99+, old devices is missing all styles. Could you add some backward implementation nicely because the effect seems changed a lot bewteen 3.34.1 vs 3.35.0. Many users still use old version of chrome, and the @layer completely broke the style

### Is your feature request related to a problem?

#4529 

### Describe the solution you'd like

Add @support when the browser doesn't have @layer

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
