### ISSUE TITLE
OrderList: Missing moveUpButtonProps

### ISSUE THREAD

**Issue by rory-instil** [primefaces/primevue#4581]
### Describe the bug

According to the documentation there is a a `moveTopButtonProps` on the `OrderList` component: https://primevue.org/orderlist/#api.orderlist.props.moveTopButtonProps
On attempting to use this component however it does not work.

On looking at the source it appears that this was present before but was refactored out accidentally afterwards (with the other three buttons `moveUpButtonProps`, `moveDownButtonProps`, and `moveBottomButtonProps` remaining as expected): https://github.com/primefaces/primevue/blob/master/components/lib/orderlist/OrderList.vue#L5-L32

In the reproduction you can see how 3 out of the 4 buttons are disabled with the props unable to be applied to the Move Top button

### Reproducer

https://codesandbox.io/s/nifty-forest-nyxwyw

### PrimeVue version

3.32.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Try to use `:move-top-button-props="{ disabled: false }"` and see that button is still disabled / property is not available

### Expected behavior

- Apply `:move-top-button-props="{ disabled: false }"` to `OrderList`
- Move top button is enabled by default

**Comment by FlipWarthog** [comment]
@rory-instil This issue still has the default name. Should be renamed something like "OrderList: Missing moveUpButtonProps"

**Comment by rory-instil** [comment]
> @rory-instil This issue still has the default name. Should be renamed something like "OrderList: Missing moveUpButtonProps"

Yup! Sorry about that.
