### ISSUE TITLE
Typo: 'kepap' used instead of 'kebab'

### ISSUE THREAD

**Issue by robokozo** [primefaces/primevue#4594]
### Describe the bug

Typo: 'kepap' used instead of 'kebab'

For example: 

```
let kebapProp = prop.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
```

### Reproducer

https://codesandbox.io/s/primevue-create-vue-issue-template-kw9g6i

### PrimeVue version

3.36

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4593
