### ISSUE TITLE
Button slots for icon and loadingicon do not work and render as "icon only"

### ISSUE THREAD

**Issue by LanFeusT23** [primefaces/primevue#4595]
### Describe the bug

Using slots for `icon` and `loadingicon` does not work.

The default slot works correctly.

I believe the issues steps from the `Button.vue` component which has a default slot wrapping all other slots
```
    <button v-ripple :class="cx('root')" type="button" :aria-label="defaultAriaLabel" :disabled="disabled" v-bind="getPTOptions('root')" data-pc-name="button" :data-pc-severity="severity">
        <slot>
            <slot v-if="loading" name="loadingicon" :class="[cx('loadingIcon'), cx('icon')]">
                <span v-if="loadingIcon" :class="[cx('loadingIcon'), cx('icon'), loadingIcon]" v-bind="ptm('loadingIcon')" />
                <SpinnerIcon v-else :class="[cx('loadingIcon'), cx('icon')]" spin v-bind="ptm('loadingIcon')" />
            </slot>
            <slot v-else name="icon" :class="[cx('icon')]">
                <span v-if="icon" :class="[cx('icon'), icon, iconClass]" v-bind="ptm('icon')"></span>
            </slot>
            <span :class="cx('label')" v-bind="ptm('label')">{{ label || '&nbsp;' }}</span>
            <Badge v-if="badge" :value="badge" :class="badgeClass" :unstyled="unstyled" v-bind="ptm('badge')"></Badge>
        </slot>
    </button>
```

However unless you pass the prop `label="whatever"` it will not render the button will render in "icon only" mode because the ButtonStyle.js has logic that only checks for the `label` prop, and not the default slot:
`'p-button-icon-only': instance.hasIcon && !props.label && !props.badge`

### Reproducer

https://stackblitz.com/edit/d49ruh?file=src%2FApp.vue

### PrimeVue version

3.35

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

All

### Steps to reproduce the behavior

1. Create a Button using the primevue/button component
2. Do not use label and icon prop, instead use the default and icon slots
=> the default slot renders but the icon is rendered in "icon only" mode and does not render the icon

### Expected behavior

The slots should be rendered if passed in properly

**Comment by LanFeusT23** [comment]
Ok as expected I have issues with the tests, I was barely able to run them locally to begin with - but it seems the PR is running into problems as well I'm honestly not sure how to fix

**Comment by tugcekucukoglu** [comment]
If you want to use the default slot, you must do all the other icon, loadingicon and label adding operations yourself.

**Comment by LanFeusT23** [comment]
I want to use all 3 slots. I don't see why the `default` slot should override the ability to use other slots Oo

**Comment by arlai-mk** [comment]
> If you want to use the default slot, you must do all the other icon, loadingicon and label adding operations yourself.

I believe you may have misunderstood the issue? 6 months later it's still not fixed. As soon as we use the default slot, we cannot use other slots together with it. It's quite annoying.

Thank you.
