### ISSUE TITLE
Tailwind: typos in passthrough/tailwind

### ISSUE THREAD

**Issue by canstand** [primefaces/primevue#4617]
### Describe the bug

For example:
- `text-overflow-ellipsis` or `overflow-ellipsis` should be `text-ellipsis`  (https://tailwindcss.com/docs/upgrade-guide#overflow-clip-ellipsis)
- `bg-transprent` should be `bg-transparent`
- `user-none` should be `select-none`   (https://tailwindcss.com/docs/user-select#class-reference)

etc.

### Reproducer

no

### PrimeVue version

3.36.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi @canstand,

So sorry for the typos! Could you please send a PR for us? we would be grateful for it. Thanks a lot!

**Comment by canstand** [comment]
Hi @mertsincan, #4618 for this needs review.

**Comment by mertsincan** [comment]
Thanks @canstand, we'll review it.
