### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by jhasuev** [primefaces/primevue#4619]
### Describe the bug

When I use Calendar in my project, I got an error:

![image](https://github.com/primefaces/primevue/assets/26802815/88dcb2c5-ff1d-47f8-b6ac-d8c81acaa07c)

In view it shows only like a text field and just on focus on it I the that errors in consoles.

"primevue": "^3.29.0",

code:
`<script setup lang="ts">
import { ref } from 'vue'
import Calendar from 'primevue/calendar'
const date = ref()

</script>

<template>
  <div>
    <Calendar v-model="date" />
  </div>
</template>
`

### Reproducer

s

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Could you send us a reproducer link?
