### ISSUE TITLE
DataTable: stripedRows option has no effect

### ISSUE THREAD

**Issue by mrichar1** [primefaces/primevue#4626]
### Describe the bug

Setting `stripedRows` on `DataTable`  doesn't display striped rows.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-g96yhp

### PrimeVue version

3.36.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Setting `stripedRows` property has no effect on the table's style.

This can also be seen in the official PrimeVue docs:

https://primevue.org/datatable/#striped

### Expected behavior

Rows should be striped.

**Comment by cagataycivici** [comment]
The functionality is there, the color is not super visible on Lara light.
