### ISSUE TITLE
Size: Table disappear when select size

### ISSUE THREAD

**Issue by brunogroth** [primefaces/primevue#4627]
### Describe the bug

When clicking on the same table size already selected, the table disappears.
It happens at TreeTableDoc and at DataTableDoc

Production error: https://primevue.org/treetable/#size

Repo Files:
https://github.com/primefaces/primevue/blob/master/doc/treetable/SizeDoc.vue
https://github.com/primefaces/primevue/blob/master/doc/datatable/SizeDoc.vue

Exception: 
TypeError: Cannot read properties of null (reading 'class')
    at Proxy.Ae (index.546573f1.js:891:626)
    at $o (entry.4b48ee25.js:1:16066)
    at Wi.ne [as fn] (entry.4b48ee25.js:1:50873)
    at Wi.run (entry.4b48ee25.js:1:4166)
    at De.D.update (entry.4b48ee25.js:1:51635)
    at hn (entry.4b48ee25.js:1:12855)
    at Gr (entry.4b48ee25.js:1:14487)

or

TypeError: t.size is null 
   at
    NuxtJS 23
[entry.4b48ee25.js:1:13353](https://primevue.org/_nuxt/entry.4b48ee25.js)
    NuxtJS 24

### Reproducer

https://primevue.org/treetable/#size

### PrimeVue version

3.36.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Go to https://primevue.org/treetable/#size
Select "Normal" or "Small" and "Small" again, The table will disappear.

![image](https://github.com/primefaces/primevue/assets/96024737/04bf5ab0-c5f0-4fed-9288-daa9413b5c54)

### Expected behavior

The table should not disappear when the same size is selected

**Comment by tugcekucukoglu** [comment]
I did not get the error you mentioned above on live or local demos. Do you have a reproducer link? Cannot replicate the issue.
