### ISSUE TITLE
SpeedDial: Overlapping Issue

### ISSUE THREAD

**Issue by loxK** [primefaces/primevue#4630]
### Describe the bug

It uses opacity to hide items, so nothing can be clicked thought the hidden items when using it as a floating action button (FAB) :

![image](https://github.com/primefaces/primevue/assets/136687/f9f3caeb-02ad-4511-8d8b-9f1608ff74e2)

### Reproducer

https://codesandbox.io/embed/stupefied-sound-yyy6zw

### PrimeVue version

3.36.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox, Chrome

**Comment by tugcekucukoglu** [comment]
This is an expected situation in a component such as SpeedDial. When the list is opened, pointer-events changes to auto.

**Comment by chz** [comment]
> This is an expected situation in a component such as SpeedDial. When the list is opened, pointer-events changes to auto.

I thins it is not expected situation. This is bug.

**Comment by loxK** [comment]
How an invisible item that prevents interacting with the content below can be an "expected situation" ?

This is a bug. Please reopen.

**Comment by loxK** [comment]
> This is an expected situation

@tugcekucukoglu How can an invisible item, that prevents interacting with the content below, be an "expected situation" ? This is an UX Design nonsense.

This is a bug. Please reopen.

**Comment by matt-sr** [comment]
Has anyone found a workaround for this that doesn't involve breaking/removing animations? @tugcekucukoglu this most definitely is a bug...

**Comment by minzdrav** [comment]
@tugcekucukoglu please reopen the issue! This is a bug!

**Comment by minzdrav** [comment]
Hey @loxK @matt-sr 
Ziad from discord chat created a workaround: https://stackblitz.com/edit/gyj14u?file=src%2FApp.vue
You can thank him in Prime Discord - primevue channel. He is a good guy :)
