### ISSUE TITLE
Menu: Consider alternative to deprecating links in menu components

### ISSUE THREAD

**Issue by tommie** [primefaces/primevue#4633]
### Describe the feature you would like to see added

I only know what's in the deprecation message. This FR is based on that. Appologies if it's misguided.

PrimeVue is deprecating the use of `<router-link>` magic inside the various menu components. Instead, it encourages the users to use template customization to do the same thing. I think this is a step back in DevEx, because it makes getting started much harder. I now have to understand how the customization API works, instead of just knowing what `to` does in Vue Router.

The amount of code to do what PrimeVue does now is non-trivial:

https://github.com/primefaces/primevue/blob/52d7d11235accc6032d05100a71c38cdca1f0a24/components/lib/menu/Menuitem.vue#L15-L28

Having to do this not only for `Menuitem`, but also e.g. `PanelMenu` makes it ever more daunting:

https://github.com/primefaces/primevue/blob/52d7d11235accc6032d05100a71c38cdca1f0a24/components/lib/panelmenu/PanelMenuSub.vue#L20-L37

### Describe the solution you'd like

I would suggest the `PrimeVue.use` function takes `linkComponent` as an option: https://github.com/primefaces/primevue/blob/52d7d11235accc6032d05100a71c38cdca1f0a24/components/lib/config/PrimeVue.js#L4

This would be a dynamic component that `Menuitem` et al. instantiate using `<component is>`, a mechanism already in use there for enabling the `item` slot: https://github.com/primefaces/primevue/blob/52d7d11235accc6032d05100a71c38cdca1f0a24/components/lib/panelmenu/PanelMenuSub.vue#L38

Then, the link component API would have to be documented (likely simply just a subset of `<router-link>`) and we can elect to use `<router-link>` or `<nuxt-link>` or something custom.

The default could be a wrapped `<a>` component that helps render an icon, and handles the action props. It warns if it receives the router-specific `to` attribute, perhaps hinting at configuring `<router-link>`. I.e. this would be the `<a>` half of what `Menuitem` currently defaults to.

### Describe alternatives you have considered

Defining custom components for menu items also requires thinking about expanded/collapsed and selected/highlighted theming. It would be much nicer if PrimeVue know about the concept of links, even if it didn't know the router specifics. I'm guessing the number of slot props will be ever increasing to handle this. It would be much easier with a defined link API.

### Additional context

Related to #3884, #4351.

#3118 could perhaps make use of the same defined link API, though as I just added there, I think that issue is more about the theme API.

**Comment by AverageCakeSlice** [comment]
For the time being I've just been using `command: async () => { await router.push(<some route here>); }` to substitute out the `to` field. I wholeheartedly agree though, it makes navigation a lot more obtuse than it used to be.

**Comment by zavvla** [comment]
Is there any information on the to property? I really don't want to replace it with command...

**Comment by tugcekucukoglu** [comment]
Using vue-router as a dependency forced users who did not use a router to download the package. For this, it was necessary to make some decisions. `item` slot was a functionality that has been used for a long time, so we followed this path. But still, the best place to discuss this would be [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by tommie** [comment]
Created https://github.com/orgs/primefaces/discussions/556. Added a note there that no `vue-router` dependency is required in my proposal.

**Comment by tugcekucukoglu** [comment]
Thank you!

**Comment by manu144x** [comment]
I was about to pay for the component library, but never in a million years I would have imagined that a basic thing like :to router links are not supported.

I guess it's time to re-evaluate another framework. It's a shame because I really liked it.

I don't understand why it's so hard to say: if you want to use the :to with the vue router you need to install the vue-router, if not, just don't use the to and do it with the command or @click, anyway you want, so nobody has to install the dependency if they will not use it.
