### ISSUE TITLE
integration with tailwind : float label

### ISSUE THREAD

**Issue by johndegey** [primefaces/primevue#4634]
Hello,

I am testing PrimeVue with the complete integration of tailwind as a replacement for vuetify.
I've managed to use tailwind to have a floating label with InputText.

But when I tried to make the same thing with the Password component, regarding the generated html, it seems to me that it is impossible to use the "peer" approach of tailwind.

Is there another approach for this ?
Should I have a mix of prime css with tailwind ?

Thank you

Regards

John

**Comment by tugcekucukoglu** [comment]
The team is working on new presets. It will be announced this week.

Thank you.

**Comment by cagataycivici** [comment]
We now have a FloatLabel component in core as well, which will have a counterpart as a Tailwind preset, here is an example implementation from gallery;

https://stackblitz.com/~/github_project/cagataycivici/material-input-vue
