### ISSUE TITLE
Calendar: ReferenceError: currentYear is not defined 

### ISSUE THREAD

**Issue by chz** [primefaces/primevue#4635]
### Describe the bug

1. Open https://primevue.org/calendar 
2. Click Calendar input select date.
3. After again click selected date calendar then change month it will be throw error `ReferenceError: currentYear is not defined `

![Screenshot 2023-10-17 at 22 50 22](https://github.com/primefaces/primevue/assets/3233370/8d7a2590-2a16-49ce-b509-fd2cb8d57913)

### Reproducer

https://primevue.org/calendar

### PrimeVue version

3.36.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Open https://primevue.org/calendar
2. Click Calendar input select date.
3. After again click selected date calendar then change month it will be throw error `ReferenceError: currentYear is not defined `

### Expected behavior

Must be shown month select

**Comment by chz** [comment]
@tugcekucukoglu Please review this fix. Probably missed "**this**" keyword

**Comment by seymenk** [comment]
https://github.com/primefaces/primevue/pull/4615
