### ISSUE TITLE
SplitButton: No default command

### ISSUE THREAD

**Issue by liborjelinek** [primefaces/primevue#4639]
### Describe the feature you would like to see added

SplitButton has a concept of default command (button). However, it would be often useful to behave more like a dropdown (combobox) of buttons. In other words that an user have to choose which command (button) to trigger every time.

### Is your feature request related to a problem?

Yes, I am building a "change text to heading 1-6" command toolbar in a text editor. Clicking on heading button itself make no sense since there is no some heading, but only heading level 1, heading level 2, etc.

<img src="https://github.com/primefaces/primevue/assets/383059/ec1d8769-1be3-460f-99db-35c73a26a973" width="25%">

### Describe the solution you'd like

SplitButton without default command:

- Adding `noDefault` prop will enable the behaviour
- Clicking on the button or right arrow does nothing but opening drop-down menu of options
- Only clicking on item from drop-down will trigger a command

Or, maybe a new component DropdownButton will this behaviour, but I will prefer keep SplitButton with optionally "no-default" flag.

### Describe alternatives you have considered

IMHO there are no workarounds to mimic this with PrimeVue...

### Additional context

I have used to this "no default" behaviour from [Bulma dropdown](https://bulma.io/documentation/components/dropdown/) and miss it a lot in PrimeVue.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
