### ISSUE TITLE
DataTable: Cell editing doesn't retain values when using slotProps

### ISSUE THREAD

**Issue by dipbhi** [primefaces/primevue#4642]
### Describe the bug

In a cell editable `DataTable`, when the `#editor` template uses `slotProps` properties (`data[field]`) as the `v-model` for `InputText` (or any other input element), it doesn't retain the value when the editing is completed (value displayed using the `#body` template).

This works fine when you use state value directly as the `v-model` for the InputText.

Specific condition(s):
- Columns are defined statically. 
- In the editing example given on the PrimeVue website, it uses dynamically generated columns, which works fine.

### Reproducer

https://codesandbox.io/p/sandbox/objective-feather-s6wkcw

### PrimeVue version

3.36.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Edited value should retain when the editing is completed.

**Comment by tugcekucukoglu** [comment]
Saving process can be controlled with `cell-edit-complete` emit. Live example: https://primevue.org/datatable/#cell_edit

**Comment by dipbhi** [comment]
Hi @tugcekucukoglu,
This is not regarding saving process. Issue is that the slotProps values are not updating from the input element when columns are defined statically. 

The live example on the website uses dynamic columns where it works. 

Look at my reproducer link and you will see that it doesn't work the same way for columns defined individually. https://codesandbox.io/p/sandbox/objective-feather-s6wkcw
