### ISSUE TITLE
Add custom wrapper support for helper components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#4646]
Currently, primevue components such as DataTable need a helper component within themselves. These helper components must be directly child components. But sometimes users may need to wrap them with a custom wrapper instead of using them directly as children. Exp;
```
<DataTable :value="products" tableStyle="min-width: 50rem">
     <MyColumn field="code" header="Code"></MyColumn>
     <MyColumnWrapper :fields="['name', 'category']"></MyColumnWrapper>
     <Column field="quantity" header="Quantity"></Column>
</DataTable>
```
<hr />

Affected Components;
|  | Components | Helper Components |
| --- | --- | --- |
✅ | DataTable | Column, Row, ColumnGroup | 
✅ | TreeTable | Column
✅ | Accordion | AccordionTab
✅ | TabView | TabPanel

**Comment by mertsincan** [comment]
Hi @moyoakala yes, you can use it.

**Comment by hackjackhack** [comment]
Why is this commit reverted may I ask?

**Comment by mertsincan** [comment]
I only reverted my fixes for TabView and Accordion. Since they do not contain default slots, it was not technically possible to establish a structure like DataTable and TreeTable. We plan to make improvements to them in future versions. Currently, you can create custom wrapper components for DataTable and TreeTable.

Best Regards,

**Comment by hackjackhack** [comment]
Cool. I was trying to create custom dynamic async tabpanel, which are loaded based on runtime conditions without v-if.Will the future improvement of tabview cover this?

**Comment by fhnaumann** [comment]
> I only reverted my fixes for TabView and Accordion. Since they do not contain default slots, it was not technically possible to establish a structure like DataTable and TreeTable. We plan to make improvements to them in future versions. Currently, you can create custom wrapper components for DataTable and TreeTable.
> 
> Best Regards,

Do you know a way to create custom wrapper components for Accordion (including AccordionTab)?

**Comment by mertsincan** [comment]
Unfortunately, there is no way for now :/ I  plan to make improvements to them in future versions.

**Comment by james-cavanagh** [comment]
Hi @mertsincan, is there an update on this issue please?

Additionally, is there a list of components that cannot be wrapped? Such a list would help me make an informed decision about whether PrimeVue is a suitable component library to pursue within my organisation. I hope it is, as, aside from the wrapping issue with several key components, it's fantastic. I essentially need to ensure its stability before discussing a Pro Support package, as these types of issues could significantly impact our decision-making process.

**Comment by nikolay-kornev** [comment]
@mertsincan Could you please provide example of working wrapper component for `Column`? I cannot make it render, no matter what I do. In my specific case, I am creating a custom UI library. I wrap PrimeVue components as described here - https://tailwind.primevue.org/guides/building-ui-library/. 

I have wrapped `DataTable`, and `Column` components. When I try using them, all I see is pagination. Columns are not rendering.

**Comment by luizottavioc** [comment]
I'm having the same problem. My custom columns are not rendered in the DataTable component

**Comment by claushellsing** [comment]
Same thing happen to me

**Comment by Thiritin** [comment]
Okay... I have run into the same issue. It looks like it works if the Custom Component has a v-if Attached to it.

![image](https://github.com/primefaces/primevue/assets/6755282/e5ceb582-b545-4c27-ae14-aec6d2865e9a)
![image](https://github.com/primefaces/primevue/assets/6755282/1851fca7-49d6-4a69-9b2b-75431885ec08)

(If adding a v-if to the upc it will be visible again)

**Comment by luizottavioc** [comment]
In my case, v-if has no effect...
![code](https://github.com/primefaces/primevue/assets/89395176/1b29e2a5-4812-4981-9d27-6538d3eb1cfe)
![preview](https://github.com/primefaces/primevue/assets/89395176/0f6c5535-9a68-4cc2-89db-3c09c6400a7e)

**Comment by luizottavioc** [comment]
I did some tests here and I found a solution to temporarily resolve it.

In my structure, I have a "DefaultTable" component and I just pass the columns to it, then my table columns are not inside the Datatable component.

To make the custom columns rendered by the thrid component, I need to import them into my DefaultTable using the `v-if="true"` condition and adding a `display: none` to don't show them by default, like this:

```js
// DefaultTable.vue
<template>
  <TableLoading v-if="tableData === null" />
  <div
    v-else
    class="w-full overflow-y-auto"
  >
    <DataTable
      ref="dt"
      :value="tableData"
      [...]
    >
      <template #header>[...]</template>
      <StringColumn v-if="true" field="" header="" class="hidden" />
      <ClassColumn v-if="true" field="" header="" class="hidden" />
      <BooleanColumn v-if="true" field="" header="" class="hidden" />
      [...]
      <slot name="columns"></slot>
    </DataTable>
  </div>
</template>

<script lang="ts" setup>
import StringColumn from '@/components/tables/columns/default/StringColumn.vue'
import ClassColumn from '@/components/tables/columns/default/ClassColumn.vue'
import BooleanColumn from '@/components/tables/columns/default/BooleanColumn.vue'
[...]
</script>
```
In the component where my table is built, i just pass the custom columns into the column slot reusing the `v-if="true"` like this:
```js
//UsersPage.vue
<template>
  <DefaultTable url="/users" [...]>
    <template #columns>
      <StringColumn
        v-if="true"
        field="idUser"
        header="ID"
      />
      <BooleanColumn
        v-if="true"
        field="online"
        header="Connection Status"
        true-text="Online"
        false-text="Offline"
      >
        <template #body="{ data }">
          <UserConnectionStatusChip :is-online="data.online" />
        </template>
      </BooleanColumn>
      <ClassColumn
        v-if="true"
        field="companyBranch"
        header="Company Branch"
        :options="metadata.companyBranches"
      />
    </template>
  </DefaultTable>
</template>

<script lang="ts" setup>
import DefaultTable from '@/components/tables/DefaultTable.vue'
import StringColumn from '@/components/tables/columns/default/StringColumn.vue'
import BooleanColumn from '@/components/tables/columns/default/BooleanColumn.vue'
import ClassColumn from '@/components/tables/columns/default/ClassColumn.vue'
</script>
[...]
```

**Comment by Thiritin** [comment]
> I did some tests here and I found a solution to temporarily resolve it.
> 
> In my structure, I have a "DefaultTable" component and I just pass the columns to it, then my table columns are not inside the Datatable component.
> 
> To make the custom columns rendered by the thrid component, I need to import them into my DefaultTable using the `v-if="true"` condition and adding a `display: none` to don't show them by default, like this:
> 
> ```js
> // DefaultTable.vue
> <template>
>   <TableLoading v-if="tableData === null" />
>   <div
>     v-else
>     class="w-full overflow-y-auto"
>   >
>     <DataTable
>       ref="dt"
>       :value="tableData"
>       [...]
>     >
>       <template #header>[...]</template>
>       <StringColumn v-if="true" field="" header="" class="hidden" />
>       <ClassColumn v-if="true" field="" header="" class="hidden" />
>       <BooleanColumn v-if="true" field="" header="" class="hidden" />
>       [...]
>       <slot name="columns"></slot>
>     </DataTable>
>   </div>
> </template>
> 
> <script lang="ts" setup>
> import StringColumn from '@/components/tables/columns/default/StringColumn.vue'
> import ClassColumn from '@/components/tables/columns/default/ClassColumn.vue'
> import BooleanColumn from '@/components/tables/columns/default/BooleanColumn.vue'
> [...]
> </script>
> ```
> 
> In the component where my table is built, i just pass the custom columns into the column slot reusing the `v-if="true"` like this:
> 
> ```js
> //UsersPage.vue
> <template>
>   <DefaultTable url="/users" [...]>
>     <template #columns>
>       <StringColumn
>         v-if="true"
>         field="idUser"
>         header="ID"
>       />
>       <BooleanColumn
>         v-if="true"
>         field="online"
>         header="Connection Status"
>         true-text="Online"
>         false-text="Offline"
>       >
>         <template #body="{ data }">
>           <UserConnectionStatusChip :is-online="data.online" />
>         </template>
>       </BooleanColumn>
>       <ClassColumn
>         v-if="true"
>         field="companyBranch"
>         header="Company Branch"
>         :options="metadata.companyBranches"
>       />
>     </template>
>   </DefaultTable>
> </template>
> 
> <script lang="ts" setup>
> import DefaultTable from '@/components/tables/DefaultTable.vue'
> import StringColumn from '@/components/tables/columns/default/StringColumn.vue'
> import BooleanColumn from '@/components/tables/columns/default/BooleanColumn.vue'
> import ClassColumn from '@/components/tables/columns/default/ClassColumn.vue'
> </script>
> [...]
> ```

Oh my god, thank you. That is a smart solution to overcome this issue.

**Comment by anthonyespirat** [comment]
still got the issue on 4.0.0

**Comment by NodeAdam** [comment]
So is `v-if="true"` the solution, or is it a workaround? Will there be an actual fix?

**Comment by Real-Gecko** [comment]
Any working example of this?

**Comment by Ciriak** [comment]
> So is `v-if="true"` the solution, or is it a workaround? Will there be an actual fix?

Well at least it works but it feels very unconventional

@Real-Gecko 

**DataTable.vue**

```vue
<DataTable>
    <StatusColumn
      v-if="true"
      field="status"
      header="status" />
</DataTable>
```

**StatusColumn.vue**

```vue
<template>
<Column
    v-bind="props"
  >
    <template #body="{ data }">
      {{data}}
    </template>
      </Column>
</template>

<script setup lang="ts">
import type { ColumnProps } from 'primevue/column';
import Column from 'primevue/column';
const props = defineProps<ColumnProps>();
</script>
```

**Comment by Real-Gecko** [comment]
> ```
> <DataTable>
>     <StatusColumn
>       v-if="true"
>       field="status"
>       header="status" />
> </DataTable>
> ```

It works if column is a direct descendant of `DataTable` but does not work for nested children like:
```vue
// SomethingList.vue
  <List>
    <LinkColumn v-if="true" field="title" header="Title />
  </List>
```
```vue
// List.vue
    <DataTable>
      <slot></slot>
    </DataTable>
```

**Comment by richardlaven** [comment]
This is still an issue in the latest version of Primevue (4.1.0). I cannot seem to wrap column with my own component. Anyone have a working sollution?

**Comment by Edgaras318** [comment]
anyone?

**Comment by eviannaive** [comment]
same problem😿

**Comment by patie** [comment]
same problem here :(

**Comment by alxjzx100** [comment]
Same here,  Primevue 4.3.3

**Comment by Ciriak** [comment]
> > So is `v-if="true"` the solution, or is it a workaround? Will there be an actual fix?
> 
> Well at least it works but it feels very unconventional
> 
> [@Real-Gecko](https://github.com/Real-Gecko)
> 
> **DataTable.vue**
> 
> <DataTable>
>     <StatusColumn
>       v-if="true"
>       field="status"
>       header="status" />
> </DataTable>
> **StatusColumn.vue**
> 
> <template>
> <Column
>     v-bind="props"
>   >
>     <template #body="{ data }">
>       {{data}}
>     </template>
>       </Column>
> </template>
> 
> <script setup lang="ts">
> import type { ColumnProps } from 'primevue/column';
> import Column from 'primevue/column';
> const props = defineProps<ColumnProps>();
> </script>

This solution doesn't work anymore with the latest version of primevue ? any update ?

**Comment by ludhriq** [comment]
The solution that i found is just pass the `key` attribute on the custom column component when using inside DataTable.

Key forces Vue to respect your component's identity, ensuring that it is recreated (rather than just subtly updated) when necessary, perfectly synchronizing its lifecycle with the parent <DataTable>'s inspection cycle.

Essentially, both key and v-if are forcing Vue to perform a more explicit and complete rendering cycle for your component, solving the problem, but in this case the best option to be used is the key attribute

CustomColumn.vue
```js
<template>
    // forcing sortable to be always true and passing all the props to Column component
    <Column
        v-bind="$attrs"
        sortable
    >
        // passing all the slots to Column component
        <template v-for="(_, slotName) in $slots" #[slotName]="slotProps">
            <slot :name="slotName" v-bind="slotProps"/>
        </template>
        <!-- <template #body>
            <slot/>
        </template>
    </Column>
</template>
```

Using custom column component
```js
<DataTable>
    <FilterColumn
        key="price" <--------
        field="price"
        header="Price"
        sortable
    >
        <template #filter="{ filterModel }">
            <Select
                v-model="filterModel.matchMode"
                :options="options"
                optionLabel="label"
                optionValue="value"
            />
            <InputText v-model="filterModel.value" />
        </template>
    </FilterColumn>
</DataTable>

```
