### ISSUE TITLE
InputGroup: InputNumber et al. with show-buttons is incompatible with trailing addon

### ISSUE THREAD

**Issue by tommie** [primefaces/primevue#4658]
### Describe the bug

When using `InputGroup` with input components that have optional built-in addons, the border rounding happens twice.

From a quick glance through the form components, this affects: `Calendar`, `InputNumber`, `SelectButton`.

`<Calendar show-icon>` has the problem (for the input element) even without a trailing addon.

The `<InputNumber button-layout=horizontal>` and `SelectButton` additionally have the issue at the start of the component as well.

The `<Password toggle-mask>` works.

Tangentially related to #4527.

### Reproducer

https://codesandbox.io/s/inputgroup-trailing-addon-repro-zysrhz?file=/src/App.vue

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Expected behavior

There is no border rounding except the start and end of the input group.

**Comment by tommie** [comment]
Updated with: `Calendar show-icon` is broken even without a trailing addon.

**Comment by tugcekucukoglu** [comment]
I'm currently working on new InputGroup and InputGroupAddon components. Implementation will become easier with the `pt` property.

**Comment by tommie** [comment]
@tugcekucukoglu Thanks! Also note the issue with Calendar show-icon, which happens without an addon..

Wouldn't it be easier to keep this open until that has landed, so we could know the issue is resolved?
