### ISSUE TITLE
Nuxt3 + PrimeVue + TailwindCSS: Tailwind based PrimeOne Design not working as expected

### ISSUE THREAD

**Issue by fermaud** [primefaces/primevue#4665]
### Describe the bug

Hi, I tried to setup Nuxt3 + PrimeVue + TailwindCSS with the Tailwind based PrimeOne Design and it doesn't work as expected. The style seems to load but only partially.
A page with a Timeline & Dropdown for example
<img width="434" alt="image" src="https://github.com/primefaces/primevue/assets/13439156/7ea71bf7-3378-4bab-8f11-6b8fa4d17e25">

Thanks for your work 🙏🏼 

### Reproducer

https://stackblitz.com/edit/nuxt-starter-jky4yp

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome up-to-date

**Comment by micheee** [comment]
Hi @fermaud  

this has been discovered, here: https://github.com/primefaces/primevue-nuxt-module/issues/6

Background: the Passthrough Tailwind preset can't be serialized as it contains functions, on the other hand, `nuxts` serializes any config-objects to JSON when passing them to its nitro runtime, so the: 
```ts
  options: {
      ripple: true,
      unstyled: true,
      pt: Tailwind,
```

will be passed as:

```ts
  options: {
      ripple: true,
      unstyled: true,
      pt: {} // this turns to an empty object
```

My workaround can be found in that issue as well https://github.com/primefaces/primevue-nuxt-module/issues/6#issuecomment-1773357291 while not the most beautiful solution, it is at least easy enough to maintain, and I am not sure how quickly the serialization issue can be resolved.

**Comment by fermaud** [comment]
Thank you @micheee I'll try your solution until a patch is released ! 👍🏼

**Comment by fermaud** [comment]
@micheee 
You fix is working, but I have an error when I run `npm run build`

`[error] [vite]: Rollup failed to resolve import "quill" from "/opt/build/repo/node_modules/primevue/editor/editor.esm.js".`
`This is most likely unintended because it can break your application at runtime.`
`If you do want to externalize this module explicitly add it to 'build.rollupOptions.external`

Here is a new project with the fix.

https://stackblitz.com/edit/nuxt-starter-9pvd9x

**Comment by cristiancosano** [comment]
> @micheee You fix is working, but I have an error when I run `npm run build`
> 
> `[error] [vite]: Rollup failed to resolve import "quill" from "/opt/build/repo/node_modules/primevue/editor/editor.esm.js".` `This is most likely unintended because it can break your application at runtime.` `If you do want to externalize this module explicitly add it to 'build.rollupOptions.external`
> 
> Here is a new project with the fix.
> 
> https://stackblitz.com/edit/nuxt-starter-9pvd9x

That error occurs because you are importing the 'Editor' component which requires quill.

More info: https://primevue.org/editor/

**Comment by fermaud** [comment]
@cristiancosano I do not import Editor..

**Comment by tugcekucukoglu** [comment]
> @cristiancosano I do not import Editor..

Could you update your nuxt.config

```
primevue: {
    components: {
        include: '*',
        exclude: ['Editor', 'Chart']
    }
}
```

**Comment by fermaud** [comment]
This works thanks @tugcekucukoglu

**Comment by mertsincan** [comment]
Hi all,

PrimeVue v3.38.1 and Nuxt-PrimeVue v0.1.0 released 🚀

- Nuxt-PrimeVue + Tailwind starter updated; https://github.com/primefaces/primevue-examples/tree/main/nuxt-styled-tailwind
- New module doc; https://primevue.org/nuxt/

For `pt`, please see new `importPT`option; https://primevue.org/nuxt/#importpt

Best Regards,

**Comment by gbarros1994** [comment]
For those who couldn't, I created a simple and functional example repository. It contains Nuxt 3 + PrimeVue Tailwind. Just clone, install and test the components

https://github.com/sfxcode/nuxt3-primevue-starter

**Comment by molul** [comment]
Hi. I'm having this same error ([error] Nuxt Build Error: [vite]: Rollup failed to resolve import "quill" from "/vercel/path0/node_modules/primevue/editor/index.mjs".) when deploying my nuxt app to Vercel.

This is my primevue config in nuxt.config.ts (the workaround mentioned here didn't work):

```
primevue: {
    options: {
      locale: primevueLocaleOptions,
      ripple: false,
      unstyled: true,
      theme: {
        options: {
          cssLayer: {
            name: 'primevue'
          }
        }
      }
    },

    importPT: {
      from: path.resolve(__dirname, './assets/primevuePresets/main/')
    },

    autoImport: false,
    components: {
      include: '*',
      exclude: ['Editor', 'Chart']
    }
  },
```
