### ISSUE TITLE
PanelMenu: Error when using `#item` slot

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primevue#4671]
### Describe the bug

When using `#item` slot, PanelMenu fails to render. Console shows the following error:
```
Uncaught ReferenceError: processedItem is not defined
    at Proxy.getMenuItemProps2 (primevue_panelmenu.js?v=98b45702:1113:45)
    at primevue_panelmenu.js?v=98b45702:1222:23
    at renderList (chunk-QSL5RKHU.js?v=3ab457b4:4140:16)
```

Looks like a copy/paste error here: https://github.com/primefaces/primevue/commit/e8acbefd2aaaa92d584a8a835c1abe3964ff53f1

### Reproducer

https://stackblitz.com/edit/xq9nts-sjhrtg?file=src%2FApp.vue

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Load stackblitz reproducer
2. View console log

### Expected behavior

No error

**Comment by Rakasch** [comment]
Also get this issue after upgrading to primevue 3.37.0
![image](https://github.com/primefaces/primevue/assets/8471027/7c9b6dca-8d0b-42d7-a5c1-06f88fc6cfbf)
