### ISSUE TITLE
SplitButton: Wrong formatting with Tailwind

### ISSUE THREAD

**Issue by bipsen** [primefaces/primevue#4673]
### Describe the bug

SplitButton doesn't have any formatting when used with the Tailwind passthrough, and fields like "severity" has no effect.

### Reproducer

https://stackblitz.com/edit/github-cdpee7

NB: In this reproduction, the dropdown also doesn't work. I am not experiencing that in my own setup but am still getting the descriped issue.

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use Tailwind in a Vite or Nuxt project via passthrough, like so:

```
import Tailwind from 'primevue/passthrough/tailwind';
app.use(PrimeVue, { unstyled: true, pt: Tailwind });
```

When using SplitButton, the button has no margins and is white.

### Expected behavior

SplitButton should look like a regular Button and respond to severity.

**Comment by tugcekucukoglu** [comment]
Could you try to add this `app.use(PrimeVue, { unstyled: true, pt: Tailwind, ptOptions: { mergeProps: true } });` with the latest version of PrimeVue? If you prefer you could copy and paste `splitbutton, button, tieredmenu` items from here https://primevue.org/splitbutton/#theming.tailwind

We are working on new Tailwind theme for some changes. When https://tailwind.primevue.org/ is ready, there is no need to add `ptOptions: { mergeProps: true } `
