### ISSUE TITLE
How to use usePassThrough in primevue in vue3 typescript?

### ISSUE THREAD

**Issue by abhinandkaippalli** [primefaces/primevue#4675]
I wanted to change the dark mode on my data table. So I using with tailwind and I wanted to update that. So I used usePassThrough method to change the default style to new one? But It's not working.
`const CustomTailwind = usePassThrough(
  Tailwind,
  {
    DataTable: {
      column: {
        headercell: () => ({
          class: [
            'text-right border-2 border-b border-solid border-red-300 font-bold'
          ]
        })
      }
    },
  },
  {
    mergeSections: true,
    mergeProps: false,
  }
);

app.use(PrimeVue, { unstyled: true, pt: CustomTailwind })`

**Comment by tugcekucukoglu** [comment]
Could you send a reproducer link?

**Comment by tugcekucukoglu** [comment]
I guess there was a typo. Please change `DataTable ` as `datatable`.
