### ISSUE TITLE
Dropdown pre select model value not selected 

### ISSUE THREAD

**Issue by ss2016ss** [primefaces/primevue#468]
Pre selected city is "New York" but its not selected in drop down value
Example: 
`<Dropdown v-model="selectedCity" :options="cities" optionLabel="name" placeholder="Select a City" />`

`data() {
	return {
		selectedCity: "New York",
		cities: [
			{name: 'New York', code: 'NY'},
			{name: 'Rome', code: 'RM'},
			{name: 'London', code: 'LDN'},
			{name: 'Istanbul', code: 'IST'},
			{name: 'Paris', code: 'PRS'}
		]
	}
}`

**Comment by cagataycivici** [comment]
This is expected because selectedCity would be `{name: 'New York', code: 'NY'}` in your case which is not equal to 'New York'. Alternative is using optionValue="label" so that dropdown checks for the label against the model.
