### ISSUE TITLE
Menubar: Submenu item creates horizontal scrollbar

### ISSUE THREAD

**Issue by Ruben-aah** [primefaces/primevue#4680]
### Describe the bug

When using a menubar with submenu items, the submenu items will always open to the right, even if the edge of the viewport has been reached. This will create a horizontal scrollbar to display the submenu items. 

![image](https://github.com/primefaces/primevue/assets/133119180/794817d9-fd65-4565-b187-45312e4c0416)

### Reproducer

https://stackblitz.com/edit/xntyzj?file=src%2FApp.vue

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a page with a menubar.
2. Fill the menubar with a lot of submenu items.
3. Open up the nested menu items until it reaches the edge of the screen.

### Expected behavior

I would expect the submenu item to open to the other side if there is no more space on side that it's trying to open to.

**Comment by tmlmt** [comment]
Great point. Actually similar / related to #4724 I posted yesterday. One could say it's actually down to a single common issue.

**Comment by tugcekucukoglu** [comment]
We will work on the responsiveness of not only the Menubar but also all Overlay panels. Definitely in our roadmap.

Thank you!
