### ISSUE TITLE
Carousel: page attribute not updating carousel

### ISSUE THREAD

**Issue by autoboxer** [primefaces/primevue#4684]
### description

The `page` attribute isn't updating which page of carousel items are in view.  Dynamically changing the `page` value updates `indicators` and `left/right navigation` correctly, however, the carousel items themselves don't shift to show the correct `page`.

It looks like internally the `Carousel` component makes a call to `navForward()` or `navBackward()` when the selected page index changes.  Without those functions exposed or `page` updates working, there's no way for actions external to the `Carousel` or its controls to update what page of items are shown.

### related issues

[e.g. Carousel Component: add Methods like navForward() to Public API](https://github.com/primefaces/primevue/issues/4499)

### Reproducer

https://codesandbox.io/p/sandbox/morning-meadow-3j8xll?file=%2Fsrc%2FApp.vue%3A1%2C1

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 118

### Steps to reproduce the behavior

1. go to https://codesandbox.io/p/sandbox/morning-meadow-3j8xll?file=%2Fsrc%2FApp.vue%3A1%2C1
2. click on the `page +1` button - note the controls and in view carousel page updates
3. click on the `page -1` button - note that the controls update, but the page in view does not
4. from this point on, all adjustments to the `page` value will update the carousel controls, but not the visible page

### Expected behavior

updating the value that gets passed into the `page` carousel attribute should update both the page in view, as well as the carousel controls (assuming the passed in value is a valid page index).

**Comment by autoboxer** [comment]
I've been playing around with the `page` `watcher`, but don't see a way to determine which function to call (`navForward()` or `navBackward()` based on the `newValue`, as `d_page` has already been updated, so the new `page` index can't be compared against it.  If there were a way in the `watcher` to determine which page the user were navigating from, this would be as easy as calling `navForward()` or `navBackward()`.  I'm likely missing a way to do the comparison as I'm new to the codebase.

**Comment by autoboxer** [comment]
I'm working on a PR for this and should have something working in the near future.

**Comment by ostrui** [comment]
I still have this bug on "primevue": "^3.20.0",

**Comment by dimaskurniawan0804** [comment]
I still have this bug on "primevue": "^3.37.0",

**Comment by mzhadigerov** [comment]
it's been a while since version 4 released, but the issue still persists.

**Comment by mzhadigerov** [comment]
Nevermind it worked. My carousel was wrapped with `v-if`. After changing it to `v-show` it works.
