### ISSUE TITLE
Support for iconify

### ISSUE THREAD

**Issue by Jak2k** [primefaces/primevue#4686]
### Describe the feature you would like to see added

Support for all icons on iconfify.

### Is your feature request related to a problem?

Your set of icons is missing many things.

### Describe the solution you'd like

You should load icons from iconify.

### Describe alternatives you have considered

Using chakra UI.

### Additional context

https://iconify.design/

**Comment by FlipWarthog** [comment]
PrimeVue lets you customize icons so you're not locked in, see https://primevue.org/customicons/

With something like [iconify-prerendered](https://github.com/cawa-93/iconify-prerendered), you can easily load and use alternative icon sets, ex. https://stackblitz.com/edit/rev9v1?file=src%2FApp.vue

**Comment by Jak2k** [comment]
Usually the iconify-icons are fetched dynamicly during dev or build, when needed.

**Comment by tugcekucukoglu** [comment]
Thanks for the stackblitz demo. It clears the issue.

**Comment by andrescellini** [comment]
hi, why not supporting inconify directy in the icon prop? in quasar the have something like this... 

`<Button type="button" label="Search" icon="material-symbols:favorite-outline-rounded" :loading="loading" @click="load" />
`
