### ISSUE TITLE
DataTable: Grindlines moving together with content when having Tailwind installed

### ISSUE THREAD

**Issue by felldo** [primefaces/primevue#4691]
### Describe the bug

When you scroll, the border moves with the content, and you see the content through the gap where the border was in the header. The border moves between the column header and the header with the `Reset all` button, as well as below the column header
When removing the show gridlines attribute from the DataTable it works fine.
I followed this [doc](https://primevue.org/tailwind) to include tailwind
![image](https://github.com/primefaces/primevue/assets/31566807/be4beb2d-5ea0-476d-9426-99bd0a0d1f3e)

The same happens with the vertical lines, when you freeze for example the first 2 columns

### Reproducer

https://stackblitz.com/edit/nuxt-starter-r31tcz?file=app.vue

### PrimeVue version

3.39.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Visit the stackblitz link and scroll in the DataTable

### Expected behavior

The border stays when you scroll while having tailwind installed.

**Comment by mertsincan** [comment]
Hi,

Unfortunately, your stackblitz link doesn't work for me. Could you please attach it again? Also, as you know, we moved the tailwind project to a new site. https://tailwind.primevue.org/ We are updating all preset codes now. If you send a new stackblitz, we'll fix it asap.

Best Regards,

**Comment by felldo** [comment]
> Unfortunately, your stackblitz link doesn't work for me. 

What do you mean? I opened the link again and it loads my example just fine. Even in other browsers (edge, not logged in or anything) it works and replicates the issue. May you try again with a different browser?

**Comment by mertsincan** [comment]
@felldo, when I try to open your link in Chrome, the page does not load and throws an error. I tried it in FF now and I managed to open it. When I examine your codes, you are trying to use tailwind with our styled mode and theme. As far as I understand, Tailwind overrides some table styles. Please see;
```css
@layer tailwind-base {
  table {
    text-indent: 0;
    border-collapse: collapse;  /* Please see this line */
  }
}
```

Please add this css in your app;
```css
.p-datatable-table {
    border-collapse: separate;
}
```
Also, our example without tailwind;
https://stackblitz.com/edit/bxfzn4?file=src%2FApp.vue

Best Regards,
