### ISSUE TITLE
InputNumber: Doc typo

### ISSUE THREAD

**Issue by Mallon94** [primefaces/primevue#4695]
Describe the bug

Under the 'Vertical' section of the InputNumber Component, there was a typo.

`import { ref } from"vuetest";`

It should be 

`import { ref } from "vue";`

I created a PR addressing this. I linked the PR in the Reproducer section as well, you know, its only a Doc issue.

### Reproducer

PR - > https://github.com/primefaces/primevue/pull/4694

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

N/A

### Expected behavior

N/A

**Comment by tugcekucukoglu** [comment]
PR accepted. Thanks you!
