### ISSUE TITLE
Add paginatorDropdownAppendTo property to DataTable

### ISSUE THREAD

**Issue by cuberinooo** [primefaces/primevue#4699]
### Describe the feature you would like to see added

I would like to use the "appendTo" property for pagination as well, just like with AutoComplete dropdown.

### Describe the solution you'd like

Target element to attach the paginator dropdown overlay

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by cuberinooo** [comment]
ok thanks.
