### ISSUE TITLE
TabView: Closable for TabView tabs

### ISSUE THREAD

**Issue by binarri** [primefaces/primevue#4705]
### Describe the feature you would like to see added

Closable for `TabView` and/or `TabMenu` tabs like in **PrimeReact** as follow

![image](https://github.com/primefaces/primevue/assets/8007836/8eae424e-9792-401e-b846-fae3b51fb3fe)

**Comment by HUIHUIABC** [comment]
++++1

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue disccussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
