### ISSUE TITLE
Ambigous column sort icons in DataTable

### ISSUE THREAD

**Issue by fprijate** [primefaces/primevue#4708]
IMHO current icons for column sort are ambigous. 
I don't know is it arrow that counts or lines (Ok it is arrow meaning the biggest at the tip . Why then distracting lines)

1.  Left icon is interpreted by me:  start at the top with the smallest value an go down to the largest
3.  Right icon is interpreted by me: start at the bottom with the largest value an go up to the smallest

Which has the same meaning to me - sort top to bottom (A-Z sort)
I would flip the left part (lines) in the right icon and change the meaning - the left icon is (A-Z), the right (Z-A)

![down](https://github.com/primefaces/primevue/assets/1025131/98fa7503-2de9-4383-88b3-dec0a01cb554)![Up](https://github.com/primefaces/primevue/assets/1025131/95ad327c-c29a-4467-8eb7-de06fa479e98)

There are some other possibilities, which seem more logical to me:

 **Simplest: Only one arrow - meaning, we start with smallest at the begining of the arrow and go down/up to the largest** 

**Other possibilities  (maybe reversing one of the arrows)**

1, ![Capture3](https://github.com/primefaces/primevue/assets/1025131/bd394101-3203-4e46-8d25-3183d4ac5570), 
2. ![Capture1](https://github.com/primefaces/primevue/assets/1025131/d139f93e-976b-48fe-82d3-dfd6e406b791)
3. ![Capture2](https://github.com/primefaces/primevue/assets/1025131/2b639afd-70bb-41cd-8f2a-f3efeaa44ce3)
4. ![Capture4](https://github.com/primefaces/primevue/assets/1025131/cb83ea95-80e4-4b18-9c58-1708282084bf)

### Is your feature request related to a problem?

As described

**Comment by FlipWarthog** [comment]
This has come up recently. See this closed issue for context and an example showing how to override

https://github.com/primefaces/primevue/issues/3978

**Comment by Voltra** [comment]
This has also come up in a few other issues and PRs, for instance #3732

**Comment by onursenture** [comment]
It's already fix here: #4981. 

Thank you!
