### ISSUE TITLE
Image: Error: Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by istanfrank** [primefaces/primevue#4710]
### Describe the bug

No Error with Version "primevue": "^3.29.2"
Error with Version: 3.38.1

### Reproducer

https://codesandbox.io/s/loving-orla-3tn7j2?file=/src/App.vue

### PrimeVue version

3.38.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome  118.0.5993.71

### Steps to reproduce the behavior

1.) Click on Image for Preview
2.) Click on empty place in preview dialog
3.) got Error

### Expected behavior

Errormessage:
focustrap.esm.js:43 Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')
    at findNextFocusableElement (focustrap.esm.js:43:1)
    at findNextFocusableElement (focustrap.esm.js:43:1)
    at eval (focustrap.esm.js:45:1)
    at Array.forEach (<anonymous>)
    at MutationObserver.eval (focustrap.esm.js:39:1)

**Comment by tugcekucukoglu** [comment]
Image component should be imported globally or locally.

**Comment by istanfrank** [comment]
i can not replicate the error on codesandbox. The only thing that i know is i got this error on different Windows PC's, but not on Mac

I disabled all plugins from, VS Code,
main.js
```
import { createApp } from 'vue'
import App from './App.vue'
import PrimeVue from 'primevue/config';
import Image from 'primevue/image';

const app = createApp(App);
app.use(PrimeVue, { ripple: true });
app.component('Image', Image);
app.mount('#app');
```

package.json:
```
{
  "name": "imageTest",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "core-js": "^3.33.2",
    "primevue": "^3.39.0",
    "vue": "^3.3.7",
    "vue-router": "^4.2.5"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.8",
    "@vue/cli-plugin-router": "~5.0.8",
    "@vue/cli-service": "^5.0.8"
  }
}
```

App.vue:
```
<template>
    <div>
    <Image
      src="https://www.primefaces.org/wp-content/uploads/2019/12/primevue-logo.png"
      alt="Image"
      width="100"
      preview
    />
  </div>
</template>
```

vue.config.js:
```
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true
})

```

And this is, what i get after clicked on Preview and after clicked in preview Dialog out of the picture. i can't even catch the error.

Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'nextSibling')
TypeError: Cannot read properties of null (reading 'nextSibling')
    at findNextFocusableElement (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:48:157)
    at findNextFocusableElement (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:48:128)
    at eval (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:50:74)
    at Array.forEach (<anonymous>)
    at MutationObserver.eval (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:44:22)
ERROR
Cannot read properties of null (reading 'nextSibling')
TypeError: Cannot read properties of null (reading 'nextSibling')
    at findNextFocusableElement (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:48:157)
    at findNextFocusableElement (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:48:128)
    at findNextFocusableElement (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:48:128)
    at eval (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:50:74)
    at Array.forEach (<anonymous>)
    at MutationObserver.eval (webpack-internal:///./node_modules/primevue/focustrap/focustrap.esm.js:44:22)

**Comment by istanfrank** [comment]
After Build, the error not happen with Version: 3.38.1. got the error only in localmode. with previos Version, don't get the error also on localmode. If this is normal, then can close this.

**Comment by GoldenFinger** [comment]
It is a bug.  you can try your the example from your doc. 

`
"primevue": "^3.40.0",
`
https://codesandbox.io/s/7mtmsc

![image](https://github.com/primefaces/primevue/assets/7462146/838d5495-8414-42ab-a494-c0c6d0479ed1)

**Comment by GoldenFinger** [comment]
version ` "primevue": "^3.40.1" `  also throw this error

**Comment by K4T** [comment]
I can only confirm that for me this is also happening (but not always).

**Comment by andrelec1** [comment]
Bug still here in 3.53.1 ...

Fixed with patch-package

+++ b/node_modules/primevue/focustrap/focustrap.esm.js
@@ -46,7 +46,8 @@
       if (mutation.type === 'childList' && !el.contains(document.activeElement)) {
         var findNextFocusableElement = function findNextFocusableElement(_el) {
+          if (!_el) return null;
           var focusableElement = DomHandler.isFocusableElement(_el) ? ...;
           return ObjectUtils.isNotEmpty(focusableElement) ? focusableElement : _el.nextSibling && findNextFocusableElement(_el.nextSibling);
         };
         DomHandler.focus(findNextFocusableElement(mutation.nextSibling));
       }
