### ISSUE TITLE
Table columns with null values not sorted properly

### ISSUE THREAD

**Issue by fprijate** [primefaces/primevue#4716]
### Describe the bug

primevue@3.35.0 sorted columns with null values correctly.
Later versions  3.36.0 - 3.38.1 treats them as the biggest values (bottom of the table.)
IMHO there is a problem with [#4555](https://github.com/primefaces/primevue/issues/4555). I didn't check it

### Reproducer
 Sort the name or category column

https://stackblitz.com/edit/4ulyna?file=src%2Fservice%2FProductService.js

### PrimeVue version

3.38.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome 118.0

### Steps to reproduce the behavior

on stackblitz sort the name or category column

### Expected behavior

to sort correctly

**Comment by FlipWarthog** [comment]
There's now a `nullSortOrder` prop to configure this behavior: https://primevue.org/datatable/#api.datatable.props.nullSortOrder

**Comment by tugcekucukoglu** [comment]
`nullSortOrder`  solves the problem.

Thank you @FlipWarthog
