### ISSUE TITLE
OverlayPanel: closeOnEscape broken

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4717]
### Describe the bug
Bug https://github.com/primefaces/primevue/issues/4693 still exists in 3.38.1

### Reproducer

https://stackblitz.com/edit/yfzpcc?file=src%2FApp.vue

### PrimeVue version

3.38.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primevue/issues/4712

Sorry for the confusion.
