### ISSUE TITLE
DataTable: issue in rowClass function.

### ISSUE THREAD

**Issue by ShreyasAch** [primefaces/primevue#4721]
### Describe the bug

Hello team, i am using primevue lastest verion in our Nuxt3 project and i have a datatable which display certain data. Among that data i have a property called total for which i am trying to apply rowClass function. But the function is not working consistently i.e few hours back it worked like a charm but with no code changes its not working anymore. 

Component code:
DataTable  :rowClass="rowClassfn"  v-model:selection="selectedEntries"  :value="defaultData" 
            Column field="code" header="Code" Column
            Column field="name" header="Name" Column
            Column field="total" header="Total" Column
 DataTable
 
 For information:
 I have represented the above code without proper tags as it was not reflecting in the error panel. In code i have maintained 
  the syntax of the DataTable.
  
rowClass function :
const rowClassfn = (data) => {
    return [{ 'bg-gray-100': data.total === 0}];
};

In the above code i am trying to apply gray backgorund to those records whose value of total property is 0, but its not applying the class consistently into the table. Expecting your response to this issue as soon as possible.

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.38.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

chrome

**Comment by tugcekucukoglu** [comment]
Could you update the reproducer link?
