### ISSUE TITLE
DataTable: #loading templates broken with lazy virtual scroller

### ISSUE THREAD

**Issue by zachlearnscode** [primefaces/primevue#4723]
### Describe the bug

It appears an update sometime after 3.31 has broken the loading templates on lazy loaded, virtual scroller datatables.

Repro is link to PrimeVue example for that component linked in the docs here: https://primevue.org/datatable/#lazy_virtualscroll

### Reproducer

https://stackblitz.com/edit/wdtncx?file=src%2FApp.vue

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to repro link
After the table loads, scroll anywhere in the table beyond the initial set of loaded results
Note that the #loading templates do not appear (the table appears completely empty)
Scroll back to the top of the table
Note that the #loading templates appear for the very first set of results
Continue to scroll anywhere in the table but within range of the first set of results at the top
Note that the #loading templates do not appear

### Expected behavior

The loading templates should appear whenever the loading property in virtualScrollerOptions is true

**Comment by tugcekucukoglu** [comment]
Could you update the reproducer link?

**Comment by zachlearnscode** [comment]
Sorry about that. I have updated the the link. I had to fork the PV StackBlitz in order to share. If that doesn't work for whatever reason, the repro is the same code linked under Virtual Scroll > Lazy here: https://primevue.org/datatable/#lazy_virtualscroll

**Comment by zachlearnscode** [comment]
@tugcekucukoglu I ran a git bisect between versions 3.31 and 3.37 and it returned [this commit of yours from September](https://github.com/primefaces/primevue/commit/e6499c0365eca6d8bb709eb8c0b711c8d747fcff) as the commit that potentially introduced this issue. It looks like that code is tied to the [@layers implementation](https://github.com/primefaces/primevue/issues/4504).

Do you think the @layers implementation could have created this bug?

**Comment by zachlearnscode** [comment]
thank you!

**Comment by zachlearnscode** [comment]
@mertsincan So, the loading templates are behaving _differently_ than they were before, but they still appear to be broken.

Previously, all sets of results past the first failed to display the loading template. Now, you can see loading templates down to the second or third set up results, but they eventually move of out view.

Again, you can see the issue in the docs here: [https://primevue.org/datatable/#lazy_virtualscroll](url)

Should we reopen this issue?

**Comment by zachlearnscode** [comment]
@mertsincan Please see my comment above

**Comment by LuckyShuii** [comment]
Would be cool to have this fixed
