### ISSUE TITLE
Menubar: menus overflow out of the window when justified right

### ISSUE THREAD

**Issue by tmlmt** [primefaces/primevue#4724]
### Describe the bug

When a Menubar is justified to the right of the window, dropdowns overflow outside of it, especially when the submenu items are longer than the parent item. See screenshot: 

![image](https://github.com/primefaces/primevue/assets/10244927/a1afbe70-bf81-4e74-9aa2-22b51892bd3d)

### Reproducer

https://codesandbox.io/p/sandbox/floral-morning-x7kt2q?file=%2Fsrc%2FApp.vue%3A12%2C3

### PrimeVue version

3.38.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open Menu
2. Observe that the label in the dropdown is not entirely visible

### Expected behavior

I would expect the dropdown to be positioned from the right of the window and extending to the left

**Comment by tugcekucukoglu** [comment]
We will work on the responsiveness of not only the Menubar but also all Overlay panels. Definitely in our roadmap.

Thank you!
