### ISSUE TITLE
OverlayPanel: Hides when entering data into InputText

### ISSUE THREAD

**Issue by AydarVess** [primefaces/primevue#4725]
### Describe the bug

Bug Description:
The OverlayPanel component from PrimeVue is exhibiting unexpected behavior. When entering data into the InputText element within the OverlayPanel, the text entered is not saved in the value variable, and, more critically, the OverlayPanel closes after the first keypress.

This behavior is inconsistent with the expected behavior, where the OverlayPanel should remain open while data is being entered into the InputText.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-xfl3md?file=%2Fsrc%2FApp.vue%3A5%2C28

### PrimeVue version

3.38.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Click on the Button to open the OverlayPanel.
2. Inside the OverlayPanel, there is an InputText.
3. Click on the InputText and start entering text.

### Expected behavior

When entering data into InputText, the text should be saved in the value variable, and the OverlayPanel should not hide.

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primevue/issues/4712
