### ISSUE TITLE
Remove vue-router support from Menu components

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#4739]
- [x] Breadcrumb
- [x] ContextMenu
- [x] Dock
- [x] Menu
- [x] Menubar
- [x] MegaMenu
- [x] PanelMenu
- [x] Steps
- [x] TabMenu
- [x] TieredMenu

**Comment by Payn** [comment]
Hello @tugcekucukoglu 
how to use routing with TabMenu now? Or any other way to display different views based on active tab?
Thanks

**Comment by mikecbone** [comment]
@Payn You can do something like this:

```vue
<template>
  <TabMenu :model="menuItems" :active-index="activeMenuItemIndex">
    <template #item="{ item, props }">
      <router-link v-if="item.route" v-slot="{ href, navigate }" :to="item.route" custom>
        <a :href="href" v-bind="props.action" @click="navigate">
          <span :class="item.icon" />
          <span class="ml-2">{{ item.label }}</span>
        </a>
      </router-link>
    </template>
  </TabMenu>
</template>

<script setup>
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();

const activeMenuItemIndex = ref(0);

const menuItems = [
  { label: 'MyTabOne', icon: 'pi pi-fw pi-code', route: '/tabone' },
  { label: 'MyTabTwo', icon: 'pi pi-fw pi-book', route: '/tabtwo' },
  { label: 'MyTabThree', icon: 'pi pi-fw pi-id-card', route: '/tabthree' },
];

watch(
  () => route.path,
  (updatedPath) => {
    activeMenuItemIndex.value = menuItems.findIndex((item) => updatedPath.startsWith(item.route));
  },
  { immediate: true }
);
</script>
```

The `watch` is similar to vue-routers [active class](https://router.vuejs.org/api/interfaces/RouterLinkProps.html#activeClass). You could do something like
```js
activeMenuItemIndex.value = menuItems.findIndex((item) => item.route === updatedPath );
```
for the [exact active class](https://router.vuejs.org/api/interfaces/RouterLinkProps.html#exactActiveClass).

**Comment by Payn** [comment]
Awesome, this works. Thank you.

**Comment by Yonaro** [comment]
Any reason on why this has been removed?

**Comment by vinodkola1337** [comment]
> Any reason on why this has been removed?

You can find the explanation [here](https://github.com/primefaces/primevue/issues/4633#issuecomment-1827780322).

**Comment by zanyar3** [comment]
-1, why has removed?

**Comment by erropix** [comment]
@tugcekucukoglu This is a breaking change and yet not mentioned in the [3.40 changelog](https://github.com/primefaces/primevue/releases/tag/3.40.0)?

**Comment by sey** [comment]
We just discovered about this change. I think it is a big issue to use semantic versioning and introduce a breaking change in minor version bump.
