### ISSUE TITLE
MultiSelect Name: prop overshadowing

### ISSUE THREAD

**Issue by petitkriket** [primefaces/primevue#4743]
### Describe the bug

https://github.com/primefaces/primevue/pull/4588/files

`this.$primevue.config.locale.selectionMessage`over shadows selectedItemsLabel when set and prevent any "contexutal" use

1. having a global "generic" translation with "items" "elements" or whatever
2. having a component and "local" and component specific translation matching the local context of the developer that needs the component

### Reproducer

https://stackblitz.com/edit/ejwndf-bepfox?file=src%2FApp.vue

### PrimeVue version

3.39.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1.set a translation via the global API (in main.js)
1.set a  local and contextual translation via the 

### Expected behavior

setting a global translation should work
setting a local translation via the prop should work.

local overrides the global API (similar as the pass through API)

**Comment by petitkriket** [comment]
i dont get how can i promote a change from a fork but i believe inverting this assingation order would do the trick

https://github.com/petitkriket/primevue/pull/1/files

**Comment by tugcekucukoglu** [comment]
Thank you for your contribution!
