### ISSUE TITLE
splitterpanel:  TypeError: this.$slots.default is not a function

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#4746]
### Describe the bug

splitterpanel.esm.js:31 Uncaught (in promise) TypeError: this.$slots.default is not a function
    at Proxy.isNested (splitterpanel.esm.js:31:35)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at Object.get [as isNested] (runtime-core.esm-bundler.js:3407:22)
    at Object.get (runtime-core.esm-bundler.js:2931:16)
    at Proxy.getPTOptions (splitterpanel.esm.js:38:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at Object.get [as getPTOptions] (runtime-core.esm-bundler.js:3407:22)
    at Proxy.render$8 (paginator.esm.js:140:15)
isNested @ splitterpanel.esm.js:31
run @ reactivity.esm-bundler.js:178
get value @ reactivity.esm-bundler.js:1147
get @ runtime-core.esm-bundler.js:3407
get @ runtime-core.esm-bundler.js:2931
getPTOptions @ splitterpanel.esm.js:38
run @ reactivity.esm-bundler.js:178
get value @ reactivity.esm-bundler.js:1147
get @ runtime-core.esm-bundler.js:3407
render$8 @ paginator.esm.js:140
renderComponentRoot @ runtime-core.esm-bundler.js:816
componentUpdateFn @ runtime-core.esm-bundler.js:5701
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5814
setupRenderEffect @ runtime-core.esm-bundler.js:5822
mountComponent @ runtime-core.esm-bundler.js:5612
processComponent @ runtime-core.esm-bundler.js:5565
patch @ runtime-core.esm-bundler.js:5040
mountChildren @ runtime-core.esm-bundler.js:5284
processFragment @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5014
mountChildren @ runtime-core.esm-bundler.js:5284
processFragment @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5014
mountChildren @ runtime-core.esm-bundler.js:5284
mountElement @ runtime-core.esm-bundler.js:5191
processElement @ runtime-core.esm-bundler.js:5156
patch @ runtime-core.esm-bundler.js:5028
mountChildren @ runtime-core.esm-bundler.js:5284
processFragment @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5014
mountChildren @ runtime-core.esm-bundler.js:5284
mountElement @ runtime-core.esm-bundler.js:5191
processElement @ runtime-core.esm-bundler.js:5156
patch @ runtime-core.esm-bundler.js:5028
componentUpdateFn @ runtime-core.esm-bundler.js:5773
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5814
updateComponent @ runtime-core.esm-bundler.js:5641
processComponent @ runtime-core.esm-bundler.js:5576
patch @ runtime-core.esm-bundler.js:5040
patchBlockChildren @ runtime-core.esm-bundler.js:5427
patchElement @ runtime-core.esm-bundler.js:5319
processElement @ runtime-core.esm-bundler.js:5167
patch @ runtime-core.esm-bundler.js:5028
componentUpdateFn @ runtime-core.esm-bundler.js:5773
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5814
updateComponent @ runtime-core.esm-bundler.js:5641
processComponent @ runtime-core.esm-bundler.js:5576
patch @ runtime-core.esm-bundler.js:5040
patchBlockChildren @ runtime-core.esm-bundler.js:5427
processFragment @ runtime-core.esm-bundler.js:5513
patch @ runtime-core.esm-bundler.js:5014
patchBlockChildren @ runtime-core.esm-bundler.js:5427
patchElement @ runtime-core.esm-bundler.js:5319
processElement @ runtime-core.esm-bundler.js:5167
patch @ runtime-core.esm-bundler.js:5028
componentUpdateFn @ runtime-core.esm-bundler.js:5773
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5814
callWithErrorHandling @ runtime-core.esm-bundler.js:158
flushJobs @ runtime-core.esm-bundler.js:357
09:19:23.414 paginator.esm.js:140 Uncaught (in promise) TypeError: $options.getPTOptions is not a function
    at Proxy.render$8 (paginator.esm.js:140:15)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5701:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)
    at updateComponent (runtime-core.esm-bundler.js:5641:18)
    at processComponent (runtime-core.esm-bundler.js:5576:7)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at patchBlockChildren (runtime-core.esm-bundler.js:5427:7)
    at processFragment (runtime-core.esm-bundler.js:5513:9)

![image](https://github.com/primefaces/primevue/assets/16963395/631f3233-4bc4-4d8c-bc28-83648b834a81)

### Reproducer

no

### PrimeVue version

last

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Could you tell us your environment?

**Comment by NeluQi** [comment]
Vue3 + vite + ionic + primevue

**Comment by Marchiuzzz** [comment]
+1 having the same issue, also getting a bunch of these, might be related (custom warning formatter):
```
PrimeVue inject missing: $pcAccordionPanel
vue-warn.client.ts:10 Vue trace: at <Paginator>
at <Categories>
at <ObjectListFilters>
at <TabPanel>
at <TabPanels>
at <Tabs>
at <DynamicSources>
at <BaseTransition>
at <Transition>
at <Portal>
at <Dialog>
at <DialogWrapper>
at <DynamicSources>
at <ClientOnly>
at <SourceManager>
at <BaseTransition>
at <Transition>
at <Portal>
at <Dialog>
at <DialogWrapper>
at <DynamicSourceWizard>
at <Management>
at <Text>
at <Text>
at <SplitterPanel>
at <Splitter>
at <BaseTransition>
at <Transition>
at <Portal>
at <Dialog>
at <DialogWrapper>
at <PageContentCreateEdit>
at <ClientOnly>
at <ProblemBuilder>
at <RouteProvider>
at <RouterView>
at <NuxtPage>
at <Admin>
at <AsyncComponentWrapper>
at <LayoutLoader>
at <NuxtLayoutProvider>
at <NuxtLayout>
at <App>
at <NuxtRoot>
```
```
PrimeVue inject missing: $pcAccordionPanel
vue-warn.client.ts:10 Vue trace: at <Accordion>
at <Categories>
at <ObjectListFilters>
at <TabPanel>
at <TabPanels>
at <Tabs>
at <DynamicSources>
at <BaseTransition>
at <Transition>
at <Portal>
at <Dialog>
at <DialogWrapper>
at <DynamicSources>
at <ClientOnly>
at <SourceManager>
at <BaseTransition>
at <Transition>
at <Portal>
at <Dialog>
at <DialogWrapper>
at <DynamicSourceWizard>
at <Management>
at <Text>
at <Text>
at <SplitterPanel>
at <Splitter>
at <BaseTransition>
at <Transition>
at <Portal>
at <Dialog>
at <DialogWrapper>
at <PageContentCreateEdit>
at <ClientOnly>
at <ProblemBuilder>
at <RouteProvider>
at <RouterView>
at <NuxtPage>
at <Admin>
at <AsyncComponentWrapper>
at <LayoutLoader>
at <NuxtLayoutProvider>
at <NuxtLayout>
at <App>
at <NuxtRoot>```
