### ISSUE TITLE
OverlayPanel toggle method not existing

### ISSUE THREAD

**Issue by ochiers** [primefaces/primevue#475]
Hello, 

I use PrimeVue in 2.0.0 and I have a problem with the toggle method on OverlayPanel.

VSCode says that :
![image](https://user-images.githubusercontent.com/5451658/92921054-ac554400-f433-11ea-8538-f4345681ec9f.png)

but my code is like the demo !

- view.component.ts

`public toggleTooltip(event): void {
    this.$refs.batchNumberOverlayRef.toggle(event);
  }`

- view.component.html

`<OverlayPanel
      ref="batchNumberOverlayRef"
      id="batchNumberOverlay"
      name="batchNumberOverlay"
      appendTo="body"
      style="width:300px"
    >
      <span v-text="$t('samplesChekApp.visit.infoSerialAndBatchNumber')"></span>
    </OverlayPanel>`

I don't understand why I don't have the same behavior.
Any help?

Thanks for read my post !

**Comment by cagataycivici** [comment]
Can you try with PrimeVue 2.0.9 please?
