### ISSUE TITLE
Errors in documentation for DynamicDialog component

### ISSUE THREAD

**Issue by jacobse** [primefaces/primevue#4752]
### Describe the bug

When using DynamicDialog in my application I found the following had to be done differently from the current documentation in order to get it to work.

### Passing Data
- In the code example (for the component being loaded) it has 'this.dialogRef.data', but I had to do 'this.dialogRef.value.data'

### Events
- In the code example (for the usage of this.$dialog) it has the event handler directly in the parameters object, but I had to instead wrap it in emits {}
- In the code example (for the component being loaded) it has emits defined/used as onCancel/onSave, but I had to emit just cancel

I have a PR to change the documentation code examples:
https://github.com/primefaces/primevue/pull/4753

### Reproducer

https://primevue.org/dynamicdialog/

### PrimeVue version

3.37.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Documentation is fixed. 

Thank you.
