### ISSUE TITLE
InputNumber doesn't update the v-model on @keyup.enter

### ISSUE THREAD

**Issue by imperator6** [primefaces/primevue#476]
In my use case i want to persist the entered number on key 'enter'.  

`v-model="object.mynumber" @keyup.enter="saveNumber"`

But the the model is not updated si that it contains still the old number.

**Comment by cagataycivici** [comment]
@mertsincan Wdyt?

**Comment by mertsincan** [comment]
Unfortunately, it is not possible with the keyup event. After v3.0 is released, you can use the "input" event for such issues. Please see the details;
https://github.com/primefaces/primevue/issues/506

Best Regards,
