### ISSUE TITLE
TabView: Missing type support for tabpanel when creating a global passthrough

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#4761]
### Describe the bug

There is missing type support on the TabPanelPassThroughMethodOptions which appears to have more properties than the type suggests. Looking at the screenshots below, you can see that the 'tabpanel' property is missing from the type.

![rider64_viHm0fkGpw](https://github.com/primefaces/primevue/assets/49190778/7e304d8f-7f6a-437c-8292-4eceaa860f99)
![chrome_cclj6AOS22](https://github.com/primefaces/primevue/assets/49190778/fbe6de91-e56e-4e8a-9347-244498c2262f)

The 'tabpanel' property gives access to data such as context, parent and props which I have found useful when styling the nav bar in the TabView i.e. setting classes on active tab etc. I suspect that this data should be accessible via context in the TabPanelPassThroughMethodOptions however trying to access this throws the following error:

`Cannot read properties of undefined (reading 'children')`

I believe this is happening due to context being undefined on the initial mount of the component.

As a temporary solution, I have extended the TabPanelPassThroughMethodOptions to include the 'tabpanel' property which I have typed as a Partial of the TabPanelPassThroughMethodOptions.

`headerAction: (options : TabPanelPassThroughMethodOptions & { tabpanel : Partial<TabPanelPassThroughMethodOptions>})`

I'm unsure if the tabpanel property is purposeful, if so it will require a simple update to the TabPanelPassThroughMethodOptions type which I am more than happy to commit.

### PrimeVue version

3.39.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a global passthrough object for tabpanel like so:

```
tabpanel: {
  
}

```
2. Add headerAction or any other passthrough option to the object with options

```
tabpanel: {
  headerAction: (option : TabPanelPassThroughMethodOptions) => {

  } 
}
````

3a. Try to access tabpanel object.
3b. Try using the active property in the context object.

### Expected behavior

I would expect to be able to access the context, parent and props objects via context instead of tabpanel,

**Comment by JakeMinor** [comment]
As mentioned in the description, if the solution is to add the 'tabpanel' property to the TabPanelPassThroughMethodOptions then I am more than happy to do so if my work around is suitable, please don't hesitate to ask :)

**Comment by tugcekucukoglu** [comment]
`tabpanel` is not a valid option for `headerAction`, but current tab options can be find using `context` and `props`. 

![Screenshot 2023-11-17 at 17 07 30](https://github.com/primefaces/primevue/assets/32294991/066e0cac-592c-45f4-9664-f10533892c2f)
