### ISSUE TITLE
Property "$primevue" was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by ancagavrilescu** [primefaces/primevue#4765]
### Describe the bug

Hi, 

We're creating a library which contains also wrapper components over primevue.
When we're trying to use for example, the ImageWrapper component inside other application we encounter the following error when we click on the image:
`Property "$primevue" was accessed during render but is not defined on instance. `
The component wrapper looks like this:
```
<template>
    <Image
        v-bind="{ ...$attrs, ...props }"
        :preview="true"
    >
        <template
            v-for="(_, slotName) in $slots as Readonly<ImageSlots>"
            #[slotName]="scope = {}"
            :key="slotName"
        >
            <slot
                :name="slotName"
                v-bind="scope"
            />
        </template>
    </Image>
</template>

<script setup lang="ts">
import Image, { ImagePassThroughOptions, ImageSlots } from 'primevue/image';
import { PassThrough } from 'primevue/ts-helpers';
import { PassThroughOptions } from 'primevue/passthrough';

export type ImageWrapperImagePassThroughOptions = ImagePassThroughOptions;
export type ImageWrapperPassThroughOptions = PassThroughOptions;

type ImageInstance = InstanceType<typeof Image>;
type ImageInstanceProps = ImageInstance['$props'];

const props = defineProps<{
    preview?: ImageInstanceProps['preview'];
    imageStyle?: ImageInstanceProps['imageStyle'];
    imageClass?: ImageInstanceProps['imageClass'];
    zoomInDisabled?: ImageInstanceProps['zoomInDisabled'];
    zoomOutDisabled?: ImageInstanceProps['zoomOutDisabled'];
    // pt?: ImageInstanceProps['pt'];
    pt?: PassThrough<ImageWrapperImagePassThroughOptions>;
    // ptOptions?: ImageInåstanceProps['ptOptions'];
    ptOptions?: ImageWrapperPassThroughOptions;
    unstyled?: ImageInstanceProps['unstyled'];
}>();
</script>
```

Can you please help us?

### PrimeVue version

3.36.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by ancagavrilescu** [comment]
Hi, 

I'm not sure how can I reproduce the issue with the current applications for this, but if you create a library which contains a wrapper component over Image component (component wrapper from the issue's description) from the primevue and try to use this library inside another application you'll be able to reproduce it.

The workaround we implemented for this is to export PrimeVue from 'primevue/config'.

Thank you!

**Comment by micheldpcarlos** [comment]
Hi @anca987, I'm also creating a custom component lib using PrimeVue as a base; how did you get InstanceType working on Vue 3? I'm getting an error on build:

error during build:
Error: [vite:vue] [@vue/compiler-sfc] Unresolvable type reference or unsupported built-in utility type

Base/Button.vue
8  |  });
9  |  
10 |  type ButtonProps = InstanceType<typeof Button>['$props']
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |  type ButtonSlots = InstanceType<typeof Button>['$slots']

**Comment by anca987** [comment]
Hello @micheldpcarlos,

Sorry for my late reply, not sure if will help you, because if you want to have also some custom theming is not a good solution, it will bring with it the primevue theme...
I exported PrimeVue ( from 'primevue/config') in my index.ts.

If you found another solution, please let me know :).

**Comment by micheldpcarlos** [comment]
Thanks @anca987 

I addressed this issue by exporting a plugin to install PrimeVue unstyled. I'm having issues with the types and not being able to use InstanceType :/

**Comment by anca987** [comment]
How did you make it unstyled? 😃 

If I understood you correct I solved this (but I'm really not proud of this solution) like this:
`<template>
    <Chips
        class="nshine-vue"
        v-bind="{ ...$attrs, ...props }"
        @add="add"
        @remove="remove"
        @update:model-value="(value: any[]) => emit('update:modelValue', value)"
    >
        <template
            v-for="(_, slotName) in $slots as Readonly<ChipsSlots>"
            #[slotName]="scope = {}"
            :key="slotName"
        >
            <slot
                :name="slotName"
                v-bind="scope"
            />
        </template>
    </Chips>
</template>

<script setup lang="ts">
import type { ChipsAddEvent, ChipsRemoveEvent, ChipsSlots } from 'primevue/chips';
import Chips from 'primevue/chips';

export type ChipsWrapperAddEvent = ChipsAddEvent;
export type ChipsWrapperRemoveEvent = ChipsRemoveEvent;

type ChipsInstance = InstanceType<typeof Chips>;
type ChipsInstanceProps = ChipsInstance['$props'];

const props = defineProps<{
    modelValue?: ChipsInstanceProps['modelValue'];
    max?: ChipsInstanceProps['max'];
    addOnBlur?: ChipsInstanceProps['addOnBlur'];
    allowDuplicate?: ChipsInstanceProps['allowDuplicate'];
    separator?: ChipsInstanceProps['separator'];
    inputId?: ChipsInstanceProps['inputId'];
    inputClass?: ChipsInstanceProps['inputClass'];
    inputStyle?: ChipsInstanceProps['inputStyle'];
    disabled?: ChipsInstanceProps['disabled'];
    placeholder?: ChipsInstanceProps['placeholder'];
    ariaLabelledby?: ChipsInstanceProps['ariaLabelledby'];
    ariaLabel?: ChipsInstanceProps['ariaLabel'];
    pt?: ChipsInstanceProps['pt'];
    ptOptions?: ChipsInstanceProps['ptOptions'];
    unstyled?: ChipsInstanceProps['unstyled'];
}>();

const emit = defineEmits(['update:modelValue', 'add', 'remove']);
const add = (payload: ChipsWrapperAddEvent) => {
    emit('add', payload as ChipsAddEvent);
};
const remove = (payload: ChipsWrapperRemoveEvent) => {
    emit('remove', payload as ChipsRemoveEvent);
};
</script>
`
You can decide which properties you want to extend...

**Comment by micheldpcarlos** [comment]
Thanks for sharing @anca987 

I'm using PrimeVue unstyled + Tailwind, so I had to export this plugin to be used in my app that uses my custom ui-lib.

It installs PrimeVue unstyled instance and global directives and services.

> plugins/primeVuePlugin.ts
```
import PrimeVue from 'primevue/config';
import ConfirmationService from 'primevue/confirmationservice';
import Ripple from 'primevue/ripple';
import ToastService from 'primevue/toastservice';
import Tooltip from 'primevue/tooltip';
import type { App } from 'vue';
 
/**
 * Install PrimeVue Plugin
 * this is required to set primevue services and configuration
 */
export default {
  install: (app: App<Element>) => {
    app.use(PrimeVue, {
      unstyled: true
    });
 
    app.use(ToastService);
    app.use(ConfirmationService);
 
    app.directive('tooltip', Tooltip);
    app.directive('ripple', Ripple);
  }
};

```
