### ISSUE TITLE
[Vue warn]: Failed to resolve directive: tooltip 

### ISSUE THREAD

**Issue by mahanteshaCloudMPower** [primefaces/primevue#4766]
### Describe the bug

When I try to use the tooltip, I get an error like this.

Nuxt 3
Node 20
npm 9
primevue 3
![Screenshot from 2023-11-07 13-16-12](https://github.com/primefaces/primevue/assets/80378935/8aa3481f-0894-4c41-a355-23e56d8cdf0d)
primeval

### Reproducer

https://codesandbox.io/p/sandbox/friendly-parm-dgn9nl?file=%2Fsrc%2FApp.vue%3A11%2C74

### PrimeVue version

3.39.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

Chrome 

### Steps to reproduce the behavior

When I try to use the tooltip, I receive an error like this.

1. I'm using this as an input field and button. 

### Expected behavior

when I use npm run dev to run the project

**Comment by tugcekucukoglu** [comment]
Reproducer demo seems working correctly. Tooltip should be imported globally or locally.

`import Tooltip from 'primevue/tooltip';`
