### ISSUE TITLE
Regarding CSP (Issue 4241)

### ISSUE THREAD

**Issue by OliverTr54** [primefaces/primevue#4770]
Hey there,

I was trying to implement CSP "nonce" as mentioned in issue 4241, but it won't work for inline style elements in my case.

Could you possibly provide a complete example?

Thanks in advance,
Oliver

**Comment by tugcekucukoglu** [comment]
Hi,

Could you try to use with latest version?

```
app.use(PrimeVue, {
    csp: {
        nonce: '...'
    }
});
```
