### ISSUE TITLE
Dropdown: Stuck in place on scroll if parent is sticky

### ISSUE THREAD

**Issue by aguyfromdenmark** [primefaces/primevue#4771]
### Describe the bug

If a Dropdown is a child of an element which has `position:sticky;`, scrolling the browser window will leave the dropdown stuck in place. 

This seems to be because the dropdown's position is position:absolute; and the offset calculated is calculated from the top of the document. 

I guess, if this has to work, there will need to be a check if a parent is position:sticky;, and the calculate the offset from the top of the browser window, and the re-calculate the offset on every scroll event. 

### Reproducer

https://codesandbox.io/p/sandbox/goofy-cannon-xq97yl

### PrimeVue version

3.29.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Expected behavior

The dropdown options stay connected to the dropdown itself on scroll.

**Comment by tugcekucukoglu** [comment]
The default value of the `appendTo` property is `body`. If you're using position: sticky and don2t break default behavior, you should set the `appendTo` property as `self`.

**Comment by aguyfromdenmark** [comment]
@tugcekucukoglu That information should be added to the documentation then. There is no mention of an `appendTo` property here https://primevue.org/dropdown/.

**Comment by tugcekucukoglu** [comment]
You could find from API section: https://primevue.org/dropdown/#api.dropdown.props.appendTo

**Comment by aguyfromdenmark** [comment]
Got it working @tugcekucukoglu . I wrote it as `:appendTo="self"`, which did not work. `appendTo="self"` did work.
