### ISSUE TITLE
MultiSelect: in Chrome, opening a MultiSelect can break my layout

### ISSUE THREAD

**Issue by justinrlle** [primefaces/primevue#4773]
### Describe the bug

Given that: 
I have an SPA with the following CSS :
```css
html, body {
  overflow: hidden;
  height: 100%;
}
```
And that I have a `MultiSelect` outside of the viewport, so that I need to scroll to see it,
If I click on the `MultiSelect`, the layout gets broken.

https://github.com/primefaces/primevue/assets/10925994/daaf30c7-4f8f-41ec-a9ef-a3d8635032e0

If I wrap the `MultiSelect` with a `<div class="relative">` (as suggested in https://github.com/primefaces/primevue/issues/4469#issuecomment-1731053135), the layout is not broken anymore when opening the `MultiSelect`.

### Reproducer

https://stackblitz.com/edit/ix5nvq?file=src%2FApp.vue

### PrimeVue version

3.39.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Click on the `MultiSelect` and on the `Dropdown` at the top, nothing breaks.
2. Scroll down to the other `MultiSelect` and `Dropdown`, at the middle of the page
3. Click on the `Dropdown` on the right, nothing weird happens
4. Click on the `MultiSelect` on the left, the layout get's broken.

If you wrap the `MultiSelect` in a `<div class="relative">`, it works again correctly

### Expected behavior

The page layout is not modified.

**Comment by justinrlle** [comment]
Another fix is to add 
```js
app.use(PrimeVue, {
  pt: {
    multiselect: {
      root: { class: 'relative' },
    },
  },
});
```
To the PrimeVue configuration, and where `relative` is a tailwind class adding `position: relative`. So maybe just adding this CSS prop to the root container of the `MultiSelect` should fix this?

**Comment by tugcekucukoglu** [comment]
It seems the solution solves the demo problem.

Thanks for the update.

**Comment by tombreplacer** [comment]
Thanks, the solution worked for me too. The multiselect now behaves like a dropdown, opening to the side where space is available.
