### ISSUE TITLE
Button not registered in FileUpload

### ISSUE THREAD

**Issue by bgorhoball** [primefaces/primevue#478]
Hello, 

I am using primevue 2.0.9 and have some questions on FileUpload -

1.  Icon of item remove button
The icon to remove the items on the RHS could not be rendered as shown below. It seems the [Button](https://github.com/primefaces/primevue/blob/master/src/components/fileupload/FileUpload.vue#L23) component is not yet registered in the [components](https://github.com/primefaces/primevue/blob/master/src/components/fileupload/FileUpload.vue#L402)
![image](https://user-images.githubusercontent.com/47683197/93066920-22181480-f6ad-11ea-82ad-7a872a2f326a.png)

2. webkitdirectory support for the input tag
As per the MDN [web](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory), is it possible to have 'webkitdirectory' added as a property just like 'multiple'? 

I could create PR if needed. Thanks a lot!

**Comment by cagataycivici** [comment]
For directory support, please monitor;

https://github.com/primefaces/primevue/issues/499
