### ISSUE TITLE
InputSwitch: Emit two events upon single click if wrapped by <label> tag.

### ISSUE THREAD

**Issue by Andrey-Buldyshev** [primefaces/primevue#4781]
### Describe the bug

Single click on InputSwitch wrapped by <label> leads to two events instead of one.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-demo-forked-3f5rcc

### PrimeVue version

3.30.0 or greater

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1) Wrap InputSwitch component by html tag <label>

 ```
<label>
  <InputSwitch
     v-model="value"
    @input="toggled"
  />
  <span>InputSwitch label</span>
</label>
```

2) Click on InputSwitch 
3) Observe that toggled function executed two times (it changes value from false to true and then from true to false)
4) Click on `InputSwitch label` 
5) Observe that toggled function executed one time as expected

Also you can use the next example to reproduce the issue: https://codesandbox.io/p/sandbox/primevue-demo-forked-3f5rcc

Click on InputSwitch and see in dev tools that it prints two messages:
```
InputSwitch was toggled. Current value is true
InputSwitch was toggled. Current value is false
```

Note: wrapping `input` by `label` tag is common practice and valid scenario. Also In some cases it is only possible solution.

More info:
Breaking change was done during transition from 3.29.2 to 3.30.0 when `event.preventDefault();` was removed.
Link to compare https://github.com/primefaces/primevue/compare/3.29.2...3.30.0

![Screenshot 2023-11-08 at 13 32 49](https://github.com/primefaces/primevue/assets/5293099/d57ddf18-8324-4a1d-b137-e93965557f4f)

### Expected behavior

`change/click/input/update:modelValue` should happen only once if we click on InputSwitch or on label.

**Comment by tugcekucukoglu** [comment]
Please try to use the version 3.43.0. The issue is fixed for the earlier versions.
