### ISSUE TITLE
Prime Vue Issue -Lara-light theme missing layer after update and doesn't work

### ISSUE THREAD

**Issue by mpellegrini88** [primefaces/primevue#4787]
### Describe the bug

After setting up the editor with the visual configurator, we attempted to implement the lara-light-blue theme but noticed that it doesn't work. Upon inspecting the theme, we realized that the layer is missing. It's urgent because we need to implement the theme as soon as possible.

### Reproducer

https://codesandbox.io/p/sandbox/wild-tdd-k9rmn9?file=%2Fpublic%2Ftheme.css%3A1%2C1-7059%2C1

### PrimeVue version

PrimeVue 3.28.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

implement theme and see that the borders and the rendering of the default styling of some components fail.
I made a sample on codebox bu it doesn't show the behaviour properly. It seems to work correctly but when i download a new theme from visual editor and try to implement it components styling is not what it's supposed to be.

### Expected behavior

theme has to work properly and the components needs to be render accordingly

**Comment by mpellegrini88** [comment]
*we are currently using version 3.39 not 3.28

**Comment by tugcekucukoglu** [comment]
PrimeVue uses @layer css. With the latest version theme.css needs @layer rules. All classes must be below @layer primevue{} except for the styles of @:root, @font-face, Editor, and FullCalendar. 

```
@layer primevue {
    * {
    box-sizing: border-box;
  }

  .p-component {
    font-family: var(--font-family);
    font-feature-settings: var(--font-feature-settings, normal);
    font-size: 1rem;
    font-weight: normal;
  }

  ...
}

```

**Comment by sdiricco-move** [comment]
Will you also update the version of https://designer.primevue.org/#/ to be able to configure the theme correctly?
