### ISSUE TITLE
Calendar date selection on enter key

### ISSUE THREAD

**Issue by tudorels** [primefaces/primevue#479]
Hello, 

It would be nice to have date selection on enter key, especially if user enter manually the date is more easy to press enter on keyboard and automatically entered date is selected and calendar popup close.
Thanks!

**Comment by cagataycivici** [comment]
It is available, you need to focus to the field first to open the calendar then hit the down arrow to open move focus into the navigators, now you are in the DatePicker, hit the tab to add focus to the current date and use arrow keys and enter to select it.
