### ISSUE TITLE
DataTable: Header is not applying sticky class when using unstyled and tailwind

### ISSUE THREAD

**Issue by Bene-Graham** [primefaces/primevue#4790]
### Describe the bug

When setting a column the header cells are not getting the sticky class. The body cell do get the sticky class.

### Reproducer

https://codesandbox.io/p/sandbox/adoring-hodgkin-kq77wm

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox, Chrome

### Expected behavior

The header cell get the sticky class applied to them just click the body cells.

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. Could you please send a runnable sample link for us to replicate? For now, closed. If the problem persists with the latest version, please reopen this ticket or create a new issue. Thanks a lot for your understanding!

Best Regards,
