### ISSUE TITLE
Panel: p-panel-header-icon override severity

### ISSUE THREAD

**Issue by gimler** [primefaces/primevue#4796]
### Describe the bug

When you add a header icon to panel component it ignores the severity.

See example the cog icon should be red.

### Reproducer

https://stackblitz.com/edit/xvxwwz?file=src%2FApp.vue

### PrimeVue version

3.40.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

The cog icon is red the severity is used

**Comment by tugcekucukoglu** [comment]
`p-panel-header-icon` can be removed or `pt` property can be used to override styles.
