### ISSUE TITLE
Button: rounded icon only buttons ignore size

### ISSUE THREAD

**Issue by gimler** [primefaces/primevue#4799]
### Describe the bug

See example. All rounded icon only buttons have the same size.

### Reproducer

https://stackblitz.com/edit/udg8wc?file=src%2FApp.vue

### PrimeVue version

3.40.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for the reproducer link. Please check `p-button-icon` classes from the dev tools, all rounded buttons have different font-size.
