### ISSUE TITLE
Menu: Incorrect props in Pass Through in MenuItem

### ISSUE THREAD

**Issue by johnluxor** [primefaces/primevue#4802]
### Describe the bug

Hello!

I have a Menu component and trying to stylize it via pass-through options.

```JS
menu: {
    root: ({ props, context }) => ({
      class: [
        { 'bg-white shadow-xl border border-neutral-50 rounded-lg overflow-hidden': props?.popup },
      ],
    }),
    menu: {
      class: ['m-0 p-0 list-none', 'outline-none'],
    },
    menuItem: ({ props, context }) => ({   // PROPS here is item props, not menu
      class: [
        'last:border-t hover:bg-secondary-500 hover:text-white rounded-lg transition-colors duration-100',
      ],
    }),
  },
```

in `props` in the menuItem section I expect Menu Props as it is said in docs, but I got props of the item. It might be correct, but I cannot change the style of MenuItem depending on some props. In my case I have different styles depending on `popup` prop 

### Reproducer

n/a

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

N/A

### Steps to reproduce the behavior

Hello!

I have a Menu component and trying to styllize it via pass through options.

```JS
menu: {
    root: ({ props, context }) => ({
      class: [
        { 'bg-white shadow-xl border border-neutral-50 rounded-lg overflow-hidden': props?.popup },
      ],
    }),
    menu: {
      class: ['m-0 p-0 list-none', 'outline-none'],
    },
    menuItem: ({ props, context }) => ({   // PROPS here is item props, not menu
      class: [
        'last:border-t hover:bg-secondary-500 hover:text-white rounded-lg transition-colors duration-100',
      ],
    }),
  },
```

in `props` in the menuItem section I expect Menu Props as it is said in docs, but I got props of the item. It might be correct, but I cannot change the style of MenuItem depending on some props. In my case I have different styles depending on `popup` prop 

### Expected behavior

I expect Menu props or access to Menu(parent) props via child

**Comment by tugcekucukoglu** [comment]
Hello,

props provides component options and context option provides menuitem options. https://primevue.org/menu/#api.menu.interfaces.MenuContext

**Comment by johnluxor** [comment]
I know it, that is what I described. The problem is I cannot stylize MenuItem depending on Menu is popup or not, because in MenuItem doesn't have access to parent props. Maybe there is another way to do it?
In general - I use Menu component in two cases - like popup and like not popup and it has different styles depending on it.

**Comment by hlohrenz** [comment]
I'm running into this issue too. I can't have unique menu styles based on if it's in a popup or not. This is extremely unfortunate that this hasn't been paid attention to since 2023 and it's 2026 :( There's still no solution?
