### ISSUE TITLE
Menu: Property 'item' does not exist on type '{ submenuheader: MenuItem; }'

### ISSUE THREAD

**Issue by apiret** [primefaces/primevue#4810]
### Describe the bug

I added `lang="ts"` to the example at https://primevue.org/menu/#template. When I ran the command `vue-tsc --noEmit`, I got the following error:
`
error TS2339: Property 'item' does not exist on type '{ submenuheader: MenuItem; }'.
<template #submenuheader="{ item }">
`

Here are the versions of TypeScript and vue-tsc that I am using:
"typescript": "^5.2.2",
"vue-tsc": "^1.8.22"

Thank you for your help!

### Reproducer

/

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/4809
