### ISSUE TITLE
Scrollable Table alignment improvement #462

### ISSUE THREAD

**Issue by mr83-uw** [primefaces/primevue#482]
This update will cause a misaligned table when a scroll height is set and there are too few elements in the table to render the scroll bar on the body of the table.

**Comment by cagataycivici** [comment]
This was fixed in PrimeReact and PrimeNG, @mertsincan please do the same for 3.0.0-rc.1 and 2.1.0.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/bfa9f99dc614e3b42fc16b719345547f635093e7

**Comment by cagataycivici** [comment]
We should also port this to 2.1.0.
