### ISSUE TITLE
Inplace: Spacing issue between Input and Closebutton

### ISSUE THREAD

**Issue by navedqb** [primefaces/primevue#4828]
### Describe the bug

![Inplace](https://github.com/primefaces/primevue/assets/109583873/5758780b-4191-4f8f-b81b-f908f1b3cf20)

No space between input and closebutton.

### Reproducer

https://primevue.org/inplace/#input

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://primevue.org/inplace/#input
2. Click on 'Click to Edit'
3. There is no space between input and closebutton

### Expected behavior

There should be adequate space between input and closebutton.

**Comment by tugcekucukoglu** [comment]
Spacing can be changed by the user because `content` slot have controls here.

Thank you.
