### ISSUE TITLE
When using datatable with scrollable + virtualScroll + lazy, columns needs for a #loading template

### ISSUE THREAD

**Issue by mdartic** [primefaces/primevue#483]
Hello,

I'm using the datatable component, with a scrollable + virtualScroll + lazy enabled.

When displaying data, I see a lot of errors in my console, coming from here : https://github.com/primefaces/primevue/blob/master/src/components/datatable/ColumnSlot.vue#L23

I read again your virtualscroll example (https://primefaces.org/primevue/showcase/#/datatable/scroll), and discover you define for each column a template for the `#loading` slot.

I did this, and this is working.

I was asking myself why is it mandatory, and why not define it "by default" in the [TableLoadingBody](https://github.com/primefaces/primevue/blob/master/src/components/datatable/TableLoadingBody.vue) if there is no `$scopedSlots` named `loading` for the current column `col` ?

**Comment by cagataycivici** [comment]
VirtualScroll implementation will be redone in near future and we'll add the necessary enhancements. Closing as this issue applies to the old implementation. Thank you.
