### ISSUE TITLE
Dropdown: Selected value not shown using filter when contentValue is used

### ISSUE THREAD

**Issue by DanRoddis** [primefaces/primevue#4838]
### Describe the bug

**REOPENED FROM https://github.com/primefaces/primevue/issues/4456**

Issue still exists

![image](https://github.com/primefaces/primevue/assets/394947/c09bc62c-7eb4-47c4-8f54-fc5c44be6725)

Spain is selected in the screenshot above but when the selected item is filtered out it looks like there is no longer a selection, I'd expect Spain to still be shown as the selected item rather than 'Select a country'

Describe the bug
When using the Dropdown control when a contentValue is selected e.g. an id property when filtering the placeholder is shown rather than the detail of the selected item.

Issue is visible in the following StackBlitz, select an option, then filter for another option - the placeholder content is displayed rather than the selected option.

https://stackblitz.com/edit/suqusr?file=src%2FApp.vue

Rather than having to specify a template for the slot the default should be that the selected item is always displayed rather than the placeholder.

Reproducer
https://stackblitz.com/edit/suqusr?file=src%2FApp.vue

PrimeVue version
3.34.0

Vue version
3.x

Language
TypeScript

Build / Runtime
Vue CLI App

Browser(s)
No response

Steps to reproduce the behavior
Go to https://stackblitz.com/edit/suqusr?file=src%2FApp.vue
Select an option in the dropdown
Filter the dropdown to not include the selected option
The selection option is no longer displayed in the selection area and instead the placeholder is displayed

Expected behavior
Go to https://stackblitz.com/edit/suqusr?file=src%2FApp.vue
Select an option in the dropdown
Filter the dropdown to not include the selected option
The selected option is always displayed in the selection area while it is selected

### Reproducer

https://stackblitz.com/edit/suqusr?file=package.json

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Go to https://stackblitz.com/edit/suqusr?file=src%2FApp.vue
Select an option in the dropdown
Filter the dropdown to not include the selected option
The selection option is no longer displayed in the selection area and instead the placeholder is displayed

### Expected behavior

Go to https://stackblitz.com/edit/suqusr?file=src%2FApp.vue
Select an option in the dropdown
Filter the dropdown to not include the selected option
The selected option is always displayed in the selection area while it is selected

**Comment by tugcekucukoglu** [comment]
This behavior prevents using #value slot. 

```
 <template #value="slotProps">
        <div v-if="slotProps.value">
            <div>{{ slotProps.value.name }}</div>
        </div>
        <span v-else>
            {{ slotProps.placeholder }}
        </span>
    </template>
```

As I mentioned before, you're demo working correctly. Also, I want to share a live demo: https://primevue.org/dropdown/#filter
