### ISSUE TITLE
Resize support for ColumnGroup

### ISSUE THREAD

**Issue by Alpiag** [primefaces/primevue#484]
Hi

We have seen that when we activate ColGroups in a DataTable (PRIME VUE), It's not possible to perform column resize

Are you going to include this feature soon?

Best Regards

**Comment by cagataycivici** [comment]
NG and React also do not support this, only PrimeFaces does with a complex implementation. It is on our roadmap.

**Comment by cagataycivici** [comment]
Closing due to lack of demand from the community. We'll add it to the roadmap if more users require the function.

**Comment by mauritsderoover** [comment]
This would be a great feature for us to have. Has it been re-evaluated whether it will be supported?

**Comment by khudia** [comment]
Yes please do this!! And statefull treeTable

**Comment by konkines** [comment]
Are there any updates?

**Comment by kr2748** [comment]
We want to use resizable columns with columnGroup.

**Comment by 1Map** [comment]
Still not able to reorder and resize columns where using columnGroup

**Comment by 1Map** [comment]
Almost a year now.  This is a really big issue as my text in my DataTable cell is getting cut off and I cannot resize my columns when grouped in ColumnGroup
