### ISSUE TITLE
DataTable - expansion row lag with large dataset

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#4840]
### Describe the bug

On a table with 500 rows (basic table, no additional features), it takes around 2 seconds to register a click on an expander button. See demo on the attached reproducer link.

I understand that `lazy` mode is suggested when using large data sets, but that is only really useful for pagination / filtering / sorting. For my use case I need to be able to render a large number of rows on one page.

The table itself renders at a reasonable speed but I am just experiencing a lag when using features such as the expansion row and the checkbox column. I have previously opened a discussion ticket for the checkbox column (https://github.com/orgs/primefaces/discussions/319).

Also, I have tried using Virtual Scroll but that was also producing a lag as soon as I try adding HTML / formatting inside the columns.

### Reproducer

https://stackblitz.com/edit/prncz5-wzfzzf?file=src%2FTable.vue

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Fixed for the next version. Please see details; https://github.com/primefaces/primevue/issues/4977
