### ISSUE TITLE
Calendar: Today Button and Clear Button Passthrough options don't apply

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#4849]
### Describe the bug

None of the classes which are passed to the `clearButton` and `todayButton` passthrough properties on the CalendarPassThroughOptions are being applied. For example,

![clearButton & todayButton passthrough options](https://github.com/primefaces/primevue/assets/49190778/5384ae02-87bd-49b0-87f9-b872287b052a)

In the screenshot above, I am trying to apply the `btn btn-danger` classes to the today button and clear button. Passing these classes should provide me with a red button as seen in the [bootstrap 5 documentation](https://getbootstrap.com/docs/5.0/components/buttons/#examples). In the example below, they are appearing with the `btn btn-primary` classes attached due to the passthrough configuration I have set up for button which sets these classes if a severity isn't passed through.

However, the classes aren't being applied to the buttons and no errors are appearing in the console.

![Clear and Today buttons in calendar](https://github.com/primefaces/primevue/assets/49190778/48638d92-a39c-46db-9ef5-b5b958a21e0f)

![Elements in the console](https://github.com/primefaces/primevue/assets/49190778/7a0318ea-4184-4dfc-abb0-aaeb6e3571a7)

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a calendar passthrough.
2. Add the `clearButton` and `todayButton` properties to the passthrough object.
3. Add a class which can be applied to a button.

### Expected behavior

I expect that the Clear Button and Today Button would override the default classes which are applied to the buttons or a new props which allows the user to set the severity of the Clear/Today buttons.

**Comment by tugcekucukoglu** [comment]
Calendar uses Button component for `todayButton` and `clearButton`. Implementation should be like this:

```
todayButton: {
   root: 'btn btn-danger'
}
```
