### ISSUE TITLE
Multiselect: Placeholder css classed will be attached when an option has the same name as the placeholder

### ISSUE THREAD

**Issue by Kanatorabo** [primefaces/primevue#4851]
### Describe the bug

When the placeholder has the same text as an option then the multiselect will attach the placeholder class on the selected option. It should only attache this class when no option is selected.

### Reproducer

https://stackblitz.com/edit/uwu9sh?file=src%2FApp.vue

### PrimeVue version

^3.40.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
When the placeholder property is added, this class will also be added. It will not be checked whether option and placeholder are the same.
