### ISSUE TITLE
PrimeVue Nuxt: IntelliSense not working

### ISSUE THREAD

**Issue by kswzr** [primefaces/primevue#4853]
### Describe the bug

When installing a fresh project as described in the documentation for Nuxt projects, the IntelliSense in the IDE is not working.

### Reproducer

.

### PrimeVue version

newest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Officially, Vue recommends activating the [Volar extension](https://marketplace.visualstudio.com/items?itemName=Vue.volar) after disabling Vetur.  `create-vue` sets the Volar setup by default and I have created [a demo](https://github.com/tugcekucukoglu/primevue-volar-tester). It seems IntelliSense is working correctly. Similarly adding `jsconfig.json`: 

```
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./pages/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

to a Nuxt could solve the problem.

**Comment by tugcekucukoglu** [comment]
Closing the issue due to inactivity. If the problem persists, please let us know.

Thank you,
