### ISSUE TITLE
TabView: TabPanel not recognised

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4854]
### Describe the bug

If you move a TabPanel into it's own component, it will no longer be displayed within the parent TabView component.
https://stackblitz.com/edit/82pwzc?file=src%2FApp.vue,src%2FTabPanelA.vue

I had a look into the primevue TabView code. 
There is some code that i think should search for TabPanels in child components. 
But it doesn't seem to work for me.

### Reproducer

https://stackblitz.com/edit/82pwzc?file=src%2FApp.vue,src%2FTabPanelA.vue

### PrimeVue version

3.41.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to reproducer
confirm that the first TabPanel is not displayed

**Comment by tugcekucukoglu** [comment]
The team is working on DataTable and Column in a similar situation. Once a result is reached for the DataTable, we will port the solution for the TabView.
