### ISSUE TITLE
Wrong Branch/Release?

### ISSUE THREAD

**Issue by knighttower** [primefaces/primevue#4868]
### Describe the bug

I was just looking at the NPM and it seems that the last release was "2.10.." making it the latest release. So when someone is wanting to use the V3 but uses "@latest" their code is going to break as it is pulling an old version. 
![image](https://github.com/primefaces/primevue/assets/649334/b453e606-3f38-4a85-8df2-0bfc2ef42cb8)

Not sure if that was on purpose or a confusion mistake when merging, but if the V2 version is now legacy, it should not co-mingle with the V3 branch, nor should be the same in the NPM unless V2 has already been deprecated.

### Reproducer

https://www.npmjs.com/package/primevue?activeTab=versions

### PrimeVue version

3.41.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
It's fixed now.

Thanks,
