### ISSUE TITLE
Compatible with Vue 3?

### ISSUE THREAD

**Issue by frederikhors** [primefaces/primevue#487]
_I apologize if it is written somewhere and I have not read it, I have searched._

Can I use this project with Vue 3?
Is there a temporary branch of work in progress that I can try?

I need to start a new project and need to find out more before starting.

Thank you.

**Comment by hdacostac** [comment]
Hi @frederikhors I asked to Catagay by twitter a few weeks ago and the told me that soon will release PrimeVue3, totally compatible with Vue3.
Vue3 has been released yesterday 18/09/2020 so, I'm waiting very excited for the primevue release.

**Comment by cagataycivici** [comment]
PrimeVue 3.0.0-rc.1 will be released on 28th of September, work is done, we're just updating the documentation right now.

https://github.com/primefaces/primevue/issues/491

**Comment by Codermar** [comment]
Are the API for both vue 2 and vue 3 the same? Largely the same?
