### ISSUE TITLE
DataTable VirtualScroll Feature broken

### ISSUE THREAD

**Issue by mr83-uw** [primefaces/primevue#488]
1. Demo for Virtual Scroll Broken on this page. (https://primefaces.org/primevue/showcase/#/datatable/scroll)
2. Virtual Scroll not working with multiselect. The scroll bar jumps around, and finally moves to the top of the table.
3. PrimeNg virtual scroll does not require callbacks or manually setting extra fields for the virtual scroll feature locally. (https://primefaces.org/primeng/showcase/#/table/virtualscroll) Should the Vue virtual scroll not require manual callbacks if we don't need to wire it to a remote data source?

**Comment by cagataycivici** [comment]
Although I'm unable to replicate, we'll reimplement the Virtual Scrolling for Vue and React based on the NG version so closing this one now in favor of https://github.com/primefaces/primevue/issues/541
