### ISSUE TITLE
DataView: The array returned to the template #list is malformed according to what the documentation states, and breaks functionality

### ISSUE THREAD

**Issue by tripex** [primefaces/primevue#4882]
### Describe the bug

When I create an array with objects as stated in the documentation, the slotProps.items is simply not existing, so can't manipulate it. 
Instead it does so I can't control the data written in the dom.

### Reproducer

https://codesandbox.io/p/devbox/determined-firefly-9j6h79?file=%2Fsrc%2FApp.vue

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

There should be a items array or object in the slotProps.items

**Comment by tugcekucukoglu** [comment]
`slotProps.items` returns the data according to how to set the `value` of the DataView. Version 3.41.0 has some breaking changes. Please see the live demo: https://primevue.org/dataview/#basic

If you have any further questions about your demo, please use discord or disccussions.

**Comment by tripex** [comment]
@tugcekucukoglu 
> `slotProps.items` returns the data according to how to set the `value` of the DataView. Version 3.41.0 has some breaking changes. Please see the live demo: https://primevue.org/dataview/#basic
> 
> If you have any further questions about your demo, please use discord or disccussions.

Well, that's just not correct, I'm using the documentation, but in the example you see provided with this issue, you can see the slotProp does not contain any items key, it has a data key.

**Comment by tugcekucukoglu** [comment]
I've tried to mention this line: https://stackblitz.com/run?file=src%2FApp.vue%3AL7

`<div v-for="(item, index) in slotProps.items" :key="index" class="col-12">...</div>`

`data` option is deprecated, please use `items` parameter. For more information: https://github.com/primefaces/primevue/issues/4818
