### ISSUE TITLE
:pt can't override local component's tailwind class

### ISSUE THREAD

**Issue by Larshavin** [primefaces/primevue#4883]
### Describe the bug

I tried to use tailwind css with primevue component. 

Set up main.js as like this
```import Tailwind from 'primevue/passthrough/tailwind';
import { usePassThrough } from "primevue/passthrough";
import MyDesignSystem from './design-system.js'

const app = createApp(App)

app.use(PrimeVue, {
    ripple: true, unstyled: true, pt: usePassThrough(Tailwind, MyDesignSystem), ptOptions: {
        mergeSections: true,
        mergeProps: false
    }
});
```

and I use <Button> component with custom tailwind classes

```
<Button class="justify-center w-full mt-5 bg-[#1e4ae9] border-[#1e4ae9]" @click="save()"> SAVE </Button>
```

I checked tailwind style class like 'bg-[#1e4ae9] border-[#1e4ae9]' can't override on default :pt properties, (bg-blue-500 wins for representive style)
But something like 'bg-indigo-600 border-indigo-600' works well. So, I think bg-[# ... ] style is not work on :pt. 

It there any solution for fix this issue?

### Reproducer

https://vitejsvite3gg5r4-jjp5--5173--6843a59c.local.webcontainer.io

### PrimeVue version

3.41.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Set up unstyled mode and use Tailwind Pass Through
2. import Button component and use it with custom tailwind arbitrary values class (https://tailwindcss.com/docs/border-color#arbitrary-values) something like 'border-[#243c5a]'
3. check whether color changed or not 

### Expected behavior

tailwind's arbitrary values class must override on default :pt class

**Comment by tugcekucukoglu** [comment]
It seems reproducing is broken. Could you update it?

**Comment by cagataycivici** [comment]
The built-in Tailwind preset is deprecated, please use the new presets at;

https://tailwind.primevue.org

The new copy-paste approach is the suggested one instead of usePassThrough.
