### ISSUE TITLE
3.41 version bug: Toast & Slider style 

### ISSUE THREAD

**Issue by xushnudbek20** [primefaces/primevue#4885]
### Describe the bug

When I update primevue  from `3.32.1` to `3.41.1`.  I seen that style bugs.

![image](https://github.com/primefaces/primevue/assets/52786242/84ec9b38-6ed1-46ed-ab5a-1ed83af2b475)
Before: 
![image](https://github.com/primefaces/primevue/assets/52786242/aa200680-d988-4e62-8cb3-a90a4d13d0b4)

After:
![image](https://github.com/primefaces/primevue/assets/52786242/44efad4b-1008-4e75-be24-cda1a2456d9a)

### Reproducer

PrimeVue 3 Issue Template

### PrimeVue version

3.41.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 119

**Comment by Xyorqin** [comment]
Are changed any styles?

**Comment by xushnudbek20** [comment]
> Are changed any styles?

No, I just updated primevue version

**Comment by Xyorqin** [comment]
What you say ?

вт, 28 нояб. 2023 г., 14:03 Xushnudbek Xudoynazarov <
***@***.***>:

**Comment by FlipWarthog** [comment]
`@layer` was added in 3.35.0 (https://github.com/primefaces/primevue/issues/4504); could be you have custom styles that previously were not overriding PrimeVue styles but now are.

**Comment by tugcekucukoglu** [comment]
> `@layer` was added in 3.35.0 (#4504); could be you have custom styles that previously were not overriding PrimeVue styles but now are.

Thank you @FlipWarthog . It solves the problem.

**Comment by slumtrimpet** [comment]
@tugcekucukoglu 

I don't understand how the @FlipWarthog comment solves the problem.  So if for example we had generic CSS of the following in our project root:

```
* {
  margin: 0;
  padding: 0;
}
```

That now overrides all padding and margin style in primevue while it previously did not.  That doesn't really seem acceptable.  How do you suggest we resolve this?
