### ISSUE TITLE
DataTable: Multiple Selection.

### ISSUE THREAD

**Issue by ShreyasAch** [primefaces/primevue#4887]
### Describe the bug

Hi team, in the DataTable component i am using selection props which is set to multiple. I also have integrated pagination to the table with rowsPerPageOptions = [25,50,100]. So now if i select multiple selection checkbox its not only selecting those 25 rows on the page rather its considering the entire data which consider has 100 entries. My query is how to limit the multiple selection to those rows, per page rather than entire dataset.

Code for the component:

<|DataTable  v-model:selection="selectedEntries" :value="defaultData" paginator :rows="15"
              :rowsPerPageOptions="[15, 25, 50, 75, 100]"  editMode="cell">

      <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
       <Column field="name" sortable header="customer Name"></Column>
       <Column field="age" sortable header="customer Age"></Column>
       <Column field="phnumber" sortable header="customer phone number"></Column>

<|/DataTable>

Here consider the data array that i pass has 100 entries. Based on the above code only 15 rows will be displayed in 1st page. but when i select multiple option its not only selecting those 15 rows but the entire data. 

**Note:** 
The header checkbox toggles the selection state of the whole dataset by default, when paginator is enabled you may add selectAll property and select-all-change event to only control the selection of visible rows. I did go through this topic but did not solve my problem. Hence putting it up to get some help from the team.

Expecting a fast response from your side.

### Reproducer

https://primevue.org/datatable/#checkbox_row_selection

### PrimeVue version

3.41.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

chrome

### Expected behavior

Expected behaviour is to select those active rows present per page.

**Comment by tugcekucukoglu** [comment]
Hi,

You could try to use `selectAll` property and `select-all-change` event. For further questions, please use discord or discussions.
