### ISSUE TITLE
Portal: wrong type appendTo props

### ISSUE THREAD

**Issue by lakkvak** [primefaces/primevue#4888]
### Describe the bug

If the type for appentTo props is HTMLDivElement , an error will occur in the console 
![image](https://github.com/primefaces/primevue/assets/79806441/f0408a8f-0100-45f1-b734-802402156235)
Apparently because the Portal component has appendTo props with type String 
![image](https://github.com/primefaces/primevue/assets/79806441/eea32c5d-5676-4671-93df-023fac8f4473)

### Reproducer

https://stackblitz.com/edit/zgwjlu?file=src%2FApp.vue

### PrimeVue version

3.40

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1 Specify appendTo props with type HTMLElement
2 Open the console

**Comment by tugcekucukoglu** [comment]
`ref` does not return an HTML element. The demo can be changed like this: ` :appendTo="testCont?.$el"`

**Comment by lakkvak** [comment]
> `ref` does not return an HTML element. The demo can be changed like this: ` :appendTo="testCont?.$el"`

No, you're wrong. Try writing it yourself and the panel will not teleport to the selected node. 
testCont?.$el always returns undefined. Because testCont itself is a node, it does not refer to a component, but to a div
![image](https://github.com/primefaces/primevue/assets/79806441/575c033d-2b5d-4c89-bee5-190348c770fe)
