### ISSUE TITLE
Datatable menu filter Calendar input error

### ISSUE THREAD

**Issue by arnyee** [primefaces/primevue#4891]
### Describe the bug

Hello, I hope you can help me, I ave a big problem, I hope you can help me to solve it!
I have a datatable with a menu filter and modifyed Calendar daterange filter and because of the modificaiton the only input in the filter popover is a Calendar like this:

`<template #filter="{filterModel}">
                <div>
                    <Calendar v-model="filterModel.value" show-on-focus :manualInput="false" :showButtonBar="true" selectionMode="range" :hideOnRangeSelection="true" dateFormat="yy-mm-dd" />
                </div>
            </template>`
            
As you see no additional fields for the input to focus on before the caleendar focus, and because of this, the calendar is appear under the datatable, but after I add a value to the Calendar the  :hideOnRangeSelection="true" make unfocused the Calendar input and after I clicket it again to the calendar input field the popover with the calendar widget is work correctly.

filterModel.value for default value is an empty array.

I think if someohow I can remove the autofocus from the calendar input after i open the filter menu could absolve my probem but I don't find a solution for that.

### Reproducer

https://codesandbox.io/p/devbox/wizardly-chandrasekhar-k6skck?file=%2Fsrc%2FApp.vue%3A19%2C19

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a Datatable with a filter Like I show with the description and the filed default value must be [] like this: date: {value: []}
After you click the filter menu of the column, than the Claendar popover will be appear in the bottom of the table and not as a popover. After that if you click on the widget, than you click again to the Calendar input the popover with the widget will be good.

If I add an input html field before the claendar, than the input filed would be focused and the Claendar will work as expected.

### Expected behavior

The first time I click in the Calendar and it has no value, than it will be nice if the widget popover sohw, and not tthe widget appear after the Datatable

**Comment by tugcekucukoglu** [comment]
This is a demo issue, not a core issue. Please create a topic in discord or discussion.

**Comment by arnyee** [comment]
It's not a demo issue it's a core issue I think because if I want to add only a calendar to a CLoumn filter without other input, the autofocus is make it bad! Please help me! The option to not autofocus the Filter input or anything else is possible?
