### ISSUE TITLE
Component Name: Dropdown Issue

### ISSUE THREAD

**Issue by raihanM95** [primefaces/primevue#4892]
### Describe the bug

If Dropdown selection changed many times then value change but text not change

![Screenshot_1](https://github.com/primefaces/primevue/assets/30027772/f19fad5e-29db-4cd2-994a-27938e8c7570)

### Reproducer

https://primevue.org/dropdown/

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by Joyjk** [comment]
I have also facing same problem. When multiple time change the dropdown option the remains same. This is a bug hampering our development.
