### ISSUE TITLE
Datatable: Overlay doesn't work when using the frozen column with Buttons

### ISSUE THREAD

**Issue by prabinsh** [primefaces/primevue#4898]
https://github.com/primefaces/primevue/assets/57542986/8b4c7f9c-4b9a-4b00-ab65-9ed0b221843e

### Describe the bug

I am using the frozen column and button for one of the column. The button still shows up when passing the frozen column. Please check the issue by scrolling to the right in the reproducer

### Reproducer

https://codesandbox.io/p/sandbox/long-surf-cvwckd

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a datatable with a frozen column
2. In one of the column add the Button
3. Scroll

### Expected behavior

Button shouldn't be seen when passing the frozen column

**Comment by tugcekucukoglu** [comment]
Thanks for the reproducer link. Button component has position relative css style. Removing it using `pt` or another way solves this demo problem.

**Comment by prabinsh** [comment]
Thanks @tugcekucukoglu. 
I used the following pt
```
       <Button
          :label="data.id"
          class="p-button-rounded p-button-text mr-2 mb-2"
          :pt="{
            root: { style: { position: 'static' } },
          }"
          @click=""
        />
```
Updated the reproducer with the new code.
