### ISSUE TITLE
OverlayPanel :before "indicator" needs dynamic placement

### ISSUE THREAD

**Issue by SpeakInCode** [primefaces/primevue#490]
The `:before` selector for the `.p-overlaypanel` that indicates the button above it with a CSS triangle, is always on the left side. So when the toggle button is near the right side of the viewport and the OverlayPanel opens, the indicator doesn't point to the correct position.

![Example ScreenShot](https://user-images.githubusercontent.com/6510555/94064740-596e7b80-fda7-11ea-82d0-a5d358c810e4.png)

**Comment by cagataycivici** [comment]
@mertsincan wdyt? This could be tricky to implement for small screens.
