### ISSUE TITLE
Inaccurate Line Graph Rendering in PrimeVue Chart Component for Steep Data Sections

### ISSUE THREAD

**Issue by osemec** [primefaces/primevue#4904]
### Describe the bug

In the PrimeVue Chart component using the 'line' type, there is a rendering issue where the line graph incorrectly extends beyond the specified value for steep sections of the graph. This anomaly occurs irrespective of the actual data value, but is noticeable in sections where the data changes sharply, causing the graph line to peak above the actual value. This results in a visually inaccurate representation, where the line graph suggests a higher value than what is actually specified in the data.

### Reproducer

https://codesandbox.io/p/devbox/primevue-chart-js-bug-4gk5ds

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Implement a PrimeVue Chart component with the type set to 'line'.
2. Provide a data series with sharp changes in values to create steep sections in the graph.
3. Render the chart.
4. Observe that in sections where the data changes sharply, the line graph extends above the actual specified value, inaccurately depicting the data.

### Expected behavior

The line graph should accurately represent the data points without extending beyond the specified values, even in steep sections of the graph. The visual representation should align precisely with the data values provided, ensuring an accurate and true depiction of the data.

**Comment by tugcekucukoglu** [comment]
PrimeVue just renders the [chart.js](https://www.chartjs.org/) as a component. For more information [official side](https://www.chartjs.org/) can be visited.
