### ISSUE TITLE
wrong type appendTo props

### ISSUE THREAD

**Issue by lakkvak** [primefaces/primevue#4905]
### Describe the bug

A copy of this https://github.com/primefaces/primevue/issues/4888
I left a comment there that the suggested option doesn't work https://github.com/primefaces/primevue/issues/4888#issuecomment-1830120822

### Reproducer

https://stackblitz.com/edit/zgwjlu?file=src%2FApp.vue

### PrimeVue version

3.40

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by SchwarzesWasser** [comment]
I have same problem. In prop :appendTo="testCont?.$el" we can attach HTML element or instance of component. 
In the first case in ref we haven't property `.$el` and see this warning: 
```
