### ISSUE TITLE
Listbox: issue with navigating through list items using tab and enter buttons

### ISSUE THREAD

**Issue by pawelnykun** [primefaces/primevue#4906]
### Describe the bug

The problem occurs when the user navigates through list items using tab button and then press enter. 
It looks like there is some problem with focus.

### Reproducer

https://codesandbox.io/p/devbox/wizardly-cartwright-lc896p

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

#First example

1. Navigate through list items using tab button and try to focus on the second element
2. Press enter 
3. There is no navigation to the requested URL

### Expected behavior

In the above example, there should be navigation to the requested url.

--------------------------------------------------------------------------------------
#Second example:

1. When I open the [Reproducer link](https://codesandbox.io/p/devbox/wizardly-cartwright-lc896p) and edit div in `<template #option="{ option }">` like this:
`<div @keydown.enter="navigateTo(option.url)">`
and then I repeat steps from 1 to 2, the url from selected item is being displayed in the console (  `navigateTo` function fired )
2. But if I also use NVDA program https://www.nvaccess.org/download/ and repeat the same steps the `navigateTo `  function does not fire 

### Expected behavior

In the above example, the url from selected list item should be displayed in the console ( `navigateTo` function should fire )

**Comment by pawelnykun** [comment]
I remind myself :)

**Comment by pawelnykun** [comment]
Kindly reminder :)

**Comment by Magiczne** [comment]
I have very similar issue. When i found that issue i thought there is something that can help me, but there is notthing here :/

@tugcekucukoglu @mertsincan is there any possibility to look at this? From accessibility point of view it is a bit critical.

**Comment by tugcekucukoglu** [comment]
Could you send stackblitz demo because codesandbox is not working?

**Comment by Magiczne** [comment]
@tugcekucukoglu https://stackblitz.com/edit/primevue-create-vue-issue-template-afjkrg?file=src%2FApp.vue
