### ISSUE TITLE
ListBox: multiple tag not working

### ISSUE THREAD

**Issue by marianaibarra** [primefaces/primevue#4909]
### Describe the bug

The multiple tag of the Listbox component is not working as expected.

https://github.com/primefaces/primevue/assets/100448228/dc54c201-342b-42c5-9326-0fc379a56a35

### Reproducer

https://github.com/primefaces/primevue/assets/100448228/dc54c201-342b-42c5-9326-0fc379a56a35

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vite

### Browser(s)

Microsoft Edge

### Steps to reproduce the behavior

1. Create a Listbox component
2. Add "multiple tag"

### Expected behavior

To select multiple elements, not just one.

**Comment by tugcekucukoglu** [comment]
Sorry for the confusion. We updated the docs. `metaKeySelection` property should be added.
