### ISSUE TITLE
Listbox: Filter doesn't select text in input with shift+Home, shift+End keys

### ISSUE THREAD

**Issue by yureckey** [primefaces/primevue#4915]
### Describe the bug

It seems, Filter in Listbox doesn't select text when keyboard SHIFT+HOME (or SHIFT+END) is used (it's on Windows)

### Reproducer

https://primevue.org/listbox/#filter

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 119, Windows 10

### Steps to reproduce the behavior

go https://primevue.org/listbox/#filter
enter any text in filter input. Use keys Shift+Home to select all entered text - cursor is moved to the beginning, but text is not selected

### Expected behavior

text in filter input is selected

**Comment by yureckey** [comment]
Same behavior in Dropdown filter
https://primevue.org/dropdown/#filter

**Comment by makis83** [comment]
This bug is present on Linux as well.
