### ISSUE TITLE
DataTable or Column leak computed properties to their children through VirtualScroller

### ISSUE THREAD

**Issue by Kotoriii** [primefaces/primevue#4924]
### Describe the bug

Using a DataTable > Column > Custom component structure like

```
<DataTable>
  <Column>
    <CustomComponent />
  </Column>
</DataTable>
```

Makes the custom component inherit implicit computed properties coming from the DataTable / Column Primevue components. This creates performance and name clashing issues.

Since CodeSandBox does not support Vue Dev Tools, I can only post screenshots of my local DevTools findings.

PrimeVue Component / (Inside DataTable->Column)
<img width="459" alt="Screenshot 2023-12-04 at 13 23 50" src="https://github.com/primefaces/primevue/assets/6981718/0a4423d9-4be4-47b7-a570-937caadda828">
<img width="407" alt="Screenshot 2023-12-04 at 13 24 04" src="https://github.com/primefaces/primevue/assets/6981718/d627a867-5849-47bc-9a14-cac4e3fc0cbd">

Custom Component (Inside Column)
<img width="430" alt="Screenshot 2023-12-04 at 13 24 16" src="https://github.com/primefaces/primevue/assets/6981718/511e9964-57fb-4a61-9fb9-2425d15912ee">
<img width="383" alt="Screenshot 2023-12-04 at 13 24 22" src="https://github.com/primefaces/primevue/assets/6981718/8d19c52b-85bb-4896-ba7a-808490548019">

The leaked properties seem to come from an implicit VirtualScroller inject
<img width="320" alt="Screenshot 2023-12-05 at 10 24 41" src="https://github.com/primefaces/primevue/assets/6981718/496fed50-b391-4c08-a4e4-543012dfdd6d">

It would be great to know why this happens and if it can be prevented in any way. I'm checking the vue 2 version, and this doesn't happen there.

### Reproducer

N/A

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by luizzappa** [comment]
I am also facing this warning using the `DataTable` component.

![image](https://github.com/primefaces/primevue/assets/65685842/1f042eb1-6523-4e24-94c7-9f9c4fa0119c)

The structure of my code is more or less like this:

```javascript
        <DataTable 
            :globalFilterFields="['alias', 'licenseKey', 'usage', 'status']" 
            v-model:filters="filters"
            filterDisplay="menu"
        >
          <Column field="alias" header="Alias" sortable bodyStyle="width: 35%">
            <template #filter="{ filterModel }">
              <InputText v-model="filterModel.value" type="text" class="p-column-filter" placeholder="Search by alias" />
            </template>
          </Column>
        </DataTable >
```

My environment: nuxt + primevue (nuxt-primevue) + windows 10 + chrome. 

The error never happens the first time I load the page, but if I navigate to another page and return, it appears 
(sometimes I have to browse more than once to appear). It should happen when the component is already mounted on the client side.

**Comment by mertsincan** [comment]
The original issue has been fixed. For the other issue, please track https://github.com/primefaces/primevue/issues/4745

Best Regards,
