### ISSUE TITLE
Dialog: Theming incomplete (maximizableButton/Icon)

### ISSUE THREAD

**Issue by jplacht** [primefaces/primevue#4930]
### Describe the bug

The Tailwind default theme provided in `Dialog` documentation is incomplete, using the design base and creating a Dialog leads to the `maximizableButton` not being rendered properly.

![Screenshot 2023-12-06 at 08 54 24](https://github.com/primefaces/primevue/assets/8456042/e06fa94c-250d-4f9c-ab9b-944fa9a7c9ca)

Following additions lead to a proper placement:

```javascript
icons: {
    class: "flex",
},
maximizableButton: {
    class: [
        'flex items-center justify-center overflow-hidden relative',
        'w-8 h-8 text-gray-500 border-0 bg-transparent rounded-full transition duration-200 ease-in-out mr-2 last:mr-0',
        'hover:text-gray-700 hover:border-transparent hover:bg-gray-200',
        'focus:outline-none focus:outline-offset-0 focus:shadow-[0_0_0_0.2rem_rgba(191,219,254,1)]', // focus
        'dark:hover:text-white/80 dark:hover:border-transparent dark:hover:bg-gray-800/80 dark:focus:shadow-[inset_0_0_0_0.2rem_rgba(147,197,253,0.5)]'
    ]   
},
maximizableButtonIcon: {
    class: "w-4 h-4 inline-block",
},       
```

### Reproducer

https://primevue.org/dialog/

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Any

### Steps to reproduce the behavior

1. Go to https://primevue.org/dialog/ and select "Theming"
2. Use Unstyled Tailwind in component

### Expected behavior

maximizableButton is properly rendered besides closeButton

**Comment by tugcekucukoglu** [comment]
The team is working on new presets and plans to announce it on December 12. New improvements will be added every week.

Thank you
