### ISSUE TITLE
Dialog: allow maximize from start and binding

### ISSUE THREAD

**Issue by ineshbose** [primefaces/primevue#4933]
### Describe the bug

Having a default maximized dialog is not supported currently, but it would be really great to have this ability.

### Reproducer

https://primevue.org/dialog/#maximizable

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
`pt` property and/or headless mode with `container` slot can be used for this. You could try to implement [headless mode](https://primevue.org/dialog/#headless) or directly using

```
:pt="{
   root: 'p-dialog-maximized'
}"
```

can help.

**Comment by ineshbose** [comment]
Yeah, adding `p-dialog-maximized` will have it cover the screen, but the maximize button functionality doesn't change, so `container` slot is necessary - quite an inconvenient workaround to be honest...

**Comment by Oli8** [comment]
Adding `p-dialog-maximized` caused some styling issues so I went with:
```javascript
const dialog = ref()

function maximize() {
  if (dialog.value.maximized) return

  dialog.value.maximize()
}
```
```html
<template>
  <Dialog ref="dialog" @show="maximize">...</Dialog>
</template>
```

Note that in my case I want the dialog to always be maximized.

**Comment by anchan42** [comment]
> Adding `p-dialog-maximized` caused some styling issues so I went with:
> 
> ```js
> const dialog = ref()
> 
> function maximize() {
>   if (dialog.value.maximized) return
> 
>   dialog.value.maximize()
> }
> ```
> 
> ```
> <template>
>   <Dialog ref="dialog" @show="maximize">...</Dialog>
> </template>
> ```
> 
> Note that in my case I want the dialog to always be maximized.

Thanks a lot for this. I have been looking for this.
I think this look a lot cleaner then pt option.

**Comment by d0peCode** [comment]
it should be possible to set `maximized` via prop without need to call function via template ref on mounted

**Comment by anchan42** [comment]
If you want it to always maximised, full screen drawer might be a better obtion.
