### ISSUE TITLE
Calendar: Input value is not updated when model is changed externally

### ISSUE THREAD

**Issue by koljada** [primefaces/primevue#4938]
### Describe the bug

When v-model is changed outside of calendar component (programmatically) then an input still shows previous value. It gets updated when opening the calendar next time.

### Reproducer

https://codesandbox.io/p/devbox/adoring-ellis-4kgr47

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Edge 119.0.2151.97

### Steps to reproduce the behavior

1. Open the calendar.
2. Click 'This month' button in footer. Notice that selected dates are displayed correctly.
3. Close the calendar.
4. **Observe:  input value is not updated (different from model value).**
5. Open and close the calendar without changing dates.
6. **Observe: input value is now updated.**

### Expected behavior

Input value is updated whenever model is changed, just like it is when model is changed from within the calendar

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll fix it before the milestone is released.
