### ISSUE TITLE
The toggleMask state of the Password component is the opposite of the icon image

### ISSUE THREAD

**Issue by ruo-love** [primefaces/primevue#4939]
### Describe the bug

![Snipaste_2023-12-07_17-41-09](https://github.com/primefaces/primevue/assets/82558143/ce6259be-dc3f-4523-a7b7-275f90f2be73)
![Snipaste_2023-12-07_17-41-00](https://github.com/primefaces/primevue/assets/82558143/bb4ed858-b62f-4638-a155-30480be8540d)

![Snipaste_2023-12-07_17-28-15](https://github.com/primefaces/primevue/assets/82558143/6db8da4e-629e-4652-adb1-a357bc1fbbf3)

### Reproducer

vue3

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
We do not think there is a problem with the icon state. If you encounter any other problems, we would like to know.

**Comment by ruo-love** [comment]
> We do not think there is a problem with the icon state. If you encounter any other problems, we would like to know.

In normal circumstances, when the icon depicting open eyes, the password should be visible, and when the icon depicting closed eyes, the password should be invisible. However, the Password component behaves in the opposite way: when the icon with open eyes is selected, the password remains invisible

![12](https://github.com/primefaces/primevue/assets/82558143/414cd75f-b943-40d8-8caf-3f068e13caa5)
![23](https://github.com/primefaces/primevue/assets/82558143/6779d4a0-12d0-4eec-8997-69d49854e28f)

**Comment by ruo-love** [comment]
> We do not think there is a problem with the icon state. If you encounter any other problems, we would like to know.

As a user of PrimeVue, I am eagerly looking forward to you resolving this confusion for me. Thank you very much.

**Comment by ruo-love** [comment]
> We do not think there is a problem with the icon state. If you encounter any other problems, we would like to know.

![66](https://github.com/primefaces/primevue/assets/82558143/06c0c819-9cd0-4d32-9d3f-c04b920a968e)
As a user of PrimeVue, I am eagerly looking forward to you resolving this confusion for me. This is the icon status of the password component in the Ant Design (antd) component library. In contrast to PrimeVue, I believe there is an error in the password icon status and the visibility of the password in PrimeVue, according to user habits. I look forward to your response. Thank you very much.

antd: https://ant.design/components/input
