### ISSUE TITLE
CascadeSelect: optionGroupChildren doesn't work in string type

### ISSUE THREAD

**Issue by yuugou727** [primefaces/primevue#4944]
### Describe the bug

Not sure it is wrong documentation or this feature should be fixed. 

[Document](https://primevue.org/cascadeselect/#api.cascadeselect.props.optionGroupChildren) shows that the prop `optionGroupChildren` accepts both `string` and `string[]`.  I have an option tree. Each layer has its children in `children` key. So I assigned `:optionGroupChildren="'children'"` but CascadeSelect was broken.  It works only when I change it to `['children', 'children', 'children']`.

### Reproducer

https://stackblitz.com/edit/cd7uiz?file=src%2FApp.vue,src%2FmockTree.js

### PrimeVue version

3.43.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Switch `:optionGroupChildren` between  `'children'` and `['children', 'children', 'children']`.

### Expected behavior

CascadeSelect `optionGroupChildren` should accept `string` when option tree has same children key in each layer.

**Comment by Sanjayashok2512** [comment]
how to dynamically generate the optionGroupChildren
my 1st parent have 3 nested children
my 2nd parent have 2 nested children
when i click the 1st parent the optionGroupChildren will be as ["children","children","children"]
when i click the 2nd parent optionGroupChildren will be as ["children","children"] will be update as this
how to do?????
