### ISSUE TITLE
DataTable: padding for rowExpansion does not work

### ISSUE THREAD

**Issue by Pawel2505** [primefaces/primevue#4948]
I want the rowExpansion element has zero padding. I tried different possibilities e.g. 
`:pt="{ rowExpansion: { style: 'padding: 0px!important;' } }" `
etc. however it didn't work.

The thing is I cannot change the version of Primevue at the moment and the version I use (3.30.1) does not contain rowExpansionCell element which I guess could help.

**Comment by tugcekucukoglu** [comment]
You could try to add pt for `rowExpansionCell`
