### ISSUE TITLE
Editor: Two Heading Selections

### ISSUE THREAD

**Issue by goekhantopcu** [primefaces/primevue#4949]
### Describe the bug

When i use the Editor Component, there are two select components for changing the font-size

<img width="1397" alt="image" src="https://github.com/primefaces/primevue/assets/64787457/16ce332f-f32a-4231-b5b3-0d3daf510a70">

<img width="1381" alt="image" src="https://github.com/primefaces/primevue/assets/64787457/0ca45816-eef0-4191-abc2-acf73ca0a056">

JFI: I use the Editor inside a Fieldset. And my "quill" version is "1.3.7"

`const newVehicleNote = ref<string>('');`
`<Editor v-model="newVehicleNote" :pt="{ codeblock: 'hidden' }" editor-style="height: 180px" />`

### Reproducer

The CodeSandbox Url wont work for me, sorry :/ 

### PrimeVue version

3.43.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome v119.0.6045.159 (arm64)

### Expected behavior

I think there should only be one selection component visible

**Comment by tugcekucukoglu** [comment]
Please check this example: https://stackblitz.com/edit/kqbqts?file=src%2FApp.vue. It seems working correctly.
