### ISSUE TITLE
Add indentation property to TreeTable

### ISSUE THREAD

**Issue by MohanYadav1** [primefaces/primevue#495]
Tree table toggler left margin is 16 px hardcoded in treetablerow component.

I want to set toggler(expand/collapse) button left margin as 24 px but unable to set because already set as 16 px in treetable row component. We need to pass prop from treetable to treetablerow component so that user can pass required left margin instead fixed 16 px.

**Comment by rathiayush** [comment]
Any update on this?

**Comment by cagataycivici** [comment]
```html
<TreeTable :indentation="2"
```

Would make the spacing 2 rem. for a child.

**Comment by MohanYadav1** [comment]
Thanks @cagataycivici to merge this change, I see you have committed this change into  primevue 3.0.0. We are using primevue 2.0.8 and "vue": "2.6.10". After updating primevue version from 2.0.8 to 3.0.0, we are getting below errors:

Error:


ERROR in ./node_modules/primevue/components/paginator/Paginator.vue?vue&type=template&id=7f4b8eab& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/paginator/Paginator.vue?vue&type=template&id=7f4b8eab&)
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error)

  Errors compiling template:

  <template> cannot be keyed. Place the key on real elements instead.

  4  |              <slot name="left" :state="currentState"></slot>
  5  |          </div>
  6  |                  <template v-for="item of templateItems" :key="item">
     |                                            ^^^^^^^^^^^
  7  |                          <FirstPageLink v-if="item === 'FirstPageLink'" @click="changePageToFirst($event)" :disabled="isFirstPage" />
  8  |                          <PrevPageLink v-else-if="item === 'PrevPageLink'" @click="changePageToPrev($event)" :disabled="isFirstPage" />

 @ ./node_modules/primevue/components/paginator/Paginator.vue?vue&type=template&id=7f4b8eab& 1:0-187 1:0-187
 @ ./node_modules/primevue/components/paginator/Paginator.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=script&lang=js&
 @ ./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=script&lang=js&
 @ ./node_modules/primevue/components/treetable/TreeTable.vue
 @ ./node_modules/primevue/treetable.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./sourceLearningLibraryConfiguration/components/Dashboard.vue?vue&type=script&lang=js&
 @ ./sourceLearningLibraryConfiguration/components/Dashboard.vue?vue&type=script&lang=js&
 @ ./sourceLearningLibraryConfiguration/components/Dashboard.vue
 @ ./sourceLearningLibraryConfiguration/routing/vue-router.js
 @ ./sourceLearningLibraryConfiguration/app.js
 @ multi ./sourceLearningLibraryConfiguration/app.js

ERROR in ./node_modules/primevue/components/treetable/TreeTableRow.vue?vue&type=template&id=0cede5c1& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/treetable/TreeTableRow.vue?vue&type=template&id=0cede5c1&)
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error)

  Errors compiling template:

  Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

  16 |          <template v-else><span>{{resolveFieldData(node.data, col.props?.field)}}</span></template>
  17 |      </td>
  18 |  </tr>
     |
  19 |  <template v-if="expanded && node.children && node.children.length">
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  20 |      <sub-ttnode v-for="childNode of node.children" :key="childNode.key" :columns="columns" :node="childNode" :parentNode="node"  :level="level + 1"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  21 |                      :expandedKeys="expandedKeys" :selectionMode="selectionMode" :selectionKeys="selectionKeys" :indentation="indentation"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  22 |                      @node-toggle="$emit('node-toggle', $event)" @node-click="$emit('node-click', $event)" @checkbox-change="onCheckboxChange"></sub-ttnode>
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 |  </template>
     |  ^^^^^^^^^^^

  invalid expression: Unexpected token '.' in

    col.props?.columnKey||col.props?.field||i

  Raw expression: :key="col.props?.columnKey||col.props?.field||i"


  1  |
  2  |  <tr :class="containerClass" @click="onClick" @keydown="onKeyDown" @touchend="onTouchEnd" :style="node.style" tabindex="0">
  3  |      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.bodyStyle" :class="col.props?.bodyClass">
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  4  |          <button type="button" class="p-treetable-toggler p-link" @click="toggle" v-if="col.props?.expander" :style="togglerStyle" tabindex="-1" v-ripple>
  5  |              <i :class="togglerIcon"></i>

  invalid expression: Unexpected token '.' in

    col.props?.bodyStyle

  Raw expression: :style="col.props?.bodyStyle"


  1  |
  2  |  <tr :class="containerClass" @click="onClick" @keydown="onKeyDown" @touchend="onTouchEnd" :style="node.style" tabindex="0">
  3  |      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.bodyStyle" :class="col.props?.bodyClass">
     |                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  4  |          <button type="button" class="p-treetable-toggler p-link" @click="toggle" v-if="col.props?.expander" :style="togglerStyle" tabindex="-1" v-ripple>
  5  |              <i :class="togglerIcon"></i>

  invalid expression: Unexpected token '.' in

    col.props?.bodyClass

  Raw expression: :class="col.props?.bodyClass"


  1  |
  2  |  <tr :class="containerClass" @click="onClick" @keydown="onKeyDown" @touchend="onTouchEnd" :style="node.style" tabindex="0">
  3  |      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.bodyStyle" :class="col.props?.bodyClass">
     |                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  4  |          <button type="button" class="p-treetable-toggler p-link" @click="toggle" v-if="col.props?.expander" :style="togglerStyle" tabindex="-1" v-ripple>
  5  |              <i :class="togglerIcon"></i>

  invalid expression: Unexpected token '.' in

    col.props?.expander

  Raw expression: v-if="col.props?.expander"


  2  |  <tr :class="containerClass" @click="onClick" @keydown="onKeyDown" @touchend="onTouchEnd" :style="node.style" tabindex="0">
  3  |      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.bodyStyle" :class="col.props?.bodyClass">
  4  |          <button type="button" class="p-treetable-toggler p-link" @click="toggle" v-if="col.props?.expander" :style="togglerStyle" tabindex="-1" v-ripple>
     |                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  5  |              <i :class="togglerIcon"></i>
  6  |          </button>

  invalid expression: Unexpected token '.' in

    checkboxSelectionMode && col.props?.expander

  Raw expression: v-if="checkboxSelectionMode && col.props?.expander"


  5  |              <i :class="togglerIcon"></i>
  6  |          </button>
  7  |          <div class="p-checkbox p-treetable-checkbox p-component" @click="toggleCheckbox" v-if="checkboxSelectionMode && col.props?.expander" role="checkbox" :aria-checked="checked">
     |                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  8  |              <div class="p-hidden-accessible">
  9  |                  <input type="checkbox" @focus="onCheckboxFocus" @blur="onCheckboxBlur" />

  invalid expression: Unexpected token '.' in

    col.children?.body

  Raw expression: :is="col.children?.body"


  13 |              </div>
  14 |          </div>
  15 |          <component :is="col.children?.body" :node="node" :column="col" v-if="col.children?.body" />
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^
  16 |          <template v-else><span>{{resolveFieldData(node.data, col.props?.field)}}</span></template>
  17 |      </td>

  invalid expression: Unexpected token '.' in

    col.children?.body

  Raw expression: v-if="col.children?.body"


  13 |              </div>
  14 |          </div>
  15 |          <component :is="col.children?.body" :node="node" :column="col" v-if="col.children?.body" />
     |                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  16 |          <template v-else><span>{{resolveFieldData(node.data, col.props?.field)}}</span></template>
  17 |      </td>

 @ ./node_modules/primevue/components/treetable/TreeTableRow.vue?vue&type=template&id=0cede5c1& 1:0-190 1:0-190
 @ ./node_modules/primevue/components/treetable/TreeTableRow.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=script&lang=js&
 @ ./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=script&lang=js&
 @ ./node_modules/primevue/components/treetable/TreeTable.vue
 @ ./node_modules/primevue/treetable.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./sourceLearningLibraryConfiguration/components/Dashboard.vue?vue&type=script&lang=js&
 @ ./sourceLearningLibraryConfiguration/components/Dashboard.vue?vue&type=script&lang=js&
 @ ./sourceLearningLibraryConfiguration/components/Dashboard.vue
 @ ./sourceLearningLibraryConfiguration/routing/vue-router.js
 @ ./sourceLearningLibraryConfiguration/app.js
 @ multi ./sourceLearningLibraryConfiguration/app.js

ERROR in ./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=template&id=455c8289& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=template&id=455c8289&)
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error)

  Errors compiling template:

  invalid expression: Unexpected token '.' in

    col.props?.columnKey||col.props?.field||i

  Raw expression: :key="col.props?.columnKey||col.props?.field||i"


  22 |              <thead class="p-treetable-thead">
  23 |                  <tr>
  24 |                      <th v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.headerStyle" :class="getColumnHeaderClass(col)" @click="onColumnHeaderClick($event, col)"
     |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  25 |                          :tabindex="col.props?.sortable ? '0' : null"  :aria-sort="getAriaSort(col)" @keydown="onColumnKeyDown($event, col)">
  26 |                          <span class="p-column-resizer" @mousedown="onColumnResizeStart" v-if="resizableColumns"></span>

  invalid expression: Unexpected token '.' in

    col.props?.headerStyle

  Raw expression: :style="col.props?.headerStyle"


  22 |              <thead class="p-treetable-thead">
  23 |                  <tr>
  24 |                      <th v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.headerStyle" :class="getColumnHeaderClass(col)" @click="onColumnHeaderClick($event, col)"
     |                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  25 |                          :tabindex="col.props?.sortable ? '0' : null"  :aria-sort="getAriaSort(col)" @keydown="onColumnKeyDown($event, col)">
  26 |                          <span class="p-column-resizer" @mousedown="onColumnResizeStart" v-if="resizableColumns"></span>

  invalid expression: Unexpected token '.' in

    col.props?.sortable ? '0' : null

  Raw expression: :tabindex="col.props?.sortable ? '0' : null"


  22 |              <thead class="p-treetable-thead">
  23 |                  <tr>
  24 |                      <th v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.headerStyle" :class="getColumnHeaderClass(col)" @click="onColumnHeaderClick($event, col)"
     |                                                                                                                  
  25 |                          :tabindex="col.props?.sortable ? '0' : null"  :aria-sort="getAriaSort(col)" @keydown="onColumnKeyDown($event, col)">
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  26 |                          <span class="p-column-resizer" @mousedown="onColumnResizeStart" v-if="resizableColumns"></span>

  invalid expression: Unexpected token '.' in

    col.children?.header

  Raw expression: :is="col.children?.header"


  25 |                          :tabindex="col.props?.sortable ? '0' : null"  :aria-sort="getAriaSort(col)" @keydown="onColumnKeyDown($event, col)">
  26 |                          <span class="p-column-resizer" @mousedown="onColumnResizeStart" v-if="resizableColumns"></span>
  27 |                          <component :is="col.children?.header" :column="col" />
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  28 |                          <span class="p-column-title" v-if="col.props?.header">{{col.props?.header}}</span>
  29 |                          <span v-if="col.props?.sortable" :class="getSortableColumnIcon(col)"></span>

  invalid expression: Unexpected token '.' in

    col.props?.header

  Raw expression: v-if="col.props?.header"


  26 |                          <span class="p-column-resizer" @mousedown="onColumnResizeStart" v-if="resizableColumns"></span>
  27 |                          <component :is="col.children?.header" :column="col" />
  28 |                          <span class="p-column-title" v-if="col.props?.header">{{col.props?.header}}</span>
     |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  29 |                          <span v-if="col.props?.sortable" :class="getSortableColumnIcon(col)"></span>
  30 |                          <span v-if="isMultiSorted(col)" class="p-sortable-column-badge">{{getMultiSortMetaIndex(col) + 1}}</span>

  invalid expression: Unexpected token '.' in

    _s(col.props?.header)

  Raw expression: {{col.props?.header}}


  26 |                          <span class="p-column-resizer" @mousedown="onColumnResizeStart" v-if="resizableColumns"></span>
  27 |                          <component :is="col.children?.header" :column="col" />
  28 |                          <span class="p-column-title" v-if="col.props?.header">{{col.props?.header}}</span>
     |                                                                                ^^^^^^^^^^^^^^^^^^^^^
  29 |                          <span v-if="col.props?.sortable" :class="getSortableColumnIcon(col)"></span>
  30 |                          <span v-if="isMultiSorted(col)" class="p-sortable-column-badge">{{getMultiSortMetaIndex(col) + 1}}</span>

  invalid expression: Unexpected token '.' in

    col.props?.sortable

  Raw expression: v-if="col.props?.sortable"


  27 |                          <component :is="col.children?.header" :column="col" />
  28 |                          <span class="p-column-title" v-if="col.props?.header">{{col.props?.header}}</span>
  29 |                          <span v-if="col.props?.sortable" :class="getSortableColumnIcon(col)"></span>
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  30 |                          <span v-if="isMultiSorted(col)" class="p-sortable-column-badge">{{getMultiSortMetaIndex(col) + 1}}</span>
  31 |                      </th>

  invalid expression: Unexpected token '.' in

    col.props?.columnKey||col.props?.field||i

  Raw expression: :key="col.props?.columnKey||col.props?.field||i"


  32 |                  </tr>
  33 |                  <tr v-if="hasColumnFilter()">
  34 |                      <th  v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :class="getFilterColumnHeaderClass(col)" :style="col.props?.filterHeaderStyle">
     |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  35 |                          <component :is="col.children?.filter" :column="col" v-if="col.children?.filter"/>
  36 |                      </th>

  invalid expression: Unexpected token '.' in

    col.props?.filterHeaderStyle

  Raw expression: :style="col.props?.filterHeaderStyle"


  32 |                  </tr>
  33 |                  <tr v-if="hasColumnFilter()">
  34 |                      <th  v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :class="getFilterColumnHeaderClass(col)" :style="col.props?.filterHeaderStyle">
     |                                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  35 |                          <component :is="col.children?.filter" :column="col" v-if="col.children?.filter"/>
  36 |                      </th>

  invalid expression: Unexpected token '.' in

    col.children?.filter

  Raw expression: :is="col.children?.filter"


  33 |                  <tr v-if="hasColumnFilter()">
  34 |                      <th  v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :class="getFilterColumnHeaderClass(col)" :style="col.props?.filterHeaderStyle">
  35 |                          <component :is="col.children?.filter" :column="col" v-if="col.children?.filter"/>
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  36 |                      </th>
  37 |                  </tr>

  invalid expression: Unexpected token '.' in

    col.children?.filter

  Raw expression: v-if="col.children?.filter"


  33 |                  <tr v-if="hasColumnFilter()">
  34 |                      <th  v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :class="getFilterColumnHeaderClass(col)" :style="col.props?.filterHeaderStyle">
  35 |                          <component :is="col.children?.filter" :column="col" v-if="col.children?.filter"/>
     |                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  36 |                      </th>
  37 |                  </tr>

  invalid expression: Unexpected token '.' in

    col.props?.columnKey||col.props?.field||i

  Raw expression: :key="col.props?.columnKey||col.props?.field||i"


  39 |              <tfoot class="p-treetable-tfoot" v-if="hasFooter">
  40 |                  <tr>
  41 |                      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.footerStyle" :class="col.props?.footerClass">
     |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  42 |                          <component :is="col.children?.footer" :column="col" />
  43 |                          {{col.props?.footer}}

  invalid expression: Unexpected token '.' in

    col.props?.footerStyle

  Raw expression: :style="col.props?.footerStyle"


  39 |              <tfoot class="p-treetable-tfoot" v-if="hasFooter">
  40 |                  <tr>
  41 |                      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.footerStyle" :class="col.props?.footerClass">
     |                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  42 |                          <component :is="col.children?.footer" :column="col" />
  43 |                          {{col.props?.footer}}

  invalid expression: Unexpected token '.' in

    col.props?.footerClass

  Raw expression: :class="col.props?.footerClass"


  39 |              <tfoot class="p-treetable-tfoot" v-if="hasFooter">
  40 |                  <tr>
  41 |                      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.footerStyle" :class="col.props?.footerClass">
     |                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  42 |                          <component :is="col.children?.footer" :column="col" />
  43 |                          {{col.props?.footer}}

  invalid expression: Unexpected token '.' in

    col.children?.footer

  Raw expression: :is="col.children?.footer"


  40 |                  <tr>
  41 |                      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.footerStyle" :class="col.props?.footerClass">
  42 |                          <component :is="col.children?.footer" :column="col" />
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  43 |                          {{col.props?.footer}}
  44 |                      </td>

  invalid expression: Unexpected token '.' in

    "\n                        "+_s(col.props?.footer)+"\n                    "

  Raw expression: {{col.props?.footer}}


  40 |                  <tr>
  41 |                      <td v-for="(col,i) of columns" :key="col.props?.columnKey||col.props?.field||i" :style="col.props?.footerStyle" :class="col.props?.footerClass">
  42 |                          <component :is="col.children?.footer" :column="col" />
     |
  43 |                          {{col.props?.footer}}
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  44 |                      </td>
     |  ^^^^^^^^^^^^^^^^^^^^

 @ ./node_modules/primevue/components/treetable/TreeTable.vue?vue&type=template&id=455c8289& 1:0-187 1:0-187
 @ ./node_modules/primevue/components/treetable/TreeTable.vue
 @ ./node_modules/primevue/treetable.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./sourceLearningLibraryConfiguration/components/Dashboard.vue?vue&type=script&lang=js&
 @ ./sourceLearningLibraryConfiguration/components/Dashboard.vue?vue&type=script&lang=js&
 @ ./sourceLearningLibraryConfiguration/components/Dashboard.vue
 @ ./sourceLearningLibraryConfiguration/routing/vue-router.js
 @ ./sourceLearningLibraryConfiguration/app.js
 @ multi ./sourceLearningLibraryConfiguration/app.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rathiayush** [comment]
Hi, @cagataycivici  Is support for Primevue 2.0 reached end of life? Is Primevue 3.0.0 compatible with vue 2.x?

**Comment by MohanYadav1** [comment]
I think we need to merged this same change into branch 2.1.0 for Vue 2x. Please confirm @cagataycivici .

**Comment by cagataycivici** [comment]
PrimeVue 2.x is still maintained, as an example we'll release 2.1.1 today with this enhancement getting ported back to 2.x.
