### ISSUE TITLE
Datatable: Column resize expand mode and Stateful loses scroll

### ISSUE THREAD

**Issue by savilaj** [primefaces/primevue#4950]
### Describe the bug

With stateful local or session, when restoring state you lose the scroll of the table and it is transmitted to the window.

### Reproducer

https://codesandbox.io/p/devbox/funny-goldstine-ffqgzx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpzmzfe00009356e04um3qe2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpzmzfe00002356egm8h0mo1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpzmzfe00006356eyesbyyyr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpzmzfe00008356ea50cbb53%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpzmzfe00002356egm8h0mo1%2522%253A%257B%2522id%2522%253A%2522clpzmzfe00002356egm8h0mo1%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpzmzfe00008356ea50cbb53%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpzmzfe00007356eoxku3z2l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpzmzfe00008356ea50cbb53%2522%252C%2522activeTabId%2522%253A%2522clpzmzfe00007356eoxku3z2l%2522%257D%252C%2522clpzmzfe00006356eyesbyyyr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpzmzfe00003356e9x9fz4m1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clpzmzfe00004356e4v0aw8ip%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clpzmzfe00005356equv0gdnu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%255D%252C%2522id%2522%253A%2522clpzmzfe00006356eyesbyyyr%2522%252C%2522activeTabId%2522%253A%2522clpzmzfe00003356e9x9fz4m1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.43.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1 - We access the application
2 - Resize columns until the table is forced to scroll
3 - Press CTRL + F5 to force repainting
4 - table scroll is lost

**Comment by tugcekucukoglu** [comment]
Thanks for the codesandbox link. I followed these steps
```
1 - We access the application
2 - Resize columns until the table is forced to scroll
3 - Press CTRL + F5 to force repainting
4 - table scroll is lost
```

 and the demo seems to be working as expected.

**Comment by savilaj** [comment]
Follow these steps:
1 - Go to https://ffqgzx-5173.csb.app/
![Screenshot_1](https://github.com/primefaces/primevue/assets/74399934/e47ee9dd-8069-4483-bd0c-90af8e28b26d)

2 - Resize columns until the table is forced to scroll
![Screenshot_2](https://github.com/primefaces/primevue/assets/74399934/119a1219-39e0-434e-b9eb-8984840e74fa)

3 - Refresc the page
![Screenshot_3](https://github.com/primefaces/primevue/assets/74399934/2ff389e5-a6a8-47a1-8710-caf37a1083a2)

4 - table scroll is lost
![Screenshot_4](https://github.com/primefaces/primevue/assets/74399934/7f9aaac1-884d-4c3a-9ce4-405e380072eb)
