### ISSUE TITLE
Calendar: Time only mode does not work

### ISSUE THREAD

**Issue by Ancient-Dragon** [primefaces/primevue#4952]
### Describe the bug

When I try to use time only mode, the date is shown. I wouldn't expect the date to be shown as well.

### Reproducer

https://primevue.org/calendar/#time

### PrimeVue version

3.42.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

View the documentation page and use the time only calendar, select a time and see that the date is there.

### Expected behavior

When I click on a time the date does not appear. This is regression from 3.38.1 which used to work as expected.

**Comment by Ancient-Dragon** [comment]
Looks like hte changes to formatDateTime are the problem in that PR, by reverting those changes I was able to get it working again with timeOnly mode

**Comment by Ancient-Dragon** [comment]
@tugcekucukoglu let me know if you want me to push changes / make the PR.

**Comment by tugcekucukoglu** [comment]
Sorry, I did not see your comments. You could always send PR, we'll gratefully review it.

**Comment by rstainsby** [comment]
> This PR is the problem: #4901

Apologies, this PR was never intended to be merged in it's current state, I only created it to help triage another issue
