### ISSUE TITLE
Menubar, Megamenu, Contextmenu and etc.: Twice render if $attrs.id not defined

### ISSUE THREAD

**Issue by i7slegend** [primefaces/primevue#4953]
### Describe the bug

Components like a menu (Menubar, Megamenu, Contextmenu) and another which generates id in the dom triggers "initial" render twice: first - with id null (if $attrs.id not passed), and next render with generated id

I got example with dirty fix in the codesandbox only with menubar

### Reproducer

https://codesandbox.io/p/devbox/frosty-stitch-t2m2m9?file=%2Fsrc%2FApp.vue

### PrimeVue version

3.43.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Create any component which generate id for DOM. All components what do it generate id after mount and trigger render twice also it's triggers submenus if child component uses id too

### Expected behavior

Initial render trigger once (ofc if $attrs.id has not changed)

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4954

**Comment by mertsincan** [comment]
@i7slegend This PR broke our entire Id structure. Ids are constantly generated as undefined. That's why I reverted it. You can try your PR with Listbox demo;
```
<ul id="undefined_list" class="p-listbox-list" style="" tabindex="-1" role="listbox" aria-multiselectable="false" aria-disabled="false" data-pc-section="list"> ....
```
For now, I set a milestone for it. We check it before the milestone is released.
Best Regards,

**Comment by i7slegend** [comment]
> @i7slegend This PR broke our entire Id structure. Ids are constantly generated as undefined. That's why I reverted it. You can try your PR with Listbox demo;
> 
> ```
> <ul id="undefined_list" class="p-listbox-list" style="" tabindex="-1" role="listbox" aria-multiselectable="false" aria-disabled="false" data-pc-section="list"> ....
> ```
> 
> For now, I set a milestone for it. We check it before the milestone is released. Best Regards,

Got it.
Yeah it's reproduce under the nuxt server. In "standalone" vue components it's works correctly.

So i have test nuxt variant and see what beforeMount() not called on the server. I test the case with data() & beforeCreate() and found what it's called at same time (very very close) and it's affect to next problem: data() replace id to `undefined` after beforeCreate() hook.
IMHO, in this case enough move UniqueComponentId to the data() instead use in any hooks (at least under the nuxt framework). 🙃

**Comment by i7slegend** [comment]
Attach code block (on example Listbox) which works under nuxt as expected:
```js
    data() {
        return {
            id: this.$attrs.id || UniqueComponentId(),
            filterValue: null,
            focused: false,
            focusedOptionIndex: -1
        };
    },
    watch: {
        '$attrs.id': function (newValue) {
            this.id = newValue || UniqueComponentId();
        },
        options() {
            this.autoUpdateModel();
        }
    },
    mounted() {
        this.autoUpdateModel();
    },
```

**Comment by mertsincan** [comment]
Hi @i7slegend,

Thanks a lot for the detailed info! Yes, we are working to update it like in the above code block.

**Comment by i7slegend** [comment]
Hello! Sorry for reopen this issue, i found what commits above doesn't goals to fix trigger render twice. It's reproduces now

I mean in the attached code block before (https://github.com/primefaces/primevue/issues/4953#issuecomment-1906996273) this (use OR operator in state component for id property).
Example for Menubar component:
```diff
    data() {
        return {
-           id: this.$attrs.id,
+           id: this.$attrs.id || UniqueComponentId(),
            filterValue: null,
            focused: false,
            focusedOptionIndex: -1
        };
    },
    watch: {
        '$attrs.id': function (newValue) {
            this.id = newValue || UniqueComponentId();
        },
        options() {
            this.autoUpdateModel();
        }
    },
    mounted() {
        this.autoUpdateModel();
    },
```

**Comment by i7slegend** [comment]
Oh, issue not reopened 😖
