### ISSUE TITLE
Tooltip: Incorrect Tailwind classes in doc for unstyled mode

### ISSUE THREAD

**Issue by strobh** [primefaces/primevue#4955]
### Describe the bug

The documentation for the `Tooltip` component in unstyled mode contains incorrect Tailwind classes:

```
export default {
    directives: {
        tooltip: {
            // [...]
            arrow: ({ context }) => ({
                class: [
                    'absolute w-0 h-0 border-transparent border-solid',
                    {
                        '-m-t-1 border-y-[0.25rem] border-r-[0.25rem] border-l-0 border-r-gray-600': context?.right || (!context?.right && !context?.left && !context?.top && !context?.bottom),
                        '-m-t-1 border-y-[0.25rem] border-l-[0.25rem] border-r-0 border-l-gray-600': context?.left,
                        '-m-l-1 border-x-[0.25rem] border-t-[0.25rem] border-b-0 border-t-gray-600': context?.top,
                        '-m-l-1 border-x-[0.25rem] border-b-[0.25rem] border-t-0 border-b-gray-600': context?.bottom
                    }
                ]
            }),
            // [...]
        }
    }
}
```

The class `-m-t-1` does not exist in Tailwind. It should be `-mt-1` instead. Due to this error, the arrow of the tooltip is not positioned correctly as can be seen in the reproducer.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-3heujr?file=src%2FApp.vue

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Hover over the element with the tooltip. In the reproducer it's the text `Hover to see the tooltip`.
The arrow of the tooltip is not perfectly centered.

### Expected behavior

The arrow of the tooltip should be perfectly centered.

**Comment by tugcekucukoglu** [comment]
We're transferring the Tailwind docs to [tailwind.primevue](https://tailwind.primevue.org/).

Thanks for your contribution.
