### ISSUE TITLE
Dropdown: Unable to add tooltip

### ISSUE THREAD

**Issue by iampapagray** [primefaces/primevue#4964]
### Describe the bug

I have a Dropdown that works fine until i added a v-tooltip="'Some Info'". 
Then i get this error in console:
```` Uncaught (in promise) TypeError: Cannot set properties of null (setting '$_ptooltipModifiers') ````

### Reproducer

https://codesandbox.io/p/sandbox/competent-sunset-54z78h

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a Dropdown element with options, v-model, optionsLabel, optionsValue.
2. Add a v-tooltip prop to the Dropdown element.
3. Check console for error

### Expected behavior

The Dropdown should simply have a tooltip

**Comment by mertsincan** [comment]
Thanks a lot for the report! I set a milestone. We'll fix it before the milestone is released.

**Comment by iampapagray** [comment]
@mertsincan @tugcekucukoglu Is there any update on this issue yet??
