### ISSUE TITLE
Listbox: multiple not working

### ISSUE THREAD

**Issue by kuaj** [primefaces/primevue#4966]
### Describe the bug

After recent change multiple prop does not work anymore. 
Please check your documentation. It was working in 3.41.0

### Reproducer

https://primevue.org/listbox/#multiple

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Click one option
2. Click second option
3. Option one is deselected

### Expected behavior

Option one stays selected

**Comment by Rakasch** [comment]
Seems the Listbox documentation is missing some description.
check the Datatable description, it has the same setting.
Try:
`:metaKeySelection="false"`

**Comment by kuaj** [comment]
Hey @Rakasch 
thank you for the answer - it works. 
It is hidden breaking change to the component behaviour. I would still suggest that the meta key selection by in not `true` by default

**Comment by tugcekucukoglu** [comment]
We will change the default type of `metaKeySelection` to `false` according to user demand. Please track this ticket https://github.com/primefaces/primevue/issues/4985
