### ISSUE TITLE
Dropdown: Handle v-model change with command in option

### ISSUE THREAD

**Issue by iampapagray** [primefaces/primevue#4970]
I am using the Dropdown component to allow users toggle between two views. 
This works fine. Both views contains forms the users can interact with.
Now, i need to implement a "Changes unsaved, do you want to leave" dialog when a user changes the view mode using the dropdown. Thus, i added a command: () => {} to the options for the dropdown. 

However, the v-model is changed regardless of the logic in the command callback. 
I then used a <template> within the dropdown and used the click event to call the callback. This approach 
calls the callback function but the v-model still changes even when the callback does not change it.

Has anyone done anything similar to this? Is there a better way of doing this? 

Snippet:

```
<Dropdown
 v-model="mode"
 :options="modeOptions"
 optionLabel="name"
 optionValue="value"
 placeholder="Select Mode"
 size="small"
>
 <template #option="slotProps">
  <div class="flex" @click="slotProps.option.command">
    <div>{{ slotProps.option.name }}</div>
   </div>
 </template>
</Dropdown>


//script
const mode = ref('student')
const isEditing = ref(true)
const modeOptions = [
 {
  name: 'Student',
  value: 'student',
  command: () => {
   if(isEditing.value){ 
    //block mode changing
   }else{
    mode.value = 'student'
    }
   }
  },
   {
  name: 'Teacher',
  value: 'teacher',
  command: () => {
   if(isEditing.value){ 
    //block mode changing
   }else{
    mode.value = 'teacher'
    }
   }
  }
]
```

**Comment by iampapagray** [comment]
I have been able to achieve my goal by removing the v-model prop from Dropdown.
And then to give visuals on the active mode, i pass the mode to the placeholder instead. Hope this helps others. 

```
<Dropdown
 :options="modeOptions"
 optionLabel="name"
 optionValue="value"
 :placeholder="mode"
 size="small"
>
 <template #option="slotProps">
  <div class="flex" @click="slotProps.option.command">
    <div>{{ slotProps.option.name }}</div>
   </div>
 </template>
</Dropdown>
```

Doing this prevents vue and the component (i'm not sure which) from automatically assigning the selected option to the mode variable.

**Comment by Rakasch** [comment]
v-model is a shorthand for v-bind:modelValue and @update:modelValue
You could also solve this by using `v-bind:modelValue="selectedMode"` and handle `@update:modelValue="onUpdateMode($event)"` yourself.
In `onUpdateMode` you do whatever you want.
eg. create a promise, show the dialog within the promise. if the dialog is confirmed resolve the promise and change the selectedMode.

**Comment by tugcekucukoglu** [comment]
We do not recommend changing `v-model` when an item is clicked. Dropdown does this itself already. As @Rakasch said `v-bind:modelValue` and `@update:modelValue` can handle this request.

So closing the issue. Thanks for the updates!
