### ISSUE TITLE
Chips: Allow options to select like Autocomplete

### ISSUE THREAD

**Issue by santhikumar43** [primefaces/primevue#4971]
### Describe the bug

I am using Chips component, it is allowing options to add manually. Is there any way to provide an option to select like Autocomplete.

Like Combox, It allows multiple options to select in the dropdown and also allows to add values manually.

### Reproducer

None

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
