### ISSUE TITLE
inputNumber: sample code in documentation suggest to use deprecated props

### ISSUE THREAD

**Issue by yureckey** [primefaces/primevue#4973]
### Describe the bug

The code samples in 
https://primevue.org/inputnumber/#buttons
https://primevue.org/inputnumber/#vertical
uses incrementButtonIcon, decrementButtonIcon which according to very same doc is deprecated since 3.27.0
It's very minor, but still, documentation shouldn't promote usage of deprecated props.

### Reproducer

https://primevue.org/inputnumber/#buttons

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 119, Windows 10

### Steps to reproduce the behavior

check
https://primevue.org/inputnumber/#buttons
https://primevue.org/inputnumber/#vertical
code uses 
incrementButtonIcon, decrementButtonIcon

### Expected behavior

usage of slots

**Comment by tugcekucukoglu** [comment]
We'll update the documentation.

Thanks for your attention.
