### ISSUE TITLE
Improve performance of row expansion feature on DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#4977]
Expanding/collapsing certain rows in big data caused performance problems. Some improvements have been made to overcome this issue. 

Note: If you don't need `expandedRows` all the time, I recommend using `@update:expandedRows` instead of `v-model:expandedRows` (two-way binding).

Exp;
```
<DataTable :expandedRows="expandedRows" @update:expandedRows="onExpandedRows" ...>


const onExpandedRows = (newValue) => {
    // You can get the new expandedRows to use any time.
   ...
}
```

**Comment by MiguelBamberino** [comment]
really good to see this has been improved. We look forward to its release.
