### ISSUE TITLE
InputNumber: maxlength limit not work

### ISSUE THREAD

**Issue by mehmetdilmen** [primefaces/primevue#4979]
### Describe the bug

Hello everyone,

The same problem I had was solved in the primeng section, but I could not find any development for vue.

Issue:
[https://github.com/primefaces/primeng/pull/13442]

### Reproducer

https://github.com/primefaces/primeng/pull/13442

### PrimeVue version

0.2.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
PrimeVue InputNumber does not have `maxlength` property. So closing the issue.
