### ISSUE TITLE
 Table: Sort icons are not showing correct amount directions

### ISSUE THREAD

**Issue by onursenture** [primefaces/primevue#4981]
Reported on the PrimeLand:

<img width="450" alt="image" src="https://github.com/primefaces/primevue/assets/244957/e573ac4d-8c03-46ec-8f01-f390bc27959b">

**Comment by Voltra** [comment]
It seems to me that this was the case before (in v2 IIRC), but no this feels like a regression. It's the same icon that's just flipped upside down and makes it (or just the arrow) ambiguous.

Simply switching the icons from the "before" case would have made more sense and kept everything meaningful.

cf. #4708 and #3732

**Comment by onursenture** [comment]
> It seems to me that this was the case before (in v2 IIRC), but now this feels like a regression. It's the same icon that's just flipped upside down and makes it (or just the arrow) ambiguous.
> 
> Simply switching the icons from the "before" case would have made more sense and kept everything meaningful.
> 
> cf. #4708 and #3732

I don't understand why you think it's ambiguous. If we're discussing the icons used in the 'After' section in my previous comment, the arrows' direction and the amount indicator parts are in the correct orientation to prevent confusion.

**Comment by Voltra** [comment]
They aren't though. In the after case, ascending order, the arrow goes from the bigger bar to the smaller bar which is quite the opposite of ascending order
