### ISSUE TITLE
Menu / Tooltip: Tooltip not working on disabled menu items

### ISSUE THREAD

**Issue by duese1990** [primefaces/primevue#4989]
### Describe the bug

Hi,

I'm using the menu component. Depending on the log in state of the user, some menu items are disabled. I like to have a tooltip here like "only for registered users", but the tooltip is not working on disabled menu items.

Everthing works fine on active menu items.

Kind regards

### Reproducer

-

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

only Edge tested

### Expected behavior

Show tooltip also on disabled menu items.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
