### ISSUE TITLE
InputGroup: InputGroup is broken

### ISSUE THREAD

**Issue by nicolascvoodoo** [primefaces/primevue#4991]
### Describe the bug

It seems that the component is not present in the package anymore.

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Juste open any StackBlitz example on the InputGroup document page.

exemple: https://stackblitz.com/run?file=src%2FApp.vue
or: https://stackblitz.com/run?file=src%2FApp.vue

### Expected behavior

The component should behave as it should.

**Comment by SamuelWei** [comment]
I think it is missing in unplugin-vue-components

**Comment by SamuelWei** [comment]
See my PR: https://github.com/unplugin/unplugin-vue-components/pull/728

**Comment by mertsincan** [comment]
Thanks @SamuelWei ;)
