### ISSUE TITLE
MegaMenu: Expecting MenuItem[][] instead of MenuItem[] in second level items

### ISSUE THREAD

**Issue by jbreuil** [primefaces/primevue#4997]
### Describe the bug

MegaMenu is supposed to take any MenuItem[] as its value but if you do not provide an items property of MenuItem[][] its breaks.

### Reproducer

https://stackblitz.com/edit/angular-qvm9mg-skwtny?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Uncomment the megamenu using the list named breaks

### Expected behavior

Documentation is stating :
model | MenuItem[]
and MenuItem definition is :
export interface MenuItem {
    /**
     * Property name or getter function to use as the label of an item.
     */
    label?: string | ((...args: any) => string) | undefined;
    /**
     * Icon of the item.
     */
    icon?: string | undefined;
    /**
     * Route configuration such as path, name and parameters.
     * @deprecated since v3.33.0.
     */
    to?: RouteLocationRaw | undefined;
    /**
     * Callback to execute when item is clicked.
     * @param {MenuItemCommandEvent} event - Custom command event.
     * @todo next release should be able to change
     */
    command?: (event: MenuItemCommandEvent) => void;
    /**
     * External link to navigate when item is clicked.
     */
    url?: string | undefined;
    /**
     * 	An array of children menuitems.
     */
    items?: MenuItem[] | undefined;
    /**
     * A boolean or a function to return a boolean to specify if the item is disabled.
     * @defaultValue false
     */
    disabled?: boolean | ((...args: any) => boolean) | undefined;
    /**
     * A boolean or a function to return a boolean to specify if the item is visible.
     * @defaultValue true
     */
    visible?: boolean | ((...args: any) => boolean) | undefined;
    /**
     * Specifies where to open the linked document.
     */
    target?: string | undefined;
    /**
     * Defines the item as a separator.
     * @defaultValue false
     */
    separator?: boolean | undefined;
    /**
     * Inline style of the menuitem.
     */
    style?: any;
    /**
     * Style class of the menuitem.
     */
    class?: any;
    /**
     * Unique identifier of an item.
     */
    key?: string | undefined;
    /**
     * Optional
     */
    [key: string]: any;
}
so megamenu should not be expecting items: MenuItem[][]

**Comment by tugcekucukoglu** [comment]
MegaMenu accepts multiple submenu. This way was followed to distinguish this.

Thanks for your attention.
