### ISSUE TITLE
> In normal circumstances, when the icon depicting open eyes, the password should be visible, and when the icon depicting closed eyes, the password should be invisible. However, the Password component behaves in the opposite way: when the icon with open eyes is selected, the password remains invisible

### ISSUE THREAD

**Issue by ruo-love** [primefaces/primevue#4999]
> We do not think there is a problem with the icon state. If you encounter any other problems, we would like to know.

In normal circumstances, when the icon depicting open eyes, the password should be visible, and when the icon depicting closed eyes, the password should be invisible. However, the Password component behaves in the opposite way: when the icon with open eyes is selected, the password remains invisible

![12](https://github.com/primefaces/primevue/assets/82558143/414cd75f-b943-40d8-8caf-3f068e13caa5)
![23](https://github.com/primefaces/primevue/assets/82558143/6779d4a0-12d0-4eec-8997-69d49854e28f)

_Originally posted by @ruo-love in https://github.com/primefaces/primevue/issues/4939#issuecomment-1869863109_

**Comment by ruo-love** [comment]
As a user of PrimeVue, I am eagerly looking forward to you resolving this confusion for me. Thank you very much.

**Comment by ruo-love** [comment]
![Uploading 66.png…]()

As a user of PrimeVue, I am eagerly looking forward to you resolving this confusion for me. This is the icon status of the password component in the Ant Design (antd) component library. In contrast to PrimeVue, I believe there is an error in the password icon status and the visibility of the password in PrimeVue, according to user habits. I look forward to your response. Thank you very much.

antd: https://ant.design/components/input

**Comment by tugcekucukoglu** [comment]
There is no full consensus on this topic I guess. Other libraries that think like PrimeVue:

https://mui.com/material-ui/react-text-field/#input-adornments
https://vuetifyjs.com/en/components/text-fields/#login-form


We do not think this is an issue at the moment and we are closing the issue. The best place to discuss this would be discussions.
