### ISSUE TITLE
Divider: Divider line doesn't show (Using the `nuxt-primevue` module)

### ISSUE THREAD

**Issue by TM-SunnyDay** [primefaces/primevue#5000]
### Describe the bug

I used the nuxt primevue module to use components in nuxt based on the documentation, but I found that the Divider component cannot display lines.

I have found the same issue, which should be caused by the import order of the style sheet, but in Nuxt, I don't know how to fix it.
#1086

In the server rendered page, its order is correct, so when the page is opened, the dividing line is displayed.

But after hydration, Nuxt seems to have moved the theme style file after the component style, which caused the split line to disappear.

![image](https://github.com/primefaces/primevue/assets/49872538/07427082-c870-4178-8207-e981a3840553)
![image](https://github.com/primefaces/primevue/assets/49872538/b1c9ee42-6249-43b8-a6f1-914807139402)
![image](https://github.com/primefaces/primevue/assets/49872538/5ab69dd2-5ad2-4379-8d9f-c80cdf424b82)

I think the border top style in the theme should be set completely (`border-top: 1px solid #e5e7eb;`), just like other components, or CSS variables can be used to replace it(`border-top: 1px var(--divider-border-style) #e5e7eb;`).

### Reproducer

https://stackblitz.com/edit/nuxt-starter-g9aefo?file=nuxt.config.ts,app.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 120.0.6099.130

### Steps to reproduce the behavior

1. Initialize Nuxt
2. Installing the `nuxt-primevue` module
3. Use any theme css file in the `css` option of `nuxt.config.ts`
4. Using the Divider component

**Comment by antoinezanardi** [comment]
Do we have some news about this bug ?

**Comment by mertsincan** [comment]
Hi,

This is related to theme. I set a milestone for it. We'll fix it before the milestone is released.
