### ISSUE TITLE
TableBody: Render "BodyRow" binding dataKey of props to key attribute

### ISSUE THREAD

**Issue by IanLai0201** [primefaces/primevue#5006]
### Describe the bug

In 3.45.0 version.
"DataTable" render "BodyRow" binding row index to key attribute.

Is it possible to switch to using 'dataKey' of props for improved reusability during rendering?

![image](https://github.com/primefaces/primevue/assets/65215264/11fe065e-3258-4134-b443-66759d9c00a4)

### Reproducer

https://stackblitz.com/edit/hsltmk?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
You're right! I'll update it before the milestone is released.
