### ISSUE TITLE
CascadeSelect: Submenu(list) items go off screen and does not allow vertical scroll bar

### ISSUE THREAD

**Issue by baaskoen** [primefaces/primevue#5007]
### Describe the bug

As in the reproducer link (https://stackblitz.com/edit/4fw4mp-y1ukj2?file=src%2FApp.vue), if you open the submenu "Australia", you cannot scroll down with your keyboard buttons. By default the list also has no max-height, meaning it will just create a long unfriendly list.

In discord someone helped me with a temporary hotfix which can be seen here:
https://stackblitz.com/edit/4fw4mp-1ceoxn?file=src%2FApp.vue

### Reproducer

https://stackblitz.com/edit/4fw4mp-y1ukj2?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

See the attached stackblitz.

### Expected behavior

By default, submenu's and sublists (see also TieredMenu) should have a max height, and should be scrollable with keyboard buttons.

**Comment by melloware** [comment]
We have an open PrimeReact PR to fix this if you want to port it to PrimeVue

https://github.com/primefaces/primereact/pull/5681

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll review it before the milestone is released.

**Comment by tugcekucukoglu** [comment]
Fixed with version 4.
