### ISSUE TITLE
Tree: TreeNode module not resolved by rollup during build

### ISSUE THREAD

**Issue by dcb99** [primefaces/primevue#5009]
### Describe the bug

When attempting to build via `npm run build` I get the following error:
```
Error: [vite]: Rollup failed to resolve import "primevue/treenode" from "<redacted>/primevue-sample/src/components/HelloWorld.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
...
```

### Reproducer

https://github.com/dcb99/primevue-sample

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Clone repo, run `npm install`, followed by `npm run build`, you should see the error. Interestingly enough, there are no issues when doing `npm run type-check`.

### Expected behavior

App builds without errors.

**Comment by dmcbride** [comment]
Just trying to add primevue to the vite rollup section gets:

```
vite v5.0.12 building for production...
✓ 103 modules transformed.
[commonjs--resolver] Failed to resolve entry for package "primevue". The package may have incorrect main/module/exports specified in its package.json.
✓ built in 1.10s
error during build:
Error: Failed to resolve entry for package "primevue". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/dmcbride/prj/k2/ka-web/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29443:17)
    at resolvePackageEntry (file:///home/dmcbride/prj/k2/ka-web/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29440:5)
    at tryNodeResolve (file:///home/dmcbride/prj/k2/ka-web/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29210:20)
    at Object.resolveId (file:///home/dmcbride/prj/k2/ka-web/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:28978:28)
    at file:///home/dmcbride/prj/k2/ka-web/node_modules/rollup/dist/es/shared/node-entry.js:18692:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/dmcbride/prj/k2/ka-web/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
    at async resolveId (file:///home/dmcbride/prj/k2/ka-web/node_modules/rollup/dist/es/shared/node-entry.js:17261:26)
    at async ModuleLoader.resolveId (file:///home/dmcbride/prj/k2/ka-web/node_modules/rollup/dist/es/shared/node-entry.js:17675:15)
    at async Object.resolveId (file:///home/dmcbride/prj/k2/ka-web/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:8141:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/dmcbride/prj/k2/ka-web/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
```

At the moment, I have in my vite.config.js:

```
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vue': ['vue'],
          'vue-router': ['vue-router'],
          'pinia': ['pinia'],
          'primevue': ['primevue'], // if I comment this out, it works.
          'fontawesome': ['@fortawesome/fontawesome-svg-core'],
        },
      },
    },
  },
```

so maybe there is something that can be added to primevue's package.json for this?

**Comment by RebeccaStevens** [comment]
I've got the same error but it can't find `primevue/calendar`.

```sh
Error:  Could not resolve entry module "primevue/calendar".
Error:  Nuxt Build Error: Could not resolve entry module "primevue/calendar".
  at error (node_modules/.pnpm/rollup@4.6.1/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
  at ModuleLoader.loadEntryModule (node_modules/.pnpm/rollup@4.6.1/node_modules/rollup/dist/es/shared/node-entry.js:17957:20)
  at async Promise.all (index 40)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by RebeccaStevens** [comment]
@dmcbride The `primevue` npm package doesn't have any top level exports, you need to import from subpackages e.g. `primevue/button`.

**Comment by RebeccaStevens** [comment]
I think the issue might be related to the module resolution.
I'm using `"moduleResolution": "bundler"` and as the `primevue` npm package doesn't have any top level exports, the resolutions fails.

Though this is just a hunch I haven't tested.
Though I would have thought `"moduleResolution": "bundler"` wouldn't have this issue. I'd only expect it from `"moduleResolution": "node16"` - so maybe this isn't the source of the issue.

**Comment by RebeccaStevens** [comment]
Looks like it is a module resolution issue.
Adding the following to primevue's npm package fixes the issue for me.

```jsonc
"exports": {
  "./icons/*": {
    "types": "./icons/*/index.d.ts",
    "import": "./icons/*/index.esm.js",
    "require": "./icons/*/index.cjs.js"
  },
  "./*/style": {
    "types": "./*/style/*style.d.ts",
    "import": "./*/style/*style.esm.js",
    "require": "./*/style/*style.cjs.js"
  },
  "./*": {
    "types": "./*/*.d.ts",
    "import": "./*/*.esm.js",
    "require": "./*/*.cjs.js"
  }
},
```

**Comment by RebeccaStevens** [comment]
Found the cause (at lease for me).
It's a problem with the `primevue-nuxt-module`

```ts
export const Checkbox: typeof import("primevue/checkbox")['default']
```

should be

```ts
export const Checkbox: typeof import("../node_modules/primevue/checkbox")['default']
```

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your report! I set a milestone for it. I'll check before the milestone is released.

**Comment by dcb99** [comment]
> Hi,
> 
> Thanks a lot for your report! I set a milestone for it. I'll check before the milestone is released.

Sounds good, thanks for getting this sorted.

**Comment by dcb99** [comment]
@mertsincan I'm also starting to see this issue with ConfirmationOptions also, when trying to do:
`import { type ConfirmationOptions } from 'primevue/confirmationoptions';`

**Comment by mertsincan** [comment]
@dcb99 I checked it now. I think your import is wrong. Please try;
```
import type { TreeNode } from 'primevue/treenode'; // instead of import { type TreeNode }
```
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

After this change, your project works fine for me. So, closed.

@RebeccaStevens Could you please attach a sample project with your config to replicate it? and could you please create a new ticket for it?

**Comment by dcb99** [comment]
> @dcb99 I checked it now. I think your import is wrong. Please try;
> 
> ```
> import type { TreeNode } from 'primevue/treenode'; // instead of import { type TreeNode }
> ```
> 
> https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
> 
> After this change, your project works fine for me. So, closed.
> 
> @RebeccaStevens Could you please attach a sample project with your config to replicate it? and could you please create a new ticket for it?

I'll give this a try, but the compiled  code is identical, regardless of where the `type` keyword is added.

**Comment by RebeccaStevens** [comment]
Welp, I took a couple of weeks off, come back to the project and now I can't reproduce this bug. I haven't updated any dependency...

If it pops up again, I'll open a new issue.
