### ISSUE TITLE
Tooltip: missing nonce for inline styles

### ISSUE THREAD

**Issue by jasonfellows** [primefaces/primevue#5010]
### Describe the bug

When adding a nonce via PrimeVue csp config option, no nonce is added to the inline styles injected by BaseDirective for the Tooltip component.

Reproduction with a Nuxt app: https://github.com/jasonfellows/primevue-toolip-missing-nonce
Deployed to Vercel to view CSP violations and witness missing nonce for inline styles: https://primevue-toolip-missing-nonce.vercel.app/

### Reproducer

https://github.com/jasonfellows/primevue-toolip-missing-nonce

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Add a strict CSP to an app
2. Use Tooltip directive
3. View CSP violations in console

### Expected behavior

All inline scripts and styles injected by PrimeVue contain the nonce attribute provided to PrimeVue config to enable usage with strict CSPs.

**Comment by mertsincan** [comment]
Hmm, interesting! We'll check again before the next version is released.

Best Regards,

**Comment by alfisdad** [comment]
Just upgraded to version 3.47.2 and, unfortunately, still getting the CSP violations in the console and the tooltip arrow doesn't show
