### ISSUE TITLE
<SplitButton> inherits CSS properties from <DynamicDialog> "footer" and disrupts the original design

### ISSUE THREAD

**Issue by istanfrank** [primefaces/primevue#5012]
### Describe the bug

The <SplitButton> inherits CSS properties from <DynamicDialog> "footer" and disrupts the original design of <SplitButton>. See image. Empty dialog, <SplitButton> once in the content area and once in the footer area. Of course, I can correct it using CSS, but I don't think that's intended. I haven't tested it in the "Header" section.

SplitButton Destroyed this CSS-Part from footer:
.p-dialog .p-dialog-footer button {
    margin: 0 0.5rem 0 0;
    width: auto;

<img width="563" alt="image" src="https://github.com/primefaces/primevue/assets/140466890/9f6a33e9-56ee-4f73-bff2-badceb1e4c09">

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-jzqxvm?file=/src/components/InfoDemo.vue

### PrimeVue version

3.45

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

paste <SplitButton> to content and footer and find the difference in design

**Comment by mertsincan** [comment]
Sorry for the delayed response! We'll give an update before the next version is released.

Sorry again :/

**Comment by istanfrank** [comment]
thanks you.
