### ISSUE TITLE
Documents support multiple languages？

### ISSUE THREAD

**Issue by frontend-qin** [primefaces/primevue#5017]
### Describe the bug

I really like this UI library. It's so beautiful. Can I add multilingual support to the document, such as the Chinese version, German version, Japanese version, etc.? I want to do Chinese translation

### Reproducer

https://primevue.org/introduction/

### PrimeVue version

3.x

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by cagataycivici** [comment]
Thank you for your interest in contribution, the website is unfortunately hard coded to be English at the moment, no translation API is built-in. Once it is done, we'll put up a contributing guide to detail out the process. Again thank you for considering to contribute. I'll close the ticket for now and move the idea to the upcoming contributing guide as we'll have the translations as part of the "help needed" section in the new document.
