### ISSUE TITLE
BUG SplittButton not change disabled on menuitems

### ISSUE THREAD

**Issue by istanfrank** [primefaces/primevue#5019]
### Describe the bug

the items do not changed and are not reactive. if i change teh state for an item to disabled it is still enabled, stays with initial state. 

<template>    
<div class="card flex justify-content-center">
        <ToggleButton v-model="checked" class="w-8rem" />
        <SplitButton label="Save" icon="pi pi-plus" @click="save" :model="items" />
    </div>
</template>

<script setup>
import { ref } from 'vue';
const checked = ref(false);
const items = [
    {
        label: 'Update',
    },
    {
        label: 'Delete',
        disabled: checked.value,
    },
    {
        label: 'Vue Website',
    },
    { label: 'Upload', icon: 'pi pi-upload', to: '/fileupload' }
];
</script>

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-kpqjrj?file=/src/App.vue

### PrimeVue version

3.45

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by istanfrank** [comment]
works with  disabled: ()=>toggleDisable but not with disable: toggleDisable

**Comment by tugcekucukoglu** [comment]
Working with 'reactive' and an array of objects needs an extra step. I want to share [this demo](https://stackblitz.com/edit/eyk3kn?file=src%2FApp.vue)
