### ISSUE TITLE
Dropdown: Dropdown is opening after using custom clear icon

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#5022]
### Describe the bug

When using custom icon for dropdown clear icon the dropdown is opening after using clear action, when it should not be doing that, as when not using custom slot it is not doing so.

The problem disappears when `data-pc-section="clearicon"` is applied to the element in custom slot. 

### Reproducer

https://codesandbox.io/p/devbox/elated-butterfly-qnswkn

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go into reproduction example
2. Select something in dropdown
3. Use clear icon - dropdown is opening after using clear icon
4. Comment custom slot and perform steps 2 and 3 - dropdown is not opening
5. Ucomment code fragment with `data-pc-section` - dropdown is not opening

### Expected behavior

data-pc-section **should not** be required for custom slot to work properly, or if it is required it should be available in the slot scope.

**Comment by tugcekucukoglu** [comment]
As you have said adding `data-pc-section="clearicon"` solves the problem. We were solving similar problems with classes before. We switched to `data-pc-section` with Unstyled mode.

**Comment by Magiczne** [comment]
@tugcekucukoglu if this is the **solution** then it should be either documented or being available in a slot.

Coming to framework which is telling that is supports unstyled mode, and having different behavior for which i have to deep dive inside vendor code is not something that should be acceptable if talking about high quality.

I don't think the issue I have pointed is solved, so I don't know why you've closed this ticket.
