### ISSUE TITLE
Button: Uncaught TypeError: _ctx.cx is not a function

### ISSUE THREAD

**Issue by trananhmanh89** [primefaces/primevue#5023]
### Describe the bug

JS throw error `Uncaught TypeError: _ctx.cx is not a function`

![image](https://github.com/primefaces/primevue/assets/20571336/eb90e547-f0e1-4537-92ec-b5059c807d35)

### Reproducer

https://github.com/trananhmanh89/primevue-test

### PrimeVue version

latest

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vue CLI App

### Browser(s)

Latest Chrome

### Steps to reproduce the behavior

1. Clone this repo https://github.com/trananhmanh89/primevue-test
2. Run npm i
3. Open file index.html by chrome
4. See the error on console

### Expected behavior

It should show as Dialog example: https://primevue.org/dialog/#basic

**Comment by JohnHawley** [comment]
I am experiencing this as well, identical errors as the screenshot provided by **trananhmanh89**, although I'm building with Rollup.

I'm very new to this library and very interested in the solution to this—perhaps a user config error with ESM builds.

While trying to track this down, it looks like components aren't extended with _BaseComponent_ and the **cx** method is not being extended to vue **_ctx**

**Comment by mertsincan** [comment]
This is really interesting. I'm still working on this issue. I'll give an update before the next version is released.

**Comment by frangeris** [comment]
Same issue here, just a fresh install, building with webpack

**Comment by mertsincan** [comment]
Note: I moved it to the next milestone to work on it in more detail.

**Comment by mertsincan** [comment]
Hi,

I reviewed this issue. Seems like a webpack config issue. After removing the following config, the error is gone.

```
        new webpack.DefinePlugin({
            __VUE_OPTIONS_API__: false,
            __VUE_PROD_DEVTOOLS__: false,
            __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: false,
        }),
```

Best Regards,

**Comment by trananhmanh89** [comment]
@mertsincan Thank you. 
It's seem because the webpack config turn off `__VUE_OPTIONS_API__` cause this issue. Set it `true` then every will be ok.

**Comment by trananhmanh89** [comment]
> @mertsincan Thank you. It's seem because the webpack config turning off `__VUE_OPTIONS_API__` causing this issue. Set it `true` then everything will be ok.
