### ISSUE TITLE
DataTable: Error - Are mandatory columns

### ISSUE THREAD

**Issue by silvasamu** [primefaces/primevue#5031]
### Describe the bug

Hello, when executing this code with the columns empty, it gives an error

`Link: https://stackblitz.com/run?file=src%2FApp.vue`

```
<template>
    <div class="card">
        <DataTable :value="products" tableStyle="min-width: 50rem">
            <template #empty>
                empty records
            </template>

            <Column v-for="col of columns" :key="col.field" :field="col.field" :header="col.header"></Column>
        </DataTable>
    </div>
</template>

<script setup>
import { ref } from 'vue';

const products = ref([]);
const columns = [];

</script>
```

The error is:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'forEach')  at Proxy.columnsLength (BodyRow.vue:470:26)`

Code line in BodyRow.vue:

       columnsLength() {
            let hiddenColLength = 0;

            this.columns.forEach((column)=>{
                if (this.columnProp(column, 'selectionMode') === 'single')
                    hiddenColLength--;
                if (this.columnProp(column, 'hidden'))
                    hiddenColLength++;
            }
            );

            return this.columns ? this.columns.length - hiddenColLength : 0;
        }
    },

I believe the solution would be to add: ` if(!this.columns) return 0;`

Code complete:

```
columnsLength() {
            let hiddenColLength = 0;

            if(!this.columns) return 0;
            
            this.columns.forEach((column)=>{
                if (this.columnProp(column, 'selectionMode') === 'single')
                    hiddenColLength--;
                if (this.columnProp(column, 'hidden'))
                    hiddenColLength++;
            }
            );

            return this.columns ? this.columns.length - hiddenColLength : 0;
        }
}
```

My greetings!!!

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.45

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Last Chrome 

### Steps to reproduce the behavior

Create a table without columns and the error will occur.

```
<script setup>
import { ref } from 'vue';

const products = ref([]);
const columns = [];

</script>
```

### Expected behavior

A table without columns

**Comment by mertsincan** [comment]
Thanks a lot for your report, this issue has already been fixed in https://github.com/primefaces/primevue/issues/5005

Best Regards,
