### ISSUE TITLE
Can't paste a decimal value when there is a total value in the input.

### ISSUE THREAD

**Issue by zdebski** [primefaces/primevue#5034]
### Describe the bug

**Current behavior**
When there is a total value, e.g., "100," I can't paste the value "100,1". I can do it only when the value in the input is also a decimal.

![vue-input](https://github.com/primefaces/primevue/assets/50101249/f77190bd-42eb-435f-8c8a-bc4f8037b217)

The main issue is, for example, working with various types of spreadsheets. Attemping to paste values from spreadsheets into the Vue input component is now impossible.

**Expected behavior**
There should always be the possibility of pasting value to the input, no matter if it's decimal or total.

Possibly related to: https://github.com/primefaces/primevue/issues/4430

### Reproducer

*

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox 121.0 , Chrome 120.0.6099.130

### Steps to reproduce the behavior

1. Type the value 100 into the Vue input component.
2. Copy value 100,1
3. Try to paste the value into the Vue input component.

### Expected behavior

There should always be the possibility of pasting value to the input, no matter if it's decimal or total.

**Comment by tugcekucukoglu** [comment]
Are you using `minFractionDigits` and `minFractionDigits`properties? It might be related with this.

**Comment by zdebski** [comment]
> Are you using `minFractionDigits` and `maxFractionDigits`properties? It might be related with this.

We use `maxFractionDigits `equal to the precision, so:
if the precision is 0 then `maxFractionDigits` = 0

**Comment by tugcekucukoglu** [comment]
Could you update this [demo](https://stackblitz.com/edit/szeovd?file=src%2FApp.vue) according to your use case?

**Comment by zdebski** [comment]
@tugcekucukoglu demo has been updated.
https://stackblitz.com/edit/szeovd-jmrlrr?file=src%2FApp.vue\

**Comment by tugcekucukoglu** [comment]
In the demo you sent, it seems that copy-paste works correctly. How can we see the real problem?

**Comment by tugcekucukoglu** [comment]
We added an update for InputNumber for the version 3.47.0. Both inputs must accept decimals and have the same `maxFractionDigits` values. If you think the issue persists, please add an update.
