### ISSUE TITLE
Password Component does not comply to WCAG

### ISSUE THREAD

**Issue by dongenar** [primefaces/primevue#5035]
### Describe the bug

This contains 2 parts:
1.
<div class="p-password p-component p-inputwrapper p-input-icon-right" data-pc-name="password" data-pc-section="root" id="password" data-cy="password" aria-describedby="Password" aria-required="true">
ARIA attribute is not allowed: aria-required="true" not allowed

2.
<input class="p-inputtext p-component p-password-input w-full" data-pc-name="inputtext" data-pc-section="input" type="password" aria-label="Password" aria-controls="pv_id_1_panel" aria-expanded="false" aria-haspopup="true">
ARIA attribute is not allowed: aria-expanded="false"

### Reproducer

https://codesandbox.io/p/devbox/stupefied-joliot-84vsky?file=%2Fsrc%2FApp.vue%3A10%2C47

### PrimeVue version

3.41.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
There is `pt` property. For example;

```
            :pt="{
                input: {
                    root: {
                        'aria-required': true
                    }
                }
            }"

```
