### ISSUE TITLE
PrimeVue Designer will return?

### ISSUE THREAD

**Issue by rasc-br** [primefaces/primevue#5040]
### Describe the bug

In my opinion, https://designer.primevue.org/ was the best way to generate custom themes.
This is a bug or the tool is not returning?

### Reproducer

https://designer.primevue.org/

![image](https://github.com/primefaces/primevue/assets/33508295/3e4ddabf-73db-46b0-968c-d860759278b4)

### PrimeVue version

3.45

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Currently old designer is deprecated. We are working on a new designer.

Thanks for your understanding.

**Comment by zanyar3** [comment]
When !?

> Currently old designer is deprecated. We are working on a new designer.
> 
> Thanks for your understanding.
