### ISSUE TITLE
Datatable Expandrows broken in 3.45

### ISSUE THREAD

**Issue by yormy** [primefaces/primevue#5041]
### Describe the bug

Expanding rows in 3.44 works, and when I upgrade the package to 3.45 it no longer show the expanded section

### Reproducer

x

### PrimeVue version

3.45

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome

### Steps to reproduce the behavior

x

### Expected behavior

x

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it. https://primevue.org/datatable/#row_expansion Can you please attach a stackblitz/codesandbox link to replicate?

**Comment by mertsincan** [comment]
Unfortunately, closed for now. If an update comes from your side, please reopen this ticket. Thanks a lot for your understanding!

Best Regard,

**Comment by yormy** [comment]
Apparently it was not in the expanded section but in the expander button.

My code is 
`        <Column expander style="width: 1rem">
            <template #body="{ data }">
                <div v-if="hasExpandedData(props, data)">
                    <div @click="onExpandClicked(data)" @keydown="onExpandClicked(data)">
                        <span v-if="isExpanded(data)">
                            <y-icon icon="icon-collapse" />
                        </span>
                        <span v-else>
                            <y-icon icon="icon-expand" />
                        </span>
                    </div>
                </div>
            </template>
        </Column>
`

This specific code stopped working
The code from your docs `<Column expander style="width: 5rem" />` does work

When I add the template it stops working
        <Column expander style="width: 5rem" >
            <template #body>
                xxx
            </template>
        </Column>

So It seems there might be an issue in events firing when I include the template body for the expander. My main goal is to hide the expander when there is no data in the expanded section. Alternative approaches are also welcome

**Comment by mertsincan** [comment]
Interesting! Do you have any errors on console?

**Comment by yormy** [comment]
Sadly no..
No errors, no warnings, no info's

**Comment by yormy** [comment]
Sadly no..
No errors, no warnings, no info's

**Comment by tugcekucukoglu** [comment]
I want to share a [demo link](https://stackblitz.com/edit/16r7fy?file=src%2FApp.vue). The 'body' templating is working as expected. If the problem still persists, please send us a reproducer link.

**Comment by yormy** [comment]
Wierd, when I open your link the 'togger' button does not do anything. Not in chrome, not in chrome-anonymous, not in firefox

**Comment by yormy** [comment]
What about for other people?. When I click in your link the 'expand all' button all rows expand, when I click on toggle nothing happens

**Comment by mertsincan** [comment]
Hi @yormy,

By adding a template to the expander button, you override its default behaviour. That's why you need to implement the toggle/collapse behaviour manually. I have attached a working example below. If your problem still persists, please send us a stackblitz link and write what steps we need to follow to see your case.

https://stackblitz.com/edit/16r7fy-5epxpj?file=src%2FApp.vue

Best Regards,

**Comment by tugcekucukoglu** [comment]
We add `rowTogglerCallback` for `body` template. If you want to track it, please check https://github.com/primefaces/primevue/issues/5123. The demo that I've shared will work fine with the next version.
