### ISSUE TITLE
Accordion: Click events getting propegated through to header

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#5042]
### Describe the bug

I have a InputText in the Accordion Header Template.  The problem is:  If I click on the inputtext to put focus, then the click event is propegated down to the header and the accordion tab gets collapsed.  How do I prevent this.  In other words, still collapse/expand as before, but not if there are any custom buttons, inputtext, etc within the header template of the accordion tab.

Try on:

[Codesanbox](https://codesandbox.io/p/devbox/blissful-panka-yjhn2c)

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Just try and put a Button in the header template of the accordion tab.  Then try and click on the button.  It should not collapse/expand the accordion tab.

**Comment by mertsincan** [comment]
Hi,

Please try `@click.stop`;
```
<Button
            size="small"
            severity="success"
            type="button"
            label="PRESS ME - SHOULD NOT COLLAPSE/EXPAND"
            class="mx-2 my-1 min-w-0"
            @click.stop
          />
```

Best Regards,
