### ISSUE TITLE
DataTable - expansion row lag with large dataset

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#5043]
### Describe the bug

This was supposedly [fixed in 3.45.0](https://github.com/primefaces/primevue/issues/4977) but it does not appear to be fixed.

Original issue logged here: https://github.com/primefaces/primevue/issues/4840

There is still a noticeable lag when clicking the expander button. As you can see in the reproducer link, it's a relatively simple table and the expansion row just contains `Hello World`.

### Reproducer

https://stackblitz.com/edit/prncz5-wzfzzf?file=src%2FTable.vue

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi,

Please see my note at https://github.com/primefaces/primevue/issues/4977. 

Updated; https://stackblitz.com/edit/prncz5-wdiqdf?file=src%2FTable.vue

Best Regards,
