### ISSUE TITLE
Datatable no function for sort and filter in lazymode

### ISSUE THREAD

**Issue by istanfrank** [primefaces/primevue#5044]
### Describe the bug

if lazy mode false it sort without problems. since update i guess after 3.43 it is not more sort.

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-84k7x8?file=/src/App.vue

### PrimeVue version

3.46

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Datatable with virtualarray and lazy=true will not sort. without it will osrt normal.

**Comment by istanfrank** [comment]
also filtering do not work in lazymode anymore.

**Comment by mertsincan** [comment]
Hi @istanfrank, 

In a lazy table, you need to perform such operations with callbacks. Please see our doc;
https://primevue.org/datatable/#lazy_load

```
...
const onPage = (event) => {
    lazyParams.value = event;
    loadLazyData(event);
};
const onSort = (event) => {
    lazyParams.value = event;
    loadLazyData(event);
};
const onFilter = (event) => {
    lazyParams.value.filters = filters.value ;
    loadLazyData(event);
};
...
```
Best Regards,
