### ISSUE TITLE
DataTable - pagination lag with large dataset

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#5045]
### Describe the bug

I am experiencing a problem with the pagination causing a noticeable lag when used with a large dataset.

On the reproducer link, I have 1000 rows and I have set a page size of 500 (so there are two pages). When clicking the page 2 button, you will notice it "hangs" for a second and then you see the selected page load. This is despite the fact I am using the `loading` prop to show a loading indicator, but this loading indicator does not appear as soon as you press the page button.

The table in the reproducer link is a very basic, unformatted table. The actual table I have in my project is more complex and has an expander column, as well as checkboxes and formatted data. This means the lag is a lot more noticeable - it is hanging for 3 seconds in my case.

I understand it could be slow due to the volume of data to load, however, if the loading indicator could appear instantly then that would really improve the user experience.

### Reproducer

https://stackblitz.com/edit/prncz5-jzs1x8?file=src%2FTable.vue

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Hi @omzy, this is related to the rendering time of the browser. Actually, we recommend lazy or virtualscroll features with paginator for such structures. Maybe, this link may help you even a little bit; https://dev.to/mertsincan/handling-big-data-on-datatable-with-checkbox-selection-multiselect-4hgc

Best Regards,
