### ISSUE TITLE
DataTable: Hydration attribute mismatch with sortable columns

### ISSUE THREAD

**Issue by Ky6uk** [primefaces/primevue#5046]
### Describe the bug

It looks like the code generated on the server is mismatched with the code generated on the client when the property `sortable` is enabled for the `Column` component.

It seems like icon SVG IDs generated on the client and server are different.

### Reproducer

https://stackblitz.com/edit/primevue-sortable-column-nuxt-bug?file=app.vue

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

1. Open [this](https://stackblitz.com/edit/primevue-sortable-column-nuxt-bug?file=app.vue) link.
2. Open the developer console in the browser.
3. Click on the reload preview icon.
4. See a warning in the developer console.
5. Remove `sortable` in the `Column` component.
6. Click on the reload preview icon.
7. Everything is fine now.

### Expected behavior

The same code is rendered on the server and client without warnings.

**Comment by mertsincan** [comment]
Interesting! I'll check it before the next release.

**Comment by bp26** [comment]
The same warnings appear when using Rating and Knob components. Most likely even more components are affected by this. Downgrading to previous versions doesn't help, this bug has been present at least since 3.41.0

**Comment by diego-lipinski-de-castro** [comment]
Same bug with Panel component
