### ISSUE TITLE
TreeTable : checkboxes are missing

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#5052]
### Describe the bug

After the update, the checkbox (selectionMode) disappeared. I'm using my cell template, but checkboxes worked before. Now they are simply not on the page

not work
![image](https://github.com/primefaces/primevue/assets/16963395/d46a8255-7980-4f4f-aeb5-f343ff594433)

and not work
![image](https://github.com/primefaces/primevue/assets/16963395/ebe6603d-402e-45c7-aef4-848a95ea8f90)

### Reproducer

no

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by ZiadJ** [comment]
Seems to be working fine with v3.4.6:
https://stackblitz.com/edit/yq2zcf?file=package.json

**Comment by NeluQi** [comment]
I found the reason. Sorry. css overlapped with another library and that was why it was hidden.

checkbox works
