### ISSUE TITLE
DataTable: Empty column causes maximum recursive calls to be reached

### ISSUE THREAD

**Issue by CodeNamedRobin** [primefaces/primevue#5053]
### Describe the bug

The following component gives a ERRORDING
```vue
<template>
  <DataTable>
    <Column/>
  </DataTable>
</template>
```

Providing a `field`  fixes the issue.
```vue
<template>
  <DataTable>
    <Column field="" />
  </DataTable>
</template>
```

### Reproducer

https://codesandbox.io/p/devbox/old-silence-7j7hlh

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Make DataTable with empty column
2. It dies
3. Add field
4. It doesn't die

### Expected behavior

Page doesn't die.

**Comment by richardshergold** [comment]
It's not just empty columns that cause this error.  I have a column that just displays a button in it:

<Column>
            <template #body="{ data }">
                <button class="view-button" @click="useScheduledMessage(data.id)">View</button>
            </template>
</Column>

I get this error now - but the error goes away if I add an empty header e.g

<Column header="">
            <template #body="{ data }">
                <button class="view-button" @click="useScheduledMessage(data.id)">View</button>
            </template>
</Column>

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/5069
