### ISSUE TITLE
Calendar: When use with Datatable filter, the calendar would show at the bottom of the page. 

### ISSUE THREAD

**Issue by anchan42** [primefaces/primevue#5055]
### Describe the bug

The calendar would show at the bottom of the page when the filter icon is clicked and the calendar field gets focused. Click on the calendar icon would make it disappear. Subsequent clicks or focus would work properly.

### Reproducer

https://codesandbox.io/p/devbox/primevue-demo-forked-69xnpd

### PrimeVue version

3.46

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on the Country filter icon.
2. Scroll down to see the calendar panel at the bottom of the page.

### Expected behavior

The calendar panel should show as a popup.

**Comment by mertsincan** [comment]
Unfortunately, I couldn't open the attached codesanbox link. @tugcekucukoglu Could you please try, too?

**Comment by tugcekucukoglu** [comment]
I have tried Chrome, Firefox, and Safari, and could not open. Could you share a new link?

**Comment by anchan42** [comment]
Please try the new link below:
https://stackblitz.com/edit/eivnbp?file=src%2FApp.vue

The original link still working for me but it show "@vnode-* hooks in templates are no longer supported." error now for some reason.

**Comment by tugcekucukoglu** [comment]
- When the Calendar receives focus, the Calendar panel will open. To prevent this default behavior, `showOnFocus` property can be changed to false. 
- I can not see any error message in the demo that you have sent about `@vnode-*`. It's Vue core related error and might be related your local dependencies.

**Comment by anchan42** [comment]
Sorry, I wasn't concise enough and also went off topic. Thanks a lot for looking in to this.

- Please see screen record for the Calendar component's problem. [Video](https://youtu.be/Dl21hdnIQKY)
- The @vnode-* problem is on Code Sandbox only and has nothing to do with PrimeVue. This is off topic and probably not worth wasting you time. Please see picture below anyway.

![image](https://github.com/primefaces/primevue/assets/19514416/f5f933cd-2716-41e4-8fc8-f8ba37c04440)

**Comment by tugcekucukoglu** [comment]
Thank you for the video. I can suggest using 'showOnFocus' property for Calendar. Because when Calendar receives focus, the panel will open

**Comment by anchan42** [comment]
Thanks, I am using showOnFocus as a work around for the moment.
I understand that when Calendar recieves focus, the default is that the panel will open.
But it should open as a popup panel like this:
![image](https://github.com/primefaces/primevue/assets/19514416/7878ca0d-84d1-472a-a9d4-93a9db13536c)

Instead of appending itself at the end of document like this:

![image](https://github.com/primefaces/primevue/assets/19514416/19902f5f-f193-47f4-8f01-5eb00dd85dd7)
