### ISSUE TITLE
DataTable: Column with no props throws exception

### ISSUE THREAD

**Issue by cnSchwarzer** [primefaces/primevue#5056]
### Describe the bug
```
<DataTable> 
    <Column>   <--  This throws bug in 3.46, normal in 3.44
      <template #body="{ data }: { data: WashJobTask }">
        <div class="flex flex-row-reverse gap-2 align-items-center">
          xxx
        </div>
      </template>
      <template #header>
        <div class="flex flex-row-reverse w-full gap-3 align-items-center">
           xxx
        </div>
      </template>
    </Column>
</DataTable>
```
### Reproducer

https://codesandbox.io/p/sandbox/nostalgic-tu-hj2v3g

### PrimeVue version

3.46

### Vue version

  "dependencies": {
    "@vitejs/plugin-vue": "4.3.4",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "primevue": "^3.46.0",
    "vite": "4.5.1",
    "vue": "3.3.4"
  },

Note: @vitejs/plugin-vue use 4.6.x will solve the issue.

### Language

TypeScript

### Build / Runtime

Vite

**Comment by CodeNamedRobin** [comment]
I think this is the same issue as #5053 ?
