### ISSUE TITLE
DataTable: persistent expandedRows with dataKey doesn't working properly

### ISSUE THREAD

**Issue by cnSchwarzer** [primefaces/primevue#5057]
### Describe the bug

I use pinia to store the expanded state { '1': true }, but when the page refresh and the data got loaded later, it doesn't expand and need to reset the expanded value manually to make it work. See reproducer.

### Reproducer

https://codesandbox.io/p/sandbox/practical-beaver-mlv9gy

### PrimeVue version

3.46

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi @cnSchwarzer,

Unfortunately, your codesandbox link doesn't open. Could you please update it? Thanks a lot for your report!

Best Regards,

**Comment by cnSchwarzer** [comment]
Does the codesandbox service down? I cannot open any box currently.

**Comment by mertsincan** [comment]
Of course, I'll check again before the next version is released. Thanks a lot fo your update ;)

**Comment by cnSchwarzer** [comment]
It can open now.

**Comment by mertsincan** [comment]
Hi @cnSchwarzer,

It opened. But, unfortunately, I couldn't replicate this issue. How can I replicate your case?

**Comment by cnSchwarzer** [comment]
Hi, @mertsincan 

Click on row expand and refresh the page, you can see that the row is not expanded as expected

However, like in the commented code, if we set expanded key to {} and set to the stored value in nextTick, it works.

You can see localStorage that the expanded key is stored but the component doesn't expand it.
