### ISSUE TITLE
OverlayPanel: wrong position after expanding body

### ISSUE THREAD

**Issue by pawelnykun** [primefaces/primevue#5058]
### Describe the bug

It seems that after expanding/collapsing the body section, the OverlayPanel does not get positioned correctly.

### Reproducer

https://codesandbox.io/p/devbox/immutable-dust-yrhdjl?file=%2Fsrc%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to link
2. Click "Show OverlayPanel" button to show OverlayPanel
3. Click "Add more content to body" button a few times

### Expected behavior

The OverlayPanel should recalculate self position every time when body section gets expanded/collapsed

**Comment by mertsincan** [comment]
Hi,

You can use `alignOverlay` method of OverlayPanel. Please try;
https://codesandbox.io/p/devbox/crazy-haslett-cz45r3?file=%2Fsrc%2FApp.vue%3A17%2C6

Best Regards,
