### ISSUE TITLE
Dropdown: After selecting an option, clearing the value using close icon should clear the filter input

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primevue#5060]
### Describe the bug

Dropdown: After selecting an option, clearing the value using close icon should clear the filter input.

### Reproducer

https://stackblitz.com/edit/mfbhvb?file=src%2FApp.vue

### PrimeVue version

3.46

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to https://primevue.org/dropdown/#filter
2. Pass showClear prop to clear the selected option using close icon.
3. Type desired value in the dropdown's filter field.
4. Select an option based on the ones provided post-filtering.
5. Unwrap dropdown.
6. Observe that the previously typed value in the filter field has not been cleared.
7. Clear the dropdown value by clicking on the clear icon.
8. Observe that the previously typed value in the filter field has not been cleared.

### Expected behavior

On clicking the clear icon, the previously typed value in the filter should clear.

**Comment by akshayaqburst** [comment]
This is an issue that I recently fixed in Primeng. Link for reference - Primeng PR link for reference - https://github.com/primefaces/primeng/pull/14511

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your PR and enhancement! But, this is not the right behaviour. They are independent of each other. It is normal for the filter to remain when you clear the value. For example, when you try an editable Dropdown in the same case and delete the selected text without using clearIcon, the filter will still remain. Please try with clearIcon and without clearIcon.
https://stackblitz.com/edit/mfbhvb-nmjvvq?file=src%2FApp.vue

Best Regards,

**Comment by mertsincan** [comment]
Also, this type of enhancement can be supported with a prop and the filter can be cleared only when pressing clearIcon. 
```
Prop's name;
resetFilterOnClear="true"
... another names :)
```

**Comment by akshayaqburst** [comment]
I hope you are working on it. Let me know if you need my help in anything. Thanks,

**Comment by mertsincan** [comment]
Honestly, a PR would be nice :)

**Comment by akshayaqburst** [comment]
Sure @mertsincan, will create a PR within next 12 hours
