### ISSUE TITLE
DataTable: Uncaught TypeError: Cannot read properties of null (reading 'sortable') at Proxy.getColumnPT8

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#5062]
### Describe the bug

Just a normal empty datatable is not working and throwing an error:
Uncaught TypeError: Cannot read properties of null (reading 'sortable')
![image](https://github.com/primefaces/primevue/assets/57847174/f69644fb-ca4b-4bb4-8979-3c79d35a638c)

My code:
```
 <DataTable :value="new Array(4)" class="p-datatable-sm">
      <Column>
        <template #body>
          <Skeleton height="0.4rem" animation="none"></Skeleton>
        </template>
      </Column>
      <Column>
        <template #body>
          <Skeleton height="0.4rem" animation="none"></Skeleton>
        </template>
      </Column>
    </DataTable>
```

### Reproducer

https://stackblitz.com/edit/ceg4gb?file=src%2FApp.vue

### PrimeVue version

3.46

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll fix it for the next version.

**Comment by cnSchwarzer** [comment]
Same as #5056
