### ISSUE TITLE
@mouseenter on an element disabled v-tooltip

### ISSUE THREAD

**Issue by iampapagray** [primefaces/primevue#5063]
I have a div with a v-tooltip that works fine. I am now required to perform some actions when the div is hovered, thus i use the @mouseenter to run a method. 

However, once i add @mouseenter to the div, the tooltips are not displayed anymore. Is there a workaround?

Please help

**Comment by mertsincan** [comment]
Hi,

This behaves similarly to the behaviour of the browser. Therefore, you can wrap your disabled element with <span> or <div style="inline-block"> tag. This is a recommended behaviour.

```
<div style="inline-block" v-tooltip ...>
   <div> // disabled
</div>
```

Best Regards,

**Comment by iampapagray** [comment]
@mertsincan I'm confused with your response. I am not dealing with a disabled element.

**Comment by mertsincan** [comment]
Ops! Sorry for the confusion! I've checked a lot of issues, and I think it's time to take a break :) I'll check it again.

Sorry again :/

**Comment by tugcekucukoglu** [comment]
[This example](https://stackblitz.com/edit/1aaz5y?file=src%2FApp.vue) seems to be working. How can we replicate the issue?

**Comment by iampapagray** [comment]
> [This example](https://stackblitz.com/edit/1aaz5y?file=src%2FApp.vue) seems to be working. How can we replicate the issue?

Mmm.. Your sample seems to work fine. Maybe it could be because im doing this within a template in the Timeline component. I'll go over it again and maybe post a snippet here. Thanks for you help

**Comment by tugcekucukoglu** [comment]
Closing the issue due to inactivity. If the problem still persists, please let us know.

Thank you,
