### ISSUE TITLE
Multiselect: Does not show options when the last value is selected

### ISSUE THREAD

**Issue by lakkvak** [primefaces/primevue#5064]
### Describe the bug

Create a multiselect with a virtual scroll, select the last item (You can and not quite the last). Open the panel with the list and there will be empty, if you scroll a little the items will reappear. 
![image](https://github.com/primefaces/primevue/assets/79806441/623551c5-d79a-4cd6-b77b-7e57eac04e38)

### Reproducer

https://codesandbox.io/s/grfjl6

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll fix it before the next version is released.

Best Regards,

**Comment by antlionguard** [comment]
if selected item index 10 or more  this problem happens.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/5130
