### ISSUE TITLE
Dropdown: autoSize works incorrectly with filter and not only

### ISSUE THREAD

**Issue by lakkvak** [primefaces/primevue#5073]
### Describe the bug

When first opened, the height of the list will always be equal to scrollHeight, even if the number of items fits into a smaller size. When you enter a filter value, the height is set to the correct size, but I would like it to set the automatic height when opening the dropdown. 
![image](https://github.com/primefaces/primevue/assets/79806441/46c88748-0727-4045-b776-4c51c3cc6011)

Also after entering the filter value and closing the dd, and after a new opening the height is not set automatically 
![image](https://github.com/primefaces/primevue/assets/79806441/74b8a5ad-690e-4d4d-8d21-00b175a72d23)

Without a filter, the height does not adjust for the number of elements![image](https://github.com/primefaces/primevue/assets/79806441/5e1e86b9-9df1-4ff0-a8af-59cb076375f5)

### Reproducer

https://stackblitz.com/edit/aqjwcg?file=src%2FApp.vue

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

The height should automatically adjust to the number of elements when dd is first opened

**Comment by mertsincan** [comment]
Thanks a lot for your report! It seems like a bug. I added a milestone for this ticket. We'll fix it in the tagged milestone.

Best Regards,
