### ISSUE TITLE
DropDown: CSP nonce not present on virtual scroller style

### ISSUE THREAD

**Issue by alfisdad** [primefaces/primevue#5074]
### Describe the bug

When using the dropdown component, I get a CSP "refused to apply inline style" error when clicking on the element. The style element is:
```
<style type="text/css" data-primevue-style-id="virtualscroller">
.p-virtualscroller {
    position: relative;
    overflow: auto;
    contain: strict;
    transform: translateZ(0);
    will-change: scroll-position;
    outline: 0 none;
}

.p-virtualscroller-content {
    position: absolute;
    top: 0;
    left: 0;
    /* contain: content; */
    min-height: 100%;
    min-width: 100%;
    will-change: transform;
}

.p-virtualscroller-spacer {
    position: absolute;
    top: 0;
    left: 0;
    height: 1px;
    width: 1px;
    transform-origin: 0 0;
    pointer-events: none;
}

.p-virtualscroller .p-virtualscroller-loader {
    position: sticky;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

.p-virtualscroller-loader.p-component-overlay {
    display: flex;
    align-items: center;
    justify-content: center;
}

.p-virtualscroller-loading-icon {
    font-size: 2rem;
}

.p-virtualscroller-loading-icon.p-icon {
    width: 2rem;
    height: 2rem;
}

.p-virtualscroller-horizontal > .p-virtualscroller-content {
    display: flex;
}

/* Inline */
.p-virtualscroller-inline .p-virtualscroller-content {
    position: static;
}
</style>
```

### Reproducer

Can't replicate in codesandbox as can't get nonce to work there

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add Content Security Policy for styles in <HEAD> of index.html e.g. `<meta http-equiv="Content-Security-Policy" content="style-src 'self' 'nonce-123456789'">`
2. Add csp nonce 123456789 in Primevue configuration
3. Add Dropdown component to a view
4. CSP error shows in DevTools when dropdown is activated

### Expected behavior

Nonce is added as an attribute to the style element and no CSP error is reported

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll fix it on the next version.

**Comment by alfisdad** [comment]
Great! Thanks. BTW - loving PrimeVue. Switched from Vuetify as PrimeVue is much better for accessibility.
