### ISSUE TITLE
Editor: Accessibility issue with tab key

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5076]
### Describe the bug

Hello, sorry for my english. When you press the tab key inside the editor you expect it to navigate to another focusable element but the editor adds a /t and the user is stuck in the editor.

### Reproducer

.

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

JavaScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hello, no problem ;)
Interesting issue! Could you please try it with Quill.js? Our editor component uses Quill.js API.

**Comment by JoseAntonioNavasSolutia** [comment]
I think it's a quill.js problem because I hit the tab key and it doesn't focus on the text area.

Reproductor: https://codesandbox.io/p/devbox/jovial-dust-66933x?file=%2Fsrc%2FApp.vue

**Comment by mertsincan** [comment]
Thanks a lot for the update! Could you please create a Github issue on Quill.js repo? 

Best Regards,
