### ISSUE TITLE
Calendar: Incorrect interface "CalendarContext" for Calendar component

### ISSUE THREAD

**Issue by Nik-Str** [primefaces/primevue#5077]
### Describe the bug

Framwork: PrimeVue (Unstyled and Tailwind)
Version: 3.46.0
Component: Calendar
TypeScript: true 

// Current exported interface
```ts
export interface CalendarContext {
    date: string | Date | string[] | Date[] | undefined | null;
    today: boolean;
    otherMonth: boolean;
    selected: boolean;
    disabled: boolean;
    month: CalendarMonthOptions;
    monthIndex: number;
    year: CalendarYearOptions;
}
```
// Type that is shown if console.log context
```ts
type ContextExample = {
  date: {
    day: number
    month: number
    year: number
    otherMonth: boolean
    selectable: boolean
    today: boolean
  }
  disabled: boolean
  selected: boolean
}
```
### Reproducer

*

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

No need to reproduce, just check the export and compare to calendar "dayLabel" prop in the Lara example given:
https://tailwind.primevue.org/calendar/

Reference:
text-primary-500 dark:text-primary-400":_**e.date.today**_

**Comment by mertsincan** [comment]
Thanks a lot, @Nik-Str! We'll check it before the next version is released.
