### ISSUE TITLE
Button: Override cursor: default !important when button is disabled

### ISSUE THREAD

**Issue by ancagavrilescu** [primefaces/primevue#5079]
### Describe the bug

Hello,

We are trying to create a custom theme for our library, but we encounter a problem while styling the Button component.
If one tries to override the style for when the Button component is disabled, one cannot because of the: 
`.p-disabled, .p-disabled * {
    cursor: default !important;
    pointer-events: none;
    user-select: none;
}`.

We would like to be able to style it differently, with cursor: not-allowed.

Can you please guide us on what we should do?

Thank you!

### Reproducer

https://codesandbox.io/s/4wzgj2

### PrimeVue version

3.43.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Interesting! We wrap p-disabled style with @layer primevue. Could you please try your style without @layers?
Exp;
```
.p-disabled, .p-disabled * { cursor: not-allowed; pointer-events: auto; }
```

Best Regards,

**Comment by ancagavrilescu** [comment]
Hi,

Thank you for responding, I apologise, but just to be sure I understand correctly what you're suggesting: you're suggesting that we should comment the import from _component.scss file for the button?
