### ISSUE TITLE
Autocomplete bug: Data key is ignoring and component allowing dulicates in v-model

### ISSUE THREAD

**Issue by MarcelGeo** [primefaces/primevue#5080]
### Describe the bug

In autcomplete - duplicate values are allowed in multiple mode. Prop ```data-key``` attribute is defined correctly as key of object in v-model but duplicates occurring.

Value and suggestions are array of objects ```{key: number, label: string}```.
![image](https://github.com/primefaces/primevue/assets/12643115/352f3354-5ba0-421a-9ea1-6633cfe4dbb7)

### Reproducer

https://codesandbox.io/p/devbox/practical-meadow-sjjy29?file=%2Fsrc%2FApp.vue%3A21%2C6-24%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrapcy2000072066x24alx69%2522%252C%2522sizes%2522%253A%255B42.37308146399056%252C57.62691853600944%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrapcy2000022066b1ngooa6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrapcy2000042066ppnrtqn1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrapcy2000062066ptmlme5t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrapcy2000022066b1ngooa6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrapcy2000012066swissiwf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrapdnty003x2066pm8daqu5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrapcy2000022066b1ngooa6%2522%252C%2522activeTabId%2522%253A%2522clrapdnty003x2066pm8daqu5%2522%257D%252C%2522clrapcy2000062066ptmlme5t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrapcy2000052066dolwikuq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrapcy2000062066ptmlme5t%2522%252C%2522activeTabId%2522%253A%2522clrapcy2000052066dolwikuq%2522%257D%252C%2522clrapcy2000042066ppnrtqn1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrapcy2000032066fec4r8gf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrapcy2000042066ppnrtqn1%2522%252C%2522activeTabId%2522%253A%2522clrapcy2000032066fec4r8gf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to example
2. Start write something to autocomplete input
3. Select first suggestion
4. Select the same suggestion

### Expected behavior

If dataKey attribute is defined, disallow duplicated chips in multiple mode.

**Comment by mertsincan** [comment]
Hi @MarcelGeo,

There is no structure to prevent duplicate items in the AutoComplete with multiple. I think you can control it with modelValue and @update:modelValue. Exp;
```
<AutoComplete modelValue="values" @update:modelValue="setValues" ... />

setValues(newValues) {
     // prevent duplicate items in newValues
    values = ...
}
```
If you want this type of structure to be included in Primevue core, can you create a ticket in the Primevue discussion so that other users can upvote? Thanks a lot!

Best Regards,

**Comment by MarcelGeo** [comment]
@mertsincan If I pass non existing key to ```dataKey``` props, there is also highlighting enabled by default from primevue. Highlighting of selected option is not working with existing dataKey.

https://codesandbox.io/p/devbox/practical-meadow-sjjy29?file=%2Fsrc%2FApp.vue%3A39%2C22

Every option is highlighted with purple color:

![image](https://github.com/primefaces/primevue/assets/12643115/3492b3a5-69f1-4634-8cca-39b181845356)

```
<AutoComplete
    v-model="value"
    multiple
    optionLabel="label"
    @complete="search"
    :suggestions="items"
    dataKey="nonexistentKey"
  />
```
