### ISSUE TITLE
DataView: Not displaying items in grid, though does display in list

### ISSUE THREAD

**Issue by shaunc** [primefaces/primevue#5083]
### Describe the bug

The DataView component renders as empty in "grid" mode, though it works in "list" mode.
```vue
<script setup lang="ts">
import DataView from "primevue/dataview"

const sectionDatapoints = [
  { name: "test", dp_name: "test" }
]
</script>

<template>
  <DataView :value="sectionDatapoints" layout="grid" dataKey="dp_name">
    <template #list="slotProps">
      <div class="grid grid-nogutter">
        <div v-for="item in slotProps.items" :key="item.dp_name">
          {{ item.name }}
        </div>
      </div>
    </template>
  </DataView>
</template>
```
This will display an item when `layout` is changed to `"list"`, but displays none as is.

### Reproducer

https://codesandbox.io/p/devbox/primevue-create-vue-issue-template-kw9g6i?file=%2Fsrc%2FApp.vue%3A10%2C7&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrcwvsd400073b5wcs6s22pk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrcwvsd300023b5wosolplmj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrcwvsd300043b5w9sdunhgt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrcwvsd400063b5wmusoxp6m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrcwvsd300023b5wosolplmj%2522%253A%257B%2522id%2522%253A%2522clrcwvsd300023b5wosolplmj%2522%252C%2522activeTabId%2522%253A%2522clrcx1sw800e13b5wmd0g1u44%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcwvsd300013b5w5vb5vxuf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrcwwpk6003f3b5wjqq9skno%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A7%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clrcx1sw800e13b5wmd0g1u44%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clrcwvsd400063b5wmusoxp6m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcwvsd400053b5wv3m6buez%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrcwvsd400063b5wmusoxp6m%2522%252C%2522activeTabId%2522%253A%2522clrcwvsd400053b5wv3m6buez%2522%257D%252C%2522clrcwvsd300043b5w9sdunhgt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcwvsd300033b5w59e8x5dm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrcwvsd300043b5w9sdunhgt%2522%252C%2522activeTabId%2522%253A%2522clrcwvsd300033b5w59e8x5dm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome v  120.0.6099.129

### Steps to reproduce the behavior

Will display empty as is.

### Expected behavior

Should display an item.

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check it before the 3.38 version is released. Thanks a lot for your understanding! 

Best Regards,

**Comment by tugcekucukoglu** [comment]
The `layout` property will tell which DataView will work in which mode. Therefore, #grid slot should be preferred in grid mode and #list slot in list mode.
