### ISSUE TITLE
Please reopen 5041, added comments, but cannot reopen ticket

### ISSUE THREAD

**Issue by yormy** [primefaces/primevue#5084]
### Describe the bug

Please reopen 
https://github.com/primefaces/primevue/issues/5041

Added comments on what is going on. I could not find a button to reopen teh ticket

### Reproducer

x

### PrimeVue version

3.45

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

xxxx

### Steps to reproduce the behavior

x

### Expected behavior

xxxxx

**Comment by mertsincan** [comment]
Sorry for the confusion. It would be better if we continue with the main issue. Thanks a lot for your report!
