### ISSUE TITLE
DataTable: The initial value of expendedRow is not reflected and the value change is not detected. 

### ISSUE THREAD

**Issue by bdh92123** [primefaces/primevue#5086]
### Describe the bug

If the expandedRow props of a DataTable is specified as an initial value along with some data, it is not reflected.
- It seems to operate by watching expandedRows prop, and the immediate property appears to be false.

If only part of the data specified as expandedRows is modified externally, it will not be reflected.
- Due to the same problem as above, the deep property seems to be false when watching expandedRows. It seems problematic that the entire value must be replaced to be reflected.

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-ym4crg

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 

### Steps to reproduce the behavior

Initial values not being reflected
1. Specifies an initial value for expandedRows along with some data.
2. The specified row is not expanded.

Partial modifications to the expandedRows value are not reflected
1. Add the dataKey of a specific row as true in the expandedRows value.
2. The specified row is not expanded.

### Expected behavior

1. It should appear expanded with the initial data.
2. Some modifications to the expandedRows value must also be reflected.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll check it before the next version is released.

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed in https://github.com/primefaces/primevue/issues/5057

Best Regards,
