### ISSUE TITLE
Toast doesnt work

### ISSUE THREAD

**Issue by kayahasa** [primefaces/primevue#509]
app.component('Toast', Toast);

this.$toast.add({ severity: 'info', summary: 'Info Message', detail: 'Message Content', group: 'tl', life: 3000 });

Doesnt work with no Logs

**Comment by cagataycivici** [comment]
You need to configure ToastService as well. Please use forum for cases like these;

https://forum.primefaces.org/viewforum.php?f=110

See: https://primefaces.org/primevue/showcase/#/toast
