### ISSUE TITLE
InputNumber: update:modelValue event is not triggered until blur event

### ISSUE THREAD

**Issue by gauravjhs** [primefaces/primevue#5090]
### Describe the bug

update:modelValue should be triggered on every input change. This event is only triggered once we remove focus from the component. InputText component works as expected.

### Reproducer

https://stackblitz.com/edit/m3wdph?file=src%2FApp.vue

### PrimeVue version

3.46.x

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome, Edge

### Steps to reproduce the behavior

Change the number in the component without removing focus on the component

### Expected behavior

The changed number should be visible in the display area as well.

**Comment by mertsincan** [comment]
Hi,

I think you can use @input event for it. Please see the details;

The **input** event parses the value in the current input field and returns it to model. The value that comes to the model is the value that is **not validated**. This event is called every time one presses a key.

**In current behavior**, the model is updated in three ways;
1. Clicking outside to validate the change after changing something in inputNumber.
2. Changing the value using spinner's button/arrow keys
3. Pressing the 'enter' key

And the value that comes to the model is the value that is **validated**.

**Comment by omzy** [comment]
Any reason why this behaviour is inconsistent with other form controls? For example, `InputText` component fires the `update:modelValue` event on keyup.
