### ISSUE TITLE
DataTable: Dropdown doesn't reposition on click of filter menu

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#5093]
### Describe the bug

When using PrimeVue in unstyled mode, the dropdown menu which shows the different filter options doesn't reposition. To my understanding and by looking at the source code, it appears that this repositioning is done on mount of the overlay.

![image](https://github.com/primefaces/primevue/assets/49190778/300596c5-1c9c-47c0-93be-6b814328b3d4)

Here are the classes which I have applied. I have tried applying absolute positioning however as the overlay is mounted to the body and not the component this unfortunately doesn't give the desired output.
![image](https://github.com/primefaces/primevue/assets/49190778/e79881fd-f36c-4540-a5ee-53b021076f9b)

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Interesting! Could you please attach a stackblitz link for us to replicate?

**Comment by JakeMinor** [comment]
Thanks for the fast response, turns out it actually works fine! It's just doesn't work properly in the Cypress runner for some reason 🤷🏻‍♂️
