### ISSUE TITLE
Knob: Problem with the step property when using the keyboard arrows

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5097]
### Describe the bug

Hello.
When, for example, I set step=4 and the knob receives focus and i use the keyboard arrows increase/decrease the value by 1 instead of 4.

### Reproducer

https://codesandbox.io/p/devbox/goofy-paper-qpx2t4?file=%2Fsrc%2FApp.vue%3A9%2C31

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

Chrome / Edge

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll fix it before the milestone is released.
