### ISSUE TITLE
Reimplement TabView with Templating

### ISSUE THREAD

**Issue by lochstar** [primefaces/primevue#51]
I get an error when trying to import the `TabView` component:

`You may need an additional loader to handle the result of these loaders.`

This is because of the use of JSX for this component, commit is here: https://github.com/primefaces/primevue/commit/b3036ec6140d9d542d0e0e869d01ce9ad351f865

Is it a requirement we must include https://github.com/vuejs/jsx in order to build this project? Can we refactor the JSX back to Vue template format? It's not clear to me why it had to be changed.

**Comment by cagataycivici** [comment]
I think we can redo the tabview with templating, I'll check this.
