### ISSUE TITLE
Dialog component VNode

### ISSUE THREAD

**Issue by kayahasa** [primefaces/primevue#510]
using Dialog Node as:
  <Dialog header="Header" v-model:visible="display">
    Content
  </Dialog>

causes below log and doesnt work:
[Vue warn]: resolveDirective can only be used in render() or setup().
runtime-core.esm-bundler.js:233
[Vue warn]: Invalid VNode type:

**Comment by cagataycivici** [comment]
Could you please provide more info or a sample project to help us replicate?

**Comment by tReMaker** [comment]
`vue create test`
select preset vue 3
`npm install primevue --save`

src/App.vue
```
<template>
  <Button label="Submit" />
</template>

<script>
import Button from 'primevue/button';

export default {
  name: 'App',
  components: {
    Button
  }
}
</script>
```

`npm run serve`

in browser console
runtime-core.esm-bundler.js?53ba:38 [Vue warn]: resolveDirective can only be used in render() or setup().
runtime-core.esm-bundler.js?53ba:38 [Vue warn]: withDirectives can only be used inside render functions.
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol)

**Comment by kayahasa** [comment]
Exactly the same error, Thanks tReMaker 👍 

Does using Composition API must ?

**Comment by cagataycivici** [comment]
We're working to resolve the issue.

**Comment by kayahasa** [comment]
Please note that, this issue is valid for some other components like DataTable, Toast and Dialog (i have tried these components, there may be others)

**Comment by cagataycivici** [comment]
This is caused by #511, try with 3.0.0-rc.2 to resolve this problem.
