### ISSUE TITLE
DataTable: Cannot read properties of null when  editMode="cell" and  selectionMode="single"

### ISSUE THREAD

**Issue by lakkvak** [primefaces/primevue#5100]
### Describe the bug

If the table has a props  `selectionMode="single"`, ` editMode="cell"`  
And in the column body template we have a div, not a pure value. ![image](https://github.com/primefaces/primevue/assets/79806441/de011761-240a-4b69-885f-e088109f7749)
   
 there will be an error in the console when clicking on a cell 
 `chunk-LI252WGL.js?v=e3bda5c5:1700 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')`
![image](https://github.com/primefaces/primevue/assets/79806441/3521a6ee-4efc-4243-afed-864a76c85176)

### Reproducer

https://stackblitz.com/edit/aghk4e?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll fix it asap.
