### ISSUE TITLE
Sidebar: Can't change the size of the sidebar.

### ISSUE THREAD

**Issue by tripex** [primefaces/primevue#5101]
### Describe the bug

When adding the sidebar, the documentation states that i can change the size of the sidebar, using the class. 
However, I use tailwind, and the width of the sidebar is constantly w-80 even if I add class w-5/6 

### Reproducer

codesandbox did not work

### PrimeVue version

3.40.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Add the sidebar to the mockup, change the class to a width, and see nothing changes.

### Expected behavior

It should change the size of the sidebar when adding a width class.

**Comment by mertsincan** [comment]
Interesting! Do you see w-80 class for sidebar in DOM? I set a milestone, we'll check before the milestone is released.

**Comment by tripex** [comment]
> Interesting! Do you see w-80 class for sidebar in DOM? I set a milestone, we'll check before the milestone is released.

Yes, this is the open div tag on the element.

`<div role="complementary" aria-modal="true" class="flex flex-col pointer-events-auto relative transition-transform duration-300 bg-white text-gray-700 border-0 shadow-lg h-full w-80 dark:border dark:border-blue-900/40 dark:bg-gray-900 dark:text-white/80" data-pc-name="sidebar" data-pc-section="root" data-pd-focustrap="true">`

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate it. Please try;
https://stackblitz.com/run?file=src%2FApp.vue
Demo: https://tailwind.primevue.org/sidebar/

For now, moved to next version. Could you please attach a sample link for us to replicate?

Best Regards,

**Comment by tugcekucukoglu** [comment]
`mergeProps` option can be set as `true` of `ptOptions` property and use the !important prefix of Tailwind. Similar examples can be found in [docs](https://tailwind.primevue.org/guides/overriding-presets/#important)
