### ISSUE TITLE
DataTable: Column Resizing doesn't work as expected using unstyled mode.

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#5104]
### Describe the bug

When trying to resize the columns in the DataTable in either fit or expand mode, the columns seem to act very inconsistently in the way which they resize. In some cases, they will snap to a small size and other times they won't resize at all. 

There is a possibility that I could be missing some CSS, in which case please let me know! however I have compared what I have to the tailwind passthrough and it seems to be fairly similar if not the same.

https://github.com/primefaces/primevue/assets/49190778/50f13d7f-edea-4b17-bea6-34434d37b155

### Reproducer

https://stackblitz.com/edit/vue-ykt4c6

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone and we'll fix this issue before the milestone is released.

**Comment by JakeMinor** [comment]
Amazing thank you!

**Comment by mertsincan** [comment]
Hi @JakeMinor,

I updated your custom preset. Please see;
https://stackblitz.com/edit/vue-ifm6wq?file=src%2Fmain.js%3AL640

Also, you can use our tailwind preset to update it.
https://tailwind.primevue.org/datatable/#resize_fitmode

Best Regards,

**Comment by nirmalFullstack120589** [comment]
@mertsincan 
what exact changes made in presets?

**Comment by rickvosta** [comment]
Wow, the thing that fixes this is adding the resize indicator css back in.. That's rough.

    :pt="{
      columnResizeIndicator: {
        style: 'position: absolute; width: 2px; background-color: blue; z-index: 11;',
      },
    }"

This is the fix I applied. Hope this helps someone.
