### ISSUE TITLE
Calendar: 12h time picker changes from 12 am to 12 pm automatically

### ISSUE THREAD

**Issue by dmhendricks** [primefaces/primevue#5108]
### Describe the bug

If the 12-hour time picker contains a time between midnight and 1am, it will automatically switch to `pm` if a new date is selected. Previously mentioned in #4449.

This has caused a number of scheduling incidents with users when they pull up a document, change the date, and don't notice that the `am` subtly and automatically changes to `pm`.

### Reproducer

(see steps to reproduce below)

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

You can reproduce it on the current v3.46.0 [documentation page](https://primevue.org/calendar/) demo:

1. Go here: https://primevue.org/calendar/
2. Select a date and time. Make the time 12:xx **AM**. Example:
<img width="396" alt="Screenshot 2023-10-11 at 10 56 36 AM" src="https://github.com/primefaces/primevue/assets/8184361/32e4478e-6098-4a20-8229-35502d172848">

3. Click off of field to remove focus (you can click anywhere else on the page)
4. Click on the field again and select any **date** (don't touch the time, just change the date). When you do that, the "am" will automatically change to "pm" even though the time wasn't changed/touched:
<img width="392" alt="Screenshot 2023-10-11 at 10 58 51 AM" src="https://github.com/primefaces/primevue/assets/8184361/089b8eae-e7ef-4157-befe-a23b0272dc5e">

### Expected behavior

If you click the field to change the date, the time that was previously selected should be preserved rather than automatically switching from `am` to `pm`.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone and we'll fix it before the milestone is released. Best Regards,
