### ISSUE TITLE
TabView + Splitter: Navigation Buttons not showing

### ISSUE THREAD

**Issue by quaro77** [primefaces/primevue#5111]
### Describe the bug

when creating a TabView with scrollable="true" inside a Splitter panel, the NextButton in the left tab panel is not shown. I need to click on the right corner of the tabs to make it show, and from that moment the button is correctly visible.

I tried creating a CodeSandbox example, but Splitter doesn't seem to work correctly there.

Example code in the comment

### Reproducer

https://codesandbox.io/p/devbox/thirsty-saha-3wfnws?file=%2Fsrc%2FApp.vue

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

1. There is no NextButton in the left TabView
2. Click in the rightmost corner of the visible tab titles
3. The NextButton should now show and work as intended

### Expected behavior

NextButton visible from the beginning if all the tabs are not visible on screen

**Comment by quaro77** [comment]
<template>
<div id="container" style="width: 500px; height: 500px;">
  <Splitter style="height: 100vh" class="mb-5">
      <SplitterPanel :size="10" :minSize="5">
        <TabView :scrollable="true">
          <TabPanel header="Item 1"> </TabPanel>
          <TabPanel header="Item 2"> </TabPanel>
          <TabPanel header="Item 3"> </TabPanel>
          <TabPanel header="Item 4"> </TabPanel>
          <TabPanel header="Item 5"> </TabPanel>
          <TabPanel header="Item 6"> </TabPanel>
          <TabPanel header="Item 7"> </TabPanel>
        </TabView>
      </SplitterPanel>
      <SplitterPanel :size="90" :minSize="50">
        <TabView :scrollable="true">
          <TabPanel header="Item 1"> </TabPanel>
          <TabPanel header="Item 2"> </TabPanel>
          <TabPanel header="Item 3"> </TabPanel>
        </TabView>
      </SplitterPanel>
    </Splitter>
    </div>
</template>

**Comment by mertsincan** [comment]
Interesting! I set a milestone and we'll check before the milestone is released.
