### ISSUE TITLE
DataTable: Converting circular structure to JSON error when trying to pass scope to column slots

### ISSUE THREAD

**Issue by JakeMinor** [primefaces/primevue#5115]
### Describe the bug

I've recently being trying to create a wrapper around the DataTable/Column to create a custom table. The aim is to pass columns, items and the rest of the props to the wrapper component and have it generate a data table with full customisability via scoped slots in a similar way to [Bootstrap-Vues table](https://bootstrap-vue.org/docs/components/table#header-and-footer-custom-rendering-via-scoped-slots). 

As the columns are treated as separate components to the table, I have started out by splitting out the slots into different arrays; one for columns and one for the datatable. In order to allow for individual columns to be targeted by slots, I have split them out even further by naming the slot in the following convention `#COLUMN_SLOT_NAME(column(NAME_OF_COLUMN))` - An example of this would be `#header(column(id))`. In my wrapper component when dynamically generating each column based on the one passed in from the parent, I split the column scopes down further by filtering the ColumnSlots array down by matched the field properties of the column so that they are not overwritten. In order to visualise this further, I have attached a StackBlitz link showing the implementation

This provides a great implementation of how I would like my wrapper component to work, however, when I try to pass the scope of the slot which is provided by the Column component. I get the following error:

![image](https://github.com/primefaces/primevue/assets/49190778/0c72aa1c-34d1-48d5-89bf-893dae53960d)

Would you be able to point me in the right direction where I am going wrong? Is this a flaw of the DataTable or simply not possible due to my implementation?

Thank you in advance :)

### Reproducer

https://stackblitz.com/edit/vue3-script-setup-with-vite-sclour?file=src%2FApp.vue

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi,

Wooww, a different perspective ;) I checked your codes. This is related to `{{ scope }}` binding. Please update your code;
```
//<template #header(column(id))="scope">{{ scope }}</template>
<template #header(column(id))="scope">{{ scope?.column?.props?.field }}</template>
```
The header template exports `column` instance. https://github.com/primefaces/primevue/blob/master/components/lib/datatable/HeaderCell.vue#L28

Best Regards,
