### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by brunocbcsilva** [primefaces/primevue#5116]
### Describe the bug

When using the calendar component with the "`selectionMode='range'`" prop, the first selected month receives the "`p-highlight`" class. However, upon selecting the next month, i.e., the second month, the element does not receive the "`p-highlight`" class, aesthetically hindering the visualization of selected periods in the component.

### Reproducer

https://codesandbox.io/p/devbox/primevue-create-vue-issue-template-kw9g6i?file=%2Fsrc%2FApp.vue%3A11%2C3-11%2C58&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrksjqq800072v6ihf9q4lok%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrksjqq800022v6ilm0nlvlu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrksjqq800042v6ikzbstu1b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrksjqq800062v6ig81745zh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrksjqq800022v6ilm0nlvlu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrksjqq700012v6i4gf458vl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrkt7mv3002a2v6hfl7jw3jz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A58%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrksjqq800022v6ilm0nlvlu%2522%252C%2522activeTabId%2522%253A%2522clrkt7mv3002a2v6hfl7jw3jz%2522%257D%252C%2522clrksjqq800062v6ig81745zh%2522%253A%257B%2522id%2522%253A%2522clrksjqq800062v6ig81745zh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrksjqq800052v6ixy48kcf5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrksjqq800052v6ixy48kcf5%2522%257D%252C%2522clrksjqq800042v6ikzbstu1b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrksjqq800032v6iyqevswv3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrksjqq800042v6ikzbstu1b%2522%252C%2522activeTabId%2522%253A%2522clrksjqq800032v6iyqevswv3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1 - Click on the Calendar component;
2 - Select the first date;
3 - Select the second date;

Note: Upon selecting the second date, the element does not receive a visual highlight similar to the first element.

### Expected behavior

The second element should receive the same visual highlight as the first element.

**Comment by mertsincan** [comment]
Interesting! Which theme are you using? I checked startDate and endDate. They both have the p-highlight class. Could you please attach a sample stackblitz link and screenshot to replicate it?

Also, I set a milestone. If you attach them, we will check before the milestone is released.

Best Regards,
