### ISSUE TITLE
"Date is after" filter option doesn't work properly

### ISSUE THREAD

**Issue by kadennguyen10** [primefaces/primevue#5117]
### Describe the bug

Hi guys, I really need your help on this issue.
I’ve encountered an issue with the date filtering feature with the Primevue Calendar. When selecting the "Date is after" filter option, the results include entries from 08/30/2023, but I expected it to display dates starting from 08/31/2023 onwards.

Could you please clarify if this is a known issue? Additionally, if there’s a workaround to obtain the correct filtering results (dates after 08/30/2023), that information would be greatly appreciated.

Thank you
![CalendarPrimevue](https://github.com/primefaces/primevue/assets/76994128/241e5373-2269-4201-9544-bfeebfa58fe8)

### Reproducer

https://github.com/primefaces/primevue/assets/76994128/241e5373-2269-4201-9544-bfeebfa58fe8

### PrimeVue version

3.34.1

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

I’ve encountered an issue with the date filtering feature with the Primevue Calendar. When selecting the "Date is after" filter option, the results include entries from 08/30/2023, but I expected it to display dates starting from 08/31/2023 onwards.

### Expected behavior

 I expected it to display dates starting from 08/31/2023 onwards.

**Comment by kadennguyen10** [comment]
Please update the status for this issue.

**Comment by mertsincan** [comment]
Interesting! We're using the following code to compare the dates;
```
dateAfter(value, filter) {
            if (filter === undefined || filter === null) {
                return true;
            }

            if (value === undefined || value === null) {
                return false;
            }

            return value.getTime() > filter.getTime();
        }
``` 
Could you please attach a sample stackblitz link for us to replicate? Also, I set a milestone for this ticket. We'll check it before the milestone is released.

Best Regards,

**Comment by mertsincan** [comment]
Hi,

Please see comment; https://discord.com/channels/787967399105134612/787968875135762452/1199076953735565342

Best Regards,
