### ISSUE TITLE
The CascadeSelect component loads data on demand,

### ISSUE THREAD

**Issue by weitianhao** [primefaces/primevue#5120]
The CascadeSelect component loads data on demand, similar to selecting a country and then loading the current country's provinces, and so on.

**Comment by mertsincan** [comment]
Unfortunately, it is not possible for now.  Can you create a discussion ticket for this feature? https://github.com/orgs/primefaces/discussions/categories/primevue Then, we can also expect upvotes from other users about this. We will be happy to implement this when there are enough upvotes. Thanks a lot for your understanding!
