### ISSUE TITLE
Badge: Add pass through property to v-badge if using pass through locally in a component

### ISSUE THREAD

**Issue by mbaljeetsingh** [primefaces/primevue#5124]
### Describe the bug

Hi

I'm trying to get `v-badge` and other directives working in the case of unstyled mode. I'm adding pass-through property locally like following,

```
<template>
  <Badge
    v-bind="$attrs"
    :pt="preset"
    :ptOptions="{ mergeSections: false, mergeProps: false }"
  />
</template>

<script setup>
defineOptions({
  inheritAttrs: false,
});

import Badge from 'primevue/badge';

import prime from '@/presets/prime';
const { badge: preset } = prime;
</script>

<style scoped></style>

```

The `v-badge` directive works, but it doesn't get the preset styles. How can I add the preset styles in this case?
Thanks

### Reproducer

-

### PrimeVue version

^3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Install primevue in the vue 3 project
2. Use unstyled mode
3. Create badge component as added in the above example and add badge property. It won't work as required. Also, using v-badge directive doesn't take the classes.

### Expected behavior

There should be a way to add preset classes when not adding preset globally. We can have a guide on the website similar to following `https://tailwind.primevue.org/guides/building-ui-library/` for directives too

**Comment by tugcekucukoglu** [comment]
Hi,

I must say, I am a little confused. Are you using `Badge` component or `v-badge` directive?

Also, local `pt` can be added PrimeVue directives already. For example https://stackblitz.com/edit/4neqrs?file=src%2FApp.vue%3AL7

**Comment by mertsincan** [comment]
Agree with @tugcekucukoglu. We have two badge presets;
1) `badge` key for <Badge> component
2) `directives.badge` key for v-badge directive
https://tailwind.primevue.org/badge/#presets.lara

Another example; https://stackblitz.com/edit/r6zper?file=src%2FApp.vue

**Comment by mbaljeetsingh** [comment]
Hi @tugcekucukoglu  @mertsincan 

Thanks for the reply.

First of all, I'm creating a library on top of Primevue unstyled. I have added an example in the following link for button + badge. I'm assuming, it is using `v-badge` internally. But, how do I make sure `v-badge` gets the styles in the case of a button?

https://stackblitz.com/edit/r6zper-qdf4wj?file=src%2FApp.vue

<img width="1094" alt="image" src="https://github.com/primefaces/primevue/assets/872762/6a3a485c-c0ff-425d-a82a-184600f8dee4">

**Comment by tugcekucukoglu** [comment]
`data-pc-section` will tell which option should be added class in the component used. In this case, `badge` option should be updated. At this point, the preset needs improvement. For example: https://stackblitz.com/edit/r6zper-y39rec?file=src%2Fpresets%2Flara%2Fbutton%2Findex.js%3AL268

This seems to solve the issue. If the problem still persists, please let us know.

**Comment by mbaljeetsingh** [comment]
Hi @tugcekucukoglu 

Thanks for the solution regarding the button. With preset now I have some default styles. In the docs, it says to add the `badgeClass` prop, but I guess the class mentioned is from `primevue.css`. 

`<Button type="button" label="Messages" icon="pi pi-users" badge="8" badgeClass="p-badge-danger" outlined />`

I tried to change the badge class to following `badgeClass="!bg-red-500 !text-white"`. Let me know if you think it is the recommended approach. 

But, somehow I think as the button has `severity` prop, it should adapt accordingly. is it possible with the preset changes?


..........

Another issue I have is with the `v-badge` directive. You mentioned in the previous message, we can add `pt` prop in the v-badge directive, I get it. But, as I'm creating a library on top of primevue. I somehow need to export directive with the default preset applied. Do you think it is possible in the case of `v-badge` and other directives.

Like in the below image, I'm exporting components (badge) with default styles
<img width="1141" alt="image" src="https://github.com/primefaces/primevue/assets/872762/7aa8573e-0b83-4871-a2aa-f8b08569f241">
