### ISSUE TITLE
Dialog issue a11y screen reader.

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5125]
### Describe the bug

Hi, NVDA screen reader reads the header and description twice when I have closable=true

### Reproducer

https://codesandbox.io/p/devbox/lucid-swanson-t2dq56?file=%2Fsrc%2FApp.vue%3A26%2C55

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

Chrome / Edge / Firefox

### Expected behavior

The screen reader read once the tittle and description

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll check it before the milestone is released.

Best Regards,

**Comment by tugcekucukoglu** [comment]
We followed a path as documented [here](https://primevue.org/dialog/#accessibility). Each screenreader may behave differently. Therefore, if there is a role or attribute you want to change, you can use the `pt` property.
