### ISSUE TITLE
Dropdown: Expected $primevue.config.zIndex is undefined when Vue rendered as a custom element

### ISSUE THREAD

**Issue by jakubferenc** [primefaces/primevue#5126]
### Describe the bug

The PrimeVue at the line `ZIndexUtils.set('overlay', el, this.$primevue.config.zIndex.overlay);` expects that Vue's `globalProperties` with the `$primevue` extension are automatically injected to all Vue components. 

However, when rendering a Vue component as a web component with `defineCustomElement()`, the global `globalProperties` object is not present, because we don't initialise the `app` and don't plug-in the PrimeVue via `app.use()`.

### Reproducer

https://codesandbox.io/p/sandbox/restless-sea-3sysrw

### PrimeVue version

3.4.5

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a custom element with `defineCustomElement()`
2. Render it in the html
3. Add <Dropdown /> component with the needed props
4. Observe the error in console regarding `config` being undefined

### Expected behavior

Dropdown is rendered without errors, the Dropdown component doesn't rely on Vue's `globalProperties` as any Vue component should be able to be rendered as a custom element/web component.

**Comment by mertsincan** [comment]
Hi,

Primevue plugin is required; https://primevue.org/vite/#plugin
Maybe, the following link can help to you to register PrimeVue plugin;
https://rimdev.io/vue-3-custom-elements

Best Reagrds,
