### ISSUE TITLE
Textarea: modelValue should accept Nullable<string> as InputText does

### ISSUE THREAD

**Issue by Peanut4287** [primefaces/primevue#5127]
### Describe the bug

Textarea does not allow a `null` modelValue, InputText does. Shouldn't both accept the same?
![pic](https://github.com/primefaces/primevue/assets/157473901/e94d9d01-3bc3-4bc1-93fb-3c191049ec01)

### Reproducer

https://codesandbox.io/p/devbox/blissful-chatelet-cc5mk3?file=%2Fsrc%2FApp.vue%3A13%2C1

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone. I'll check it before the milestone is released.
