### ISSUE TITLE
Calendar: 'view' property has no effect when changed after component initialization

### ISSUE THREAD

**Issue by ponix-net** [primefaces/primevue#5132]
### Describe the bug

When I bind some dynamic variable to `view` property it has no effect after value change.
Should change view mode.

### Reproducer

https://codesandbox.io/p/sandbox/divine-tree-yrhm8g

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the report! I set a milestone for it. We'll check it before the milestone is released.

Best Regards,

**Comment by tugcekucukoglu** [comment]
I cannot open the codesandbox, could you share it again with stackblitz link?

**Comment by ponix-net** [comment]
> I cannot open the codesandbox, could you share it again with stackblitz link?

Sure. [StackBlitz](https://stackblitz.com/edit/qiebjd?file=src%2FApp.vue)
