### ISSUE TITLE
Toast: Not showing using CDN

### ISSUE THREAD

**Issue by Kingside88** [primefaces/primevue#5133]
### Describe the bug

Hi, first I want to say PrimeVue is by far the best UI Framework.
Unfortunatly the toast component is not working.

### Reproducer

https://codesandbox.io/p/sandbox/primevue-toast-error-z67lwt?file=%2Findex.html%3A204%2C1

### PrimeVue version

3.33.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Browser(s)

Edge, Chrome

### Steps to reproduce the behavior

1. configure app: `app
                .use(primevue.config.default)
                .use(primevue.toastservice)                
                .directive('ripple', primevue.ripple)
                .directive('toast', primevue.toast)

                .component('p-button', primevue.button)
                .component('p-toast', primevue.toast)
                ;`

2.
`// Nothing happens
this.$toast.add({ severity: 'info', summary: 'Info', detail: 'Message Content', life: 3000 });`
or 
```
const { useToast } = primevue.usetoast;
// Error: "No PrimeVue Toast provided!"
let toast = useToast();
```
3. Updating to a version greater 3.40.0 leads to Error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'extend')
    at basecomponent.min.js:1:8008
    at basecomponent.min.js:1:16871
```

### Expected behavior

Toast should showing up

**Comment by mertsincan** [comment]
Thanks a lot! I'll check and get back to you.

**Comment by mertsincan** [comment]
Hi,

Please try;
https://codesandbox.io/p/sandbox/primevue-toast-error-forked-qljcgh?file=%2Findex.html%3A51%2C1
There are common components in core.js. But when you import them again, this error occurs;
https://github.com/primefaces/primevue/blob/master/rollup.config.js#L174

Best Regards,

**Comment by Kingside88** [comment]
Thank you so much!
Now it works with the newest version 3.46.0.
I want to share what some other issues with the newest version:

1. Adding this script will let toast working without any error. `<script src="https://cdnjs.cloudflare.com/ajax/libs/primevue/3.46.0/toasteventbus/toasteventbus.min.js"></script> `
2. The basecomponent script let primeVue show up an error in the console and primeVue is not working at all: `<script src="https://cdnjs.cloudflare.com/ajax/libs/primevue/3.46.0/basecomponent/basecomponent.min.js"></script>`
3. Adding the Button script will let the button looks like non-styled button: `<script src="https://cdnjs.cloudflare.com/ajax/libs/primevue/3.46.0/button/button.min.js"></script> `
4. the scripts for toast.min.js and toastservice.min.js must be added directly to the top, but below core.min.js.
