### ISSUE TITLE
Theme problem

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5137]
### Describe the bug

Hello, i use this theme:
primevue/resources/themes/bootstrap4-light-blue/theme.css

I want change the primary-color but the components not use the CSS var
Example:
.p-tag {
    background: #007bff;
    color: #ffffff;
    font-size: 0.75rem;
    font-weight: 700;
    padding: 0.25rem 0.4rem;
    border-radius: 4px;
}

It should be this? :

.p-tag {
    background: var(--primary-color);
    color: #ffffff;
    font-size: 0.75rem;
    font-weight: 700;
    padding: 0.25rem 0.4rem;
    border-radius: 4px;
}

### Reproducer

.

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your feedback! We're working on New Theme structure. This can be help to you to customize everything using css variables. Please see our roadmap;
https://www.youtube.com/watch?v=VTSp9NRc6qE

Best Regards,
