### ISSUE TITLE
Overlay Panel: Header doesn't show

### ISSUE THREAD

**Issue by quantumwebco** [primefaces/primevue#5148]
### Describe the bug

When implementing the confirm popup with the header option, the header doesn't show
```
confirm.require({
    target: event.currentTarget,
    header: "Delete Class",
    message: "Are you sure?",
    icon: "pi pi-exclamation-triangle",
    accept: () => {
        router.delete(route("admin.classes.destroy", 1));
    },
});
```

![image](https://github.com/primefaces/primevue/assets/12368817/0f72d516-8da6-42da-86ee-074bfbf4aaee)

### Reproducer

https://codesandbox.io/p/devbox/fervent-kilby-xw9jqf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrszdzqc00073j6exqrwo9vd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrszdzqc00023j6eztuf8d19%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrszdzqc00043j6exaalezol%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrszdzqc00063j6ebmrtse45%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrszfzp6001o3j6ennz5f0wd%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrszdzqc00023j6eztuf8d19%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00013j6eg1tl4d14%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrszfid000473j6e99p5914c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A58%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A58%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00023j6eztuf8d19%2522%252C%2522activeTabId%2522%253A%2522clrszfid000473j6e99p5914c%2522%257D%252C%2522clrszdzqc00063j6ebmrtse45%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00053j6e60dh8ofq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00063j6ebmrtse45%2522%252C%2522activeTabId%2522%253A%2522clrszdzqc00053j6e60dh8ofq%2522%257D%252C%2522clrszdzqc00043j6exaalezol%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00033j6e1nay1kny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00043j6exaalezol%2522%252C%2522activeTabId%2522%253A%2522clrszdzqc00033j6e1nay1kny%2522%257D%252C%2522clrszfzp6001o3j6ennz5f0wd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszfzl9001i3j6en0ba75dh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrszfzp6001o3j6ennz5f0wd%2522%252C%2522activeTabId%2522%253A%2522clrszfzl9001i3j6en0ba75dh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chromium

### Steps to reproduce the behavior

Add a confirm popup, set the header option, it doesn;t show.

https://primevue.org/confirmpopup/#api.options.ConfirmationOptions.header

### Expected behavior

There is some header text showing

**Comment by mertsincan** [comment]
Hi @quantumwebco,

ConfirmPopup and ConfirmDialog use same ConfirmOptions API but ConfirmPopup doesn't use `header` option. It is for ConfirmDialog. You can use `container` slot to customize according to your needs.

Best Regards,

**Comment by Anubarak** [comment]
Shouldn't the docs at least be changed?
I guess removing not working examples would be nice in that case
