### ISSUE TITLE
TabView - Hidden Scroll Buttons

### ISSUE THREAD

**Issue by iampapagray** [primefaces/primevue#5149]
When using the TabView in a dynamic way (where the number of tabs can change) the scroll icons are not displayed until you click on the last tab header. 

Checkout this fork to understand the issue better:
https://codesandbox.io/p/devbox/primevue-demo-forked-q8l4sx

Steps:
1. create TabView with fewer tabs than viewport width
2. Dynamically increase tabs to need scroll icons/buttons

Expected:
Once the number of tabs increase, scroll icons/buttons should appear immediately

Actual:
Until you click on last tab, scroll icons/buttons are not shown

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll fix before the milestone is released.

**Comment by tugcekucukoglu** [comment]
Could you try to use v3.48.1? This issue might be fixed with [#5111 ](https://github.com/primefaces/primevue/issues/5111)

**Comment by iampapagray** [comment]
@tugcekucukoglu I just tested with v3.48.1.
It works as expected now... Thank you
