### ISSUE TITLE
Multiselect: example does not work when used as CDN

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [primefaces/primevue#5151]
### Describe the bug

Grouped multiselect children does not render as expected
<img width="985" alt="Screenshot 2024-01-25 at 11 04 18" src="https://github.com/primefaces/primevue/assets/29608698/9baefd07-1353-4e6b-9008-c9a8945dc7cb">

### Reproducer

https://codepen.io/maxorhd/pen/BabwGMo?editors=1111

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Interesting! I'll check and get back to you.

**Comment by mertsincan** [comment]
Hi @diego-lipinski-de-castro,

I reviewed your sample. You need to use kebab-case instead of camel-case for attributes in HTML structures. Please try;
```
<div id="app">
	<MultiSelect 
                    v-model="selectedCities"
                    :options="groupedCities" 
                    option-label="label"
                    option-group-label="label" 
                    option-group-children="items"
                    display="chip"
                    placeholder="Select Cities"
                    class="w-full md:w-20rem">
                                <template #optiongroup="slotProps">
                                    <div class="flex align-items-center">
                                        <div>{{ slotProps.option.label }}</div>
                                    </div>
                                </template>
         </MultiSelect>
</div>
```
