### ISSUE TITLE
DataTable: Selection Highlight not Working

### ISSUE THREAD

**Issue by tmorgan497** [primefaces/primevue#5152]
### Describe the bug

On the latest version of PrimeVue (3.47+), the row selection highlighting of DataTables is not working. I tested by downgrading to 3.46.0 which does work as expected. Tested using 'single' and 'multiple' selection modes.

### Reproducer

https://codesandbox.io/p/devbox/green-fire-rn6hyv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrtex5u200072a6ci5abj831%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrtex5u200022a6cxn2va3hf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrtex5u200042a6cgnb2jd58%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrtex5u200062a6c5rjl0kb4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrtex5u200022a6cxn2va3hf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtex5u200012a6c5mz1camx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrtex5u200022a6cxn2va3hf%2522%252C%2522activeTabId%2522%253A%2522clrtex5u200012a6c5mz1camx%2522%257D%252C%2522clrtex5u200062a6c5rjl0kb4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtex5u200052a6cnbjfslrg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrtex5u200062a6c5rjl0kb4%2522%252C%2522activeTabId%2522%253A%2522clrtex5u200052a6cnbjfslrg%2522%257D%252C%2522clrtex5u200042a6cgnb2jd58%2522%253A%257B%2522id%2522%253A%2522clrtex5u200042a6cgnb2jd58%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtex5u200032a6c8spbg40w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clrtf9iop00k12a6b8r0zxjyq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrtf9i950040efgb30xy8l57%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtex5u200032a6c8spbg40w%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Edge 120, Firefox 121

### Steps to reproduce the behavior

1. Create DataTable with sample data
2. Set selection mode to 'single' or 'multiple'
3. Select rows

### Expected behavior

Expect the selected rows to highlight with the given theme. Using unstyled: false

**Comment by tugcekucukoglu** [comment]
With version 3.47.0 we made some changes in theme design. Selections with checkboxes will no longer highlight the selected line. But you can style it as you want using `pt` property. So closing the issue.

Thanks,
