### ISSUE TITLE
Tooltip: OutOfBounds alignment does not affect tooltip arrow position

### ISSUE THREAD

**Issue by Billiam** [primefaces/primevue#5153]
### Describe the bug

When a tooltip needs to be repositioned due to it's out OutOfBounds check, the tooltip arrow's direction is updated, but it will still be positioned at the original location.

![tooltip arrow positioned incorrectly](https://github.com/primefaces/primevue/assets/242008/37ca5798-31d5-49bc-a2bd-56ec708bd0b7)

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-38skqh?file=/src/App.vue

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

1. Visit https://codesandbox.io/s/primevue-demo-forked-38skqh?file=/src/App.vue, which contains two top-positioned tooltips, but without enough space to display the first one above the input.
2. Hover over top input
3. Observe that tooltip appears below input (desirable)
4. Observe that tooltip arrow appears points upwards (desirable)
5. Observe that tooltip arrow appears below the tooltip (bug)

1. Hover over bottom input, which has enough room to display tooltip
2. Observe tooltip appears above input, with arrow pointing down correctly

### Expected behavior

When tooltip has to be repositioned due to out of bounds check, arrow appears on correct side of tooltip.

**Comment by mertsincan** [comment]
Oops! Thanks a lot for your report! I set a milestone for it. We'll check it before the milestone is released.
