### ISSUE TITLE
Themes: end value has mixed support, consider using flex-end instead warning

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#5155]
### Describe the bug

When I run npm run dev (where dev is just the command `vite`), I get the following warning on my VsCode terminal:

```
[vite:css] end value has mixed support, consider using flex-end instead
3931|      padding: 0 1.5rem 1.5rem 1.5rem;
3932|      display: flex;
3933|      justify-content: end;
   |      ^^^^^^^^^^^^^^^^^^^^^
3934|      gap: 0.5rem;
3935|      border-bottom-right-radius: 6px;
```

The warning comes from the lara-light-teal theme.css file (because that is the theme I use), but this is present in all theme css files.

### Reproducer

-

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Interesting! I didn't understand it. The `justify-content` supports `end` value; https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

**Comment by Rasool-deldar** [comment]
Same issue

 WARN  [vite:css] end value has mixed support, consider using flex-end instead                                                                                                                                           11:30:09 PM  
3958|      padding: 0 1.5rem 1.5rem 1.5rem;
3959|      display: flex;
3960|      justify-content: end;
   |      ^^^^^^^^^^^^^^^^^^^^^
3961|      gap: 0.5rem;
3962|      border-bottom-right-radius: 6px; (x2)

**Comment by rizen** [comment]
Same issue:

 WARN  [vite:css] end value has mixed support, consider using flex-end instead                                 3:54:56 PM
3923|      padding: 0 1.5rem 1.5rem 1.5rem;
3924|      display: flex;
3925|      justify-content: end;
   |      ^^^^^^^^^^^^^^^^^^^^^
3926|      gap: 0.5rem;
3927|      border-bottom-right-radius: 0.375rem; (x3)


If I change `justify-content: end;` to `justify-content: flex-end;` the error goes away
