### ISSUE TITLE
Font Download: Failed to decode downloaded font in version 3.46.0

### ISSUE THREAD

**Issue by akanksha058** [primefaces/primevue#5157]
### Describe the bug

Upgrading primevue to version 3.46.0 and using the theme `lara-light-blue`  causes the issue 
```
Failed to decode downloaded font: http://127.0.0.1:5173/fonts/Inter-roman.var.woff2?v=3.19
OTS parsing error: invalid sfntVersion: 1008813135
```

Although this is just a console error similar to https://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font

### Reproducer

NA

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 

### Steps to reproduce the behavior

Use any component with the mentioned theme

### Expected behavior

No console error

**Comment by gmlewis** [comment]
Thank you, @akanksha058 for filing this issue.  Here is an interesting data point... 
If I search for that file in our project, I see it exists here:

```
$ find . -name Inter-roman.var.woff2
./node_modules/.pnpm/primevue@3.46.0_vue@3.3.11/node_modules/primevue/resources/themes/lara-light-blue/fonts/Inter-roman.var.woff2
```

It's almost as if the `pnpm install` command didn't create the softlink to its correct final destination.

I'm wondering if a temporary workaround might be to copy this file to our project directly and place it in the location:
`dist/assets/fonts/Inter-roman.var.woff2` ?

**Comment by gmlewis** [comment]
This looks very interesting: https://github.com/PrestaShop/PrestaShop/issues/29559#issuecomment-1537939085
and indeed, this is the exact problem in our case.  
You can probably close this ticket while we see why HTML is being returned.

**Comment by mertsincan** [comment]
@gmlewis Thanks a lot for your help! So, closed now.

**Comment by ayophanz** [comment]
I had same problem with primevue icons, btw I already added this` import "primeicons/primeicons.css";`

![image](https://github.com/primefaces/primevue/assets/24581584/6dc73118-9e9a-4855-aa05-c1a1caeec8bc)

**Comment by Shukla1001** [comment]
``
