### ISSUE TITLE
TabView : Scrollable tabs breaks after particular met conditions

### ISSUE THREAD

**Issue by Horos34** [primefaces/primevue#5158]
### Describe the bug

**Context :**

I'm using the TabView component with dynamic scrollable props and TabPanel.
My tabs can be set as "deleted" because i don't want to trigger reactivity for another reason (i'm not allowed to tell).
So at first, when opening tabs i want to check if my tab list length is higher than 2. If it does i set my scrollable prop to true otherwise it's false.

**The issue :**

When i open a lot of tabs, TabView activates arrow buttons which slide the content of the tab list. When clicking on this button and arriving at the end of the list, if i delete 80% of my tabs, the moment my "2 paged" slider become a "1 paged" slider, the arrow button disappear and i can't slide again. 

If i want to have the slider again, i need to have enough tabs that it goes out of the screen and click on the last tab seen on screen, or reload the page (i don't want this option).

### Reproducer

https://codesandbox.io/p/sandbox/primevue-tabview-issue-forked-qhvwdt

### PrimeVue version

3.47.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Edge, Chrome

### Steps to reproduce the behavior

1. Click Add Tab button minimum 20 times
2. Click right arrow 
3. Click on multiple tab cross until you have no arrows 

**Behavior 2 : (not a wanted behavior)**

1. Click Add Tab button minimum 20 times
2. Click right arrow 
3. Click on multiple tab cross until you have no arrows 
4. Click Add Tab button again until you can't see the new ones
5. Click on the last tab you can see  

**Behavior 3 : (not a wanted behavior)**

1. Click Add Tab button minimum 20 times
2. Click right arrow
3. reload page
4. delete tabs 
5. (Normal TabView behavior)

### Expected behavior

As the TabView component deals with the tabs, it should activate the animation that takes us back to the "first page" of the tab navs and put the scroll props to false when length of tab list is below 2. But when reopening tabs, the scrollable props should come back to true when tab list length is more than 2.

Just the normal behavior of the TabView component.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll check it before the milestone is released. As far as I remember, we solved this kind of problem in PrimeNg.

**Comment by tugcekucukoglu** [comment]
Cannot open the codesandbox link. Could you share a stackblitz link?

**Comment by Horos34** [comment]
Hello, sorry for the late answer, is this link better ? 
https://codesandbox.io/p/sandbox/primevue-tabview-issue-forked-qhvwdt?file=%2Fsrc%2Fstore%2Findex.js

**Comment by Horos34** [comment]
Hello, sorry for the late answer. The link bellow should work now. 
https://codesandbox.io/p/sandbox/primevue-tabview-issue-forked-qhvwdt?file=%2Fsrc%2Fstore%2Findex.js

**Comment by tugcekucukoglu** [comment]
Still same.

![Screenshot 2024-03-19 at 11 31 15](https://github.com/primefaces/primevue/assets/32294991/3c9b735d-c941-4287-b23e-f7bda9c82a40)

**Comment by tugcekucukoglu** [comment]
Could you try to use the latest version? Issue might be related with this [issue](https://github.com/primefaces/primevue/issues/5111)

**Comment by Horos34** [comment]
yes it's kinda the same issue, but by upgrading the primevue to the latest version and it got fixed

**Comment by tugcekucukoglu** [comment]
Thanks for the update!
