### ISSUE TITLE
Chips not recognise w-full on class or inputClass

### ISSUE THREAD

**Issue by MEngMAHCelebi** [primefaces/primevue#5163]
### Describe the bug

Chips don't recognise w-full.

reproduce e.g.:
<template>
  <DynamicDialog />
  <div class="grid">
    <div class="col-12">
      <Chips v-model="value" class="w-full" inputClass="w-full" />
    </div>
    <div class="col-12">
      <inputText class="w-full" />
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const value = ref();
</script>

### Reproducer

https://codesandbox.io/s/primevue-demo-forked-9hr3w6

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Hi,

You can use pt prop with `container` selector;
```
<Chips v-model="value" :pt="{ container: 'w-full'}" />
```

Best Regards,

**Comment by MEngMAHCelebi** [comment]
i use it also with prop as workarround, just want to inform you. But thank you.

**Comment by MEngMAHCelebi** [comment]
Because you have in api inputClass, but not work as expected.
