### ISSUE TITLE
InputMask: Cursor bug on Android devices when having a mask like (000)

### ISSUE THREAD

**Issue by keremozben** [primefaces/primevue#5164]
### Describe the bug

On Android devices, when having a mask for phone numbers like this (999) 999 99 99, if you try to delete the value and if the cursor moves to the left of the first paranthesis, entering a new value becomes problematic because cursor moves irraticly.

### Reproducer

can-not-fork-due-to-error

### PrimeVue version

3.47

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use an Android mobile device

Set a mask like (999) 999 99 99
Enter a value
Delete it by pressing delete key, cursor moves to the left of the first paranthesis.
Try to enter new value such as 535 000 00 00
The value inside the paranthesis should be 535, but becomes 355 due to cursor position

### Expected behavior

Entered value should be correct

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll check it before the milestone is released.

**Comment by tugcekucukoglu** [comment]
We cannot replicate the problem. How can we reproduce the issue?

**Comment by keremozben** [comment]
@tugcekucukoglu Sorry for late response, here is how you can reproduce the issue.

Use an Android mobile device please.

Set a mask like (999) 999 99 99
Enter a value
Delete it by pressing delete key, when the cursor is on the left side of the first paranthesis, try to enter another value like 535 inside the paranthesis. The value should be 535, but it became 355. The cursor shifts the numbers to the right somehow.

Here is an example video. https://github.com/primefaces/primevue/assets/1444098/a80d4e72-348e-4869-a89b-1f34c90fba8d

**Comment by keremozben** [comment]
@tugcekucukoglu Do you need any other info for this one ? Can you give an estimation for fix date ?

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. Please send  a repo or stackblitz demo.
