### ISSUE TITLE
Checkbox: Input field no longer hidden

### ISSUE THREAD

**Issue by dahjson** [primefaces/primevue#5172]
### Describe the bug

The containing div `<div class="p-hidden-accessible" v-bind="ptm('hiddenInputWrapper')" :data-p-hidden-accessible="true">` around the input field was removed, and the input field is no longer hidden for the checkbox.

https://github.com/primefaces/primevue/commit/99b1edd5cedddbd12d72b24fcd240abe18b308b5#diff-3f9994e923862cdf274c4681cec5f730bd4dc420e932b39359400c959e8479fa

### Reproducer

https://github.com/primefaces/primevue/commit/99b1edd5cedddbd12d72b24fcd240abe18b308b5#diff-3f9994e923862cdf274c4681cec5f730bd4dc420e932b39359400c959e8479fa

### PrimeVue version

3.47.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by rubjo** [comment]
Seeing the same, this is unfortunate. @mertsincan Would you happen to know which version to revert to when seeing this?

**Comment by mertsincan** [comment]
Hi,

We made improvements to accessibility in the last release. This change was truly necessary. Now the checkbox and radiobutton components are in a better state. Please see our changes; https://github.com/primefaces/primevue/issues/5071

Also, we'll update all layouts asap. For now, you can update layout's theme-base folder from https://github.com/primefaces/primevue-sass-theme/releases/tag/3.47.2

Best Regards,

**Comment by dahjson** [comment]
Updating the theme fixed the issue. Thanks for the quick response on this!
