### ISSUE TITLE
Upgrade Apollo theme to primevue 3.47.2

### ISSUE THREAD

**Issue by lpalacecr** [primefaces/primevue#5173]
### Describe the bug

Upgrade version of primevue 3.38 to 3.47.2, the theme failed.
I bought the Apollo theme version 5.0, I made a new project and when I updated the version of Primevue from 3.38 to 3.47.2 the inputSwitch stopped working, the checkbox, multiselect and radioButton display a circle when an option is marked.

I have seen that several bugs have been fixed from version 3.38 to 3.47.2, so I would like to be able to update the version of the apollo theme.

I attach a word document with several errors found so far.

In this discussion [https://github.com/orgs/primefaces/discussions/1023#discussion-6133370](url) you can see that it is not only the Apollo theme, everything seems to indicate that the other themes also fail.

Is it possible to update the Primevue version of a theme or do I have to stay with the version I have?

I appreciate the help you can give me.

Translated by Google Translate.

Original text:
Yo compré el tema apollo versión 5.0, hice un nuevo proyecto y cuando le actualicé la versión de primevue de la 3.38 a la 3.47.2 el inputSwitch dejó de funcionar, los checkbox, multiselect y lo radioButton desliegan un círculo caundo se marca una opción.

He visto que de la versión 3.38 a la 3.47.2 se han corregido varios errores por lo que me gustaría poder actualizar la versión del tema apollo.

Adjunto documento en word con varios errores hasta ahora encontrados.

En esta discusión https://github.com/orgs/primefaces/discussions/1023#discussion-6133370, se puede apreciar que no solamente es el tema Apollo, todo parace indicar que los otros temas también fallan.

Es posible actualizar la versión de primevue de un tema o me tengo que quedar con la versión que tengo?

Agradezco la ayuda que me puedan brindar.

[Upgrade Apollo theme.docx](https://github.com/primefaces/primevue/files/14087170/Upgrade.Apollo.theme.docx)

### Reproducer

https://codesandbox.io/p/devbox/blazing-river-5cvr6n?file=%2Fpackage.json%3A8%2C30

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Any browser

### Steps to reproduce the behavior

1. In Apollo menu, go to UI KIT/input page. Any component wiht checkbox fail.
2. In Apollo menu, go to APPS/List. The application fail. This error occurs in version 3.46 too
3. In Apollo menu, go to APPS/Bloq/List. The application fail. This error occurs in version 3.46 too

Please see the attached document.

### Expected behavior

The normal behavior of the component

**Comment by mertsincan** [comment]
Hi,

We made improvements to accessibility in the last release. This change was truly necessary. Now the checkbox and radiobutton components are in a better state. Please see our changes; https://github.com/primefaces/primevue/issues/5071

We'll update all layouts asap. For now, you can update Apollo's theme-base folder from https://github.com/primefaces/primevue-sass-theme/releases/tag/3.47.2

Best Regards,

**Comment by lpalacecr** [comment]
Hi,
I already copied the theme-base folder to \apollo-vue-5.0.0\apollo-vue-5.0.0\apollo-vite\public\layout\styles\theme, however the problems persist. Apart from copying the folder, you should do something else. If it's not too much trouble, could you give me a little guide.

Thank you so much...

Translated by Google Translate.

Original text:
Ya copie la carpeta theme-base en \apollo-vue-5.0.0\apollo-vue-5.0.0\apollo-vite\public\layout\styles\theme, sin embargo, los problemas persisten. A parte de copiar la carpeta debería hacer algo más. Sino es mucha la molestia, me podría dar una pequeña guía.

Muchas gracias...
