### ISSUE TITLE
RadioButton | Checkbox | InputSwitch: Style disorder 3.47.2

### ISSUE THREAD

**Issue by lindongchen** [primefaces/primevue#5174]
### Describe the bug

1.RadioButton | Checkbox Style disorder: it look like lost the style sheet about “.p-radiobutton .p-radiobutton-input，.p-radiobutton.p-highlight .p-radiobutton-input”, but I think the functionality is available.
2.InputSwitch: Same question 1, but Its value cannot be emit changed

- The above issues were encountered during the upgrade to 3.47.2, and before they are available in 3.3x
- In chrome broswer latesd

### Reproducer

-

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

-

### Expected behavior

-

**Comment by mertsincan** [comment]
Hi,

We made improvements to accessibility in the last release. This change was truly necessary. Now the checkbox and radiobutton components are in a better state. Please see our changes; https://github.com/primefaces/primevue/issues/5071
