### ISSUE TITLE
New `invalid` and `variant` properties

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#5176]
- [x] invalid: "false" | "true"
- [ ] variant: "outline" | "filled"

Components;

- [ ] AutoComplete
- [ ] Calendar
- [ ] CascadeSelect
- [ ] Checkbox
- [ ] Chips
- [ ] Dropdown
- [ ] InputMask
- [ ] InputNumber
- [ ] InputSwitch
- [ ] InputText
- [ ] Listbox
- [ ] MultiSelect
- [ ] Password
- [ ] RadioButton
- [ ] SelectButton
- [ ] Textarea
- [ ] ToggleButton
- [ ] TreeSelect
- [ ] TriStateCheckbox

**Comment by SamuelWei** [comment]
@tugcekucukoglu What about adding [aria-invalid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid) attribute if the new prop invalid is true ? This would save writing a lot of code.

**Comment by tugcekucukoglu** [comment]
Thanks for your interest! I can add it to the next version.
