### ISSUE TITLE
Button + link + disabled

### ISSUE THREAD

**Issue by MathiasHandle** [primefaces/primevue#5180]
Hello guys I have a question. What is correct usage of disabled Button + RouterLink ?

If I wrap `Button` with `RouterLink`, the link is still active (clickable) even when the `Button` has disabled prop set to true.

That's due to the RouterLink wrapping Button component. So css rule `pointer-events` is applied only to rendered `<button>` element and not parent `<a>` element.
```vue
<RouterLink :to="{ name: 'Checkout' }">
  <Button
    rounded
    link
    :disabled="!isAllowedNavigation"
    severity="primary"
    label="Navigate somewhere">
  </Button>
</RouterLink>
```

If I do it the opposite way, the link is disabled (not clickable) as it's inside rendered `<button>` element, however I loose all the styling, due to `RouterLink` being passed-in as default slot, thus overwriting label prop.
```vue
<Button
  rounded
  link
  :disabled="!isAllowedNavigation"
  severity="primary"
  label="Button label">
  <RouterLink :to="{ name: 'Checkout' }">Navigate somewhere</RouterLink>
</Button>
```

**Comment by MathiasHandle** [comment]
I've solved it by calling a router function

```vue
<script setup>
import {useRouter} from 'vue-router'

const router = useRouter()
</script>

<template>
  <Button
    rounded
    link
    :disabled="!isAllowedNavigation"
    severity="primary"
    label="Navigate somewhere"
    @click="router.push({ name: 'Checkout' })"
  />
</template>
```

However the rendered html is `button` element. It would be nice if `Button` would take a prop `entity` and render as a passed in html element. Or some other solution that would let you change rendered html

**Comment by mertsincan** [comment]
> If I wrap Button with RouterLink, the link is still active (clickable) even when the Button has disabled prop set to true.
This is expected behaviour. You need to add `pointer-events: none` to RouterLink when it is disabled.

Best Regards,
