### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by quantumwebco** [primefaces/primevue#5181]
### Describe the bug

When having a datepicker/Calendar component in a datatable filter, where ```filter-display="menu"``` and ```:show-filter-match-modes="false"``` if there is just 1 calendar the filed gets focussed but the datepicker is not attached to the field, it attaches to the body and displays oddly. If there are 2 datepickers showing the second field is fine or the filter has macth modes showing both are fine, so I assume it is something to do with initial focus happening before the Calendar component has mounted

I tried using the ```append-to``` attribute, which makes the calendar show but kind of inline rather than outside of the filter popup

![image](https://github.com/primefaces/primevue/assets/12368817/3196d5c3-b5a9-48e1-9b9a-56f0047cf90f)
![image](https://github.com/primefaces/primevue/assets/12368817/f17a9c1c-a28d-41cc-ba4d-2d448c5fa816)
![image](https://github.com/primefaces/primevue/assets/12368817/89545d44-9d34-41ba-9d7a-29e9915995e4)

### Reproducer

https://codesandbox.io/p/devbox/lucid-swanson-hxywx3?workspaceId=0d27d726-9811-4946-a4d7-0e63d34b384b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrszdzqc00073j6exqrwo9vd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrszdzqc00023j6eztuf8d19%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrszdzqc00043j6exaalezol%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrszdzqc00063j6ebmrtse45%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrszdzqc00023j6eztuf8d19%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00013j6eg1tl4d14%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrszfid000473j6e99p5914c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A58%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A58%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00023j6eztuf8d19%2522%252C%2522activeTabId%2522%253A%2522clrszfid000473j6e99p5914c%2522%257D%252C%2522clrszdzqc00063j6ebmrtse45%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00053j6e60dh8ofq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00063j6ebmrtse45%2522%252C%2522activeTabId%2522%253A%2522clrszdzqc00053j6e60dh8ofq%2522%257D%252C%2522clrszdzqc00043j6exaalezol%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00033j6e1nay1kny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00043j6exaalezol%2522%252C%2522activeTabId%2522%253A%2522clrszdzqc00033j6e1nay1kny%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chromium based, firefox etc.

### Steps to reproduce the behavior

Create a table with  menu filters, hide match modes, add datepicker

### Expected behavior

Datepicker shows like 
![image](https://github.com/primefaces/primevue/assets/12368817/4321007c-45ec-42f2-8878-26c7c3a0dbb4)

**Comment by mertsincan** [comment]
Hi,

Please try the latest version. I think this issue has already been fixed in 3.47.x.

Best Regards,

**Comment by quantumwebco** [comment]
Oops sorry, thanks!
