### ISSUE TITLE
DataTable: rowsPerPageOptions only accepts number

### ISSUE THREAD

**Issue by quantumwebco** [primefaces/primevue#5183]
### Describe the bug

Want to add an "All" option to the rowsPerPage but the type is ```number[]```

### Reproducer

https://codesandbox.io/p/devbox/lucid-swanson-hxywx3?workspaceId=0d27d726-9811-4946-a4d7-0e63d34b384b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrszdzqc00073j6exqrwo9vd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrszdzqc00023j6eztuf8d19%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrszdzqc00043j6exaalezol%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrszdzqc00063j6ebmrtse45%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrszdzqc00023j6eztuf8d19%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00013j6eg1tl4d14%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrszfid000473j6e99p5914c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A58%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A58%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00023j6eztuf8d19%2522%252C%2522activeTabId%2522%253A%2522clrszfid000473j6e99p5914c%2522%257D%252C%2522clrszdzqc00063j6ebmrtse45%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00053j6e60dh8ofq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00063j6ebmrtse45%2522%252C%2522activeTabId%2522%253A%2522clrszdzqc00053j6e60dh8ofq%2522%257D%252C%2522clrszdzqc00043j6exaalezol%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrszdzqc00033j6e1nay1kny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrszdzqc00043j6exaalezol%2522%252C%2522activeTabId%2522%253A%2522clrszdzqc00033j6e1nay1kny%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Add an "All" option to rowsPerPageOptions

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your feature request! Could you please create a discussion ticket for it? We can expect upvotes from other users about this. We will be happy to implement this when there are enough upvotes. Thanks a lot for your understanding!

**Comment by averinbox** [comment]
UP!

**Comment by Kreyco** [comment]
I added the Feature request if it's helpful for you! 😄 
[DataTable: rowsPerPageOptions only accepts number #3805](https://github.com/orgs/primefaces/discussions/3805)

**Comment by quantumwebco** [comment]
What I have done as a workaround is look at the ```totalRecords``` prop and use that as one of the values in the ```rowsPerPageOptions``` something like ```:rowsPerPageOptions="[5, 10, 20, 50, data.meta?.total > 50 ? data.meta.total : 100]"```
