### ISSUE TITLE
Toast: persistent toast

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5191]
### Describe the bug

Can you make a persistent toast even if you change pages using vue-router?

### Reproducer

.

### PrimeVue version

3.47.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by antlionguard** [comment]
In my case i create toast for success login but i redirect user to homepage after login and that causes toast not shown.

**Comment by Tamas-hi** [comment]
Toasts are persistent on all pages during navigation, if you omit the `life `option when creating a message.

**Comment by antlionguard** [comment]
> Toasts are persistent on all pages during navigation, if you omit the `life` option when creating a message.

in `3.47.2` thats not true.

**Comment by JoseAntonioNavasSolutia** [comment]
I have tried removing the life option and it does not appear. I want my toast to last 3 seconds

**Comment by mertsincan** [comment]
Interesting! Our live demo works fine for me. Please see;
https://primevue.org/toast/#sticky

Programmatically, you can clear all toast using toast.removeAllGroups(); after 3s

Best Regards,

**Comment by antlionguard** [comment]
> Interesting! Our live demo works fine for me. Please see; https://primevue.org/toast/#sticky
> 
> Programmatically, you can clear all toast using toast.removeAllGroups(); after 3s
> 
> Best Regards,

After `3.48.0` thats works fine. No problem at all on page changes.

**Comment by JoseAntonioNavasSolutia** [comment]
It doesn't work for me.
I do this: 		
toast.add({
  severity: nuevo?.tipo,
  summary: nuevo?.titulo,
  detail: nuevo?.mensaje,
  position: nuevo?.posicion,
  closable: nuevo?.cerrable,
  group: "api"
});

and router.push("/") but the toast is removed

**Comment by omnichronous** [comment]
In my case I wanted to show a toast when navigating from one page to another but I had the `<Toast />` element only in the layout that was used by the first page. The next page used a different layout and `<Toast />` just wasn't in the DOM tree. I moved it out into `app.vue` and that solved my problem.

```vue
<template>
  <div>
    <Toast />
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

The only caveat is that your toasts will still disappear whenever you get sent to the error page.

**Comment by antlionguard** [comment]
in 3.49.1 there's same issue appears if you redirect a page uses different layout.
