### ISSUE TITLE
Dropdown: Editable option causes the menu to not open with option in view when scrolling is present

### ISSUE THREAD

**Issue by dahjson** [primefaces/primevue#5192]
### Describe the bug

If you select an option that requires scrolling, and then closing the menu it doesn't automatically scroll to the selected option when you reopen the menu.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-xrjcor

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by dahjson** [comment]
Looks like there is an autoOptionFocus that is false by default. When I set it to true it fixes the issue. Is this a new option?

**Comment by mertsincan** [comment]
Hi,

This option always existed but the default was true. We made improvements regarding accessibility, and in the accessibility guides, we determined that when an editable element gets focus, it is actually the element in focus, and then when you press the down key, it goes to the selected element. So users who want to use the old behaviour need to set autoOptionFocus="true". 

Best Regards,
