### ISSUE TITLE
DataTable: Row selection styling defect

### ISSUE THREAD

**Issue by NikoGJ** [primefaces/primevue#5196]
### Describe the bug

On Datatable selection, I don't see the row being selected, whatever the theme used. It doesn't appear visually as selected. Was it removed intentionally ?
 

### Reproducer

https://primevue.org/datatable/#single_row_selection

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Brave

**Comment by gleenk** [comment]
I had a similar problem with row selection and Checkboxes too. There's no style.

**Comment by mertsincan** [comment]
Oops! Thanks a lot for your report! This is related to https://github.com/primefaces/primevue/issues/5105. We'll fix asap.
