### ISSUE TITLE
SplitButton templating is broken

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#5199]
The custom content replaced the button instead of getting placed inside a button. Also the main button always renders in icon only mode causing shrinking when using a template.

**Comment by StoffelCPR** [comment]
This seems to have broken my SplitButtons. They're now double in size instead of spanning their div like the button beside it:

![image](https://github.com/primefaces/primevue/assets/32580372/1e356199-9faa-4a99-a735-d72dbacfb740)
