### ISSUE TITLE
Deprecate Legacy Themes

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#5201]
As a prerequisite of the new theming api of V4, deprecate the legacy themes as they won't be available in v4.

- Arya
- Bootstrap (Replacement would be Lara)
- Fluent
- Luna
- Mira
- Nano
- Nova
- Rhea
- Saga
- Tailwind
- Vela
- Viva

**Comment by minzdrav** [comment]
Hi @cagataycivici 
What will happen to the custom theme that we created for our project? We used mytheme as the base for our theme.
How hard it will be to migrate to v4? Will you provide a migration guide?

**Comment by mikekidder** [comment]
@minzdrav - One of the technical lead of PrimeTek is writing a Primeflex to Tailwind migration tool.  

See more discussion on the Discord | Primeland | #primeflex channel -- [Message Link](https://discord.com/channels/787967399105134612/787969521264230410/1199232482042707988)

**Comment by pontsci** [comment]
> Hi @cagataycivici What will happen to the custom theme that we created for our project? We used mytheme as the base for our theme. How hard it will be to migrate to v4? Will you provide a migration guide?

Same here, we used a custom theme and when we go from 3.46 -> 3.47/3.48 our entire theme breaks in our Nuxt project. Hoping we have some way to migrate, otherwise it seems our current project will be stuck on 3.46 for a while.

**Comment by mikebouzidis-aurizon** [comment]
We're having exactly the same issue I don't understand why such a significant breaking change was released as a minor version. 

We're going to be stuck on 3.46 until this migration tool is built and we can migrate

**Comment by n00ge** [comment]
Re-iterating what the others said above. This impacts (breaks) a project I work on as well. Introducing a breaking change like this on a minor version is a huge impact. I'm curious how this affects others decisions to move away from PrimeVue entirely.

**Comment by pontsci** [comment]
Unfortunately, this was a pretty big hit for my company's trust of the library and we have since moved on to a new framework. We need to have up-to-date, stable component frameworks that don't introduce breaking changes into a minor version patch without advance notice. So, unfortunately, after a solid year with Primevue, we have since moved on to a different component library.

**Comment by redfox05** [comment]
@pontsci which framework did you go with, as we've been looking but not able to find anything close to what PrimeVue offers. But the issues raised are concerning, and the developers have not even tried to explain themselves when questioned above, very odd, and not reassuring/professional.

**Comment by davidfenko** [comment]
@cagataycivici do we have any guidance available regarding concerns raised above?
