### ISSUE TITLE
Upload: The code example on the templete section doesn't work. Error messages are not showing.

### ISSUE THREAD

**Issue by anchan42** [primefaces/primevue#5202]
### Describe the bug

1. There is a stray comma at the end of formatSize function. 

2. I also have to change ` const sizes = this.$primevue.config.locale.fileSizeTypes;` to `const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];` to make it work.

3. The error messages are not showing until all the files are removed which is weird. I render the error messages manually as a workaround. Maybe a separate template slot for the error messages would make things more consistent.

[Code example](https://stackblitz.com/edit/1arjxy?file=src%2FApp.vue)

![image](https://github.com/primefaces/primevue/assets/19514416/1ec592d1-7544-4869-b099-f8e4868cbb23)
![image](https://github.com/primefaces/primevue/assets/19514416/046ec888-1390-4a78-baf5-bf5af39ccf32)

### Reproducer

https://stackblitz.com/edit/1arjxy?file=src%2FApp.vue

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

1. Add file number limit or file size limit.
2. Upload files that exceed the limit.
3. Remove the file one by one.

### Expected behavior

The error message should show when the limit is exceeded.

**Comment by tugcekucukoglu** [comment]
If you have added the `fileLimit` prop and will use the content slot, you must also define the error messages yourself in this content slot. For example,

```
<template #content="{ messages }>"
```

Since the `fileLimit` prop is not used in the live demo, it was not added to the demo.

**Comment by anchan42** [comment]
Thanks a lot. I understand now. It just looks strange that the error messages showed up when all the files were removed. It is no big deal though 🙏
