### ISSUE TITLE
DataTable: resizableColumns and paginator bug

### ISSUE THREAD

**Issue by mabangwang** [primefaces/primevue#5210]
### Describe the bug

![image](https://github.com/primefaces/primevue/assets/45955163/abf8f272-7e28-40d5-b583-49d6dc49bfc9)

### Reproducer

https://stackblitz.com/~/edit/favtgn

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

chrome 120.0.6099.225

### Steps to reproduce the behavior

1.when DataTable use [resizableColumns],[paginator :rows="10"],[showGridlines] to define table
![image](https://github.com/primefaces/primevue/assets/45955163/e1b6fe80-3904-42c2-83e0-870ba625acc6)
2.column data is long
 
![image](https://github.com/primefaces/primevue/assets/45955163/2cda9c7e-9675-4335-91fd-f30dad068a85)

3.click paginator
![image](https://github.com/primefaces/primevue/assets/45955163/784c4484-82a2-4cff-90c3-4f7ca235f1c4)

![image](https://github.com/primefaces/primevue/assets/45955163/ddbd4bc0-8d6e-4a86-9863-f1d49a42bf7f)

**Comment by mertsincan** [comment]
Thanks a lot for the report! I set a milestone for it. We'll fix it before the milestone is released.
