### ISSUE TITLE
Slider: [Violation] Non-passive event

### ISSUE THREAD

**Issue by aeruggiero** [primefaces/primevue#5213]
### Describe the bug

Hi all,
the slider component generates the following error:
![image](https://github.com/primefaces/primevue/assets/68345097/148212d9-a59b-46da-84ec-bc3f723ccb7e)

To reproduce, just go to the devtools in this page:
https://primevue.org/slider/#api

(I don't know why, but sometimes it shows, sometimes it doesn't)

Thanks!

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-uqcxp8?file=src%2FApp.vue

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Hi,

To be honest, I really don't know anything about this warning. But, I found; https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

For now, I set a milestone for it. We'll review it before the milestone is released.
