### ISSUE TITLE
v3.48.0 Breaks all Styles in Ultima Theme

### ISSUE THREAD

**Issue by caputech** [primefaces/primevue#5220]
### Describe the bug

After v3.46.0, styles in the Ultima theme are broken. v3.47.0 caused issues with Radio Buttons / Checkboxes mostly, but v3.48.0 seems to have removed or broken all styles. This can be seen easily by simply running the latest version of the Ultima theme (5.2.0)

### Reproducer

https://www.primefaces.org/store/templates.xhtml

### PrimeVue version

3.48.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

All Styles are broken in v3.48.0 using the Ultima Theme.

load latest version of Ultima theme (v5.2.0)
npm install
npm run dev
All styles missing/broken.

### Expected behavior

Styles work as expected.  Ultima was purchased with lifetime support.

**Comment by dahjson** [comment]
Same here, I just spend a good bit of time updating my theme for version 3.47.2, and now my theme is broken again with version 3.48.0.

**Comment by antham** [comment]
I picked the css from https://github.com/primefaces/primevue/commit/c6151fe1ae82f8aff132a1e3d422ed4ae4dc22a0 to replace mine (lara-light-indigo), the UI was completely broken and could figure out what was happening.

**Comment by mikekidder** [comment]
Themes are released with a particular version, are they not?

Sakai -- release 5.9.0     
package.json  ->    "primevue": "3.39.0",

You can probably go up to 3.45.0, but most have had issues going beyond that version as discussed in the Discord channels.
PrimeTek is transitioning is transitioning away from Primceflex to TailwindCSS

**Comment by mikekidder** [comment]
Agree, and should of been handled better.  Not defending, and don't work for them.
If latest PrimeVue updates were version 4.x.x, Semantic Versioning would have made it clear they were not backwards compatible.

**Comment by cvalues** [comment]
We have used the theme builder to change styles at a chose theme and we are working with this theme since months. 
Now everything is broken, is there a way to merge our generated theme fromn the primevue themebuilder with the new changes or do we have to stay on 3.46.0?

**Comment by Ky6uk** [comment]
Upgrading `3.46` -> `3.48` also breaks almost everything in my case. I am quickly discovering that many class names are gone (but still appeared in the documentation, like `p-inputswitch-checked`). At the moment it looks like a huge breaking change upgrade even for a minor version. Can't find a list of breaking changes and a way how to adopt the changes after the upgrade. 🤔

**Comment by mertsincan** [comment]
Hi all,

PrimeVue is currently undergoing intensive development, with many improvements in progress. We're planning to update and release the complete PrimeVue template by the end of February. We apologize for the delay.

Best Regards,

**Comment by inane** [comment]
No, I am sorry @jvidagany . I am with the last version that was working.

**Comment by jasontalon** [comment]
Hello, any update on this issue? I'm using the Apollo template and could not update from PrimeVue v3.38.1 to the latest v3.52.0

**Comment by ALC-Poehacker** [comment]
Hi, same problem for Verona template. PrimeVue v3.44.0 still work. Later versions breaks all styles.
