### ISSUE TITLE
Breaking change in minor update 3.34 -> 3.35 - using @layer 

### ISSUE THREAD

**Issue by milanio** [primefaces/primevue#5228]
### Describe the bug

css @layer is only supported since Chrome 99+ - https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
If you need to support any earlier version (for example because you are using PrimeVue in Android System Webview on older Androids) you cannot do a minor PrimeVue version upgrade. Is there any workaround? Can we somehow disable @layer completely?

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template?file=README.md

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 95

### Steps to reproduce the behavior

1. Use Official PrimeVue Examples - https://github.com/primefaces/primevue-examples/tree/main/vite-ts-quickstart
2. npm run build 
3. npm run preview
4. open in browser Chrome 95 (for Example in Windows Sandbox) - you will see:
<image src="https://github.com/primefaces/primevue/assets/2590486/7b8b55b5-9e0f-4812-b819-32bd1eb356b7" width=300>

### Expected behavior

See unbroken PrimeVue Example page 
<image src="https://github.com/primefaces/primevue/assets/2590486/f8e2abbf-7a68-41fa-a74b-0107eaa45b31" width=300>

**Comment by mertsincan** [comment]
Hi,

We are currently working on the new theming API. When it is finished, you will be able to control it with an option such as layer="true|false". We will announce this when we complete it. Thanks a lot for your understanding!

Best Regards,

**Comment by FVolral** [comment]
Any news about it ? I've a weird issue where webpack is reordering the layer in production when it create its chunk-vendors
