### ISSUE TITLE
Divider: type dotted/dashed without effect

### ISSUE THREAD

**Issue by danielrentz** [primefaces/primevue#5233]
### Describe the bug

The dotted/dashed style type is not visible. Seems there is no definition for classes "p-divider-dashed" and "p-divider-dotted".

### Reproducer

https://primevue.org/divider/#type

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox

### Steps to reproduce the behavior

Go to https://primevue.org/divider/#type, check example box.

**Comment by tugcekucukoglu** [comment]
Thank you for your report. You could track this [issue](https://github.com/primefaces/primevue/issues/5231)
