### ISSUE TITLE
Calendar: error when incrementing/decrementing time using selection-mode

### ISSUE THREAD

**Issue by AAndonio** [primefaces/primevue#5236]
### Describe the bug

Using the Calendar component with `show-time` and `selection-mode` (range or multiple)  and passing a ref with undefined value as v-model, raises an uncaught error when clicking on increment/decrement buttons for time because v-model is undefined.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-mf7ib7?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Instantiate the Calendar component with props: `show-time` and `selection-mode="range"`
2. Pass a ref with undefined value as Calendar v-model
4. Click on the input to open the calendar
5. Click on increment/decrement time buttons
6. Check the console

### Expected behavior

Should handle the undefined value correctly and using the time buttons should insert the current date as the first value of the selection

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll check it before the milestone is released.

**Comment by AAndonio** [comment]
Hello again, I tested it with PrimeVue 4.0.0 and the error still persists.
