### ISSUE TITLE
InputGroup: Not working with Tailwind

### ISSUE THREAD

**Issue by san-kumar** [primefaces/primevue#5237]
### Describe the bug

I'm using "primevue/passthrough/tailwind" but it is not working with  InputGroup, InputGroupAddon. The icon appears on the top instead of left.

![image](https://github.com/primefaces/primevue/assets/33421306/8b592e3e-9da3-413f-a901-365fdb8b54ff)

### Reproducer

https://stackblitz.com/edit/kcuyyb-xek8jo?file=src%2FApp.vue,src%2Fmain.js

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

The icon should appear on the left (like Lara theme). Instead it appears on the top

**Comment by tugcekucukoglu** [comment]
`passthrough/tailwind` will be deprecated. We suggest using Tailwind presets.

Thanks for your understanding!
