### ISSUE TITLE
DataTableProps: Importing breaks hot reloading in Vite, hangs on: `vite:hmr [file change]`

### ISSUE THREAD

**Issue by Aspyryan** [primefaces/primevue#5238]
### Describe the bug

When having the import `const props = defineProps<DataTableProps>();` in a file present, while changing a reference prop in vue 3. the Hot reloading hangs, stops the browser tab from working and doesn't reload untill 5 minutes have passed. 
When removing the primevue imports, everything works perfectly. And nothing hangs. Running `npx vite --version` shows `vite/5.0.12 linux-x64 node-v18.18.0` on stackblitz and `vite/5.0.12 win32-x64 node-v18.18.2` on my system. The vue and typescript versions all match. What is causing this.

NOTE: Adding the interface myself and using it that way also works? This is becoming weird. Please provide some information on how to proceed

https://github.com/primefaces/primevue/assets/52763578/d262bb94-d4b9-46ed-af7b-0394979f7251

### Reproducer

Watch video / Stackblitz HMR works defferently then on windows systems

### PrimeVue version

^3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use this as the app.vue file:
```vue
<script setup lang="ts">
import { type DataTableProps } from 'primevue/datatable';
import { ref } from 'vue';

const props = defineProps<DataTableProps>();

const test = ref<string>('Test2');
</script>

<template>
	<span>Test5</span>
</template>
```

1. Change the test ref to something random
2. Try changing the Test span to something
3. Notice nothing reloads
4. Try reloading browser
5. Notice it hangs
6. Wait 5 minutes
7. Reload completes

8. Remove import
9. Try again
10. Everything works

### Expected behavior

Hot reloading to be consistent and not breaking on an import

**Comment by NeluQi** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

Please try;
```
import type { DataTableProps } from 'primevue/datatable';
```
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

Best Regards,

**Comment by Aspyryan** [comment]
Hi @mertsincan,

This does not solve the problem, still the same issue.

**Comment by Aspyryan** [comment]
@mertsincan, could you please reopen the issue, it is not fixed
