### ISSUE TITLE
Tooltip: custom z-index does not work

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#5239]
### Describe the bug

I have changed the base z-index of the tooltip to 1700.
This is not applied, the tooltips are still at 1000.

(Changing z-index of menus etc is working.)

![image](https://github.com/primefaces/primevue/assets/8471027/4fce4225-e421-4114-a935-adbaf83b7eb1)

![image](https://github.com/primefaces/primevue/assets/8471027/fe22454e-45cc-48f5-9909-bd1b8d00dc13)

I found an old issue with a workaround.
This workaround still works.
https://github.com/primefaces/primevue/issues/2468#issuecomment-1144566572
The mentiond vuejs bug is already fixed since vuejs v3.2.32.

### Reproducer

https://stackblitz.com/edit/rm76cd?file=src%2FApp.vue

### PrimeVue version

3.48.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

see reproducer

### Expected behavior

z-index of tooltip should be at 1700.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll review before the milestone is released.

**Comment by tugcekucukoglu** [comment]
It seems [this issue](https://github.com/primefaces/primevue/issues/2468) still remains as we can see from the demo that you've shared. And the same workaround needs to be used also. When a change occurs on the Vue core side, we will update all the directives.

**Comment by jjaychen1e** [comment]
This issue still exist in the latest version of PrimeVue + Vue 3, please reopen it @tugcekucukoglu @mertsincan
