### ISSUE TITLE
TreeTable: new Column PassThrough for Checkbox doesn't work

### ISSUE THREAD

**Issue by malikba** [primefaces/primevue#5241]
## Description
PassThrough options for checkbox on TreeTable were changed in PrimeVue v3.48.0.
The [new option found](https://primevue.org/treetable/#pt.doc.column) in the documentation `rowCheckbox` isn't working at all.

### Reproducer

https://stackblitz.com/edit/rtllxp?file=src%2FApp.vue

### PrimeVue version

3.48.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Try to use `:pt="{ rowCheckbox: { class: 'test' }}"` on a Column component of a TreeTable.

### Expected behavior

The `test` class isn't applied on the `.p-treetable-checkbox` element (or `data-pc-name="rowcheckbox"`)

**Comment by mertsincan** [comment]
Hi,

Please try;
```
:pt="{ rowCheckbox: { root: {class: 'test' } }}"
```
rowCheckbox uses https://primevue.org/checkbox/#pt.doc.checkbox

Best Regards,
