### ISSUE TITLE
TabView: Issues with Vue 3.4.16

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [primefaces/primevue#5242]
### Describe the bug

With version 3.4.16 of Vue, tab views in PV have become broken: Many times, the tabs won't display their contents. Switching back to Vue 3.4.15 solves this issue.

So yeah, this might be a Vue bug, but since it affects PV, I thought reporting it here a good idea.

### Reproducer

No time for this...

### PrimeVue version

3,48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Any

### Steps to reproduce the behavior

Have a tab view with some tabs. Switching between tabs sometimes works as expected, but sometimes the tab contents won't display.

### Expected behavior

Working tabs...

**Comment by BITSOLVER** [comment]
I came across this issue as well.

**Comment by NeluQi** [comment]
+1

**Comment by Aspyryan** [comment]
Same issue +1, reverting to 3.4.15 works

**Comment by NeluQi** [comment]
Version 3.4.16 Vue completely breaks components prime (Computed property "getPTOptions" is already defined in Methods. )

**Comment by EzeFSpa** [comment]
Same issue.

Maybe this can help:

I have 2 tabs with content. When i click the secod, all content tabs gone. This caught my attention: they have  "display: none" in both divs. 

![image](https://github.com/primefaces/primevue/assets/16340729/3a101440-e2c1-4caf-81c6-1302a0c3d90c)

**Comment by BITSOLVER** [comment]
vue 3.4.18 seems ok for me with PrimeVUE now

**Comment by sfxcode** [comment]
Hi, after the last updates from the vue team for me it is solved with the latest 3.4.18 version.

Think it is resolved from their side.

Happy coding,

Tom

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the updates!

**Comment by Daniel-WWU-IT** [comment]
Vue 3.4.18 seems to have fixed this (at least in our case).

**Comment by lewandy** [comment]
Same issue here, updating to "vue": "^3.4.19", solved the issue. thanks @Daniel-WWU-IT  for opening this issue.

**Comment by dcb99** [comment]
Why was this issue closed? I'm still having issues the TabView with 3.48.1 and Vue 3.4.19
![image](https://github.com/primefaces/primevue/assets/31573956/2ac663b6-0f4c-42f4-8212-f3926837c605)

**Comment by EzeFSpa** [comment]
Sorry for the delay, I confirm that after updating to the latest versions, I no longer see this problem

**Comment by rpatidar** [comment]
I am facing issue , the tab switch shows but the content is not updated

I am on the latest version 

```
  "dependencies": {
    "@iconify/vue": "^4.1.2",
    "@primevue/themes": "^4.0.0",
    "@tanstack/vue-table": "^8.20.4",
    "@vueuse/core": "^11.0.0",
    "chart.js": "3.3.2",
    "date-fns": "^3.6.0",
    "openapi-fetch": "^0.11.1",
    "openapi-typescript-fetch": "^2.0.0",
    "pinia": "^2.2.2",
    "primeicons": "^6.0.1",
    "primevue": "^4.0.0",
    "tiny-case": "^1.0.3",
    "ts-node": "^10.9.2",
    "vee-validate": "^4.13.2",
    "vue": "^3.4.34",
    "vue-router": "^4.4.0",
    "yup": "^1.4.0"
  },
```

**Comment by rpatidar** [comment]
it looks like issue with the where i click on the tab,  link is wrapped inside a button 
if i am clicking on the link area tab switch works. if i click on the button area , tab switch is done but content is not updated. 

![Uploading Screenshot 2024-08-18 at 10.24.39 PM.png…]()

**Comment by chaynesprime** [comment]
Based on @rpatidar's findings, was able to fix w/css overrides:
.p-tab {
  padding: 0 !important;
}

.p-tab a {
  padding: 1em;
}
