### ISSUE TITLE
Toast: Using "group" won't appear

### ISSUE THREAD

**Issue by iamnobodysir** [primefaces/primevue#5246]
### Describe the bug

When I set my group in the toast, it won't appear.

### Reproducer

https://stackblitz.com/edit/vfocsb-5kjfxd?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

 toast.add({
    severity: 'success',
    summary: 'Info message',
    detail: 'Message content',
    life: 3000,
    group: 'bl',
  });

### Expected behavior

To show toast

**Comment by ZiadJ** [comment]
That's because the group isn't specified there in the template. Here's the fixed version: https://stackblitz.com/edit/vfocsb-dsj7kh?file=src%2FApp.vue

**Comment by iamnobodysir** [comment]
> That's because there's no matching group in the template. Here's the fix: https://stackblitz.com/edit/vfocsb-dsj7kh?file=src%2FApp.vue

Thank you, I was having trouble understanding the doc.
