### ISSUE TITLE
MeterGroup: Cutoff at the beginning when the first element is 0

### ISSUE THREAD

**Issue by kilobyte2007** [primefaces/primevue#5252]
### Describe the bug

The meter group is cut at the beginning if the first value of value is 0.

<img width="672" alt="SCR-20240209-kyyo" src="https://github.com/primefaces/primevue/assets/1911258/65ac47ae-75fa-412a-a150-9b6e75cfac68">

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-gsstdw?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 121

### Expected behavior

The meter group should be rounded from both sides independently of the values.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone for it. We'll check before the milestone is released.
