### ISSUE TITLE
Calendar: When entering the time by hand into timeOnly calendar, values switch to NaN:NaN

### ISSUE THREAD

**Issue by Tyde** [primefaces/primevue#5254]
### Describe the bug

If I have a Calendar with the timeOnly and hourFormat="24" parameter and I enter the time in the format 09:00 directly into the input as text, it fails and switches to NaN:NaN. There is no option to recover from this.

Reproducer taken from the example from the documentaion

### Reproducer

https://stackblitz.com/edit/vv7pr3?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Have a Calendar with a null value
Go into InputText from Calendar
Type 09:00
--> Value switches to NaN:NaN

### Expected behavior

The time that was writteen is accepted as the time in the Calendar. AFAIK this has worked in earlier versions

**Comment by Tyde** [comment]
Issue seems to lie here:
https://github.com/primefaces/primevue/blob/971a346c5f30a81c559a4831fb2456356ffcaecc/components/lib/calendar/Calendar.vue#L1811
If the modelValue is not yet defined, it will fall back into an "invalid date" which leads to the NaN:NaN issue

**Comment by jozefnad** [comment]
now, there is issue that date resets if I change timeOnly component
