### ISSUE TITLE
Password: the :pt option "input" doesn't respond

### ISSUE THREAD

**Issue by BrayanDev01** [primefaces/primevue#5255]
### Describe the bug

I'm making a :pt call as I did in past versions, but the input option has no effect

### Reproducer

https://stackblitz.com/edit/fziemq-bfwpxk?file=src%2FApp.vue

### PrimeVue version

3.48.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi,

Password uses InputText component. Please try;
https://stackblitz.com/edit/fziemq-w83bqi?file=src%2FApp.vue

Best Regards,

**Comment by BrayanDev01** [comment]
@mertsincan  Sorry, I tried it several ways but it didn't work for me

**Comment by BrayanDev01** [comment]
My need is to just increase the size of my password input to "width: 100%", the solution you gave me did not work for me

**Comment by BrayanDev01** [comment]
Thanks for the clarification
