### ISSUE TITLE
Upload: The code example on the template section doesn't work

### ISSUE THREAD

**Issue by anchan42** [primefaces/primevue#5259]
### Describe the bug

There is a stray comma at the end of formatSize function.

I also have to change const sizes = this.$primevue.config.locale.fileSizeTypes; to const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']; to make it work.

https://stackblitz.com/run?file=src%2FApp.vue

![image](https://github.com/primefaces/primevue/assets/19514416/2080bb49-9c8e-4755-a8c8-4c2b56ad18aa)

Related issues #5202.

### Reproducer

https://stackblitz.com/edit/rzilsm?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

1. Goto https://primevue.org/fileupload/
2. Scroll down to template section.
3. Click on stackblitz link.

### Expected behavior

There should be no errors.

**Comment by tugcekucukoglu** [comment]
The live demo is fixed. Thank you. Also, you don't need to change sizes constant. A tip for the PrimeVue configuration for setup:

```
import { usePrimeVue } from 'primevue/config';

const $primevue = usePrimeVue();

const sizes = $primevue.config.locale.fileSizeTypes
```

**Comment by anchan42** [comment]
Thanks a lot for the tip! 😄
