### ISSUE TITLE
Listbox: Global checkbox to select/unselect all items.

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5263]
### Describe the bug

Similar MultiSelect component

### Reproducer

.

### PrimeVue version

3.48.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
