### ISSUE TITLE
Unable to get datatable working using cdn

### ISSUE THREAD

**Issue by rdksgit** [primefaces/primevue#5265]
### Describe the bug

First of all thanks for the most amazing components library, well done

I am trying to get the datatable working using cdn, however it comes up with

vue.global.js:1612  [Vue warn]: Failed to resolve component: datatable
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>
vue.global.js:1612  [Vue warn]: Component is missing template or render function. 
  at <Column key=1 field="User A" header="User A" > 
  at <App>

I am using primevue 3.48.1.

Apologies in advance if the bug report is not descriptive enough, i am very new to Vue :)
Thanks
Sameer

### Reproducer

test

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

<script src='https://unpkg.com/vue@3/dist/vue.global.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/primevue/3.48.1/core/core.min.js"></script>
<script src="https://unpkg.com/primevue/datatable/datatable.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/primevue@3.48.1/resources/themes/aura-light-cyan/theme.css" />
<div  id="app" class="card flex justify-content-center">
  
    <div class="col-md-4" >
     
  </div>
<div class="col-md-8">
<h2>List of Users belonging to X</h2>
<DataTable :value="users">
  <Column v-for="col of users" :key="col.id" :field="col.name" :header="col.name"></Column>
</DataTable>
   
  </div>
  
</div>
<script>
    const app = Vue.createApp({    
      components: {Tree: primevue.tree, DataTable: primevue.datatable, Column: primevue.column },
  data(){
    return {
          searchText: '',
          selectedKey: '',
          toast: '',
          node:'',
          data: [
            {
              key: 1,
              label: "Franchisee 1",
              children: [
                { key: 2, label: "Office 1.1" },
                { key: 3, label: "Office 1.2" },
              ],
            },
            { key: 4, label: "Node 2" },
            
          ],
          users: [
            { id: 1, name: "User A"},
            { id: 4, name: "User B" },
          ]
        };
 
    },
    mounted(){
    },
    methods:{
     
        getUsers(){
            
        }
        
    }
    
   
});
app.mount('#app');
</script>

### Expected behavior

It should show the datatable rendered

**Comment by sudipmandal** [comment]
In CDN mode the row edit is not working, you can try to build it in the above stackblitz page, the edit pencil icon at end of the row does not show up.
