### ISSUE TITLE
documentation issue at datatable selection 

### ISSUE THREAD

**Issue by ntedgi** [primefaces/primevue#527]
**BUG**  when using selection with  **v-model:selection** table doesn't load  the table rows 
displaying an empty table 

**Ways to reproduce:**
follow this page at any of the example 

https://www.primefaces.org/primevue/showcase/#/datatable/selection

**How to solve this issue?**

**v-model:selection** shuld be  change to  **:selection.sync**

**Comment by cagataycivici** [comment]
The link is for Vue 3, for Vue 2 you need to use the following one;

https://www.primefaces.org/primevue/showcase-v2/#/datatable/selection
