### ISSUE TITLE
InputIcon class support & InputField style updates

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#5273]
Inner input-icon changes:

- Calendar
- Password

**Comment by InvisibleSmiley** [comment]
In case anyone else stumbles over this like I did, FTR:

This change in PrimeVue 3.49.0 removed classes `p-input-icon-left` and `p-input-icon-left`, previously used for styling `i` tags inside custom containers with those classes applied. I guess this wasn't officially supported, and `IconField` should be used. Haven't tried that.

I fixed it by making these changes:
- replace `p-input-icon-left` by `p-icon-field-left` on container
- replace `p-input-icon-right` by `p-icon-field-right` on container
- add `p-icon-field` to container
- add `p-input-icon` to `i` tags inside the container (which probably already had `pi` applied)
