### ISSUE TITLE
document.body.setAttribute('data-p-unselectable-text') missing second arguments.

### ISSUE THREAD

**Issue by AtrionTechSD** [primefaces/primevue#5280]
https://github.com/primefaces/primevue/blob/01c23a0b14e318e8efac127da36b95d5118aae65/components/lib/dialog/Dialog.vue#L304

Hello, it's my first time posting a issue here. The problema trigger when dragging Dialog componente, cause it's missing a second arguments in referenced code.

**Comment by mwishum** [comment]
I think this was already fixed but not yet released (3.49.0). 
#5244
