### ISSUE TITLE
DataTable: No way to add additional content in the table header below column headers and filters

### ISSUE THREAD

**Issue by Magiczne** [primefaces/primevue#5283]
### Describe the bug

Currently there is no way to add custom content into the table header just below the column headers and filters. We're struggling because of that, cause we need to add some custom content like secondary scrollbar that is synchronized with the bottom one, or some additional information.

I've created PR, that solves this issue by adding additional slot. I hope this will be resolved.
Additionaly this slot allows users to add custom content, and by adding some additional css using it to make sticky header for the datatable with additional content, necessary for the user.

### PrimeVue version

latest

### Vue version

3.x

**Comment by Magiczne** [comment]
@tugcekucukoglu @mertsincan 

Can we get at least some info on is it even considered?

**Comment by tugcekucukoglu** [comment]
Please check https://github.com/primefaces/primevue/pull/5284#issuecomment-1994430640

We need more community demand.

Thanks,

**Comment by daprezjer** [comment]
@tugcekucukoglu is there a way to thumbs this up to show more community demand? We're looking to put a simple tooltip on the header but can't because of this restriction.

![image](https://github.com/user-attachments/assets/92d37dd5-34ec-4827-b2f5-7f7ff739afb1)

**Comment by kwilson1337** [comment]
Yeah not being able to have some custom header code is really holding us back as well. All it would take is a slot in the table header section.
