### ISSUE TITLE
Dialog: Error when clicking on Dialog header: "setAttribute requires 2 arguments but only 1 present"

### ISSUE THREAD

**Issue by sdoerger** [primefaces/primevue#5287]
### Describe the bug

When clicking on the top area (header) of a PrimeVue Dialog component, an error is logged to the console indicating a problem with the setAttribute method being called with insufficient arguments."

`entry.e016913e.js:1 TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at Proxy.initDrag (Dialog.11d13b5e.js:7:365) at e.visible.e.$slots.container.e.showHeader.o.onMousedown.i.<computed>.i.<computed> (Dialog.11d13b5e.js:7:3881) at At (entry.e016913e.js:1:13068) at Be (entry.e016913e.js:1:13146) at HTMLDivElement.n (entry.e016913e.js:1:72052)`

This seems to happen to all dialogs.

![image](https://github.com/primefaces/primevue/assets/59424441/3fb17bec-02af-42de-a782-372f14aa7f66)

### Reproducer

https://primevue.org/dialog/

### PrimeVue version

^3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

- Go to [PrimeVue Dialog Documentation](https://primevue.org/dialog/)
- Click on the Dialog header area.
- Open the browser console to view the error.
- See error

### Expected behavior

No error in console.

**Comment by tugcekucukoglu** [comment]
Fixed for the next version: https://github.com/primefaces/primevue/issues/5240
