### ISSUE TITLE
Harcoded 16px margin-left in TreeTable

### ISSUE THREAD

**Issue by barbybindal** [primefaces/primevue#529]
Is there any way to change margin-left from 16px to ??px, in below code line. We need to align parent and child correctly.
https://github.com/primefaces/primevue/blob/master/src/components/treetable/TreeTableRow.vue#L264

**Comment by cagataycivici** [comment]
Tracked at #495

**Comment by cagataycivici** [comment]
There is a new indentation prop now, more detains in 495.
