### ISSUE TITLE
Toast: Poor visibility on high contrast backgrounds in Aura dark theme

### ISSUE THREAD

**Issue by marknn3** [primefaces/primevue#5290]
PrimeVue v3.48.1

### Issue
Toast messages in Aura-dark theme have very poor visibility when displayed over a high contrast background.
This is because the Toast message background has a too high transparancy.
![image](https://github.com/primefaces/primevue/assets/4366965/3d71e798-1213-4ef1-a867-437a9857f531)

### Proposal
Here is a proposal with much improved visibility:
![image](https://github.com/primefaces/primevue/assets/4366965/307f3eaa-ca2f-49ea-9f74-fb84e289a727)

These are the proposed style changes. They should be applied to all applicable css selectors and to all Aura dark themes.
* Info:  <pre>background: rgba(20, 29, 48, 0.8);</pre>
* Success: <pre>background: rgb(28, 46, 31, 0.8);</pre>
* Warn:  <pre>background: rgba(52, 44, 22, 0.8);</pre>
* Error:  <pre>background: rgba(51, 26, 27, 0.8);</pre>

Note: These toast message background colors are visually identical to the original version when displayed over a black background.

The message text can probably be slightly brightened.

The Lara dark theme also has this same visibility issue, but is less prominent due to brighter message text.

This is likely a change for v4.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/5226

**Comment by marknn3** [comment]
> Duplicate #5226

@tugcekucukoglu I understand why you think this is a duplicate, but I respectfully disagree.
&num;5226 is about the tailwind.primevue components, and does not address poor visibility.

**Comment by luke-z** [comment]
Yeah, #5226 is about the white border which shouldn't be there when using tailwindcss. This one is about the transparency.

**Comment by cugarteblair** [comment]
> > Duplicate #5226
> 
> @tugcekucukoglu I understand why you think this is a duplicate, but I respectfully disagree. #5226 is about the tailwind.primevue components, and does not address poor visibility.

I have this problem as well. I do not use tailwind

**Comment by cugarteblair** [comment]
> PrimeVue v3.48.1
> 
> ### Issue
> Toast messages in Aura-dark theme have very poor visibility when displayed over a high contrast background. This is because the Toast message background has a too high transparancy. ![image](https://private-user-images.githubusercontent.com/4366965/305272439-3d71e798-1213-4ef1-a867-437a9857f531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTQ2OTksIm5iZiI6MTczMjExNDM5OSwicGF0aCI6Ii80MzY2OTY1LzMwNTI3MjQzOS0zZDcxZTc5OC0xMjEzLTRlZjEtYTg2Ny00MzdhOTg1N2Y1MzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTQ1MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWNiM2UxNDgwN2I2ZDgyNjMxOTQxM2I1N2Q2M2M0YWQzZDc1YmJiNDE5NTRjMDZjMTNjZTIzNTlmZGVmZDc1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._9l2hKu8ptAlHbBKv4bTFptgKQkM5i_31RmSbu6OE1s)
> 
> ### Proposal
> Here is a proposal with much improved visibility: ![image](https://private-user-images.githubusercontent.com/4366965/305274009-307f3eaa-ca2f-49ea-9f74-fb84e289a727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTQ2OTksIm5iZiI6MTczMjExNDM5OSwicGF0aCI6Ii80MzY2OTY1LzMwNTI3NDAwOS0zMDdmM2VhYS1jYTJmLTQ5ZWEtOWY3NC1mYjg0ZTI4OWE3MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTQ1MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YyODAzNjNjOGFhNzU0MTZkOTUxMGVmNjYxYTYxNWQ1NjM0NmFkMDJjMzMxYjY4YzMwNWUyYTkxMGQyOGVhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.I4lgsBTUNqFT8svAyeJjZ0Xu431Ll0D9KwFtDNMge-o)
> 
> These are the proposed style changes. They should be applied to all applicable css selectors and to all Aura dark themes.
> 
> * Info:  background: rgba(20, 29, 48, 0.8);
> * Success: background: rgb(28, 46, 31, 0.8);
> * Warn:  background: rgba(52, 44, 22, 0.8);
> * Error:  background: rgba(51, 26, 27, 0.8);
> 
> Note: These toast message background colors are visually identical to the original version when displayed over a black background.
> 
> The message text can probably be slightly brightened.
> 
> The Lara dark theme also has this same visibility issue, but is less prominent due to brighter message text.
> 
> This is likely a change for v4.

Is there a workaround for this?

**Comment by luke-z** [comment]
@cugarteblair we're using a workaround in a custom theme.

Here's the code:

```
import { definePreset } from '@primeuix/styled'
import Aura from '@primevue/themes/aura'

const CustomAura = definePreset(Aura, {
  components: {
    toast: {
      colorScheme: {
        dark: {
          error: {
            background: '{red.500}',
            color: '{white}',
          },
          success: {
            background: '{green.500}',
            color: '{white}',
          },
          warn: {
            background: '{yellow.600}',
            color: '{white}',
          },
          info: {
            background: '{blue.500}',
            color: '{white}',
          },
        },
      },
    },
  },
})

export default {
  preset: CustomAura,
  options: {
    darkModeSelector: '.dark',
  },
}
```

Using this, the transparency is lost, but this was the easiest way to make the toasts readable in dark mode.
Maybe you could add a transparency somehow, but we are happy with it haha
