### ISSUE TITLE
DataTable: Changing value of expendedRow is not reflected

### ISSUE THREAD

**Issue by bdh92123** [primefaces/primevue#5291]
Detail of issue is in #5086 and not fixed in version 3.48.1
The problem of initial values not being reflected has been fixed, but the problem of changes not being reflected still exists.

Following is part of issue #5086 

> If only part of the data specified as expandedRows is modified externally, it will not be reflected.
> 
> Due to the same problem as above, the deep property seems to be false when watching expandedRows. It seems problematic that the entire value must be replaced to be reflected.

**Comment by bdh92123** [comment]
@tugcekucukoglu  You can replicate issue in https://codesandbox.io/s/primevue-demo-forked-ym4crg (URL is in mentioned issue #5086 )
 Try to click "expand black watch" button.

**Comment by tugcekucukoglu** [comment]
Unfortunately, codesandbox demo is not working.

**Comment by bdh92123** [comment]
@tugcekucukoglu The codesandbox mentioned above works well, but I have prepared the stackblitz reproducer again for you, give it a try. 
https://stackblitz.com/edit/ydc9nq?file=src%2FApp.vue

**Comment by ZiadJ** [comment]
@bdh92123 You closed the issue because you found a workaround?
