### ISSUE TITLE
Toast: rendered outside the vue app container

### ISSUE THREAD

**Issue by bronte2k7** [primefaces/primevue#5298]
### Describe the bug

Toast component is rendered outside the vue app container. No matter what part of the page the toast component is used, it is always rendered outside the vue app container

### Reproducer

https://codesandbox.io/s/primevue-2-issue-template-dw7jd7

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 121

**Comment by tugcekucukoglu** [comment]
Toast component uses Teleport component of Vue core. And this is expected behaviour.
