### ISSUE TITLE
Dialog: error on modal dragging

### ISSUE THREAD

**Issue by nodart-labs** [primefaces/primevue#5299]
### Describe the bug

there is an error on dialog dragging appearing in console:

Uncaught TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present.
    at Proxy.initDrag (primevue_dialog.js?v=58883c87:657:23)
    
fix it please

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome latest

### Steps to reproduce the behavior

init dialog open and drag by header

**Comment by coricss** [comment]
Same error when dragging dialog

![image](https://github.com/primefaces/primevue/assets/83864808/9ac2907f-75d7-4c45-a098-e7ca683742d0)

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/5240
