### ISSUE TITLE
MultiSelect not showing selected items

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#53]
Got an array of LookupVm class which has an id and a name properties. Binding everything together seems not working. Selected items not shown on the MultiSelect. Please see the code bellow:
```
<template>
...
<div class="p-col-12 p-md-4">
    <label for="roles">Role</label>
</div>
<div class="p-col-12 p-md-8">
    <MultiSelect id="roles" v-model="selectedRoles" optionLabel="name" :options="roleList" />
</div>
...
</template>
<script lang="ts">
	import Vue from "vue";
	import { UserService, LookupVm } from "@/services/index";

	export default Vue.extend({
		data() {
			return {
				selectedRoles: new Array<LookupVm>(),
				roleList: new Array<LookupVm>(),
			}
		},
		mounted() {
			this.loadRoleList();
		},
		methods: {
			loadRoleList() {
				UserService.getRolesLookup().then((result) => { this.roleList = result; })
			}
		},
	});
</script>
```
Screens:
![image](https://user-images.githubusercontent.com/13495631/65698721-e12a8880-e074-11e9-90e1-1149c23158fb.png)

![image](https://user-images.githubusercontent.com/13495631/65699308-cd335680-e075-11e9-814e-8cea98d96df3.png)

![image](https://user-images.githubusercontent.com/13495631/65699531-24392b80-e076-11e9-9cec-8aa938dc4405.png)

**Comment by denis-pujdak-adm-it** [comment]
Workaround: after I added ` placeholder="Select a Role"` it started showing the selected item.
```
<MultiSelect id="roles" v-model="selectedRoles" optionLabel="name" :options="roleList" placeholder="Select a Role" />
```

**Comment by cagataycivici** [comment]
I'm unable to replicate, if you can provide us a sample code that replicates the issue, it will be great.

**Comment by denis-pujdak-adm-it** [comment]
Do you know any sandbox so I can reproduce the issue? I tried that one (https://qmfcn.codesandbox.io/) but primevue is not working well there.
