### ISSUE TITLE
How do I remove hints from IDE/Vs code primevue css?

### ISSUE THREAD

**Issue by champ7champ** [primefaces/primevue#5302]
<img width="598" alt="image" src="https://github.com/primefaces/primevue/assets/81758691/1fd572d0-c15d-43b0-8c3c-78e79266586d">

This is terribly annoying in vscode webstorm (( can I turn it off somehow?

**Comment by champ7champ** [comment]
And it feels like because of this, he's been pulling up tailwindcss for a very long time

**Comment by tugcekucukoglu** [comment]
It is probably related tailwind or other third-party libraries.

Thanks for your time.
