### ISSUE TITLE
Password: after reset password meter not reset

### ISSUE THREAD

**Issue by mdrakash** [primefaces/primevue#5304]
### Describe the bug

when I reset my formData, password meter not update

### Reproducer

https://codesandbox.io/p/sandbox/elastic-swirles-w9qgvk

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
Cannot open the codesandbox demo. Could you share stackblitz link?

**Comment by mdrakash** [comment]
here is [https://stackblitz.com/edit/angular-qvm9mg-wz54uu?file=src%2FApp.vue](url)

**Comment by mdrakash** [comment]
https://stackblitz.com/edit/angular-qvm9mg-wz54uu?file=src%2FApp.vue
