### ISSUE TITLE
Center TabView tabs

### ISSUE THREAD

**Issue by ralfcarneborn** [primefaces/primevue#5317]
Hi, cant seem to figure out how I would flex the tabs OR center the tabs in a Tabview, here is the default example from the docs: https://stackblitz.com/edit/px4yqn?file=src%2FApp.vue

If i try to do flex: 1 on the tabs, the animation on the transition becomes all janky. I cant seem to figure out how to center what I got either. If i do other flexbox changes, then when i resize the page the active tab indicator does not follow along with the tab size.

I would not consider this a bug, but i cant find any example on how to solve this, or is it not meant to be possible?

**Comment by ZiadJ** [comment]
Seems to work fine with `:pt="{ nav: { style: 'justify-content: center' } }"`

 https://stackblitz.com/edit/px4yqn-ncuh9a?file=src%2FApp.vue

**Comment by ralfcarneborn** [comment]
I  must be having some general tailwind/primevue problems in my turborepo environment or something, the exact same code is giving me issues in my storybook.

Thanks for having a look at it, i will try to figure out how to properly create a turborepo package that creates components using primevue and tailwind, please let me know if there is a good example out there, im struggling.

**Comment by tugcekucukoglu** [comment]
@ZiadJ thanks for the solution!

@ralfcarneborn presets can be overridden https://tailwind.primevue.org/guides/overriding-presets/ and you can create your own library. For more information https://tailwind.primevue.org/guides/building-ui-library/
