### ISSUE TITLE
Menu components: Hidden Menu-Item can still be activated (focused) on Keyboard-Navigation

### ISSUE THREAD

**Issue by ico85** [primefaces/primevue#5318]
### Describe the bug

Setting an Menuitem to invisible like this: item.visible = false hides the menuitem correctly in the UI. However when navigating with Keyboard-Arrows the hidden Item still can receive focus. It seems that the visible Menu-Items are not in sync with the invisible Menu-Items.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-izcznw?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Set item.visible = false in a Menu-Item
2. Use Arrow-Navigation with keyboard to navigate through the Menu-Items. The hidden Menu-Item is activated and programmatically "activated", but it's not visible.

### Expected behavior

The Hidden Menu-Item should not receive Focus with keyboard navigation.

**Comment by tugcekucukoglu** [comment]
Affected components

- [ ] Breadcrumb
- [ ] ContextMenu
- [ ] Dock
- [ ] Menu
- [ ] Menubar
- [ ] MegaMenu
- [ ] PanelMenu
- [ ] Steps
- [ ] TabMenu
- [ ] TieredMenu

**Comment by Slyznord** [comment]
@tugcekucukoglu Hi! I have solved this problem for MenuBar component, but i can't push it to open merge request. Am I doing something wrong?

**Comment by tugcekucukoglu** [comment]
@Slyznord https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request can be help.
