### ISSUE TITLE
Dialog: On drag

### ISSUE THREAD

**Issue by sun-pandey** [primefaces/primevue#5325]
### Describe the bug

initDrag(e) {
            e.target.closest("div").getAttribute("data-pc-section") !== "icons" && this.draggable && (this.dragging = !0,
            this.lastPageX = e.pageX,
            this.lastPageY = e.pageY,
            this.container.style.margin = "0",
            document.body.setAttribute("data-p-unselectable-text"),
            !this.isUnstyled && r.addClass(document.body, "p-unselectable-text"))
        }

### Reproducer

https://primevue.org/dialog/

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

All

### Steps to reproduce the behavior

Error can be reproduced for any of the Dialog examples on https://primevue.org/dialog/

### Expected behavior

There should be no error in the Console.

**Comment by tugcekucukoglu** [comment]
Fixed for the next version https://github.com/primefaces/primevue/issues/5240

Thank you.
