### ISSUE TITLE
Breaking changes / Semantic versioning

### ISSUE THREAD

**Issue by jasonsaayman** [primefaces/primevue#5326]
### Describe the bug

Hi, it seems that several breaking changes were released in a minor version. Does this repo no longer follow semantic versioning? If that is the case could you make that more clear to the consumers of this project? Bumping a minor and having your entire UI break is not great, there are a number of things removed in the minor change.

### Reproducer

n/a

### PrimeVue version

3.48.x

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by cagataycivici** [comment]
Hi, for questions please use the discussions in the future.

https://github.com/orgs/primefaces/discussions

We're switching to semantic version with the upcoming v4 in 1-2 weeks, currently v3 was used to align with Vue version but it does not suit well to our side so v4 is necessary.
