### ISSUE TITLE
Dialog: On header click shows error

### ISSUE THREAD

**Issue by LukasGrofcikDemi** [primefaces/primevue#5328]
### Describe the bug

When using a dialog, clicking on header (except close icon) throws
> TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present.

### Reproducer

could not reproduce

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to [https://primevue.org/dialog/](https://primevue.org/dialog/)
2. Click on Show button
3. Click on header element, but not on close button
4. Console logs error

### Expected behavior

No error

**Comment by tugcekucukoglu** [comment]
Please try to use version 3.49.0. It was fixed.

Thank you.
