### ISSUE TITLE
inputOTP - integerOnly doesn't work with number pad

### ISSUE THREAD

**Issue by yureckey** [primefaces/primevue#5329]
### Describe the bug

with integerOnly I cannot use numbers pad.

### Reproducer

https://primevue.org/inputotp/#integeronly

### PrimeVue version

3.49.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 121, Windows 10

### Steps to reproduce the behavior

https://primevue.org/inputotp/#integeronly
use keyboard top row with numbers - input works
use number pad (right side of keyboard) - input doesn't work

### Expected behavior

numbers should work for both top row and number pad

**Comment by franmc01** [comment]
Solution here: https://github.com/primefaces/primevue/pull/5358

**Comment by franmc01** [comment]
@melloware How does the reviews work? I want to contribute :)

**Comment by melloware** [comment]
@franmc01 its easy just submit a PR and PrimeTek will review it or reject it!

**Comment by yureckey** [comment]
Hmm, I'm trying just released 3.50 and it is even more broken somehow 🤔 
I'm still on Windows 10, last Chrome - any number key pressed doesn't show in https://primevue.org/inputotp/#integeronly
not regular number keys, not additional

**Comment by sinchijackal** [comment]
> Hmm, I'm trying just released 3.50 and it is even more broken somehow 🤔 I'm still on Windows 10, last Chrome - any number key pressed doesn't show in https://primevue.org/inputotp/#integeronly not regular number keys, not additional

The same issue is observed on iOS 17.4

**Comment by franmc01** [comment]
@yureckey I had resolved that situation in the PR https://github.com/primefaces/primevue/pull/5358

but it was not accepted, in that case I sent some fixes from the landing

**Comment by franmc01** [comment]
There I sent the pr again, from my tests the problem is that event.keyCode is used in favor of event.key; From what I saw the first one is obsolete. I changed the implementation to event.key and it worked perfectly, I had even added the validation that when you copy a code it is also validated that it is numerical because in the current one it is either numerical or it does not let you copy any string

**Comment by Payn** [comment]
Any update to this? It's not fixed, IntegerOnly still doesn't accept numbers in version 3.50.

**Comment by franmc01** [comment]
I sent this PR: https://github.com/primefaces/primevue/pull/5424

**Comment by franmc01** [comment]
No accepted :(
