### ISSUE TITLE
Stepper component style build is broken

### ISSUE THREAD

**Issue by haiming236** [primefaces/primevue#5332]
### Describe the bug

When encountering style issues using the new component Stepper, please send it for resolution
![PixPin_2024-02-24_20-26-54](https://github.com/primefaces/primevue/assets/81062909/a35f6fe4-e15b-4160-8e5e-fe56d97378d3)
![PixPin_2024-02-24_20-26-22](https://github.com/primefaces/primevue/assets/81062909/251f6398-4f4a-4490-948d-a89ce441beb3)

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-asv6zd?file=src%2Fmain.ts

### PrimeVue version

3.49

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by zhaoyao** [comment]
The issue is caused by the primevue/stepper/style/package.json file. It mistakenly uses the contents of stepperpanel/package.json. 

```json
{
    "main": "./stepperpanel.cjs.js",
    "module": "./stepperpanel.esm.js",
    "unpkg": "./stepperpanel.min.js",
    "types": "./StepperPanel.d.ts"
}

```


Replacing it with the following:

```json
{
    "main": "./stepperstyle.cjs.js",
    "module": "./stepperstyle.esm.js",
    "unpkg": "./stepperstyle.min.js",
    "types": "./StepperStyle.d.ts"
}
```

will fix the issue, allowing for successful imports.

**Comment by haiming236** [comment]
Thank you for resolving the backend runtime error, but the component still cannot be rendered properly. Did you succeed? The frontend console printed ReferenceError: StepperStyle is not defined

**Comment by Slluxx** [comment]
Facing the same issue.
