### ISSUE TITLE
InputOtp: Numpad not working

### ISSUE THREAD

**Issue by twihno** [primefaces/primevue#5335]
### Describe the bug

Numpad doesn't do anything in `integerOnly` mode. Only the "normal" number keys or an on-screen keyboard can be used

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-rz9mox?file=src%2FoverflowDemo.vue

### PrimeVue version

3.49.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Use `integerOnly` mode
2. Try entering any value with the numpad

### Expected behavior

Numpad should also be usable to input values in `integerOnly` mode

**Comment by twihno** [comment]
Duplicate of #5329 . The github search apparently only worked after I opened this issue...

**Comment by franmc01** [comment]
Solution here: https://github.com/primefaces/primevue/pull/5358

**Comment by franmc01** [comment]
@mertsincan @melloware guys can you check my Pr
