### ISSUE TITLE
InputOtp: Length not working

### ISSUE THREAD

**Issue by twihno** [primefaces/primevue#5336]
### Describe the bug

Values with more than "length" characters can be entered

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-rz9mox?file=src%2FoverflowDemo.vue

### PrimeVue version

3.49.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Try entering more than "length" characters

### Expected behavior

The input should "block" additional input after "input" characters

**Comment by francescods** [comment]
+1
