### ISSUE TITLE
TabPanel: props can not be kebab-case

### ISSUE THREAD

**Issue by Anubarak** [primefaces/primevue#5338]
### Describe the bug

As Like this one
https://github.com/primefaces/primevue/issues/1263

Some props like `content-class` or `content-style` still cannot be kebab-case and must be camelCase.

```vue
<TabView>
  <!-- does not work -->
  <TabPanel
	content-style="background: red"
	content-class="some-class"
	header="Header I">
	<p class="m-0">styling and class are ignored</p>
  </TabPanel>
  
  <!-- works -->
  <TabPanel
	contentStyle="background: red"
	contentClass="some-class"
	header="Header II">
	  <p class="m-0">styling works</p>
  </TabPanel>

</TabView>
```

### Reproducer

https://stackblitz.com/edit/scv6yh?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

See props on the first TabPanel and on the second TabPanel.
CamelCase Props work (2nd), kebab-case do not work (1st)

### Expected behavior

Both should work as per Vue rules

**Comment by tugcekucukoglu** [comment]
Could you check the next version 4? There are huge changes with version versions.

**Comment by Anubarak** [comment]
It still does not work with your v4 version.
Can you re-open or should I close this issue?
