### ISSUE TITLE
FullCalendar is not working on primevue v3

### ISSUE THREAD

**Issue by tomer-yechiel** [primefaces/primevue#534]
edit:
found the issue, full calendar is now at v5
need to change the doc to:
npm install @fullcalendar/core@4.0.2 --save

in the documentation it said to import this 3 lines
import '@fullcalendar/core/main.min.css';
import '@fullcalendar/daygrid/main.min.css';
import '@fullcalendar/timegrid/main.min.css';

but import '@fullcalendar/core/main.min.css'; is not existing
i installed npm install @fullcalendar/core --save
and i see core folder at npm_modules, but i dont see main.min.css at that folder

**Comment by cagataycivici** [comment]
Please monitor;

https://github.com/primefaces/primevue/issues/540
