### ISSUE TITLE
DataTable: [Vue warn]: Invalid prop: type check failed for prop "rowClass". Expected String | Object, got Function

### ISSUE THREAD

**Issue by saeedkgr** [primefaces/primevue#5341]
### Describe the bug

in DataTable rowClass prop can be a function and work fine as function but in BaseDataTable.Vue defined as 
        rowClass: {
            type: [String, Object],
            default: null
        },
so a warning generate in console when used as function.

### Reproducer

ss

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

chrome

### Steps to reproduce the behavior

1. define a function like
const rowClass = (data) => {
  return ['cursor-pointer', { 'bc-changed-dataset': data.isChanged }]
}
2. define prop :rowClass='rowClass'

### Expected behavior

no vue warning

**Comment by nikitakoliadin** [comment]
Same problem

**Comment by schoonc** [comment]
Looks like it was introduced by this commit:
![image](https://github.com/primefaces/primevue/assets/4659633/86a3ea0c-6bdd-43f4-a37c-61677963b3d7)

**Comment by cuberinooo** [comment]
Same issue here: https://github.com/primefaces/primevue/issues/5349

**Comment by shtse8** [comment]
I have the same, any fix and workaround for now?
