### ISSUE TITLE
InputOTP - Missing Types

### ISSUE THREAD

**Issue by sn0rcha** [primefaces/primevue#5342]
### Describe the bug

InputOTP is missing the type definitions:

```Could not find a declaration file for module 'primevue/inputotp```

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-2bd61h?file=src%2FApp.vue

### PrimeVue version

3.49.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

All

### Steps to reproduce the behavior

1. Import InputOTP from 'primevue/inputotp'
2. See the typescript error

### Expected behavior

Types should be present.

**Comment by tugcekucukoglu** [comment]
It is fixed with 3.49.1.

Thank you.
