### ISSUE TITLE
ToastService $toast is not any more

### ISSUE THREAD

**Issue by anilrepala505** [primefaces/primevue#5346]
### Describe the bug

I have updated VUE version from 2.X to 3.2.45 and started using primevue (3.49.1) along with primeflex(3.3.1) & primeicons (6.0.1).

Tried to implement toast message into the application but it is giving error and unable to find a fix for it.

### Package.json
 "primevue": "^3.49.1",
 "primeicons": "^6.0.1",
 "primeflex": "^3.3.1",
  "vue": "^3.2.45"

### main.js
import { createApp } from 'vue'
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
const app = createApp(App)
app.use(PrimeVue, { ripple: true })
.use(ToastService)
.component('Toast', Toast)
.mount('#app')

### Page.vue
<template>
    <div class="card flex justify-content-center">
        <Toast />
        <Button label="Show" @click="show()"></Button>
    </div>
</template>
<script  >
export default {
    name: 'ToastMessage',
    methods: {
        show() {
            console.clear()
            console.log('toast')
            this.$toast.add({ severity: 'info', summary: 'Info', detail: 'Message Content', life: 3000 });
        },
    }
}
</script>

![Screenshot 2024-02-27 180740](https://github.com/primefaces/primevue/assets/8802790/bf8ed5ad-ce8e-4152-b6b4-3a57ae1a099f)

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-4ecohu?file=src%2Fmain.js,src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Thanks for the stackblitz demo. It seems to be working correctly.

**Comment by anilrepala505** [comment]
![image](https://github.com/primefaces/primevue/assets/8802790/0293fe69-dd92-460f-9481-a4155efba432)
