### ISSUE TITLE
Paid themes do not work since version 3.46

### ISSUE THREAD

**Issue by lpalacecr** [primefaces/primevue#5352]
### Describe the bug

Paid themes do not work since version 3.46

Since version 3.46 the themes and even primeblocks do not work, they are on version 3.49 and they still continue to fail, and it is not seen that they are making the corresponding fixes, between these versions very important fixes have been made that I have not been able to update. It is possible that at least version 3.46 will include the bugs fixed.

@cagataycivici @tugcekucukoglu 

Translated by Google translator.

Original text:

Desde la versión 3.46 los temas e incluisive primeblocks no funcionan, van por la versión 3.49 y aún siguen fallando, y no se ve que le esten haciendo los correspondientes arreglos, entre dichas versiones se han hecho arreglos muy importantes que no he podido actualizar. Es posible que al menos en la versión 3.46 incluyan los bugs correjidos.

@cagataycivici @tugcekucukoglu 

### Reproducer

https://codesandbox.io/p/devbox/blazing-river-5cvr6n?file=%2Fpackage.json%3A8%2C30

### PrimeVue version

3.47.2-3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Any Browser

### Steps to reproduce the behavior

1. In Apollo menu, go to UI KIT/input page. Any component wiht checkbox fail.
2. In Apollo menu, go to APPS/List. The application fail. This error occurs in version 3.46 too
3. In Apollo menu, go to APPS/Bloq/List. The application fail. This error occurs in version 3.46 too

### Expected behavior

The normal behavior of the component

**Comment by colinatwork** [comment]
Upping this. We're in the same boat and could just use some guidance on how to correct the issue.

**Comment by tugcekucukoglu** [comment]
Currently, I'm working on the templates and planning to release and add them to the store next week.

Thanks for your understanding.

**Comment by roos-robert** [comment]
> Currently, I'm working on the templates and planning to release and add them to the store next week.
> 
> Thanks for your understanding.

Thank you so much for the update @tugcekucukoglu - looking forward to it! 😊

**Comment by lpalacecr** [comment]
Excellent news, thank you very much...
I suggest that for the next updates you consider the topics, because the bank credit application that I have, it is extremely important that the components are as stable as possible, there is a lot of money that is controlled.

Thanks @tugcekucukoglu

Translated by Google Translate.

Original text:

Excelente noticia, muchas gracias...
Sugiero que para las próximas actualizaciones consideren los temas, porque la aplicación de crédito bancario que tengo, es sumamente importante que los componentes estén lo más estable posible, es mucho el dinero que se controla.

Gracias @tugcekucukoglu
