### ISSUE TITLE
MegaMenu: Declarative pass through not working

### ISSUE THREAD

**Issue by lancetharper** [primefaces/primevue#5353]
### Describe the bug

New declarative syntax not working with MegaMenu.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-upers1?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a MegaMenu
2. Add pt options with new declarative syntax
3. See pt options are not applied

Still works when using old syntax

### Expected behavior

pt options with new syntax are applied the same as the old

**Comment by jason-nabooki** [comment]
Same issue with `PanelMenu` I believe.

**Comment by tugcekucukoglu** [comment]
Could you try using the latest version? It seems to be working.
