### ISSUE TITLE
DataTable: Dynamic Custom Columns don't work as expected

### ISSUE THREAD

**Issue by PLamming87** [primefaces/primevue#5359]
### Describe the bug

When trying to add custom column wrappers to a datatable using the dynamic method, the columns do not render at all in the table.

![image](https://github.com/primefaces/primevue/assets/33496217/1b695731-f6d6-4d1d-a81a-1bb625b8e333)

### Reproducer

https://stackblitz.com/edit/dynamic-custom-col-issue?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Add custom column wrappers as dynamic columns to the Datatable using a v-for or other method.

### Expected behavior

The columns are rendered dynamically the same way basic Column components are, and the order of these components can be changed dynamically.

**Comment by TheZlodziej** [comment]
Also had this problem, the one way to temporary solve it would be to define column body component, e.g.
```
<Column
          v-for="(col, index) of selectedColumns"
          :key="`${col.field}_${index}`"
          :field="col.field"
          :header="col.header"
        >
          <template #body="slotProps">
            <component :is="col.bodyComponent" :value="slotProps.data[col.field]" />
          </template>
        </Column>
```

**Comment by PLamming87** [comment]
I appreciate the comment.  

Unfortunately this doesn't really work for our use case since we have custom filtering and edit inputs in each column as well.  While we could add templates and custom components for those as well, that then requires us to build out 3x the components.

I'll keep this work around in mind though if there is no other fix for this soon.

**Comment by PLamming87** [comment]
After working on this a bit more, I was able to find another partial workaround to at least display the column dynamically using a second wrapper component.

![image](https://github.com/primefaces/primevue/assets/33496217/86bb4882-fce8-4c75-a021-02eb3f7b2266)

However, this solution still does not allow us to change the order of the columns from a component outside of the datatable (like by changing the order in the tableColumns array)  or hide/show columns (they get pushed to the end of the datatable after toggling).  So this isn't really a full solution to our use case yet.

**Comment by tugcekucukoglu** [comment]
Please track https://github.com/primefaces/primevue/issues/4940
