### ISSUE TITLE
Column: Unable to wrap component

### ISSUE THREAD

**Issue by mike-r-morgan** [primefaces/primevue#5360]
### Describe the bug

The `DataTable` Component slots `Column` components used to map out the rows in a table. Here is an example of implementation:

```jsx
        <DataTable
          :value="products"
        >
          <Column field="name" header="name" />
	</DataTable>

```

Imported directly from PrimeVue, the column will work as intended, with the header set to “name” and the rows set to each `product` ’s `name` properties.

Now, let’s try to wrap the `Column` component in a very simple, barebones way:

```
<template>
  <Column :field="field" :header="header"/>
</template>

<script>
import Column from 'primevue/column';
export default {
  name: 'Column',
  components: {
    Column
  },
  props: {
    header: {
      type: String,
      required: true
    },
    field: {
      type: String,
      required: true
    }
  }
};
</script>
```

For some reason, this will not render in the DataTable. There are no warnings, errors, or any sort of hint thrown to the console. Wrapping the original PrimeVue Column component in a template element within the DataTable component slot does not break the implementation.

### Reproducer

https://stackblitz.com/edit/6rxmlz?file=src%2FApp.vue

### PrimeVue version

3.43.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Create a new custom component which wraps the `Column` component
2. slot that custom component into the Datatable, same way you would with the original

### Expected behavior

Though the component is wrapped, the rows should render in the DataTable.

**Comment by bsimons** [comment]
I encountered the same issue, with PrimeVue version **3.50.0**.

To not have to repeat the #sorticon template for each column:

```js
  ...
  <Column field="title" header="Title" sortable>
    <template #sorticon="scope">
      <CustomSortIcon :direction="scope.sortOrder" />
    </template>
  </Column>
  ...
```

Tried to use a wrapped component:

```js
<script setup lang="ts">
import Column from 'primevue/column'
import CustomSortIcon from '@/components/datatable/CustomSortIcon.vue'

const props = defineProps<{
  field: string
  header: string
  sortable: boolean
}>()
</script>

<template>
    <Column :field="field" :header="header" :sortable="sortable">
      <template #sorticon="scope">
            <CustomSortIcon :direction="scope.sortOrder" />
          </template>
    </Column>
</template>
```

And using it like this:

```js
  ...
  <CustomColumn field="title" header="Title" sortable /> 
  ...
```
This will not render in the DataTable without any warnings, errors, or hints.

**Comment by nikolay-kornev** [comment]
I am having the same issue. My custom component wrapping the library Column component will not render. When inspecting in Vue.js devtools, I don't see that columns data is injected.

**Comment by sj-dg** [comment]
We are also building our own component library using primevue where we encountered this same error.

We were able to successfully wrap Datatable component with our passthrough styles but we have to import Column directly from primevue. 

When we try to wrap Column or use `defineAsyncComponent()` it never gets rendered.

**Comment by ZiadJ** [comment]
Reusable custom columns as a component would really help keep things tidy with more complex data. I can only hope this will get the attention it deserves sooner than later.

**Comment by some-user123** [comment]
Just hit the same issue with primevue 4.0.0 :-(

Would love the remove redundant code...

**Comment by undefinedhuman** [comment]
Same for me (bump)

**Comment by lasficw** [comment]
Yep, same here

**Comment by rxy001** [comment]
The issue still exists in version 4.0.7.
