### ISSUE TITLE
Password: (accessiblility) cannot access toggle button using keyboard

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primevue#5362]
### Describe the bug

focus cannot be moved to Password's toggle button, then cannot toggle using keyboard

### Reproducer

https://primevue.org/password/#togglemask

### PrimeVue version

3.4.9.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. go to Password toggle show case : https://primevue.org/password/#togglemask
2. use tab to set focus on password field
3. hit tab several times, focus is never set on toggle password button

### Expected behavior

Toggle button should be able to be activated using keyboard.

**Comment by tugcekucukoglu** [comment]
We implemented the standards we mentioned [here](https://primevue.org/password/#accessibility). If you think differently, we can open a topic about this in discussions. I'm closing the issue for now.

**Comment by melloware** [comment]
@tugcekucukoglu its not quite accessibly though.  See: https://medium.com/kiipco/password-creation-3-ways-to-make-it-accessible-bc8f2b53b7ee#1751

PrimeReact PR: https://github.com/primefaces/primereact/pull/6052/files

**Comment by tugcekucukoglu** [comment]
I am going to start accessibility reviews on PrimeVue, PrimeReact, and PrimeNG in a few weeks. In the meantime, we can review it again. And, thanks for the article.
