### ISSUE TITLE
Carousel: not working properly with "unstyled"

### ISSUE THREAD

**Issue by Yves852** [primefaces/primevue#5375]
### Describe the bug

The carousel is no more working properly when Primevue is set to "unstyled: true".

With  `unstyled: false`
![image](https://github.com/primefaces/primevue/assets/86199387/79bdd6fc-1c20-4f3c-8a19-3dcec40d4566)
![image](https://github.com/primefaces/primevue/assets/86199387/14ed8dea-0349-41e5-8b58-50511a27e892)

With  `unstyled: true`
![image](https://github.com/primefaces/primevue/assets/86199387/d08dc9e9-e914-4148-b082-73bd946ad1a4)
![image](https://github.com/primefaces/primevue/assets/86199387/c8caeae2-fd8b-4d1d-86cb-be71afba06c2)

### Reproducer

https://stackblitz.com/~/github.com/Yves852/primevue-create-vue-typescript-issue-Carousel-unstyled

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chromium, Firefox

### Steps to reproduce the behavior

1. Add carousel component to a Vue3 project with a theme enabled (example aura-light-green)
2. In main.ts change the following

```diff
// [Imports...]
const app = createApp(App);

app.use(PrimeVue, 
 { 
-    unstyled: false 
+    unstyled: true 
 });

app.component('Carousel', Carousel);
app.mount('#app');
```

### Expected behavior

The carousel behave as expected as the component embed its logic independently of  the theme.

**Comment by tugcekucukoglu** [comment]
Carousel removes all styles as expected. You could take a look unstyled + tailwind usage from here: https://tailwind.primevue.org/
