### ISSUE TITLE
Editor: Deprecation warning in console, missing functionality with quill v2.0.0

### ISSUE THREAD

**Issue by luke-z** [primefaces/primevue#5381]
### Describe the bug

Using the Editor with quill version 1.3.7 results in a deprecation warning in the console (can also be observed on https://primevue.org/editor).
This deprecation warning is a known issue (https://github.com/vueup/vue-quill/issues/409, https://github.com/quilljs/quill/issues/3806) and should be resolved with quill version 2.

quill v2 is currently in release candidate 2, however it seems like the Editor is not fully compatible with this version, as using a pre-initialized v-model does not work with the Editor anymore.

I haven't tested everything, but it seems like the rest works as intended. The only thing not working smoothly is displaying the initial value.

on a side note: It seems like the Editor isn't auto imported with the nuxt-primevue module. I have to import it in the script section using ```import Editor from 'primevue/editor'```

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-kqkipp?file=app.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Brave

### Steps to reproduce the behavior

1. Install quill 2.0.0-rc.2
2. Add the Editor component
3. Use a ref with a pre-initialized value as the v-model target

### Expected behavior

The Editor should display and use the original v-model value as can be seen on the example page https://primevue.org/editor/#template

**Comment by tugcekucukoglu** [comment]
Since the editor uses a third-party library, it is not auto-imported. Can be used like this:

```
primevue: {
    components: {
        exclude: []
    }
}
```

I would like to point out that we currently only provide theme support to the Editor.

Thank you!

**Comment by luke-z** [comment]
Well I was just pointing out the fact that version 2.0.0-rc.2 will resolve a deprecation problem but also cause compatibility issues with the Primevue Editor :)
If the stable version of quill 2.0.0 is released and people install the newest version for usage with Primevue then it will eventually not work as intended, so you should keep it in mind for a future release :)

**Comment by GreenBattery** [comment]
@luke-z  do you have some workaround for displaying the initial value?

**Comment by luke-z** [comment]
@GreenBattery sorry, I only updated the package to v2 to see if the deprecation warning disappears.. When I saw that it isn't really compatible with Primevue at the moment, I reverted to 1.3.7 and posted this issue. So I haven't spent any time trying to find a workaround
