### ISSUE TITLE
implement boostrap in a primevue

### ISSUE THREAD

**Issue by xkiller838** [primefaces/primevue#5388]
### Describe the bug

Could you help me? I am using boostrap 5.2 in vue 3 and I am trying to follow the example that is in boostrap on the primevue documentation page but the examples are very simple buttons one table above but the modal one is not complete and the examples are very few, I would appreciate adding some more examples of how to implement boostrap in the modal and other components, not just buttons and a table, I tried to follow the same example using pt that is in the table in the Diaolog modal but it did not work for me

### Reproducer

PrimeVue 3 Issue Template

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

ES5

### Build / Runtime

Vite

### Browser(s)

implement boostrap in a primevue

### Steps to reproduce the behavior

Could you help me? I am using boostrap 5.2 in vue 3 and I am trying to follow the example that is in boostrap on the primevue documentation page but the examples are very simple buttons one table above but the modal one is not complete and the examples are very few, I would appreciate adding some more examples of how to implement boostrap in the modal and other components, not just buttons and a table, I tried to follow the same example using pt that is in the table in the Diaolog modal but it did not work for me

### Expected behavior

Could you help me? I am using boostrap 5.2 in vue 3 and I am trying to follow the example that is in boostrap on the primevue documentation page but the examples are very simple buttons one table above but the modal one is not complete and the examples are very few, I would appreciate adding some more examples of how to implement boostrap in the modal and other components, not just buttons and a table, I tried to follow the same example using pt that is in the table in the Diaolog modal but it did not work for me

**Comment by xkiller838** [comment]
![modalPrimeVue](https://github.com/primefaces/primevue/assets/33810066/d5453a9a-0521-402f-9603-1b5bd0a89ee2)

**Comment by xkiller838** [comment]
Could you tell me if this is the correct way to customize the Dialog component with boostrap?

**Comment by tugcekucukoglu** [comment]
You can ask your questions to the entire community on Discord or in discussions. The issue is being closed because it is not a core bug.
