### ISSUE TITLE
CascadeSelect: Editable prop feature.

### ISSUE THREAD

**Issue by ShreyasAch** [primefaces/primevue#5392]
### Describe the bug

Hi team, i am using CascadeSelect component and i would like to have a editable prop just like the Dropdown component has where user can type in the required options and the filtered results are displayed as options in the overlay just as the dropdown component. This would help users to focus on that one option they are looking for rather than going through series of options.

### Reproducer

https://primevue.org/cascadeselect/

### PrimeVue version

3.38.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

chrome

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
