### ISSUE TITLE
TreeSelect: slow with large datasets

### ISSUE THREAD

**Issue by DBolderman** [primefaces/primevue#5396]
### Describe the bug

When using the TreeSelect component with some very large datasets (1000+ items) the performance gets very slow. 
With the selectionMode set to ‘checkbox’ it renders even slower.

The part which causes the most delay is in the `TreeNode` component, where in the mounted hook the method `setAllNodesTabIndexes()` is called. This will fetch all available nodes and loops through all the nodes, and does that for every single node. E.g. when you have 1000 nodes, it will loop 1000 times through every node, doing 1000 times the exact same thing. Since only the root nodes are processed in the mounted hook this should be executed only once.

Also, I wonder if the lines 278-280 and 290 are really necessary, because the tabIndex is already set in the template code? 
It looks like the end result is the same? 

![image](https://github.com/primefaces/primevue/assets/159419754/d4ec0f3a-90aa-4379-aae0-b2e9813c323f)

If this could be fixed it would really help the user experience.

### Reproducer

https://stackblitz.com/edit/primevue-treeselect-slow-performance?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by DBolderman** [comment]
Today I noticed the following Verbose Message in Chrome DevTools when toggling a node with 1000 children (`TreeSelect` component with `checkbox` mode):

`[Violation] Forced reflow while executing JavaScript took 61ms`

Seems like some suboptimal DOM mutation vs. reading problem, which might be the cause of the slowness when rendering a very large dataset.

**Comment by danieldavies99** [comment]
+1 for this, I think that implementing virtual scroll in the tree select component would be a good solution, this has already been done for primeng https://github.com/primefaces/primeng/issues/13772

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/6196
