### ISSUE TITLE
Documentation: Left-hand menu vanishes under 1199px screen width

### ISSUE THREAD

**Issue by thepurpleblob** [primefaces/primevue#5398]
### Describe the bug

Web site...

@media screen and (max-width: 1199px) .layout-news-active .layout-sidebar {
    top: 0;
}

Sidebar containing all documentation links completely vanishes on narrow(ish) screens (under 1199px). This really threw me as I was a new user and had no idea that it should be there. I was on Discord asking "where is the documentation?". As the site seems pretty much useless without this menu, I'm not sure it's intentional that it vanishes on small screens.

### Reproducer

https://primevue.org/setup/

### PrimeVue version

n/a

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 122.0.6261.94 

### Steps to reproduce the behavior

Open the docs and go to the setup page (or any page with the left hand menus). Drag the browser window narrower. At some point the menus will all vanish. 

### Expected behavior

Either do not remove the menus or have a "hamburger" to get them back.

**Comment by thepurpleblob** [comment]
Wide(r) screen....

<img width="1188" alt="Screenshot 2024-03-09 at 14 29 30" src="https://github.com/primefaces/primevue/assets/664139/fbea69db-0933-4c0f-aee4-9a161adb5108">

Narrow screen (no menu)...

<img width="1150" alt="Screenshot 2024-03-09 at 14 29 44" src="https://github.com/primefaces/primevue/assets/664139/af9492c5-190d-4877-a754-d19f92bfc13a">

**Comment by tugcekucukoglu** [comment]
Thanks for the feedback. It is being closed because it is not a core bug.
