### ISSUE TITLE
Button's secondary background color is too bright

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#54]
It feels like the secondary buttons are too bright. Maybe it is just my monitor. I nearly can see the background. The secondary buttons look like just labels. Some of the users might think they are not buttons.
Any thoughts?

![image](https://user-images.githubusercontent.com/13495631/65701308-fef9ec80-e078-11e9-9561-1256542e2062.png)

Bellow are bootstrap buttons where the secondary one looks much darker:
![image](https://user-images.githubusercontent.com/13495631/65701779-cc9cbf00-e079-11e9-9cc7-26df3b987d02.png)
https://getbootstrap.com/docs/4.0/components/buttons/

This is `#ccc` comparing to the original version which looks better for me:
![image](https://user-images.githubusercontent.com/13495631/65702749-73ce2600-e07b-11e9-9b01-4b1b015567e4.png)

**Comment by cagataycivici** [comment]
You may override it in your application, it is more like a design decision. We'll keep it as it is on our side for now. Thank you for your feedback.

**Comment by denis-pujdak-adm-it** [comment]
> You may override it in your application
Yep, that's what I did in my project and it was just my opinion.
Thanks
