### ISSUE TITLE
[All components]: TypeScript emits are in an incompatible format with `defineEmits`

### ISSUE THREAD

**Issue by matthew-dean** [primefaces/primevue#5405]
### Describe the bug

If a developer is attempting to extend a PrimeVue component using TypeScript, they will immediately encounter a TypeScript error when attempting to use the emits for that component along with `defineEmits`. Other type exports don't have this issue.

(Note: a Stackblitz case is not needed since the bug is visible only when type-checked by TS.)

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-vfkvmz?file=src%2FApp.vue

### PrimeVue version

3.48.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Extend a component, e.g.:
```vue
<script setup lang="ts">
import Dialog, {
  type DialogProps,
  type DialogEmits,
  type DialogSlots
} from 'primevue/dialog'

defineProps<DialogProps>()
const emit = defineEmits<DialogEmits>()
defineSlots<DialogSlots>()
</script>

<template>
  <Dialog
    v-bind="$props"
    v-on="emit"
  >
    <slot />
  </Dialog>
</template>

```
Observe:
<img width="935" alt="Screenshot 2024-03-12 at 8 35 05 AM" src="https://github.com/primefaces/primevue/assets/414752/6bf89e3c-9fd5-4819-afa7-33fe4a713968">

### Expected behavior

TypeScript type exports should be compatible with Vue composition.

**Comment by slavco86** [comment]
I can confirm this is an issue for me too. In fact, also trying to extend Dialog and finding it extremely difficult to do. `DialogEmits` are incompatible so no TS support in handling component events for my HOC I'm trying to on top of Dialog. Because again, there is no way for me to change props default values of the Prime Dialog, which are not helpful in my use case and make the Dialog usage overly verbose, having to set same prop values everywhere.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your report! Fixed for v4.RC1. Please see;

https://www.dropbox.com/scl/fi/8eilnv6mp3jtcwg7boj7f/PrimeVue_TS_test.mov?rlkey=h5agqvral0nnxi6grei8qzeqh&st=ywkx1xyz&dl=0

Best Regards,

**Comment by Anubarak** [comment]
Is this really fixed?
When I do the following
```vue
const emit = defineEmits<DatePickerEmits>();
```
I receive the error
> [vite] Internal server error: [@vue/compiler-sfc] Unresolvable type: TSConditionalType
/home/robin/.../node_modules/@primevue/core/index.d.ts
5  |  declare type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never;
6  |  
7  |  export declare type EmitFn<Options = ObjectEmitsOptions, Event extends keyof Options = keyof Options> = Options extends Array<infer V>
   |                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8  |      ? (e: V, ...args: any[]) => void
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9  |      : {} extends Options
   |  ^^^^^^^^^^^^^^^^^^^^^^^^
10 |      ? (e: string, ...args: any[]) => void
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |      : UnionToIntersection<
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
12 |            {
   |  ^^^^^^^^^^^
13 |                [key in Event]: Options[key] extends (...args: infer Args) => any ? (e: key, ...args: Args) => void : (e: key, ...args: any[]) => void;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14 |            }[Event]
   |  ^^^^^^^^^^^^^^^^^^
15 |        >;
   |  ^^^^^^^
  Plugin: vite:vue
