### ISSUE TITLE
Image: Escape key does not close image preview

### ISSUE THREAD

**Issue by navedqb** [primefaces/primevue#5407]
### Describe the bug

Preview image does not close on escape after clicking on the image.

### Reproducer

https://primevue.org/image/#preview

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://primevue.org/image/#preview
2. Open preview image
3. Zoom in the image until zoom button is disabled.
4. Press Escape to close the preview

Preview does not close on escape

### Expected behavior

Preview image should close on escape

**Comment by tugcekucukoglu** [comment]
Which browser are you testing? Can not replicate the issue.

**Comment by navedqb** [comment]
Hi, tested it on chrome.

Have you clicked on the image after opening preview?
Escape does not work only then.

**Comment by tugcekucukoglu** [comment]
Thanks for the update. I've tested on Chrome, Firefox, and Safari. It seems to be working.

**Comment by ZiadJ** [comment]
@tugcekucukoglu I've been able to reproduce it. Have you zoomed in fully with the zoom icons before pressing Escape?

**Comment by ZiadJ** [comment]
@tugcekucukoglu I've been able to reproduce it in Firefox. Have you zoomed in fully with the zoom icons before pressing Escape?
