### ISSUE TITLE
OverlayPanel: Property visible does not exist on type

### ISSUE THREAD

**Issue by matttat** [primefaces/primevue#5409]
### Describe the bug

As indicated in the title, the property 'visible' does not exist on the type, despite being provided in the documentation.
https://primevue.org/overlaypanel/#api.overlaypanel.interfaces.OverlayPanelState

![image](https://github.com/primefaces/primevue/assets/25712270/90f32c59-f56e-4981-924b-94bb252b3c14)

### Reproducer

#

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by ZiadJ** [comment]
It definitely needs to be exposed in typescript. Right now, I'm having to cast it to `any` in order to be able to access it without getting typescript errors in the IDE.

**Comment by ZiadJ** [comment]
@tugcekucukoglu You just need to add `visible` as a boolean property in [OverlayPanel.d.ts](https://github.com/primefaces/primevue/blob/master/components/lib/overlaypanel/OverlayPanel.d.ts)

**Comment by tugcekucukoglu** [comment]
I understand. Unfortunately, `visible` is not a valid property of the OverlayPanel. Please see: https://github.com/primefaces/primevue/blob/master/components/lib/overlaypanel/BaseOverlayPanel.vue#L8
and
https://github.com/primefaces/primevue/blob/master/components/lib/overlaypanel/OverlayPanel.d.ts#L124

`visible` is just a key of the state object of OverlayPanel as described here: https://primevue.org/overlaypanel/#api.overlaypanel.interfaces.OverlayPanelState
