### ISSUE TITLE
Reimplement Virtual Scrolling

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#541]
VirtualScrolling experience should be similar to PrimeNG both from the perspective of developer and end user.

**Comment by LadislavBohm** [comment]
Can you also add few words to documentation about how to use this current/new version of virtual scroll?
What are those parameters returning from event and how to properly configure them? Especially since the example in showcase does not work, thank you.

**Comment by cagataycivici** [comment]
Covered in 692.

**Comment by richardmward** [comment]
Would love to see this on `Dropdown` as well
