### ISSUE TITLE
Tag | Message | ...: Multiple definitions of severity

### ISSUE THREAD

**Issue by joaomarcelofm** [primefaces/primevue#5413]
### Describe the bug

The severity prop has multiple definitions, for example [warn](https://primevue.org/message/#api.message.props.severity) and [warning](https://primevue.org/tag/#api.tag.props.severity) in the Message and Tag component respectively.

Another example is `danger` and `error`, which can be used interchangeably, but this may be expected. 🤔 

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-3u3yts?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Use `warn`/`warning` in different components
2. Severity breaks.

### Expected behavior

The ideal behavior was that even `severity` was typed, and all components that used it shared the same definition (at least for the PrimeVue-provided ones). This makes the usage of `severity` confusing and may lead to unexpected errors.

If the severity definition isn't shared across components, at least typing the expected value of each component.

**Comment by wijzijnweb** [comment]
"Another example is danger and error, which can be used interchangeably, but this may be expected. "

This is also very cumbersome.

```
    <InlineMessage v-if="currentStatus" :severity="currentStatus.severity" class="text-xs my-2">
        <strong class="font-bo ld">Huidige status: </strong>
            <span class="block sm:inline">{{ currentStatus.name }}</span>
        </InlineMessage>

        <div class="flex gap-2">
            <div v-for="status in statussen">
                <Button v-if="value !== status.value"
                        :severity="status.severity"
                        @click.prevent="$emit('clicked', status)">
                    {{ status.name }}
                </Button>
            </div>
        </div>
```
Now I need two severities to apply the right styling.
Might need a bit more consistency.
