### ISSUE TITLE
DataTable: Sort not working in some filter columns

### ISSUE THREAD

**Issue by robsen-git** [primefaces/primevue#5416]
### Describe the bug

Copied the DataTable example with basic filtering and added sortable attribute. Sorting then does not work for columns Country and Agent. Clicking on column header does nothing.

Might be related to https://github.com/primefaces/primevue/issues/3575

### Reproducer

https://stackblitz.com/edit/wgdafv?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

1. Click on "Agent" column header

### Expected behavior

Sortmode toggles, table gets sorted

**Comment by tugcekucukoglu** [comment]
As long as I see, only `filterField` property is used for these Columns. You could add `field` or `sortField` property for sort process as well.
