### ISSUE TITLE
Button: having a link in a Button component leads to incorrect tab behavior

### ISSUE THREAD

**Issue by eensander** [primefaces/primevue#5417]
### Describe the bug

When navigating Buttons that contain a link with the <kbd>TAB</kbd>-key, it is needed to press <kbd>TAB</kbd> twice before going to the next element. 

### Reproducer

https://primevue.org/button/#link

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox 123.0.1, Chrome 122.0

### Steps to reproduce the behavior

The example of a [Link in a Button](https://primevue.org/button/#link)  in the documentation suffices to reproduce the problem for me:
1. Click/focus on the first of the three buttons: "Link"
2. Press <kbd>TAB</kbd>: the second button is now focussed,
3. Press <kbd>TAB</kbd> again: the same button stays focussed, but seemingly with a slightly different border,
4. When pressing <kbd>TAB</kbd> again, it correctly focusses the next button
5. Now when pressing <kbd>TAB</kbd> again, the same problem occurs.

### Expected behavior

I expect one <kbd>TAB</kbd> to be sufficient to move to the next element

**Comment by tugcekucukoglu** [comment]
The demo will be fixed for the next version. Thank you.
