### ISSUE TITLE
FileUpload (mode="basic"): Could not override `chooseButtonLabel` & `chooseIcon` with passthrough

### ISSUE THREAD

**Issue by tommykamkcm** [primefaces/primevue#5420]
### Describe the bug

I'm using the tailwindcss Lara preset downloaded from the [builder page](https://tailwind.primevue.org/builder/).

After playing around with `Fileupload` component, I found that the style of the `Choose` button doesn't align with the `Button` component (icon should be stick to the left and label should fill in the rest of the space).

I tried to fix it by passing the following passthrough:
```
const fileUploadPreset: PassThrough<FileUploadPassThroughOptions> = {
    root: 'w-full', // OKAY
    chooseButton: 'w-full', // OKAY
    chooseIcon: 'grow-0', // NOT WORKING
    chooseButtonLabel: 'grow' // NOT WORKING
}
```

And I couldn't see my classes from the developer tool's element tab
<img width="872" alt="image" src="https://github.com/primefaces/primevue/assets/1722447/be6840cb-4780-48e8-8232-910349e55f21">

### Reproducer

N/A

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

```
<script setup>
const buttonPreset = {
  root: 'w-full',
};
const fileUploadPreset = {
  root: 'w-full', // OKAY
  chooseButton: 'w-full', // OKAY
  chooseIcon: 'grow-0', // NOT WORKING
  chooseButtonLabel: 'grow', // NOT WORKING
};
</script>

<template>
  <div class="flex flex-col justify-center items-center space-y-4">
    <FileUpload
      mode="basic"
      name="files[]"
      url="/api/upload"
      accept="image/*"
      :pt="fileUploadPreset"
    />
    <Button icon="pi pi-camera" label="Button" :pt="buttonPreset" />
  </div>
</template>
```

### Expected behavior

Classes can be appended to the `chooseButtonLabel` & `chooseIcon` element

**Comment by tugcekucukoglu** [comment]
In basic mode, you should use `uploadIcon` and `label` options. `chooseIcon` and `chooseButtonLabel` only can be used in advanced mode.
