### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by matthew-dean** [primefaces/primevue#5439]
### Describe the bug

Dropdown component's `optionsLabel` and `optionsValue` either don't work (or stopped working?) or somehow the options stop working in some scenarios?

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-i3tgzg?file=src%2FApp.vue

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

any

### Steps to reproduce the behavior

1. Open the StackBlitz
2. See that the dropdown does not properly bind the `optionsLabel` and `optionsValue` fields. Instead, it binds the whole object as the label.

<img width="302" alt="Screenshot 2024-03-18 at 6 35 45 PM" src="https://github.com/primefaces/primevue/assets/414752/7123fc13-9b57-452a-9eaf-6f9bb0c7622c">

### Expected behavior

I expect the label to be the label and the value to be the value. Honestly, I can't figure out how this component is intended to work, or why it isn't working here.

**Comment by ZiadJ** [comment]
You wrongly pluralized `option`. Remove the 's' and you're good to go.
