### ISSUE TITLE
Password: Input Attributes isn't taking in count input html attributes

### ISSUE THREAD

**Issue by FabianMontoya** [primefaces/primevue#5447]
### Describe the bug

I notice that `Password` component isn't taking in count the input html attributes that want, I noticed it exactly using the `autocomplete` attribute.

It works into `InputText` component, but into `Password` component isn't.

If you see into the example, the InputComponent the HTML generated is:

Vue
```html
<InputText
    id="email"
    v-model="inputValue"
    type="email"
    placeholder="Type your email"
    autocomplete="email"
  />
```

Result
```html
<input class="p-inputtext p-component" data-pc-name="inputtext" data-pc-section="root" id="email" type="email" placeholder="Type your email" autocomplete="email">
```

Note the `autocomplete` attribute is OK, but see into the Password:

Vue
```html
<Password
    v-model="passwordValue"
    toggle-mask
    :feedback="false"
    placeholder="Please type your password"
    autocomplete="current-password"
  />
```

Result
```html
<input class="p-inputtext p-component p-password-input" data-pc-name="inputtext" data-pc-section="root" type="password" aria-controls="pv_id_1_panel" aria-expanded="false" aria-haspopup="true" placeholder="Please type your password">
```

Look that the attribute `autocomplete` disappeared.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-zhq3yj

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 122.0.6261.129 (Official Build) (arm64)

### Steps to reproduce the behavior

Implement the [`Password` component](https://primevue.org/password/) and add any [HTML Input Attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

### Expected behavior

The final component generated take in count the other HTML Input Attributes set as the [`InputText` component](https://primevue.org/inputtext/) do.

**Comment by FabianMontoya** [comment]
> There is a way to add attribute with `pt` property
> 
> ```
>  <Password
>             :pt="{
>                 input: {
>                     root: {
>                         autocomplete: true
>                     }
>                 }
>             }"
>         />
> ```

I'll check it, but, my question is, It should be part of the input component?, that attributes should be inherited right?

**Comment by colinatwork** [comment]
I would agree with @FabianMontoya that while its great that you can add a passthrough, its a lot more code than what is required for InputText. And in most cases the browser will flag the Password component as needing an autocomplete attribute as it's type is set to "password". https://www.chromium.org/developers/design-documents/create-amazing-password-forms/

**Comment by SamuelvLopes** [comment]
to me works 

:pt="{
                                    input: {
                                        autocomplete: 'off'
                                    }
                                }"

**Comment by dominik-korsa** [comment]
Related: #3882
In that issue a cleaner solution is suggested (using `inputProps` instead of `pt`). I've also created a pull request to allow setting the `autocomplete` attribute directly.
