### ISSUE TITLE
Configure and validateOnBlur not working with primeVue

### ISSUE THREAD

**Issue by UXProv** [primefaces/primevue#5448]
### Describe the bug

I'm trying to trigger the errors display only after the field has been touched. From what I understood from the documentation I should use the configure({ validateOnBlur: true }) to achieve so. Also tried to set all the other properties to false, but unless I get the error message immediately or onSubmit (I wasn't able to reproduce my local behaviour on stackblitz, but event stackblitz is not working as expected)

### Reproducer

https://stackblitz.com/edit/vee-validate-v4-prime-vue-caaz2i?file=src%2FApp.vue

### PrimeVue version

3.29.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox 123

### Steps to reproduce the behavior

Try to use
configure({
  validateOnBlur: true,
  validateOnChange: false,
  validateOnInput: false,
  validateOnModelUpdate: false,
});
To have field errors of a form being displayed only after the field has been touched

### Expected behavior

The error should be set only after the field has been touched

**Comment by tugcekucukoglu** [comment]
You could use Discord or discussions for your questions. It is being closed because there is no core issue.
