### ISSUE TITLE
Disabled Button do not have the right cursor on hover  

### ISSUE THREAD

**Issue by zaynbsn** [primefaces/primevue#5450]
Button component with disabled props to true

The cursor when hovering the button should be "not-allowed" and it is "default" at the moment

That's all

**Comment by tugcekucukoglu** [comment]
It's a current design decision.

Thanks for interests,

**Comment by BenJackGill** [comment]
What is the rationale behind this design decision?

Having the extra visual feedback of a `not-allowed` cursor seems like nice way to indicate the button cannot be clicked.
