### ISSUE TITLE
Website / Documentation - Fix third-party dependencies documentation

### ISSUE THREAD

**Issue by Sub-Xaero** [primefaces/primevue#546]
Hope this is the right place to post this, couldn't find a dedicated repo for the PrimeVue website.

On the PrimeVue website, in the following section https://www.primefaces.org/primevue/showcase/#/setup, under Third-Party dependencies.

The "Component", and "Dependency" cells for "Toast and Terminal" are the wrong way around.

![screenshot-www primefaces org-2020 10 12-14_03_18](https://user-images.githubusercontent.com/9960703/95749665-d64c9100-0c93-11eb-98dc-912470bbd42c.png)

**Comment by cagataycivici** [comment]
Got it, thank you.
