### ISSUE TITLE
InputOtp: integerOnly prop

### ISSUE THREAD

**Issue by EfrenColinDC** [primefaces/primevue#5462]
### Describe the bug

When I set the **integerOnly** prop it does not work and does not allow me to enter any number.
In fact, the example page does not work either, I already tried in browsers like Firefox, Edge

` <InputOtp v-model="form.nip" integerOnly :length="6" />`

### Reproducer

x

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Edge, Firefox

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/5422
