### ISSUE TITLE
RadioButton: Selected item indicator is wrong positioned

### ISSUE THREAD

**Issue by FabianMontoya** [primefaces/primevue#5464]
### Describe the bug

The RadioButton, when I select an option, the style of the internal circle is wrong.

When I select an option, when I move fast the focus, the circle indicator keep in a wrong position, when I put again the hover, the position is okey again, I dont know if is a transition error or something else

Look the video:

https://github.com/primefaces/primevue/assets/37662924/974de49f-bd08-4260-a207-4aec878d3d65

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 122.0.6261.129 (Official Build) (arm64)

### Steps to reproduce the behavior

Implement `RadioButton` component:

![Screenshot 2024-03-22 at 19 15 27](https://github.com/primefaces/primevue/assets/37662924/d84bcd51-72c1-4437-b7a4-5b654c820eb5)

### Expected behavior

Centered component always:

![Screenshot 2024-03-22 at 19 15 54](https://github.com/primefaces/primevue/assets/37662924/9fa64c09-2fd1-4187-b843-aee1de450c97)

**Comment by ZiadJ** [comment]
Possible duplicate: https://github.com/primefaces/primevue/issues/5258

**Comment by tugcekucukoglu** [comment]
Yes, it is a duplicated issue. We could track 5258.

**Comment by OliverRC** [comment]
Are there any plans to resolve this?

On your own docs website with `Lara` theme
https://primevue.org/radiobutton/

<img width="151" height="168" alt="Image" src="https://github.com/user-attachments/assets/dcb6a161-305d-47e5-8cb9-3251fd8b09b8" />

<img width="361" height="109" alt="Image" src="https://github.com/user-attachments/assets/c2ef4712-ec91-47ba-a61e-3f08a03c5cc2" />

TailwindUI / TailwindPlus solves this elegantly
```
 <input id="push" type="radio" name="notification-method" class="relative size-4 appearance-none rounded-full border border-gray-300 bg-white before:absolute before:inset-1 before:rounded-full before:bg-white not-checked:before:hidden checked:border-indigo-600 checked:bg-indigo-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:border-gray-300 disabled:bg-gray-100 disabled:before:bg-gray-400 dark:border-white/10 dark:bg-white/5 dark:checked:border-indigo-500 dark:checked:bg-indigo-500 dark:focus-visible:outline-indigo-500 dark:disabled:border-white/5 dark:disabled:bg-white/10 dark:disabled:before:bg-white/20 forced-colors:appearance-auto forced-colors:before:hidden" />
      <label for="push" class="ml-3 block text-sm/6 font-medium text-gray-900 dark:text-white">Push notification</label>
```
