### ISSUE TITLE
Autocomplete [multiple]: remove option on select if already selected

### ISSUE THREAD

**Issue by bogdan0083** [primefaces/primevue#5466]
### Describe the bug

Right now if `multiple` is set to `true` and we select option which is already selected, I expect it to be removed from selected options.

### Reproducer

https://stackblitz.com/~/github.com/primefaces/primevue

### PrimeVue version

3.51.0-SNAPSHOT

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Open and initialize repro link (`npm install && npm run dev`)
3. open `/autocomplete/#multiple`
4. select multiple options.
5. Now try to select already selected options. Nothing happens: 

![Mar-23-2024 14-06-10](https://github.com/primefaces/primevue/assets/7077307/16b121d5-f32e-4626-9120-ab01e1699140)

### Expected behavior

Already selected options should be removed on select. Or at least we should have a special property to enable such behavior.

I can send a PR if you interested in fixing it.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

Thank you.
