### ISSUE TITLE
Component Name: Issue TreeTable

### ISSUE THREAD

**Issue by svmrw** [primefaces/primevue#5468]
### Describe the bug

In the TreeTable component, in the option using Template, an example with buttons is provided. However, it is not clear how to pass data to the button, for example id or any other arbitrary value from nodes.
Example:
`<Button @click="$router.push('/category/' + id)" type="button" icon="pi pi-pencil" rounded />`
How to send and receive id?

### Reproducer

https://primevue.org/treetable/#template

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by svmrw** [comment]
```js
<Column headerStyle="width: 10rem">
    <template #body="slotProps">
        <div class="flex flex-wrap gap-2">
            <Button @click="$router.push('/category/' + slotProps.node.id)" type="button" icon="pi pi-pencil" rounded />
        </div>
    </template>
</Column>
```

**Comment by tugcekucukoglu** [comment]
Thanks for the update!
