### ISSUE TITLE
Nuxt3 + Tailwind: Correct Way to Style Components?

### ISSUE THREAD

**Issue by phuze** [primefaces/primevue#5469]
### Describe the bug

I want to style a Primevue component within the scope of whatever parent/child component it's used in (not globally).

I have created a minimal reproduction of my project on [StackBlitz](https://stackblitz.com/edit/primevue-nuxt-issue-template-uskrzx?file=pages%2Ftest-1.vue,pages%2Ftest-2.vue,pages%2Ftest-3.vue,pages%2Ftest-4.vue) .

Here are the various test cases, and results -- the only one which seems to work as expected, is **Test 4**. This all seems a bit janky -- have I misconfigured my project? Is wrapping every class in `:deep()` really my only option?

**What is the correct way to style a Primevue component?**

🟦 **Test 1** - `<style scoped>`:

```vue
<script setup>
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Panel from 'primevue/panel'
</script>

<template>
  <Panel header="Transactions">
    <DataTable :value="[{amount: 100, type: 'debit'},{amount: 200, type: 'debit'}]">
      <Column field="type" header="Type" />
      <Column field="amount" header="Amount" />
    </DataTable>
  </Panel>
</template>

<style lang="scss" scoped>
.p-panel-content {
  @apply p-0
}
</style>
```
Result _(not working)_:
![image](https://github.com/primefaces/primevue/assets/9218035/3a9a12ea-ca62-47b2-91e7-cb85e2aa8474)

🟦 **Test 2** - `<style>`:
```vue
<style lang="scss">
.p-panel-content {
  @apply p-0
}
</style>
```
Result _(working, BUT this impacts all Primevue components globally -- no good)_:
![image](https://github.com/primefaces/primevue/assets/9218035/1467468a-2851-4001-865d-470370cea972)

🟦 **Test 3** - Passthrough:

```vue
<Panel header="Transactions"
       pt:header:class="p-0"
       pt:content:class="p-0">
    <DataTable :value="[{amount: 100, type: 'debit'},{amount: 200, type: 'debit'}]">
      <Column field="type" header="Type" />
      <Column field="amount" header="Amount" />
    </DataTable>
</Panel>
```

Result _(not working; causes base styling to disappear)_:
![image](https://github.com/primefaces/primevue/assets/9218035/5896b4fa-5b6d-485c-87cc-334e2c826d29)

🟦 **Test 4** - `<style scoped>` + `:deep()`:

```vue
<style lang="scss" scoped>
:deep(.p-panel-content) {
  @apply p-0
}
</style>
```

Result _(working as expected; style only applied to the specific component)_:
![image](https://github.com/primefaces/primevue/assets/9218035/6cdd7351-e1ee-494d-b69d-9cf40605c3ef)

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-uskrzx?file=pages%2Ftest-1.vue,pages%2Ftest-2.vue,pages%2Ftest-3.vue,pages%2Ftest-4.vue

### PrimeVue version

^3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by edimitchel** [comment]
It seems that using pt is overriding the whole bunch of utility classes used.

What is set before assigning new class via pt: `p-panel-content p-5 border border-t-0 last:rounded-br-lg last:rounded-bl-lg border-surface-200 dark:border-surface-700 bg-surface-0 dark:bg-surface-900 text-surface-700 dark:text-surface-0/80`

After applying `p-0`: `p-panel-content p-0`

This behavior is probably expected as pt is making accessible nested styles for restyling them, but in a sense, I'm surprised that it's fully rewritten them.

Just for information, you can pass class to pt without the `:class` suffix: `pt:content="p-0"`

**Comment by phuze** [comment]
I've realized the PrimeVue documentation has conflicting information related to Nuxt configurations. In some cases, it reflects that options need to be nested within an `options` property, and in other cases, it doesnt.

I incorrectly referenced the second example, since it mentioned Tailwind immediately above it.

![image](https://github.com/primefaces/primevue/assets/9218035/84aa1ccf-508a-4f6f-b401-2811fba5ad6c)

In my case, I was doing this:

```js
// bad
primevue: {
  unstyled: true,
  ripple: true,
  importPT: { from: path.resolve(__dirname, './presets/lara/') }
}
```

Looking through the PrimeVue code however, I can see that the `options` property is required:

```js
// good
primevue: {
  options: {
    unstyled: true,
    ripple: true,
  },
  importPT: { from: path.resolve(__dirname, './presets/lara/') }
}
```

Moreover, I discovered there are additional configuration options for controlling how pass-through works.
To keep existing utility classes, you need to set `mergeSections` and `mergeProps`.

```js
primevue: {
  options: {
    unstyled: false,
    ripple: true,
    ptOptions: {
      mergeSections: true,
      mergeProps: true,
    }
  },
  importPT: { as: 'Lara', from: '~/assets/presets/lara' },
  components: { include: '*' },
  directives: { include: '*' },
}
```

Even with pass-through working, I've realized its limited.
For example, you cant style this element path `thead > tr > th` for a `<DataTable>` using pass-through properties.

In truth, this entire pass-through mechanism seems cumbersome and not worth the effort, or the mess it makes of your code. IMHO, the best way to style PrimeVue components is to simply open DevTools Inspector, find the related class structure, and apply your styles with `:deep()`:

```vue
<style lang="scss" scoped>
:deep() {
  .p-panel-content {
    @apply pt-0 pr-0 pb-2 pl-0
  }
  .p-datatable-thead tr > th {
    @apply py-1 px-4
  }
  .p-datatable-tbody tr:last-child > td {
    @apply border-none
  }
}
</style>
```
