### ISSUE TITLE
Using InputNumber inside DataTable cell doesn't change v-model if you press Enter or Tab

### ISSUE THREAD

**Issue by zukka77** [primefaces/primevue#547]
When you "cell-edit" an InputNumber and you press Enter or Tab, the cells switch to non-edit-mode, but value in the InputNumber reverts back to the old value:
```html
<DataTable :value="values" :autoLayout="true" editMode="cell" class="editable-cells-table">
            <Column header="Code" field="code" />
            <Column header="Price" field="price"/>
            <Column header="Quantity" field="quantity">
            <template #editor="slotProps">           
                <InputNumber v-model="slotProps.data[slotProps.column.field]" :min="0"/>
            </template>
            </Column>
</DataTable>
```
It works if you change the value via arrows key or if you click outside the DataTable.
primevue@2.1.0
vue@2.6.12

**Comment by mdartic** [comment]
Same for me, we use the primevue@2.2.0, and encounter this bug.

The fix proposed in https://github.com/primefaces/primevue/pull/592/commits/1b109c35390e562b6bf8badbf6740fe45aa22e81 solved the bug for us.

We use it as a patch for now.

@cagataycivici do you want we propose a PR for the 2.x branch ?

**Comment by mertsincan** [comment]
Hi all,

I've made a few improvements with the InputNumber. I'll add them and the 'input' event support to the 2.x version.

Best Regards,

**Comment by mdartic** [comment]
@mertsincan maybe you already answer somewhere, but could you precise what's the future of the 2.x branch ?

We love it, and we think to upgrade to the 3.x branch (and Vue 3 too), but we don't know when.

We encounter some bugs on the 2.x branch, and we have to tell you them (we have some fixs too, but not already pushed on github).

Could we still propose PRs for the 2.x branch ?

**Comment by cagataycivici** [comment]
@mdartic We have an active 2.x branch, when a version for v3 gets released, a v2 counterpart will follow in a day or two. Feel free to create issues whether they apply to both v2-v3 or just one of them.

@mertsincan Let's discuss this one today as I'd like to release v2 by tomorrow.

**Comment by mertsincan** [comment]
Hi,

Fixed with https://github.com/primefaces/primevue/issues/705 and https://github.com/primefaces/primevue/issues/676

Best Regards,
