### ISSUE TITLE
Dropdown Pass Through: item

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5470]
### Describe the bug

In "item" I want in the function "getClass" to get the data of that option but right now there is no way to customize each option.

:pt="{
input: ({ props, state }) => ({
	'aria-labelledby': `titulo-${id}`,
	'aria-describedby': `error-${id} info-${id}`,
	'aria-required': ....
}),
item: ({ instance, state, props, global, context}) => ({
	class: 'flex align-items-center	' + getClass(context),
	'aria-setsize': paginacion.numeroRegistros ?? opcionesCalculadas?.length
}),
}"

### Reproducer

.

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

**Comment by JoseAntonioNavasSolutia** [comment]
This example: https://stackblitz.com/edit/primevue-create-vue-issue-template-dbydc3?file=src%2FApp.vue

**Comment by tugcekucukoglu** [comment]
`context.option` will be available for the next version.

**Comment by Antal1609** [comment]
This will also be useful for the multi-select pass trough options like [token, tokenLabel and removeTokenIcon](https://primevue.org/multiselect/).

Will this be considered as well?
