### ISSUE TITLE
InputNumber & InputOpt, no entries or undefined

### ISSUE THREAD

**Issue by VapoFred78** [primefaces/primevue#5472]
### Describe the bug

Hello !
I'm having a problem with the InputNumber and InputOpt intergerOnly components, I'm using a keyboard that doesn't have a numeric keypad so I have to press shift to use the numbers on the keyboard, but it seems that the inputs are blocked if you press anything other than a numeric character.

### Reproducer

.

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

import and use a component InputNumber and use shift + a number on the keyboard.

### Expected behavior

no entries or undefined

**Comment by Yirou** [comment]
I have same issue. Any solutions? For now, I am interpreting keyboard code but it's a temporary solution.

**Comment by tugcekucukoglu** [comment]
https://github.com/primefaces/primevue/issues/5422

Fixed for the next version.

Thanks,
