### ISSUE TITLE
Nuxt3 + Tailwind: Ripple does not work

### ISSUE THREAD

**Issue by phuze** [primefaces/primevue#5475]
### Describe the bug

Ripple doesn't work. Refer to the demonstration project on [StackBlitz](https://stackblitz.com/edit/primevue-nuxt-issue-template-uuiuuw?file=app.vue).

```js
// nuxt.config.js

primevue: {
    unstyled: true,
    ripple: true,
    importPT: { as: 'Lara', from: '~/presets/lara' },
    components: { include: '*' },
    directives: { include: '*' },
}
```

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-uuiuuw?file=app.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Correct implementation of ripple should be like this:

```
primevue: {
    options: {
        ripple: true
    }
}
```
