### ISSUE TITLE
Checkbox: new `indeterminate` state

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue#5479]
Affected components;

- [x] Tree
- [x] TreeTable

**Comment by Tarabass** [comment]
How can this be a alternative for tristate checkbox? Ones checked it can only be unchecked, the third state is not working at all.

A tristate checkbox is a very common component which should be able to let the user select true, false or null..

**Comment by Mettbrot** [comment]
Any news on this? indeterminate is only the initial state. Currently there is no third state available.
