### ISSUE TITLE
DataTable: Checkbox in a row behind the header is clickable

### ISSUE THREAD

**Issue by J43fura** [primefaces/primevue#5483]
### Describe the bug

Checkbox in a row behind the header is clickable

### Reproducer

https://stackblitz.com/edit/lkxqdj?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

Checkbox in a row behind the header is clickable.
- ![image](https://github.com/primefaces/primevue/assets/73950268/80583cad-e045-4942-9ce4-9bbe86d0b65c)
- ![image](https://github.com/primefaces/primevue/assets/73950268/1eaf5384-8f13-4534-b485-aee257929849)

### Expected behavior

Checkbox in a row behind the header is not supposed to be clickable.

**Comment by J43fura** [comment]
Problem lies here:
- ![image](https://github.com/primefaces/primevue/assets/73950268/8c28e0bb-338b-42a8-b9d8-4d893991e364)

My current solution is making the `z-index: 2` of `.p-datatable-scrollable-table > .p-datatable-thead;`
```css
 .p-datatable-scrollable-table > .p-datatable-thead {
  top: 0;
  z-index: 2;
}
```

**Comment by tugcekucukoglu** [comment]
Thanks for the demo. I've cloned it but header radiobutton is not rendered in the dom.
<img width="899" alt="Screenshot 2024-03-28 at 09 34 41" src="https://github.com/primefaces/primevue/assets/32294991/b39dd1d9-e352-435b-8513-bb0d057b62f1">

How can we replicate the issue?

**Comment by tugcekucukoglu** [comment]
Thanks for the updates. DataTable uses RadioButton component and its styles. There is another solution for this.

```
<Column
        selectionMode="single"
        :pt="{
          rowradiobutton: {
            root: {
              style: { 'z-index': 0 },
            },
          },
        }"
      ></Column>
```
