### ISSUE TITLE
TreeTable: Documentation for Column > Slots > Body Is Incorrect

### ISSUE THREAD

**Issue by incutonez** [primefaces/primevue#5485]
### Describe the bug

According to the docs for [TreeTable's body slot](https://primevue.org/treetable/#api.column.slots.body), it should have more properties in it, but when we inspect the slotProps, we see that it only has `node` and `column`.

### Reproducer

https://stackblitz.com/edit/3tv8sw?file=src%2Fservice%2FNodeService.js,src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open Fiddle
2. Open debugger
3. Notice debugger prints `undefined` when trying to access `slotProps.data` and `slotProps.field`

### Expected behavior

I believe this documentation was copied from the DataTable, so either the docs need to be updated to reflect that TreeTable is a bit different and does not include those properties, or the internal code needs to expose those properties on the slot's props.  The latter would be desired, but I understand if it's not feasible.

**Comment by tugcekucukoglu** [comment]
TreeTable uses `node` option for `body` slot and is documented here https://primevue.org/treetable/#api.column.slots.body

**Comment by incutonez** [comment]
@tugcekucukoglu Furthermore, if you inspect the `node` object, it doesn't have the properties that are supposed to be present in `TreeNode`, unless that's not what `node` represents?  Kinda hard when the docs use a lot of `any` instead of some generic type.
