### ISSUE TITLE
Autocomplete: forceSelection true causes the change event to be emitted twice when an option from the list is selected

### ISSUE THREAD

**Issue by TravisAlexandra** [primefaces/primevue#5489]
### Describe the bug

For Autocomplete component, `:force-selection=true` causes the `@change` event to be triggered twice when an option from the list is selected, the first time with value `null` and the second time with the selected value. 

This behavior causes issues when using a watcher based on the values ​​stored for that autocomplete.

### Reproducer

https://stackblitz.com/edit/mcve4z?file=src%2FApp.vue

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Open the link for reproducer
2. Open inspect mode > Console
3. Search for 's'
4. Select an option from the list
5. Check the console: the console was triggered twice when selection the value, with values 'null' and '

**Comment by tugcekucukoglu** [comment]
Thanks for the demo. It seems the demo uses version 3.50.0 and cannot replicate the issue with the latest version. Could you try to use the latest version?

**Comment by TravisAlexandra** [comment]
I reopened the issue: https://github.com/primefaces/primevue/issues/5857
