### ISSUE TITLE
Declare events in "emits" section of every component

### ISSUE THREAD

**Issue by LadislavBohm** [primefaces/primevue#549]
Currently when using primevue in Vue 3 it gives you a warning every time an event is emitted because it's not declared in 'emits' section.

![image](https://user-images.githubusercontent.com/4920886/95840052-fe93c880-0d43-11eb-9789-7cc554d8e672.png)

It would be nice to have those events declared at least using the array syntax:

```
emits: ['row-select', 'row-unselected', ...]
```

**Comment by cagataycivici** [comment]
We'll do it, thank you.
