### ISSUE TITLE
MultiSelect: Can deselect disabled options

### ISSUE THREAD

**Issue by J43fura** [primefaces/primevue#5490]
### Describe the bug

MultiSelect: Can deselect disabled options on clicking select-all-checkbox 

### Reproducer

https://stackblitz.com/edit/rgyeif?file=src%2FApp.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Have a MultiSelect with a default selected option but also is disabled
2. Click on select-all-checkbox

### Expected behavior

Clicking on select-all-checkbox should not deselect disabled options

**Comment by tugcekucukoglu** [comment]
Since only valid options can be selected, select-all will deselect invalid options. You can make a selection programmatically with the `selectall-change` event.
