### ISSUE TITLE
Button: Not styled in Brave Browser

### ISSUE THREAD

**Issue by don-yan** [primefaces/primevue#5492]
### Describe the bug

Button styles are not loading in the Brave Browser on MacOS

At first I thought that it was my implementation, but they are also broken on the Primevue website

https://primevue.org/

![E8F9A0F5-0F32-42BF-8C8D-DBE696F675BD](https://github.com/primefaces/primevue/assets/366698/24d262f0-6e8c-4e77-b2e7-1e45cfcb8b4b)

### Reproducer

N/A

### PrimeVue version

3.38.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Brave 1.13.86

### Steps to reproduce the behavior

Open site in Brave Browser.

### Expected behavior

The styles should load like they do in every other browser that I've tested.

**Comment by runyasak** [comment]
Hi, @don-yan.
I've tested on my Brave browser with version 1.51.110 on Mac, arm64.

Here is my screenshot:

<img width="1552" alt="image" src="https://github.com/primefaces/primevue/assets/6861191/110f91c3-0fff-4f41-a267-802f0f2cf271">

Would you mind clearing your browser cache and refreshing?
Alternatively, consider updating your browser to the latest version, which is currently 1.64.113.

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. Could you try to use the latest version of Brave and clear the cache?
