### ISSUE TITLE
PrimeVue 3.50.0 DataTable.d.ts => rowClass?: (data: any) => object | undefined;

### ISSUE THREAD

**Issue by ajon88** [primefaces/primevue#5498]
### Describe the bug

3.49.1 => rowClass?: (data: any) => object | string | undefined;
TypeScript threw an error in version 3.50.0.
 The expected type comes from property 'rowClass' which is declared here on type 'DataTableProps & VNodeProps & AllowedComponentProps & ComponentCustomProps & Record<string, unknown>'

### Reproducer

npx vue-tsc --noEmit --skipLibCheck

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome/Edge

### Steps to reproduce the behavior

npx vue-tsc --noEmit --skipLibCheck

### Expected behavior

no such error

**Comment by ZiadJ** [comment]
Duplicate: https://github.com/primefaces/primevue/pull/5414

**Comment by TQ-Benji** [comment]
Also getting the error from typescript when setting rowClass to a function

Type '(data: Item) => string' is not assignable to type '(data: any) => object | undefined'.ts-plugin(2322)
DataTable.d.ts(1070, 5): The expected type comes from property 'rowClass' which is declared here on type 'DataTableProps & VNodeProps & AllowedComponentProps & ComponentCustomProps & Record<string, unknown>'
(property) DataTableProps.rowClass?: ((data: any) => object | undefined) | undefined
A function that takes the row data as a parameter and returns a string to apply a particular class for the row.

**Comment by slavco86** [comment]
I have the same issue
Looking into [DataTable.d.ts](https://github.com/primefaces/primevue/blob/6615f31d8a96512a40c9cc4b9f512125e741fcd0/components/lib/datatable/DataTable.d.ts#L1070)
```
rowClass?: (data: any) => object | undefined;
```

Isn't particularly helpful as it doesn't provide any idea of what shape `object` should the function return 🤔
