### ISSUE TITLE
PrimeVue 4.0.0-beta.1 still import styles of removed components

### ISSUE THREAD

**Issue by ws-rush** [primefaces/primevue#5510]
### Describe the bug

PrimeVue 4.0.0-beta.1 still import styles of removed components even I exclude them

[5:18:10 PM]  WARN  "primevue/tristatecheckbox/style" is imported by "virtual:#primevue-style", but could not be resolved – treating it as an external dependency.

[5:18:10 PM]  WARN  "primevue/dataviewlayoutoptions/style" is imported by "virtual:#primevue-style", but could not be resolved – treating it as an external dependency.

[nitro 5:18:13 PM] ✔ Nuxt Nitro server built in 5362 ms

[5:18:13 PM]  ERROR  [worker reload] [worker init] Cannot find module '/home/rush/Projects/Saraf/node_modules/primevue/tristatecheckbox/style' imported from /home/rush/Projects/Saraf/.nuxt/dev/index.mjs
Did you mean to import primevue@3.49.1_vue@3.4.21/node_modules/primevue/tristatecheckbox/style/tristatecheckboxstyle.cjs.js?

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-viwscv

### PrimeVue version

4.0.0-beta.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by edimitchel** [comment]
This is probably linked to the not updated nuxt plugin (nuxt-primevue) which relies on removed/renamed parts of the new beta version..

**Comment by tattyd** [comment]
I'm encountering this as well - is there a beta version of the `nuxt-primeview` plugin we can upgrade to?

**Comment by edimitchel** [comment]
They announced a compatible version for next week

**Comment by tugcekucukoglu** [comment]
Thanks for the updates. It will be fixed when the new version of `nuxt-primevue` module is released.

**Comment by robert-hoffmann** [comment]
This is still happening with PrimeVue 4.1.0

` WARN  "primevue/button/style" is imported by "virtual:#primevue-style", but could not be resolved – treating it as an external dependency.  `
` ERROR  [worker reload] [worker init] Cannot find package 'primevue' imported from D:\..redacted..\.nuxt\dev\index.mjs    `

This is on Nuxt 3, using the V4 compatibility mode, and running in a cloudflare workers environement (using the Material theme, and definePreset() in the nuxt config)
