### ISSUE TITLE
DataTable: Custom component not rendering

### ISSUE THREAD

**Issue by nicolasr2310** [primefaces/primevue#5516]
### Describe the bug

Wrapping the DataTable component like described on the documentation : https://tailwind.primevue.org/guides/building-ui-library/ doesn't work : the component doesn't render at all and no errors are shown.

### Reproducer

https://codesandbox.io/p/devbox/agitated-danny-hjycnj

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

In the example as you can see the DataTable is shown if it comes directly from primevue library, but if it's the custom one wrapping it, it does not display the data even though the table tag is created.

### Expected behavior

The component rendered correctly with the data inside

**Comment by tugcekucukoglu** [comment]
Please track https://github.com/primefaces/primevue/issues/4940
