### ISSUE TITLE
SplitButton: Pass Through Options button, menuButton und menu do not work

### ISSUE THREAD

**Issue by ibrdavid** [primefaces/primevue#5517]
### Describe the bug

My goal is to influence the button inside the SplitButton-component. therefore i am using the pass trough option via :pt={...}. I tried the options root, button, menuButton and menu but only root worked. In a simple case, i just want to set some style-definitions like this:

```
<SplitButton label="Save" @click="save" :model="items" :pt="{
    root: {
      style: {
        padding: '10px',
        'background-color': 'yellow',
       },
    },
    button: {
      style: {
        padding: '15px',
        'background-color': 'blue',
      },
    },
  }"
/>
```

the styling of the root-element works, but the button-element is not changing at all. it can easily be checked by inspecting the element via devtools (F12). I added this example as a stackblitz-fork.

### Reproducer

https://stackblitz.com/edit/5ps6zx-432t4s?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox, Chrome, Edge

### Expected behavior

The expected behaviour would be, that the button-Element of the SplitButton receives the setting for padding and backgroud-color, that were defined in the pt-option.

**Comment by tugcekucukoglu** [comment]
SplitButton uses Button component internally. So the pt implementation should be like this:

```
<SplitButton :pt="{
   button: {
        root: {
            style: ...
        }
   }
}"
```
