### ISSUE TITLE
ScrollPanel: Errors in moveBar() when xBar and yBar attributes don't exist

### ISSUE THREAD

**Issue by autoboxer** [primefaces/primevue#5518]
### Describe the bug

In some cases, the requestAnimationFrame() that sets attributes for `this.$refs.xBar` and this.$refs.yBar` throw errors due to neither `xBar` nor `yBar` existing on `this.$refs`.

#### screenshot

<img width="720" alt="ScrollPanel Error" src="https://github.com/primefaces/primevue/assets/2757601/8648bfb8-82c3-454a-83e5-003322fc30fc">

### Reproducer

none - PR incoming though

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 123.0.6312.87

### Steps to reproduce the behavior

This doesn't seem to happen in all cases and is hard to reproduce, but in my case it's due to a scrollbar which doesn't need to be rendered, being placed in a Panel which takes up 1/3 of the screen width.  When it does occur, it happens on load, before the ScrollPanel is interacted with in any way.

### Expected behavior

No errors are thrown due to the ScrollPanel component loading.

**Comment by tugcekucukoglu** [comment]
How can we replicate this issue? Could you share a stackblitz link?

**Comment by autoboxer** [comment]
although it's happening consistently in my app, I haven't been able to easily replicate the issue.  I'll hopefully free up a bit next week and can try to put something together, but may not be able to showcase the same behavior in a sandbox environment.  I was hoping the error showing that there are cases where `xBar` and `yBar` are not set as expected when the `requestAnimationFrame` is run would be adequate, but I completely understand if it's not.
