### ISSUE TITLE
Column 'field' prop type allows just string

### ISSUE THREAD

**Issue by LadislavBohm** [primefaces/primevue#552]
According to documentation specifying column field should support this:

"Property name or a getter function of a row data."

However in prop types of Column component it only allows String. Getter function works but throws a lot of warnings:
![image](https://user-images.githubusercontent.com/4920886/95887680-708a0300-0d80-11eb-8069-5fce682f13c2.png)

**Comment by LadislavBohm** [comment]
I could submit PR some components I'm currently using if interested. Because when you click through an app I sometimes get around 100 warnings because of this and it slows down browser.
I know it's just warning and I can turn it off but then I lose other meaningful warnings.

**Comment by tugcekucukoglu** [comment]
Hi,

**Comment by tugcekucukoglu** [comment]
Hi,
I couldn't replicate it. Could you please attach a codesandbox link or your repo?

**Comment by cagataycivici** [comment]
There seems to be a doc issue, currently functions are not supported, docs are fixed now.
