### ISSUE TITLE
TreeTable: Column Group

### ISSUE THREAD

**Issue by ShreyasAch** [primefaces/primevue#5527]
### Describe the bug

Hi team, i am using TreeTable component to display my data, but i want to group few columns like the column group component present in datatable but unfortunately i couldn't find any documentation regarding column grouping in the treetable component. Addition of column group component into tree table will be the great add-on for this component.

### Reproducer

https://primevue.org/treetable/

### PrimeVue version

3.41.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

chrome

**Comment by vinodkola1337** [comment]
+1 

Would love this feature

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by DmitrySkibitsky** [comment]
+1. I encountered this problem. I needed to display summary data in TreeTable, but ColumnGroup and Row components do not work in the footer.
