### ISSUE TITLE
InputNumber PrimeVue v4: passthrough for "input" ignored

### ISSUE THREAD

**Issue by micvm** [primefaces/primevue#5528]
### Describe the bug

In primevue version 4, passthrough attributes for the `input` segment (e.g. `class` or `style`) are ignored even if the documentation says this is supported. For `root` it works as expected.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-rrhafz?file=src%2FApp.vue

### PrimeVue version

4.0.0-beta.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Steps to reproduce the behavior

1. Include in your template  an InputNumber component
2. Set, for example, `:pt="{ input: { style: 'width: 4rem', class: 'text-center' } }"`
3. The resulting DOM for the input of `InputNumber` does not contain any of the listed styles or classes.
4. Do the same for `root` instead of `input` and you will see the `div` of the component having them.

### Expected behavior

The resulting DOM should have under `style` and `class` the data inserted as passthrough option.

**Comment by SagewLivingstone** [comment]
Just ran into this issue myself, I had to do the following:

`:pt="{ input: { root: { style: 'width: 4rem', class: 'text-center' } } }"`

The documentation is *not* clear about this at all. I only figured this out by looking at how the presets were styling the component :/

**Comment by micvm** [comment]
Thanks for sharing this. Especially because it worked in the previous version and the documentation at https://v4.primevue.org/inputnumber/ seems to be the same as for v3.

**Comment by vzakharov** [comment]
> Just ran into this issue myself, I had to do the following:
> 
> `:pt="{ input: { root: { style: 'width: 4rem', class: 'text-center' } } }"`
> 
> The documentation is _not_ clear about this at all. I only figured this out by looking at how the presets were styling the component :/

will it work with the pt:input:.... syntax? Doesn't seem to.

**Comment by vzakharov** [comment]
Gosh, PrimeVue team seems to be just _fond_ of adding breaking changes without even any documentation about them.

**Comment by Tarabass** [comment]
> Thanks for sharing this. Especially because it worked in the previous version and the documentation at https://v4.primevue.org/inputnumber/ seems to be the same as for v3.

Doesn't work in v3 neither..

**Comment by vpuentem** [comment]
Having the same issue, the docs are not clear about this. Followed the component and passthrogh sections and couldn't make it work

https://primevue.org/passthrough/
https://primevue.org/inputnumber/#pt.doc.inputnumber

**Comment by CalebMills** [comment]
> Having the same issue, the docs are not clear about this. Followed the component and passthrogh sections and couldn't make it work
> 
> https://primevue.org/passthrough/ https://primevue.org/inputnumber/#pt.doc.inputnumber

So the docs are pretty unclear, but the "pcInput" option from InputNumber is giving you access to the InputText pass through props, so you additionally have to chain on what InputText passthrough option you want to target.

If you look at the InputNumber pass through options in the V4 docs you can see the description column says "Used to pass attributes to the InputText component.". This means you have to go reference the InputText pass through options and chain on which InputText option you are trying to target.

Here's an example where I'm additionally targeting the "root" PassThrough option of InputText.
`<InputNumber
        v-model="value1"
        inputId="integeronly"
        fluid
        pt:pcInput:root="test" // This works
        :pt="{ // This also works
          pcInput: {
            root: 'test'
          },
        }"
    />`
    
    I dug through the code behind the scenes for this and the InputNumber component uses the InputText component within itself and the pcInput PassThrough prop for InputNumber is an object that gets passed through to the InputText :pt props. The docs should make this a lot more clear and either explicitly state what passthrough options pcInput accepts as an additional object in the description. Or link to the InputText passthrough options in the description.

**Comment by davidjmstewart** [comment]
@SagewLivingstone's suggestion above was my solution. Here is how I made the background of the component red, for example:

```ts
  <InputNumber
    @input="preventFocusOnMobile"
    input-id="blue-input"
    v-model="blue"
    class="w-1/5"
    :min="0"
    :max="255"
    showButtons
    buttonLayout="vertical"
    :allow-empty="false"
    :pt="{
      incrementButton: {
        class:
          'border-2 hover:bg-blue-200 dark:hover:bg-blue-400 h-10 active:bg-blue-500 dark:active:bg-blue-500',
      },
      decrementButton: {
        class:
          'border-2 hover:bg-blue-200 dark:hover:bg-blue-400 h-10 active:bg-blue-500 dark:active:bg-blue-500',
      },
      pcInputText: {
        root: {
          class: 'bg-red-500',
        },
      },
    }"
  />
```
Which resulted in:
![image](https://github.com/user-attachments/assets/ea1afe46-3884-4cdd-9460-5bd0bf0016c9)

**Comment by tugcekucukoglu** [comment]
Thanks for the updates. It seems the problem is solved.
