### ISSUE TITLE
DataTable rendering infinite loop if you sort and group the same column

### ISSUE THREAD

**Issue by OliverRC** [primefaces/primevue#5539]
### Describe the bug

If you sort and group on the same column it seems to explode the renderer. It goes into some find of infinite loop.

e.g
```
    <DataTable
      v-model:filters="filters"
      :value="customers"
      paginator
      :rows="10"
      dataKey="id"
      filterDisplay="row"
      :loading="loading"
      :globalFilterFields="['name', 'representative.name', 'status']"
      sortMode="single"
      sortField="country.name"
      :sortOrder="1"
      rowGroupMode="rowspan"
      groupRowsBy="country.name"
    >...
```
The error in chrome:

> Maximum recursive updates exceeded in component <DataTable>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

### Reproducer

https://stackblitz.com/edit/ygmnwy?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 123.0.6312.105

### Steps to reproduce the behavior

Do a sort and a group on the same column

### Expected behavior

Either it should be documented that you cannot do this or it should still work.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by OliverRC** [comment]
Umm the DataTable crashing the tab because of an infinite loop is, in my opinion, a bug.

**Comment by NodeAdam** [comment]
This is a bug. Grouping is unusable if you can't sort
