### ISSUE TITLE
Primevue 3 umd components don't expose global names

### ISSUE THREAD

**Issue by adrianfiedler** [primefaces/primevue#554]
I have a vue 2 app using script urls to primevue components like this:
```
<script src="https://unpkg.com/primevue/components/calendar/calendar.umd.min.js"></script>
<div id="wrapper">
    <p-calendar></p-calendar>
</div>
  const myApp = new Vue({
    components: {
      'p-calendar': calendar
    }
  });
```
This is also the url that is described in primevue 2 documentation: https://www.primefaces.org/primevue/showcase-v2/#/setup
This worked fine until the release of vue 3 some days ago. Because now the url
https://unpkg.com/primevue/components/calendar/calendar.umd.min.js
leads to
https://unpkg.com/primevue@3.0.0/components/calendar/calendar.umd.min.js

And it looks like the 3.0.0 components don't expose names like calendar or dialog. Now my app breaks and I only see errors in console like this:
`Uncaught ReferenceError: calendar is not defined`

This happens for any component I use.

Please see my stackblitz example:
https://stackblitz.com/edit/js-esllan?file=index.html

**Comment by tugcekucukoglu** [comment]
Hi,
We looked into your project. If you are using Vue2, you need to use PrimeVue2. Otherwise project will fail. 
If you want to carry your project Vue3, you should use PrimeVue3.
