### ISSUE TITLE
MenuBar: Hydration Errors in v3.51.0

### ISSUE THREAD

**Issue by rickngo** [primefaces/primevue#5541]
### Describe the bug

After updating to v3.51.0, I am now receiving hydration errors for the MenuBar component. This is occurring on Chrome (Windows and Mac) and Firefox, that I've tested so far.

When I downgrade to v3.50.0, there are no hydration errors

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-a9mcrv?file=components%2FNavBar.vue,app.vue,package.json,package-lock.json

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Please see Stackblitz. I created a MenuBar component with routes and rendered it in the App

### Expected behavior

No hydration errors

**Comment by rizen** [comment]
+1

**Comment by i7slegend** [comment]
relates to !5486 

i think i never win this SSR 🥲

**Comment by NakkuTricks** [comment]
+1

**Comment by Yves852** [comment]
As a solution you can provide an SSR-friendly id with **useId()** in **Nuxt >= 3.10**:

```diff
<script setup>
+  const MegaMenuId = useId()
</script>

<template>
    <MegaMenu
+     :id="MegaMenuId"
      :model="items"
    >
        <!-- ... -->
    </MegaMenu>
</template>
```

https://nuxt.com/docs/api/composables/use-id
https://primevue.org/megamenu/#api.megamenu.interfaces.MegaMenuFocusedItemInfo.parentKey

**Comment by tugcekucukoglu** [comment]
Sorry for the confusion. It will be fixed for the next version.
