### ISSUE TITLE
Paginator: `first` props wont work

### ISSUE THREAD

**Issue by scripty-script** [primefaces/primevue#5543]
### Describe the bug

The paginator first won't work.
Or their is proper way to set the first?

![image](https://github.com/primefaces/primevue/assets/98148272/e02445fa-8bba-44a1-83d2-352035b2076b)

### Reproducer

https://stackblitz.com/edit/m8g8mj-icefsk?file=src%2FApp.vue

### PrimeVue version

^3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by bblumenfelder** [comment]
Same issue here

**Comment by tugcekucukoglu** [comment]
`first` does not reflect the page number. According to the above example, if you reflect the page as 2, `first` should be between 10 and 19.
