### ISSUE TITLE
InputNumber Not Working android

### ISSUE THREAD

**Issue by hiepeng** [primefaces/primevue#5545]
### Describe the bug

https://github.com/primefaces/primevue/assets/72748313/e9403da5-f7d0-4bc6-8f08-ffcc6506f699

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template?file=README.md

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

browse android

### Steps to reproduce the behavior

help

### Expected behavior

help

**Comment by melloware** [comment]
You can read about it here on PrimeReact: https://github.com/primefaces/primereact/issues/6275

I explain exactly why it is not working.  Basically PrimeTek has properly removed `onKeyPress` events which is deprecated in all browsers.  The bad news is of Android is the ONLY browser that doesn't respect proper keyboard events.  So hacks will have to be made to support android.

**Comment by melloware** [comment]
See Primereact PR: https://github.com/primefaces/primereact/pull/6332

**Comment by tugcekucukoglu** [comment]
Thanks for the clarification. It was reverted for the next version.
