### ISSUE TITLE
[v4 beta 1: Calendar] Failed to resolve component: Button

### ISSUE THREAD

**Issue by ronaldtveen** [primefaces/primevue#5550]
### Describe the bug

When importing the `Calandar` in a non-global scope you get warnings in the browser console, see the [Stackblitz](https://stackblitz.com/edit/wyuvuj?file=src%2Fmain.js) demo.

```
main.js:24 [Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Calendar modelValue=undefined onUpdate:modelValue=fn > 
  at <App>
```

### Reproducer

https://stackblitz.com/edit/wyuvuj?file=src%2Fmain.js

### PrimeVue version

4.0.0-beta.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

1. Visit the [Stackblitz](https://stackblitz.com/edit/wyuvuj?file=src%2Fmain.js) demo
  Here I have imported `Calendar` from PrimeVue instead of importing it in the global scope via `App.js`.
1. Check console for warnings
1. Uncomment line `#19` in App.vue to globally import the PrimeVue `<Button>` component:
    `app.component('Button', Button)`
1. Check console for warnings again
  This basically "fixes" the warning but this way is not desirable, I want the imports to be done in the SFC and not globally.

### Expected behavior

By just importing the Calendar component there should not be any global imports needed to suppress Vue Warnings in the console.

**Comment by tugcekucukoglu** [comment]
It will be fixed for beta-2.

Thanks,
