### ISSUE TITLE
Dropdown: `filter` + `editable` has no effect on the filter

### ISSUE THREAD

**Issue by matthew-dean** [primefaces/primevue#5557]
### Describe the bug

A common pattern in editable dropdown components is to apply / show a filter when it matches, and change the filter to say "New [x]..." (or hide the dropdown) when there are no matches.

Currently, the PrimeVue component does none of those things, and the filter does not respond to / apply the entered text. Also, when `editable`, the "filtering" textbox is redundant / useless, as, logically, there's already a field to apply the filter. 

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-osnpg8?file=src%2FApp.vue

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 123

### Steps to reproduce the behavior

1. See the Stackblitz
2. Enter text in the editable dropdown.
3. Note that the dropdown is not filtered according to the edited text.

### Expected behavior

Filter should apply the contents of the editable text box / there should not be two editable textboxes.

**Comment by tugcekucukoglu** [comment]
As you have said editable mode does not filter options. According to community demand, we could consider adding this functionality.

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
