### ISSUE TITLE
Upload: cancel file select event tiggers bubbling 

### ISSUE THREAD

**Issue by wk-iei** [primefaces/primevue#5559]
### Describe the bug

I have a Upload component in a Dialog:

Dialog.vue
```
<Dialog
      v-model:visible="visible"
      modal
      header="Edit Profile"
      :style="{ width: '25rem' }"
      @hide="visible = false"
    >
      <UploadFile @cancel="handelCancel" />
    </Dialog>
```
UploadFile.vue
```
<FileUpload
      mode="basic"
      name="demo[]"
      url="/api/upload"
      accept="image/*"
      :maxFileSize="1000000"
      @upload="onUpload"
    />
```
when the file select window popup,  click `cancel` button will trgger `@cancel ="handelCancel"`. I have to diclear another emit like 
`@hide="handelCancel"`

### Reproducer

https://stackblitz.com/edit/hndvbt?file=src%2FApp.vue,src%2FUploadFile.vue

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
We cannot reproduce the issue you mentioned with the demo you sent. Can you send a demo where we can see issue?

**Comment by wk-iei** [comment]
> We cannot reproduce the issue you mentioned with the demo you sent. Can you send a demo where we can see issue?

![screenshot](https://github.com/primefaces/primevue/assets/153057208/44ea4bf7-168d-4a08-a634-538793a9ce84)

here is a screenshot of the Reproducer link

**Comment by tugcekucukoglu** [comment]
It is being closed because there is no core issue. For more questions about demos, discord or discussions can be used.
