### ISSUE TITLE
[v4 beta1: SelectButton] Pass Through missing both BUTTON and LABEL options

### ISSUE THREAD

**Issue by ronaldtveen** [primefaces/primevue#5576]
### Describe the bug

In PrimeVue v3 the `<SelectButton>` Pass Through options had four labels [documented here](https://primevue.org/selectbutton/) for v3 (see PASS THROUGH tab)
1. root
2. button
3. label
4. hooks

In PrimeVue v4 this is limited to [v4 docs](https://v4.primevue.org/selectbutton/) (see PASS THROUGH tab):
1. root
2. hooks

I'm guessing (first time looking at the code) that the methode `ptm()` should be replaced with `getPTOptions()` for these lines of code:
- [v4 button](https://github.com/primefaces/primevue/blob/b828f34a86f99437db12a54bbd379b657bdbfed9/components/lib/selectbutton/SelectButton.vue#L11)
- [v4 label](https://github.com/primefaces/primevue/blob/b828f34a86f99437db12a54bbd379b657bdbfed9/components/lib/selectbutton/SelectButton.vue#L15)

Like it does in v3:
- [v3 button](https://github.com/primefaces/primevue/blob/8365a30f5b996d7cd8a0c7349b27047218092e96/components/lib/selectbutton/SelectButton.vue#L17)
- [v3 label](https://github.com/primefaces/primevue/blob/8365a30f5b996d7cd8a0c7349b27047218092e96/components/lib/selectbutton/SelectButton.vue#L22)

### Reproducer

https://stackblitz.com/edit/ypxj2k?file=src%2FApp.vue

### PrimeVue version

v4.0.0 beta 1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Open StackBlitz example and remove the commented lines from code `<< REMOVE THIS COMMENT LINE TO REVEAL ERROR >>` (twice) to make the `button` key active in the PT object. 

This throws a console error right away because of the missing button option described above.

**Comment by tugcekucukoglu** [comment]
SelectButton uses ToggleButton component internally. It will be added to the documentation.

**Comment by rubjo** [comment]
Is this completed? Docs for passThrough in v4 refer to `pcButton`, which doesn't seem to work.

**Comment by Miss-Sixty** [comment]
> 这完成了吗？v4 中的 passThrough 文档请参阅`pcButton`，但似乎不起作用。
> 
> https://v4.primevue.org/selectbutton/#pt.doc.steps

 In this way
 pcButton: { root: { class: 'flex-1' } }

**Comment by kimboender1983** [comment]
> > 这完成了吗？v4 中的 passThrough 文档请参阅`pcButton`，但似乎不起作用。
> > https://v4.primevue.org/selectbutton/#pt.doc.steps
> 
> In this way pcButton: { root: { class: 'flex-1' } }

This is a step further, but it does not seem to target the button itself. So when the button is active, how do we style this? The context property seems to be missing also which holds the active property.

![Scherm­afbeelding 2024-09-03 om 16 31 33](https://github.com/user-attachments/assets/57e29cef-5e69-42b1-9d2d-2adb42ea29d6)
