### ISSUE TITLE
OrganizationChart: Need a Vertical layout

### ISSUE THREAD

**Issue by lindongchen** [primefaces/primevue#5581]
### Describe the bug

I think OrganizationChart is a very valuable component,
But the horizontal layout limits its number of nodes,
I understand that it was implemented using `<table>` tag, 
and vertical layout cannot be achieved well by rotating nodes or panels.
I hope the official team can have a better implementationm. 

Thinks~

### Reproducer

-

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

-

### Expected behavior

-

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
