### ISSUE TITLE
Stepper v4: current step invisible

### ISSUE THREAD

**Issue by ixxie** [primefaces/primevue#5585]
### Describe the bug

The current step in the new `Stepper` component has its step number hidden in v4:

![image](https://github.com/primefaces/primevue/assets/20320695/433b9529-25e2-438b-bb36-8fb8d6a15c80)

### Reproducer

https://v4.primevue.org/stepper/

### PrimeVue version

4.0.0-beta.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Fixed for the 4.0.0-beta-3.

Thank you.
