### ISSUE TITLE
Calendar: Localization days not showing

### ISSUE THREAD

**Issue by Rekl0w** [primefaces/primevue#5587]
### Describe the bug

I tried to localize calendar for my project, but the dayNamesShort not showing at the calendar.

### Reproducer

https://stackblitz.com/edit/gpsywq?file=src%2Fmain.js

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on the Calendar
2. dayNamesShort not showing
![screenshot](https://github.com/primefaces/primevue/assets/91488737/01da9a18-4237-4d68-baf0-6a8a90b47deb)

### Expected behavior

![image_2024_04_15T14_11_50_858Z](https://github.com/primefaces/primevue/assets/91488737/bc8b1d2f-5a78-488f-b83d-ef878eb63a17)

**Comment by d2a8k3u** [comment]
@Rekl0w Before this bug is fixed, you can resolve the issue by adding the attribute 'firstDayOfWeek' to the locale object.

**Comment by Rekl0w** [comment]
> @Rekl0w Before this bug is fixed, you can resolve the issue by adding the attribute 'firstDayOfWeek' to the locale object.

Thank you
