### ISSUE TITLE
InputOtp: Basic usage not showing values in the input fileds

### ISSUE THREAD

**Issue by mateenagy** [primefaces/primevue#5590]
### Describe the bug

When you use `<InputOtp v-model="value">` it's not showing the values when typing, also when you delete the values you can't use any of the input anymore and not remove the value.

On the other hand if you use template, it is working as expected. 

### Reproducer

https://stackblitz.com/edit/usrzap?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Safari

### Steps to reproduce the behavior

Just use the basic `<InputOtp v-model="value">` component.

### Expected behavior

The basic version works as the same as with template.

**Comment by NamesMT** [comment]
Locking vue to 3.4.21 fixed the issue,
Caused by upstream: vuejs/core#10710

**Comment by mateenagy** [comment]
It's fixed with `Vue 3.4.23`
