### ISSUE TITLE
Input of type number reverts to default value on change in Vue.js 3.3 app

### ISSUE THREAD

**Issue by wasifsyed-driverup** [primefaces/primevue#5595]
### Describe the bug

Description:
After a recent redeployment of our Vue.js 3.3 application on AWS Amplify, without any changes to the dependencies, the <inputNumber>  fields across the application have started malfunctioning. Any attempt to change the value in these input fields results in the value resetting to its default or previous value.
I had to use old package_lock.json file then it worked.

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.51

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

chrome,edge,firefox

### Steps to reproduce the behavior

Steps to Reproduce:

Open the application.
Navigate to any form with a number input.
Try entering or changing the value in the number input field.
Expected Behavior:
The input should accept and display the new value entered by the user.

Additional Information:

This issue is also reproducible in a Stackblitz environment, suggesting it might not be related to the deployment on AWS Amplify specifically.
There were no changes in the dependencies or major code changes related to the input handling in the recent deployment.
The issue is observed across different browsers and devices.
Possible Solutions:

Check if there are any Vue.js or browser-specific issues reported recently that could affect number inputs.
Review any global event handlers or Vue.js directives that might interfere with the normal behavior of input fields.

### Expected behavior

Actual Behavior:
The input field automatically reverts to its initial value immediately after the user attempts to modify it.

**Comment by Rekl0w** [comment]
Your stackblitz link is not working

**Comment by wasifsyed-driverup** [comment]
@Rekl0w  can you try this https://stackblitz.com/edit/1hbutu?file=src%2FApp.vue

**Comment by wasifsyed-driverup** [comment]
@iampapagray  can you tell which library its associated with

**Comment by iampapagray** [comment]
@wasifsyed-driverup this library. I am currently using version 3.48.1 and it works

**Comment by wasifsyed-driverup** [comment]
@iampapagray  It was working fine. Is there a possible reason why it happened after a fresh npm install? One more thing it worked with downgrading the version.

**Comment by goekhantopcu** [comment]
I have this issue as well, the model-value resets on every change no matter how i trigger the update (via button or manual input)

**Comment by goekhantopcu** [comment]
God knows why, but after deleting my node_modules and re-installing the dependencies it worked out for me.
