### ISSUE TITLE
Calendar: Hours are set to 00 when clicking the "Today" button

### ISSUE THREAD

**Issue by thristov78** [primefaces/primevue#5596]
### Describe the bug

When the "Today" button is clicked, the hours field is set to 00 instead of the current hour. The minutes field is populated correctly.

The problem can be reproduced with showTime and showButtonBar attributes enable.

### Reproducer

https://stackblitz.com/edit/primevue-calendar-today-hours-bug?file=src%2FApp.vue

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/primevue-calendar-today-hours-bug?file=src%2FApp.vue
2. Click on the calendar component
3. The calendar displays the current date, hours, minutes
4. Click on the "Today" button
5. The hours field is changes to 00, not to the current hour

### Expected behavior

The hours field should be populated with the current hour, just like the minutes fields.

**Comment by srabieb** [comment]
+
