### ISSUE TITLE
Datatable / paginator pt

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#5627]
### Describe the bug

I want put "disbled" in the buttons of pagination while the api is loading but in "firstPageButton", "previousPageButton", "nextPageButton", "lastPageButton" and "RowsPerPageDropdown" not work but in "pageButton" work it..

If the user navigates by keyboard, he/she can press the buttons on the pagination.

paginator: ({ paginator }) => ({
				firstPageButton: ({}) => ({
					disabled: cargandoServicio
				}),
				previousPageButton: ({}) => ({
					disabled: cargandoServicio
				}),
				nextPageButton: ({}) => ({
					disabled: cargandoServicio
				}),
				lastPageButton: ({}) => ({
					disabled: cargandoServicio,
				}),
				pageButton: ({}) => ({
					disabled: cargandoServicio
				}),
				RowsPerPageDropdown: ({}) => ({
					disabled: cargandoServicio
				})
			})

### Reproducer

https://stackblitz.com/edit/4fj5sv?file=src%2FApp.vue

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
`pt` property can define aria, data-* or custom attributes but not property. 

In this case, we can suggest this usage, for example: : `nextPageButton: 'p-disabled'`
