### ISSUE TITLE
DataTable: showGridlines not working

### ISSUE THREAD

**Issue by farukgkc** [primefaces/primevue#5634]
### Describe the bug

Hello,
Although I use the showGridlines parameter in the DataTable component, the lines do not appear in my table. Can you help me with what I need to do to make the lines appear?

Example Code : 
```vue
<template>
  <div class="row row-sm">
  <Card class="mg-b-20">
    <template #content>
      <span class="p-card-title">Satıcı Takip Listesi</span>
      <!-- Tablo start -->
      <div class="mg-t-20">
        <DataTable :value="products" showGridlines >
          <Column field="storeCountry" header="Hangi Ülkedeki Mağazası Takip Ediliyor"></Column>
          <Column field="storeName" header="Mağaza Adı"></Column>
          <Column field="sellerNationality" header="Satıcı/Mağaza Uyruğu"></Column>
          <Column field="sellerId" header="Satıcı/Mağaza Id'si"></Column>
          <Column field="sellerRating" header="Rating"></Column>
          <Column field="sellerReview" header="Review"></Column>
          <Column field="date" header="Takip Başlangıç Tarihi"></Column>
          <Column field="storeASIN" header="Mağaza ASIN\'lerini İndir"></Column>
          <Column field="sellerNoFallowing" header="Mağazayı Takip Etmeyi Bırak"></Column>
        </DataTable>
      </div>
      <!-- Tablo stop -->
    </template>
  </Card>
</div>
</template>

<script>
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import Row from 'primevue/row';

export default {
  components: {
    DataTable,
    Column,
    ColumnGroup,
    Row,
  },

  data(){
    return {
      products: [
        { storeCountry: 'Türkiye', storeName: 'Store Adı 1', sellerNationality: 'Türkiye',sellerId: 'ABC123456',
            sellerRating: '100', sellerReview: '670', date: '05/04/2024', storeASIN: 'İndir', sellerNoFallowing: 'No Fallow' },
            { storeCountry: 'Amerika', storeName: 'Store Adı 2', sellerNationality: 'Çin',sellerId: 'ABC123456',
            sellerRating: '80', sellerReview: '1635', date: '05/04/2024', storeASIN: 'İndir', sellerNoFallowing: 'No Fallow' },
            { storeCountry: 'Fransa', storeName: 'Store Adı 3', sellerNationality: 'Çin',sellerId: 'ABC123456',
            sellerRating: '95', sellerReview: '0', date: '16/08/2023', storeASIN: 'İndir', sellerNoFallowing: 'No Fallow' },
            { storeCountry: 'Çin', storeName: 'Store Adı 4', sellerNationality: 'Almanya',sellerId: 'ABC123456',
            sellerRating: '50', sellerReview: '109', date: '30/03/2023', storeASIN: 'İndir', sellerNoFallowing: 'No Fallow' }
      ],

    };
  },
};

</script>

<style>

</style>

``` 

![image](https://github.com/primefaces/primevue/assets/16747993/3038821c-afd4-49c6-bce8-4f3d4376bbee)

### Reproducer

https://stackblitz.com/

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Could you provide a proper link? The live demo seems to be working: https://primevue.org/datatable/#gridlines

**Comment by farukgkc** [comment]
Hello Ms. @tugcekucukoglu ,

If I need to give a little more detailed information;
I use a theme other than primevue by default on my site.
I also imported the primevue theme. And I use some of the primevue components on my site.
I have this observation,

I use "aura-light-teal" as the primevue theme.
In "node_modules>primevue>resources>themes>aura-light-teal>theme.css"

 
```vue
.p-datatable.p-datatable-gridlines .p-datatable-header {
border-width: 1px 1px 0 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-footer {
border-width: 0 1px 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-paginator-top {
border-width: 0 1px 0 1px;
}
.p-datatable.p-datatable-gridlines .p-paginator-bottom {
border-width: 0 1px 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-thead > tr > th {
border-width: 1px 0 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-thead > tr > th:last-child {
border-width: 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-tbody > tr > td {
border-width: 1px 0 0 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-tbody > tr > td:last-child {
border-width: 1px 1px 0 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-tbody > tr:last-child > td {
border-width: 1px 0 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-tbody > tr:last-child > td:last-child {
border-width: 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-tfoot > tr > td {
border-width: 1px 0 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-tfoot > tr > td:last-child {
border-width: 1px 1px 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-thead + .p-datatable-tfoot > tr > td {
border-width: 0 0 1px 1px;
}
.p-datatable.p-datatable-gridlines .p-datatable-thead + .p-datatable-tfoot > tr > td:last-child {
border-width: 0 1px 1px 1px;
}
.p-datatable.p-datatable-gridlines:has(.p-datatable-thead):has(.p-datatable-tbody) .p-datatable-tbody > tr > td {
border-width: 0 0 1px 1px;
}
.p-datatable.p-datatable-gridlines:has(.p-datatable-thead):has(.p-datatable-tbody) .p-datatable-tbody > tr > td:last-child {
border-width: 0 1px 1px 1px;
}
.p-datatable.p-datatable-gridlines:has(.p-datatable-tbody):has(.p-datatable-tfoot) .p-datatable-tbody > tr:last-child > td {
border-width: 0 0 0 1px;
}
.p-datatable.p-datatable-gridlines:has(.p-datatable-tbody):has(.p-datatable-tfoot) .p-datatable-tbody > tr:last-child > td:last-child {
border-width: 0 1px 0 1px;
}
``` 
When I added the codes to my own style.css and added "border-color: #e2e8f0;" the lines became visible.

As far as I understand, I cannot access all css of aura-light-teal.
I think when this problem is solved, other problems will be solved. (I have different problems in different components, such as padding, etc.)

Can you help with this issue?

**Comment by tugcekucukoglu** [comment]
You may be using a different theme other than PrimeVue and you may have padding etc. styles in your base css file that do not match the aura design and these styles may be crushing aura. In this case, you can identify the css that causes this yourself.

'As far as I understand, I cannot access all css of aura-light-teal.' We didn't quite understand what you meant in this sentence. All codes of PrimeVue are accessible.
https://github.com/primefaces/primevue/blob/master/public/themes/aura-light-teal/theme.css

Closing due to not being a core issue.

**Comment by FVolral** [comment]
@farukgkc are you using Bootstrap ? because I've a similar issue and Bootstrap seems to win against the PrimeVue Cascade Layer :

![image](https://github.com/primefaces/primevue/assets/38896748/fa250f57-8732-4bae-bc82-e9cd37d5db20)

That's how Bootstrap is imported in my app.scss : 
`@import "bootstrap/dist/css/bootstrap.min.css";
@import 'bootstrap-reboot' layer(bsreboot) ;

/* establish a layer order up-front, from lowest to highest priority */
@layer bootstrap, bsreboot, reset, mainapp, primevue, customfixprimevue;
`

@tugcekucukoglu there is also a small typo in the docs :
[here](https://primevue.org/csslayer/#bootstrap)
![image](https://github.com/primefaces/primevue/assets/38896748/a8407158-3818-47b6-94fd-98f4e117865a)

**Comment by FVolral** [comment]
@farukgkc I had a similar issue, it looks like you are using bootstrap and since Primevue 3.35 there is a breaking change. 

make use that you layer your import of bootstrap : 
```- @import "bootstrap/dist/css/bootstrap.min.css";
+ @import "bootstrap/dist/css/bootstrap.min.css" layer(bootstrap); ```

and that bootstrap is before Primevue in the following rule: 
```/* establish a layer order up-front, from lowest to highest priority */
@layer bootstrap, primevue;```

**Comment by farukgkc** [comment]
@FVolral,

I added it to my application as you said. but nothing changed.

![image](https://github.com/primefaces/primevue/assets/16747993/5ef707a2-083b-472f-93a3-843f15e23f20)
