### ISSUE TITLE
InputNumber: Not able enter number with fraction and zero

### ISSUE THREAD

**Issue by 0x6a68** [primefaces/primevue#5640]
### Describe the bug

I am not able to enter a number with a leading zero after the separator without using the arrow keys. Example try to enter: `0.01` 

### Reproducer

https://stackblitz.com/edit/1ae5vg?file=src%2FApp.vue

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to the reproducer
2. Enter the following characters: 0.01
3. You should see 0.10 in the input field

### Expected behavior

Expected to enter `0.01` without using the arrow keys.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/5170
