### ISSUE TITLE
MultiSelect: `p-focus` class being applied on hover

### ISSUE THREAD

**Issue by omzy** [primefaces/primevue#5647]
### Describe the bug

Seems like this was broken in 3.47.0. When you hover over an option, the `p-focus` class is being applied. Previously, the `p-focus` class would only be applied when the option was clicked (which I think is the correct behaviour). Furthermore, if you hover over an option and then hover away from the list, the option still has `p-focus` class.

In the reproducer link, which is using 3.46.0, the above issue is NOT occurring. Compare this to the same example in your current documentation site: https://primevue.org/multiselect/#basic

### Reproducer

https://stackblitz.com/edit/g1vpgm-pj9d6v

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
It's a behavior change. `p-focus` remains an option when mouse moves out to support the keyboard accessibility.
