### ISSUE TITLE
Dark Mode Toggle: The default styeld primevue in v4 is unable to auto detect dark mode

### ISSUE THREAD

**Issue by fu050409** [primefaces/primevue#5666]
### Describe the bug

 The default styeld primevue in v4 is unable to auto detect dark mode.

The dark mode will be worked when the settings is:

```
app.use(PrimeVue, {
    theme: {
        base: PrimeOne,
        preset: Aura,
        options: {
            darkModeSelector: 'system',
        }
    }
 });
```

At this time, dark style is enabled if the system prefres theme is `dark`, but when i set `darkModeSelector` to other values like `dark-mode`, the dark classes 
 which startswith `dark:` are worked, but the default dark style is not enabled when label `<html>` or `<body>` has a class `dark-mode`.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template

### PrimeVue version

4.0.0-beta.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 124.0.6367.91

### Steps to reproduce the behavior

1. Import primevue after primevue v4.0.0-beta.1 is installed
```
import PrimeVue from "primevue/config";
// @ts-ignore
import PrimeOne from "primevue/themes/primeone";
// @ts-ignore
import Aura from "primevue/themes/primeone/aura";
```

2. Setup PrimeVue and use it
```
app.use(PrimeVue, {
  ripple: true,
  theme: {
    base: PrimeOne,
    preset: Aura,
    options: {
      prefix: "p",
      darkModeSelector: "system",
      cssLayer: false,
    },
  },
});
```

### Expected behavior

The primevue dark style should work when `dark-mode` class is set to `<html>` or `<body>`.

**Comment by mertsincan** [comment]
PrimeVue does not add the dakMode class to any DOM element, it only creates selectors for style and variables. If you have implementations that depend on this class, you need to add that class to the dom element like Tailwind; https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection

Our doc; https://v4.primevue.org/theming/styled/#darkmodetoggle

```js
if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
  document.documentElement.classList.add('< darkModeSelector >'')
} else {
  document.documentElement.classList.remove('< darkModeSelector >')
}

and addEventListener('change', ...)
```

Best Regards,

**Comment by fu050409** [comment]
Thank you very much for your patience, I did create buttons in my page for adding and removing `dark-mode` classes to and from the `<html>` tags, however `PrimeVue`'s Dark Mode styles didn't take effect when the `dark-mode` classes were added to `<html>`, I don't know if this is the expected result or if it's due to some stupid oversight on my part?

**Comment by fu050409** [comment]
Well, I suddenly realized what my problem was, the dark mode selector in PrimeVue's config item needs to start with a `. ` at the beginning, but I seem to have overlooked it, my mistake indeed.😅😅

I hope you'll forgive me for my recklessness. :)
