### ISSUE TITLE
InputGroupAddon stopped working

### ISSUE THREAD

**Issue by teoring** [primefaces/primevue#5670]
Hello,

I don't know if this is known issue but when I updated from 3.47.0 to 3.52.0 my login form breaks.

This is how it looks on 3.47.0

![image](https://github.com/primefaces/primevue/assets/12891023/7fd7656e-dc33-4535-a92d-f6cc42bc8159)

And this is how it looks in 3.52.
![image](https://github.com/primefaces/primevue/assets/12891023/45f0033c-0787-4517-b1c6-78a88363c241)

Its a very simple code:

                        <InputGroup :class="{ 'p-invalid': emailErrorMsg }">
                            <InputGroupAddon>
                                <i class="pi pi-envelope"></i>
                            </InputGroupAddon>

                            <span class="p-float-label">
                                <InputText
                                    id="email"
                                    @keyup="checkEmailField"
                                    placeholder="Email"
                                    v-model="email"
                                    name="email"
                                    :class="{ 'p-invalid': emailErrorMsg }"
                                    aria-describedby="email-text-error"
                                />
                                <label for="email">Email</label>
                            </span>
                        </InputGroup>

I am running Node v20.12.2. 

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-8cx1sy?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 122.0.6261.112 

### Steps to reproduce the behavior

Even example from PrimeVue websites doesn't work:

<InputGroup>
    <InputGroupAddon>$</InputGroupAddon>
    <InputNumber placeholder="Price" />
    <InputGroupAddon>.00</InputGroupAddon>
</InputGroup

### Expected behavior

See attached screenshots for expected behavior.

**Comment by bphein1980** [comment]
I am facing the same issue on 3.52.0.

InputGroup and InputGroupAddon are not in the resolver for auto importing. 

You can import them manually for the time being...

```
import InputGroup from 'primevue/inputgroup'
import InputGroupAddon from 'primevue/inputgroupaddon'
```

**Comment by tugcekucukoglu** [comment]
Adding

```
import InputGroup from 'primevue/inputgroup'
import InputGroupAddon from 'primevue/inputgroupaddon'
```

solves the problem.
