### ISSUE TITLE
Button: Missing Passthrough Options

### ISSUE THREAD

**Issue by zaleshanin** [primefaces/primevue#5685]
### Describe the bug

The passthrough options are not passed down to the `icon` and `loadingicon` slot in unstyled mode.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-4nagez?embed=1&file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
When you decide to use slots, you have to do it yourself. So closing due to not being a core issue.
