### ISSUE TITLE
Horrible table-main-checkbox performance

### ISSUE THREAD

**Issue by henrikps** [primefaces/primevue#5692]
### Describe the bug

Response time in table is above 2s. No custom stuff added its just plain and simple combination of virtuallscroll and selectable rows
https://stackblitz.com/edit/vitejs-vite-qv4xzb?file=src%2FApp.vue,src%2Fmain.ts

### Reproducer

https://stackblitz.com/edit/vitejs-vite-qv4xzb?file=src%2FApp.vue,src%2Fmain.ts

### PrimeVue version

3 and 4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Click the first checkbox on the left (the main one)

### Expected behavior

It does not take 2+ seconds to rerender

**Comment by mertsincan** [comment]
Hi,

Please see my blog post; https://dev.to/mertsincan/handling-big-data-on-datatable-with-checkbox-selection-multiselect-4hgc

Best Regards,
