### ISSUE TITLE
RadioButton: RadioButton 'checked' property and Native Input 'checked' Values Not Aligned with :modelValue

### ISSUE THREAD

**Issue by zagushka** [primefaces/primevue#5694]
### Bug Description
The RadioButton component exhibits a synchronization issue between its `checked` property and the native input's `checked` attribute when used with the `:modelValue` prop. 
Despite setting the `checked` value based on the `modelValue`, input's `checked` value may change if the `modelValue` remains unchanged. 
This discrepancy results in the `@update:model-value` event not firing upon clicking the same RadioButton for the second time.
To highlight the issue, I removed CSS styling to visually display both the RadioButton wrapper and its native input on [stackblitz example](https://stackblitz.com/edit/primevue-create-vue-issue-template-jql41c?file=src%2FApp.vue).

I believe this was introduced during the refactoring of the RadioButton component.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-jql41c?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Expected behavior

I would expect the native input's 'checked' state to match the value of the ':modelView' prop.

**Comment by tugcekucukoglu** [comment]
It is a Vue concept: https://vuejs.org/guide/components/v-model

If you do not prefer to use v-model, RadioButton's value should be changed in handler method.
