### ISSUE TITLE
Paginator: PassThrough not work properly

### ISSUE THREAD

**Issue by sbaldocchi** [primefaces/primevue#5699]
### Describe the bug

pt option jumpToPageInput not work on component Paginator

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template-ebsxbg?file=src%2FApp.vue

### PrimeVue version

3.52

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by thinksamwp** [comment]
I have a similar issue with the DataTable filterOperatorDropdown passthrough prop.

Upon reviewing the source code, changing line 71 in ColumnFilter.vue from 
```vue
:pt="getColumnPT('filterOperatorDropdown')"
``` 
to
```vue
:pt="{ root: getColumnPT('filterOperatorDropdown')}" 
```  
appears to fix the issue.

https://github.com/primefaces/primevue/blob/c543d2a84e06b74bf64354c02a3df56ed0625163/components/lib/datatable/ColumnFilter.vue#L71

**Comment by sbaldocchi** [comment]
Hi, i tried your implementation but it doesn't seem to work. I have updated the script in StackBlitz. Thanks again.
