### ISSUE TITLE
TreeTable: sorting does not work with lazy-loaded data

### ISSUE THREAD

**Issue by ray007** [primefaces/primevue#5703]
### Describe the bug

TreeTable with lazy loaded data.
Clicking on the column headers changes the sort icon, but not the order of displayed rows.

Example was made by only adding `sortable` to the column definition of the lazy load from documentation.

### Reproducer

https://stackblitz.com/edit/7mwdun?file=src%2FApp.vue

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Load example
2. Click on column header - row order does not change

### Expected behavior

Row order does change depending on data.

**Comment by memin20** [comment]
Is there a workaround for this problem? Which version was the last known working version?

**Comment by alqa-dash** [comment]
3.52.0 - sort with lazy load does not work. 

I've tried to use @sort="onSort($event)". Sort works but when one clicks sort on column on page other then first, paginator set current page to 1.

**Comment by sergeydus** [comment]
nested sorting doesn't work in general, even when data is not lazy loaded

**Comment by alqa-dash** [comment]
Unfortunately yes, it does not work but it should because if dataset is already fetched - there is no need to ask server again but with some order applied.
