### ISSUE TITLE
Calendar: `name` should be passed to the `input` if provided

### ISSUE THREAD

**Issue by trajano** [primefaces/primevue#5711]
### Describe the bug

When using PrimeVue to augment an existing web app.  It doesn't pass the value of the calendar field because the `name` property is kept on the span and not pushed to the underling `input` field

### Reproducer

https://jsfiddle.net/hjobdmay/

### PrimeVue version

3.52

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. https://jsfiddle.net/hjobdmay/
2. fill in a date and text
3. click submit

### Expected behavior

date value should be provided

**Comment by trajano** [comment]
The workaround for those who need it is to add a hidden field like this

```
<p-calendar v-model="date" date-format="yy-mm-dd" :manualInput="true" :showOnFocus="false"></p-calendar>

<input type="hidden" name="date" :value="date?.toLocaleDateString()" />
```

**Comment by trajano** [comment]
It appears that `id` is not passed in either which means `label for="idRef"` will not work

**Comment by m-meier** [comment]
For id there's the inputId property. Unfortunately there is no equivalent for the name, however you could use the passthrough feature instead of a hidden input: 
` <p-calendar v-model="date" input-id="myinput" pt:input:name="test123" date-format="yy-mm-dd" :manualInput="true"
                    :showOnFocus="false"></p-calendar>`

**Comment by tugcekucukoglu** [comment]
New `name` property is added. `inputId` property is also available for the input element of Calendar.
