### ISSUE TITLE
Setting text for Editor / Quill component doesn't work

### ISSUE THREAD

**Issue by Friis1978** [primefaces/primevue#5724]
### Describe the bug

When using the textEditor to edit text (loading a default text into the component, it isnt set in the editor window. But the updateValue emit is running, so the text should be there. I tried to use the 'onBeforeMounted' function to force the update, but no lock. Can someone please tell me if im doing something wrong, or there is a bug. 

Here is my code:

`<template>
      <Editor
        v-model="inputComputed"
        editorStyle="height: 200px; border: none;"
        :placeholder="placeholder" 
      >
        <template v-slot:toolbar>
          <span class="ql-formats">
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>

            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              <button class="ql-list" value="bullet"></button>
              <button class="ql-indent" value="-1"></button>
              <button class="ql-indent" value="+1"></button>
              <button v-tooltip.bottom="'Link'" class="ql-link"></button>
            </span>
          </span>
        </template>
      </Editor>
</template>`

`<script setup>
import { on } from "events";
import Editor from "primevue/editor";

const emit = defineEmits(["update:input","updateValue"]);

const { label, input, placeholder, error } = defineProps({
  label: {
    type: String,
  },
  input: {
    type: String,
  },
  placeholder: {
    type: String,
  },
  error: {
    type: String,
  },
});

const inputComputed = computed({
  get: () => input,
  set: (val) => {
    emit("updateValue", val);
    emit("update:input", val);
  },
});

onBeforeMount(() => {
  if (input) {
    emit("updateValue", input);
    emit("update:input", input);
  }
});
</script>`

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Browser(s)

Chrome Version 124.0.6367.119

### Steps to reproduce the behavior

Use my code to test it, I use it in a form component like this:
`<InputTextarea
          v-if="$formTypes.txtarea?.includes(key)"
          class="w-full"
          v-model:input="subform[key]"
          :inputType="subform[key]"
          :label="getLabel(key)"
          :placeholder="`Vælg en ${getLabel(key)}`"
          :error="showSubError(key) ? showSubError(key) : ''"
          @updateValue="(e) => updateSubValue(key, e)"
   />
`
And here is the InputTextarea component

`<template>
  <div>
    <label v-if="label" for="textfield" class="font-semibold w-6rem">{{
      label
    }}</label>
    <div class="p-2 border-2 border-themePrimary rounded-xl">
      <Editor
        v-model="inputComputed"
        editorStyle="height: 200px; border: none;"
        :placeholder="placeholder" 
      >
        <template v-slot:toolbar>
          <span class="ql-formats">
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>

            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              <button class="ql-list" value="bullet"></button>
              <button class="ql-indent" value="-1"></button>
              <button class="ql-indent" value="+1"></button>
              <button v-tooltip.bottom="'Link'" class="ql-link"></button>
            </span>
          </span>
        </template>
      </Editor>
    </div>
    <span class="input-error">
      {{ error }}
    </span>
  </div>
</template>

<script setup>
import { on } from "events";
import Editor from "primevue/editor";

const emit = defineEmits(["update:input","updateValue"]);

const { label, input, placeholder, error } = defineProps({
  label: {
    type: String,
  },
  input: {
    type: String,
  },
  placeholder: {
    type: String,
  },
  error: {
    type: String,
  },
});

const inputComputed = computed({
  get: () => input,
  set: (val) => {
    emit("updateValue", val);
    emit("update:input", val);
  },
});

onBeforeMount(() => {
  if (input) {
    emit("updateValue", input);
    emit("update:input", input);
  }
});
</script>`

### Expected behavior

The text in the textarea field should be updated, when text is prefilled.

**Comment by DendiRob** [comment]
Hello, I have met the same problem literally today, I have tried to set plain text, without fetching any data from the server, and nothing changed

**Comment by nike4192** [comment]
my solution to the problem
```vue
<script setup lang="ts">
function initEditorValue({ instance }) {
  instance.setContents(instance.clipboard.convert({
    html: 'some html',
    // or
    // text: 'some text',
  }));
}
</script>

<template>
  <Editor @load="initEditorValue" />
</template>
```

**Comment by Friis1978** [comment]
@nike4192 that worked, thank you very much

**Comment by PetrosyanDev** [comment]
@nike4192 Thank you very much, I was struggling for so long.

**Comment by 2234839** [comment]
@nike4192  Thank you very much. This helps me. Have a good life

**Comment by 2234839** [comment]
I just updated some dependencies and the @nike4192 method doesn't work either, I now use the following hack code to fix the problem


![图片](https://github.com/user-attachments/assets/ba4f4fc7-d92e-4875-99f4-18bc1bd71904)
![图片](https://github.com/user-attachments/assets/e038468e-7b07-4275-b749-b34f7e187f4e)

**Comment by ingIsmaelCM** [comment]
Thanks so much @nike4192 . I had same problem and your solution solved it.

**Comment by tugcekucukoglu** [comment]
Thanks for the updates.
