### ISSUE TITLE
Remove PrimeVueStyled and PrimeVueUnstyled plugins

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#5728]
We believe that once the 'base' model of the New Theme API is removed, these plugins are no longer needed.

**Comment by deisner** [comment]
@mertsincan I think the docs need to be updated, then: https://v4.primevue.org/vite/#styled -- they still instruct the user to use the PrimeVueStyled plugin, and so you get an file-not-found error when you `npm run dev`.
