### ISSUE TITLE
Slider: "Unable to preventDefault inside passive event listener invocation" in primevue_slider.js (touchmove)

### ISSUE THREAD

**Issue by GlebMatveev** [primefaces/primevue#5745]
### Describe the bug

Hello!

I'm getting the error "Unable to preventDefault inside passive event listener invocation" in primevue_slider.js when I use the Slider component on a mobile device (Android, Chrome).

The error is only reproduced on a mobile device when moving the slider with a finger.

When moving the slider with the mouse, the error does not occur.

I'm guessing the error is related to the touchmove event.

![Screenshot_4](https://github.com/primefaces/primevue/assets/46741863/ff7b0a66-a369-4805-9e59-ccbf951d246d)

https://github.com/primefaces/primevue/assets/46741863/8f965998-2f83-48ef-8e1c-7e0c303a9786

### Reproducer

https://stackblitz.com/edit/vitejs-vite-2taiwj

### PrimeVue version

4.0.0-beta.2

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

The error can be reproduced by opening my example at https://stackblitz.com/edit/vitejs-vite-2taiwj, connecting the mobile device to the PC and opening the console (chrome://inspect/#devices).

**Comment by Ben-Avrahami** [comment]
i have the same issue on 3.51.0

**Comment by caryhgq** [comment]
Components use .passive and .prevent together !
![image](https://github.com/user-attachments/assets/302276c0-0ec6-4c96-a154-f9db2b7e4c11)

**Comment by pauldps** [comment]
This is also happening with the Knob component.
