### ISSUE TITLE
Support for Reactive Masks

### ISSUE THREAD

**Issue by ilyavaiser** [primefaces/primevue#575]
It does'nt work now. For example:
`
input-mask(
      v-model="phoneNumber"
      :mask="phoneMask"
      :placeholder="phoneMask"
      )
`
Doesn't change mask

**Comment by ilyavaiser** [comment]
Any news?

**Comment by EquisTango** [comment]
As the mask is evaluated onMount, a workarround is to force a re-render of the component:
https://michaelnthiessen.com/key-changing-technique/

You will also need to re-focus the control after re-render.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
