### ISSUE TITLE
InputText: No showClear

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#5752]
### Describe the bug

Although the Dropdown has a showClear property, the InputText does not

### Reproducer

Not needed

### PrimeVue version

latest

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Subject explains it

### Expected behavior

Should show Clear button like in Dropdown

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by 1Map** [comment]
Still no showClear on the InputText (Almost year since I posted this ticket)

**Comment by JustWuu** [comment]
Using <input type="search"> provides a built-in clear button in some browsers.
The @search event is triggered when the input is cleared using the built-in clear button or through JavaScript.

<InputText type="search" @search="console.log('clear')" />

![Image](https://github.com/user-attachments/assets/d716c640-8cfa-451e-987f-79b551a68be7)

![Image](https://github.com/user-attachments/assets/62a5cc5c-a6cf-44c6-a321-70922b959bf5)

**Comment by 1Map** [comment]
@JustWuu Thanks.  Agree, that this is just a workaround.  Problem is.  For example, what if the type is a password, and you also want a clear?

**Comment by dxvgef** [comment]
The default clear button style of the InputText component using type="search" is different from the clear button style of primevue, which looks a little weird

**Comment by nikkorejz** [comment]
Any updates?

**Comment by cintek** [comment]
@nikkorejz @1Map @dxvgef if you are still interested: I opened a discussion for this topic: https://github.com/orgs/primefaces/discussions/4794
