### ISSUE TITLE
InputNumber: buttons don't have type="button" and trigger form submit

### ISSUE THREAD

**Issue by butskristof** [primefaces/primevue#5754]
### Describe the bug

If you enable the buttons on InputNumber, they should have a `type="button"` attribute. They currently don't have this and trigger a form submission if the InputNumber component is used in a `<form>` tag. 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-hawfhb?file=src%2FApp.vue

### PrimeVue version

4.0.0-beta.3

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click the right-hand button in the reproducer
2. the form is submitted

### Expected behavior

The form should not submit

**Comment by m-meier** [comment]
This is a duplicate of #5700. It will be fixed in rc1
