### ISSUE TITLE
Error on Dialog Primevue 3 - 'v-model' directives require no argument

### ISSUE THREAD

**Issue by tudorels** [primefaces/primevue#576]
Hello,

When I try to set dialog with v-model:visible="displayEditForm" it throws error 'v-model' directives require no argument.
If I use the old syntax :visible.sync="displayEditForm", it works but is deprecated (.sync' modifier on 'v-bind' directive is deprecated.)

Thank you!

**Comment by cagataycivici** [comment]
Are you using an extension like Vetur? I also have it, I think this is an IDE related issue. App runs fine right?

**Comment by tudorels** [comment]
App runs fine, and I also find that using a syntax like :visible="displayEditForm" instead of v-model:visible="displayEditForm" it works without the error.
Thanks!

**Comment by cagataycivici** [comment]
Then it seems like an issue with the vue tools support on your end, I think vetur needs to be updated on vscode.
