### ISSUE TITLE
PrimeVue v4 styled mode doesn't work with Tailwind as documented

### ISSUE THREAD

**Issue by minkyn** [primefaces/primevue#5762]
### Describe the bug

According to the v4 document, if I want to use the styled mode with Tailwind CSS, I need to first turn on the cssLayer option:
```typescript
app.use(Prime Vue, {
  theme: {
    preset: Aura,
    options: {
      prefix: 'p',
      darkModeSelector: 'system',
      cssLayer: true,
    },
  },
}
```

Then create a css file (`./assets/style.css`) arranging the layer order:
```css
@layer tailwind-base, primevue, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

However, with this setup, when I experiment a simple page, the styles turn out to come all from Tailwind preflight including the button instead of PrimeVue:
```html
<h1>Home</h1>
<p>Welcome to the Home Page</p>
<Button label="OK" />
```

I tried adjusting the order of importing the css file in `main.ts`:
```typescript
import './assets/style.css'
import PrimeVue from 'primevue/config'
import Aura from 'primevue/themes/aura'
```
as well as
```typescript
import PrimeVue from 'primevue/config'
import Aura from 'primevue/themes/aura'
import './assets/style.css'
```
but neither works.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template

### PrimeVue version

4.0.0-beta3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a style file at `./assets/style.css`:
```css
@layer tailwind-base, primevue, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

2. Setup PrimeVue config in `main.ts`:
```typescript
import { createApp } from 'vue'

import PrimeVue from 'primevue/config'
import Aura from 'primevue/themes/aura'
import './assets/style.css'

import App from './App.vue'

const pinia = createPinia()

const app = createApp(App)

app.use(PrimeVue, {
  theme: {
    preset: Aura,
    options: {
      prefix: 'p',
      darkModeSelector: 'system',
      cssLayer: true,
    },
  },
})

app.mount('#app')
```

3. Create a simple page at `App.vue`:
```html
<template>
  <div>
    <h1>Home</h1>
    <p>Welcome to the Home Page</p>
    <Button label="OK" />
  </div>
</template>
```

### Expected behavior

The heading and paragraph should be rendered in Tailwind CSS preflight, and the button should be rendered in PrimeVue Aura theme.

**Comment by minkyn** [comment]
It looks like it works when I change from `cssLayer: true` to `cssLayer: { name: "primevue" }`

**Comment by m-meier** [comment]
At least in beta 1 (haven't tried it with the latest one yet) you could also specify the order directly in the configuration. It is not documented however, so I don't know if it will stay this way:

`cssLayer: {
        name: "primeui",
        order: "tailwind-base, primeui, primevue, tailwind-utilities;",
      },`

**Comment by minkyn** [comment]
I think the key question I'm asking is about consistency between the public documentation and the actual solution. Hope this can be fixed soon in the coming RC1 release.

**Comment by flmn** [comment]
when using cssLayer: true, you can check developer tools, you will find the layer name is primeui, consistency is the problem.

**Comment by minkyn** [comment]
Here is what I found:
1. When I set `cssLayer: true` or `cssLayer: { name: "primeui" }`, the layer's name defaults to "primeui" instead of "primevue" as documented, but there is no way to rearrange its layer order. `@layer tailwind-base, primeui, tailwind-utilities;` doesn't work. "primeui" always comes at the bottom most layer.
2. In order for the layer ordering to work, I have to use a different layer name (e.g. "primevue"). After `@layer tailwind-base, primevue, tailwind-utilities;`, the DevTools actually shows layer ordering as `primeui, tailwind-base, primevue, tailwind-utilities`; ugly but works. I assume "primeui" was set at the bottom layer by the framework and not able to be changed, so adding a new layer "primevue" is the only workaround I can find now.

**Comment by minkyn** [comment]
Here is what I found in the code:
```typescript
if (cssLayer) {
  var order = themes.SharedUtils.object.getItemValue(cssLayer.order || 'primeui', params);
  return "@layer ".concat(order);
}
```
Maybe the solution is not to add a default `@layer` statement in the framework? Since developers will definitely write their own ordering in the css file when they try to enable `cssLayer` option.

**Comment by f-r3d** [comment]
I had the same problem using Vue 3 + Vite.
I resolved with tailwind guide:
https://tailwindcss.com/docs/guides/vite#vue

Basically I added postcss

**Comment by BenJackGill** [comment]
Any tips to get layers working with PrimeVue + Nuxt?

`nuxt.config.ts` file looks like this (only relevant parts included):
```TypeScript
import Aura from "@primevue/themes/aura";

export default defineNuxtConfig({
  css: ["@/assets/style.css", "@/assets/flags.css"],

  modules: [
    "@primevue/nuxt-module",
    "@nuxtjs/tailwindcss",
    "@nuxt/image",
    "nuxt-vuefire",
    "@nuxt/eslint",
    "@vee-validate/nuxt",
    "@pinia/nuxt",
  ],

  primevue: {
    importTheme: { from: "@/themes/primevue-theme.js" },
    options: {
      theme: {
        options: {
          cssLayer: {
            name: "primevue",
            order: "tailwind-base, primevue, tailwind-utilities",
          },
        },
        preset: Aura,
      },
    },
  },

});
```

`/assets/style.css` file looks like this:
```CSS
@layer tailwind-base, primevue, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

This is what the layers looks like in Chrome Dev Tool (I think this is correct?):
<img width="755" alt="Screenshot 2024-10-17 at 4 10 07 PM" src="https://github.com/user-attachments/assets/7a12762f-79b7-4b6e-a5b7-6ec5aae79b5a">


But the tailwind classes still do not work unless I use `!` to increase it's priority.

Obviously I have missed a step but I'm not sure what.

Any help is appreciated!

**Comment by BenJackGill** [comment]
Ok got it working with Nuxt.

I had to seperate out the layers like this `tailwind-base, primevue, tailwind-components, tailwind-utilities`.

Here is the new code that worked for me:

Inside the `nuxt.config.ts` file:
```
  css: ["@/assets/style.css"],

  primevue: {
    importTheme: { from: "@/themes/primevue-theme.js" },
    options: {
      theme: {
        options: {
          cssLayer: {
            name: "primevue",
            order: "tailwind-base, primevue, tailwind-components, tailwind-utilities",
          },
        },
        preset: Aura,
      },
    },
  },
```

Inside the `/assets/style.css` file:
```
@layer tailwind-base, primevue, tailwind-components, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-components {
  @tailwind components;
}

@layer tailwind-utilities {
  @tailwind utilities;
}
```

**Comment by tugcekucukoglu** [comment]
For more information: https://primevue.org/tailwind/

**Comment by caseytrombley** [comment]
Has anyone resolved this yet? PrimeVue 4 doesn't work with Tailwind despite the documentation saying otherwise

**Comment by corepay** [comment]
@caseytrombley I implemented this is a nuxt3 / nuxt4 compat monorepo with layers...seems to be working well:  https://gearboxgo.com/articles/web-application-development/primevue-with-tailwind-40/

**Comment by jackstruck** [comment]
> [@caseytrombley](https://github.com/caseytrombley) I implemented this is a nuxt3 / nuxt4 compat monorepo with layers...seems to be working well: https://gearboxgo.com/articles/web-application-development/primevue-with-tailwind-40/

@corepay  I followed your guide but still didn't have any success: the primevue component styles are all messed up. You mention installing the @tailwindcss/vite package: do I need to include it as a plugin within my nuxt.config as its [installation guide](https://tailwindcss.com/docs/installation/using-vite) recommends? 

Also I note that you have `@plugin` instead of `@import` in your app.css file, which results in the following error: `Unknown at rule @plugincss` and doesn't match primevue's [instructions](https://primevue.org/tailwind/). Is this intentional? Neither seems to impact my project, however.

**Comment by corepay** [comment]
@jackstruck 

Sorry bud don't know if I can help I started using nuxt-ui several months ago.  I prefer the primevue style/design and really appreciate their hard work but nuxt-ui has a lot of stuff baked in like tailwind4, fonts, images, i18n and color-mode.  Theming is dead simple and for me it reduced the config, troubleshooting and cog overhead a lot.

**Comment by jackstruck** [comment]
@corepay Super appreciate the response 🙏 I will look into nuxt-ui!
