### ISSUE TITLE
Inplace: Traps focus

### ISSUE THREAD

**Issue by pickbreaker** [primefaces/primevue#5770]
### Describe the bug

Inplace traps the focus when tabbing through the page. This is imho not expected behaviour.

### Reproducer

https://stackblitz.com/edit/xw2gex?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by ZiadJ** [comment]
Actually relates to an [older issue](https://github.com/primefaces/primevue/issues/2348#issuecomment-1482689096) which I did not report because it was not a priority back then, at least for me
