### ISSUE TITLE
inputmask: Cannot read properties of undefined (reading 'begin')

### ISSUE THREAD

**Issue by Dav3rs** [primefaces/primevue#5773]
### Describe the bug

Hi, I have been having problems with what I assume is the maskinput, it has never happened to me nor have I been able to replicate it in browserstack, but every day I get these errors in Sentry, and in the clarity recordings I can see that the site crashes when it is produces.

![image](https://github.com/primefaces/primevue/assets/50024128/0569b9a6-799b-4f94-8aba-bfc8c7cb7b25)

And this is a fragment of the referenced script where the crash have place, which lead me to conclude that is on the maskinput component.
![image](https://github.com/primefaces/primevue/assets/50024128/736d6ff1-fc8a-4354-bd96-0df695896a98)

### Reproducer

Unknown, it only happens on mobile according to Sentry errors.

### PrimeVue version

latest (3.52.0)

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

I wasn't able to reproduce. This is how I'm using the component:
```vue
<InputMask
  v-model="text"
  id="phone"
  ref="phoneInput"
  type="tel"
  class="p-inputtext-lg w-full"
  name="phone"
  required
  title="Phone Number"
  mask="(999) 999-9999"
  @blur="validatePhone"
/>
```

**Comment by eyal-egf** [comment]
@Dav3rs 

Have you ever found a solution to this issue? We're getting the same now in Sentry, also coming from the InputMask component.. it seems to happened a lot though we haven't gotten any complaints from users,
are you sure this was a UI blocker (crashes) in your case?


<img width="575" alt="Image" src="https://github.com/user-attachments/assets/ce579a3b-7a72-4aaf-a741-4e546f9602c8" />

**Comment by eyal-egf** [comment]
@Dav3rs Thank you very much for this!! 🙏🏼

**Comment by drenner-versatile** [comment]
Still happening in 2026. Caused by this line in `caret()`

```
if (!this.$el.offsetParent || this.$el !== document.activeElement) {
    return;
}
```
