### ISSUE TITLE
V4 styled mode doesn't work

### ISSUE THREAD

**Issue by jalajc** [primefaces/primevue#5775]
### Describe the bug

As per documenation 
For Vite based setup with primevue @ v4 beta 3, documentation on website mentions
`import PrimeVueStyled from 'primevue/styled';`
Above line is giving errors.

While on github readme page of V4 beta 3 repository, documentation is different. Left me confused as if which documentation is correct and/or outdated.

### Reproducer

Ok 

### PrimeVue version

4.0.0-beta3

### Vue version

3.x

### Language

Javascript

### Build / Runtime

Vite

### Browser(s)

chrome

### Steps to reproduce the behavior

Codespaces and run as documented on website

### Expected behavior

Run styled component without error

**Comment by m-meier** [comment]
You are correct, the Vite Getting started page is outdated. There no longer is a preconfigured module for styled mode I think. 
The initialization described in  https://v4.primevue.org/theming/styled/ works and I assume it will be the default.

**Comment by tugcekucukoglu** [comment]
Documentation is updated. You could use the latest styled mode implementation.
