### ISSUE TITLE
`UseToast` conflicts with Nuxt UI

### ISSUE THREAD

**Issue by RSickenberg** [primefaces/primevue#5776]
### Describe the bug

I'm using the latest revisions of nuxt / nuxt UI and primevue altogether. 

When I want to use a toast, the primevue `useToast` conflicts with `nuxt/ui` one.

### Reproducer

N/A

### PrimeVue version

0.3.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Create a basic Nuxt App with Nuxt/UI then,

try to run `useToast` following their implementation.
The result conflicts.	

### Expected behavior

I expect to have a non.conflicting solution.

**Comment by tugcekucukoglu** [comment]
If you import useToast with a different name, the problem will be solved.

**Comment by JohnCampionJr** [comment]
The problem is that the official Primevue nuxt module imports useToast, so there's not a great way to resolve this.
