### ISSUE TITLE
tree view toggler/expander icon issue

### ISSUE THREAD

**Issue by rathiayush** [primefaces/primevue#578]
tree view expander icon available even after setting up property **leaf** to true. It is working fine in treetable but not in treeview.

**Comment by rathiayush** [comment]
#579 Possible fix

**Comment by ayush-intersof** [comment]
@cagataycivici any update?

**Comment by cagataycivici** [comment]
I am not able to replicate, 'p-treenode-leaf' hides it already, please provide a code sandbox or a sample GitHub repo if the issue persists.
