### ISSUE TITLE
PrimeVue v4 tokens missing a lot from v3

### ISSUE THREAD

**Issue by minkyn** [primefaces/primevue#5782]
### Describe the bug

In PrimeVue v3, there are many theme variables available to customize, such as "--text-color", "--surface-ground", "--font-family", etc.

In PrimeVue v4, those are all missing, with much fewer customizable tokens found at [here](https://v4.primevue.org/theming/styled/#customization). And the Figma UI Kit hasn't matched those yet.

What shall we expect? Will v4 be adding more semantics tokens later? Or will those we see now be just what it will be eventually in v4? And when will a v4-matched Figma UI Kit be available?

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-typescript-issue-template

### PrimeVue version

v4.0.0-beta3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
`tailwindcss-primeui` plugin can be used for this purpose. For more information https://v4.primevue.org/tailwind/
