### ISSUE TITLE
Fieldset collapsed automatically

### ISSUE THREAD

**Issue by alqa-dash** [primefaces/primevue#5793]
### Describe the bug

When Fieldset is an item of array 

```
  <div class="card" v-for="(card, index) in cards" :key="index">
    <Fieldset :legend="card" :toggleable="true">
      <template #legend>
        <div class="flex align-items-center">
          <Button
            icon="pi pi-times"
            severity="danger"
            text
            @click="deleteCard(index)"
          ></Button>
          <span>{{ card }}</span>
        </div>
      </template>
      <p class="m-0">
        Lorem ipsum...
      </p>
    </Fieldset>
  </div>
```

and one can remove items so that if penultimate Fieldset is deleted, the last Fieldset becomes collapsed.

### Reproducer

https://stackblitz.com/edit/jemp9e?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click "delete" button on second Fieldset
2. The last Fieldset becomes collapsed

### Expected behavior

Expanded Fieldset remains expanded

**Comment by ZiadJ** [comment]
Seems like expected behavior to me. How about using `stopPropagation` as workaround? Here's an updated version using it:
https://stackblitz.com/edit/jemp9e-apomx5?file=src%2FApp.vue

**Comment by alqa-dash** [comment]
Thank you very much! This was exactly what I need.

**Comment by ZiadJ** [comment]
Alternatively, you can use `:key="card"` to be sure to get a unique Id.
