### ISSUE TITLE
DataTable: headers are missing in responsive layout

### ISSUE THREAD

**Issue by AniaKru95** [primefaces/primevue#5799]
### Describe the bug

DataTable headers do not display properly, using #header slot and stack responsiveLayout.

### Reproducer

https://stackblitz.com/edit/2enqv4?file=src%2FApp.vue

### PrimeVue version

3.32.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Create simple Datatable
2. Put responsiveLayout="stack"
3. Remove 'header' from datatable props
4. Add template 'header' 
5. Place labels to template header
6. Check on mobile screen

### Expected behavior

Display headers on mobile screens

**Comment by tugcekucukoglu** [comment]
Stack mode is deprecated. Please try to use the new implementation.

**Comment by AniaKru95** [comment]
Is new implementation responsive?
