### ISSUE TITLE
Paginator: The `Previous Page` translation key in config.locale is different from that in primelocale

### ISSUE THREAD

**Issue by kevin82222** [primefaces/primevue#5801]
### Describe the bug

In the plugin configuration, the `locale.aria.prevPageLabel` is different from [primelocale](https://github.com/primefaces/primelocale).
The `primelocale`'s key is `previousPageLabel`.

### Reproducer

PrimeVue 3 Issue Template not found.

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

On the `previous page` link, there should be a correctly translated `aria-label` attribute.

**Comment by melloware** [comment]
I agree with this change. PrimeFaces and PrimeReact already use this label.

**Comment by tugcekucukoglu** [comment]
PrimeVue uses the correct name. PrimeLocale should be updated.

**Comment by melloware** [comment]
@tugcekucukoglu i think PrimeVue needs to update as PrimeFaces JSF and PrimeReact use `previousPageLabel`

PrimeReact: https://github.com/primefaces/primereact/blob/master/components/lib/paginator/PrevPageLink.js#L41

PrimeFaces JSF: https://github.com/primefaces/primefaces/blob/ac8ec841b0529491fd77f1aced3379409c64135f/primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js#L102-L109
