### ISSUE TITLE
primevue@4.0.0-beta.4: toast and confirm are broken

### ISSUE THREAD

**Issue by ilearnio** [primefaces/primevue#5803]
### Describe the bug

Just upgraded from primevue v3 to v4.0.0-beta.4 and the main issues I have are `No PrimeVue Confirmation provided!` and `Error: No PrimeVue Toast provided!`. 

![image](https://github.com/primefaces/primevue/assets/14331216/970cd02e-244c-4b42-acd4-a6059aff5100)

According to https://v4.primevue.org/confirmdialog/ , the setup for v4 looks the same as it was for v3 and it seems to me that I have it as it should be.

So I have this in my main.ts
```
app.use(ToastService)
app.use(ConfirmationService)
```

I have added the components to my root `App.vue` and I am using `const toast = useToast()` but there's something wrong with the symbols of both useToast and useConfirm

### Reproducer

-

### PrimeVue version

4.0.0-beta.4 + vite@^4.3.9

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome, MacOS

### Steps to reproduce the behavior

1. Follow this setup instructions https://v4.primevue.org/confirmdialog/
2. See error when opening toast of confirmation. 

### Expected behavior

should work

**Comment by m-meier** [comment]
Have you imported Toast und added it to your template? It seems to work fine for me with beta4:
https://stackblitz.com/edit/vitejs-vite-5jjxem?file=src%2Fmain.js,src%2FApp.vue

**Comment by ilearnio** [comment]
Hm, yeah, my setup looks identical. But I'll give it another look today

**Comment by AntonioPrimera** [comment]
I have the same issue and the setup seems to be the same. The code worked on v3 without any change.

As context: I'm using it in a Laravel + Inertia app and just added primevue for the Toast component.

**Comment by calumk** [comment]
For future googlers.... - I had an issue that was related to this. 
I was using the primevueresolver from unplug

```
import { PrimeVueResolver } from 'unplugin-vue-components/resolvers'
```
Everything worked except the toasts.... 
I had to aswitch to using the  "official" resolver 
```
import {PrimeVueResolver} from '@primevue/auto-import-resolver';
```
