### ISSUE TITLE
Vite Compatibility

### ISSUE THREAD

**Issue by YannikSc** [primefaces/primevue#581]
## The problem

When using Vue 3 and Vite for building PrimeVue components can't be used as they throw a `Uncaught SyntaxError: import not found: default` in the browser console.

Vite also give a warning for PrimeVue: `[vite] cannot resolve entry for dependency primevue.`

## Reproduce

```bash
# Setup Vue 3 with Vite as described on vuejs.org 
npm init vite-app hello-vue3 # OR yarn create vite-app hello-vue3
cd hello-vue3
npm install

# Install PrimeVue 3 as primefaces.org describes
npm install primevue@^3.0.0 --save

# Import any component in the src/main.js file
# Like the dialog (import Dialog from 'primevue/dialog';)

# Run vite
npm run dev

# Open http://localhost:3000/ (or similar) in your browser an open the console
```

**Comment by Zony-Zhao** [comment]
Same problem here.
![image](https://user-images.githubusercontent.com/50739849/96575171-008cf700-1303-11eb-9ab1-2f020fa1338e.png)
I managed to have a workaround to pass compilation, but run time error occurs:
![image](https://user-images.githubusercontent.com/50739849/96575263-20bcb600-1303-11eb-8b6b-46123b5d099f.png)

**Comment by Zony-Zhao** [comment]
For anyone comes to this.
https://github.com/vitejs/vite/issues/933.
Can PrimeVue guys export these js module as es module for vite to work?

**Comment by cagataycivici** [comment]
Vite support is in our high priority list, I'll be keeping this issue updated.

**Comment by nandin-borjigin** [comment]
Any update on this ?

**Comment by cagataycivici** [comment]
Planned for next week!

**Comment by tudorels** [comment]
It's very good news!

**Comment by cagataycivici** [comment]
In progress...

<img width="765" alt="Screen Shot 2021-01-18 at 14 27 59" src="https://user-images.githubusercontent.com/686247/104910001-bebf2b80-5999-11eb-83f0-d4d9a3e681e7.png">

**Comment by cagataycivici** [comment]
Resolved for 3.2.0-rc.1, I'll create a simple Quickstart example repo as well.

**Comment by thiago-figueiredo** [comment]
When will it be possible to install this RC? Do you know? I see no such tag on the repo.

**Comment by cagataycivici** [comment]
Later this week.

**Comment by Fonz001** [comment]
After a long search, came by this thread. Good to see that this is going to be picked up!

**Comment by cagataycivici** [comment]
Try 3.2.0-rc.1 please also we have a [starter](http://github.com/primefaces/primevue-quickstart-vite) app now.

**Comment by lewebsimple** [comment]
Though the starter app works fine (with warnings about <script setup> being experimental), I can't get 3.2.0-rc.1 to import with TypeScript:
```
Module '".../vite-primevue/node_modules/primevue/config/PrimeVue"' has no default export.ts(1192)
```

I'm using the vue-ts preset with `yarn create @vitejs/app` to which I added primevue / primeicons.

**Comment by makurtu** [comment]
I can confirm that, as @lewebsimple said, PrimeVue 3.2.0-rc.1 is not working as expected if you are using TypeScript.

I moved back to `primevue@3.1.2` until TS support.

**Comment by EthanHaid** [comment]
You can get around that issue with 
`import * as PrimeVue from 'primevue/config';`
though a default export should be added eventually to avoid this

**Comment by slumtrimpet** [comment]
> You can get around that issue with
> `import * as PrimeVue from 'primevue/config';`
> though a default export should be added eventually to avoid this

That gets around the hard stop on being able to use 3.2.0-rc.1 with vite/typescript at all... but in the browse console it still throws:

`[Vue warn]: A plugin must either be a function or an object with an "install" function.`

**Comment by slumtrimpet** [comment]
> > You can get around that issue with
> > `import * as PrimeVue from 'primevue/config';`
> > though a default export should be added eventually to avoid this
> 
> That gets around the hard stop on being able to use 3.2.0-rc.1 with vite/typescript at all... but in the browse console it still throws:
> 
> `[Vue warn]: A plugin must either be a function or an object with an "install" function.`
> 
> On the line:
> 
> `app.use(PrimeVue)`

Following up on myself and @EthanHaid... this imports DOES work and doesn't gripe about anything in the console:

```
import PrimeVue from 'primevue/config/config.esm'
```

Also, because the impact is even more evident on this module, the following gets the PrimeVue ToastService to work in vite/typescript:

```
import ToastService from 'primevue/toastservice/toastservice.esm'
```

**Comment by lewebsimple** [comment]
@slumtrimpet I'm getting a missing definition error when importing from `primevue/config/config.esm` ... I've enabled allowJs in tsconfig.
What works in my case without console warning produces a (harmless) ts(1192) about no default export, which I ignore with  `@ts-expect-error`

Any idea ?

**Comment by Anubarak** [comment]
Is there any plan to include this in the vue2 version as well?
So in your PrimeVue v2 
https://github.com/primefaces/primevue/releases/tag/2.10.4
