### ISSUE TITLE
Import Error in Nuxt 3 with PrimeVue v4: Unable to Import from theme.js

### ISSUE THREAD

**Issue by khaledOghli** [primefaces/primevue#5810]
### Describe the bug

When using PrimeVue v4 with Nuxt 3, there is an issue with importing from theme.js for example. Specifically, attempting to import { definePreset } from 'primevue/themes' results in an error.

To Reproduce:

Set up a Nuxt 3 project.
Install PrimeVue v4.
Attempt to import { definePreset } from 'primevue/themes' in theme.js.
Example import statement:
```
import { definePreset } from 'primevue/themes';
```
Observe the following error:
```
ERROR  [worker reload] [worker init] Directory import '/home/projects/node_modules/primevue/themes' is not supported resolving ES modules imported from /home/projects/theme.js
Did you mean to import primevue/themes/index.mjs?
```

Minimal Reproduction Example:
A minimal reproduction of the issue can be found here: [https://stackblitz.com/edit/nuxt-starter-dhgcfm](https://stackblitz.com/edit/nuxt-starter-dhgcfm)

### Reproducer

https://stackblitz.com/edit/nuxt-starter-dhgcfm

### PrimeVue version

4.0.0-beta.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by patriciorivera** [comment]
Same here.

**Comment by kevynbarbosa** [comment]
I got this error too

**Comment by Truimo** [comment]
I was also here.

**Comment by Masanix** [comment]
I got the same error.

**Comment by mkalinski93** [comment]
I cannot add any theme. The entire primevue components are unstyled and I can´t seem to find a way to apply the Aura theme to the components so far

**Comment by khaledOghli** [comment]
> I cannot add any theme. The entire primevue components are unstyled and I can´t seem to find a way to apply the Aura theme to the components so far

Yeah, same here unfortunately

**Comment by patriciorivera** [comment]
> I cannot add any theme. The entire primevue components are unstyled and I can´t seem to find a way to apply the Aura theme to the components so far

same.

**Comment by roobr** [comment]
Same

**Comment by Bomberus** [comment]
For me components style just disappeared when using 4.0.0-beta.4. It seems in the npm package the themes directory is missing completely. Downgrading to 4.0.0-beta.3 works though.

**Comment by mkalinski93** [comment]
> For me components style just disappeared when using 4.0.0-beta.4. It seems in the npm package the themes directory is missing completely. Downgrading to 4.0.0-beta.3 works though.

can you upload a stackblitz example on how you´ve setup the theme exactly?

**Comment by patriciorivera** [comment]
same problem here.

**Comment by jackiboy** [comment]
@mkalinski93 I hade to use commonJS with beta3.

Here is my config file `theme.cjs` and the nuxt config below.

```js
const config = require("primevue/themes/actions");
const Aura = require("primevue/themes/aura");

const MyPreset = config.definePreset(Aura, {
  semantic: {
    primary: {
      50: "{zinc.50}",
      100: "{zinc.100}",
      200: "{zinc.200}",
      300: "{zinc.300}",
      400: "{zinc.400}",
      500: "{zinc.500}",
      600: "{zinc.600}",
      700: "{zinc.700}",
      800: "{zinc.800}",
      900: "{zinc.900}",
      950: "{zinc.950}",
    },
    colorScheme: {
      light: {
        primary: {
          color: "{zinc.950}",
          inverseColor: "#ffffff",
          hoverColor: "{zinc.900}",
          activeColor: "{zinc.800}",
        },
        highlight: {
          background: "{zinc.950}",
          focusBackground: "{zinc.700}",
          color: "#ffffff",
          focusColor: "#ffffff",
        },
      },
      dark: {
        primary: {
          color: "{zinc.50}",
          inverseColor: "{zinc.950}",
          hoverColor: "{zinc.100}",
          activeColor: "{zinc.200}",
        },
        highlight: {
          background: "rgba(250, 250, 250, .16)",
          focusBackground: "rgba(250, 250, 250, .24)",
          color: "rgba(255,255,255,.87)",
          focusColor: "rgba(255,255,255,.87)",
        },
      },
    },
  },
});

module.exports = {
  preset: MyPreset,
  options: {
    darkModeSelector: ".p-dark",
  },
};

```

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  srcDir: "src/",

  modules: ["nuxt-primevue"],

  // primevue
  primevue: {
    importTheme: { from: "@/config/theme/theme.cjs" },
    options: {
      ripple: true,
    },
  },

  css: ["@/assets/css/main.css"],

  devtools: { enabled: false },
});

```

**Comment by khaledOghli** [comment]
> > For me components style just disappeared when using 4.0.0-beta.4. It seems in the npm package the themes directory is missing completely. Downgrading to 4.0.0-beta.3 works though.
> 
> can you upload a stackblitz example on how you´ve setup the theme exactly?


i start with new nuxt 3 project in stackblitz , then i go step by step using primevue v4 docs 
https://v4.primevue.org/nuxt/

here is reprod:
https://stackblitz.com/edit/nuxt-starter-hnkdol?file=theme.js

**Comment by jackiboy** [comment]
I can confirm the the RC.1 has fixed this issue.

See a minimal example here:

https://stackblitz.com/edit/nuxt-starter-s3qlvs?file=theme.js

**Comment by khaledOghli** [comment]
> I can confirm the the RC.1 has fixed this issue.
> 
> See a minimal example here:
> 
> https://stackblitz.com/edit/nuxt-starter-s3qlvs?file=theme.js

Yeah, the issue is now fixed with RC.1 Version

**Comment by mertsincan** [comment]
Thanks a lot for the updates! 

Best Regards,
