### ISSUE TITLE
RadioButton

### ISSUE THREAD

**Issue by Semsveta** [primefaces/primevue#5812]
### Describe the bug

The inputClass and inputStyle props on the component are not affecting the input element style.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-zrgxp1?file=README.md,src%2FApp.vue,src%2Fmain.js

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

Add the props to the component and try to add style to the input.

**Comment by tugcekucukoglu** [comment]
You can see that inputStyle and inputClass are added to the DOM correctly. It would help if you tried to use the pt property: https://primevue.org/radiobutton/#pt.doc.radiobutton

**Comment by Semsveta** [comment]
Thank you for getting back. You are right - it's adding class and style to the DOM, however doesn't have impact on the input element. I tried pass trough prop:  pt input style works, but if I add pt input class doesn't have an effect. I have updated https://stackblitz.com/edit/vitejs-vite-zrgxp1?file=README.md,src%2FApp.vue,src%2Fmain.js
