### ISSUE TITLE
Passthrough attributes not applied to InputText inside Password component

### ISSUE THREAD

**Issue by trombonist76** [primefaces/primevue#5814]
### Describe the bug

Hello! I am using Password component but nested passthrough attributes not effects InputText component inside Password component.

`<p-password v-model="inputValue" :pt="{ input: { class: 'w-full' } }" w-full/>`

![Screenshot 2024-04-06 at 01 22 33](https://github.com/primefaces/primevue-nuxt-module/assets/66271151/bb9e07ec-3a19-4a8d-99b3-d36e02f1f942)

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-igbt4w?file=app.vue

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Arc

### Steps to reproduce the behavior

1- Add the Password component in your template and attempt to pass through nested attributes

```
<template>
    <div>
        <password v-model="inputValue" :pt="{ input: { class: 'w-full' } }"/>
    </div>
</template>
```

2- Observe that the nested passthrough attribute for input does not affect the InputText component inside the Password component as expected.

### Expected behavior

The nested passthrough attributes should be correctly applied to the InputText component inside the Password component. In this case, the class w-full should be added to the input element inside the Password component, causing the input field to take the full width of its container.

**Comment by blevinelrp** [comment]
This is also an issue in version "4.0.0-beta.4".

pcInput passthrough is not making it to the nested InputText.

**Comment by dinyo** [comment]
try:
`:pt="{ input: { root: { class: 'w-full' } } }"`

https://github.com/orgs/primefaces/discussions/2007#discussioncomment-9531521

**Comment by blevinelrp** [comment]
> try: `:pt="{ input: { root: { class: 'w-full' } } }"`
> 
> https://github.com/orgs/primefaces/discussions/2007#discussioncomment-9531521

That works (and that behavior makes sense).

Updating the passthrough docs for each component that uses nested components would probably help to eliminate a lot of the confusion (For example, the "description" column could include a link to the passthrough docs for the child component).

**Comment by beijixiaohu** [comment]
> try: `:pt="{ input: { root: { class: 'w-full' } } }"`
> 
> https://github.com/orgs/primefaces/discussions/2007#discussioncomment-9531521

Thanks a ton! I've been searching online forever and finally found the right answer. Really appreciate it!

**Comment by reitbauer** [comment]
> try: `:pt="{ input: { root: { class: 'w-full' } } }"`
> 
> https://github.com/orgs/primefaces/discussions/2007#discussioncomment-9531521

This does not work for me in version 4.0.0-rc.1

**Comment by trombonist76** [comment]
It is replaced with pcInput

**Comment by trombonist76** [comment]
> > try: `:pt="{ input: { root: { class: 'w-full' } } }"`
> > 
> > https://github.com/orgs/primefaces/discussions/2007#discussioncomment-9531521
> 
> This does not work for me in version 4.0.0-rc.1

input replaced with pcInput you can check the documentation
https://primevue.org/password/

**Comment by reitbauer** [comment]
> > > try: `:pt="{ input: { root: { class: 'w-full' } } }"`
> > > https://github.com/orgs/primefaces/discussions/2007#discussioncomment-9531521
> > 
> > 
> > This does not work for me in version 4.0.0-rc.1
> 
> input replaced with pcInput you can check the documentation https://primevue.org/password/

My bad. many thanks

**Comment by ljubodrag** [comment]
For PrimeVue v3 this is what worked for me:

```
:pt="{
  pcInputText: {
    root: {
      class: 'my-password-input',
    }
  },
  root: {
    class: 'my-password-root',
  },
}"
```
