### ISSUE TITLE
Dialog: Displaced button

### ISSUE THREAD

**Issue by joaomarcelofm** [primefaces/primevue#5817]
### Describe the bug

The close button gets displaced depending on the size of the header content. The image below, of course, is an extrapolation of the issue to showcase it. However, I'd expect that action buttons that have a clear relationship to the layout, instead of the content itself, would remain unchanged based on content changes:

<img width="428" alt="Screenshot 2024-06-03 at 08 21 29" src="https://github.com/primefaces/primevue/assets/30631810/6e448d64-e359-41be-938b-9aa98bc8ebfe">

### Reproducer

https://stackblitz.com/edit/fnv4cr?file=src%2FApp.vue

### PrimeVue version

3.*

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

All

### Steps to reproduce the behavior

1. Open dialog
2. See displaced button

### Expected behavior

Button should be placed in relation to the layout, not the header's content.

**Comment by tugcekucukoglu** [comment]
This visual defects can be solved using pt property for Dialog component: 

```
:pt="{
     header: {
        style: { 'align-items': 'flex-start' }
     }
}"
```

**Comment by joaomarcelofm** [comment]
@tugcekucukoglu if this is a "defect" why close the issue instead of raising it as a bug? 😕
