### ISSUE TITLE
Button disabling not working dynamically

### ISSUE THREAD

**Issue by dhanushkac** [primefaces/primevue#583]
I tried creating a disabled button as below.

`<Button label="Disabled" disabled="disabled" />`

No matter what value I give, the button will be disabled as long as `disabled` attribute has it. 

Expected:

`<Button label="Disabled" disabled />` & `<Button label="Disabled" disabled="isDisabled" />` should be only case that disables the button when `isDisabled` is true. when `isDisabled` is false button should be enabled.

**Comment by LadislavBohm** [comment]
If you want to bind some value to an attribute in Vue, you have to different syntax. For example like this:

<Button label="Disabled" :disabled="isDisabled" />

Notice ':' before disabled.

**Comment by dhanushkac** [comment]
> If you want to bind some value to an attribute in Vue, you have to different syntax. For example like this:
> 
> ```
> <Button label="Disabled" :disabled="isDisabled" />
> ```
> 
> Notice ':' before disabled.

Yes. My concern is that the given attribute behaviour is unexpected.

**Comment by dheimoz** [comment]
Hello dhanushkac, I had trouble to understand v-bind at first. For example, with v-model you pass the variable declared at data and you are done. With events you also specify the function name declared at methods and that´s it.
However, as LadislavBohm pointed out, if you are passing a variable declared at data you need to use either the long form v-bind:disabled="disabled" or just :disabled="disabled.
For more in depth information, please take a look at this:

https://vuejs.org/v2/guide/syntax.html#Using-JavaScript-Expressions

And remember, if you sorted the problem, please close the issue.

Thanks.

**Comment by cagataycivici** [comment]
This is the expected behavior, disabled is an enumerated property like readonly, draggable so a binding is required to control it.

**Comment by dhanushkac** [comment]
@cagataycivici 

`<Button label="Disabled" disabled="disabled" />` and `<Button label="Disabled" disabled />` is giving the same result. Any benefit of adding `disabled="disabled"`? 

What I thought is, since this is a component that should allow with dynamic behaviour. anyway that `:disabled` solved the initial issue. but my above concern is still there.
