### ISSUE TITLE
4.0.0-beta.4 InputText size prop doesnt work

### ISSUE THREAD

**Issue by TomasSimkus** [primefaces/primevue#5839]
### Describe the bug

In the 4.0.0-beta.4 version, the InputText component size prop is not working

### Reproducer

https://stackblitz.com/edit/rzyceg?file=src%2FApp.vue

### PrimeVue version

4.0.0-beta.4

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

**Comment by cagataycivici** [comment]
Added for RC.1, thanks.
