### ISSUE TITLE
PrimeVue 3 Sample code

### ISSUE THREAD

**Issue by BenHayat** [primefaces/primevue#584]
Hello Team;

Where can I find a Sample project for PrimeVue 3?
I want to see how a PrimeVue project is setup with proper settings.

Thanks

**Comment by LadislavBohm** [comment]
Example setup from their documentation worked fine for me. As for project there is this for example:

https://github.com/primefaces/primevue-typescript-quickstart

**Comment by BenHayat** [comment]
> 
> 
> Example setup from their documentation worked fine for me. As for project there is this for example:
> 
> https://github.com/primefaces/primevue-typescript-quickstart

Thanks... After posting here I saw the link in docs
