### ISSUE TITLE
Browser Infinite Waiting State Error When Using VirtualScroll in MultiSelect Component

### ISSUE THREAD

**Issue by scarlet0o0** [primefaces/primevue#5846]
### Describe the bug

We are currently using PrimeVue effectively in our project. However, when a large amount of data exists in the MultiSelect and VirtualScroll is applied, clicking the select-all checkbox, closing the select box, and then reopening it causes the browser to enter an infinite waiting state. Is there a solution for this?

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

https://github.com/primefaces/primevue/assets/67679972/a845bd68-99ed-46f3-affa-6be2519bd821

**Comment by 1Map** [comment]
They have a "for loop" on MultiSelect (findSelectedOptionIndex).  This takes forever when there are 100,000 records and hangs...

https://github.com/primefaces/primevue/blob/401dd225677796f05321b0c98ac68b51f3487de6/components/lib/multiselect/MultiSelect.vue#L852

**Comment by luixal** [comment]
Maybe related to #6177 ?
