### ISSUE TITLE
Tailwind Dropdown Float Label: Label is always floated

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue#5849]
### Describe the bug

I am using Tailwind PrimeVue with the latest Aura preset.

The Dropdown Float Label feature does not work correctly because the label is always floated, even when no value is selected from the dropdown.

I'm not sure if this is a bug, or the dropdown float label feature is not yet supported on Tailwind PrimeVue. If it is the latter, can I please request the feature is added. It's very helpful for creating forms.

Here is a screenshot showing the problem where no value is selected but the label is still floated. It is using Tailwind PrimeVue and the latest Aura presets:

![Screenshot 2024-06-07 at 11 07 52 AM](https://github.com/primefaces/primevue/assets/2043257/6229d6c6-982e-4b2c-b66e-8de731e85ad2)

Here is a screenshot of how it should look. It was taken from the [main PrimeVue docs](https://primevue.org/dropdown/#floatlabel):

![Screenshot 2024-06-07 at 11 09 43 AM](https://github.com/primefaces/primevue/assets/2043257/42acbff9-59e0-4cdf-af16-4309bafc4796)

**Example Code:**

```Vue
<template>
  <div class="m-10">
    <FloatLabel class="w-full">
      <Dropdown
        v-model="selectedCity"
        inputId="dd-city"
        :options="cities"
        optionLabel="name"
        class="w-full"
      />
      <label for="dd-city">Select a City</label>
    </FloatLabel>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const selectedCity = ref();
const cities = ref([
  { name: 'New York', code: 'NY' },
  { name: 'Rome', code: 'RM' },
  { name: 'London', code: 'LDN' },
  { name: 'Istanbul', code: 'IST' },
  { name: 'Paris', code: 'PRS' },
]);
</script>
```

### Reproducer

https://stackblitz.com/edit/nuxt-starter-aq6fq2?file=package.json

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Go to the [reproduction link](https://stackblitz.com/edit/nuxt-starter-aq6fq2?file=package.json) and see that the label is floated before selecting a dropdown option.

### Expected behavior

The label should only be floated after selecting a dropdown option.

**Comment by tugcekucukoglu** [comment]
This is not a core issue. could you create an issue for this repo: https://github.com/primefaces/primevue-tailwind ?
