### ISSUE TITLE
FileUpload Preview columns become misaligned when both image and non-image files are uploaded

### ISSUE THREAD

**Issue by Christoph-Wagner** [primefaces/primevue#585]
This affects both the Vue 2 and 3 version of PrimeVue and can be seen [at the showcase](https://www.primefaces.org/primevue/showcase/#/fileupload) by selecting an image file and a text file:

![image](https://user-images.githubusercontent.com/1609329/96422776-fd511880-11e7-11eb-9435-d7661eb8ee18.png)

It’s because the row has

```vue
<div v-if="isImage(file)">
    <img role="presentation" :alt="file.name" :src="file.objectURL" :width="previewWidth" />
</div>
```

a simple solution would be to do

```vue
<div>
    <img v-if="isImage(file)" role="presentation" :alt="file.name" :src="file.objectURL" :width="previewWidth" />
</div>
```

instead, but I guess that would be suboptimal if only non-images are uploaded.

**Comment by cagataycivici** [comment]
Should be fine with your suggestion, thanks.
