### ISSUE TITLE
Menu: Popup is not hiding on click

### ISSUE THREAD

**Issue by sadiqkhoja** [primefaces/primevue#5853]
### Describe the bug

The popup of menu is not closing fast enough. When I am using `window.print()` as the command of the a menu item, the menu is also printed. See the attached stackblitz link.

I have also tried `nextTick()`, but menu is still printed.

### Reproducer

https://stackblitz.com/edit/cewres?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to stackblitz link
2. Click on the button
3. Click on the print button

See menu is also printed

### Expected behavior

Menu popup is not visible in the print preview.

**Comment by ZiadJ** [comment]
Have you tried using `setTimeout` instead?

**Comment by sadiqkhoja** [comment]
yes @ZiadJ setTimeout works but with at least 100ms. I am not sure if that the best thing to do

**Comment by tugcekucukoglu** [comment]
Since Tieredmenu uses transition in Vue, it may be necessary to consider the transition-duration.

**Comment by sadiqkhoja** [comment]
I ended up with hiding the menu via `@media print `
