### ISSUE TITLE
TreeTable: Row Index is not accessible

### ISSUE THREAD

**Issue by hasan75** [primefaces/primevue#5855]
### Describe the bug

In **TreeTable** Component, While Using body slot in Column, **index** cannot be accessible.

     <Column header="SN" expander>
         <template #body="slotProps">
           {{ slotProps.index }}
         </template>
      </Column>

  Here The Row Index is displaying.

### Reproducer

https://stackblitz.com/edit/treetable-rowindex-bug?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. open app.vue page
2. See there's no content in the "SN" column

### Expected behavior

There Should be numeric value like 0,1,2.. in the "SN" column according to the row index

**Comment by Aakash-Sondagar** [comment]
@hasan75 
{{ slotProps?.node?.key?.length == 1 ? slotProps.node.key : slotProps.node.key.slice(-1) }}
try this workaround

![image](https://github.com/primefaces/primevue/assets/89018309/772a5a9d-c161-449c-8fe7-55deea1f5a3d)

**Comment by hasan75** [comment]
@Aakash-Sondagar Thanks for the workaround. But documentation says index is accessable.
