### ISSUE TITLE
Tree: Integration with ContextMenu

### ISSUE THREAD

**Issue by steve-ky** [primefaces/primevue#5864]
### Describe the bug

I need to add context menu to Tree component, similar with DataTable exclusive integration with ContextMenu. 
Is there any way to do this?

### Reproducer

none

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Tree with context menu , similar with DataTable exclusive integration with ContextMenu.

**Comment by tugcekucukoglu** [comment]
You could use discussions or Discord channel for demo requests.
