### ISSUE TITLE
Calendar: Keydown Event not firing

### ISSUE THREAD

**Issue by JohnCampionJr** [primefaces/primevue#5870]
### Describe the bug

Attach an event to keydown event of Calendar, and it will not fire when keys are entered in input.

### Reproducer

Stackblitz not working

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by andrew-cmdltt** [comment]
I have a both problem if I understand you clearly. When I try to bind enter button press event with filterCallback by this line @keydown.enter="filterCallback()" and don't get such result as a filter fields. This problem also  has a place to be in v4 of Primevue.
