### ISSUE TITLE
DataTable column filters stop working after navigating to next page

### ISSUE THREAD

**Issue by Falloucik** [primefaces/primevue#588]
Welcome, 
after navigating to next page in DataTable example and then trying to filter the results by Name/Country the Table doesn't show any results until the user sorts them. I'm wondering if this is a bug, the behavior on the first page is different and the global filter seems to be working fine on other pages. I've encountered the same problem working on my project.

**Comment by tugcekucukoglu** [comment]
Could you test it again?

[https://primefaces.org/primevue/showcase/#/datatable/filter](https://primefaces.org/primevue/showcase/#/datatable/filter)

**Comment by cagataycivici** [comment]
Unable to replicate, if the issue persists please create a new ticket with a test case reproducing the issue e.g. code sandbox or a github repo and it will be reviewed by our team once again.
