### ISSUE TITLE
Where can I find sample code for the homepage template?

### ISSUE THREAD

**Issue by cc-7z** [primefaces/primevue#5885]
![微信图片_20240614134114](https://github.com/primefaces/primevue/assets/62325709/dc3d315f-d8ad-4c56-85d7-97657eb71fa1)

![image](https://github.com/primefaces/primevue/assets/62325709/1df08b25-01d5-439d-9c18-7d499ba86e35)

Where can I find the sample code for these templates? Can you give me a link?

**Comment by coderabsolute** [comment]
Even, I'm looking for it.

**Comment by tugcekucukoglu** [comment]
https://github.com/primefaces/primevue/blob/master/apps/showcase/components/landing/samples/OverviewApp.vue
