### ISSUE TITLE
Documentation: Documentation for Dropdown returns 404

### ISSUE THREAD

**Issue by sdoerger** [primefaces/primevue#5888]
### Describe the bug

Currently the documentatin for <Dropdown> has vanished. https://primevue.org/dropdown/ return 404 and the component is not finable in the documentation either.

Was it renamed?

### Reproducer

https://primevue.org/dropdown/

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

Go to https://primevue.org/dropdown/

**Comment by mertsincan** [comment]
Hi,
Renamed with <Select> in v4. Please use https://primevue.org/select/

Best Regards,
