### ISSUE TITLE
BaseComponent: Browser DevTools Console displays a warning when using Primevue v4 components with Nuxt

### ISSUE THREAD

**Issue by luke-z** [primefaces/primevue#5889]
### Describe the bug

When refreshing a page I get the following warning:
``` [nuxt] Could not access `pt`. The only available runtime config keys on the client side are `public` and `app` ```

When following the stacktrace, I end up around here:

https://github.com/primefaces/primevue/blob/917ef22d9a4afcea0c59d1e4644218b3f0dcd222/packages/core/src/basecomponent/BaseComponent.vue#L65

We are using Nuxt 3.12.1

### Reproducer

https://stackblitz.com/edit/nuxt-starter-dr71ht

### PrimeVue version

4.0.0-rc.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Brave

### Steps to reproduce the behavior

1. Open the website
2. Open the browser dev tools console
3. Refresh the page

### Expected behavior

No warnings

**Comment by borsTiHD** [comment]
I think these issues are the same:  
- https://github.com/primefaces/primevue/issues/5895
- Primvue Nuxt Module: https://github.com/primefaces/primevue-nuxt-module/issues/69

**Comment by Tarabass** [comment]
> I think these issues are the same:
> 
>     * [[nuxt] Could not access pt. The only available runtime config keys on the client side are public and app #5895](https://github.com/primefaces/primevue/issues/5895)
> 
>     * Primvue Nuxt Module: [[nuxt] Could not access `pt`. The only available runtime config keys on the client side are `public` and `app` primevue-nuxt-module#69](https://github.com/primefaces/primevue-nuxt-module/issues/69)

Yes, they are. Except that this issue is on v4rc and the other is on v3.52 :)

**Comment by mertsincan** [comment]
Please see; https://github.com/primefaces/primevue/issues/5895#issuecomment-2170978918
