### ISSUE TITLE
Overriding ProgressSpinner colors doc error

### ISSUE THREAD

**Issue by cooliopas** [primefaces/primevue#589]
On docs at [https://primefaces.org/primevue/showcase/#/progressspinner](url) says you can change spinner colors by overriding:

`@keyframes ui-progress-spinner-color {`

but it should be:

`@keyframes p-progress-spinner-color {`

Also, I had to change the order of imports to have it working, otherwise the original keyframes animation css was applied.

So, instead of using the imports order like said on [https://github.com/primefaces/primevue-quickstart/blob/master/src/main.js](url):

```
import { createApp } from 'vue'
import App from './App.vue';

import ProgressSpinner from 'primevue/progressspinner';

import 'primevue/resources/themes/saga-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';

const app = createApp(App);
```

... I had to change to:

```
import { createApp } from 'vue'

import ProgressSpinner from 'primevue/progressspinner';

import App from './App.vue';

import 'primevue/resources/themes/saga-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';

const app = createApp(App);
```

PrimeVue is amazing! Already using it with Vue 3. Thanks

**Comment by cagataycivici** [comment]
Got it, thank you.
