### ISSUE TITLE
Menu: Using the popup mode, the menu has a transparent background in dark mode.

### ISSUE THREAD

**Issue by luke-z** [primefaces/primevue#5890]
### Describe the bug

The background of the Menu component, when using it in popup mode, is transparent when using a dark mode theme.

![image](https://github.com/primefaces/primevue/assets/37207714/bdc089a4-c4c8-42e2-af5d-50f38b03d138)

It can be observed on the primevue website itself, thus I have not created a reproducer.
It works in light mode as expected.

### Reproducer

https://primevue.org/menu/#popup

### PrimeVue version

4.0.0-rc.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Brave

### Steps to reproduce the behavior

1. Go to the primevue website linked in the reproducer
2. Set the color mode to dark
3. Click on the popup button to display the menu

### Expected behavior

Menu should have a background color

**Comment by JediPixels** [comment]
The entire Dark theme backgrounds are transparent now. I upgraded from beta 4 to rc1 and it changed. If you check out any component on the PrimeVue site like the DatePicker https://primevue.org/datepicker/ you can see the effects.

You can even check out the `Card` component in dark mode and you can see the background is transparent:
[https://primevue.org/card/](https://primevue.org/card/)

Thanks.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/de2560a1cb847e4756f8345bbfd7843b90f02c4b

**Comment by JediPixels** [comment]
I updated to rc.2 and it's working again... thank you.
