### ISSUE TITLE
Approach to animating <DataTable> with <TransitionGroup>

### ISSUE THREAD

**Issue by vzakharov** [primefaces/primevue#5891]
Hi everyone. Not really an issue here, but I was thinking if there is any way to attach TransitionGroup animations to a DataTable component.

Seems like there could be two ways to do this:
- By intercepting DataTable's tags it uses (<tbody>/<tr>)
- By somehow “programmatically” attaching TransitionGroup to said tags.

My intuition tells me that none is really possible, there’s just no API for that.

Has anyone considered the same and found a solution? I love the versatility of DataTable, but the lack of movement/removal/addition animations looks really subpar to the rest of it.

**Comment by abdullah131566** [comment]
> Hi everyone. Not really an issue here, but I was thinking if there is any way to attach TransitionGroup animations to a DataTable component.
> 
> Seems like there could be two ways to do this:
> 
> * By intercepting DataTable's tags it uses (/)
> * By somehow “programmatically” attaching TransitionGroup to said tags.
> 
> My intuition tells me that none is really possible, there’s just no API for that.
> 
> Has anyone considered the same and found a solution? I love the versatility of DataTable, but the lack of movement/removal/addition animations looks really subpar to the rest of it.

You can still do that by transitioning the body slot in each column.
