### ISSUE TITLE
primevue@4.0.0-rc.1 incorrect background colors

### ISSUE THREAD

**Issue by julichan** [primefaces/primevue#5894]
### Describe the bug

Hello,

Colors breaks from primevue@4.0.0-rc.1 where they worked well on beta4
Fieldset and Card are perfect white in light mode and transparent in darkmode. --p-content-background is defined to those colors.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template

### PrimeVue version

4.0.0-rc.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Edge, chrome

### Steps to reproduce the behavior

I use the following configuration from documentation:
 // Initialize Prime vue
app.use(PrimeVue, {
  theme: {
    preset: Aura,
    options: {
        prefix: 'p',
        darkModeSelector: 'system', // setting this to a class sets the background to pure white (p-surface-0 ffffff)
        cssLayer: true // Changing this value did not seem to change a single thing.
    }
  },
  ripple: true
});

I don't have any customization of the style variables or whatsoever

### Expected behavior

The background colors or the components should have dark colors in dark mode and light colors (I'm guessing not perfect white) in light mode.

**Comment by luke-z** [comment]
Seems to be the reason for https://github.com/primefaces/primevue/issues/5890

**Comment by julichan** [comment]
I did not use any popup thought. I only have fieldsets and buttons at the moment

**Comment by JediPixels** [comment]
The entire Dark theme backgrounds are transparent now. I upgraded from beta 4 to rc1 and it changed. If you check out any component on the PrimeVue site like the `DatePicker` [https://primevue.org/datepicker/](https://primevue.org/datepicker/) you can see the effects.

Thanks.

**Comment by julichan** [comment]
It seems the commit at fault is https://github.com/primefaces/primevue/commit/a054a92ef1cfc3d1dc0dc7b16b9d2ba7aab082d8
All it does is transforming the dark theme background to transparent. can this be reverted ?
Thanks,

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/commit/de2560a1cb847e4756f8345bbfd7843b90f02c4b
