### ISSUE TITLE
[nuxt] Could not access pt. The only available runtime config keys on the client side are public and app

### ISSUE THREAD

**Issue by Tarabass** [primefaces/primevue#5895]
### Describe the bug

After a clean installation I get the following warning in the console. In bigger projects it can even result in an error instead of a warning. 

`[nuxt] Could not access 'pt'. The only available runtime config keys on the client side are 'public' and 'app'. See 'https://nuxt.com/docs/guide/going-further/runtime-config' for more information.`

```npm
npx nuxi init NuxtPrimeVueTest
npx nuxi@latest module add primevue
```

### Reproducer

https://stackblitz.com/edit/github-ydzyjt

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

```npm
npx nuxi init NuxtPrimeVueTest
npx nuxi@latest module add primevue
```

**Comment by Tarabass** [comment]
Issue on PrimeVue Nuxt Module
https://github.com/primefaces/primevue-nuxt-module/issues/69

**Comment by FatNerdPeng** [comment]
I have encountered the same problem. I did not have this problem before, but I encountered it after updating some dependencies. Specifically 
`nuxt 3.11.1 to 3.12.1`
 `primevue 3.50.0 to 3.52.0`
`vue 3.4.21 to 3.4.27`
I don't know which one caused this warning.In my case,the code I ultimately traced is here `http://.../_nuxt/node_modules/.pnpm/nuxt@3.12.1_@opentelemetry+api@1.9.0_@unocss+reset@0.61.0_floating-vue@5.2.2_sass@1.77.5_unocss@0.61.0_vite@5.2.13/node_modules/nuxt/dist/app/nuxt.js?v=2acd929e`:
```
return new Proxy(runtimeConfig,{
        get(target, p, receiver) {
            if (typeof p === "string" && p !== "public" && !(p in target) && !p.startsWith("__v")) {
                console.warn(`[nuxt] Could not access \`${p}\`. The only available runtime config keys on the client side are ${keys.join(", ")} and ${lastKey}. See \`https://nuxt.com/docs/guide/going-further/runtime-config\` for more information.`);
            }
            return Reflect.get(target, p, receiver);
        }
    });
```
So, does `pt` refer to `pass through`? The only time I use the `pt` attribute is when modifying the style of the primevue component, I use a similar notation:
```
:pt="{
    content: () => ({
      style: {
        textAlign: 'center',
      },
    }),
  }"
```

**Comment by Tarabass** [comment]
> I have encountered the same problem. I did not have this problem before, but I encountered it after updating some dependencies. Specifically 
> `nuxt 3.11.1 to 3.12.1`
>  `primevue 3.50.0 to 3.52.0`
> `vue 3.4.21 to 3.4.27`
> I don't know which one caused this warning.In my case,the code I ultimately traced is here `http://.../_nuxt/node_modules/.pnpm/nuxt@3.12.1_@opentelemetry+api@1.9.0_@unocss+reset@0.61.0_floating-vue@5.2.2_sass@1.77.5_unocss@0.61.0_vite@5.2.13/node_modules/nuxt/dist/app/nuxt.js?v=2acd929e`:
> ```
> return new Proxy(runtimeConfig,{
>         get(target, p, receiver) {
>             if (typeof p === "string" && p !== "public" && !(p in target) && !p.startsWith("__v")) {
>                 console.warn(`[nuxt] Could not access \`${p}\`. The only available runtime config keys on the client side are ${keys.join(", ")} and ${lastKey}. See \`https://nuxt.com/docs/guide/going-further/runtime-config\` for more information.`);
>             }
>             return Reflect.get(target, p, receiver);
>         }
>     });
> ```
> So, does `pt` refer to `pass through`? The only time I use the `pt` attribute is when modifying the style of the primevue component, I use a similar notation:
> ```
> :pt="{
>     content: () => ({
>       style: {
>         textAlign: 'center',
>       },
>     }),
>   }"
> ```

Pt stands for pass through indeed. Primevue has a Pt config option in the nuxt config, but that's on the primevue object/module configuration, not on the root of the config declaration. It even occurs when you don't use Pt at all, anywhere. So not in the config or on a component.

**Comment by mertsincan** [comment]
Hi all,

I can't decide if this is a bug or something I should fix. Nuxt has reserved the `$config` name with the new improvements. We have $config computed in BaseComponent and other vue files. Nuxt interferes with this variable that we define as inline. When I replace this computed name with $primevueConfig, everything works smoothly. That's what I did for now. It would have been better if Nuxt had given it a more specific name.
https://nuxt.com/docs/guide/going-further/runtime-config#exposing
> Public runtime config is accessible in Vue templates with $config.public.

Exp;
```
// in my app
<template>
    <div>...</div>
</template>
<script>
export default {
    name: 'MyComponent',
    beforeCreate() {
        console.log(this.$config); // output: { public: ..., app: ...}
    },
    computed: {
        $config() {
            return { test: 'TEST'};
        }
    }
};
</script>
```
<img width="851" alt="Screenshot 2024-06-16 at 00 59 30" src="https://github.com/primefaces/primevue/assets/11868120/04326442-4127-481b-b94e-ef2385f12bc1">

**Comment by mertsincan** [comment]
Discussion in Nuxt; https://github.com/nuxt/nuxt/discussions/27645
