### ISSUE TITLE
Themes are installed by the wrong package

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#5898]
When @primevue/core is installed, the @primevue/theme package is also installed. This is a mistake and unstyled mode may also cause problems. That's why themes should always be included in the project separately from the @primevue/themes package.

**Comment by mcmimik** [comment]
Hi @mertsincan,

In version `rc.2`, the import `import { $dt } from "@primevue/themes";` stopped working and has been replaced with `import { $dt } from "@primeuix/styled";`.

Could you please clarify where we should import `$dt` from now, considering the documentation still points to the `@primevue/themes` package? Also, when using the import from `@primeuix/styled`, TypeScript reports that the `$dt` export is missing, which seems similar to the issue described in [#5749](https://github.com/primefaces/primevue/issues/5749).

Currently, we have to use the following workaround:
```typescript
// @ts-expect-error Remove once types are fixed
import { $dt } from "@primeuix/styled";
```

Could you please address the type definition so we don't need to use `@ts-expect-error`?

Thank you!

**Comment by mcmimik** [comment]
Additionally, we need to import types from `ts-helpers`, specifically the `DesignToken` type. Currently, it seems impossible to import this type from `@primevue/core` without encountering an error. Could you please fix an explicit export of the `DesignToken` type?

**Comment by cwillinx** [comment]
Also, import Aura from `@primevue/themes/aura` seems to be gone, but not available under `@primeuix/styled` either.

**Comment by mertsincan** [comment]
> Also, import Aura from @primevue/themes/aura seems to be gone, but not available under @primeuix/styled either.
Is its type definition?

**Comment by mertsincan** [comment]
@primeuix/styled is the core API. So, you shouldn't need this. You need always use @primevue/themes and it uses this core API and exports it via @primevue/themes.

**Comment by cwillinx** [comment]
Vite can't find them:


This is the import:
```
import type { PrimeVueConfiguration } from 'primevue/config';
import { definePreset } from '@primevue/themes';
import Aura from '@primevue/themes/aura';
```

This is the error message on dev build:
```
Error: The following dependencies are imported but could not be resolved:
  @primevue/themes (imported by /Users/.../src/Frontend/src/shared/primeOptions.ts)
  @primevue/themes/aura (imported by /Users/.../src/Frontend/src/shared/primeOptions.ts)
  Are they installed?
```

**Comment by mertsincan** [comment]
Thanks a lot for the update, @cwillinx! But, this structure has already changed. Please see; https://primevue.org/theming/styled/

Custom theme example; https://github.com/primefaces/primevue/blob/master/apps/showcase/themes/app-theme.js

A starter with vite; https://github.com/primefaces/primevue-examples/tree/main/vite-quickstart

**Comment by cwillinx** [comment]
Ok, now I understand, I have to install it as a separate npm package. 

Doing that, it's working fine, I just realized this change

**Comment by mcmimik** [comment]
> Could you please create a separate ticket for it? I'll work on it in the next release.

Sure, here it is: https://github.com/primefaces/primevue/issues/5910
@mertsincan
