### ISSUE TITLE
DataTable: PrimeVue v4 Column Filter highlight not working

### ISSUE THREAD

**Issue by LittleTurtle2333** [primefaces/primevue#5900]
### Describe the bug

PrimeVue v4.0.0-rc.1 DataTable Column Filter highlight not working

### Reproducer

https://primevue.org/datatable/#basic_filter

### PrimeVue version

4.0.0.rc.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by LittleTurtle2333** [comment]
![image](https://github.com/primefaces/primevue/assets/32336368/47da70bf-ad59-4501-bc4a-138c16d7591b)

**Comment by eaf-jtanneh** [comment]
I'm having this problem too. The issue is easily reproducible via the documentation. There is no `active` class being applied to the filter button. Here's a side-by-side comparison between v3.53 and v4.
![Screenshot 2024-07-03 at 9 48 48 AM](https://github.com/primefaces/primevue/assets/73910284/05c556e1-341b-464d-9ce4-6e35d6011e29)

```
v3.53 filter button classes when active
p-column-filter-menu-button p-link p-column-filter-menu-button-active

v4 filter button classes when active
p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-datatable-column-filter-button
```

**Comment by tugcekucukoglu** [comment]
It is a design decision. You can change it using pt prop or new design tokens.

**Comment by schoonc** [comment]
If someone is looking for a solution, I have come to this:

    <column
        :pt="{
          pcColumnFilterButton: pcColumnFilterButton
        }"
      >
    
    ...
    
    function pcColumnFilterButton ({ context }) {
      return {
        style: context.active ? 'background: var(--p-primary-100)' : ''
      }
    }

**Comment by dassels** [comment]
While the pass through option works, I've got hundreds of columns to fix after the update. And the design tokens don't seem to have any provision for an 'active' state. Is there anyway to target this globally without having to make a custom component or add this code to every instance?

**Comment by schoonc** [comment]
Maybe this will do https://primevue.org/configuration/#pt ? And yes, I also did not find how to set up using tokens. Although @tugcekucukoglu [says](https://github.com/primefaces/primevue/issues/5900#issuecomment-2243043378) that it is possible. @tugcekucukoglu maybe it's a bug that there are no corresponding tokens?

**Comment by dassels** [comment]
Thanks! I missed that you can set things up there. I was unable to find an example of how to use it with the _context_ variable but managed to eventually find this [post ](https://github.com/primefaces/primevue/issues/4278#issue-1853056522) that had some examples. So what I have looks like this:

```
app.use(PrimeVue, { 
  ripple: true,
  pt: {
    datatable: {
      column: {      
        pcColumnFilterButton: ({ context }) => ({style: context.active ? 'background: var(--p-primary-100)' : ''}),
      }
    }
  }
});
```

And so far seems to work!

**Comment by Mettbrot** [comment]
Thank you! If your Linter is unhappy with implicit `any`, use `{ ColumnPassThroughMethodOptions } from "primevue/column"`

```
import { ColumnPassThroughMethodOptions } from "primevue/column";
...
pcColumnFilterButton: ({ context }: ColumnPassThroughMethodOptions) => ({ style: context.active ? "background: var(--p-primary-100)" : "" }),
```

**Comment by ardio-sos** [comment]
> Thanks! I missed that you can set things up there. I was unable to find an example of how to use it with the _context_ variable but managed to eventually find this [post ](https://github.com/primefaces/primevue/issues/4278#issue-1853056522) that had some examples. So what I have looks like this:
> 
> ```
> app.use(PrimeVue, { 
>   ripple: true,
>   pt: {
>     datatable: {
>       column: {      
>         pcColumnFilterButton: ({ context }) => ({style: context.active ? 'background: var(--p-primary-100)' : ''}),
>       }
>     }
>   }
> });
> ```
> 
> And so far seems to work!

I like this solution, it works well. However, ideally, I would like to change the icon to filled. But it doesn't seem to work:

`pt: {
                datatable: {
                    column: {
                        pcColumnFilterButton: ({ context }) => ({
                            class: context.active ? 'pi pi-filter-fill' : 'pi pi-filter',
                        })
                    }
                }
            }`

Am I doing something wrong or is this a limitation?
