### ISSUE TITLE
Typo in tailwindcss-primeui npm package

### ISSUE THREAD

**Issue by Peanut4287** [primefaces/primevue#5902]
### Describe the bug

Since this repo is linked on https://www.npmjs.com/package/tailwindcss-primeui I guess this is the right place to report this typo.
Inside `tailwindcss-primeui/src/utils/preset.js`, there is a typo (three dashes instead of two):
```javascript
{
  '.bg-emphasis': {
    background: 'var(--p-content-hover-background)',
    color: 'var(---p-content-hover-color)' // should be `--p-content-hover-color`, not `---p-content-hover-color`
  }
}
```

### Reproducer

n/a

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Thanks for your attention. Could you create an issue for this repo: https://github.com/primefaces/tailwindcss-primeui

Thank you.
