### ISSUE TITLE
[Nuxt] Installation example of rc.1 doesn't work with rc.2, as @primevue/themes is missing

### ISSUE THREAD

**Issue by luke-z** [primefaces/primevue#5904]
### Describe the bug

[This commit](https://github.com/primefaces/primevue/commit/2fdfe2f13e714f19118d612ace9f4b583fd08628) removed @primevue/themes and added @primeuix/styled to the dependencies. Thus, the previous package is not in the node_modules folder anymore.

The example on primevue.org is still using the @primevue/themes package: https://primevue.org/nuxt/#importtheme
When defining a custom theme, I can only find ```definePresets``` as an importable function from @primeuix/styled, however I cannot find the Aura exportable anymore.

Currently I can only use a theme if I manually install @primevue/themes as a dependency and import Aura

```
import { definePreset } from '@primeuix/styled' // <----
import Aura from '@primevue/themes/aura'   // <----

const CustomAura = definePreset(Aura, {
  semantic: {
    primary: {
      50: '{green.50}',
      100: '{green.100}',
      200: '{green.200}',
      300: '{green.300}',
      400: '{green.400}',
      500: '{green.500}',
      600: '{green.600}',
      700: '{green.700}',
      800: '{green.800}',
      900: '{green.900}',
      950: '{green.950}',
    },
  },
})

export default {
  preset: CustomAura,
  options: {
    darkModeSelector: '.dark',
  },
}

```

### Reproducer

-

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by mkalinski93** [comment]
same here

**Comment by mertsincan** [comment]
Hi everyone,

Yes, this was a bug in RC.1. You need to install `@primevue/themes` package for themes. 
https://primevue.org/vite/#styled

Best Regards,

**Comment by timobehrens** [comment]
@mertsincan  What about Nuxt? I upgraded to RC2 and now my local env is failing... I followed a guide and copied the aura theme into a "presets" folder in my project and load it in my nuxt.config like so:
```js
  primevue: {
    options: {
      unstyled: true,
    },
    importPT: { from: path.resolve(__dirname, "./presets/aura/") },
  },
```

Error message when running `npm run dev`
```
 ERROR  Error: Could not load /Users/[...]/node_modules/primevue/base/style/index.mjs (imported by virtual:#primevue-style): ENOENT: no such file or directory, open '/Users/[...]/node_modules/primevue/base/style/index.mjs'
```

**Comment by luke-z** [comment]
@timobehrens I have not used the unstyled mode yet.

But here is the way I'm using the styled mode:

I create a ts file in a themes folder, add the stuff I posted above and import it in nuxt.config.ts using 

```
primevue: {
    importTheme: { from: '@/themes/my-theme' },
},
```

Alternatively you can put this in the app.vue file inside of the script block to use the default Aura theme:

```
import { usePreset } from "@primevue/themes";
import Aura from "@primevue/themes/aura";

usePreset(Aura);
```

I played around with custom PT for a moment, but couldn't really get it to work. (Following https://primevue.org/nuxt/#importpt)
What I tried was importing the Button as ```import Button from "@primevue/themes/aura/button"``` to have the default Button config and then using importPT in the nuxt.config.ts file to import the following file:

```
import Button from "@primevue/themes/aura/button"

const MyCustomPT = {
  button: Button,
}

export default MyCustomPT
```

I didn't work though :P

**Comment by AndyLukac** [comment]
Hey guys, I'm also having trouble with rc2 using Nuxt.
I have opened up an issue on the `primevue-nuxt-module` repo. It would actually be great know the difference between these two libraries and they both seem to be required ("@primevue/nuxt-module": "4.0.0-rc.2", "primevue": "4.0.0-rc.2").

**Comment by luke-z** [comment]
@AndyLukac the nuxt module is just there to simplify the integration with nuxt.

You could thereotically just follow the vite installation docs and do it yourself.

The module registers all the components, directives and so on so you don't have to do it yourself.

**Comment by AndyLukac** [comment]
Hi @luke-z, thanks for your prompt reply. 
Great to know, thanks for that.
Regarding the error, I'm actually not at all using the tristatecheckbox component. To give you some context we have monorepo which includes wrapped primevue components which are exported from within a package (although we do not use all of the components). So within my nuxt project I import these wrapped components. 

Do you have any other ideas on what it could be? 

Here is my package.json

`{
  "name": "backrock",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/i18n": "^8.3.1",
    "@nuxtjs/tailwindcss": "^6.11.4",
    "@primevue/nuxt-module": "4.0.0-rc.2",
    "autoprefixer": "^10.4.18",
    "nuxt": "3.11.1",
    "nuxt-primevue": "3.0.0",
    "vue": "3.4.27",
    "vue-router": "4.3.2"
  },
  "dependencies": {
    "@orion/comet": "1.37.0",
    "@pinia/nuxt": "0.5.1",
    "pinia": "2.1.7",
    "primevue": "4.0.0-rc.2"
  }
}
`

**Comment by luke-z** [comment]
I suppose it's the "nuxt-primevue" package, which is the previous v3 nuxt module

**Comment by AndyLukac** [comment]
I just tested the version 4.0.0-beta.4. The error regarding the tristatecheckbox has gone, however I'm still getting this error: 

`Error: Could not load /opt/homebrew/var/www/site-6play-bo/modern-apps/node_modules/.pnpm/primevue@4.0.0-rc.2_vue@3.4.27_typescript@5.4.5_/node_modules/primevue/basecomponent/style/index.mjs (imported by virtual:#primevue-style): ENOENT: no such file or directory, open '/opt/homebrew/var/www/site-6play-bo/modern-apps/node_modules/.pnpm/primevue@4.0.0-rc.2_vue@3.4.27_typescript@5.4.5_/node_modules/primevue/basecomponent/style/index.mjs'`

**Comment by luke-z** [comment]
@AndyLukac I mean you don't need that at all.

You already have ```@primevue/nuxt-module```, so there is no need for the previous ```nuxt-primevue``` package. You can remove this completely.

The primevue team has moved to a monorepo, that's why it's a different package now.

**Comment by AndyLukac** [comment]
Ah, of course, that makes sense. Thank you.

Although, there seems to be another problem.

I'm trying to import a theme, as described in this doc: https://primevue.org/nuxt/#importtheme
however I am receiving this error: 
![image](https://github.com/primefaces/primevue/assets/32932349/b0acc0ef-4557-4f3a-8fcc-5dc360ebdc14)

**Comment by AndyLukac** [comment]
Please disregard the above message, I had made a mistake

**Comment by luke-z** [comment]
Awesome, glad it works!
