### ISSUE TITLE
InputMask: v4 no classes are passed to target inpud component

### ISSUE THREAD

**Issue by mzuccaroli** [primefaces/primevue#5908]
### Describe the bug

class attribute of the component is not passed to target input  like other primevue components

example:
`
      <InputMask
        class="w-full my-class"
        unstyled
        type="text"
        :disabled="authStore.isLoading"
        mask="999-999-999"
      />
`
does not pass the classess "w-full" and "my-class" to generated input element

### Reproducer

https://stackblitz.com/

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

`
      <InputMask
        class="w-full my-class"
        unstyled
        type="text"
        :disabled="authStore.isLoading"
        mask="999-999-999"
      />
`
does not pass the classess "w-full" and "my-class" to generated input element

### Expected behavior

generated input element should have the  "w-full" and "my-class" classes

**Comment by blevinelrp** [comment]
InputMask wraps InputText.
You need to use a passthrough to add classes to internal dom elements.
For example:

```
        <InputMask id="basic" v-model="value" mask="99-999999" placeholder="99-999999"
        :pt="{
            root: {
              root: {class: 'w-100 my-custom'}
            }
          }"
        />
```

**Comment by mzuccaroli** [comment]
ok but in v3 you can easily use class without passthrough, it's a quite breaking change

**Comment by blevinelrp** [comment]
Breaking changes are one of the main reasons for major version updates (i.e. v3 to v4).  That seems reasonable to me.

Also, being more explicit about which DOM element receives the "class" passthrough seems like the correct choice.  For example, what if you wanted to apply the class to the div that wraps the input, but not the input itself?  There should be some way of specifying that.
