### ISSUE TITLE
InputChips: v4 missing docs

### ISSUE THREAD

**Issue by pawmanaloto** [primefaces/primevue#5909]
### Describe the bug

Can't find InputChips documentation in the docs. https://primevue.org/inputchips/ goes to 404

### Reproducer

N/A

### PrimeVue version

4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by luke-z** [comment]
Do you mean "Chips"?

It has been removed and can be replaced with an AutoComplete.

See the migration guide for more information: https://primevue.org/guides/migration/v4/

**Comment by ildyria** [comment]
I disagree, the behaviour is completely different, especially with the separators.

Furthermore, @tugcekucukoglu discribes those in https://github.com/primefaces/primevue/issues/5612
> Chips --> InputChips

The chip visual with e.g. comma separation is not provided AFAIK in the AutoComplete.
So I do think that documentation is indeed missing.

**Comment by kepoly** [comment]
I've just ran into this today, InputChips is the new nomenclature in v4 and is the recommended update via IDE hints but I do not see it in the documentation.

**Comment by Jorelia** [comment]
![image](https://github.com/user-attachments/assets/ecffed57-69e3-40f1-9a08-5b94a95878a5)

**Comment by skipmaple** [comment]
`node_modules/primevue/chips/index.d.ts` line 67

<img width="626" alt="image" src="https://github.com/user-attachments/assets/4afe0092-c106-47ac-a41d-0e1f389fec6d" />

There still no InputChips docs. @tugcekucukoglu

**Comment by luke-z** [comment]
@skipmaple https://primevue.org/guides/migration/v4/#changes

Use AutoComplete with multiple enabled and typeahead disabled.

> Do you mean "[Chips](https://v3.primevue.org/chips/)" from v3?
> 
> It has been removed and can be replaced with an AutoComplete.
> 
> See the migration guide for more information: https://primevue.org/guides/migration/v4/

**Comment by skipmaple** [comment]
> @skipmaple https://primevue.org/guides/migration/v4/#changes
> 
> Use AutoComplete with multiple enabled and typeahead disabled.
> 
> > Do you mean "[Chips](https://v3.primevue.org/chips/)" from v3?
> > It has been removed and can be replaced with an AutoComplete.
> > See the migration guide for more information: https://primevue.org/guides/migration/v4/

Thanks. By search docs I found this: https://primevue.org/autocomplete/#multiple

and it suits my needs.

**Comment by PaulMcML** [comment]
Unfortunately 'autocomplete with typeahead disabled' doesn't work as well as the old inputchips when part of a form. Hitting 'return' to create the chip cascades through to the form and submits the form rather than just creating the chip, making it unusable.

**Comment by jatfield** [comment]
> Unfortunately 'autocomplete with typeahead disabled' doesn't work as well as the old inputchips when part of a form. Hitting 'return' to create the chip cascades through to the form and submits the form rather than just creating the chip, making it unusable.

This can be avoided by adding  @keydown.enter.prevent, but that does feel like a workaround.
