### ISSUE TITLE
CascadeSelect: should limit the height and display scrollbars.

### ISSUE THREAD

**Issue by Ice-Hazymoon** [primefaces/primevue#5913]
### Describe the bug

When there is too much data, the CascadeSelect component fills up the entire screen.

![image](https://github.com/primefaces/primevue/assets/25239977/41c72ae4-a07e-4290-8abf-c5675c446f38)

I can't create a duplicate through the issue template, these links are not accessible.

![image](https://github.com/primefaces/primevue/assets/25239977/e917a0df-cd5a-4bca-a438-7ebf2dad5800)
![image](https://github.com/primefaces/primevue/assets/25239977/0aee832e-12bb-4fdc-a281-5a019f15e5f8)

### Reproducer

null

### PrimeVue version

4.0.0-rc.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by GuanJiayao** [comment]
Set the pt attribute for the component:
:pt="{ list: { class: ['max-h-[200px] overflow-y-auto'] }, optionList: { class: ['max-h-[200px] overflow-y-auto'] } }
The first and second levels work, but the last level does not display on the interface.
