### ISSUE TITLE
Popover - Misplaced arrow

### ISSUE THREAD

**Issue by Synar** [primefaces/primevue#5915]
### Describe the bug

The arrow of the popover is incorrectly placed, off to the left of the target element. 

This issue is also present in primevue's very own website, in the documentation of the v4 version of popover (the issue was absent in v3), making it easy to reproduce. I got it both on my pixel's chrome and on firefox on my desktop.

### Reproducer

https://primevue.org/popover/

![Screenshot_20240619-105204.png](https://github.com/primefaces/primevue/assets/16291122/edff3d2f-de26-409c-b803-8e87903dc907)

![Screenshot_20240619-105146.png](https://github.com/primefaces/primevue/assets/16291122/3b0e1ead-d1da-479a-9e2e-520fcd9f5254)

### PrimeVue version

4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Go to https://primevue.org/popover/, click on any of the example buttons triggering a popover to be displayed 

### Expected behavior

Arrow aligns itself to the target

**Comment by multun** [comment]
I can reproduce this behavior on wider screens, even in the documentation example, by aligning buttons to the right of the screen:
![2024-06-20_11-06-1718874474](https://github.com/primefaces/primevue/assets/5047140/6e3a5809-754a-4306-80c2-476f0b481f89)

**Comment by multun** [comment]
This is a regression from Primevue 3.52, where the same example works fine:
![2024-06-20_11-06-1718877117](https://github.com/primefaces/primevue/assets/5047140/d08959a3-8e07-478b-9c90-aff6b2968a8d)

**Comment by blouflashdb** [comment]
I have the same problem.

**Comment by multun** [comment]
@blouflashdb can you please confirm [this change](https://github.com/primefaces/primevue/pull/5934) fixes the issue?

**Comment by blouflashdb** [comment]
> @blouflashdb can you please confirm [this change](https://github.com/primefaces/primevue/pull/5934) fixes the issue?

how can I test your PR?

**Comment by multun** [comment]
@blouflashdb 

## If you're OK with using a build I made

In your `package.json`, remove previous references to primevue, and add the following:

```
    "@primevue/auto-import-resolver": "https://dl.multun.net/primeview-pr-5934/primevue-auto-import-resolver-4.0.0-rc.2.tgz",
    "@primevue/core": "https://dl.multun.net/primeview-pr-5934/primevue-core-4.0.0-rc.2.tgz",
    "@primevue/icons": "https://dl.multun.net/primeview-pr-5934/primevue-icons-4.0.0-rc.2.tgz",
    "@primevue/metadata": "https://dl.multun.net/primeview-pr-5934/primevue-metadata-4.0.0-rc.2.tgz",
    "@primevue/nuxt-module": "https://dl.multun.net/primeview-pr-5934/primevue-nuxt-module-4.0.0-rc.2.tgz",
    "@primevue/themes": "https://dl.multun.net/primeview-pr-5934/primevue-themes-4.0.0-rc.2.tgz",
    "primevue": "https://dl.multun.net/primeview-pr-5934/primevue-4.0.0-rc.2.tgz",
```

## If you're not OK with using a build I made

This is _not great_ as you're downloading and running a build I made. If you want to do it yourself, buckle up: It's my first week doing JS, and I'm not aware of the less cursed ways of doing this. If anyone is aware of a better way to do this, please point it out.

1) Clone my fork and checkout my branch `git clone -b fix-popup-arrow-offset git@github.com:multun/primevue.git primevue-pr`
2) Build and pack all packages in the primevue workspace:
```sh
cd primevue-pr
mkdir dist
dist_dir="$(realpath dist)"
for package in packages/*; do pushd "$package"; pnpm pack --pack-destination "$dist_dir"; popd; done
```
3) get the path to each package, and use `file:` references to install these

**Comment by jeverduzco** [comment]
I have the same issue with V4.

**Comment by AleeeKoi** [comment]
Hello, I'm facing the same issue, is it not fixed yet?

**Comment by AutoAwesome** [comment]
I have also the same issue in 2025 :-(

**Comment by xndbogdan** [comment]
![Image](https://github.com/user-attachments/assets/4e3ab264-497c-4961-a0a3-a7e1151e5bda)
Same issue here

**Comment by xndbogdan** [comment]
> ![Image](https://github.com/user-attachments/assets/4e3ab264-497c-4961-a0a3-a7e1151e5bda) Same issue here

I fixed the issue by adding some custom styling:
`.p-popover.p-popover-arrow-flipped::before {
    left: auto;
    right: 1.25rem;
}

.p-popover.p-popover-arrow-flipped::after {
    left: auto;
    right: 1.25rem;
}`

Then added this class
`<Popover ref="appearancePopover" class="p-popover-arrow-flipped">`

![Image](https://github.com/user-attachments/assets/0556d242-bf14-4193-ab52-fabafd1303eb)

Looking fine now

**Comment by AutoAwesome** [comment]
Here is how to actually fix it guys:

Open `src/assets/primevue/popover.css` and add this to the bottom of the file:
```css
.p-popover:after, .p-popover:before {
    left: calc(1.25rem + var(--p-popover-arrow-left))
}
```

Thanks to [iduchamp](https://github.com/primefaces/primevue-tailwind/issues/341#issuecomment-2491583721).
