### ISSUE TITLE
palette function not exported by @primevue/themes index.d.ts

### ISSUE THREAD

**Issue by mzuccaroli** [primefaces/primevue#5928]
### Describe the bug

the palette function is not exported and generates a typescript error (the js function still works)
https://primevue.org/theming/styled/#Palette

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

`
import { palette } from '@primevue/themes';
 `

generates the typescript error:

`
error TS2305: Module '"@primevue/themes"' has no exported member 'palette'.
`

### Expected behavior

no typescript error

**Comment by blouflashdb** [comment]
I have the same problem.

**Comment by borsTiHD** [comment]
Same here.

**Comment by tugcekucukoglu** [comment]
The new implementation should be like this;

`npm i @primeuix/styled`;

then

`import { palette } from '@primeuix/styled';`

**Comment by blouflashdb** [comment]
Its still not exported. @tugcekucukoglu 
https://www.npmjs.com/package/@primeuix/styled?activeTab=code

**Comment by borsTiHD** [comment]
> Its still not exported. @tugcekucukoglu https://www.npmjs.com/package/@primeuix/styled?activeTab=code

With `"@primeuix/styled": "^0.0.3",` it worked for me.  
It has the correct export.
