### ISSUE TITLE
[Primevue-Tailwind presets]: Presets not updated to primevue version 4. 

### ISSUE THREAD

**Issue by mrc-bsllt** [primefaces/primevue#5933]
### Describe the bug

As per title, the presets in the documentation of tailwind-primevue [https://tailwind.primevue.org/overview](url) are not updated with the relevant [data-pc-section] of the primevue 4 components.
Allego come riproduzione

### Reproducer

https://tailwind.primevue.org/calendar/

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mrc-bsllt** [comment]
> From the doc's [tailwind section](https://primevue.org/tailwind/#presets):
> 
> > Currently, the Tailwind CSS Presets are not compatible with v4 and will be with a future update after v4 final.
> 
> This is also mentioned in the _Migration to V4_ guide within the [breaking changes](https://primevue.org/guides/migration/v4/#breaking):
> 
> > The Tailwind CSS presets for the unstyled mode are not updated to v4 yet.
> 
> But in my opinion it should also be mentioned in the [introduction](https://primevue.org/introduction/) and on the specific Tailwind PrimeVue [website](https://tailwind.primevue.org/overview), but it's sadly not.

ah ok, yes I had missed this parts.

**Comment by tugcekucukoglu** [comment]
Thanks for the report. When the final version is released, the presets will be updated.

**Comment by kissu** [comment]
Is this considered as done as of today? 🤗 
Not sure regarding the dates/releases.

**Comment by barbara-b-boechat-sh3** [comment]
I'm asking myself the same... it done already?
