### ISSUE TITLE
MultiSelect: v4 filter input aria attribute prop missing

### ISSUE THREAD

**Issue by blouflashdb** [primefaces/primevue#5936]
### Describe the bug

In v3 you had the filterInputProps prop in the MultiSelect component for setting aria attributes to the filter input. In v4 you no longer have this prop in the MultiSelect component however the docs still say you have it. https://primevue.org/multiselect/#accessibility

### Reproducer

-

### PrimeVue version

4.0.0rc2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use the MultiSelect component with filter. Set filterInputProp.

### Expected behavior

Have a prop to set aria attributes to the filter input element.

**Comment by tugcekucukoglu** [comment]
`pcFilter` pt property option can be used instead.
