### ISSUE TITLE
Named routes support for Menu Components

### ISSUE THREAD

**Issue by guillaume-blz** [primefaces/primevue#594]
Is it possible to make fully compatible menu items with named route? Doc: https://router.vuejs.org/guide/essentials/named-routes.html

Actually `isActive` method of the TabMenu component check only with the string path declaration.

Example:

```javascript
const items = [
  {
    label: 'Dashboard',
    to: { name: 'dashboard' },
  },
  {
    label: 'Post',
    to: { name: 'post', params: { id: 1570 } },
  },
];
```

**Comment by cagataycivici** [comment]
Named routes work fine but TabMenu only is an exception as it checks paths, there is room for improvement here.

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primevue/issues/830
