### ISSUE TITLE
CSS not Server Side Rendered with PrimeVue 4 / Nuxt 3

### ISSUE THREAD

**Issue by cheike569** [primefaces/primevue#5945]
### Describe the bug

I'm on PrimeVue `4.0.0-rc.2` with Nuxt `3.12.12`. 

Theme styles are not rendered Server Side.

Whenever I do a full page reload, the layout shifts and it takes a second before the PrimeVue component chunks are loaded (including the styles).

This was working in PrimeVue 3 without issues.

`nuxt.config.js`

```
import Aura from '@primevue/themes/aura';

/* ... */

primevue: {
        options: {
            theme: {
                preset: Aura
            },
        }
}
```

![ssrissue](https://github.com/primefaces/primevue/assets/244036/16d721f8-f332-4360-99b8-19106730de65)

### Reproducer

https://stackblitz.com/edit/nuxt-starter-xjup5v?file=app.vue

Compare the PrimeVue component to a regular button with a custom CSS class. (see `style.css`)
The button will be red from the very beginning, and not shift later.

![shift](https://github.com/primefaces/primevue/assets/244036/6632628f-657f-4073-acd5-f4fea0850083)

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Setup a new Nuxt Project with PrimeVue 4.

### Expected behavior

CSS should be processed on the server and delivered with the initial response. This worked in PrimeVue 3.

**Comment by adrianpdm** [comment]
I also experienced this issue.
However, such issue only occur when manually importing component.
```ts
export default defineNuxtConfig({
  modules: ['@primevue/nuxt-module'],
  primevue: {
    components: {
      include: [], // set to empty array to prevent registering all components
    },
  },
})
```

Here's what i've tried so far:
- manually import in Vue SFC
- use `unplugin-vue-components` and `primevue-autoimport-resolver` to register used components automatically
- register components manually via plugin using `nuxtApp.vueApp.component()`

All exhibits same behavior, that is CSS not server-rendered

**Comment by cheike569** [comment]
@mertsincan This was working in 4.0.0-rc.3, and is now broken again in 4.0.2.
See: https://stackblitz.com/edit/nuxt-starter-xjup5v?file=package.json

**Comment by danielklein-arch** [comment]
Any update on this issue ?

**Comment by DJsushi** [comment]
This issue still persists with version 4.2.2.

**Comment by maaticlang** [comment]
Currently it works with this configuration.

```
export default defineNuxtConfig({
   modules: [
		'@primevue/nuxt-module',
	],
  ...
  primevue: {
  		autoImport: false,
  		components: {
  			include: [
  				'Button',
  				'Divider',
  				'FloatLabel',
  				'IconFiled',
  				'InputIcon',
  				'InputText',
  			],
  		},
  		options: {
  			theme: {
  				preset: Aura,
  				options: {
  					prefix: 'p',
  					darkModeSelector: 'light',
  					cssLayer: false,
  				},
  			},
  		},
  	},
   ...
}
  ```

**Comment by dolphinwow** [comment]
This also happens in primevue 4.2.5. It happens most notably after autoImport: false.

**Comment by dolphinwow** [comment]
I think I just solved it by applying the solution in this link: [https://github.com/primefaces/primevue/issues/4210#issuecomment-1753921602](https://github.com/primefaces/primevue/issues/4210#issuecomment-1753921602)
