### ISSUE TITLE
Sidebar: Missing Doc

### ISSUE THREAD

**Issue by Tanvir-rahman** [primefaces/primevue#5951]
### Describe the bug

Sidebar doc is missing

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to Components -> Overlay section

### Expected behavior

Sidebar doc should be visible. It's also visible in v3.
[https://v3.primevue.org/overlaypanel/](https://v3.primevue.org/overlaypanel/)

**Comment by tugcekucukoglu** [comment]
Sidebar has been renamed with version 4. We do not find it appropriate to have two different documentation for the same components.
