### ISSUE TITLE
ConfirmDialog: Add asynchronous shutdown functionality to ConfirmDialogs and ConfirmPopups

### ISSUE THREAD

**Issue by AAABingBing** [primefaces/primevue#5954]
### Describe the bug

Can we add asynchronous shutdown functionality to ConfirmDialogs and ConfirmPopups?
I hope to use it like ElementPlus message boxes, so that ConfirmDialogs can be closed asynchronously. Although I know I can use the Dialogs component, it is slightly more cumbersome to use compared to ConfirmDialogs.
Just like this [ElementPlus MessageBox](https://element-plus.org/en-US/component/message-box.html#customization)

![element-plus message-box](https://github.com/primefaces/primevue/assets/53040248/5ba0be15-fff8-4ccf-ae2e-1f4ba469fede)

### Reproducer

/

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Just like this [ElementPlus MessageBox](https://element-plus.org/en-US/component/message-box.html#customization)

![element-plus message-box](https://github.com/primefaces/primevue/assets/53040248/5ba0be15-fff8-4ccf-ae2e-1f4ba469fede)

**Comment by tugcekucukoglu** [comment]
The issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
