### ISSUE TITLE
Is there some way to find the old documentation?

### ISSUE THREAD

**Issue by LeonardoRochaInacio** [primefaces/primevue#5959]
### Describe the bug

I'm trying to read some properties and examples from the old component "TabView" but that one doesn't exist in the new PrimeVue version. There is some way to find the old documentation?

### Reproducer

.

### PrimeVue version

3.44.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by TPei** [comment]
There's a version switcher on the website if that's what you mean. For example the TabView Component from v3 can be found here: https://v3.primevue.org/tabview/

**Comment by tugcekucukoglu** [comment]
Thanks for the updates. Version 2 and version 3 are documented like version 4.
