### ISSUE TITLE
Website: Search Missing

### ISSUE THREAD

**Issue by TPei** [primefaces/primevue#5961]
### Describe the bug

Hey, sorry, not sure if this is the right place for this. But the component search on the https://primevue.org/ website has disappeared. Is this intentional? This makes it so much harder to find appropriate documentation :/

### Reproducer

-

### PrimeVue version

-

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Search button / cmd+k opens search that allows for searching by component name

**Comment by tugcekucukoglu** [comment]
Thanks for the report. Closing due to is not a core bug.

**Comment by TPei** [comment]
> Thanks for the report. Closing due to is not a core bug.

Hey, thanks for the feedback. Is there some other place to point this @tugcekucukoglu ? Is the website generated from this repo or managed by someone externally? :)
