### ISSUE TITLE
Themes folder is missing in Primevue 4.0.0-rc.2

### ISSUE THREAD

**Issue by khaledOghli** [primefaces/primevue#5962]
### Describe the bug

@primevue/themes do not exist, themes folder is missing in Primevue 4.0.0-rc.2 

### Reproducer

-

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

node

### Steps to reproduce the behavior

# Using pnpm
pnpm add primevue@4.0.0-rc.2
pnpm add -D @primevue/nuxt-module@4.0.0-rc.2

after downloading the packages, check for the themes folder within @primevue node_modules

**Comment by luke-z** [comment]
You need to install this package separately from now on if you want to use styled mode.

https://primevue.org/vite/#styled

**Comment by khaledOghli** [comment]
Thanks, I think it would be better also to add this info to Nuxt Installation Guide
