### ISSUE TITLE
Primvue V4 Style Configuration : colorScheme Dark Surface Not Work as expected

### ISSUE THREAD

**Issue by khaledOghli** [primefaces/primevue#5963]
### Describe the bug

surface Variables: Still Take the root variables for light and dark mode

  semantic: {
    colorScheme: {
      light: {
        surface: {
          0: '#00ffff',
          50: '{zinc.50}',
          100: '{zinc.100}',
          200: '{zinc.200}',
          300: '{zinc.300}',
          400: '{zinc.400}',
          500: '{zinc.500}',
          600: '{zinc.600}',
          700: '{zinc.700}',
          800: '{zinc.800}',
          900: '{zinc.900}',
          950: '{zinc.950}',
        },
      },
      dark: {
        surface: {
          0: '#ff2',
          50: '{slate.50}',
          100: '{slate.100}',
          200: '{slate.200}',
          300: '{slate.300}',
          400: '{slate.400}',
          500: '{slate.500}',
          600: '{slate.600}',
          700: '{slate.700}',
          800: '{slate.800}',
          900: '{slate.900}',
          950: '{slate.950}',
        },
      },
    },
  },
  
![Screenshot 2024-06-25 at 12 13 38 PM](https://github.com/primefaces/primevue/assets/65956317/2f2c67fb-d849-45d2-943b-efc0cb45f6cc)
.

### Reproducer

https://stackblitz.com/edit/nuxt-starter-dhgcfm?file=theme.js

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

Go to the repro link: 

https://stackblitz.com/edit/nuxt-starter-dhgcfm?file=theme.js

**Comment by blevinelrp** [comment]
Seems to be working as expected in your stackblitz example.

light
![image](https://github.com/primefaces/primevue/assets/169848517/3f5b4b93-a384-471e-8b8e-9d5077fa4105)

dark
![image](https://github.com/primefaces/primevue/assets/169848517/ceb5d302-7b5a-4ae6-90c9-45a878f2a5a8)

Can you provide more details regarding where you think this is not working?

**Comment by vruello** [comment]
I think I have the same issue with 4.0.0-rc.2.

As I understand the new theming system, the Aura preset sets the fieldset background to `content.background` (https://github.com/primefaces/primevue/blob/master/packages/themes/src/presets/aura/fieldset/index.js). `content.background` is set to `surface.0` in light color scheme (https://github.com/primefaces/primevue/blob/master/packages/themes/src/presets/aura/index.js#L272) and to `surface.900` in dark color scheme (https://github.com/primefaces/primevue/blob/master/packages/themes/src/presets/aura/index.js#L394).

If I'm correct, in the example, the background of the fieldset should be #00ffff in light theme and `--p-slate-900`  (#0f172a) in dark theme. However, when you switch themes, the background color of the fieldset does not change.

The css variable `--p-surface-0` seems to be updated (as you showed up), but for some reason it does not seem to update `--p-fieldset-background`.

**Comment by blevinelrp** [comment]
Still not seeing the issue.

surface-0 theme override value:
![image](https://github.com/primefaces/primevue/assets/169848517/4f69b838-8076-49b8-8f74-da875f280c1f)

How it gets used (how you described above).  You can see the outcome is p-surface-0 using the override surface-0 color from the light theme.
![image](https://github.com/primefaces/primevue/assets/169848517/75aace66-721a-49fa-bb4d-810d86961506)
![image](https://github.com/primefaces/primevue/assets/169848517/a7eae0b1-f05b-400f-87f7-bfc584a983fb)
![image](https://github.com/primefaces/primevue/assets/169848517/c3ac4e6e-9a89-4a6e-a59f-11be5a4317f2)
![image](https://github.com/primefaces/primevue/assets/169848517/8dd31a16-fa70-4d0a-9a9a-96327df9f2f0)

**Comment by vruello** [comment]
Wow thanks! The documentation needs to be updated (https://primevue.org/theming/styled/#darkmodetoggle).

**Comment by khaledOghli** [comment]
> There is a bug in how "toggleTheme" is implemented. It should be the following:
> 
> ```
> const toggleTheme = () => {
>   const element = document.querySelector('html');
>   element.classList.toggle('p-dark');
> };
> ```
> 
> That is why you aren't seeing the update when the theme "switches" (because it isn't currently switching).

And that is the solution, Thanks man.
but really the documentation needs to be more clear.

**Comment by dxvgef** [comment]
> > “toggleTheme”的实现方式存在错误。应该是以下内容：
> > ```
> > const toggleTheme = () => {
> >   const element = document.querySelector('html');
> >   element.classList.toggle('p-dark');
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这就是为什么当主题“切换”时您看不到更新（因为它当前没有切换）。
> 
> 这就是解决方案，谢谢。但实际上文档需要更清晰。

So far, I still can't switch between light and dark colors, according to the code in the documentation

**Comment by dxvgef** [comment]
> There is a bug in how "toggleTheme" is implemented. It should be the following:
> 
> ```
> const toggleTheme = () => {
>   const element = document.querySelector('html');
>   element.classList.toggle('p-dark');
> };
> ```
> 
> That is why you aren't seeing the update when the theme "switches" (because it isn't currently switching).

So far, I still can't switch between light and dark colors, according to the code in the documentation

**Comment by IceflowRE** [comment]
```
// change dark mode surface
updateSurfacePalette({ light: null, dark: darkPalette })
// change light mode surface
updateSurfacePalette({ light: lightPalette, dark: null })
```
This works for me.
