### ISSUE TITLE
TreeSelect: expandedKeys not working 

### ISSUE THREAD

**Issue by AericN** [primefaces/primevue#5967]
### Describe the bug

When passing 'expandedKeys' to TreeSelect it doesn't expand the specified key. I pass the data as expandedKeys="{'1':true}".  This functionality works when the component is a Tree but not as TreeSelect. Is there a different way to do it?

### Reproducer

https://stackblitz.com/edit/cynavd-c9cvw9?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome Version 126.0.6478.116

### Steps to reproduce the behavior

Create TreeSelect component > try to set expandedKeys field

### Expected behavior

When setting the expandedKeys field on a TreeSelect component the specified key should be expanded.

**Comment by james-astra** [comment]
Also facing this problem

**Comment by james-astra** [comment]
Any update on this issue?
