### ISSUE TITLE
Improve utils methods in all packages

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue#5968]
Use @primeuix/utils package instead of DomHandler, ObjectUtils, ZIndexUtils and EventBus.

**Comment by dominiksulak** [comment]
Please I need help. When trying to import and use "dom" insted of "DomHandler" (I was updating primeVue from 3.30.2 --> 4.0.0) constantly getting this error: `AppMenuItem.vue:5 Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@primeuix_utils_dom.js?v=4b85fe6c' does not provide an export named 'default' (at AppMenuItem.vue:5:8)`. I dont know how to import correctly. Thanks a lot!

**Comment by dominiksulak** [comment]
Could anybody please response to my question? I need help with switching from EventBus to primeuix/utils package. Thanks a lot!

**Comment by mertsincan** [comment]
Hi @dominiksulak,

The methods are exported with named export. Please try;
```
import { addClass } from '@primeuix/utils/dom';
or 
import * as dom from '@primeuix/utils/dom'; 
dom.addClass()

import { EventBus } from '@primeuix/utils/eventbus';
```
