### ISSUE TITLE
Documentation for Tag "warn" is wrong.

### ISSUE THREAD

**Issue by tance77** [primefaces/primevue#5973]
### Describe the bug

The documentation for https://primevue.org/tag/ is wrong. For the  `warn` tag the string that should be passed to severity should be `warning`.

![Screenshot 2024-06-26 at 2 32 01 PM](https://github.com/primefaces/primevue/assets/3421501/fdeedc70-8f92-4cc1-8f19-1b828156877a)

**Comment by Yves852** [comment]
@tance77 I'm facing the same problem. Did you found a solution? Using Primevue v4.0.5 (upgraded from V3), it works with "warning" and stops with "warn".

**Comment by tance77** [comment]
> @tance77 I'm facing the same problem. Did you found a solution? Using Primevue v4.0.5 (upgraded from V3), it works with "warning" and stops with "warn".

I just changed it in my config for tag. I just thought it wasn't a good use of my time to make a PR.
