### ISSUE TITLE
MultiSelect: 'v-if="filter"' erroneously removed in v4

### ISSUE THREAD

**Issue by goldengecko** [primefaces/primevue#5978]
### Describe the bug

Line 89 should have  `v-if="filter"` on the IconField element. It used to be there in the equivalent code in v3.

The impact of it not being there is that you can't display the select/deselect all checkbox without also showing the search field.

### Reproducer

N/A

### PrimeVue version

4.0.0-rc2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Create a MultiSelect and don't add the `filter` option. The `toggleShowAll` checkbox will appear as expected, but the filter textfield will also be shown which is incorrect.

### Expected behavior

Filter should only be shown when the filter attribute is set.

**Comment by tugcekucukoglu** [comment]
Contribute to the project by submitting a PR and add value to our community! Share your improvements and enhancements; we look forward to your feedback! PR's always welcomed.
