### ISSUE TITLE
Calendar dateFormat not working

### ISSUE THREAD

**Issue by ihelmer07** [primefaces/primevue#598]
per the docs: 
`dateFormat="dd.mm.yyyy"` in the calendar is used to change the date.

It is not working.
```
<Calendar v-model="launch.date" v-bind:id="'dateInput_'+index" class="form-control"
              placeholder="Click to set date" view="month" dateFormat="dd.mm.yy" :yearNavigator="true"
              yearRange="2020:2030"></Calendar >
```
![image](https://user-images.githubusercontent.com/14080785/97016613-8d59cf80-1512-11eb-90ae-b6ab516b937c.png)

**Comment by cagataycivici** [comment]
Should be;

dateFormat="dd.mm.yy"
