### ISSUE TITLE
Nuxt module component autoImport in v4 rc3 doesn't work with component prefixes

### ISSUE THREAD

**Issue by HummingMind** [primefaces/primevue#5980]
### Describe the bug

If i remove component prefixes from the component configuration the build step works fine. If I add it to the configuration the build breaks with the following error:
![image](https://github.com/primefaces/primevue/assets/87399963/463e8c00-c566-4a97-b2d1-5d991fc4b94e)

Config:
![image](https://github.com/primefaces/primevue/assets/87399963/b47de246-67c0-43d5-aee3-6d7e62d32b26)

Thank you!

### Reproducer

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-ev7evr)

### PrimeVue version

4.0.0-rc.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by mertsincan** [comment]
Interesting! I couldn't replicate it. Could you please create a sample project for us to replicate? I tried with `PrimeButton` and `PrimeCalendar` components. It works fine for me.

**Comment by HummingMind** [comment]
Maybe it's a Windows only issue again? Similar to Nuxt/Nitro and [5879](https://github.com/primefaces/primevue/issues/5879).
I'll do a Codesandbox a bit later today and see what happens there. Will let you know.

**Comment by HummingMind** [comment]
It's not a full one-to-one, but it's close and the error shows up when you run "npm run build"
[Stackblitz](https://stackblitz.com/edit/nuxt-starter-ev7evr)

**Comment by mertsincan** [comment]
Thanks a lot @HummingMind, Fixed for the next version.
