### ISSUE TITLE
Passthrough : documentation

### ISSUE THREAD

**Issue by julichan** [primefaces/primevue#5990]
### Describe the bug

I tried the passthrough setting on select button but it did not work as I expected.
The documentation list both root and pcButton as possible passthrough parameters.
While pt:root:class will pass any class to selectButton, it did not work with pt:pcButton:class pt:pc-button:class nor pt:pcbutton:class for the buttons inside... I imagined it was passed to the html element directly but that wasn't the case.
After spending several hours trying, I figured out that i needed to write: pt:pc-button:root:class because it's passing from a primevue component to another.
This is not explained anywhere in documentation and no exemple is made either.
This is a request to improve documentation:  https://primevue.org/passthrough/. 🫨
Perhaps it would be wise to show a a nested exemple on the passthrough tab of each component in the documentation

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template

### PrimeVue version

4.0.0.rc-2, 4.0.0.rc-3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Edge

**Comment by julichan** [comment]
Actually i managed to make it work using pt:pc-button:root:class ... 🤣 
I did not see any exemple or clear explanation about the imbrication of components and passthrough. Perhaps, this bug should be used to improve documentation https://primevue.org/passthrough/. 🫨

**Comment by tugcekucukoglu** [comment]
Thanks for your feedback. This is being closed as it is not a core issue.
