### ISSUE TITLE
Accordion: Theming content background not working

### ISSUE THREAD

**Issue by Willen17** [primefaces/primevue#5997]
### Describe the bug

_components/lib/accordion/style/AccordionStyle.js_

Changing background for the content in the accordion does not work. There is a mistake present in the code, ther should **not** be a _color:_ property after _background:_

`.p-accordioncontent-content {
/../
    background: color: ${dt('accordion.content.background')};
/../
}`

it should be:

`.p-accordioncontent-content {
/../
    background: ${dt('accordion.content.background')};
/../
}`

### Reproducer

-

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Check the applied background styling for  Accordion-content-content.

**Comment by eneeio-nm** [comment]
I can confirm this via Devtools:

![screenshot-2024-07-09--09 18 02@2x](https://github.com/primefaces/primevue/assets/127733587/c1729f55-0008-4e97-9363-fa1d01b2319a)

**Comment by eneeio-nm** [comment]
@Willen17 I believe it should actually be `.p-accordioncontent-content { /../ background-color: ${dt('accordion.content.background')}; /../ }`
