### ISSUE TITLE
Card (and many other components) content missing?

### ISSUE THREAD

**Issue by t-k-** [primefaces/primevue#600]
I am playing primevue with Vue 3. I find anything I add into a card component disappeared in the final rendering.

Here is the SFC:
```
<template>
<Card>
Content
</Card>
</template>
```

Here is the final HTML I copied from Chrome:
```html
<body>
    <div id="app" data-v-app=""><div class="p-card p-component"><!--v-if--><div class="p-card-body"><!--v-if--><!--v-if--><div class="p-card-content"></div><!--v-if--></div></div></div>
  <script src="bundle.js?329a3e6f14934e1ea9b0"></script>
</body>
```
(the card itself is there, but no content)

I've tried many other components such as panel and toolbar, they all have this issue. 

Here is a branch where I put everything needed to reproduce the issue:
https://github.com/t-k-/vue3-webpack-boilerplate/tree/debug

To reproduce, clone that repo and issue
```
npm install
npm run watch
```

I am a newbie, so please remind me if I have done anything wrong. Thank you!

**Comment by Nicholas-Westley** [comment]
I have the same issue.  There is nothing in my card components.

```
<Card>
    This is inside card
</Card>
```

renders as 

```
<div class="p-card p-component">
  <!--v-if-->
  <div class="p-card-body">
  	<!--v-if-->
  	<!--v-if-->
  	<div class="p-card-content"></div>
  	<!--v-if-->
  </div>
</div>
```

**Comment by t-k-** [comment]
@Nicholas-Westley 

After comparing the code between `vue-cli/primevue-playground`, I find the problem is caused by two aspects:
*  Primevue actually requires `<Card>` to have a slot template, although in the official documentation they have something like
```
<Card>
	Content
</Card>
```
you need to change it to 
```
<Card>
<template slot="content">
        Content
    </template>
</Card>
```

* In Vue 3, slot syntax has changed to `<template v-slot:content>` instead of `<template slot="content">`

Therefore, the overall snippet will look like:
```
    <Card>
        <template v-slot:content> 
        Content
        </template>
    </Card>
```

**Comment by t-k-** [comment]
I will update the example code in my repo: https://github.com/t-k-/vue3-webpack-boilerplate (a scaffold w/o using CLI)
for anyone potentially to encounter this issue. Please star it if it helps you.

Closed.
