### ISSUE TITLE
PrimeVue4 does not work with Nuxt3

### ISSUE THREAD

**Issue by effancy** [primefaces/primevue#6004]
### Describe the bug

When setting up a new Nuxt project and doing the PrimeVue setup accourding to the instructions and adding the button, it does not appear as intended.

<img width="325" alt="Bildschirmfoto 2024-07-02 um 20 55 45" src="https://github.com/primefaces/primevue/assets/96884895/0006b662-4185-4297-9f8e-8a355fc1ce25">

### Reproducer

-

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 126

### Steps to reproduce the behavior

1. Init a new Nuxt project using `npx nuxi@latest init primevuetest`
2. `cd primevuetest`
3. `npm install primevue@4.0.0-rc.2`
4. `npm install --save-dev @primevue/nuxt-module@4.0.0-rc.2`
5. Add to nuxt config `modules: ['@primevue/nuxt-module']`
6. `npm run dev`

### Expected behavior

It's expected that the button appears styled as in the documentation.

**Comment by tugcekucukoglu** [comment]
[Theming](https://primevue.org/configuration/#theme) section might be helpful.
