### ISSUE TITLE
DataTable: Pass Through keys for emptyMessage not working

### ISSUE THREAD

**Issue by msladek** [primefaces/primevue#6006]
### Describe the bug

In the DataTable pass through keys for emptyMessage aren't working, namely:

- `emptyMessage`
- `emptyMessageCell`

Attributes set in the pass through object for the keys don't appear in the DOM tree.

### Reproducer

PrimeVue 3: https://stackblitz.com/edit/primevue-3-vite-issue-template-kq9t6x?file=src%2FApp.vue
PrimeVue 4: https://stackblitz.com/edit/primevue-4-vite-issue-template-1kh2cr?file=src%2FApp.vue

### PrimeVue version

3.53.0 / 4.0.0-rc.3

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Expected behavior

Pass through attributes like `class` for the keys  should appear in the DOM tree.

**Comment by code3z** [comment]
Hey, this may be the wrong place to put this, but `pt:pcCloseButton` on `<Dialog />` is not working either. Here's the code:
```
    <Dialog
      :visible="true"
      modal
      header="Edit Profile"
      class="max-w-96 bg-white p-8"
      :draggable="false"
      pt:pcCloseButton="!bg-transparent"
      pt:header="heading-sm"
    >
      <span class="text-surface-500 dark:text-surface-400 block mb-8">Update your information.</span>

        <label for="email" class="font-semibold w-24 block">Email</label>
        <InputText
          id="email"
          type="email"
          placeholder="you@example.com"
          class="flex-auto"
        />
    </Dialog>
```
I am also using unstyled + tailwind.

**Comment by pohsiu** [comment]
I thought `pt:pcCloseButton:class="bg-transparent"` should work

**Comment by RohitHadiya7** [comment]
is this fixed cuz i got the same error pt for emptymessage not working
only works when explicitely defined in the usePassthrough.

not working directly from component pt
