### ISSUE TITLE
Nuxt autoimport component prefix: add typescript dynamic name support

### ISSUE THREAD

**Issue by ReWWeR** [primefaces/primevue#6007]
### Describe the bug

When added in nuxt.config prefix for component, then IDE doesn't see the new component name, it takes types from node_modules folder, where the names of the components are written without prefix.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-csnodp?file=README.md

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. add in `nuxt.config` ```components: { prefix: 'Pv' }```
2. add button in any `.vue` file
```<pv-button label="Check 2" icon="pi pi-check" />```
3. It works, but IDE will show an error, that it is unknown custom HTML tag

### Expected behavior

IDE should take new type name

**Comment by mertsincan** [comment]
I'll try with `dts: true`;
https://github.com/primefaces/primevue/blob/master/packages/nuxt-module/src/module.ts#L66

**Comment by kingshuaishuai** [comment]
> I'll try with `dts: true`; https://github.com/primefaces/primevue/blob/master/packages/nuxt-module/src/module.ts#L66

I also noticed that the internal dts attribute is set to false, is it intended to be passed in as a configuration item.
I can't get Intellisense now.
Is there any other way to get Intellisense in nuxt？

**Comment by kingshuaishuai** [comment]
I have an idea to auto import primevue components and get Intellisense in nuxt.
step 1: install `@primevue/metadata` package,
step2: Constructs the configuration that nuxtConfig automatically imports
```ts
import { components } from "@primevue/metadata";

import type { ImportsOptions } from "nuxt/schema";

export function getPrimeVueAutoImports(options?: {
  prefix?: string
}): ImportsOptions["presets"] {
  const prefix = options?.prefix || "";

  return components.map((item) => ({
    from: item.from as string,
    imports: [{
      name: "default",
      as: `${prefix}${item.as as string}`
    }]
  }));
}

```
step3: Import automatically in nuxtConfig
```ts
import { getPrimeVueAutoImports } from "./utils/primeVueAutoimports";
export default defineNuxtConfig({
  // ...
  imports: {
    presets: [
      ...getPrimeVueAutoImports()
    ]
  }
});
```
then you can get autoimports and Intellisense;

**Comment by mertsincan** [comment]
Also, please see;
https://github.com/unplugin/unplugin-vue-components/blob/main/src/types.ts#L155

Test:
```js
<PrimeButton label="Submit" />
```

Config:
```ts
primevue: {
        // ...
        autoImport: true,
        components: {
              prefix: 'Prime'
        }
},
```

Output: 
`components.d.ts`
```d.ts
/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    FocusTrap: typeof import('primevue/focustrap')['default']
    KeyFilter: typeof import('primevue/keyfilter')['default']
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
```

**Comment by byronogis** [comment]
@mertsincan Is this judgment expected ?

https://github.com/primefaces/primevue/blob/fbc12930b173f6fbbb10e966ffc7bf1dced36e05/packages/nuxt-module/src/register.ts#L48C10-L48C30
