### ISSUE TITLE
PrimeVue 4.0.0 not available on unpkg

### ISSUE THREAD

**Issue by anabright** [primefaces/primevue#6009]
### Describe the bug

`https://unpkg.com/primevue/core/core.min.js` seems to redirect to `https://unpkg.com/primevue@4.0.0/core/core.min.js` but there is a 404 error. Any ideas what the problem is?

### Reproducer

Embedded Web Components

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
We changed this structure in v4.0. Please see the new one;
https://primevue.org/cdn/
