### ISSUE TITLE
Tabs Navigation Issue: Button Click not working

### ISSUE THREAD

**Issue by Azoorb** [primefaces/primevue#6010]
### Describe the bug

The Tabs menu example does not work on the documentation site. The menu only changes when clicking on the text, not on the button. However, the active tab does change.

https://primevue.org/tabs/#tabmenu

A fix worked for me :

```vue
<Tabs v-if="menus">
    <TabList>
        <Tab v-for="tab in items" :key="tab.label" :value="tab.route" @click="router.push(tab.route)">
            <div class="flex flex-row gap-2 items-center">
                <i :class="tab.icon" />
                <span>{{ tab.label }}</span>
            </div>
        </Tab>
    </TabList>
</Tabs>
 ```

### Reproducer

https://primevue.org/tabs/#tabmenu

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Thanks a lot for your report!

**Comment by tugcekucukoglu** [comment]
The description says router-view is not implemented in the demo. Could you send a reproducer?

**Comment by luke-z** [comment]
Could replicate the problem on my side.
The issue is the following:
![image](https://github.com/user-attachments/assets/7110e89b-e05c-4ff1-a45b-547b15f15211)
If you follow the example and add a router-link / nuxt-link then there's an anchor tag inside of the tab button. So this is the only part of the entire tab that is actually "clickable" with a link.

The documentation should rather include this example, which I can confirm works for me:
```
<Tabs :value="$route.fullPath">
      <TabList>
        <Tab value="/cockpit/my-organization" to="/cockpit/my-organization" as="router-link">
          {{ $t('myOrganization') }}
        </Tab>
        <Tab value="/cockpit/my-organization/users" to="/cockpit/my-organization/users" as="router-link">
          {{ $t('users') }}
        </Tab>
      </TabList>
    </Tabs>
```

This turns the entire tab button into an anchor tag. So clicking anywhere on the tab will navigate to the supplied link.

**Comment by luke-z** [comment]
@tugcekucukoglu Do I need to open a new issue for that?

**Comment by tugcekucukoglu** [comment]
Sorry for the late answer. Could you share a producer?

**Comment by Mettbrot** [comment]
Hi @tugcekucukoglu here is a reproducer based on the official template from the website:
https://stackblitz.com/edit/zpgc3a

**Comment by Mettbrot** [comment]
@Azoorb could you add the reproducer to the description and reopen this ticket please?

**Comment by Azoorb** [comment]
> @Azoorb could you add the reproducer to the description and reopen this ticket please?

Hey Mettbrot, thanks for the reproducer, but I can't reopen this issue. I think we need to create another one.

**Comment by Jarpiino** [comment]
any fix?

**Comment by Jarpiino** [comment]
oh found it, shame it's not on the official docs.
