### ISSUE TITLE
There are no IntelliSense for Components props in VSCode

### ISSUE THREAD

**Issue by kingshuaishuai** [primefaces/primevue#6013]
## Problems
When the mouse points to the component, the component type is indicated.

<img width="1623" alt="image" src="https://github.com/primefaces/primevue/assets/25154825/480167ac-ef03-43f1-8ae8-16395b40d885">

But, There's no intellisense when I type in props.

<img width="1660" alt="image" src="https://github.com/primefaces/primevue/assets/25154825/f2dabbe8-9476-4e06-9fff-4c01adbe9e88">

My Custom Components is normal. And It's type is Wrapped By `__VLS_WithDefaults<__VLS_TypePropsToOption<>>`, I can get intellisense for it.
<img width="1122" alt="image" src="https://github.com/primefaces/primevue/assets/25154825/55bad828-0271-4e32-9488-956bd0cad3d0">
<img width="803" alt="image" src="https://github.com/primefaces/primevue/assets/25154825/19c3c4d5-87c0-4761-9d89-de1cafe2e48b">

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-s6kabt?file=src%2FApp.vue

### PrimeVue version

4.0

### Vue version

^3.4.21

### Language

TypeScript

### Build / Runtime

Vite

**Comment by kingshuaishuai** [comment]
Maybe `DefineComponent` type in `@primevue/core` is incorrect, I change `DefineComponent`'s import from 'vue' in primevue/button, it works!

<img width="1201" alt="image" src="https://github.com/primefaces/primevue/assets/25154825/be032042-0a6d-44a6-b3d0-5a13ad5d53e5">

<img width="906" alt="image" src="https://github.com/primefaces/primevue/assets/25154825/c4ce95fc-f450-48a9-9717-8d3607c2e20c">

**Comment by kingshuaishuai** [comment]
I try to use `extends` to create new `DefineComponent` interface, it not woks. Maybe the type only can be written by vue's export .

**Comment by kingshuaishuai** [comment]
Maybe it is monorepo dependencies issue. before i installed vue in root project as dependencies and every child project as dev and peer dependency, then I delete all vue dependencies in child project, and just installed it on root project, the component prop intellisense is work!

**Comment by kingshuaishuai** [comment]
close

**Comment by 2234839** [comment]
My project also has this problem, vscode has no relevant type hints at all
![图片](https://github.com/user-attachments/assets/021f7403-6ead-445a-9e3e-678b753bbd98)

**Comment by kingshuaishuai** [comment]
> My project also has this problem, vscode has no relevant type hints at all ![图片](https://private-user-images.githubusercontent.com/28727933/349335742-021f7403-6ead-445a-9e3e-678b753bbd98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODM1NzksIm5iZiI6MTcyMTE4MzI3OSwicGF0aCI6Ii8yODcyNzkzMy8zNDkzMzU3NDItMDIxZjc0MDMtNmVhZC00NDVhLTllM2UtNjc4Yjc1M2JiZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAyMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNDViMzhjYzkyOTJiYjc5ZGRkNTdiZTA4ZTljOGJjMmVjZTEyZmVmYzU3MWU0Y2I3ZGUzMTZmNTMzNTMzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTuPTt_1sQjgXzIc85-qoQWWAh8372_gcJRZRJFOX1A)

我解决的步骤是 重新创建一个新项目，然后开启自动导入，发现新项目是 OK 的，然后在老项目中找是不是哪里出问题了，如果用的 vite，在 vite 中配置自动导入后，记得在 tsconfig 中引入 components.d.ts
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/9e3cb544-77ba-4418-b0da-ceaaa99233a2">
<img width="927" alt="image" src="https://github.com/user-attachments/assets/a471b476-1ac0-439d-808f-c09be7c1138d">
如果你用的是 nuxt，nuxt 中它的模块中关闭了 dts 文件的生成，你可以直接修改 node_modules 中的文件，开启 dts，然后使用 [patch-package](https://www.npmjs.com/package/patch-package) 创建一个补丁，之后在nuxt.config.ts中将对应的文件包含进来
<img width="755" alt="image" src="https://github.com/user-attachments/assets/5b40b025-7282-4e9d-80d5-73330fbcad83">
希望对遇到此问题的人有所帮助

English Version:
My solution is to create a new project, and then turn on the automatic import, found that the new project is OK, and then find out if there is something wrong in the old project, if you use vite, after configuring the automatic import in vite, remember to introduce components.d.ts in tsconfig:
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/9e3cb544-77ba-4418-b0da-ceaaa99233a2">
<img width="927" alt="image" src="https://github.com/user-attachments/assets/a471b476-1ac0-439d-808f-c09be7c1138d">

If you use nuxt, nuxt has modules that disable dts generation, you can switch to node_modules to enable dts. Then use [patch - package] (https://www.npmjs.com/package/patch-package) to create a patch, after nuxt. Config. Ts include the corresponding files:
<img width="755" alt="image" src="https://github.com/user-attachments/assets/5b40b025-7282-4e9d-80d5-73330fbcad83">

I hope this will be helpful to those who encounter this problem

**Comment by 2234839** [comment]
@kingshuaishuai  非常感谢你的帮助，但我这里新建一个项目，然后引入 primeVue 都无法获得正确的类型提示
![图片](https://github.com/user-attachments/assets/bbfe9d00-51f9-43e9-be8a-18fdd217ac46)

**Comment by kingshuaishuai** [comment]
> @kingshuaishuai 非常感谢你的帮助，但我这里新建一个项目，然后引入 primeVue 都无法获得正确的类型提示 ![图片](https://private-user-images.githubusercontent.com/28727933/349366703-bbfe9d00-51f9-43e9-be8a-18fdd217ac46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTQ5MzgsIm5iZiI6MTcyMTE5NDYzOCwicGF0aCI6Ii8yODcyNzkzMy8zNDkzNjY3MDMtYmJmZTlkMDAtNTFmOS00M2U5LWJlOGEtMThmZGQyMTdhYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA1MzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZGU5YzRjZGU1ZTBjYTk2OTQ0YmQ4MzllNDNiZmMyMWZmODdkYzNkMjNiNDVlZjdlMDUwOTFmOTMxMDg0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rpmQcAp1sZtyLt2TE02qVSFkkH6-in4dDkEA_mWKeI)

能出现这些就是有只能提示的
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/366eb3c2-1031-4ca7-b632-063095672d76">
:value 我的情况跟你一样，具体的值你可以点进组件内部查看具体类型，然后自己加就行：
<img width="730" alt="image" src="https://github.com/user-attachments/assets/e9765594-fab2-43d0-b70b-05bcdc492d87">
<img width="723" alt="image" src="https://github.com/user-attachments/assets/87f43475-448f-4fb2-97af-add7c5de7fce">

**Comment by 2234839** [comment]
这些是有的，我现在也是你这么个用法，但还是希望能够得到完整的类型提示，能够有类型报错

**Comment by 2234839** [comment]
@kingshuaishuai  https://github.com/primefaces/primevue/issues/5903#issuecomment-2241346807
