### ISSUE TITLE
TABS: Globally enabling Ripple breaks Scrollable Tabs

### ISSUE THREAD

**Issue by aeruggiero** [primefaces/primevue#6017]
### Describe the bug

When using scrollable in Tabs and having ripple globally enabled, the layout of the tabs breaks.

### Reproducer

https://primevue.org/tabs/#scrollable

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

https://primevue.org/tabs/#scrollable
Go here and enable ripple

### Expected behavior

It should behave like when Ripple is not enabled

**Comment by mertsincan** [comment]
Good catch! Thanks a lot for your report!
