### ISSUE TITLE
Multiselect dropdown closes after selecting one option

### ISSUE THREAD

**Issue by nanaaikinson** [primefaces/primevue#602]
Multiselect closes after an option is selected or even clicking in the filter box. There should be a way to select multiple options without the dropdown closes. Any help?

**Comment by technobulka** [comment]
Same problem. It's appears after fix multiselect in the dialog.

**Comment by devilwacause** [comment]
Line 167 -> MultiSelect.vue

` if (!this.disabled && (!this.overlay || !this.overlay.contains(event.target)) && !DomHandler.hasClass(event.target, 'p-multiselect-close')) {`

should be

` if (!this.disabled && (!this.$refs.overlay || !this.$refs.overlay.contains(event.target)) && !DomHandler.hasClass(event.target, 'p-multiselect-close')) {`

Changing this to pay attention to the reference works as expected.

**Comment by devilwacause** [comment]
#632

**Comment by nanaaikinson** [comment]
The way I fixed this issue was to downgrade the version i am using.. That is from 2.2.0 to 2.0.1

**Comment by cagataycivici** [comment]
This works for me;

https://www.primefaces.org/primevue/showcase/#/multiselect

Which versions does it happen?

**Comment by technobulka** [comment]
I have this problem on 2.2.0 and 2.2.1.

**Comment by nanaaikinson** [comment]
@cagataycivici version 2

**Comment by rafhaelpc** [comment]
Same problem in 2.2.1

**Comment by cagataycivici** [comment]
I was looking at v3 which works, adding v2.2.2 milestone to this.

**Comment by cagataycivici** [comment]
Fixed for 2.2.2 which is due later today, thank you.
