### ISSUE TITLE
Traverse to next element with key press of Enter

### ISSUE THREAD

**Issue by fwt-parth-jariwala** [primefaces/primevue#6023]
### Describe the bug

Now i want to implement that if i press enter in any element or component its should move focus to next element. Currently this behaviour is achieved by tab press by default.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-zofhup?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi,

This is not a PrimeVue issue. Please use discussions or our discord channel. 

Best Regards,
