### ISSUE TITLE
BaseComponent: Missing import 'isFunction'

### ISSUE THREAD

**Issue by mathisdudler** [primefaces/primevue#6024]
### Describe the bug

When using `usePassThrough` with the PassThroughOption `mergeProps = true` then the Error `isFunction is not defined` occurs.
This is also reproducible when using the directive `:ptOptions="{ mergeProps: true }"`.

I've hunted this Bug down to this change: https://github.com/primefaces/primevue/commit/796edf4c113932c2c01ec1371e3cc9e228ac5552#diff-628aa5aef48709786658e4fc862c3ea50d581a12497294252e6750be3e664c7e

There is just the `isFunction` import missing from `@primeuix/utils/object`.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-a9doer?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

ALL

### Build / Runtime

Nuxt

**Comment by mertsincan** [comment]
Good catch! Thanks a lot for your report!
