### ISSUE TITLE
InputMask: Passed props are not set

### ISSUE THREAD

**Issue by SwitzerChees** [primefaces/primevue#6025]
### Describe the bug

Properties like id or name are not passed through anymore to the native rendered input of type text.
The problem can be reproduced or seen directly in the official documentation:
V4 Documentation (https://primevue.org/inputmask/):
```vue
<div class="flex-auto">
    <label for="phone" class="font-bold block mb-2">Phone</label>
    <InputMask id="phone" v-model="value2" mask="(999) 999-9999" placeholder="(999) 999-9999" fluid />
</div>
```
The rendered native input element is missing the id="phone" prop:
![image](https://github.com/primefaces/primevue/assets/26026462/46393ea0-d906-4069-a5e5-d3b7b05265d7)

V3 Documentation (https://v3.primevue.org/inputmask/):
```vue
<div class="flex-auto">
    <label for="phone" class="font-bold block mb-2">Phone</label>
    <InputMask id="phone" v-model="value2" mask="(999) 999-9999" placeholder="(999) 999-9999" />
</div>
```

The rendered native input element has the id="phone" prop:
![image](https://github.com/primefaces/primevue/assets/26026462/33f97876-e5ca-41b0-bc4f-82a7aeb77c88)

This problem not only exists on the official documentation website but also when I use the component directly in my own application.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-yzbded?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. use InputMask component
2. define id or name property in the input mask
![image](https://github.com/primefaces/primevue/assets/26026462/6746ab06-4401-410a-9ef2-770c188a6673)

3. check the rendered html output and check if they are missing.
![image](https://github.com/primefaces/primevue/assets/26026462/3b62539e-00b5-44cd-be8d-8bccf5ef0191)

### Expected behavior

The same behaviour like on V3 and as described in the following part of the documentation (https://primevue.org/inputmask/#accessibility):

> InputMask component renders a native input element that implicitly includes **any passed prop**.

**Comment by SwitzerChees** [comment]
No there are no errors in the console, not on the official documentation page (https://primevue.org/inputmask/) and also not in my own application when I use the InputMask.

Back in V3 a native input element was used with v-bind:
https://github.com/primefaces/primevue/blob/v3-prod/components/lib/inputmask/InputMask.vue
![image](https://github.com/primefaces/primevue/assets/26026462/7e2ad74c-4328-4882-a7ae-468cb3ee71bb)

Now in the V4 there is now the :pt used from the InputText component:
https://github.com/primefaces/primevue/blob/master/packages/primevue/src/inputmask/InputMask.vue
![image](https://github.com/primefaces/primevue/assets/26026462/0b5e09e3-e1da-4b86-a767-b2d426f9c8de)
and props like **placeholder** and **class** have their own props now.

maybe something in the passthrough logic doesn't work as expected?

**Comment by mertsincan** [comment]
Thanks a lot! We'll fix it in the next version.

**Comment by vanpyrzericj** [comment]
Just want to add onto this that being able to pass the `type` attribute (which we can do for `<InputText>`) would also be ideal, in addition to the OP's attributes. 

This is helpful when, for example, an input mask of a phone number is added, where we want to set `type="tel"` for mobile keyboards to display the numeric keypad.

**Comment by tugcekucukoglu** [comment]
New pt usage of InputMask:

```
<InputMask
            :pt="{
                pcInputText: {
                    root: 'className'
                }
            }"
        />

```

**Comment by luke-z** [comment]
@tugcekucukoglu 
Isn't it a bit of an anti-pattern to place the id property inside a passthrough property instead of directly on the custom HTML element, which adds it to the input element?

**Comment by SwitzerChees** [comment]
That doesn't resolve the issue. Please check on your OWN documentation page the error remains even on your own page:
https://primevue.org/inputmask/#mask

![image](https://github.com/user-attachments/assets/16824088-9b03-4248-9846-ca3cb2907318)

And the rendered native input element doesn't have the id anymore.

![image](https://github.com/user-attachments/assets/45c1d53f-a2a3-41b5-b12f-619b001909e4)

If there is now a way to pass through attributes with PT then it would also make sense to update your own documentation ;-).

**Comment by tugcekucukoglu** [comment]
@luke-z agree with you. 

@SwitzerChees `id` property problem is obvious and there is no link with `pt` property. 

Could you create an issue about this defect? I can fix it for the next version.

**Comment by SamuelWei** [comment]
@SwitzerChees I copied most of this issue and create a new one as @tugcekucukoglu asked for: https://github.com/primefaces/primevue/issues/6100

**Comment by SwitzerChees** [comment]
@SamuelWei that's great thank you 👍🏼
