### ISSUE TITLE
Password: pass through to input failing

### ISSUE THREAD

**Issue by matt-voror** [primefaces/primevue#6027]
### Describe the bug

Pass through to input within Password component is not working.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-nudoc8?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Pass though values should appear on the input component within the dom.

**Comment by JaredCostall** [comment]
```
 pt:pc-input:root:data-test="test"
```

**Comment by idsalmantm** [comment]
<Password v-model="password" inputId="on_label" toggleMask pt:pcinputtext:root:class="w-full" pt:root:class="w-full" />
