### ISSUE TITLE
Menu Component not lining up correctly

### ISSUE THREAD

**Issue by devilwacause** [primefaces/primevue#603]
Primevue ^2.2.0 

![image](https://user-images.githubusercontent.com/24920886/97173608-d69e5f00-175e-11eb-8db2-ab5ffaeb7572.png)

Zoom doesnt change the location that I can see, its always to the right and down from the initiating button.

Thanks,

**Comment by cagataycivici** [comment]
Please create a new ticket with a test case that can help us to replicate, or if it happens on showcase a more detailed explanation using the live demo and we'll review again.
