### ISSUE TITLE
Drawer: Footer Div/Slot added by default

### ISSUE THREAD

**Issue by ShrinidhiRajeevKulal** [primefaces/primevue#6048]
### Describe the bug

In PrimeVue version 4, the Drawer component automatically includes a footer div or footer slot by default. This behavior occurs even when the footer slot is not explicitly mentioned or needed. We would prefer the footer to only be added when explicitly defined.
![screenshot](https://github.com/primefaces/primevue/assets/97423739/eccb63d7-bc4d-493a-935e-dfbee6ea66f7)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-18djpc?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

1. Use the Drawer component without specifying a footer slot.
2. Inspect the rendered HTML of the Drawer component.
3. Observe the presence of a footer div or slot.

### Expected behavior

The Drawer component should not include a footer div or slot unless explicitly defined by the user.

**Comment by Sandip124** [comment]
@ShrinidhiRajeevKulal the footer slot is introduced in primevue 4 by the team and was not available in primevue 3 and also managing slot with a boolean property on every slot is not good idea as it may break the ui somewhere. It kinda make sense here though.
I think it doesnot affect your ui and if it does then you can simply handle with pass through
```
:pt="{
footer: 'hidden'
}"
```
