### ISSUE TITLE
Dynamic Dialog with component loader

### ISSUE THREAD

**Issue by seijikohara** [primefaces/primevue#605]
I want to be able to display dialogs programmatically from outside the Vue instance.
Like Buefy's dialog component.
https://buefy.org/documentation/dialog#from-outside-vue-instance

**Comment by LadislavBohm** [comment]
And how would you specify content of the dialog? From what I can see in the docs Buefy has some pre-made confirmation dialog that you can easily make yourself with existing Dialog component here.

**Comment by seijikohara** [comment]
@LadislavBohm 
If possible, implement a pre-made dialog.
The content of the dialog can be specified by HTML string.

In Buefy, you can display a dialog like this

```javascript
Dialog.alert({
      type: "is-danger",
      title: "Error",
      message: `<div>An error has occurred.</div>`,
      hasIcon: true,
      confirmText: "Close"
    });
```

**Comment by cagataycivici** [comment]
This is in our roadmap, similar to PrimeNG Dynamic Dialog;

https://primefaces.org/primeng/showcase/#/dynamicdialog

**Comment by rubjo** [comment]
Thanks for making PrimeVue, it seems modern, very extensive and of high quality - a massive amount of work!

Like the OP, programmatic dialogs is probably the only feature I am really missing, coming from Buefy and some other frameworks.

It would be very helpful if the contents of the dialog could also be a component (https://buefy.org/documentation/modal/#programmatic) - but it does look like this is exactly how PrimeNG Dynamic Dialog works.

A year later, any updates on the status of this feature?

**Comment by TheParad0X** [comment]
I remember switching all the PrimeNg Dialogs to dynamic ones a few years ago. Now I am waiting to be able to do the same with PrimeVue... 😁

**Comment by tugcekucukoglu** [comment]
Could you please try to use v3.15.0? Dynamic Dialog is available for PrimeVue.
