### ISSUE TITLE
Menu section: PassThrough `context.item` has not right MenuItem entry

### ISSUE THREAD

**Issue by NicolaiHorlacher** [primefaces/primevue#6055]
### Describe the bug

The TieredMenu component doesn't have the right `context.item` set in the PassThroughMethodOptions.

In the example I try to set a `data-testid` with the PassThrough functionality based on the `id` field of the MenuItems.
This behavior works with the Menu component, but not with the TieredMenu component.

To illustrate the issue I gave every element with a `data-testid` a orange border.

Curiously if I use `context.item.item` to access the data it works fine.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-wrnwmq?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

`TieredMenu` should have the same behavior as `Menu`.

**Comment by frandmb** [comment]
Looks like this is also the case with the `props` property under `[Component]PassThroughMethodOptions`. The same incorrect pt type definitions for `context` and `props` seems to happen in many (if not all) components.
