### ISSUE TITLE
How can I append a DataTable filter overlay to any HTML element, excluding the default Protal value "body"? 

### ISSUE THREAD

**Issue by andrew-cmdltt** [primefaces/primevue#6063]
I know that PrimeVue has a Portal component that is used for appending wrapped elements to any HTML element. For this, we should provide the appendTo property with a string value to find an HTML element by querySelector (#needSelector, .needSelector and so on). I use this property forCalendar, but is there a similar prop for DataTable column filters? It will be vety helpfull for Module Federation where the styles of shared application incapsulated by selector and overlays can't be appended outside the application wrapper element.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
