### ISSUE TITLE
How to pass slots through from Parent to Child Components with PrimeVue?

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue#6086]
### Describe the bug

I am trying to wrap some PrimeVue components to make my own component library. But how do I handle all the slots?

Some PrimeVue components have a large number of slots so passing each one individually would be a massive pain.

Fortunately, I found [this solution](https://gist.github.com/loilo/73c55ed04917ecf5d682ec70a2a1b8e2?permalink_comment_id=4389210) to pass all slots from Parent to Child Component.

Here is an example in use with the PrimeVue [Dropdown](https://v3.primevue.org/dropdown/#api) component:

```Vue
<Dropdown v-bind="$attrs" >
  <template v-for="(_, name) in $slots" #[name]="scope">
    <slot :name v-bind="scope" />
  </template>
</Dropdown>
```

Unfortunately, it doesn't work with PrimeVue because TypeScript it gives this error on `#[name]` regarding no index signature on `DropdownSlots`:

>Element implicitly has an 'any' type because expression of type 'string | number' can't be used to index type 'DropdownSlots'.
>
>No index signature with a parameter of type 'string' was found on type 'DropdownSlots'. ts(7053)

Any ideas for a fix or workaround?

P.S. I tried re-creating the error in stackblitz but I couldn't get it to show. Not sure what settings I need to tweak for that or if it's even possible to make it show there. I provided the live reproduction regardless.

### Reproducer

https://stackblitz.com/edit/primevue-3-vite-ts-issue-template-2mr5hg?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by BenJackGill** [comment]
Answering my own issue here, but I found this fantastic package called Vue Forward Slots to solve all these issues related to forwarding slots: https://www.npmjs.com/package/vue-forward-slots

I am using it like this to forward all slots (including the default slot):

```lang-Vue
  <ForwardSlots :exclude="[]">
    <Dropdown
      :id="id"
      v-bind="$attrs"
      v-model="modelValue"
    />
  </ForwardSlots>
```

I hope someday something like this makes it's way into core vue.js.

**Comment by yzzting** [comment]
I think it may not be closely related to PrimeVue itself, and you can try using inject and provide to solve it.
