### ISSUE TITLE
DataTable: Changing datatable.header.cell.padding doesn't work properly

### ISSUE THREAD

**Issue by dilepremon** [primefaces/primevue#6090]
### Describe the bug

While changing DataTable.header.cell.padding using definePreset, it doesn't work properly (has no effect)
![Screenshot 2024-07-22 at 11-56-26 DataTable wrong padding - StackBlitz](https://github.com/user-attachments/assets/43321f31-0354-4d4e-af25-e9d8cfbac511)
.

### Reproducer

https://stackblitz.com/edit/8fykei

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox 128.0, Chrome 126.0

**Comment by bettercalljason** [comment]
You are using the `Noir` preset, which requires additional `colorScheme` configuration (https://primevue.org/theming/styled/#noir). An example can be found [here](https://primevue.org/theming/styled/#component).

Try something like this:
```typescript
const CustomPreset = definePreset(Noir, {
  components: {
    datatable: {
      colorScheme: {
        light: {
          header: {
            background: '{surface.100}',
            cell: {
              padding: '0.125rem 0.5rem',
            },
          },
        },
        dark: {
          header: {
            background: '{surface.100}',
            cell: {
              padding: '0.125rem 0.5rem',
            },
          },
        },
      },
    },
  },
});
```

**Comment by dilepremon** [comment]
Yes, you're right. Now it's working. But the same problem was with Aura. The strange thing that all other properties worked correctly without adding light/dark.
