### ISSUE TITLE
DatePicker: Disabled Dates functional check.

### ISSUE THREAD

**Issue by antlionguard** [primefaces/primevue#6096]
### Describe the bug

I wanna set disabled dates with result of the any given function to `disabledDates` props. If function returns true the date must be disabled. 

I just added example to reproducer.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-x47uux

### PrimeVue version

4.0.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Cannot run the stackblitz demo.
