### ISSUE TITLE
PrimeVue FileUpload FileLimit

### ISSUE THREAD

**Issue by devilwacause** [primefaces/primevue#610]
app.js:67178 [Vue warn]: Error in render: "TypeError: Cannot read property 'length' of null"

found in

---> <FileUpload> at node_modules/primevue/components/fileupload/FileUpload.vue
       <VueSimplePortal>
         <VueModal>
           <Panel> at node_modules/primevue/components/panel/Panel.vue
             <BannerManage> at resources/js/vuejs_views/BannerManage.vue
               <Root>
warn @ app.js:67178
logError @ app.js:68437
globalHandleError @ app.js:68432
handleError @ app.js:68392
Vue._render @ app.js:70097
updateComponent @ app.js:70611
get @ app.js:71022
Watcher @ app.js:71011
mountComponent @ app.js:70618
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:75588
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:78488
init @ app.js:69669
createComponent @ app.js:72517
createElm @ app.js:72464
createChildren @ app.js:72592
createElm @ app.js:72493
createChildren @ app.js:72592
createElm @ app.js:72493
createChildren @ app.js:72592
createElm @ app.js:72493
createChildren @ app.js:72592
createElm @ app.js:72493
createChildren @ app.js:72592
createElm @ app.js:72493
createChildren @ app.js:72592
createElm @ app.js:72493
patch @ app.js:73014
Vue._update @ app.js:70490
updateComponent @ app.js:70611
get @ app.js:71022
Watcher @ app.js:71011
mountComponent @ app.js:70618
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:75588
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:78488
init @ app.js:69669
createComponent @ app.js:72517
createElm @ app.js:72464
createChildren @ app.js:72592
createElm @ app.js:72493
patch @ app.js:73053
Vue._update @ app.js:70490
updateComponent @ app.js:70611
get @ app.js:71022
Watcher @ app.js:71011
mountComponent @ app.js:70618
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:75588
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:78488
Vue._init @ app.js:71556
VueComponent @ app.js:71691
mount @ app.js:138
(anonymous) @ app.js:68533
flushCallbacks @ app.js:68459
Promise.then (async)
timerFunc @ app.js:68486
nextTick @ app.js:68543
Vue.$nextTick @ app.js:70068
(anonymous) @ app.js:138
run @ app.js:71111
flushSchedulerQueue @ app.js:70855
(anonymous) @ app.js:68533
flushCallbacks @ app.js:68459
Promise.then (async)
timerFunc @ app.js:68486
nextTick @ app.js:68543
queueWatcher @ app.js:70947
update @ app.js:71087
notify @ app.js:67289
reactiveSetter @ app.js:67614
proxySetter @ app.js:71174
showAddDialog @ app.js:4559
invokeWithErrorHandling @ app.js:68407
invoker @ app.js:68732
original._wrapper @ app.js:74091
Show 22 more frames
app.js:68441 TypeError: Cannot read property 'length' of null
    at VueComponent.chooseDisabled (app.js:53783)
    at Watcher.get (app.js:71022)
    at Watcher.evaluate (app.js:71127)
    at VueComponent.computedGetter [as chooseDisabled] (app.js:71376)
    at Object.get (app.js:68648)
    at Proxy.render (app.js:58639)
    at VueComponent.Vue._render (app.js:70095)
    at VueComponent.updateComponent (app.js:70611)
    at Watcher.get (app.js:71022)
    at new Watcher (app.js:71011)

Getting this error in relation to a file limit

<FileUpload name="banner[]" :customUpload="true" @uploader="myUploader" :fileLimit="filelimiter" accept='image/*' chooseLabel="Browse">

filelimiter = 1

Code block in the FileUpload component triggering error is

chooseDisabled() {
            return this.disabled || (this.fileLimit && this.fileLimit <= this.files.length + this.uploadedFileCount);
        },

**Comment by cagataycivici** [comment]
Fixed via PR
