### ISSUE TITLE
Tabs / Cards and possible other components: Can not disable dark mode

### ISSUE THREAD

**Issue by CoolGoose** [primefaces/primevue#6102]
### Describe the bug

Hello folks.

I am trying to disable the dark-mode automatic usage in PrimeVue
Unfortunately even if the workaround with 
```
/* This ensures the application always uses the light theme, overriding the device's dark mode settings. */
html {
    color-scheme: light;
}
```
seems do disable part of it, it doesn't disable it for all components 

![image](https://github.com/user-attachments/assets/6609d6fa-eb10-4ca4-aaf2-6674d7606563)

Compared on how it works if i change my local theme to light mode.

![image](https://github.com/user-attachments/assets/826b3757-f047-47b1-9468-143fc24e50b2)

I tried using the darkModeSelector with a fake one

```
app.use(PrimeVue, {
    theme: {
        preset: BubtyPreset,
        options: {
            cssLayer: {
                name: 'primevue',
                // Enable PrimeVue CSS layer and configure the tailwind styles to have higher specificity with layering
                order: 'tailwind-base, primevue, tailwind-utilities',
                darkModeSelector: '.fake-dark-selector', // trying to also force a non-usage of the dark mode
            },
        },
    },
})
```
but it doesn't seem to work (the stackblitz repo only has darkModeSelector set to false, but that doesn't work either)

![image](https://github.com/user-attachments/assets/f4b4d425-3e66-43fd-9aac-189395696da1)
![image](https://github.com/user-attachments/assets/492af927-599b-4a13-8df2-0ab8309a3ea2)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-pua3pn?file=tailwind.config.js,src%2Fassets%2Fmain.css,src%2Fmain.js

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to the repro stackblitz, try on a Windows machine with light mode / dark mode , dark mode should not trigger.

### Expected behavior

Not use dark mode at all.

**Comment by fotovoltaice** [comment]
Hello, 
we have the exact same issue. 
we need to force somehow the primevue to exect light mode only, or to respect the tailwind/ nuxt3 color-mode setup.
Currently, color mode works ok, 
but the primevue is dark no matter if we change to light or not. 
we're in the dark here! 🤣 need help!

**Comment by CoolGoose** [comment]
@cagataycivici (I do apologize for the direct tagging) but I saw you updated the docs for how to force enable Dark mode constantly, but any way to force Light mode constantly 😅

**Comment by CoolGoose** [comment]
Actually this seems it's a PEBKAC error. 

darkModeSelector needs to be at the options level not cssLayer

app.use(PrimeVue, {
    theme: {
        preset: BubtyPreset,
        options: {
            darkModeSelector: '.fake-dark-selector', // trying to also force a non-usage of the dark mode
            cssLayer: {
                name: 'primevue',
                // Enable PrimeVue CSS layer and configure the tailwind styles to have higher specificity with layering
                order: 'tailwind-base, primevue, tailwind-utilities',
            },
        },
    },
})

**Comment by frankcapodanno** [comment]
Why is completed ? If I use the solution of @CoolGoose  the results is that all the components style are broken and the "light-theme" is not forced correctly. 
![Aura-Broken](https://github.com/user-attachments/assets/596f9c14-621a-407d-83e5-8a0a04e21997)

**Comment by fasterinnerlooper** [comment]
@frankcapodanno I'm not sure if maybe it's missing from your screenshot but I wonder if the reason that the styling isn't working is because you aren't importing Aura from `@primevue/themes/Aura`?

**Comment by cybtroxy** [comment]
Why is this closed? I’m having the same issue and I can’t make the dark mode go away 😅. I was hoping for a simple _disableDarkMode_ config option. I’ll appreciate any working settings you can provide.
Thanks in advance 🙏!!!

**Comment by MaciejJezierskiFiskars** [comment]
@cybtroxy had same problem yesterday. I don't have a proper fix but workaround:

Set fake selector

`createApp(App)
  .use(PrimeVue, {
    theme: {
      preset: Aura,
      options: {
        darkModeSelector: ".fake-dark-selector",
      },
    },
  })`

Set in config (unocss for me).

import { defineConfig, presetMini } from 'unocss'

export default defineConfig({
    presets: [
        presetMini({
            dark: {
                dark: '.disable-dark',
            }
        })
    ],
})

**Comment by swrzalek** [comment]
same issue as above.

**Comment by mertsincan** [comment]
Please see;
https://primevue.org/theming/styled/#darkmode
> It is also possible to disable dark mode completely using false or none as the value of the selector.

**Comment by Alpscloud** [comment]
Same problems with darkmode:
`app.use(PrimeVue, {
  theme: {
    preset: ThemePreset
  },
  options: {
    darkModeSelector: false
  }
});`

`darkModeSelector: false` - doesn't work. I see the dark theme components in my app... 

Somebody found the solution?

**Comment by unicorns4re4live** [comment]
> Please see; https://primevue.org/theming/styled/#darkmode
> 
> > It is also possible to disable dark mode completely using false or none as the value of the selector.

Thanks, that works for me!

**Comment by Haru-Kazumoto** [comment]
> Actually this seems it's a PEBKAC error.
> 
> darkModeSelector needs to be at the options level not cssLayer
> 
> ```
> app.use(PrimeVue, {
>     theme: {
>         preset: BubtyPreset,
>         options: {
>             darkModeSelector: '.fake-dark-selector', // trying to also force a non-usage of the dark mode
>             cssLayer: {
>                 name: 'primevue',
>                 // Enable PrimeVue CSS layer and configure the tailwind styles to have higher specificity with layering
>                 order: 'tailwind-base, primevue, tailwind-utilities',
>             },
>         },
>     },
> })
> ```

Works for me, thank you!

**Comment by agm1984** [comment]
Mine didnt fix it when i put `darkModeSelector: false` but the issue for me was when my macOS was set to dark mode, the website would have dark inputs and one page had a dark background also, so the fix for me was to find the CSS acting and it was this:

Changing it to this fixed it, now my site is always in light mode:
```css
:root {
  color-scheme:light;
}
@media (prefers-color-scheme:dark) {
  :root{
    color-scheme:light !important;
  }
}
```

EDIT: I just had this problem again in another app, and it turned out that my `options` key in my PrimeVue config was in the wrong place. Claude actually fixed it for me:

Here is the working config:
```
    .use(PrimeVue, {
        theme: {
            preset: MyPreset,
            options: {
                darkModeSelector: false,
                cssLayer: {
                    name: 'primevue',
                    order: 'tailwind-base, primevue, tailwind-utilities',
                },
            },
        },
    })
```

**Comment by PaulloClara** [comment]
this worked for me

```ts
primevue: {
    options: {
      theme: {
        preset: PrimevueThemePreset,
        options: {
          darkModeSelector: false,
        },
      },
    },
  },
```

**Comment by levine404** [comment]
I'm also curious why this is marked as closed.  This seems fundamentally broken.  Toggling Dark mode only seems to work at the system level.  It's a bit of nuisance to have to toggle dark/light at the system level to test.  I've tried all approaches in this thread, and have not found any configuration that works.

* The `darkModeSelector: false` and `darkModeSelelctor: ".some-target"` does not behave as expected, if my device (windows) is configured as Dark mode, dark mode will always be on, if Light mode is configured at the device level, light mode will always be on, regardless of this property
* When forcing light mode via CSS, or Google Chrome settings, PrimeVue still seems unaware of the light mode

**Comment by ceferrari** [comment]
> I'm also curious why this is marked as closed. This seems fundamentally broken. Toggling Dark mode only seems to work at the system level. It's a bit of nuisance to have to toggle dark/light at the system level to test. I've tried all approaches in this thread, and have not found any configuration that works.
> 
> * The `darkModeSelector: false` and `darkModeSelelctor: ".some-target"` does not behave as expected, if my device (windows) is configured as Dark mode, dark mode will always be on, if Light mode is configured at the device level, light mode will always be on, regardless of this property
> * When forcing light mode via CSS, or Google Chrome settings, PrimeVue still seems unaware of the light mode

@CoolGoose

**Comment by Arthurin915** [comment]
> this worked for me
> 
> primevue: {
>     options: {
>       theme: {
>         preset: PrimevueThemePreset,
>         options: {
>           darkModeSelector: false,
>         },
>       },
>     },
>   },

This was the only thing that worked for me, no need to overide the css color-scheme in root or try to force prefered color scheme.

**Comment by agm1984** [comment]
> this worked for me
> 
> primevue: {
>     options: {
>       theme: {
>         preset: PrimevueThemePreset,
>         options: {
>           darkModeSelector: false,
>         },
>       },
>     },
>   },

that didnt work for me. only overriding the root css works when MacOS is in dark mode

**Comment by Prains** [comment]
have the same issue with windows 11 dark mode preference

darkModeSelector: false did not forced it to be light mode. only overriding all css selectors did help

**Comment by wind-of** [comment]
> Please see; https://primevue.org/theming/styled/#darkmode
> 
> > It is also possible to disable dark mode completely using false or none as the value of the selector.

Thanks, worked for me.

**Comment by gleenk** [comment]
Is it possibile to disable darkmode also in Volt?

**Comment by fachrihr** [comment]
> this worked for me
> 
> primevue: {
>     options: {
>       theme: {
>         preset: PrimevueThemePreset,
>         options: {
>           darkModeSelector: false,
>         },
>       },
>     },
>   },

Thanks. It works on nuxt.

```
// https://nuxt.com/docs/api/configuration/nuxt-config
import Aura from '@primevue/themes/aura';

export default defineNuxtConfig({
  compatibilityDate: '2025-05-15',
  devtools: { enabled: true },
  modules: [
    '@nuxtjs/tailwindcss',
    '@primevue/nuxt-module',
    '@nuxtjs/color-mode'
  ],
  primevue: {
    options: {
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.dark-mode',
        }
      }
    }
  },
  colorMode: {
    preference: 'light',
    fallback: 'light',
  }
});
```

**Comment by IsaacHayes1995** [comment]
For me it was tailwind causing the issue, as the dark variants are applied by 'prefers-color-scheme' rather than a css selector.

I added this to my css fixed the issue:
`@custom-variant dark (&:where(.dark, .dark *));`

As per the tailwind docs: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

It would then use the selector, rather than the system default.

**Comment by danillojose** [comment]
Why documentation about primevue also tailwind CSS is so confusing? I'm trying to creating an application with these and have many problems with configurations. Please unify and test the documentation before posting, you will help many users.
