### ISSUE TITLE
Popover: Incorrect tokens used in 'arrowLeft' calculation

### ISSUE THREAD

**Issue by confususs** [primefaces/primevue#6113]
### Describe the bug

Hi! I wanted to use the ConfirmPopup component / useConfirm service, but realized the arrow was a bit off when the target is located on the right side of the screen:

![Screenshot_2024-07-25_15-26-08](https://github.com/user-attachments/assets/592062b8-c5fc-42c8-a40a-2809aba3d02f)

Probably happened when tokens were updated in this commit: https://github.com/primefaces/primevue/commit/e7853c5f70372ae4245ab91071f526ca9b05396c#diff-89a7aba8600570cccf7cc7e48a1524d33e7a435c536e92160803a6154459d592R42

I don't know much about the token system yet, but I guess the token used should be named `confirmpopup.arrow.offset` instead of `popover.arrow.offset`, because in the end the token is converted to the `--confirmpopup-arrow-offset` variable.

Also, it appears that by overwriting the variable, the offset which originally was `1.25rem` is omitted too.

--

For ppl stumbling upon this issue, this is how I fixed it locally for now:
```
import ConfirmPopup from "primevue/confirmpopup";
import { $dt } from "@primevue/themes";
import { absolutePosition, getOffset, addClass } from "@primeuix/utils/dom";
ConfirmPopup.methods.alignOverlay = function () {
    absolutePosition(this.container, this.target, false);
    var containerOffset = getOffset(this.container);
    var targetOffset = getOffset(this.target);
    var arrowLeft = 0;
    if (containerOffset.left < targetOffset.left) {
        arrowLeft = targetOffset.left - containerOffset.left;
    }
    this.container.style.setProperty(
        $dt("confirmpopup.arrow.offset").name,
        "".concat(
            `calc(${arrowLeft}px + ${$dt("confirmpopup.arrow.offset").value})`
        )
    );
    if (containerOffset.top < targetOffset.top) {
        this.container.setAttribute("data-p-confirmpopup-flipped", "true");
        !this.isUnstyled && addClass(this.container, "p-confirmpopup-flipped");
    }
};
```

But even in the old version, the arrow isn't exactly centered on the target. Perhaps the offset should more like `calc(${arrowLeft}px + ${$dt("confirmpopup.arrow.offset").value} * 2 - 1px)`, but don't take my word for it.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-iv3wcz?file=src%2FApp.vue

### PrimeVue version

4.0.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use the stackblitz link and click the button

### Expected behavior

The arrow is perfectly centered on its target, regardless of target position in the screen

**Comment by leosin** [comment]
I have a question regarding the popover component. Although the popover can automatically align to the left or right based on the target's position relative to the window, how can I customize the alignment of the popover to the left or right manually?

**Comment by confususs** [comment]
> I have a question regarding the popover component. Although the popover can automatically align to the left or right based on the target's position relative to the window, how can I customize the alignment of the popover to the left or right manually?

Several ways - the easiest way would be to create an element in the DOM with your custom position and use that as a target (the way it is intended to be used) - a (much) harder way would be to mock an element and its position and pass it as a target to `useConfirm().require({target: fakeElement})`. 

Or perhaps you could add a class to the popover and set its position in css :man_shrugging:, but then the arrow won't point exactly to the your target
