### ISSUE TITLE
Docs: Error in guide for new styled mode

### ISSUE THREAD

**Issue by CaptainException** [primefaces/primevue#6114]
### Describe the bug

The example for the new styled mode is missing a trailing slash on the import: 
```js
import Aura from '@primevue/themes/aura';
```
This causes a module not found error.

### PrimeVue version

4.0.1

### Steps to reproduce the behavior

1. Go to https://primevue.org/theming/styled/#configuration

### Expected behavior

It should be:
```js
import Aura from '@primevue/themes/aura/';
```

**Comment by tugcekucukoglu** [comment]
Could you tell us your environment?
