### ISSUE TITLE
 API package not compiled? Missing: import { PrimeIcons } from "primevue/api";

### ISSUE THREAD

**Issue by cwdx** [primefaces/primevue#6117]
### Describe the bug

```bash
[vite] Internal server error: Failed to resolve import "primevue/api" from "Component.vue". Does the file exist?
```

### Reproducer

x

### PrimeVue version

4.0.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Any

### Expected behavior

In v3 we were able to import from `import { PrimeIcons } from "primevue/api";`
https://github.com/primefaces/primevue/blob/v3-prod/components/lib/api/PrimeIcons.js

In v4 the api doesn't seem to be compiled.
The source file doe exist in the `master` branch:
https://github.com/primefaces/primevue/blob/master/packages/core/src/api/Api.js
https://github.com/primefaces/primevue/blob/master/packages/core/src/api/PrimeIcons.js

![Screenshot 2024-07-26 at 11 06 49](https://github.com/user-attachments/assets/b23b6d9e-63b3-44d1-ab2d-61ff5448a0bc)

**Comment by matheusm** [comment]
I have the same issue! There are any advance?

**Comment by pulseczaralex** [comment]
Same issue

**Comment by tugcekucukoglu** [comment]
https://github.com/primefaces/primevue/blob/master/packages/core/src/api/Api.js#L4

Am I missing something?

**Comment by cwdx** [comment]
@tugcekucukoglu Yes the Api file looks correct, but I think it needs to be exported from the `package.json`

https://github.com/primefaces/primevue/blob/master/packages/primevue/package.json

You see, the export is missing there.

<img width="339" alt="Screenshot 2024-08-23 at 11 55 04" src="https://github.com/user-attachments/assets/5e3c7d19-7520-496a-9a47-de389157b790">

**Comment by cantin-f** [comment]
Still down in 4.0.5 :

import { FilterMatchMode, FilterOperator } from 'primevue/api';

Failed to resolve import "primevue/api" from "****.vue". Does the file exist?

**Comment by mertsincan** [comment]
Yep, please use `from '@primevue/core/api'` or `from 'primevue'`
