### ISSUE TITLE
Datatable select all visible rows

### ISSUE THREAD

**Issue by xybydy** [primefaces/primevue#612]
Hi,

I am playing with Datatable component and I intent to delete all visible rows but instead all rows, even unseen ones are deleted. In the source code it seems `onToggleAll` function in `MultiSelect.vue` file selects all the data whether you intent or not.

So is there any workaround to select all visible cell in a datatable?

**Comment by tugcekucukoglu** [comment]
It is available.
Please visit [https://primefaces.org/primevue/showcase/#/datatable/crud](https://primefaces.org/primevue/showcase/#/datatable/crud)

For example, first you need to use global filtering and check all/some filtered rows that you want to delete, then click the delete button. When you clear the global filter input, all the undeleted items will be seen.

Best,

**Comment by xybydy** [comment]
With using filters, yes. But I simply want to delete the first 10 visible items, it seems I can't do it.

**Comment by xybydy** [comment]
Using the filters, yes. But I simply want to delete the first 10 visible items, it seems I can't do it.
