### ISSUE TITLE
DatePicker: Day name didn't show when i set locale manualy

### ISSUE THREAD

**Issue by fahmi-nugroho** [primefaces/primevue#6125]
### Describe the bug

I set custom locale in main.ts with this

`locale: {
    dayNames: ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'],
    dayNamesShort: ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'],
    dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'], 
    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'Juli', 'August', 'September', 'October', 'November', 'December'],
    monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  },`
  
  
![image](https://github.com/user-attachments/assets/90651070-6331-428a-9aeb-dfacb10aa86d)
In my datepicker not showing dayNames

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-axfuz7?file=src%2Fmain.ts

### PrimeVue version

4.0.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by avramz** [comment]
Can reproduce, issue is shallow merge of default and custom options during install. PR is up.

cc @fahmi-nugroho
