### ISSUE TITLE
AutoImports in Nuxt broken since 4.0.0 release

### ISSUE THREAD

**Issue by Ripwords** [primefaces/primevue#6126]
### Describe the bug

Auto imports technically works but all the types seems to be missing since version 4.0.0 (can confirm it's still broken in 4.0.2)

I can confirm the last working version was 4.0.0-rc.3. In the screenshots below you can see i've upgraded 4.0.0-rc.3 to 4.0.0 and i lose syntax highlighting even if i explicitly enable autoImports in nuxt.config

![image](https://github.com/user-attachments/assets/d2dbcac9-523c-40ff-bbbb-908ab92c474d)

This is after i downgrade to 4.0.0-rc.3, i get syntax highlighting back even without specifying autoImports in nuxt.config
![image](https://github.com/user-attachments/assets/e1bccdf9-51b7-4816-bef7-fbeffef58091)

### Reproducer

nuxt_template_broken

### PrimeVue version

4.0.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Nuxt project install primevue ^4.0.0
2. Components don't have syntax highlights
3. Downgrade to 4.0.0-rc.3, and syntax highlights returns

### Expected behavior

Syntax highlights with newer versions

**Comment by dsherley9** [comment]
I'm also experiencing this issue.

**Comment by Ripwords** [comment]
Issue was solved for me in v4.0.4
