### ISSUE TITLE
SelectButton: context and state are missing

### ISSUE THREAD

**Issue by yu0307** [primefaces/primevue#6127]
### Describe the bug

for SelectButton control, `context` param is completely missing, and `state` param carries no value when using pass through

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-prpygz?file=src%2FApp.vue

### PrimeVue version

4.0.1

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

<template>
  <SelectButton
    :pt="{
      pcButton: ({ context, state }) => {
        console.log(context);
        console.log(state);
      },
    }"
    :allowEmpty="false"
    :options="['on', 'off']"
    aria-labelledby="basic"
  />
</template>

### Expected behavior

should have context param as instructed by the doc

**Comment by tugcekucukoglu** [comment]
Correct implementation:

```
<SelectButton
            :pt="{
                pcButton: {
                    root: ({ context, state }) => {}
                }
            }"
/>
```
