### ISSUE TITLE
Menu componets: Design Token does not work

### ISSUE THREAD

**Issue by ShiYaoDiving** [primefaces/primevue#6129]
### Describe the bug

Design token do not work on MENU, these is no 'PC{id}' in the <DIV>

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-fhzqdg?file=src%2FApp.vue

### PrimeVue version

4.0.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Just like the case demonstrating.
<MENU :dt="DESIGNTOKEN"> does not work

### Expected behavior

I think there must be some code missing....

**Comment by ShiYaoDiving** [comment]
I think it is because of the <Portal> of  Menu.vue.
If I remove the 
```vue
<Portal :appendTo="appendTo" :disabled="!popup">
``` 

(line2 in Menu.vue). 
The Design Token will work

**Comment by ShiYaoDiving** [comment]
I think it because of the Portal  is outside of the div.. it iwll influence all components with that:
autocomplete.calendar,,cascadeselect colorpicker contextmenu dialog dropdown menu multiselect overlaypanel....

**Comment by cromerc** [comment]
Running into the same problem here. Something of note, the problem only occurs when using a scoped design token. I can set the style using design tokens in my global component preset theme. However that isn't what I want to do, I want to use a scoped token to only style a specific menu and not all of them.

This is only primevue 4.0.4.

**Comment by ShiYaoDiving** [comment]
That’s right and i think it just because of the <Protal> If you remove them from Menu.vue and the dt will work

**Comment by micvm** [comment]
Is this the same matter also for the Dialog component?

https://stackblitz.com/edit/cnrvm8?file=src%2FApp.vue

**Comment by tugcekucukoglu** [comment]
Thanks for the reports. It'll be fixed for version 4.0.6.

**Comment by svwezel** [comment]
Button and Tabs Also don't seem to work.

**Comment by 2234839** [comment]
The select component is valid here before, but it is not valid today

**Comment by tugcekucukoglu** [comment]
Thanks for the stackblitz examples. We are investigating the issue, which will be fixed for the next version 4.1.0.

**Comment by deisner** [comment]
> Button and Tabs Also don't seem to work.

Could be https://github.com/primefaces/primevue/issues/6129. If you roll-back to Vue 3.5.5, does it work?
