### ISSUE TITLE
TreeTable: rowcheckboxicon slot is not implemented

### ISSUE THREAD

**Issue by JasonLandbridge** [primefaces/primevue#6130]
### Describe the bug

The slot [rowcheckboxicon](https://primevue.org/treetable/#api.column.slots.rowcheckboxicon) is not implemented in [TreeTable](https://primevue.org/treetable/#), although it is defined as such. 

A quick search in [TreeTableRow.vue](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/treetable/TreeTableRow.vue) reveals no mention of the slot rowcheckboxicon

### Reproducer

https://stackblitz.com/edit/wszd5u?file=src%2FApp.vue

### PrimeVue version

4.0.2

### Vue version

4.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. setup a treetable as normal
2. try to use the slot rowcheckboxicon with a valid icon
3. nothing happens

### Expected behavior

Expect the implementation of rowcheckboxicon such that custom checkboxes can be added and used with the treetable.

**Comment by KumJungMin** [comment]
The `Treetable` documentation states that there are three slots for controlling the checkbox icon on docs: [checkboxicon](https://primevue.org/treetable/#api.treetable.slots.checkboxicon), [rowcheckboxicon](https://primevue.org/treetable/#api.column.slots.rowcheckboxicon), and [headercheckboxicon](https://primevue.org/treetable/#api.column.slots.headercheckboxicon). 
In contrast, the `DataTable`, which is similar to `Treetable`, provides [rowcheckboxicon](https://primevue.org/datatable/#api.column.slots.rowcheckboxicon) and [headercheckboxicon](https://primevue.org/datatable/#api.column.slots.headercheckboxicon). 
Therefore, clarification is needed regarding the purpose of managing these slots.

- **Case 1**: If the purpose is to use `checkboxicon`, the explanations for `rowcheckboxicon` and `headercheckboxicon` should be removed from the documentation.
- **Case 2**: If the intent is to use `rowcheckboxicon` and `headercheckboxicon` like the dataTable, then `checkboxicon` should be removed from the documentation, and the code should be modified as proposed in the [PR](https://github.com/primefaces/primevue/pull/6131).

**Comment by tugcekucukoglu** [comment]
The `checkboxicon` slot is available for TreeTable.
