### ISSUE TITLE
Create default export for all Vue components

### ISSUE THREAD

**Issue by gwenf** [primefaces/primevue#614]
**Current Behavior:**

You have to import components separately:

```js
import Button from '...'
import Card from '...'

app.component('Button', Button)
app.component('Card', Card)
```

**Desired Behavior:**

There should be `index.js` and `index.ts` files in the root folder for components so we can use this syntax:

```js
import { Button, Card } from '...'

app.component('Button', Button)
app.component('Card', Card)
```

**Comment by cagataycivici** [comment]
We've done it for PrimeNG but then the whole suite gets imported to your app, which is not desired for bundle size. Instead you can create your own your-primevue-shorthand.js file and import-export the components from there to end up with;

```
import { Button, Card } from 'your-primevue-shorthand';
```

**Comment by mariusa** [comment]
For apps which do want to use most components and bundle size isn't an issue, is there a way to quickly setup all of them?

In vue 2 with bootstrap-vue, this worked:
```
import BootstrapVue from 'bootstrap-vue'
Vue.use(BootstrapVue)
```

Then all components were available in the entire app.

**Comment by tageecc** [comment]
any updates? @cagataycivici

**Comment by tageecc** [comment]
> For apps which do want to use most components and bundle size isn't an issue, is there a way to quickly setup all of them?
> 
> In vue 2 with bootstrap-vue, this worked:
> 
> ```
> import BootstrapVue from 'bootstrap-vue'
> Vue.use(BootstrapVue)
> ```
> 
> Then all components were available in the entire app.

any updates?

**Comment by epcgrs** [comment]
> For apps which do want to use most components and bundle size isn't an issue, is there a way to quickly setup all of them?
> 
> In vue 2 with bootstrap-vue, this worked:
> 
> ```
> import BootstrapVue from 'bootstrap-vue'
> Vue.use(BootstrapVue)
> ```
> 
> Then all components were available in the entire app.

In vue3 this not working, bootstrap-vue is only supported by v2 🙁

**Comment by xzdwq** [comment]
There is a way with a plugin for vite. It works for me

`vite.config.ts`
```ts
import Components from 'unplugin-vue-components/vite';

export default defineConfig({
  plugins: [
    Components({
      extensions: ['vue'],
      include: [/\.vue$/, /\.vue\?vue/],
      dts: 'src/components.d.ts',
      dirs: ['src/**/*', 'node_modules/primevue/**/*'],
    }),
  ],
});
```

```vue
<template>
  <div>
    <Toolbar>
      <template #end>
        <Button icon="pi pi-search" class="mr-2" />
      </template>
    </Toolbar>
  </div>
</template>

<script setup lang="ts">
// import Toolbar from 'primevue/toolbar';
// import Button from 'primevue/button';
</script>
```

**Comment by 2000sh** [comment]
The solution above worked for me.

**Comment by factoidforrest** [comment]
I'm concerned that this opinionated approach is inconvenient for those who do not need to hyperoptimize bundle size. I suggest that PrimeVue include a "loadAllComponents" option in the configuration object passed along with the plugin to `app.use`. Having it off by default is opinionated enough.

**Comment by factoidforrest** [comment]
I'm concerned that this opinionated approach is inconvenient for those who do not need to hyperoptimize bundle size. I suggest that PrimeVue include a "loadAllComponents" option in the configuration object passed along with the plugin to `app.use`. Having it off by default is opinionated enough.
