### ISSUE TITLE
Unstyled DatePicker throws error onKeyDown if input field is empty 

### ISSUE THREAD

**Issue by mikahozz** [primefaces/primevue#6147]
### Describe the bug

When opening the calendar and clicking an arrow down, DatePicker throws an error: 
```
TypeError: Cannot read properties of undefined (reading 'focus')
    at Proxy.trapFocus (primevue_datepicker.js?v=ecbf9ced:4352:46)
    at Proxy.onKeyDown (primevue_datepicker.js?v=ecbf9ced:4407:14)
    at callWithErrorHandling (chunk-YYVLN2RI.js?v=ecbf9ced:1678:19)
    at callWithAsyncErrorHandling (chunk-YYVLN2RI.js?v=ecbf9ced:1685:17)
    at HTMLInputElement.invoker (chunk-YYVLN2RI.js?v=ecbf9ced:10331:5)
```

Vue throws a warning with this info:
```
[Vue warn]: Unhandled error during execution of native event handler 
  at <InputText key=0 ref=fn<bound inputRef> id=null  ... > 
  at <DatePicker unstyled="" showIcon="" iconDisplay="button"  ... > 
  at <App>
```

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-1kvrox?file=src%2FApp.vue

### PrimeVue version

4.0.0-rc.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 126, Safari 17

### Steps to reproduce the behavior

1. DatePicker component with `unstyled` property
2. Empty input field
3. Open Calendar with the button
4. Click arrow down 

### Expected behavior

Navigating the calendar should work with arrow keys.

**Comment by cjalex1313** [comment]
I created this https://github.com/primefaces/primevue/pull/6155 as a fix

**Comment by mikahozz** [comment]
This seems to work now, thanks 👍
