### ISSUE TITLE
Typescript support is non-existent in All components

### ISSUE THREAD

**Issue by rafaelsmgomes** [primefaces/primevue#6152]
### Describe the bug

I get no typescript support on my template section with Primevue.
There is no destructuring, no way of knowing what props do I need to pass to the template slots. 
It's really bad. 
I thought the problem was just mine, but I don't think so.
I use neovim, so I tried fumbling with the configuration (mind you this does not happen with other 3rd-party components).
Then I gave up and switched to VSCode, still nothing.
Dug through the documentation, basically almost no mention to typescript, except to say it has stellar support. 
One of my coworkers has the exact same problem. So I don't think this is just me. 

And there is no word anywhere of this issue. Either we're the only people facing this or most users don't use typescript. 

If I'm wrong, please point to me where in the docs do I need to look to set this up to work. 

Best

### Reproducer

I also don't get hints on stackblitz

### PrimeVue version

4.0.0-rc.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Just start a regular project with the recommended Vue build script. 
Then follow the steps to install Primevue. 

### Expected behavior

I expected some hints on the templates section, maybe I should not expect those.

**Comment by cagataycivici** [comment]
I'll check with the team, thanks. We are not aware of any issues until now but worth checking because the team spends a lot of time on type checking.

**Comment by tugcekucukoglu** [comment]
Vue recommends activating the Volar extension for VSCode after disabling Vetur. Have you had a chance to try this?

**Comment by rafaelsmgomes** [comment]
Yes, using Volar with Typescript with the recommended configuration for Nvim.
I did try all the possible iterations of the recommended setup. 
Also tried on VSCode. This is just the default setup. 
Tried this with multiple projects, still not getting any type checking on my project. 

The weird thing is that other components have type-checking just fine.

Here is some screenshots for example:
<img width="1448" alt="image" src="https://github.com/user-attachments/assets/89da53e7-8937-40cf-b81e-6acd3d945f66">
<img width="981" alt="image" src="https://github.com/user-attachments/assets/f475fb95-1960-4044-8d2d-756be1a97f79">

**Comment by rafaelsmgomes** [comment]
I do get type checking on the script part though.
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/e8912793-31dd-47e0-89f1-ce58a3c29342">

**Comment by rafaelsmgomes** [comment]
Just by sheer amounts of tries, I've had it working sometimes when my main typescript configuration breaks.
For some reason, when I change the tsconfig and save without reloading, the typechecking will work on the primevue elements, but break everywhere else. 
If I restart the TSServer, then it will stop working for Primevue, but work for the rest of the project again. 

Very weird. I've changed my configuration in every each way, still getting this error. 

Again, the weird part is that other 3rd party components work just fine

**Comment by tugcekucukoglu** [comment]
Could you try to fork and use this [example](https://stackblitz.com/edit/vitejs-vite-wdrk3k) locally? Also, sharing a demo or a repo with your setup helps us.

**Comment by rafaelsmgomes** [comment]
Played around with what you sent me and it worked. 

Realized that it was a newer version of the package `primevue@4.0.4` and updated. 
Types are working now! Thanks!

**Comment by rafaelsmgomes** [comment]
Nope, might have spoken too soon. 
Well, it did work for me locally. I'm gonna try to play around with this and will give you an update. 
Not sure where the problem is though. 
I'll try to build a new repo from scratch and test it again. I'll share that with you guys. 
Can't share our current repos cause they are work related.

**Comment by rafaelsmgomes** [comment]
Still can't get it to work on my work project, but running from your default setup there has been some typing. 
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/349659fd-2a14-4634-b526-4d0403285a92">

Although it quickly deteriorated. For some reason this typing on the props was working 5 minutes ago, and now it no longer is...
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/6869a8e1-8e93-434c-9a50-2639c8536061">

This is your own repo that you shared.
I had the exact same result with a clean repo started with `bun create vue@latest`

**Comment by rafaelsmgomes** [comment]
Same result in VSCode.
I also don't use VSCode a lot, so this is the recommended setup for it. Basically only installed Vue stuff.

<img width="1277" alt="image" src="https://github.com/user-attachments/assets/d12ffe8e-88f3-4515-b431-04d232f9ab56">

**Comment by tugcekucukoglu** [comment]
A demo or a repository that we can test on would be very useful.

**Comment by Ripwords** [comment]
I'm not 100% but i think it's related to our issue as well #6126

**Comment by rafaelsmgomes** [comment]
I'll try the 4.0.4 release and see if it solves the issue!

**Comment by nicolascvoodoo** [comment]
Same issue here on VSCode + Vue (official) extensions and primevue@4.0.4. (macOS 14.5)

**Comment by nicolascvoodoo** [comment]
It may be related to https://github.com/primefaces/primevue/issues/6060

**Comment by i7slegend** [comment]
> It may be related to #6060

It's also reference to #5903 (already under team review), nearly to #6051 (nuxt module) and maybe to #6178

**Comment by jmroon** [comment]
To the PrimeVue team. The issue is the `DefineComponent` used in @primevue/core.

![image](https://github.com/user-attachments/assets/11fd3dca-d569-4051-a8bd-5df507bd9c37)

When the import is replaced with DefineComponent from vue, intellisense works as expected, both for explicit imports and also prefixed component names (e.g. for nuxt)

![image](https://github.com/user-attachments/assets/8487bc11-9148-43ff-b39d-53d5a483493b)

**Comment by jmroon** [comment]
Okay yeah I see the problem. The empty objects are overriding generics that are based on P. I'll submit a PR.

**Comment by nicolascvoodoo** [comment]
Hey guys, any news about this?

**Comment by Eirmas** [comment]
I created a PR to fix this
https://github.com/primefaces/primevue/pull/6477

**Comment by maersk96** [comment]
Got the same issue (v.4.1.0)
