### ISSUE TITLE
Stepper: The Template demo from the docs does not work

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue#6157]
### Describe the bug

I'm not sure why but the Stepper [Template demo](https://primevue.org/stepper/#template) from the docs does not show when opened in Stackblitz: https://stackblitz.com/edit/mjgmfs?file=src%2FApp.vue

Note: The actual demo embedded into the docs website still works. You have to open that same Template demo in Stackblitz to see that the component cannot be seen on the page.

### Reproducer

https://stackblitz.com/edit/mjgmfs?file=src%2FApp.vue

### PrimeVue version

4.0.3

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Stackblitz demo implementation defects. Live demos will be updated. Thanks for your attention.
