### ISSUE TITLE
[MenuBar]: Slow performance 

### ISSUE THREAD

**Issue by FabienVINCENT** [primefaces/primevue#6164]
### Describe the bug

When we have a large amount of data the component is very slow when displaying the submenus or hovers.

in primevue2 I had the same menu but I didn't have this problem (try in primevue3 same problem).

I tried with the Aura theme or with Tailwind presets, it's the same.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-tk2bqe?file=src/App.vue

### PrimeVue version

4.0.3

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Arc, chrome, firefox

### Steps to reproduce the behavior

1. Click on menu item
2. hover a submenu item
3. the submenu with large content is very slow and hover is laggy

**Comment by FabienVINCENT** [comment]
primevue 3 : [https://stackblitz.com/edit/primevue-3-vite-issue-template-qkvcjn?file=src/App.vue](https://stackblitz.com/edit/primevue-3-vite-issue-template-qkvcjn?file=src/App.vue)

primevue 2 : [https://codesandbox.io/p/sandbox/gifted-jang-6t45m5?file=/src/App.vue:28,1](https://codesandbox.io/p/sandbox/gifted-jang-6t45m5?file=/src/App.vue:28,1)

**Comment by avramz** [comment]
Can reproduce, fix in PR

**Comment by FabienVINCENT** [comment]
I confirm that it improves performance. On tests with 500 items it is still a little laggy but much less so. Thanks

**Comment by avramz** [comment]
There is also a transition on each list item, which visually looks like it's lagging when working with bigger lists, turning that one off improved overall experience for me. cc @FabienVINCEN
![Screenshot 2024-08-05 at 2 03 07 PM](https://github.com/user-attachments/assets/a277e6c6-3386-4de9-9e3d-2ca5bc847331)
T

**Comment by FabienVINCENT** [comment]
> There is also a transition on each list item, which visually looks like it's lagging when working with bigger lists, turning that one off improved overall experience for me. cc @FabienVINCEN ![Screenshot 2024-08-05 at 2 03 07 PM](https://private-user-images.githubusercontent.com/3598876/355094202-a277e6c6-3386-4de9-9e3d-2ca5bc847331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjE3NzQsIm5iZiI6MTcyMjg2MTQ3NCwicGF0aCI6Ii8zNTk4ODc2LzM1NTA5NDIwMi1hMjc3ZTZjNi0zMzg2LTRkZTktOWUzZC0yY2E1YmM4NDczMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTIzNzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc2YTM1OTAyN2YxNmVkNTNlMWEzYTE2YmI0NWFiYmQzYjdjNjZmYWI1ZGY1MmIyNmNlZmE4ZWIwMTczYTAwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2h8r1Cdte8Y3uXgtjOJCYpI25AhhxKSk2WjcUQRVU8I) T

not sure if this helps much in my case
