### ISSUE TITLE
DataTable columns and mounted propKey check not work properly

### ISSUE THREAD

**Issue by Aky22** [primefaces/primevue#617]
If the DataTable child has no properties, then the mounted and/or columns() computed prop throws error. 
The bug is in this specific statement: `child.$options._propKeys.indexOf('columnKey') !== -1` 

PrimaVue version: V2.0.8

**Comment by cagataycivici** [comment]
I can't replicate with 2.2.1;

```html
<DataTable></DataTable>
```

**Comment by philgruneich** [comment]
@Aky22 was clear that if a DataTable **child** has no props then the component throws the aforementioned error. I've managed to reproduce it by adding a "propless" component to the DataTable header slot.

```
<DataTable>
  <template #header>
    <MyProplessComponent />
  </template>
</DataTable>
```

The workaround is to add an empty props object to your propless component
```
export default {
  name: 'MyProplessComponent',
  props: {}
}
```
