### ISSUE TITLE
Button: iconPos not working when use custom icon

### ISSUE THREAD

**Issue by fahmi-nugroho** [primefaces/primevue#6174]
### Describe the bug

`<Button label="Update" iconPos="right">
        <template #icon>D</template>
      </Button>`

I set iconPos to right but this is what I get 
![image](https://github.com/user-attachments/assets/9c9f5366-2fba-4fa4-9eb8-7e53bad3544b)

### Reproducer

https://stackblitz.com/edit/qnqskt?file=src%2FApp.vue

### PrimeVue version

4.0.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
`class` option can be passed to icon slot.

```
<Button label="Update" iconPos="right">
            <template #icon="slotProps">
                <i :class="slotProps.class" />
            </template>
</Button>
```

**Comment by fahmi-nugroho** [comment]
Thanks, where can i read that kind of docs?

**Comment by tugcekucukoglu** [comment]
https://primevue.org/button/#api.button.slots.icon
