### ISSUE TITLE
Button with `as` doesn't work for NuxtLink

### ISSUE THREAD

**Issue by frasza** [primefaces/primevue#6180]
### Describe the bug

Creating a Button with `as: 'NuxtLink'` doesn't seem to work. If I use router-link it works.

Example:
```
<Button
   as="NuxtLink"
   label="Click"
   :to="{ name: 'index' }"
/>
```

### Reproducer

-

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Button uses `<component :is="as"` structure so, this is related to nuxtjs; https://github.com/nuxt/nuxt/issues/13659

**Comment by frasza** [comment]
@mertsincan I see, thank. Altho, if I set

```
<script lang="ts" setup>
const NuxtLink = resolveComponent('NuxtLink')
</script>
<template>
            <Button
              :as="NuxtLink"
              label="Click"
              :to="{ name: 'index' }"
            />
</template
```

I get error on type of `as`: `Type 'string | ConcreteComponent<{}, any, any, ComputedOptions, MethodOptions, {}, any>' is not assignable to type 'string | undefined'`. I couldn't find an answer in Nuxt post.

**Comment by frasza** [comment]
Note: if I ignore the error, it actually works, just seems to be conflicting types.
