### ISSUE TITLE
Datatable: [v4] filter is missing active class

### ISSUE THREAD

**Issue by TomasSimkus** [primefaces/primevue#6183]
### Describe the bug

missing filter active class as it was in v3
https://primevue.org/datatable/#advanced_filter

![image](https://github.com/user-attachments/assets/3e40794b-c27d-49e9-8551-4f19f96bc0cb)

https://v3.primevue.org/datatable/#advanced_filter

![image](https://github.com/user-attachments/assets/94e6f08e-8afa-4b97-bbec-056fa300fd2a)

### Reproducer

https://primevue.org/datatable/#advanced_filter

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by schoonc** [comment]
@TomasSimkus if you need a solution right now: https://github.com/primefaces/primevue/issues/5900#issuecomment-2247037376

**Comment by tugcekucukoglu** [comment]
There are some changes between v3 and v4. It is not a core bug.
