### ISSUE TITLE
Tabs: Wrong emit update:value type

### ISSUE THREAD

**Issue by alexey-yarmosh** [primefaces/primevue#6184]
### Describe the bug

index argument of the emit `update:value` event has type 'string', while it should be number.

### Reproducer

https://stackblitz.com/edit/ozcdfn-hex46x?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

https://stackblitz.com/edit/ozcdfn-hex46x?file=src%2FApp.vue

### Expected behavior

index has type number

**Comment by trombonist76** [comment]
In the `<Tab value="0">Header I</Tab>` binding, the value is a string. If you change it to `<Tab :value="0">Header I</Tab>`, it will emit the index as a number.

**Comment by alexey-yarmosh** [comment]
Expected type of prop is "string", so in that case it is `Type 'number' is not assignable to type 'string'.`

**Comment by tugcekucukoglu** [comment]
Fixed for the next version v4.0.5. 

Thank you.
