### ISSUE TITLE
AutoComplete: PT for input doesn't work

### ISSUE THREAD

**Issue by Brads3290** [primefaces/primevue#6189]
### Describe the bug

PT doesn't work for the input element of the AutoComplete component. The following code does not result in the `bg-red-500` class being added to the input:

```ts
<AutoComplete
    placeholder="Start typing.."
    :pt="{ pcInput: { class: 'bg-red-500' } }"
  />
```

According to [the docs](https://primevue.org/autocomplete/), `pcInput` is the correct passthrough target.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-wyukfi?file=src%2FApp.vue

### PrimeVue version

4.0.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by avramz** [comment]
Can repro, fix is in PR

**Comment by kaelonR** [comment]
I've found that all the `pcX` entries now point to other components within the PrimeVue library, and that these objects now need a `root` entry under which the classes are added.

So e.g. instead of doing this:
`{ pcInput: { class: 'bg-red-500' } }`

It will work if you do this:
`{ pcInput: { root: { class: 'bg-red-500' } } }`

**Comment by tugcekucukoglu** [comment]
Correct `pt` usage of InputText in AutoComplete:

`:pt="{ pcInput: { root: { class: 'bg-red-500' } } }"`

**Comment by calculabs** [comment]
> Correct `pt` usage of InputText in AutoComplete:
> 
> `:pt="{ pcInput: { root: { class: 'bg-red-500' } } }"`

Has this changed? Not working for me. Trying to use pt to apply p-0 class to the autocomplete input. Followed your usage exactly, does not reflect. 

![Screenshot 2025-01-09 at 4 54 19 PM](https://github.com/user-attachments/assets/1cb40dbf-c280-4ae8-aab7-576f742d532c)
![Screenshot 2025-01-09 at 4 51 46 PM](https://github.com/user-attachments/assets/09b6ba66-dd0b-4787-ac8c-e1b8e980830a)

**Comment by albydarned** [comment]
> Followed your usage exactly, does not reflect.

Same for me... Did you find a solution?
