### ISSUE TITLE
Select: Virtual scroll only rendering the first 12 values (Tailwind)

### ISSUE THREAD

**Issue by 1H-Alex** [primefaces/primevue#6190]
### Describe the bug

The Select component with virtual scroll activated only displays the first 12 values. After those values, the list is empty. The length of the list still seems to represent all of the values.

Please note that [official demo of the virtual scroll for the Select component in the Tailwind version of Primevue](https://tailwind.primevue.org/select/#virtualscroll) is not working correctly due to main.js trying to import none-existing components. Even if sanitized, the virtual scroll functionality in the Select component is still not working. When running this example with the latest version of Primevue (4.0.4), as seen in the example below, the code is still not working as expected. 

 **The 4.0.1 version with Tailwind** is also not working, see [example](https://stackblitz.com/edit/1kgcmj?file=package-lock.json). 

 **The 4.0.4 version without Tailwind** seems to be working, see [example](https://stackblitz.com/edit/voe2zk?file=src%2FApp.vue).

### Reproducer

https://stackblitz.com/edit/tmzwfq?file=package.json

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome V 127, Safari V 17.5 (19618.2.12.11.6), FF V 128

### Steps to reproduce the behavior

1. Click the Select input field
2. Scroll down
3. See that the list only shows the first 12 values and then an empty list. 

### Expected behavior

1. Click the Select input field
2. Scroll down
3. New values should appear as needed

**Comment by tugcekucukoglu** [comment]
Could you create an issue tailwind-primevue repo? It is not a core problem.

Also demo example seems to be working: https://tailwind.primevue.org/select/#virtualscroll

**Comment by ralfcarneborn** [comment]
Im having the same issue, not that the example that @1H-Alex showed was in unstyled mode, which is what i am using also.
The tailwind demo that @tugcekucukoglu , is that unstyled mode also?

If anyone has solved this please let me know.

**Comment by Nagell** [comment]
The connected ticket with a couple of solutions can be found here: https://github.com/primefaces/primevue-tailwind/issues/316
