### ISSUE TITLE
Disable ripple effect on some buttons

### ISSUE THREAD

**Issue by aastrum** [primefaces/primevue#6200]
How to disable ripple effect on one of the button in Nuxt 3?

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
