### ISSUE TITLE
VirtualScroller: Unstyled mode broke core functionality

### ISSUE THREAD

**Issue by ITSFerroli** [primefaces/primevue#6202]
### Describe the bug

When the unstyle mode is set to true, the VirtualScroller component, and all others that use it (e.g., MultiSelect, etc.), do not function as they should.

### Reproducer

https://stackblitz.com/~/github.com/ITSFerroli/vitejs-vite-txpng6

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Please refer to the issue at the provided link and try updating the unstyle parameter in the main.js file. If it is set to false, the VirtualScroller works correctly; if it is set to true, it does not.

**Comment by ITSFerroli** [comment]
duplicate #6294

**Comment by tugcekucukoglu** [comment]
duplicate
