### ISSUE TITLE
Button: In vuejs3, disabled button does not work if using as="router-link" property

### ISSUE THREAD

**Issue by init-daemon** [primefaces/primevue#6205]
### Describe the bug

In vuejs3, disabled button does not work if we use the as="router-link" property, same for loading, the loader is displayed but the button is not disabled

```html
<Button
  label="Annuler"
  severity="secondary"
  icon="pi pi-arrow-left"
  disabled
  :to="{ name: 'login' }"
  as="router-link"
/>
```

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-jwmema?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi,

I updated the demo with vue-router@4. Please try;
https://stackblitz.com/edit/primevue-4-vite-issue-template-9eegsb?file=src%2FApp.vue

Also, we don't add any class for the disabled to Button. You can make it using pt prop easily.
