### ISSUE TITLE
Dialog: Firefox Close Button Focus Issue

### ISSUE THREAD

**Issue by joshrap67** [primefaces/primevue#6208]
### Describe the bug

When using Firefox, (129.0), the close button immediately gains focus when the dialog opens. This does not occur on Chrome (127.0.6533.100).

Found it on the project I am working on, but it is reproducible on the Dialog's documentation [page](https://primevue.org/dialog/).

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-368xd9?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox (129.0)

### Steps to reproduce the behavior

1. Open the dialog
2. Observe the close button immediately gaining focus.
![firefox](https://github.com/user-attachments/assets/e7d8ca7a-40d0-4660-b1da-44cc0cd1f1ab)

### Expected behavior

That the close button does not gain focus unless the user initiates it. See chrome below
![chrome](https://github.com/user-attachments/assets/53722f49-1efa-450a-af71-3e7a7750543e)

**Comment by 2234839** [comment]
I have this problem too, and I can only hide it directly now


![图片](https://github.com/user-attachments/assets/32bfd34e-9be7-41b9-a3d8-ecdb103a187d)

**Comment by tugcekucukoglu** [comment]
Chrome does not reflect focusVisible styles but Firefox does. This is a difference between browsers.
