### ISSUE TITLE
DataTable filterMatchMode not working

### ISSUE THREAD

**Issue by ihelmer07** [primefaces/primevue#621]
using latest 3.0.1 and vue 3.0.2
The filterMatchMode is only using startsWith even if other modes are specified per the docs.
```
<Column :sortable="true" field="title" header="Title" filterMatchMode="contains">
              <template #filter>
                <input_text type="text" v-model="filters['title']" class="p-column-filter" />
              </template>
            </Column>

```

Unfiltered - with `filterMatchMode="contains"`
![image](https://user-images.githubusercontent.com/14080785/97887970-32815e80-1cf0-11eb-82aa-39a0a1dbf539.png)

add "we" - should bring back 3rd one:
![image](https://user-images.githubusercontent.com/14080785/97888038-4a58e280-1cf0-11eb-8ff6-6bd687ef7884.png)

add "a" should bring back top 3:
![image](https://user-images.githubusercontent.com/14080785/97888128-6197d000-1cf0-11eb-98cd-989e7302b034.png)

**Comment by tugcekucukoglu** [comment]
Hi,
Could you attach a code sandbox project or a repo, so we can try to replicate?

**Comment by cagataycivici** [comment]
Unable to replicate, if the issue persists please create a new ticket with a test case reproducing the issue e.g. codesandbox or a github repo and it will be reviewed by our team once again.
