### ISSUE TITLE
pi-spin doesn't make icon spin anymore.

### ISSUE THREAD

**Issue by anchan42** [primefaces/primevue#6213]
### Describe the bug

It not spinning in the documentation site too.
https://v3.primevue.org/icons/#spin

### Reproducer

https://v3.primevue.org/icons/#spin

### PrimeVue version

3.53

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome latest, fire fox

### Steps to reproduce the behavior

Go to the document page to see spin section of the icon component.

### Expected behavior

The icon should spin when p-spin applied.

**Comment by anchan42** [comment]
I tried it on FireFox, Chrome and Edge on the same computer and the icon was not spinning on all three browsers.
That was why I opened the issue. I tried it agian on iPad using Chrome this morning and it was working ok!! So it is my computer. Not sure what it is yet though.

**Comment by Owen3H** [comment]
I'm guessing this is related to https://github.com/primefaces/primeicons/issues/1159

**Comment by anchan42** [comment]
I tried it again on another computer. This one got Chrom, Edge, Firefox and Opera. The icon doesn't spin on all of them. The two computers that have the problem are Windows so it might be OS specific? Seem to be working ok on iOS and Andriod.

**Comment by Owen3H** [comment]
Windows strikes again. Unchecking the top one indeed solved it, ty!

**Comment by sslobodian-iqmessenger** [comment]
You can also play with this option to affect the animation:
![image](https://github.com/user-attachments/assets/1081630a-c222-4881-9513-8112634059c6)

If I redefine the animation style for `pi-spin` in my project, it will work regardless. So I believe it can be fixed on the library side.

**Comment by anchan42** [comment]
That make a lot of sense :)
