### ISSUE TITLE
Password: When `toggleMask` and `width: 100%` are used together the toggle icon moves outside the input

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue#6214]
### Describe the bug

When `Password` has `toggleMask` and `width: 100%` applied the toggle mask icon appears outside the input.

**Works with `toggleMask` - toggle icon stays inside the input:**
![Screenshot 2024-08-12 at 10 10 08 AM](https://github.com/user-attachments/assets/be96719e-3534-43a4-afe3-9dbc3ec6a3c4)

**Broken with `toggleMask` and `width: 100%` - toggle icon is outside the input:**
![Screenshot 2024-08-12 at 10 09 59 AM](https://github.com/user-attachments/assets/4b27f2be-22c8-4536-a4cb-eee739b02280)

```Vue
<template>
  <div class="card flex justify-center">
    <Password v-model="value" toggleMask style="width: 100%" />
  </div>
</template>

<script setup>
import { ref } from 'vue';

const value = ref(null);
</script>
```

### Reproducer

https://stackblitz.com/edit/oag7hm?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
`fluid` property can be used.

**Comment by Cyrille-Dakhlia** [comment]
@tugcekucukoglu could you explain a little bit more please?
I'm new to PrimeVue and I've tried to use the `fluid` property, but I haven't seen any change and I still face the issue, so I guess I'm missing something
