### ISSUE TITLE
DatePicker: Unable to change the year after selecting a date.

### ISSUE THREAD

**Issue by lircos** [primefaces/primevue#6215]
### Describe the bug

DatePicker component: after choosing a date, I am unable to change the selected year. To reproduce - select a date, and then open again the date picker and try to click on the year in order to change it.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-qhep7d?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. click on the input to select a date
2. open again the date picker
3. try to click on the year in order to change it.

**Comment by tugcekucukoglu** [comment]
Duplicate
