### ISSUE TITLE
Password: Using an external lib for the Strength Meter

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue#6216]
### Describe the bug

I am using the PrimeVue `Password` component with strength meter.

I want to integrate it with the [zxcvbn library](https://github.com/dropbox/zxcvbn) for checking password strength. The `zxcvbn` library provides a strength score, and I want to map that score to the strength meter.

Specifically, I want:

- A `zxcvbn` score of 2 for "medium" strength.
- A `zxcvbn` score of 3 for "strong" strength.

However, I'm unsure how to integrate this since the `Password` Strength Meter uses `mediumRegex` and `strongRegex` props to check for patterns in the input. I need guidance on how to use the `zxcvbn` score with these props, or maybe any other way of integrating the two.

```Vue
<template>
  <div class="card flex justify-center">
    <Password v-model="password" placeholder="Password" />
  </div>
</template>

<script setup lang="ts">
import { ref, watchEffect } from 'vue';
import zxcvbn from 'zxcvbn';

const password = ref(null);

// How do we use this 'score' for the Password strength meter?
// Score of 2 is medium, score of 3 or above is strong.
watchEffect(() => {
  if (password.value) {
    const { score } = zxcvbn(password.value);
    console.log(score);
  }
});
</script>
```

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-l62tv7?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by avramz** [comment]
At the current state, the Password component only accepts `mediumRegex` and `strongRegex` props. The component could be extended so it accepts a custom password strength fn (which would return a score of 0..3).

Happy to put a PR for this if needed cc @tugcekucukoglu @cagataycivici

**Comment by avramz** [comment]
@BenJackGill Workaround example: https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-zrqgvq?file=src%2FApp.vue

**Comment by tugcekucukoglu** [comment]
We do not provide support for 3rd party libraries that we don't use as dependencies. For example, the `strengthFn` prop might confuse users not using the mentioned library. Therefore, this PR is being closed.

**Comment by tugcekucukoglu** [comment]
For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by cagataycivici** [comment]
Instead we should give a hook to bind custom implementations, a PR to plugin a custom meter would be great instead of directly depending on it, we'd definitely merge then.

**Comment by avramz** [comment]
@cagataycivici The PR is not depending on anything, but is infact exposing a custom hook for the password strentgh, wether its a 3rd party lib or a custom implementation is up to the dev...
