### ISSUE TITLE
Inplace: Autofocus not working for content slot

### ISSUE THREAD

**Issue by lasficw** [primefaces/primevue#6218]
### Describe the bug

The `Inplace` Component currently doesn't support `autofocus` attribute on e.g. `InputText` component. This was already fixed somewhere in version 3 of PrimeVue but got broken again in PrimeVue 4.0.0.

There is also an example in the showroom where the `autofocus` is used but not working. See here: 
https://primevue.org/inplace/#input

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-xtudnc?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add `Inplace` component
2. Add `InputText` component with `autofocus` attribute to `content` slot
3. Add a simple `display` slot
4. Click on display
5. InputText is not focused automatically

### Expected behavior

The input should be focused automatically when the `autofocus` attribute is set

**Comment by tugcekucukoglu** [comment]
Using `content` slot, you can add a wrapper and `focustrap` directive for your demo.

**Comment by diadras** [comment]
The above comment wasn't really clear for me, but I figured it out. 
For some in the future that also doesn't fully understand the fix yet, here is what fixes the issue:

The autofocus issue (as seen in the demo) can be resolved by wrapping the `InputText` in a `div` and applying the `v-focustrap` directive to that div-wrapper.

Example:
```vue
<template #content="{ closeCallback }">
  <div v-focustrap>
    <InputText autofocus placeholder="Enter text.." @blur="closeCallback" />
  </div>
</template>
```
