### ISSUE TITLE
Accordion does not support dynamic tabs

### ISSUE THREAD

**Issue by LadislavBohm** [primefaces/primevue#622]
It seems like Accordion component does not support binding dynamic number of tabs. Following code does not work:

```
<Accordion>
   <AccordionTab v-for="tab in tabs" :key="tab.title" :header="tab.title">
      <p>{{tab.content}}</p>
   </AccordionTab>
</Accordion>
```

**Comment by ahegyes** [comment]
I can confirm this. v-for for the AccordionTab component doesn't work currently.

**Comment by dheimoz** [comment]
duplicated issue #616

**Comment by ntedgi** [comment]
This issue happens  because of this line 

at **Accordion.vue** :line 105

`            return this.$slots.default().filter(child => child.type.name === 'accordiontab');
`

when using **v-for** the child type is **Slot(Fragment)**

**Comment by cagataycivici** [comment]
Fixed and also added a demo for dynamic tabs.
