### ISSUE TITLE
ListBox: Why does selecting an already selected option deselect it? How to disable this behavior?

### ISSUE THREAD

**Issue by HppZ** [primefaces/primevue#6227]
### Describe the bug

selecting an already selected option deselect it.

### Reproducer

not necessary

### PrimeVue version

4.04

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

chrome 127.0.6533.100

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
