### ISSUE TITLE
Confirm: Can't disable draggable on confirm spawned by ConfirmationService

### ISSUE THREAD

**Issue by geiregjo** [primefaces/primevue#6240]
### Describe the bug

It's not possible to disable draggable on a Confirm spawned by the ConfirmationService.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-snlxqt?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Click the "Open Confirm" button
2. Drag the Confirm around

### Expected behavior

Expected Confirm not te be draggable.

**Comment by tugcekucukoglu** [comment]
Are you using ConfirmPopup or ConfirmDialog? Only ConfirmDialog has draggable prop.
