### ISSUE TITLE
PassThrough: does not override native styles

### ISSUE THREAD

**Issue by quantumwebco** [primefaces/primevue#6246]
### Describe the bug

When adding passthrough globally it doesn't override the native styles. If you set cssLayer option to true it overrides some styles but others are completely lost

How can I have the native styles with primevue but override some with tailwindcss

This used to be easy in primevue 3 by using css layers but it no longer seems to work in 4

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-8whkyh?file=src%2FApp.vue,src%2Fmain.ts,src%2Fassets%2Fmain.css

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

Please see https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-8whkyh?file=src%2FApp.vue,src%2Fmain.ts,src%2Fassets%2Fmain.css

### Expected behavior

Passthrough should override the styles from primevue

**Comment by quantumwebco** [comment]
This also affects adding classes to elements directly
![image](https://github.com/user-attachments/assets/4972a8e9-1bb7-488a-bed9-97ec5c1c79db)
![image](https://github.com/user-attachments/assets/b5eeb563-4b44-4d75-b70a-bc711b37cec1)

**Comment by tugcekucukoglu** [comment]
We could suggest using `!` prefix for tailwind classes.

Thank you.

**Comment by quantumwebco** [comment]
That doesn't work
