### ISSUE TITLE
Dialog: Modal mode changes background color in dark mode

### ISSUE THREAD

**Issue by tmorgan497** [primefaces/primevue#6247]
### Describe the bug

When using dark mode (by setting a body class of `p-dark`) with tailwindcss, having a modal dialog causes the background surface colors to toggle back to light mode until the dialog is hidden. I am using styled mode in Primevue with the Aura preset.

![dialog](https://github.com/user-attachments/assets/ac553ba7-60de-48fb-82cd-6a50a18c818d)

### Reproducer

https://github.com/tmorgan497/minimal-nuxt-primevuev4

### PrimeVue version

4.0.0-rc.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Edge 127.0.2651.105

**Comment by tmorgan497** [comment]
Using the html tag instead of the body tag seems to resolve the issue (if it's an issue).

The `toggleColorScheme()` function changed from

```javascript
function toggleColorScheme() {
    isDarkMode.value = !isDarkMode.value;
    if (isDarkMode.value) {
        document.body.classList.add("p-dark");
    } else {
        document.body.classList.remove("p-dark");
    }
    userStore.setDarkMode(isDarkMode.value);
}
```

to

```javascript
function toggleColorScheme() {
  isDarkMode.value = !isDarkMode.value;
  window?.document.querySelector('html').classList.toggle('p-dark');
}
```

Sample on stackblitz: https://stackblitz.com/edit/github-cvahdj?file=layouts%2Fdefault.vue

**Comment by tugcekucukoglu** [comment]
Interesting. I checked the stackblitz that you have shared: https://stackblitz.com/edit/github-cvahdj?file=layouts%2Fdefault.vue but cannot replicate. It might be related how to call `toggleColorScheme ` function.
