### ISSUE TITLE
Icon attribute supports component type

### ISSUE THREAD

**Issue by AAABingBing** [primefaces/primevue#6248]
### Describe the bug

The current use of custom icons can only be via the slot method

```vue
<script setup>
import IconAccount from '~icons/line-md/account'
</script>

<template>
  <Button label="Test">
    <template #icon>
      <IconAccount />
    </template>
  </Button>
</template>
```

It is recommended that all components of the icon property support the component type

Just like this:

```vue
<script setup>
import IconAccount from '~icons/line-md/account'
</script>

<template>
  <Button label="Test" :icon="IconAccount" />
</template>
```

### Reproducer

/

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for your suggestion. We currently recommend using icon slots for 3rd party icon libraries. The icon prop is designed for PrimeIcons. We can move it to discussions for more demand.
