### ISSUE TITLE
DataTable filtering versions

### ISSUE THREAD

**Issue by gogo2497** [primefaces/primevue#6253]
### Describe the bug

DataTable provides logic to filter numeric values ('less than', 'greater than', etc.). However, this works only for numbers (integers), while we might need to filter semantic versions ('1.2.0' for example). 

### Reproducer

no

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
