### ISSUE TITLE
Drawer: Nested drawer dissmis

### ISSUE THREAD

**Issue by FabienVINCENT** [primefaces/primevue#6262]
### Describe the bug

When we have a drawer nested in another and we change the value of "dismissable" the click on the mask of the child closes both

### Reproducer

https://stackblitz.com/edit/vitejs-vite-nu6jez?file=src/App.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Click to open parent drawer
2. Inside parent drawer click to open children drawer
3. Click on the children mask close both

**Comment by FabienVINCENT** [comment]
@tugcekucukoglu This is not fixed un 4.0.5 : https://stackblitz.com/edit/vitejs-vite-nu6jez?file=package.json,src/App.vue

**Comment by TY235** [comment]
Hi, it seems like the issue is not fixed when `modal` is set to `false`.
