### ISSUE TITLE
Toast: incorrect element pointers placement on the component image

### ISSUE THREAD

**Issue by kanishev** [primefaces/primevue#6265]
### Describe the bug

Hi! While exploring Toast Pass Through documentation I noticed that some of options are not correspond with pointers marked on the image above. F.e. value 5 is "messageText" but on the image it's a "messageIcon" i guess, and so on.

I thought to fix it by my own, but unfortunately I couldn't find the sources that create the image. 

### Reproducer

-

### PrimeVue version

4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to https://primevue.org/toast
2. Open the Pass Through section tab

**Comment by luke-z** [comment]
I see what you mean

![image](https://github.com/user-attachments/assets/fad8f4b8-fdeb-475d-aa40-5e83f85d987a)

For example Value 5 in the (Options table)[https://primevue.org/toast/#pt.doc.toast] reads messageText, however it should be messageIcon. It seems like Value 3 and Value 4 are redundant and thus everything is shifted by 1.

**Comment by tugcekucukoglu** [comment]
Thank you @luke-z . We are working on a new PT Viewer currently. It will be fixed.
