### ISSUE TITLE
Issue with PrimeVue Components: "Failed to resolve component" when integrating module into app

### ISSUE THREAD

**Issue by hungnguyen18** [primefaces/primevue#6268]
### Primevue component not found when writing in nuxt module and using that nuxt module to integrate into app.
I am experiencing an issue with PrimeVue components in my project. Here are the details:
**Project Setup:**

- I have two repositories: `app` and `module`.
- In module, I am using PrimeVue version 4.0.4.

**Issue Description:**

- When I start the application within the module, all PrimeVue components work as expected.
- However, when I integrate the module into the app, I encounter the following error: "Failed to resolve component" for all PrimeVue components.
<img width="611" alt="image" src="https://github.com/user-attachments/assets/bb015ed8-c595-4c89-aad4-387ebf4197ac">

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-kdvhuw

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Set up `module` with PrimeVue v4.0.4.
2. Integrate `module` into the `app`.
3. Attempt to use PrimeVue components within the `app`.

### Expected behavior

PrimeVue components should work correctly within the app after integration.

**Comment by tugcekucukoglu** [comment]
Cannot run stackblitz.
