### ISSUE TITLE
Textarea: When using auto-resize with rows="1" set, the initial height is incorrect

### ISSUE THREAD

**Issue by XuJinNet** [primefaces/primevue#6270]
### Describe the bug

I am using the Textarea component with auto-resize and rows="1" set, but the component’s initial height is incorrect, and the bottom of the text is obscured. It requires a keyboard input to recover to normal.
![image](https://github.com/user-attachments/assets/bc75d614-75c3-4635-a416-dd950592889f)

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-uj45rg?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 127

**Comment by svwezel** [comment]
Initial height is also wrong with a different value for rows (although less noticeably).

**Comment by GhostvOne** [comment]
Issue still here
