### ISSUE TITLE
DataTable:Has a fixed header, the header's border is displayed incorrectly.

### ISSUE THREAD

**Issue by yyj961010** [primefaces/primevue#6271]
### Describe the bug

When the header of the datatable component is fixed, scrolling the table causes the header's border to disappear. This issue occurs consistently when the table is scrolled vertically, making it difficult to distinguish the header from the rest of the table content

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-6zshgv?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### Steps to reproduce the behavior

Scroll the table to reproduce the problem

### Expected behavior

The table header border displays normally

**Comment by blockisec** [comment]
I do not have a fixed header and do not have header borders in v4 too.

**Comment by keving2301** [comment]
Having the same issue here. Header border disappears on scroll.

**Comment by tugcekucukoglu** [comment]
Please re-test it with v4.2.3. It seems the problem is solved. If you find another bug, please create a new issue.
