### ISSUE TITLE
Carousel: Is not working properly in unstyled mode

### ISSUE THREAD

**Issue by maschaut** [primefaces/primevue#6272]
### Describe the bug

In unstyled mode the Carousel has a very strange behaviour. It also ignores the "numVisible" property (directly in the component and in the responsiveOptions).

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-axu1gs?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Firefox, ..

### Steps to reproduce the behavior

The linked Stackblitz example works as expected in styled mode.
When you try this code in unstyled mode, it doesn't work anymore.

**Comment by tugcekucukoglu** [comment]
`responsiveOptions` is not supported in unstyled mode. Also, some visual distortions are expected in unstyled mode. We can recommend tailwind presets as an example. https://tailwind.primevue.org/carousel/#presets.lara

**Comment by maschaut** [comment]
So the only option is to adjust the presets to the behaviour you want to have?
Will there be improvements in future versions?
Maybe you should update the tailwind-docu for this component.
