### ISSUE TITLE
InputMask: input is getting mixed up

### ISSUE THREAD

**Issue by zyless** [primefaces/primevue#6276]
### Describe the bug

The input for the InputMask Component gets mixed up when unmask is set to true

https://github.com/user-attachments/assets/c1e94d48-87bd-484d-b262-78bbeae31322

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-ppqqfe?file=src%2FApp.vue

### PrimeVue version

4.0.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Use the following props for the InputMask Component:

```
mask="***** ***** ***** *****"
slot-char="_"
:auto-clear="false"
:unmask="true"
```

Type numbers into the Field

**Comment by alansgonzaga** [comment]
It was working on v3.
Anyone could make it work?
