### ISSUE TITLE
DatePicker: Format output value

### ISSUE THREAD

**Issue by KFRANCMM** [primefaces/primevue#6278]
Hi there, quick question about the DatePicker component. How can I format the output value when it's used in v-model? 

The prop format only affects the display but not the output value.
` <DatePicker v-model="date" aria-label="Date" date-format="yy-mm-dd" />
`
`Output: "date": "2024-08-22T19:21:40.946Z"`

For now the only solution for me is
`formatedDate =  date.value.toISOString().split('T')[0]`

But I think this is a difficult way to format each date entry in a form, do you have any simplified solution to format the output in that component?

**Comment by mazay33** [comment]
> Hi there, quick question about the DatePicker component. How can I format the output value when it's used in v-model?
> 
> The prop format only affects the display but not the output value. `<DatePicker v-model="date" aria-label="Date" date-format="yy-mm-dd" />` `Output: "date": "2024-08-22T19:21:40.946Z"`
> 
> For now the only solution for me is `formatedDate = date.value.toISOString().split('T')[0]`
> 
> But I think this is a difficult way to format each date entry in a form, do you have any simplified solution to format the output in that component?

@KFRANCMM 
check my answer https://github.com/primefaces/primevue/issues/1127#issuecomment-2361737407 may be useful
