### ISSUE TITLE
Select: Chinese IME input will be stopped in filter input element

### ISSUE THREAD

**Issue by charlie0228** [primefaces/primevue#6279]
### Describe the bug

When using Chinese, Japanese or Korean IME, when typing and select characters.
It will accident trigger unexpected  behavior in `<Select>` filter input and break up typing process.

Just like the GIF below, when I'm typing & using `Enter` to confirm the typing, the `<Select>` filter will trigger keydown Enter to close the dropdown panel.
And the Selected Item is not changed.

![Aug-23-2024 17-13-37](https://github.com/user-attachments/assets/da7b3f4a-84f4-4989-a6b2-24f67461b8f5)

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-a9rucv?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Using Chinese, Japanese or Korean IME to typing in `<Select>` filter input.

### Expected behavior

Avoid filter keydown detect when IME is composing.

**Comment by hurahurat** [comment]
Not only Select component but AutoComplete with chip.
When enter is press please detect when IME is composing.
ie.  if (event.isComposing || event.keyCode === 229) return;
