### ISSUE TITLE
Calendar wrong date in v-model

### ISSUE THREAD

**Issue by tudorels** [primefaces/primevue#628]
Hello, I noticed that when selecting the date in the calendar, the value in the v-model is wrong. For example when selecting the date 27.10.2020 the value in the v-model is 2020-10-26T22:00:00.000Z.
Can I make any settings to have the correct date? or it is a problem with calculating the time in the Calendar component?

Thank you!

**Comment by tugcekucukoglu** [comment]
Please use the forum for questions and support requests.

Best,

**Comment by tudorels** [comment]
I know how to use Calendar component, but I think it is a bug because the diplayed date is correct but in v-model is wrong 
 registered ... Thanks!

**Comment by tudorels** [comment]
Hello, I found an old bug that is related with this. I've noticed the same problem in Calendar component from primevue 3, the selected date is set in v-model to one day ago. Here is the link:
https://github.com/primefaces/primeng/issues/2426

Thanks!

**Comment by makurtu** [comment]
Yes, I found same bug, `v-model` is set to one day ago.

@tugcekucukoglu I don't know why not use GH instead of forum. In forum I can't search for a thread (I have to use Google to find something), so it's obviously that GH is more usable in terms of issue duplication. I think that if you want to move people use the forum, you must improve it!

**Comment by anchan42** [comment]
I think the best way to deal with this for application that is not care much about time zone is to remove it out completely.
Whith luxon, I did this:

```
//Make jsDateTime timezone agnostic
const removeTz = (jsDate) => {
  return DateTime.fromJSDate(jsDate).toISO({ includeOffset: false });
};

```
