### ISSUE TITLE
Whether to support uniapp

### ISSUE THREAD

**Issue by ylm-king** [primefaces/primevue#6288]
I want to use primevue in uniapp, but don't know how to introduce and use Primevue

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
