### ISSUE TITLE
Dock: not work

### ISSUE THREAD

**Issue by lichunxiao1130** [primefaces/primevue#6291]
### Describe the bug

in the Dock component,  the animation is not work

### Reproducer

https://primevue.org/dock/

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

chrome v128, edge v128

### Steps to reproduce the behavior

just go the showcase 'https://primevue.org/dock/'，it not work yet.

### Expected behavior

the animation work

**Comment by luke-z** [comment]
@tugcekucukoglu I think he's talking about the effect seen on the v3 dock when hovering over the icons. This does not appear on v4.

https://v3.primevue.org/dock/#basic vs. https://primevue.org/dock/#basic
