### ISSUE TITLE
DataTable: Selection highlight not working

### ISSUE THREAD

**Issue by csntr** [primefaces/primevue#6296]
### Describe the bug

When selecting rows by clicking them, the rows are not getting the `bg-highlight` class even though `highlightOnSelect` is set to true.

Best place to check this is the official docs: https://tailwind.primevue.org/datatable/#row_selection

### Reproducer

https://tailwind.primevue.org/datatable/#row_selection

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
It is not a core bug. Please create a ticket for tailwind-primevue project.
