### ISSUE TITLE
missing type definition for toast/useToast.js

### ISSUE THREAD

**Issue by johnalphared** [primefaces/primevue#630]

**Comment by tugcekucukoglu** [comment]
Hi,
Could you attach a codesandbox link or a repo?

**Comment by bernabei** [comment]
Hi @tugcekucukoglu,
I have a similar problem using TS with this steps:

1. Clone the official TS quickstart https://github.com/primefaces/primevue-typescript-quickstart
2. Following the documentation, add mitt dependency... npm install mitt --save
3. Configure Toast and ToastService in main.ts
4. Add <Toast /> in App.vue
5. import useToast in HelloWorld.vue component
6. run 'npm run serve' and this is the output (note that nothing change using prmievue/usetoast in lowecase):
ERROR in src/components/HelloWorld.vue:9:26
TS2307: Cannot find module 'primevue/useToast' or its corresponding type declarations.

**Comment by martinzaruba82** [comment]
Have the same issue and when i check primevue nodemodules:
![image](https://user-images.githubusercontent.com/72380131/98943751-48610180-24f0-11eb-821b-cdbdbdfbcf74.png)
The usetoast.d.ts is missing ....

**Comment by bernabei** [comment]
> Have the same issue and when i check primevue nodemodules:
> ...
> The usetoast.d.ts is missing ....

Exactly

**Comment by cagataycivici** [comment]
Fixed via 645

**Comment by dhax** [comment]
how is this fixed by a comment to manually add the d.ts after npm installing?
