### ISSUE TITLE
Button: `iconPos` not working if label is not given

### ISSUE THREAD

**Issue by oliver139** [primefaces/primevue#6300]
### Describe the bug

When using the `Button` component with `icon` and `badge` only, `iconPos` is not working until `label` is added.

### Reproducer

https://stackblitz.com/edit/fkyrqu?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

`iconPos` work as normal without adding `label`

**Comment by tugcekucukoglu** [comment]
The icon and label are lined up between each other. We couldn't decide if this is a bug. So we can move this issue to discussions.
