### ISSUE TITLE
Design token does not work with Drawer component

### ISSUE THREAD

**Issue by Ciriak** [primefaces/primevue#6302]
### Describe the bug

```vue
  <Drawer :visible="true" :dt="drawerColor">
    <SideBarMenu />
  </Drawer>
```

```typescript
const drawerColor = ref({
  background: '{amber.500}'
})
```

Result :
![image](https://github.com/user-attachments/assets/15297e87-41ec-4be4-ae6b-82a6d335031d)

Am i doing something wrong here ? This token should exist, right ? 

![image](https://github.com/user-attachments/assets/9f5900f5-e485-4fca-afff-8c29341ccad5)

I tried with the example provided in the documentation (using the `ToggleSwitch `component ) and it works fine

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-apgmml?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome latest

**Comment by tugcekucukoglu** [comment]
The changes coming with 4.1.0 will solve this issue. You could try it when it's released.
