### ISSUE TITLE
MultiSelect: Translation does not take effect

### ISSUE THREAD

**Issue by cromerc** [primefaces/primevue#6303]
### Describe the bug

MultiSelect does not show the locale translation when you have a comma separated select and have selected various items. It always shows in English.

In the stackblitz that I shared I show a working Select component that will change between English, Spanish or Chinese. Then after that there is a MultiSelect component that does not change language when the language is modified.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-v4fdq8

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add a multi select component that is comma separated and set its max selected labels to a value lower than the number of options.
2. Change the locale for the primevue components.
3. The translation does not take effect on this specific component.

### Expected behavior

The component should show "N elementos seleccionados" instead of "N items selected" if spanish is selected for example.

**Comment by avramz** [comment]
There is a `selectedItemsLabel` prop for MultiSelect, which takes precedence over the locale.
Demo: https://stackblitz.com/edit/primevue-4-vite-issue-template-shrs7a?file=src%2FApp.vue,src%2Fassets%2Fprimevuelocales.json

By looking at the code, the `selectedItemsLabel` [has a default value](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/multiselect/BaseMultiSelect.vue#L77), so `selectionMessage` from locale config will [never render](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/multiselect/MultiSelect.vue#L809). 
`selectedItemsLabel` should be removed in favor of locale data. Happy to put a PR for this. @tugcekucukoglu thoughts?

**Comment by c-scholz** [comment]
Stumbled across this today, too. Fix would be appreciated.

**Comment by avramz** [comment]
Fix in PR :)
