### ISSUE TITLE
Multiple Components: Background color classes not working without important

### ISSUE THREAD

**Issue by blockisec** [primefaces/primevue#6305]
### Describe the bug

using the sakai template, on multiple components like `Card` and `Button` the background color classes like `bg-primary` do not have any effect anymore in primevue 4. One must use `!important`. This also affects paddings and maybe other things.

### Reproducer

none

### PrimeVue version

4

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
`cssLayer` option of PrimeVue can be changed but we suggest using '!' prefix.

**Comment by quantumwebco** [comment]
The ```!``` prefix does not work in lots of cases. The whole passthrough and theming stuff is a mess
