### ISSUE TITLE
Unable to add css class to InputNumber

### ISSUE THREAD

**Issue by EnelKyss** [primefaces/primevue#6314]
### Describe the bug

Whenever I try to add any css working class, it will be placed in wrong div, not the one that actually matters.
InputText works.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template?file=README.md

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

chrome

### Steps to reproduce the behavior

add any class to <InputNumber /> component

### Expected behavior

added class should change the appereance of the input

**Comment by eneeio-nm** [comment]
@EnelKyss have you tried `inputClass` prop?
https://primevue.org/inputnumber/#api.inputnumber.props.inputClass

**Comment by eneeio-nm** [comment]
Here's an example of how I have been able to make an InputNumber have a blue border:
https://stackblitz.com/edit/oq5xjt?file=src%2FApp.vue
