### ISSUE TITLE
InputMask: unmask doesn't work properly

### ISSUE THREAD

**Issue by sohaibali123** [primefaces/primevue#6321]
### Describe the bug

When using unmask with component InputMask it scrambles text when typing away. 

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-8e6kdq?file=src%2FApp.vue

### PrimeVue version

4.0.0-rc.3

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Click on Input Mask
2. Start typing

### Expected behavior

Input should work like any other. You type and input shows what you typed as you type away.

**Comment by rodrigorodriguescosta** [comment]
I have the same issue, this is the main reason I started to use primevue, I need to get the raw value from v-model but it has the issue on that, I am unluck

**Comment by alansgonzaga** [comment]
#6276

**Comment by sohaibali123** [comment]
Duplicate issue.

**Comment by sohaibali123** [comment]
Duplicate Issue
