### ISSUE TITLE
Dropdown Label Not Showing Without v-model

### ISSUE THREAD

**Issue by danny007in** [primefaces/primevue#6330]
### Describe the bug

The `Dropdown` component's label is not displaying correctly when the `v-model` directive is not used. The issue occurs even though the `option-label` attribute is set correctly. The expected behavior is for the dropdown to show the label of the selected option, but it remains empty or shows the placeholder instead.

### Reproducer

https://stackblitz.com/edit/primevue-3-vite-ts-issue-template-8dokq5?file=src%2FApp.vue

### PrimeVue version

3.x

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a `Dropdown` component with the following configuration:
    ```vue
    <Dropdown
      id="dropdown_with_vmodel"
      v-model="selected_value"
      :options="options"
      option-label="label"
      placeholder="Search"
      filter
      dropdown-icon="false"
      filter-placeholder="Search"
      class="w-full md:flex md:basis-1/3"
      :class="{ hidden: headerFilterVselect }"
      @change="onOptionSelected($event)"
      @filter="onOptionSearch($event)"
    >
      <template #value="slotProps">
        <span v-if="slotProps.value">
          {{ slotProps.value.label }} |
          {{ slotProps.value.additional_info_1 }} |
          {{ slotProps.value.additional_info_2 }}
        </span>
        <span v-else>
          {{ slotProps.placeholder }}
        </span>
      </template>
      <template #option="slotProps">
        {{ slotProps.option.label }} |
        {{ slotProps.option.additional_info_1 }} |
        {{ slotProps.option.additional_info_2 }}
      </template>
    </Dropdown>
    ```
2. Populate the `options` array with some sample data.
3. Remove the `v-model` directive from the `Dropdown` component.
4. Observe that the dropdown does not display the label of the selected option.

### Expected behavior

**Expected Behavior:**
The dropdown should display the label of the selected option even if the `v-model` directive is not used.

**Actual Behavior:**
The dropdown does not display the label and shows the placeholder instead.

**Comment by tugcekucukoglu** [comment]
We suggest using `v-model` while selecting items.
