### ISSUE TITLE
Design token does not work with TieredMenu component 

### ISSUE THREAD

**Issue by asmussens** [primefaces/primevue#6331]
### Describe the bug

If I want to insert design tokens with the `dt` property in the TieredMenu it doesn't work

`<TieredMenu :mode="model" :dt="tokens" />`

Similar to the following issues:

- https://github.com/primefaces/primevue/issues/6302

Result:

![image](https://github.com/user-attachments/assets/8e02a456-a88e-40bc-b33a-08a034796bc5)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-ucemnj

### PrimeVue version

4.0.3

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by asmussens** [comment]
> I think it is a duplicate of #6129

But in that issue it is refering to the menu component. In this issue I am refering to the tieredMenu. Maybe they are related dont wanna exclude that possibility.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/6129
