### ISSUE TITLE
Sample code not working 

### ISSUE THREAD

**Issue by wangmengmike** [primefaces/primevue#6332]
### Describe the bug

I am testing the tree component of PrimeVue. I tried in stackblitz, all code worked fine.
Then I downloaded source code, to run locally in my PC. 
I first ran, npm install, end up with no error.
Then I tried to use npm run build, again no error.
Then tried npm run dev, it gives out lots of error with wrong coding:

rror: Build failed with 9 errors:
node_modules/@primevue/themes/aura/index.mjs:1:0: ERROR: Unexpected "%"
node_modules/@primevue/themes/index.mjs:1:0: ERROR: Unexpected "%"
node_modules/@primevue/themes/lara/index.mjs:1:0: ERROR: Unexpected "%"
node_modules/@primevue/themes/nora/index.mjs:1:0: ERROR: Unexpected "%"
node_modules/primevue/config/index.mjs:1:0: ERROR: Unexpected "%"
...
    at failureErrorWithLog (F:\workspace\nodejs\primevue-tree\node_modules\esbuild\lib\main.js:1649:15)
    at F:\workspace\nodejs\primevue-tree\node_modules\esbuild\lib\main.js:1058:25
    at F:\workspace\nodejs\primevue-tree\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 0,
        file: 'node_modules/@primevue/themes/aura/index.mjs',
        length: 1,
        line: 1,
        lineText: '%TSD-Header-###%�\x16ɠ�j�\x11��\x00�a<�\x01\x00\x04\x00�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x01\x00�U\x02�:�\x00\x00#�P\x00��;��H���~J��\x06����٪�8\x16;-��# ߀�w\x05s',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Unexpected "%"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 0,
        file: 'node_modules/@primevue/themes/index.mjs',
        length: 1,
        line: 1,
        lineText: '%TSD-Header-###%p\x17ɠ�j�\x11��\x00�a<�\x01\x00\x04\x00�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x01\x00���5:�\x00\x00Y�P\x00\f�H.\x01G\x19��-[4w\x0FI<t\x1A��S��*\fl�',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Unexpected "%"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 0,
        file: 'node_modules/@primevue/themes/lara/index.mjs',
        length: 1,

### Reproducer

https://stackblitz.com/edit/6bhs8h?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Download the https://stackblitz.com/edit/6bhs8h?file=src%2FApp.vue project.
2. Open the project with Visual Studio Code
3. npm run build
4. npm run dev, then I see the errors.

### Expected behavior

It's a sample from PrimeVue website. Which runs fine in the stackblitz. And I expect to see the project show's the same page as stackblitz.

**Comment by wangmengmike** [comment]
![image](https://github.com/user-attachments/assets/171d13ad-d9bd-4989-adac-201d2b348ed2)

**Comment by m-meier** [comment]
It looks like your package files are still compressed or encrypted (the files should not start with %TDS..). Try removing the whole node_modules folder and reinstalling it. If you problem persists, can you post your node version and the contents of your package.json?
