### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by c-scholz** [primefaces/primevue#6335]
### Describe the bug

The following icons exist in the PrimeIcons package and are listed in the PrimeVue docs but aren't exported members in the @primevue/core/api module:
- `ADDRESS_BOOK`
- `ARROW_DOWN_LEFT_AND_ARROW_UP_RIGHT`
- `ARROWS_ALT`
- `BELL_SLASH`
- `BUILDING_COLUMNS`
- `BULLSEYE`
- `CART_ARROW_DOWN`
- `CART_MINUS`
- `CHART_SCATTER`
- `CLIPBOARD`
- `COMMENTS`
- `CROWN`
- `EQUALS`
- `ETHEREUM`
- `EXPAND`
- `FACE_SMILE`
- `FILE_ARROW_UP`
- `FILE_CHECK`
- `FILE_PLUS`
- `FOLDER_PLUS`
- `GAUGE`
- `GRADUATION_CAP`
- `HAMMER`
- `INDIAN_RUPEE`
- `LIGHTBULB`
- `LIST_CHECK`
- `MARS`
- `MICROCHIP`
- `MICROCHIP_AI`
- `OBJECTS_COLUMN`
- `PAUSE_CIRCLE`
- `PEN_TO_SQUARE`
- `PINTEREST`
- `PLAY_CIRCLE`
- `RECEIPT`
- `REPLY`
- `SHOP`
- `SIGN`
- `SORT_UP_FILL`
- `SORT_DOWN_FILL`
- `STAR_HALF`
- `STAR_HALF_FILL`
- `THUMBTACK`
- `TIKTOK`
- `TROPHY`
- `TURKISH_LIRA`
- `TWITCH`
- `VENUS`
- `WAREHOUSE`
- `WAVE_PULSE` 

Please add them to the icons exported by the core api.

Also the following Icons are named wrong and should be renamed to: 
- `ARROW_H` -> `ARROWS_H` 
- `ARROW_V` -> `ARROWS_V`
- `MICREPHONE` -> `MICROPHONE`
- `SORT_ALPHA_ALT_DOWN` -> `SORT_ALPHA_DOWN_ALT` 
- `SORT_ALPHA_ALT_UP` -> `SORT_ALPHA_UP_ALT`
- `SORT_NUMERIC_ALT_DOWN` -> `SORT_NUMERIC_DOWN_ALT`
- `SORT_NUMERIC_ALT_UP` -> `SORT_NUMERIC_UP_ALT`

Please rename the keys to reflect the docs.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-7sp74y?file=src%2FApp.vue

### PrimeVue version

^4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. install PrimeIcons ^7.0.0 and PrimeVue ^4.0.0
2. `import { PrimeIcons } from '@primevue/core/api';` in a Vue SFC
3. bind `PrimeIcons.WAREHOUSE` or `PrimeIcons.WAVE_PULSE` to a HTML node's class attribute

TS Error: `Vue: Property WAREHOUSE does not exist on type PrimeIconsOptions`
In Browser: class attribute has no value

### Expected behavior

All icons available in PrimeIcons library should be exposed by the core/api module and have their keys named correctly.

**Comment by c-scholz** [comment]
I spent the 30mins manually comparing the index.d.ts file in the core/api module to the icon list in the docs and found many more missing and some wrongly named. Updated the Issue accordingly.

**Comment by d33p-dev** [comment]
hmm, i'm trying to use pi-trophy, pi-pulse-wave and a few others and they're not in the primeicons.css.  what is the fix for this?  i just did npm install primeicons but i already had what i think is the latest version

`    "primeicons": "^6.0.1",`

**Comment by d33p-dev** [comment]
Ok, I installed latest which is actually 7.0.0

`npm install primeicons@latest`

And, I have the icons now....
