### ISSUE TITLE
Using fontawesome with menus

### ISSUE THREAD

**Issue by leifcr** [primefaces/primevue#634]
I expected fontawesome to work with menus similar to how it works on buttons:
Code:

```vue
<template>
  <MenuBar :model="items" />
</template>

<script lang="ts">
import {
  Options,
  Vue,
} from 'vue-class-component';
import MenuBar from 'primevue/menubar';

@Options({
  components: {
    MenuBar,
  },
})
export default class App extends Vue {
  get items() {
    return  [
                { label: 'Home', icon: 'fa fa-home' }
            ]
    }
}
</script>
<style></style>
```

From the HTML I can see that instead of a <i> class, it creates the following:
```
<span class="p-menuitem-icon fa fa-home"></span>
```

Is it possible to change the tag of the icon on the menues to work with other iconsets?

**Comment by leifcr** [comment]
For fontawesome svg icons to wrok, it has to be in a <i> tag.

**Comment by cagataycivici** [comment]
span and i tags with font-awesome so closing the issue.

**Comment by leifcr** [comment]
@cagataycivici After testing a bit more, span works fine, but the tag cannot include ```p-menuitem-icon``` in the class. Could you either wrap the icon in a span with needed classes, or allow for removing of the class?
