### ISSUE TITLE
Datepicker: No manual input in view = 'year'

### ISSUE THREAD

**Issue by muelbr** [primefaces/primevue#6347]
### Describe the bug

Currently it is not possible to manually enter a year in the year picker mode like in the other modes.

### Reproducer

https://primevue.org/datepicker/#yearpicker

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to https://primevue.org/datepicker/#yearpicker
2. Type a correct year and press enter (or leave the focus)
3. Value is not taken

### Expected behavior

Entering manually a year like I am able to do so with view = date | month

**Comment by avramz** [comment]
Can repro, fix in PR
