### ISSUE TITLE
DataTable - VUE3 - TS

### ISSUE THREAD

**Issue by bpor92** [primefaces/primevue#635]
component: DataTable,
primevue: 3,
vue: 3,
typescript: 3.9.3

![image](https://user-images.githubusercontent.com/21037852/98906723-e5567700-24bd-11eb-97c6-dd0f11bd9a01.png)

**Comment by cagataycivici** [comment]
Please see;

https://github.com/vuejs/vue-cli/issues/4738

Seems like a tsconfig issue.
