### ISSUE TITLE
Speedial: Visible list bounding box

### ISSUE THREAD

**Issue by stepanhanzalek** [primefaces/primevue#6350]
### Describe the bug

When using the SpeedDial component, the (speed dial button) list is not being properly hidden and still has a bounding box at all times. `pointer-events` is being set when changing the state of the speed dial, but that does not hide the bounding box.

When you have elements you would like to interact with under the hidden list, you are not able to interact with the elements because of the bounding box.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-pgagzc?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Edge 128

### Steps to reproduce the behavior

Goto 'App.vue'. You should be able to click the button with 'X' on it. Well, you are not.

### Expected behavior

The button with 'X' should be clickable when the speed dial is not opened. The icons are hidden something else that using `display: none`, so their bounding box is still active and you are not able to click through it.

My solution was introducing the following overrides:

```css
.p-speeddial-open .p-speeddial-list {
  display: flex !important;
}
.p-speeddial-list {
  display: none !important;
}
```

Applying `display: none` to the list when its disabled and `display: flex` when its enabled. This resolved the issue.

**Comment by tugcekucukoglu** [comment]
We can't decide if this is a bug. So we can move this issue to discussions.

Thank you. It is closing for now.
