### ISSUE TITLE
Upgrading from PrimeVue 3.x with PrimeFlex to PrimeVue 4

### ISSUE THREAD

**Issue by d33p-dev** [primefaces/primevue#6362]
### Describe the bug

This is not a bug but since the forums are no longer viable, it's unclear where to post a question.  I have a PV 3.x PrimeFlex app that is going to launch soon but was considering upgrading to PV 4 and the new design system.  I have a LOT of code that uses the primeFlex classes.  Correct me if I'm wrong but looking at the PV 4 docs it seems it will be an almost complete rewrite of all my custom CSS classes that rely on PrimeFlex variables as well as many changes to PrimeVue components as well.  

Is there a migration guide somewhere?  Is PV 4 stable and is doing the upgrade going to benefit my app in someway?

### Reproducer

https://nothing.com

### PrimeVue version

3.latest

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

There are no steps to reproduce

### Expected behavior

There is no expected behavior

**Comment by eneeio-nm** [comment]
FYI there's a Discussion area on the main PrimeFace instance:
https://github.com/orgs/primefaces/discussions/categories/primevue

**Comment by tugcekucukoglu** [comment]
We strongly suggest using tailwind with PrimeVue 4. For migration: 

https://primevue.org/guides/migration/v4/
https://primevue.org/guides/primeflex/
