### ISSUE TITLE
ProgressBar: rendered text in progress bar not formatted properly as animation loads vl

### ISSUE THREAD

**Issue by s-wolfram** [primefaces/primevue#6363]
### Describe the bug

As the progress bar is loaded with the specified value, text that is added to ProgressBar, e.g.:
`<ProgressBar :value="56">283/500</ProgressBar>` could be stacked and rendered incorrectly :

<img width="126" alt="image" src="https://github.com/user-attachments/assets/e0ba0f2f-3791-473c-914c-5537e3a692dc">

Once the animation is finished loading, the it renders properly (if the percent large enough for the space needed to render the text)
Here is the image once the animation finished loading the progress-value:

<img width="124" alt="image" src="https://github.com/user-attachments/assets/44ae2e30-b944-4170-898e-e013fd325097">

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-stxvmd?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 128.0.6613.120 (Official Build) (64-bit)

### Steps to reproduce the behavior

Run this script (also linked with stackblitz above) and press the button to see the issue. 

```
<template>
  <div>
    <ProgressBar style="max-width: 400px" :value="value">
      {{ value * 1000 }} / {{ 100 * 1000 }}
    </ProgressBar>
    <button @click="onclick">
      press here to toggle and see the issue during animation
    </button>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const value = ref(1);

const onclick = () => {
  if (value.value === 1) value.value = 30;
  else value.value = 1;
};
</script>
```

### Expected behavior

As the animation loads the progress-value (percentage of progress bar), either hide the text until it is finished loading or determine programmatically what substring of the string can be rendered to not mess up the style.

**Comment by 1Map** [comment]
I could only fix this by setting some styles in the passthrough:

```
<ProgressBar style="max-width: 400px" :value="value" :pt="{
    value: {
      style: 'overflow: visible;'
    },
    label: {
      style: 'display: block; position: absolute; left: 0; width: 400px; text-align: center; white-space: nowrap; color: yellow;'
    }
  }">
    {{ value * 1000 }} / {{ 100 * 1000 }}
  </ProgressBar>
```

**Comment by tugcekucukoglu** [comment]
Thanks for the updates. It seems the problem is solved.
