### ISSUE TITLE
Popover: Focus not working

### ISSUE THREAD

**Issue by jameshhood** [primefaces/primevue#6366]
### Describe the bug

I have a use-case where I have an item I want to add to cart and I use a popover to take in a unit of measure and quantity.
![image](https://github.com/user-attachments/assets/4d66feaf-cb8d-45dc-babb-596b846756ec)

According to the documentation
> When the popup gets opened, the first focusable element receives the focus and this can be customized by adding autofocus to an element within the popup.

Since my unit of measure defaults to the first item in the index, I want to autofocus on the quantity for easy keying in. I've added the autofocus and nothing happens. I've tried adding a ref to the InputNumber as well and that doesn't seem to work. 

Here is a basic reproduction using the snippet from documentation
[autofocus example](https://stackblitz.com/edit/primevue-4-vite-issue-template-xndccw?file=src%2FApp.vue)
[manual focus example](https://stackblitz.com/edit/primevue-4-vite-issue-template-1ecmwa?file=src%2FApp.vue)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-xndccw?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Click button to open popover
Notice Quantity field

### Expected behavior

According to the documentation
> When the popup gets opened, the first focusable element receives the focus and this can be customized by adding autofocus to an element within the popup.

So first and foremost the first focusable element should receive focus by default. If autofocus is added to another element that should apply focus. Then if a ref is applied and a manual focus is desired, that should also work.

**Comment by tugcekucukoglu** [comment]
InputNumber is a composite component and there are some edge cases. Solution could be like this:

```
<InputNumber ref="inputNumber" v-model="qty" :min="0" autofocus placeholder="Quantity" class="pt-4"> </InputNumber>

const toggle = (event) => {
    op.value.toggle(event);
    setTimeout(() => {
        inputNumber.value.$refs.input.$el.focus();
    }, 0);
};
```

**Comment by nsnyder** [comment]
This still seems to be an issue. Even with a generic `<input>` element, which should receive focus. Here's a [repro link](https://stackblitz.com/edit/vitejs-vite-v6txvbls?file=src%2FApp.vue). I also note that the trigger doesn't receive the `aria-controls` or `aria-expanded` attributes that it should.

I'd look at submitting a PR, but I'm struggling to figure out where the change would go. Requesting this be reopened.
