### ISSUE TITLE
Component CSS not imported if component isn't in the page template

### ISSUE THREAD

**Issue by NicolasMelin** [primefaces/primevue#6375]
Hello All,

I have created my own componant based of Primevue components. All works well, except the style !
- My component use the Primevue <Button> component.
- In a page of my Vue projet, I only import my component but the Button CSS is not imported (css var var `--p-button-primary-background` is not defined).
- But if I import the `<Button>` component in the page, all works well with the CSS button !

What I make wrong ?

Thank's by advance for your help.

Best regards

**Comment by DjilanoS** [comment]
Same exact issue here.

**Comment by mertsincan** [comment]
If Primevue components are used on a page or within a component, they are added to their own styles. We think this is more effective than a single style file with a large size. Do you have Button component in your custom component?

**Comment by NicolasMelin** [comment]
I have found the problem, Primevue components was transpiled in my component after the build, to fix it I have added this config in my `vite.config.js` :

```javascript
export default defineConfig({
    plugins: [vue()],
    build: {
        ...
        rollupOptions: {
            external: [
                'vue',
                'primevue/button',
                'primevue/dialog',
                'primevue/inputtext',
                'primevue/password',
                '@vuelidate/validators',
                '@vuelidate/core',
            ],
            output: {
                globals: {
                    'vue': 'Vue',
                    'primevue': 'PrimeVue',
                    'primevue/button': 'PrimeVue.Button',
                    'primevue/dialog': 'PrimeVue.Dialog',
                    'primevue/inputtext': 'PrimeVue.InputText',
                    'primevue/password': 'PrimeVue.Password',
                    '@vuelidate/core': 'VuelidateCore',
                    '@vuelidate/validators': 'VuelidateValidators',
                },
            },
        },
    },
});
```

**Comment by DjilanoS** [comment]
> I have found the problem, Primevue components was transpiled in my component after the build, to fix it I have added this config in my `vite.config.js` :
> 
> ```js
> export default defineConfig({
>     plugins: [vue()],
>     build: {
>         ...
>         rollupOptions: {
>             external: [
>                 'vue',
>                 'primevue/button',
>                 'primevue/dialog',
>                 'primevue/inputtext',
>                 'primevue/password',
>                 '@vuelidate/validators',
>                 '@vuelidate/core',
>             ],
>             output: {
>                 globals: {
>                     'vue': 'Vue',
>                     'primevue': 'PrimeVue',
>                     'primevue/button': 'PrimeVue.Button',
>                     'primevue/dialog': 'PrimeVue.Dialog',
>                     'primevue/inputtext': 'PrimeVue.InputText',
>                     'primevue/password': 'PrimeVue.Password',
>                     '@vuelidate/core': 'VuelidateCore',
>                     '@vuelidate/validators': 'VuelidateValidators',
>                 },
>             },
>         },
>     },
> });
> ```

Thanks for the reply.
This doesn't seem to work for me, I am wrapping PrimeVue's button component.
Here's my component.

**Button.vue**
```js
<script lang="ts">
import {useSegment} from '@/utils/segment';
import {type ButtonProps} from 'primevue/button';

export interface IButtonProps extends /* @vue-ignore */ ButtonProps {
    trackEvent?: string;
    href?: string;
    svgIcon?: string;
    label?: string;
}
</script>

<script setup lang="ts">
import {computed} from 'vue';
import Button from 'primevue/button';

defineOptions({inheritAttrs: true});

const props = withDefaults(defineProps<IButtonProps>(), {
    label: 'Button',
});

const {track} = useSegment();

const emit = defineEmits<{
    (e: 'click'): void;
}>();

const onClick = async () => {
    if (props.disabled) return;
    if (props.trackEvent) trackClickEvent();

    if (props.href) {
        window.open(props.href, '_blank', 'noopener, noreferrer');
    }

    emit('click');
};

const trackClickEvent = () => {
    if (!props.trackEvent) return;
    track('click-' + props.trackEvent);
};
</script>

<template>
    <Button
        v-bind="props"
        :class="{
            'p-button-vertical':
                props.iconPos === 'top' || props.iconPos === 'bottom',
        }"
        @click="onClick"
    >
        <template #icon v-if="svgIcon">
            <component
                :is="svgIcon"
                :class="[
                    {'p-button-icon-right': props.iconPos === 'right'},
                    {'p-button-icon-top': props.iconPos === 'top'},
                    {'p-button-icon-bottom': props.iconPos === 'bottom'},
                ]"
            />
        </template>
    </Button>
</template>

<style lang="scss">
.p-button:not(.p-splitbutton-button) svg {
    width: 16px;
    height: 16px;
}
</style>
```

*Vite.config.ts*
```js
export default defineConfig({
    plugins: [vue()],
    build: {
        ...
        rollupOptions: {
            external: [
                'vue',
                'primevue/button',
            ],
            output: {
                globals: {
                    'vue': 'Vue',
                    'primevue': 'PrimeVue',
                    'primevue/button': 'PrimeVue.Button'
                },
            },
        },
    },
});
```

And here is the component rendered. It does show the primevue classes, but the styling for the Button component is empty.
It's only for the button, all other components are fine.

![button comp](https://github.com/user-attachments/assets/05fc4c74-1530-4fca-a072-6df75dd44570)

**Comment by NicolasMelin** [comment]
Have you installed and imported PrimeVue in your Vue project where you import your external component with the PrimeVue Button ?

**Comment by DjilanoS** [comment]
No, because our design system itself has PrimeVue included. All other components and styling work.
Installing PrimeVue (again) in the project i'm using basically mitigates the fact of creating your own design system based on PrimeVue.

**Comment by NicolasMelin** [comment]
Yes and i'm agree with you.

In your built component result (dist folder).

You have this : `<button class="p-button..."...>` // Result of PrimeVue Button after compilation

or this : `<Button ...>` // PrimeVue Button

**Comment by mertsincan** [comment]
Thanks a lot for your updates, could you please attach a sample project for us to replicate? Also, do you use `@primevue/themes` package?

**Comment by NicolasMelin** [comment]
Yes I use a PrimeVue theme, but not in my component, I use it in my main project :

- Main project package :
   - PrimeVue
   - Primevue theme
   - My component based on primevue components
  
You can find my component based on PrimeVue [here](https://github.com/ESPRI-Digital/vue-authentication-form)

**Comment by mertsincan** [comment]
I don't have access to the link. Could you please attach a sample project for us to replicate?

**Comment by DjilanoS** [comment]
> Yes and i'm agree with you.
> 
> In your built component result (dist folder).
> 
> You have this : `<button class="p-button..."...>` // Result of PrimeVue Button after compilation
> 
> or this : `<Button ...>` // PrimeVue Button (You must have this one)

So when using your `vite.config` it makes the button appear as `import Button from 'primevue/button` in my `main-xxxxxx.ts`.

If you then install Primevue and Primevue theme in the project the `import Button from 'primevue/button` in my `<Button/>` component is still not working.

**Comment by mertsincan** [comment]
Could you please attach a sample project for us to replicate?

**Comment by NicolasMelin** [comment]
> I don't have access to the link. Could you please attach a sample project for us to replicate?

In my project I init PrimeVue globaly like that :

```typescript
import { definePreset } from '@primevue/themes';
import Lara from '@primevue/themes/lara';

export const install: UserModule = ({ app, router, isClient }) => {
   ...
    app.component('Button', Button);
   ...
   app.use(PrimeVue, {
        locale: primeVueTrad.fr,
        ripple: true,
        theme: {
            preset: definePreset(Lara, {}),
            options: {
                prefix: 'p',
                cssLayer: false,
                darkModeSelector: '.dont-use-darkmode',
            },
        },
    });
}
```

**Comment by Winter979** [comment]
@NicolasMelin did you end up solving this problem? Im having a similar one and feel my solution is kinda hacky.

**Comment by NicolasMelin** [comment]
> [@NicolasMelin](https://github.com/NicolasMelin) did you end up solving this problem? Im having a similar one and feel my solution is kinda hacky.

Hi ! Yes I have fix my problem by modifying the [vite config of my project](https://github.com/primefaces/primevue/issues/6375#issuecomment-2363562149).
