### ISSUE TITLE
DataTable global filter freeze InputText on large dataset

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#638]
Hi folks!

I have a dataset of about 2300 registers, and I put a global filter to filter my dataset, but when I type into InputText, it freezes for seconds (while DataTable is doing filter task). It's acceptable that the task of filtering takes some seconds, but it should not block  InputTask.

I think that it happens because filter task runs on same thread of keyboard input on InputText, maybe we have to decouple it.

**Comment by makurtu** [comment]
I see that PrimeReact has same error: https://github.com/primefaces/primereact/issues/1666

So, there is a codesandbox to reproduce this error.

**Comment by cagataycivici** [comment]
Debounce could be one solution;

https://vuejs-tips.github.io/v-debounce/

We've plans to provide our own debounce as well in the future.
