### ISSUE TITLE
InputText: support for prefix and suffix

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#6383]
### Describe the bug

InputText currently does not support prefix and suffix, while InputNumber for example does. Is there a chance we can add this to InputText as well?

### Reproducer

PrimeVue docs

### PrimeVue version

4.0.6

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by eneeio-nm** [comment]
@Tamas-hi - maybe you could use [InputGroup](https://primevue.org/inputgroup/)?

**Comment by Tamas-hi** [comment]
Thanks, InputGroupAddon indeed works for this purpose. I am closing this one.
