### ISSUE TITLE
Datatable:migration from 3 to 4 removed button filter highlighting feature

### ISSUE THREAD

**Issue by koen-i** [primefaces/primevue#6385]
### Describe the bug

In primevue 3 the filterbutton on top of a datatable was highlighted when a filter was active. This feature is not available anymore in primevue 4.
The code to apply other CSS when the instace has a filter active was removed. I checked the code. This part of the code was not correctly migrated to version 4. It is missing.
You can reproduce it on the primevue website: https://primevue.org/datatable/#advanced_filter
vs https://v3.primevue.org/datatable/#advanced_filter

This is confusing for the enduser as he/she can not see that a filter is active.

### Reproducer

https://template

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

**Comment by koen-i** [comment]
As far as I know, changes need to be made in primevue/datatable/style/index.mjs

Replacing this: 
 pcColumnFilterButton: 'p-datatable-column-filter-button',

By something like this:
  pcColumnFilterButton:  function filterMenuButton(_ref6) {
        var instance = _ref6.instance;
        return ['p-datatable-colum-filter-button', {
          'p-datatable-column-filter-button-active': instance.hasFilter()
        }];
  },

**Comment by colinatwork** [comment]
Bumping as we are seeing the same issue in v4.0.7

**Comment by tugcekucukoglu** [comment]
It is a design decision. You could implement v3 styles to v4 using design tokens.
