### ISSUE TITLE
I can't change darkModeSelector after app.use()

### ISSUE THREAD

**Issue by Sojaner** [primefaces/primevue#6388]
### Describe the bug

I initiate the vue application using:
```
app.use(PrimeVue, {theme: {options: {darkModeSelector: 'system'}}})
```
But later in the app need to switch to the class based dark mode, but I can't figure out how this could be done!

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-r4xg26

### PrimeVue version

4.0.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

TypeScript

**Comment by mertsincan** [comment]
Hi,

You need to set the dark class to HTML element. Please see; https://primevue.org/theming/styled/#darkmode

Best Regards,

**Comment by Sojaner** [comment]
> Hi,
> 
> 
> 
> You need to set the dark class to HTML element. Please see; https://primevue.org/theming/styled/#darkmode
> 
> 
> 
> Best Regards,

This doesn't solve my problem!

I want to start by the system dark mode setting `darkModeSelector: 'system'` until the user logs in and their settings are loaded.
If their settings has it that they prefer either always light or always dark, then I want to set `darkModeSelector: '.app-dark'` and manipulate the HTML element class accordingly, without needing to restart the application to use the `app.use()` with the new settings. But none of the functions or methods provided manipulate the settings in the way I need it!

**Comment by whilemouse** [comment]
app.vue(or nuxt.config.ts)
````
app.use(PrimeVue, {
  // Default theme configuration
  theme: {
    preset: Aura,
    options: {
      darkModeSelector: true,
    },
  },
})
````

nuxt.config.ts(or app.vue)
````
primevue: {
    options: {
      theme: {
        darkModeSelector: true,
      },
    },
  },
````


index.vue
````
<script lang="ts" setup>
const primeVue = usePrimeVue()

function onDarkMode() {
  primeVue.config.theme.options.darkModeSelector = true
}

function offDarkMode() {
  primeVue.config.theme.options.darkModeSelector = false
}
</script>

<template>
  <div>
    {{ primeVue.config.theme.options.darkModeSelector }}
    <Button label="onDarkMode" @click="onDarkMode" />
    <Button label="offDarkMode" @click="offDarkMode" />
  </div>
</template>
````

**Comment by nickofthyme** [comment]
The proposed solution using `usePrimeVue` does not update the component to adapt the new `darkModeSelector`.

The use case here is to allow users to set the theme to `dark`, `light` or system. The only way to do this now is to watch changes to `prefers-color-scheme` and set `darkModeSelector` to match. It would be nice to have a better solution than this.

```ts
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    // apply :root classes
});
```

**Comment by nickofthyme** [comment]
After looking into the code I found this...

https://github.com/primefaces/primevue/blob/8cf3f0c26b2564f064a2572e3bd2ca4beac650c4/packages/core/src/config/PrimeVue.js#L212-L217

Here you are only updating the theme if the entire theme reference changes. So with this we can initially set the value to the default value.

```ts
// main.ts
app.use(PrimeVue, {
  theme: {
    preset: Aura,
    options: {
      darkModeSelector: 'system', // default mode
    },
  },
});
```

Then we can trigger an update to `darkModeSelector` using a helper function like this...

```ts
import { usePrimeVue } from 'primevue';

function changePrimeTheme(darkModeSelector: string) {
  primeVue.config.theme = {
    ...primeVue.config.theme,
    options: {
      ...primeVue.config.theme.options,
      darkModeSelector,
    },
  };
}

if (themeMode === 'system') {
  changePrimeTheme('system');
} else {
  changePrimeTheme('.app-dark');
}
```
