### ISSUE TITLE
DatePicker : cannot manipulate overlay ?

### ISSUE THREAD

**Issue by Kamsou** [primefaces/primevue#6393]
### Describe the bug

Hello ! 

I've just switched from Calendar to DatePicker, and I can't manipulate the overlay to tell it to close or open as I could with the calendar, is this normal?

I'd like to close my overlay by clicking on the buttons in my footer and not by clicking on the date. 

Is there a way? 

![Capture d’écran 2024-09-12 à 16 46 33](https://github.com/user-attachments/assets/7a250364-e53a-4b64-909d-d2bc378a0da2)

Thanks

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-bwfbbx?file=src%2FApp.vue

### PrimeVue version

^4.0.0-rc.3

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by avramz** [comment]
Hi! The DatePicker component itself does not support this out of the box, but you can easily create a custom component by utilizing InputText (meybe even InputMask), Popover, and DatePicker!

Something like this: https://stackblitz.com/edit/primevue-4-vite-issue-template-eiozch?file=src%2FApp.vue

**Comment by Kamsou** [comment]
Thank you very much @avramz! it will manage the use we wanted. I close this.

**Comment by Kamsou** [comment]
Thank you very much @avramz! it will manage the use we wanted. I close this.
