### ISSUE TITLE
DataTable: Striped rows with even numbered indexes don't highlight on hover

### ISSUE THREAD

**Issue by colinatwork** [primefaces/primevue#6397]
### Describe the bug

When there is a DataTable configured with striped rows and a selection mode and a user hovers over an even indexed row, it does not highlight. If they hover over an odd number one, it does highlight. Two screenshots attached, the first shows hovering over `Row 0` with a highlight (expected), the second shows hovering over `Row 1` with no highlight (unexpected).
<img width="448" alt="Screenshot 2024-09-12 at 1 31 52 PM" src="https://github.com/user-attachments/assets/82dbcf31-6c37-4605-8273-eacba840231b">
<img width="441" alt="Screenshot 2024-09-12 at 1 31 56 PM" src="https://github.com/user-attachments/assets/5e3c5404-1e86-4ed7-bef9-da0c6f43f5e0">

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-kodwg1?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Configure a DataTable with striped rows and a selection mode
2. Hover over an even numbered row to see the expected behavior of the row highlight to indicate the hover
3. Hover over an odd numbered row and see there is _no_ row highlight to indicate the hover

### Expected behavior

When there is a selection mode and a user hovers over a row, the row should always highlight, regardless of stripping.

**Comment by tugcekucukoglu** [comment]
Fixed the latest version. Please try to use v4.2.3.
