### ISSUE TITLE
[MultiSelect]: cannot select the pcFilterContainer

### ISSUE THREAD

**Issue by FabienVINCENT** [primefaces/primevue#6405]
### Describe the bug

The pcFilterContainer PT is not selectable.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-szpwo2?file=src/main.js,src/App.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Chilc on the select, check the element, class not applied

**Comment by tugcekucukoglu** [comment]
Correct implementation: 

```
pcfiltercontainer: {
   root: { class: '' }
}
```
