### ISSUE TITLE
Select: autoFilterFocus stuck when switching between Selects

### ISSUE THREAD

**Issue by Tobberoth** [primefaces/primevue#6420]
### Describe the bug

When switching between Select components with filter and autoFilterFocus set, the focus does not switch, unless user clicks outside of the selects to blur the first one.

I tried to recreate in the nuxt issue template, but it does not recognize the Select component.

A new nuxt project with PrimeVue and @primevue/nuxt-module with the following app.vue reproduces the error:

```
<script setup>
  const options1 = ref(["Foo", "Bar", "FooBar"])
</script>

<template>
  <Select :options="options1" filter autoFilterFocus />
  <Select :options="options1" filter autoFilterFocus />
</template>
```

### Reproducer

Unable

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Click Select 1, type something to assert that the filter is focused.
2. Click Select 2, without clicking elsewhere first. Assert that Select 1 closes, and that Select 2 opens.
3. Type text, notice that Select 1 opens and text is entered in the filter in Select 1, not in Select 2.

### Expected behavior

As with MultiSelect, I expect the filter of Select 2 to be autofocused when it is opened.

**Comment by avramz** [comment]
Can reproduce. Looks like setTimeout used in `hide` method is causing this, we need to execute focus after it.
