### ISSUE TITLE
FileUpload: `progress` on preview don't show correct value

### ISSUE THREAD

**Issue by hrynevychroman** [primefaces/primevue#6421]
### Describe the bug

https://github.com/user-attachments/assets/e06f08bd-9cb5-4b72-bec3-5f3b550434c0

I will open a fix PR

### Reproducer

https://stackblitz.com/edit/uedtey?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All Browsers

**Comment by tugcekucukoglu** [comment]
It is not a core bug. You can write your own examples.

**Comment by hrynevychroman** [comment]
@tugcekucukoglu This is a bug in docs. See the linked PR where I add updates. I just created this issues as described in https://github.com/primefaces/primevue/blob/master/.github/PULL_REQUEST_TEMPLATE.md
