### ISSUE TITLE
Form components: Hovering over component when `invalid` is set, the border is no longer red

### ISSUE THREAD

**Issue by felldo** [primefaces/primevue#6426]
### Describe the bug

When hovering over a form component with the invalid prop enabled, the red border vanishes
![chrome_JlbVzRoIrF](https://github.com/user-attachments/assets/8735de0d-73a3-4ab1-95d8-875263c71e80)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-7karte?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
It is a design decision. This behaviour can be changed using new design tokens.

**Comment by jacobg** [comment]
The invalid input can be kept red in hover state with this style:
```css
.p-inputtext.p-invalid:hover {
  border-color: var(--p-inputtext-invalid-border-color);
}
```

But how would you do that with a design token? There doesn't seem to be anything documented here for invalid hover state:
https://primevue.org/inputnumber/#theming.tokens
