### ISSUE TITLE
DataTable: Not able to use MultiSelect Column and option at the same time.

### ISSUE THREAD

**Issue by Aspyryan** [primefaces/primevue#6429]
### Describe the bug

When trying to use a multiselect column and a selectionMode: Multiple on the same datatable, selecting it will not work. When hitting the checkbox, 2 events are fired. A select event from the checkbox, then a propagation to the row click which fires another select event, which unselects the same row. Thus this is making it unable to select the row. The checkbox should have .stopPropagation() event on it.

### Reproducer

https://stackblitz.com/edit/rmytwj?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Stackblitz, Edge

### Steps to reproduce the behavior

1. Click on the row only multiple times and see it updating correctly
2. Click the checkbox and watch it completely break

### Expected behavior

Should stop propagating after the checkbox click so the row-click is not fired after.

**Comment by Aspyryan** [comment]
I think this should fix it (untested): https://github.com/primefaces/primevue/compare/master...Aspyryan:primevue:patch-1

**Comment by tugcekucukoglu** [comment]
The multiple selection mode of Column and DataTable are separated modes. We do not recommend using these two at the same time.

**Comment by hurahurat** [comment]
I got the same problem and it works fine in primevue version 3 but broken in version 4 @tugcekucukoglu
