### ISSUE TITLE
Component Name: Password

### ISSUE THREAD

**Issue by sadobass** [primefaces/primevue#6434]
### Describe the bug

Password width 100% does not apply.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-gptkbs?file=src%2FApp.vue,package.json,src%2Fmain.js

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

ms Edge, safari

### Steps to reproduce the behavior

`
  <InputText style="width: 100%" />
  <Password style="width: 100%" />
`

![스크린샷 2024-09-19 오전 11 38 28](https://github.com/user-attachments/assets/0a7c8eb7-48b9-4d5d-abb9-d346ccea0834)

### Expected behavior

InputText and Password must have the same width.

**Comment by tugcekucukoglu** [comment]
We can suggest using new `fluid` property for width: 100% style.
