### ISSUE TITLE
Galleria: Global ripple effect breaks Galleria

### ISSUE THREAD

**Issue by ap-jirikralovec** [primefaces/primevue#6438]
### Describe the bug

When using global ripple effect, the Galleria component's navigation/close buttons are now styled as `position: relative`. This breaks the entire layout of Galleria:

![image](https://github.com/user-attachments/assets/43591d1b-a410-4853-81c8-7d5e27f6eff6)

### Reproducer

https://stackblitz.com/edit/hheeak?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Setup a Vue project with PrimeVue
2. Globally enable `ripple` as part of the theme
3. Use `Galleria` component with full-screen
4. The close button and navigation items are broken

### Expected behavior

It is expected that the ripple effect will not break the component.

**Comment by Kami-prog** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler
