### ISSUE TITLE
Missing .d.ts file for usetoast

### ISSUE THREAD

**Issue by mcshaz** [primefaces/primevue#645]
PrimeVue 3.0.1 is missing the typescript declaration file and thus making 
`import { useToast } from 'primevue/usetoast';` create errors when imported into typescript

I have temporised by adding my own .d.ts file
```typescript
export declare function useToast(): { add(args:{ severity?: string, summary?: string, detail?: string, life?: number, closable?: boolean, group?: string }): void }
```

**Comment by cagataycivici** [comment]
Duplicate of #630
