### ISSUE TITLE
Select: Should dispatch native bubbling "change" event

### ISSUE THREAD

**Issue by coreyworrell** [primefaces/primevue#6450]
### Describe the bug

Selecting a value does not trigger native `change` event. This can be very convenient when working with validation for example.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-32cbg4?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Thanks for your attention. We will create our own form library next quarter. It will be fixed then.
