### ISSUE TITLE
Panel: Toggle button not a text button if toggleButtonProps is used

### ISSUE THREAD

**Issue by tokainz** [primefaces/primevue#6457]
### Describe the bug

Setting the `toggleButtonProps` causes the toggle button of the Panel component to no longer be a text button.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-xixldr?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add a Panel component to your app
2. Set the `toggleButtonProps` to anything
3. The toggle button of the panel is now just an icon-only button and no longer a text button

### Expected behavior

Just setting the `toggleButtonProps` should not change the appearance of the button.

**Comment by tugcekucukoglu** [comment]
`toggleButtonProps` does not merge Button properties. If you want to add aria-* attribute you could use pt property.

**Comment by tokainz** [comment]
Yes i know, it's just an example. But still setting anything in the toggleButtonProps should not remove the text-button styles. Even setting `:toggleButtonProps='{}'` results in the issue.
