### ISSUE TITLE
Showcase: Dark mode state is not persistent

### ISSUE THREAD

**Issue by mergehez** [primefaces/primevue#6461]
### Describe the bug

When you set the theme to dark mode and refresh the page or open a page in a new tab, the theme switches back to light mode.

The site doesn't detect my theme preference as well. It forces to light mode!

### Reproducer

no need

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 128.0.6613.138

### Steps to reproduce the behavior

see the description

**Comment by tugcekucukoglu** [comment]
It is not a core bug. We temporarily closed.

**Comment by chocolateimage** [comment]
I made a Tampermonkey script which automatically switches to dark mode on the docs.

Install Tampermonkey, click on "Create new Userscript", replace the existing code with the one below and press CTRL+S.

```js
// ==UserScript==
// @name         Auto Dark Mode for PrimeVue Docs
// @version      2024-12-16
// @description  Automatic dark mode for the PrimeVue docs because they don't want that
// @author       chocolateimage
// @match        https://primevue.org/**
// @icon         https://www.google.com/s2/favicons?sz=64&domain=primevue.org
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function getToggleThemeButton() {
        return document.querySelector("html body div#__nuxt div.layout-wrapper div.layout-topbar div.layout-topbar-inner ul.topbar-items li button.topbar-item");
    }

    var interval = setInterval(() => {
        const toggleThemeButton = getToggleThemeButton();
        if (toggleThemeButton == null) return;

        clearInterval(interval);
        if (!document.documentElement.classList.contains("p-dark")) {
            toggleThemeButton.click();
        }
    },50);
})();
```

**Comment by mergehez** [comment]
The primevue team just doesn't give a sh*t about what their users says. so we have to find workarounds like these..

the following line is actually enough. I am using 'User JavaScript and CSS' extension.

```js
document.documentElement.classList.add("p-dark")
```
