### ISSUE TITLE
Menubar: Issue with PrimeVue Ultima version 6 template

### ISSUE THREAD

**Issue by nexgen-ui** [primefaces/primevue#6466]
### Describe the bug

The top menu bar utilities and ui-kit menus do not navigate when clicked on in the Ultima template.

### Reproducer

Not necessary

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 128

### Steps to reproduce the behavior

1. Select the UI Kit or Utilites menu from the top bar in the Ultima Template.
2. Select a menu item from the sub-menu.
3. Nothing happens

### Expected behavior

The sub menu items should open the menu item

**Comment by tugcekucukoglu** [comment]
Please use discussion for template support.
