### ISSUE TITLE
OverlayBadge: Styling associated with pcbadge not being applied

### ISSUE THREAD

**Issue by alfisdad** [primefaces/primevue#6473]
### Describe the bug

I'm using Tailwind to apply styles in unstyled mode and am trying to upgrade my site to using the latest version of Primevue. I'm hitting this problem attempting to replace the v-badge directive with the new OverlayBadge component. In my primevue.ts file, where I set up the PrimeVueConfiguration, I have inserted styles for OverlayBadge as follows:
```
:
    overlaybadge: {
        root: {
            class: 'relative'
        },
        pcbadge: {
            class: 'absolute top-0 right-0 translate-x-1/2 -translate-y-1/2 origin-bottom-right'
        }
    },
:
```
The root classes are applied but the pcbadge classes are not. Instead the classes set up for badge -> root are applied.

### Reproducer

https://stackblitz.com/edit/overlaybadgeissue?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

See reproducer

### Expected behavior

pcBadge passthrough option classes should be applied.

**Comment by tugcekucukoglu** [comment]
Correct implementation:

```
 overlaybadge: {
        root: {
            class: 'relative'
        },
        pcbadge: {
              root:  {
                   class: 'absolute top-0 right-0 translate-x-1/2 -translate-y-1/2 origin-bottom-right'
              }
        }
    },

```

**Comment by alfisdad** [comment]
Thanks!
