### ISSUE TITLE
DataTable: Column resizing does not work with Vue 3.5

### ISSUE THREAD

**Issue by eliaspanagiotidis** [primefaces/primevue#6476]
### Describe the bug

After upgrading to Vue 3.5, column resizing in case of columnResizeMode="expand" and resizableColumns stopped working as expected. 

### Reproducer

https://stackblitz.com/edit/b7jonc?file=package.json

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open the stackblitz (copied from documentation)
2. Try to resize columns

### Expected behavior

Consistent behavior with Vue 3.4 was expected.

**Comment by Leshkens** [comment]
@eliaspanagiotidis 
The same problem, but with columnResizeMode="fit". If you change this property to "fit" in your example, the resizing the columns will not work at all.

**Comment by Leshkens** [comment]
**3.5.5** this is the latest vue version on which "fit" works and "expand" works correctly.

**Comment by tugcekucukoglu** [comment]
Please track: https://github.com/primefaces/primevue/issues/6014
