### ISSUE TITLE
FileUpload: Misleading Documentation: fileLimit

### ISSUE THREAD

**Issue by easy-easy** [primefaces/primevue#6478]
### Describe the bug

In the Documentation of FileUpload **fileLimit** is described with: _Maximum number of files that can be uploaded._ which is technically correct but misleading.

If you set up a fileLimit of eg 10, you can only upload 10 files within the complete lifecycle, not just a limit per request. So you can not upload 5 files two times, the second try, the limit hits.

Workaround in the upload event with fileupload is a ref of FileUpload:
```
  fileupload.value.uploadedFileCount=0
```

Regards.

### Reproducer

https://no-template.needed/

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

Should better described in the document, or if I manually call clear() on the object, uploadedFileCount should also be resetted.

**Comment by tugcekucukoglu** [comment]
We will check the documentation.

Thank you!
