### ISSUE TITLE
Toggleswitch: Disabled Checked Looks Same As Disabled Unchecked

### ISSUE THREAD

**Issue by colinatwork** [primefaces/primevue#6479]
### Describe the bug

In PrimeVue v3, and as recently as v4.0.0-rc.3, if a Toggleswitch was disabled but checked, it would have a greyed out primary color, helping indicate that the switch was in the checked state. And if the Toggleswitch was disabled but unchecked, it would simply be greyed out. 

It seems that as of PrimeVue v4.0.0 did away with this, and now regardless of if the switch is checked or not, it will use the same background disabled color, which makes it harder to tell if it is checked. Screenshot attached.
<img width="126" alt="Screenshot 2024-09-25 at 1 00 12 PM" src="https://github.com/user-attachments/assets/5de8ea1a-6963-4ff5-9f1e-301151db06f0">

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-rtgywt?file=src%2Fmain.js

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

A disabled checked switch should include the primary color greyed out while a disabled unchecked switch should not include the primary color. Ideally these two states would use two different design tokens.

**Comment by cagataycivici** [comment]
This is by design, but in the future we sure can add more tokens for checked-disabled state as well. I'll use this specific case on how to extend default tokens and default theming documentation so that you don't depend on us to add new tokens/styles in core for customization.

**Comment by cagataycivici** [comment]
The theming system can be extended by adding custom design tokens and additional styles. This feature provides a high degree of customization, allowing you to adjust styles according to your needs, as you are not limited to the default tokens.

Use the extend property to add custom tokens along with the css property to utilize them. As an example, let's customize the disabled state of the ToggleSwitch component to add an opacity token, and use the primary color for the handle. By default, there is no opacity option available, and the disabled switch uses a gray handle by design.

```js
const MyPreset = definePreset(Aura, {
    components: {
        toggleswitch: {
            extend: {
                root: {
                    disabledOpacity: '0.7' 
                },
                handle: {
                    myCheckedDisabledBackground: '{primary.color}'
                } 
            }
        },
        css: ({ dt }) => `
.p-toggleswitch.p-disabled .p-toggleswitch-slider {
    opacity: ${dt('toggleswitch.my.disabled.opacity')};
}

.p-toggleswitch.p-disabled .p-toggleswitch-handle {
    background: ${dt('toggleswitch.my.checked.disabled.background')};
}
`
    }
});
```

**Comment by colinatwork** [comment]
Hello! I tried implementing this, but I get weird visuals when trying to use the extend key. Updated Stackblitz here: https://stackblitz.com/edit/primevue-4-vite-issue-template-rtgywt?file=src%2Fmain.js
