### ISSUE TITLE
[Query](primevue2.x): What does the TabPanelHeaderSlot do ?

### ISSUE THREAD

**Issue by cRAN-cg** [primefaces/primevue#648]
First of all this is not a bug/any feature request. Issue is not with the code but with my brain trying to understand a code snippet.

**https://github.com/primefaces/primevue/blob/2.x/src/components/tabview/TabView.vue**

I was going through the code base and found the `TabPanelHeaderSlot` functional component. 
I have not been able to understand it's render function. Could you please help me understand this.

Thanks in advance and much love to the team for the library ❤️

**Comment by cagataycivici** [comment]
It renders the custom header slot of TabPanel, in upcoming version we'll try using <component /> element as we did in PrimeVue 3 which eliminates the necessity for functional components like TabPanelHeaderSlot.

**Comment by cRAN-cg** [comment]
Thanks for the reply @cagataycivici :)
