### ISSUE TITLE
Password: Using slots `maskicon` and `unmaskicon` forces the icon outside the input

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue#6487]
### Describe the bug

When using custom icon slots for the `Password` component, the icons are moved outside the input.

Here is what it should look like:
![Screenshot 2024-09-27 at 3 27 27 PM](https://github.com/user-attachments/assets/675b917a-eb8c-4d0c-ab9c-3065bf104382)

Here is what it looks like using custom icon slots:
![Screenshot 2024-09-27 at 3 29 17 PM](https://github.com/user-attachments/assets/3e209c6c-ded9-4c5b-836c-65df6d1b1592)

```Vue
    <Password v-model="value" toggleMask>
      <template #maskicon="slotProps">
        <EyeSlashIcon class="size-5" @click="slotProps.toggleCallback" />
      </template>
      <template #unmaskicon="slotProps">
        <EyeIcon class="size-5" @click="slotProps.toggleCallback" />
      </template>
    </Password>
```

### Reproducer

https://stackblitz.com/edit/eubsf1-46j3ec?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
`class` option is available for both icon slots. `slotProps.class` can be added dynamically.

**Comment by BenJackGill** [comment]
Sorry, but I'm not sure how that helps. Are we supposed to use a special class to force the icon back inside the input? Can you tell me what the class is or show me on the live reproduction?

**Comment by BenJackGill** [comment]
@tugcekucukoglu Can this be reopened? I don't know how your answer solves the issue.

The problem is that using slots to change the icons causes it to display incorrectly. I'm not sure how the class you mentioned solves the issue.

Maybe you can illustrate it using the reproduction I provided? https://stackblitz.com/edit/eubsf1-46j3ec?file=src%2FApp.vue
