### ISSUE TITLE
Nuxt with PrimeVue - Toast show wrong position

### ISSUE THREAD

**Issue by solitarymx** [primefaces/primevue#649]
I added primevue to the project I created with Nuxtjs, and when I experiment in a blank page, "Toast" turns out to be wrong.
But when I run "Dialog" on the same page, it appears in the middle of the screen.
Toast position = "bottom-center" or "top-right" shows up in the same place without realizing it.

Index Page / "Dialog" looks pretty good.
![index](https://user-images.githubusercontent.com/3239339/99693730-bda67680-2a9c-11eb-9c4f-a9eec6260e3e.jpg) / ![dialog](https://user-images.githubusercontent.com/3239339/99693746-c1d29400-2a9c-11eb-8620-c0c5b34245de.jpg)

Toast ( position: top-right ) - Wrong  /  Toast ( position: bottom-center) - Wrong
![toast-top-right](https://user-images.githubusercontent.com/3239339/99693988-fcd4c780-2a9c-11eb-9660-13b11cbfef50.jpg) / ![toast-bottom-center](https://user-images.githubusercontent.com/3239339/99693655-acf60080-2a9c-11eb-85cc-23f531945abb.jpg)

Dialog Code Page:
![dialog-code](https://user-images.githubusercontent.com/3239339/99694696-bfbd0500-2a9d-11eb-9929-1a2679b029af.JPG)

Toast Code Page:
![toast-code](https://user-images.githubusercontent.com/3239339/99694737-c8add680-2a9d-11eb-9fd0-16566da99627.JPG)

I'm getting this view on the "Chrome device emulation page" not on the phone.

**Comment by cagataycivici** [comment]
Please create a new issue and provide a case that we can replicate. I'm afraid we cannot do much with the given information. A code sandbox will greatly help.
