### ISSUE TITLE
Component Name: DataTable > Reorder

### ISSUE THREAD

**Issue by irmzn** [primefaces/primevue#6491]
### DataTable Column Reorder Drag Problem

DataTable Column Reorder Drag Problem

Step 1
![image](https://github.com/user-attachments/assets/97b92d5f-d23b-44a1-bbb0-5b822e1b1cb0)

Step 2
![image](https://github.com/user-attachments/assets/54a55eaa-70fa-4606-baf3-153a296a2c38)

Step 3
![image](https://github.com/user-attachments/assets/af48ab9d-6a29-4d7e-84c3-14ee380f10a2)

Source Code:
![image](https://github.com/user-attachments/assets/601ba8ba-5488-4990-bb1a-946887211591)

Kolonu Taşırken Checkbox ve rowOrder Sağ veya Sol Tarafa Çoklanıyor.

### Reproducer

https://stackblitz.com/edit/p2ednl?file=src/App.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome All

### Steps to reproduce the behavior

Table Column Drag Movement Problem

### Expected behavior

Column Copy Right Problem

**Comment by irmzn** [comment]
@tugcekucukoglu help me please

**Comment by tugcekucukoglu** [comment]
You could add `field` prop to all Column components.
