### ISSUE TITLE
Dynamic Component: Not resolving in Nuxt app

### ISSUE THREAD

**Issue by sun-pandey** [primefaces/primevue#6497]
### Describe the bug

In Nuxt or app, any primevue component is not resolved when used as dynamic component.
This used to work in primevue 3.x

### Reproducer

https://stackblitz.com/edit/nuxt-starter-hwj6pa?file=nuxt.config.js,app.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

To reproduce, 

1. created a brand new Nuxt app, 
2. install and setup primevue, @primevue/themes in nuxt.config.js as per primevue documenation. 
3. replace App.vue with following (somehow full code is not showing up. please see linked stackblitz link)
`
<script setup>
const dyn = ref('InputText')
</script>

<template>
  <div>
    <div>
      <label>Component showing:</label>
      <InputText/>
    </div>
    <div>
      <label>Dynamic Component not showing:</label>
      <component :is="dyn"/> 
    </div>
  </div>
</template>

`

### Expected behavior

Expected the InputText component to be rendered.

**Comment by tugcekucukoglu** [comment]
Stackblitz demo seems to be working correctly.  What should we do to see the problem?

**Comment by sun-pandey** [comment]
> Stackblitz demo seems to be working correctly. What should we do to see the problem?

I see it's working in Stackblitz after I imported ref from 'vue'. As I mentioned, I am getting this issue in Nuxt 3.13.x. Now I have created a Nuxt project and here is the link to Stackblitz
https://stackblitz.com/edit/nuxt-starter-hwj6pa?file=nuxt.config.js,app.vue
Thank you.

**Comment by tugcekucukoglu** [comment]
It seems it is a Nuxt-related problem. Please check: https://github.com/nuxt/nuxt/issues/13659

**Comment by sun-pandey** [comment]
> It seems it is a Nuxt-related problem. Please check: [nuxt/nuxt#13659](https://github.com/nuxt/nuxt/issues/13659)

Thanks for the link. as per this comment, the only reason NuxtLink isn't registered globally is so that Nuxt can manage in tree shaking.
https://github.com/nuxt/nuxt/issues/13659#issuecomment-1717191411

Here the issue is with PrimeVue components. 

Thank you so much for looking into. Appreciate it.
