### ISSUE TITLE
DataTable: headerCell pt in Column not work

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#6498]
### Describe the bug

I want to add a data-testId property to th but it doesn't work.

### Reproducer

https://stackblitz.com/edit/fhrzbx?file=src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
It's about general Vue syntax rules. headerCell pt implementation should be like this:
```
:pt="{
                headerCell: ({}) => ({
                    'data-testId' : 'test'
                })
            }"```


We think it would be useful to ask for support from the community first in such demo problems. For example Discord and Github discussions. It does not always mean that there will be a core problem.
