### ISSUE TITLE
DataTable - ContextMenu warning

### ISSUE THREAD

**Issue by mduey** [primefaces/primevue#650]
FYI...I get a warning when right-clicking a row in a datatable with a context menu.  The warning happens when this runs:

onRowContextMenu(event) {
    this.$refs.cm.show(event.originalEvent);
 }
 

The warning is:
[Vue warn]: Failed to resolve component: router-link 
  at <SubMenu model= (3) [{…}, {…}, {…}] root=true onLeafClick=fn<bound onLeafClick> > 
  at <BaseTransition onEnter=fn onLeave=fn<onLeave> appear=false  ... > 
  at <Transition name="p-contextmenu" onEnter=fn<bound onEnter> onLeave=fn<bound onLeave> > 
  at <ContextMenu model= (3) [{…}, {…}, {…}] ref="cm" > 
  at <DataTables orgs= (1334) [{…}, {…}, counties= [] > 
  at <App>
  ...runtime-core.esm-bundler.js?5c40:38

Vue: 3.0.0
Primevue: 3.0.1

**Comment by cagataycivici** [comment]
You need to use vue-router for context menu.
