### ISSUE TITLE
Button (and others): Scoped tokens stopped working between Vue 3.5.5 and Vue 3.5.6

### ISSUE THREAD

**Issue by deisner** [primefaces/primevue#6502]
### Describe the bug

It appears that scoped tokens work as expected with Vue 3.5.5, but not with Vue 3.5.6 and later. I originally had the problem when trying to figure out why I couldn't style a Menu, but I've reproduced it here with just a Button, and a `:dt` prop that should change the button's background color to blue.

This may be related to (or identical to) https://github.com/primefaces/primevue/issues/6129

### Reproducer

https://stackblitz.com/github/deisner/vuejs-dt-demo/tree/vuejs-dt-demo-vue3_5_6?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

ALL

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/github/deisner/vuejs-dt-demo/tree/vuejs-dt-demo-vue3_5_6?file=src%2FApp.vue
2. The button background is green, but it should be blue, due to the scoped token `:dt` prop. This is with vue@3.5.6
3. Go to https://stackblitz.com/github/deisner/vuejs-dt-demo/tree/vuejs-dt-demo-vue3_5_5?file=src%2FApp.vue
4. The button background is blue, as expected. The only difference is we're using vue@3.5.5 here.

### Expected behavior

The button background should be blue. It is when using vue@3.5.5, but not with vue@3.5.6. Nothing else differs between the two stackblitz workspaces.

<img width="826" alt="image" src="https://github.com/user-attachments/assets/fa3c1b6d-4292-4551-97ec-12f7ddd1d963">

<img width="881" alt="image" src="https://github.com/user-attachments/assets/a54cb56e-f3b9-4d0b-a8f8-2e29def58d7d">

**Comment by deisner** [comment]
I think https://github.com/primefaces/primevue/issues/6129 is at least not identical to this issue: Here is a stackblitz with vue@3.5.5 where the `Button` and `Menubar` scoped tokens work, but not so for `Menu`.

https://stackblitz.com/edit/hkya3e?file=src%2FApp.vue

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/e6a4a999-18f0-4aca-8a61-117ffc95f782">

**Comment by Scott-McMullan-ABB** [comment]
Following after posting a similar issue https://github.com/orgs/primefaces/discussions/2773

**Comment by j0rgedev** [comment]
Hey @Scott-McMullan-ABB. I've just updated my answer

**Comment by tugcekucukoglu** [comment]
Thanks for the stackblitz examples. We are investigating the issue, which will be fixed for the next version 4.1.0.
