### ISSUE TITLE
DataTable: Cannot resize columns

### ISSUE THREAD

**Issue by Azoorb** [primefaces/primevue#6512]
### Describe the bug

The "fit" mode for column resizing in the datatable is not working. Resizing works in the documentation, but it doesn't work in the Stackblitz example provided.

### Reproducer

https://stackblitz.com/edit/xfp6yw?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome v129.0.6668.71

**Comment by anchan42** [comment]
I have the same problem.

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/6436
