### ISSUE TITLE
DynamicDialog: Breakpoints have no effect or do not function properly.

### ISSUE THREAD

**Issue by MEngMAHCelebi** [primefaces/primevue#6514]
### Describe the bug

The width is taken from the 'style', but not from the breakpoint. Open your own example, switch to the developer tools in the browser, select the responsive mobile view, refresh the page, and it doesn’t change—the width remains at 50vw."

### Reproducer

https://stackblitz.com/edit/4da5eh?embed=1&file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://primevue.org/dynamicdialog/#example
2. open in stackblitz, an try breakpoints function

**Comment by MEngMAHCelebi** [comment]
i had the same problem with     "core-js": "^3.38.1", and vue-cli and Primevue 3.53.0, but with     "core-js": "^3.37.1", and Primevue 3.53.0 the breakpoints in DD works. also no emit of maximized and unmaximized. i can not recognize if the dialog is maximized or not.

**Comment by MEngMAHCelebi** [comment]
### Reproducer

https://stackblitz.com/edit/4da5eh?embed=1&file=src%2FApp.vue

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/0c3ad067-7806-4a73-8330-00df1f4485ad">
<img width="418" alt="image" src="https://github.com/user-attachments/assets/6e5400d1-4e8c-4228-bd95-4acbbaad70a8">


the width must be 100vw but its stil 50vw.

Its is from your own example.

**Comment by galaxyblur** [comment]
Experiencing the same here

**Comment by galaxyblur** [comment]
a workaround:
```
  function showMyComp() {
    dialog.open(MyComp, {
      props: {
        modal: true,
        pt: {
          root: {
            class: 'w-screen sm:w-11/12 md:w-9/12 lg:w-8/12',
          },
        },
      },
    });
  }

```

**Comment by tugcekucukoglu** [comment]
It was fixed for the next version. Thank you.

**Comment by MEngMAHCelebi** [comment]
Thank you.
