### ISSUE TITLE
Specify DataTable Header with Template and Display in Different Style

### ISSUE THREAD

**Issue by bns-m-ochiai** [primefaces/primevue#6516]
### Describe the bug

When using DataTable header Template, the style of the `p-column-header-content` class is not applied and does not have any decoration like bold.
This issue occurs in the PrimeVue v4 environment.

I have attached a reproduced sample.
Thank you for your confirmation.

### Reproducer

https://stackblitz.com/edit/bwqlmv?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

https://stackblitz.com/edit/bwqlmv?file=src%2FApp.vue

Preview the sample.

The relevant code is below.

`<Column field="quantity">
        <template #header>Quantity </template>
        <template #data> </template>
      </Column>`

**Comment by tugcekucukoglu** [comment]
The new class name is: `p-datatable-column-header-content`. You can add styles using header template, or headerStyle, headerClass props.

**Comment by bns-m-ochiai** [comment]
Thank you.
I will explicitly use a new class.
