### ISSUE TITLE
Nuxt 3.13 Design token not working

### ISSUE THREAD

**Issue by geminigeek** [primefaces/primevue#6517]
### Describe the bug

Nuxt 3.13 Design tokens not working , check the reproduction

### Reproducer

https://stackblitz.com/edit/nuxt-starter-vpdzyb?file=app%2Fpages%2Findex.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

visit the home page
check the ToggleSwitch they are same 
ToggleSwitch example is copied from https://primevue.org/theming/styled/#scopedtokens

### Expected behavior

the design tokens should work as they are working in example https://primevue.org/theming/styled/#scopedtokens

**Comment by RobJmz** [comment]
I have exactly same problem

**Comment by tugcekucukoglu** [comment]
It was fixed for the next version. If you think the problem still persists, please let us know.
