### ISSUE TITLE
TreeSelect: Unable to declare a custom template for "default" slot of nested Tree component

### ISSUE THREAD

**Issue by ducmerida** [primefaces/primevue#6519]
### Describe the bug

I want to customize the items inside the TreeSelect compontent, i'm trying to declare the "default" template so the nested Tree component could use it but it doesn't work.

### Reproducer

https://stackblitz.com/edit/vckhax?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Declare a custom template named "default" inside the TreeSelect component

### Expected behavior

The content of "default" template should be used and displayed as the template for the "default" slot of nested Tree component

**Comment by tugcekucukoglu** [comment]
Unfortunately, the default slot can't be used with TreeSelect. Provided slots: https://primevue.org/treeselect/#api.treeselect.slots
