### ISSUE TITLE
ConfirmPopup: Not positioned correctly when not used inside <button>

### ISSUE THREAD

**Issue by marc-bq** [primefaces/primevue#6525]
### Describe the bug

ConfirmPopup component is rendered in wrong place when not used inside <button> tag.  
After clicking on the same element a second time while the ConfirmPopup is still displayed, then is rendered in the correct place. 

### Reproducer

https://stackblitz.com/edit/igcfdm?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

- Click on trash icon or Label to see how the element is rendered in a wrong place
- Click a second time without closing the popup to see how is rendered correectly. 
- Click on the Button or Star icon to see how is rendered correctly on the first click (both elements are inside a button tag)

### Expected behavior

ConfirmPopup renders just below the clicked element

**Comment by eneeio-nm** [comment]
I would say for accessibility reasons you should only ever attach click events to buttons, otherwise (without a lot of additional code) it degrades the experience for users who prefer navigating with keyboard.
