### ISSUE TITLE
I noticed today that there are also memory leaks when navigating between pages. To replicate the issue:

### ISSUE THREAD

**Issue by prempopatia** [primefaces/primevue#6528]
PrimeVue version
4.0.7

Vue version
3.5.11

I noticed today that there are also memory leaks when navigating between pages. To replicate the issue:

1. Visit the PrimeVue Button page: https://primevue.org/button/
![Captura de pantalla 2024-09-19 163955](https://github.com/user-attachments/assets/0fd1d68f-1045-4f90-b112-277eab489bf0)
2. Use Chrome DevTools (or another browser's developer tools) to take a memory snapshot.
![Captura de pantalla 2024-09-19 163947](https://github.com/user-attachments/assets/fb10bc50-7f99-419d-b2bb-962dfc695dbf)
3. Navigate to the DataTable page.
4. Continuously switch between the Button and DataTable pages 10 to 20 times.
![Captura de pantalla 2024-09-19 164004](https://github.com/user-attachments/assets/67031362-4fee-4086-ba3e-bf649a82c9bb)
5. After performing these steps, the memory usage increases significantly, rising from an initial 30 MB to around 850 MB. This indicates a possible memory leak associated with these components.
![Captura de pantalla 2024-09-19 165100](https://github.com/user-attachments/assets/13a35782-df1c-41d4-997b-12c721e0e856)

It seems that the memory is not being properly released, leading to substantial growth over time.

_Originally posted by @IvanCausera in https://github.com/primefaces/primevue/issues/6223#issuecomment-2361248574_

**Comment by tugcekucukoglu** [comment]
Thank you. We can track https://github.com/primefaces/primevue/issues/6223
