### ISSUE TITLE
Editor Component: Bullet list option adds a numbered list

### ISSUE THREAD

**Issue by asakahn** [primefaces/primevue#6532]
### Describe the bug

Bullet list option adds a numbered list. Also discussed here:
https://github.com/orgs/primefaces/discussions/1841

### Reproducer

https://stackblitz.com/edit/primevue-3-vite-issue-template-ykezco?file=src%2FApp.vue,src%2Fmain.js,src%2FEditor.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Either click on the bullet list button in the toolbar, or type a dash, then you will see a numbered list popup instead.

### Expected behavior

A bullet or dot should appear rather than the numbered list.

**Comment by asakahn** [comment]
I've highlighted the fix in this [discussion](https://github.com/orgs/primefaces/discussions/1841) but I'll copy and paste it again here:

The new Quill Editor v2 uses `<ol>` tags even for unordered (bullet) lists and uses the `data-list='bullet'` attribute on the `<li>` to determine whether it's an ordered or bullet list. More info: https://github.com/slab/quill/issues/3957#issuecomment-1895961689

Currently, PrimeVue's Editor component style file `node_modules/primevue/editor/style/index.mjs` has this code, which is automatically adding the numbered list to all `<li>` tags:

`.ql-editor ol li:before {\n    content: counter(list-0, decimal) '. ';\n}`

Another line of CSS should be added like so to make it more specific to the attribute type:

`.ql-editor ol li[data-list="bullet"]::before {
    content: '\2022';
}`


### A temporary fix for people coming across issue is this:

**Editor.vue**
```
<script setup lang="ts">
import Editor from 'primevue/editor';
</script>

<template>
<Editor />
</template>

<style>
.ql-editor ol li[data-list="bullet"]::before {
    content: '\2022';
}
</style>
```

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by anchan42** [comment]
A button that doesn’t do what it is designed to do is definitely a bug. It looks like a fix is easy too. Can we fix it please?🙏

**Comment by dayoadedapo** [comment]
> A button that doesn’t do what it is designed to do is definitely a bug. It looks like a fix is easy too. Can we fix it please?🙏

I second this. Literally just spent ages thinking I was doing wrong.
