### ISSUE TITLE
FloatLabel: Placeholder not hidden when empty field

### ISSUE THREAD

**Issue by muelbr** [primefaces/primevue#6536]
### Describe the bug

If an input field (e.g. inputtext, datepicker) has a placeholder value and is wrapped with FloatLabel, then the placeholder and label are shown together when the field is empty. It looks then like in this issue here:
https://github.com/primefaces/primevue/issues/5956

Perhaps the bug was introduced with this change (FloatLabelStyle.js on line 58)
https://github.com/primefaces/primevue/commit/f492825569814a203c671d7a419c8f1c0cf6fb64#diff-2451da7b05a052289b5e1bb7324c20f7f3ba55fa5ebaab6e85dbb5305ae0bcf7

There is a whole section "commented out" where `input:placeholder` would be set with `opacity: 0` (typical float label pattern)

### Reproducer

https://github.com/primefaces/primevue

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a input field with a placeholder value
2. Wrap the field with FloatLabel Component

### Expected behavior

When the input field is empty only the label should be displayed. The placeholder should be hidden.

**Comment by muelbr** [comment]
@cagataycivici Is there a reason for this disabled (block comment) stylings in FloatLabelStyle.js? Or was it just for development purposes?
Regards

**Comment by anchan42** [comment]
I put this in the css to fix it temporarily:

`.p-inputtext::placeholder {
	color: transparent;
}

.p-inputtext:focus::placeholder {
	 color: inherit;
}`

**Comment by tugcekucukoglu** [comment]
FloatLabel acts like placeholder. You should choose to use floatLabel or placeholder

**Comment by anchan42** [comment]
My use case: 
![image](https://github.com/user-attachments/assets/008e44a5-3821-48bc-bf76-18004ec5d26e)

**Comment by m-meier** [comment]
Another use case for simultaneous use would be for autocomplete fields where the float label is the description of the field (like "Teacher") and the placeholder would include search hints (like "Search by last name or department")

**Comment by BenJackGill** [comment]
+1 agree. I have many use cases like this. Please reopen this issue :)

**Comment by muelbr** [comment]
> FloatLabel acts like placeholder. You should choose to use floatLabel or placeholder

Even though I appreciate this project and your work, this is a rather arbitrary interpretation. A floating label is a label and is a descriptive information about the content of the field (**what** to enter). A placeholder is a hint or example about the correct input (**how** to enter).

In the end it is also confusing because it represents a breaking change from before.

Kind regards
