### ISSUE TITLE
TabPanel header slot reactivity is delayed

### ISSUE THREAD

**Issue by sp00x** [primefaces/primevue#654]
It seems that when working with templated slots for TabPanel headers there's a bit of lag in the reactivity - it is one step behind all the time:

Interpolated headers are immediately updated, while templated show the previous value:

It appears it can be fixed by assigning a :key to the entire TabPanel that is bound to the reactive value, but this seems like an awful hack:

```
<template>
  <div>
    <div>
      Toggle this:
      <input type="checkbox" v-model="toggle" />{{ toggle }}
    </div>

    Works as expected:
    <TabView>
      <TabPanel :header="`interpolated ${toggle}`">
        content goes here
      </TabPanel>
    </TabView>

    Observe delayed behavior here:
    <TabView>
      <TabPanel>
        <template slot="header">
          <span>templated {{ toggle }}</span>
        </template>
        <template> content goes here </template>
      </TabPanel>
    </TabView>

    Observe "fixed" behavior in :key hack here:
    <TabView>
      <TabPanel :key="toggle">
        <template slot="header">
          <span>templated {{ toggle }}</span>
        </template>
        <template> content goes here </template>
      </TabPanel>
    </TabView>

  </div>
</template>

<script>
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";

export default {
  name: "App",
  components: { TabView, TabPanel },
  data() {
    return {
      toggle: false,
    };
  },
};
</script>

<style>
</style>
```

Demo: https://d55si.csb.app/

Vue 2.x

**Comment by sp00x** [comment]
Edit: only.. the :key hack doesn't work because if you have multiple tab panels then they are reordered when they :key is updated as it removes then adds the new element... 👎

**Comment by cagataycivici** [comment]
Please use;

```xml
<template #header>
```

instead of

```xml
<template slot="header">
```

2nd one is deprecated in Vue 2 and seems to be causing issues, I'll update the docs to use the new syntax where necessary in the v2 docs now.
