### ISSUE TITLE
Toast: Toast is displayed incorrectly on most phones

### ISSUE THREAD

**Issue by dongwa** [primefaces/primevue#6547]
### Describe the bug

Toast is displayed incorrectly on most phones, such as:

![image](https://github.com/user-attachments/assets/bb303ed1-0f64-4c80-a0b4-876a16c0636d)

### Reproducer

https://primevue.org/toast/

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

ALL

### Steps to reproduce the behavior

use phone to try https://primevue.org/toast/

### Expected behavior

![image](https://github.com/user-attachments/assets/01536250-d29e-4315-a66e-c44b99a32d3f)

**Comment by tugcekucukoglu** [comment]
These are can be changed it using pt or new design tokens.

**Comment by julisch94** [comment]
> These are can be changed it using pt or new design tokens.

@tugcekucukoglu  Could you please add one or two more sentences how exactly?

I'm doing this in my `main.ts`:
```ts
import ToastService from 'primevue/toastservice'
app.use(ToastService)
```
and I'm not really sure how to bring in pt or design tokens here.
