### ISSUE TITLE
InputText: when clicking into InputText, ToolTip is rendered to body and does not disappear in FireFox

### ISSUE THREAD

**Issue by elFallino** [primefaces/primevue#6549]
### Describe the bug

This bug seems to occur using FireFox only (tested using 131.0.2 (64-Bit) on Windows 10) but not using Chrome or Edge.

Bug Demo: https://stackblitz.com/edit/tcussc?file=src%2FApp.vue

### Code sample:
```
<template>
  <div class="card flex justify-center">
    <InputText v-tooltip.top="'Enter something here'" name="CID" />
  </div>
</template>

<script setup></script>
```

### Bug description:
-  set the tag _name_ to "CID" (or contains CID along other chars but seperated with spaces like _"some CID stuff"_ - seems not to be case sensitive, so "cid" works, too )
-  have a ToolTip set.
-  hover with the cursor so the ToolTip gets visible and then enter the InputText by clicking into it

The ToolTip "jumps" to tomewhere else (in my tests it jumps to the end of BODY-Element in the DOM) and stays there.
It seems that the same issue occurs when the placeholder contains "CID".

### Screenshots:
![image](https://github.com/user-attachments/assets/d4ce2b26-c59c-4e26-b85c-f99de83c951b)

### 
I testet it using PrimeVue 4.1.0 or 4.0.7 and maybe other versions are affected, too.

### Reproducer

https://stackblitz.com/edit/tcussc?file=src%2FApp.vue

### PrimeVue version

4.1.0, 4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox 131.0.2 

### Steps to reproduce the behavior

1. set the tag name to "CID" (or contains CID along other chars but seperated with spaces like "some CID stuff" - seems not to be case sensitive, so "cid" works, too )
2. have a ToolTip set.
3. hover with the cursor so the ToolTip gets visible and then enter the InputText by clicking into it

### Expected behavior

The ToolTip should disappear when clicking the InputText Component

**Comment by tugcekucukoglu** [comment]
Cannot replicate it. Please try to use the latest version. If you think the problem still appears, please let us know.

**Comment by StayeR-Code** [comment]
Can confirm that this still happening on 4.3.6. Any fix?

Every tooltip after closing appears on body and stays there breaking the whole page layout
