### ISSUE TITLE
InputNumber: v-model not updating

### ISSUE THREAD

**Issue by psuplat** [primefaces/primevue#6551]
### Describe the bug

InputNumber does not update the value specified in v-model on every keystroke, but rather when I leave or enter field (focus/blur). It would appear that this component uses _v-model:lazy_ instead of _v-model_

Since I need to make certain checks & calculations on the fly in the background as user types, this makes this component completely useless. Not to mention **this completely breaks the vuejs fundamental input and v-model behaviors**

If that alone is not enough to treat this a priority fix, than I don't know what will. If this cannot be fixed for whatever reason, maybe just remove this component from library? Just don't give people something that causes them hours to figure out why basic vue functionality is not functioning.

(Sorry for venting, but I did just lost aforementioned hours wondering my code does not work as expected 😖 )

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-wclciu?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

**Comment by CCodam** [comment]
While I can't tell you if it's intended or not, I'll let some more experience Prime folk answer that one, I can give you a couple of solutions to your problem.

https://stackblitz.com/edit/primevue-4-vite-issue-template-xcptpm?file=src%2FApp.vue

You can listen for the input emit event on the InputNumber component.
```vue
<InptNumber v-model="testValNumber" @input="onNumberChangeInstant" />
```
The event is triggered instantly, and you can then do with the value as you see fit.
```js
function onNumberChangeInstant(event) {
  testValNumber.value = event.value;
}
```

Another solution, which you may like even better, is to use the new KeyFilter directive. https://primevue.org/keyfilter/
You can use it just the way you wanted to use the InputNumber component.
```vue
<InputText v-model="testValTextKey" v-keyfilter.num />
```

**Comment by psuplat** [comment]
@CCodam - thanks. Since in some cases I needed the currency formatting offered by the InputNumber the @input option was a better choice here.

**Comment by tugcekucukoglu** [comment]
Reference issue: https://github.com/primefaces/primevue/issues/506
