### ISSUE TITLE
Component Name: Table select checkboxes incorrect style

### ISSUE THREAD

**Issue by timothymarois** [primefaces/primevue#6552]
### Describe the bug

When using table component with selection, the checkboxes are incorrect style. 

Checkboxes when using table select options: (these aren to correct)

<img width="126" alt="Screenshot 2024-10-10 at 7 11 15 PM" src="https://github.com/user-attachments/assets/693660a9-2ad3-4c52-98d4-feb9f3864dbc">

Checkboxes not related to tables: (these are correct)

<img width="65" alt="Screenshot 2024-10-10 at 7 11 25 PM" src="https://github.com/user-attachments/assets/c096ff11-c86a-4c19-938f-877f2f28de83">

Code:

```
                   <DataTable
                        v-model:selection="selectedItems"
                        :value="items"
                        data-key="id"
                        lazy
                        selection
                        scrollable
                        show-gridlines
                        resizable-columns
                        table-style="min-width: 50rem"
                        size="small"
                    >
                        <Column
                            selection-mode="multiple"
                            header-style="width: 2rem;text-align:center"
                        />
                  </DataTable>
```

### Reproducer

screenshot of out of the box presets

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by timothymarois** [comment]
@tugcekucukoglu Thank you for the response. What i reported above is a defect, not an improvement.
