### ISSUE TITLE
Tooltip directive: problem Tooltip customization

### ISSUE THREAD

**Issue by averinbox** [primefaces/primevue#6554]
### Describe the bug

Hello everyone!
Please tell me how the Pass Through settings for the tooltip directive should look in unstyled mode. My task is to use the v-tooltip directive on buttons. When I register a global class for the directive in the application PT settings.

        Tooltip: {
            root: { class: 'position-absolute top-0 start-0 p-4' }
        },

The class field always remains empty.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-pq5zsw?file=src%2FApp.vue,src%2Fmain.js

### PrimeVue version

4.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Crome

### Steps to reproduce the behavior

When I register a global class for the directive in the application PT settings.

```
        Tooltip: {
            root: { class: 'position-absolute top-0 start-0 p-4' }
        },

```

### Expected behavior

When hovering over the tooltip, ours should have a global class for styling.

**Comment by CCodam** [comment]
The Tooltip is a directive.
To set it globally.
```js
app.use(PrimeVue, {
  pt: {
    directives: {
      tooltip: {
        root: { class: 'position-absolute top-0 start-0 p-4' }
      }
    }
  }
});
```

To set it locally.
```vue
<Button
  label="Button"
  v-tooltip="{ 
    value: 'Tooltip message',
    pt: {
      root: { class: 'position-absolute top-0 start-0 p-4' }
    }
  }"
/>
```

**Comment by averinbox** [comment]
> ```js
> directives: {
>       tooltip: {
>         root: { class: 'position-absolute top-0 start-0 p-4' }
>       }
>     }
> ```

Thank you very much! You helped me a lot. It wasn't quite obvious in the documentation.
