### ISSUE TITLE
Change Theme Dynamically

### ISSUE THREAD

**Issue by abelandcain** [primefaces/primevue#656]
I am able to load different free themes based on import in main.js.
 
`import 'primevue/resources/themes/luna-pink/theme.css'`

But i want to change theme conditionally from inside app.

This is an option in vuetify. Is it possible with primevue???

P.S. I just started using prime vue and its awesome!!!!

**Comment by cagataycivici** [comment]
If you simply put the theme using a link tag instead of bundling it within your app, you can do it dynamically as we did in the showcase.

https://github.com/primefaces/primevue/blob/ee81506e57af75e2c36016c3f295974368917d65/src/App.vue#L91
