### ISSUE TITLE
Drawer : Modal parameters should allow interaction with the content behind it.

### ISSUE THREAD

**Issue by ptorrent** [primefaces/primevue#6560]
### Describe the bug

When I put modal parameter to false, I don't see the overlay but I can't interact with elements behind the drawer

### Reproducer

https://stackblitz.com/edit/qkuurx?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

all

### Steps to reproduce the behavior

But text behind the drawer, try to select it with parameter modal = false

### Expected behavior

You should be able to select content behind the drawer if modal = false

**Comment by CCodam** [comment]
We need to pass in modal to the mask styling in drawer/style/DrawerStyle.js line 118-129, and add the following line.
See dialog/style/DialogStyle.js line 134-151 for comparison.
```js
pointerEvents: modal ? 'auto' : 'none'
```

While we wait, we can use the following css as a workaround.
```css
.p-drawer-mask:has(> [aria-modal="false"]) {
  pointer-events: none
}
```

**Comment by CCodam** [comment]
Alternatively use passthrough as a workaround.
```vue
<Drawer v-model:visible="visible" :modal="false" header="Drawer" pt:mask:style="pointer-events: none">
```

**Comment by ptorrent** [comment]
Yes it works. Thanks

**Comment by jacobg** [comment]
`pt:mask:style="pointer-events: none"` also fixes for me, but still seems like a bug.

**Comment by tugcekucukoglu** [comment]
Thanks for the updates.
