### ISSUE TITLE
InputText: 在tsx模式下，出现组件属性不存在的情况。

### ISSUE THREAD

**Issue by XAllure** [primefaces/primevue#6561]
### Describe the bug

在tsx模式下，出现组件属性不存在的情况。
![image](https://github.com/user-attachments/assets/0ac9ef6b-2d35-48e0-a0f4-1c002fa70d25)

### Reproducer

暂无

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Please check the latest version. If the problem still persists, please reopen this issue.
