### ISSUE TITLE
DataTable: RTL Support?

### ISSUE THREAD

**Issue by hoseynhoseyni** [primefaces/primevue#6562]
### Describe the bug

Thank you for this amazing project. I need RTL (Right-to-Left) support. As mentioned in the project's roadmap, this feature is planned for version 4. Could you please let me know if this feature, especially for the DataTable, will be available in 2024?
If there's anything I can do to help speed up the development of this feature, please let me know

### Reproducer

-

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
You could check the latest version for RTL support.
