### ISSUE TITLE
Toast: Not working in Nuxt 3.13.2

### ISSUE THREAD

**Issue by Ed1ks** [primefaces/primevue#6563]
### Describe the bug

After updating to Nuxt 3.13.2 the Toasts dont work anymore using useToast() composable from primvue/nuxt module.
In 3.13.1 it worked fine.

### Reproducer

https://stackblitz.com/edit/nuxt-starter-nq7qcl?file=app.vue

### PrimeVue version

4.1.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Edge, Stackblitz

### Steps to reproduce the behavior

1. open Stackblitz
2. On Button click, no Toast show up
3. install Nuxt 3.13.1
4. On Button click a Toast show up

### Expected behavior

A Toast

**Comment by vampirefan** [comment]
Same problem here. with warning: `No PrimeVue Toast provided!`
A workaround is to manually add a nuxt plugin for the toast.

**Comment by tugcekucukoglu** [comment]
Cannot replicate, could you try to use the latest version?

**Comment by Ed1ks** [comment]
> Cannot replicate, could you try to use the latest version?

Have you tried the Reproducer, or did you just closed the issue?
