### ISSUE TITLE
TreeTable: rowReorder does not work

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#6565]
### Describe the bug

This in your documentation does not work in the code:

https://primevue.org/treetable/#api.column.props.rowReorder

### Reproducer

N/A

### PrimeVue version

Latest

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

**Comment by 1Map** [comment]
Any feedback on this as I still see this bug in the latest version

**Comment by tugcekucukoglu** [comment]
It is not bug. TreeTable does not have such a feature. And not planning to add.

**Comment by 1Map** [comment]
You are wrong:

TreeTable does have such a feature, as it is stated in your documentation.

https://primevue.org/treetable/#api.column.props.rowReorder

The only thing keeping me back with your components is the reordering of rows on your treetable.
