### ISSUE TITLE
FloatLabel: Variant prop does not work

### ISSUE THREAD

**Issue by oguzhanmemis7849** [primefaces/primevue#6568]
### Describe the bug

I am using PrimeVue version 4.0.7.

I want to set a variant in FloatLabel. But no matter what I set, nothing works.

`<FloatLabel class="w-full" variant="on">
    <Select
      inputId="status"
      :options="groupedStatusList"
      optionValue="value"
      optionLabel="label"
      optionGroupLabel="label"
      optionGroupChildren="items"
      class="w-full"
      v-model="status"
    />
    <label for="status"
      >Status <span class="text-[--sompo-red]">*</span></label
    >
</FloatLabel>`
![image](https://github.com/user-attachments/assets/608c3a6a-e0dd-4c83-a289-549587882587)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-ytceno?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome, Edge, Firefox

**Comment by CCodam** [comment]
That functionality was added here https://github.com/primefaces/primevue/commit/fadd88a0a3d4e4d5872b10daa7001144a4da0a88 **after** the 4.0.7 release.
You will need to upgrade to **4.1.0**

**Comment by tugcekucukoglu** [comment]
Could you try to use the latest version?
