### ISSUE TITLE
Icons: I discover not have ppt(powerpoint) icon, Whether add it in the future

### ISSUE THREAD

**Issue by bitporo** [primefaces/primevue#6586]
Whether add powerpoint icon in the future
![image](https://github.com/user-attachments/assets/ecd25000-c58c-4325-8ea2-d08ed106022c)

**Comment by eneeio-nm** [comment]
@bitporo I'd suggest creating a request in the Prime Icon repo > https://github.com/primefaces/primeicons

**Comment by bitporo** [comment]
@eneeio-nm OK, thanks
