### ISSUE TITLE
Dropdown: Component keeps focus when an option is selected with tab

### ISSUE THREAD

**Issue by stephanestermann** [primefaces/primevue#6589]
### Describe the bug

The description of the Dropdown says that the focus moves to the next element in page is an option is selected with tab.
![image](https://github.com/user-attachments/assets/9d84fede-8c35-4bde-9e32-a408ee85359f)

The problem also appear in PrimeVue 4
Run the stackblitz in a browser and you will see (in console) that the following textbox get for a short time the focus but lost it immediately and the Dropdown will focused again
![image](https://github.com/user-attachments/assets/2876eb91-c81b-4304-8cdb-c59cea6a523a)

In the Github Discussions i found an entry which reported a similar Behave

### Reproducer

https://stackblitz.com/edit/primevue-3-vite-issue-template-df6tsb?file=src%2FApp.vue

### PrimeVue version

3.53.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Focus the Dropdown
2. Select with keydown an option
3. Choose the option with the TAB-key
4. The option is selected, but the focus is still on the Dropdown

### Expected behavior

The focus should be on the following textbox, like it is documentated.

**Comment by CCodam** [comment]
> [!IMPORTANT]
> This issue is due to the **setTimeout** within the **hide()** method of the **Dropdown**(v3)/**Select**(v4) component

https://github.com/primefaces/primevue/blob/8d8ca02bd375b565d99e02cb92831da6699c22d0/components/lib/dropdown/Dropdown.vue#L316
I'm not sure what issue the _// For ScreenReaders_ comment on the **setTimeout** refers to, it's been there at least as far back as 2022.

Using **nextTick** instead of  **setTimeout** fixes the focus issue, however I'm not sure if that's enough for the ScreenReaders issue?
```js
await nextTick();
_hide();
```

> [!TIP]
> Temporary workaround
> https://stackblitz.com/edit/primevue-3-vite-issue-template-2jt5q9?file=src%2FApp.vue

- We ref the **Dropdown** component
- We override the **hide()** method at **onMounted** to use **nextTick** instead

**Comment by stephanestermann** [comment]
Thanks for the workarround @CCodam , it work's :grinning:

**Comment by tugcekucukoglu** [comment]
Offical documentation offers the same behaviour: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/
So there is no plan to change this bahaviour.

**Comment by stephanestermann** [comment]
@tugcekucukoglu 
When I select an item in the dropdown at "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/" with the tab key, then the focus is after the selection in next focusable element?
So it's not the same behavior?

In the PrimeVue-Dropdown/Select-Component the focus jump for some milliseconds to the next focusable element and then back to the dropdown. You can see this behavior in Stackblitz of the issue.

**Comment by Rubydesic** [comment]
@tugcekucukoglu As stephanestermann noted, this is _not_ the same behavior as the page you linked. On the page you linked, the combobox correctly transfers focus to the next element.
