### ISSUE TITLE
Dialog: pt pcCloseButton not work

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#6594]
### Describe the bug

I have a <dialog 		:pt="{
			root: ({}) => ({
				id: `${id}`,
				'aria-labelledby': `titulo-modal-${id}`,
				'aria-describedby': props?.conInfo ? `descripcion-modal-${id}` : undefined,
			}),
			pcCloseButton: ({}) => ({
				'data-testid': 'cerrarModal',
				onclick: (evt) => {
					cerrarModal();
				},
			}),
		}" but pcCloseButton not working. 

### Reproducer

https://stackblitz.com/edit/5oxyf8?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Current implementation is correct. 

Thanks for your contribution.
