### ISSUE TITLE
IftaLabel / FloatLabel : label not showing on InputNumber (and maybe it is expected...)

### ISSUE THREAD

**Issue by Fabback** [primefaces/primevue#6598]
### Describe the bug

IftaLabel and FloatLabel don't display the <label> content when using InputNumber

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-ek6xli?file=src%2FApp.vue

### PrimeVue version

4.1.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

I was expected to have the same display on both types of input, but only because it doesn't say otherwise in the documentation (or that I missed)

(EDIT)
BTW : had to modify a bit the template (updating to 4.1.1 and removing deprecated components)

**Comment by CCodam** [comment]
The label is there, although it's hidden behind the InputNumber span that encapsulates the InputText.
I'm not really sure what the best course of action is to resolve this issue in the codebase, we can give the label a higher z-index, we can reorder them, or change the examples to place the label after the input.

> [!TIP]
> Workaround/Solution
> https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-ptnl2h?file=src%2FApp.vue

- Place the Label component after the Input component
```vue
  <IftaLabel>
    <InputNumber name="inputNumber" />
    <label for="inputNumber">Label for number input</label>
  </IftaLabel>
```

**Comment by Fabback** [comment]
That is actually one thing I didn't think about !

It worked like a charm, so I guess this is not so much a bug, than it is a misinterpretation on my behalf.

Thanks,
