### ISSUE TITLE
in chrome: keyboard navigation is not working in drawer when it needs to scroll

### ISSUE THREAD

**Issue by Christian-Lange-ext-deka** [primefaces/primevue#6600]
### Describe the bug

A Drawer that has text-only content that is not visible on a single page can not be scrolled by keyboard.

I could set a tabindex in the the drawer but this is bad practice as far as I know.

Is little bit bigger, but I'm wondering why PrimeVue is not using a native html dialog for the PrimeDrawer and the PrimeDialog. In a native dialog I do not have the problem.

### Reproducer

https://stackblitz.com/edit/jjnqsi?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

working in:
- Firefox 131.0.3 (32-Bit)

not working in:
- Chrome Version 128.0.6613.186 (Offizieller Build) extended (64-Bit)

### Steps to reproduce the behavior

1. create a Drawer
2. put much text inside, that it not fits on the page
3. enter the Drawer by keyboard
4. try to scroll by keybard (up and down keys do not work)

### Expected behavior

up and down keys should scroll the content

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
