### ISSUE TITLE
updatePreset utils theme: not working

### ISSUE THREAD

**Issue by JoseAntonioNavasSolutia** [primefaces/primevue#6605]
### Describe the bug

Nuxt.config.ts:
primevue: {
		usePrimeVue: true,

		options: {
			unstyled: false,
			ripple: false,
			inputVariant: "outlined",
			theme: {
				preset: Lara,
			},
		},

const update= () => {

	updatePreset({
		semantic: {
			primary: {
				50: "{indigo.50}",
				100: "{indigo.100}",
				200: "{indigo.200}",
				300: "{indigo.300}",
				400: "{indigo.400}",
				500: "{indigo.500}",
				600: "{indigo.600}",
				700: "{indigo.700}",
				800: "{indigo.800}",
				900: "{indigo.900}",
				950: "{indigo.950}",
			},
		},
		colorScheme: {
			light: {
				primary: {
					color: "{indigo.50}", 
					inverseColor: "#ffffff",
					hoverColor: "{indigo.50}",
					activeColor: "{indigo.50}",
				},
				highlight: {
					background: "{indigo.50}",
					focusBackground: "{indigo.50}",
					color: "#ffffff",
					focusColor: "#ffffff",
				},
			},
		},
	});
};

### Reproducer

.

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

ES6

### Build / Runtime

Nuxt

**Comment by tiberiu-potec** [comment]
I've got the same issue, did you manage to solve it?

**Comment by JoseAntonioNavasSolutia** [comment]
Yes, 
I install @primevue/nuxt-module, @primevue/themes, @primevue/auto-import-resolver and primevue. 
I uninstall @nuxt-primevue
and it was solved.

nuxt.config.ts:

	modules: [
	        ....
		"@primevue/nuxt-module",
	],
primevue: {
		usePrimeVue: true,

		options: {
			unstyled: false,
			ripple: false,
			inputVariant: "outlined",
			theme: {
				preset: Lara,
			},
		},
....
