### ISSUE TITLE
DocPTVIewer: hovering over section name doesn't show the section correctly

### ISSUE THREAD

**Issue by mergehez** [primefaces/primevue#6614]
### Describe the bug

hovering over section name doesn't show the section correctly

In the screenshot below there is a line below head section but there actually should be a box

![image](https://github.com/user-attachments/assets/7a495102-5cc7-4058-bcbc-2f09f61bda3c)

### Reproducer

no need

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 128.0.6613.138

### Steps to reproduce the behavior

1. Go to [https://primevue.org/datatable/](https://primevue.org/datatable/)
2. Open the "PASS THROUGH" tab
3. Hover over "thead" from the list on the right side

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
