### ISSUE TITLE
Component Name: DataTable Cannot use the editorCancelCallBack / editorSaveCallback while editing in cell mode

### ISSUE THREAD

**Issue by gunerfurkanilker** [primefaces/primevue#6617]
### Describe the bug

Cannot use the editorCancelCallBack / editorSaveCallback while editing in cell mode

When i'm using cell edit mode, i added a button next to the my input, however when i want to use editorCancelCallBack / editorSaveCallback buttons, cell doesn't close.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-ylsyei?file=src%2FApp.vue

### PrimeVue version

^4.0.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome Version 129.0.6668.101

### Steps to reproduce the behavior

Click the cell on cell edit mode, and try to use buttons of the click custom editorCancelCallBack / editorSaveCallback events, cell doesn't close 

### Expected behavior

editorCancelCallBack / editorSaveCallback events close the editing cell

**Comment by tugcekucukoglu** [comment]
These callbacks are for editMode: row not cell
