### ISSUE TITLE
TreeTable: filterField - also defined as a function, but ignore getter value

### ISSUE THREAD

**Issue by MstrVLT** [primefaces/primevue#6618]
### Describe the bug

```
filterField?: string | ((item: any) => string) | undefined;
```
FilterField is also defined as a function, but the getter is not called  (App.vue:34)
```
      <Column
        :filterField="() => 'size'"
        header="Size (custom)"
        style="min-width: 12rem"
      >
```

### Reproducer

https://stackblitz.com/edit/hbntzb

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

**Comment by MstrVLT** [comment]
The DataTable also contains this issue

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
