### ISSUE TITLE
With Typescript shims not working for: this.$dialog, this.$confirm, this.$toast

### ISSUE THREAD

**Issue by Burtsev-Alexey** [primefaces/primevue#6624]
Shims are declared in module 'vue' doesnt work with options API, I changed it to be module '@vue/runtime-core' - and it works.
![image](https://github.com/user-attachments/assets/186f50a4-7f6f-4a46-b854-8e9587a9e411)

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-gss6mp?file=src%2FApp.vue

### PrimeVue version

4.1.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Interesting! Please see this issue; https://github.com/primefaces/primevue/issues/6199

@sceee Could you please check this issue?

**Comment by sceee** [comment]
@Burtsev-Alexey I cannot see in your reproducer what is not working.
Also, your reproducer is using an older primevue version (4.0.0-rc.3), please update it first to use the latest version.
Could you then please explain the steps you did to reproduce it?
The Shims should only affect the typescript compile, not runtime.

FYI @mertsincan

**Comment by Burtsev-Alexey** [comment]
> The Shims should only affect the typescript compile, not runtime.
Yes, it effects only compilation errors.
> Also, your reproducer is using an older primevue version (4.0.0-rc.3), please update it first to use the latest version.
I have used the one that was provided in link when I was creating an issue. I have not realized I need to change version...
> I cannot see in your reproducer what is not working.
Because StackBlitz doesnt show syntax (compilation) errors... You need to open project in IDE (I use VSCode)

This is how it looks without fix:
![image](https://github.com/user-attachments/assets/5cce9076-3646-4dda-b2fc-95f519a7ab23)

This is how it looks with fix:
![image](https://github.com/user-attachments/assets/fc50b8dc-46ae-4fdf-9de6-266a44703c04)

**Comment by sceee** [comment]
Hi @Burtsev-Alexey , I've updated your reproducer to primevue 4.1.1 (and removed the StepperPanel import which is no longer exported) and ran `npm run build` (which you can also do in stackblitz) - no issues are displayed:
https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-baezk4?file=package.json

![image](https://github.com/user-attachments/assets/db8db03d-8f9a-4e0a-9344-b4a34ac2fd64)

According to your screenshots it looks like you are using a different project locally - as the affected component is called `Foo.vue`.
Probably you have other libraries installed that incorrectly augment vue types creating that issue? See #6199 for details.

**Comment by Burtsev-Alexey** [comment]
> Probably you have other libraries installed that incorrectly augment vue types creating that issue? See #6199 for details.

@sceee This could be the case, Thank you I will try now with clean reproducer and come back with result

**Comment by Burtsev-Alexey** [comment]
@sceee You are right, I found the "evil", it was https://github.com/imcvampire/vue-axios dependency that is "cleaning up" ComponentCustomProperties

Sorry for inconvenience, issue closed.
