### ISSUE TITLE
No multiple option in v4 AutoComplete?

### ISSUE THREAD

**Issue by molul** [primefaces/primevue#6625]
I'm looking for a component similar to this: 
https://www.npmjs.com/package/react-tag-autocomplete

so you type some text and it displays suggestions, if any. If no suggestion exists, you can press a key (usually ',') and it gets added to the result as a new chip. 

I've read throughout the Select, MultiSelect and AutoComplete components, but I think there's nothing with that functionality. Am I right? (Please say no xD).

**Comment by CCodam** [comment]
You can use the **AutoComplete** component with `multiple :typeahead="false"` and press the **Enter** key to add as new chip
https://primevue.org/autocomplete/#multiple

Using "," as separator is possible with the undocumented "deprecated" **InputChips** component, which the **AutoComplete** component uses behind the scenes, but then you miss out on suggestions.

I hope that we at some point will get the separator and other logic from the **InputChips** (old v3 **Chips**) component into in the **AutoComplete** component

For workaround and additional information on this see https://github.com/primefaces/primevue/issues/6611

**Comment by molul** [comment]
> You can use the **AutoComplete** component with `multiple :typeahead="false"` and press the **Enter** key to add as new chip
> https://primevue.org/autocomplete/#multiple
> 
> Using "," as separator is possible with the undocumented "deprecated" **InputChips** component, which the **AutoComplete** component uses behind the scenes, but then you miss out on suggestions.
> 
> I hope that we at some point will get the separator and other logic from the **InputChips** (old v3 **Chips**) component into in the **AutoComplete** component
> 
> For workaround and additional information on this see https://github.com/primefaces/primevue/issues/6611

That doesn't seem to work in mobile, does it? I typed stuff in the first input and pressed enter and nothing happened.

**Comment by CCodam** [comment]
You're correct, a lot of modifications are necessary for the AutoComplete component to function as you need.
I still hope that this is something that can be addressed by someone at some point, I currently don't have the time myself, to make a quality pull request for these feature feature changes :/

The following is how far I've gotten .. it should work with suggestions and on mobile.
https://stackblitz.com/edit/primevue-4-vite-issue-template-muvzf2?file=src%2FApp.vue
However there is still several issue to overcome.
As an example, when typing in lowercase "apple" and pressing Enter, Tab or the separator ",", it will try to match this with a suggestions, and replace it with the item "Apple".
However the suggestions are not the complete item list, it's a filtered list updated on search, and if you press Enter, Tab or the separator ",", while the search logic is processing, the list will be empty, which will result in no match and a lowercase "apple" chip.

**Comment by CCodam** [comment]
You're correct, a lot of modifications are necessary for the AutoComplete component to function as you need.
I still hope that this is something that can be addressed by someone at some point, I currently don't have the time myself, to make a quality pull request for these feature changes :/

The following is how far I've come .. it should work with suggestions and on mobile.
https://stackblitz.com/edit/primevue-4-vite-issue-template-muvzf2?file=src%2FApp.vue
However there is still several issue to overcome.
As an example, when typing in lowercase "apple" and pressing Enter, Tab or the separator ",", it will try to match this with a suggestions, and replace it with the item "Apple".
However the suggestions are not the complete item list, it's a filtered list updated on search, and if you press Enter, Tab or the separator ",", while the search logic is processing, the list will be empty, which will result in no match and a lowercase "apple" chip.

**Comment by molul** [comment]
Here's a Vue component that works almost exactly as I explained: 
https://vue-tag-input.vercel.app/

In the menu, select Examples -> AutoComplete with API (can't provide the direct link because it's a Vue web app and it returns 404 if you don't arrive from the home page).

It's quite convenient: 
-It can provide suggestions from a defined array. Click on the suggestion from the list to add it.
-Press Enter for adding current text as tag 
-Backspace for attempting to delete (turns light red), another backspace to confirm deletion
-Works on mobile

It doesn't have comma for adding text as tag, but I actually prefer enter, so the text I type can have commas.

I'll have to take some time to style it like the rest of Primevue components I'm using, but it's a great resource that Primevue doesn't currently have (despite having an amazing library of components, truth be told).

Here's hoping Primevue adds this someday :) Well, actually, I'll raise a feature request.

**Comment by molul** [comment]
> You're correct, a lot of modifications are necessary for the AutoComplete component to function as you need. I still hope that this is something that can be addressed by someone at some point, I currently don't have the time myself, to make a quality pull request for these feature changes :/
> 
> The following is how far I've come .. it should work with suggestions and on mobile. https://stackblitz.com/edit/primevue-4-vite-issue-template-muvzf2?file=src%2FApp.vue However there is still several issue to overcome. As an example, when typing in lowercase "apple" and pressing Enter, Tab or the separator ",", it will try to match this with a suggestions, and replace it with the item "Apple". However the suggestions are not the complete item list, it's a filtered list updated on search, and if you press Enter, Tab or the separator ",", while the search logic is processing, the list will be empty, which will result in no match and a lowercase "apple" chip.

Sorry, I didn't notice your reply before my last message.

I tested that and it's pretty good. After further thought, I think I prefer not using comma for adding a new tag (Enter is fine). What you say about "apple"/"Apple" is not really a problem for me.

The only downside in your example is that, in mobile, while Enter does work (thanks for that), unlike in desktop, it enters a new line and you can't use backspace for deleting the last chip. But well, you can just click on the "X" in the chip. 

I could use this for now, although I hope [the feature request I submitted](https://github.com/orgs/primefaces/discussions/2904) is taken by someone someday :)

Thanks very much!

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by guillaume-bonnefoy** [comment]
Hi, I made an implemention of this myself, for my use case.
It was a bit of a struggle so I figured I might share.
Please share any improvement you might see. Specifically I handle a `addNewTag` case in the `parent.vue`, to allow error handling, but this should ideally be scopped to `AutoCompleteWithTags.vue`

![image (3)](https://github.com/user-attachments/assets/0fec9a3d-93ab-4c9c-a10a-28ea7a6b974c)


**AutoCompleteWithTags.vue**
```
<script setup lang="ts">
// As of 10/09/2024, Primevue's AutoComplete is lacking a way to both
// autocomplete and create new tags with the "enter key". This is why
// we need to implement this manually.
// When using it, you must update the parent component's selectedTags
// when the eventType is 'pressEnter'

const props = defineProps<{
  availableTags: ITag[]
}>()
const emit = defineEmits(['addTag', 'deleteTag'])
const selectedTags = defineModel('selectedTags', { type: Array as PropType<ITag[]> })

const filteredTags: Ref<ITag[] | undefined> = ref([])

const autoCompleteRef = ref()

function filterTags(event: { query: string }) {
  filteredTags.value = props.availableTags.filter((item: any) => {
    const isIncluded = item.value.includes(event.query)
    const isSelected = selectedTags.value?.some((selected: any) => selected.id === item.id)

    return isIncluded && !isSelected
  }) ?? []
}

// @keyup.enter When the user presses enter
// We reproduce the same behavior as in @change="handleTagSelect", but manually
// The event type 'pressEnter' requires a manual update to selectedTags in the parent component
async function handleTagInput(event: { target: HTMLInputElement }) {
  const newTag = event.target.value
  if (!newTag) return

  emit('addTag', { tag: newTag, eventType: 'pressEnter' })

  event.target.value = ''
  autoCompleteRef.value.hide()
}

// @change="handleTagSelect" Whenever the user makes a change to the selected tags (dropdown, autocomplete, deletion)
// This is also triggered on deletion (X icon)
// Since the deletion is handled in @option-unselect="handleTagDelete", we need to ignore the event in this function
async function handleTagSelect(event: { originalEvent: Event, value: ITag[] }) {
  const userClickedOnDeletionIcon = (event.originalEvent.currentTarget as HTMLElement)?.classList.contains('p-chip-remove-icon')
  const lastTag = event.value[event.value.length - 1]
  if (lastTag && !userClickedOnDeletionIcon) {
    emit('addTag', { tag: lastTag.value, eventType: 'dropdownClick' })
  }
}
</script>

<template>
  <AutoComplete
    ref="autoCompleteRef"
    v-model="selectedTags"
    dropdown
    dropdownMode="current"
    empty-search-message="Press enter to create a new tag"
    inputId="asset_tags"
    multiple
    optionLabel="value"
    :suggestions="filteredTags"
    @change="handleTagSelect"
    @complete="filterTags"
    @keyup.enter="handleTagInput"
    @option-unselect="emit('deleteTag', $event.value.id, $event.value.value)"
  />
</template>

```

**parent.vue**
```
<template>
  <AutoCompleteWithTags
    v-model:selectedTags="selectedTags"
    :availableTags
    @add-tag="addNewTag"
    @delete-tag="deleteTag"
  />
</template>

<script setup lang="ts">
// ...
async function addNewTag(eventType: 'pressEnter' | 'dropdownClick') {
  const response = await yourApiCall()

  if (eventType === 'pressEnter') selectedTags.value.push(response.data)
}
// ...
</script>
```
