### ISSUE TITLE
SplitButton: Prop Style not working 

### ISSUE THREAD

**Issue by xiscohv** [primefaces/primevue#6633]
### Describe the bug

When adding the prop style with background or color does not work. By default gets the background and color of the internal buttons and does not override. 

### Reproducer

https://stackblitz.com/edit/giaqdp?file=src%2FApp.vue

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

ALL

### Steps to reproduce the behavior

1. In the button it works
https://stackblitz.com/edit/eidbio?file=src%2FApp.vue
2. In the splitbutton does not work
https://stackblitz.com/edit/giaqdp?file=src%2FApp.vue

To reproduce it add :style="{ backgroundColor: 'red' }" to any SplitButton.

### Expected behavior

Change the css property to the entire component.

**Comment by betavs** [comment]
```vue
    <SplitButton
      label="Save"
      @click="save"
      :model="items"
      :style="{ backgroundColor: 'red' }"
      :buttonProps="{ style: { backgroundColor: 'red' } }"
      :menuButtonProps="{ style: { backgroundColor: 'red' } }"
    />
```

**Comment by xiscohv** [comment]
That works! Thank you! Is there a way to change the color of the button/splitbutton conserving the hover, click, etc?

**Comment by betavs** [comment]
> That works! Thank you! Is there a way to change the color of the button/splitbutton conserving the hover, click, etc?

Reset button/splitbutton css variables, for example: `--p-button-primary-background`
