### ISSUE TITLE
Menubar: Submenu is not closed if you put your cursor to another part of the menubar and click

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#6638]
### Describe the bug

As the title says and as the GIF shows, when you click away when your submenu is open, it should disappear. However, it doesn't when you click on another part of the menubar. It makes the user experience really uncomfortable.

First I show the correct behaviour, then the incorrect one.
![chrome-capture-2024-10-24](https://github.com/user-attachments/assets/0f31fc30-829d-4e30-8be9-fcb5a7e21a2b)

### Reproducer

In the description

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by tugcekucukoglu** [comment]
It is expected behaviour. Thank you!
