### ISSUE TITLE
Tabs: Unable to navigate to some tabs, when scrollable property is set

### ISSUE THREAD

**Issue by rishabhtiwary** [primefaces/primevue#6642]
### Describe the bug

In the Tabs component, when scrollable property is set, some tabs are hidden in the view. 
On next button click, the hidden tab is skipped. Same behaviour observed on previous button click.
User is unable to navigate to these tabs.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-xsczij?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

At each step, observe the tabs visible:
1. Go to the Tabs component in the view, when scrollable property is set.
2. Click on the next button. 
3. Click on previous button.  

### Expected behavior

User should be able to navigate to any tab.

**Comment by tugcekucukoglu** [comment]
Cannot replicate. Which browser do you use?
