### ISSUE TITLE
Reference to a non existing function in InputChips component

### ISSUE THREAD

**Issue by sbaby83** [primefaces/primevue#6643]
Hi,

InputChips component calls a "removeOption" function which does not exist.

`Uncaught TypeError: _ctx.removeOption is not a function`

https://github.com/primefaces/primevue/blob/b752717783d995fe7e7c158f85381ef1986fb343/packages/primevue/src/inputchips/InputChips.vue#L31

Version : 4.1.1

**Comment by avramz** [comment]
Hi, InputChips have been deprecated since 4.0.0-beta.3 -> https://github.com/primefaces/primevue/milestone/184?closed=1

**Comment by sbaby83** [comment]
Does "deprecated" means unusable ?

**Comment by tugcekucukoglu** [comment]
Hi,

InputChips is deprecated and we do not support it. It will be completely removed with version 5.
