### ISSUE TITLE
Slider range operation bug

### ISSUE THREAD

**Issue by grene78** [primefaces/primevue#6649]
### Describe the bug

When the slider is configured for range operation with a lower bound below 0.  A value of 0 will render on the far left of the slider.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-izxnwj?file=src%2FApp.vue

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

edge, chrome

### Steps to reproduce the behavior

create slider with min -100 to max 100 
now set model value = [0,50] 
[1,50] and [-1,50' work as expected

### Expected behavior

when range is 0 is should render between -1 and 1 but instead renders to the left.

**Comment by j0rgedev** [comment]
Hello @grene78. I've created a PR that fixes this issue. Let's wait for the team to check it out 😁🫱🏻‍🫲🏻
