### ISSUE TITLE
Size prop support for more components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#6651]
Currently InputText and Button have this prop, expand the usage to more components;

- AutoComplete
- CascadeSelect
- Checkbox
- DatePicker
- InputMask
- InputNumber
- InputOtp
- MultiSelect
- Password
- RadioButton
- Select
- SelectButton
- Textarea
- ToggleButton
- TreeSelect

The new Design tokens added are;

**semantic**
```js
form.field.sm.font.size
form.field.sm.padding.x
form.field.sm.padding.y
form.field.lg.font.size
form.field.lg.padding.x
form.field.lg.padding.y
```

**components**
- cascadeselect
- treeselect
- select
- multiselect
- textarea

```js
componentname.sm.font.size
componentname.sm.padding.x
componentname.sm.padding.y
componentname.lg.font.size
componentname.lg.padding.x
componentname.lg.padding.y
```

- checkbox
```js
checkbox.sm.width
checkbox.sm.height
checkbox.icon.sm.size
checkbox.lg.width
checkbox.lg.height
checkbox.icon.lg.size
```

- radiobutton
```js
radiobutton.sm.width
radiobutton.sm.height
radiobutton.icon.sm.size
radiobutton.lg.width
radiobutton.lg.height
radiobutton.icon.lg.size
```

- autocomplete
```js
autocomplete.dropdown.sm.width
autocomplete.dropdown.lg.width
```

- datepicker
```js
datepicker.dropdown.sm.width
datepicker.dropdown.lg.width
```

- inputotp
```js
inputotp.gap
inputotp.input.width
inputotp.input.sm.width
inputotp.input.lg.width
```

- togglebutton
```js
togglebutton.sm.font.size
togglebutton.sm.padding
togglebutton.lg.font.size
togglebutton.lg.padding
```

**Comment by jumika** [comment]
Is it possible to somehow integrate this prop in InputGroup? I find myself writing custom code for InputGroup cases to get the group inline with other small size inputs.
