### ISSUE TITLE
OrderList: 'selection' prop is not working as expected

### ISSUE THREAD

**Issue by rbsamoht** [primefaces/primevue#6660]
### Describe the bug

The `selection` prop of the OrderList is not updated when items are selected in the OrderList

### Reproducer

https://stackblitz.com/edit/jahezs

### PrimeVue version

4.1.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the StackBlitz
2. Open the developer console
3. Select a few items in the OrderList
4. Click on the button labelled `Print selection in console`
5. Check the console output (the value of the `selection` ref pointing to the `selection` prop of the OrderList is always `[]`)

### Expected behavior

The value of the `selection` ref should reflect the selection

**Comment by avramz** [comment]
Hi! :) 

This is not a bug, you can simply utilize Vue3 syntax with v-model:selection. As in the sample https://stackblitz.com/edit/jahezs-4n9an7?file=src%2FApp.vue

https://v3-migration.vuejs.org/breaking-changes/v-model#v-model-arguments
