### ISSUE TITLE
Menu components: Blocked aria-hidden on an element error

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#6692]
### Describe the bug

When using a MenuBar with Router (https://primevue.org/menubar/#router) and you click on a menu item you receive the following error in your console:

`Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: a
Ancestor with aria-hidden:  `

![image](https://github.com/user-attachments/assets/9c79cd8a-3d14-4d8a-9b2c-67843c28be0d)

### Reproducer

https://primevue.org/menubar/#router

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Brave

### Steps to reproduce the behavior

1. Visit the link and click on the Router dropdown
2. See the error on console (at least in Brave)

**Comment by nestorrente** [comment]
This is happening in PrimeVue's 3.x menu items too. It seems that the items are rendered with `aria-hidden="true"` even when the menu is already opened, and thus visible.

![image](https://github.com/user-attachments/assets/e9c39942-7627-4991-a581-957e3ca53d71)

**Comment by cvkipp** [comment]
I found this is also happening with PrimeVue 4.x PanelMenu component

**Comment by eepson123tw** [comment]
TieredMenu also happening~

**Comment by pdipax** [comment]
Chips when use @remove also happening~

**Comment by lwpinion** [comment]
@tugcekucukoglu Do you intend to apply this fix in v3 as well? This bug isn't just an error in the console, but sometimes prevents the navigation from even taking place.

**Comment by jougisljs** [comment]
In "4.2.5" ， using Dock also show the error.
How to handle it ?

**Comment by scottmillion** [comment]
Had this issue on TieredMenu component. 

@mousedown.prevent fixed it.
