### ISSUE TITLE
Docs: Edit dialog emit event description clearly

### ISSUE THREAD

**Issue by kimhanui** [primefaces/primevue#6698]
### Describe the bug

I want to suggest changing `Dialog`'s  emit event( **update:visible** ) description like this
`Emitted when the visible changes.`
to
`Emitted when the visible changes to 'false'`

because It is never emitted when visible changes to 'true'
> ref : https://github.com/primefaces/primevue/blob/master/packages/primevue/src/dialog/Dialog.vue#L143

### Reproducer

.

### PrimeVue version

4.1.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

ALL

### Steps to reproduce the behavior

See docs https://primevue.org/dialog/#api.dialog.emits.update:visible

### Expected behavior

Please edit the description

**Comment by tugcekucukoglu** [comment]
Thanks for your attention. we check the documentation.
