### ISSUE TITLE
Forms: Could not resolve "valibot"

### ISSUE THREAD

**Issue by 25Das** [primefaces/primevue#6708]
### Describe the bug

X [ERROR] Could not resolve "valibot"

    node_modules/@primeuix/forms/resolvers/valibot/index.mjs:4:54:
      4 │ import { getDotPath, safeParse, safeParseAsync } from "valibot";
        ╵                                                       ~~~~~~~~~

  You can mark the path "valibot" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

 ERROR  error while updating dependencies:                                                                                                                                                                                                 12:01:49  
Error: Build failed with 1 error:
node_modules/@primeuix/forms/resolvers/valibot/index.mjs:4:54: ERROR: Could not resolve "valibot"
    at failureErrorWithLog (C:\www\stabilite\stabilite-tauri\node_modules\vite\node_modules\esbuild\lib\main.js:1472:15)
    at C:\www\stabilite\stabilite-tauri\node_modules\vite\node_modules\esbuild\lib\main.js:945:25
    at C:\www\stabilite\stabilite-tauri\node_modules\vite\node_modules\esbuild\lib\main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    

For some reason it breaks resolving valibot, but I am not using valibot resolver.

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template-192m3f?file=app.vue

### PrimeVue version

4.2.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Open reproduce or "edit in stackblitz" from form resolvers docs.

**Comment by mertsincan** [comment]
Thanks a lot for your report! I'll check and get back to you

**Comment by mertsincan** [comment]
PrimeVue 4.2.1 Released 🚀 Please try it.
