### ISSUE TITLE
MultiSelect: maxSelectedLabels prop not respected

### ISSUE THREAD

**Issue by zkriszti** [primefaces/primevue#6716]
### Describe the bug

The maxSelectedLabels prop is not respected in the MultiSelect component. There has been [an earlier issue](https://github.com/primefaces/primevue/issues/6485), where this problem occured with the chip display option, but now this seems to be present even without chip. 

### Reproducer

https://stackblitz.com/edit/jhpdp2?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

My minimal reproducible example has been forked from the [example of the documentation](https://primevue.org/multiselect/#basic):
- go to: [https://stackblitz.com/edit/jhpdp2?file=src%2FApp.vue,package-lock.json](https://stackblitz.com/edit/jhpdp2?file=src%2FApp.vue)
- Select more than 3 cities from the dropdown - this will be entirely possible even though value for the maxSelectedLabels prop is 3.

### Expected behavior

After selecting n elements, where n is the value of maxSelectedLabels, the (n+1)th element shouldn't be selectable

**Comment by brambekkers** [comment]
@tugcekucukoglu Can you explain the behavior you aspect when use `maxSelectLabels="3"`. I dont see any visual feedback. 

![Image](https://github.com/user-attachments/assets/79286d4f-a4e3-4a0e-b7fb-5601ae9e0179)

Can you help me on this one?
