### ISSUE TITLE
Form: type of v-slot="$form" is incorrect

### ISSUE THREAD

**Issue by Lirrrx** [primefaces/primevue#6717]
type of v-slot="$form" is incorrect.
Screenshot 1 - real $form contents.
Screenshot 2 - incorrect type definitions.

![CleanShot 2024-11-03 at 00 40 55@2x](https://github.com/user-attachments/assets/f2cfd2a5-447f-4fe4-92c2-ac789c2f4b53)

![CleanShot 2024-11-03 at 00 40 21@2x](https://github.com/user-attachments/assets/69832579-ebf6-4e14-a1c7-06a22760cb9d)

Repo with reproduce https://github.com/Lirrrx/prime-vue-form-ts-issue

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-vblteo?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

any

### Expected behavior

$form types represent real output

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check and get back to you.

**Comment by alirni** [comment]
@mertsincan  I got this too. So I fixed it and sent a PR. #6941
I hope this will help.
