### ISSUE TITLE
Autocomplete on dynamic forms

### ISSUE THREAD

**Issue by raizdev** [primefaces/primevue#6719]
### Describe the bug

How does autoComplete on dynamicForm works? It not documented and I am just wondering how to add it or is this not supported? I am talking about the complete, suggestions fn ofcourse :)

````
fields: {
   executor: {
      label: 'Contractor',
      as: 'autoComplete',
      schema: z.string().min(1, { message: 'Contractor is required.' }),
      complete: (event) => {
          console.log(event)
      },
      suggestions: (event) => {
          console.log(event)
      }
   }
}
````

### Reproducer

https://stackblitz.com/edit/toi4ll?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Please try;
https://stackblitz.com/edit/toi4ll-barvrm?file=src%2FApp.vue

Component name is set to 'as' option. Exp; <AutoComplete> => as: 'AutoComplete'

**Comment by raizdev** [comment]
> Please try; https://stackblitz.com/edit/toi4ll-barvrm?file=src%2FApp.vue
> 
> Component name is set to 'as' option. Exp; => as: 'AutoComplete'

ofcourse... I'm stupid. Thanks for your help mert, maybe to add in documentation somewhere, probably others will ask it either. Good night !!
