### ISSUE TITLE
Forms: InputNumber inside FormField requires extra keypress for input when validation error is visible

### ISSUE THREAD

**Issue by jsodeman** [primefaces/primevue#6727]
### Describe the bug

When an InputNumber is wrapped in a FormField and the validation error is visible, you have to press a key twice to get the key to input into the field. For example pressing "55" to get "5".

If the validation error isn't already visible then the input works as expected.

### Reproducer

https://stackblitz.com/edit/hlkqty?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to the linked stackblitz

type a single digit into the field, the validation error will disappear but the number won't be set

type a second digit, this digit will appear in the input

**Comment by tugcekucukoglu** [comment]
Reference issue: https://github.com/primefaces/primevue/issues/506
