### ISSUE TITLE
MultiSelect: Selected labels hidden

### ISSUE THREAD

**Issue by 25Das** [primefaces/primevue#6728]
### Describe the bug

This was quite tricky for me to track but I found this iteraction:

- MultiSelect + FloatLabel + Form

MultiSelect usually breaks selected label without v-model and works if a placeholder is present.

Per docs, in Form setup, v-model is not used, so it instantly breaks MultiSelect selected labels even with initialValues set, except, again, if you use a placeholder but placeholder is incompatible with FloatLabel as it overlaps.

In my search on devtools I found this `p-multiselect-label-empty` appling `visibility: hidden` on MultiSelect label div.

### Reproducer

https://stackblitz.com/edit/gpxcu9?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

- Access reproducer, placeholder is set and overlapping FloatLabel
- Remove placeholder and select any option, now its broken
- Setting v-model on MultiSelect fix it, but defeats Form usage

----

- Without Form, MultiSelect labels work with v-model
- Without v-model but with placeholder it works again, but overlap FloatLabel

### Expected behavior

Same functionality as MultiSelect FloatLabel example but with Form usage.
No v-model or placeholder hacks.

**Comment by 25Das** [comment]
With more testing I found:

- Leaving or binding an empty placeholder does nothing
- Leaving or binding a space as placeholder breaks component padding
- Dinamically change placeholder to an empty string if form field has some value fix the component interaction behavior, no placeholder is shown and labels appear correctly when respective option is selected

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/6536
