### ISSUE TITLE
Component Name: Select (Autofocus not working as expected on Select component in PrimeVue)

### ISSUE THREAD

**Issue by basitiyidir** [primefaces/primevue#6730]
### Describe the bug

When adding the autofocus attribute to the Select component in PrimeVue, the expected focus behavior does not occur on page load. In contrast, the Input component correctly focuses when autofocus is applied.

<img width="666" alt="pic" src="https://github.com/user-attachments/assets/b7e61387-c83a-49b7-b6d9-85a0762a0ebb">

### Reproducer

https://stackblitz.com/edit/nlblb9-duc3ug?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Add autofocus to the Select component in a PrimeVue project.
2. Load the page and observe that the Select component does not automatically receive focus.
3. Compare with the Input component, where autofocus works as expected.

### Expected behavior

 The Select component should automatically receive focus on page load when the autofocus attribute is set, similar to how it functions with the Input component.

**Comment by tugcekucukoglu** [comment]
Select does not have 'autofocus' property currently. According to more demand, we can consider to add this functionality. Temporary solution: 
```
<template>
    <div>
        <Select ref="selectRef"  />
    </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
const selectRef = ref(null);
onMounted(() => {
    selectRef.value.$refs.focusInput.focus()
})
</script>
```
