### ISSUE TITLE
ToggleSwitch: does not switch visually when selecting Material theme 

### ISSUE THREAD

**Issue by frozzen-git** [primefaces/primevue#6735]
### Describe the bug

This can be seen on your site https://primevue.org/toggleswitch/.
Is it supposed to be?

### Reproducer

 https://primevue.org/toggleswitch/

### PrimeVue version

4.2.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by lan-nguyen91** [comment]
same issue for me, not showing up on Lara theme

**Comment by j0rgedev** [comment]
Hello everyone. This issue was caused due to an inconsistency in a design token from the toggleswitch component. A workaround for this is:
```js
const MyPreset = definePreset(Aura, {
    components: {
        toggleswitch: {
            root: {
                gap: '0px'
            }
        }
    }
});
```
