### ISSUE TITLE
DatePicker: manual input not working

### ISSUE THREAD

**Issue by jzalaya** [primefaces/primevue#6739]
### Describe the bug

The DatePicker default behaviour is manualnput true, which, if I'm understanding correctly, is supposed to allow typing the date with the keyboard. That is not working. Directly in the examples exposed in the documentation happens. 

### Reproducer

https://stackblitz.com/edit/u9znrf-r6br5k?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Try to introduce a date in the datepicker with the manualInput set to true (or not specified, as the default is true)

### Expected behavior

Allow user to introduce the dates manually

**Comment by viniciusNoleto** [comment]
Same issue here 🙋🏻‍♂️

- **Vue:** `3.4.10`
- **Nuxt:** `3.10.2`
- **Primevue:** `4.2.1`
- **Vite:** `5.4.0`

**Comment by liliangeovana** [comment]
Up!

**Comment by Emme243** [comment]
Up!

**Comment by kelvinmarlow** [comment]
Same issue here 🙋🏻‍♂️

    Vue: 3.5.12
    Primevue: 4.2.2
    Vite: 5.4.10

**Comment by KumJungMin** [comment]
after this [PR](https://github.com/primefaces/primevue/commit/79f51434d7873e9826166e5fc21db5c83f083190#diff-05dae630cadea5c6f78d333adc7cfaaa3bb8be1b691b7dd3b75300d48cf12ea7), the input not working :(

([datepicker commit history link](https://github.com/primefaces/primevue/commits/593523bddaa1fc05ed41ad209620a1c627cd14aa/packages/primevue/src/datepicker/DatePicker.vue))

**Comment by KumJungMin** [comment]
If no one is working on fixing this bug, would it be okay for me to fix it? :)

**Comment by eyal-egf** [comment]
I have a requirement for the manual input to work in mobile as well...
does anyone know if this feature is supposed to work or is planned to work for mobile devices?
(currently it does not)

**Comment by Cris200399** [comment]
I fixed it, when I changed the version of primevue, from 4.2.2 to 4.2.5
