### ISSUE TITLE
DataTable: Can't copy text with control + c when Table has selectable rows

### ISSUE THREAD

**Issue by muratyldzxc** [primefaces/primevue#6740]
### Describe the bug

When selecting a row, when i.e. single selection mode is active, you can not copy the content of the cell.
This bug resolved in primevue 3 actually. But primevue 4 doesn't have the solution as I checked the source code. 
The previous PR is [https://github.com/primefaces/primevue/issues/5757](url)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-uymduz?file=src%2FApp.vue

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

When selecting a row, when i.e. single selection mode is active, you can not copy the content of the cell.

### Expected behavior

I should be able to copy content of a cell.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by mrheinen** [comment]
How is this not a defect ? Is there a workaround ?

**Comment by mrheinen** [comment]
I created a PR for this:
https://github.com/primefaces/primevue/pull/7147

Thanks to @nameless on Discord for this support

**Comment by shashank-fm** [comment]
is there any update? is this issue fixed?

**Comment by mrheinen** [comment]
The PR was merged so this should be in the next release.  Would also be
happy to know when that release happens
