### ISSUE TITLE
InputGroup: IconField is not supported in InputGroup

### ISSUE THREAD

**Issue by Sytten** [primefaces/primevue#6743]
### Describe the bug

The following code breaks the `InputGroup`:
```html
<InputGroup>
      <IconField>
        <InputIcon class="pi pi-check" />
        <InputText placeholder="Vote" />
      </IconField>
      <InputGroupAddon>
        <Button icon="pi pi-times" severity="secondary" />
      </InputGroupAddon>
    </InputGroup>
```

### Reproducer

https://stackblitz.com/edit/jxrbaj-vwqhxa?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Should be able to use `IconField` in an `InputGroup` to have an icon inline in the text area.

**Comment by Shadercloud** [comment]
This a still an issue.  When you focus the input (ie click the InputText) the InputIcon disappears.

**Comment by Drumstix42** [comment]
Looks like a z-index issue when the input field is focused.
