### ISSUE TITLE
MultiSelect unable to use chip & chipicon together 

### ISSUE THREAD

**Issue by TomasSimkus** [primefaces/primevue#6744]
### Describe the bug

When using using Multiselect component with with chip & chipicon together its not possible to use them both. The chip and chipicon functionality doesn't work together as expected. it would be helpful if the chip slot had a removeCallback to provide more control over chip removal actions if its not working together...

### Reproducer

https://stackblitz.com/edit/9m9k4r?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Expected behavior

Unable to see close icon while using chip & chipicon together

**Comment by tugcekucukoglu** [comment]
chip slot covers the chipicon slot. We can suggest using chip slot in this case.
