### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by ayii0111** [primefaces/primevue#6746]
### Describe the bug

The `pt` styling is ineffective for certain parts of the `<Tree>` component, such as `nodeLabel`... (it seems to primarily affect the internal `<TreeNode>` elements where the `pt` DOM is ineffective).

However, elements like `wrapper`, which are directly part of the `<Tree>` component's `pt` DOM, are not ineffective.

I've demonstrated this contrast in the example and provided relevant comments.

This is the corresponding pt section from the official website：https://primevue.org/tree/#pt.doc.tree

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-p3acwj?file=src%2FApp.vue,src%2Fservice%2FNodeService.js

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

I've demonstrated this contrast in the example and provided relevant comments.

### Expected behavior

Expectations are to comply with the official usage guidelines：https://primevue.org/tree/#pt.doc.tree

**Comment by tugcekucukoglu** [comment]
Correct usage: 

```  
  :pt="{
      nodeLabel: 'text-red-500'
  }" 
```
