### ISSUE TITLE
ColorPicker: Possibility to write text in <input>

### ISSUE THREAD

**Issue by pdnko** [primefaces/primevue#6748]
### Describe the bug

When <input> is clicked, caret appears and text can be entered

![image](https://github.com/user-attachments/assets/76461937-765b-487e-ad1c-bbed39540849)

### Reproducer

I could not reproduce this in your templates

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior
1. Install by this doc: https://primevue.org/nuxt/
2. Add <ColorPicker> to your template
3. Save the file
4. Click on <ColorPicker> in your browser
5. A pop-up window with colors will appear
6. Try typing something using the keyboard
7. The text will be in a colored rectangle (<input> element)

### Expected behavior

No text should be entered and there should be no flashing cursor (caret)

**Comment by pdnko** [comment]
#6749

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
