### ISSUE TITLE
Vue template does not show typescript error when there is no explicit import on a primevue component

### ISSUE THREAD

**Issue by woahitsjc** [primefaces/primevue#6750]
### Describe the bug

I'm using primevue with typescript. I've got a pretty basic setup for initialising prime vue with the app:

```ts
app.use(PrimeVue, {
        theme: {
            preset: SomeCustomPreset,
            options: {
                darkModeSelector: "",
            }
        }
    });
```

The main issue is that typescript recognises primevue components in typings without explicit importing it. This does not cause any errors in the IDE/build and also does not render the component i.e. a primevue Card.

I don't want to use the autoimport approach because I prefer an explicit import and component.d.ts seems to cause a lot of issues like intellisense and file changes out of sync.

This is my tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": [
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "skipLibCheck": true,
    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "vueCompilerOptions": {
    "strictTemplates": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.vue"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

I would like the error to appear compile time if I do forget to import this explicitly or register it as a global component. Any ideas how I can achieve this?

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-rxeego?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Inspect the `App.vue` and `main.ts` files in stackblitz.

### Expected behavior

Without a global component registered or an explicit import, `Button` should display an error message.

**Comment by Tamas-hi** [comment]
I can confirm this is happening for me as well.

**Comment by tugcekucukoglu** [comment]
How can replicate the issue?
