### ISSUE TITLE
DataTable: expandedRows prop doesn't care if value is false

### ISSUE THREAD

**Issue by CrispinStichartFNSB** [primefaces/primevue#6752]
### Describe the bug

The [documentation](https://primevue.org/datatable/#row_expansion) states this about `expandedRow`:

> Expanded rows can either be an array of row data or when `dataKey` is present, an object whose keys are strings referring to the identifier of the row data and values are booleans to represent the expansion state e.g. `{'1004': true}`

In reality however, the value doesn't matter -- it can be `false` or `null` or anything else, and the row will still be expanded. `DataTable` only cares whether there's a key at all.

Seems like it could just be "fixed" by updating the documentation and making it the intended behavior. 

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-bybahj?file=src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
We'll investigate it. Thanks for your attention.

**Comment by SomeoneIsWorking** [comment]
I have this issue with version 3, it doesn't care if I change expandedRows in runtime (or even before render, it only sends update events, doesn't care about the value I pass).
