### ISSUE TITLE
Component Name: InputNumber does not work on Android devices

### ISSUE THREAD

**Issue by Raudmees** [primefaces/primevue#6766]
### Describe the bug

How it should be: User should be able to delete number value on Android device
How it is: User is not able to delete InputNumber filed value on Android device

I tested on BrowserStack on multiple devices as well as in real device

https://github.com/user-attachments/assets/e38b4a6a-afe0-4134-bbab-25df39cfb73d

### Reproducer

https://stackblitz.com/edit/nuxt-starter-ue7jj9?file=app.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Android

### Steps to reproduce the behavior

1. Open browser on Android device 
2. Use InputNumber field
3. See the bug

### Expected behavior

It should behave same as it was on VuePrime 3.53.0. Version 3.53.0 InputNumber works well on all devices.

**Comment by sivareddyuppathi** [comment]
Assign to me I will work on this.
