### ISSUE TITLE
Select: Design tokens with dt for the overlay are not working

### ISSUE THREAD

**Issue by asmussens** [primefaces/primevue#6781]
### Describe the bug

If I use the `dt` for the design tokens on the select component the overlay is not being styled. The design tokens are not placed on the component.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-em7pwr?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by j0rgedev** [comment]
Hey @asmussens. This also seems an issue to me. However, overriding the `overlay.background` token from the component layer in a custom preset solves this problem. So, as you said, the issue only appears with the scoped tokens. I tried to debug it but with no success 
cc: @tugcekucukoglu
