### ISSUE TITLE
Button: IconPos does not work when custom icon is set

### ISSUE THREAD

**Issue by xiscohv** [primefaces/primevue#6785]
### Describe the bug

When the icon template is used in the button, the prop iconPos does not work

### Reproducer

https://stackblitz.com/edit/qgx1oy?file=index.html,src%2FApp.vue

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

All

### Steps to reproduce the behavior

1.Create a button and add icon template.
2.Add iconPos to "bottom"
 

### Expected behavior

Icon should be placed where the iconPos is set.

**Comment by tugcekucukoglu** [comment]
icon slot provides class also. For example:
```
<Button label="Profile" iconPos="bottom">
            <template #icon="{ class: customClass }">
                <span :class="[customClass, 'pi pi-twitter']" />
            </template>
</Button>
```

**Comment by JustineMiko** [comment]
Thank you so much @xiscohv ! it works like a charm !
