### ISSUE TITLE
documentation: preset theming and css() function positioning within the theme declaration is wrong

### ISSUE THREAD

**Issue by petitkriket** [primefaces/primevue#6790]
### Describe the bug

There is a documented example to inject css when using the Primevue v4 preset.
The documentation example does not work, and I suspect that there is an error in the documentation.

1. 
- [In the extends documentation](https://primevue.org/theming/styled/#extend) at the global preset level
The position of the css property seems wrong in the example. 

```
const MyPreset = definePreset(Lara, {
  components: {
    tag: {
      // inside a component itself, works 🎉 
      css: ({ dt }) => ``,
  },
  // inside the `components:` at the same level of other components like seen in the theme `extend` documentation section ❌
        css: ({ dt }) => `
.p-toggleswitch.p-disabled .p-toggleswitch-slider {
    opacity: ${dt('toggleswitch.my.disabled.opacity')};
}

.p-toggleswitch.p-disabled .p-toggleswitch-handle {
    background: ${dt('toggleswitch.my.checked.disabled.background')};
}
`
    }
});
```
2.
On the other hand, when i place the css property within the `tag` or `button` object itself, it works

The css property has to be within the component itself.- [material theme working example](https://github.com/primefaces/primevue/blob/aec47f4fcb4748f7bd36fe8efa16342c453de3a0/packages/themes/src/presets/material/autocomplete/index.js#L112) at an atomic component preset level.

3.
On the root position of the theme object it seems to work, see [material theme root declaration](https://github.com/primefaces/primevue/blob/aec47f4fcb4748f7bd36fe8efa16342c453de3a0/packages/themes/src/presets/material/index.js#L185). But it's empty so it's unclear.

## Reproduction
a simple [reproduction](https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-vnlfbv)

## Proposition

1. Can you clarify if both or all the 3 uses should be working ?
2. If not, updating the docs could help

### Reproducer

https://github.com/primefaces/primevue/blob/aec47f4fcb4748f7bd36fe8efa16342c453de3a0/packages/themes/src/presets/material/index.js#L185

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. add css customization and or extended Design Token to the theme.
2. inspect the DOM and see that the given properties are not applied

### Expected behavior

1. add css customizations with or without design tokens
2. see that the css is properly injected and enjoy Tags with a thin border.

**Comment by brillz0r** [comment]
> I can't seem to get the `css: ({ dt }) => ...` function to work wherever I put it.

Same for me

**Comment by hisuwh** [comment]
@brillz0r this actually worked for me once I upgraded to the latest version of PrimeVue
