### ISSUE TITLE
Text Button: Disabled state undiscernible

### ISSUE THREAD

**Issue by Mettbrot** [primefaces/primevue#6792]
### Describe the bug

The disabled State is almost not discernible when the Button uses the text style. A Lower opacity should be used there, maybe 0.3 instead of 0.6

Guess which ones are disabled (its the middle two)
![grafik](https://github.com/user-attachments/assets/f097c185-d8ae-4f09-b679-3ecfd06274ac)

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-9bh624

### PrimeVue version

4.2.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

The button disabled opacity should be lower if the button is in text mode.

**Comment by tugcekucukoglu** [comment]
It is a design decision. You could change it with new tokens.
