### ISSUE TITLE
Contribution guide: Incompatibility with Windows

### ISSUE THREAD

**Issue by Tamas-hi** [primefaces/primevue#6794]
### Describe the bug

The _setup_ script inside _package.json_ has the following command:

`rm -rf **/node_modules **/dist ./pnpm-lock.yaml && pnpm install`

Possible solutions:

- disclaimer to docs that UNIX-based OS should be used for contribution
- OS should be taken into account and the respective command should be applied

### Reproducer

-

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
