### ISSUE TITLE
PR Issue: Return Clean Attribute Selector for Node Environments 

### ISSUE THREAD

**Issue by K3TH3R** [primefaces/primevue#6797]
### Describe the bug

I've run into an issue when trying to do snapshot testing with my components using PrimeVue in our unit tests. We use XState for all of our state management, which means our Vue components are almost all "dumb" components that only render specific states based on the props provided to them. This makes them really easy to unit test because all we're testing is basic interactions and their rendering which we capture via the snapshot testing.

However, we've started integrating PrimeVue into our app rebuild, and our snapshot tests are now becoming flakey because of this [$attrSelector in the beforeCreate()](https://github.com/primefaces/primevue/blob/180c921c894f0537767c33b0568754c773caa960/packages/core/src/basecomponent/BaseComponent.vue#L73). Depending on the run order of the unit tests in Vitest, which can vary between runs because of it's multi-threading capabilities, this attribute selector can be a different number on every single run:
<img width="658" alt="Screenshot 2024-11-18 at 3 48 47 pm" src="https://github.com/user-attachments/assets/4da0d0ea-7cbe-4313-9905-559131ed27ed">

We essentially can't use snapshot testing with PrimeVue components unless we manually mock every PrimeVue component when they're used (which is very tedious) or shallowRender every component which is doable but isn't actually an option if you're using Vue Testing Library because they [don't provide shallow render capabilities](https://github.com/testing-library/vue-testing-library/issues/45).

Primarily opening this issue in order to provide documentation for the PR I'm about to open.

### Reproducer

N/A

### PrimeVue version

4.2.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by K3TH3R** [comment]
@tugcekucukoglu Here's the reproduction details:

1. `git clone git@github.com:K3TH3R/ts-issue-starter-template.git`
2. `cd ts-issue-starter-template && git checkout primevue-unit-test-issue && yarn install`
3. `yarn app1:test --watch` and the tests should pass as expected.
4. Open up `apps/app1/src/app/App.spec.ts` in your text editor

## Isolating Tests Breaks Snapshots
If you change this line on line 40:
```ts
it('renders properly #3', async () => {
```
to

```ts
it.only('renders properly #3', async () => {
```
You'll see that the snapshot tests start failing with something like this:
<img width="578" alt="Screenshot 2024-11-19 at 2 24 22 pm" src="https://github.com/user-attachments/assets/e46265cf-1ddd-4770-b4fe-f79996c2d7d0">


## Prepending Tests Breaks Snapshots
Uncomment the lines 14-25 and you'll see that adding new unit tests with snapshots in it breaks any snapshots that come after the new test.

**Comment by tugcekucukoglu** [comment]
Thanks for the explanations. When this https://github.com/primefaces/primevue/issues/6895 issue is solved the problem will be solved. Please track https://github.com/primefaces/primevue/issues/6895
