### ISSUE TITLE
Select: Select Component's content Slots Not Working

### ISSUE THREAD

**Issue by zhangliangying999** [primefaces/primevue#6799]
### Describe the bug

I am having an issue with using the content Slots of the Select component. The expected functionality of populating and customizing the content within the Select dropdown using Slots is not working as intended.

### Reproducer

https://stackblitz.com/edit/2cqyb6?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Navigate to the provided code link: https://stackblitz.com/edit/2cqyb6?file=src%2FApp.vue
2. Examine the code where the Select component is used and the Slots are configured.
3. Try to interact with the Select component and observe that the content Slots do not display or function properly.

### Expected behavior

The content Slots within the Select component should correctly display the custom content and allow for proper interaction and selection within the dropdown.

**Comment by j0rgedev** [comment]
Hello @zhangliangying999. I got your point, and I agree that the purpose of the content slot might not be clear. It seems to be more relevant for customizing the entire structure of the dropdown when using the [virtual scroller](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/select/Select.vue#L111), but maybe someone from the team can help us understand its exact use case.
In the meantime, if your goal is to customize the appearance of the options within the dropdown, the option slot is the way to go.
Example based on the provided repro:
```js
<Select
  v-model="selectedCity"
  :options="cities"
  optionLabel="name"
  placeholder="Select a City"
  class="w-full md:w-56"
  :virtualScrollerOptions="{ itemSize: 38 }"
>
  <template #header>
    <p>header</p>
  </template>
  <template #option="{ option }">
    <span>My Custom Option => {{ option.name }}</span>
  </template>
  <template #footer>
    <p>footer</p>
  </template>
</Select>
```

**Comment by tugcekucukoglu** [comment]
Thanks for the updates, it clears the problem.
