### ISSUE TITLE
Chaining Operator with Vue 3

### ISSUE THREAD

**Issue by chrisnoden** [primefaces/primevue#680]
I am using Vue 3 within a Symfony 5 project.

Some of the PrimeVue 3 components fail to be processed with an error that has been reported in similar use cases on the Forum:

eg:
```
 error  in ./node_modules/primevue/components/datatable/DataTable.vue?vue&type=script&lang=js

Module parse failed: Unexpected token (310:67)
File was processed with these loaders:
 * ./node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
|         if (this.reorderableColumns) {
|             let columnOrder = [];
>             this.columns.forEach(col => columnOrder.push(col.props?.columnKey||col.props?.field));
|             this.d_columnOrder = columnOrder;
|         }
```

The problem seems to be with the Chaining Operator `?.` but I have had no success in trying to get Babel to work with it. Manually editing the primevue component files to the long-hand ternary approach resolves the issue temporarily (until yarn replaces the lib files).

I don't know if vue-loader is unable to work alongside these new TypeScript features - I'm not a JS expert, but I've spent many hours googling and trying various solutions to no avail.

**Comment by onivaldorj** [comment]
I am using PrimeVue 3 within a Symfony 5.2 project, similar result.

**Comment by chrisnoden** [comment]
@onivaldorj You are a superstar. I had seen a few people suggesting to exclude files like this, but didn't know how to take that into the Encore context.
