### ISSUE TITLE
Doc: Persist the state of theme even after refresh.

### ISSUE THREAD

**Issue by sivareddyuppathi** [primefaces/primevue#6808]
### Describe the bug

After changing the theme to dark mode and refresh the screen. After refresh it is going to defaul theme. It is not pesisting the theme state, it is resetting after refresh.
Change the theme by visiting(https://primevue.org/) and refresh it will go to default theme.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/d5af2abd-b6d7-4965-b7bc-7d831aee8f6c">

### Reproducer

https://primevue.org/

### PrimeVue version

4.2.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

After changing the theme to dark mode and refresh the screen. After refresh it is going to defaul theme. It is not pesisting the theme state, it is resetting after refresh.
Change the theme by visiting(https://primevue.org/) and refresh it will go to default theme.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/d5af2abd-b6d7-4965-b7bc-7d831aee8f6c">

### Expected behavior

It should persist the state even after refresh the window.

**Comment by sivareddyuppathi** [comment]
PR: https://github.com/primefaces/primevue/pull/6807

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
