### ISSUE TITLE
Carousel: Item disappear when there is only one item with autoplay and circular activated

### ISSUE THREAD

**Issue by Allenille** [primefaces/primevue#6812]
### Describe the bug

Carousel: Item disappear when there is only one item with autoplay and circular activated

### Reproducer

https://stackblitz.com/edit/evvfnc?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

To reproduce you can take the circular example from here : https://primevue.org/carousel/#circular
Open it in stackblitz and instead of having 9 elements in your list just remove the ither to have only one element to show.
![Capture d’écran 2024-11-19 111356](https://github.com/user-attachments/assets/158e2d31-498d-4930-8744-d02406e700b5)

### Expected behavior

Element should appear and not disappear

**Comment by sivareddyuppathi** [comment]
Hi @Allenille , if you pass `:numVisible="1"` if you have only one element it will work as expected. Let me know if it is not.

` <Carousel
      :value="products"
      :numVisible="1"
      :numScroll="1"
      :responsiveOptions="responsiveOptions"
      circular
      :autoplayInterval="3000"
    >`

**Comment by Allenille** [comment]
Hi @sivareddyuppathi , still have the issue with :numVisible="1" : https://stackblitz.com/edit/evvfnc-vyqemd?file=src%2FApp.vue
As @D4RKAR117 mentioned if I remove the circular prop everything is working fine.
To resolve this I just deactivate circular props when there is less element than the number of element visible but I think that this problem should be handled by the caroussel itself no ?
