### ISSUE TITLE
DatePicker can't input 

### ISSUE THREAD

**Issue by eddydn** [primefaces/primevue#6821]
### Describe the bug

Dear,

I can't input any characters into the DatePicker input. This problem has occurred in versions 4.1.1 and 4.2.2, and it still happens when I check [PrimeVue DatePicker](https://primevue.org/datepicker/).

### Reproducer

https://primevue.org/datepicker/

### PrimeVue version

4.1.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

### Steps to reproduce the behavior

Step:
- Input '1'
- Input '2' => Error.

### Expected behavior

Step:
- Input '1'
- Input '2' => Can input letter '2'

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/6739

**Comment by Div-divine** [comment]
I am also having the same isuue of inputting manually a value into the datePicker on version 4.2, has anyone got a solution ?
