### ISSUE TITLE
KeyFilter: Doesn't seem to be working as expected

### ISSUE THREAD

**Issue by XAllure** [primefaces/primevue#6833]
### Describe the bug

It doesn't seem to be executed as expected. In Chinese mode, you can enter whatever you want.

### Reproducer

暂无

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by XAllure** [comment]
![image](https://github.com/user-attachments/assets/5a410577-2e36-49e7-b188-681302408c02)

**Comment by jongwoo328** [comment]
It seems to be the same issue as [this](https://github.com/primefaces/primevue/issues/6724)

**Comment by tugcekucukoglu** [comment]
Duplicate https://github.com/primefaces/primevue/issues/6724
