### ISSUE TITLE
PanelMenu: same styles for focus-visible and hover

### ISSUE THREAD

**Issue by MasterCarl** [primefaces/primevue#6836]
### Describe the bug

Currently, with the PanelMenu component item/itemcontent, there seems to be no way to define `focus-visible` styles for keyboard-only users that don't also appear on hover.
The Stackblitz example illustrates an attempt to create focus styles by adding conditional classes that depend on `context.focused`. The issue seems to be that after interacting with a `content` section, e.g. by clicking, `mouseenter` events update the `data-p-focused` attribute, possibly to mimic focus styles.

Note that on the PanelMenu header, I was able to achieve distinct `:hover` and `focus-visible` styles by using the respective Tailwind modifiers. On the items, that approach didn't seem to have any effect.
Any help is appreciated!

### Reproducer

https://stackblitz.com/edit/vitejs-vite-niz8gg?file=src%2Fmain.ts

### PrimeVue version

4.1.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Go to the linked example
2. Open any root item, e.g. "files"
3. Use arrow-down and arrow-up to highlight an item. An outline should appear.
4. Use the mouse and hover over the expanded items. The hover styles should be different from the focus styles.

### Expected behavior

The outline should only appear on keyboard navigation, not on mouseover/hover.

Additionally, it should be possible for child nodes to receive focus. Currently, while anywhere under the first root node, the `activeElement` remains `ul#pv_id_1_0_list.p-panelmenu-submenu.p-panelmenu-root-list`.

**Comment by MasterCarl** [comment]
https://github.com/user-attachments/assets/8e7eaf64-58ac-4de1-af81-dd763c6dad6a

Screen recording: Using keyboard to reveal red (`focus-after`) and blue (`context.focused`) outlines, and using the mouse to show hover effects (will remain on exit).

**Comment by tugcekucukoglu** [comment]
PanelMenu is a composed component, so there is no plan to change current behaviours.

Thanks for your suggestions.

**Comment by MasterCarl** [comment]
@tugcekucukoglu Thank you for your comment, but could you please elaborate? Is the intended way of making this component accessible to override the slot and make it focusable using e.g. `tabIndex`? Or is this just not something that is supported by PrimeVue?

**Comment by MasterCarl** [comment]
After digging further, it seems like https://github.com/primefaces/primevue/issues/5130 could solve this accessibility issue. Are you planning to add the focusOnHover prop to further components?
