### ISSUE TITLE
[FEATURE REQUEST] - Avatar Component

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#684]
Element to display avatar image, icon, or initials.

Exampls: [Quasar](https://quasar.dev/vue-components/avatar) and [AntD] (https://2x.antdv.com/components/avatar/).

**Comment by cagataycivici** [comment]
![screely-1606593997221](https://user-images.githubusercontent.com/686247/100525067-9d7a6400-31ce-11eb-8408-896c5c967efc.png)
