### ISSUE TITLE
Password: pcInputText pass through isn't working

### ISSUE THREAD

**Issue by TylerWanta** [primefaces/primevue#6846]
### Describe the bug

I'm trying to use pass through to pass a design token from a Password component to its InputText, but the InputText is not receiving anything being passed to it.

### Reproducer

Templates won't load, even after 15 min :(

### PrimeVue version

4.2.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create Password with pass through to InputText.
2. See that nothing gets set

```
  <FloatLabel variant="in" :dt="floatLabelStyle">
      <Password :pt="{ root: {class: 'test-root', dt: inputStyle}, pcInputText: { class: 'test-input', props: { dt: inputStyle } } }" :dt="inputStyle" :fluid="true" name="password" v-model="inputText" inputId="id" :disabled="disabled" toggleMask @update:model-value="onInput">
          <template #maskicon="slotProps">
              <ion-icon class="pi p-password-toggle-mask-icon" name="eye-off-outline" @click="slotProps.toggleCallback"></ion-icon>
          </template>
          <template #unmaskicon="slotProps">
              <ion-icon v-if="isLocked && showUnlock" class="pi p-password-toggle-mask-icon" name="lock-open-outline" @click="unlock"></ion-icon>
              <ion-icon v-else class="pi p-password-toggle-mask-icon" name="eye-outline"@click="slotProps.toggleCallback"></ion-icon>
          </template>
          <template #content>
              <div></div>
          </template>
      </Password>
      <label for="id">{{ label }}</label>
  </FloatLabel>
```

Image: 
<img width="701" alt="image" src="https://github.com/user-attachments/assets/284ea009-9f3e-45f4-80e9-f99f6ac6d467">

You can see that the root is getting the `test-root` class, but nothing is getting the `test-input` class.

### Expected behavior

The `TextInput` receives the data being passed through to it.

**Comment by TylerWanta** [comment]
Trying to set `dt` of InputText like so also doesn't work

```
<Password
  :pt=" 
  { 
      root: ({state}) => 
      {
          state.unmasked = isUnmasked;
      }, 
      pcInputText:
      { 
          root: ({ instance, props}) => 
          {
              textFieldInstance = instance;
              props.dt = inputStyle;
          },
      } 
  }"
</Password>
```

**Comment by tugcekucukoglu** [comment]
Thanks for the updates.
