### ISSUE TITLE
DynamicDialog : missing "emits" parameter in documentation

### ISSUE THREAD

**Issue by Azoorb** [primefaces/primevue#6851]
### Describe the bug

As mentioned here: : https://github.com/primefaces/primevue/issues/5674#issuecomment-2092623987, the emits parameter is missing from the documentation. If events are not declared within the emits key, they won't work.

### Reproducer

https://stackblitz.com/edit/mkfekr-utlr3a?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
We want to share the type definition file for DynamicDialog: https://github.com/primefaces/primevue/blob/master/packages/primevue/src/dynamicdialogoptions/DynamicDialogOptions.d.ts#L67

Duplicate: https://github.com/primefaces/primevue/issues/5674
