### ISSUE TITLE
Virtual Scroller/DataTable: Rows unreasonably tall when rows < itemSize and data table is scrollable

### ISSUE THREAD

**Issue by DMDoom** [primefaces/primevue#6853]
### Describe the bug

When the number of rows in a DataTable is smaller than Virtual Scroller's itemSize, rows begin to take more space than necessary, becoming unreasonably vertically tall. This only occurs when scrollable (and scrollHeight) is defined by the DataTable. If it's not, the rows take the correct amount of space. VirtualScrollers autoSize and DataTable's size properties are ignored.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-633k7e?file=src%2FApp.vue

### PrimeVue version

4.0.0-rc.3 / 4.2.3

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to reproduction project's App.vue
2. Change itemSize to 3, the rows display correctly
3. Change itemSize back to 300
4. The rows have now become unnecessarily tall

### Expected behavior

The rows should always take only as much vertical space as required and should not ignore DataTable's size property.

**Comment by tugcekucukoglu** [comment]
Since the value size is smaller than the itemSize, it caused a visual problem in this demo. Since VirtualScroll does its own calculations, it is necessary to give an appropriate itemSize.
