### ISSUE TITLE
Filter of Select doesn't Filter the Turkish Words with Capital Letters

### ISSUE THREAD

**Issue by gunerfurkanilker** [primefaces/primevue#6856]
### Describe the bug

Select component filter field cannot filter Turkish words such as İstanbul, İzmir, Şanlıurfa etc.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-rpfsxr?file=src%2FApp.vue

### PrimeVue version

4.2.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 131.0.6778.86 

### Steps to reproduce the behavior

1. Click the selectbox whick includes Turkish characters word list
2. Try to filter that list with lowercase letters example i,ü,ö
3. You're going to see filter is not filtering the list

### Expected behavior

Select filter should filter the list that words includes Turkish characters

**Comment by tugcekucukoglu** [comment]
Please send a valid link.

**Comment by gunerfurkanilker** [comment]
I updated link.
