### ISSUE TITLE
Component Name: Issue Title

### ISSUE THREAD

**Issue by tomaszpuzio** [primefaces/primevue#6858]
### Describe the bug

filterModel and filterCallback parameters from a Column component are undefined when used together with TreeTable

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-oyz9ta?file=src%2FApp.vue,src%2Fservice%2FNodeService.js

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

In the Reproducer I put @input event handler on type filter and there I console log filterModel and filterCallback. In the inspector both return undefined.

### Expected behavior

filterModel and filterCallback should return corresponding parameters (same as when a Column component is used with DataTable component and as defined in the docks - see https://primevue.org/treetable/#api.column.slots.filter)

**Comment by tugcekucukoglu** [comment]
The API you mentioned is valid for DataTable, not TreeTable. So we can close this issue.

**Comment by tomaszpuzio** [comment]
@tugcekucukoglu Thanks for such a fast response! Shouldn't then the documentation be updated? Currently it looks like it is possible - https://primevue.org/treetable/#api.column.slots.filter
