### ISSUE TITLE
Popover: Can't access correct slotProps data from a Table row

### ISSUE THREAD

**Issue by rcarnevale** [primefaces/primevue#6863]
### Describe the bug

When I try to get slotProps from a Table row inside a Popover it only give me the last row data even in the previous ones.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-ufpzyk?file=src%2FApp.vue

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

In my example you just need to open the popover and see that all rows will show the last row code

### Expected behavior

Popover should use proper slotProp data for the row.

**Comment by tugcekucukoglu** [comment]
In such cases, it is necessary to send parameters: https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-aes7gj?file=src%2FApp.vue
