### ISSUE TITLE
InputText: Missing attributes such as placeholder.

### ISSUE THREAD

**Issue by XAllure** [primefaces/primevue#6867]
### Describe the bug

Property 'placeholder' does not exist on type 'IntrinsicAttributes & InputTextProps & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
![image](https://github.com/user-attachments/assets/3219877c-9233-4f8c-ab29-ecb14c5458f5)

### Reproducer

nothing

### PrimeVue version

4.2.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by j0rgedev** [comment]
Hello @XAllure. Could you please share a minimal reproduction?
