### ISSUE TITLE
Missing CSS files in PrimeVue package (themes and resources)

### ISSUE THREAD

**Issue by majdjihad** [primefaces/primevue#6869]
### Describe the bug

I encountered an issue while trying to use PrimeVue in my Nuxt project. The required CSS files, such as theme files and PrimeVue resources, are missing from the installed package. Specifically, the following paths are not found after installing primevue and adding configuration for the config file I tried the CDN links but they don't work:

file is missing:

- node_modules/primevue/resources/themes/saga-blue/theme.css

- node_modules/primevue/resources/primevue.min.css

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template?file=README.md

### PrimeVue version

4.2.3

### Vue version

4.x

### Language

ALL

### Build / Runtime

Nuxt

**Comment by j0rgedev** [comment]
Hello @majdjihad. The reproduction provided isn't from a nuxt project. Could you please update it?

**Comment by majdjihad** [comment]
> Hello @majdjihad. The reproduction provided isn't from a nuxt project. Could you please update it?

@j0rgedev The issue is that the files related to the style are not loaded, not the code.

**Comment by j0rgedev** [comment]
@majdjihad you shouldn't create a plugin and import those old css files which are from v3 and not v4. To use PrimeVue V4 in nuxt, please read here https://primevue.org/nuxt/#theme

**Comment by majdjihad** [comment]
> @j0rgedev ,The issue has been solved thank you for helping me.

**Comment by majdjihad** [comment]
>> @mertsincan ,The issue has been solved thank you for helping me.
