### ISSUE TITLE
[FEATURE REQUEST] - PopOver Component

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#687]
Similar to a tooltip, but allowing for more enhanced display.

Example: [AntD](https://2x.antdv.com/components/popover/).

**Comment by cagataycivici** [comment]
Isn't this OverlayPanel?

https://primefaces.org/primevue/showcase/#/overlaypanel

**Comment by JoseGoncalves** [comment]
I am looking to something similar, i.e., a component that would allow to generate tooltips with elaborate content (not only text).

Looking into the OverLayPanel showcase, it lacks tthe flexibility to positon on top/left/right and can not (at least in a simple way) show the overlay when hovering an element.

Please consider adding a Popover component to PrimeVue with a similar functionality as this one:

https://bootstrap-vue.org/docs/components/popover
