### ISSUE TITLE
usePrimeVue() throws "Error: PrimeVue is not installed!"

### ISSUE THREAD

**Issue by Abouhassane** [primefaces/primevue#6872]
### Describe the bug

I'm trying to change localization/language, which requires to use `usePrimeVue()`, but it throws this error 👇 

```
primevue_config.js?v=0af5ea85:221 Uncaught (in promise) Error: PrimeVue is not installed!
    at usePrimeVue (primevue_config.js?v=0af5ea85:221:11)
    at changePrimeLocaleIssue (App.vue:26:22)
    at callWithErrorHandling (chunk-U3LI7FBV.js?v=0af5ea85:2263:19)
    at callWithAsyncErrorHandling (chunk-U3LI7FBV.js?v=0af5ea85:2270:17)
    at HTMLButtonElement.invoker (chunk-U3LI7FBV.js?v=0af5ea85:11202:5)
```

The error is caused by using usePrimeVue(). the only workaround i found to make the localization work is this 👇 
Using `$primevue` within the app context

```js
import { usePrimeVue } from "primevue/config";
import { getCurrentInstance } from 'vue'

const instance = getCurrentInstance()

// const primevue = usePrimeVue(); // This throws an error
const primevue = instance?.appContext.config.globalProperties.$primevue;
primevue.config.locale = await getLocale(); // workaround
```

### Reproducer

https://stackblitz.com/edit/primevue-3-use-prime-vue-issue-template-6kyd4h?file=src%2FApp.vue

### PrimeVue version

4.2.3

### Vue version

3.5.13

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 130.0.6723.117

### Steps to reproduce the behavior

1. Open the stackblitz link
2. Click on `Click me to reproduce issue`

### Expected behavior

There should be no error when I change language, which uses `usePrimeVue()`.

**Comment by tugcekucukoglu** [comment]
Thanks for the reproducer. It's known Vue bug but there is a workaround.

```
const $primevue = usePrimeVue();
defineExpose({
  $primevue,
});
```

Also, I've updated your demo: https://stackblitz.com/edit/primevue-3-use-prime-vue-issue-template-6kyd4h-klb8aj5i?file=src%2FApp.vue

**Comment by devmadhavv** [comment]
For user using Nuxt js v3, create a plugin file `primevue.client.ts` and register your primevue services
```
import ConfirmationService from 'primevue/confirmationservice';
import ToastService from 'primevue/toastservice';
import PrimeVueConfig from 'primevue/config';  // <----------- this here

export default defineNuxtPlugin((nuxtApp) => {
  // Register PrimeVue services needed by useConfirm() and useToast()
  nuxtApp.vueApp.use(ToastService);
  nuxtApp.vueApp.use(ConfirmationService);
  nuxtApp.vueApp.use(PrimeVueConfig);  // <----------- this here
});
```
