### ISSUE TITLE
PrimeVueResolver prefix does not work

### ISSUE THREAD

**Issue by jongbonga** [primefaces/primevue#6875]
### Describe the bug

When using `PrimeVueResolver({ components: { prefix: 'p-' } })` the components are not working anymore or they lose their styles.

I cannot use `p-button` or `p-select` etc

### Reproducer

https://stackblitz.com/edit/vitejs-vite-jxvnlf?file=src%2FApp.vue

### PrimeVue version

4.2.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
To use prefix: `@primevue/auto-import-resolver` should installed and added to main.js.

**Comment by xiehaibin18** [comment]
Try this！

vite.config.js

```
...
Components({
  resolvers: [
    {
      type: "component",
      resolve: (name) => {
        if (name.startsWith("V")) {
          return PrimeVueResolver()
            .find(({ type }) => type === "component")
            .resolve(name.slice(1));
        }
        return null;
      },
    },
  ],
}),
...
```

test.vue

```
...
<v-button>test</v-button>
...
```

**Comment by ilyaliao** [comment]
Try this:

```
Components({
  resolvers: [PrimeVueResolver({
    components:{
      prefix: 'P'
    }
  })],
})
```

<img width="569" height="158" alt="Image" src="https://github.com/user-attachments/assets/b13a94cf-7d8d-4041-a743-d5519b5820b8" />
