### ISSUE TITLE
ScrollTop: global passthrough options not working

### ISSUE THREAD

**Issue by ali-418** [primefaces/primevue#6876]
### Describe the bug

I tried using global passthrough to add classes to the ScrollTop component but they aren't being applied. Instead, the classes defined in the global passthrough for the Button component are being applied. 

Passing the passthrough options directly to the ScrollTop component works.

### Reproducer

https://stackblitz.com/edit/nuxt-starter-qtuns2

### PrimeVue version

4.2.3

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Go to the reproducer. There is a Button component at the top of the page and a ScrollTop component at the bottom.
2. Scroll down to the bottom of the page
3. The ScrollTop button is blue when it should be pink as defined in `passthrough/scrolltop/index.js`

### Expected behavior

The options defined in the global passthrough file are applied to the ScrollTop component

**Comment by tugcekucukoglu** [comment]
Correct implementation 
```
 <ScrollTop
            :pt="{
                root: '!bg-pink-400',
            }"
        />
 ```

**Comment by ali-418** [comment]
Setting `/passthrough/scrolltop/index.js` to that still does not work
```
export default {
  root: '!bg-pink-400',
};
```
Is there no ScrollTop support for global passthrough ?

**Comment by ali-418** [comment]
@tugcekucukoglu can this issue be reopened?

**Comment by nneto** [comment]
> Correct implementation
> 
> ```
>  <ScrollTop
>             :pt="{
>                 root: '!bg-pink-400',
>             }"
>         />
> ```

But the issue is about setting it globally.
