### ISSUE TITLE
[FEATURE REQUEST] - Stats Component

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#688]
Display statistical data, including up/donw indicators.

Example: [AntD](https://2x.antdv.com/components/statistic/).

**Comment by cagataycivici** [comment]
I think this would be too opiniated for a component and we already cover this with different designs with our dashboards.
<img width="1274" alt="Screen Shot 2020-12-09 at 16 07 54" src="https://user-images.githubusercontent.com/686247/101633814-dfaa6d80-3a38-11eb-80aa-ec924e3df8bb.png">
<img width="1452" alt="Screen Shot 2020-12-09 at 16 08 14" src="https://user-images.githubusercontent.com/686247/101633818-e20cc780-3a38-11eb-952b-b5b7e8f2c3c7.png">
<img width="1395" alt="Screen Shot 2020-12-09 at 16 08 23" src="https://user-images.githubusercontent.com/686247/101633824-e2a55e00-3a38-11eb-9fae-a5422fb21939.png">
