### ISSUE TITLE
Design tokens for the toolbar are not considered in the image component

### ISSUE THREAD

**Issue by Christian-Lange-ext-deka** [primefaces/primevue#6881]
### Describe the bug

I tried to change the design of the toolbar with design tokens. And it had no effect.

Could be connected with https://github.com/primefaces/primevue/issues/6129  but is still an issue.

### Reproducer

https://stackblitz.com/edit/tsjkwu-gmo5r4?file=src%2FApp.vue

### PrimeVue version

4.1.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. go to https://primevue.org/image/#preview
2. open stackblitz https://stackblitz.com/run?file=src%2FApp.vue
3. add tokens to Image 
``` :dt="{
        colorScheme: {
          light: {
            preview: {
              mask: {
                color: 'red',
                background: 'blue',
              },
            },
            toolbar: {
              background: 'orange',
              borderColor: 'orange',
              borderRadius: '0',
            },
          },
        },
      }"
```
4. Tokens on preview have an effect, tokens on toolbar have no effect

### Expected behavior

all design-tokens should be used

**Comment by tugcekucukoglu** [comment]
Please track this ticket: https://github.com/primefaces/primevue/issues/6895
