### ISSUE TITLE
FloatLabel is broken since Primevue 4.1.0

### ISSUE THREAD

**Issue by NicolasMelin** [primefaces/primevue#6882]
Hello,

FloatLabel is broken since Primevue `4.1.0` :

![image](https://github.com/user-attachments/assets/b2c6282e-e3cc-4faf-86dd-6fbf1675fdcd)

With Primevue `4.0.7` :
![image](https://github.com/user-attachments/assets/610bbcce-502b-46b8-84ae-135e3688c4af)

My code example :

```
<template>
  <div class="card flex justify-center mt-4">
      <FloatLabel>
          <InputText id="username" v-model="value" />
          <label for="username">Username</label>
      </FloatLabel>
  </div>
</template>
```

Thanks by advance for your help.

Regards

**Comment by 25Das** [comment]
For me this is intermittent sometimes it loads broken sometimes it loads correctly, some pages this does not occur in others occur intermittently

**Comment by Abassion** [comment]
Would it be possible to share a minimal reproducible example using tools like [Stackblitz](https://stackblitz.com/)?

**Comment by 25Das** [comment]
I don't know whats the cause but it is still happening on 4.2.4.

In my use case it breaks on a page specifically then it spreads breaking all Primevue float labels across the whole app then when I refresh the application it starts breaking other Primevue component stylization, I need to close dev server to fix it.

I don't saw happens on production yet.

I am using Nuxt and it broke when I navigate in and Nuxt started optimizing checkbox component

`✨ new dependencies optimized: primevue/checkbox`
`✨ optimized dependencies changed. reloading `

Maybe this is not correlated except for the sudden interruption succeeded by reloading

**Comment by tugcekucukoglu** [comment]
Cannot replicate: https://primevue.org/floatlabel
Please try to remove node_modules and package-lock.json. They could be outdated.

**Comment by NicolasMelin** [comment]
I have found my error and it's was to not have updated the `@primevue/themes` module... -_-"

**Comment by Kemboi-Dun** [comment]
Had an issue with **IftaLabel** and **FloatLabel**
## FIX
Updated primevue to the latest version [**primevue@4.2.5** at the writting of this comment] and removed the outdated `package-lock.json` and `node_modules`.
