### ISSUE TITLE
DataTable - Column: Filter Menu Button Behavior Change

### ISSUE THREAD

**Issue by EmreAka** [primefaces/primevue#6887]
### Describe the bug

Hi, 

In PrimeVue V3, PrimeReact and PrimeNG Libraries, when you Apply filter, the background color of filter menu button changes. 
![{013CF450-B13D-48F8-8057-2B1F208EB5EF}](https://github.com/user-attachments/assets/4fe7a8be-9e05-4de5-9b1a-9285bb731a61)
source: https://v3.primevue.org/datatable/#advanced_filter

But In PrimeVue V4, it does not. 
![image](https://github.com/user-attachments/assets/c03f194e-b139-478c-9993-44d1dfa79a84)
source: https://primevue.org/datatable/#advanced_filter

### Reproducer

https://primevue.org/datatable/#advanced_filter

### PrimeVue version

latest

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Steps to reproduce the behavior

1. Go to the documentation for both V3 and V4.
2. Go to DataTable component.
3. Find Advance Filters example.
4. Apply filter for one of the columns.

### Expected behavior

I want the button in the header that opens filter menu to be highlighted (background color and color change) as in PrimeVue v3 and PrimeReactand PrimeNG. Thank you.

**Comment by tugcekucukoglu** [comment]
It is a design decision.

Thank you.
