### ISSUE TITLE
InputNumber: Not allowed to start the decimal with DOT(.) or COMMA(,)

### ISSUE THREAD

**Issue by stephanestermann** [primefaces/primevue#6888]
### Describe the bug

Users want to input a decimal number, which start with zero, with the decimal character
Examples: 0.5 => .5 / 0,5 => ,5

### Reproducer

https://v3.primevue.org/inputnumber/

### PrimeVue version

3.53.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

1. Type ,5
2. The text in the inputbox is 5,00

### Expected behavior

The text in the inputbox should be: 0,5

**Comment by tugcekucukoglu** [comment]
InputNumber uses Intl.NumberFormat internally. It is an API behavior.
