### ISSUE TITLE
Skeleton Component

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#689]
Displaying a placeholder until content loads.

Examples: [Quasar](https://quasar.dev/vue-components/skeleton) and [AntD](https://2x.antdv.com/components/skeleton).

**Comment by cagataycivici** [comment]
Set to 3.0.3

**Comment by dheimoz** [comment]
Seems that ver 3.0.3 will be awesome @cagataycivici Thanks for the great efforts!!!!
