### ISSUE TITLE
Component Name: Tab

### ISSUE THREAD

**Issue by kylefarris** [primefaces/primevue#6903]
### Describe the bug

For the `@update:value` event of the `Tabs` component (v4), the documentation (https://primevue.org/tabs/#api.tabs.emits) says that the value provided to the event handler can be either a `string` or `number` but Typescript is complaining saying that the value must be a `number`. 

I took a look at the source to see if i could just patch the typing issue somewhere and submit a PR but after an earnest 15-20 minutes of looking I couldn't quite figure out where that's being defined.

Obviously this isn't a huge issue but should be a fairly easy (if you know the codebase well 😅) low-hanging fruit to patch.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-ub6lrx?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Load the code into VS Code and `ts-checker` should show an error in the code editor.

### Expected behavior

No type error should be detected since it should emit with a parameter that can be either a `string` or `number`.

**Comment by tugcekucukoglu** [comment]
Please try to use version 4.2.4. It seems the problem is solved with earlier versions.
