### ISSUE TITLE
DataTable: RowExpansion & RowSelection 

### ISSUE THREAD

**Issue by Azalen** [primefaces/primevue#6904]
### Describe the bug

When I use an outer DataTable with Row Expansion and an inner DataTable and I want the inner DataTable be use RowSelection (single mode) the Fokus breaks. After this I cannot access the inner DataTable anymore via Keyboard Tabbing.

You can see this issue live in action in here by opening a Row Expansion and then click on the outer DataTables row (the row you just used for expansion) 

https://stackblitz.com/edit/lwvsx7?file=src%2FApp.vue

```bash
chunk-VT7FWPCL.js?v=073310a7:2351 Uncaught TypeError: Cannot set properties of null (setting 'tabIndex')
    at Proxy.onRowClick2 (primevue_datatable.js?v=5caf848d:12067:28)
```

### Reproducer

https://stackblitz.com/edit/lwvsx7?file=src%2FApp.vue

### PrimeVue version

4.2.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

opening a Row Expansion and then click on the outer DataTables row (the row you just used for expansion)  on some empty space

### Expected behavior

Fokus and thus the ability to access the inner DataTable via Keyboard should not break

**Comment by KumJungMin** [comment]
I submitted a PR to resolve the error message. Are you looking to address the error message, or is your focus more on fixing the tab navigation issue?

@Azalen

**Comment by Azalen** [comment]
Tab Navigation Issue, because functionality breaks
