### ISSUE TITLE
Multiselect: Cannot read properties of undefined (reading '$el')

### ISSUE THREAD

**Issue by markokos01** [primefaces/primevue#6909]
### Describe the bug

When using the Multiselect component and setting `filter` to `false`, an error occurs:

`Cannot read properties of undefined (reading '$el')`

### PrimeVue version

4.2.4

### Vue version

3.x

**Comment by Winter979** [comment]
Example

https://stackblitz.com/edit/primevue-4-vite-issue-template-83lttnl5?file=src%2FApp.vue

**Comment by Winter979** [comment]
![image](https://github.com/user-attachments/assets/082d8c11-5b7e-4f1e-84fa-f424b3fb0bbe)

Unless im missing something here (please correct me if i am). I feel that this code is redundant since its trying to focus on an element that just got de-rendered by the outsideClickListener

**Comment by anuzpandey** [comment]
I too have the same error when `autoFilterFocus` is enabled.

**Comment by anexis-fabianamhof** [comment]
This issue still exists in PrimeVue 4.2.5
