### ISSUE TITLE
InputNumber: Odd Behavior Trying to make a number negative

### ISSUE THREAD

**Issue by ck-pando** [primefaces/primevue#6913]
### Describe the bug

When I have an InputNumber element with currency enabled. If there is already a positive value in the input and I want to make it negative, I need to delete the entire value of the input before making it negative. This behavior is not intuitive.

### Reproducer

https://primevue.org/inputnumber/#currency

### PrimeVue version

4.*.*

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to the PrimeVue website example of Input Number Currency: [PrimeVue](https://primevue.org/inputnumber/#currency)
2. For the `United States` example, attempt to directly make the value negative by doing any of: 
- Clicking in front of the `$` and typing `-`
- Clicking immediately after the `$` and typing `-`, 
- Using arrow keys to go to the start of the value and typing `-`

### Expected behavior

I would expect as a user to be able to put my cursor in front of the number or currency and add a `-` to make it negative.

**Comment by tugcekucukoglu** [comment]
InputNumber was built on certain standards. Therefore, there is a usage as you have listed above. The usage you currently suggest is not on the roadmap.

Thanks for your understanding.
