### ISSUE TITLE
Button: Missing Design Tokens For Disabled States

### ISSUE THREAD

**Issue by haiderchristoph** [primefaces/primevue#6917]
### Describe the bug

I'm wondering how to modify disabled button styles. According to the [official documentation](https://primevue.org/button/) there are no design tokens for disabled states at all? What's the primevue v4 intended way to tackle this? Are we supposed to override `.p-button:hover`? How could I differentiate between primary, secondary, ... buttons and their respective disabled styles.

No reproducer attached, as there's nothing to reproduce.

### Reproducer

asdf

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
There is `disabled.opacity` token for all components. Closing due to that is a design decision.
