### ISSUE TITLE
Calendar: Manual date input when time picker is included

### ISSUE THREAD

**Issue by sanjogs** [primefaces/primevue#6919]
### Describe the bug

When time picker is enabled for the calendar component, if we manually input a date , the input is ignored. Manual date input only works when time part is included too. Also the time needs to be included in specific format including the spaces. Is there a way to have the calendar automatically populate current time or start of day (12:00 am) when user only inputs the date part?

### Reproducer

https://stackblitz.com/edit/primevue-3-vite-issue-template-pymr6i?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue

### PrimeVue version

3.53.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the included stack blitz reproducer
2. I have included calendar component with date picker only and another one which incldes both date and time picker
3. Manual date input works fine on the date picker, but doesn't work on the date and time picker

### Expected behavior

When user doesn't input a particular time, then it probably makes sense to automatically set time to start of the day (12:00 AM).

**Comment by tugcekucukoglu** [comment]
Please track https://github.com/primefaces/primevue/issues/6739
