### ISSUE TITLE
VirtualScroller Component

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue#692]
Component to dynamically load data, as the user scrolls the container.

Example: [Quasar](https://quasar.dev/vue-components/infinite-scroll).

**Comment by dheimoz** [comment]
Hello @go4cas I wonder if DefferedContent suit your needs? https://primefaces.org/primevue/showcase/#/deferredcontent

**Comment by cagataycivici** [comment]
This is planned for 3.2.0, already available in PrimeNG;

https://primefaces.org/primeng/showcase/#/virtualscroller

**Comment by LadislavBohm** [comment]
> Hello @go4cas I wonder if DefferedContent suit your needs? https://primefaces.org/primevue/showcase/#/deferredcontent

I don't think so as I don't see a way to use this in a table component. Perhaps you would have to wrap every row in DeferredContent and check if it's the last one but it doesn't seem like a good way to do it. If you have an example on how to use it in this scenario it would be nice.

**Comment by go4cas** [comment]
Hi @LadislavBohm, yes the lazy load feature of the `virtualscroller` component from primng is what I am looking fo, but fo vue.js. It would be ideal if this could work on table;es as well.

**Comment by cagataycivici** [comment]
@mertsincan is currently working on it. This one is on the top of our todo list.
