### ISSUE TITLE
DatePicker: manul input doesn't work

### ISSUE THREAD

**Issue by ndovnar** [primefaces/primevue#6923]
### Describe the bug

It's impossible to enter value even if manualInput prop is true

### Reproducer

https://stackblitz.com/edit/j4a6ha?file=src%2FApp.vue

### PrimeVue version

4.x

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. setup datepicker component
2. focus input and try to enter value manually 
3. verify that it doesn't work

### Expected behavior

Manual input should work

**Comment by muelbr** [comment]
Introduced with Primevue-Version 4.2.0 (4.1.1 works properly).

Kind regards

**Comment by tugcekucukoglu** [comment]
Please track https://github.com/primefaces/primevue/issues/6739
