### ISSUE TITLE
Issue of tailwind with dark style 

### ISSUE THREAD

**Issue by johison** [primefaces/primevue#6929]
### Describe the bug

const rowClass = (data : any) => {
    return [{ 
        '!text-gray-300 !dark:text-gray-700': data.attivo === false || data.attiva === false
    }];
}; i have a problem with this class that is not applied, when it is in light mode work, it works but when it is in dark mode it does not work the applied class, it seems that does not load correctly all tailwind classes...

### Reproducer

gug

### PrimeVue version

4.2.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

iui

### Steps to reproduce the behavior

hh

### Expected behavior

i expect that the dark mode classes should be applied

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).

**Comment by andrescellini** [comment]
same problem, te class seems to be there, but has not effect. Any workarround?

**Comment by andrescellini** [comment]
the problem was wrong sintaxis with the !

@johison insted of `!dark:text-gray-700` try `dark:!text-gray-700`
