### ISSUE TITLE
TreeTable: Row selected on click at node toggle icon

### ISSUE THREAD

**Issue by KriXPello** [primefaces/primevue#6932]
### Describe the bug

TreeTable toggles selection when clicked exactly on expand icon (when clicked directly on button works fine). Here is example:

![treetable_bug](https://github.com/user-attachments/assets/5ea1daaa-053c-477a-b922-66c29f1a87ac)

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-fz8jucim

### PrimeVue version

4.2.4

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open my stackblitz link
2. Click on any expandable TreeTable row to select it like so:
![image](https://github.com/user-attachments/assets/3968816a-075c-4975-8fca-1d6320553418)
3. Click on expand icon in different places until it remove selection. In my case i was able to toggle selection by click there:
![image](https://github.com/user-attachments/assets/5129b4d7-bb64-4414-9a4c-ae828ed31b2e)

### Expected behavior

When you click on a button or icon in that button, the row should expand without selection.

I was able to find that problem is in `packages\primevue\src\treetable\TreeTableRow.vue` in `onClick` method:

```js
onClick(event) {
    // problem here
    if (isClickable(event.target) || getAttribute(event.target, 'data-pc-section') === 'nodetogglebutton' || getAttribute(event.target, 'data-pc-section') === 'rowtoggleicon' || event.target.tagName === 'path') {
        return;
    }

    this.setTabIndexForSelectionMode(event, this.nodeTouched);

    this.$emit('node-click', {
        originalEvent: event,
        nodeTouched: this.nodeTouched,
        node: this.node
    });
    this.nodeTouched = false;
}
```

Need to add `|| getAttribute(event.target, 'data-pc-section') === 'nodetoggleicon'` check, because icon has attribute `data-pc-section="nodetoggleicon"`, not the `rowtoggleicon`

**Comment by KriXPello** [comment]
for thoose who don't want to wait, there are temporary solution:
in entry file of your Vue application (with `const app = createApp(App);`) write:
```
const originalGetAttribute = Element.prototype.getAttribute;
Element.prototype.getAttribute = function (name) {
  const realValue = originalGetAttribute.call(this, name);
  if (name === 'data-pc-section' && realValue == 'nodetoggleicon') {
    return 'rowtoggleicon';
  }
  return realValue;
};
```

**Comment by peter-360ag** [comment]
You can also use a template with expandedKeys for this:
```
const expandedTreeNodes = ref({});
```

```
const toggleNode = (node) => {
    expandedTreeNodes.value[node.key] = !expandedTreeNodes.value[node.key];
};
```


```
<TreeTable
    v-model:expandedKeys="expandedTreeNodes">
    <Column field="name" :row-editor="true"  expander>
          <template #body="scopeData">
              <div class="flex justify-between w-full mt-2" @click="toggleNode(scopeData.node)">
                  <div>some data</div>
              </div>
          </template>
    </Column>
</TreeTable>
```
