### ISSUE TITLE
`BodyRow` option to render plain `td` instead of `BodyCell`.

### ISSUE THREAD

**Issue by TylerWanta** [primefaces/primevue#6935]
### Describe the bug

I'm having some major performance issues with the `DataTable` on older devices. It looks like each `BodyCell` is taking around `4ms` to fully render, which is pretty bad. Since 99% of my table cells only render plain text, I was going to just add a flag to `Column` to skip rendering the `BodyCell` and just place a raw `td` instead.

 I'm trying to fork and publish the repo in order to try to more easily debug and test this but when running `pnpm build` under `packages/primevue/`, no `dist` folder is created to publish. There are no errors in the console, the command finishes, and I am trying this on Windows. 

Is this expected or am I building this wrong? If I am building this wrong, can you provide some quick steps on how to properly build and publish the package to npm under my own package? 

Thanks

### Reproducer

h

### PrimeVue version

4.2.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Navigate to `packages/primeveu` and run `pnpm build`

### Expected behavior

A `dist` folder would be created in the same directory.

**Comment by tugcekucukoglu** [comment]
We may not be able to help you because we do not know your setup. You can prepare a repo and share it on Discord or Discussions.
