### ISSUE TITLE
TreeTable: Node unexpectedly gets selected when I expand it

### ISSUE THREAD

**Issue by moduly-solutions-slechner** [primefaces/primevue#6936]
### Describe the bug

In the TreeTable Component, when I expand a row, in some cases the parent node gets selected (and therefore the @node-select event gets fired).  I spent some time to reproduce this issue and after a while I found out, that this only happens, if the expansion action is done by clicking somewhere on the round expansion button/area (defined by "expander" tag on a Column) outside the "down-arrow" icon. So I feel like the issue is that the selection event is not properly bind to the whole click area, but only the icon itself. (See stackblitz)

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-fmv9y7dc?file=src%2FApp.vue

### PrimeVue version

4.2.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Make a simple TreeTable with parent and child node and try to expand and collapse the child node. Check with @node-select when a selection is triggered and you will see that sometimes, expansion triggers it.

### Expected behavior

On expansion, I don't expect the parent node to be marked as selected.

**Comment by moduly-solutions-slechner** [comment]
Oh, I've just seen that this issue is also explained here: #6932

**Comment by KriXPello** [comment]
@moduly-solutions-slechner i can suggest temporary solution:

```js
const originalGetAttribute = Element.prototype.getAttribute;
Element.prototype.getAttribute = function (name) {
  const realValue = originalGetAttribute.call(this, name);
  if (name === 'data-pc-section' && realValue == 'nodetoggleicon') {
    return 'rowtoggleicon';
  }
  return realValue;
};
```

**Comment by moduly-solutions-slechner** [comment]
@KriXPello cheers mate, works fine :)
