### ISSUE TITLE
Megamenu: Unstyled mode includes styles

### ISSUE THREAD

**Issue by jacksonrya** [primefaces/primevue#6938]
### Describe the bug

Despite using unstyled mode, a style attribute is included on the 'rootList' `<ul>` tag.

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-xydtgdbu?file=src%2FApp.vue

### PrimeVue version

4.2.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. View stackblitz
2. Notice the extracted style attribute in the description.
3. Notice the use of `unstyled` in source.

### Expected behavior

That no styles would be added to any elements when using unstyled mode.

**Comment by tugcekucukoglu** [comment]
Styles added as a result of calculations from JavaScript are not removed with unstyled mode because it is not possible for the user to calculate them in styled mode.

Thank you.

**Comment by d-akourou** [comment]
I was also using the megamenu component and I updated to a version after 4.1.0 where these inline styles were added, as fix to this [issue](https://github.com/primefaces/primevue/issues/6578).   
I'm using unstyled as well.
These inline styles are causing issues in the desktop version. Is is something that you are planning to address in the future?
