### ISSUE TITLE
Tree component

### ISSUE THREAD

**Issue by AlexBindevald** [primefaces/primevue#6940]
### Describe the bug

Vue Tree Component tree branches does not expand during filtering to display matching search results.

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

4.2.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Create a tree component with filtering. When filter input is inserted the tree is filtererd, but the nodes are not open if it is a child node.

The same issue is bringed out here also https://github.com/primefaces/primevue/issues/3996

### Expected behavior

When tree is being filtered, then the nodes should be opened

The same issue is bringed out here also https://github.com/primefaces/primevue/issues/3996

I saw there was even done a feature branch, but was closed.

**Comment by AlexBindevald** [comment]
<InputText v-model="filterValue" autocomplete="off" :class="cx('pcFilterInput')" :placeholder="filterPlaceholder" :unstyled="unstyled" @keydown="onFilterKeydown" :pt="ptm('pcFilterInput')" />

If the @keydown would be changed to keyup then it is possible to do easy workaround. But currently you are getting filter value before the full input

**Comment by tugcekucukoglu** [comment]
Duplicate #6928

**Comment by AlexBindevald** [comment]
It is not duplicate, different scenarios
