### ISSUE TITLE
Tooltip: Missing exported TooltipPassThroughOptions

### ISSUE THREAD

**Issue by bjarnef** [primefaces/primevue#6952]
### Describe the bug

We have different presets for PrimeVue componennts and passthrogh options.

However for Tooltip component I can't find any `TooltipPassThroughOptions` - only `TooltipPassThroughMethodOptions`.

![image](https://github.com/user-attachments/assets/284a42d3-8bfa-49f7-a6bf-19d592840e92)

So the Tooltip hasn't any of the classes set in unstyled mode.

I could solve it using inline PT options instead, but if we use Tooltip is several Vue components, we would have to do this in every component - or create our own component wrapping this to extend from.

```
<span class="dot"
      v-tooltip="{
        value: 'Something',
        showDelay: 500,
        hideDelay: 300,
        pt: {
          root: 'p-tooltip p-component',
          arrow: 'p-tooltip-arrow',
          text: 'p-tooltip-text'
        }
      }">
</span>
```

### Reproducer

-

### PrimeVue version

3.53.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 131.0.6778.109

**Comment by tugcekucukoglu** [comment]
Correct name: `TooltipDirectivePassThroughOptions`

**Comment by bjarnef** [comment]
Actually I tried that, but

```
import type { TooltipDirectivePassThroughOptions } from 'primevue/tooltip';

type DefaultPrimePresetType = {
  tooltip?: TooltipDirectivePassThroughOptions;
};
```

```
const DefaultPrimePreset: DefaultPrimePresetType = {
  tooltip: {
      root: ({ context }) => [
        'p-tooltip p-component',
        {
          'p-tooltip-right': context.right,
          'p-tooltip-left': context.left,
          'p-tooltip-top': context.top,
          'p-tooltip-bottom': context.bottom,
        },
      ],
      arrow: () => 'p-tooltip-arrow',
      text: () => 'p-tooltip-text',
    },
};

export default DefaultPrimePreset;
```

But the tooltip added is without CSS classes unlike the other components. It works using line PT options though, although it doesn't seem to set the position CSS classes.

In default presets it didn't allow me to set string value for `arrow` and `text`, but inline it is allowed as shown here: 

```
pt: {
  root: (options: TooltipPassThroughMethodOptions) => ({
    class: [
        'p-tooltip p-component',
        {
          'p-tooltip-right': options.context.right,
          'p-tooltip-left': options.context.left,
          'p-tooltip-top': options.context.top,
          'p-tooltip-bottom': options.context.bottom
        }
    ]
  }),
  arrow: 'p-tooltip-arrow',
  text: 'p-tooltip-text'
}
```
