### ISSUE TITLE
Custom CSS Injection in PrimeVue 4 Preset Works in Standalone Vue but Not with Nuxt Module

### ISSUE THREAD

**Issue by tonwiebsci** [primefaces/primevue#6959]
### Describe the bug

We are experiencing an issue with PrimeVue 4 where our custom preset successfully injects CSS in a standalone Vue application but fails to do so when using the @primevue/nuxt-module. While token overrides are functioning correctly in both environments, the CSS defined within the preset does not apply when using Nuxt.

**Behavior:**

- **Standalone Vue:**
  - **Token Overrides:** Function correctly.
  - **CSS Injection:** Custom CSS defined in the preset is successfully injected and applied.
- **Nuxt Module:**
  - **Token Overrides:** Function correctly.
  - **CSS Injection:** Custom CSS defined in the preset is not injected or applied. Styles such as `.p-button.p-button-custom { color: orange; }` and `.p-button.p-button-custom { color: red; }` are missing in the final build.

**Our Custom Preset:**

```
// theme/custom.ts
import { definePreset } from '@primevue/themes';
import Lara from '@primevue/themes/lara';

const FrameworkPreset = definePreset(Lara, {
  components: {
    button: {
      padding: {
        x: '10rem',
      },
      css: ({ dt }) => `
        .p-button.p-button-custom {
          color: orange;
        }
      `,
    },
  },
  css: ({ dt }) => `
    .p-button.p-button-custom {
      color: red;
    }
  `,
});

export default FrameworkPreset;
```

**Standalone Vue Setup**:

```
import { createApp } from 'vue';
import PrimeVue from 'primevue/config';
import { definePreset } from '@primevue/themes';
import Lara from '@primevue/themes/lara';
import App from './App.vue';

import Button from 'primevue/button';
import Card from 'primevue/card';

const app = createApp(App);

const FrameworkPreset = definePreset(Lara, {
  components: {
    button: {
      padding: {
        x: '10rem',
      },
      css: ({ dt }) => `
        .p-button.p-button-custom {
          color: orange;
        }
      `,
    },
  },
  css: ({ dt }) => `
    .p-button.p-button-custom {
      color: red;
    }
  `,
});

app.use(PrimeVue, {
  theme: {
    preset: FrameworkPreset,
  },
});

app.component('Button', Button);
app.component('Card', Card);

app.mount('#app');
````

**Standalone Vue Observations:**

- The application renders correctly with the custom padding and CSS overrides.
- The CSS from the preset is being applied:
![image](https://github.com/user-attachments/assets/0e9deb5a-45cb-43c9-a5ef-66f0fb1f34b8)

**Nuxt Module Setup:**

```
// nuxt.config.ts
import path from 'path';
import themePreset from './theme/custom';

export default defineNuxtConfig({
  devtools: { enabled: true },
  primevue: {
    options: {
      theme: {
        preset: themePreset,
      },
    },
  },
  modules: ['@primevue/nuxt-module'],
  vite: {
    resolve: {
      alias: {
        '@': path.resolve(__dirname),
      },
    },
  },
  css: [
    '/node_modules/primeflex/primeflex.css',
    '/node_modules/primeicons/primeicons.css',
  ],
});
```

**Nuxt Module Observations:**

- **Token Overrides:** Working as expected (e.g., `button.padding.x` is applied).
- **CSS Injection:** None of the custom CSS from the preset is applied. Styles such as `.p-button.p-button-custom { color: orange; }`  and `.p-button.p-button-custom { color: red; }` are missing in the final build.

**Minimal Reproduction:**

- **Standalone Vue Example:** [StackBlitz Example](https://stackblitz.com/edit/vitejs-vite-hsrvhv9t)
- **Nuxt Module Example:**  [StackBlitz Example](https://stackblitz.com/edit/nuxt-starter-f5vs6sek)

**Question:** Is the `@primevue/nuxt-module` currently not supporting CSS injection from the [css](url) property in `definePreset` as demonstrated in the standalone Vue setup? If so, is there a workaround or an upcoming fix to enable CSS injection within Nuxt when using custom presets?

**Additional Context:**

- PrimeVue Version: 4.2.4
- Nuxt Version: 3.12.4
- Vite Version: 6.0.3

**What We've Tried:**

1. **Correct Configuration**: Ensured that the preset is correctly passed within the theme.preset option in nuxt.config.ts.
2. **Component Registration**: Registered components globally in both setups.
3. **Minimal Preset**: Created a minimal preset to isolate the issue.
4. **CSS Rules**: Verified that removing CSS rules in the preset restores visibility in the standalone Vue app.
5. **Console Logs**: Added extensive logging to the mergeColorSchemes function to trace the CSS injection process.

Despite these efforts, the CSS injection works flawlessly in standalone Vue but fails to apply any styles when using the Nuxt module.

**Request for Assistance:** Could the PrimeVue team please confirm whether the `@primevue/nuxt-module` fully supports CSS injection via the `definePreset`'s `css` property? If not, are there any recommended steps or configurations to enable this functionality? Any insights or guidance would be greatly appreciated.

Example Minimal App.vue for both Nuxt module and Standalone Vue:

```
<!-- App.vue -->
<template>
  <div class="p-4">
    <Card class="mb-4">
      <template #title>Button with custom severity</template>
      <template #content>
        <Button type="submit" severity="custom" label="Custom" />
        <p>Styles are missing</p>
      </template>
    </Card>
  </div>
</template>
```

**Final Notes:**

Ensure that your Nuxt environment is correctly set up to handle the styled theming system of PrimeVue 4. Since the standalone Vue setup works, the issue is likely specific to the Nuxt module's handling of the css injection. Providing a clear, detailed, and structured issue as outlined above will help the PrimeVue maintainers understand and address your problem more effectively.

### Reproducer

https://stackblitz.com/edit/nuxt-starter-f5vs6sek

### PrimeVue version

4.2.4

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by j0rgedev** [comment]
Hello @tonwiebsci. According to the docs, to set your custom preset, you need to use the [importtheme configuration](https://primevue.org/nuxt/#importtheme). Making that change, the css works as shown in the image:
![image](https://github.com/user-attachments/assets/c103aeca-51a8-4a95-91d5-1eadb8885ffe)
Updated files:
**nuxt.config.ts**
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
import path from 'path';

export default defineNuxtConfig({
  devtools: { enabled: true },

  primevue: {
    autoimport: true,
    importTheme: { from: '@/theme/custom.ts' },
  },

  modules: ['@primevue/nuxt-module'],

  vite: {
    resolve: {
      alias: {
        '@': path.resolve(__dirname),
      },
    },
  },

  css: [
    '/node_modules/primeflex/primeflex.css',
    '/node_modules/primeicons/primeicons.css',
  ],
});
```

**/theme/custom.ts**
```ts
import { definePreset } from '@primevue/themes';
import Lara from '@primevue/themes/lara';

const FrameworkPreset = definePreset(Lara, {
  components: {
    button: {
      padding: {
        x: '10rem',
      },
      css: ({ dt }) => `
        .p-button.p-button-custom {
            color: orange;
        }
      `,
    },
  },
  css: ({ dt }) => `
    // i commented this style, otherwise, the page will not show hehe
    // body {
    //     display: none !important
    // }
    .p-button.p-button-custom {
        color: red;
    }
  `,
});

// Export FrameworkPreset as default
export default {
  preset: FrameworkPreset,
  options: {
    // custom preset options, for example:
    // ripple: true,
  },
};
```

**Comment by tonwiebsci** [comment]
oh my god! thank you so much
