### ISSUE TITLE
TextArea: When AutoResize present getting error

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [primefaces/primevue#6960]
### Describe the bug

        <Textarea v-model="comments" class="w-full" :rows="2" :autoResize="true"  />
        
        Uncaught runtime errors:
×
ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:308:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:327:7)

unable to reproduce on stackblitz, maybe because it uses vite and not vue cli, on vite not reproducable

my packages:
```
  "dependencies": {
    "@primevue/themes": "4.2.4",
    "@tinymce/tinymce-vue": "4.0.7",
    "@vuelidate/core": "2.0.0",
    "@vuelidate/validators": "2.0.0",
    "axios": "1.7.9",
    "chart.js": "3.5.0",
    "chartjs-plugin-datalabels": "2.2.0",
    "core-js": "3.39.0",
    "moment": "2.29.4",
    "moment-hijri": "2.30.0",
    "pinia": "2.0.16",
    "primeflex": "3.3.1",
    "primeicons": "7.0.0",
    "primevue": "4.2.5",
    "print-js": "1.6.0",
    "sprintf-js": "1.1.3",
    "tinymce": "6.2.0",
    "v-onboarding": "2.9.0",
    "vue": "3.5.13",
    "vue-fluid-dnd": "0.9.2",
    "vue-pdf-embed": "2.1.0",
    "vue-router": "4.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.7",
    "@babel/eslint-parser": "^7.25.7",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-eslint": "^5.0.8",
    "@vue/cli-plugin-router": "^5.0.8",
    "@vue/cli-plugin-vuex": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.23.0",
    "lint-staged": "^15.2.10",
    "prettier": "^3.3.3",
    "sass": "^1.79.4",
    "sass-loader": "^16.0.2"
  },
```

### Reproducer

https://stackblitz.com/edit/wrk8yzgu?file=src%2FApp.vue,package.json

### PrimeVue version

4.2.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome

**Comment by AmmarMohamadIsmaeel** [comment]
The issue is reproduce when using vue cli, on vite its not reproducable

**Comment by cagataycivici** [comment]
Vue CLI is not supported. From their website;

Vue CLI is in Maintenance Mode!

For new projects, please use [create-vue](https://github.com/vuejs/create-vue) to scaffold [Vite](https://vitejs.dev/)-based projects. Also refer to the [Vue 3 Tooling Guide](https://vuejs.org/guide/scaling-up/tooling.html) for the latest recommendations.
