### ISSUE TITLE
Select: label not showing in the input box for the option with null value

### ISSUE THREAD

**Issue by mgksmv** [primefaces/primevue#6975]
### Describe the bug

Label in `Select` component not showing when default value with `null` value is selected.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-qhegcvk8?file=src%2FApp.vue

### PrimeVue version

4.2.3

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Because of the `option-value="id"`, it is expected behaviour.

**Comment by mgksmv** [comment]
But what if I need a default option with `null` value? In cases when select field is optional.

**Comment by DC240** [comment]
> Because of the `option-value="id"`, it is expected behaviour.

I just experienced this as well and for me also, it does definitely not feel like 'expected' behaviour. When I add an option with id: null and label: None, I expect to see 'None' when I select this option, even though option-value="id". 

What do you recommend otherwise when the field is optional? I would love some feedback, thanks.

**Comment by mgksmv** [comment]
> > Because of the `option-value="id"`, it is expected behaviour.
> 
> I just experienced this as well and for me also, it does definitely not feel like 'expected' behaviour. When I add an option with id: null and label: None, I expect to see 'None' when I select this option, even though option-value="id".
> 
> What do you recommend otherwise when the field is optional? I would love some feedback, thanks.

This might not be a good solution but I started using `0` instead of `null` when field is optional as a workaround. I still don't get it why this is expected behavior.

**Comment by DC240** [comment]
> > > Because of the `option-value="id"`, it is expected behaviour.
> > 
> > 
> > I just experienced this as well and for me also, it does definitely not feel like 'expected' behaviour. When I add an option with id: null and label: None, I expect to see 'None' when I select this option, even though option-value="id".
> > What do you recommend otherwise when the field is optional? I would love some feedback, thanks.
> 
> This might not be a good solution but I started using `0` instead of `null` when field is optional as a workaround. I still don't get it why this is expected behavior.

Thanks, that would indeed do the trick. Problem for me is that I already have a lot of saved data with the 'null' value, so that would require some extra work. For me, the #value slot works as well. However, as you mentioned, this are not the most straightforward solutions to me either...

**Comment by mgksmv** [comment]
> > > > Because of the `option-value="id"`, it is expected behaviour.
> > > 
> > > 
> > > I just experienced this as well and for me also, it does definitely not feel like 'expected' behaviour. When I add an option with id: null and label: None, I expect to see 'None' when I select this option, even though option-value="id".
> > > What do you recommend otherwise when the field is optional? I would love some feedback, thanks.
> > 
> > 
> > This might not be a good solution but I started using `0` instead of `null` when field is optional as a workaround. I still don't get it why this is expected behavior.
> 
> Thanks, that would indeed do the trick. Problem for me is that I already have a lot of saved data with the 'null' value, so that would require some extra work. For me, the #value slot works as well. However, as you mentioned, this are not the most straightforward solutions to me either...

You know what... I think I found a solution. Just set placeholder attribute in `Select` component and it seems to be working. I updated my demo in stackblitz and you can see it here: https://stackblitz.com/edit/vitejs-vite-qhegcvk8?file=src%2FApp.vue
