### ISSUE TITLE
DatePicker: unfocus removes input text

### ISSUE THREAD

**Issue by sohaibali123** [primefaces/primevue#6979]
### Describe the bug

1 - Once date picker is set to manualInput any text that is in input gets removed when clicking away. I don't know if this is intended or a bug. As I think it should be in invalid state rather than removing text completely.

2 -Also on manualInput while typing in date it doesn't update the component if date is not completely entered in.

### Reproducer

https://stackblitz.com/edit/wtcj7kkr-9mfe92wv?file=src%2FApp.vue

### PrimeVue version

4.2.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Firefox

### Expected behavior

2 - Entering date for example if i entered '11/' the component should update and display month november. once entered 11/20 the component should update again and display month november and select 20. When dateFormat is set to 'mm/dd/yyyy'.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
