### ISSUE TITLE
DatePicker: Not possible to enter 1979/02/28 when dateFormat is set to 'yy/mm/dd'

### ISSUE THREAD

**Issue by ivantakahasi** [primefaces/primevue#6981]
### Describe the bug

"When setting the date format of the DatePicker to 'yy/mm/dd', 
it becomes very difficult to manually enter the last part of the date, such as '28' or '20'."

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

4.2.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

TypeScript

### Browser(s)

Edge, Chrome

### Steps to reproduce the behavior

1 - set yy/mm/dd to date-format
2 - set true to manual-input
3 - try to type 1979/02/28 using your keyboad.
and then you find it difficult to enter the last date, '28'.

### Expected behavior

Should be able to enter 1979/02/28

**Comment by tugcekucukoglu** [comment]
v-model will be formatted when single digits are entered for days and also months. This commit resolves cursor start and end position bugs. Cursor position was fixed when in yy/mm/dd format to not break existing formatting behavior.
