### ISSUE TITLE
Toast Service: remove() broken (or insufficiently documented and typed)

### ISSUE THREAD

**Issue by galaxyblur** [primefaces/primevue#6987]
### Describe the bug

What is the recommended way to remove an existing toast, programmatically? The `remove` function exists in the Toast Service doc, but doesn't provide enough info to be used. The code doesn't either, and doesn't contain sufficient typing to derive the methodology.

### Reproducer

https://stackblitz.com/edit/primevue-nuxt-issue-template?file=README.md

### PrimeVue version

4.2.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by j0rgedev** [comment]
Hello @galaxyblur. The remove method isn't broken. Please, review the documentation I've just added and let me know if that solves your issue.
Best regards and merry christmas😁

**Comment by tugcekucukoglu** [comment]
https://primevue.org/toast/#sticky

**Comment by galaxyblur** [comment]
@tugcekucukoglu Respectfully, that is not what I'm looking for. The function that needs documentation is `remove()` in the Toast Service, not `removeAllGroups()`, which is what you linked to.

https://github.com/primefaces/primevue/blob/master/packages/primevue/src/toastservice/ToastService.js#L10

@j0rgedev attempted to document the actual function in question. However, even in that PR, I think there is still an unanswered part:

How is a toast identified for removal later? Is an id assigned, or an object reference? If it is simply based on the properties of the toast message, how do duplicate toasts (which are sometimes valid use-cases) get removed?

**Comment by RobArkesteijn** [comment]
I would like an answer to this question. How can you close a specific toast that is not linked to a group?

**Comment by iamvanja** [comment]
I discovered it.

```ts
  toast.add({
    severity: 'info',
    summary: 'Info',
    detail: 'Message Content',
    id: 'my-id',
  });

```
and then to remove
```ts
toast.remove({ id:'my-id' });
```

`id` is not typed in `ToastMessageOptions`.

I expected that `toast.add` would return an id, but that is not the case.

I think this definitely needs to be documented.

**Comment by jdenisTeomed** [comment]
Thanks for the trick ! 
I've seen an opened issue for that point : #8202
