### ISSUE TITLE
MultiSelect: itemcheckboxicon slot does't provide "selected" value 

### ISSUE THREAD

**Issue by SchwarzesWasser** [primefaces/primevue#6990]
### Describe the bug

I am trying to customize the checkbox icon in the component, but the `selected` property always returns `undefined`. A boolean value was expected.

In the StackBlitz example, I tried to log the value of the property to the console.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-ghy3q27h?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
The right name should be `checked`. This will be fixed for the next version.
