### ISSUE TITLE
Datatable: Filter Icon isn't highlighted when filter is active

### ISSUE THREAD

**Issue by prabinsh** [primefaces/primevue#6996]
### Describe the bug

![image](https://github.com/user-attachments/assets/0a526f0b-59ae-4765-b081-f5ddf63c50e5)
In Primevue 4, the filter icon isn't highlighted when the filter is active which makes its harder to understand the current active filters.

### Reproducer

https://stackblitz.com/edit/4jfdknvm?file=src%2FApp.vue

### PrimeVue version

4.25

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Please try the example in https://primevue.org/datatable/#filter

### Expected behavior

The filter icon should be active

**Comment by tugcekucukoglu** [comment]
It is a design decision, not a bug. You can change it using new tokens.

Thank you.

**Comment by prabinsh** [comment]
@tugcekucukoglu Thank you for your response. I appreciate the visual cues that indicated which filters were active; they were incredibly useful for enhancing user experience. I am disappointed to see such a valuable feature removed

**Comment by radush-v** [comment]
@prabinsh could you please explain how did you resolved this issue?
