### ISSUE TITLE
Input Mask: invalid type for pt root

### ISSUE THREAD

**Issue by laylatichy** [primefaces/primevue#6998]
### Describe the bug

invalid type for root pt, probably copy paste error

https://github.com/primefaces/primevue/blob/master/packages/primevue/src/inputmask/InputMask.d.ts#L66

### Reproducer

-

### PrimeVue version

4.2.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by tugcekucukoglu** [comment]
Cannot replicate the problem. The current implementation is correct.

Thank you.
