### ISSUE TITLE
Calendar.vue: Poor handling of user input.

### ISSUE THREAD

**Issue by jonasraoni** [primefaces/primevue#70]
It's complex/non-intuitive for the end-user to fill something into the calendar's text input, to the point where it's better to disable it.

I was going to fix, but I just noticed that my PRs were ignored/merged without my name, so I lost the motivation haha 🤪

**Comment by jonasraoni** [comment]
Examples:
- Strange behaviour when a date/time is filled, and you try to edit (press backspace or change something), sometimes it's blocked, sometimes it erases everything, etc.
- Time/date field when partially filled erases everything

**Comment by cagataycivici** [comment]
Sorry to hear about the PR handling, please do not hesitate to provide one for review.

@mertsincan This one is for you, manual input handling should behave like NG or React;

https://www.primefaces.org/primeng/#/calendar
https://www.primefaces.org/primereact/#/calendar

**Comment by jonasraoni** [comment]
Hi, I've updated the package to beta.12 and I'm checking on IE11... Here I still have the same problems to edit, so I will keep it disabled.

My opinion: the manual edition should be more permissive, if the model is valid or not is out of the scope of the component (or should be configurable).
