### ISSUE TITLE
Button: size attr does not work with flex very well

### ISSUE THREAD

**Issue by tc0o** [primefaces/primevue#7015]
### Describe the bug

I believe it's relative with https://github.com/primefaces/primevue/issues/6072

### Reproducer

https://stackblitz.com/edit/nkdkhupd?file=src%2FApp.vue

### PrimeVue version

4.2.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

- visit official example: https://primevue.org/button/#sizes
- edit in stackblitz
- remove the attr `items-center`

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primevue/issues/7017
