### ISSUE TITLE
Component Name: InputText

### ISSUE THREAD

**Issue by palachX** [primefaces/primevue#7016]
### Describe the bug

In version 3.51.0 u use update:modelValue and save reactivity
![image](https://github.com/user-attachments/assets/af81818f-1d17-4ace-a808-b7c6d65df890)

In version 4.2.5 u kill reactivity because u use this.writeValue
![image](https://github.com/user-attachments/assets/ba19a2fe-d09e-4ec4-b61f-f749a47e5aed)

And i can't change value in input.

See this text in input don't change, but modelValue change:

![image](https://github.com/user-attachments/assets/fb023ddf-60b2-4757-955d-215deb0d50c7)
![image](https://github.com/user-attachments/assets/47e2e5ca-e960-4f16-b2cd-01f9f0f9a82c)

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-9ubq2xzw?file=src%2FWorkComponent.vue

### PrimeVue version

4.2.5

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 131.0.6778.205

### Steps to reproduce the behavior

1. Write clear component this code:

```
<script setup>
const [model] = defineModel({
   set(value) {
    return value.slice(0, 2)
  }
})
</script>

<template>
  <input type="text" v-model="model" />
</template>
```

2. Use him in another component:

```
<script setup>
import { ref } from 'vue'
import MyComponent from './MyComponent.vue'
  
const myText = ref('')
</script>

<template>
  This input capitalizes everything you enter:
  <MyComponent v-model="myText" />
</template>
```

And use u InputText

1. Write clear component this code:

```
<script setup>
import InputText from 'primevue/inputtext'

const [model] = defineModel({
  set(value) {
    return value.slice(0, 2)
  }
})
</script>

<template>
  <InputText  v-model="model" />
</template>
```

2. Use him in another component:

```
<script setup>
import { ref } from 'vue'
import MyComponent from './MyComponent.vue'
  
const myText = ref('')
</script>

<template>
  This input capitalizes everything you enter:
  <MyComponent v-model="myText" />
</template>
```

### Expected behavior

Value in InputText reactivity

**Comment by palachX** [comment]
As it turned out, the problem has been found so far specifically with .slice(0, n), if you do return value + '_'; then it works, it's unclear why, but it seems to me that the problem is in the writeValue method.

![image](https://github.com/user-attachments/assets/13f0feba-aa20-4ffa-81ed-92e947001e08)

**Comment by cagataycivici** [comment]
PrimeVue 3.x has reached EOL by the end of 2024 so we're unable to assist.

**Comment by palachX** [comment]
Please see description, problem in version 4.2.5

PrimeVue version
4.2.5

**Comment by ZiadJ** [comment]
> PrimeVue 3.x has reached EOL by the end of 2024 so we're unable to assist.

@cagataycivici It's a v4 issue actually and it involves both `InputText` and `Textarea`. 
Notice how only native elements work as expected here:  
https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-qqzff9k4?file=src%2FMyComponent.vue
