### ISSUE TITLE
PrimeVue FileUpload FileLimit

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primevue#703]
#610

**Comment by qecce** [comment]
Hey, 
there were changes made, but the fix is not complete for 2.2.2. 
I guess its the line 125 where "files" is not an array but should be one.
There is also another ticket about the same issue.
https://github.com/primefaces/primevue/issues/677?_pjax=%23js-repo-pjax-container

**Comment by ilyavaiser** [comment]
This fix not worked
