### ISSUE TITLE
All components that emit events now give Vue warnings (and are sometimes unusable), even though they didn't beforehand

### ISSUE THREAD

**Issue by MatijaNovosel** [primefaces/primevue#720]
Using Vue3 and typescript support (https://github.com/MatijaNovosel/fin-app).

Been using PrimeVue for a decent amount now and out of nowhere some components became unusable and my console keeps getting clogged up with yellow Vue warnings.

An example being the DataView component, declared as such:

```
<data-view
  v-else
  layout="grid"
  :paginator="true"
  :rows="16"
  :value="state.changes"
  paginatorPosition="bottom"
>
  <template #grid="slotProps">
    <div class="p-col-12 p-md-3 p-p-2">
      <change-card
        :expense="slotProps.data.expense"
        :title="slotProps.data.description"
        :amount="slotProps.data.amount"
        :category="formatCategory(slotProps.data.category)"
        :date="format(slotProps.data.date, 'dd/MM/yyyy - HH:mm')"
      />
    </div>
  </template>
</data-view>
```

**change-card** being my custom component which is nothing but a div with some text.

I have changed nothing over my last commit on the project and somehow the pagination does not work and the developer console keeps displaying this when switching pages:

![image](https://user-images.githubusercontent.com/36193643/100554008-1e4e6400-3292-11eb-8876-cb83c9a989aa.png)

**Comment by dheimoz** [comment]
This is a new option in Vue 3 https://v3.vuejs.org/guide/migration/emits-option.html#emits-option
But it was fixed a month ago 
https://github.com/primefaces/primevue/commit/4044be48cbd64d9107f525f239fd88a968882851

Have you upgraded to the latest version 3.02?

**Comment by MatijaNovosel** [comment]
Whoops, it would seem as if I had version ^3.0.0 specified in my package.json file but npm did not register any changes from primevue. Had to npm install again after changing it to ^3.0.2. 

Thank you very much!

**Comment by dheimoz** [comment]
@MatijaNovosel glad it worked.
