### ISSUE TITLE
Tooltips do not work in Vue 3

### ISSUE THREAD

**Issue by Eireternal** [primefaces/primevue#721]
Follow documentation for tooltips.

Attached v-tooltip parameter to a selector.

Hover over selector and notice a tooltip does not appear.

**Comment by dheimoz** [comment]
I have tooltips enabled. My first suggestion is to double check that you have installed the latest version of Prime Vue. Then, in your main.js import the directive
import Tooltip from "primevue/tooltip";

I have used a constant to mont Vue
const app = createApp(App);

Then add the directive

app.directive("tooltip", Tooltip);

Finally, attach the directive for instance in a Dropdown like this:

<Dropdown
              v-tooltip.top="'Select a choice'"
              v-model="model"
              :options="options"
              optionLabel="label"
              optionValue="name"
              placeholder="Select"
/>


Hope this helps.

**Comment by Eireternal** [comment]
Hi and thank you for the quick reply.

Update my primevue from 3.0.1 to 3.0.2

My setup in my main.ts is identical to yours.

Wasn't able to see your example of attaching the directive, could you repost?

Here' is an example of what I have: (This is inside a Datatable)
<span class="p-column-title" v-tooltip.top="'test'"><span>{{col.header}}:</span> {{slotProps.data[col.field]}}</span>

Another note in case this helps, my component hierarchy looks like this:
Main.ts > Profiles.vue (Page) > DTable.vue (component on page & where I'm trying to get the tooltip to work)

Thanks again.

**Comment by dheimoz** [comment]
Sure
`<Dropdown
              v-tooltip.top="'Select a choice'"
              v-model="model"
              :options="options"
              optionLabel="label"
              optionValue="name"
              placeholder="Select"
/>`

**Comment by Eireternal** [comment]
Ok so if I add your code above the line I had... it works for both. If I remove your line of code it doesn't work.

`<template #body="slotProps">
                <Dropdown v-tooltip.top="'Select a choice'" v-model="model" :options="options" optionLabel="label" optionValue="name" placeholder="Select" />
                <span class="p-column-title" v-tooltip.top="'test'"><span>{{col.header}}:</span> {{slotProps.data[col.field]}}</span>

            </template>`

So confused as to why that is.

**Comment by dheimoz** [comment]
Do you need tooltips for every choice that has the dropdown? I am sorry, but I am failing to understand the use case. I use the tooltip just to provide a brief explanation for the dropdown.

**Comment by Eireternal** [comment]
For my use case I need tootips on each table entry. I don't need dropdowns but put them in to follow along with your test. On load, if I hover over the dropdown or the table entry (which is the span tag), no tooltip appears.

However once I open any of the dropdowns, I do get the tooltips to popup on both the dropdowns and the table entries. For some reason opening the dropdown allows tooltips to then show up.

![image](https://user-images.githubusercontent.com/7497639/100674305-28b83e80-3322-11eb-8d7a-0616ff9ff9bb.png)

![image](https://user-images.githubusercontent.com/7497639/100675040-6cf80e80-3323-11eb-8467-d48cef07cc06.png)

**Comment by dheimoz** [comment]
Hello @Eireternal , I think I got it. If I understand correctly, you require a tooltip for each row in a Datatable, am I right?

If this is the case, I think you should rename the issue. It is a little bit misleading.

According to the templating documentation https://primefaces.org/primevue/showcase/#/datatable/templating
You can customize how the columns are rendered. I do not think you can template a specific row, beside styling them.

Perphaps Context menu can help you https://primefaces.org/primevue/showcase/#/datatable/contextmenu or Row Expansion https://primefaces.org/primevue/showcase/#/datatable/rowexpand

These are not as great as a tooltip, but you can argument that this options are not invasive.

If you really need tooltips, you can add another column with an icon pi-info-circle and with Templating that column you could incorporate a tooltip:

`<template #body="slotProps">
            <Rating v-tooltip="'INFORMATION'"  :modelValue="slotProps.data.rating" :readonly="true" :cancel="false" />
        </template>`

**Comment by Eireternal** [comment]
Oh man, ok upon further testing, it seem this was an embarrassing case of user error. Tooltips were always working, however they were popping up behind the table initially. When a dropdown is opened, it moved the tooltips z-index to the front.

When applying a tooltip on an element, it seems that if any parent elements have a z-index with a nonzero value, (which was my case), tooltips will will appear behind the z-indexed element. I would have thought that the tooltips would be in front no matter what.

You can see the tooltip peeking out on the left side there.

![image](https://user-images.githubusercontent.com/7497639/100784733-dda73580-33cc-11eb-8562-fddf9382fe86.png)

**Comment by cagataycivici** [comment]
Please create a new ticket with the new issue so we can review. A sample reproducible test case will also help us when reviewing your new ticket.
