### ISSUE TITLE
子页面导航上的刷新无法使用

### ISSUE THREAD

**Issue by bufanyun** [primefaces/primevue#722]
子页面导航上的刷新无法使用，刷新以后页面是空白
![image](https://user-images.githubusercontent.com/26652343/100606164-fb7c8800-3343-11eb-910e-fc94a98c8955.png)

**Comment by bufanyun** [comment]
refreshSelectedTag(view) {
      this.$store.dispatch('tagsView/delCachedView', view).then(() => {
        const { fullPath } = view
        console.log('fullPath:'+fullPath)
        location.reload()
        // this.$nextTick(() => {
        //   this.$router.replace({
        //     path: '/redirect' + fullPath
        //   })
        // })
      })
    },


修改/src/layout/components/TagsView/index.vue，第136行起的方法可以解决，但是这样写法是全局刷新，页面会全部重新加载，用户体验不是很好

**Comment by cagataycivici** [comment]
Please create a ticket with a sample that we can replicate, English translation will also help greatly.
