### ISSUE TITLE
Keyboard support problem for AutoComplete 

### ISSUE THREAD

**Issue by nimruth** [primefaces/primevue#723]
hitting 'ArrowDown' to highlight the first element is not working.

using `DomHandler.addClass(this.overlay.firstChild.firstElementChild, 'p-highlight');` instead of `DomHandler.addClass(this.overlay.firstChild.firstChild, 'p-highlight');` will fix it

**Comment by dheimoz** [comment]
This feature could be handy for accessibility purposes. Hope @cagataycivici could consider this for the next milestone.

**Comment by cagataycivici** [comment]
Resolved now, thank you.
