### ISSUE TITLE
BUG: Calendar navigation (next, prev month) inside DataTable or OverlayPanel not working

### ISSUE THREAD

**Issue by sun-pandey** [primefaces/primevue#729]
If Calendar component is placed inside DataTable edit slot or inside a OverlayPanel, month navigation goes to the prev or next month (month-change event is properly emitted) but the calendar closes itself. 
It doesn't stay on so can not pick a date after prev or next month navigation.

**Comment by cagataycivici** [comment]
This sounds similar to an issue we had in PrimeNG, working on it.
