### ISSUE TITLE
打包时提示几个文件不存在

### ISSUE THREAD

**Issue by bufanyun** [primefaces/primevue#730]
打包时提示几个文件不存在，如下：

[root@VM-8-5-centos ]# yarn serve

yarn run v1.22.10
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 WARNING  Compiled with 3 warnings                                                                  8:42:15 AM

 warning  in ./src/store/modules/permission.js

"export 'asyncRoutes' was not found in '@/router'

 warning  in ./src/store/modules/permission.js

"export 'asyncRoutes' was not found in '@/router'

 warning  in ./src/store/modules/user.js

"export 'resetRouter' was not found in '@/router'

**Comment by cagataycivici** [comment]
Please create a ticket with a sample that we can replicate, English translation will also help greatly.
