### ISSUE TITLE
Textarea does not auto resize its height when created

### ISSUE THREAD

**Issue by derMart** [primefaces/primevue#733]
As title, create a Textarea with `:autoResize=true` and its model to contain some large text.
The Textarea will only adjust its height after the contents of the textarea dom element is changed by the user (so that its scrollheight is affected, e.g. by entering a newline)

Initially, `this.cachedScrollHeight` is falsy, so that it will be set to `this.$el.scrollHeight` by
https://github.com/primefaces/primevue/blob/5323d888105bea2bec31fe9ee8e533b29e61414b/src/components/textarea/Textarea.vue#L26
Then, the code block following:
https://github.com/primefaces/primevue/blob/5323d888105bea2bec31fe9ee8e533b29e61414b/src/components/textarea/Textarea.vue#L30
won't be executed, which results in the height of $el not being set to the scrollHeight.

The fix for this issue is simple, just remove:
https://github.com/primefaces/primevue/blob/5323d888105bea2bec31fe9ee8e533b29e61414b/src/components/textarea/Textarea.vue#L26
That way, the height of $el will be adjusted, as `this.cachedScrollHeight !== this.$el.scrollHeight`

**Comment by fairking** [comment]
Agree. I have the same issue. I am not sure but I thought it was working before.

**Comment by cagataycivici** [comment]
This was also in PrimeNG-PrimeReact so I've ported the solution from there to fix it.

**Comment by ilzbergs** [comment]
Can someone know to deal with this situation, when autoResize doesn't resize if text is larger that textArea field? Only resize on user typing.

**Comment by DaniCima** [comment]
I don't understand why the bug has been closed if it is still occurring.
