### ISSUE TITLE
Calendar popup does not close on selection on range mode

### ISSUE THREAD

**Issue by afonic** [primefaces/primevue#734]
Example:

![Screen Recording 2020-12-02 at 19 28 37](https://user-images.githubusercontent.com/7423993/100909107-f7cc3b00-34d4-11eb-8eb9-fe83786bbdeb.gif)

It should close on select like the normal picker.

**Comment by cagataycivici** [comment]
This is by design, other Prime UI libs also have it. If there is more demand, we'll add a new prop like hideOnRangeSelection. Thank you for your feedback.

**Comment by afonic** [comment]
I don't understand why the range popup should have different behavior than the regular popup.

**Comment by mrdigitalau** [comment]
I second this, I don't like the fact it doesn't close when the date is selected. Although, fantastic library thank you!

**Comment by mirupal** [comment]
Please add `hideOnRangeSelection`

**Comment by Anubarak** [comment]
I would also like to have that prop. It's very confusing

**Comment by afonic** [comment]
@Anubarak this won't work on the second selection though, because the modelValue.length is always 2 after the first selection.

You need to check for empty values.

An approach that works using lodash:

```
if (Array.isArray(calendar.modelValue) && _.some(calendar.modelValue, item => _.isNull(item))) {
    calendar.overlayVisible = false
}
```

**Comment by Anubarak** [comment]
@afonic indeed, thank you.
Had done it this way because by the time when `date-select` is triggered, the modelValue was not updated... Not sure if that's intended or not but
`modelValue === null` -> the first is selected
`modelValue === ['xxx', null]` -> both are selected
`modelValue === ['xxx', 'yyy']` -> the first is selected

**Comment by cope** [comment]
Uhm, actually, I would love to have both hideOnRangeSelection but also hideOnSelection as well.

I am using the range to give my users an option to select a single date or a range.

On single selection I just filter for that date, and on range I do a from-to filter.

**Comment by KeerthanaAnandan** [comment]
please bring hideOnRangeSelection, i am using new version on prime vue and still this issue persist

**Comment by Hitsudzy** [comment]
still waiting a 'hideOnRangeSelection' in 2022...

**Comment by jcduhail** [comment]
the calendar.overlayVisible = false does not work for me.. Im using vue 3.2.31, is their another property ?

I had to do an ugly :

`document.querySelector(".p-datepicker").style.visibility = "hidden"`

then re-show it on focus event..

**Comment by afonic** [comment]
It should still work. Did you add a `ref` to the calendar component for the `$refs` to work?

**Comment by jcduhail** [comment]
> It should still work. Did you add a `ref` to the calendar component for the `$refs` to work?


Mmhh, my calandar is a parent component and i access to the child, maybe that's why, i'll try more thanks.

**Comment by mertsincan** [comment]
Thanks all! Duplicate of https://github.com/primefaces/primevue/issues/2684 We’ll add it to the next version.

**Comment by adydeeram** [comment]
**if this still and issue, i have resolved it with following**

**Component**

` <Calendar :maxDate="maxDate" inputId="birth_date" :hide="hideSelection" style="width: 100%;" selectionMode="range" showButtonBar
          v-model="dates" :manualInput="false" ref="calender">
          <template #footer>
            <div class="relative">
              <Button label="Select Date " @click="calender.overlayVisible = false" class="selectDateButton" text/>
            </div>
          </template>
        </Calendar>
  
  const calender = ref()
         
        `
