### ISSUE TITLE
[Bug] Prime Vue 3 - MenuModel, MenuBard does not work when nested label are dynamic, submenu not showing

### ISSUE THREAD

**Issue by ntgraph** [primefaces/primevue#735]
Prime 3.0.2 in vue 3.
Hi, I am using a Menubar model with menumodel api example.
My goal is to locallized the label so instead of put in data, I put it in computed so the 
label is like this: label: $i18n.t('somekey').

If the model is only one level(root level), label are localized in computed, everything display fine when change locale, submenu also display.

If the model is nested more than one level, the whole submenu does not display,  although in vue devtools inspector, all labels were properly translated in model.
Please help.

**Comment by cagataycivici** [comment]
Could you please provide a sample code that we can use to replicate?

**Comment by ntgraph** [comment]
Hi, Here is my explanation.
Example here is Client is in root level and is translated with vue-i18n-next.If I have multiple items BUT only one (root) level, menubar will translated correctly when change locale.
As soon as the root has nested level like sample below, menubar will display root level, but submenu will not display.   If inspect in vue-devtools, the items object is ok, all label are translated.  I build my menu based on menumodel.  I did not test on other menu component....
Localized key are omitted here for simplicity.
<template>
    <Menubar :model="items" class="mx-2 "></Menubar>
</template>computed: {
 items () {
  return [
   {
    label: this.$i18n.t('sidebarNav.client'),
    icon: 'pi pi-fw pi-pencil',
    items: [
     {
      label: this.$i18n.t('sidebarNav.city'),
      icon: 'pi pi-fw pi-align-left',
     },
     {
      label: 'Right',
      icon: 'pi pi-fw pi-align-right',
     },


    ],
   },}


Hope I explain correctly.
Lap

    On Wednesday, December 9, 2020, 09:13:21 AM EST, Cagatay Civici <notifications@github.com> wrote:  
 
 


Could you please provide a sample code that we can use to replicate?

**Comment by ntgraph** [comment]
Hi,
I hope you can help me on this Menubar, refer to code below:Items' label are localized.  I have a locale selector, on select it change language on the fly....
So with menu bar, I need items to be in computed to change on the fly, except when click on startup data, submenu won't display, there is no error in "items" il you look in inspection, all labels are localized properly.
If I change items to put in data, submenu will display, but language will not change on the fly.  When change locale, browser need refresh to change displayed language.
I hope you can help as this is the basic structure of application.Thanks in advance,
Lap
<template>
    <Menubar :model="items" class="mx-2 "></Menubar>
</template>

<script>
   export default {
      name: 'ConfigurationMenuBar',

      // data () {
      //     return {
      //        items: [
      //           {
      //              label: this.$i18n.t('menubar.startupData'),
      //              icon: 'pi pi-fw pi-pencil',
      //              items: [
      //                 {
      //                    label: this.$i18n.t('sidebarNav.client'),
      //                    icon: 'pi pi-fw pi-align-left',
      //                 },
      //                 {
      //                    label: 'Right',
      //                    icon: 'pi pi-fw pi-align-right',
      //                 },
      //                 {
      //                    label: 'Center',
      //                    icon: 'pi pi-fw pi-align-center',
      //                 },
      //                 {
      //                    label: 'Justify',
      //                    icon: 'pi pi-fw pi-align-justify',
      //                 },
      //
      //              ],
      //           },
      //           {
      //              label: this.$i18n.t('sidebarNav.tax'),
      //              icon: 'fal fa-file-invoice-dollar',
      //           },
      //           {
      //              label: this.$i18n.t('sidebarNav.productAttribute'),
      //              icon: 'fal fa-tasks',
      //           },
      //        ],
      //     }
      //
      // },

      computed: {
         left() {
            return 'leftA';
            },

         items () {
            return [
               {
                  label: this.$i18n.t('sidebarNav.client'),
                  icon: 'pi pi-fw pi-pencil',
                  items: [
                     {
                        label: this.$i18n.t('sidebarNav.city'),
                        icon: 'pi pi-fw pi-align-left',
                     },
                     {
                        label: 'Right',
                        icon: 'pi pi-fw pi-align-right',
                     },


                  ],
               },
               {
                  label: this.$i18n.t('sidebarNav.tax'),
                  icon: 'fal fa-file-invoice-dollar',
               },
               {
                  label: this.$i18n.t('sidebarNav.productAttribute'),
                  icon: 'fal fa-tasks',
               },
            ]
         },


      },

   }



</script>



    On Wednesday, December 9, 2020, 09:13:21 AM EST, Cagatay Civici <notifications@github.com> wrote:  
 
 


Could you please provide a sample code that we can use to replicate?

**Comment by ntgraph** [comment]
Hi Cagatay,
Can you check my previous post, code are there. I can not put the menumodal code in computed.  Menubar won't display submenu.  If you have time, please have a look.
thanks,

**Comment by MarioLiebisch** [comment]
Stumbled over the very same issue. As soon as the menu data/model is computed, the menu stops working. Updating it as regular data seems to work fine, though.

The created DOM etc. is all fine for me, it just doesn't react to inputs, i.e. `p-menuitem-active` isn't added as a class. (I didn't dig too deep into this so far.)

To reproduce, you just have to use computed data:

```html
<Menubar :model="menuItems"></Menubar>
```
```ts
get menuItems() {
    return [
        {
            label: "Top Level",
            items: [
                { label: "Sub Level Not Shown" },
                { label: "Sub Level Not Shown" },
            ]
        }
    ];
}
```

In this example, you'd get the "Top Level" menu entry, it will show with the dropdown arrow, etc. but won't do anything. Adding `p-menuitem-active` by hand makes it pop open as expected.

So my current workaround is something like this:
```ts
menuItems = [];

someUpdateFunction() {
    this.menuItems = [/* ... */];
}
```
This way the dynamic menu works, although it's far from ideal and somewhat defeats the whole purpose of reactive components.

**Comment by antonio-wundermart** [comment]
I have the same issue but for the PanelMenu: as soon as I define the model in the compute options (for example provided by vuex in the state), the sub menu doesn't work anymore.

**Comment by qbyte-opensource** [comment]
I have the same issue with vuex getters.

`
methods: { }
`

I've tried @MarioLiebisch method,

**Comment by qbyte-opensource** [comment]
I have the same issue with vuex getters and actions.

```
data() {
  return {
    items: [
      {
        label: "user.email",
        to: "/profile",
        items: [
            { 
              label: "Log out ",
              command: () => { this.logout() }
            }
        ]
      }
    ]
  };
}
computed: { 
    ...vuex.mapGetters(["user"])
},
methods: {
    ...vuex.mapActions(["updateUser"]),
    logout() {
        this.updateUser(null);
    }
}
```

I've tried @MarioLiebisch method, and it throws and error on updateUser

**Comment by cagataycivici** [comment]
For me this is expected and vue change detection related, you need to create a new instance of the menu when updating it to help Vue to indicate that something has changed.

**Comment by chris-deep** [comment]
I get the same issue.  Just trying to get the sample code to work at this point.  I only see the root level items, drop down for Menubar does not appear no matter what I try so far.

**Comment by bobhablutzel** [comment]
I found a solution to this which is to create an intermediate computed that holds the value I want in the nested object. For example: 

```
const loggedIn = computed( () => authHeader.value !== "" )
const signInLabel = computed( () => loggedIn.value ? "Sign out" : "Sign in")

const about = ref([
  { icon: 'pi pi-fw pi-user', items: [
      {label: signInLabel},
      {label: 'Register', disabled: loggedIn },
    ]
  },
])

```

Doing this gives me complete reactivity with a nested submenu

**Comment by wanglin86769** [comment]
I have the same issue, isn't there any solution after almost two years?

**Comment by wanglin86769** [comment]
MarioLiebisch's solution above works for me.

**Comment by AlpDemirSavas** [comment]
@wanglin86769 I could not understand MarioLiebisch's code. Can you share this part of your code or can you explain in details. Thank you.

**Comment by MarioLiebisch** [comment]
@AlpDemirSavas Instead of returning your menu contents as a computed value create a data entry and replace/overwrite this once you're updating things.

So instead of:
```ts
get menuItems() {
  return ["one", "two", "three"];
}
```
You'd do it this way:
```js
function UpdateMenu() {
  menuItems = ["one", "two", "three"];
}
```
