### ISSUE TITLE
Two issues when combining grouping and expansion in Datatable + possible fix

### ISSUE THREAD

**Issue by MadeMyDay** [primefaces/primevue#742]
I am using the datatable from PrimeVue 3.0.2. in grouped mode where the grouped rows also are expandable.

**Problem 1:**

When expanding a row which is in a group the rowspan ist set wrong. Reason is the grouping field column is removed from the row but columns.length remains the same in the template.

**Possible Fix**

In TableBody.vue where the expansion td and its rowspan are set:

```vue
<td :colspan="rowGroupMode === 'subheader' ? columns.length - 1 : columns.length">
```

**Problem 2**

If a group has expanded rows they stay visible even if the whole group is collapsed. Reason is that the expanded row has no connection to a possible grouping.

**Possible Fix**

Extend the v-if condition for the expandable row:

```vue
<tr class="p-datatable-row-expansion" v-if="templates['expansion'] && expandedRows && isRowExpanded(rowData) && (expandableRowGroups ? isRowGroupExpanded(rowData) : true)" :key="getRowKey(rowData, index) + '_expansion'">
```

**Altogether:**

```vue
<tr class="p-datatable-row-expansion" v-if="templates['expansion'] && expandedRows && isRowExpanded(rowData) && (expandableRowGroups ? isRowGroupExpanded(rowData) : true)" :key="getRowKey(rowData, index) + '_expansion'">
  <td :colspan="rowGroupMode === 'subheader' ? columns.length - 1 : columns.length">
    <component :is="templates['expansion']" :data="rowData" :index="index" />
  </td>
</tr>
```

**Comment by dheimoz** [comment]
thanks for sharing @MadeMyDay

**Comment by cagataycivici** [comment]
Could you please post your DataTable usage code so we can try to replicate it to begin with?

**Comment by MadeMyDay** [comment]
Hi @cagataycivici, you should easily see it with the following settings (stripped down for readability):

```vue
<DataTable
        :value="fields"
        v-model:expandedRows="expandedRows"
       :expandableRowGroups="true"
        v-model:expandedRowGroups="expandedRowGroups"
        rowGroupMode="subheader"
        groupRowsBy="fieldType"
        sortMode="single"
        sortField="fieldType"
        :sortOrder="1"
      >
        <Column
          field="fieldType"
          header="Type"
          :sortable="false"
        >
          <template #body="slotProps">
            {{ slotProps.data.fieldType }}
          </template>
        </Column>
        <Column
          field="label"
          header="Name"
          :sortable="false"
        />
        <Column
          field="templates"
          header="Element(s)"
          :sortable="false"
        >
          <template #body="slotProps">
            <div class="flex items-center">
              <div class="truncate mr-4">
                {{ slotProps.data.templates.length }}
              </div>
              <Button
                :label="getToggleLabel(slotProps.data)"
                class="p-button-text p-button-sm justify-self-end"
                @click="toggleRow(slotProps.data)"
              />
            </div>
          </template>
        </Column>
        <Column
          headerStyle="text-align: right"
        >
          <template #body="slotProps">
            <div class="flex justify-end">
              <Button
                label="edit"
                class="p-button-primary p-button-sm"
                @click="console.log(slotProps.data)"
              />
            </div>
          </template>
        </Column>
        <template
          #expansion="slotProps"
        >
          <DataTable :value="slotProps.data.templates">
            <Column
              field="fieldContextLabel"
              header="Label in element"
              sortable
            />
            <Column
              field="label"
              header="Element"
              sortable
            />
            <Column
              field="fieldName"
              header="Edit in Element"
              headerStyle="text-align: right"
            >
              <template #body="template">
                <div class="flex justify-end">
                  <router-link to=...>
                    <i
                      class="pi pi-pencil"
                    />
                  </router-link>
                </div>
              </template>
            </Column>
          </DataTable>
        </template>
        <template
          #groupheader="slotProps"
            {{ slotProps.data.fieldType }}
        </template>
      </DataTable>
```
While writing this I think I figured out why this happened to me. I don't have/want to have a dedicated expand icon at the beginning of the row. But since this is usually done with an own expander column this would explain why in my case one column is missing for the rowspan. Question is if the datatable component should recognize if an expander column is present or if the expansion is done "inline" like in my case.

The second problem (visible rows from the expansion even if parent is grouped/collapsed) is a still a bug imho.

With my modifications it looks like this:

Groups with "Textfield" expanded:

![image](https://user-images.githubusercontent.com/337699/101654223-8b0af080-3a40-11eb-8781-e02cd9695024.png)

Textfield first row expanded:

![image](https://user-images.githubusercontent.com/337699/101654335-b097fa00-3a40-11eb-95e9-1c00af1736ce.png)

As I said, the missing column may very well be the missing expander column. The second one would be still visible subtable in my screenshot (the brighter purple one) even if parent group is closed.

**Comment by cagataycivici** [comment]
Thanks, added for review in upcoming maintenance release.

**Comment by cagataycivici** [comment]
I'm afraid I can't resolve this without a case that can be executed, I'd really appreciate if yoıu fork our template below and send sample code that I can work on that demonstrates the case with some dummy data;

https://codesandbox.io/s/primevue-issue-template-v3-5tlbl

**Comment by tugcekucukoglu** [comment]
We cannot replicate the issue. Please try to use it with latest PrimeVue version. If the issue is still persist, please reopen this ticket with a codesandbox example.
