### ISSUE TITLE
[3.x] ConfirmationService with TS

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#767]
Hi!

First of all, congratulations for the awesome changes on this last 3.1.1 release! :tada: 

I have a small bug on my TypeScript project using PrimeVue 3.1.1, when I try to use ConfirmationService, there is an error importing it on `use` section:

```js
...
import ConfirmationService from 'primevue/confirmationservice';
...
...
app.use(ConfirmationService)
```

It fires this error:

```
Argument of type 'typeof import("/<project-path>/node_modules/primevue/confirmationservice")' is not assignable to parameter of type 'Plugin_2'.
  Property 'install' is missing in type 'typeof import("/<project-path>/node_modules/primevue/confirmationservice")' but required in type '{ install: PluginInstallFunction; }
```

I have to add any config in some `*.d.ts` file?

**Comment by pmenika** [comment]
I am also having the same issue. Anything you found to fix this?

**Comment by makurtu** [comment]
Nope, I'm still having this issue.

**Comment by ananni13** [comment]
Same issue here.

There are quite a few bugs in a lot of the components released in 3.1.1.

**Comment by avbentem** [comment]
As a workaround the following works for me, when added to `src/shims-vue.d.ts`:

```typescript
import {PluginFunction} from 'vue';

declare module 'primevue/confirmationservice' {
  export const install: PluginFunction<{}>;
}
```

My full `src/shims-vue.d.ts` currently reads:

```typescript
import {PluginFunction} from 'vue';

declare module '*.vue' {
  import type {DefineComponent} from 'vue';
  const component: DefineComponent<{}, {}, unknown>;
  export default component;
}

// TODO remove workaround; see https://github.com/primefaces/primevue/issues/767
// TS2345: Argument of type 'typeof import("(...)/node_modules/primevue/confirmationservice")'
// is not assignable to parameter of type 'Plugin_2'. Property 'install' is missing in type
// 'typeof import("(...)/node_modules/primevue/confirmationservice")' but required in type
// '{ install: PluginInstallFunction; }'.
declare module 'primevue/confirmationservice' {
  export const install: PluginFunction<{}>;
}
```

**Comment by ananni13** [comment]
Thanks @avbentem, that works.

I'm not sure if it warrants opening another issue since it's still related to the `ConfirmationService`, but the `useConfirm` import is also not working as it is presented in the docs:
```javascript
import { useConfirm } from 'primevue/useconfirm';
```

With that, I get this error:
```
ERROR  Failed to compile with 1 errors                                                                               10:30:11 PM

This dependency was not found:

* primevue/useconfirm in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=ts

To install it, you can run: npm install --save primevue/useconfirm
Issues checking in progress...

ERROR in src/App.vue:78:28
TS2307: Cannot find module 'primevue/useconfirm' or its corresponding type declarations.
    76 | import { computed, defineComponent, ref, watch } from 'vue'
    77 | import { useAxios } from '@vue-composable/axios'
  > 78 | import { useConfirm } from "primevue/useconfirm"
       |                            ^^^^^^^^^^^^^^^^^^^^^
```

If I import it like this, it works:
```javascript
import { useConfirm } from 'primevue/components/confirmation/useConfirm';
```

**Comment by makurtu** [comment]
Hi folks, I'm trying to implement @avbentem solution but no luck, it throws same error again.

On the other hand, I created this issue almost a month ago and there is no news from owners, I hope this project is still alive.

**Comment by ananni13** [comment]
@makurtu I changed my `shims-vue.d.ts` to this, works for me (basically the same as above, just moved the import inside):
```typescript
declare module '*.vue' {
  import { defineComponent } from 'vue'
  const component: ReturnType<typeof defineComponent>
  export default component
}

declare module 'primevue/confirmationservice' {
  import { PluginFunction } from 'vue'
  export const install: PluginFunction<{}>
}
```

**Comment by hognevevle** [comment]
@makurtu Actually it seems the missing type was added by the team [8 days ago](https://github.com/primefaces/primevue/commit/3a20c598ab5411079a63a77acc032fb79ad5e63c). They just haven't made any new releases for 8.x since then.

**Comment by dhax** [comment]
seems to be working fine now with ^3.1.2 without any of the above mentioned modifications to shims-vue.d.ts.

**Comment by pmenika** [comment]
I used Dialog in Primevue which has exact same confirmation box option.

**Comment by makurtu** [comment]
@dhax Okay, so I will close this issue. Thanks!
