### ISSUE TITLE
CDN links for V2 are pointing to V3 components

### ISSUE THREAD

**Issue by juanparati** [primefaces/primevue#768]
In the v2 documentation the CDN links are pointing to v3 of the components:

Example
https://unpkg.com/primevue/components/calendar/calendar.umd.min.js  (Points to https://unpkg.com/primevue@3.1.1/components/calendar/calendar.umd.min.js)

**Comment by tugcekucukoglu** [comment]
For PrimeVue 3 resolved in 3.2.0-rc.1 and for PrimeVue 2 it will be fixed in 2.4.0

For PrimeVue 2 correct internals

[https://unpkg.com/primevue@2.3.0/calendar/calendar.umd.min.js](https://unpkg.com/primevue@2.3.0/calendar/calendar.umd.min.js)
