### ISSUE TITLE
ObjectUtils.resolveFieldData() must not include Object.keys() condition

### ISSUE THREAD

**Issue by nestorrente** [primefaces/primevue#769]
In both versions 2 and 3, the method `ObjectUtils.resolveFieldData(data, field)` has the following preconditions:

```javascript
if (data && Object.keys(data).length && field) {
    // Do stuff...
} else {
    return null;
}
```

IMHO, it mustn't include the `Object.keys(data).length` condition, as long as the object `data` could have only non-enumerable properties, which are no returned by `Object.keys()` (i.e., inherited ones or symbol properties), and that doesn't mean that the result of getting one of those properties shall be `null`.

I know this is a breaking change that solves a very rare use case, but I wanted to notify about it.

**Comment by cagataycivici** [comment]
I remember it was added to fix a common case, I'm afraid I can't remember the reason so unless there are major issues with this, we'd like to keep it as it is. I think this code is also same in PrimeNG and PrimeReact with no complaints so far.
