### ISSUE TITLE
Modal dialog not blocking background

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#77]
I have the following modal:
```
<Dialog v-if="createRowVisible" :visible.sync="createRowVisible" 
        header="Add contact" :modal="true">
	<CreateContactForm @on-cancel="hideCreateDialog" @on-success="rowCreated" />
</Dialog>
```
When modal is opened the background is not blocked and I can still manupulate anything outside of the modal modal.

Also it would be nice if blocked backgroud gets dimmed. So users know it is blobked.
Thank you.

**Comment by cagataycivici** [comment]
It seems dimmed for me, at least on showcase, we'll apply the trapFocus we had on other Prime dialogs like NG has.
