### ISSUE TITLE
Need to have a top navigator component

### ISSUE THREAD

**Issue by voquanghoa** [primefaces/primevue#771]
I often need to implement the top navigator component for my projects but I see the one from Vuew Showcase website looks nice. Could you extract it to a component and include it to the library.

![image](https://user-images.githubusercontent.com/10450325/101976476-32259d00-3c78-11eb-87bf-a509230eaa25.png)

Thank you very much.

**Comment by dheimoz** [comment]
Hello @voquanghoa I wonder if the toolbar component suits your needs? https://primefaces.org/primevue/showcase/#/toolbar

That is what I use to create the main navigator.

**Comment by voquanghoa** [comment]
> Hello @voquanghoa I wonder if the toolbar component suits your needs? https://primefaces.org/primevue/showcase/#/toolbar
> 
> That is what I use to create the main navigator.

Thanks for replying. The Toolbar component has another usage thing because of its appearance.

```
Toolbar is a grouping component for buttons and other content.
```

Of cause, I can put the links into a toolbar but it's quite bad

**Comment by dheimoz** [comment]
Another option is using PrimeFlex and setup a div with your icons and menus.
https://primefaces.org/primevue/showcase/#/primeflex
 
https://primefaces.org/primevue/showcase/#/grid

**Comment by voquanghoa** [comment]
> Another option is using PrimeFlex and setup a div with your icons and menus.
> https://primefaces.org/primevue/showcase/#/primeflex
> 
> https://primefaces.org/primevue/showcase/#/grid

Thanks for replying, in fact, we have many issues to do so, like the appearance, hide/show menu, highlight links, responsive. 

The problem is not how to implement it, the problem is do we have it as default.

For example in some other libraries, we have it:

- https://coreui.io/docs/components/header/
- https://bootstrap-vue.org/docs/components/navbar
- https://vuematerial.io/components/drawer
- https://mdbootstrap.com/docs/vue/navigation/navbar/
- https://quasar.dev/vue-components/toolbar
- https://vuetifyjs.com/en/components/navigation-drawers/#mini-variant
- https://vuesax.com/docs/components/Navbar.html#default
- https://element.eleme.io/#/en-US/component/menu
- https://josephuspaye.github.io/Keen-UI/#/ui-toolbar

It's not easy to compare with a library is better than another in some words, for me, I still love to use PrimeVue (that's why I'm here and open an issue). But this component is missing from the library is true and I am really want to have it as default,

Thank you very much

**Comment by StitiFatah** [comment]
Same request, I checked the issues just for that tbh, I discovered PrimeVue few months ago when starting using Vue3 and have used it to for a project before going back to Vue2 (and BoostrapVue ) for another one . Honestly PrimeVue feels better ( and seems to have more and more high quality components ) but I don't understand why it lacks such a "basic" component.

**Comment by voquanghoa** [comment]
> Same request, I checked the issues just for that tbh, I discovered PrimeVue few months ago when starting using Vue3 and have used it to for a project before going back to Vue2 (and BoostrapVue ) for another one . Honestly PrimeVue feels better ( and seems to have more and more high quality components ) but I don't understand why it lacks such a "basic" component.

Thanks for repying. I hope the author will consider this one after the New Year holiday 👍 

Happy New Year to you as well 🎉🎉🎉🎉

**Comment by The-Bright-Lord** [comment]
+1, At least need to make the Menubar sticky and take up the full space of the top area and the grid should adjust accordingly

**Comment by cagataycivici** [comment]
This and many more will be provided by the upcoming PrimeBlocks, there will be various alternatives. Stay tuned.

**Comment by mariusa** [comment]
Hi, any update on PrimeBlocks? Just discovered PrimeVue (coming from BootstrapVue), surprised it doesn't have a top navbar too like the other libs mentioned above. Thanks.

**Comment by mariusa** [comment]
@cagataycivici Which free component from https://www.primefaces.org/primeblocks-ng/#/  provides the requested top navigator component?

**Comment by lpares12** [comment]
@mariusa Did you find something? All I could find was the paid blocks here https://www.primefaces.org/primeblocks-vue/#/application/navbar.
I think there is no free component for a navbar.

**Comment by Michael2109** [comment]
Does it look like this feature will be added? This is a common feature in many components libraries. 
It doesn't seem right that the only solution you're offering is for us to pay for PrimeBlocks. An app header is a pretty common component used in a webpage.

**Comment by antdking** [comment]
at least it was the first feature I went to add so didn't waste much time here

**Comment by Luferov** [comment]
Any status? I can't find Clipped drawer in primevue and it very sad.
