### ISSUE TITLE
Any RTL (right to left) support?

### ISSUE THREAD

**Issue by eladcandroid** [primefaces/primevue#772]

**Comment by cagataycivici** [comment]
Yes, we are planning to add this to showcase in the near future. As a side note, please use forum or discord channel for questions to receive faster responses.

**Comment by nabizadeh84** [comment]
> Yes, we are planning to add this to showcase in the near future. As a side note, please use forum or discord channel for questions to receive faster responses.

Hi,
Also In need for RTL Support In DataTable.
it is a good new for your planning and I hope to do that in near time.

**Comment by brahimoulhaj** [comment]
Hi,
Please is there any news about RTL support ?

**Comment by hamza202** [comment]
RTL ??

**Comment by morteza-mortezai** [comment]
Hi ,
is RTL supported now ?

**Comment by mhelmydiab** [comment]
Urgently Needing RTL Support

**Comment by pcm0nk** [comment]
is this on Primeroadmap or its just planned for future ?

**Comment by Imadozone** [comment]
Unfortunately, I won't be able to use this library without RTL support. 
I am moving away to Quasar Dev :(

**Comment by Bahramudin** [comment]
Hi any RTL support? Or let us go with Quasar?

**Comment by saleh-gholamian** [comment]
Don't wait, if it is added it is unlikely to be available in the free version!
Prime is great but not for free.
I also go to Quasar.

**Comment by benfodil** [comment]
its 2024 we need RTL right now, guys come on

**Comment by Bahramudin** [comment]
@benfodil As it seems, they do not have plan to any RTL support. It is better to not wait and waste the time, recommend to go with Quasar.

**Comment by benfodil** [comment]
@Bahramudin i use vuetify btw its great but i will see quasar thanks

**Comment by alwaqfi** [comment]
Sadly, they pushed the RTL Mode support to the end of Q4 this year. For me, I can't wait for that (Maybe it will get delayed again) and will be checking Quasar and Vuetify.

**Comment by HazNet** [comment]
its 2024 we need RTL right now, guys come on
