### ISSUE TITLE
2.x Incorrect menu positioning inside DataTable

### ISSUE THREAD

**Issue by ilyavaiser** [primefaces/primevue#794]
![image](https://user-images.githubusercontent.com/1227366/102271868-f79a5980-3f30-11eb-9fea-3d6e2d620701.png)

The menu is not being placed where it should be. Goes beyond the layout and creates scrolling. This is fixed by forcibly changing the positioning of the DataTable to static

```
<template lang="pug">
  DataTable
    template(#columns)
      Column(bodyStyle="text-align: right;")
        template(#body="slotProps")
          Button.p-button.p-button-icon.p-button-icon-only(
            @click="toggle($event, slotProps.data.id)"
            )
            span.icon-settings
          Menu(ref="menu" :model="contextMenuItems" :popup="true")
</template>
```

**Comment by rafaeljosem** [comment]
Same issue in version 3.x of prime vue

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.0, please try with the latest version available and create a new ticket if issue persists so that we can work on it again. Thank you.
