### ISSUE TITLE
[3.x] Datatable exporting template #body to CSV

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#798]
Hi!

It is not an issue, but an enhancement. What do you think about exporting `<template #body="slotProps">` instead of `field` value?
I use a function to format dates in `bdoy` and when I export Datatable to CSV it exports unformated data like `2012-01-09T23:00:00.000000Z`.

My template function is very simple:

```js
<Column field="startDate" :sortable="true" header="Start Date">
     <template #body="slotProps">
            {{ formatDate(slotProps.data.startDate) }}
     </template>
</Column>
```

Now Datatable exports data like this: `field['startDate']` and obviously it is not formated.

**Comment by cagataycivici** [comment]
I can see an exportFunction available in v3 branch so this seems to be available already.
