### ISSUE TITLE
[Bug] Error import ScrollTop component

### ISSUE THREAD

**Issue by tamnguyen02121993** [primefaces/primevue#799]
Hi,
I have discovered a issue when i'm trying to import ScrollTop component. I try to rename `scrolltop.vue` to` scrolltop.js` in `node_modules` and it work
Version: **3.1.1**
Vue: 3.x
Hope this issue will be fixed on next release.
Thanks

**Comment by cagataycivici** [comment]
New build fixed this issue, thank you.
