### ISSUE TITLE
Transpile ObjectUtils.js when installing from npm

### ISSUE THREAD

**Issue by fooflare** [primefaces/primevue#8]
Hi, this is not really an issue but a proposal to avoid an error:

```
ERROR  Failed to compile with 1 errors

error  in ./node_modules/primevue/components/utils/ObjectUtils.js

Module parse failed: Unexpected token (134:29)
You may need an appropriate loader to handle this file type.
|     }
| 
>     static filterConstraints = {
| 
|         startsWith(value, filter) {
....
```
This is caused by babel-loader that by default ignores node_modules folder, so this file is not transpiled. This error doesn't affect every component but those that are dependent of this file.

I think in the README file there could be an advice about adding to the `vue.config.js` file of the project:

```
module.exports = {
    [...,]
    transpileDependencies: [
        "primevue"
    ]
}
```
to get this file transpiled by the vue cli. Source: https://cli.vuejs.org/config/#transpiledependencies

Thank you and regards.

**Comment by cagataycivici** [comment]
Could you please try with 1.0.0-beta.2?

**Comment by fooflare** [comment]
Nice, in beta2 is working without this option. I'm sorry for not realizing about this new release and have tried it before opening this issue.

Thanks and regards.

**Comment by cagataycivici** [comment]
Thanks for the heads up, we've just done beta.3 which ships transpiled code for the js files we use so it is now even better.
