### ISSUE TITLE
Feature request: Components/content within menuitems (especially in MegaMenu)

### ISSUE THREAD

**Issue by djpretzel** [primefaces/primevue#805]
This might not make as much sense for the other menu components, but for megamenus it's nice to have (much) more control over the contents of the menu dropdowns, including the ability to include other components/logic within the "item" - see http://meganavbar.com/B4/ for a particularly robust implementation. Also nice to be able to explicitly specify full-width menu dropdowns, and mix/match such that some menu items are "mega" and others are standard dropdowns (or tiered/multilevel)

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primevue/issues/1244
