### ISSUE TITLE
InputNumber not immediately returning data

### ISSUE THREAD

**Issue by RichWK** [primefaces/primevue#806]
Hello — I'm using 3.1.1 and have my component set up like this:

`<InputNumber v-model="userInput" @blur="onBlur" />`

The prop looks like this:

`userInput: null`

And the method looks like this:

```
onBlur() {
    console.log( this.userInput );
    setTimeout( () => { console.log( this.userInput ) }, 500 );
}
```

The first log returns _null_ (when I would expect it to return the field's value) and the second log returns the correct value (I entered '2019' into the field).

Is this a bug or am I doing something wrong?

**Comment by tugcekucukoglu** [comment]
Please check [#506](https://github.com/primefaces/primevue/issues/506). If the problem persists, please reopen this issue.
