### ISSUE TITLE
Version 3.1.0 is missing files chip.d.ts and chip.js in "./node_modules/primevue" (seems like a bug)

### ISSUE THREAD

**Issue by mirupal** [primefaces/primevue#807]
Using the typescript example project as base.

Not sure if I am missing something, but tried to use Chip which was giving me an error in IDE (VSCode) and on build.

Fixed temporarily by adding and adjusting the files accordingly to location of Chip component.

**Comment by fairking** [comment]
Try to remove all content of `/node_modules/` folder and run `npm install`. I had similar issues with Primevue and I guess it could be a cache.

**Comment by cagataycivici** [comment]
Seems to be a duplicate;

https://github.com/primefaces/primevue/issues/781

**Comment by mirupal** [comment]
This didn't help. Same result - the mentioned files are missing.

The files are also missing in `https://github.com/primefaces/primevue/tree/3.1.1/exports`.

I'm on OSX using yarn and `primevue 3.1.1` but had same result with `primevue 3.1.0` .


steps before running `yarn install`
- removed dir `node_modules` from project dir and run `yarn install`
- cleared npm cache with `npm cache clean --force`
- cleared yarn cache with `yarn cache clean`
- removed everything primevue related from `~/.npm/`


package.json dependencies:
```json
 "dependencies": {
    "@fullcalendar/core": "^5.4.0",
    "@fullcalendar/daygrid": "^5.4.0",
    "@fullcalendar/interaction": "^5.4.0",
    "@fullcalendar/timegrid": "^5.4.0",
    "apexcharts": "^3.23.0",
    "chart.js": "^2.9.4",
    "core-js": "^3.6.5",
    "highcharts": "^8.2.2",
    "mitt": "^2.1.0",
    "primeflex": "^2.0.0",
    "primeicons": "4.0.0",
    "primevue": "3.1.1",
    "vue": "^3.0.3",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "4",
    "vue3-apexcharts": "^1.1.1",
    "vue3-highcharts": "^0.1.3",
    "vuex": "^4.0.0-rc.2"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3"
  }
```
