### ISSUE TITLE
Data TAbla editable dont update data; 

### ISSUE THREAD

**Issue by nicolecortes** [primefaces/primevue#809]
I am using the vue and primevue versions:
**"primevue": "3.1.1",
 "vue": "3.0.4"**
 
I am having a problem when editing a table value. When I press the "TAB" and "INTRO" button it  **is supposed to capture this new value** but it is actually getting the old value, at the beginning it is left with the default value (0). The data update only works when I click, but TAB and INTRO do not update the data, I do not know if it is a bug but so far the editable DataTable is not working as it should. In the example on the page they use an "InputText" but it is useless to use this element since the entered values must be decimal.

Does anyone know how to solve this problem? the only difference I see is that I am using an **"InputNumber"** instead of an **"InputText"**, but it should still capture the value  

```
 <DataTable :value="ingresoDato" editMode="cell" @cell-edit-complete="onCellEditComplete($event, 1)" class="editable-cells-table">
              <Column v-for="col of columnas" :field="col.field" :header="col.header" :key="col.field">
              <template #editor="slotProps">
                      <InputNumber :modelValue="slotProps.data[slotProps.column.props.field]"    @update:modelValue="onCellEdit($event, slotProps)"
                    :disabled="col.field=='numero'" mode="decimal" :minFractionDigits="1" :maxFractionDigits="1" />
              </template>
      </Column>
</DataTable>
```

**Comment by tugcekucukoglu** [comment]
Hi,
It looks like you need to use v-model instead of :modelValue for InputNumber.  Also you can ask your question on the forum.

Best,
