### ISSUE TITLE
Why some componentes are not available to vue 2? (QUESTION)

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [primefaces/primevue#810]
Hi, thanks to the hard work with the components, I noticed that some components are not available to Vuejs2, only for vuejs3, is not possible to develop them that are compatible with both versions?

I tried to use Vue3 for now I give up, lot of bugs during the migration, I back to Vue2, I intend to use Vue 3 in the future but also I'd like to use some components such as Avatar which is taged as "New" on the page and it's only available to Vue3.

are you going to abandon all vuejs 2 components?

![image](https://user-images.githubusercontent.com/3034127/103050048-11abeb80-4572-11eb-9d44-ba919bc1745b.png)

**Comment by ilyavaiser** [comment]
Vue3 is cool, but I would like to see more support for version 2.

**Comment by cagataycivici** [comment]
They are being worked on in 2.x. branch, PrimeVue 2.x branch is actively maintained/developed and will be in 2021 as well.

https://github.com/primefaces/primevue/tree/2.x

P.S. Please use discord or forum for questions.
