### ISSUE TITLE
[3.1.1] import primevue/useToast in TypeScript throws CaseSensitivePathsPlugin error

### ISSUE THREAD

**Issue by avbentem** [primefaces/primevue#813]
Using the following, **which works fine for other components**, makes WebStorm or webpack complain on macOS APFS:

```typescript
// Error: 
import { useToast } from 'primevue/useToast';
```

```text
Module not found: Error: [CaseSensitivePathsPlugin] `[..]/node_modules/primevue/useToast.js` does not match the corresponding path on disk `usetoast.js`.
```

Also, `yarn serve` would fail with:

```text
ERROR  Failed to compile with 1 error

This dependency was not found:

* primevue/useToast in ./src/path/to/my/code.ts

To install it, you can run: npm install --save primevue/useToast
```

Same errors for a fresh Git clone followed by `yarn install`.

Changing the import like below works just fine:

```typescript
// Workaround: full path instead of 'primevue/useToast'
import { useToast } from 'primevue/components/toast/useToast';
```

And aside, on macOS APFS lowercasing the `t` like the following _seemed_ to work as well. But this would still fail on more strict (Linux) file systems, such as in a Docker `node:lts-alpine` build image:

```typescript
// Wrong: lower case first t in usetoast
import { useToast } from 'primevue/usetoast';
```

**Comment by tugcekucukoglu** [comment]
This issue fixed with PrimeVue 3.2.0 .
