### ISSUE TITLE
Dialog's close Icon not working and out-focused clicking not closing the dialog

### ISSUE THREAD

**Issue by Mrbeyond** [primefaces/primevue#815]
The close icon on the header is not working but the the maximize works well, also when :modal option is used and the Dialog is not clicked but the transparent background around, the Dialog does not close as well jus like the usual modal.

I've created the demo on codesandbox to if needed.
LINK:   https://n7vb3.csb.app;
version 3.1.1
Please I need help with this.

**Comment by tugcekucukoglu** [comment]
Hi,
[https://sofp9.csb.app/](https://sofp9.csb.app/)

You can use v-model instead of v-bind.

**Comment by samcyn** [comment]
@Mrbeyond  for some reason some things are not well documented in primevue docs. I had to dive into their codebase to see what is going on..
to close the dialog simply use this event @update:visible.

something like this 
`<Dialog
      header="Header"
      v-bind:visible="shows"
      :modal="true"
      :style="{ width: '60vw' }"
      @update:visble="hideHandler"
    >`
   then in your methods handle "hideHandler" like this 
`hideHandler(value) {
   if (!value) {
     this.shows = false;
}
}`

Note if you're using vue3 handle this in your setUp method.

**Comment by michal-miler** [comment]
Thanks @samcyn for your tip. A little note: you have a typo in `@update:visible="closeModal"`

So:

```
<Dialog
          header="Header"
          :visible="shows"
          :modal="true"
          @update:visible="hideHandler"
>
```

**Comment by andrew-d-moore** [comment]
This should be in the documentation for sure.

**Comment by SinusQuell** [comment]
I wonder why this issue has been closed when it's still not fixed?

**Comment by yeasir2148** [comment]
**"Having to use v-model insead of v-bind"** - is this in the documentation? If not, this should be mentioned in the documentation as a note or waring or something. I just spent a few hours trying to debug why this was not warning. If it's already there, i am sure it is not very obvious.

**Comment by GuilhermeLimaSP** [comment]
A little comment in the documentation would have to help me save several minutes...
