### ISSUE TITLE
DataTable perPageDropdown not loading properly when clicked

### ISSUE THREAD

**Issue by abhayjai1** [primefaces/primevue#816]
Hi @cagataycivici : Hope you are doing awesome!

**Use Case:** I'm using primevue DataTable and passing `RowsPerPageDropdown` with `paginatorTemplate` as I want to enable the per page dropdown inside my table. My demo code is like below-

`<DataTable 
      :rows="10"
      :pageLinkSize="10"
      :rowsPerPageOptions="[10, 20, 50]"
      :alwaysShowPaginator="false"
      paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
      :totalRecords="tableData?tableData.length:0"
      currentPageReportTemplate="(Showing page {currentPage} of total {totalPages} pages)">
`

After doing above, I'm able to see the dropdown on UI as shown below-
![image](https://user-images.githubusercontent.com/12663877/103359141-56d59d80-4add-11eb-9a38-53134de69563.png)

The above DataTable code is present in one of the vue component called DataTable.vue and this I'm using as a web component at various places and in one of the Angular application. 

**Issue:** As I mentioned, the dropdown is visible in my angular app UI but when I click on it, it doesn't open properly means it just come and go away in microseconds. I can see the passed values as an array to load under that dropdown. Not sure what's wrong.

**Things I've tried-** I tried using the `<Paginator :rowsPerPageOptions="[10, 20, 50]">` also by following the official documentation but same issue. Applied all required CSS to my local still no success. I removed the currently installed Primevue version 1.0.4 and installed the latest V 2.2.3 but no luck.

In one of the GitHub issue of Primevue, I noticed another user raised the same defect where he had some issue with dropdown display and you fixed it in version 1.0.2 I think and currently I'm using primevue version 1.0.4 still this issue. 

Please help ASAP. Thanks much!

**Comment by abhayjai1** [comment]
Hi @cagataycivici, Today I debugged the Dropdown.vue file under Primevue and could notice that in my case, when I click on the dropdown, the `show()` method is called and `overlayVisible` property is set to true but instantly, the `hide()` method is also called from `bindOutsideClickListener()` method which is being called from `onOverlayEnter()` method - resulting the dropdown to be hidden and the dropdown is going away. 

I don't know how the dropdowns are working in official docs/demos. 
I'm using Primevue version 1.0.4. Also, tried with copying the latest code of Dropdown.vue to local but in that case I was getting another error "Cannot read property style of null" from `onOverlayEnter()` method.

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue, please try with the latest version available and create a new ticket if issue persists so that we can work on it again. Thank you.
