### ISSUE TITLE
Improve active route detection in TabMenu

### ISSUE THREAD

**Issue by noamichael** [primefaces/primevue#830]
Previously, #417 covered the issue where `<TabMenu/>` items were only consider active if the route path matched the item route exactly (`===` vs. `startsWith`). This was fixed in commit 7fb409d6acd494475a437e92b37c496165b73b16`:

```js
isActive(item) {
    return this.activeRoute.startsWith(item.to);
}
```

However, since commit 3f2b51a4870aceb993f550df68f16cba9953d2d3,  the route match has reverted back to using exact matches only:

```js
isActive(item) {
     return this.activeRoute === item.to;
}
```

I believe this is a regression and there should at least be an option to determine if the match should be exact or fuzzy [much like the official vue router](https://router.vuejs.org/api/#exact).

**Comment by cagataycivici** [comment]
There is a new property called **exact** to decide if route matching should be exact or not.

**Comment by namcodes** [comment]
```
  <TabMenu :model="subsTrackerTypes.tabs"
               :exact="false"
               v-model:activeIndex="activeIndex"
      />
```
how to exact false? i want to use v-model:activeIndex
