### ISSUE TITLE
Splitter for v2

### ISSUE THREAD

**Issue by bdbusch** [primefaces/primevue#831]
I can't seem to get any of the popular splitters (https://openbase.io/categories/js/best-vue-split-pane-libraries?orderBy=RECOMMENDED&) to work with the Babylon template. 

The events _fire_, but nothing moves. 

I see you have a working splitter in 3, is that going to be backported? I can't jump to vue3 yet due to some "legacy" component dependencies. 

Thanks.

**Comment by cagataycivici** [comment]
Please see;

https://www.primefaces.org/primevue-2-3-0-brings-12-new-components-for-vue-2/
