### ISSUE TITLE
Vue3: Accordion doesn't work when loaded asyncronously

### ISSUE THREAD

**Issue by maherma-adg** [primefaces/primevue#836]
Accordion is not rendered when loaded as asynccomponent on Vue3

This code doesn't work
```
import { defineAsyncComponent as dac } from 'vue'
const Button = dac(() => import('primevue/button'))
const Accordion = dac(() => import('primevue/accordion'))
const AccordionTab = dac(() => import('primevue/accordiontab'))
```

This code do
```
import { defineAsyncComponent as dac } from 'vue'
const Button = dac(() => import('primevue/button'))
import Accordion from 'primevue/accordion'
import AccordionTab from 'primevue/accordiontab'
```

others components as Button, InputText, Checkbox, etc... can be loaded sync or async as you wise

Manuel

**Comment by mrichar1** [comment]
Seeing the same problem with TabPanel and TabView

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1, please try with the latest version available and create a new ticket if issue persists so that we can work on it again. Thank you.
