### ISSUE TITLE
components path of v2.3.0 is diffrent from other version , on unpkg.com

### ISSUE THREAD

**Issue by west-farmer** [primefaces/primevue#838]
No "components" in the path of v2.3.0

as a compare:
https://unpkg.com/browse/primevue@2.3.0/accordion/
https://unpkg.com/browse/primevue@2.2.3/components/accordion/
https://unpkg.com/browse/primevue@3.1.1/components/accordion/

Is a issue or design ?

**Comment by cagataycivici** [comment]
Yes, internals have been changed, there is no components folder anymore.

**Comment by west-farmer** [comment]
Thanks , I will change references of  my project.
