### ISSUE TITLE
Add p-placeholder to Dropdown label

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#84]
Would like to apply a custom style to the placeholder text but I cannot see any difference between empty label and selected label. I would like to apply `opacity` to the placeholder.
See what I've got now:
![Screenshot_7](https://user-images.githubusercontent.com/13495631/68535385-c7e64e80-0339-11ea-9d0f-17eb0f92bf53.png)

And what I would like to achieve:
![Screenshot_8](https://user-images.githubusercontent.com/13495631/68535405-2d3a3f80-033a-11ea-9dad-ba928538c54c.png)

"primevue": "1.0.0-beta.12"

**Comment by denis-pujdak-adm-it** [comment]
The `AutoComplete` placeholder looks fine. Opacity is missing on `Dropdown` and `MultiSelect` components.

**Comment by cagataycivici** [comment]
With beta.14 you can use .p-placeholder class to add opacity.
