### ISSUE TITLE
primevue/fieldset not found V2

### ISSUE THREAD

**Issue by zsuzsmuzs** [primefaces/primevue#842]
I just updated primevue to v2.3.0 and now I get the above error message.

Would be great if you could fix this.

**Comment by maydinbil61** [comment]
Use this İmport fieldset from "primevue/fieldset/fieldset'"

**Comment by zsuzsmuzs** [comment]
Works, Thank you :)

**Comment by renathoaz** [comment]
how can I import it using nuxt ?

It is not working setting it on components.
By the way there's no locale option for nuxt config.
```

nuxt module:
primevue: {
    locale ????? is there a option ?
    theme: 'pontovani',
    ripple: true,
    components: [ 'Fieldset'
    ],
    directives: ['Tooltip'],
  },

```

**Comment by tugcekucukoglu** [comment]
Related to this issue [#860 ](https://github.com/primefaces/primevue/issues/860)
