### ISSUE TITLE
Knob replaceAll causes issue with nuxt SSR

### ISSUE THREAD

**Issue by elliottross23** [primefaces/primevue#844]
I'm trying to use primevue in NuxtJS with SSR and have it working but the Knob component throws the error `this.valueTemplate.replaceAll is not a function`

Since replaceAll is not available in browser javascript this line could be replaced with `this.valueTemplate.replace(/{value}/g, this.value);` and would then work in both nodejs and browser environments.

**Comment by cagataycivici** [comment]
Fixed for v3, will be ported to v2 as well. Thank you.

**Comment by thearabbit** [comment]
+1

**Comment by JohannesSchwegler** [comment]
> I'm trying to use primevue in NuxtJS with SSR and have it working but the Knob component throws the error `this.valueTemplate.replaceAll is not a function`
> 
> Since replaceAll is not available in browser javascript this line could be replaced with `this.valueTemplate.replace(/{value}/g, this.value);` and would then work in both nodejs and browser environments.

how did you set it up? i get an error when i run it with ssr: true

**Comment by elliottross23** [comment]
@JohannesSchwegler here's the relevant parts of my `nuxt.config.js`

I'm using `"nuxt": "^2.14.6"` in my `package.json`

```
export default {
   target: 'server',
   ssr: true,
   modules: ['primevue/nuxt'],
   build: {
      transpile: ['primevue']
   },
   primevue: {
      theme: 'saga-blue',
      ripple: true,
      components: [/* What components you want */]
   }
}
```

**Comment by thearabbit** [comment]
@elliottross23, very thanks. It work fine for me too.
```
"nuxt": "^2.15.3"
"primevue": "^2.4.0"
```
