### ISSUE TITLE
Style and class is a reserved attribute and cannot be used as component prop

### ISSUE THREAD

**Issue by sandanat** [primefaces/primevue#857]
Primevue version: >=3
Error: "Style and class is a reserved attribute and cannot be used as component prop"

Steps to reproduce:
1. [Open repo](https://codesandbox.io/s/primevue-3x-2gpjc)
2. Open console
3. Detect error

![image](https://user-images.githubusercontent.com/49751869/104460323-02dbb600-55bf-11eb-9dee-98d3feb1c870.png)

**Comment by cagataycivici** [comment]
You need to use PrimeVue 2.x with Vue 2.x. Use PrimeVue 3.x only if you are on Vue 3.x.

**Comment by sandanat** [comment]
> You need to use PrimeVue 2.x with Vue 2.x. Use PrimeVue 3.x only if you are on Vue 3.x.

Yes, it works fine. Sorry for my mistake.
However, what is the purpose of manual class and style forwarding to the root element? This is a default vue behavior (see [details](https://v3.vuejs.org/guide/class-and-style.html#with-components))
