### ISSUE TITLE
ConfirmPopup : useConfirm define target is missing in ts

### ISSUE THREAD

**Issue by Zaaaoo** [primefaces/primevue#859]
In my setup :
```
const cancelCreate = (event: any): void => {
  confirm.require({
    message: 'Etes vous certain de vouloir annuler la création ?',
    icon: 'pi pi-exclamation-triangle',
    rejectLabel: 'Non',
    acceptLabel: 'Oui',
    accept: () => {
      router.push('accueil')
    },
    reject: () => {
      console.log('Reject')
    },
  })
}
```
It would be nice to add the possibility to define the target when we use `useConfirm()`
Without target we cannot use this component
Unless we can define it on the Component? `<ConfirmPopup></ConfirmPopup>`

The actual useConfirm don't have target properties :
useconfirm.d.ts :

```
export declare function useConfirm(): { 
    require(args:{ 
        message?: string;
        group?: string;
        icon?: string;
        header?: string;
        accept?: Function;
        reject?: Function;
        acceptLabel?: string;
        rejectLabel?: string;
        acceptIcon?: string;
        rejectIcon?: string;
        blockScroll?: boolean;
        acceptClass?: string;
        rejectClass?: string;
    }): void 

    close(): void 
}
```

![image](https://user-images.githubusercontent.com/70746510/104900110-f3bc8580-597b-11eb-8c9c-74a41465c2d9.png)

**Comment by mewforest** [comment]
Same here.. Any updates?

`Uncaught (in promise) TypeError: Cannot read property 'offsetHeight' of undefined
    at Function.absolutePosition (utils.esm.js?dd76:177)
    at Proxy.alignOverlay (confirmpopup.esm.js?9421:96)
    at Proxy.onEnter (confirmpopup.esm.js?9421:80)
    at eval (runtime-dom.esm-bundler.js?830f:551)
    at Object.enter (runtime-core.esm-bundler.js?5c40:2398)
    at Array.eval (runtime-core.esm-bundler.js?5c40:3942)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?5c40:355)
    at flushJobs (runtime-core.esm-bundler.js?5c40:391)`
