### ISSUE TITLE
Nuxt integration

### ISSUE THREAD

**Issue by phr3nzy** [primefaces/primevue#86]
Implementing PrimeVue with Nuxt currently requires a tedious workaround. Would be nice if there was a module for it.

**Comment by cagataycivici** [comment]
Maybe we can provide a sample github project example, I'll discuss with my colleagues, thank you.

**Comment by cagataycivici** [comment]
There is a quickstart;
https://github.com/primefaces/primevue-nuxtjs-quickstart

We've also added documentation on integration.
https://github.com/primefaces/primevue/commit/8ff1ca42ad9373eaade7b6a0f6f69862abf312b3

**Comment by antpv** [comment]
> There is a quickstart; https://github.com/primefaces/primevue-nuxtjs-quickstart
> 
> We've also added documentation on integration. [8ff1ca4](https://github.com/primefaces/primevue/commit/8ff1ca42ad9373eaade7b6a0f6f69862abf312b3)

When your change ssr property as true in nuxt.config, its crashed. Why do we need an example how to use primevue with Nuxt without ssr?
