### ISSUE TITLE
primevue/fieldset not found

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#860]
When I installed primevue 2.3.0 using "npm install" command, "node_modules/primevue/fieldset/index.js" file was missing, and the following error information was displayed.

This dependency was not found:
* primevue/fieldset in ./src/main.js
To install it, you can run: npm install --save primevue/fieldset

**Comment by bdbusch** [comment]
I also have the same thing. I purchased the Babylon Admin template as well, which uses it.

**Comment by cagataycivici** [comment]
PrimeVue 2.4.0 will move to a new build as PrimeVue 3.2.0 so this should be fixed as well.

**Comment by bfleming-ciena** [comment]
I'm sorry, what's actually the solution to this dependency error that can't be fixed?
