### ISSUE TITLE
"Clear" button in Calendar wrongly labeled

### ISSUE THREAD

**Issue by abinadi** [primefaces/primevue#863]
When the button bar is enabled in the Calendar, it shows "Today" twice. It should have "Today" on the left and "Clear" on the right.

The screenshot is from: https://primefaces.org/primevue/showcase/#/calendar

![Screenshot from 2021-01-16 01-51-24](https://user-images.githubusercontent.com/1260758/104806478-6f141080-579d-11eb-9d0f-c2bb7262ca5b.png)

**Comment by galaxyblur** [comment]
Seconded (v2.3.0)

**Comment by cagataycivici** [comment]
Fixed for V3, will be ported to 2.x as well.

**Comment by dmoore2** [comment]
This looks like it will be fixed in release 2.4, when will this be released?
