### ISSUE TITLE
How to register a plugin in PrimeVue Chart?

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#867]
Hi everyone

I am having problems with registering plugins in the Charts (https://www.primefaces.org/primevue/showcase-v2/#/chart)

Based on the documentation from Chart.js I need to register the plugin first (https://www.chartjs.org/docs/latest/developers/plugins.html#using-plugins)
Eg:
```
var chart1 = new Chart(ctx, {
    plugins: [plugin]
});
```
If I simply use options it doesn't work.
```
options: {
    plugins: {
        ...my...plugin...settings...here...
```

Would be nice to mention it in the documentation. Thanks.

As an example I would like to register the following plugin: https://www.npmjs.com/package/chartjs-plugin-crosshair

Thanks for any help.

**Comment by cagataycivici** [comment]
Please use discord or forum for questions, thank you.

**Comment by fairking** [comment]
Thanks @cagataycivici . Will do. Apologize if it's not a big case.

**Comment by cagataycivici** [comment]
We now use chart js v3 so the docs need to be updated accordingly.

**Comment by baxsmaxbax** [comment]
So, is there answer about registering plugin for ChatJS?

**Comment by FlipWarthog** [comment]
@baxsmaxbax Chart now has a `plugins` prop for registering ChartJS plugins. See API docs: https://primevue.org/chart/

**Comment by baxsmaxbax** [comment]
Here's the way I'm trying:
```
<template>
	<Chart type="line" :data="chart_data" :options="basicOptions" :plugins="['ChartAnnotation']" />		
</template>

<script>
import Chart from 'primevue/chart';
import * as ChartAnnotation from 'chartjs-plugin-annotation';
</script>
```
But it doesn't work for me.

**Comment by FlipWarthog** [comment]
@baxsmaxbax Replied on your discussions post here: https://github.com/orgs/primefaces/discussions/187

**Comment by helderhernandez** [comment]
what worked for me (i'm using nuxtjs and primevue for nuxt)
 
```js
// install chart.js
 npm install chart.js
 
 // install plugin
 npm install chartjs-plugin-datalabels --save
```
 
 And in the template
```js
 <template>
        <div>
            <Chart
                type="doughnut"
                :data="chartData"
                :options="chartOptions"
                :plugins="[ChartDataLabels]"
                class="w-full" />
        </div>
</template>

<script setup lang="ts">
// imports
import Chart from 'primevue/chart';
import ChartDataLabels from 'chartjs-plugin-datalabels';

// consts
const chartData = ref();
const chartOptions = ref();

onMounted(() => {
    chartData.value = setChartData(); // my func with chart data
    chartOptions.value = setChartOptions(); // my function with chart opt
});

</script>
```
