### ISSUE TITLE
Multiselect: selected values are not shown without placeholder

### ISSUE THREAD

**Issue by sandanat** [primefaces/primevue#868]
Selected values for multiselect are not shown when `placeholder` prop is not specified

Primevue: v2.3.0
1. Open [example](https://codesandbox.io/s/primevue-multiselect-placeholder-uri00?file=/src/App.vue)
2. Select values for multiselect
3. Identify selected values are not shown
4. Specify placeholder
5. Selected values are shown

Selected values must be visible without placeholder specified

**Comment by cagataycivici** [comment]
It works on v3 so we'll check for v2.

**Comment by luckyluck** [comment]
I have the same issue with primevue 4.2.5.
