### ISSUE TITLE
Datatable custom global filter

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#873]
Hi guys,

I have a Datatable with a set of columns that has: `Name`, `Lastname1` and `Lastname2`. If I search by `name` + `lastname1` on global filter, Datatable can't filter my data.

For example:

| Name  | Lastname1 | Lastname2 |
| ------------- | ------------- | ------------- |
| Bob  | Smith  | Rose |
| Bob  | Grey  | Stone |

I can't filter by `Bob Smith`, If I type "Bob Smith" in global filter box, there is nothing displayed in Datatable.

(You can try search in https://www.primefaces.org/primevue/showcase/#/datatable by "lenna 2020", and nothing will be displayed).

Is there any method to implementing our custom global filter? I see that [Datatables.net](https://datatables.net/) is able to filter multiple columns in global filter, maybe we can program it in a custom global filter.

**Comment by abinadi** [comment]
I also could not find a way to do a custom global filter. This would be extremely helpful.

**Comment by cagataycivici** [comment]
Let us discuss this internally and get back to you.

**Comment by makurtu** [comment]
> Let us discuss this internally and get back to you.

An "ugly trick" is that, if you pass from backend a "full name field" containing all name data, and filtering that field, you can filter datatable as expected.

Example:

```json
{
    "name": "Bob",
    "lastname1": "Smith",
    "lastname2": "Rose",
    "full_name": "Bob Smith Ros"
}
````
Then, you can:

```js
<Column
      field="name"
      :sortable="true"
      filterField="full_name"
      header="Name"
    ></Column>
```

Now it filter datatable as expected if you type "Bob Smith".

**Comment by cagataycivici** [comment]
Please try the **globalFilterFields** property for this.
