### ISSUE TITLE
Calendar: prop showOtherMonths = false does not hide neighbour months` dates

### ISSUE THREAD

**Issue by sandanat** [primefaces/primevue#875]
Primevue v2.3

[Repo](https://codesandbox.io/s/primevue-calendar-showothermonths-6991c?file=/src/App.vue) - prop `showOtherMonths = false`  must hide neighbour months' dates, but it doesn't

**Comment by wujiang1900** [comment]
I'm using vue3. I see this bug in our app. :showOtherMonths="false" not working.

Could you fix it?
![Screen Shot 2021-09-02 at 6 08 29 PM](https://user-images.githubusercontent.com/11969043/131927295-08f6e187-3e57-4869-b435-7458cad16568.png)
