### ISSUE TITLE
Compile Problem with Directives( Typescript and 3.2.0-rc.1)

### ISSUE THREAD

**Issue by sfxcode** [primefaces/primevue#877]
Version: 3.2.0-rc.1

Tooltip and Ripple Directives

After Update following code does not compile anymore:

```
ERROR in src/main.ts:125:26
TS2693: 'Tooltip' only refers to a type, but is being used as a value here.
```

```
   125 | app.directive('tooltip', Tooltip);
  > 126 | app.directive('ripple', Ripple);
        |                         ^^^^^^
```

Works fine with: 3.1.2

Greetings,

Tom

**Comment by Zaaaoo** [comment]
Same here : 
![image](https://user-images.githubusercontent.com/70746510/105496990-8895ea80-5cbe-11eb-9432-c0e1d4d61d78.png)

**Comment by cameronrr** [comment]
Same! The issue is the same when adding directive into an SFC. Thank you.

**Comment by dhax** [comment]
did you find any workaround for this, as this directive is used in many components?
Issue still present in v3.2.0, also when enabling it only for PrimeVue components via ```app.use(PrimeVue, { ripple: true });``` with console error ```[Vue warn]: Failed to resolve directive: ripple ```

**Comment by sfxcode** [comment]
We have the problem with the bought diamond theme, which use ripple as well ....

**Comment by RobWalker** [comment]
As a workaround the following is 'working' for me:

```
// @ts-ignore
app.directive('tooltip', Tooltip);

// @ts-ignore
app.directive('ripple', Ripple);
```

**Comment by dhax** [comment]
additionally, for whom is using eslint with @typescript-eslint/ban-ts-ignore like in a standard vue-cli project, this seems to be the workaround ;)

// eslint-disable-next-line
// @ts-ignore
app.directive('tooltip', Tooltip);

**Comment by thomassittig** [comment]
hey there, this is still not working in the 3.2.2 version.

And i think ignoring the lint rules here can only be a temp. workaround :(

**Comment by fairking** [comment]
I have primevue 2.8.0 and I had the same issue.

So the actual fix is:
Instead of having `import Tooltip from 'primevue/tooltip/Tooltip';` you must change to `import Tooltip from 'primevue/tooltip';`

And the error gone away.

**Comment by projct1** [comment]
How to disable ripple globally? I dont need this, but got error in Tabs component `[Vue warn]: Failed to resolve directive: ripple`
But if i remove `TabList` error is gone.
