### ISSUE TITLE
FileUpload can't upload file after drag'&'drop

### ISSUE THREAD

**Issue by j-bitmaker** [primefaces/primevue#881]
Hi. When I try to upload pdf-file after attemption to drag'&'drop directly from zip archive - I get 0 size of uploaded file. But when I try do it, when I have already unzip file - it works OK. 

![image](https://user-images.githubusercontent.com/51827834/105692856-056bd300-5f10-11eb-91ac-f5c4f655e9c5.png)

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1, please try with the latest version available and create a new ticket if issue persists so that we can work on it again. Thank you.
