### ISSUE TITLE
Dialog component scrollbar shift

### ISSUE THREAD

**Issue by palagadec** [primefaces/primevue#882]
When opening a modal Dialog, the scrollbar is removed which results in a 15px shift on the body

## Expected Behavior
No shift when opening a modal

## Current Behavior
With modal property set to true (adds `p-overflow-hidden` class in body), the scrollbar is removed which creates a 15px shift. 

## Possible Solution
- Counterbalance by adding a 15px right padding to the body when adding p-overflow-hidden class.
- Keep the scrollbar

## Steps to Reproduce
1. Use the Dialog component with `:modal="true"`
2. Open the modal
3. Notice the shift

## Description
I'm suggesting to change the modal behaviour so that the shift induced by the scrollbar removal is no longer visible.

## Possible Implementation
In `Dialog.vue`, when adding the `'p-overflow-hidden'` class to `document.body`, also add a `'p-pr-15'` class (`padding-right: 15px;`) and remove it when removing the overflow class

**Comment by mertsincan** [comment]
Hi,

This is entirely dependent on the user's layout. Adding padding* CSS can break the app of users Or the same behavior continues if any element such as topbar or footer has position: fixed. Therefore, Users can override p-overflow-hidden class according to their needs. We may use overflow: overlay instead of overflow: auto for such problems in the future. Not all browsers currently support this. https://caniuse.com/css-overflow-overlay

Best Regards,

**Comment by vasiliyaltunin** [comment]
You can just override with:

```
.p-overflow-hidden {
  overflow: auto;
}

```

It still allow to user to scroll page, but no more shift and in modal mode i did not see how it can harm, because user can't click through overlay!

**Comment by areindl** [comment]
Hey all!

I found a nicer solution:

html,body {
    scrollbar-gutter: stable both-edges !important;
}

With the scrollbar-gutter, the scrollbar is still locked and the layout shift is not there anymore!

**Comment by cagataycivici** [comment]
Reopening due to community feedback. In 3.35.0 *:blockScroll="false"* helps as well but a nicer solution is preferred.

**Comment by mertsincan** [comment]
Affected components:

- [ ] Dialog
- [ ] BlockUI
- [ ] Calendar
- [ ] Galleria
- [ ] Image
- [ ] Sidebar

**Comment by timyourivh** [comment]
I have a layout that does not make use of body overflow and causes my page to shift like the issue describes.
I fixed this by adding this to my CSS:

```css
body.p-overflow-hidden {
    --scrollbar-width: 0px !important;
}
```

This will prevent the padding from being applied to the body as no scrollbar will ever appear in our body due to our layout.

**Comment by tommie** [comment]
For anyone screwing this up like I just did, and seeing shifts in 3.37.0: make sure you don't set `scrollbar-gutter: stable` on `<html>`. Only `<body>`. I had the

```css
html, body {
  margin: 0;
}
```

rule and simply added `scrollbar-gutter` there. Bad idea. :)

```css
body {
  margin: 0;
  scrollbar-guttern: stable;
}
```

works. (Perhaps resetting margins on `<html>` is a relic that isn't necessary today. Seems fine in Chrome.)

**Comment by askomarov** [comment]
why its closed? the problem is still there

**Comment by gabrielgomeso** [comment]
I've used

`.p-overflow-hidden { overflow: auto; overflow-x: hidden; } 
`
since with only overflow: auto I was getting a horizontal scroll.

**Comment by noise-kngdm** [comment]
Still broken for me.

**Comment by samsam8882** [comment]
should I add follows? it doesn't work:

<style scoped>
.p-overflow-hidden { overflow: auto; overflow-x: hidden; } 
</style>

**Comment by ekstremedia** [comment]
> should I add follows? it doesn't work:
> 
> `<style scoped> .p-overflow-hidden { overflow: auto; overflow-x: hidden; } </style>`

@samsam8882 It wont work in scoped, you have to apply it globally, and you might also have to do important on it, i had to.

`body.p-overflow-hidden {
  overflow: auto !important;
}`

**Comment by tommie** [comment]
> It wont work in scoped, you have to apply it globally

https://vuejs.org/api/sfc-css-features.html#deep-selectors
