### ISSUE TITLE
Please add placeholder to the InputText component

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [primefaces/primevue#89]
It will be nice to have a placeholder for the `InputText` component. It brings some example or explanation for users.
For example:
```
<InputText  v-model="item.name" placeholder="eg. 'My sample project'" />
```
Thank you 👍

**Comment by cagataycivici** [comment]
It is already possible, all properties are passed to the underlying input element, I've just tried it and confirm that it works.

**Comment by denis-pujdak-adm-it** [comment]
Apologies. Tried out know and it is working. Probably something went wrong with my previous test.
Thanks.
