### ISSUE TITLE
Input number in p-inputgroup has border-radius

### ISSUE THREAD

**Issue by vaiil** [primefaces/primevue#890]
![localhost_8081_](https://user-images.githubusercontent.com/3755615/105993831-e019c900-60b7-11eb-9176-960301a2e70a.png)
Code:
```vue
<div class="p-inputgroup">
  <PrimeVueInputNumber mode="decimal" />
  <PrimeVueButton icon="pi pi-save" />
</div>
```

It happens because `input number` creates new html element  (with classes `p-inputnumber p-component`) wrapping input. So the input is the last child in the wrapper and style for selector `.p-inputgroup input:last-child` is appling.

**Comment by tugcekucukoglu** [comment]
This issue is not clear. It seems to be an issue on your side. Please check this example

[https://codesandbox.io/s/nrt7f](https://codesandbox.io/s/nrt7f)
