### ISSUE TITLE
Autocomplete Templating in the input field

### ISSUE THREAD

**Issue by panwauu** [primefaces/primevue#911]
Hi,

In the documentation it is displayed how to use templating in the suggestion panel.
Is it possible to use a template in a similar way in the AutoComplete Input field?
If not this would be a nice feature to add.

Thank you all and best regards,
Oskar

**Comment by cagataycivici** [comment]
Templating is supporting in multiple mode in the input field, not available in single mode as single mode uses a plain input text right now.
