### ISSUE TITLE
DataTable sort not working with boolean shorthand

### ISSUE THREAD

**Issue by chrisnoden** [primefaces/primevue#912]
A DataTable that previously displayed sort options is no longer showing them. I am on Vue 3.0.5 and have tried PrimeVue 3.1.1 and 3.2.0-rc.1

Previously using the accepted property of just `sortable` worked, but a recent changed has broken this.

eg
`<Column field="timestamp" header="DateTime" sortable="true">` <- works

`<Column field="timestamp" header="DateTime" sortable>` <- no longer works, even though this is valid (and recommended) vue syntax

Refs: https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primevue/commit/a08b66db5adc9594e9669bf719569ec1abaa83a3
