### ISSUE TITLE
v3.2.0-rc.1 webpack babel errors with optional chaining operator

### ISSUE THREAD

**Issue by chrisnoden** [primefaces/primevue#913]
3.2.0-rc.1 breaks previously hard-earned webpack config - the use of the optional chaining operator can cause problems with babel. Perhaps you should document how to get this into our webpack (and, ideally, Encore) configs? Took me a day to figure out how to resolve your previous usage and you've changed it again in 3.2.0-rc.1 

```
error  in ./node_modules/primevue/datatable/datatable.esm.js

Module parse failed: Unexpected token (180:57)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         shouldRenderCol(column) {
|             if (this.rowGroupMode && this.rowGroupMode === 'subheader') {
>                 return this.groupRowsBy !== column.props?.field;
|             }
| 
```

It is the change of filename to `.esm.js` that breaks webpack config.

In my webpack.config.js (for Encore) I had to modify the babel loader:

```
    .addLoader({
        test: /\.js$/,
        loader: 'babel-loader',
        options: {
            plugins: [require("@babel/plugin-proposal-optional-chaining")]
        },
        exclude: file => (
            /node_modules/.test(file) &&
                !/\.vue.js/.test(file) &&
                !/\.esm.js/.test(file)
        )
    })
```

**Comment by LaurenceHo** [comment]
I ran into the same problem... Try to add above config into vue cli but it doesn't work. :(

**Comment by redsuperbat** [comment]
Ran into the same problem
