### ISSUE TITLE
Tooltip focus fails with some input components

### ISSUE THREAD

**Issue by mathewlk** [primefaces/primevue#915]
**Version**: 3.1.1

**Issue**: Using `v-tooltip.focus` doesn't seem to work with `InputNumber`'s. It works fine with `InputText` and with `InputNumber` without the focus, but when focus is added nothing shows up.

**Steps to Reproduce**: Add an element with `v-tooltip.focus` like this on the page:
```
<InputNumber
          id="purchasePrice"
          v-model="purchasePrice"
          prefix="$"
          v-tooltip.bottom.focus="'What you actually plan to pay for property, not necessarily the list price'"
        />
```

Nothing shows up when the number box is clicked.

**Expected Results**: Tooltip shows up similar to `InputText`

If this is expected, something should at least be added to the documentation. Although I think it'd be better to treat this like a bug as I'd imagine wanting to add help text to `InputNumber` would be a pretty common use case.

Thanks!

**Comment by cagataycivici** [comment]
Also applies to AutoComplete, InputMask ...
