### ISSUE TITLE
Middle node of CascadeSelect can't select

### ISSUE THREAD

**Issue by west-farmer** [primefaces/primevue#916]
None leaf node of nested hierarchy data are valid value  in some model, like departents.

**Comment by cagataycivici** [comment]
Not sure if I get it, do you experience at live demo as well?

https://primefaces.org/primevue/showcase/#/cascadeselect

**Comment by west-farmer** [comment]
Sorry for my poor english, I means only the last layer item can selected now.
![image](https://user-images.githubusercontent.com/55118339/106624244-66e70e00-65b0-11eb-920a-91b56c773a3b.png)
Sample,  I want to select "Australia" or "Queensland" .

**Comment by west-farmer** [comment]
Got it by using 'group-change' event

**Comment by cagataycivici** [comment]
Groups are not selectable items so this is expected, group-change can be used instead.

**Comment by agm1984** [comment]
I also want to mention that if your submenu item's don't load when you click the parent, you need to make sure the objects in your options array are proxies. It is a known issue that the PrimeVue submenu related components can fail if the item isn't a proxy.

For example, this fails:

``` vue
const cascadeOptions = computed(() => ([
    {
        name: 'Something',
        children: [
            {
                name: 'Sub-item',
            },
        ],
    },
]));
```

But this works:

``` vue
const cascadeOptions = computed(() => ([
    reactive({
        name: 'Something',
        children: [
            {
                name: 'Sub-item',
            },
        ],
    }),
]));
```

Mine is working so far with that, but it could be possible you need this:

``` vue
const cascadeOptions = computed(() => ([
    reactive({
        name: 'Something',
        children: [
            reactive({
                name: 'Sub-item',
            }),
        ],
    }),
]));
```

Note the addition of `reactive` to each object. This is what you need if you click the option and the sub-item options don't load.
