### ISSUE TITLE
AccordionTab has old values instead current

### ISSUE THREAD

**Issue by pedrodelgado81** [primefaces/primevue#92]
Hi.
I have a Datatable and an Accordion with two expanded AccordionTabs (these AccordionTabs must be always expanded). When I select a row into my Datatable, the Accordion must load values of that row.

When I click into a row of my Datatable, the Accordion reloads values but AccordionTabs still have the previous value, not actual.
Example

```
ValueDatatable------ValueIntoAccordion-------ValueInto AccordionTabs
          1                  1                      null
          2                  2                      1
          3                  3                      2
```

This happends only when accordionTabs are expanded. When are collapsed and expand the value it's correct. It seems that AccordionTabs refresh before the Accordion has the new value.

Thanks

**Comment by cagataycivici** [comment]
Please provide a code sample to help us replicate, a stackblitz template will help.

**Comment by casti11** [comment]
A code sample could be this:
```
<template>
  <div>
      <DataTable :value="elements" :selection.sync="selected" selectionMode="single">
        <Column header="Id" field="id"> </Column>
        <Column header="Description" field="description"> </Column>
      </DataTable>
      
      <Accordion>
        <AccordionTab :header="selected" :active="true">
          <span>{{ selected }}</span>
        </AccordionTab>
      </Accordion>
  </div>
</template>

<script>
export default {
  data() {
    return {
      elements: [
        { id: "1", description: "Hello world" },
        { id: "2", description: "Hola mundo" },
        { id: "3", description: "Bonjour le monde" }
      ],
      selected: null
    };
  }
};
</script>
```
And the behaviour I'm getting is the following:

1. After I click a row for the first time:
![image](https://user-images.githubusercontent.com/37068618/70507126-05eab400-1b2c-11ea-8399-995a5ad16d16.png)

2. When I select  another row:
![image](https://user-images.githubusercontent.com/37068618/70507169-1bf87480-1b2c-11ea-9458-e303c6bcf690.png)

And it goes like that all the time, having the value of the variable updated in the header of the AccordionTab, but the previous one in its content. If I open/close the tab, the value updates, but when I change the selected value, it gets one step behind again.

**Comment by cagataycivici** [comment]
I've solved this explicitly setting a default template for the content of the tab;

```
 <Accordion>
            <AccordionTab  :header="selected" :active="true" v:slot="default">
                <template #default>
                     <span>{{ selected }}</span>
                </template>
            </AccordionTab>
      </Accordion>
```

No idea, why it works though, could be a vue core issue.
