### ISSUE TITLE
ScrollPanel isn't revealing all of the content when scrolling

### ISSUE THREAD

**Issue by nrayburn-tech** [primefaces/primevue#922]
I am experimenting with vue/vite/primevue and am having an issue with the `ScrollPanel` not scrolling to reveal all of the content.

Primevue version is `^3.2.0-rc.1`

Video of the issue.  As you can see, the last line of the content isn't visible.  After deleting the `Toolbar`, the entire list can be scrolled into view.
![recording](https://user-images.githubusercontent.com/52075362/106419976-518eaa00-641f-11eb-990a-ba561b1d5ef5.gif)

Reproduction
1. Clone this repo, https://github.com/nrayburn-tech/vue-app
2. `npm install` && `npm run dev`
3. Open the webpage in your browser and shrink the window, so that scrollbars appear.
4. Try to scroll down either list and notice you cannot view all the content.
5. Remove the `Toolbar` component or move it below the two list items and the scrolling works fine.

**Comment by mertsincan** [comment]
This issue is not related to PrimeVue. Please try;
```
                 <Toolbar>
			<template #left> Left </template>
			<template #right> Right </template>
		</Toolbar>
		<div class="p-d-flex" style="height: calc(100% - 52px)">  // 100% - topbarHeight
			<div style="flex-basis: 15%" class="p-p-5">
				<chat-list />
			</div>
			<div style="flex: auto">
				<message-list />
			</div>
		</div>
```

Best Regards,
