### ISSUE TITLE
add data dynamically to rows of treetable

### ISSUE THREAD

**Issue by v01061374** [primefaces/primevue#93]
Hi
I want to implement sth like the table below (containing specific controls and links in some rows). how can i do this with your treetable. the place of control buttons are not important. The only thing that matters is how i can iterate through data of each row to toggle modals by them (not simple hrefs but vue buttons)

![69626474-f95f5980-105d-11ea-87fd-4e01ae2585e8](https://user-images.githubusercontent.com/18301748/69626720-6d99fd00-105e-11ea-8c60-339fdf17c17c.png)

**Comment by v01061374** [comment]
If only i can find a way to insert html as data, the problem is solved

**Comment by denis-pujdak-adm-it** [comment]
You can use templates. Just apply a template to the "Direct Costs" table mate:
```
<Column field="brand" header="Brand">
        <template #body="slotProps">
            <img :src="'demo/images/car/' + slotProps.data.brand + '.png'" :alt="slotProps.data.brand"  width="48px"/>
        </template>
</Column>
```

See examples here: https://www.primefaces.org/primevue/#/datatable/templating

**Comment by v01061374** [comment]
Hi again @denis-pujdak-adm-it . Thank you for your reply.
I'm afraid it doesn't work for me, though it should.
I just copied the code from the docs, but when i want to use slotProps it is undefined and the error below shows up:
TypeError: Cannot read property 'type' of undefined"

**Comment by v01061374** [comment]
@denis-pujdak-adm-it 
I tried using  `slotProps.node.data.type` instead of  `slotProps.data.type` and it worked for me. (despite the fact that your suggestion is exactly right according to the docs!!)
btw thank you so much

**Comment by denis-pujdak-adm-it** [comment]
I am glad you managed to find a solution. Best wishes with your project.

**Comment by v01061374** [comment]
@denis-pujdak-adm-it tnx a lot
