### ISSUE TITLE
Improve knob interaction

### ISSUE THREAD

**Issue by luxaritas** [primefaces/primevue#930]
Right now, using the knob component feels quite buggy - basically however I drag it makes it "glitch" significantly. It should be able to behave in one of the following ways:
- Dragging around the outside of the knob should cause it to follow the mouse radially
- Dragging up or right increases the knob position, dragging down or left decreases the knob position

**Comment by cagataycivici** [comment]
Currently it is available on other Prime libs with no major complaints so decided to keep it as it is. When there is more demand on this, we'll reconsider it. Thank you for your feedback.
