### ISSUE TITLE
Customizing the line of Timeline component

### ISSUE THREAD

**Issue by wanglin86769** [primefaces/primevue#931]
I am developing a web application involving approval process using PrimeVUE 2.3.0, and the new Timeline component is very helpful. 
Currently, the marker is customizable, but the line is not.
Hope the color and width of each line (before or after a marker) can also be customizable in future version. Thanks.

**Comment by Aterr** [comment]
Same here. Would be nice if we could customize the line also.

**Comment by cagataycivici** [comment]
Added to the roadmap, thank you. Sounds good for sure.
