### ISSUE TITLE
password-meter.png missing in resources/images in v3.2.0

### ISSUE THREAD

**Issue by dhax** [primefaces/primevue#935]
This relative module was not found:

* ./images/password-meter.png in ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/primevue/resources/primevue.min.css

**Comment by cybay** [comment]
node_modules/primevue/resources/images$ cp hue.png password-meter.png
dirty fix just to make it build.

**Comment by cagataycivici** [comment]
We'll do a 3.2.1 right away.

**Comment by cagataycivici** [comment]
3.2.1 is released, thank you;

https://www.npmjs.com/package/primevue/v/3.2.1
