### ISSUE TITLE
Calendar component throws error on blur if popup is not visible

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#940]
Calendar component throws error `DomHandler.js:187 Uncaught TypeError: Cannot read property 'querySelectorAll' of null"` on blur (tab out) if the popup panel is not visible.

To recreate, set :showOnFocus="false" or press Esc to close the popup once the edit has been entered, then press tab.

Vue: 3.0.5
PrimeVue 3.1.2

**Comment by cagataycivici** [comment]
3.2.2 is now available on NPM.

https://github.com/primefaces/primevue/blob/master/CHANGELOG.md#322-2021-02-04
