### ISSUE TITLE
Dropdown component does not fire focus or blur events

### ISSUE THREAD

**Issue by avenmore** [primefaces/primevue#944]
To recreate, add `@blur` and `@focus` event handlers to a Dropdown component. These are not called when tabbing through the component.

Expect that these events should work the same as they do on InputText, Password, Calendar, etc.

Vue: 3.0.5
PrimeVue: 3.2.2

**Comment by avenmore** [comment]
Still not fixed 3 months later, and should be as simple as adding `<input v-bind="$attrs"` in Dropdown.vue.

**Comment by cagataycivici** [comment]
Add high priority to be worked on this week's release.
