### ISSUE TITLE
Feature Request: Popover Component

### ISSUE THREAD

**Issue by JoseGoncalves** [primefaces/primevue#945]
Please consider adding a Popover component to PrimeVue with a similar functionality as this one:

https://bootstrap-vue.org/docs/components/popover

**Comment by dheimoz** [comment]
Hello @JoseGoncalves  I wonder if tooltip satisfies your needs.
https://primefaces.org/primevue/showcase/#/tooltip

**Comment by JoseGoncalves** [comment]
Hi @dheimoz. No, tooltip is not enough for my use case. With the current tooltip component you can only add text. I would like to generate a tooltip with a more "rich" content (i.e., with icons, images, text with different styles/sizes, etc...). This content could be added via a template.

**Comment by dheimoz** [comment]
Makes sense. Thanks for the clarification.
