### ISSUE TITLE
Vue3 PrimeVue and ToastService "is not assignable"

### ISSUE THREAD

**Issue by cope** [primefaces/primevue#946]
I'm quite confused by these two errors:
![image](https://user-images.githubusercontent.com/112515/106929983-53a18300-6715-11eb-9525-cb28bd75b79b.png)
![image](https://user-images.githubusercontent.com/112515/106930010-5ac89100-6715-11eb-8036-c3ae35402cd8.png)

Toast and Dialog seem to be fine:
![image](https://user-images.githubusercontent.com/112515/106930284-aa0ec180-6715-11eb-823e-f99fcff54ada.png)
![image](https://user-images.githubusercontent.com/112515/106930323-b2ff9300-6715-11eb-8cd6-32266fb408a1.png)

I'm using
		"mitt": "^2.1.0",
		"primeicons": "^4.1.0",
		"primevue": "^3.2.2",
		"vue": "^3.0.5",

I'm not sure if the above causes Toast not to work, but this is how I tried and no luck:
![image](https://user-images.githubusercontent.com/112515/106930860-505ac700-6716-11eb-9367-f6c97e854ca5.png)

**Comment by cope** [comment]
Interestingly, Dialog works:
![image](https://user-images.githubusercontent.com/112515/106935517-bd249000-671b-11eb-949c-8df37713e871.png)

**Comment by cope** [comment]
OK, IMHO the documentation really should specify that adding `<Toast />` into the template is required :(

**Comment by Eireternal** [comment]
> OK, IMHO the documentation really should specify that adding `<Toast />` into the template is required :(

OMG, I spent hours trying to figure out why I followed the documentation perfectly and nothing would show up. Please someone add this to documentation.

**Comment by dheimoz** [comment]
Hello @Eireternal , remember that PR's are always welcome. Cheers.
