### ISSUE TITLE
DataTable pagination stops working after filter has been applied

### ISSUE THREAD

**Issue by BrianJoyce** [primefaces/primevue#947]
Pagination stops working if a global or column filter is applied to a table or column on a DataTable.
On initial load it works fine, then if you apply the filter and try to go to a second or third page on the table the data doesn't change, however pagination numbers do.  If you remove whatever you were filtering by and try to go to another page it still doesn't work.
However if you don't apply a filter, pagination is fine.
The bug exists on https://www.primefaces.org/primevue/showcase/#/datatable too.
This bug relates to VUE 3 and Primevue 3.2.2
Problem isn't there in Primevue 2.x

**Comment by emersoncpaz** [comment]
Having the same problem on Primevue 3.2.1.

**Comment by gopz19** [comment]
Facing the same problem. any idea when this will be resolved.

**Comment by emersoncpaz** [comment]
The problem continues in Primevue 3.2.4

**Comment by gopz19** [comment]
This is a blocker for us. Please someone fix asap or atleast confirm if 'Work in progress'. Else i may have to move to some other third party.

**Comment by dheimoz** [comment]
Hello @gopz19, please remember that this is an open source project. The team at PrimeTek had their own schedule and assist the community at their best capability. Should you need to move to other party I recommend you Vuetify or Quasar. 

And remember, PR are always welcome. That is the best way to speed things up.

Cheers

**Comment by cagataycivici** [comment]
Fixed for https://github.com/primefaces/primevue/issues/977.

Coming up tomorrow with the all new mighty filtering.

**Comment by fcofabricio** [comment]
The problem continues in Primevue 2.4.1
