### ISSUE TITLE
Router support for PanelMenu headers

### ISSUE THREAD

**Issue by scottix** [primefaces/primevue#949]
# Summary
PanelMenu is not using router-link and only providing the url option. Which is odd because it seems PanelMenuSub is using router-link.

# Code
```vue
<template>
  <PanelMenu :model="menuItems" />
</template>
<script>
import PanelMenu from 'primevue/panelmenu'
export default {
  data() {
    return {
         menuItems: {
          label: 'Activity',
          icon: 'pi pi-book',
          to: '/activity'
        },
    }
  }
}
</script>
```

# Version
3.2.2

# Actual Result
Nothing

# Expected Result
Provide a router link

**Comment by cagataycivici** [comment]
Where exactly do you need router-link?

**Comment by scottix** [comment]
> Where exactly do you need router-link?

At the top level there is an anchor tag that is not using router-link

https://github.com/primefaces/primevue/blob/3.2.4/src/components/panelmenu/PanelMenu.vue#L6

It should be the same as PanelMenuSub

https://github.com/primefaces/primevue/blob/3.2.4/src/components/panelmenu/PanelMenuSub.vue#L5
