### ISSUE TITLE
An error occurred in the type prompt under TS

### ISSUE THREAD

**Issue by WumaCoder** [primefaces/primevue#952]
## Environment
"dependencies": {
    "primeicons": "^4.1.0",
    "primevue": "^3.2.1",
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@types/node": "^14.14.25",
    "@vitejs/plugin-vue": "^1.1.4",
    "@vue/compiler-sfc": "^3.0.5",
    "@vuedx/typecheck": "^0.6.0",
    "@vuedx/typescript-plugin-vue": "^0.6.0",
    "typescript": "^4.1.3",
    "vite": "^2.0.0-beta.65"
  }

## Question
![image](https://user-images.githubusercontent.com/39021696/107224734-c7fc5f00-6a52-11eb-8594-d7a9c4452c48.png)
Vue not constructor

![image](https://user-images.githubusercontent.com/39021696/107224816-e95d4b00-6a52-11eb-82fb-871bc95da00d.png)
*.d.ts file define error

## Solution
![image](https://user-images.githubusercontent.com/39021696/107224965-245f7e80-6a53-11eb-8712-8ffa36f5e5c5.png)
![image](https://user-images.githubusercontent.com/39021696/107224983-2a555f80-6a53-11eb-851d-1a7e09a4f733.png)

**Comment by mertsincan** [comment]
Hi @WumaCoder,

Is this definition OK for you?
```
interface ButtonProps {
    label?: string;
    icon?: string;
    iconPos?: string;
    badge?: string;
    badgeClass?: string;
}

declare class Button {
    $props: ButtonProps
}

export default Button;
```

**Comment by WumaCoder** [comment]
> Hi @WumaCoder,
> 
> Is this definition OK for you?
> 
> ```
> interface ButtonProps {
>     label?: string;
>     icon?: string;
>     iconPos?: string;
>     badge?: string;
>     badgeClass?: string;
> }
> 
> declare class Button {
>     $props: ButtonProps
> }
> 
> export default Button;
> ```

very good 😀

**Comment by WumaCoder** [comment]
Hope to update as soon as possible

**Comment by mertsincan** [comment]
Yes, I'll update all components.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/issues/957
