### ISSUE TITLE
Improve Typescript support

### ISSUE THREAD

**Issue by tom10271** [primefaces/primevue#953]
https://github.com/primefaces/primevue/blob/master/src/components/tabmenu/TabMenu.d.ts

It is not utiltizing TS properly, this is just one of the file.

**Comment by mertsincan** [comment]
Fixed in #957

**Comment by tom10271** [comment]
The point is `any[]` or `any` are not good types.

https://github.com/primefaces/primevue/commit/fa82ecc38fe6a79c9e8720c402b29889f4717259#diff-235de3e499768eb41677a5073ea785c631ca4978866935a2951631015432f7afR2

This is expected which can help developer to write code without checking the doc

```ts
type MenuItem = {
    label?: string;
    icon?: string;
    to?: string;
    command?: void;
    url?: string;
    items?: MenuItem[];
    disabled?: boolean;
    visible?: boolean | (() => boolean);
    target?: string;
    separator?: boolean;
    style?: any;
    class?: string;
};
```

**Comment by mertsincan** [comment]
Hi @tom10271,

Thanks a lot for the update! Could you please create PR for this issue? Thanks a lot.

Best Regards,
