### ISSUE TITLE
Chart.js gives Chart is not a contructor

### ISSUE THREAD

**Issue by basvdijk** [primefaces/primevue#955]
When using the chart as documented on https://primefaces.org/primevue/showcase/#/chart 

It gives `Uncaught (in promise) TypeError: Chart is not a constructor`

![image](https://user-images.githubusercontent.com/644550/107366444-76011b00-6ade-11eb-9fe3-e3dee29392d6.png)

**Comment by cagataycivici** [comment]
Have you installed chart.js from npm?

**Comment by basvdijk** [comment]
@cagataycivici yes:
```
 "dependencies": {
    "@vee-validate/rules": "^4.0.6",
    "axios": "^0.21.1",
    "chart.js": "^2.9.4",
    "jwt-decode": "^3.1.2",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primevue": "^3.2.4",
    "vee-validate": "^4.1.16",
    "vue": "^3.0.5",
    "vue-axios": "^3.2.4",
    "vue-i18n": "^9.0.0-rc.5",
    "vue-router": "^4.0.3",
    "vuex": "^4.0.0"
  },
```

**Comment by martinfruehmorgen** [comment]
Hello,

I have the same issue.
Also the codepen
https://codesandbox.io/s/80oiz
from
https://primefaces.org/primevue/showcase/#/chart/bar

does not work...

Thanks!
Martin

**Comment by bkoplin** [comment]
Same issue here.

**Comment by basvdijk** [comment]
@cagataycivici any updates on this one?

**Comment by AVapps** [comment]
Same here also.

**Comment by AVapps** [comment]
Got it working with vite 2 by replacing : 
`import Chart from 'primevue/chart'`
with :
`import Chart from 'primevue/chart/Chart.vue'`

**Comment by cagataycivici** [comment]
@mertsincan Could it be related to a similar issue in PrimeNG? The way we import chartjs?

**Comment by TuguldurJ** [comment]
Same issue is here

**Comment by mertsincan** [comment]
I think this issue is related to server-side rendering. Maybe, we can import chart.js when Chart component is mounted to the page.

**Comment by AVapps** [comment]
I confirm that I don't use SSR and I have this issue.

**Comment by TuguldurJ** [comment]
I can also confirm that this is not an SSR issue. I think this should be resolved because Chart.js is a crucial component for PrimeVue.
