### ISSUE TITLE
Add vetur component data to improve developer experience

### ISSUE THREAD

**Issue by rwparris2** [primefaces/primevue#962]
Vetur is the defacto extension for working with vue in VSCode.

It has a feature that allows framework authors to supply metadata to support code completion. This makes for a much nicer development experience. It allows me to be much more productive because I won't have to keep referring to the documentation for simple things like "what was that param named again?".

https://vuejs.github.io/vetur/guide/component-data.html#other-frameworks

Some examples of other libraries with vetur support:

- https://github.com/vuejs/vue-router/tree/dev/vetur
- https://github.com/element-plus/element-plus/tree/dev/vetur

**Comment by cagataycivici** [comment]
Sounds good, we'll get to it. Thanks.
