### ISSUE TITLE
ScrollTop props have wrong type definitions

### ISSUE THREAD

**Issue by ananni13** [primefaces/primevue#963]
https://github.com/primefaces/primevue/blob/1c814647603de59d4f0015d7e7a914749ae65abc/src/components/scrolltop/ScrollTop.d.ts#L1-L12

`icon` and `behavior` should be of type `string`. ([Docs](https://primefaces.org/primevue/showcase/#/scrolltop))

Also, shouldn't the class be named **`ScrollTop`** instead of **`ScrollTo`**?

**Comment by cagataycivici** [comment]
Got it thanks.
