### ISSUE TITLE
Charts extra event

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#969]
Hi guys it would be nice to have an event when user clicks on the empty area of the chart. Not just the selected bar/line.

Thanks.

**Comment by cagataycivici** [comment]
Sounds good to me.

**Comment by fairking** [comment]
Thanks @cagataycivici . The reason it might needed is to catch the area click to be able to fire the dialog box to add a new element to the chart (eg. timeline).

**Comment by cagataycivici** [comment]
I've checked this out for v3 and since vue 3 inherits the events by default @click already works without us touching anything. As PrimeVue 2 is in maintenance mode only, closing the ticket. Thank you.
