### ISSUE TITLE
Top row radio button focus issue

### ISSUE THREAD

**Issue by codeplotter** [primefaces/primevue#971]
No matter which radio button I select in a DataTable, the top radio button gets focus after the click (I am using script tag with umd file from jsdeliver with primevue 2.3):

<img width="279" alt="Screen Shot 2021-02-15 at 12 39 25 AM" src="https://user-images.githubusercontent.com/25725009/107913700-7bb79000-6f26-11eb-81ae-99123832cd95.png">

**Comment by cagataycivici** [comment]
This should fixed in 2.4.0.
