### ISSUE TITLE
Cannot find module 'primevue/config' 

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primevue#975]
Hi, i have  an error in vuejs 2:
`Cannot find module 'primevue/config' `
my webpack:
`  configureWebpack: {
    resolve: {
      extensions: [".js", ".vue"],
    }},`

my package.json:
```
{
  "name": "",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "axios": "0.18.0",
    "blend4web": "18.5.0",
    "core-js": "^3.6.5",
    "element-ui": "^2.14.1",
    "file-saver": "^2.0.5",
    "font-awesome": "4.7.0",
    "jszip": "^3.5.0",
    "node-less": "^1.0.0",
    "node-sass": "^5.0.0",
    "pako": "^2.0.2",
    "primeicons": "^4.1.0",
    "primevue": "^2.0.0",
    "rxjs": "^6.6.3",
    "sass-loader": "^10.1.1",
    "save-as": "^0.1.8",
    "vue": "^2.6.12",
    "vue-router": "^3.2.0",
    "vue-rx": "^6.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@types/resize-observer-browser": "^0.1.5",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "less": "^3.0.4",
    "less-loader": "^5.0.0",
    "typescript": "~3.9.3",
    "uglifyjs-webpack-plugin": "^1.0.0-rc.0",
    "vue-template-compiler": "^2.6.11"
  }
}
```

**Comment by cagataycivici** [comment]
It seems like an issue with your setup, I'm not able to replicate. Which exact PrimeVue version you have?

**Comment by alexcroox** [comment]
I have the same issue, fresh install of prime-vue. v2.0.3 has a syntax error unexpected '<'.

So I downgraded to v2.0.0 and now I get `Cannot find module 'primevue/config'`

If I look inside node_modules/prime-vue there is no folder or file called `config` @cagataycivici

**Comment by RndRss** [comment]
You are using Primevue 2.0.0 this configuration was introduced in 2.3.0. Source: https://github.com/primefaces/primevue/issues/823#issue-777083628

So until version 2.2.3 is no need for this configuration

Change log
https://github.com/primefaces/primevue/blob/master/CHANGELOG.md

**Comment by alexcroox** [comment]
The syntax error was because I was trying to use it with SSR (Nuxt). I think I’ve discovered this library does not work with SSR and can only be rendered on the client side

**Comment by vadimt2** [comment]
PrimeVue 2.0.0

**Comment by cagataycivici** [comment]
2.0.0 doesn't have primevue/config.

**Comment by vadimt2** [comment]
https://www.primefaces.org/primevue/showcase-v2/#/setup
```
npm install primevue@^2.0.0 --save
npm install primeicons --save
```
then
```
import PrimeVue from 'primevue/config';

Vue.use(PrimeVue);
```

Path:
```
https://www.primefaces.org/primevue/showcase-v2/#/setup
```
Issue:
```
Failed to compile.

./src/main.js
Module not found: Error: Can't resolve 'primevue/config' in 'E:\MyOwnProjects\VueJS\VueJsPclub\VueJS1Pclub\src
```

**Comment by alexcroox** [comment]
Yeah the docs are out of date causing confusion

**Comment by rafaelguillermo** [comment]
Hi, i need help..

Errorrrrrr..

Line 5: ./src/main.js 5:0-39
import PrimeVue from 'primevue/config';

My project has created:::      vue init webpack directory
-------------------------------------
rblanco@Rafaels-MacBook-Pro payVueFirebaseFrom % npm run dev

> pay-vue-firebase-from@1.0.0 dev /Users/rblanco/Documents/applications/github/mePay/payVueFirebaseFrom
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 13% building modules 32/42 modules 10 active .../mePay/payVueFirebaseFrom/src/App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization                                                               

 ERROR  Failed to compile with 1 errors                                                                                                           7:37:43 AM

 error  in ./node_modules/primevue/config/config.esm.js

Module parse failed: Unexpected token (95:39)
You may need an appropriate loader to handle this file type.
| var PrimeVue = {
|     install: (app, options) => {
|         let configOptions = options ? {...defaultOptions, ...options} : {...defaultOptions};
|         const PrimeVue = {
|             config: reactive(configOptions)

 @ ./src/main.js 5:0-39
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

-------------------------------------
main.js
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

import PrimeVue from 'primevue/config';

import 'primevue/resources/themes/saga-blue/theme.css'       //theme
import 'primevue/resources/primevue.min.css'                 //core css
import 'primeicons/primeicons.css'                           //icons
import 'primeflex/primeflex.css';

import InputText from 'primevue/inputtext';
import Password from 'primevue/password';

const app = createApp(App);
app.use(PrimeVue);

app.component('InputText',InputText);
app.component('router',router);

app.mount('#app');
-------------------------------------

package.js

{
  "name": "pay-vue-firebase-from",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "rblanco <mangelan03@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "build": "node build/build.js"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "primeicons": "^4.1.0",
    "primevue": "^3.5.0",
    "primeflex": "^2.0.0",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

Please help

**Comment by tugcekucukoglu** [comment]
Please use PrimeVue 3 for Vue 3 and PrimeVue 2 for Vue 2.

**Comment by rafaelguillermo** [comment]
thank you..
