### ISSUE TITLE
Tooltip persists even after parent component has been hidden

### ISSUE THREAD

**Issue by tobeyOguney** [primefaces/primevue#983]
![image](https://user-images.githubusercontent.com/28822467/108221863-86e20a00-7138-11eb-9649-8553a966893e.png)
![image](https://user-images.githubusercontent.com/28822467/108222072-bd1f8980-7138-11eb-9ffd-4fbb0d21c430.png)

Is there a way around this issue?
I'm using the tooltip component as a Vue directive.

**Comment by cagataycivici** [comment]
I'm not sure, how do you hide your content? With css or with v-if?

**Comment by tobeyOguney** [comment]
I hide it with CSS (v-show)

**Comment by cagataycivici** [comment]
Can you remove the content with v-if instead? Otherwise we don't have a callback to destroy the tooltip.

**Comment by tobeyOguney** [comment]
I've done this as well. But, the issue still persists.

Have you been able to reproduce it so far? (Perhaps, there's something else I'm doing wrong)

**Comment by tugcekucukoglu** [comment]
Could you check [this example](https://codesandbox.io/s/wonderful-gareth-8jwzg)

**Comment by cagataycivici** [comment]
Unable to replicate with the latest PrimeVue 3.4.1. If the issue persists, please try with the latest version available and create a new ticket with our codesandbox template forkso that we can work on it again. Thank you.
