### ISSUE TITLE
OverlayPanel with input closes when typing on mobile

### ISSUE THREAD

**Issue by gbdematos** [primefaces/primevue#984]
Hi,

Steps to reproduce this bug: Create an OverlayPanel with an text or number input inside. Open the overlay on mobile and touch the input to start typing. As soon as the touch keyboard appears, the Overlay closes.

I tried setting dismissable to false, but it still happens.

Any way I could solve this?

Thanks

**Comment by cagataycivici** [comment]
We'll review, thank you.

**Comment by tugcekucukoglu** [comment]
Where did the issue occurs? Android or iOS?

**Comment by gbdematos** [comment]
> Where did the issue occurs? Android or iOS?

I only tested on Android.

**Comment by tugcekucukoglu** [comment]
Thanks, it's fixed for Android.
