### ISSUE TITLE
DataTable Column header slot does not work

### ISSUE THREAD

**Issue by ubau** [primefaces/primevue#987]
After upgrading to primevue 3.3.0-rc.1 got error in DataTable Column header slot

Uncaught (in promise) TypeError: can't access property "children", _ctx.col is undefined

```html
  <Column
    field="deptCode"
    style="width: 54px; text-align: center"
    :sortable="false"
  >
    <template #header>
      <span title="Department"> Dept. </span>
    </template>

    <template #body="slotProps">
      <span :title="`${slotProps.data.deptName}`">{{
        slotProps.data.deptCode
      }}</span>
    </template>
  </Column>
```

This worked with previous versions.

**Comment by ZakyAbanoub** [comment]
Neither the Datatable Column headerClass for sure

**Comment by medfrk** [comment]
the somme error for me  Uncaught (in promise) TypeError: can't access property "children", _ctx.col is undefined

**Comment by cagataycivici** [comment]
Both are fixed, thx!
