### ISSUE TITLE
datatable filtering not working 

### ISSUE THREAD

**Issue by BrianJoyce** [primefaces/primevue#988]
Filtering is not working properly.
https://www.primefaces.org/primevue/showcase/#/datatable/state and enter in a global search. It doesn't filter. Then when you delete the search nothing comes up, then you re-apply the filter everything comes up.

Perhaps related to commit https://github.com/primefaces/primevue/commit/7e2888012b673f1608bf6112f9f5d6b85bc1c532

**Comment by makurtu** [comment]
Take a look al demo code, this line:

```js
<InputText v-model="filters1['global']" placeholder="Global Search" />
```

must be:

```js
<InputText v-model="filters1['global'].value" placeholder="Global Search" />
````
Notice the `.value` after the filter definition.

**Comment by cagataycivici** [comment]
Demo is fixed, thank you. This was a regression of the new advanced filtering. The table state demo was not updated.
