### ISSUE TITLE
FileUpload callback 'Select' little adjust.

### ISSUE THREAD

**Issue by nigthwolfer** [primefaces/primevue#990]
Greetings. First of all I would like to thank you for this excellent work. Using FileUpload, I realized that the 'select' callback returns the empty files array. So, I added the reference 'this.' as follows and the callback worked as expected. 

https://github.com/primefaces/primevue/blob/19fe8b219baef59dc103ec2c022bae32ecd66b80/src/components/fileupload/FileUpload.vue#L160
Addition of the 'this' reference. 

`this.$emit('select', {originalEvent: event, files: this.files});`

Best regards.

**Comment by cagataycivici** [comment]
Got it, thank you so much!
