### ISSUE TITLE
Float label needs position correction on validation error.

### ISSUE THREAD

**Issue by KotkaZ** [primefaces/primevue#994]
The floating label needs position correction when using it with error classes. I think the picture describes it better.
![image](https://user-images.githubusercontent.com/56869558/108594275-b3d52d80-7381-11eb-90e9-54cd6756b88a.png)

**Comment by cagataycivici** [comment]
Can you please post your code, not able to replicate yet.

**Comment by Hassanbhb** [comment]
I knwo this old, but This happened to me the issue might be that you are using the <Message/> component inside the <FloatLabel/> component

```
<FloatLabel variant="on">
  <InputText />
  <label>Server</
  <Message v-if="$field.invalid" /> <!-- this breaks FloatLabel -->
</FloatLabel>
```

it should be like this

```
<FloatLabel variant="on">
  <InputText />
  <label>Server</label>
 </FloatLabel>
 <Message v-if="$field.invalid" />
```
