### ISSUE TITLE
Failed to resolve component: Calendar

### ISSUE THREAD

**Issue by medfrk** [primefaces/primevue#997]
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Failed to resolve component: Calendar 
  at <Customer onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <LayoutBasic onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

**Comment by Daveedz99** [comment]
![immagine](https://user-images.githubusercontent.com/75852758/108741011-8ed5eb80-7536-11eb-9da0-71c51f966690.png)

**Comment by cagataycivici** [comment]
I'm unable to replicate, if issues persists please create a new ticket and attach a code sandbox or a repo for us to review.
